### ISSUE TITLE
PI-hole cannot be installed

### ISSUE THREAD

**Issue by bdl555** [MichaIng/DietPi#100]
I get a githubusercontent.com.../master.zip could not be downloaded or is unreachable error

**Comment by blindpet** [comment]
This works, github had some issues the past week or so

```
curl -s "https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/automated%20install/basic-install.sh" | bash
```

**Comment by Fourdee** [comment]
Just tested. Working fine here: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L994

Most likely, your RPi was unable to resolve the url, or, connection drop.
On your RPi, try:
wget https://github.com/jacobsalmela/AdminLTE/archive/master.zip
If that works, run dietpi-software and retry the installation.

Ticket closed as unable to replicate. Re-open if required.
