### ISSUE TITLE
Mali kernel drivers for Orange Pi PC2

### ISSUE THREAD

**Issue by topilski** [MichaIng/DietPi#1003]
Hi, can you add mali drivers for GPU decoding for Orange Pi PC2. https://link.piboard.io/OPiPC2-Debian-Mali450-01-GD image according description contains needed ko modules.

**Comment by pidiet** [comment]
Awesome!

**Comment by daisreaux** [comment]
what about Orange Pi Zero Plus H5?

**Comment by Fourdee** [comment]
@vgoffman 

Our current focus for full GPU implementation and support, is only for the major popular devices:
- Odroid
- RPi

Therefore, this is a low priority request. We'd love to implement everything our users request, but we must manage our available time and limit features/support for non-common devices.
