### ISSUE TITLE
JRiver Mediacenter 22 Rpi3 DietPi v1.51 ->works..!!

### ISSUE THREAD

**Issue by sfb2** [MichaIng/DietPi#1005]
hi there, ;-)
read before here (but havent found it again ?) about JRiver Mediacenter on pi3..:

Installed it via this:
https://yabb.jriver.com/interact/index.php/topic,106027.0.html?PHPSESSID=tu9nj8hrnf77m3ef9ur3h6do27

had v1.51 here, did only this:
wget -q "http://dist.jriver.com/mediacenter@jriver.com.gpg.key" -O- | sudo apt-key add -
sudo wget http://dist.jriver.com/latest/mediacenter/mediacenter22native.list -O /etc/apt/sources.list.d/mediacenter22.list
sudo apt-get update
sudo apt-get install mediacenter22

it installed vorbis-tools + musepack-tools too..

Multimedia->Media Center 22->works !!

Interesting:
options->samplerate changes automatically to max dtoverlay "capacity"..:
have rpi-dac (unfortunately ;-() changes all above 192khz (352,384,704,768 and up) to (in my case) 192khz max..
GUI works fine so far, no issues, DLNA-rendering works out of the box..
"sounds" (in my opinion) not so good as pure "MPD" (in DietPi)..

btw.:please modify the rpi-dac overlay to min. 384khz/768khz !! ;-) 
(should be possible, but i have not enough "skills": 
http://stackissue.com/raspberrypi/linux/enable-352k8-and-384k-sample-rates-for-i2s-connected-boards-hats-that-support-those-rates-1460.html"

**Comment by Fourdee** [comment]
@sfb2 

Thanks for the info 👍  

I'll mark this as closed, please use: https://github.com/Fourdee/DietPi/issues/988
