### ISSUE TITLE
DietPi-Software | AlexaPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1006]
### Vote for it on FeatHub: https://feathub.com/MichaIng/DietPi/+57

> http://dietpi.com/phpbb/viewtopic.php?f=12&t=1960#p7474
https://github.com/alexa-pi/AlexaPi/wiki/Installation

**Comment by Fourdee** [comment]
Install script
- requires user input?
- Automate? (would need a fork for stability, re: pihole): 

https://github.com/alexa-pi/AlexaPi/blob/master/src/scripts/setup.sh

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by MichaIng** [comment]
Added to FeatHub: https://feathub.com/MichaIng/DietPi/+57
