### ISSUE TITLE
v150 to v151

### ISSUE THREAD

**Issue by newdietpi** [MichaIng/DietPi#1009]
Does a new update purposely prevent old versions from working?

I have an opi one that was working ok on v150, for some reason I wasn't able to connect to it remotely by it's local IP address the last 2 days. I had to physically connect it to a monitor in order to update it so I could get pi-hole working and connect to it via local ip address again.

**Comment by Fourdee** [comment]
@newdietpi 

> Does a new update purposely prevent old versions from working?

Nope. Only when you run ```dietpi-update``` will any changes be made.

> I have an opi one that was working ok on v150, for some reason I wasn't able to connect to it remotely by it's local IP address the last 2 days. 

Could be an issue with SSH server failing, or local network issue. Check services with:
```
systemctl status dropbear -l
systemctl status sshd -l
```
