### ISSUE TITLE
DietPi-Software | NZBget

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1013]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=1907&p=7514#p7292
https://github.com/nzbget/nzbget

**Comment by Invictaz** [comment]
Would be great

**Comment by ghost** [comment]
Really looking forward for this integrated in DietPi!

**Comment by Fourdee** [comment]
- 🈯️ online doc : http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=7575#p7575

**Comment by Fourdee** [comment]
Completed. 
NZBget really is fast, even in the web interface it feels much more responsive, compared to our typical python based "stuff" :)
