### ISSUE TITLE
[dietpi-software][APT] Deprecated apt commands/options

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1018]
Referring to the first named issue here: https://github.com/Fourdee/DietPi/issues/475#issuecomment-305838743

While running dietpi-software to install packages, some error message shows up regularly saying, that "`--force-yes`" as apt-get option is deprecated and there should be some options "`--allow...`" used instead.

I failed to find some official list of apt-get options, maybe there are some man pages providing them? apt -h just shows the basic commands.

However, I found the following debian bug report, handling the same topic already in 2015: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806948

Therefore `--allow-downgrades`, `--allow-remove-essential` and `--allow-change-held-packages` would provide the same result. Looks like it could be differentiated more here, being less dangerous than just force yes for every kind of prompt.

I see that topic made already it's way as a comment inside dietpi-software code:
>2799 		# if (( $DISTRO == 4 )): then
>2800 			# force_options='--allow'
>2801 		# fi
________________
While making some research about that, I found another interesting one: https://www.debian.org/doc/manuals/debian-faq/ch-pkgtools.en.html#s-apt-get

=> Since Jessie most apt-get commands can be called simpler, using just apt. Since both just works the same, it will be not worth to implement, just found that interesting 😄 .

**Comment by Fourdee** [comment]
@MichaIng 

> Therefore --allow-downgrades, --allow-remove-essential and --allow-change-held-packages would provide the same result. Looks like it could be differentiated more here, being less dangerous than just force yes for every kind of prompt.

Great job researching this and finding a fix to that warning 👍 

I'll get this added to to v152.

> Since Jessie most apt-get commands can be called simpler, using just apt. Since both just works the same, it will be not worth to implement, just found that interesting

Nice!

**Comment by Fourdee** [comment]
@MichaIng 

Works a treat, great job 👍 

Marking as completed.
