### ISSUE TITLE
RPi Jessie | WiFi = excessive "calling CRDA" print on tty1

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#102]
> http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=151#p565

Print appears harmless, does not affect operation of system. However, possible boot delay report from forum post (above).

**Comment by Fourdee** [comment]
> bugreport-c4e98412b213-0

wlan0 adapter is not being brought up during boot.

editing /etc/rc.local and adding the following is a workaround:
ifup wlan0

Possible systemd ordering, or, caused by CRDA failing.

**Comment by Fourdee** [comment]
As per http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=151#p568

Regardless of the /etc/default/crda setting. CRDA claims its not set:
root@dietpi:~# crda
COUNTRY environment variable not set

Notes to self:
- Can we disable CRDA?
- Can we run CRDA using runtime options (eg: crda --code=GB)?
- Do we need to add anything to the /etc/network/interfaces file for CRDA to function?

**Comment by Blamoo** [comment]
`apt-get install iw crda` solves this, I think...

**Comment by Fourdee** [comment]
Spot on, resolves the issue! Thanks for the info.

iw and crda will be installed during v100 patch.

Date: Tue, 3 Nov 2015 02:24:17 -0800

**Comment by blamoo** [comment]
Ah, sorry for deleting that post :p
