### ISSUE TITLE
DietPi-Software | Avahi-Daemon

### ISSUE THREAD

**Issue by GrahamEnigma** [MichaIng/DietPi#1030]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?

152

- SBC Device (EG: RPi 3)?
Rpi 3
- Power supply used (EG: 5v 1A RAVpower)?
USB

- SD card used (EG: Sandisk ultra)?

Sandisk
- Distro (EG: Jessie) | ```uname -a```?
Jessie

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

This is fresh :-)

#### Expected behaviour:

I changed hostname (RoonKitchen and Roon_Kitchen) and it did not display when scanning for IPs

#### Actual behaviour:

Hostname is blank

**Comment by Fourdee** [comment]
@GrahamGIGA 

Thanks for the report 👍 

I was unable to replicate this on RPi3, setting ```Roon_Kitchen``` as hostname in ```dietpi-config``` > Security options > Hostname, then rebooting, hostname is applied correctly and view-able from Roon.

The only thing that may throw this out is a space in the hostname, ensure this doesn't exist.

> Hostname is blank

Is this blank in:
- ```dietpi-config``` > Security options > Hostname ?
- ```cat /etc/hostname``` ?
- ```cat /etc/hosts```?

If its not blank, it may be router is not updating the hostname of device, possibly due to current DHCP lease. Try restarting the router to see if it refreshes the new hostname of device.

**Comment by Fourdee** [comment]
@GrahamGIGA 

If you want to view hostname outside of Roon, you may need to install ```avahi-daemon``` for hostname network broadcast:
```
apt-get install avahi-daemon -y
reboot
```

**Comment by GrahamEnigma** [comment]
Hi Dan, I'll give that a try!

Cheers

**Comment by GrahamEnigma** [comment]
Hi Dan, that fixes the publication.  However one odd issue if I name the host Roon_Boom (or anything else with an underscore) the underscore is removed when rpeorting the Hostname.

Cheers

Graham
<img width="783" alt="screen shot 2017-07-02 at 5 30 41 pm" src="https://user-images.githubusercontent.com/6692257/27774725-3445d54e-5f4c-11e7-9e54-69b646ec7bec.png">

**Comment by k-plan** [comment]
@GrahamGIGA 

>  However one odd issue if I name the host Roon_Boom (or anything else with an underscore) the underscore is removed when rpeorting the Hostname.

No, not DietPi issue, it is a restrictions on valid hostnames corresponding to [RFC](https://en.wikipedia.org/wiki/Request_for_Comments):
[Restrictions on valid hostnames](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames)


@Fourdee 

it will be a nice feature, to put `avahi-daemon` -  mDNS, Zeroconf, Bonjour - how ever you call it, as option into `DietPi-Software | Add additional linux software options`. So we can install it automated.
May be helpful for music-player demons, samba, print server, RPi Zero Ethernet Gadget and so on ...

**Comment by Fourdee** [comment]
@k-plan 

Great suggestion 👍 

I'll add to DietPi-Software. We could also include it as a pre-req for all audio software installations.

**Comment by k-plan** [comment]
@Fourdee 

> We could also include it as a pre-req for all audio software installations.

But it will help only Mac-user. Windows doesn’t have Zeroconf/Bonjour support out of the box.
Yes, you can install it: https://learn.adafruit.com/bonjour-zeroconf-networking-for-windows-and-linux/#microsoft-windows

Audio software installations, especially with streaming, mostly use services like Universal Plug and Play (UPnP), Airplay or Digital Living Network Alliance (DLNA) to broadcast their self announce.
Most of them do this out of the box.

**Comment by Fourdee** [comment]
Avahi-daemon is currently prereq for (automatically installed as needed):
- MPD
- Shariport-sync
- Virtual Here

Aside from the above (where its required for the software), I believe its best we leave the installation of Avahi-Daemon optional by end-user.

I'll mark this as completed.
