### ISSUE TITLE
[Question] If I setup DietPi in a VM can I create a image of the system and flash it on my actual Pi?

### ISSUE THREAD

**Issue by DiljotSG** [MichaIng/DietPi#1033]
Just like the title says, is this possible?

**Comment by Fourdee** [comment]
@DiljotSG 

Wouldnt work, different CPU arch. Would be like trying to run Mac OSX on android without emulation.

**Comment by DiljotSG** [comment]
Thank you for the reply, that is what I thought.

**Comment by Fourdee** [comment]
@DiljotSG 

Aye, would be nice. Give it 10 years, ARM will most likely overtake x86 (energy efficiency now and performance isn't far off), then it might be possible ;)
