### ISSUE TITLE
NZBget requires filesystem permissions to run (eg: EXT4)

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1038]
Moved all userdata to my USB stick then installed NZBget

ps -A | grep nzbget 

shows nothing
Cannot connect to port 6789

Made a config file out of the template but it seems to be not running. In HTOP I see nothing.

**Comment by Fourdee** [comment]
@Invictaz 

Lets check service status:
```
systemctl status nzbget.service -l
```

**Comment by Invictaz** [comment]
I found what is wrong during package.run downloading. Maybe it's because it's installing on a FAT32 USB stick? Need to fix this. 

tar: Exiting with failure status due to previous errors
ERROR: Unpacking failed.

![image](https://user-images.githubusercontent.com/20338545/27702493-872a3ff6-5d04-11e7-9665-6d629cd0aa12.png)

**Comment by Invictaz** [comment]
@Fourdee 

![image](https://user-images.githubusercontent.com/20338545/27702601-e22b4260-5d04-11e7-99a8-93477785af0f.png)

**Comment by Invictaz** [comment]
Dietpi userdata is now on /mnt/USB_1/dietpi_userdata and not on /mnt/dietpi_userdata/

So a redirect is missing somewhere (also).

**Comment by Invictaz** [comment]
I changed mount mode from /dev/UUID to /dev/SD in Drive Manager since FAT does not seem to support users. This did not work.

**Comment by Fourdee** [comment]
@Invictaz 

FAT16/32 does not support file permissions. We do not recommend using it for user data.

You'll need to move your userdata back to RootFS. Then format USB drive with ext4. Then you can transfer user data back to USB drive.

**Comment by Invictaz** [comment]
@Fourdee Thanks for the quick reply. Not exactly the solution I was hoping for but understandable.

**Comment by Fourdee** [comment]
@Invictaz 

Yep, permissions will reduce filesystem performance, however, the majority of software requires them to function. So, we recommend avoiding FAT 16/32 for user data location.

I'll mark this as closed. Please reopen if required.
