### ISSUE TITLE
DietPi-Software | XMPP-Server

### ISSUE THREAD

**Issue by DJCrashdummy** [MichaIng/DietPi#1039]
if anyhow possible at least one XMPP-Server would be nice.

although i'm not an expert i guess ~~[jabberd](http://jabberd2.org/) (written in C) or~~ [Prosody](https://prosody.im/) (written in Lua) would be a good choice, since i also read about them in conjunction with OpenWrt.

i'm not sure about [ejabberd](https://www.ejabberd.im/) (written in Erlang), but [Openfire](https://www.igniterealtime.org/projects/openfire/index.jsp) or [Tigase](http://www.tigase.net/content/tigase-xmpp-server) (both written in Java) would be to heavy for some boards...

---
maybe useful resources:
[XMPP Server (Prosody) in OpenWrt](https://wiki.openwrt.org/doc/howto/xmpp.server)
[prosody on a shared hoster](https://plaintext.blog/hosting/Uberspace/prosody.html)
[Configuring Prosody](https://github.com/jsxc/xmpp-cloud-auth/wiki/prosody) ([Configuring ejabberd](https://github.com/jsxc/xmpp-cloud-auth/wiki/ejabberd))

**Comment by DJCrashdummy** [comment]
the development of **jabberd** seems really slow now and also some XEP needed for OMEMO-support aren't implemented [(although pending since more than 3 years now)](https://github.com/jabberd2/jabberd2/issues/55).

so... yes it is still a working XMPP-server, but i would use it just as last resort.

**Comment by DJCrashdummy** [comment]
talking about OMEMO... the developers of conversations [suggest to use Prosody or ejabberd](https://github.com/siacs/Conversations#running-your-own):
> Ejabberd is slightly more mature nowadays but Prosody is arguably easier to set up.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
