### ISSUE TITLE
NPM Version control vs Node Red

### ISSUE THREAD

**Issue by JohnMacrae** [MichaIng/DietPi#1047]
## Creating a bug report/issue:
Node Red does not  recommend the use of NPM > v3 but version 4 or later is installed by dietpi
Could we have the choice of version or perhaps a clever way of dealing with this please?

#### Required Information:
- DietPi Version | 1.5
- SBC Device  RPi 3
- Power supply used Fine
- SD card used  Sandisk ultra
- Distro  Jessie?

#### Additional Information (if applicable):
- Node Red
- Can this issue be replicated on a fresh installation of DietPi?

YES

#### Expected behaviour:
A recommended version of NPM should be installed

#### Actual behaviour:
Version 5 is currently installed

#### Steps to reproduce:
Install node red from the Dietpi-software module

#### Did you submit a ```dietpi-bugreport```?
No

**Comment by Fourdee** [comment]
NPM is installed along with nodeJS. A shared library which is used by multiple DietPi-Software software titles.

We found ```npm``` < v5 (available through apt) was buggy with various software title installations. Hence we decided to always install the latest version from http://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh.

As Node-Red currently works with ```npm``` v5. I'll mark this as closed.
