### ISSUE TITLE
DietPi System | Option to set a custom NTP Server addresses

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1049]
@Fourdee 

It will be a handy and nice feature, if we can set a custom NTP Sever addresses (IP or fully qualified domain name) directly in `dietpi-config` and/or `dietpi.txt`.

For new users, a listing of some predefine NTP  Server,  how as well in `Choose Apt Mirror` would be very helpful.

Thanks in advance for your efforts.

cu
k-plan

**Comment by Fourdee** [comment]
@k-plan 

Yep, good suggestion 👍  I'll take a look for v154.

**Comment by Fourdee** [comment]
> http://www.pool.ntp.org/zone/europe
In most cases it's best to use pool.ntp.org to find an NTP server (or 0.pool.ntp.org, 1.pool.ntp.org, etc if you need multiple server names). The system will try finding the closest available servers for you. If you distribute software or equipment that uses NTP, please see our information for vendors.

**Comment by Fourdee** [comment]
![image](https://user-images.githubusercontent.com/7077026/28071565-34175496-6648-11e7-9933-eec0bbdcf99b.png)
![image](https://user-images.githubusercontent.com/7077026/28072144-05608c6a-664a-11e7-9f20-628d81706be9.png)

**Comment by Fourdee** [comment]
Also added to ```dietpi.txt```, applied during 1st run automation.

**Comment by Fourdee** [comment]
Completed.
