### ISSUE TITLE
DietPi-Software | Searx Meta Search Engine

### ISSUE THREAD

**Issue by DJCrashdummy** [MichaIng/DietPi#1050]
i know, with [YaCy](https://github.com/Fourdee/DietPi/issues/817) there is already a search engine available, but [Searx](https://github.com/asciimoo/searx) is not completely the same:
it is a **meta** search engine and relies on the indexes from other providers (simplified you can think about it like your own free DuckDuckGo), but therefore it is not so heavy like YaCy.

as an lightweight alternative to YaCy it would be nice to have Searx as an option.

there is also a documentation for installing: https://asciimoo.github.io/searx/dev/install/installation.html

**Comment by kaffeekanne** [comment]
As public searx instances are often very slow due to heavy traffic it would be awesome to have this officially included in dietpi. Will probably install it by hand, but for the interested non expert an automated installation would be nice.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by b1n4ryj4n** [comment]
still not implemented?

**Comment by Nutjob** [comment]
I would also like an implementation of Searx on Dietpi

**Comment by IAmCainey** [comment]
I have been using Searx for a little bit now and its the only way i browse the net,. Cmon :)

**Comment by surtarso** [comment]
kudos for searx!!  yacy , tho awesome, is too intense for simple use

**Comment by tmcgough** [comment]
Seems all avenues have been closed, but I would like to add my vote for searx or searxng as both are very useful and would love to see them added to the list of tools on DietPi.  YaCy can fill up your storage if left unchecked and not very verbose on searrches.  Searx and Searxng are both very efficient and work great on the DietPi.  As you state, they can be installed manually but it would be very nice to see them as an option along with YaCy in the approved added installation options.
