### ISSUE TITLE
Video disk recorder is eating up boot time

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1057]
Dietpi v152

Video disk recorder fails in serial bootup log and is tried a few times. 
Googled a bit and it seems I don't need it.  How to disable it? It is a service

**Comment by Invictaz** [comment]
Possibly related to Me TV installed but not sure.

**Comment by Fourdee** [comment]
@Invictaz 
> Video disk recorder fails in serial bootup log and is tried a few times

This isn't installed on DietPi by default.

Check the status of the service with:
```
systemctl status NAMEOFSERVICE -l
```

**Comment by Fourdee** [comment]
I'll mark this as closed. Please reopen if required.
