### ISSUE TITLE
DietPi-Config | Support for composite video output + overscan compensation

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1058]
In resolution setting there is no such thing as 720x576 (PAL)

Also there is only an overscan setting yes or no but no overscan compensation values, see this adafruit example

![image](https://user-images.githubusercontent.com/20338545/27935766-42131132-62ad-11e7-8b28-0be33d21074f.png)

**Comment by Fourdee** [comment]
```
sdtv_mode=0    Normal NTSC
 sdtv_mode=1    Japanese version of NTSC – no pedestal
 sdtv_mode=2    Normal PAL
 sdtv_mode=3    Brazilian version of PAL – 525/60 rather than 625/50, different subcarrier
```

**Comment by Fourdee** [comment]
Overscan Compensation becomes available once Overscan is enabled:
![image](https://user-images.githubusercontent.com/7077026/28170016-f23fb186-67db-11e7-8451-50c856ad2ca2.png)

**Comment by Fourdee** [comment]
- 🈯️ Test overscan
Interesting, ```disable_overscan=1``` has no effect. Values always pulled from ```overscan_*```
- 🈺 Test SDTV: Unable, lack composite device.

**Comment by Fourdee** [comment]
@Invictaz 

Any chance you would be willing to test the SDTV modes in testing branch for us?
https://github.com/Fourdee/DietPi/blob/master/TESTING-BRANCH.md

**Comment by Fourdee** [comment]
I'll mark this as completed. Testing outstanding, however, confident functional.

@Invictaz 
If you get a chance to test this, please let us know.

**Comment by Invictaz** [comment]
@Fourdee Is the overscan=1 now working or still ignored?

I also have a weird bug in v153. Sometimes it switches back to headless instead of composite.
