### ISSUE TITLE
Failure to Install Emby Server

### ISSUE THREAD

**Issue by DncrJim** [MichaIng/DietPi#1059]
#### Required Information:
- DietPi Version | 153
- SBC Device | RPi 3

#### Issue:
Fresh install of DietPi fails to install emby-server using 'dietpi-software'.

"http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb is offline and/or unreachable."

Perhaps the solution is obvious and/or simple, but I have exhausted my skill level and forum/google search to no avail. 

#### Additional Information:
I have not submitted a bug report because the system auto-restarts after failure to install. If system info etc. is necessary for debug, I will be happy to submit the report.

Note: a new version of emby-server was released early this week (and failing to auto-upgrade, prompting this ill-conceived and apparently futile attempt at a fresh install); I do not know if this is relevant.

**Comment by Fourdee** [comment]
@DncrJim 

Thanks for report. 👍  Confirmed.

Seems the connection test fails:
```
[Info] Testing connection to http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb
 [Info] Max duration of 20 seconds, please wait...
 [Failed] Connection test | An issue has occured
```

**Comment by Fourdee** [comment]
```libjpeg8``` packages have been removed from SID repo. Only ARMv8 exists as unofficial port:
https://packages.debian.org/sid/libjpeg8

Only other available package is in Wheezy, lacks ARMv8:
https://packages.debian.org/wheezy/libjpeg8

---

- 🈯️ ARMv7
Raspbian and emby repo
```
root@DietPi:~# apt-cache policy libjpeg8
libjpeg8:
  Installed: 8d1-2
  Candidate: 8d1-2
  Version table:
 *** 8d1-2 0
        500 http://www.mirrorservice.org/sites/archive.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
     8c-2ubuntu8 0
        500 http://download.opensuse.org/repositories/home:/emby/xUbuntu_14.04/  Packages
```

- 🈴 ARMv8 | Lack of available ```libjpeg8``` package for this arch. Install now disabled.
Still requires ```libjpeg8``` from another source.
All links provide 404: https://packages.debian.org/sid/arm64/libjpeg8/download
- 🈯️ AMD64 (stretch)
Resolved using appropriate Debian_x.0 opensuse repos

---

http://download.opensuse.org/repositories/home:/emby/xUbuntu_14.04/ is the only repo which contains ARM binaries.

**Comment by Fourdee** [comment]
@DncrJim 

Fixed for v154.

You can patch the script now with:
```
wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-software -O /DietPi/dietpi/dietpi-software
```

Emby server will now install in ```dietpi-software```.
