### ISSUE TITLE
DietPi-Software and DPlatform

### ISSUE THREAD

**Issue by DJCrashdummy** [MichaIng/DietPi#1061]
i'm not sure wether [DPlatform Shell](https://dfabric.github.io/DPlatform-ShellCore/) by @DFabric is already known or not, but lately i came across it and in my view there are some similarities with DietPi respectively DietPi-Software to be concrete.

the scopes of the projects are not the same (minimal SBC-OS vs. application-management), so completely joining forces won't make sense but maybe it is possible to collaborate and exchange code.

**Comment by Fourdee** [comment]
@DJCrashdummy 

> https://dfabric.github.io/DPlatform-ShellCore/

Interesting project, thanks for sharing.
