### ISSUE TITLE
DietPi-Software | Steam client

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1062]
Since DietPi is going for native X86 64 bit Steam or (parts of) SteamOS are maybe quite nice.

The GPU Drivers for Nvidia are implemented in DietPi already (with Vulkan) 

http://steamcommunity.com/groups/steamuniverse/discussions/1/143387886726826685/

Links to the FAQ and repo:

http://steamcommunity.com/groups/steamuniverse/discussions/1/648814395741989999/

**Comment by Invictaz** [comment]
Also: Moonlight which is a streaming client for NVIDIA Gamestream

https://github.com/irtimmer/moonlight-embedded/wiki/Packages

**Comment by Fourdee** [comment]
@Invictaz 

Had my eye on this aswell, want to test streaming 👍 

> https://wiki.debian.org/Steam#A64-bit_systems_.28amd64.29

**Comment by Fourdee** [comment]
- 🈴 NV, no sound in games.

Remove bundled libs:
```
rm -R "$HOME"/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/alsa-lib
rm -R "$HOME"/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/alsa-lib

rm "$HOME"/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libasound.so.*
rm "$HOME"/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libasound.so.*
```

**Comment by Invictaz** [comment]
Steam does not run after selecting from the start menu, alsno not when installing the Nvidia driver.

The packages you describe are still being installed, at least I saw them after selecting my ALC663 sound card...

**Comment by Invictaz** [comment]
Steam is unable to start since it cannot apply updates

![20170718_235824](https://user-images.githubusercontent.com/20338545/28341758-45c5c16e-6c15-11e7-9122-4812a5c9fd66.jpg)

**Comment by Invictaz** [comment]
I tried again. Dietpi is installed on a usb stick with 6gb free

![20170719_000307](https://user-images.githubusercontent.com/20338545/28341880-d000d062-6c15-11e7-8f31-196720f1af76.jpg)

**Comment by Invictaz** [comment]
Here is the bootstrap_log
[bootstrap_log.txt](https://github.com/Fourdee/DietPi/files/1157427/bootstrap_log.txt)

**Comment by Invictaz** [comment]
Partially it's permission issues. Partially related to driver and partially it misses pieces 

https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues
https://askubuntu.com/questions/614422/problem-with-installing-steam-on-ubuntu-15-04
https://askubuntu.com/questions/771032/steam-not-opening-in-ubuntu-16-04-lts
https://bbs.archlinux.org/viewtopic.php?id=157825
https://bbs.archlinux.org/viewtopic.php?id=221007
https://github.com/voidlinux/void-packages/issues/4239
https://www.reddit.com/r/linuxquestions/comments/4o8xlc/ubuntu_1604_fatal_error_failure_to_load_steamuiso/

Maybe needs 32 bit Steam to run on 64?

https://www.reddit.com/r/linux_gaming/comments/13jwam/fatal_error_failed_to_load_steamuiso_how_to_fix/

**Comment by Fourdee** [comment]
Nudging to v155, clearly lots more work to do on this ticket.

**Comment by Invictaz** [comment]
@Fourdee I'm a little bit further now. Seems the coulnd't find bootstrap is because Steam is in the wrong place.
Dunno if that is fixable since it's now in Dietpi userdata folder

https://github.com/ValveSoftware/steam-for-linux/issues/4076

**Comment by Invictaz** [comment]
@Fourdee running the NVIDIA .run instead of the apt-get install needs the 32 bit compatibility files for Steam to work. There might be some Mesa conflicts I have seen. My latest error window is now somewhat like this. Some errors have been resolved, others not.

![plaatje5](https://user-images.githubusercontent.com/20338545/29008044-d087e1c8-7b07-11e7-8924-de898f806a0a.png)

**Comment by MichaIng** [comment]
@Fourdee 
I guess there is still work to do on this?
If it is not working reliably currently on we don't find the time to fix, we should properly disable it for now?

**Comment by MichaIng** [comment]
Time has passed and I made some update: https://github.com/MichaIng/DietPi/commit/93efa92a64a37ddbf2f1190d8d641f85d68998e0
We installed old/deprecated packages before, hence I updated our installer to pull the modern (and suggested/recommended by steam package) i386 Nvidia driver libs, if Nvidia driver is installed.

@Invictaz 
The changed Steam data dir location should not be an issue since we symlink it from /root/.steam, hence the original path stays valid. However this does not work when executing the client as different non-root user. So I am thinking in this case whether the shared data dir is a good idea here, since it breaks the general multi-user functionality. Generally any user could be added to games, video (and on Buster render) groups and should then be able to run steam. There is not much integration like a systemd unit or such shipped with the package, which would execute as fixed user (like username = `steam`), e.g. autostarting on boot, and then reasonably use /mnt/dietpi_userdata/steam as data dir.

**Comment by Invictaz** [comment]
@MichaIng Great for picking this up again. I have the Nvidia driver running.

However, having the 32 bit Nvidia drivers is only part of the problem. AFAIK I did run the Steam client from both root and non-root user and it did not work. So what is wrong?

**Comment by MichaIng** [comment]
@Invictaz 
The bootstrap bug should have been solved meanwhile btw. Also as said there has been some things changed about the Nvidia drivers/libs composition, hence I think this can all be best tested on a fresh DietPi/Debian Buster system.

**Comment by MichaIng** [comment]
I have sound here, running it on VirtualBox. We'll make it available on ARM as well via Box86: https://github.com/MichaIng/DietPi/pull/4020

For gamepad and VC input devices btw `steam-devices` is usually required, so we'll install this as well.

**Comment by Invictaz** [comment]
@MichaIng Thanks for the hard work
