### ISSUE TITLE
Image Request | Banana Pi M3 official support

### ISSUE THREAD

**Issue by stdusm** [MichaIng/DietPi#1063]
This is a request to  support Banana Pi M3 officially.
I use it for more than one year without any issues with latest updates and so on.
Here is the sample:
http://forum.banana-pi.org/t/bpi-m3-new-image-dietpi-preview-bpi-m3-sd-emmc-image-2016-5-14/1685 
Thanks.

**Comment by Fourdee** [comment]
@stdusm 

> http://forum.banana-pi.org/t/bpi-m3-new-image-dietpi-preview-bpi-m3-sd-emmc-image-2016-5-14/1685

This is an unofficial image created by BPi, not provided/supported by us as we lack the board currently.

I'll pop the BPi M3 on the SBC purchase list.

**Comment by Elluminatus** [comment]
Would be very nice because of the sata port and the cpu performance. Nice piece of hardware for a little server in the house.

**Comment by zgon81** [comment]
What is the status? It would be really great to officialy implement the DietPi on my BananaPi M3...

**Comment by Fourdee** [comment]
@zgon81 

> What is the status? 

Unfortunately, still lacking the board for implementation. Price of unit is also in question, beyond current funds.

We'd need to see alot more user interest to warrant a purchase.

**Comment by Fourdee** [comment]
Closing due to BPi image/support being dropped.
