### ISSUE TITLE
[Dupe] Emby Server installation is failing 

### ISSUE THREAD

**Issue by stdusm** [MichaIng/DietPi#1064]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 
153
- SBC Device (EG: RPi 3)? 
BPI M3
- Power supply used (EG: 5v 1A RAVpower)? 

- SD card used (EG: Sandisk ultra)? 
mmc
- Distro (EG: Jessie) | ```uname -a```?  
Linux MediaServer 3.4.39-BPI-M3-Kernel #1 SMP PREEMPT Tue May 3 13:47:01 UTC 2016 armv7l GNU/Linux

#### Additional Information (if applicable):
- Software title? 
Emby Server
- Can this issue be replicated on a fresh installation of DietPi? 
yes

#### Expected behaviour:
Emby Server is installed

#### Actual behaviour:
Emby Server installation is failing 

#### Steps to reproduce:
Install Emby Server

#### Extra details:
Unable to Install Emby Server: web interface media streaming  server   
http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb is offline and/or unreachable.
Similar for Subsonic 6

**Comment by Fourdee** [comment]
@stdusm 

Hi, thanks for the report 👍 

This is fixed for v154, and can be also be patched now, please see following link:
https://github.com/Fourdee/DietPi/issues/1059#issuecomment-313682864
