### ISSUE TITLE
[Question] Dependence on package "pciutils"?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1068]
Is dietpi actually (still) dependent on the package "pciutils" respectively it's provided commands?

I do not find any use of `lspci`, `setpci` or `update-pciids` inside the code, nor any other use of the package: https://github.com/pciutils/pciutils

On my Pi2 I tried to run `lspci` with this result:
> pcilib: Cannot open /proc/bus/pci
> lspci: Cannot find any working access method.

I mean it doesn't disturb aether, but in case of looking for diet perfection... ;).

I just purged it on my system and watch out for errors.

**Comment by Fourdee** [comment]
@MichaIng 

> I do not find any use of lspci, setpci or update-pciids inside the code, nor any other use of the package: https://github.com/pciutils/pciutils

Great find, its not needed 👍

Can be removed from system prep script and we could also patch for its removal:
https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L126

We'll need to check VM/Native PC to ensure removing this package doesn't cause dep issues, with other packages that may need it.

**Comment by Fourdee** [comment]
@MichaIng 

Resolved with your commit 👍 : https://github.com/Fourdee/DietPi/issues/1070

Will mark this as completed.
