### ISSUE TITLE
XRDP install doesn't work unless TightVNC is installed 

### ISSUE THREAD

**Issue by FutureTense** [MichaIng/DietPi#1069]
#### Required Information:
- DietPi Version | ```153```
- SBC Device ODROID C1+
- Power supply: USB
- SD card used EEMC
- Distro (EG: Jessie) | ```Linux DietPi 3.10.104 #1 SMP PREEMPT Sun Mar 26 14:55:18 CEST 2017 armv7l GNU/Linux```

#### Additional Information (if applicable):
- Software title:XRDP
- Can this issue be replicated on a fresh installation of DietPi? I believe so.

#### Expected behaviour:

Should be able to launch desktop using Windows Remote Desktop
#### Actual behaviour:

See description and screenshot posted on [forum](http://dietpi.com/phpbb/viewtopic.php?f=11&t=2053)

#### Steps to reproduce:

Fresh DietPi install.
Install a desktop, such as MATE
Install XRDP
Start a remote desktop connection from Windows

#### Extra details:

From a bit of research I discovered others fixed this by installing TightVNC before installing XRDP.  I uninstalled XRDP, installed TightVNC then installed XRDP and it worked.  I did not try installing TightVNC after installing XRDP

**Comment by Fourdee** [comment]
@FutureTense 

Thanks 👍 

> https://github.com/Fourdee/DietPi/issues/1071
http://dietpi.com/phpbb/viewtopic.php?f=11&t=2053#p7982

**Comment by Fourdee** [comment]
Notes:
- Straight forward apt install ```xrdp```
- Possible apt installation issue, would explain the install of tightvnc to resolve?

Tests:
- 🈯️ Fresh DietPi image, install XRDP only (LXDE)
- 🈯️ Fresh DietPi image, install MATE & XRDP.
![image](https://user-images.githubusercontent.com/7077026/28215711-d2b27e68-68a6-11e7-91d8-b50779531b98.png)

**Comment by Fourdee** [comment]
@FutureTense 

We were unable to replicate the issue in our tests. We believe this may be limited to an APT installation issue, or a unknown connection issue with XRDP server (in which case we would need logs to debug).

- Can you remember seeing any onscreen apt errors during the 1st installation (eg: prompt).
- If the connection issue occurs again, please can you paste the results of the XRDP logs:
```cat /var/log/xrdp-sesman.log```

**Comment by FutureTense** [comment]
I'll try a fresh install when I get a chance. Please leave this open for a few weeks?

**Comment by Fourdee** [comment]
@FutureTense 

> I'll try a fresh install when I get a chance. Please leave this open for a few weeks?

Yep no worries, please let us know results 👍

**Comment by MichaIng** [comment]
@FutureTense
Is this issue resolved for you? Otherwise now is a good time for a fresh installation and retest, as v6.0 was released which can't be updated to from 159 or lower.

**Comment by Fourdee** [comment]
@MichaIng 

May be linked to similar issue with https://github.com/Fourdee/DietPi/issues/1442

However, i'll close this in preference of the above, which I'll test/verify/resolve installation.
