### ISSUE TITLE
Plex media server - will not install

### ISSUE THREAD

**Issue by bwaddington** [MichaIng/DietPi#1073]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by Fourdee** [comment]
@bwaddington 

Hi, thanks for report.

We'll need more information.

- Which device are you running (eg: RPI 3)?
- Did you receive any on screen error prompts during the installation?

**Comment by bwaddington** [comment]
Thank you for getting back to me! i have managed to sort it out, there was a problem with the mirror site. plex installed but there was no web interface. just did a clean install of dietpi and its all working now.

**Comment by Fourdee** [comment]
@bwaddington 

Thanks for letting us know 👍 . I'll mark this as resolved.
