### ISSUE TITLE
DietPi-Config | Auto Reconnect Wifi in DietPi - Wireless Network Options

### ISSUE THREAD

**Issue by bhaveshgohel** [MichaIng/DietPi#1074]
Dear @Fourdee ,
Is it possible to add Auto Reconnect Wifi in 'DietPi - Wireless Network Options' by setting Wireless Details in 'Manually Set Wireless Details' option. 

**Goal** : Raspberry Pi will keep on searching for the SSID at some interval and if the network available it will connect to that network and  when on disconnect it again search for the same network and repeat.

**Comment by Fourdee** [comment]
@bhaveshgohel 

> Is it possible to add Auto Reconnect Wifi in 'DietPi - Wireless Network Options' by setting Wireless Details in 'Manually Set Wireless Details' option.

Currently not, if the SSID drops connection, WiFi will unlikely reconnect.

> Goal : Raspberry Pi will keep on searching for the SSID at some interval and if the network available it will connect to that network and when on disconnect it again search for the same network and repeat.

I made a script to monitor existing WiFi connections, and, reconnect if it fails. We could implement that system into DietPi-Config?
https://community.roonlabs.com/t/wifi-disappears-after-a-day/25850/20?u=dan_knight

**Comment by bhaveshgohel** [comment]
Dear @Fourdee, 
I tested the script and it is working fine... :+1:  ( Thank you for adding in V155.  :tada: )


>We could implement that system into DietPi-Config?

We can add it inside 'Manually Set Wireless Details' option as one field  --> Auto Reconnect- Yes/No. [ suggestion]

**Comment by Fourdee** [comment]
Completed.
