### ISSUE TITLE
[dupe] Emby install failed

### ISSUE THREAD

**Issue by trebunski** [MichaIng/DietPi#1079]
## Creating a bug report/issue:
Unable to Install Emby Server: web interface media streaming server 
http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb is offline and/or unreachable. 

#### Required Information:
- DietPi Version: 153
- SBC Device: oDroid XU3/4 (armv7l)
- Distro (EG: Jessie) : Linux dpi 3.10.105+ #1 SMP PREEMPT Tue Jun 6 15:02:21 CEST 2017 armv7l GNU/Linux

#### Additional Information (if applicable):
- Emby
- Reproduceable: Yes i reproduced it twice on fresh installation-

#### Expected behavior:
Install Emby will be completed

#### Actual behavior:
Error at installation step

#### Steps to reproduce:
- Go to dietpi-software> Software Optimized > select Emby
- Trigger install Optimized Software
- Get Error: "Unable to Install Emby Server: web interface media streaming server 
http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb is offline and/or unreachable.  "

#### Did you submit a ```dietpi-bugreport```?
no

**Comment by Fourdee** [comment]
Hi, 
Thanks for the report 👍 

Please see:
https://github.com/Fourdee/DietPi/issues/1059#issuecomment-313682864
