### ISSUE TITLE
LXDE cannot be installed nor uninstalled

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1086]
Native PC X86_64

Cannot submit a bug report, its 53 mb and the max is 50 :(
LXDE is partially installed due to a hang on reset (shutdown the network controller) so I had to hard reset my pc. 

I want to reinstall it but gives ALSA 100 error

Only option is to reflash the image and try again.

As you see LXDE is still installed although cannot be selected for deinstall. In other words the previous attempt to deinstall LXDE failed although was succesfull in the Dietpi-uninstaller. Apt-get update apt-get autoremove and apt-get upgrade didnt do anything. I also ran the dietpi cleaner, didnt work.

![img_20170718_203824](https://user-images.githubusercontent.com/20338545/28334882-d539b468-6bfc-11e7-86a8-a57c15490fe6.jpg)

![img_20170718_204518](https://user-images.githubusercontent.com/20338545/28334920-eff6a248-6bfc-11e7-9442-ccf9f2ac45c0.jpg)
![img_20170718_204652](https://user-images.githubusercontent.com/20338545/28334919-eff52a8a-6bfc-11e7-8a24-b2a0b0275894.jpg)

**Comment by Invictaz** [comment]
@Fourdee Any clue?

**Comment by Fourdee** [comment]
@Invictaz 

We'll need to see the apt log, as reported in the error message.

> Cannot submit a bug report, its 53 mb and the max is 50 :(

Thanks, i'll see if we can tweak this.

**Comment by Fourdee** [comment]
Outdated.
