### ISSUE TITLE
Dietpi-Software | LCDproc or LCD4Linux for Dietpi

### ISSUE THREAD

**Issue by Elluminatus** [MichaIng/DietPi#1089]
A good Solution for older LCD Displays (eg. 20*4) to run on a headless device as a small info screen.

for more Information:

http://lcdproc.omnipotent.net/

or

https://lcd4linux.bulix.org/

Workaround for old serial or parallel LCD to USB: eg. http://www.electroschematics.com/12459/arduino-i2c-lcd-backpack-introductory-tutorial/
or http://www.raspberrypi-spy.co.uk/2015/05/using-an-i2c-enabled-lcd-screen-with-the-raspberry-pi/
or https://eckstein-shop.de/USB-zu-UART

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
