### ISSUE TITLE
Upgrade "v100" been waiting for "apt-get update"

### ISSUE THREAD

**Issue by septs** [MichaIng/DietPi#109]
![](https://cloud.githubusercontent.com/assets/3842474/11035189/a892144e-872b-11e5-843b-7fad76455d38.png)

Model: Raspberry Pi 1 model B+

**Comment by Fourdee** [comment]
Hi Septs,

At the command prompt, can you run the following code please:

> rm /DietPi/dietpi/.dietpi-apt-get_update
> killall apt-get
> /DietPi/dietpi/dietpi-apt-get_update 2

**Comment by septs** [comment]
thank you, `rm /DietPi/dietpi/.dietpi-apt-get_update` after normal

**Comment by Fourdee** [comment]
Awesome, thanks for letting me know.

I've updated the dietpi-apt-get_update code for v101. This will prevent this issue from occurring.

**Comment by septs** [comment]
![](https://cloud.githubusercontent.com/assets/3842474/16679018/1bfabd9c-4517-11e6-8137-e48a601ef29c.gif)

**Comment by Fourdee** [comment]
@septs 

Can you please paste results of:

```
cat  /DietPi/dietpi/.dietpi-apt-get_update
```

And:

```
/DietPi/dietpi/dietpi-apt-get_update 2 
#Your connection looks slow, please wait for at least 2 minutes before terminating.
cat /var/log/dietpi-apt-get_update
```

PS. What program did you use to record screen to .gif, its awesome :)

**Comment by septs** [comment]
later, several attempts by the update

---

Re: record screen: 
Ubuntu see https://wiki.ubuntu.com/CreatingScreencasts
Windows/OS X see http://www.cockos.com/licecap/

**Comment by Fourdee** [comment]
Nice:
![test](https://cloud.githubusercontent.com/assets/7077026/16691489/c1734070-4524-11e6-97ba-87ac04a97f2e.gif)
