### ISSUE TITLE
PiBakery configuration compatibility

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#1098]
Maybe it's handy that people who don't have a mouse / keyboard can setup DietPi before first launch. PiBakery is intended for this first setup but lacks some of the building blocks that Dietpi-config has.  

https://github.com/davidferguson/pibakery

**Comment by Fourdee** [comment]
@Invictaz 

> Maybe it's handy that people who don't have a mouse / keyboard can setup DietPi before first launch. 

We have our own automation system to achieve this:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=273#p1140

**Comment by Invictaz** [comment]
@Fourdee not correct as the /boot/dietpi.txt is IN the image and thus on a EXT4 partition you cannot write on from Windows. Correct me if I'm wrong.

**Comment by sytone** [comment]
I use ext2fsd to do any changes like this http://www.ext2fsd.com/
