### ISSUE TITLE
Information: DietPi development on temporary hold (paternity leave)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1100]
Hi all,

Just a heads up, development on DietPi has mostly been put on hold, and my activity will be reduced for a few weeks. Expecting the baby 👶 to arrive in the next day or two.

I'll monitor and reply to tickets, and, keep the ship running, when possible.

**Comment by dhernan3** [comment]
My congratulations!!!
My best wishes for all your family and new baby!

**Comment by Fourdee** [comment]
![img_20170801_025424_hdr](https://user-images.githubusercontent.com/7077026/28965214-e39762a4-7907-11e7-8a43-2ddc673ba8e9.jpg)

**Comment by dhernan3** [comment]
Congratulations!

**Comment by elRadix** [comment]
@Fourdee is a Happy Father now, congratulations with your new born!!

**Comment by Lanxon** [comment]
Congratulations...best day ever for you..

**Comment by Invictaz** [comment]
Congrats

**Comment by WolfganP** [comment]
Congrats @Fourdee. So I assume this is the newer release, Fivedee? :-)

**Comment by Fourdee** [comment]
@WolfganP 

Thanks 👍 

> Fivedee? :-)

Lol, second baby. 6D ;)

**Comment by k-plan** [comment]
@Fourdee 

Congratulations and regards to mother, father, son to the new member of the gowing family.

btw, nice name

**Comment by Elluminatus** [comment]
Congrats and all the best for your family...

**Comment by alexthe-red** [comment]
congrats on the new branch!

**Comment by Fourdee** [comment]
Thanks everyone. 

I'll mark this as closed. DietPi devolpment will continue, however, at a much slower pace. Simply don't have the time :frowning_face:
