### ISSUE TITLE
Tonido doesn't install (and FIX)

### ISSUE THREAD

**Issue by dhernan3** [MichaIng/DietPi#1101]
Tonido doesnt' install, failed to download libjpeg8. Tried on Raspberry Pi3 and VM.

Unable to Install Tonido: lightweight cloud based backup system   http://ftp.us.debian.org/debian/pool/main/libj/libjpeg8/libjpeg8_8d1-2_amd64.deb is offline and/or unreachable. 

The problem is the package trying to install doesn't exist. The package must be called:
libjpeg8_8d-1+deb7u1_amd64.deb      for VM
libjpeg8_8d-1+deb7u1_armhf.deb       for RPi 3

**Comment by Fourdee** [comment]
@dhernan3 

Thanks for the report 👍 

Yep, the required package version has changed, no longer available. We'll take a look.

**Comment by Fourdee** [comment]
@dhernan3 

~~This should of been resolved in v154 (at least for Emby install): https://github.com/Fourdee/DietPi/issues/1059
Is the issue still occurring with v154 installed?~~

Confirmed.

**Comment by Fourdee** [comment]
@dhernan3 

Fixed for v155, can be patched now with:
```
wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-software -O /DietPi/dietpi/dietpi-software
```
Tonido will now install.
