### ISSUE TITLE
Image Request | Rock64

### ISSUE THREAD

**Issue by douglasmiranda** [MichaIng/DietPi#1102]
### https://github.com/Fourdee/DietPi/issues/1102#issuecomment-336475062

---

So, any plans for support / make an DietPi for [Rock64](https://www.pine64.org/?page_id=7147)?

[Here](http://wiki.pine64.org/index.php/ROCK64_Main_Page) we can see it's already running Debian Strech Linux Kernel 4.4.

PS: I'm asking here, because I'm waiting for a long time the approval of my account on DietPi forum, so far nothing.

**Comment by Fourdee** [comment]
@douglasmiranda 

Ordered one recently, its in transit:
![image](https://user-images.githubusercontent.com/7077026/29002686-fd9ecc5c-7a9f-11e7-80d0-a9e3fec92d92.png)

When it arrives, we'll support the board and provide an image.

> PS: I'm asking here, because I'm waiting for a long time the approval of my account on DietPi forum, so far nothing.

Apologies for the delay, i've activated all accounts. If still no joy, please let me know the username for the account.

**Comment by k-plan** [comment]
Hmm, seem to have some nice hardware features, which RPi users have to wait for a long time ...

But Rockchip RK3328 Quad-Core ARM Cortex A53 64-Bit Processor ? 

Hope, it will be not the same non-starter like PINE A64 for the community ... 😉

**Comment by Fourdee** [comment]
notes:
- 🈴 https://github.com/ayufan-rock64/linux-build/releases/download/0.4.17/stretch-minimal-rock64-0.4.17-85-arm64.img.xz hangs on boot ```[7.x]``` for ```eth0 device MAC address```
- Worked on second boot
- 🈺 EMMC untested
- 🈺 Intermittent hangs/loss of connection during SSH sessions. Flaky eth drivers?
- 🈺 Issues with ayufan repo, we'll remove.
```
E: Failed to fetch http://deb.ayufan.eu/orgs/ayufan-rock64/releases/Packages.gz  Writing more data than expected (14108 > 12449)
   Hashes of expected file:
    - Filesize:12449 [weak]
    - SHA512:d7d6a86264c9a18fe8d5fa89422bab7509cbcfd3b630d4ccd13d777cea2d2ce39a8701212955c9754669162e44542d1d1390401bc071845e96740792b6a2452b
    - SHA256:8dcedca9b8bee3851a8b4778e8cb2a4b79a7a34823a1b24eda48c9a2dac06367
    - SHA1:60555aaa5aa4c5fcd520cedca3ee4476f101ed2c [weak]
    - MD5Sum:3c15712b76685318d080184e9caeb4dc [weak]
   Release file created at: Mon, 31 Jul 2017 09:49:37 +0000

```

---

Audio
- 3.5mm = ```hw:0,0```
- HDMI = ```hw:1,0```

**Comment by alexthe-red** [comment]
+1 for rock64. DietPi has ruined me f0r all non-compatible boards out there :)

**Comment by Fourdee** [comment]
### Image available for beta testing:
### http://dietpi.com/downloads/testing/DietPi_Rock64-arm64-(Stretch).7z

#### Known issues:
#### https://github.com/Fourdee/DietPi/issues/1102#issuecomment-323343966

**Comment by molemantis** [comment]
Thanks for this beta! As commented in your notes, SSH hangs when launching dietpi-software (works when directly connected to console) using either ssh or dropbear, and I wasn't able to boot after flashing to EMMC. Everything else is working great.

**Comment by DeviantEng** [comment]
So glad to see there's work on this already.  Like others, for me it's DietPi or bust when it comes to Linux on SBC's.  Definitely hope eMMC booting is supported as well.  I received a ROCK64 today, but I believe it's DoA so I've still got a couple of weeks before I can contribute any testing.

**Comment by alexthe-red** [comment]
Something that threw me off for a bit with this board and Dietpi:: 

- Couldn't access via SSH unless fresh dietpi install had ethernet settings set to 10. Pine forums mention that you can physically accomplish this by snipping a couple wire pairs on your ethernet cable. But I edited the dietpi config file before imaging the SD. Once inside, I was bumped the ethernet speed to 100 with `ethtool -s eth0 speed 100 duplex full`. Too afraid to bump it to 1000 since the Pine64 board couldn't handle it (http://dietpi.com/phpbb/viewtopic.php?f=11&t=833)

- The memory card I was using (32gig) wouldn't correctly partition to use all the space, so consequently it would fill up during  the auto updates on first boot and cancel the update script. I fixed this using the following thread:
https://www.raspberrypi.org/forums/viewtopic.php?t=45265

Should I just be posting these as issues? Or are they separate because of the testing status?

**Comment by Fourdee** [comment]
### Image updated for Release candidate:
#### - http://dietpi.com/downloads/images/DietPi_Rock64-arm64-(Stretch).7z

Includes latest kernel and fixes networking issues. Also includes working ayufan Rock64 repo (for kernel updates).

Existing users should reinstall with this image, as patching is not possible.

---

### ETA on Official Release:
Pending v157 being released due to fixes listed below.

---

Notes:
- EMMC is untested on this image.
- CPU temp is incorrect, as read out by ```cpu``` and ```dietpi-config``` | 🈯️ Fixed in v157
- Issues with incorrect board detection in some DietPi scripts | 🈯️ Fixed in v157

**Comment by Fourdee** [comment]
Performance notes:
- SD, disappointing compared to RPi (17.5MB/s)
![image](https://user-images.githubusercontent.com/7077026/31553378-3597074c-b032-11e7-9616-982eeff2beba.png)
- LAN
```
root@DietPi:~# iperf -c 192.168.0.111 -p 5001 -t 30 -d
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
------------------------------------------------------------
Client connecting to 192.168.0.111, TCP port 5001
TCP window size:  425 KByte (default)
------------------------------------------------------------
[  3] local 192.168.0.20 port 57508 connected with 192.168.0.111 port 5001
[  5] local 192.168.0.20 port 5001 connected with 192.168.0.111 port 55342
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-30.0 sec  1.15 GBytes   330 Mbits/sec
[  5]  0.0-30.0 sec  5.29 GBytes  1.51 Gbits/sec
```
- Heat eff. Impressive, no heatsink required for general use.
```
 [Ok] Stress Test Completed
 [Info]  - Start Time: Fri 13 Oct 16:23:33 BST 2017
 - End Time  : Fri 13 Oct 16:24:33 BST 2017
 - Duration  : 60 seconds
 - Min Temp  : 43 'c
 - Max Temp  : 66 'c
 - log       : /root/dietpi-config_stress.log
```

**Comment by DeviantEng** [comment]
Will be testing eMMC with this board early next week.

**Comment by BryanSmithDev** [comment]
Is 3.5mm audio a known issue? I get nothing but noise from it. However I am running video out HDMI so might that be the issue? HDMI claiming the audio over 3.5mm? I have selected 3.5mm in diet-pi config. I am on v156 however. The index issues that are fixed via v157 might have fixed this.

EDIT: Tried v157. Still no audio.

**Comment by Fourdee** [comment]
@BryanSmithDev 

> EDIT: Tried v157. Still no audio.

Thanks 👍  looks like the audio cards/devices have changed since last kernel.
```
hw:0,0 = HDMI
hw:1,0 = 3.5mm
```

Resolved for v158

**Comment by Fourdee** [comment]
<img width="672" alt="rock64dp" src="https://user-images.githubusercontent.com/7077026/32147130-edd17bf4-bcd9-11e7-9fba-ae035d49769a.png">

**Comment by Fourdee** [comment]
Live on http://dietpi.com , with known outstanding issue with audio which will be patched in v158: https://github.com/Fourdee/DietPi/issues/1102#issuecomment-340279988

**Comment by douglasmiranda** [comment]
I'm trying to run on my Rock64, but everytime dietpi-update runs I get the error: 

insufficient space to run rootfs

(I'm using Etcher to flash the sd card)

**Comment by molemantis** [comment]
You need to resize your root partition to use all available disk space. 

Here are the basic commands I used: 

gdisk /dev/mmcblk1
w 
Y

fdisk /dev/mmcblk1
d
choose / partition

n
choose / partition 
w

partprobe
resize2fs /dev/mmcblk1p7 (7 being / )

**Comment by douglasmiranda** [comment]
Great! Thanks xD

**Comment by xnathanh** [comment]
@molemantis @douglasmiranda i got same things 

insufficient space to run rootfs
(I'm using Etcher to flash the sd card)

but i try to resize root partition,doesn't work,could you send more detail of resize root partition script?

**Comment by Fourdee** [comment]
Reference:
https://github.com/Fourdee/DietPi/issues/1333#issuecomment-353661049

**Comment by darthyoh** [comment]
Hi !
I'm interested in getting a rock 64 (powered by dietpi)
First, thanks for the job done with it.
I just have a question : one of the reasons i'm interested with it is the emmc module to increase transfert rate. I imagine installing dietpi on a emmc module. Do you think this process http://dietpi.com/phpbb/viewtopic.php?f=8&t=980 can be applied to the rock 64 board ?

**Comment by ambient-home-systems** [comment]
The latest v156 image hangs on first boot. Anyone else experiencing this? SD card works fine with other Debian images, but can't get DietPi to boot. Any thoughts?

**Comment by Fourdee** [comment]
@joshuamallow 

Hi,

Please try the v6.0 RC image:
http://dietpi.com/downloads/testing/v6.0/DietPi_Rock64-ARMv8-Stretch.7z

**Comment by ambient-home-systems** [comment]
Can you update the v6.0 RC image? The compression is corrupt.

**Comment by Fourdee** [comment]
@joshuamallow 

> Can you update the v6.0 RC image? The compression is corrupt.

Confirmed, apologies, thanks for letting us know 👍 

Image has been re-compressed and uploaded:
http://dietpi.com/downloads/testing/v6.0/DietPi_Rock64-ARMv8-Stretch.7z

![image](https://user-images.githubusercontent.com/7077026/35475473-fb98a380-0396-11e8-900b-d83e30b132e8.png)

**Comment by ambient-home-systems** [comment]
Thanks!

Working great...no issues so far. Is this going to be the final version once v6 goes to production?

**Comment by Fourdee** [comment]
@joshuamallow 

Yep. There will be a minor ```dietpi-update``` later today, to bring it up to v6.0 release.

**Comment by ViRb3** [comment]
@Fourdee the latest image fails to boot on a Rock64 1GB board. I believe this may be related to: https://github.com/armbian/build/commit/475f0cbd8700db23d882faca891f9c7196e824c0
I never managed to boot Android or Armbian either.
