### ISSUE TITLE
Software Request: Radicale (A Free and Open-Source CalDAV and CardDAV Server)

### ISSUE THREAD

**Issue by pidiet** [MichaIng/DietPi#1108]
# Radicale

**A Free and Open-Source CalDAV and CardDAV Server**

## About Radicale

Radicale is a small but powerful CalDAV (calendars, todo-lists) and CardDAV (contacts) server, that:

>     Shares calendars through CalDAV, WebDAV and HTTP.
>     Shares contacts through CardDAV, WebDAV and HTTP.
>     Supports events, todos, journal entries and business cards.
>     Works out-of-the-box, no installation nor configuration required.
>     Can warn users on concurrent editing.
>     Can limit access by authentication.
>     Can secure connections.
>     Works with many CalDAV and CardDAV clients.
>     Is GPLv3-licensed free software. 

http://radicale.org/

**Comment by kaffeekanne** [comment]
Is radicale still considered? Development of Baikal is halted, and radicale seems to be the alternative with low resources needed. #1107

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by pedrom34** [comment]
I'd love to see radicale in dietpi-software instead of baikal.

**Comment by caribou-snake** [comment]
please add Radicale to dietpi

**Comment by pedrom34** [comment]
Well, I looked around a bit, and there's a package in debian. So with 
``shell
apt-get install radicale``
I made it work.

**Comment by baldpitter** [comment]
Sure, installing the debian package is an option. However, I too think that dietpi should support radicale natively. That would be a great addition!

**Comment by STPKITT** [comment]
I can only agree. While Baikal is back into development Radicale should be offered as a more slim & robust alternative since it works without needing a database.

**Comment by iraklis10** [comment]
Another vote for radicale
