### ISSUE TITLE
OrangePi Zero 2Plus H5 boot hang

### ISSUE THREAD

**Issue by jiangyanfeng** [MichaIng/DietPi#1110]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Expected behaviour:
boot successfuly

#### Actual behaviour:
boot hang at "fuse init (API version 7.26)" and a few minutes later, "armbian GNU/Linux 8 DietPi tty1", and still cannot login 

#### Steps to reproduce:
1、download and uncompress DietPi_v150_OrangePiZero2PlusH5-arm64-(Jessie).img from dietpi.com
2、format the tf card (the img file has been check the hash value)
3、write DietPi_v150_OrangePiZero2PlusH5-arm64-(Jessie).img to the tf card
4、boot the OrangePi Zero 2Plus H5 from tf

**Comment by Fourdee** [comment]
@jiangyanfeng 

Thanks for the report 👍 

We'll check.

**Comment by jiangyanfeng** [comment]
I found a error message in the boot log: 

systemd[1]: Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.server failed to load: No such file or directory.

**Comment by jiangyanfeng** [comment]
I take a photo for the boot screen:
http://www.donghootech.com/ueditor/php/upload/image/20170820/1503284747878241.jpg

**Comment by Fourdee** [comment]
@jiangyanfeng 
> display-manager.service

Thats not one of our services, can you check status?

```
systemctl status display-manager.service -l
```

**Comment by jiangyanfeng** [comment]
@Fourdee As above said, I cannot boot into console cmd line, so I cannot run the cmd to check the service status. But I think the display-manager.service is not the reason cause boot hang.

**Comment by Fourdee** [comment]
> boot hang at "fuse init (API version 7.26)" 

🈴 Confirmed (10+ mins). Occurs after apt-get upgrade (kernel upgrade)

**Comment by Fourdee** [comment]
Moved out of milestone, this is a kernel related issue (we use ARMbian) outside of our control.

**Comment by Fourdee** [comment]
Closing as OPi support has been dropped.
