### ISSUE TITLE
DietPi-Software | OPENHAB2

### ISSUE THREAD

**Issue by Elluminatus** [MichaIng/DietPi#1117]
[http://docs.openhab.org/index.html](url)

Homeautomation, cool piece of software

**Comment by R1CH-T** [comment]
[I requested this quite a while ago](https://github.com/Fourdee/DietPi/issues/210) and think that there are several reasons for this not having been added, so far. These might include:

1. The complexity of the task of creating the installer.
2. The rate of change in openhab development and the amount of issues arising from the change to version 2.
3. Not enough interest from DietPi users.
4. Not enough [time and money](https://github.com/Fourdee/DietPi/issues/1100) for @Fourdee to pursue this up to now.

I'm all for adding this to DietPi, but completely understand why this might be a difficult task.

You might try bribing Dan by donating some cash to the war-chest and offering help with the coding and/or testing. I've found that this has helped in the past :wink:

You might want to check out the [latest development milestone](https://github.com/Fourdee/DietPi/milestone/58) to see what's being added to DietPi in the next release.

Something you might be interested in is the [addition](https://github.com/Fourdee/DietPi/pull/1087) of [Home Assistant](https://home-assistant.io/). It has been [committed for the next release](https://github.com/Fourdee/DietPi/milestone/58?closed=1).

> Homeautomation, cool piece of software

I agree.

Rich.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
