### ISSUE TITLE
Question: Automated installation 

### ISSUE THREAD

**Issue by douglasmiranda** [MichaIng/DietPi#1118]
Is there a way to automatize the installation? 

If I want to build a cluster, and DietPi needs to be installed in several boards, how should I proceed?

**Comment by R1CH-T** [comment]
Hi,

Take a look at https://github.com/Fourdee/DietPi/blob/master/dietpi.txt.

This file can be modified to automate various installation options, software selections etc.

It should be modified after you write DietPi to the SD card(s) and before you insert it into your board(s) and boot up.

It can be found on the SD card's /boot partition.

Hope this helps.

**Comment by douglasmiranda** [comment]
Awesome!!

(But shame on me, how could I not see that file..)

**Comment by R1CH-T** [comment]
Cool!

Post your links and experiences to the [DietPi Forums](http://dietpi.com/phpbb/viewforum.php?f=5).

> (But shame on me, how could I not see that file..)

It happens to all of us. I expect that you read the relevant instructions early on and forgot the bits you needed to know, several hours later!

**Comment by douglasmiranda** [comment]
I think my username wasn't approved on the DietPi Forum yet =/ douglasmirandasilva@gmail.com

**Comment by Fourdee** [comment]
@douglasmiranda 
Apologies, unable to find user with your email address. Most likely triggered as spam. 

Please can you recreate the account and provide username. I'll activate.

**Comment by MichaIng** [comment]
Close, as question was answered.
