### ISSUE TITLE
Unstable behavior when using wifi on 2.4Ghz and unable to boot OS on 5ghz

### ISSUE THREAD

**Issue by qpens** [MichaIng/DietPi#1125]
#### Required Information:
- DietPi Version | 155
- SBC Device Odroid C2
- Power supply used 5v 4A
- SD card used Lexar
-Wifi Edimax
- Distro (EG: Jessie) | Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 

GNU/Linux

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Actual behaviour:
Its not connecting to wifi on freshly instaled OS on sdcard. With eth connection I managed to start wifi on 2.4ghz but whole thing was throttling couldn't put commands in putty wery long time to respond after connecting to 5ghz I couldn't boot to OS I solved that problem by removing wifi and connecting eth

That's what happened after connection to 5ghz network

![img_20170831_004453](https://user-images.githubusercontent.com/30188485/29900172-e823a018-8de7-11e7-9c1f-e5da8404170b.jpg)

**Comment by Fourdee** [comment]
Marking as closed due to:
- inactivity
- Pre DietPi v6.x
