### ISSUE TITLE
Chromium Without desktop Fail start

### ISSUE THREAD

**Issue by qpens** [MichaIng/DietPi#1127]
#### Required Information:
- DietPi Version | 155
- SBC Device oDroid C2
- Power supply used 5v 4A 
- SD card used Lexar
- Distro (EG: Jessie) | Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux
-LCD Waveshare 10.1 1280×800, IPS

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Expected behaviour:
autostart chromium

#### Actual behaviour:
Start fail 

![img_20170901_125329](https://user-images.githubusercontent.com/30188485/29969015-3ebabd6a-8f16-11e7-9917-9ed4ef965307.jpg)
![img_20170901_125359](https://user-images.githubusercontent.com/30188485/29969026-433c9606-8f16-11e7-957f-01a0df2a90f6.jpg)
![img_20170901_125342](https://user-images.githubusercontent.com/30188485/29969028-44b56b34-8f16-11e7-8533-ff31c6362f09.jpg)

**Comment by Invictaz** [comment]
Have the same issues on the x86_64 test build. Might be possible that this is GPU related? Or it displays the Chromium screen on the other ( side of) the display.

**Comment by Fourdee** [comment]
@qpens 
Thanks for the report 👍 

I've personally only tested this with RPi. Does Chromium function correctly from Desktop launch?

**Comment by qpens** [comment]
I didn't Install desktop I'm using only dietpi with octoprint just to run my 3d printer. I'm trying to set this thing so only chromium with octoprint will be showing up on start.

**Comment by Fourdee** [comment]
@qpens 

Unable to replicate on a fresh install with 720P and 1080P. Chromium displays correctly (albeit, not full screen). May be limited to your monitor. Try changing the resolution in ```dietpi-config``` > display options.

Desktop is installed by default with Chromium. Try ```dietpi-autostart``` and changing to desktop, see if Chromium loads correctly.

**Comment by qpens** [comment]
Waveshare instruction says put 
max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 1280 800 60 6 000
hdmi_drive=1

in config.txt
but that doesn't work I checked on UART terminal and its still loading 720p I try to change the resolution in dietpi-config  but there is only 720p and 1080p closest to my screen checked 1080p but it crashes the screen
I edit boot.ini and changed 720p to 800p but that doesn't work
How to force dietpi to use waveshare config?

**Comment by qpens** [comment]
I reinstalled the OS and screen was working fine from v144 to V155 
![img_20170902_194948](https://user-images.githubusercontent.com/30188485/29998258-7c645604-901e-11e7-8b2c-f3587e37090d.jpg)

after installing Octoprint screen got funny

![img_20170902_202739](https://user-images.githubusercontent.com/30188485/29998296-1ace5100-901f-11e7-95b8-6b649c52f5e4.jpg)

**Comment by Fourdee** [comment]
@qpens 

> Waveshare instruction says put
max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 1280 800 60 6 000
hdmi_drive=1
in config.txt
but that doesn't work I checked on UART terminal and its still loading 720p

Those options are for RPi, wont have any effect on Odroid C2. Take a look at ```/DietPi/boot.ini```, there is a few HDMI options in there that may work.

**Comment by qpens** [comment]
Before starting kernel

![img_20170903_223826](https://user-images.githubusercontent.com/30188485/30006794-ef8232b6-90f8-11e7-9356-f233ce26dea9.jpg)

Desktop

![img_20170903_223655](https://user-images.githubusercontent.com/30188485/30006811-482f50ec-90f9-11e7-89d5-30170bac9047.jpg)


changes in boot.ini didn't help


chromium still faill ;(

**Comment by qpens** [comment]
Problem with screen Fixed

In config.txt
Block both framebuffer 
 
boot.ini 
 change resolution from me it was 1280x800p60hz
