### ISSUE TITLE
wifi configuration fails when key contains = character

### ISSUE THREAD

**Issue by gretel** [MichaIng/DietPi#1132]
#### Required Information:
- DietPi Version | 1.55
- SBC Device | Rpi Zero W
- Power supply used | industrial
- SD card used | samsung 16gb
- Distro | jessie

#### Expected behaviour:
wifi should connect
#### Actual behaviour:
various errors messasges related to `wlan0` appearing - wlan not functional

#### Steps to reproduce:
set a `Wifi_KEY` containing `"` in `dietpi.txt`

**Comment by k-plan** [comment]
> In the first place, the choice of a secure WPA network key (also known as a passphrase or a pre-shared key) should be selected during the PSK process. This should use the maximum key length of 63 characters.  ...
> However, special characters in the password may cause problems with some operating systems, especially with Apple iOS. Particular caution is required with special characters from the international language area (eg ü, ö, ä ,ß or also § ). Same for keys contains characters which are not permitted '~!#$%^&@()=[]}{\|;:'<>/ ° " $ € ł µ ² ³ ` ? and so on.  Depending on the operating system ( Microsoft Windows , Mac OS X , Unix ), they are encoded differently and are not compatible with each other.

BTW: quotation marks in configs, scritps and batch files have a specific importance (e.g. can mark start and ending of a value). Especially if this files will be parsed via bash scripts by `sed `, `awk` , `gwk` , etc.

**Comment by gretel** [comment]
@k-plan i was not referring to any wifi-related issue in general, and i am quite aware of the limitations, thanks for pointing that out. `"` is a valid character for WPA keys.
the documentation nor inline comments in `dietpi.txt` mention any restrictions in regards to not being allowed to use the `=` character with dietpi.
i consider this as a bug because it would require users to change existing access point configuration(s) and all nodes connected to have them join a '`=`' free setup - which is quite a hassle, honestly - and not what i consider to be a lightweight approach.
the exception is dietpi - i guess there is no or proper string escape in place. the tools like `sed` etc. work all fine if used properly.

**Comment by hippytyre** [comment]
I think I'm having the same problem. The WIFI SSID I'm trying to connect my Pi Zero W to is -=word=- I've tried to put it into quotation marks but this doesn't seem to help. Has this issue been looked at or does anyone have a workaround? Changing the SSID is not an option I'm afraid.

**Comment by Fourdee** [comment]
@hippytyre 

Hi,

Try escaping each ```\=``` entry, when entering the SSID:
```-\=word\=-```

Bug/limitation, unsure at the moment. Depends on results of above ^^

**Comment by Fourdee** [comment]
Outdated.
