### ISSUE TITLE
Chromium not fully shown on the screen

### ISSUE THREAD

**Issue by qpens** [MichaIng/DietPi#1137]
#### Required Information:
- DietPi Version | 155
- SBC Device Odroid C2
- Power supply used 5v 4A
- SD card used Lexar
- Distro (EG: Jessie) |Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux
-Screen Waveshare 10.1 1280x800

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Expected behaviour:
chromium on full screen
#### Actual behaviour:
![img_20170907_003422](https://user-images.githubusercontent.com/30188485/30139226-77435a82-9364-11e7-8cbf-696219663094.jpg)

**Comment by Fourdee** [comment]
Marking as closed due to <v6.0.
