### ISSUE TITLE
dietpi orange pi pc module load

### ISSUE THREAD

**Issue by keiser1080** [MichaIng/DietPi#115]
Hi,

there are some problem with the module loading

```
root@DietPi:~# lsmod
Module                  Size  Used by
root@DietPi:~# cat /etc/modules
#Orange Pi -------------
#For SATA Support
sw_ahci_platform

#Display and GPU
lcd
hdmi
ump
disp
mali
mali_drm
8192cu
8188eu
8189es
gpio-sunxi


#bt
btusb
root@DietPi:~# modprobe btusb
modprobe: ERROR: could not insert 'btusb': Exec format error
root@DietPi:~# modprobe -f btusb
```

**Comment by Fourdee** [comment]
Yep its a known issue. modprobe and lsmod appear to be dead and empty.

For the Orange Pi we are using a modified version of http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=342 image as the base. The original image  by loboris also has the same issues.

**Comment by keiser1080** [comment]
did you use the same kernel?
i  try to found some hep http://www.orangepi.org/orangepibbsen/forum.php?mod=redirect&goto=findpost&ptid=342&pid=6496&fromuid=135990

**Comment by Fourdee** [comment]
Yes, using the same kernel.

loboris uploads new kernels on https://mega.nz/#F!wh8l2BjK!OBep3nMldBletvNNwkH2Jg , might be worth trying the latest one. Its down for me at the moment, i'll try again tomorrow.

**Comment by keiser1080** [comment]
the kernel is hosted somewhere else see the attached script.
[update_kernel.sh.txt](https://github.com/Fourdee/DietPi/files/38185/update_kernel.sh.txt)

**Comment by Fourdee** [comment]
Just ran the script. Modules are now working :+1: 

> root@DietPi:~# lsmod
> Module                  Size  Used by
> gpio_sunxi              8233  0
> 8189es                901572  0
> 8188eu                915632  0

You can do the following:

```
wget https://raw.githubusercontent.com/loboris/OrangePi-BuildLinux/master/update_kernel.sh
chmod +x update_kernel.sh
./update_kernel.sh
```

**Comment by Fourdee** [comment]
For DietPi v102:
I've added the update script to dietpi-config > Advanced > update firmware.

**Comment by keiser1080** [comment]
Thanks!

I have to run the script? Or you will push the update?

**Comment by Fourdee** [comment]
Yes, you can run the update_kernel.sh script on your system now if you like.

I will also add to the DietPi update system for v102.

**Comment by keiser1080** [comment]
thanks Dan for your help.
And for dietpi !!!

**Comment by keiser1080** [comment]
feedback:
script it's working but return small error
cp: impossible d'évaluer « /boot/uImage »: Aucun fichier ou dossier de ce type
cp: impossible d'évaluer « /boot/script.bin »: Aucun fichier ou dossier de ce type

don't found /boot/uImage &  /boot/script.bin

But everything is working 

thanks again
