### ISSUE TITLE
DietPi-Software | Locate

### ISSUE THREAD

**Issue by HamBone41801** [MichaIng/DietPi#1153]
The locate command searches for and displays the absolute location of and file matching the user's input via command line.  It uses an address database that is updated daily (or by the use of `sudo updatedb`).

**Comment by Fourdee** [comment]
@HamBone41801 

Hi,

You can also use the command ```find```, that doesn't require a database or additional daily processing, pre-installed with DietPi:

To find a file with name ```bob``` on rootfs:
```
find / -name 'bob'
```

To find a file with name ```file``` and any extension on rootfs:
```
find / -name 'file.*'
```

To find a ```.html``` file in ```/var/www```
```
find /var/www -name '*.html'
```
