### ISSUE TITLE
Stretch | MotionEye fails to install (deps)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1155]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=986&start=30#p8818

**Comment by MichaIng** [comment]
dietpi-software downloads/expects the "jessie" version here with related older library dependencies: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L6376-L6405

On official raspbian stretch repo there is "motion" available, auto installing the mentioned newer library versions as dependencies. I don't know about the python packages, but they seem to be not affected anyway and could be installed afterwards.

**Comment by Fourdee** [comment]
@MichaIng 

> On official raspbian stretch repo there is "motion" available

👍 
Confirmed, Raspbian and Debian Stretch :
https://packages.debian.org/stretch/motion
```
root@DietPi:~# apt-cache search motion | grep ^motion
motion - V4L capture program supporting motion detection
```

>  Mr-Dave released this on Oct 25, 2016

Also looks like the motion project has stopped devolpment:
https://github.com/Motion-Project/motion/releases

So yep, for Stretch we can install via apt. Package is latest version (4.0.1)

---

```
The headers or library files could not be found for zlib
```

**Comment by Fourdee** [comment]
Ok, install fixed.

Tests:
Could be camera failure (wouldnt be the 1st time), or issue with Stretch we need to resolve:
```
root@DietPi:~# raspistill -o cam.jpg
mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:EN                                                                 OMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is instal                                                                 led correctly

root@DietPi:~# lsmod
Module                  Size  Used by
bcm2835_gpiomem         3900  0
uio_pdrv_genirq         3923  0
uio                    10396  1 uio_pdrv_genirq
fixed                   3285  0
bcm2835_v4l2           44210  0
videobuf2_vmalloc       5856  1 bcm2835_v4l2
videobuf2_memops        2009  1 videobuf2_vmalloc
videobuf2_v4l2         16949  1 bcm2835_v4l2
videobuf2_core         34090  2 bcm2835_v4l2,videobuf2_v4l2
v4l2_common             6220  1 bcm2835_v4l2
videodev              184617  4 v4l2_common,videobuf2_core,bcm2835_v4l2,videobuf                                                                 2_v4l2
media                  28334  1 videodev
ip_tables              13142  0
x_tables               20590  1 ip_tables
ipv6                  408451  18
```

**Comment by Fourdee** [comment]
Putting https://github.com/Fourdee/DietPi/issues/1155#issuecomment-336500461 down to my camera failure (this being the 2nd one lol).

Also tried:
- Jessie
- ```rpi-update``` kernel

Same issues.

As installation is now resolved, marking as closed.
