### ISSUE TITLE
Odroid C2 WiFi Fail

### ISSUE THREAD

**Issue by qpens** [MichaIng/DietPi#1156]
#### Required Information:
- DietPi Version | 156
- SBC Device Odroid C2
- Power supply used 5v 4A
- SD card used Lexar
- Wifi Edimax EW-7811Un
- Distro (EG: Jessie) | Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Expected behaviour:
After enabling and setting up wifi in dietpi.txt I should get wifi connection
#### Actual behaviour:
No IP no Connection no WiFi

![img_20170922_224850](https://user-images.githubusercontent.com/30188485/30765991-56b4d1f0-9fea-11e7-84b4-5f841a299e83.jpg)

![img_20170922_224810](https://user-images.githubusercontent.com/30188485/30765992-56d9b18c-9fea-11e7-8579-3a0dfe0a3400.jpg)

**Comment by Fourdee** [comment]
@qpens 

Thanks for the report 👍 

> After enabling and setting up wifi in dietpi.txt I should get wifi connection

Can you please confirm the ```dietpi.txt``` changes were made prior to 1st run of the device?
If you are applying these settings, after this point, it needs to be completed in ```dietpi-config```
https://github.com/Fourdee/DietPi/blob/master/dietpi.txt#L4-L8

And ```Wifi_Enabled=1``` was set in ```dietpi.txt```?

Also, please paste results of:
```
lsusb
```

**Comment by qpens** [comment]
lsusb result 

![img_20170923_223317](https://user-images.githubusercontent.com/30188485/30777300-780f94a0-a0af-11e7-88cf-e1e5c8622b5b.jpg)



On second sd card, I made fresh install with that config 

![img_20170923_220940](https://user-images.githubusercontent.com/30188485/30777266-d644160a-a0ae-11e7-96b4-4286c14bddf0.jpg)

![img_20170923_222601](https://user-images.githubusercontent.com/30188485/30777268-db1bfc56-a0ae-11e7-9870-eb449825e138.jpg)

**Comment by qpens** [comment]
I checked another card Alfa AWUS051NH on V144 works fine but after upgrade to 156 It's a fail


![img_20170924_224034](https://user-images.githubusercontent.com/30188485/30787101-7f8f1e6a-a179-11e7-8afe-f6eb6295a55a.jpg)

**Comment by qpens** [comment]
I tested both and they are working fine problem with Edimax was that this card needs to be configured with static IP on start (V144)

Alfa was working fine on V144 but after upgrade to V156 same thing happen

**Comment by Fourdee** [comment]
Marking as closed due to outdated.
