### ISSUE TITLE
Letsencrypt supports Free Noip.com Dynamic DNS

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1159]
Letsencrypt currently/now supports the free version of noip.com's DDNS service -- so it seems like we can remove the warning from dietpi.

The only thing I think that needs to be done is to change the text on the installer and on the webpage to remove the warning it doesn't work.  It might even be a good idea to just change it to it DOES work - since it has been saying otherwise.

I've successfully used dietpi-letsencrypt to grab a cert for a noip.com free ddns address so I know it works.

If I get some time I'll try to hunt down the changes and submit them but it seems it might be quicker for someone to make the changes who knows where in the code the text is.

**Comment by Fourdee** [comment]
@techdabbler 

> Letsencrypt currently/now supports the free version of noip.com's DDNS service

Excellent, thanks for letting us know.

> If I get some time I'll try to hunt down the changes and submit them but it seems it might be quicker for someone to make the changes who knows where in the code the text is.

I'll add it to my list aswell.

**Comment by ghost** [comment]
I got to digging tonight... and thinking.  I don't believe there is any code that needs changing or editing. It seems the only notation to noip.com free's service not working is just in the certbot wiki entry.

**Comment by jbz-dev** [comment]
From what I know Letsencrypt supports noip free accounts for a while. Always been using DietPi with free NOIP for a year :)

**Comment by ghost** [comment]
@Bridouz Yup. It seems its been a while. I just started reading the documentation first (GASP!) and was happy to dsicover through some googling they are supported now.  I'd like to save the other 2 people who read the documentation before they try it some time. HA!

**Comment by MichaIng** [comment]
Also the hint, that nginx is not supportet is obsolete. I will take care of it together with the other certbot rework: https://github.com/Fourdee/DietPi/issues/734

**Comment by MichaIng** [comment]
Hmm, I think I just fixed the Nginx support hint, but can't find something about noip any more. Was this already fixed before?

**Comment by MichaIng** [comment]
I think this is obsolete, no wrong warning any more that I can find. Will close.
