### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by Hestonian** [MichaIng/DietPi#1161]
#### Required Information:
- DietPi Version | 156
- SBC Device RPi B+
- Power supply used 5v 2A Anker
- SD card used Kingston 32GB
- Distro Jessie | Linux Gateway 4.9.40+ armv6l GNU/Linux

#### Additional Information (if applicable):
- Software PiHole installation
Post upgrade from v155 to v156, pi-hole stopped working as DNS server resulting in URL requests from devices within network timing out when accessing external sites.  Tried uninstall and re-install of the Pi-Hole through DietPi-Software, resulting in the following error during install:
 #               processing | D i e t  P i             #

 [Info] Apt-get is processing, please wait...

Segmentation fault
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'bluetooth' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)
 [Failed] The apt cache may be corrupt, apt mirror offline, or you have held broken packages. DietPi-Software will now exit.

 [Info] Apt Log:
Segmentation fault
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'bluetooth' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)

 [Info] Please try:
 [Info] - Fixing apt package errors with 'apt-get install -f'
 [Info] - Change apt mirror: 'dietpi-config' > 'Networking: NAS/MISC' > 'Apt Mirror'
 [Info] - Clear and refresh apt 'apt-get update'
 [Info] - If problems persist, please create a Git ticket so DietPi can investigate the issue:
 - https://github.com/Fourdee/DietPi/issues

Ran "apt-get install -f" followed by "apt-get autoremove" to get the following error:

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libpci3
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.
root@gateway:~# apt-get autoremove
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libpci3
0 upgraded, 0 newly installed, 1 to remove and 32 not upgraded.
After this operation, 68.6 kB disk space will be freed.
Do you want to continue? [Y/n]
Segmentation fault
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'bluetooth' is missing final newline
E: Sub-process /usr/bin/dpkg returned an error code (2)

 
- Can this issue be replicated on a fresh installation of DietPi?  - Not verified yet.

#### Expected behaviour:
The PiHole install should have completed without failure which is not what is happening.  How to revert back to v155 to test if this is a DietPi-Software incompatibility for the utility?

#### Actual behaviour:
Apt-get errors preventing PiHole from being re-installed

#### Steps to reproduce:
Uninstall PiHole and re-install in version v156.

#### Did you submit a ```dietpi-bugreport```?
No

#### Extra details:
Network access via Ethernet.

Verified that lighttpd service has not started.
root@gateway:~# service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-29 11:49:03 BST; 1h 26min ago
 Main PID: 25909 (code=exited, status=255)

Sep 29 11:49:03 gateway systemd[1]: Started Lighttpd Daemon.
Sep 29 11:49:03 gateway lighttpd[25909]: Segmentation fault
Sep 29 11:49:03 gateway lighttpd[25909]: Segmentation fault
Sep 29 11:49:03 gateway lighttpd[25909]: Segmentation fault
Sep 29 11:49:03 gateway lighttpd[25909]: 2017-09-29 11:49:03: (network.c.409) can't bind to port:  80 Address already in use
Sep 29 11:49:03 gateway systemd[1]: lighttpd.service: main process exited, code=exited, status=255/n/a
Sep 29 11:49:03 gateway systemd[1]: Unit lighttpd.service entered failed state.
Sep 29 11:52:58 gateway systemd[1]: Stopped Lighttpd Daemon.
Sep 29 12:04:16 gateway systemd[1]: Stopped Lighttpd Daemon.
Sep 29 12:06:25 gateway systemd[1]: Stopped Lighttpd Daemon.

**Comment by Fourdee** [comment]
@Hestonian 

Thanks for the report 👍 

> Segmentation fault

Hardware failure, PSU instability, and/or SD card insufficient. Not a DietPi specific issue.

Please try 
- re-writing the DietPi image to a well branded SD card (EG: Sandisk)
- Using official RPi PSU (5v/2.5A)

**Comment by Hestonian** [comment]
OK.  But do you have a process to revert to an earlier version of DietPi i.e. so I can revert to v 155 to test?

**Comment by Fourdee** [comment]
@Hestonian 
> OK. But do you have a process to revert to an earlier version of DietPi i.e. so I can revert to v 155 to test?

We cannot replicate segmentation faults from v151 > v156. There is nothing wrong with the v155 > v156 upgrade. The issue lies with your hardware.

As your current installation is experiencing seg faults, it would not be of any benefit to downgrade on a unstable system. The issues will still be there.

Please look at resolving your hardware setup, ensuring stable operation of the RPi, by using official PSU and well branded SD card (eg: sandisk).

I'll mark this as closed.

**Comment by Invictaz** [comment]
Unplugging the Pi with write actions still running (since the RAM is also on the disk) is a possible explanation.

**Comment by Hestonian** [comment]
I had PiHole running on the same hardware/power supply since v148 so I had a strong basis for investigation.   SD card corruption during the upgrade from 155 to 156 write is a possibility.    

Appreciate that the issue is marked closed so I'll try re-install.   Thanks.
