### ISSUE TITLE
NanoPi m1 support linux kernel 3.8+, need use docker image

### ISSUE THREAD

**Issue by peter850421** [MichaIng/DietPi#1162]
## Creating a bug report/issue:
Nanopi M1 DietPi is still under kernel 3.4 ! 

I know Nanopi Neo  has below image can run Docker.  However, when NanoPi M1 uses this image , M1's only one of three USB ports can be used.  Can somebody help to update the image or change the Neo image to adapt to M1 ?

http://dietpi.com/downloads/images/no_release/(NR_4.x)_DietPi_NanoPiNEO-armv7-(Jessie).7z

**Comment by Fourdee** [comment]
Marking as closed, due to:
- We only support/provide images based on the official available image.
- The kernel version installed, is dependent on the above.
- We do not provide additional kernels, outside of the above.
