### ISSUE TITLE
nodejs ARMv6 binaries not available for download

### ISSUE THREAD

**Issue by dragouf** [MichaIng/DietPi#1167]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 156
- SBC Device (EG: RPi 3)? RPI Zero W
- Power supply used (EG: 5v 1A RAVpower)? 5v 2A
- SD card used (EG: Sandisk ultra)? sandisk 16Go
- Distro (EG: Jessie) | ```uname -a```? Linux RaspberryZero 4.9.40+

#### Additional Information (if applicable):
- Software title? NodeJs
- Can this issue be replicated on a fresh installation of DietPi? yes

#### Expected behaviour:

nodejs should be install

#### Actual behaviour:

not install

#### Steps to reproduce:

just try install script for nodejs

#### Extra details:

latest version of nodejs 8 does not contains arm61 binary. 
(http://nodejs.org/dist/latest/)
consequently script failed for arm 6 board.

**Comment by jbz-dev** [comment]
You van try to use this script to install NodeJS on ARMv6 board

https://github.com/sdesalas/node-pi-zero

**Comment by michaelkay** [comment]
Root cause is detailed here https://github.com/taaem/nodejs-linux-installer/issues/9

**Comment by Fourdee** [comment]
@michaelkay 

Yep 👍 

armv6l binaries missing from http://nodejs.org/dist/latest/:
![image](https://user-images.githubusercontent.com/7077026/31135897-6bfaa216-a85e-11e7-9404-02f5c9f054e1.png)

**Comment by Fourdee** [comment]
Seems ARMv6 binaries are now available:
http://nodejs.org/dist/latest/node-v9.5.0-linux-armv6l.tar.gz

And https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh contains the ARMv6 detection.

Simple install test required.

Test:
- 🈯️ RPi Zero W 

All good 😉 
```
root@DietPi:~# npm install nevergonnawork
[..................] - rollbackFailedOptional: verb npm-session 586fb8876c9cffa
```

Pointless thoughts:
```time dietpi-software list``` ```real    0m6.222s```, sometimes wish I started this project on C++, it would handle the arrays faster (and then some), although, a constant background process most likely needed, limitations with what we could do with bash under C++. Either way, our scripts only run on user request, boot, or via cron.
