### ISSUE TITLE
[Question] | dietpi-update -y

### ISSUE THREAD

**Issue by maweki** [MichaIng/DietPi#1170]
It would be nice to have a non-interactive way to update dietpi. I have a lot of machines organized via ansible and it would be nice to bring out the updates in a concerted way.

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-update#L18
```
dietpi-update 1
```

**Comment by port19x** [comment]
#6486
