### ISSUE TITLE
[Question] | Replacing old kernel version 3.10.38 for DietPi_SparkySBC-armv7-(Stretch).7z image

### ISSUE THREAD

**Issue by kotamotov** [MichaIng/DietPi#1176]
Audiophiles are waiting for new kernel version for SparkySBC to connect new DACs.
 Is it possible to replace old kernel version 3.10.38 for DietPi_SparkySBC-armv7-(Stretch).7z image?

**Comment by Fourdee** [comment]
@kotamotov 
Hi,

Unfortunately, upgrading the kernel is a large comminuty effort and a huge undertaking, which also relies on the ARM manufacture's willingness to make it possible.

I believe currently, Allo are investigating this, but no ETA yet.

**Comment by Fourdee** [comment]
Outdated, no update from manufacture. Marking as closed.
