### ISSUE TITLE
DietPi-Software | DLNA audio render/endpoint

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1183]
> http://blog.scphillips.com/posts/2014/05/playing-music-on-a-raspberry-pi-using-upnp-and-dlna-v3/ | https://github.com/hzeller/gmrender-resurrect/blob/master/INSTALL.md

**Comment by Fourdee** [comment]
Binaries compiled and hosted on dietpi.com

Online doc:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=9012#p9012

**Comment by Fourdee** [comment]
Note to self:
- 🈯️ Ensure ALSA stream is free, when playback is not active.

**Comment by Fourdee** [comment]
Installed by default for all Allo GUI images, during v157 update.
Also available in ```dietpi-software``` for SSH/Term users

**Comment by mpember** [comment]
Why did the update install this software on a system which previously didn't have it?

**Comment by Fourdee** [comment]
@mpember 

Hi,

GMrender will be installed on all Allo GUI systems, to match the current version of Allo GUI interface and its pre-req software.

You can disable the service in the web interface, if not required.
