### ISSUE TITLE
DietPi-Setup | Inital Setup via Wifi-Hotspot (dietpi-wifi)

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1185]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=2310
>
>
> ![image](https://user-images.githubusercontent.com/17237601/31384899-44432dde-adc1-11e7-8c01-8243689fc2c9.png)

**Comment by hoobatoo** [comment]
[DietPi Forum Post](http://dietpi.com/phpbb/viewtopic.php?f=12&t=2310#p10305)

I wonder if this wifi autohotspot could be incorporated somewhat easier into dietpi? http://www.raspberryconnect.com/network ... et-routing

The service calls a script that checks for presence of the SSID entered into wpa_supplicant.conf, and if not present then starts hostapd and dnsmasq and creates a hotspot. It presently requires mucking about in /etc/network/interfaces and replacing the entire contents with the following. 

It does not appear to work as is.

**Comment by Fourdee** [comment]
Marking as closed.

Although i'd love to have this implemented, with lack of time and higher priority tickets, not possible currently with lack of interest.
