### ISSUE TITLE
DietPi-Software | BubbleUPnP Server

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1188]
> https://www.computeraudiophile.com/forums/topic/32132-allo-sparky-usbridge/?do=findComment&comment=728276

```
#jre/jdk
dietpi-software install 8

wget https://launchpad.net/~bubbleguuum/+archive/bubbleupnpserver/+files/bubbleupnpserver_0.9-2_all.deb
dpkg -i bubbleupnpserver_0.9-2_all.deb
```

NB: requires package ```upstart-job```, not available in Stretch on RPi.

**Comment by Heroldgray** [comment]
Fantastic if you manage to add BubbleUPnP Server support (DietPi and Allo Web GUI).

**Comment by Fourdee** [comment]
Moved back to planning, to focus on Stretch and outstanding issues.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
