### ISSUE TITLE
DietPi-Software | raspotify (Spotify connect client)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1189]
> https://www.computeraudiophile.com/forums/topic/32132-allo-sparky-usbridge/?do=findComment&comment=728214

**Comment by Fourdee** [comment]
Install method: http://dietpi.com/phpbb/viewtopic.php?f=9&t=2352#p9167
```
# Install curl and https apt transport
sudo apt-get -y install curl apt-transport-https

# Add repo and its GPG key
curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo apt-key add -v -
echo 'deb https://dtcooper.github.io/raspotify jessie main' | sudo tee /etc/apt/sources.list.d/raspotify.list

# Install package
sudo apt-get update
sudo apt-get -y install raspotify
```

**Comment by Fourdee** [comment]
Unable to test playback as I lack spotify premium account, and, trial has already been used previously.
Service is running, install/uninstall functional.

**Comment by Fourdee** [comment]
online doc:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=9368#p9368

**Comment by Fourdee** [comment]
Stretch repo not available, will use jessie for all distros:
```
Err https://dtcooper.github.io stretch/main armhf Packages
  HttpError404
```

**Comment by Fourdee** [comment]
Marking as completed, however, unable to test audio playback at this time: https://github.com/Fourdee/DietPi/issues/1189#issuecomment-340273204

**Comment by georgegeorgetj** [comment]
Has this been abandoned for DietPi? I can't get to install Raspotify - both the automatic installer as well as the manual fail.

**Comment by Joulinar** [comment]
Hi,

Many thanks for your report. What kind of device you are running? It should be still working as I did some test installation last week without issues.

**Comment by georgegeorgetj** [comment]
Hi! It's a Nanopi board.I think it was you that we were talking over at the forum Joulinar. 
I'm still trying to get around with it and haven't found a working solution. 
Which method? The automatic installer or the manual? The automatic installer reports that the script is for the Raspberry Pi only. Shouldn't it be a more universal installation since it is through the DietPi image? I have compiled a DietPi image for the NeoPlus2.

**Comment by Joulinar** [comment]
Yes it's me again. I guess there is a misunderstanding what DietPi is and how it's working. DietPi themselves isn't an own OS or Debian system. DietPi is a set of scripts on top of a Debian base image. Means for RPi systems the base image is Raspbian Lite. For other systems it's Armbian for example. And your device is not running Raspbian Lite as base image. Therefore Raspotify will not work in your device as long as you are not able to get Raspbian Lite running. Next to that, DietPi is not developing the Rasporify installation script. We simply use the stuff provided by Raspotify.

**Comment by georgegeorgetj** [comment]
I see.It's pretty clear I have no luck with this. Thank you so much for clarifying!

**Comment by Joulinar** [comment]
Well just get a RPi board and your issue is gone :wink:

**Comment by georgegeorgetj** [comment]
I got all RPis except from RPi4. In my project there's space only for a RPiZero which Initially used but due to supporting armv6 set of instructions, I'm not able to run Roon-Bridge. :(
