### ISSUE TITLE
Waveshare32 does not work with a waveshare 4" LCD.

### ISSUE THREAD

**Issue by Darwin-II** [MichaIng/DietPi#1199]
Hello. I have been trying to use my waveshare 4" LCD with Diet Pi but it does not work properly. After installing Waveshare32 and rebooting my pi the screen shows three columns of text next to each other. There is also the secondary issue where Diet Pi freezes during the boot sequence.

I am using a Raspberry Pi 3 model B, a sandisk ultra 32GB and I have Diet Pi 157 on it.

**Comment by Fourdee** [comment]
Marking as closed:
- Outdated
- We only support the waveshare32 currently
