### ISSUE TITLE
Request | RT Kernel option

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1200]
Toggle option to enable/disable RT/Stock kernel.

RT: Real time

**Comment by sfb2** [comment]
yeah, that would be very nice..
also please a patched/advanced kernel with extended 384khz-support..
because this is missing since v154 (at my feel ;-) )

**Comment by Fourdee** [comment]
Closed due to: https://github.com/Fourdee/DietPi/issues/1378
