### ISSUE TITLE
Diet Pi not recognising external storage

### ISSUE THREAD

**Issue by Darwin-II** [MichaIng/DietPi#1204]
I recently made the switch from Raspbian to Diet Pi and I saved all my data from Raspbian on a 16GB Sandisk Ultra. Now when I plug that SD card into my Raspberry Pi using a USB SD card reader Diet Pi does not recognise it.

So when I plug my SD card reader into my Raspberry Pi the machine does not recognise it. 

When I plug it into my Raspberry Pi Zero (running Raspbian Lite) the machine does recognise my SD card.

Now for what I am using:

Raspberry Pi 3 model B,

32GB Sandisk ultra (not for file storage, Diet Pi runs of of this)

Diet Pi V157.

**Comment by Fourdee** [comment]
@Darwin-II 
Sounds like a corrupt SD card. If SD card reader + SD socket on RPi's are unable to read it.

Are you referring to a image clone > SD card, or, DietPi-UserData moved to SD card?
