### ISSUE TITLE
DietPi-Config | Typo in dietpi-config dialog

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1205]
Think you have missed write up here:

http://dietpi.com/phpbb/viewtopic.php?f=9&t=2145&p=9147#p9147

Auto size swapfile ([since v155 size is now set to "2048 - total memory"](https://github.com/Fourdee/DietPi/blob/master/CHANGELOG.txt#L87))

![171021-0002](https://user-images.githubusercontent.com/17237601/31853854-2f83194a-b690-11e7-903d-2bf1e097a781.gif)

```
Mode: Generating new swapfile
 Please wait...

 [Info] Size     = 1554 MB
 [Info] Location = /var/swap
 [Info] Deleting existing swapfile (/var/swap)

```

Nice to see, that you have fixed it in `dietpi.txt`:

```
# >> Misc Options -----------------------------------
#Size of dphys-swapfile to generate (MB)
#   0=Disabled.
Swapfile_Size=512

```
😃 

---------------------------

... and ["Ondemand" is now the default CPU governor for all devices](https://github.com/Fourdee/DietPi/blob/master/CHANGELOG.txt#L8). (recommended)

![171021-0001](https://user-images.githubusercontent.com/17237601/31854080-225be9f0-b694-11e7-9eab-633d1f84e8ad.gif)

**Comment by Fourdee** [comment]
@k-plan 

legend 👍 

Changes made :)
