### ISSUE TITLE
DietPi-System | Nanopi Neo Air WiFi (AP6212A) support

### ISSUE THREAD

**Issue by Dalto1** [MichaIng/DietPi#1209]
See this post for info :
[http://dietpi.com/phpbb/viewtopic.php?f=11&t=2205&p=9271#p9271](url)

**Comment by Fourdee** [comment]
Marking as closed due to:
- ARMbian based images dropped. 
- No official available Neo Air Debian image
- 0 installs via survey results

**Comment by troyane** [comment]
@Fourdee I'd like to mention that here are official images available:

* ARMbian -- https://www.armbian.com/nanopi-neo-air/
* Official Neo Air Debian image -- nanopi-neo-air_debian-nas-jessie_4.14.52_20180628.img.zip (Image File with Support for 1-bay NAS Dock, kernel:Linux-4.x.y) available from here -- https://drive.google.com/drive/folders/1_mPtgAVaRtYVfsYRgLJ15CAB_48ob_yQ

**Comment by troyane** [comment]
@Fourdee shouldn't we open this issue? Looks like it is tightly connected to https://github.com/Fourdee/DietPi/issues/738#issuecomment-418447508
