### ISSUE TITLE
General | Wikipedia page for DietPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1228]
> https://twitter.com/marcdraco63/status/927631556784648192
> https://en.wikipedia.org/wiki/Wikipedia:How_to_create_a_page

**Comment by k-plan** [comment]
@Fourdee 

like to help you out, but it's a job for a  :gb:  native speaker

But some hints for missing links:

https://en.wikipedia.org/wiki/Raspberry_Pi#Operating_systems

https://en.wikipedia.org/wiki/Light-weight_Linux_distribution#Overview_of_distributions

(here a Wikipedia sub page link is missing)

-------------------

and here  a lack of links to http://dietpi.com/#download on some Wikipedia sub pages (I think so):

https://en.wikipedia.org/wiki/ODROID#Operating_systems

https://en.wikipedia.org/wiki/Banana_Pi#Available_operating_systems

https://en.wikipedia.org/wiki/Pine64

https://en.wikipedia.org/wiki/Asus_Tinker_Board#External_links

Hope it will help.

**Comment by Fourdee** [comment]
Marking as closed, no progress. We offer online docs via our forum. I'am unable to take this on for the foreseeable future, due to lack of available time.

If someone is able to pick this one up, please reopen.
