### ISSUE TITLE
Allo USBridge not playing using Mosaic UV DAC

### ISSUE THREAD

**Issue by paulstephane** [MichaIng/DietPi#1234]
## Creating a bug report/issue:
Reference code: adc52cd0-5767-4c2a-a8e9-f8a3f5d86857-0 

Allo USBridge does not play to Mosaic UV Dac. RaspberryPi with DietPi plays correctly to the DAC. Allo USBridge plays correctly to another DAC. 
With the USBridge to the Mosaic, the sound is a series of uninterrupted clicks.
Mosaic USB input is 1.0.

Addition: without the USBridge card, the Sparky plays to the DAC only through the USB 3.0 port, not through the two USB 2.0 ports.

Thanks for looking into this.

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 158
- SBC Device (EG: RPi 3)? Sparky
- Power supply used (EG: 5v 1A RAVpower)? Allo 5V supply
- SD card used (EG: Sandisk ultra)? 
- Distro (EG: Jessie) | ```uname -a```? Linux DietPi 3.10.38 #96 SMP PREEMPT Tue Nov 7 17:10:13 IST 2017 armv7l GNU/Linux

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by paulstephane** [comment]
Issue solved by Allo
Can be closes

**Comment by Fourdee** [comment]
@paulstephane 
> Issue solved by Allo
Can be closes

Thanks. Apologies for not replying to this ticket, got lost in the pile :frowning_face:
