### ISSUE TITLE
Bootloop - Error line 302 0#NTPD: invalid number

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1238]
## Required Information:
- DietPi Version  158
- SBC Device  rpi zero
- Power supply used 5.1v 2a
- SD card used  Sandisk Ultra 8GB
- Distro (EG: Jessie) | 4.9.52+

## Info:
If i have not connected my USB LAN device i will end up in a boot loop that i can't break.
![img_20171117_123643](https://user-images.githubusercontent.com/3670907/32949013-828b52c6-cba1-11e7-9860-183e955f496d.jpg)

How to solve this?
I trie myself by disbleing NTP over dietpi-config, same problem!

**Comment by Fourdee** [comment]
@tatoosh 

Please change/verify the value of ```boot_wait_for_network=``` in ```/DietPi/dietpi.txt``` to:
```
boot_wait_for_network=1
```

**Comment by oparoz** [comment]
I think you meant @tatoosh ?

**Comment by tatoosh** [comment]
@Fourdee then my boot is delayed? I need a very fast boot for my music player project. Any other chance to solve this?

Here is my dietpi.txt:
```
boot_wait_for_network=0#NTPD mirror, applied to /etc/ntp.conf
#       For a full list, please see http://www.pool.ntp.org
```
maybe this is enough?
>boot_wait_for_network=0   #NTPD mirror, applied to /etc/ntp.conf

**Comment by Fourdee** [comment]
@tatoosh 

0 will be fastest for boot, but will not wait for network.

Also, ensure new line after ```=0```, as per:
https://github.com/Fourdee/DietPi/blob/master/dietpi.txt#L159

**Comment by tatoosh** [comment]
@Fourdee: solved by inserting blank after ```boot_wait_for_network=0```.

**Comment by tatoosh** [comment]
@Fourdee: solved by inserting blank ```after boot_wait_for_network=0 ```
So you habe to check your script please.
