### ISSUE TITLE
DietPi-Software | Medusa

### ISSUE THREAD

**Issue by DDA78** [MichaIng/DietPi#1246]
Can I propose inclusion of medusa in the software list, it has much more features then sickrage and more actively developed

https://github.com/pymedusa/Medusa

https://github.com/pymedusa/Medusa/wiki/Installation-&-Configuration-Guides

**Comment by DDA78** [comment]
Hello,

Is the inclusion of this possible, any ETA 

Thanks for the work you developers are doing.

**Comment by sfb2** [comment]
thx a lot..according to their github theres also a Medusa-"Docker"-image  for armhf too..->[https://hub.docker.com/r/lsioarmhf/medusa/](https://hub.docker.com/r/lsioarmhf/medusa/)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by ezekini** [comment]
I would really like this addition. Sickrage is going down badly and a huge part of sickrage users are moving to Medusa or SickChill.
https://www.reddit.com/r/sickrage/comments/9ll427/echelon_attempting_hostile_takeover_again/

**Comment by LauWs** [comment]
Please reopen and add Medusa to the software list.

**Comment by bonshates** [comment]
To start, thank you to all of the folks that support DietPi. It is greatly appreciated.

I have read that most of the SickRage devs have moved over to Medusa. Please consider adding it to DietPI.
https://www.reddit.com/r/sickrage/comments/9myqx0/can_some_give_me_a_run_down_on_what_is_going_on/
