### ISSUE TITLE
DietPi-Software | node-red: Add a soft link for config folder at install

### ISSUE THREAD

**Issue by borpin** [MichaIng/DietPi#1256]
### Background
Node-RED users expect to find their configurations etc in a folder ~/.node-red.  DietPi uses the folder /mnt/dietpi_userdata/node-red.  This folder location is required every time a node is added via npm to Node-RED.

### Solution
Add a soft link at install time from ~/.node-red to /mnt/dietpi_userdata/node-red

BTW, such a simple process to install Node-RED with DietPi - fantastic.

**Comment by Fourdee** [comment]
Completed, v159 for new installations of node-red.
