### ISSUE TITLE
DietPi-Update | Shows update available (when not), shows update available for lower version than current.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1258]
I've personally never seen this issue in testing, but may be related to slow network during boot and no clear of ```.update_available``` file.

> http://dietpi.com/phpbb/viewtopic.php?f=11&t=2409&p=9710#p9389

**Comment by MichaIng** [comment]
Hehe, had this at least with testing branch on VMs, where update to _**same**_ version string was sometimes shown.  First thought, that this makes sense for testing, if new commits/PRs were merged, but then `dietpi-update` didn't want to because of version string match.

Thanks for solving!

**Comment by Fourdee** [comment]
This should now be resolved. ```.update_available``` always cleared prior to checking for updates.

Marking as completed.
