### ISSUE TITLE
DietPi-Config | Upgrade WiFi to use wpa_supplicant.conf

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1262]
The "correct" way to do it (or so i'am told), however, resolves issues with RPi onboard WiFi scan failure on Stretch:
https://github.com/Fourdee/DietPi/issues/475#issuecomment-346698969

**Comment by Fourdee** [comment]
REF: https://github.com/Fourdee/DietPi/issues/1250#issuecomment-347637636

**Comment by Fourdee** [comment]
#### ToDo:
- 🈯️ Update ```dietpi-config``` to new system
- 🈯️ Update ```boot``` and automated first run to new system
- 🈯️ Patch existing WiFi enabled users to new system
- 🈯️ Support keys WPA-PSK/WEP/NONE
- 🈯️ Removal of ```iw reg set```, in preference of ```wpa_supplicant.conf country=```
- Support auto detection of key type based on SSID results?
- 🈯️ Verify compatibility with hotspot install
- 🈺 test everything.
-- 🈯️ OPEN host
-- 🈯️ WPA-PSK host
-- 🈴 WEP host, tests failed. Lacks further investigations/time, outdated and potentially insecure. Dropping support for ```WEP```.

#### Issues:
- 🈯️ Netplug not compatible, remove: Setting static IP for wlan, results in both eth and wlan reporting already up, when re init. Due to ```netplug```?

**Comment by TheOldPresbyope** [comment]
I agree and am closing #1250.

**Comment by Fourdee** [comment]
Completed.
