### ISSUE TITLE
DietPi-Software | MySQL: Fix or remove actual installation on Stretch? 

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1269]
On Stretch, `mysql-server` changed into a meta package that actually installs MariaDB: https://packages.debian.org/de/stretch/mysql-server
It is the same for Raspbian.

I didn't recognize any real problem with this, as still MariaDB uses the same commands etc. but it might be confusing for user, that make their choice between the offered MariaDB and MySQL stacks and finally find the same database on both. At least the `unix_socket` login method, coming by default with MariaDB, potentially leads to problems with scripts, that expect password root login, also via non-root unix users.

So the question is, if we wan't to preserve the possibility to (really) install MySQL, or if we want to follow Debian and completely remove it from DietPi.

I just checked, there really is no mysql package anymore available, thus we would need to switch to oracles repo: https://dbahire.com/how-to-install-mysql-server-on-debian-stretch/

**Comment by Fourdee** [comment]
@MichaIng 

> So the question is, if we wan't to preserve the possibility to (really) install MySQL, or if we want to follow Debian and completely remove it from DietPi.
I just checked, there really is no mysql package anymore available, thus we would need to switch to oracles repo: https://dbahire.com/how-to-install-mysql-server-on-debian-stretch/

Personally, i'd be happy to remove MySQL option from Stretch. Lets follow Debian on this.
