### ISSUE TITLE
DietPi-System | Quirks noticed by v158 image update 

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1270]
----------
### General

- [x]  - a typo in `dietpi.txt`
```
# >> Misc Options -----------------------------------
#Size of dphys-swapfile to generate (MB)
#   0=Disabled | 1=auto (1GB-RAM = size) | 2+=manual
```
since v155 size is now set to "2048 - total memory"
so it have to be:
```
# >> Misc Options -----------------------------------
#Size of dphys-swapfile to generate (MB)
#   0=Disabled | 1=auto (2GB-RAM = size) | 2+=manual
```

.

- [x]  - missing feature in `dietpi-drive_manager` : exfat support
easy it fix, if you want: 
`apt-get install exfat-fuse exfat-utils`
(_tested and work on updated images_)

.

- [ ]  - update `finalize`:
- automated delete of unwanted `.xxxx` files in `/boot/dietpi/...`
- delete all unessential logfiles in `/var/log/ ...`, especially if you have tested different software and/or have change over to `Logrotate and Rsyslog`
- delete all unessential files in `/var/backup/ ...`
- delete all unwanted directory by image editing from other operation system like: `.Trashes` , `.fseventsd` ,  `System Volume Information` , etc.

.

- [x]  - dphys-swapfile  generation during  inital installation process:
- to speedup 2. boot process, I like to have only generated a fix dphys-swapfile of eg 100 MB (if we really need this?)
- after printing initial setup dialog and after (or before) auto-update dietpi system files, you can create the dphys-swapfile size define in `dietpi.txt` eg `auto (2GB-RAM = size)`

Why? Because of generating such a large default dphys-swapfile during second bootup before dietpi has started is a really P.I.T.A. Particularly with slow SD cards and devices without a monitor option, so you don't know, what's really going on ...
Possilble that's user will break initial setup process because of the long periode of time without reaction during dphys-swapfile  generation.
.....

......

------------------

### Dependent on devices

- [x]  - Patching 154 leave package which is no longer required: (OrangePi One, Odroide C1, PineA64, NanoPi Neo, RPi)
```
[Info] Patching 153 to 154
 
 The following packages will be REMOVED:
  pciutils*
```

```
apt-get upgrade

Reading state information... Done
Calculating upgrade... The following package was automatically installed and is no longer required:
  libpci3
Use 'apt-get autoremove' to remove it.

```
- Fixed in updated images, but a patch will be helpfull

.

- [ ]  - `dietpi-config`  green_led options make no sense for Allwinner H3 devices:
see: https://github.com/Fourdee/DietPi/issues/1257#issuecomment-347012900

.

- [x]  - can't change WiFi country code in dietpi-config
- Odroid C1 => not working with USB: `Ralink Technology, Corp. RT5370 Wireless Adapter`
- Odroid C1 => not working with USB: `Edimax EW-7612UAn Realtek RTL8191SU`
- OrangePi One => not working with USB:  `Realtek Semiconductor Corp RTL8188EUS`
- NanoPi Neo => not working with USB: 
       - `ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n`
       - `ID 1737:0079 Linksys WUSB600N v2 Dual-Band Wireless-N Network Adapter [Ralink RT3572]`
        - `ID 148f:2870 Ralink Technology, Corp. RT2870 Wireless Adapter`
        - `ID 0bda:8172 Realtek Semiconductor Corp. RTL8191SU 802.11n WLAN Adapter`
        - `ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
`
- PineA64 => working with:  `Pine addon WiFi board`

![171203-0004](https://user-images.githubusercontent.com/17237601/33527593-d3773b14-d853-11e7-9eb1-4573bf478632.gif)

![171203-0003](https://user-images.githubusercontent.com/17237601/33527595-e666b34e-d853-11e7-96f5-59735c5fe9c7.gif)

![171203-0002](https://user-images.githubusercontent.com/17237601/33527444-90bb6bbc-d851-11e7-8584-1b5ef5e4036d.gif)

.

- [x]  - updated [ARMbian sources.list](https://github.com/Fourdee/DietPi/issues/1271#issuecomment-348806978): (NanoPi Neo, OrangePi one)

```
root@DietPi:~# cat /etc/apt/sources.list.d/armbian.list
deb http://apt.armbian.com jessie main jessie-utils jessie-desktop
```
- Fixed in updated images

.
......

.......

--------------

### Hints for special devices

**oDroid C1:**

- `dietpi.txt` :  
`cpu_governor=ondemand` make no sense with Kernel 3.x, where is no such CPU governor
![171203-0001](https://user-images.githubusercontent.com/17237601/33527653-aed6474a-d854-11e7-9cea-0fbb59f9c7a0.gif)
![171203-0005](https://user-images.githubusercontent.com/17237601/33527661-cf8224a0-d854-11e7-82c4-c9e3675ff3a3.gif)
change it in `dietpi.txt` by hand to `cpu_governor=interactive` before image building

.

**oDroid C2:**

- [ ]  - messages during (kernel) update:

```
grep: /etc/ssh/sshd_config: No such file or directory
/var/lib/dpkg/info/setup-odroid.postinst: line 5: /etc/ssh/sshd_config: No such file or directory
Failed to restart ssh.service: Unit ssh.service failed to load: No such file or directory.
patching file boot.ini
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file boot.ini.rej
patching file boot.ini
Hunk #1 FAILED at 49.
1 out of 1 hunk FAILED -- saving rejects to file boot.ini.rej
patching file boot.ini
Hunk #1 FAILED at 4.
1 out of 1 hunk FAILED -- saving rejects to file boot.ini.rej
patching file boot.ini
Hunk #1 succeeded at 37 with fuzz 2 (offset -60 lines).
patching file boot.ini
Hunk #1 succeeded at 37 (offset -60 lines).
Hunk #2 succeeded at 70 (offset -60 lines).
patching file /boot/boot.ini
Hunk #1 succeeded at 87 (offset -60 lines).
patching file boot.ini
Hunk #1 FAILED at 49.
1 out of 1 hunk FAILED -- saving rejects to file boot.ini.rej
patching file boot.ini
Hunk #1 succeeded at 41 (offset -60 lines).
patching file boot.ini
Hunk #1 succeeded at 91 (offset -62 lines).
Hunk #2 succeeded at 122 (offset -62 lines).
Processing triggers for initramfs-tools (0.120+deb8u3) ...
```
So please better have a look into generated files during update: 
[boot.ini.C2.zip](https://github.com/Fourdee/DietPi/files/1541085/boot.ini.C2.zip)
But `finalize` write back your `boot_c2.ini` from master.

- [ ]  -  removing `setup-odroid` (?)
During first `apt-get upgrade` a new script `setup-odroid` was install:

![171208-0001](https://user-images.githubusercontent.com/17237601/33746312-a0e83a92-dbbc-11e7-99e7-30697ccd84ea.gif)

Think, it is not needed and user can make with this any installation inconsistent.
Possible, it's as well included in other meveric based installations.

.

**PineA64:**

- [ ]  - `dietpi-config` => `LED Control`  make no sense. 
It's only one red led on board and it can't be configured by `dietpi-led_control`. 
So it will be nice to remove this for PineA64 devices.

.

**Raspberry Pi:**

- [ ]  - `dietpi-config` => `Advanced Options ` => `Update firmware` 
![171210-0001](https://user-images.githubusercontent.com/17237601/33805085-d1d8962c-ddb2-11e7-8a65-17124763b067.gif)
- as long as if you want/will provide a custom kernel/firmware packet, I think, it's better to disable this option like it's done for other devices

.....

.....

----------------

**Comment by Fourdee** [comment]
Thanks @k-plan,

I'll take a look at this after v159. Wrapping up v159 + Stretch currently.

**Comment by k-plan** [comment]
@Fourdee 

Okay. 
If you willing to work on it, you can hack down the task list. 👍

**Comment by MichaIng** [comment]
@k-plan @Fourdee 
Started to go through the steps, as this goes often hand in hand with preparation script automation. Need some time with my wife now, will go on tomorrow.
https://github.com/Fourdee/DietPi/pull/1312

**Comment by Fourdee** [comment]
> Started to go through the steps, as this goes often hand in hand with preparation script automation.

@MichaIng 

Great work, legend 👍 

> Need some time with my wife now

Yep, same here, gotta keep the wife happy 😉 😉

**Comment by Fourdee** [comment]
@k-plan 

> dphys-swapfile generation during inital installation process:

👍 Moved:  https://github.com/Fourdee/DietPi/commit/40c2a2ffb6d47f83d623222cbad0fe5f02443d8b

**Comment by Fourdee** [comment]
I'll mark this as closed as it appears to apply to <v6.x. Please reopen if required.
