### ISSUE TITLE
DietPi-System | ARMbian sources.list change

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1271]
@Fourdee 

While updating the last image (NanoPi-Neo), this error occur:

```
:~# apt-get update
...
W: Failed to fetch http://apt.armbian.com/dists/jessie/InRelease  Unable to find expected entry 'utils/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
:~# cat /etc/apt/sources.list.d/armbian.list
deb http://apt.armbian.com jessie main utils jessie-desktop

```

http://apt.armbian.com/dists/jessie/InRelease

```
Origin: Armbian
Label: Armbian
Suite: jessie
Codename: jessie
Date: Sun, 3 Dec 2017 12:13:49 UTC
Architectures: arm64 armhf
Components: main
Description: Generated by aptly
...
```

What shall/can we do? Remove `utils jessie-desktop` from the list?
Cross-check with last night build image on OrangePi One which was updated without any error:

Now it's the same error:

```
root@OrangePi-One:~# apt-get update
...
Fetched 845 kB in 23s (36.2 kB/s)
W: Failed to fetch http://apt.armbian.com/dists/jessie/InRelease  Unable to find expected entry 'utils/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

```

😢   😠   💩   👎 

`k-plan@DietPi:~# ... stop building update images for now! Please help ....`

**Comment by Fourdee** [comment]
@k-plan 

https://github.com/armbian/build/search?utf8=%E2%9C%93&q=armbian.list&type=Code

Try:
```
deb http://apt.armbian.com jessie main jessie-utils jessie-desktop
```

Failing that, we can remove ```utils``` and ```jessie-desktop``` via patch.

**Comment by k-plan** [comment]
@Fourdee 
> `deb http://apt.armbian.com jessie main jessie-utils jessie-desktop`

```
root@OrangePi-One:~# cat /etc/apt/sources.list.d/armbian.list
deb http://apt.armbian.com jessie main jessie-utils jessie-desktop
```

```
W: Failed to fetch http://apt.armbian.com/dists/jessie/InRelease  Unable to find expected entry 'jessie-utils/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

For now, I only see` main/...` in [InRelease](http://apt.armbian.com/dists/jessie/InRelease)

```
main/Contents-arm64.gz
main/Contents-armhf.gz
main/binary-arm64/Packages
main/binary-arm64/Packages.bz2
main/binary-arm64/Packages.gz
main/binary-arm64/Release
main/binary-armhf/Packages
main/binary-armhf/Packages.bz2
main/binary-armhf/Packages.gz
main/binary-armhf/Release
```

> Failing that, we can remove utils and jessie-desktop via patch.

👍  Nice! 
Shall/can I do this in updated images by hand?

**Comment by k-plan** [comment]
@Fourdee 

do some reseach: https://forum.armbian.com/topic/5355-unable-to-find-expected-entry-jessie-utilsbinary-armhfpackages-in-release-file/

I think, they have f... up on of their repository server.

https://apt.armbian.com/dists/jessie/

![171203-0006](https://user-images.githubusercontent.com/17237601/33530268-6661f896-d87d-11e7-9d82-7123694c2136.gif)

```
Origin: Armbian
Label: Armbian
Suite: jessie
Codename: jessie
Date: Sun, 3 Dec 2017 12:13:49 UTC
Architectures: arm64 armhf
Components: main
Description: Generated by aptly
....
```


http://apt.uk.armbian.com/dists/jessie/

![171203-0007](https://user-images.githubusercontent.com/17237601/33530271-724998bc-d87d-11e7-94a4-6d25192e3239.gif)

```
Origin: Armbian
Label: Armbian
Suite: jessie
Codename: jessie
Date: Sat, 25 Nov 2017 06:45:54 UTC
Architectures: arm64 armhf
Components: jessie-desktop jessie-utils main utils
Description: Generated by aptly
....
```
Have done a quick look into their last `Armbian_5.35_Orangepione_Debian_jessie_default_3.4.113`

```
root@OrangePi-One:~# cat /etc/apt/sources.list.d/armbian.list
deb http://apt.armbian.com jessie main jessie-utils jessie-desktop

```
should be fine.

👍 

So we have to wait until Igor will fix it.

So I will build some new update images with the correct source.list. 
But not today anymore.

**Comment by k-plan** [comment]
Nice,  repository server is fixed. :smiley: 

https://apt.armbian.com/dists/jessie/

```
Origin: Armbian
Label: Armbian
Suite: jessie
Codename: jessie
Date: Mon, 4 Dec 2017 12:08:18 UTC
Architectures: arm64 armhf
Components: jessie-desktop jessie-utils main utils
Description: Generated by aptly
```
Will test it tomorrow with:  `deb http://apt.armbian.com jessie main jessie-utils jessie-desktop`

:+1:

**Comment by k-plan** [comment]
> Will test it tomorrow with: `deb http://apt.armbian.com jessie main jessie-utils jessie-desktop`

- Done
- Works
- building updated ARMbian images now

Close.
