### ISSUE TITLE
v159 Release

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1287]
### ToDo:
- 🈯️ Switch to RPi Stretch image on dietpi.com https://github.com/Fourdee/DietPi/issues/475#issuecomment-350519670
- 🈯️ Create/upload Allo GUI RPi Stretch image, to replace Jessie version 
-- 🈯️ Test updates of existing installations
- 🈯️ Update Allo GUI Sparky image
-- 🈯️ Test updates of existing installations
-- 🈯️ update forum links
- 🈯️ Xmas Tree? 🎄 
- 🈯️ Merge https://github.com/Fourdee/DietPi/pull/1289
- 🈯️ Update DietPi Update Mirror
- 🈯️ Twitter post for update https://twitter.com/DietPi_/status/940004236028506113

**Comment by Fourdee** [comment]
~Release will now be done Monday evening, ran out of time today.~

Nope, we made it :)

**Comment by k-plan** [comment]
> - Xmas Tree? 🎄

Yes, please .... :laughing:

:speak_no_evil:

**Comment by Fourdee** [comment]
@k-plan 
![image](https://user-images.githubusercontent.com/7077026/33810796-276c7b96-de01-11e7-940d-4cbfa40507af.png)

**Comment by k-plan** [comment]
@Fourdee 

Very nice! 👍 

Good to see, you don't lose one's  humour! 😄

**Comment by Fourdee** [comment]
@k-plan 

> Good to see, you don't lose one's your humour!

Trying, although its really salty recently lol

**Comment by Fourdee** [comment]
Completed.

Thanks @k-plan and @MichaIng for all your contributions this release, really appreciate it 👍
