### ISSUE TITLE
DietPi-Services | stop/start dietpi-wifi-monitor drops connection

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1288]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=2547&p=9866#p9853

User reports with ```dietpi-backup```, but this should be triggered with ```dietpi-services``` commands.

**Comment by Master92** [comment]
Had the same issue when running software installation with `dietpi-software`.

Last output is:
```
 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron
 [Ok] nginx
 [Ok] octoprint
dietpi-wifi-monitor
```
After that, the connection drops and won't automatically reestablish.

#### Required information:
- DietPi Version: 158 and 159
- SBC Device: Pine A64+ 1GB

#### Update:
When commenting out ```dietpi-wifi-manager``` in ```/DietPi/dietpi/dietpi-services``` as suggested, the bug doesn't occur anymore.

**Comment by Yury-MonZon** [comment]
It is weird, but for dietpi-update it didn't work.
Info here: http://dietpi.com/phpbb/viewtopic.php?f=11&t=2547&p=9918#p9918

**Comment by Master92** [comment]
Did you update your system after commenting out ```dietpi-wifi-manager``` and before updating again?
Seems like the ```/DietPi/dietpi/dietpi-services``` file gets replaced by each version-upgrade.

**Comment by Yury-MonZon** [comment]
Nope. I was on v158, commented it out and tried to update to v159. After it disconnected I had to power cycle it to reboot. Then checked that it is still commented out and tried to run the update again with the same results. 
monzon@MZ-Cloud:~ $ cat /DietPi/dietpi/dietpi-services | grep wifi
                #'dietpi-wifi-monitor'

**Comment by Fourdee** [comment]
@Master92 

> Seems like the /DietPi/dietpi/dietpi-services file gets replaced by each version-upgrade.

Correct, all DietPi scripts are replaced during the upgrade 👍 

> monzon@MZ-Cloud:~ $ cat /DietPi/dietpi/dietpi-services | grep wifi
#'dietpi-wifi-monitor'

@Yury-MonZon 

Bizarre,

Does connection drop (as per https://github.com/Fourdee/DietPi/issues/1288#issuecomment-350653480) occur when you run the commands full path?
```
/DietPi/dietpi/dietpi-services stop
```

**Comment by Yury-MonZon** [comment]
No, it doesn't disconnect this way.
`monzon@MZ-Cloud:~ $ sudo /DietPi/dietpi/dietpi-services stop
[sudo] password for monzon:

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron
 [Ok] proftpd
 [Ok] nginx
 [Ok] php5-fpm
 [Ok] mysql
 [Ok] fail2ban
 [Ok] avahi-daemon
 [Ok] rpimonitor

`

**Comment by Yury-MonZon** [comment]
It does disconnect in the middle of installation,
not at the beginning.
[code]
monzon@MZ-Cloud:~ $ sudo dietpi-update 1
 [Info] Checking RootFS R/W access. Please wait...
 [Ok] RootFS R/W access.

 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Checking for DietPi updates
 Please wait...

 [Info] Checking Mirror : http://dietpi.com/downloads/dietpi-update_mirror/master/server_version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0     26      0 --:--:-- --:--:-- --:--:--    26
 [Ok] Using update server: http://dietpi.com/downloads/dietpi-update_mirror/master/server_version

 [Ok] Update available
 [Info] Current Version : 158
 [Info] Server Version  : 159
 [Info] Detecting drives, please wait...
 [Info] Detected /dev mount: /dev/mmcblk0p1 > /boot
 [Info] Detected UUID mount: /dev/mmcblk0p2 > /mnt/6e11ba37-3d23-4d99-8ad6-b6a7a5fb372d
 [Info] Detected UUID mount: /dev/sda1 > /
 [Info] Processing drive information, please wait...
 [Info] Checking available free space on RootFS, please wait...
 [Ok] 402975 MB available, 500 MB required
 [Ok] Updates have been found and are being applied, please wait...
 [Info] Current Version : 158
 [Info] Server Version  : 159
 #               processing | D i e t  P i             #


 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron
 [Ok] proftpd
 [Ok] nginx
 [Ok] php5-fpm
 [Ok] mysql
 [Ok] fail2ban
 [Ok] avahi-daemon
 [Ok] rpimonitor

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  384k  100  384k    0     0   700k      0 --:--:-- --:--:-- --:--:--  699k
Archive:  /tmp/dietpi-update/update.zip
5cc4e59a128ff3998802e4a80fa5751d11f7a88f
   creating: /tmp/dietpi-update/DietPi-master/
  inflating: /tmp/dietpi-update/DietPi-master/.gitattributes
   creating: /tmp/dietpi-update/DietPi-master/.github/
  inflating: /tmp/dietpi-update/DietPi-master/.github/ISSUE_TEMPLATE.md
  inflating: /tmp/dietpi-update/DietPi-master/.github/PULL_REQUEST_TEMPLATE.md
  inflating: /tmp/dietpi-update/DietPi-master/.gitignore
  inflating: /tmp/dietpi-update/DietPi-master/CHANGELOG.txt
  inflating: /tmp/dietpi-update/DietPi-master/PREP_SYSTEM_FOR_DIETPI.sh
  inflating: /tmp/dietpi-update/DietPi-master/README.md
  inflating: /tmp/dietpi-update/DietPi-master/TESTING-BRANCH.md
  inflating: /tmp/dietpi-update/DietPi-master/boot_c1.ini
  inflating: /tmp/dietpi-update/DietPi-master/boot_c2.ini
  inflating: /tmp/dietpi-update/DietPi-master/boot_xu4.ini
  inflating: /tmp/dietpi-update/DietPi-master/config.txt
  inflating: /tmp/dietpi-update/DietPi-master/dietpi.txt
   creating: /tmp/dietpi-update/DietPi-master/dietpi/
 extracting: /tmp/dietpi-update/DietPi-master/dietpi/.dietpi-autostart_index
 extracting: /tmp/dietpi-update/DietPi-master/dietpi/.install_stage
 extracting: /tmp/dietpi-update/DietPi-master/dietpi/.update_stage
 extracting: /tmp/dietpi-update/DietPi-master/dietpi/.version
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/boot
   creating: /tmp/dietpi-update/DietPi-master/dietpi/conf/
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/apache.ownnextcloud.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/apache2_jessie.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/brutefir.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/brutefir_config
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/cava.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/cron.daily_dietpi
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/cron.hourly_dietpi
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/deluge.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/deluge.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/deluge_web.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fail2ban_jail.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fstab
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fstab_rock64
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fstab_vm
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fstab_x86_64-native
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/fstab_x86_64-native_EFI
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/gmrender.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/haproxy_init
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/htoprc
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/kodi_udev
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/minidlna.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/mpd.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/netdata.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/network_interfaces
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/nginx.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/nginx.site-available-default
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/nginx.sites-dietpi.nextcloud.config
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/nginx.sites-dietpi.owncloud.config
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/openbazaar-server.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/opentyrian_run
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/phpsysinfo.ini
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/proftpd.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/raspimjpeg.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/roonbridge.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/smb.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/squeezeboxserver.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/squeezelite.service
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/vsftpd.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/xorg_c1.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/xorg_c2.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/conf/xorg_xu4.conf
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-autostart
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-backup
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-banner
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-bugreport
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-cleaner
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-cloudshell
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-config
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-cpu_set
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-cpuinfo
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-cron
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-drive_manager
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-funtime
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-launcher
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-letsencrypt
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-logclear
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-morsecode
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-obtain_hw_model
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-process_tool
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-ramdisk
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-ramlog
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-services
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-software
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-survey
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-sync
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/dietpi-update
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/finalise
   creating: /tmp/dietpi-update/DietPi-master/dietpi/func/
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/change_hostname
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/check_connection
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/create_mysql_db
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-led_control
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-notify
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-optimal_mtu
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_curlftpfs
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_dphys-swapfile
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_hardware
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_nfsclient
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_smbclient
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_software
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/dietpi-set_userdata
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/obtain_network_details
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/func/run_ntpd
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/login
   creating: /tmp/dietpi-update/DietPi-master/dietpi/misc/
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/misc/dietpi-justboom
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/misc/start_kodi
  inflating: /tmp/dietpi-update/DietPi-master/dietpi/patch_file
 extracting: /tmp/dietpi-update/DietPi-master/dietpi/server_version
  inflating: /tmp/dietpi-update/DietPi-master/uEnv.txt

 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Updating DietPi
 Please wait...

 [Info] Current Version : 158
 [Info] Server Version  : 159

 [Info] Patching 158 to 159
 [Info] Checking RootFS R/W access. Please wait...
 [Ok] RootFS R/W access.
 [Info] Initializing database, please wait...
 [Info] Reading database, please wait...

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Automated reinstall
 Please wait...

 [Info] 159: Allo is not currently installed
 [Info] The program must be installed, before reinstall can be used
 [Ok] No changes applied for: Allo
 [Info] 128: MPD is not currently installed
 [Info] The program must be installed, before reinstall can be used
 [Ok] No changes applied for: MPD
 [Ok] Reinstalling Nextcloud: A safe home for all your data
 [Info] 47: ownCloud is not currently installed
 [Info] The program must be installed, before reinstall can be used
 [Ok] No changes applied for: ownCloud
 [Info] 36: SqueezeLite is not currently installed
 [Info] The program must be installed, before reinstall can be used
 [Ok] No changes applied for: SqueezeLite
 [Info] 32: YMPD is not currently installed
 [Info] The program must be installed, before reinstall can be used
 [Ok] No changes applied for: YMPD
 [Info] Detecting drives, please wait...
 [Info] Detected /dev mount: /dev/mmcblk0p1 > /boot
 [Info] Detected UUID mount: /dev/mmcblk0p2 > /mnt/6e11ba37-3d23-4d99-8ad6-b6a7a5fb372d
 [Info] Detected UUID mount: /dev/sda1 > /
 [Info] Processing drive information, please wait...
 [Info] Checking available free space on RootFS, please wait...
 [Ok] 402975 MB available, 500 MB required
 [Info] Testing connection to http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian
 [Info] Max duration of 20 seconds, please wait...
 [Ok] Connection test | Completed

 [Ok] NTPD: time sync | Completed


 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] stop : cron
 [Ok] stop : proftpd
 [Ok] stop : nginx
 [Ok] stop : php5-fpm
 [Ok] stop : mysql
 [Ok] stop : fail2ban
 [Ok] stop : avahi-daemon
 [Ok] stop : rpimonitor
dietpi-wifi-monitor
[/code]

**Comment by Fourdee** [comment]
@Yury-MonZon 

> [Ok] stop : cron
[Ok] stop : proftpd
[Ok] stop : nginx
[Ok] stop : php5-fpm
[Ok] stop : mysql
[Ok] stop : fail2ban
[Ok] stop : avahi-daemon
[Ok] stop : rpimonitor
dietpi-wifi-monitor

Ah yes, thats because the updated script is now running, which replaces your dietpi-wifi-monitor changes.

I've disabled control of ```dietpi-wifi-monitor ``` for v160 onwards:
- https://github.com/Fourdee/DietPi/commit/793a923f266c4b1c77dd0d274ff4206f2836c59a

**You'll need to wait for v160 release notification, then**:
- Comment out ```#dietpi-wifi-monitor ``` in ```/DietPi/dietpi/dietpi-services```
- ```dietpi-update```
- New script will have ```dietpi-wifi-monitor ``` disabled by default.

Completed, albeit waiting for v160 release.
