### ISSUE TITLE
DietPi-Software | Plexmediaserver: installed but launches only as Plex Web

### ISSUE THREAD

**Issue by Dinesh3219** [MichaIng/DietPi#1290]
Hi, 
I installed plexmediaserver on my odroid xu4 from dietpi-softwares but when i launch IPaddress:32400 it only launches as a web client and not as a server. Is there any way to fix this. 

Thank you for your guidance.. i think i am doing something wrong..

**Comment by Fourdee** [comment]
@Dinesh3219 

Hi,

You need to add ```/web``` after the port, eg:
http://192.168.0.100:32400/web

> http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1949#p1949

**Comment by Dinesh3219** [comment]
Hi Fudree,

Thank you for replying.. yes I have added web at the end.. I login with ipaddress:32400/web and it takes me through the plex log in page and everything seems normal, but the server section is missing under the users and I cannot link any of my folders to PLEXSERVER. I have my windows computer on the same network and when I go under the networks tab in My Computer then I can see plexmediaserver - dietpi. So I think the installation of plexmediaserver from dietpi-software is fine but I still cannot see the server section under users tab. I have re-installed my plexmediaserver few times but I keep hitting into the same wall.
If there is anything else that I should do then please help me out.

Thanks a lot.
![plex log in](https://user-images.githubusercontent.com/34437979/34069072-5963acf4-e262-11e7-8271-d0773da0b767.jpg)

**Comment by Fourdee** [comment]
Outdated, marking as closed.
