### ISSUE TITLE
Cant finidh firsh setup get stuck

### ISSUE THREAD

**Issue by FusionPlmH** [MichaIng/DietPi#1291]
#### Required Information:
- DietPi Version |158
- SBC Device rpi3
- Power supply used5v2a
- SD card used samsung ultra 32gb
- Distro (EG: Jessie) |stretch

#### Additional Information (if applicable):
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Update & upgrade APT
 Please wait...

Get:1 https://www.mirrorservice.org/sites/archive.raspbian.org/raspbian stretch InRelease [15.0 kB]
Get:2 https://www.mirrorservice.org/sites/archive.raspbian.org/raspbian stretch/main armhf Packages [11.7 MB]
Get:3 https://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:4 https://archive.raspberrypi.org/debian stretch/main armhf Packages [127 kB]
Get:5 https://archive.raspberrypi.org/debian stretch/ui armhf Packages [27.7 kB]

After Get5: ,get stuck for a long period
get help pls

**Comment by LeeMenHin** [comment]
need to be wait for a long p
