### ISSUE TITLE
Failed to execute operation: Activation of org.freedesktop.systemd1 timed out

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1293]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 158
- SBC Device (EG: RPi 3)? NanoPi M1
- Power supply used (EG: 5v 1A RAVpower)? 5V 3A Rydges SpeedPower
- SD card used (EG: Sandisk ultra)? Sandisk 32GB
- Distro (EG: Jessie) | ```uname -a```? Linux S001 3.4.113-sun8i #4 SMP PREEMPT Wed Nov 22 13:45:28 CET 2017 armv7l GNU/Linux

#### Additional Information (if applicable):
- Software title? systemd
- Can this issue be replicated on a fresh installation of DietPi? not tested

#### Expected behaviour:

I shall be able to start stop or restart etc a daemon

#### Actual behaviour:

it doesnt but gives the error message Failed to execute operation: Activation of org.freedesktop.systemd1 timed out

#### Steps to reproduce:

use systemd to start restart stop etc a daemon

#### Did you submit a ```dietpi-bugreport```?

no

#### Extra details:

restarting the device fixes the issue for a period of time
trying systemctl restart systemd-logind doesnt work too

**Comment by MichaIng** [comment]
Sorry that this bug report was never answered. However I guess the issue is solved or obsolete and mark it as closed. Feel free to reopen, if required.
