### ISSUE TITLE
DietPi-Software | Wifi Hotspot not working out of the box. RPi3 

### ISSUE THREAD

**Issue by yuret** [MichaIng/DietPi#1299]
## Creating a bug report/issue:
hostapd wont start and the log is:

Dec 13 17:07:07 DietPi hostapd[943]: Starting advanced IEEE 802.11 management: hostapd/usr/sbin/hostapd: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Dec 13 17:07:07 DietPi hostapd[943]:  failed!

OpenSSL> version
OpenSSL 1.1.0f  25 May 2017
OpenSSL>

 
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
159
- SBC Device (EG: RPi 3)?
RPi 3
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
Transcend UHS-I 16 Gb
- Distro (EG: Jessie) | ```uname -a```?
Linux DietPi 4.9.62-v7+ #2 SMP Fri Nov 17 23:52:26 GMT 2017 armv7l GNU/Linux

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?
Yes

#### Expected behaviour:

Wi-Fi Hotspot should work
#### Actual behaviour:

Wi-Fi Hotspot not working
#### Steps to reproduce:

By installing WiFi hotspot from optimized apps
#### Did you submit a ```dietpi-bugreport```?

No

**Comment by Fourdee** [comment]
@yuret 

Thanks for the report 👍 

If possible, please could you test following (copy and paste all into term):
```
wget http://dietpi.com/downloads/binaries/all/libssl1.0.0_1.0.1t-1+deb8u7_armhf.deb -O package.deb
dpkg -i package.deb
dietpi-services restart
dietpi-services status
```

**Comment by Fourdee** [comment]
https://github.com/Fourdee/DietPi/issues/1303#issue-281684601

**Comment by yuret** [comment]
Thank you! Your solutions works:
DietPi-Services
─────────────────────────────────────────────────────
 Mode: status
 Please wait...

 [Ok] cron      active (running) since Thu 2017-12-14 08:14:18 GMT; 11s ago
 [Ok] isc-dhcp-server   active (running) since Thu 2017-12-14 08:14:20 GMT; 8s ago
 [Ok] hostapd   active (running) since Thu 2017-12-14 08:14:21 GMT; 8s ago

**Comment by Fourdee** [comment]
@yuret 

Legend 👍 Thanks for confirming.

I've applied the fix for v160. Completed.
