### ISSUE TITLE
DietPi-Globals | Replace duplicate function/var code in our scripts

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1311]
By simply loading this script on demand to export global vars.

Also allows for logged in bash user session to use our commands (eg: ```AGI```) etc.

**Comment by Fourdee** [comment]
@MichaIng 

```
root@DietPi:~# AGI thispackagedoesnotexist_Test
 [Info] APT is processing, please wait...

E: Unable to locate package thispackagedoesnotexist_Test
```

---

**Comment by MichaIng** [comment]
Nice! 👍 
Just some minor questions/hints:
- Why not include the error check/output to base AGI etc. directly? Would be helpful in every script and terminal, I think.
- Since -qq includes -y, we can remove the latter: https://wiki.ubuntuusers.de/apt/apt-get/ Why ubuntu wiki is so much better/more detailed than debian ones? Totally missing complete command overviews with all sub commands and options there! 😛.

**Comment by Fourdee** [comment]
@MichaIng 

> Why not include the error check/output to base AGI etc. directly? Would be helpful in every script and terminal, I think.

Makes sense, i'll take a look. 👍 

> Since -qq includes -y, we can remove the latter

Its a habit thing more than anything, although, having ```-y``` in there, ensures if we (or apt) change any options in the future, the ```-y``` should always ensure start of install. I'll leave it in for now.

**Comment by Fourdee** [comment]
ToDo:
- 🈯️ Global dietpi-notify
- 🈯️ Replace existing ```/DietPi/dietpi/dietpi-notify``` commands in dietpi scripts with ```dietpi-notify``` etc
- 🈯️ Replace existing ```apt-get``` commands in dietpi scripts with ```AGI``` etc
- 🈯️ Send my commit
- 🈯️ Manually fix conflicts on outstanding PR's
-- 🈯️+ using global dietpi-notify
-- 🈯️+ using global AGX commands

---

- ```dietpi-drive_manager``` not listing USB drives, list mode is ```1```, caused by:
-- ```Print_Input_String()``` in ```dietpi-notify``` in ```dietpi-global```.
--- 🈯️ Fixed, seems ```i``` was not local to ```dietpi-global``` and being passed back to script loading dietpi-notify
--- confirm defined ```i``` is not changed by ```dietpi-notify```
```
root@DietPi:~# i=1230
root@DietPi:~# . /DietPi/dietpi/func/dietpi-globals
root@DietPi:~# dietpi-notify 0 Test program
 [Ok] Test program
root@DietPi:~# echo $i
1230

#and visa versa
root@DietPi:~# unset i
root@DietPi:~# . /DietPi/dietpi/func/dietpi-globals
root@DietPi:~# dietpi-notify 0 Test program
 [Ok] Test program
root@DietPi:~# echo $i

```

**Comment by Fourdee** [comment]
@MichaIng 

> Why not include the error check/output to base AGI etc. directly? Would be helpful in every script and terminal, I think.

We can provide a notify for result of the ```apt-get``` command, but if we want to handle the end result, we'll need to do this outside the global script.
eg: in ```dietpi-software```, we need to handle the exit code, then we can match it to software title etc if its a failure. If we simply ```exit``` in ```dietpi-global AGX```, we lose the ability to do that.

![image](https://user-images.githubusercontent.com/7077026/34146868-7da81220-e493-11e7-8127-7dcf98f50c09.png)

**Comment by Fourdee** [comment]
This is now completed as intended, however, we'll continue to add/improve it as needed in the future.

**Comment by Fourdee** [comment]
dietpi-drive_manager move userdata:

- 🈯️ Resolved: https://github.com/Fourdee/DietPi/commit/63bf1a2d50b9b1ae818853f7cc53cc3c080ed5b8
```
root@DietPi:~# readlink -f /mnt/dietpi_userdata
/mnt/00293bdc-f422-41a3-99f9-7bfd50eeb266/dietpi_userdata
root@DietPi:~# readlink -f /mnt/dietpi_userdata
/mnt/dietpi_userdata
```

---

```
root@DietPi:~# echo $(/DietPi/dietpi/func/dietpi-set_userdata return_source)
[Info] DietPi-Globals loaded  [Info] Checking for (elevated) root access, please wait..  [Ok] Root access verified. /mnt/dietpi_userdata
```

Ok,
- 🈴 Disable any print for a default load of globals?, nope, we need error information if rootfs rw, root user access fails etc.
![image](https://user-images.githubusercontent.com/7077026/34193363-2c53da9a-e54b-11e7-8d1e-fff763c59d3c.png)

**Comment by Fourdee** [comment]
Completed (again).

**Comment by Fourdee** [comment]
- use of ```G_``` at start of all global commands/vars to clearly define global status, and, avoid variable interaction.
```
root@DietPi:~# G_
G_AGA              G_AGI              G_AGUP             G_CHECK_URL
G_AGDUG            G_AGP              G_CHECK_ROOTFS_RW  G_DIETPI-NOTIFY
G_AGF              G_AGUG             G_CHECK_ROOT_USER
```

**Comment by Fourdee** [comment]
@MichaIng 

Globals are now finalized, using ```G_format``` https://github.com/Fourdee/DietPi/issues/1311#issuecomment-352999485

Supported use in PREP_SYSTEM: https://github.com/Fourdee/DietPi/issues/1311#issuecomment-353039600

Completed (for now) 😄

**Comment by Fourdee** [comment]
Check and automatically install required packages:
NB: renamed to ```G_AG_CHECK_INSTALL_PREREQ```
![image](https://user-images.githubusercontent.com/7077026/34293112-4f424242-e6fb-11e7-98a5-bbe73cd43387.png)

**Comment by Fourdee** [comment]
Note to self:
- Allo GUI replace ```$(/DietPi/dietpi/dietpi-cpuinfo 1)``` with ```G_OBTAIN_CPU_TEMP```
-- + ```/DietPi/dietpi/dietpi-cpuinfo 3```, with ```G_OBTAIN_CPU_USAGE```

**Comment by Fourdee** [comment]
### Improved error handling:

Notes:
- ```G_AGx``` commands are automatically error handled

#### ```G_RUN_CMD mkdir /never/gonna/work```
![image](https://user-images.githubusercontent.com/7077026/34354844-0feba94a-ea29-11e7-89d5-1182d0499174.png)

#### ```G_AGI nevergonnawork```
![image](https://user-images.githubusercontent.com/7077026/34354855-2ae55f20-ea29-11e7-8e61-21f0d8dc64f5.png)

#### Disable whiptail (eg: headless)
#### ```export G_USER_INPUTS=0; G_AGI nevergonnawork```
```
root@DietPi:~# G_AGI nevergonnawork
 [Info] APT installation for: nevergonnawork
 [Info] APT is processing, please wait...

E: Unable to locate package nevergonnawork

 [Error] G_AGI: nevergonnawork
 [Info] exit_code = 100
 [Info] HW_MODEL:12 | HW_ARCH:3 | DISTRO:5
 [Info] Logfile contents:
E: Unable to locate package nevergonnawork
 [Info] Unable to continue, the program will now terminate.
 [Error] Unable to continue, this program will now terminate.
```

---

#### DietPi-Software:
![image](https://user-images.githubusercontent.com/7077026/34318583-abb6f004-e7c3-11e7-9b05-a8e9ac190e8b.png)

**Comment by MichaIng** [comment]
@Fourdee 
Maybe we can include the option the directly send the error as dietpi-bugreport (together with all the other system data)?
_______________
About bug reporting generally, although this would belong into an own topic, it would be nice to have an option or by default make an output that one can copy&paste directly into github preformatted.
Nextcloud e.g. offers this via an app and by this all information is together directly: https://apps.nextcloud.com/apps/issuetemplate

**Comment by MichaIng** [comment]
I played around a bid with global error handling and info echo during installation. It would be nice to reduce the overall amount of echo lines without reducing the information content.

I loved the installation script of PiHole and had a look into their method:
- `echo -n 'test...'` skips new line
- `"\\r\\033[K"` at the beginning of string, will overwrite existing line.
- Thus you can use:
```
echo -n 'Command is running...'
if ( command succeded ); then
  echo -e "\\r\\033[KCommand succeded"
else
  echo -e "\\r\\033[KCommand failed"
end
```
... to just show the final result of a command, after it's finished.
- Maybe we can use this for `G_RUN_CMD`?

Another issue I found with `G_RUN_CMD` is, if you want to forward output into a file, e.g. `G_RUN_CMD echo "blabla" > /path/to/file`, the echo output of error handler will also be found in the file. I'm not sure how in this case it is set, where the input for `G_RUN_CMD` ends and in case it's output could be treated. Is it possible to somehow parenthesise the error handlers input?

**Comment by Fourdee** [comment]
@MichaIng 

> Maybe we can include the option the directly send the error as dietpi-bugreport (together with all the other system data)?

Love the idea 👍 

The main issue we have is structure, currently bug reports are simply uploaded to an FTP server. Its really not that much fun to work with bug reports in that format.

Maybe we could add a simple error send on failures, however, we'd need a better system to log them than FTP. SQL db on server, some kind of API on github that allows us to automatically generate a ticket? All options need research.

> copy&paste directly into github preformatted.

Might work, not a bad idea 👍

**Comment by Fourdee** [comment]
@MichaIng 

> Another issue I found with G_RUN_CMD is, if you want to forward output into a file, e.g. G_RUN_CMD echo "blabla" > /path/to/file, the echo output of error handler will also be found in the file. I'm not sure how in this case it is set, where the input for G_RUN_CMD ends and in case it's output could be treated. Is it possible to somehow parenthesise the error handlers input?

Yep, had the same issue with ```cat << _EOF_ > file```. I'll take a look, but we may need another command for this.

edit:
cant see a way to achieve redirect handles with the command:
```
root@DietPi:~# G_ERROR_HANDLER_COMMAND='echo 1 > test'
root@DietPi:~# $G_ERROR_HANDLER_COMMAND
1 > test
```

We'll need to avoid using ```G_RUN_CMD ``` if it contains a redirect. Then we can add a global for ```G_FILE_EXISTS``` to check for file creation afterwards.

- 🈯️ ```G_FILE_EXISTS``` https://github.com/Fourdee/DietPi/commit/c54c657b4b9a1aefc0b26c5bd13e56e8b37b44f4
![image](https://user-images.githubusercontent.com/7077026/34454132-e8373096-ed5b-11e7-862e-9070c06792a6.png)

**Comment by Fourdee** [comment]
@MichaIng 

> I loved the installation script of PiHole and had a look into their method:

Yep, i agree, very clean.

Currently, i've simply enabled as much info as possible during dev, using existing ```dietpi-notify```. We can always trim/clean/refine it at a later date.
Notify may have an issue with ```echo -n 'test...` || "\\r\\033[K"```, would need testing.

**Comment by Fourdee** [comment]
@MichaIng 
having a little play with your idea 👍 
This will only print the github info on ```G_ERROR_HANDLER_ONERROR_EXIT=1``` (default)
![image](https://user-images.githubusercontent.com/7077026/34454460-f83e3e14-ed63-11e7-93ad-33a43e028913.png)

---

Results in:

#### Required Information:
- DietPi Version | v160
- SBC Device     | oDroid C2 (aarch64) (index=12)
- Distro         | buster (index=5)
- Command        | G_AGI: nevergonnawork
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-Software

#### Expected behaviour:


#### Actual behaviour:


#### Steps to reproduce:


#### Additional logs:
```
Log file contents:
E: Unable to locate package nevergonnawork
```

**Comment by Fourdee** [comment]
test:
#### Required Information:
- DietPi Version | 160
- SBC Device     | oDroid C2 (aarch64) (index=12)
- Distro         | buster (index=5)
- Command        | G_AGI: nevergonnawork
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-Software

#### Expected behaviour:


#### Actual behaviour:


#### Steps to reproduce:


#### Additional logs:
Log file contents:
E: Unable to locate package nevergonnawork

**Comment by MichaIng** [comment]
@Fourdee 
Nice so far 👍.
- On $G_USER_INPUT => whiptail, we could add an user choice at the bottom to create the guthub ready output on demand (if user has/agrees to create github account e.g.).
- If it is possible to then create this within whiptail and automark the lines (at least on SSH it marks all parts from outside the whiptail "window" as well), we could easily add more information to the output and replace the existing dietpi-bugtracker partly with this. But yeah it should stay for exceptional hard issues, as I know there are muuuch files/configs/logs gathered and copied to your server.

**Comment by MichaIng** [comment]
@Fourdee 
I played around also a bid with process messages and error handling. Basically I merged some status messages to reduce the output lines and established a new G_DIETPI-NOTIFY option "-2" == process. This process messages will not produce a newline and will be overwritten by "ok" and "failure" outputs. Thus in the end you will only see the final results and still perhaps interesting/important "2" info messages in between.

I also made the brackets all same size. As "Processing" is a long word, this might need tuning, anyway is just an offer/idea, how we could handle our output:

After adding some "2" notifications to ownCloud installation and running some of it's commands as "G_RUN_CMD" it looks like this:
![installation](https://user-images.githubusercontent.com/28480705/34455551-9722eeea-ed81-11e7-9a1d-2ff232c8c2ac.png)

During (longer) G_AGX/G_CMD_RUN commands you will see:
![installation_process](https://user-images.githubusercontent.com/28480705/34455572-022f26b8-ed82-11e7-9513-f73526e714d4.png)

**Comment by Fourdee** [comment]
@MichaIng 

> During (longer) G_AGX/G_CMD_RUN commands you will see:

Love it, looks brilliant, very nice work! 👍 

EDIT:
Once you've finished this, send the PR and i'll take a look.
We can also remove the ```dietpi-funtime``` 😉 (it looked fun, but did absolutely nothing lol)

**Comment by k-plan** [comment]
> MichaIng commented:
> But hmm, we are sort of in the wrong issue here @Fourdee is it possible for you to copy the last comments over to https://github.com/Fourdee/DietPi/issues/1285?

Yes, sorry, it was my fault. Wrong issue here. [Done!](https://github.com/Fourdee/DietPi/issues/1285#issuecomment-354602594)

_(have deleted  double comments. Sorry for the mess.)_

**Comment by k-plan** [comment]
Next run testing fun: 😃 

![171230-0003](https://user-images.githubusercontent.com/17237601/34457158-ced8e26e-eda8-11e7-803f-15abea967dc8.gif)

#### Required Information:
- DietPi Version | v
- SBC Device     | NULL (index=11)
- Distro         | stretch (index=4)
- Command        | G_AGI: apt-transport-https apt-utils bash-completion bc bzip2 ca-certificates console-setup cron curl dbus debconf dosfstools dphys-swapfile dropbear ethtool fake-hwclock fbset firmware-realtek gnupg hdparm hfsplus htop initramfs-tools iputils-ping isc-dhcp-client locales nano net-tools ntfs-3g ntp p7zip-full parted psmisc resolvconf sudo tzdata unzip usbutils wget whiptail wput zip linux-image-armhf-odroid-xu3 crda firmware-atheros firmware-brcm80211 firmware-ralink iw rfkill wireless-tools wpasupplicant
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-PREP_SYSTEM_FOR_DIETPI

#### Expected behaviour:

[Info] Non-DietPi system

- Build a new DietPi image for my Odroid HC1 from https://oph.mdrjr.net/meveric/images/Jessie/Debian-Jessie-1.1.4-20171121-XU3+XU4.img.xz

#### Actual behaviour:


- after 1h of running and updating files .... 🕛  🕐  😢  

[Error] Unable to continue, the program will now terminate.



- after this, system is f... up, `apt-get update` won't run any more.

#### Steps to reproduce:


- download the image, write it to sd card and after booting up run: `:~# ./PREP_SYSTEM_FOR_DIETPI.sh`

#### Additional logs:
```
Log file contents:
E: Method https has died unexpectedly!
E: Sub-process https received a segmentation fault.
E: Method /usr/lib/apt/methods/https did not start correctly
```

-----------------

### General Notes:

- run `apt-get update` as first step because `a_MIN_APT_PREREQS` will fail elsewhere on a fresh image

- first run and set `dpkg-reconfigure locales` to `en_GB.UTF-8` to avoid hundert messeges like this:
```
warning: Setting locale failed.
 warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_GB.UTF-8"
    are supported and installed on your system.
warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```

- set: `passwd` to a known password like "dietpi" for user "root"

------------------

NB: - how will we handle differrent disk layouts? 
Not two partitions which first is "boot" (FAT) / second is "/" (ext4), eg one big BTRFS ?

-------------

Just like that, the fun's over for today.  😃

**Comment by MichaIng** [comment]
@k-plan 
Ah just found this one: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G150229074080
> Any OS for XU4 is fully compatible with the HC1.

And as I see the packages, the image seems to be based on Meverics?

- For this device we choose the default kernel meta package `linux-image-armhf-odroid-xu3`: https://github.com/Fourdee/DietPi/blob/testing/PREP_SYSTEM_FOR_DIETPI.sh#L553
- But it depends on ancient `linux-image-3.10.106+`: https://oph.mdrjr.net/meveric/dists/all/xu3/binary-armhf/Packages Thus the existing kernel package will removed first.
- On official Debian images, `linux-image*` packages are blocked from autoremove by `/etc/apt/apt.conf.d/01autoremove(-kernels)`, which seems not the case for Meverics image.
- Removing the only installed kernel package seems to need failing, which causes the dpkg error?
- On HC1 product page they promote the use of newest 4.14 kernel on their official linux (Ubuntu based) image, so I assume `linux-image-4.14-armhf-odroid-xu4` to be stable enough also for us? Otherwise at least we should use `linux-image-4.9-armhf-odroid-xu3`.
- xu3/xu4 naming mixed together there, both are meta packages depending on linux-image-4.XX.XX packages where no device naming appears any more, thus I think they are compatible vice versa and for HC1 as well.
- **To prevent any kernel removal issues during image preparation: Install the chosen kernel package before `G_AGA`, or identify and choose already installed kernel package. I would vote for first solution, as we then keep control over which kernel is used with DietPi.**

**Comment by k-plan** [comment]
@MichaIng 

sorry @Fourdee , no english, to time-consuming

Ja, die Odroid Welt ist etwas schwieriger ....

- Die wollen kompatibel bleiben für: XU4/XU3/HC1/MC1 und nur ein Image (+ Quellen) pflegen

> We guarantee the production of ODROID XU4/XU3/HC1/MC1 to the middle of 2020, but expect to continue production long after.

Hardkernels Images (Ubuntu) sind schon zur Zeit auf 4.14.x , da gibt es auch die Kernel source für:
https://forum.odroid.com/viewtopic.php?f=146&t=28895

Meveric bastelt aus der Kernel Source ein Debian draus und pflegt das schon seit Jahren. Sein Schwerpunkt ist die Gaming Welt ( https://forum.odroid.com/viewtopic.php?f=11&t=2684 ) daher auch die gute Unterstützung für Kodi, XBMC, Grafikausgabe über HDMI.
Der ist aber auch eine "One-Man-Show" wie Dan bisher. Daher hängt er immer etwas hinterher.
Hatte aber die gesamte Mali-T628 MP6 Hardware Grafik Unterstützung als erster laufen und lange Zeit die Nase vorn damit.

Mit dem 4.x Kernel ist es zum "Bruch" gekommen, so wie ich das bis jetzt verstanden habe.
Bis 3.x nutzen alle ODROID XU4/XU3/HC1/MC1 nur `exynos5422-odroidxu3.dtb`
Seit 4.x wir es spezifischer und man muss das richtige beim booten laden je nach verwendeten Board: 
```
exynos5422-odroidxu3-lite.dtb
exynos5422-odroidxu3.dtb
exynos5422-odroidxu4-kvm.dtb
exynos5422-odroidxu4.dtb
```

Da gibt es zwar ein paar nette Tricks für, wie man das über die `boot.ini` steuern könnte, nur haben wir das im Moment (noch) nicht (_Code Schnippsel entliehen_):

```
if test "${board_name}" = "xu4"; then setenv fdtfile "exynos5422-odroidxu4.dtb"; fi
if test "${board_name}" = "xu3"; then setenv fdtfile "exynos5422-odroidxu3.dtb"; fi
if test "${board_name}" = "xu3l"; then setenv fdtfile "exynos5422-odroidxu3-lite.dtb"; fi


if ext4load mmc 0:1 0x00000000 "/boot/.next" || fatload mmc 0:1 0x00000000 ".next"  || ext4load mmc 0:1 0x00000000 ".next"; then echo "Found mainline kernel configuration"; else setenv fdtfile "exynos5422-odroidxu3.dtb"; fi
ext4load mmc 0:1 0x44000000 /boot/dtb/${fdtfile} || fatload mmc 0:1 0x44000000 dtb/${fdtfile} || ext4load mmc 0:1 0x44000000 dtb/${fdtfile}
```

Weitere Schwierigkeit, Fourdee will es "schlank" haben und will eine FAT boot Partition, in der man einfach Konfigs editieren kann.
Beides finde ich sehr gut. Aber herzlichen Glückwunsch, wenn das Gerät von SD-Karte, eMMC, USB und HDD/SSD booten kann. Das wird dann mit der `/etc/fstab` sehr schnell unschön und die Tricksereien fangen an.

Meine persönlichen "Erfahrungen" mit den verschiedenen Kernel:

- 3.x hat eine schlechtere RAM Performance, warum auch immer.

- 4.9.x ist mit dem RAM der schnellste

- 4.14.x ist etwas langsamer bei meinen Tests

Schreib/Lesegeschwindigkeit (SD-Karte), RAM Größe und Schreib/Lesegeschwindigkeit, machen bei den Devices, neben Prozessortakt und Kerne Anzahl den größten Unterschied aus.

Klar haben neuere Kernel meist bessere Unterstützung für "neue Features", doch persönlich brauche ich die wenigsten davon. Würde also vorerst zu 4.9.x bei XU4 tendieren.
Da wird aber von Seiten Hardkernel erst einmal nichts mehr kommen.

Ordoid C1/C1+/C2 schenke ich mir an dieser Stelle erst einmal. Das sind noch ganze andere Nummern mit anderen Schwierigkeiten.

**Comment by k-plan** [comment]
@Fourdee 
@MichaIng 

Only for clarification: 
I like your work so much. You are on a good trip and I think and hope you have finally success.
Only difficulties arising from a new way.
Keep one's tail up boys and girls. 😃

**Comment by MichaIng** [comment]
https://github.com/Fourdee/DietPi/issues/1357

**Comment by Fourdee** [comment]
Testing/notes: https://github.com/Fourdee/DietPi/pull/1364
- Processing only gets replaced by ok/failure, with ```G_RUN_CMD``` and few others. Ah i see, ```NOTIFY -2``` rollout.
- ```G_CHECK_URL``` does not replace
- 🈯️ https://github.com/Fourdee/DietPi/commit/d5b7c01d0c95ce9ac846d44adf02a6ae0f9ab8cd ```G_CHECK_URL``` hangs on a failed connection. No result. Due to error output being printed in background. Due escaping overwrite string, not needed.
- 🈺 Replace does not replace, if output hits screen width :
-- Maybe another idea is to use ```echo -en "\033[1A 1 \033[0m"``` which will print on the previous line?
```
root@DietPi:~# G_RUN_CMD systemctl enable dietpi-fs_partition_resize.service
 [Processing] Running command: systemctl enable dietpi-fs_partition_resize.servi [    Ok    ] systemctl enable dietpi-fs_partition_resize.service

root@DietPi:~# G_RUN_CMD echo 1
 [    Ok    ] echo 1
```

**Comment by Fourdee** [comment]
Notes: https://github.com/Fourdee/DietPi/pull/1365
- @MichaIng Looks much better 👍 
- 🈯️ Fixed with log file generation. ~```G_CHECK_URL http://google.comxxxx``` hangs, stuck in BG. kill ```tail``` process, whip appears.~
![image](https://user-images.githubusercontent.com/7077026/34480587-36acd6f4-efa5-11e7-96a0-e8b383c2c4cc.png)

**Comment by Fourdee** [comment]
Notes:
- Incorrect usermsg (not cleared from previous)
- Missing dietpi-software info 
```
 [  Error   ] DietPi-Software: G_AGI: mosquitto
 [   Info   ] exit_code = 100
 [   Info   ] VERSION:v6.-1 | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4
 [   Info   ] Log file contents:
E: Failed to fetch http://repo.mosquitto.org/debian/pool/main/m/mosquitto/mosquitto_1.4.12-0mosquitto1_armhf.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
 [   Info   ] User message:
Connection failed while trying to access: http://dietpi.com/downloads/binaries/all/libwebsockets3_1.2.2-1_armhf.deb. The URL may be offline, or invalid.
 [   Info   ] If problems persist, please report this to DietPi for investigation, including a screenshot of this error! (https://github.com/Fourdee/DietPi/issues).

```

--- 


```G_ERROR_HANDLER_ONERROR_USERMSG``` must never be defined changed in ```dietpi-globals``` additional functions. It must only be exported by the sourcing script, to ensure it never gets overwritten.

The downside:
- ```G_ERROR_HANDLER_ONERROR_USERMSG``` will be displayed for any future errors, regardless if its outdated. Unless we manually add ```unset G_ERROR_HANDLER_ONERROR_USERMSG``` in the sourcing script after each event (messy)

Solution for now, remove ```G_ERROR_HANDLER_ONERROR_USERMSG``` from scripts. See if we can implement this better in the future.

**Comment by Fourdee** [comment]
I'll mark this as completed. Will reopen if required.
