### ISSUE TITLE
DietPi-Software | Pi-Hole: Use the updated block page?

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1313]
> ![image](https://user-images.githubusercontent.com/7077026/34088585-2881a9d8-e3a2-11e7-85b8-237fb9948343.png)
https://github.com/Fourdee/DietPi/issues/1298#issuecomment-352314748

**Comment by k-plan** [comment]
@Fourdee 

Nice, thanks! 👍 

------------------

> Install by running :

`curl -sSL https://install.pi-hole.net | bash`

![171218-0004](https://user-images.githubusercontent.com/17237601/34109449-e74e626e-e403-11e7-9894-349af0d1363b.gif)

```
root@RPi-Zero_W-Stretch:~# ls -lah /var/www/
total 16K
drwxr-xr-x  4 root     root     4.0K Dec 18 12:45 .
drwxr-xr-x 12 root     root     4.0K Dec 18 12:44 ..
drwxr-xr-x  2 root     root     4.0K Jan 14  2017 cgi-bin
drwxrwxr-x  4 www-data www-data 4.0K Dec 18 13:24 html
```

```
root@RPi-Zero_W-Stretch:~# ls -lah /var/www/html/
total 20K
drwxrwxr-x 4 www-data www-data 4.0K Dec 18 13:24 .
drwxr-xr-x 4 root     root     4.0K Dec 18 12:45 ..
drwxr-xr-x 7 root     root     4.0K Dec 18 12:44 admin
-rw-r--r-- 1 root     root     3.3K Dec 18 12:46 index.lighttpd.orig
drwxr-xr-x 2 root     root     4.0K Dec 18 13:24 pihole
```

```
root@RPi-Zero_W-Stretch:~# ls -lah /var/www/html/pihole/
total 40K
drwxr-xr-x 2 root     root     4.0K Dec 18 13:24 .
drwxrwxr-x 4 www-data www-data 4.0K Dec 18 13:24 ..
-rwxr-xr-x 1 root     root      13K Dec 18 13:24 blockingpage.css
-rwxr-xr-x 1 root     root      14K Dec 18 13:24 index.php
```

-----------------------

> Install by running :

`dietpi-software install id 93`

![171215-0001](https://user-images.githubusercontent.com/17237601/34109762-e50ed0b4-e404-11e7-9010-63f33ae09c37.gif)

```
root@NanoPi-Neo:~# ls -lah /var/www/ | grep admin
lrwxrwxrwx  1 www-data www-data   19 Dez 11 20:11 admin -> /var/www/html/admin
lrwxrwxrwx  1 www-data www-data   19 Dez 11 20:11 pihole -> /var/www/html/admin
```

-------------------------



Can I help you, eg. provide additional informations or config files ?


Think, where is or will be a problem to get:

`pihole -r`

and

`pihole -up`

to run proper on lighttp and all different web stacks.
_[ provide a own update function ( 👍  )  or back to your own fork ( 👎  ) ...]_

**Comment by LexiconCode** [comment]
A bit off-topic. Would there be a possibility to specify the port that Pi Hole uses for the web administration panel? That way other services can utilize port 80.

**Comment by MichaIng** [comment]
@LexiconCode 
The current implementation should allow other services to use port 80 as well, as PiHole web ui ist just available via `.../pihole` sub location. But currently PiHole reconfiguration and update breaks this, as it reapplies it's own Lighttpd config, at least if there is an update for the web ui available.
_€: Ah if really another process/service (besides webserver) needs to bind to port 80, then the webserver that runs Pi-hole web interface, needs to use another port, thus vhosts need to be adjusted e.g. But I would always leave webserver at 80 (+443) and then better run all other server on other ports._

Hui, we have now 3 issues opened about basically the same topic:
- https://github.com/Fourdee/DietPi/issues/1313
- https://github.com/Fourdee/DietPi/issues/1375
- https://github.com/Fourdee/DietPi/issues/1623

Need to merge this, collecting all helpful information...

As PiHole is great stuff that is widely used by our users, I wan't to focus a bid to get this solved, e.g. via pihole service hooks, as mentioned within the other topic. For practical reasons just need a quick possibility to fake a lower version for `pihole -up` 😉.

**Comment by MichaIng** [comment]
Close in favour of https://github.com/Fourdee/DietPi/issues/1696
