### ISSUE TITLE
Suggestion: version comment in dietpi.txt

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1317]
Add version number in dietpi.txt so we can double check, that the file works with the dietpi version.
Or will you add another compatible check in the setup process?

**Comment by Fourdee** [comment]
@tatoosh 

> Or will you add another compatible check in the setup process?

For DietPi v160 (when released):
We've added a check to ensure any missing ```dietpi.txt``` entries from outdated versions, are now verified and added if needed. This runs during updates (eg: first run of device)

https://github.com/Fourdee/DietPi/issues/1292#issuecomment-350901663

**Comment by tatoosh** [comment]
thx that is enough i think.
