### ISSUE TITLE
[dupe] Suggestion: multi WLAN SSID for dietpi

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1321]
I am using different SSIDs and can change the wpa_supplicant file.
So it would be nice to administrate different SSIDs for **dietpi-config** and also in **dietpi.txt**.

**Comment by Fourdee** [comment]
@tatoosh 

Thanks for the request, we already have another ticket for this, please see https://github.com/Fourdee/DietPi/issues/368

I'll mark this one as closed.
