### ISSUE TITLE
Loosing WIFI by installing software

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1323]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? - 159
- SBC Device (EG: RPi 3)? - RPi Zero
- Power supply used (EG: 5v 1A RAVpower)? - 2A Powerbank
- SD card used (EG: Sandisk ultra)? - Sandisk ultra 32GB
- Distro (EG: Jessie) | ```uname -a```? - Linux lux 4.9.70+ 1068 Mon Dec 18 21:54:13 GMT 2017 armv6l GNU/Linux

#### Can this issue be replicated on a fresh installation of DietPi?
I am using two WLAN SSIDs in wpa_suppicant and by installing software with **dietpi-software** my ssh connection will be dropped. Also the ping to the RPi will be lost.

to reproduce: i wanted to install Rpi GPIO.

![image_20171219_143115](https://user-images.githubusercontent.com/3670907/34159779-b13b79f6-e4ca-11e7-8de2-c2714b8150f3.png)

**Comment by tatoosh** [comment]
after long waiting the session comes back!

**Comment by Fourdee** [comment]
@tatoosh 

Fixed for v160, however, existing users will need to disable the service control, before updating:
https://github.com/Fourdee/DietPi/issues/1288#issuecomment-351613165

**Comment by tatoosh** [comment]
Great, thx for issue linking @Fourdee
