### ISSUE TITLE
dietpi shutdown/reboot very slow

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1327]
Updates to strecth dietpi 159 my Rpi3.
Booting is very fast but a reboot tooks very long.
Screen says "Dietpi Ramdisk shutting down". 

What can i do to improve that?

**Comment by Fourdee** [comment]
@tatoosh 

Should not take longer than 1 second to save RAMdisk to disk. We'll try to replicate.

Which SD card/PSU are you using?

**Comment by tatoosh** [comment]
I am using this sd-card: SanDisk Ultra 16GB microSDHC Speicherkarte + Adapter bis zu 98 MB/Sek., Class 10
Link: https://www.amazon.de/gp/product/B073S9SFK2/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

**Comment by tatoosh** [comment]
I could not reproduce it on my other Rpi3. at the moment ...
Last message i see is
> [OK] Stopped DietPi-Ramdisk. 

So it must be a service after that.
Then i can see an error but the reboot comes after that. Can i store the information and see it like dmesg?

**Comment by tatoosh** [comment]
Reinstalled everything, no problem. 
Justed change from 16GB SanDisk to 32GB Sandisk Card.

**Comment by tatoosh** [comment]
Oh after some reboots the error comes back :(
Now i see the process:
> A stop job is running for Music Player Deamon

How to kill the service on reboot?

```mpd -V
Music Player Daemon 0.20.11
```

**Comment by tatoosh** [comment]
Also ```service mpd stop``` is delayed. I think i have to kill the process !?

**Comment by tatoosh** [comment]
Issue solved

Problem was my change of /etc/mpd.conf for the playlist folder. There was a file system permission issue. 
But u can not see this in mod.log :(
