### ISSUE TITLE
DietPi-Software | Universal Media Server

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#1328]
[Universal Media Server](http://www.universalmediaserver.com/) is an open source DLNA-compliant UPnP Media Server. Minimal configuration for more than 50 different devices.

Universal Media Server is similar to Plex and Emby except the premium features that you pay for in the latter two programs are free in Universal Media Server. Granted it doesn't have cloud storage services..who cares?

[Guide ](https://www.htpcguides.com/install-universal-media-server-on-ubuntu-14-x/)Ubuntu Raspberry Pi 3

**Comment by WolfganP** [comment]
I can't speak for Emby, but I moved from UMS to Plex a while ago and not planning to return. 
UMS dependency in Java kills any installation in small devices like Raspberry, and Plex DLNA services are included for free as in UMS and allow for custom profiles, so no advantage in there either. 
Besides, the development pace of Plex is really high, and the ability to add many active developed plugins to the server is also a plus for me.

**Comment by LexiconCode** [comment]
Do pay for DVR using plex? @WolfganP 

I can't speak for performances that's part of testing.  I can say that it core program is up-to-date and being well-maintained. There are a lot of features that are in Plex and Emby that you have to pay a premium for each month or by $120 lifetime license. DVR and guided data being foremost features I'm personally interested in UMS that are free.
As for a [comparison ](http://www.universalmediaserver.com/comparison/) to Plex and other services.

I will test on an Odroid C2 with the Roku 3 as an endpoint.

**Comment by WolfganP** [comment]
Not a DVR user, just using my media server to distribute media inside my LAN with many diff clients (from android boxes to PCs to smartTVs), which I want to offer the richest experience.
Not using DVR features, and if I decide to go there, most probably will use a targeted project like https://github.com/tvheadend/tvheadend and look for integrations with my media server (via native hookup or plugin alternative)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by echable9999** [comment]
Support UMS on Odroid.
