### ISSUE TITLE
Rock64 | rootFS re-partition/resize no effect

### ISSUE THREAD

**Issue by xnathanh** [MichaIng/DietPi#1333]
i have 64gb sdcard,but i only have <10gb,
```
root@DietPi:~# df -lh
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           393M   11M  383M   3% /run
/dev/mmcblk1p7  476M  452M     0 100% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
tmpfs           2.0G  4.0K  2.0G   1% /tmp
tmpfs            10M  1.5M  8.6M  15% /DietPi
tmpfs            20M   16K   20M   1% /var/log
/dev/mmcblk1p6  100M   42M   59M  42% /boot/efi
tmpfs           393M     0  393M   0% /run/user/0
```

```
root@DietPi:~# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk1     179:0    0 59.5G  0 disk 
├─mmcblk1p1 179:1    0  3.9M  0 part 
├─mmcblk1p2 179:2    0   64K  0 part 
├─mmcblk1p3 179:3    0    4M  0 part 
├─mmcblk1p4 179:4    0    4M  0 part 
├─mmcblk1p5 179:5    0    4M  0 part 
├─mmcblk1p6 179:6    0  112M  0 part /boot/efi
└─mmcblk1p7 179:7    0  550M  0 part /

```

**Comment by Fourdee** [comment]
@xnathanh 

Thanks for the report 👍 

Looks like the rootFS re-partition/expansion has failed. Which SBC device please?

**Comment by MichaIng** [comment]
@xnathanh 

Ui, jep partitioning went totally wrong. Just to sort issues out: You did flash image from dietpi.com just by Etcher onto your SD, which was then formatted to contain 2 partitions?

**Comment by xnathanh** [comment]
@Fourdee is rock64 4g with 64gb sd card(SanDisk SDSQUSC-064G-APCIA Ultra Plus 64GB MicroSDXC UHS-1 Class10)

**Comment by Fourdee** [comment]
@xnathanh 

Thanks 👍 

I'll try to replicate on my system.

> which was then formatted to contain 2 partitions?

@MichaIng 

Rock image has 7 partitions, although, will be a good test for our new PREP_SYSTEM 😄

**Comment by Fourdee** [comment]
Unable to replicate with current image:
```DietPi_v156_Rock64-arm64-(Stretch).img```

Putting this down to a possible instability issue with SD card and/or PSU used.

I'll mark as closed, please reopen if required.
