### ISSUE TITLE
DietPi-Software | new version of UrBackup server available (2.1.20)

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#1335]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 159
- SBC Device (EG: RPi 3)? Odroid C2
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?  aarch64 Jessie

#### Extra details:

There is a new version of UrBackup server available (2.1.20). Download it [here](http://www.urbackup.org/download.html).

**Comment by Fourdee** [comment]
@LexiconCode 

Many thanks for heads up 👍 

2.1.20 install available in v160 update.
