### ISSUE TITLE
DietPi-Software | Shairport-sync fails due to libssl1.0

### ISSUE THREAD

**Issue by stefanprobst** [MichaIng/DietPi#1337]
Installation of shairport-sync fails on stretch, because it refers to jessie's libssl version in dietpi-software at line 5924/5929/5934.
Also: Maybe we can use the shairport-sync version that is now officially in the stretch repos?

**Comment by Fourdee** [comment]
@stefanprobst 

Thanks for report 👍 

Fixed in v160. To resolve now (RPi2/3 and other ARMv7):
```
wget http://dietpi.com/downloads/binaries/all/libssl1.0.0_1.0.1t-1+deb8u7_armhf.deb -O package.deb
dpkg -i package.deb
dietpi-software install 37
```
