### ISSUE TITLE
DietPi-Software | Add LEPP

### ISSUE THREAD

**Issue by keiser1080** [MichaIng/DietPi#134]
Hi,

new software suggestion Nginx   / postgrees / Php.
Why segregation of postgresql :)
posgresql has lower memory footprint.

Let my know if i can help givin installation process of testing the script.

**Comment by Fourdee** [comment]
Hi Keiser,

Unfortunately, I do not have the time to look into your request at the moment. 
However, If you have a working installation method for this stack, by all means let me know and I'll see if we can get it added into DietPi.

**Comment by xenfomation** [comment]
@Fourdee and @keiser1080 --

Since I have been working with the webstacks recently, I will take a look at the process this week (manually) and follow up to see about converting it to an installable option.

Cheers!

**Comment by keiser1080** [comment]
If you can wait i can sens a bash script semi automates next week, si you
can addapt thé script?

**Comment by xenfomation** [comment]
Sure!

**Comment by Fourdee** [comment]
Outdated and no progress, marking as closed. Please reopen if required.
