### ISSUE TITLE
DietPi-Image | OrangePI PC: image does not boot

### ISSUE THREAD

**Issue by glogiotatidis** [MichaIng/DietPi#1347]
## Creating a bug report/issue:
OrangePI PC image does not boot. Serial console reports "** Unrecognized filesystem type ** ext2"

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? v145
- SBC Device (EG: RPi 3)? OrangePi PC v1.2
- Power supply used (EG: 5v 1A RAVpower)? 5v 2A
- SD card used: Kingston Class 10 and Sandisk Ultra Class 10

#### Actual behaviour:
Does not boot

#### Extra details:
- Managed to boot with the Orange Pi One image.
- Armbian for OrangePi PC works fine.

**Comment by Fourdee** [comment]
@glogiotatidis 

Thanks for the report 👍 We'll try to replicate.

**Comment by Fourdee** [comment]
I'll create the updated v6.0 image today (https://github.com/Fourdee/DietPi/issues/1385#issue-287129015), test, then link here.

**Comment by Fourdee** [comment]
OPi PC image re-created:
http://dietpi.com/downloads/testing/v6.0/DietPi_OPiPC-ARMv7-Stretch.7z

Tested and boots fine. Please use the image above.

Marking as resolved.

**Comment by glogiotatidis** [comment]
tested as well and boots. Thanks for the quick fix!
