### ISSUE TITLE
https not working for Punycode domain

### ISSUE THREAD

**Issue by janbildsoehansen** [MichaIng/DietPi#1356]
#### Required Information:
- DietPi Version | DietPi_v158_RPi-armv6-(Stretch)
- SBC Device (EG: RPi 3)? RPi 3
- Power supply used (EG: 5v 1A RAVpower)? yes
- SD card used (EG: Sandisk ultra)? yes
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?  ?????

#### Expected behaviour:

letsencrypt dont work prober fist it say ponycode to bildsøetech.dk then i ajust the adress to
 xn--bildsetech-4cb.dk and it works but when i go to https it dont work

what to doo..???

**Comment by Fourdee** [comment]
Marking as closed, outdated.
