### ISSUE TITLE
issue with plex installation

### ISSUE THREAD

**Issue by pgferr** [MichaIng/DietPi#1358]
## Creating a bug report/issue:
[dietpi-software_apt.log](https://github.com/Fourdee/DietPi/files/1594861/dietpi-software_apt.log)
<img width="471" alt="2017-12-30 21_50_27-192 168 1 6 - kitty" src="https://user-images.githubusercontent.com/34972686/34458039-2775181e-edc4-11e7-8013-f9b0774b0eaf.png">

#### Required Information:
- DietPi Version: DietPi_OdroidC2-armv8-(Stretch).7z
- SBC Device: OdroidC2
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used:Sandisk ultra
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by MichaIng** [comment]
Just to support investigation:
- I guess you tried `apt --fix-broken install` as suggested by the log?
- https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L6402
- http://dev2day.de/pms/dists/stretch/main/binary-armhf/Packages
- For now I don't see where the dependency issue could come from. `libc6` and `curl` should be both clearly installed. But I don't know which then again needs `:armhf` packages.

**Comment by pgferr** [comment]
i think that i have solved:

export LD_LIBRARY_PATH=/lib/arm-linux-gnueabihf:/usr/lib:/usr/local/lib:/opt/vc/lib
apt-get install libc6:armhf

**Comment by MichaIng** [comment]
@pgferr 
Ah so it was related to the LD_LIBRARY_PATH issue, as mentioned here: https://github.com/Fourdee/DietPi/issues/1329

I will mark as closed, reopen on demand.
