### ISSUE TITLE
DietPi | Whiptail: Looks not beautiful on Jessie, especially software list 

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1367]
I think this was not pre v6.0 testing, but the border, made of characters instead of lines, was as far as I remember. On Stretch everything is fine, but on Jessie:

![whiptail](https://user-images.githubusercontent.com/28480705/34493447-34d033f2-efec-11e7-9363-71a7614c9397.png)

- Tested on fresh v6.0 VirtualBox image.

**Comment by Fourdee** [comment]
@MichaIng 

Is ```en_GB.UTF-8``` installed?
```locale```

**Comment by MichaIng** [comment]
@Fourdee 
Indeed missing language setting was the problem. `dpkg-reconfigure locales` (as well as dietpi-config language setting), manually run `locale-gen` and `update-locale` didn't really set the language. `/etc/default/locale` contains the right values, but `locale` does still show POSIX on all variables. Reboot solved it finally.

Might be due to locales errors in preparation script. Will try the fixed version later.

**Comment by MichaIng** [comment]
Jep, seems to be resolved with locales fix. I will keep an eye of this on future Jessie tests, but close for now.
