### ISSUE TITLE
kodi issue:     "Package 'kodi-odroid:armhf' has no installation candidate"

### ISSUE THREAD

**Issue by pgferr** [MichaIng/DietPi#1391]
## Creating a bug report/issue:
 i cannot install kodi. The installation don't go on and i have this message:Package 'kodi-odroid:armhf' has no installation candidate

#### Required Information:
- DietPi Version: 159
- SBC Device: odroid c2
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro: debian stretch | Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux

#### Additional Information (if applicable):
<img width="494" alt="2018-01-13 11_49_30-dietpi _ fuzon view topic - dietpi-software _ details for all installation opt" src="https://user-images.githubusercontent.com/34972686/34905561-605e3cae-f85b-11e7-9228-c92fb046bd45.png">
<img width="461" alt="2018-01-13 11_48_33-root dietpi_" src="https://user-images.githubusercontent.com/34972686/34905566-7406f958-f85b-11e7-808d-216a5bfe2cdf.png">

**Comment by Fourdee** [comment]
@pgferr 

Thanks for the report 👍 

Kodi is currently not available for Debian Stretch on the C2:
https://github.com/Fourdee/DietPi/issues/1032#issue-238395824

You'll need to use the Jessie image for Kodi/GPU usage:
http://dietpi.com/download

**Comment by Fourdee** [comment]
As we no longer offer Stretch images for Odroid, due to limitations with available Meveric repos, where the Kodi binaries are installed from . I'll mark this as closed.
