### ISSUE TITLE
DietPi-Hosting | dietpi.com and fuzon.co.uk are down / not reachable / offline

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1393]
@Fourdee 

[dietpi.com](http://dietpi.com/)

```
guest@dnstools.ch:~> ping dietpi.com 
PING dietpi.com (185.101.92.145) 56(84) bytes of data. 
From 185.219.208.90 icmp_seq=1 Time to live exceeded 
 
--- dietpi.com ping statistics --- 
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

[fuzon.co.uk](http://fuzon.co.uk/meveric)

```
guest@dnstools.ch:~> ping fuzon.co.uk 
PING fuzon.co.uk (185.101.93.34) 56(84) bytes of data. 
From 185.219.208.90 icmp_seq=1 Time to live exceeded 
 
--- fuzon.co.uk ping statistics --- 
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

Checked local and via online tools like [dnstools.ch](http://en.dnstools.ch/) , [pingtool.org](http://pingtool.org/) , [ping.eu](http://ping.eu/)

**Comment by k-plan** [comment]
@Fourdee 

do some deeper research:

> ### Move of Infrastructure
> 
> As we want to constantly improve our quality, we have decided to move our Infrastructure on **Jan 14, 2018.**
> 
> Bla bla bla...
> 
> 
> Because of this and many other reasons we **will uninstall, pack, transport and install our hardware on Jan 14, 2018 starting at 17:00 (UTC). The maintenance may take up to 12 hours** depending on traffic etc.
> 
> We understand that a 12 hour maintenance is a heavy service interruption but we would like to take the next step with you to offer even better products at best cost.

https://status.myvirtualserver.com/

Leave it open for information, until it will work again.
Please close if needed. Thanks.

**Comment by Fourdee** [comment]
@k-plan 

Thanks for posting this 👍 

Had similar reports on twitter. Seems to be all up and running again now 🥂 I'll mark as closed.
