### ISSUE TITLE
Online Doc's | Linux Dash incorrect URL link (shows demo)

### ISSUE THREAD

**Issue by RmG152** [MichaIng/DietPi#1411]
#### Required Information:
- DietPi Version | 159
- SBC Device: Orange Pi Zero / Raspberry Pi 3
- Power supply used: Usb / usb hub Anker 60w
- SD card used: Samsung evo / Sandisk Ultra
- Distro:
Linux DietPiVoice1 3.4.113-sun8i #2 SMP PREEMPT Fri Mar 10 18:24:50 GMT 2017 armv7l GNU/Linux
Linux DietPi 4.9.62-v7+ #2 SMP Fri Nov 17 23:52:26 GMT 2017 armv7l GNU/Linux

#### Additional Information (if applicable):
- Software title? Linux Dash
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Expected behaviour:
Show Current system information (OS, processes, hardware info, etc(.

#### Actual behaviour:
Board is showing demo info:
https://afaqurk.github.io/linux-dash/#/system-status

#### Steps to reproduce:
Download DietPI
Install
Install LinuxDash from dietpi-config
Enter LinuxDash

#### Did you submit a ```dietpi-bugreport```?
No

#### Extra details:
NA

**Comment by gotttlieb** [comment]
I confirm this behaviour in Odroid XU4
I have take a look inside, and the problem is the ```/var/www/linuxdash/demo.js``` file.
Seems that Dietpi is not creating the correct configs at installation.

If i delete the script call from index.html an error rises form browser console: 
```linuxDash.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.4/$injector/modulerr?p0=linuxDashDemo&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.4%2F%24injector%2Fnomod%3Fp0%3DlinuxDashDemo%0A%20%20%20%20at%20https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A6%3A416%0A%20%20%20%20at%20https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A21%3A334%0A%20%20%20%20at%20a%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A20%3A483)%0A%20%20%20%20at%20https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A21%3A218%0A%20%20%20%20at%20https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A35%3A76%0A%20%20%20%20at%20r%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A7%3A302)%0A%20%20%20%20at%20g%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A34%3A428)%0A%20%20%20%20at%20Lb%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A38%3A146)%0A%20%20%20%20at%20d%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A17%3A339)%0A%20%20%20%20at%20rc%20(https%3A%2F%2F192.168.1.60%2Flinuxdash%2Fapp%2FlinuxDash.min.js%3A18%3A151)
    at linuxDash.min.js:6
    at linuxDash.min.js:35
    at r (linuxDash.min.js:7)
    at g (linuxDash.min.js:34)
    at Lb (linuxDash.min.js:38)
    at d (linuxDash.min.js:17)
    at rc (linuxDash.min.js:18)
    at Gd (linuxDash.min.js:16)
    at linuxDash.min.js:249
    at HTMLDocument.a (linuxDash.min.js:163) 
```

**Comment by RmG152** [comment]
This is working well:
/linuxdash/app/

This one not:
/linuxdash/

**Comment by gotttlieb** [comment]
I suggest to change the Documentation to avoid this confusion  and delete this dummy data form dietpi instalation. 
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=20#p108

**Comment by Fourdee** [comment]
@RmG152 

Thanks for the report 👍 

We'll investigate/resolve when possible.

**Comment by Fourdee** [comment]
Updated documentation to reflect the correct URL link (as per @gotttlieb suggestion) 👍 
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=108#p108
