### ISSUE TITLE
DietPi-Software | ownCloud/Nextcloud: v159 => v6.0 migration script

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1413]
+ Added backup script to separate branch, not intended for merging, just for download/review: https://github.com/Fourdee/DietPi/blob/dietpi-cloud-migration/dietpi-cloud-migration
+ Script could be provided to users via forum + https://github.com/Fourdee/DietPi/issues/1355
+ Could be further implemented into e.g. dietpi-backup/dietpi-software uninstall.
+ Current idea: dietpi-software install ownCloud/Nextcloud will check for existing backups and restore in case. PR for this is on the way 😃.

**Comment by MichaIng** [comment]
Automatic recovery is ready for testing: https://github.com/Fourdee/DietPi/pull/1414

On my Stretch VM following schedules worked well:
🈯️ Install ownCloud/Nextcloud ▶️ Use migration script ▶️ Uninstall without backup creation ▶️ Install
🈯️ Install ownCloud/Nextcloud ▶️ Uninstall (with automated backup creation) ▶️ Install
🈯️ Install ownCloud/Nextcloud ▶️ Use migration script ▶️ Uninstall ▶️ Install
🈯️ Install ownCloud/Nextcloud ▶️ Reinstall ownCloud/Nextcloud (with existing installdir and database)
🈯️ Use migration script on ownCloud/Nextcloud with and without optional backup directory, to move datadir to.

**Comment by keithellis74** [comment]
Does this migration script also transfer across LetsEncrypt keys/scrips?

**Comment by Fourdee** [comment]
@keithellis74 

Not as far as i'am aware, this script is only for NC/OC migration.

**Comment by MichaIng** [comment]
@keithellis74 
Yes, it only migrates NC/OC, as the instances are quite independent from webserver/SSL configurations.

To transfer LetsEncrypt info, you just need to transfer the `/etc/letsencrypt` folder, as far as I know, where keys and account infos are inside.

**Comment by MichaIng** [comment]
Announcement about the migration script: http://dietpi.com/phpbb/viewtopic.php?f=9&t=2734

Note:
- As always, do carefully check the output of the script and recheck the made backup.
- Carefully read the instructions given in the announcement above.

**Comment by Fourdee** [comment]
@MichaIng 
Many thanks for doing this for our users, really appreciate it 👍 

I'll mark this as closed for now, please reopen if required.
