### ISSUE TITLE
DietPi-Software | Running uninstall cmd with several arguments multiplies uninstall loop

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1416]
In the code of unattended (# dietpi-software uninstall $@) uninstallation, the code contains a doubled for loop through arguments (software ids): https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L14026-L14047

This leads to doubled uninstall loop on 2 arguments and tripled on 3 etc. Whiptail uninstallation is not affected.

**Comment by Fourdee** [comment]
@MichaIng 

Good find 👍 Thats a nasty one lol.

Resolved with: https://github.com/Fourdee/DietPi/commit/6ea69350b944c2be5105a289a963986f2478416e

**Comment by Fourdee** [comment]
Tested fine 🈯️ Will mark as closed.
