### ISSUE TITLE
Tonido | Fails to start due to missing libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1432]
https://github.com/Fourdee/DietPi/issues/1428#issuecomment-361168626

> https://github.com/Fourdee/DietPi/issues/1428#issuecomment-361240375

**Comment by MichaIng** [comment]
Fix with: https://github.com/Fourdee/DietPi/pull/1433

**Comment by Fourdee** [comment]
@MichaIng 

Legend 👍 

I'll host the debian binaries on dietpi.com. In the past, Debian simply remove older versions and results in dead URL links. Best to avoid it :)

I'll edit PR with new links

**Comment by Fourdee** [comment]
Merged, tested install:
- 🈯️ RPi Stretch
- 🈯️ C2 (ARMv8 disabled install)
- 🈯️ x86_64

**Comment by Fourdee** [comment]
@MichaIng 

All good, nice one 👍
