### ISSUE TITLE
XRDP won't start at startup

### ISSUE THREAD

**Issue by Gokujo** [MichaIng/DietPi#1442]
Hey,
I created a new user for working not as root on my device and I got this problem, that xrdp do not start automatically but manuall with
`systemctl restart xrdp.service`

#### Required Information:
- DietPi Version: 6.1
- SBC Device: RPi 3
- SD card used: Sandisk
- Distro: Strech ARMv6

**Comment by Fourdee** [comment]
@Gokujo 

Thanks for the report, we'll try to replicate 👍

**Comment by Gokujo** [comment]
Sorry, but it worked well with only root.

**Comment by Fourdee** [comment]
@Gokujo 

> Sorry, but it worked well with only root.

Ah I see. Try running it under user ```dietpi``` (account has same permissions are ```pi```), should be fine.

Either way, i'll test the installation, due to: https://github.com/Fourdee/DietPi/issues/1069

**Comment by Gokujo** [comment]
the same issue. 
here are logs from xrdp:
`[20180131-13:31:23] [DEBUG] libscp initialized
[20180131-13:31:23] [INFO ] starting xrdp-sesman with pid 443
[20180131-13:31:23] [ERROR] bind error on port '3350': 22 (Invalid argument)
[20180131-13:31:23] [DEBUG] Closed socket 7 (AF_INET6 :: port 0)
`

I tried now to install **TightVNC** - xrdp don't start automatically

**Comment by Fourdee** [comment]
@Gokujo 

I've updated the online doc, verified fresh install working on RPi 3 with:
- Module = Xorg
- Username = root
- Password = dietpi

It also runs with ```dietpi``` user and password, however few errors and DietPi scripts will not function as we only support ```root``` login's with desktop currently.

There are plans to implement this in the future: https://github.com/Fourdee/DietPi/issues/896

**Comment by Gokujo** [comment]
Ok, to run raspberry on root isn't good idea 'cause some modules need an ordinary user, like wsgi.
Temporary I solved this problem with bash script on startup

**Comment by Fourdee** [comment]
Completed.
