### ISSUE TITLE
Native PC BIOS image | Retry

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1448]
> https://dietpi.com/phpbb/viewtopic.php?p=10535#p10535

**Comment by Fourdee** [comment]
Tested:
http://dietpi.com/downloads/images/DietPi_NativePC-BIOS-x86_64-Stretch.7z
- 🈯️ USB mem stick

**Comment by Fourdee** [comment]
NB: missing intel-microcode

**Comment by elvis501** [comment]
Why this link is broken?

http://dietpi.com/downloads/images/DietPi_NativePC-BIOS-x86_64-Stretch.7z

**Comment by Joulinar** [comment]
because the image was update to Buster mid of 2019. The Stretch image did not exist anymore.

Alle images are located at https://dietpi.com/downloads/images/

or

https://dietpi.com/#download
