### ISSUE TITLE
Dietpi 6.1 shortcuts ?

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#1456]
I installed Dietpi v6.1 on rpi2.
But now i can't use dietpi-commands anymore.
I have overwritten .bashrc - maybe that is the reason??

![grafik](https://user-images.githubusercontent.com/3670907/35768539-9222afba-08fd-11e8-9845-1966542a0f7d.png)

**Comment by Fourdee** [comment]
@tatoosh 

The globals are loaded after completion of the login script, you must wait for it to complete. Did you CTRL+C straight after logging in?

You can manually load the globals with:
```
. /DietPi/dietpi/func/dietpi-globals
```

---

Verify the following matches:
```cat /root/.bashrc```
Should have the following at bottom.
```
/DietPi/dietpi/login
. /DietPi/dietpi/func/dietpi-globals
```

**Comment by tatoosh** [comment]
thx @Fourdee - i copied my .bashrc from dietpi v159 ... i add this line so everythinks works fine!
