### ISSUE TITLE
OrangePi Zero Image can't read partition to edit config 

### ISSUE THREAD

**Issue by RmG152** [MichaIng/DietPi#1465]
#### Required Information:
- **DietPi Version:** v6 and v6.1

- **SBC Device:** OrangePi Zero 
- **Power supply used:** 3A suply
- **SD card used:** Sandisk Ultra 32gb
- **Distro** : -

**#### Additional Information (if applicable):**
**- Software title?** DietPi
**- Can this issue be replicated on a fresh installation of DietPi?**
Yes

**#### Expected behaviour:**
1. Burn img to SD (Etcher)
2. Reconect SD to computer (windows)
3. Open 1st partition to edit wifi config

**#### Actual behaviour:**
1. Burn img to SD (Etcher)
2. Reconect SD to computer (windows)
3. Windows can't recognice partition 

#### Steps to reproduce:
1. Burn img to SD (Etcher)
2. Reconect SD to computer (windows)
3. Try to open SD

**#### Did you submit a ```dietpi-bugreport```?**
- 

**#### Extra details:**
Works well with 159

**Comment by Fourdee** [comment]
Hi,

ARMbian based images now use their default partition settings, during build.

You'll need a EXT4 capable OS, to modify ```dietpi.txt``` on the image.

We have plans to add a FAT partition to those images, at some point in the future:
https://github.com/Fourdee/DietPi/issues/1423#issue-291560616

I'll mark this as closed, question has been answered. However, please reopen if required.
