### ISSUE TITLE
USB Drive Install | Move dphys-swapfile to USB.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#147]
As title.

**Comment by Fourdee** [comment]
Available for v104 on new installations:
Dedicated USB drive installations will also move the swapfile to the USB drive.

**Comment by dschaper** [comment]
Just a small addition to this, the new version of PiHole has been updated and no longer requires a swapfile for memory considerations. As the ad-list domains are pulled, they are stored in the `tmp` directory instead of in memory.

**Comment by Fourdee** [comment]
@dschaper DietPi mounts `/tmp` to ram (tmpfs) as a performance tweak. So the swapfile increase is still necessary for <=512mb systems.

**Comment by dschaper** [comment]
Okay, good deal. I just noticed that the Pi-Hole install script still had the swapfile increase routine still set up...
