### ISSUE TITLE
DietPi

### ISSUE THREAD

**Issue by MHDMOUSTAFA** [MichaIng/DietPi#1473]
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by Fourdee** [comment]
@MHDMOUSTAFA 

Hi,

We'll need more information. Please can you post the issue you are experiencing?

**Comment by MichaIng** [comment]
Closing due to missing information and user reply.
