### ISSUE TITLE
DietPi-Software | NetData error

### ISSUE THREAD

**Issue by DasClarky** [MichaIng/DietPi#1481]
V160 reimage issue with NetData

Access to file is not permitted: /var/lib/netdata/www/

**Comment by DasClarky** [comment]
Another reinstall fix, what happened to the initial installs? Is there something i could of done to cause that?

**Comment by Fourdee** [comment]
Unable to replicate on DietPi v6.2 (current) fresh install, i'll mark this as closed. Please reopen if you experience the same issue after upgrading to DietPi v6.2.
