### ISSUE TITLE
Update 101 > 102 > 103

### ISSUE THREAD

**Issue by fravaccaro** [MichaIng/DietPi#149]
Hi,

As far as I got the update 102 is mandatory to update to any other following release (I'm on 101).

Since the diet-pi script tries to update to 103 and fails, is there a way to force the 102 update first?

Best regards,

Fra

**Comment by Fourdee** [comment]
@fravaccaro <= v101 can no longer be patched.
If you want to run v102+, you will need to download the latest DietPi image (v102) from http://dietpi.com. The image will automatically patch to v103 during 1st run.

Its rare that DietPi will require a new image, but it does happen now and then to improve areas of DietPi that cannot be changed prior to the 1st run update etc.

You are not required to reinstall your current installation. However, if you want to use the new features/improvements etc, you will need to write the updated image.

More information and reasons why the new image is required: https://www.raspberrypi.org/forums/viewtopic.php?p=855570#p855570

Please reopen if required.
