### ISSUE TITLE
PyLoad to Dietpi

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1490]
Hello is it possible to add this software to DietPi

PyLoad (Download Manager)

https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(RaspberryPi)

**Comment by Fourdee** [comment]
@symbios24 

Thanks for the request 👍 

As with all software requests, we'll mark them as closed for now. When the software title request receives more interest from additional users, we'll reopen to implement.
