### ISSUE TITLE
Dietpi in Proxmox 5.1 VE hangs on diskboot

### ISSUE THREAD

**Issue by eogextreme** [MichaIng/DietPi#1500]
Using your latest .iso:  DietPi_v6.0_NativePC-EFI-x86_64-Stretch.iso Dietpi still hangs after the installation as VM has finished . The message says that it cannot find the BIOS irmware and then reboots and hangs "Booting from harddisk..."

I am using an Intel NUC 6CAYH (Celeron J3445 4 cores) 8GB RAM- 240GB SSD.

When uploaded the iso into Proxmox in created the setup with:  Balloon 512 - Memory 1024 - 32GB SCSI HDD - Ethernet Intel e1000.

I guess i would need a KVM/LXC/AMD64 capable distro.
https://www.proxmox.com/en/proxmox-ve

**Comment by Fourdee** [comment]
Marking as closed.

We do not support Proxmox at this time. Alternatives are VMware and Virtual box image.

**Comment by cuph62** [comment]
I used the vmdk of the Vmware succesfully,
after converting the vmdk  to qcow2, this worked flawlessly in Proxmox

**Comment by eogextreme** [comment]
Thanks cuph62,

I will try to convert it, though it would be nice if @Fourdee could make the qcow2 available on the Dietpi downloads section <hint> :)

**Comment by n1ete** [comment]
> I used the vmdk of the Vmware succesfully,
> after converting the vmdk to qcow2, this worked flawlessly in Proxmox

sorry to ressurect this... could you provide the steps youve taken to run it successfull on pve after converting?
thanks so far

**Comment by JOduMonT** [comment]
@n1ete try this : https://github.com/MichaIng/DietPi/issues/1171#issuecomment-489066602

**Comment by JOduMonT** [comment]
@n1ete or

on your proxmox : `qemu-img convert -f vmdk IMAGE_TO_CONVERT.vmdk -O qcow2 IMAGE_CONVERTED.qcow2`

ref: https://blog.lbdg.me/proxmox-convert-vmdk-to-qcow2/
