### ISSUE TITLE
ompd missing user in database

### ISSUE THREAD

**Issue by shahwahed** [MichaIng/DietPi#1504]
#### Required Information:
- DietPi Version 6.1
- SBC Device RPi2
- Power supply used (5v 3A )?
- SD card used 
- Distro dietpi rasbian

#### Additional Information (if applicable):
- Software title : ompd
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Expected behaviour:

ompd should have create a ompd database
#### Actual behaviour:
database is not create

#### Steps to reproduce:
fresh install, install mpd + ompd

#### Did you submit a ```dietpi-bugreport```?
no

#### Extra details:
to fix this issue, create a ompd user and give permission to ompd database (no need to create it, first access to ompd will create the database)

CREATE USER 'ompd'@'localhost' IDENTIFIED BY 'yourpassword';
GRANT ALL PRIVILEGES ON ompd.* TO 'ompd'@'localhost';

yourpassword = password specified in /var/www/ompd/include/config.inc.php ==> $cfg['mysqli_password'] 

may be add a glitch when you install the package to ask for user and create it?

**Comment by MichaIng** [comment]
@shahwahed 
Thanks for report!
Actually we do create the user and database: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L11301-L11314
`GRANT ALL PRIVILEGES ON ompd.* TO 'ompd'@'localhost';` does actually include creation of user and database, that's true. We just split it in our script, to allow also creating databases for root user without (accidentally) touching it's authentication method (unix_socket): https://github.com/Fourdee/DietPi/blob/master/dietpi/func/create_mysql_db

Did you face any other error message or warning during dietpi-software run or do you find messages in `journalctl` or `/var/log/mysql/error.log` from time of installation attempt that could be related?

I didn't test ompd specifically on RPi (Raspbian), but on VirtualBox and other software using the same database+user creation method also on RPi. So there need to be a hint what went wrong on your system.

**Comment by shahwahed** [comment]
mysql error.log is empty

**Comment by MichaIng** [comment]
@shahwahed 
Just tested again on VM, fresh installation, v6.1 Stretch: 🈯️ 
```
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Configuring O!MPD: feature-rich, web interface audio player for mpd

[ INFO ] Creating MariaDB database: ompd
[  OK  ] Creating MariaDB database: ompd | Completed
```
```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| ompd               |
| performance_schema |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> select user, password, host, plugin from mysql.user;
+------+-------------------------------------------+-----------+-------------+
| user | password                                  | host      | plugin      |
+------+-------------------------------------------+-----------+-------------+
| root |                                           | localhost | unix_socket |
| ompd | *EE072F152A689751C0E898D21E501CA02DBC6115 | localhost |             |
+------+-------------------------------------------+-----------+-------------+
```
@Fourdee @k-plan 
Can some replicate error on RPi?

**Comment by Fourdee** [comment]
🈯️ RPi 3 (v6.2):
```
DietPi-Software
─────────────────────────────────────────────────────
 Mode: Configuring O!MPD: feature-rich, web interface audio player for mpd

[ INFO ] DietPi-Create_MySQL_DB | Creating MariaDB database: ompd
[  OK  ] Creating MariaDB database: ompd | Completed

###

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| ompd               |
| performance_schema |
+--------------------+
4 rows in set (0.01 sec)

MariaDB [(none)]> select user, password, host, plugin from mysql.user;
+------+-------------------------------------------+-----------+-------------+
| user | password                                  | host      | plugin      |
+------+-------------------------------------------+-----------+-------------+
| root |                                           | localhost | unix_socket |
| ompd | *EE072F152A689751C0E898D21E501CA02DBC6115 | localhost |             |
+------+-------------------------------------------+-----------+-------------+
2 rows in set (0.00 sec)

```

Unable to replicate.

**Comment by MichaIng** [comment]
@shahwahed 
Did you do any 1st run setup via dietpi.txt, or moving dietpi_userdata to external drive?

**Comment by Fourdee** [comment]
Marking as closed, unable to replicate.
