### ISSUE TITLE
DietPi-Images | Creation procedure

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1505]
I think it might make sense to list and discuss the steps, in how to usually create a DietPi image. For most SBCs it should be self-explained, based on the ready to run base image we use (e.g. Raspbian Lite, Meverics Odroid minimal image, ARMbian), but e.g. for x86 images it makes sense to align the procedure, starting with the official Debian netboot/mini.iso and in case VM specs:

1. **For VMs: Create and prepare the VM**
   - VirtualBox:
     - `New` machine: Name e.g. `DietPi_VirtualBox-x86_64-Stretch`, `Linux`, `Debian (64-bit)`
     - `Memory size: 1024 MB` which is default on VirtualBox and for our VMs as well. 2048 MB + GPU memory (= 2064 MB default) would be necessary to avoid swapfile creation, but as far as I read, using a swapfile on guest as well (beside host), is not uncommon as guest swap system is able to more effectively decide what to swap and what not.
     - `Create a virtual hard disk now` => `Create`
     - `File size: 8 GB` as default, or adjust as desired. It is anyway just an upper limit in combination with dynamic allocation and can be increased afterwards.
     - `VMDK` disk format for better compatibility
     - `Dynamically allocated` to reduce initial disk size. For best performance it could be beneficial to choose _Fixed size_ on end machine, but especially when sharing the image through the web, needing to pack/unpack the the whole disc size, this is not recommended. => `Create`
     - Select the new machine and `Settings` > `System` > `Motherboard`
     - `Deselect Floppy`, who needs this?
     - `Pointing device: PS/2 Mouse`, which allows disabling USB
     - Chipset: `ICH9`, the modern one, supporting USB2+3, I never had issues with it
     - Switch to `Acceleration` and assure `VT-x/AMD-V + Nested Paging` is enabled.
     - `Display` > `Visplay Memory: 16 MB`, as default for initial headless server.
     - Disable `Audio` <s>and `USB`</s> (https://github.com/Fourdee/DietPi/issues/2093#issuecomment-423964511) as default.
     - `Network` > `Attached to: Bridged Adapter` to allow local SSH, `Advanced` > `Adapter Type: virtio-net`, for best performance.
   - VMware:
     - Create new machine: Installer disc image file (use the iso from step 2 beneath)
     - Manually choose `Linux` + `Debian 9.x 64-bit` disc image.
     - Name: `DietPi_VMware-x86_64-Stretch`
     - Disk: 8G single file
     - Customize hardware: 1G RAM, Network: briged, select your hosts internet network adapter, remove audio, <s>USB`</s> (https://github.com/Fourdee/DietPi/issues/2093#issuecomment-423964511) and printer, to have a most clean image. Everything can be re-added at any time.
2. **Download base image**
     - Debian netboot/mini.iso for VMs: https://deb.debian.org/debian/dists/stretch/main/installer-amd64/current/images/netboot/mini.iso
3. **Mount image to machine**
   - VirtualBox:
     - Mount just as `optical disk` to existing optical drive.
     - Start VM
4. **Debian installation (VM)**
   - NB: The following steps can be automated, however the effort on netboot installers is too high to have any benefit over manually going through the installation for a single VM: https://www.debian.org/releases/stable/amd64/apbs01.html.en#preseed-methods
   - `Advanced options` > `Expert install`
   - `Language: Englisch > UK > en_GB.UTF-8` only, choose no `Additional locales`
   - `Keyboard: British` as well
   - Allow just network auto detection
   - `Hostname: DietPi`
   - `Domain name: leave empty`
   - APT mirror: Just use one near to you, or deb.debian.org, will be anyway overwritten by DietPi-Prep, as actually most other settings as well 😉.
   - Download installer components: **de**select everything, continue
   - Setup users > enable shadow passwords > allow root login > password: `dietpi`
   - Do **not** create normal user account.
   - Clock: Use NTP, leave default mirror 0.debian.pool.ntp.org, timezone: `Europe/London`
   - `Detect disks` > `Partition discs` > `Guided - use entire disc` > select the one available disk > `All files in one partition` > delete all created partitions again > select free space > `create new partition` > `partition size: max` > `Primary`
   - Verify: `ext4` and mount point `/` > Done setting up the partition > Finish partitioning > `No` return due to missing swap partition > `Yes` write to disk
   - Install the base system
   - `linux-image-amd64`
   - `targeted` (no generic driver installation necessary)
   - Package manager: nonfree/contrib not necessary so far, will be anyway added by DietPi-Prep
   - `No` sources!
   - Select `security updates` and `release updates`, but actually on my VMs (bridged via WLAN, IPv6 available on network but not actively used) security repo mostly times out on some IPv6 connection attempt. So I deselect them. DietPi-Prep will add them but forces IPv4 as default for APT.
    - Select and install software: `No` virtualbox-guest extension, `No` survey (user should decide this by oneself later)
   - `De`select all additional software
   - Install grub boot loader: `Yes` to master boot record, to only available partition, `Not` to the EFI removable media part, actually no idea why it detects EFI, as it was not selected on machine and is definitely not available afterwards...
   - Finish installation > set to UTC
   - Unplug (context menu on disc symbol at button, Remove disc, Force removal!) disk, to prevent reboot into installation again, before > Continue
5. **DietPi-Prep**
   - apt update; apt install -y ca-certificates curl dropbear-run
   - Connect via SSH (IP: `ip a s`) for easier copy&paste etc.
```
bash -c "$(curl -sSL https://raw.githubusercontent.com/Fourdee/DietPi/master/PREP_SYSTEM_FOR_DIETPI.sh)"
```
   - Deselect WLAN functionality for VMs, as they virtualize ethernet adapters for network only.
   - Purge all old kernel packages, e.g. `linux-image-4.9.0-4-amd64`, or manually remove them from `/lib/modules/`.
6. **Image export and packaging**
   - Mount virtual drive (vmdk) to other VM or machine, use `zerofree -v /dev/sdx` to reduce final image size. In case: `apt -y install zerofree`
   - On VirtualBox you might want to remove your default Bridged Network host adapter. For this, close VirtualBox, open `DietPi_VirtualBox-x86_64-Stretch.vbox` (and to be sure as well `DietPi_VirtualBox-x86_64-Stretch.vbox-prev`) and change the similar line to `<BridgedInterface name="eth0"/>`. As there is no way to keep the bridged networking setting without saving a certain interface name as well, and `eth0` is at least the most general one that will fit for most Linux hosts. All others will face an error message and the option to adjust the interface to an available one. No bid deal, no better way to handle this. After editing the files, you MUST NOT open the VMs settings any more, otherwise it will insert your available interface again. Directly open the top menu to export the appliance first.
   - Export the whole appliance, VirtualBox only: with OVF 1.0 format for compatibility reasons
   - Create hashes, e.g. using [HashMyFiles](https://www.nirsoft.net/utils/hash_my_files.html), saving the report to `hash.txt`.
   - Pack VM export file(s) + hash.txt with [7zip](https://www.7-zip.org/) for high compression rate.

**Comment by Fourdee** [comment]
@MichaIng 

Nice write up 👍 Thanks for this, will help users who want to run PREP.

**Comment by X3msnake** [comment]
@Fourdee @MichaIng 
If we want to build this on a 32bit architecture it throws a 
Unknown or unsupported CPU architecture i686

For what i read in the code it sets the G_HW_ARCH_DESCRIPTION=$ is there a way to add the i686? 

Were else would we need to add this new entry?

**Comment by MichaIng** [comment]
@X3msnake
Indeed right now we don't offer x86_32 support. Please read discussion here: https://github.com/Fourdee/DietPi/issues/805#issuecomment-361591310

**Comment by X3msnake** [comment]
You should commit this to the dietpi wiki or docs

**Comment by MichaIng** [comment]
Increased VM RAM size to 2G, as this is what we by default ensure in case via swap file.

**Comment by MichaIng** [comment]
Great hint from WarHawk: http://dietpi.com/phpbb/viewtopic.php?f=9&t=2960&p=11428#p11421
- Seems possible to automate most Debian installer steps. I will have a look how to handle and integrate this exactly: https://www.debian.org/releases/stable/amd64/apbs01.html.en#preseed-methods

€: Effort seems too high, especially since you need to redo this for every new `mini.iso` release and every distro version. The questions/answer vary. There are quite some answers to go through, but rebuilding the whole installer/initramfs just makes sense, if you gonna install it on several machines. We however just install it one time each image+mini.iso update.

**Comment by MichaIng** [comment]
Moved VirtualBox creation to Wiki: https://github.com/Fourdee/DietPi/wiki/How-to-create-a-DietPi-image-for-VirtualBox

VMware is next... done: https://github.com/Fourdee/DietPi/wiki/How-to-create-a-DietPi-image-for-WMware

Okay will mark this issue as closed. Further work will be done on Wiki, where it fits better: One page each device 😃.
