### ISSUE TITLE
DietPi-Software | Add MATE desktop installation option

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#151]
> http://fuzon.co.uk/phpbb/viewtopic.php?f=12&t=278&p=1178#p1176

**Comment by xenfomation** [comment]
As a fan of mate, no complaints. Will manually test this week and report findings/level of effort

**Comment by xenfomation** [comment]
MATE is not light-weight -- even on disk space.  :)

Requires Xorg/Xauth (naturally!)
The core of MATE uses **600MB** of storage.
The full environment, minus accessories, uses **900MB** of storage.
Additional accessories/extras occupy more.

I am noting this for consideration in pre-installation checks as well as other discussions @Fourdee and others have raised, specifically for a relational database to track installers, reconsidering certain DietPi directories, and so forth.

## Pass 1

Sandbox with DietPi v118
Command line attempt to install MATE (Complete):

`apt-get install mate-desktop-environment`

This failed near the end.  
I could have done a package repair, etc, but the packages that failed were related to distant third-party applications (DRM and other crypto libraries for the nice fluff that comes with a multimedia, rich desktop environment).

## Pass 2

Reset my sandbox to test the installation of MATE (core only):

`apt-get install mate-desktop-environment-core`

Packages succeeded; installed Xauth/Xorg via dietpi-software and we have success (first screenshot)

## Pass 3

With MATE CORE installed, I then ran `apt-get install mate-desktop-environment` to top off the original effort (second screenshot).

On reboot, we have full MATE (third screenshot).

## Summary - We have success

So, @Fourdee -- if we decide to offer MATE, I would like to suggest it be offered outside of the DietPi optimized packages -- possibly in Linux Software -> Window Managers -> Mate.  It may be nice to note 2 options: Core install and Full install.

Thanks!
![mate1](https://cloud.githubusercontent.com/assets/10519408/15349833/b6cb2ea2-1ca3-11e6-81d9-f0aca40cb9d5.png)
![mate2](https://cloud.githubusercontent.com/assets/10519408/15349834/b943f452-1ca3-11e6-8b05-33b010396546.png)
![mate3](https://cloud.githubusercontent.com/assets/10519408/15349862/edfaac22-1ca3-11e6-989a-0935f2d6ae02.png)

**Comment by xenfomation** [comment]
Working on this, literally now, for addition to installation options.

**Comment by xenfomation** [comment]
Update on pre-pull request
- Git clone of TESTING
- Added under Software Additional as it is not optimized
- Added MATE (full installation + extras) - 1.1GB of space
- Installs XServer/Xauth, Iceweasel, p7zip, and ALSA

Menu Screenshot:
![mate-test1](https://cloud.githubusercontent.com/assets/10519408/15631446/5fd1a204-2539-11e6-8fc8-d018be6dab62.PNG)

Wrapping up testing before commit/pull request for @Fourdee and his review.

**Comment by xenfomation** [comment]
Installation from raw v118 to MATE Desktop, IceWeasel, ALSA, etc good
![mate-good](https://cloud.githubusercontent.com/assets/10519408/15631463/cddc4a4c-2539-11e6-9c37-224a4bb7533a.PNG)

**Comment by Fourdee** [comment]
Additional implementation and testing for reference: https://github.com/Fourdee/DietPi/pull/364

**Comment by Fourdee** [comment]
Documentation to finish: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=60#p2073

**Comment by Fourdee** [comment]
Done.
