### ISSUE TITLE
Rock64 eMMC image 

### ISSUE THREAD

**Issue by elRadix** [MichaIng/DietPi#1511]
@Fourdee 

How to flash debian strech on the eMMC ?  Mine is 64gb.
Will you have to create special eMMC image?

I already have a USB eMMC reader bought together with the Rock64.

Thank you

**Comment by Fourdee** [comment]
@elRadix 

I have no idea, lack the EMMC for device to test ☹️ 

I'll flag this for research, leave it with me.

**Comment by elRadix** [comment]
@Fourdee 

In the meantime I tried to experiment. Flashed the latest image through etcher on the 64gb eMMC card.
Booting no issues at all but I got an issue with RootFS

![image](https://user-images.githubusercontent.com/6258894/36214971-0e543a94-11ab-11e8-99e8-7c96a861c881.png)


![image](https://user-images.githubusercontent.com/6258894/36214428-c340921a-11a9-11e8-98f7-81ccf55a3a66.png)

Current partition table
![image](https://user-images.githubusercontent.com/6258894/36214409-b5c96ef4-11a9-11e8-9bf3-c6206daf2cf6.png)

Is there a solution to resize the partition correctly?

**Comment by TheExpertNoob** [comment]
Sorry I'm late to this party, but I used Windows' WinDiskImager to image the eMMC with the adapter just as I would a micro SD card with no issues.

**Comment by DmitryMyadzelets** [comment]
Run `resize_rootfs.sh` from the console. For some reason it fails to do automatically, for now.

**Comment by Fourdee** [comment]
EMMC works fine in local testing.

Marking closed in favor of : https://github.com/Fourdee/DietPi/issues/1452.
