### ISSUE TITLE
Can't install Retropie with latest Odroid image

### ISSUE THREAD

**Issue by dangamboa** [MichaIng/DietPi#1515]
Retropie using latest 6.0 image for Odroid C2 fails to build, it seems that there are missing packages that can't be installed

I read that it should build with previous versions of Dietpi, here is the log

https://pastebin.com/dfg69hyR

**Comment by Fourdee** [comment]
@LieDanG 

> -- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.0/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

Please verify following is installed:
- ```apt-get install build-essential automake make cmake```

I cant see any mention of ```build-essential``` in the log, so the RetroPie script must assume is already installed. In DietPi its not pre-installed (as not needed by majority of users, additional package status, uses up additional space). Installed on demand with ```dietpi-software``` titles automatically.

**Comment by Fourdee** [comment]
NB: Flagging as non-DietPi issue, however, we'll assist where we can.

**Comment by dangamboa** [comment]
I previously installed build-essential, installed the other packages and tried again with same results

https://pastebin.com/58NKdeAt

**Comment by Fourdee** [comment]
REF: https://github.com/Fourdee/DietPi/issues/1653

**Comment by Fourdee** [comment]
Notes: Could require Debian Stretch for Odroid C2? 

Wiki states Ubuntu image required: https://github.com/RetroPie/RetroPie-Setup/wiki/Odroid-C1-C2#download-ubuntu-image-for-odroid
https://retropie.org.uk/docs/Odroid-C1-C2/

**Comment by Fourdee** [comment]
Odroid C2 Stretch:
```
E: Unable to locate package mali-fbdev
```

The only related packages I can find are in buster:
https://packages.debian.org/buster/mali-t62x-fbdev-driver

This may work?
http://deb.odroid.in/c2/pool/main/m/mali-fbdev/

![image](https://user-images.githubusercontent.com/7077026/38178160-c7abeb0e-3604-11e8-9b3f-5f73fc7bef21.png)
![image](https://user-images.githubusercontent.com/7077026/38178165-d02952bc-3604-11e8-8428-1f1c72f722df.png)
![image](https://user-images.githubusercontent.com/7077026/38178166-d4983296-3604-11e8-91f4-f5817f97a8af.png)
![image](https://user-images.githubusercontent.com/7077026/38178168-dee7f696-3604-11e8-92e5-47248ca96c91.png)

**Comment by Fourdee** [comment]
```
wget http://deb.odroid.in/c2/pool/main/m/mali-fbdev/mali-fbdev_20161003-r6p1-ee42997-15_arm64.deb -O package.deb
dpkg -i package.deb
rm package.deb
```

Appears ```mali450-odroid``` is the same package:
```
root@DietPi:~# dpkg -i package.deb
Selecting previously unselected package mali-fbdev.
(Reading database ... 36819 files and directories currently installed.)
Preparing to unpack package.deb ...
Unpacking mali-fbdev (20161003-r6p1-ee42997-15) ...
dpkg: error processing archive package.deb (--install):
 trying to overwrite '/usr/include/KHR/khrplatform.h', which is also in package mali450-odroid 20161218-r6p1-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 package.deb
root@DietPi:~# rm package.deb^C
root@DietPi:~# apt-cache search ^C
root@DietPi:~# dpkg -l | grep mali450
ii  mali450-odroid              20161218-r6p1-1                  arm64        Mali binary blob and development headers (ODROID build)
```

**Comment by Fourdee** [comment]
Tried following, failed lvl10 init SDL
```
git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
cd RetroPie-Setup

#Odroid C2: Replace mali-fbdev depends with mali450-odroid used in meveric's repo
#sed -i 's/mali-fbdev/mali450-odroid/g' scriptmodules/supplementary/sdl2.sh
#sed -i 's/mali-fbdev/mali450-odroid/g' scriptmodules/system.sh
#sed -i 's/mali-fbdev/mali450-odroid/g' scriptmodules/emulators/retroarch.sh

./retropie_setup.sh
```

**Comment by Fourdee** [comment]
I'll mark this as closed due to the following:
- RetroPie Wiki specifies Ubuntu image must be used.
- Seems incompatible with Debian Stretch + Meveric's repo currently.
- Outside our support range.

**Comment by dangamboa** [comment]
Well I was expecting that, would be possible that you test if it works with the Dietpi Image for Rock64? I'm planning to replace the C2 with that board

**Comment by bernhard263** [comment]
If Retropie complains about the missing mali-fbdev package: You probably don't need it, many systems already have the mali files installed.

````
sudo find /usr/lib/ -name "libMali.so"
sudo find /usr/lib/ -name "libGL*"
````

If these commands find any files, you don't need the package. To install Retropie anyway, an easy solution is to create and install an empty mali-fbdev dummy package to satisfy the Retropie installer:

````
sudo apt-get install checkinstall
cd ~
sudo checkinstall -y --pkgname mali-fbdev --pkgversion=3.0.0 touch dummy.txt
````

This will create and install a dummy 'mali-fbdev' package with just an empty text file in it. You can remove it later with dpkg after Retropie has installed.
