### ISSUE TITLE
ReadyMedia / MiniDLNA info

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1528]
Hello , I installed the ReadyMedia / MiniDLNA server but i cannot find instruction about how to really use it.
The only thing there is the status. can you put additional information/info about how to use/connect/setup etc?

Thanks

**Comment by Fourdee** [comment]
@symbios24 

Hi,

Thanks for the feedback, we'll flag this for review.

REF: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p49

**Comment by symbios24** [comment]
Also i cannot find info about Gmrender - DLNA audio render

**Comment by xgpt** [comment]
https://help.ubuntu.com/community/MiniDLNA << I used this successfully to help me out on a non-dietpi installation, old information, but maybe useful for adapting for use for y'all :smiley:

**Comment by Fourdee** [comment]
No review required, the current online doc covers the status page, and, a link to available upnp clients:
https://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p49
