### ISSUE TITLE
[Request/Question] Native EFI32 Support with x86_64 ?

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1531]
Hi @Fourdee 

is there anything planned to get this up and running? Most low-cost devices have 64Bit-CPUs but only EFI32 Bios. So all the x64-EFI images won't work oob.

**Comment by Fourdee** [comment]
@SuBLiNeR 

> Most low-cost devices have 64Bit-CPUs but only EFI32 Bios. So all the x64-EFI images won't work oob.

Yep 👍  

As it stands at the moment, I lack any knowledge of how to covert our existing image for 32bit EFI, outside of using 32bit EFI system to create a different image. As I lack any system capable of 32bit EFI, it may be some time before we can achieve it, via a different method.

**Comment by symbios24** [comment]
Hello any plans for a Native PC (BIOS/CSM) 32/64bit image?

Thanks

**Comment by Fourdee** [comment]
@symbios24 

64bit yes: https://github.com/Fourdee/DietPi/issues/1448
32bit not currently : https://github.com/Fourdee/DietPi/issues/805#issuecomment-361591310

**Comment by ghost** [comment]
@Fourdee Normally, Debian9 support this option while starting to install via LIVE-CD and than installs grub2 directly as EFI32 or EFI64. This must mean, if i now install DEBIAN9 and than create DietPi via PREP-script, it may run at this computer... just a thought.

**Comment by Fourdee** [comment]
Marking as closed.

We currently support 64bit x86_64 systems with 64bit EFI and/or BIOS and/or EFI under CSM.
