### ISSUE TITLE
Cannot detect external hard disk

### ISSUE THREAD

**Issue by kanztu** [MichaIng/DietPi#1534]
#### Required Information:
- DietPi Version | ```6.2 ```
- SBC Device :RPi 3 Model B (armv7l)

####  Information:

I am trying to mount my external hard disk via DietPi-Drive_Manager, but my HD can't be found

 Result of fdisk -l

>Disk /dev/mmcblk0: 14.7 GiB, 15720251392 bytes, 30703616 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6f0c83bc

>Device         Boot Start      End  Sectors  Size Id Type
/dev/mmcblk0p1       8192    93236    85045 41.5M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      94208 30703615 30609408 14.6G 83 Linux

 Result of mount

> /dev/mmcblk0p2 on / type ext4 (rw,noatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,relatime,size=495548k,nr_inodes=123887,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=27,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
tmpfs on /DietPi type tmpfs (rw,nosuid,nodev,noatime,size=10240k)
tmpfs on /var/log type tmpfs (rw,nosuid,nodev,noatime,size=20480k)
/dev/mmcblk0p1 on /boot type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)

/etc/fstab

> proc            /proc           proc    defaults											0 0
tmpfs 			/tmp  			tmpfs 	defaults,noatime,nodev,nosuid,mode=1777				0 0
tmpfs 			/var/log 		tmpfs 	defaults,size=20m,noatime,nodev,nosuid,mode=1777	0 0
tmpfs 			/DietPi 		tmpfs 	defaults,size=10m,noatime,nodev,nosuid,mode=1777	0 0

>#Internal Drives---------------------------------------------------
PARTUUID=6f0c83bc-01    /boot    auto    defaults,noatime    0 0
PARTUUID=6f0c83bc-02    /    auto    defaults,noatime    0 0

Hard disk information
diskutil info on my mac

>    Device Identifier:        disk6
   Device Node:              /dev/disk6
   Whole:                    Yes
   Part of Whole:            disk6
   Device / Media Name:      External

>   Volume Name:              Not applicable (no file system)
   Mounted:                  Not applicable (no file system)
   File System:              None

>   Content (IOContent):      FDisk_partition_scheme
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported

>   Disk Size:                500.1 GB (500107861504 Bytes) (exactly 976773167 512-Byte-Units)
   Device Block Size:        512 Bytes

>   Read-Only Media:          No
   Read-Only Volume:         Not applicable (no file system)

>   Device Location:          External
   Removable Media:          Fixed

>   Virtual:                  No
   OS 9 Drivers:             No
   Low Level Format:         Not supported

and also

>   Device Identifier:        disk6s1
   Device Node:              /dev/disk6s1
   Whole:                    No
   Part of Whole:            disk6

>   Volume Name:              exfat
   Mounted:                  Yes
   Mount Point:              /Volumes/exfat

>   Partition Type:           Windows_NTFS
   File System Personality:  ExFAT
   Type (Bundle):            exfat
   Name (User Visible):      ExFAT

>   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 USB
   SMART Status:             Not Supported
   Volume UUID:              CEAAB188-189F-38A5-A60E-D627D04DF6D6

>   Disk Size:                500.1 GB (500107860480 Bytes) (exactly 976773165 512-Byte-Units)
   Device Block Size:        512 Bytes

>   Volume Total Space:       500.1 GB (500091060224 Bytes) (exactly 976740352 512-Byte-Units)
   Volume Used Space:        9.0 MB (9043968 Bytes) (exactly 17664 512-Byte-Units) (0.0%)
   Volume Available Space:   500.1 GB (500082016256 Bytes) (exactly 976722688 512-Byte-Units) (100.0%)
   Allocation Block Size:    131072 Bytes

>   Read-Only Media:          No
   Read-Only Volume:         No

>   Device Location:          External
   Removable Media:          Fixed

I try to format to ext4, exFAT or NTFS, both cannot be detected
And I also try to connect other harddisks but also cannot detected

**Comment by k-plan** [comment]
Hi,

can you please connect your usb drive to RPi and provide:

`root@RPi-Zero:~# lsusb`

`root@RPi-Zero:~# lsblk -f`

`root@RPi-Zero:~# dmesg`

**Comment by kanztu** [comment]
Thank you for reply!

lsusb

> Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

lsblk -f

> NAME        FSTYPE LABEL  UUID                                 MOUNTPOINT
mmcblk0
|-mmcblk0p1 vfat   boot   CDD4-B453                            /boot
`-mmcblk0p2 ext4   rootfs 72bfc10d-73ec-4d9e-a54a-1cc507ee7ed2 /

dmesg

> [    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.9.59-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1047 SMP Sun Oct 29 12:19:23 GMT 2017
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt:Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] cma: Reserved 8 MiB at 0x3dc00000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 255488
[    0.000000] free_area_init_node: node 0, pgdat 80c6f380, node_mem_map bd336000
[    0.000000]   Normal zone: 2246 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 255488 pages, LIFO batch:31
[    0.000000] percpu: Embedded 14 pages/cpu @be5b0000 s25600 r8192 d23552 u57344
[    0.000000] pcpu-alloc: s25600 r8192 d23552 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 253242
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1280 bcm2708_fb.fbheight=720 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3f000000 vc_mem.mem_size=0x3f600000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 console=ttyS0,115200 root=PARTUUID=6f0c83bc-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 991096K/1021952K available (7168K kernel code, 486K rwdata, 2012K rodata, 1024K init, 770K bss, 22664K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbe800000 - 0xff800000   (1040 MB)
                   lowmem  : 0x80000000 - 0xbe600000   ( 998 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c79834   ( 487 kB)
                      .bss : 0x80c7b000 - 0x80d3b964   ( 771 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000023] Switching to timer-based delay loop, resolution 52ns
[    0.000302] Console: colour dummy device 80x30
[    0.001213] console [tty1] enabled
[    0.001257] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.001325] pid_max: default: 32768 minimum: 301
[    0.001655] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001698] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002731] Disabling memory control group subsystem
[    0.002833] CPU: Testing write buffer coherency: ok
[    0.002896] ftrace: allocating 22392 entries in 66 pages
[    0.050035] CPU0: update cpu_capacity 1024
[    0.050087] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.050149] Setting up static identity map for 0x100000 - 0x100034
[    0.052042] CPU1: update cpu_capacity 1024
[    0.052049] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.052737] CPU2: update cpu_capacity 1024
[    0.052744] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.053416] CPU3: update cpu_capacity 1024
[    0.053422] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.053511] Brought up 4 CPUs
[    0.053683] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.053712] CPU: All CPU(s) started in HYP mode.
[    0.053739] CPU: Virtualization extensions available.
[    0.054569] devtmpfs: initialized
[    0.065877] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.066191] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.066253] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.066813] pinctrl core: initialized pinctrl subsystem
[    0.067745] NET: Registered protocol family 16
[    0.070028] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.078957] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.079005] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.079172] Serial: AMBA PL011 UART driver
[    0.081105] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.081656] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.150882] bcm2835-dma 3f007000.dma: DMA legacy API manager at be80f000, dmachans=0x1
[    0.152753] SCSI subsystem initialized
[    0.152938] usbcore: registered new interface driver usbfs
[    0.153041] usbcore: registered new interface driver hub
[    0.153164] usbcore: registered new device driver usb
[    0.159844] raspberrypi-firmware soc:firmware: Attached to firmware from 2017-10-24 17:10
[    0.161297] clocksource: Switched to clocksource arch_sys_counter
[    0.208419] VFS: Disk quotas dquot_6.6.0
[    0.208530] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.208763] FS-Cache: Loaded
[    0.209026] CacheFiles: Loaded
[    0.221215] NET: Registered protocol family 2
[    0.222139] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.222277] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.222488] TCP: Hash tables configured (established 8192 bind 8192)
[    0.222602] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.222669] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.222898] NET: Registered protocol family 1
[    0.223327] RPC: Registered named UNIX socket transport module.
[    0.223359] RPC: Registered udp transport module.
[    0.223387] RPC: Registered tcp transport module.
[    0.223415] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.224425] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.226768] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.242837] FS-Cache: Netfs 'nfs' registered for caching
[    0.243844] NFS: Registering the id_resolver key type
[    0.243894] Key type id_resolver registered
[    0.243922] Key type id_legacy registered
[    0.246360] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.246508] io scheduler noop registered
[    0.246538] io scheduler deadline registered (default)
[    0.246812] io scheduler cfq registered
[    0.252472] BCM2708FB: allocated DMA memory fdd10000
[    0.252526] BCM2708FB: allocated DMA channel 0 @ be80f000
[    0.266942] Console: switching to colour frame buffer device 160x45
[    0.276870] bcm2835-rng 3f104000.rng: hwrng registered
[    0.277080] vc-mem: phys_addr:0x00000000 mem_base=0x3f000000 mem_size:0x3f600000(1014 MiB)
[    0.277742] vc-sm: Videocore shared memory driver
[    0.292779] brd: module loaded
[    0.301647] loop: module loaded
[    0.301734] Loading iSCSI transport class v2.0-870.
[    0.302352] usbcore: registered new interface driver smsc95xx
[    0.302465] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.531402] Core Release: 2.80a
[    0.531470] Setting default values for core params
[    0.534274] Finished setting default values for core params
[    0.737415] Using Buffer DMA mode
[    0.740132] Periodic Transfer Interrupt Enhancement - disabled
[    0.742930] Multiprocessor Interrupt Enhancement - disabled
[    0.745731] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.748495] Dedicated Tx FIFOs mode
[    0.751575] WARN::dwc_otg_hcd_init:1032: FIQ DMA bounce buffers: virt = 0xbdd04000 dma = 0xfdd04000 len=9024
[    0.754460] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.768380] dwc_otg: Microframe scheduler enabled
[    0.768423] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x8058f5b0
[    0.771285] WARN::hcd_init_fiq:460: FIQ ASM at 0x8058f920 length 36
[    0.774142] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbe87a000
[    0.777027] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.779836] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.782674] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.785466] Init: Port Power? op_state=1
[    0.788192] Init: Power Port (0)
[    0.791085] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.793909] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.796689] usb usb1: Product: DWC OTG Controller
[    0.799406] usb usb1: Manufacturer: Linux 4.9.59-v7+ dwc_otg_hcd
[    0.802165] usb usb1: SerialNumber: 3f980000.usb
[    0.805700] hub 1-0:1.0: USB hub found
[    0.808477] hub 1-0:1.0: 1 port detected
[    0.811939] dwc_otg: FIQ enabled
[    0.811943] dwc_otg: NAK holdoff enabled
[    0.811948] dwc_otg: FIQ split-transaction FSM enabled
[    0.811961] Module dwc_common_port init
[    0.812183] usbcore: registered new interface driver usb-storage
[    0.815204] mousedev: PS/2 mouse device common for all mice
[    0.818933] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.822027] bcm2835-cpufreq: min=600000 max=1200000
[    0.825136] sdhci: Secure Digital Host Controller Interface driver
[    0.827870] sdhci: Copyright(c) Pierre Ossman
[    0.830858] sdhost-bcm2835 3f202000.sdhost: could not get clk, deferring probe
[    0.835866] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.838797] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.844283] ledtrig-cpu: registered to indicate activity on CPUs
[    0.847312] hidraw: raw HID events driver (C) Jiri Kosina
[    0.850339] usbcore: registered new interface driver usbhid
[    0.853209] usbhid: USB HID core driver
[    0.856774] vchiq: vchiq_init_state: slot_zero = 0xbdd80000, is_master = 0
[    0.860994] [vc_sm_connected_init]: start
[    0.864657] vc_vchi_sm_init: failed to open VCHI service (-1)
[    0.864756] [vc_sm_connected_init]: failed to initialize shared memory service
[    0.867742] [vc_sm_connected_init]: end - returning -1
[    0.871145] Initializing XFRM netlink socket
[    0.874222] NET: Registered protocol family 17
[    0.877285] Key type dns_resolver registered
[    0.880597] Registering SWP/SWPB emulation handler
[    0.884276] registered taskstats version 1
[    0.893594] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.896658] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.901348] sdhost: log_buf @ bdd07000 (fdd07000)
[    0.981325] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.986608] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.989693] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    1.031406] Indeed it is in host mode hprt0 = 00021501
[    1.058157] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.063123] mmc0: new high speed SDHC card at address 0001
[    1.071420] of_cfs_init
[    1.074659] of_cfs_init: OK
[    1.083534] mmcblk0: mmc0:0001 00000 14.6 GiB
[    1.088142]  mmcblk0: p1 p2
[    1.099504] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    1.104164] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.108815] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.111994] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.114861] random: fast init done
[    1.119268] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    1.125250] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    1.128398] devtmpfs: mounted
[    1.133356] Freeing unused kernel memory: 1024K
[    1.227815] mmc1: new high speed SDIO card at address 0001
[    1.231352] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.234665] Indeed it is in host mode hprt0 = 00001101
[    1.461636] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.464794] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.468704] hub 1-1:1.0: USB hub found
[    1.471851] hub 1-1:1.0: 5 ports detected
[    1.548816] systemd[1]: System time before build time, advancing clock.
[    1.663923] NET: Registered protocol family 10
[    1.678080] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.711494] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.718241] systemd[1]: Detected architecture arm.
[    1.733686] systemd[1]: Set hostname to <DietPi>.
[    1.791385] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.931680] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.934833] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.940763] smsc95xx v1.0.5
[    2.045166] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:d3:08:d4
[    2.281393] systemd[1]: apt-daily.timer: Cannot add dependency job, ignoring: Unit apt-daily.timer is masked.
[    2.284744] systemd[1]: apt-daily-upgrade.timer: Cannot add dependency job, ignoring: Unit apt-daily-upgrade.timer is masked.
[    2.296481] systemd[1]: Listening on udev Kernel Socket.
[    2.304663] systemd[1]: Created slice User and Session Slice.
[    2.312172] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.319655] systemd[1]: Listening on udev Control Socket.
[    2.327140] systemd[1]: Reached target Swap.
[    2.571692] i2c /dev entries driver
[    2.732219] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    3.357729] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    3.370133] systemd-journald[123]: Received request to flush runtime journal from PID 1
[    3.579679] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    3.592462] usbcore: registered new interface driver brcmfmac
[    3.877921] brcmfmac: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    3.878726] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14
[    4.199659] uart-pl011 3f201000.serial: no DMA platform data
[    4.703123] brcmfmac: power management disabled
[    4.841525] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    4.841545] brcmfmac: power management disabled
[    4.920609] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
[    5.332157] Adding 2044k swap on /var/swap.  Priority:-1 extents:1 across:2044k SSFS
[    5.338512] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    5.338760] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    5.856308] random: crng init done
[    6.789367] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.790421] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xDDE1
[    8.306803] NET: Registered protocol family 15
[    8.756041] Bluetooth: Core ver 2.22
[    8.756197] NET: Registered protocol family 31
[    8.756203] Bluetooth: HCI device and connection manager initialized
[    8.757795] Bluetooth: HCI socket layer initialized
[    8.757815] Bluetooth: L2CAP socket layer initialized
[    8.757861] Bluetooth: SCO socket layer initialized
[    8.805623] Bluetooth: HCI UART driver ver 2.3
[    8.805631] Bluetooth: HCI UART protocol H4 registered
[    8.805635] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.805796] Bluetooth: HCI UART protocol Broadcom registered
[    9.037736] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    9.037746] Bluetooth: BNEP filters: protocol multicast
[    9.037764] Bluetooth: BNEP socket layer initialized
[   10.073524] PPP generic driver version 2.4.2
[   10.076651] NET: Registered protocol family 24
[   10.109689] l2tp_core: L2TP core driver, V2.0
[   10.113645] l2tp_netlink: L2TP netlink interface
[   10.118133] l2tp_ppp: PPPoL2TP kernel driver, V2.0
[   21.074335] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
[   21.256427] NFSD: starting 90-second grace period (net 80c65340)
[   25.041079] brcmfmac: power management disabled
[   34.853765] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   47.042747] usb 1-1.4: new high-speed USB device number 4 using dwc_otg
[   73.671408] usb 1-1.4: new high-speed USB device number 5 using dwc_otg
[  100.291350] usb 1-1.4: new high-speed USB device number 6 using dwc_otg
[  126.921355] usb 1-1.4: new high-speed USB device number 7 using dwc_otg



Is my pi usb port broken?

**Comment by k-plan** [comment]
Hmmm ...

- wrong PSU (min 2.5A / 5.1V) to power RPi ?

- faulty USB cable to power RPi ?

- faulty USB cable to power your USB HDD ?

- or your USB HDD  need a externel PSU to power up or a Y-USB cable ?

Can you connect a USB thumb drive and will it be recogniced?
