### ISSUE TITLE
DietPi Software | Midnight Commander line characters

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#1540]
## Creating a bug report/issue:

http://dietpi.com/phpbb/viewtopic.php?f=11&t=2877

> After the update to 6.2 my mc forgot how to draw lines in putty. This can changed to e.g. from UTF-8 to ISO-8859-1 in Translation settings but then all dietpi menus get messed up. I did reinstall via dietpi-software and via apt to no avail.

![2018-02-20 17-52-49](https://user-images.githubusercontent.com/17237601/36437604-c14b6300-1667-11e8-9793-0ad3f0695cdc.png)

#### Required Information:
- DietPi Version |  v6.2
- SBC Device | all my devices
- Distro  | Stretch (Jessie? - untested)

#### Additional Information (if applicable):
- Software title? 

Midnight Commander

- Can this issue be replicated on a fresh installation of DietPi?

Yes

#### Steps to reproduce:

` dietpi-config` =>  Language and Regional Options  =>  Locale   Change Language and Regional Settings => `de_DE.UTF-8 `

![2018-02-20 18-05-54](https://user-images.githubusercontent.com/17237601/36437957-c1f273b0-1668-11e8-8b95-222a74acfaaf.png)

`dietpi-software install id 3`

- SSH Server: `Dropbear`

- SSH Client: `putty` / `kitty` / `vssh` / `terminal` (Mac OSX)

**Comment by Fourdee** [comment]
@k-plan 

Thanks 👍 

~Yep, we removed non UTF-8 options from locale generation. I assume ``` ISO-8859-1``` required for MC.~
mm, fine under en_GB with kitty and OpenSSH. i'll test.

Ah yes:  https://github.com/Fourdee/DietPi/commit/c661692ff0fbdb111c790ab3a83efa65197d313f
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=533525

**Comment by k-plan** [comment]
@Fourdee 

> mm, fine under en_GB with kitty and OpenSSH. i'll test.

- `dietpi-config` => Language and Regional Options => Locale Change Language and Regional Settings => `en_GB.UTF-8
`

- `reboot`

- change` kitty ` to  `ISO-8859-1:1998 (Latin-1, West Europe)`

- SSH Server: Dropbear

- `mc` :

![2018-02-20 19-13-31](https://user-images.githubusercontent.com/17237601/36441570-561eeafa-1673-11e8-8824-84e71a4dccf9.png)

:+1: 

- `dietpi-software` : 

![2018-02-20 19-11-58](https://user-images.githubusercontent.com/17237601/36441654-86e072c6-1673-11e8-8aac-69219a0e9753.png)

:-1: 

- login screen:

![2018-02-20 19-12-40](https://user-images.githubusercontent.com/17237601/36441699-a91a46dc-1673-11e8-82ea-b7be9308e5fe.png)


:-1: 




```
root@RPi-Zero:~# cat /etc/profile.d/99-dietpi-force-locale.sh
cat: /etc/profile.d/99-dietpi-force-locale.sh: No such file or directory

root@RPi-Zero:~# ls -lah /etc/profile.d/
total 12K
drwxr-xr-x  2 root root 4.0K Feb 18 19:59 .
drwxr-xr-x 88 root root 4.0K Feb 20 18:34 ..
-rw-r--r--  1 root root  663 Apr 12  2016 bash_completion.sh
```

**Comment by Fourdee** [comment]
@k-plan 

👍 

🈯️ 
```
LANG='en_GB.UTF-8' mc
```

Options:
- Always export LC_ALL/LANG en_GB.UTF-8 when dropbear is installed. Our scripts are fine as we define it already in globals.
-- and/or export current locale as generated by locale, may overwrite our scripts LANG/LC_ALL defines, breaking our scripts.
- Accept this is a bug/limitation in dropbear, leave it as is (which it is), but as its our default ssh, we need to fix it.

**Comment by Fourdee** [comment]
🈯️ Yep, fixes dropbear:
```
cat << _EOF_ > /etc/profile.d/99-dietpi-force-locale.sh
# To force server locales on SSH access, as dropbear does automatically overwrite them by client values:
#!/bin/bash

if [[ "\$(tty)" = "/dev/pts/"* ]] && (( \$(locale | grep -ci -m1 'POSIX') )); then
export LANG="en_GB.UTF-8"
export LC_ALL="en_GB.UTF-8"
export LANGUAGE="en_GB:en"
fi
_EOF_
 chmod +x /etc/profile.d/99-dietpi-force-locale.sh
```

However, it will always force en_GB.UTF-8, regardless of locale.

---

🈯️ Auto-detect and set
```
cat << _EOF_ > /etc/profile.d/99-dietpi-force-locale.sh
#!/bin/bash

#Workaround for setting locale to session when POSIX is detected (eg: dropbear): https://github.com/Fourdee/DietPi/issues/1540#issuecomment-367066178
if (( \$(locale | grep -ci -m1 'POSIX') )); then
export LANG="en_GB.UTF-8"
export LC_ALL="en_GB.UTF-8"
export LANGUAGE="en_GB:en"
fi
_EOF_
chmod +x  /etc/profile.d/99-dietpi-force-locale.sh
```

---

🈯️ Need to test if setting local.gen locale, will NOT override our dietpi scripts. ~Else, this is the only solution I see~ :
```
cat << _EOF_ > /etc/profile.d/99-dietpi-force-locale.sh
#!/bin/bash

#Workaround for setting locale to session when POSIX is detected (eg: dropbear): https://github.com/Fourdee/DietPi/issues/1540#issuecomment-367066178
if (( \$(locale | grep -ci -m1 'POSIX') )); then
CURRENT_LOCALE=\$(grep -m1 'AUTO_SETUP_LOCALE=' /DietPi/dietpi.txt | sed 's/.*=//')
export LANG="\$CURRENT_LOCALE"
export LC_ALL="\$CURRENT_LOCALE"
#export LANGUAGE="\$CURRENT_LOCALE"
fi
_EOF_
chmod +x  /etc/profile.d/99-dietpi-force-locale.sh
```

```
root@DietPi:~# locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8
root@DietPi:~# nano /DietPi/dietpi/func/dietpi-globals
root@DietPi:~# nano /DietPi/dietpi/dietpi-config
root@DietPi:~# dietpi-config
[  OK  ] Root access verified.
[ INFO ] DietPi-Drive_Manager | Checking RootFS R/W access. Please wait...
[  OK  ] DietPi-Drive_Manager | RootFS R/W access.

en_GB.UTF-8
```

**Comment by k-plan** [comment]
Hmm ... puh .... really difficult.

Can't say, what to do now.

**Comment by Fourdee** [comment]
@k-plan 
Resolved for v6.3 👍 

Workaround for v6.2:
```
cat << _EOF_ > /etc/profile.d/99-dietpi-force-locale.sh
#!/bin/bash

#Workaround for setting locale to session when POSIX is detected (eg: dropbear): https://github.com/Fourdee/DietPi/issues/1540#issuecomment-367066178
if (( \$(locale | grep -ci -m1 'POSIX') )); then
CURRENT_LOCALE=\$(grep -m1 'AUTO_SETUP_LOCALE=' /DietPi/dietpi.txt | sed 's/.*=//')
export LANG="\$CURRENT_LOCALE"
export LC_ALL="\$CURRENT_LOCALE"
#export LANGUAGE="\$CURRENT_LOCALE"
fi
_EOF_
chmod +x  /etc/profile.d/99-dietpi-force-locale.sh
```

**Comment by Fourdee** [comment]
NB: Left ```LANGUAGE``` out, requires different syntax and I believe its no longer used in Linux? LANG/LC_ALL should be sufficient.

**Comment by slim0287** [comment]
First, please pardon me if I am posting this in the wrong place.  When I ssh into my dietpi, I get the following message:
-sh: 4: /etc/profile.d/99-dietpi-posix-set-locale.sh: 0: not found

Comments in the 99-dietpi-posix-set-locale.sh script referred to issue 1540 which is why I am posting here.  I'm not running dropbear nor POSIX.  The error message appears to be with how the 'if' statement is written within the script.  I haven't changed it because it's a minor annoyance for a Pi that I log into infrequently, but I thought I would report it here.  And it it helps, this dietpi is running on a Raspberry Pi 2 that I use as a DNS server with Pi-hole and I log in with ssh keys, not a password.

Thanks.

**Comment by MichaIng** [comment]
@slim0287 
Thanks for the report. No worries, fits perfect here.

Hmm, the syntax should be fine, at least works well for me and is widely used within our scripts.
Please verify that `locale` and `grep` packages are installed, but should always be: `apt install locale grep`

Also try to run the command manually: `locale | grep -qi 'POSIX' || echo 'no POSIX locale'`

**Comment by slim0287** [comment]
Both `locale` and `grep` are installed on my system.  When I run your suggested command manually, I get the following: `no POSIX locale`

When I run the `if` statement from the script on the command line, I get: `> > > > > -sh: 17: 0: not found`
Which is consistent with what I see on login.

Does that help the diagnosis?

Thanks

**Comment by MichaIng** [comment]
Hmm, okay to the commands + check syntax run. Mysterious 🤔...
Maybe your file got just somehow corrupted. Please try to reset it:
```
	cat << _EOF_ > /etc/profile.d/99-dietpi-posix-set-locale.sh
#!/bin/bash
#Workaround for setting locale to session when POSIX is detected (eg: dropbear): https://github.com/Fourdee/DietPi/issues/1540#issuecomment-367066178
if locale | grep -qi 'POSIX'; then
	CURRENT_LOCALE="\$(grep -m1 '^[[:blank:]]*AUTO_SETUP_LOCALE=' /DietPi/dietpi.txt | sed 's/^.*=//')"
	export LANG="\$CURRENT_LOCALE"
	export LC_ALL="\$CURRENT_LOCALE"
fi
_EOF_
```

**Comment by slim0287** [comment]
That solved it.  My script has a different `if` statement as well as other differences, as follows:
```
if (( $(locale | grep -ci -m1 'POSIX') )); then
	CURRENT_LOCALE=$(grep -m1 'AUTO_SETUP_LOCALE=' /DietPi/dietpi.txt | sed 's/.*=//')
	export LANG="$CURRENT_LOCALE"
	export LC_ALL="$CURRENT_LOCALE"
	#export LANGUAGE="$CURRENT_LOCALE"
fi
```
I never modified this script, so I have no idea how it was set this way.  At any rate, thanks for the help.  And I should add, I very much like DietPi!

Thanks again.
