### ISSUE TITLE
PREP: agetty

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1541]
![image](https://user-images.githubusercontent.com/7077026/36438774-caf8f732-1662-11e8-8c89-4e70a4ca887e.png)

```
	G_DIETPI-NOTIFY 2 "Reducing getty count:"

	for ((i=2; i<=6; i++))
	do

		systemctl mask getty@tty$i

	done

```

**Comment by Fourdee** [comment]
Much better:
![image](https://user-images.githubusercontent.com/7077026/36439358-8cc3262a-1664-11e8-9a6e-b33cddbea5bf.png)

**Comment by MichaIng** [comment]
@Fourdee 
Ah you already removed dbus from PREP 😄.
Do just `systemctl mask serial-getty.service` instead, which launches the additional gettys if dbus/logind is not present: https://github.com/Fourdee/DietPi/issues/1482#issuecomment-364137752
