### ISSUE TITLE
DietPi-WiFiDB | Add EAP settings selection to GUI

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1549]
WPA-PSK / WPA-EAP / NONE

> https://github.com/Fourdee/DietPi/pull/1547

And all additional vars linked to those options.

**Comment by MichaIng** [comment]
Settings possible via `dietpi-wifi.db/txt` now, handled within new DietPi-WiFiDB script: https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-wifidb

But great would be the possibility to adjust EAP settings as well via GUI. Currently only WEP/PSK SSID+key possible.

**Comment by MichaIng** [comment]
Could be added: https://github.com/MichaIng/DietPi/issues/2650
- Allow enabling/disabling hidden SSID support by adding/skipping these two settings. The extra options seem to increase connection/scan time and the vast majority of users will never need it.

**Comment by MichaIng** [comment]
Related request: https://github.com/MichaIng/DietPi/issues/2732

**Comment by MichaIng** [comment]
Marking this as closed in favour of the new request.
