### ISSUE TITLE
Image | Odroid Stretch review

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1552]
Meveric's images/repo:
- N1 | 🈯️ img | 🈯️ gpu | 🈯️ Kodi |  https://github.com/Fourdee/DietPi/issues/1519
-- DietPi image: http://dietpi.com/downloads/images/DietPi_OdroidN1-ARMv8-Stretch.7z
- C2 | 🈯️ img | 🈯️ gpu | 🈯️ Kodi | https://forum.odroid.com/viewtopic.php?f=138&t=27449#p194153
-- DietPi image: http://dietpi.com/downloads/images/DietPi_OdroidC2-ARMv8-Stretch.7z
- XU4 | 🈯️ img | 🈯️ gpu | 🈯️ Kodi https://forum.odroid.com/viewtopic.php?t=26608#p185562
-- DietPi image: https://dietpi.com/downloads/images/DietPi_OdroidXU4-ARMv7-Stretch.7z
- C1 | 🈴 img | 🈴 gpu | 🈴 Kodi | https://forum.odroid.com/viewtopic.php?f=114&t=30053

---

- XU4 4.14: https://github.com/hardkernel/linux/tree/odroidxu4-4.14.y
```
linux-image-4.14-armhf-odroid-xu4
```

XU4 4.14 + Stretch = hang on:
```
root@DietPi:~# apt-get update
0% [Working]
```

**Comment by LexiconCode** [comment]
If Kodi/GPU is holding up Odroid Stretch could you release without if it could be updated with DietPi later?

**Comment by Fourdee** [comment]
@LexiconCode 

C2 Stretch is done (minus GPU/KODI):
http://dietpi.com/downloads/images/DietPi_OdroidC2-ARMv8-Stretch.7z

I've plans to do the XU4 and C1 stretch images aswell (minus GPU/KODI). Will post them here when completed.

**Comment by k-plan** [comment]
@Fourdee 

> C2 Stretch is done (minus GPU/KODI):

- C2 | 🈯️ img | 🈯️ gpu | 🈴 Kodi | 🈴  pivpn

![180319-0001](https://user-images.githubusercontent.com/17237601/37586049-6ffd045a-2b5b-11e8-9796-a6947702c63b.gif)

Need for VPN, so I install:

```
root@Odroid-C2-Stretch:~# dietpi-software list | grep "openvpn"
id 97 | =2 | openvpn: vpn server | +rsyslog | http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=613#p613
id 117 | =0 | pivpn: openvpn installer & management tool | +rsyslog | http://dietpi.com/phpbb/viewtopic.php?http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=3469#p3469
```

![180319-0002](https://user-images.githubusercontent.com/17237601/37586335-4f021d5c-2b5c-11e8-8976-0cdf85642c15.gif)

**Comment by LexiconCode** [comment]
As soon as you have an image for Odroid XU4 an Odroid N2 I will test as well.

**Comment by Fourdee** [comment]
XU4 Stretch RC image by Meveric:
http://fuzon.co.uk/meveric/images/Stretch/Debian-Stretch-1.0~RC1-20180324-XU3-XU4.img.xz

**Comment by LexiconCode** [comment]
`apt update`
> Err:34 http://ftp.debian.org/debian stretch/main Translation-en
>   Write error - write (28: No space left on device)
> Fetched 14.4 MB in 9s (1,512 kB/s)
> Reading package lists... Done
> E: Failed to fetch http://ftp.debian.org/debian/dists/stretch/main/i18n/Translation-en  Write error - write (28: No space left on device)
> E: Some index files failed to download. They have been ignored, or old ones used instead.

> Filesystem      Size  Used Avail Use% Mounted on
> udev            931M     0  931M   0% /dev
> tmpfs           200M   11M  189M   6% /run
> /dev/mmcblk1p2  464M  422M   39M  92% /
> tmpfs           998M     0  998M   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs           998M     0  998M   0% /sys/fs/cgroup
> /dev/mmcblk1p1   71M   31M   41M  43% /boot

**Comment by Fourdee** [comment]
@LexiconCode 

Please paste the rootFS resize logs:
```
cat /var/tmp/dietpi/logs/fs_*
```

And which device/image used?

**Comment by LexiconCode** [comment]
XU4 Stretch RC image by Meveric on the Odroid N2. without dietpi scripts. Which now that I've looked at it resize the partitions.

**Comment by Fourdee** [comment]
XU4 stretch + 4.14:
- if ```console=ttySAC2,115200n8``` is missing from ```boot.ini```, hangs after ```starting kernel``` and does not continue to boot.


Image: https://dietpi.com/downloads/images/DietPi_OdroidXU4-ARMv7-Stretch.7z

**Comment by Fourdee** [comment]
XU4/C2 stretch images added to dietpi.com:
https://twitter.com/DietPi_/status/992787751262179328

Just need to verify kodi packages again, then check/do C1.

**Comment by Fourdee** [comment]
Kodi status:
- C2 🈯️ 
- XU4 🈯️ 

Great work Meveric!!!

C2/XU4 stretch images now default on dietpi.com

**Comment by Fourdee** [comment]
I'am going to leave the C1 as Jessie for now. Lack any Debian Stretch image, and, time to really invest in achieving it.

Marking as completed.

**Comment by LexiconCode** [comment]
If were used an image down loaded to day do I need to redownload?

**Comment by Fourdee** [comment]
> If were used an image down loaded to day do I need to redownload?

If the following says "Jessie", then yes
```
cat /etc/os-release
```
