### ISSUE TITLE
INFO: On leave

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1555]
Hi all,

I will be taking a break from DietPi completely for at least a week, due to RL + ill health. I may be able to come back sooner, unknown at this time.

@MichaIng 
I've removed requirements for PR reviews. You should be able to accept merges from now on 👍 

@k-plan @MichaIng 
I'd be grateful if you could both continue with the work you do, and, help keep the ship running if/when you can. However, its never a requirement, as always in your own time, when/if you can.

**Comment by k-plan** [comment]
@Fourdee 

Think nothing of it! It's okay. No problem.

Get well soon!

**Comment by MichaIng** [comment]
@Fourdee 
Jep, take care your healthiness, children and wife 😃!

Thanks for merge permissions. I will do careful use. Waiting for your return before v6.3 release anyway 😉.
_________________________
Merged PRs for overview:
https://github.com/Fourdee/DietPi/pull/1553
https://github.com/Fourdee/DietPi/pull/1562

**Comment by symbios24** [comment]
Be well soon :)

**Comment by ghost** [comment]
@Fourdee Take your time and get well soon! :wink:

**Comment by Invictaz** [comment]
Get well soon :)

**Comment by ghost** [comment]
Get well soon! :)

**Comment by blogabe** [comment]
enjoy the time away with yours

**Comment by Fourdee** [comment]
Thanks all.

Can't keep away, need something to do in-between 🤢 and 🛌. Take each day as it comes :)

**Comment by k-plan** [comment]
Nice to see you back, Fourdee. :+1:   :heart:
