### ISSUE TITLE
OpenTyrian does not install on v104

### ISSUE THREAD

**Issue by EzTargetUK** [MichaIng/DietPi#157]
I'm trying to get an OpenTyrian and it fails to install.

Looking at the script dietpi-software, it looks like you are downloading the zip file for OpenTyrian with the name of "opentyrian_armhf.zip", but your attempting to unzip "dietpi-opentyrian.zip".

Simple fix, but I thought I should point it out incase anyone else wants to play this game on the Pi.

**Comment by Fourdee** [comment]
@EzTargetUK 
Hi,

Great find and thanks for letting us know, massive error on my part. This has been resolved for the next update (DietPi v105).
