### ISSUE TITLE
[dupe] Swap File Disabled

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1572]
Hello, i enabled swap file from DietPi-Config/swap file size and put it manual to 200mb and rebooted
writing the command free -m i see that the swap file is not enabled its 0mb 
How can it be enabled?

Thanks

**Comment by MichaIng** [comment]
@symbios24 
Could you resolve by yourself? What was the issue?

I reviewed in between and thought we should rework our swapfile generation script a bid, using some more error handling and checking for dphys-swapfile APT package availability.

**Comment by symbios24** [comment]
sorry but i had typos after i post it and i cannot edit any post probably coz i use old chrome version on XP.
