### ISSUE TITLE
Aria2 configuration cleared after reboot

### ISSUE THREAD

**Issue by Lanneer487** [MichaIng/DietPi#1575]
#### Please note, the aria2-webui does not support saving settings after session shutdown, this is a known limitation with the software, please use the aria2.conf to make changes:
- Stop services with ```dietpi-services stop```
- Edit the following configuration file ```/var/lib/dietpi/dietpi-software/installed/aria2.conf```, making your required changes.
- Start services with ```dietpi-services start```

---

Original Message:
_I installed Aria2 but when I change the settings in the WebUI, they get back to default after reboot. 
Is there a solution for this? I can't find the Aria2.conf file._

**Comment by Fourdee** [comment]
@roelfoubert 

Thanks for the report, i'll try to replicate.

**Comment by Fourdee** [comment]
Test:
- ```max-connection-per-server > 3 (1)```
- Save changes
- reboot
- 🈴 Reverts to 1

Confirmed. I'll take a look.

**Comment by Fourdee** [comment]
Looks like a limitation with aria2-webui:
https://github.com/ziahamza/webui-aria2/issues/164#issuecomment-151669830
https://github.com/XUJINKAI/aria2-with-webui/issues/3#issuecomment-324953489
🈴 Has no effect, file not updated https://github.com/ziahamza/webui-aria2/issues/36#issuecomment-11328963

no aria2.conf exists, ```--conf-path=``` https://github.com/hzamani/aria2web/blob/master/config/aria2.conf

---

🈯️ Will try upgrading install to use ```/var/lib/dietpi/dietpi-software/installed/aria2.conf```, allowing end user to change settings permanently.

🈯️ Online doc updated: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=6177#p6177

🈯️ Done, just need to add some optimizations for download limits etc.

**Comment by Fourdee** [comment]
@roelfoubert 

Workaround will be available once DietPi v6.3 is released, by editing the ```/var/lib/dietpi/dietpi-software/installed/aria2.conf```: https://github.com/Fourdee/DietPi/issues/1575#issue-301808769

ETA few days (mid next week) for DietPi v6.3.

Completed.

**Comment by Joulinar** [comment]
Aria2 configuration file should be located on `/mnt/dietpi_userdata/aria2/aria2.conf`

**Comment by bt61** [comment]
> Aria2 configuration file should be located on `/mnt/dietpi_userdata/aria2/aria2.conf`

ah, of course, thank you
