### ISSUE TITLE
(rpi3) qBittorrent Bug  Gui

### ISSUE THREAD

**Issue by Tnnuy-sv** [MichaIng/DietPi#1577]
good afternoon ! my qBittorrent spent 4 days following work without shutting down with 37 torrents stopped working the gui part, in the torrents they seem to be sowing I simply can not get in ... raspberry pi 3
<a href="http://tinypic.com?ref=2dt9aw1" target="_blank"><img src="http://i68.tinypic.com/2dt9aw1.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://tinypic.com?ref=1t37h3" target="_blank"><img src="http://i66.tinypic.com/1t37h3.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Fourdee** [comment]
@tnnuyri 

Hi,

Some issues here:
- You have disabled the swapfile. Not recommended and may cause "out of memory" errors + further issues due to that. Especially with large amounts of active torrent files.
- You have installed 2 BitTorrent clients. Ideally, you should only ever install 1 BitTorrent client (either Deluge or QBitTorrent)

Try a system reboot, see if the web interface returns.

**Comment by Tnnuy-sv** [comment]
Yes ! Whenever I reboot it is active again, I would like to know why this happens .. As for swapfile I did not disable it, I did the standard install of dietpi without changing these things I just connected an external disk by usb... tks

edit : I'll try to activate swapfile

**Comment by symbios24** [comment]
you wont make it in activating swap

**Comment by Fourdee** [comment]
@tnnuyri 

> As for swapfile I did not disable it, 

Ah, this is standard as of v6.0+. Which DietPi version are you running?

You can remove unneeded software in ```dietpi-software``` > Uninstall

**Comment by Tnnuy-sv** [comment]
I'm using version v6.2 !! I think the swapfile is shut down because I use the disk in NTFS format, I'll try to put it in ext4, just wanted to know if the error was out of memory, I have other mini pcs like tinker board, odroid c2, odroid xu4

edit :Do you think the error is caused by the lack of memory?

**Comment by Fourdee** [comment]
@tnnuyri 

> Do you think the error is caused by the lack of memory?

I believe so. Adding swapfile and sticking with 1 bittorrent client should resolve.

**Comment by Fourdee** [comment]
Marking as closed. Please reopen if required.
