### ISSUE TITLE
Webmin.com down. webmin-current.deb mirrir?

### ISSUE THREAD

**Issue by tordenflesk** [MichaIng/DietPi#1584]
#### Required Information:
- DietPi Version | v6.2
- SBC Device     | Odroid XU3/4 (armv7l) (index=11)
- Distro         | jessie (index=3)
- Command        | Connection test: http://www.webmin.com/download/deb/webmin-current.deb
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-Software

#### Expected behaviour:

Install webmin
#### Actual behaviour:

webmin.com is down [ isup.me/webmin.com ]
#### Steps to reproduce:

try to setup webmin...
#### Additional logs:
```
Log file contents:
Spider mode enabled. Check if remote file exists.
--2018-03-04 14:08:25--  http://www.webmin.com/download/deb/webmin-current.deb
Resolving www.webmin.com (www.webmin.com)... 108.60.199.109
Connecting to www.webmin.com (www.webmin.com)|108.60.199.109|:80... failed: Connection timed out.
Giving up.
```

**Comment by Fourdee** [comment]
@tordenflesk 

Hi,

Appears to be working fine currently, although the redirect is slightly slow:
```
root@DietPi:~# INSTALL_URL_ADDRESS='http://www.webmin.com/download/deb/webmin-current.deb'
root@DietPi:~# G_CHECK_URL "$INSTALL_URL_ADDRESS"
[  OK  ] Connection test: http://www.webmin.com/download/deb/webmin-current.deb
```

Please can you retry the software installation?

**Comment by tordenflesk** [comment]
I don't see the point when webmin.com is down.
http://www.isitdownrightnow.com/webmin.com.html
http://downforeveryoneorjustme.com/webmin.com

**Comment by Fourdee** [comment]
@tordenflesk 

![image](https://user-images.githubusercontent.com/7077026/36948396-2dbd0386-1fd2-11e8-8b6e-79db992359bb.png)
