### ISSUE TITLE
NanoPi Neo

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1588]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=2933&p=11286#p11286

**Comment by Fourdee** [comment]
- 🈯️ Image: based on FriendlyARM official image: http://dietpi.com/downloads/images/DietPi_NanoPiNEO-ARMv7-Buster.7z
- 🈯️ Update dietpi.com

**Comment by JimLee1996** [comment]
Awesome!

**Comment by JimLee1996** [comment]
[Bug Report]Dietpi-Software

![tim 20180306195822](https://user-images.githubusercontent.com/15334330/37031170-c094ff04-2178-11e8-82de-709e0fc4b39f.png)

**Comment by Fourdee** [comment]
@JimLee1996 

Thanks for the report 👍 

Which software title/s did you select for install?

**Comment by Fourdee** [comment]
@JimLee1996 

The issue https://github.com/Fourdee/DietPi/issues/1588#issuecomment-370759100 will be fixed in v6.3 update, should be released tomorrow.

I'll mark this as completed.

**Comment by JimLee1996** [comment]
In optimized software->nginx mariadb php.
