### ISSUE TITLE
Input methods don't work

### ISSUE THREAD

**Issue by ochaochaocha3** [MichaIng/DietPi#160]
On v105 LXDE, input methods (such as ibus, fcitx) fail to start with dbus connection error.
This is because `dbus-launcher` (included in `dbus-x11` package) doesn't exist.
I confirmed that installation of `dbus-x11` solved this problem, so could you please add this package on LXDE installation?

**Comment by Fourdee** [comment]
@ochaochaocha3 
Thanks for the report. :+1: 

`dbus-x11` will now be installed with the xserver package. The xserver package is installed automatically when xserver based programs are selected for install in dietpi-software (eg: lxde).

This fix will be available and patched for current installations of xserver in the next release (v106)

Please reopen if required.
