### ISSUE TITLE
[dupe] HTTPS for dietpi.com (SSL for the website, downloads, forum, ...)

### ISSUE THREAD

**Issue by ChargingBulle** [MichaIng/DietPi#1606]
dietpi.com lacks HTTPS support.
It just doesn't feel right to download images via insecure connections  
(```http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch.7z```)

**Comment by Fourdee** [comment]
@JonasDralle 

Hi, 

Thanks for the feedback.

We already have a ticket request for this feature, i'll mark this as closed in favor of:
https://github.com/Fourdee/DietPi/issues/830
