### ISSUE TITLE
MagicMirror support

### ISSUE THREAD

**Issue by Drew80** [MichaIng/DietPi#1609]
I stumbled across this the other day.  I was hoping we could get this as an install option for the DietPi.

DietPi running Magic Mirror on arm64 boards (Pine64+, Rock64, Odroid C2).  I have been trying to get it to work however my Linux Foo is not very good.  I can test but I thought with all of the boards DietPi supports it would be a great project and new feature to DietPi OS.

https://github.com/stacywebb/magicmirror_arm64

**Comment by Fourdee** [comment]
@Drew80 

Many thanks for the request, looks interesting 👍 

As with all software requests, we initially mark them as closed, then await interest from our community before reopening and investigating.
