### ISSUE TITLE
Shairport Sync [feature request]

### ISSUE THREAD

**Issue by nickrttn** [MichaIng/DietPi#161]
Integration of https://github.com/mikebrady/shairport-sync would be awesome. The installation process for this isn't too bad to do manually but I'll take automation any day. 

It makes the RPi a great lightweight AirPlay streaming device. I'm running it headless, connected to my stereo, without `libsox` and it's fine to be honest. Haven't tried the libsox functionality because I'm on a B+ and it's supposed to eat a lot of CPU.

**Comment by Fourdee** [comment]
@nickrttn 
Thanks for the request :+1: , looks interesting. I'll compile on my RPiv2 and take it for a spin. Hopefully we can make a .deb package for the installation to make it quicker.

**Comment by Fourdee** [comment]
Looking good. Running on Orange Pi PC:
![untitled](https://cloud.githubusercontent.com/assets/7077026/12222968/046405bc-b7c3-11e5-95ab-3ab499ff5ac6.png)

Will be available in next release (v106) from dietpi-software.
Most likely a .deb install. Just need to check if RPi 1 (ARMv6) needs its own compile.

**Comment by nickrttn** [comment]
Wow! that was :zap: fast! Thanks.

**Comment by Fourdee** [comment]
@nickrttn 

Ok done some testing with soxr interpolation:
![untitled](https://cloud.githubusercontent.com/assets/7077026/12235550/739edeb2-b86c-11e5-8c75-15873b2c62d4.png)

```
RPi v2 + soxr + resync_threshold=2250 (default) | Choppy, constant resyncing, it can't keep up.
RPi v2 + soxr + resync_threshold=0 (Disabled) | Fine, but defeats the purpose of sync.
RPi v2 + soxr + resync_threshold=3500 | Fine
```

So it looks like soxr is possible on a RPi v2 if you are willing to lapse the resync_threshold somewhat.

For the dietpi-software installation, I will leave interpolation on basic (disabling soxr) for the moment.

**Comment by Fourdee** [comment]
Update, using dietpi-nice to set nice -20 for shairport-sync resolves the choppiness:
![untitled](https://cloud.githubusercontent.com/assets/7077026/12235659/fa74e332-b86c-11e5-88aa-e4fbd87798cd.png)

```
RPi v2 + soxr + resync_threshold=2250 (default) + nice -20 (dietpi-nice) | Fine
```

Enabling soxr will be down to the user, but, I will put all this info on the dietpi-software site.

**Comment by Fourdee** [comment]
> http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5&p=1221#p1221

**Comment by Fourdee** [comment]
Completed. Available in next release (v106) from dietpi-software.

Planning to release v106 in a next few days.

**Comment by nickrttn** [comment]
Just wanted to let you know that I've been running it for a couple of days now, and it works perfectly. Thanks.

**Comment by Fourdee** [comment]
@nickrttn Excellent, no worries, good to hear :+1:
