### ISSUE TITLE
Odroid HC2

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1610]
Am I right, that Odroid HC2 is just a XU4 with 3,5" HDD holder, thus we can officially add HC2 to download and preparation script list as well?

**Comment by Fourdee** [comment]
@MichaIng 

Yep, XU3/XU4/HC1/HC2 are all the same device in relation to kernel and image.

Our XU4 image covers all the above.

**Comment by MichaIng** [comment]
@Fourdee 
Great, just wanted to be sure, if questions appear in forum/here. /close

**Comment by Fourdee** [comment]
@MichaIng 

👍 

I've updated http://dietpi.com/download with HC2 ref
