### ISSUE TITLE
Please add ApplePi DAC support

### ISSUE THREAD

**Issue by orchardaudio** [MichaIng/DietPi#1626]
Hello,

Please add ApplePi DAC overlay to your system.

Thanks;
Leo

#### Required Information:
- DietPi Version: All Versions 
- SBC Device: All Raspberry Pi Devices
- Power supply used: 5V 3A or 5.25V 3A
- SD card used: Any SD Card
- Distro (EG: Jessie) | Jessie

#### Expected behaviour:
Add overlay so that ApplePi DAC driver can be loaded with config.txt file similar to official Raspian release.

Please see here for additional info:
https://github.com/raspberrypi/linux/issues/2302

I have added a zip file containing the dtbo and dts files.
[ApplePi-DAC_dtbo_dts.zip](https://github.com/Fourdee/DietPi/files/1820430/ApplePi-DAC_dtbo_dts.zip)

**Comment by Fourdee** [comment]
@orchardaudio 

Hi,

Thanks for the request. Overlay appears to be in current APT kernel:
```
root@DietPi:~# ls -lha /boot/overlays/ | grep apple
-rwxr-xr-x 1 root root 1.5K Mar 14 16:33 applepi-dac.dtbo
root@DietPi:~# uname -a
Linux DietPi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
```

I'll add this to ```dietpi-config```.

---

```
root@DietPi:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ApplePiDAC [ApplePi-DAC], device 0: bcm2835-i2s-pcm1794a-hifi pcm1794a-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by Fourdee** [comment]
Completed, available as option in ```dietpi-config``` with DietPi v6.5. ETA 1-2 weeks release.

**Comment by orchardaudio** [comment]
Thanks for taking care of it.
