### ISSUE TITLE
Image update | Support RPi 3 B+

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1627]

**Comment by Fourdee** [comment]
Completed:
http://dietpi.com/download

**Comment by Fourdee** [comment]
Kernel dump/hang when enabling WiFi modules in ```dietpi-config```
- 🈯️ ```/DietPi/dietpi/func/dietpi-set_hardware wifimodules onboard_enable```
- 🈯️ ```/DietPi/dietpi/func/dietpi-set_hardware wifimodules enable```
- 🈯️ ```/DietPi/dietpi/func/dietpi-set_hardware wificreds set```
- 🈴 ```systemctl restart networking``` loss of SSH and all network devices (lo only)
- 🈴 ```wlan0     Interface doesn't support scanning : Network is down```
```
RTNETLINK answers: Operation not possible due to RF-kill
Listening on LPF/wlan0/b8:27:eb:8b:9f:35
Sending on   LPF/wlan0/b8:27:eb:8b:9f:35
Sending on   Socket/fallback
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 5
send_packet: Network is down
dhclient.c:2315: Failed to send 300 byte long packet over wlan0 interface.
receive_packet failed on wlan0: Network is down
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 6
send_packet: Network is down
dhclient.c:2315: Failed to send 300 byte long packet over wlan0 interface.
```

```
[   46.343551] brcmfmac: brcmf_fil_cmd_data: bus is down. we have nothing to do.
[   46.343799] brcmfmac: brcmf_fil_cmd_data: bus is down. we have nothing to do.
[   46.343802] brcmfmac: brcmf_cfg80211_get_channel: chanspec failed (-5)
```
- 🈯️ ```G_RPI_UPDATE``` | 🈴 ```reboot``` kernel hang

Looks like some possible kernel teething issues.

**Comment by Fourdee** [comment]
Other notes:
- 500MHz RAM vs 450MHz on RPi 3
```
root@DietPi:~#  vcgencmd get_config int
arm_freq=1400
audio_pwm_mode=514
config_hdmi_boost=5
core_freq=400
desired_osc_freq=0x33e140
desired_osc_freq_boost=0x3c45b0
disable_commandline_tags=2
disable_l2cache=1
disable_splash=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
force_eeprom_read=1
force_pwm_open=1
framebuffer_depth=16
framebuffer_height=720
framebuffer_ignore_alpha=1
framebuffer_swap=1
framebuffer_width=1280
gpu_freq=300
hdmi_force_cec_address=65535
init_uart_clock=0x2dc6c00
initial_turbo=20
lcd_framerate=60
over_voltage_avs=0x10c8e
over_voltage_avs_boost=0x2932e
over_voltage_sdram_p=2
pause_burst_frames=1
program_serial_random=1
sdram_freq=500
sdram_schmoo=0x2000020
temp_limit=75
```

**Comment by xmijo** [comment]
I'm getting some kind of kernel-related? error after issuing the reboot command where it will print a stack trace and freeze indefinitely. Not sure how to reproduce because it seems to happen randomly.

This is with the latest image on a Pi 3 B+.

**Comment by Fourdee** [comment]
@xmijo 

Thanks for the report 👍  
I can confirm we are able to replicate the same issues.

We are unsure the cause at the moment, however, learning towards possible kernel teething issues.

> Quite a few syntax errors and 'command not found' in the boot scripts (/DietPi/dietpi/boot and /DietPi/dietpi/dietpi-cpu_set). Prints on every boot. Also, "gettext.sh: No such file or directory" on login.

Linked to: https://github.com/Fourdee/DietPi/issues/1631#issuecomment-373965406

**Comment by xmijo** [comment]
I just edited my post, I see now that you guys are already aware of the wifi issues and the boot error messages seem to have disappeared after a re-image. Not sure what caused it in the first place but seems to work fine now. But if you were able to replicate it was probably not an isolated incident..

**Comment by MichaIng** [comment]
I also faced the missing gettext.sh message. Can investigate this evening.

**Comment by k-plan** [comment]
@MichaIng 

> Can investigate this evening.

https://github.com/Fourdee/DietPi/commit/5fda19cdf8879e04eab72fabe0324f0144c3dc8d

Hope this will not open a new case full of worms. :smile: 

But: `Why try wifi to start and Failed to try-restart ntp.service: Unit ntp.service not found.` is still open, if you have spare time: https://github.com/Fourdee/DietPi/issues/1631#issuecomment-374240509


_Edit: - or you want to have some fun:_ [Re: Odroid XU4 Fan speed.](http://dietpi.com/phpbb/viewtopic.php?f=11&t=2962&p=11472#p11471) :rofl:

**Comment by Fourdee** [comment]
Reference, confirmed kernel dump/crash on Raspbian:
 https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=207997#p1288529

Seems a possible hardware issue, bad batch?
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=207997&start=25#p1288697

**Comment by xmijo** [comment]
Has anyone else experienced kernel freezing (occasionally, not every time) when issuing the reboot command? Or did I also get a faulty unit

**Comment by Fourdee** [comment]
> Has anyone else experienced kernel freezing (occasionally, not every time) when issuing the reboot command? Or did I also get a faulty unit

Unsure, however, i'll re-create our DietPi image using a RPi 3 (non-plus) just to be sure.

**Comment by Fourdee** [comment]
Image updated, same random instability issues for me.
1/5 reboots results in instant kernel dump. There is no consistency to it.

Cant be 100% sure, but I believe its an issue with the LAN chip. Always referenced in kernel dumps, and, happens during systemD ifdown of networking.
```
lan78xx_delayedwork
```
![lan](https://user-images.githubusercontent.com/7077026/37671580-eda668f2-2c63-11e8-9d5a-1d0cbb115565.jpg)

**Comment by k-plan** [comment]
@Fourdee 

> ... i'll re-create our DietPi image using a RPi 3 (non-plus) just to be sure.

by this, can you please check wifi connection on RPi 3 (non-plus)?
Lack of hardware at the moment.

[Can't get wifi working on RPI3](http://dietpi.com/phpbb/viewtopic.php?f=11&t=2970)

[WiFi Problems (RPi 3)](http://dietpi.com/phpbb/viewtopic.php?f=11&t=2976)

>  I'm always getting this error:
> `null: error fetching interface information: device not found`
> when the system tries to connect to the WiFi.

**Comment by Fourdee** [comment]
@k-plan 

> by this, can you please check wifi connection on RPi 3 (non-plus)?

Yep, just tested fine with v6.4 image on RPi 3 (non-plus).

**Comment by Zvezke** [comment]
From reading the posts above, I understand that there are various issues - but I also understand that the latest version of DietPi should be bootable on 3B+.
I've downloaded (DietPi_v6.0_RPi-ARMv6-Stretch.img), flashed and attempted to boot, but no.
Am I missing something?

**Comment by xmijo** [comment]
@Zvezke The latest version of DietPi is 6.4, not 6.0. Get the latest version from [dietpi.com/download](http://dietpi.com/download)

**Comment by Zvezke** [comment]
@xmijo Thanks for replying, Xmijo. I only see one option to download - choosing 'Download image' - which automatically starts downloading 'DietPi_RPi-ARMv6-Stretch.7z'. Is there a way to choose v6.4?
![image](https://user-images.githubusercontent.com/10761510/37828946-75b8f288-2e9d-11e8-9fa1-3bc76964c252.png)

**Comment by Fourdee** [comment]
@Zvezke 

The version number is listed inside the .7z file. Download the file and you'll see its v6.4 :)

**Comment by Zvezke** [comment]
Oh, indeed it is. Sorry for the inconvenience.

**Comment by Fourdee** [comment]
WiFi solution is:
```
rfkill unblock wifi
```

Once run, WiFi + scan is now functional. Seems a permanent setting on subsequent reboots, once applied.

**Comment by Fourdee** [comment]
WiFi fixed: https://github.com/Fourdee/DietPi/commit/02e1f6bebb09a93c89e896fb7b606f25ee8952db

My device works fine with LAN disabled and WiFi use only. But, i will be sending it back due to fault: 
https://github.com/Fourdee/DietPi/issues/1627#issuecomment-374669173

Completed.

**Comment by xmijo** [comment]
Great news that wifi is fixed

Is the kernel hang on reboot the reason for returning your device @Fourdee ? Do the issues persist on regular Rasbian, too? (Haven't got access to my device atm so cannot test it myself)
