### ISSUE TITLE
no open-ssh on "DietPi_OdroidC2-ARMv8-Stretch.7z"

### ISSUE THREAD

**Issue by pgferr** [MichaIng/DietPi#1632]
in optimezed software i found only dropbear and i have problem connecting by winscp with sftp protocol. If i use "DietPi_OdroidC2-ARMv8-Jessie.7z" is available also open-ssh. Is there any issue?

#### Required Information:
- DietPi Version 6.4
- SBC Device odroid c2
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used samsun 64
- Distro stretch

#### Additional Information (if applicable):
open ssh
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by k-plan** [comment]
@pgferr 

> If i use "DietPi_OdroidC2-ARMv8-Jessie.7z" is available also open-ssh. Is there any issue?

![180318-0002](https://user-images.githubusercontent.com/17237601/37566403-e4c7b9f4-2ab8-11e8-90a2-5a4e522bb270.gif)


![180318-0004](https://user-images.githubusercontent.com/17237601/37566410-ef828810-2ab8-11e8-80a9-ca65719bb516.gif)

You have to change SSH Server choice here.
After hit < `OK` > you have to choose `Install` hit < `OK` >

![180318-0006](https://user-images.githubusercontent.com/17237601/37566452-9b005406-2ab9-11e8-8a46-5609abec2bed.gif)

**Comment by pgferr** [comment]
i need php7 for moodle 3.4 and php7 is avilable only for stretch:
also if i use apache 2 i cannot see it.


open ssh is absolutely unavailable

2018-03-18 14:35 GMT+01:00 k-plan <notifications@github.com>:

**Comment by k-plan** [comment]
@pgferr 

1. - http://dietpi.com/#download => is only `DietPi_v6.0`_**OdroidC2**`-ARMv8-`**Jessie**`.img` at the moment. So this is supported.

2. - `DietPi_v6.2_OdroidC2-ARMv8-Stretch.img` is unready beta/testing image not fully supported.


> open ssh is absolutely unavailable

open-ssh is absolutety working on Odroid C2 DietPi v6.4 - Stretch.
unable to see any problems:

```
 ───────────────────────────────────────
 DietPi     | 15:51 | Sun 18/03/18
 ───────────────────────────────────────
 v6.4       | Odroid C2 (aarch64)
 ───────────────────────────────────────

root@Odroid-C2-Stretch:~# uname -a
Linux Odroid-C2-Stretch 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux


root@Odroid-C2-Stretch:~# cat /proc/version
Linux version 3.14.79+ (root@odroid-jessie64) (gcc version 4.9.2 (Debian/Linaro 4.9.2-10) ) #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017


root@Odroid-C2-Stretch:~# cat /etc/debian_version
9.4


root@Odroid-C2-Stretch:~# cat /DietPi/dietpi/.version
6
4


root@Odroid-C2-Stretch:~# service ssh status
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-03-18 15:50:48 GMT; 2min 18s ago
  Process: 498 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
 Main PID: 537 (sshd)
   CGroup: /system.slice/ssh.service
           ├─ 537 /usr/sbin/sshd -D
           ├─1839 sshd: root@pts/0
           ├─1844 -bash
           ├─2017 systemctl status ssh.service
           └─2022 pager

Mar 18 15:50:47 Odroid-C2-Stretch systemd[1]: Starting OpenBSD Secure Shell server...
Mar 18 15:50:48 Odroid-C2-Stretch sshd[537]: Server listening on 0.0.0.0 port 22.
Mar 18 15:50:48 Odroid-C2-Stretch sshd[537]: Server listening on :: port 22.
Mar 18 15:50:48 Odroid-C2-Stretch systemd[1]: Started OpenBSD Secure Shell server.
Mar 18 15:51:25 Odroid-C2-Stretch sshd[1839]: Accepted password for root from 192.168.0.123 port 50746 ssh2
Mar 18 15:51:25 Odroid-C2-Stretch sshd[1839]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

![180318-0007](https://user-images.githubusercontent.com/17237601/37568014-a0d8ac6e-2acf-11e8-8238-607f7ce499da.gif)

**Comment by Fourdee** [comment]
Marking as closed, please reopen if required.
