### ISSUE TITLE
apache installation non recognized from "optimized-software" 

### ISSUE THREAD

**Issue by pgferr** [MichaIng/DietPi#1633]
i am using "DietPi_OdroidC2-ARMv8-Stretch.7z"  and i have installed lamp (maria db) server environment. But in management script there are two prpblems: apache installation is not recognized from "optimized-software" 
I can see only lighttpd and i cannot install phpmyadmin?
tks

#### Required Information:
- DietPi Version | 6.4
- Distro stretch
#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by k-plan** [comment]
@pgferr 

can you please show us your first screen of `dietpi-software` ?

example:

![180318-0001](https://user-images.githubusercontent.com/17237601/37566361-4d691652-2ab8-11e8-88e3-10ace2d1fd5b.gif)

and output of:

`dietpi-software list | grep "| =2"`

**Comment by Fourdee** [comment]
No response/unable to replicate, marking as closed. Please reopen if required.
