### ISSUE TITLE
want to add a login info "df -h"

### ISSUE THREAD

**Issue by msongz** [MichaIng/DietPi#1637]
i want to know what size left of my storage every login

`df -h | grep '/dev/root'| awk '{ print $4 }'`

so, how to add it to the /DietPi/dietpi/login script ?

**Comment by msongz** [comment]
I add it to the bottom of .zshrc to work around
thank you

**Comment by Fourdee** [comment]
Another option, DietPi-Autostart > custom:
![image](https://user-images.githubusercontent.com/7077026/37603991-db8389f2-2b87-11e8-9ca0-3e0f75ce3ed8.png)
![image](https://user-images.githubusercontent.com/7077026/37604014-e92a953c-2b87-11e8-9827-44f8c20ccbe6.png)
