### ISSUE TITLE
Orange Pi i96 image

### ISSUE THREAD

**Issue by woiza** [MichaIng/DietPi#1639]
Any plans to release an image for Orange Pi i96?

https://www.96boards.org/product/orangepi-i96/

**Comment by Fourdee** [comment]
@woiza 

Hi,

Thanks for the request 👍 

We will not be able to provide a image/support for this device at this time. However, you can use DietPi-PREP on any Debian pre-image to create your own DietPi installation:
https://github.com/Fourdee/DietPi/issues/1285#issue-280771944
