### ISSUE TITLE
[LeMaker Guitar] DietPi on Debian Stretch (old kernel)

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1642]
#### Required Information:
- DietPi Version | 6.4
- SBC Device (EG: RPi 3)? LeMaker Guitar
- Power supply used (EG: 5v 1A RAVpower)? 12V 5A = if not using this PSU, it won't boot anyways
- SD card used (EG: Sandisk ultra)? PNY 16 GB (class 10)
- Distro (EG: Jessie) | Debian Stretch (Linux GuitarPi 3.10.105-s500)

#### Expected behaviour:
Never thought that DietPi will run on this device after upgrade from ARMBIAN to DIETPI with success. Afterwards upgrading from JESSIE to STRETCH was an easy going....

#### Actual behaviour:
It runs out-of-the box !

#### Steps to reproduce:
First install ARMBIAN for LeMaker Guitar for SDCard (do not put it on eMMC onboard!!!) , than use latest PREP-script by being connected via eth0. After all, get the PREP-script like it is described on the main page for DietPi. -> https://github.com/Fourdee/DietPi/issues/1285#issue-280771944

#### Did you submit a ```dietpi-bugreport```?
None, as not required!

#### Extra details:
I've never thought, that it would work with such an non anymore supported SBC.

#### Contribute:
@DietPi @noplanman and the whole team.... It just works.....!

HUGE THANKS ! :) :+1:

**Comment by Fourdee** [comment]
@SuBLiNeR 

Thanks for the feedback and info 👍 

I'll mark this as closed.
