### ISSUE TITLE
[dupe] DietPi 6.5 - apt-get errors... ?

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1655]
# Dupe: https://github.com/Fourdee/DietPi/issues/1659

---

#### Required Information:
- DietPi Version | 6.5
- SBC Device (EG: RPi 3)? RPi3

apt-get update gets you IGN or Error on fetching files from source.

1) did run apt-get update
2) did run apt-get upgrade
3) reboot
4) did dietpi-update (no stranged things happend)
5) reboot - after dietpi was succesful updated
6) login and did apt-get update again -> errors and ignore sources... what happened there?!?

btw. only happens to RPi3B if not (!) firstly run apt-get update && apt-get upgrade before dietpi-update....

there must happen something stranged somehow.... isn't it?

**Comment by rawwalk13** [comment]
I got the same problem today on my RPI2 & RPI3.
What i did is just add another working repo to the /apt/sources.list

That solved the problem instantly,  although i dont know if that was the right thing to do .

**Comment by Fourdee** [comment]
@SuBLiNeR @rawwalk13 

Thanks for the report 👍 

Confirmed, when upgrading ```raspberrypi-sys-mods``` package which fails to correctly apply the patch (not our bug, but we'll attempt fix).
https://github.com/Fourdee/DietPi/issues/1659

I'll mark this as closed in favor of https://github.com/Fourdee/DietPi/issues/1659

**Comment by Fourdee** [comment]
@SuBLiNeR @rawwalk13 
Temp fix for now, to get it working until we can fully resolve:
https://github.com/Fourdee/DietPi/issues/1659#issuecomment-377301370
