### ISSUE TITLE
DietPi-Update v6.5 | Allo firmware installed on non-AlloGUI RPi?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1656]
@Fourdee 
https://github.com/Fourdee/DietPi/blob/testing/dietpi/patch_file#L529-L538
Shouldn't this be done just on RPi's that use AlloGUI?

**Comment by Fourdee** [comment]
@MichaIng 

> Shouldn't this be done just on RPi's that use AlloGUI?

As this card can be installed via ```dietpi-config```, ideally, we need it preinstalled for all.

Although, we could do a "ondemand net install" of the firmware through ```dietpi-set_hardware```, for those cards, if needed.

**Comment by MichaIng** [comment]
@Fourdee 
> Although, we could do a "ondemand net install" of the firmware through dietpi-set_hardware, for those cards, if needed.

Jep, would prefer that way, keeping image/systems as slim as possible. But no need for urgent patch, as the firmware is just ~500k.

**Comment by MichaIng** [comment]
PR: https://github.com/Fourdee/DietPi/pull/1718

**Comment by Fourdee** [comment]
I'll run tests with Piano dac installed:
- 🈯️ RPi 3
- 🈯️ Sparky

Test with Piano dac not installed:
- 🈯️ 

---

patch removes ```/lib/firmware/allo```, will send commit.

**Comment by Fourdee** [comment]
Good to go 👍 Marking as completed.
