### ISSUE TITLE
Raspbian mirror changed to "raspbian.raspberrypi.org"

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1659]
# Workaround: https://github.com/Fourdee/DietPi/issues/1659#issuecomment-377301370

---

I just found the new version of `raspberrypi-sys-mods` trying to auto-adjust the Raspbian mirrors from [archive.raspbian.org](http://archive.raspberrypi.org) and [mirrordirector.raspbian.org](http://mirrordirector.raspbian.org) to [raspbian.raspberrypi.org](http://raspbian.raspberrypi.org) on APT upgrade.

All 3 repos are (still) active providing the same set of packages, so I am not sure if this means that the first two will be shut down by times or something, moving everything into [raspberrypi.org](https://raspberrypi.org) domain, but this needs to be observed at least I think.

[raspbian.raspberrypi.org](http://raspbian.raspberrypi.org) is not reachable via https and would be interesting to know if mirror direction is included. I didn't find any news/hint/info about this repo anywhere, not on [raspbian.org](https://raspbian.org) nor [raspberrypi.org](https://raspberrypi.org) nor anywhere via search machines.

**Comment by Fourdee** [comment]
Notes:
- ```raspberrypi-sys-mods``` patch breaks ```/etc/apt/sources.list```
```
root@DietPi:~# cat /etc/apt/sources.list
deb https://www.mirrorservice.org/sites/archive.raspbian.org/raspbian stretch main contrib non-free rpi

###

root@DietPi:~# apt-get dist-upgrade
raspberrypi-sys-mods
Updating apt sources from {mirrordirector,archive}.raspbian.org to raspbian.raspberrypi.org...

###

root@DietPi:~# cat /etc/apt/sources.list
deb https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch main contrib non-free rpi
```

```
E: Failed to fetch https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian/dists/stretch/main/binary-armhf/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Fourdee** [comment]
#### Temp workaround/fix for those who have run ```apt-get dist-upgrade```, and, are unable to update APT:
- Example of error: https://github.com/Fourdee/DietPi/issues/1659#issuecomment-377297103
- copy/paste all
```
cat << _EOF_ > /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian stretch main contrib non-free rpi
_EOF_
G_AGUP
```

**Comment by ghost** [comment]
why don't they know about this bug at theirs repo?

**Comment by Fourdee** [comment]
@SuBLiNeR

> why don't they know about this bug at theirs repo?

Feel free to tell them 😃 

Its a terrible patch (which is rare for RPi) and does not accommodate any changes to ```/etc/apt/sources.list```. I can only assume it works with Raspbian untouched (untested).

**Comment by ghost** [comment]
@Fourdee that's why it wasn't working:
it was this in mine: https://www.mirrorservce.org/...... ?
Now as i edited it to only go directly to via http://rasbian.raspberry.org it is working...

**Comment by MichaIng** [comment]
@SuBLiNeR @Fourdee 
Yeah it is not exactly a bug at their repo, it is just an absolutely negligent way of adjusting a config file 👎!!
Just sed `{mirrordirector,archive}.raspbian.org` sting within sources.list without assuring that it is not part of another URL like in our case... This even breaks sources.list if `https://archive.raspbian.org` was used.

As I use another mirror, I didn't face this bug 😅.

€: I just sent comment on their commit: https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/f2db61056a1b8abfc8ace68c39a56d584938bff1

**Comment by Fourdee** [comment]
Ok: https://github.com/Fourdee/DietPi/commit/786e4d48395a4cf9ee595b888e7ef7bafb04fd18
- Existing images should be fine, we do not run ```G_AGDUG```, which is the only way to install the updated ```raspberrypi-sys-mods``` package currently.
- Patch will run ```G_AGDUG``` to force the update, then reset ```/etc/apt/sources.list``` with the new default ```http://raspbian.raspberrypi.org/raspbian```

**Comment by MichaIng** [comment]
@Fourdee 
I think there will be no fast fix for this, thus if we want to prevent users from running into this issue, we need to switch the mirror ourself correctly. I hate that there is really no other way and we need to drop mirrordirector for now... Besides, we could also add our default mirrordirector to some sources.list.d/ file instead, leaving sources.list empty, but this is everything else than beautiful as well...

So:
```
if grep -qE '(mirrordirector|archive).raspbian.org' /etc/apt/sources.list; then

    sed -iE "\#(mirrordirector|archive).raspbian.org#c\deb http://raspbian.raspberrypi.org/raspbian $G_DISTRO_NAME main contrib non-free rpi#g" /etc/apt/sources.list

fi
```
And replacing DietPi default mirror and dietpi-config selection menu as well.

**Comment by Fourdee** [comment]
@MichaIng 

> I think there will be no fast fix for this, thus if we want to prevent users from running into this issue, we need to switch the mirror ourself correctly.

Yep, so i went for forced upgrade to cause the issue, then reset to new default ```http://raspbian.raspberrypi.org/raspbian``` (cover all) https://github.com/Fourdee/DietPi/issues/1659#issuecomment-377561175

**Comment by MichaIng** [comment]
@Fourdee 
Jep, I thought wrong, this is the only way, great job 😃! (removed above, to avoid confusion 😆)

**Comment by Fourdee** [comment]
Ok, great work on this @MichaIng 👍 

Tested RPi with patch, running fine. I'll mark this as completed. We'll need to keep an eye out for when/if ```http://raspbian.raspberrypi.org/raspbian``` goes ```https```, then update accordingly.

**Comment by Fourdee** [comment]
REF: https://twitter.com/DietPi_/status/979761183359107077
