### ISSUE TITLE
DietPi-Software | Whoopsie: G_WHIP implementation broke menu uninstall array, Hotfix!

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1660]
@Fourdee 
https://github.com/Fourdee/DietPi/commit/0767ef022230ab06f926f1be6781cd23939a3205

I felt free to directly merge this into master. The implementation of G_WHIP into uninstall menu broke the array, leading to nothing get's uninstalled. Tested and works as expected again.

Hmm, do we need hotfix update for this as well, as many user must have updated already?

**Comment by ghost** [comment]
Hotfix.... v6.5a ... ;)

**Comment by MichaIng** [comment]
@SuBLiNeR 
Jep, we will see, but as the fix is tiny, clean, easy to test and only called from a single UI element, I thought it is best to directly fix this for current updates.

But indeed, maybe we need hotfix update again, as this is quite a basic feature 😆. Currently no subsubversions or letters inside version string are supported. Would need some dietpi-update rework to implement. And as this is just a visual uncritical topic, I think we would call the hotfix v6.6 😉.

**Comment by Fourdee** [comment]
@MichaIng 

>  I think we would call the hotfix v6.6

Yep, Once we sort out https://github.com/Fourdee/DietPi/issues/1659#issuecomment-377301370, we'll do a hotfix for v6.6

> I felt free to directly merge this into master.

Yep nice one 👍

**Comment by Fourdee** [comment]
@MichaIng 

I assigned you to ticket, but for the record its probably my whoopsie! 🤣 👍

**Comment by Fourdee** [comment]
Uninstall test passed 🈯️ 

I'll mark this as resolved, thanks @MichaIng 👍
