### ISSUE TITLE
USB 1.0 DAC on Nanopi 

### ISSUE THREAD

**Issue by paulstephane** [MichaIng/DietPi#1669]
## Creating a bug report/issue:

Hello, on the nanopi neo image there seems to be no possibility to activate the USB audio as a USB 1 driver, similar to what can be done on the sparky board (changing uEnv file)
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by paulstephane** [comment]
Linux DietPi 4.14.0 #1 SMP Mon Dec 18 11:43:22 CST 2017 armv7l GNU/Linux
Dietpi version 6.5

**Comment by ghost** [comment]
@paulstephane I suggest you're using an armbian install as base? - see for reference: http://dietpi.com/phpbb/viewtopic.php?t=1896 - there is a problem with these dev-kernels and i'm not sure if this is the problem at least for your case...

**Comment by paulstephane** [comment]
I will look into it, thanks
