### ISSUE TITLE
Orange pi zero updgrade from Armbian Debian Jessie to DietPi

### ISSUE THREAD

**Issue by SmoothSilence** [MichaIng/DietPi#1672]
#### Required Information:
- DietPi Version | ```DietPi Beta(I think) for "othet" SBC```
- SBC Device (Orange Pi zero H2+ (512))
- Power supply used (5v 2A )
- SD card used (Sandisk ultra 16 Gb class 10 I)?
- Distro (Armbian-Debian-Jessie) 

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

#### Expected behaviour:

The Orange Pi zero shuld finish the upgrade to the DietPi and reboot. Booting me to the DietPi menu

#### Actual behaviour:

The installation has been terminated. With this message.
![new bitmap image](https://user-images.githubusercontent.com/37971855/38170479-d20c12c8-3586-11e8-9188-c60334ae8e2d.jpeg)

After pressing okay I rebooted the pi, I tried to log into it via SSH but it showed the 'connection timed out' error message.

**Comment by ghost** [comment]
@SmoothSilence Hi there, if you like to go from ARMBIAN to DietPi, you should do following steps:

1) Get actual latest image for your device (OPi Zero) best is Debian (Stretch) - https://dl.armbian.com/orangepizero/archive/Armbian_5.38_Orangepizero_Debian_stretch_next_4.14.14.7z 
2) after succesful boot into "armbian", do a firmware update via armbian-config & reboot!!!
3) manually install the above mentioned package - (e.g. `apt-get install firmware-misc-nonfree` )
4) than do the steps with the PREP-script.
5) You should now be on DietPi v6.x after completation of the script and some reboots afterwards.

Please give feedback if this works for you.... as it worked for myself without any problems on this device.

**Comment by Fourdee** [comment]
No response, marking as closed. Please reopen if required.
