### ISSUE TITLE
Update RPi image

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1676]
> https://github.com/Fourdee/DietPi/issues/1675#issuecomment-377807772

**Comment by ghost** [comment]
hmmmm.... why is v6.6 on testing and "master" ?

**Comment by MichaIng** [comment]
@SuBLiNeR 
v6.6 was just released some minutes ago, give us some chance to adjust the version strings 😉.

**Comment by Fourdee** [comment]
Completed:
http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch.7z
