### ISSUE TITLE
Error running dietpi-update

### ISSUE THREAD

**Issue by yonesmit** [MichaIng/DietPi#1678]
#### Required Information:
- DietPi Version | v6.5
- SBC Device     | RPi 2 Model B (armv7l) (index=2)
- Distro         | stretch (index=4)
- Command        | G_AGI: firmware-misc-nonfree
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-Patchfile

#### Additional logs:
```
Log file contents:
E: Failed to fetch https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-misc-nonfree_20161130-3+rpt3_all.deb  Operation timed out after 120000 milliseconds with 0 out of 0 bytes received
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Fourdee** [comment]
@yonesmit 

Thanks for the report 👍 

Appears to be a issue with the RPi repo server during download (timeout). Please retry ```dietpi-update```.

URL is working here: https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-misc-nonfree_20161130-3+rpt3_all.deb

**Comment by yonesmit** [comment]
I tried to run dietpi-update again. And the result is:
<code>
[  OK  ] Root access verified.
[ INFO ] DietPi-Drive_Manager | Checking RootFS R/W access. Please wait...
[  OK  ] DietPi-Drive_Manager | RootFS R/W access.


 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Checking for DietPi updates

[ INFO ] DietPi-Update | Checking Mirror : http://dietpi.com/downloads/dietpi-update_mirror/master/server_version-6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     4  100     4    0     0     17      0 --:--:-- --:--:-- --:--:--    17
[  OK  ] DietPi-Update | Using update server: http://dietpi.com/downloads/dietpi-update_mirror/master/server_version-6

[  OK  ] DietPi-Update | No updates required, your DietPi installation is up to date.

[ INFO ] DietPi-Update | Current Version : 6.6
[ INFO ] DietPi-Update | Server Version  : 6.6
</code>

No errors, but it doesn't try to update any package.
Best Regards,

**Comment by Fourdee** [comment]
@yonesmit 


Set the version to 6.5, then redo the update, just to make sure it completed:
```
echo -e "6\n5\n" > /DietPi/dietpi/.version
dietpi-update
```

**Comment by yonesmit** [comment]
I set the version to 6.5 and ran again the update procedure. The process went correctly without errors.
Thanks for your support.
Best Regards,

**Comment by MichaIng** [comment]
@yonesmit 
Great, will mark as closed. Just for the record: If something went wrong during dietpi-update process but it still runs through (adjusting version string), we just implemented an option to rerun the current patch, so no need to manually adjust `.version` anymore 😉: `dietpi-update -1`

**Comment by Fourdee** [comment]
@MichaIng 

> dietpi-update -1

Forgot about this, nice one 👍
