### ISSUE TITLE
openjdk-8-jdk/Nukkit fails to install on RPi

### ISSUE THREAD

**Issue by royspeed** [MichaIng/DietPi#1682]
# Workaround : https://github.com/Fourdee/DietPi/issues/1682#issuecomment-378664539

---

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device RPi 3
- Power supply used 5v 5A 
- SD card used Sandisk ultra32 Gb & 2Gb
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title Nukkit
- Can this issue be replicated on a fresh installation of DietPi, Yes

#### Expected behaviour:
 Error on install

#### Actual behaviour:

DietPi Error Handler: ├─────────────────────────────┐
          │                                                                                   │ 
          │ DietPi-Software: G_AGI: openjdk-8-jdk                                               
          │  - exit_code = 100                                                                  
          │  - VERSION:v6.6 | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4                                 
          │                                                                                     
          │ Log file contents:                                                                  
          │ Setting up libgtk-3-0:armhf (3.22.11-1+rpi3) ...^M                                  
          │ Setting up libatk-wrapper-java-jni:armhf (0.33.3-13+deb9u1) ...^M                   
          │ Setting up ca-certificates-java (20170531+nmu1) ...^M                               
          │ Error: missing `server' JVM at                                                      
          │ `/usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/server/libjvm.so'.^M                 
          │ Please install or use the JRE or JDK that contains these missing components.^M      
          │ dpkg: error processing package ca-certificates-java (--configure):^M                
          │  subprocess installed post-installation script returned error exit status 4^M       
          │ dpkg: dependency problems prevent configuration of openjdk-8-jre-headless:armhf:^M  
          │  openjdk-8-jre-headless:armhf depends on ca-certificates-java; however:^M           
          │   Package ca-certificates-java is not configured yet.^M      ^M                                                                                  
          │ dpkg: error processing package openjdk-8-jre-headless:armhf (--configure):^M        
          │  dependency problems - leaving unconfigured^M                                       
          │ dpkg: dependency problems prevent configuration of openjdk-8-jdk-headless:armhf:^M  
          │  openjdk-8-jdk-headless:armhf depends on openjdk-8-jre-headless (=                  
          │ 8u162-b12-1~deb9u1); however:^M                                                     
          │   Package openjdk-8-jre-headless:armhf is not configured yet.^M                     
          │ ^M                                                                                  
          │ dpkg: error processing package openjdk-8-jdk-headless:armhf (--configure):^M        
          │  dependency problems - leaving unconfigured^M                                       
          │ dpkg: dependency problems prevent configuration of openjdk-8-jdk:armhf:^M           
          │  openjdk-8-jdk:armhf depends on openjdk-8-jdk-headless (= 8u162-b12-1~deb9u1);      
          │ however:^M                                                                          
          │   Package openjdk-8-jdk-headless:armhf is not configured yet.^M                     
          │ ^M                                                                                  
          │ dpkg: error processing package openjdk-8-jdk:armhf (--configure):^M  dependency problems - leaving unconfigured^M                                       
          │ dpkg: dependency problems prevent configuration of openjdk-8-jre:armhf:^M           
          │  openjdk-8-jre:armhf depends on openjdk-8-jre-headless (= 8u162-b12-1~deb9u1);      
          │ however:^M                                                                          
          │   Package openjdk-8-jre-headless:armhf is not configured yet.^M                     
          │ ^M                                                                                  
          │ dpkg: error processing package openjdk-8-jre:armhf (--configure):^M                 
          │  dependency problems - leaving unconfigured^M                                       
          │ Processing triggers for libc-bin (2.24-11+deb9u3) ...^M                             
          │ Processing triggers for systemd (232-25+deb9u2) ...^M                               
          │ Processing triggers for libgdk-pixbuf2.0-0:armhf (2.36.5-2+deb9u2) ...^M            
          │ Processing triggers for ca-certificates (20161130+nmu1) ...^M                       
          │ Updating certificates in /etc/ssl/certs...^M                                        
          │ 0 added, 0 removed; done.^M                                                         
          │ Running hooks in /etc/ca-certificates/update.d...^M                                 
          │ ^M                                                           Error: missing `server' JVM at                                                      
          │ `/usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/server/libjvm.so'.^M                 
          │ Please install or use the JRE or JDK that contains these missing components.^M      
          │ E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.^M                 
          │ done.^M                                                                             
          │ Errors were encountered while processing:^M                                         
          │  ca-certificates-java^M                                                             
          │  openjdk-8-jre-headless:armhf^M                                                     
          │  openjdk-8-jdk-headless:armhf^M                                                     
          │  openjdk-8-jdk:armhf^M                                                              
          │  openjdk-8-jre:armhf^M                                                              
          │ E: Sub-process /usr/bin/dpkg returned an error code (1)                             
          │                                                                                     
          │ If problems persist, please report this to DietPi for investigation, including a    
          │ screenshot of this error! (https://github.com/Fourdee/DietPi/issues).

#### Steps to reproduce:
Just install via dietpi-software

#### Did you submit a ```dietpi-bugreport```?
 241b6064-2af7-4102-a050-b235d3ca5b7b-0

**Comment by Fourdee** [comment]
@royspeed 

Thanks for the report 👍 

We'll investigate.

**Comment by Fourdee** [comment]
notes:
```
root@DietPi:~# find / -name libjvm.so
/usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/client/libjvm.so
```
- This is an external bug, straight forward installation of ```openjdk-8-jdk``` fails. Seems to have happened in the past: https://www.raspberrypi.org/forums/viewtopic.php?t=197824

**Comment by Fourdee** [comment]
## Workaround:
#### Run the following commands BEFORE installing Nukkit, or, OpenJDK:
```
G_AGP ca-certificates-java openjdk-8*
G_AGI ca-certificates-java
G_AGI openjdk-8-jre-headless
G_AGI openjdk-8-jdk
```

Confirmed RPi repo is only affected by this issue.

---

mmm, temp issue with repo.

```
[FAILED] DietPi-Software | G_AGI: ca-certificates-java
[ INFO ] DietPi-Software | exit_code = 100
[ INFO ] DietPi-Software | VERSION:v6.7 | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4
[ INFO ] DietPi-Software | Log file contents:
E: Failed to fetch https://archive.raspberrypi.org/debian/pool/main/o/openjdk-9/openjdk-9-jre-headless_9~b181-4~bpo9+rpt1_armhf.deb  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

And this install JDK 9 ```openjdk-9-jre-headless```

- ```ca-certificates-java``` is required for ```openjdk-8-jre-headless``` to succeed, however, installs ```openjdk-9-jre-headless```
-  ```openjdk-8-jre-headless``` is required for ```openjdk-8-jdk``` to succeed.

🈯️ Nukkit install passed

**Comment by Fourdee** [comment]
## Another method/workaround:
```
G_AGI ca-certificates-java
G_AGI openjdk-8-jre-headless
G_AGI openjdk-8-jdk
```

Confirmed RPi repo is only affected by this issue.

**Comment by Fourdee** [comment]
As workarounds go, not ideal as ```openjdk-9-jre-headless``` is installed, however, this fixes the installation error with the ```openjdk``` package in Raspbian repo, and, will be applied to v6.7.

Completed.

**Comment by ravikv123** [comment]
run the below command.. it may solve the issue
**apt-get update
apt-get upgrade
apt-get install -f openjdk-8-jdk**

**Comment by MichaIng** [comment]
Jep `apt-get -f install` is the workaround we've implemented as well.
