### ISSUE TITLE
Nodered User add to GPIO

### ISSUE THREAD

**Issue by DrJeff** [MichaIng/DietPi#1687]
Node Red needs the user `nodered` to be added to the GPIO group or gpio doesn't work I used this
```
sudo adduser nodered gpio
```
Hope it helps anyone else stuck with no GPIO control

**Comment by Fourdee** [comment]
@DrJeff 

Thanks for the heads up 👍 

We'll apply this fix to v6.7.

**Comment by Fourdee** [comment]
Resolved for v6.7 + patched during update.

@DrJeff 
Thanks again 👍
