### ISSUE TITLE
Tor Hotspot is not Working

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1692]
Hi,
Using latest Dietpi v6.6 with a Raspberry pi 3 i installed wifi hotspot is working fine
i installed tor hotspot the hotspot is not visible/available,is not shown on any wifi device computer/smartphone
as i see in the dietpi process screen the hot-spot or tor hotspot are not there 
the dietpi-services are started ok isc-dchp-server,hostapd,cron

in other words the tor hospot is not working

**Comment by symbios24** [comment]
Update: if tor is installed together with wifi hotspot its not working if its installed separate :eg first hotspot and then tor its working.

**Comment by Fourdee** [comment]
>> https://github.com/Fourdee/DietPi/issues/1810

**Comment by Fourdee** [comment]
I'll mark this as closed in favor of : https://github.com/Fourdee/DietPi/issues/1810
