### ISSUE TITLE
Plex media server Additional Info

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1697]
Hello, i was wondering if you can put any additional Info about Plex Media Server about how to Host files from the server over Wifi. since the setup its only hosting over Lan.
Or its just as easy as installing WiFi HotSpot with plex server and thats it?
and also suggest some plex clients apps

Thank you

**Comment by Fourdee** [comment]
@symbios24 

> Or its just as easy as installing WiFi HotSpot with plex server and thats it?

It should work under hotspot fine, although untested. You'd need to install it and try. Let us know if any issues.

**Comment by Fourdee** [comment]
I'll mark this as closed, please reopen if required.
