### ISSUE TITLE
HDD Spindown

### ISSUE THREAD

**Issue by bokiroki** [MichaIng/DietPi#1702]
Hi, i read that dietpi put external hdd to sleep after 10 minutes.. but my hdd spindown after 30 minutes, i checked several times..
This is my hdd
https://www.wdc.com/products/portable-storage/wd-elements-portable.html#WDBUZG0010BBK-NESN
also i entered this command to see spindown status 
hdparm -C /dev/sda1
and output is strange.. what this mean?
/dev/sda1:
SG_IO: bad/missing sense data, sb[]:  f0 00 01 00 50 40 ff 0a 00 00 00 00 00 1d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 drive state is:  unknown

**Comment by Fourdee** [comment]
@bokiroki 

```hdparm``` and USB drives/docks is hit and miss, it relies on the USB converter providing compatible low level data.

The USB converter may also have its own custom firmware based spin down system.

In short, it would appear incompatible with ```hdparm``` at the current version.

**Comment by bokiroki** [comment]
thanks
@MichaIng @Fourdee one more question.. is there a way to limit program from using all cpu power.. so i tried to play a movie trough plex, and i got error message, and raspberry pi become unresponsive... i can't enter ssh and plex web.. yellow led light is turned on.. i think that that movie file i got error is transcoding..but i can't to anything now to stop it..only option is to turn the power off..

**Comment by Fourdee** [comment]
@bokiroki 

> i think that that movie file i got error is transcoding.

We highly recommend disabling transcoding on the RPi device and PLEX interface (under settings). CPU transcoding under performs.

Usually we'd mention ```dietpi-process_tool``` to lower the priority of PLEX processes, however, PLEX spawns a new transcoding process on the fly, which we cant background check for. However, there should be some settings in the PLEX web interface to set a lower transcode priority.
