### ISSUE TITLE
dietpi.txt format differs between machine types?

### ISSUE THREAD

**Issue by 0xmichalis** [MichaIng/DietPi#1706]
I did a dietpi installation on a raspberry pi almost half a year ago and today when I came back to it and wanted to do an odroid c2 installation I realized that the format of the dietpi.txt file I had stored in git was totally different from what I found inside the image. Was there a recent update of the format or does it differ between machine types?

For reference, a sample of the raspberrypi diet.txt I had stored in git:
```shell
#If both Ethernet and Wifi are enabled, Wifi will take priority and Ethernet will be disabled.
#   1=enabled
Ethernet_Enabled=1
Wifi_Enabled=0

#Enter your Static Network details below, if applicable.
Use_Static=0
Static_IP=192.168.0.100
Static_Mask=255.255.255.0
Static_Gateway=192.168.0.1
Static_DNS=8.8.8.8
```
and a sample of the dietpi.txt I found inside the odroid c2 image:
```shell
#	If both Ethernet and Wifi are enabled, Wifi will take priority and Ethernet will be disabled.
#		1=enabled
AUTO_SETUP_NET_ETHERNET_ENABLED=1
AUTO_SETUP_NET_WIFI_ENABLED=0

#	Enter your Wifi details below, if applicable (Case Sensitive).
AUTO_SETUP_NET_WIFI_SSID=MySuperDooperWiFi
AUTO_SETUP_NET_WIFI_KEY=0123456789
#	available | WPA-PSK / NONE | WEP=No longer supported
AUTO_SETUP_NET_WIFI_KEYMGR=WPA-PSK

#	Enter your Static Network details below, if applicable.
AUTO_SETUP_NET_USESTATIC=0
AUTO_SETUP_NET_STATIC_IP=192.168.0.100
AUTO_SETUP_NET_STATIC_MASK=255.255.255.0
AUTO_SETUP_NET_STATIC_GATEWAY=192.168.0.1
AUTO_SETUP_NET_STATIC_DNS=8.8.8.8
```

**Comment by k-plan** [comment]
@kargakis 

> Was there a recent update of the format ...

Yes, by DietPi v6.x => http://dietpi.com/phpbb/viewtopic.php?f=11&t=2739

> ... or does it differ between machine types?

No.

**Comment by 0xmichalis** [comment]
@k-plan thanks for the link
