### ISSUE TITLE
AmiBerry | Update to 2.19

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1707]
https://github.com/midwan/amiberry/releases/tag/v2.19

@midwan

We'll get this added to DietPi v6.8.

**Comment by k-plan** [comment]
BTW: 
Perhaps you can as well have a look into this: 
[Amiberry input "leaks" to the console (SDL2 bug?)](http://dietpi.com/phpbb/viewtopic.php?f=11&t=3049)

**Comment by Fourdee** [comment]
Binaries/code updated, just need to test + replicate https://github.com/Fourdee/DietPi/issues/1707#issuecomment-381403586

**Comment by Fourdee** [comment]
> https://github.com/midwan/amiberry/issues/304#issuecomment-382222815

**Comment by Fourdee** [comment]
🈯️ http://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Stretch_AmiBerry.7z Updated to include support for RPi 3B+:
https://github.com/midwan/amiberry/issues/304#issuecomment-382222815

**Comment by Fourdee** [comment]
Confirmed SDL2 terminal leak.
- confirmed FAST/STANDARD boot quit breaks keyboard input,  term switch required.
- SDL2 version is 2.0.7, should have the reported fix for terminal leak
- ? https://discourse.libsdl.org/t/workaround-rpi2-keystrokes-leaking-into-x11-terminal/21750
- ? https://github.com/inoremap/shut-term-keys
- 🈯️ Unable to replicate illegal instruction on 2.18

**Comment by Fourdee** [comment]
🈵 Has no effect:
```
G_AGI build-essential
wget https://github.com/inoremap/shut-term-keys/archive/master.zip 
unzip master.zip
cd shut-term-keys-master
make
```

---

Issue appears limited to service, running ./amiberry is fine.
```StandardInput=tty``` hangs ```(dispmanx)```
```TTYPath=/dev/tty0``` hangs ```(dispmanx)```
```TTYPath=/dev/tty1``` nothing rendered.

**Comment by Fourdee** [comment]
Resolved standard boot SDL2 keyboard link.
Fast boot is still affected, unable to resolve currently, will mark it as a known issue.
