### ISSUE TITLE
Mopidy.conf exists twice

### ISSUE THREAD

**Issue by Ritterbrater** [MichaIng/DietPi#1709]
## Creating a bug report/issue:
mopidy.conf exists twice:
/etc/mopidy/mopidy.conf
/root/.conf/mopidy/mopidy.conf

Is this correct? I would expect that only one of them is required.

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? 6.6
- SBC Device (EG: RPi 3)? RPi 3
- Power supply used (EG: 5v 1A RAVpower)? RPi 3 Orig
- SD card used (EG: Sandisk ultra)? Samsung something

#### Additional Information (if applicable):
- Software title? Mopidy 
- Can this issue be replicated on a fresh installation of DietPi? - Installation quite fresh

edit: sorry, false alert. Might be regular for mopidy: https://docs.mopidy.com/en/latest/config/#confval-core/config_dir
Can be closed. Maybe asking google the next time first.

**Comment by Fourdee** [comment]
@Ritterbrater 

> Might be regular for mopidy: https://docs.mopidy.com/en/latest/config/#confval-core/config_dir

Yep, mopidy can use both configs, so to cover all bases, we duplicate our config to both locations.
If you do edit one config, make sure to copy to the other location aswell.

I'll mark this as closed, please reopen if required.
