### ISSUE TITLE
Not able to update to 6.7

### ISSUE THREAD

**Issue by magnusoverli** [MichaIng/DietPi#1710]
#### Required Information:
- DietPi Version | v6.6
- SBC Device     | RPi 3 Model B (armv7l) (index=3)
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Error Handler  | G_ERROR_HANDLER

#### Additional Information (if applicable):
- Software title | DietPi-Update

#### Additional logs:
```
Log file contents:
Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Ign:2 https://archive.raspberrypi.org/debian stretch InRelease
Get:3 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages [11.7 MB]
Get:4 https://archive.raspberrypi.org/debian stretch Release [24.8 kB]
Ign:5 https://archive.raspberrypi.org/debian stretch Release.gpg
Reading package lists...
E: The repository 'https://archive.raspberrypi.org/debian stretch Release' is no longer signed.
```

**Comment by MichaIng** [comment]
@magnusoverli 
Thanks for your report. Just updated my RPi as well an had not issues with exactly the same repository. Perhaps a temporary issue?

Otherwise could you try to clear your APT cache and manually run apt update: `apt clean && apt update`
Possibly even:
```
apt clean
mv /var/lib/apt/lists /tmp
mkdir -p /var/lib/apt/lists/partial
apt update
```

**Comment by Fourdee** [comment]
Confirmed working on RPi for me aswell, think @MichaIng is correct with it being  temporary hosting issue.

However, @magnusoverli please let us know if the above solution resolves.

**Comment by Fourdee** [comment]
Interesting, seems Debian repo having some issues aswell with some of our users:
https://community.roonlabs.com/t/dietpi-roon-server-with-additional-hdd-ssd/41440/4?u=dan_knight

**Comment by magnusoverli** [comment]
Hi! I was able to update this morning. Did a reboot and diet dietpi-update without any errors.

**Comment by k-plan** [comment]
@magnusoverli 

Thanks for your response. 👍 

I'll mark this as closed, please reopen if required.
