### ISSUE TITLE
Odroid C2: Jackett doesn't work - mono issue.

### ISSUE THREAD

**Issue by pedrom34** [MichaIng/DietPi#1711]
#### Required Information:
- DietPi Version | 6.7
- SBC Device | Odroid C2
- Power supply used | 5v 2.5A
- SD card used | Sandisk ultra 32Gb
- Distro | Linux DietPi 3.14.79+ #1 SMP PREEMPT Sun Jul 23 00:04:44 CEST 2017 aarch64 GNU/Linux

#### Additional Information (if applicable):
- Jackett
- Can this issue be replicated on a fresh installation of DietPi? Yup

#### Expected behaviour:
Jackett should work.

#### Actual behaviour:
It doesn't. Error message:  
"Exception (Indexer): Ssl error 0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE at /build/mono-5.10.1.20/external/boringssl/crypto/ec/ec.c:835: An error occurred while sending the request"

#### Steps to reproduce:
Add an indexer, test it. Doesn't work.

#### Did you submit a ```dietpi-bugreport```?
No.

#### Extra details:
It's somehow related to mono, as explained here: https://github.com/Jackett/Jackett/issues/2173  
But I tried to downgrade mono and it doesn't work...
Can you help?

**Comment by Gabba35** [comment]
Also experiencing the same issue, pretty much exactly as above. No issues with Sonarr itself, just Jackett.

**Comment by Fourdee** [comment]
@pedrom34 

Thanks for the report 👍 

Unfortunately, there is not much we can offer as a fix/solution. As mentioned here (https://github.com/Fourdee/DietPi/issues/1322#issuecomment-379496545), we only provide the latest Mono binaries, as per its repo (http://download.mono-project.com/repo/debian/).

If Sonaar is functional, we can assume that Jackett will need to update their support for newer Mono versions.
I envy the developers who work with Mono, no doubt they spend most of their time fixing Mono bugs related to newer versions of the library.

I'll flag this as external bug.

**Comment by Fourdee** [comment]
Tests, index
- 🈯️ RPi 
- 🈴 Deb Jessie (c2)
- 🈯️ Deb Stretch (n1)

Limited to Jessie Mono Repo.

@pedrom34 
Please use our C2 Stretch image. Jackett should work fine: http://dietpi.com/downloads/images/DietPi_OdroidC2-ARMv8-Stretch.7z (ref: https://github.com/Fourdee/DietPi/issues/1552#issue-299707234)

**Comment by Fourdee** [comment]
I'll mark this as closed with C2 Stretch image offering a fix: https://github.com/Fourdee/DietPi/issues/1711#issuecomment-382612977

Please reopen if required.

**Comment by pedrom34** [comment]
Not trying to reopen, but I have some questions. I created a subject [here](http://dietpi.com/phpbb/viewtopic.php?f=9&t=3083).
