### ISSUE TITLE
Minidlna without alsa

### ISSUE THREAD

**Issue by bokiroki** [MichaIng/DietPi#1712]
My dietpi is headless, i installed minidlna trough dietpi-software and alsa soundcard installed with it.. do i need it for minidlna, how to install only minidlna without alsa software? raspberry pi 3
Thanks

**Comment by Fourdee** [comment]
@bokiroki 

Thanks for the report and good spot 👍 

I believe you are spot on, ALSA is not required for this software title, we'll verify and remove this pre-req for v6.8.

You can remove ALSA in ```dietpi-software``` > uninstall > ALSA

**Comment by Fourdee** [comment]
Verified, ALSA not required: https://packages.debian.org/stretch/minidlna

Resolved for v6.8.
