### ISSUE TITLE
CPU governor setting defaults back to performance after reboot (Allo Sparky)

### ISSUE THREAD

**Issue by renebouwmeester** [MichaIng/DietPi#1720]
#### Required Information:
- DietPi Version 6.7
- SBC Device Allo Sparky
- Power supply used SBooster 5V/3A
- SD card used (EG: Sandisk ultra)? Sandisk
- Distro: Stretch

#### Additional Information (if applicable):
- Software title? Setting governor via dietpi-config > performance options
- Can this issue be replicated on a fresh installation of DietPi? yes

#### Expected behaviour:
When set to (f.e.) ondemand, it should stick to ondemand after reboot

#### Actual behaviour
Defaults back to perfomance

#### Steps to reproduce:
Change governor via dietpi-config and reboot

#### Additional info:
Changing governor and rebooting on RasPI 3B+ works fine.

**Comment by MichaIng** [comment]
@renebouwmeester 
Thanks for the report. I was just remembering something I saw by chance yesterday, found it: https://github.com/Fourdee/DietPi/blob/testing/PREP_SYSTEM_FOR_DIETPI.sh#L1234
We set CPU governor to "performance" on Sparky for stability reasons.

But this is just during preparation for our images as default value. I didn't find anything in the code, that shows a different handling of Sparky than other devices afterwards. Also the existence of the needed `/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor` is checked, before governor setting is shown within dietpi-config.

Could you adjust the governor and then check before and after reboot: `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`?
Perhaps kernel messages give some hints about e.g. unsupported governor or something: `dmesg`?

**Comment by renebouwmeester** [comment]
Weird. It's fine now. Rebooted twice, once removing all power (it's dual powered with a USBridge attached). Setting sticks. Both cpu and cat report ondemand.

Ondemand is stable here (running slightly less hot), but the Sparky/USBridge is only running as audio bridge.

Anyway – false flag, it appears. I'll keep an eye on it and report back if it happens again. Thanks for your attention and keep up the great work with DietPi!

**Comment by Fourdee** [comment]
> We set CPU governor to "performance" on Sparky for stability reasons.

@renebouwmeester 

Yep, this is a recommendation directly from Allo. Although, i've personally never had any issues with ```ondemand``` myself, so should be fine to use it.

**Comment by MichaIng** [comment]
@renebouwmeester
Okay great, keep keep is informed if this happens again. I will mark as closed here.
