### ISSUE TITLE
Add DietPi-Drive Manager to dietpi list of preinstalled applications

### ISSUE THREAD

**Issue by msdos** [MichaIng/DietPi#1721]
In a nutshell: put a reference to http://dietpi.com/phpbb/viewtopic.php?f=8&t=673 in http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5.

EDIT: Well, autostart as well... https://github.com/Fourdee/DietPi/issues/916 should I change this issue to "add all dietpi-* namespace apps"?

**Comment by Fourdee** [comment]
@msdos 

Many thanks for the request, good spot 👍 

Added:
dietpi-drive_manager
dietpi-autostart

I'll check to see if we missed any, then add those in aswell.

**Comment by Fourdee** [comment]
```dietpi-justboom``` added. Believe we got all the critical ones. I'll mark this as closed.
