### ISSUE TITLE
[Question] PREP-Script on OrangePi PC Plus (Kernel 4.14.35)

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#1725]
Hi @Fourdee,
i've managed to compile the 4.14.35 kernel for the OPiPC+ SBC on a Debian basic installation. Now, whenever i try to use the PREP-Script, it downgrades the kernel to 4.14.18 for this board.

When i freeze (hold) the kernel, so the PREP script can't downgrade it, the device afterwards wouldn't boot into system, as it stays on u-boot with "Loading kernel...."

If i'm not converting it into DietPi, there is no problem booting it. Are you aware of a workaround for this?

Thx in advance and a nice weekend. :grin:

**Comment by ghost** [comment]
Okay, got is solved!

**Comment by MichaIng** [comment]
@SuBLiNeR 
Yeah indeed this should be the case, if an APT kernel package is still installed on the device: https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L768-L786
- `DietPi-PREP` checks for installed APT kernel packages and guarantees that they stay installed, as all other packages will be autoremoved later on.
- Kernel packages, which are (still) available within current APT repositories, will be marked by simply rerun their installation. If now the package is set on `hold`, I guess the process will be cancelled before the package is marked as `manual`. Thus the package will be later autoremoved on some devices. Debian x86 by default blocks autoremoving of any `linux-image-*` package, but that might be not true for OPi.
- I guess now the purging of the kernel package also purges files that are actually part of your manual compiled kernel and breaks it that way.

- [ ] To resolve it, I would try to purge the pre-installed kernel package manually, then install you own, then run DietPi-PREP.
- [ ] Other solution should be, if you assure, that the installed APT kernel package is the most current version (of your target distro APT repository) before marking it on hold and install your own. In this case apt installation will mark the package as intended, but no package upgrade will overwrite your custom kernel:
```
root@VM-Stretch:~# apt-mark hold bzip2
bzip2 set on hold.
root@VM-Stretch:~# apt-mark auto bzip2
bzip2 set to automatically installed.
root@VM-Stretch:~# apt install bzip2
Reading package lists... Done
Building dependency tree
Reading state information... Done
bzip2 is already the newest version (1.0.6-8.1).
bzip2 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@VM-Stretch:~# apt-mark showhold
bzip2
```
**€: Checked a bid how active hold status is handled:**
```
root@VM-Stretch:~# wget http://ftp.de.debian.org/debian/pool/main/b/bc/dc_1.06.95-9_amd64.deb
...
2018-04-21 18:30:13 (865 KB/s) - ‘dc_1.06.95-9_amd64.deb’ saved [66578/66578]
root@VM-Stretch:~# dpkg -i dc_1.06.95-9_amd64.deb
...
Setting up dc (1.06.95-9) ...
root@VM-Stretch:~# apt-mark auto dc
dc set to automatically installed.
root@VM-Stretch:~# apt-mark hold dc
dc set on hold.
root@VM-Stretch:~# apt-mark showhold dc
dc
root@VM-Stretch:~# apt full-upgrade
...
The following packages have been kept back:
  dc
...
root@VM-Stretch:~# G_AGI dc
[  OK  ] APT installation for: dc, please wait...
(Reading database ... 20185 files and directories currently installed.)
Preparing to unpack .../dc_1.06.95-9+b3_amd64.deb ...
Unpacking dc (1.06.95-9+b3) over (1.06.95-9) ...
Setting up dc (1.06.95-9+b3) ...

[  OK  ] G_AGI: dc
root@VM-Stretch:~# apt-mark showhold


```
**- So okay, G_AGI ignores hold state. In this case I am not sure why this lead to boot issues in your case 🤔** 

What we should do to solve the issue:
- [ ] `apt-mark manual $AUTO_DETECT_KERN_PKG` all found kernel packages. It does not make any sense to separate those available on repo and the others, if we anyway just process already installed ones. The result is the same, besides in those cases where kernel packages are marked on hold.
_____________________
**€: Ah lol had answer opened for a while and got distracted, how did you do it? 😆**

**Comment by ghost** [comment]
@MichaIng Hi there, i solved it whilst setting it via apt-mark hold like you already answered. But on mine side, i also uncomment the armbian-repo in the sources list, and voila, the kernel persist whilst running the PREP script.
So at least for all the SBCs out there and self-built armbian base image, you have to freeze kernel to prevent update or downgrade of it. Also uncomment armbian repo on your sources list and you're able to get the latest available kernel for the SBC on DietPi.

I think, this something ppl should know.... :)
