### ISSUE TITLE
dietpi-software install 152 (avahi-daemon) | crashes dietpi

### ISSUE THREAD

**Issue by unclehowell** [MichaIng/DietPi#1729]
## Creating a bug report/issue:

when you install software ID 152 with dietpi.txt it works fine.
But try to run the install using a command on a running system, later down the line (dietpi-software install) and it freezes mid install.

DietPi Version | 6.7 
RPi 3
5v 2a PSU
cheap & nasty 16GB SD Card 

I'm working on building something upon dietpi called WaveOS, so should have more feedback for you guys as the project develops

**Comment by Fourdee** [comment]
@unclehowell 

> when you install software ID 152 with dietpi.txt it works fine.
But try to run the install using a command on a running system, later down the line (dietpi-software install) and it freezes mid install.

Thanks for the report 👍 

I'll run a install test to see if we can replicate.

**Comment by Fourdee** [comment]
@unclehowell 

Appears to be working fine in local testing, unable to replicate.

If its a hard lock, could be hardware related (SD/PSU instability). Do you receive any error messages when it fails?

```
root@DietPi:~# dietpi-software install 152
.........
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Optimize and configure software

[ INFO ] DietPi-Software | Applying DietPi optimizations and configurations for RPi 3 Model B (armv7l), please wait...

[ SUB1 ] DietPi-Services > dietpi_controlled
[  OK  ] DietPi-Services | dietpi_controlled : avahi-daemon
[  OK  ] DietPi-Services | dietpi_controlled : cron
[  OK  ] DietPi-Software | DietPi-Software installation completed.
[ SUB1 ] DietPi-Services > start
[  OK  ] DietPi-Services | start : avahi-daemon
[  OK  ] DietPi-Services | start : cron
[ SUB2 ] DietPi-Process_tool > Apply
[  OK  ] DietPi-Process_tool | Completed
```

**Comment by Fourdee** [comment]
No response, making as closed.
Please reopen if required.

**Comment by unclehowell** [comment]
Thanks. I just install it via dietpi.txt now. That works. No error message when it freezes, it just does. 
I have a few other raspberry pi's kicking around, 2 & 3. I'll experiment and keep you posted. I'm trying to build a solution ontop of DietPi. I can't thank you enough for your work, it saves a lot of messing around. Great job
