### ISSUE TITLE
Dietpi update Failed

### ISSUE THREAD

**Issue by zzlinwq** [MichaIng/DietPi#1732]
## Creating a bug report/issue:
DietPi 6.7 
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing Xserver: linux display system

[  OK  ] DietPi-Software | APT installation for: xcompmgr xterm xinit xauth xserver-xorg dbus-x11 xfonts-base x11-xserver-utils x11-common x11-utils libgl1-mesa-dri libgles2-mesa mesa-utils, please wait...
E: Failed to fetch http://mirror.os6.org/raspbian/raspbian/pool/main/m/mtdev/libmtdev1_1.1.5-1_armhf.deb  Could not connect to mirror.os6.org:80 (198.255.68.110), connection timed out
E: Failed to fetch http://mirror.os6.org/raspbian/raspbian/pool/main/libx/libxau/libxau6_1.0.8-1_armhf.deb  Unable to connect to mirror.os6.org:http:
[FAILED] DietPi-Software | G_AGI: xcompmgr xterm xinit xauth xserver-xorg dbus-x11 xfonts-base x11-xserver-utils x11-common x11-utils libgl1-mesa-dri libgles2-mesa mesa-utils
[ INFO ] DietPi-Software | If problems persist, please report this to DietPi for investigation, including a screenshot of this error! (https://github.com/Fourdee/DietPi/issues).

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by MichaIng** [comment]
@zzlinwq 
Thanks for your report.
Just a quick check: I was able to download the .deb file. Possibly a temporary issue with the repo?

@Fourdee
Since we got several issues with repositories lately, perhaps we can skip script exit with G_AGX errors during dietpi-update, at least for the regular ones that are not related with a certain needed patch in patch_file?
This way at least the update would finish. If issue really persists during dietpi-software tasks, users can/should still report.

€: On the other hand this one occurred during dietpi-software installation...

**Comment by Fourdee** [comment]
@MichaIng 

> perhaps we can skip script exit with G_AGX errors during dietpi-update, at least for the regular ones that are not related with a certain needed patch in patch_file?

I'am not too keen on this, adds additional patch checks and may create more issues down the line, for the users installation if not consistent error handled.

Maybe we could add a while loop for all G_ERROR based commands, with a prompt after failure?:
Similar to the internet connection test prompt
- Retry
- Edit networking options (EG: change APT mirror)
- Exit

**Comment by MichaIng** [comment]
@Fourdee 
Jep, this is a great idea, same like we do for NTPD within dietpi-software: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L149

Retry of `G_AGUP` should include an apt clear like we do with the cleaner: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-cleaner#L579-L580
- Although options should be `-Rfv` to also include the partial folder 😉.

... but we should handle this within an own issue 😄.

**Comment by Fourdee** [comment]
Retry on failed DietPi G commands implemented in v6.9.
DietPi-Config option added in commit below.

**Comment by Fourdee** [comment]
No response from user, unable to replicate, will mark as completed.

Please reopen if required.

**Comment by StephanStS** [comment]
Possibly this issue has the same reason like 

- [#2834 DietPi-Software | Pi-hole: Ad list blocks codeload.github.com](https://github.com/MichaIng/DietPi/issues/2834)
- [#2307 DietPi-Update | Failed with PiHole as DNS Serever using some Filterlist](https://github.com/MichaIng/DietPi/issues/2307)

@zzlinwq: Could you check this? (-> unblock codeload.github.com in Pi-Hole)

**Comment by Joulinar** [comment]
@StephanStS 

The bug report is 2 years old :smiley:

**Comment by StephanStS** [comment]
@Joulinar: I was aware of this, possibly zzlinwq is interested what could have been the cause.  :-)
