### ISSUE TITLE
Can't find Docker in dietpi-software

### ISSUE THREAD

**Issue by lupa18** [MichaIng/DietPi#1736]
#### Required Information:
- DietPi Version | cat /DietPi/dietpi/.version
6
7

- SBC Device: Rock64
- Power supply used: 5v 3A
- SD card used: 32GB CLASS10 MICROSD CARD
- Distro: Linux DietPi 4.4.77-rockchip-ayufan-136

#### Additional Information (if applicable):
- Can this issue be replicated on a fresh installation of DietPi: yes

#### Expected behaviour:
I should see a Docker option in distpi-sofware since I'm on arm processor. 

#### Actual behaviour:
Option didn't appear

#### Steps to reproduce:
1. Run dietpi-software
2. Search on Software Optimized (and Adittional)

#### Did you submit a ```dietpi-bugreport```?
No

#### Extra details:
Nothing

thanks in advance !

**Comment by Fourdee** [comment]
@lupa18 

Thanks for the report 👍 

Confirmed, Docker install is disabled for ARMv8 devices. We'll find out why and report back.

**Comment by Fourdee** [comment]
notes:
```
aarch64-debian-jessie
aarch64-debian-stretch
aarch64-debian-buster
armv6l-raspbian-jessie
armv7l-raspbian-jessie
armv6l-raspbian-stretch
armv7l-raspbian-stretch
armv7l-debian-jessie
armv7l-debian-stretch
armv7l-debian-buster
```

**Comment by Fourdee** [comment]
Unsure why its disabled, test install on Odroid C2 was sucessful:
```
[  OK  ] DietPi-Services | docker       active (running) since Sun 2018-04-29 13:12:34 BST; 8min ago
```

🈯️ I've re-enabled ARMv8 Docker install for v6.8.

@lupa18 

Run the following command to enable the install now:
```
wget https://raw.githubusercontent.com/Fourdee/DietPi/9c01a523bb6c9374ae5069d09d734ab21022646f/dietpi/dietpi-software -O /DietPi/dietpi/dietpi-software
```

Completed for v6.8.
