### ISSUE TITLE
Image | NanoPi K1 Plus

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1744]
Thanks to FriendlyARM for sending us a dev sample 👍

**Comment by ghost** [comment]
Wish i could get in touch of it as well! ;) Would be a pleasure! 

It is a very interesting board as it seems. It may take a while until we could get in Germany to test...

**Comment by Fourdee** [comment]
https://dietpi.com/downloads/images/DietPi_NanoPiK1Plus-ARMv8-Stretch.7z

**Comment by Fourdee** [comment]
To Do:
- Soundcard selection
-- We'll use our detection method for this device:
![image](https://user-images.githubusercontent.com/7077026/39633724-abf7482a-4fb0-11e8-8c4e-ffdaff08dbb8.png)

- dietpi.com add

- Kernel reported CPU temps appear to be offset by -30'c. We could add a "rough workaround", however, any kernel updates/fixes would render this an issue. We'll leave it as is for now, known kernel issue.
![image](https://user-images.githubusercontent.com/7077026/39634313-629a30a0-4fb2-11e8-8747-c058960cf856.png)

**Comment by Fourdee** [comment]
https://twitter.com/DietPi_/status/992796789983141893

Completed.
