### ISSUE TITLE
Installing NodeJS possible?

### ISSUE THREAD

**Issue by jwillmer** [MichaIng/DietPi#1756]
I like to use a Raspberry Pi Zero W with DietPi as operation system for running a [Zigbee to MQTT bridge](https://github.com/Koenkk/zigbee2mqtt/wiki/Running-the-bridge). Therefore I need NodeJS. I could not find it in the list of supported software, does that mean this setup is not possible with DietPi?

**Comment by Fourdee** [comment]
@jwillmer 

Hi,

NodeJS is available for install in the ```Linux Software``` section:
![image](https://user-images.githubusercontent.com/7077026/39713378-7c835730-521e-11e8-816b-73b7257e4cf8.png)

It can also be quickly installed with:
```
dietpi-software install 9
```

ARMv6 is supported (RPi Zero)
