### ISSUE TITLE
DietPi-RAMdisk | Not saving to disk during shutdown (pending v6.9 testing + additional logging update)

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#1772]
Tested on: Raspberry 3, Dietpi 6.7

1) dietpi-config -> 4 Advanced Options - > i2c state -> switch from (disabled) to (enabled)
2) Save and exit -> No reboot
3) Enter dietpi-config again -> Check the settings -> i2c state correct (enabled)
4) Reboot the mache -> i2c state switched back to (disabled)

**Comment by MichaIng** [comment]
@WTFMaster
Thanks for your report. I just checked the code, where I couldn't find an issue so far. That pre reboot the correct choice is shown should be a prove that /DietPi/config.txt is adjusted correctly.

What I can think of now, is that on shutdown it is not synced to /boot/config.txt as expected.

Could you run `systemctl restart dietpi-ramdisk` and then `systemctl status dietpi-ramdisk` to check for errors? If non is shown reboot again and see if status survives then.

**Comment by Fourdee** [comment]
Fresh install test with RPi 3, unable to replicate, state is saved after reboot.

Further debugging required as per @MichaIng https://github.com/Fourdee/DietPi/issues/1772#issuecomment-388819730

**Comment by Gill-Bates** [comment]
@MichaIng 
After changing my settings, /DietPi/config.txt looks like this:

#-------i2c-------------
dtparam=i2c_arm=on
dtparam=i2c1=on
i2c_arm_baudrate=100000

After reboot RPI the file looks like this:

#-------i2c-------------
dtparam=i2c_arm=off
dtparam=i2c1=off
i2c_arm_baudrate=100000

It seems, during the reboot the changes are lost and not written to the filesystem. How can I solve this?

**Comment by Gill-Bates** [comment]
running `systemctl restart dietpi-ramdisk` and then `systemctl status dietpi-ramdisk` solved the issue.

The question is: why does not the dietpi-config tool execute this command before rebooting?

**Comment by Fourdee** [comment]
@WTFMaster 

> The question is: why does not the dietpi-config tool execute this command before rebooting?

The command is actually a service, which executes during shutdown phase. 
As we are unable to replicate this issue in local testing, we will need to debug with you.

However, before we can start, i need to add additional debugging to our script and log output. Leave it with me for now and i'll reply once its ready for testing.

**Comment by Fourdee** [comment]
Ok, full logging output added for v6.9 on all DietPi core boot services. If issues occur in the future we can collate with the logs after user runs ```dietpi-bugreport```
If the logs are clear of any errors, we can 99.9% confirm a hardware specific issue of the data not being saved correctly, outside of our control.
_NB: In the last 2 years of doing DietPi, i've never experienced the issue of RAMdisk failing to sync._

I'll mark this as closed, as it wont be until v6.9 that we can continue to debug this with the updated logging.

**Comment by Gill-Bates** [comment]
Here is my Bugreport:
`Reference CODE: ca8f7b98-88fd-4524-8ebc-2926ce337a2c-0  `
