### ISSUE TITLE
Makefile:527: recipe for target 'osutil' failed ,Makefile 3 recipe for target all failed

### ISSUE THREAD

**Issue by fayroozk** [MichaIng/DietPi#1773]
root@kali:~/Desktop/Archer_T2U_V1_150901/Driver# make
make -C UTIL/ osutil
make[1]: Entering directory '/root/Desktop/Archer_T2U_V1_150901/Driver/UTIL'
cp -f os/linux/Makefile.6.util /root/Desktop/Archer_T2U_V1_150901/Driver/UTIL/os/linux/Makefile
make -C /lib/modules/4.15.0-kali3-amd64/build SUBDIRS=/root/Desktop/Archer_T2U_V1_150901/Driver/UTIL/os/linux modules
make[2]: Entering directory '/root/Desktop/Archer_T2U_V1_150901/Driver/UTIL'
make[2]: *** /lib/modules/4.15.0-kali3-amd64/build: No such file or directory.  Stop.
make[2]: Leaving directory '/root/Desktop/Archer_T2U_V1_150901/Driver/UTIL'
Makefile:527: recipe for target 'osutil' failed
make[1]: *** [osutil] Error 2
make[1]: Leaving directory '/root/Desktop/Archer_T2U_V1_150901/Driver/UTIL'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Fourdee** [comment]
@fayroozk 

Appears the make/compile is targeting Kali:
```
/lib/modules/4.15.0-kali3-amd64/build: No such file or directory. Stop.
```

DietPi is Debian.
