### ISSUE TITLE
Add zerotier to software catalog

### ISSUE THREAD

**Issue by robotkid450** [MichaIng/DietPi#1783]
I was wondering if it would be possible to add zerotier ([www.zerotier.com](https://www.zerotier.com/)) to the DietPi software catalog.

**Comment by Fourdee** [comment]
@robotkid450 

Many thanks for the request 👍 

As our primary focus is ensuring stability with existing software titles we offer (and there is alot 😄), we mark all software requests as closed initially. 
If interest peaks from our user base for this software title, we'll reopen and investigate adding this to ```dietpi-software```.
