### ISSUE TITLE
request vmware esxi 6 iso

### ISSUE THREAD

**Issue by Ondjultomte** [MichaIng/DietPi#179]
Is it possible to get a iso that would install dietpi in esxi ? not just vmplayer

**Comment by blindpet** [comment]
You should be able to use the vmx file for esxi.

**Comment by Fourdee** [comment]
@Ondjultomte If you require the VM in a different format (eg: iso), you will need to convert it: 
http://stackoverflow.com/questions/26670337/how-can-i-convert-vmware-vmdk-file-to-iso-format-in-windows-host-machine

and

https://communities.vmware.com/thread/472934?start=0

Please reopen if required
