### ISSUE TITLE
DietPi-Software | TigerVNC+LXDE: Calling lxappearance crashes VNC virtual desktop

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1791]
> https://github.com/Fourdee/DietPi/issues/1558#issuecomment-390332722

**Comment by MichaIng** [comment]
Just verified this is still an issue on current Buster image with DietPi v6.26.0 (latest `dev` branch)...
Debugging planned for v6.27.

**Comment by MichaIng** [comment]
Not related to #1558, on Buster pcmanfm gets upgraded at latest with next APT upgrade, both issues are present independent of each others...

**Comment by MichaIng** [comment]
Okay, works well on local access. I always tested via VNC before.
Confirmed being an issue on VNC virtual desktop only, testing both in parallel.
Tested shared VNC desktop as well, working fine.

TigerVNC vs RealVNC can be tested, as well as the above on non-RPi.

**Comment by MichaIng** [comment]
TigerVNC-only issue, works well on RealVNC virtual desktop.

**Comment by MichaIng** [comment]
Report on RPi repo: https://github.com/RPi-Distro/repo/issues/202
However, I'll close the issue here and track all LXDE-on-RPi issues now here instead: #1558

**Comment by MichaIng** [comment]
Solution: `apt install dbus-user-session` (https://github.com/MichaIng/DietPi/issues/1558#issuecomment-701547904)
