### ISSUE TITLE
How do you do it? The dietpi image file

### ISSUE THREAD

**Issue by unclehowell** [MichaIng/DietPi#1793]
I want to have your image file, which is nice and small and bug free, but with my custom dietpi.txt file in it.
What's the best way to go about this? 
Because burning to an SD, switching the file, ripping it back using win32 is just messy.
Can I pay you guys to do?

**Comment by Fourdee** [comment]
@unclehowell 

Mount the image as a loopback device then mount the boot partition. You can then edit the dietpi.txt file to your needs.

You'll need a linux/DietPi install:
```
	modprobe loop
	losetup -f
	losetup /dev/loop2 /path/to/my/DietPi-image.img
	partprobe /dev/loop2

	mkdir -p /mnt/loop2p1
	mount /dev/loop2p1 /mnt/loop2p1
        nano /mnt/loop2p1/dietpi.txt

#Once finished, unmount the drive
sync
umount /mnt/loop2p1
losetup -d /dev/loop2
```

**Comment by unclehowell** [comment]
Champions, thanks

**Comment by Fourdee** [comment]
I'll mark this as answered, please reopen if required.
