### ISSUE TITLE
/dev/sda1 can't read superblock

### ISSUE THREAD

**Issue by bokiroki** [MichaIng/DietPi#1795]
We had power outage, and after power came again, i have problem with external hdd, it said it is not mounted, i can't access it.. when i try to mount it, i get message "/dev/sda1 can't read superblock"
Is there a fix to this solution?

**Comment by MichaIng** [comment]
Try to run a file system check. We added this to `dietpi-drive_manager`.
Open drive manager enter edit of the affected device and there you should see the option to run the check.

Agree to do automated fix, be aware that for some file system types (which one is it?) the repair steps might make the damage worse and lead to further data loss. If the data is extremely important and you don't have a backup, then directly giving the drive to some (expensive) data restorage service might rescue more.

After repairing, if it then is able to mount, on ext4 fs have a look into the `lost+found` folder where files (inodes) are placed that lost their hardlink to the file system.

**Comment by bokiroki** [comment]
i tried with file system check and everything went fine...i can mount hdd now.. thanks
nothing is lost on drive
