### ISSUE TITLE
Start failed

### ISSUE THREAD

**Issue by valerivp** [MichaIng/DietPi#1803]
Orange Pi i96 on Debian after instalation DietPi (with out errors), and reboot wrote:

Please login to continue

But not show command promt

#### Required Information:
v6.7
Orange Pi i96 Cortex A5

#### Expected behaviour:
promt for login

#### Actual behaviour:
nothing

#### Steps to reproduce:
install DietPi on board

#### Did you submit a ```dietpi-bugreport```?
dont know

#### Extra details:
![2018-05-28_1642](https://user-images.githubusercontent.com/28062383/40617695-c9c155d6-6297-11e8-9db2-ed387b99a7c6.png)

**Comment by Fourdee** [comment]
@valerivp 

At the point where it says "Please login to continue", you can login at this point. Simply type ```root```, enter then the password prompt will appear.

**Comment by valerivp** [comment]
@Fourdee 
it's not work
![2018-05-29_0713](https://user-images.githubusercontent.com/28062383/40637811-0dcabb1e-6310-11e8-8880-2a779228912d.png)

**Comment by Fourdee** [comment]
@valerivp 

Ah I see. Serial console is disabled by default on DietPi, after 1st run setup is completed.

You'll need to enable serial console in ```/boot/dietpi.txt``` ( and ```/DietPi/dietpi.txt```, to cover if systemD runs stop on a service that isn't in started state, unsure) before 1st run. 
Edit the files after PREP has finished, and, before you reboot the system.
```
CONFIG_SERIAL_CONSOLE_ENABLE=1
```

**Comment by Fourdee** [comment]
Solution: https://github.com/Fourdee/DietPi/issues/1803#issuecomment-393249909

Marking as closed. Please reopen if required.

**Comment by msdos** [comment]
@Fourdee I just had the problem you described in https://github.com/Fourdee/DietPi/issues/1803#issuecomment-393249909. Should this be added as a comment somehow in https://github.com/Fourdee/DietPi/blob/eb1be60e89ddc651d80345946c1b7f0585494bcc/dietpi.txt#L178?
