### ISSUE TITLE
DietPi-Autostart | Install LightDM as pre-req automatically?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1805]
When testing a bid around with login scripts on different shells and terminals, I recognized that just an error is thrown, when choosing lightdm desktop login prompt.

Wouldn't it be nice, if this is then installed automatically, or prompt a G_WHIP to ask user? We could also do this when other autostart options with required software or packages is chosen.

**Comment by Fourdee** [comment]
Completed. https://github.com/Fourdee/DietPi/commit/fd855d654bded34994b4af3d2df9d98013cd6c77

**Comment by Hoffnungsschimmer** [comment]
I use (as always) AutoStart Option 2 (automatic login). I think that's the LightDM.
