### ISSUE TITLE
Can't use Pihole and Baikal on the same dietpi-system

### ISSUE THREAD

**Issue by Krawei** [MichaIng/DietPi#1811]
#### Required Information:
- DietPi Version 6.8
- SBC Device: RPi 3
- Power supply used: 5v 1A Power supply
- SD card used: Sandisk ultra
- Distro: Stretch

#### Additional Information (if applicable):
- PiHole
- Baikal

#### Expected behaviour:
http://<IP of RPi>/admin => Pihole Web GUI
http://<IP of Rpi>/baikal/admin => Baikal Web GUI

#### Actual behaviour:
HTTP-Request to the Baikal-URL mentioned above => Delivery of the Pihole standard blocking page

#### Steps to reproduce:
Install DietPi
Install Pihole
Install Baikal
Try to access the baikal page

#### Did you submit a ```dietpi-bugreport```?
no

#### Extra details:
When requesting the Baikal-URL, I see the Pihole "standard blocking page". It seems that there's kinda "redirect everything except Pihole-Web-GUI-Request to Pihole blocking page". But there aren't any redirect orders in the lighttp.conf.

Weird.

**Comment by MichaIng** [comment]
@Krawei
Thanks for your report. I will try to reproduce.
Is the blocking page colorized or just a white pain text page?

We will get this fixed in case for v6.9 soon.

**Comment by Krawei** [comment]
@MichaIng : It is the colorized one. I'll try to upload a screenshot later.

**Comment by Fourdee** [comment]
Testing notes:
- Unable to replicate on ARMv8 (cant see it being any different for ARMv7), both pages load fine.

@Krawei 

Did you install PiHole and Baikal through ```dietpi-software```?

**Comment by MichaIng** [comment]
@Krawei @Fourdee 
I couldn't replicate as well on x86 VM. First installed pi-hole, baikal afterwards.

Could you also show result of `cat /etc/lighttpd/lighttpd.conf`? It seems like backup and recover of DietPi's lighttpd.conf didn't went well and the pi-hole edited version is in place, which blocks all other web applications: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L4476-L4499
So yeah, it's important you install pi-hole via dietpi-software.

**Comment by Krawei** [comment]
@Fourdee : I've installed pihole and baikal via dietpie-software and following the instructions from your site: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=50#p1502   

When I'm trying to access the baikal admin page, my dietpi serves this site:

![grafik](https://user-images.githubusercontent.com/25485657/40937243-43316bee-683e-11e8-9e5c-a027c1b309bc.png) (this site also returns when I'm trying to access http://192.168.2.2/phpinfo.php).

My lighttpd.conf:

https://privatebin.net/?e4a8033af3854dcc#lFtsZOh3QSp25uFqWds+vLDxxnjy94UFlhKzkw7Q1D4=

Hope you find my issue :).

**Comment by Fourdee** [comment]
@Krawei 

Yep, PiHole has overwritten the lighttpd config file. We have code in the ```dietpi-software``` install part which prevents this, so unsure as to why this occurred for you (confirmed working with fresh install just now).

The next PiHole release will allow us to avoid this issue.

#### In the mean time, to resolve, run the following commands:
```
dietpi-services stop
wget https://dietpi.com/downloads/testing/lighttpd.conf -O /etc/lighttpd/lighttpd.conf
dietpi-services start
```

**Comment by Fourdee** [comment]
Marking as closed in favor of https://github.com/Fourdee/DietPi/issues/1696.

Please reopen if required.
