### ISSUE TITLE
DietPi-Software | Bitcoin/Litecoin client node

### ISSUE THREAD

**Issue by giulio92** [MichaIng/DietPi#1813]
It would be really great to have [Bitcoin](https://github.com/bitcoin/bitcoin/) and/or [Litecoin](https://github.com/litecoin-project/litecoin) client node support in DietPi

**Comment by MichaIng** [comment]
Most likely we will implement the Bitcoin node first according to user counts.
Install instructions: https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

Added to FeatHub, feel free to vote: https://feathub.com/MichaIng/DietPi/+6

**Comment by MichaIng** [comment]
It has even been voted down. Obviously not much interest. Will mark this as closed for general cleanup, however feel free to collect further votes and when it comes closer to the top we will reopen. The FeatHub request will stay.
