### ISSUE TITLE
Odroid C2 | Kodi stuttering

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1814]
https://dietpi.com/phpbb/viewtopic.php?f=11&t=3841&p=12831#p12826

**Comment by Fourdee** [comment]
Fresh install Odroid C2 Stretch + Kodi and default options, samba server source:
- 🈯️ 720p 60Hz is fine
- 🈺 1080p 60Hz slight stuttering x264
- 🈴 1080p 24Hz, excessive vsync tearing.
- Kodi interface also seems excessively sluggish.
- Only runs under ```xinit```

Interesting, Kodi 16 under Jessie was fine from what I remember.

@oparoz 

Until a solution is found, a workaround is to try the Jessie image with Kodi 16:
https://dietpi.com/downloads/images/DietPi_OdroidC2-ARMv8-Jessie.7z

**Comment by MichaIng** [comment]
@Fourdee 
Hmm, wasn't there something with GPU support not yet fully implemented with Odroid Stretch? Okay seems resolved, but I remember reading that the solution was a bid hackish, maybe not providing same performance. Need again a closer look into the odroid forum: https://github.com/Fourdee/DietPi/issues/1552

**Comment by Gabba35** [comment]
Having the same problem. Xorg uses >100% cpu and the temp has been hitting the +80C routinely. Sometimes when idle. Had a similar problem with Sonarr, Jackett and Mono.

**Comment by MichaIng** [comment]
@Fourdee 
Just made some review about Odroid GPU acceleration:
- It's still the same issue with Kodi and C2: https://forum.odroid.com/viewtopic.php?f=138&t=27449&start=150#p232259
- On XU3/4 it does not seem to be an issue. Not listed on OT or latest posts: https://forum.odroid.com/viewtopic.php?f=96&t=30552&start=150
Although could be tested, to be sure.

Hope there is still investigation done by times, as this is the last reason we keep Jessie support, at least besides other individual user reasons 😞.

**Comment by MichaIng** [comment]
@Fourdee
Finally Stretch C2 Kodi issue seems fixed by Meveric: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5282&p=15568&sid=16232ea848e9194e0db86b2fcdb96e5c#p15545

Perhaps we need to adjust our install script accordingly?

**Comment by Fourdee** [comment]
@MichaIng 

> Update should be fine, it's part of the kodi-odroid package itself

No change needed. Updated APT package resolves issue ^^.

https://forum.odroid.com/viewtopic.php?f=138&t=27449&p=239490#p239490

**Comment by MichaIng** [comment]
@Fourdee 
Perfect. If we now can resolve the XU4 Stretch Xorg issue (https://github.com/Fourdee/DietPi/issues/2130), I would say we can take off Jessie images, or move them to some "legacy" subdir.

From my point of view, we can also disable the Jessie option within DietPi-PREP (still allow dist upgrade from base Jessie to DietPi Stretch) and encourage existing Jessie users to switch to Stretch.

When all Jessie image/creation sources are off, we can watch install counts on survey page and by times drop support completely. Would allow massive code simplifications.

**Comment by MichaIng** [comment]
@Fourdee
I believe we can close this, or do you want to run further tests?

**Comment by Fourdee** [comment]
@MichaIng 

> I believe we can close this, or do you want to run further tests?

Yep its resolved, verified with setting up my dads Odroid C2 + Kodi system 👍
