### ISSUE TITLE
从Debian系统安装DIEPT不能成功

### ISSUE THREAD

**Issue by zzlinwq** [MichaIng/DietPi#1815]
## Creating a bug report/issue:
Please excuse my poor English
机器是amlogic S905设备，
Linux amlogic 3.14.29 #137 SMP PREEMPT Thu May 17 09:26:05 MSK 2018 aarch64 GNU/Linux
Welcome to ARMBIAN 5.44 user-built Debian GNU/Linux 9 (stretch) 3.14.29 
是按下面帖子命令操作的
https://github.com/Fourdee/DietPi/issues/1285#issue-280771944
命令如下：
export GIT_BRANCH='master' 
#export GIT_BRANCH='testing' #DEV only

wget https://raw.githubusercontent.com/Fourdee/DietPi/$GIT_BRANCH/PREP_SYSTEM_FOR_DIETPI.sh -O PREP_SYSTEM_FOR_DIETPI.sh
chmod +x PREP_SYSTEM_FOR_DIETPI.sh
sudo GIT_BRANCH=$GIT_BRANCH ./PREP_SYSTEM_FOR_DIETPI.sh
但是结果不能成功：
[FAILED] DietPi-PREP | Unable to continue, DietPi-PREP will now terminate.
是什么问题？如何解决？

#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```?
- SBC Device (EG: RPi 3)?
- Power supply used (EG: 5v 1A RAVpower)?
- SD card used (EG: Sandisk ultra)?
- Distro (EG: Jessie) | ```uname -a```?

#### Additional Information (if applicable):
- Software title?
- Can this issue be replicated on a fresh installation of DietPi?

**Comment by zzlinwq** [comment]
DietPi Error Handler:
DietPi-PREP: systemctl stop dietpi-ramlog
  Exit code: 5
  DietPi version: v6.8 I HW_ MODEL :0 I HW_ ARCH:3 I DISTRO:4Image creator:Pre-image:
Log file contents:
Failed to stop dietpi-ramlog.service: Unit dietpi- ramlog.service not loaded.
If problems persist, please report this to DietPi for investigation, including ascreenshot of this error! (https :l/github .com/Fourdee/DietPi/ issues).
Unable to continue, DietPi-PREP will now terminate.
  <0k>

**Comment by Fourdee** [comment]
@zzlinwq 

Looks like an issue pre-hw selection.

Could be locale did not get applied, please paste results:
```
locale
cat /etc/locale.gen | grep '^e'
```

And lets check service it mentions, please paste results:
```
systemctl status dietpi-ramlog -l
```

- Which image ```.img``` are you using (before converting it to DietPi)?
- Which device is this running on (eg: Odroid C2)?

**Comment by zzlinwq** [comment]
@Fourdee 
root@amlogic:~# locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
root@amlogic:~# 
root@amlogic:~# 
root@amlogic:~# cat /etc/locale.gen | grep '^e'
en_GB.UTF-8 UTF-8
root@amlogic:~# systemctl status dietpi-ramlog -l
Unit dietpi-ramlog.service could not be found.
root@amlogic:~# 
root@amlogic:~#

**Comment by zzlinwq** [comment]
Which image .img are you using (before converting it to DietPi)?Armbian_5.44_S9xxx_Debian_stretch_3.14.29_icewm_20180515.img
@Fourdee

**Comment by zzlinwq** [comment]
Which device is this running on (eg: Odroid C2)? 斐讯天天链N1
http://www.phicomm.com/cn/index.php/Products/lian_spec/cateid/27/id/136.html

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40873957-e03c827e-669b-11e8-847f-c4f2215551b9.png)

https://user-images.githubusercontent.com/36132083/40873952-b9c24f84-669b-11e8-800a-d2ff102e44dc.png

**Comment by MichaIng** [comment]
@zzlinwq @Fourdee
Hmm, maybe somehow DietPi system was detected?
Does dietpi-ramdisk exist? `systemctl status dietpi-ramdisk`

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40877838-c5d3eeea-66b9-11e8-82e0-aa81bd541b5e.png)
root@amlogic:~# systemctl status dietpi-ramdisk
● dietpi-ramdisk.service - DietPi-RAMdisk
   Loaded: loaded (/etc/systemd/system/dietpi-ramdisk.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2018-06-02 01:34:31 UTC; 13h ago
  Process: 5894 ExecStart=/bin/bash -c /boot/dietpi/dietpi-ramdisk 0 &>> /var/tmp/dietpi/logs/dietpi-ramdisk.log (code=exited, status=0/SUCCESS)
  Process: 5891 ExecStartPre=/bin/mkdir -p /var/tmp/dietpi/logs (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/dietpi-ramdisk.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by zzlinwq** [comment]
@MichaIng 
root@amlogic:~# systemctl status dietpi-ramdisk
● dietpi-ramdisk.service - DietPi-RAMdisk
   Loaded: loaded (/etc/systemd/system/dietpi-ramdisk.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sat 2018-06-02 01:34:31 UTC; 13h ago
  Process: 5894 ExecStart=/bin/bash -c /boot/dietpi/dietpi-ramdisk 0 &>> /var/tmp/dietpi/logs/dietpi-ramdisk.log (code=exited, status=0/SUCCESS)
  Process: 5891 ExecStartPre=/bin/mkdir -p /var/tmp/dietpi/logs (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/dietpi-ramdisk.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by Fourdee** [comment]
@zzlinwq 

Thanks

Try:
```
rm /etc/systemd/system/dietpi-ramdisk.service
systemctl daemon-reload
rm -R /DietPi
```

Then re-run PREP commands (make sure to copy and paste this entire code in SSH window).
```
export GIT_BRANCH='master'

wget https://raw.githubusercontent.com/Fourdee/DietPi/$GIT_BRANCH/PREP_SYSTEM_FOR_DIETPI.sh -O PREP_SYSTEM_FOR_DIETPI.sh
chmod +x PREP_SYSTEM_FOR_DIETPI.sh
sudo GIT_BRANCH=$GIT_BRANCH ./PREP_SYSTEM_FOR_DIETPI.sh
```
If error occurs, please try to paste the entire contents of the SSH window. We can use to debug.

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40882401-650f26f6-6713-11e8-9a52-3cacc15124b1.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40882402-72ef9706-6713-11e8-97a7-d714e2be8f2b.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40882407-88df089e-6713-11e8-9833-1ef6f3a6e15f.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40882408-a1e5e592-6713-11e8-8245-9e9f7324842a.png)
![image](https://user-images.githubusercontent.com/36132083/40882409-adfe851e-6713-11e8-9106-f564550a68a7.png)
![image](https://user-images.githubusercontent.com/36132083/40882414-c6ecd1de-6713-11e8-8d7a-eecc4273b527.png)

**Comment by zzlinwq** [comment]
[FAILED] DietPi-PREP | Unable to continue, DietPi-PREP will now terminate.
@Fourdee @MichaIng

**Comment by Fourdee** [comment]
@zzlinwq 

Many thanks 👍 

Ok, apologies, I forgot to tell you to stop the service, before removal :)
- Reboot the system
- Rerun PREP again

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40882842-0ac427ba-6721-11e8-9bcb-0b5e92f1b49f.png)
![image](https://user-images.githubusercontent.com/36132083/40882844-13ce5786-6721-11e8-89d0-e07e6a3a4dbf.png)

**Comment by zzlinwq** [comment]
Now I reboot   the system and Rerun PREP again
@Fourdee

**Comment by zzlinwq** [comment]
[FAILED] DietPi-PREP | Unable to continue, DietPi-PREP will now terminate.

**Comment by MichaIng** [comment]
@zzlinwq 
Thanks for try and report.

Could you try to install the related APT package manually and report back the terminal output: `apt install firmware-realtek`
I see your device might not need this firmware, but for compatibility reasons we install it on all devices, as it enables support for several ethernet, wifi and bluetooth dongles.

If it remains really impossible to install it, you could remove this installation from DietPi preparation script: `sed -i '/G_AGI firmware-realtek/d' PREP_SYSTEM_FOR_DIETPI.sh`
But it would be good to investigate WHY this fails, as this should not happen, no matter if firmware will be used or not.

**Comment by Fourdee** [comment]
@MichaIng 

> But it would be good to investigate WHY this fails, as this should not happen, no matter if firmware will be used or not.

If I remember correctly, this occurs as it overwrites one of armbian's firmware .deb packages and causes an error (incompatible).
So either the armbian firmware needs to be removed, or, disable install of debian firmware.

But what confuses me is why ```dietpi-ramdisk``` exists, found the image http://soft.junlin.li/Armbian_5.44_S9xxx_Debian_stretch_3.14.29_icewm_20180515.img%20%281%29_20180531224519.xz. Unable to find it in ```/lib/systemd``` or ```/etc/systemd```

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40956828-d13f53a2-68c4-11e8-8c59-8a23bcf64eb1.png)
![image](https://user-images.githubusercontent.com/36132083/40956833-db03a776-68c4-11e8-8a66-1cacf5962932.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40956850-e9bfe824-68c4-11e8-843c-c39a1d997b3a.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40956854-fa3ff414-68c4-11e8-92e2-149129530b69.png)
@ @MichaIng @Fourdee

**Comment by zzlinwq** [comment]
Still not successful

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40959461-546facf4-68cf-11e8-8894-35c6d3ae0606.png)
![image](https://user-images.githubusercontent.com/36132083/40959470-5b5f6df6-68cf-11e8-8a3f-520e530213b9.png)
成功了吗？ @Fourdee @MichaIng

**Comment by MichaIng** [comment]
@zzlinwq 
Ah I was afraid first as you removed system core packages first, but seems the installer went through finally?

Strange, you are logged in as root, but script asks for root permissions? Could you run and paste the following?
`echo $UID`

@Fourdee
Puhh shall we try to resolve this issue for armbian images? Check for existing firmware and apt-get install firmware error outside of G_AGI handling and in case skip installation and set package on hold and as manual installed? Crazy hackaround, I wonder why armbian does not set it on hold, as every apt upgrade will fail....

**Comment by zzlinwq** [comment]
I logged in as dietpi
![image](https://user-images.githubusercontent.com/36132083/40979498-9304b930-6908-11e8-8f97-8edfa4c746e7.png)
@MichaIng

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/40979934-c61b8686-6909-11e8-815d-7ed9407a607c.png)

**Comment by zzlinwq** [comment]
I try  logged in as root, but  always prompt password error. What is password?

**Comment by zzlinwq** [comment]
Why doesn't WIFI work?

**Comment by Fourdee** [comment]
@MichaIng 

> Puhh shall we try to resolve this issue for armbian images? 

I'am tempted to do the following:
```
if [[ -f '/boot/armbianEnv.txt' ]]; then

   exit

fi
```

**Comment by Fourdee** [comment]
> I try logged in as root, but always prompt password error. What is password?

dietpi

> Why doesn't WIFI work?

Enabled in ```dietpi-config```?

Whats results of:
```
lsmod
```

**Comment by zzlinwq** [comment]
Why doesn't WIFI work?

Enabled in dietpi-config? It is enabled.

Whats results of:

lsmod
root@DietPi6689:~# lsmod
Module                  Size  Used by
brcmfmac              171742  0
brcmutil                5091  1 brcmfmac
cfg80211              415017  1 brcmfmac
aml_nftl_dev           95108  0
root@DietPi6689:~# 
@Fourdee

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/41202350-8dfcc7b6-6cfa-11e8-8ed1-3b85ff7725a8.png)
![image](https://user-images.githubusercontent.com/36132083/41202355-96e6a7de-6cfa-11e8-96ed-54a1df033924.png)

**Comment by zzlinwq** [comment]
![image](https://user-images.githubusercontent.com/36132083/41202358-a70f101a-6cfa-11e8-9f05-ee7b4162f181.png)

**Comment by Fourdee** [comment]
@zzlinwq 

Apologies for the delay.

In DietPi, WiFi relies on functional working drivers on the pre-image, and, knowing the exact WiFi hardware chipset used on the device.

Check dmesg for any errors relating to WiFi:
```
dmesg | grep brcm
dmesg | grep wlan
```

**Comment by zzlinwq** [comment]
[图片]

**Comment by zzlinwq** [comment]
roo t@DietPi6689:~# dmesg | grep brcm
roo t@DietPi6689:~# dmesg |  grep wlan
2.240105] Wifi: bcmdhd_ init_ wlan_ mem: bcmdhd_ init_ wlan_ mem: WIFI ME
I Allocated
@Fourdee

**Comment by Fourdee** [comment]
@zzlinwq 

Apologies for the delay.

Unfortunately, we can only support WiFi devices on the boards we provide images for.
