### ISSUE TITLE
General | Remove config.txt on non RPi systems

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1816]
This also needs adjustment of some scripts that expect/scrape this file (indeed unnecessarily): https://github.com/Fourdee/DietPi/blob/testing/PREP_SYSTEM_FOR_DIETPI.sh#L522

**Comment by MichaIng** [comment]
Finds within code: https://github.com/Fourdee/DietPi/search?q="config.txt"&unscoped_q="config.txt"
- 🈯️ **/DietPi/dietpi/boot**: Only touched within `if (( $G_HW_MODEL < 10 )); then`
- 🈯️ **/DietPi/dietpi/dietpi-config**: Only touched within `if (( $G_HW_MODEL < 10 )); then` or Menus that are just available for RPi.
- 🈺 **/DietPi/dietpi/func/dietpi-set_hardware**: Non-ramdisk `config.txt` declaration should be placed within RPi model check: https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-set_hardware#L56-L62
   - 🈺 Place other calls into model check statements: https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-set_hardware#L206-L207
   - https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-set_hardware#L317-L320
   - 🈯️ https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-set_hardware#L2060 Are all those options just available for RPi? Otherwise most would be without any effect, so I guess.
   - 🈯️ Cross check: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-config#L4996-L5025 **€: Cross check passed 👍.**
- 🈯️ Separate dietpi-software check, as if seems to be skipped when doing GitHub repo search: Passed!

**Comment by MichaIng** [comment]
PR up for testing: https://github.com/Fourdee/DietPi/pull/1863

**Comment by Fourdee** [comment]
REF, pending testing: https://github.com/Fourdee/DietPi/pull/1863#issuecomment-399697869

**Comment by Fourdee** [comment]
@MichaIng 

Great work on this 👍 No errors in my testing.

I believe we can mark as closed?

**Comment by MichaIng** [comment]
@Fourdee 
Jep, although I am still thinking that reverting config.txt gpu_mem to gpu_mem_XXX should be done. It is also failsafe in case user did manual add one of those. But I sleep now, will do this tomorrow.

**€: Done https://github.com/Fourdee/DietPi/pull/1885** I will mark as closed
