### ISSUE TITLE
CloudPrint 

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#1831]
Hello about this software

CloudPrint - CUPS print server, with support for Google cloud printing

Just to request some info

Does it works like  Airprint -  with Apple macOS and iOS operating systems for printing via a wireless LAN (Wi-Fi)? thought the Raspberry?

**Comment by Fourdee** [comment]
@symbios24 

Apple may require a different method of how you select to print, however, see below:
https://www.howtogeek.com/247940/how-to-print-to-a-google-cloud-printer-from-ios/

**Comment by symbios24** [comment]
is CloudPrint - CUPS print server, with support for Google cloud printing an airprint server?

does it creates an access point for printing?

Thanks

**Comment by Fourdee** [comment]
@symbios24 

> does it creates an access point for printing?

WiFi hotspot? No it does not.
