### ISSUE TITLE
manually update home-assistant

### ISSUE THREAD

**Issue by Lanneer487** [MichaIng/DietPi#1833]
Is there a possibility to manually update home-assistant?
I have version 0.69 but the latest update is 0.71 and apt-get upgrade doesn't update the package.

**Comment by Fourdee** [comment]
@roelfoubert 

Hi,

Yep, manual update is required as this software is installed via git.

1st make a backup of your system, just in-case you need to revert (as updating this software title is untested and mostly outside our control at the git end):
```
dietpi-backup
```

Once completed, you can upgrade Home Assistant, by re-running the installation:
```
dietpi-software reinstall 157
```

**Comment by Lanneer487** [comment]
Thanks this solution helps

**Comment by MZorzy** [comment]
how to skip re-download pytohn 3.6.3 and re-install it? 
it say "already exist" and then ask "continue with installation? (y/N)"
