### ISSUE TITLE
Plexmediaserver updates service 

### ISSUE THREAD

**Issue by Lanneer487** [MichaIng/DietPi#1837]
I've edited the plexmediaserver.service so it search the application support on my external disk.
When I update Plex, the service is reset to the original settings. Is there a way to prevent this?

**Comment by MichaIng** [comment]
@roelfoubert 
Create the following folder:
`mkdir /etc/systemd/system/plexmediaserver.service.d`
Then place some file inside that contains the same raw section headers and .conf ending:
`nano /etc/systemd/system/plexmediaserver.service.d/my-adjustment.conf`
E.g.
```
[Service]
ExecStartPost=/bin/bash -c '/path/to/my_own_script.sh'
```
to change/add the ExecStartPost script.
