### ISSUE TITLE
AlloGUI | Various issues

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1841]
> https://community.roonlabs.com/t/dietpi-allo-web-gui-now-available/32420/142?u=dan_knight
PW: https://github.com/Fourdee/DietPi/issues/1211

**Comment by Fourdee** [comment]
Notes:
None of these work via web interface, fine when logged in as allo user:
```
sudo /DietPi/dietpi/func/dietpi-set_hardware soundcard $soundcard
```

Due to globals and exit of unknown term, this works fine:
```
TERM=linux G_USER_INPUTS=0 sudo /DietPi/dietpi/func/dietpi-set_hardware soundcard $soundcard
```

**Comment by Fourdee** [comment]
Ok, testing passed, good to go, just need to update the images.

**Comment by Fourdee** [comment]
Notes for users, once we release v6.10:
- If you have the following issue (https://community.roonlabs.com/t/dietpi-allo-web-gui-now-available/32420/142?u=dan_knight), users will need to re-write the image as this cannot be recovered
- Existing users without the above issue, can simply update their installation

**Comment by Fourdee** [comment]
Completed.

**Comment by blogabe** [comment]
Hi @Fourdee so once this fix is pushed we'll be able to change the password for root and still be able to log into the Allo Web UI?

**Comment by Fourdee** [comment]
@blogabe

> Hi @Fourdee so once this fix is pushed we'll be able to change the password for root and still be able to log into the Allo Web UI?

Yep, once v6.10 is release and you have updated.

Or, you can install the v6.9.5 image which contains the fix now:
 https://dietpi.com/phpbb/viewtopic.php?f=8&t=2317&p=8869#p8869
