### ISSUE TITLE
Pine64 | GPU Support

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#1843]
#### Is your feature request related to a problem? Please describe:

- GPU support is not included in Pine64 boards. This blocks certain applications from working.

#### Describe the solution you'd like:

- Since there is now a Mali Driver release available (http://wiki.pine64.org/index.php/Mali_Driver) perhaps this can be included in the distro, as an option?

**Comment by Fourdee** [comment]
@midwan 
Apologies, not possible from our end currently.

Marking as closed.
