### ISSUE TITLE
DietPi-Software | Roon Extension Manager

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1866]
Testing https://github.com/Fourdee/DietPi/pull/1865

**Comment by Fourdee** [comment]
> Your license has just been renewed :slight_smile: . Happy testing!

Thanks Joel 👍 

~Unable to test, dev membership expired ☹️~
![image](https://user-images.githubusercontent.com/7077026/42098719-9905c820-7bb3-11e8-884a-e74947550716.png)

**Comment by Fourdee** [comment]
🈯️ Works a charm

@JanKoudijs Thank for adding this software into DietPi, we really appreciate your contribution!

As a small thank you, please email me daniel.knight@dietpi.com with your address, i'll send you some DietPi stickers.

Online doc: https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=13160#p13160

![image](https://user-images.githubusercontent.com/7077026/42101864-56e9a390-7bbc-11e8-8d88-7f79a45dac57.png)

**Comment by Fourdee** [comment]
Completed, available in v6.10 update.

**Comment by JanKoudijs** [comment]
Thanks @Fourdee Dan!

Now that went quick, just a week ago I downloaded the virtualbox image of DietPi to find out how a software package can be added, and now the Roon Extension Manager is ready for inclusion in v6.10 :+1: 

Proofs to me how well DietPi is set up!

DietPi is the first distribution / device that has the Extension Manager as an integrated part. Roon users that already use it for running the Roon Bridge now have the option to run extensions as well! I like it!

Thanks again.
