### ISSUE TITLE
Mosquitto installation problem - can't find executable

### ISSUE THREAD

**Issue by lupa18** [MichaIng/DietPi#1868]
#### Required Information:
- DietPi version	| 6.9
- Distro version	| stretch
- Kernel version	| 4.4.77-rockchip-ayufan-136
- SBC device		| Rock64 (aarch64)
- Power supply used	| 5V 3A
- SDcard used		| Class 10 micro SD

#### Additional Information (if applicable):
- Software title	| Mosquitto
- Was the software title installed freshly or updated/migrated? Installed Freshly
- Can this issue be replicated on a fresh installation of DietPi? Yes
- `dietpi-bugreport` f08067cc-5550-4254-968d-09db2bbf6111

#### Steps to reproduce:

1. Go to dietpi-software
2. Then choose Software Optimized
3. Mark Mosquitto (123)
4. Choose Install

#### Expected behavior:

Mosquito has to be installed, its executable must be in some place. Based on init.d script, must be at: /usr/sbin/mosquitto

#### Actual behaviour:

Executable can't be founded anywhere

**Comment by MichaIng** [comment]
@lupa18 
Thank you very much for your report. I will review your bug report and try to replicate on x86_64 VM.

**€: Just checked bug report:**
- Sadly no `/var/log/apt/term.log` available any more and `/var/tmp/dietpi/logs/dietpi-software_apt.log` shows just mosquitto package being uninstalled. @lupa18 Did you manually remove mosquitto again? Otherwise might `apt-get -f install` can't find all needed dependencies and remove the package again automatically? Test outstanding, need to be at home to run tests on VM.

**Comment by Fourdee** [comment]
Confirmed ARMv8 issue:
```
Errors were encountered while processing:
 mosquitto:armhf
[  OK  ] DietPi-Software | APT fix, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies... Done
The following packages will be REMOVED:
  mosquitto:armhf
0 upgraded, 0 newly installed,
```

---

Our current binaries ```mosquitto_1.4.14``` are still a higher version than stretch:
https://packages.debian.org/stretch/mosquitto

```
G_AGI libuuid1:armhf libc6:armhf libwrap0:armhf libssl1.0.0:armhf
```

libssl1 not in debian repo, pulled from our server

**Comment by MichaIng** [comment]
@Fourdee 
Okay, hmm maybe we can find out which package is missing on ARMv8. Maybe some update of our deb package helps. v1.5 is available.

€: Jep and I bet that stretch repo will not receive any non critical  package updates. The ones on buster are 1.4.15 but could have dependency issues on Stretch.

€€: Ah if it's just libssl1.0.0 then at least easy to fix with dietpi-software.

**Comment by Fourdee** [comment]
Notes:
- Default compile missing services and ```/etc/mosquitto/mosquitto.conf```.
- init.d used previously, lets make a systemD version ```/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf```
- no process created, no info... | ```1529937553: Error: Invalid user 'mosquitto'.```
```
root@DietPi:~# /usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf -v
root@DietPi:~#
```

---

Custom debian repo lacks ARMv8
http://repo.mosquitto.org/debian/dists/stretch/main/

**Comment by MichaIng** [comment]
@Fourdee 
> Custom debian repo lacks ARMv8

Might be the reason why we added armhf arch to arm64 devices within current install script?

**Comment by Fourdee** [comment]
Ok:
- All devices will use official Debian repo install  (1.4 currently)
- If we get complaints for this change (eg: I need 1.5 for features), we'll re-investigate post-v6.10 for ARMv7 and AMD64 using http://repo.mosquitto.org/debian/dists/stretch/main/ (1.5)

--- 

Another 'naughty?' option, 1.5 on all devices, source build over the top, ensuring services and conf exist:
- ```G_AGI mosquitto```
```
G_AGI build-essential libc-ares-dev uuid-dev libssl-dev
wget https://github.com/eclipse/mosquitto/archive/v1.5.zip -O package.zip
unzip package.zip
rm package.zip
cd mosquitto-*

sed -i '/^WITH_SOCKS:=/c\WITH_SOCKS:=no' config.mk
sed -i '/^WITH_DOCS:=/c\WITH_DOCS:=no' config.mk
make -j $(nproc --all)
make install
mv /usr/local/sbin/mosquitto /usr/sbin/mosquitto
cd ..
rm -R mosquitto-*
```

**Comment by Fourdee** [comment]
@lupa18 

Workaround (nice and simple), to install mosq:
```
G_AGI mosquitto
dietpi-services dietpi_controlled
dietpi-services restart
```

**Comment by Fourdee** [comment]
Test install's passed, completed. Please reopen if required.
