### ISSUE TITLE
Pi-hole web-interface not showing stats

### ISSUE THREAD

**Issue by fairyfeller** [MichaIng/DietPi#187]
Made a clean fresh install of DietPi (v 108) with Pi-hole on Orange Pi 2 Mini (runs and works flawlessly). Seems like pi-hole working (i mean blocking ads), but there's some elements missing in web-interface and no stats.. 
![screenshot 2016-02-04 15 16 38](https://cloud.githubusercontent.com/assets/16131050/12814726/5527bf46-cb52-11e5-9768-72994415fa64.png)

**Comment by Fourdee** [comment]
@fairyfeller 
Looks like they moved the logfile parsing code out of index.php to another shell script: https://github.com/pi-hole/AdminLTE/blob/master/index.php#L2
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh

Run the following:

```
wget https://raw.githubusercontent.com/pi-hole/pi-hole/master/advanced/Scripts/chronometer.sh -O /usr/local/bin/chronometer.sh
chmod +x /usr/local/bin/chronometer.sh
```

Then refresh the webpage (ctrl+f5).

**Comment by Fourdee** [comment]
And BC (an additional package) is now required for PiHole to work out the percentage.
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L55

```
apt-get install bc
```

Then refresh the webpage (ctrl+f5).

**Comment by Fourdee** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7077026/12817405/c4fb4594-cb49-11e5-8152-2808c764475e.png)

**Comment by fairyfeller** [comment]
Yep, after getting new chronometer.sh and BC - it started to show some stats..
Still missing some menus on the left side as Update, Whitelist, and Reboot

**Comment by Fourdee** [comment]
Resolved for v109. Will also be applied as a patch during update.

PiHole on DietPi will now be installed from a separate/stable fork of the project.
https://github.com/Fourdee/pi-hole
https://github.com/Fourdee/AdminLTE

This will allow us to merge/update the PiHole project in a testing environment, before being rolled out to DietPi users.

**Comment by Fourdee** [comment]
@fairyfeller 

> Yep, after getting new chronometer.sh and BC - it started to show some stats..
> Still missing some menus on the left side as Update, Whitelist, and Reboot

Will take a look.

Updates for PiHole are rolled out as patches with dietpi-update.

**Comment by Fourdee** [comment]
@fairyfeller 
I cant see any references to blacklist/whitelist/reboot in the sourcecode of the webpage: https://github.com/Fourdee/AdminLTE/blob/master/index.php

Are you sure this has been implemented by Pi-Hole?

**Comment by fairyfeller** [comment]
@Fourdee , i expected something like this http://jacobsalmela.com/pi-hole-2-0-web-interface-dashboard/
Thought it's already released :)
Then found this https://github.com/pi-hole/AdminLTE/commit/5eaf1c0392cf32c00fcbcf6b4afa1bd7bf0c9e74

**Comment by Fourdee** [comment]
Ah, good find. So it did exist but was removed.

As this resolves all outstanding issues, i'll close this ticket. If you experience any further issues or questions, please reopen.
