### ISSUE TITLE
Lidarr software request

### ISSUE THREAD

**Issue by stdusm** [MichaIng/DietPi#1874]
Same as Radarr/Sonarr but for music.

https://github.com/lidarr/Lidarr

**Comment by Fourdee** [comment]
Interesting, thanks for the suggestion 👍 . I'll flag this for v6.11 investigation/implementation.

**Comment by luispuerto** [comment]
i don't really know how well this app works, but I'm also interested in seeing it implemented in DietPi. Thanks!

**Comment by Fourdee** [comment]
- Online DOC: https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=13580#p13580

**Comment by Fourdee** [comment]
Completed, available in DietPi v6.13 (ETA: 1 week)
