### ISSUE TITLE
waiting for "valid' internet connection 

### ISSUE THREAD

**Issue by unclehowell** [MichaIng/DietPi#1879]
https://ibb.co/ndPY9o

Today it just won't connect, says its waiting for a valid internet connection. Internet's fine. Something must have changed your end. Can you help me diagnose this please ?

**Comment by Fourdee** [comment]
@unclehowell 

Thanks for the report 👍 

I'am unable to replicate our end. We'll need to debug.

Please mount the SD card using a SD card > USB reader, and set the following in ```/boot/dietpi.txt```
- ```CONFIG_BOOT_WAIT_FOR_NETWORK=1```

Boot the system back up, then run the following commands (paste/picture results please):
```
ip a
ping google.com -c 1
ping raspbian.raspberrypi.org -c 1
ping dietpi.com -c 1
cat /etc/network/interfaces #Please remove any WiFi keys before pasting
```

**Comment by Fourdee** [comment]
@unclehowell 

Marking as closed, I believe this is a temp issue with networking (local and/or remote), however, please reopen if required.
