### ISSUE TITLE
DietPi-Software | Add Hastebin installation option

### ISSUE THREAD

**Issue by fairyfeller** [MichaIng/DietPi#189]
It would be nice to have option for quick installation of [Hastebin](https://github.com/seejohnrun/haste-server) server.
And get your own pastebin's at http://your-dietpi-ip/xxx123 :)

**Comment by Fourdee** [comment]
@fairyfeller 
Sounds interesting :+1: , added to the list :)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
