### ISSUE TITLE
Just a question about 6.10

### ISSUE THREAD

**Issue by DaCodaHUB** [MichaIng/DietPi#1897]
I couldn’t find it in the release note but does 6.10 include the file system expansion option in diet-drive_manager?

**Comment by Fourdee** [comment]
@DaCodaHUB 

Apologies, missed that entry in changelog. Yes it does.
![image](https://user-images.githubusercontent.com/7077026/42290498-87483b5a-7fbd-11e8-908d-bd13f502f171.png)


I'll mark this as answered. Please reopen if required.
