### ISSUE TITLE
[dupe] Cant mount NFS on Rpi 

### ISSUE THREAD

**Issue by mgherghi** [MichaIng/DietPi#1904]
│ DietPi-Drive_Manager: mount -t nfs -o port=2049 192.168.1.1:/ /mnt/nfs
                  │  - Exit code: 32
                  │  - DietPi version: v6.11 | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4
                  │  - Image creator: DietPi Core Team
                  │  - Pre-image: Raspbian Lite
                  │
                  │ Log file contents:
                  │ mount.nfs: Protocol not supported

////////////////////////////////////////////////////////////////////

So i believe the problem lays in the fact that my router that is doing the nfs export is only exporting nfsv3 and the dietpi is using nfsv4 . How should i fix this issue ? 

Bugreport reference: 0c5e5354-a05d-4055-8100-e8064d21272b

**Comment by Fourdee** [comment]
@mgherghi 

Hi, thanks for the report 👍 

We are currently looking into this, however, we do need users with NFS v2/3 to assist us with testing.

#### Please can you try the following, one at a time and see which (if any) connect:
```
mkdir -p /mnt/nfs

#Test 1
mount -t nfs -o port=2049,nfsvers=3 192.168.1.1:/ /mnt/nfs

#Test 2
mount -t nfs -o port=2049,vers=3 192.168.1.1:/ /mnt/nfs
```

#### Please paste your results in the following ticket: https://github.com/Fourdee/DietPi/issues/1898
I'll mark this as closed (dupe)
