### ISSUE TITLE
DietPi-Software | Add xrdp installation option

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#191]
Please add xrdp app for windows remote desktop support, an alternative to access lxde desktop.

`sudo apt-get install xrdp`

**Comment by xenfomation** [comment]
@Fourdee -- is this still active as I have no issues taking care of this as I relentlessly use xrdp for my Debian-based distributions!

Nice, @starstuff !!  Thanks!

**Comment by Fourdee** [comment]
@xenfomation 
Yep :+1: , all open tickets are up for the taking.

**Comment by xenfomation** [comment]
Double checking deps based on recent Deb work with xrdp.  I used no machine, but will post findings.

**Comment by xenfomation** [comment]
Update as, of course, xrdp works and requires < 13MiB of space!

Screenshots attached to show the result of `apt-get install xrdp`:

![xrdp1](https://cloud.githubusercontent.com/assets/10519408/15378541/52a7d116-1d32-11e6-942b-4b7a809e21b9.png)
![xrdp2](https://cloud.githubusercontent.com/assets/10519408/15378543/548c5bdc-1d32-11e6-9d6d-f6018c864369.png)
![xrdp3](https://cloud.githubusercontent.com/assets/10519408/15378547/560ec7c4-1d32-11e6-8a64-dfe832816eb9.png)

### Linux Software

Along with No Machine, XRDP is great -- maybe this will dictate a REMOTE SERVER option under Linux Software

I will work on a prototype.

Thanks!

**Comment by xenfomation** [comment]
Working on re-testing and incorporation under "Software Linux" -> "Remote Desktop".  Seems logical to me as each package will have the description to state "Server" or "Client".

**Comment by xenfomation** [comment]
Tested and preparing to commit.

XRDP is under Software Optimized -- works with LXDE, MATE #151 , and GNUStep #357 .

![xrdpsuccess](https://cloud.githubusercontent.com/assets/10519408/15631989/5974b140-2551-11e6-8081-48c99d4bebd5.PNG)

**Comment by Fourdee** [comment]
Additional implementation and testing for reference: https://github.com/Fourdee/DietPi/pull/364

**Comment by Fourdee** [comment]
Documentation to finish: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=70#p2074

**Comment by Fourdee** [comment]
@xenfomation 
Is there a way to disable applications that are not installed, being listed?
![image](https://cloud.githubusercontent.com/assets/7077026/15900774/94b32580-2d98-11e6-8eac-3d7fd48e7897.png)

**Comment by Fourdee** [comment]
Done.
