### ISSUE TITLE
DietPi-Software | Pydio: Install rework needed, currently intrusive Apache only config

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1913]
Pydio currently configures Apache2 webserver only and PHP + Apache configuration files in an intrusive way. Needed is:
- Download from always up-to-day source: https://download.pydio.com/pub/core/ci/pydio-latest.tar.gz
  - tar.gz due to smaller download size and possible surviving user permissions
- Webserver dependent pydio-only configuration file, containing php_(admin_)value fcgi output_buffering value, FollowSymLink and other configuration, on /var/www/pydio only basis.
- Assure PHP modules are enabled: https://pydio.com/en/docs/v8/pydio-requirements
  - Interesting openssl in opposition of mcrypt (not available on Debian Buster any more)? I think we can remove mcrypt completely.

Priority low due to low install count, however it might be related to the currently suboptimal installation method: https://dietpi.com/survey
- At least Pydio is still actively developed 👍

**Comment by MichaIng** [comment]
Pydio APT repo is available, but for x86 only: https://download.pydio.com/pub/linux/debian/dists/stretch/main/

Stay with archive, to not further split/complicate install method.
_______________
Download available from GitHub: https://github.com/pydio/pydio-core/releases
and from pydio.com: https://download.pydio.com/pub/core/archives/

Official current release is 8.2.2 from 11.10., but the archive from different subdir above seems to be a different newer one. Not sure if these are daily/weekly development releases?
- But release notes show 8.2.2

Strange, https://api.github.com/repos/pydio/pydio-core/releases is empty, compared to Sonarr/Radarr etc, so it seems the on GitHub the repo owners need to actively enable this APT access features 🤔.

https://pydio.com/en/get-pydio 403 🤔 even that it is from official docs: https://pydio.com/en/docs/v8/install-archive
__________
Internal updater works well btw, so simply skip archive download/install, if already existent. Will be done since v6.18 automatically for database.
__________
PR up: https://github.com/Fourdee/DietPi/pull/2259

**Comment by Fourdee** [comment]
ASUS TB Stretch install + GUI use test:
- 🈯️ 

Loving the file drag + drop feature in GUI 😃 

Thanks @MichaIng

Although I still received the following:
![image](https://user-images.githubusercontent.com/7077026/48741613-ab966100-ec53-11e8-8e19-5aa2e2542e45.png)
```
root@DietPi:~# cat /etc/lighttpd/conf-enabled/99-dietpi-pydio.conf
$HTTP["url"] =~ "^/pydio($|/)" {
        # Deny access to pydio/data dir
        $HTTP["url"] =~ "^/pydio/data" {
                url.access-deny = ("")
        }

        # Disable PHP output buffering, recommended by Pydio
        setenv.add-environment += (
                "PHP_ADMIN_VALUE" => "output_buffering=Off",
        )

}
```

**Comment by Fourdee** [comment]
Hmm, appears to be working fine. Pydio setup does not seem to actually check the URL:
- 🈯️ Lighttpd http://192.168.0.118/pydio/data/
```
403 - Forbidden
```

**Comment by Fourdee** [comment]
Output buffer message disappears with:
```
/etc/php/7.0/mods-available/dietpi.ini
output_buffering=Off
```

**Comment by Fourdee** [comment]
🈴 mysql.service starting with mariadb.service, causes hang on ```dietpi-services start```
```
root@DietPi:~# systemctl status mysql -l
● mysql.service - LSB: Start and stop the mysql database server daemo
n
   Loaded: loaded (/etc/init.d/mysql; generated; vendor preset: enabled)
   Active: active (running) since Sat 2018-11-24 04:52:43 GMT; 32s ag
o

root@DietPi:~# systemctl status mariadb -l
● mariadb.service - MariaDB 10.1.37 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; disabled; vendor preset:
 enabled)
   Active: activating (start) since Sat 2018-11-24 04:52:44 GMT; 51s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
```

🈯️ ```rm /etc/init.d/mysql; systemctl daemon-reload```

**Comment by Fourdee** [comment]
Ok, retest of Pydio setup page results + reboot:
- 🈯️ Lighttpd
- 🈯️ Nginx
- 🈯️ Apache2

Testing passed. Completed.
