### ISSUE TITLE
DietPi-Software | SABnzbd: Pre-install language files for end user

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#1917]
#### Is your feature request related to a problem? Please describe:

- First web UI access shows:

> ### Language
> Select a web interface language.
> 
> No language files detected. Please run python tools/make_mo.py once and restart SABnzbd, or contact your package provider.

#### Describe the solution you'd like:

- Tested successfully on VM-Stretch:
```
cd /etc/sabnzbd
python tools/make_mo.py
cd $HOME/$FP_WORK_DIR
```

#### Describe alternatives you've considered:

- As the command is relatively trivial, we could also leave this to end user and provide a more lightweight install by default.

**Comment by Fourdee** [comment]
@MichaIng 

> As the command is relatively trivial, we could also leave this to end user and provide a more lightweight install by default.

Yep I agree. 

Although it only takes 2 seconds on a ASUS TB:
```
real    0m2.428s
user    0m2.050s
sys     0m0.170s
```

I'll add this by default.

---

Done and test install passed 🈯️ 
@MichaIng Great work on solution 👍
