### ISSUE TITLE
Add DietPi to Raspberry Pi Third Party OS Images

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#192]
Please add DietPi to the  Raspberry Pi Third Party OS Images to be more accessible to the general public

[https://www.raspberrypi.org/downloads/](url)

Im a new linux user, and find DietPi to be super easy to use!

**Comment by Fourdee** [comment]
@starstuff 
Thanks for all the requests.

> Please add DietPi to the Raspberry Pi Third Party OS Images to be more accessible to the general public

I've tried on various occasions to make this happen with forum posts and a few tweets https://twitter.com/DietPi_/status/693493797427232770
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=100976

Unfortunately, there are no FAQ, rules, requirements, or contact information available for users who wish to add other distros.

I think the only way we can achieve this is to promote, discuss and spread the word on DietPi. Maybe once we have enough "popularity", the Raspberry Pi staff may take notice :)

**Comment by bhaveshgohel** [comment]
+1 DietPi Rulzz... :fire:
