### ISSUE TITLE
DietPi-Software | Add PeerGuardian installation option

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#193]
Please add peerguardian to dietpi.

[http://sourceforge.net/p/peerguardian/wiki/pgl-Install-DebianUbuntu/](url)

**source**
`deb http://moblock-deb.sourceforge.net/debian jessie main`
`deb-src http://moblock-deb.sourceforge.net/debian jessie main`

**install**
`sudo apt-get install pgld pglcmd pglgui`

TIA

**Comment by Fourdee** [comment]
Looks like we will need to compile these as `deb http://moblock-deb.sourceforge.net/debian jessie main` doesnt have armhf deb packages.

https://sourceforge.net/projects/peerguardian/files/PeerGuardian%20Linux/2.3.1/

**Comment by Invictaz** [comment]
Would be nice

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
