### ISSUE TITLE
Update nexcloud

### ISSUE THREAD

**Issue by ludji49** [MichaIng/DietPi#1935]
Création d'un rapport de bogue ou d'un problème :

###### Informations requises :
- Version DietPi | `paste -sd '' /DietPi/dietpi/.version`. 6.11
- Version Distro | `echo $G_DISTRO_NAME` ou `cat /etc/debian_version`.
- Version du noyau | `uname -a`.
- Dispositif SBC | `echo $G_HW_MODEL_DESCRIPTION` EG : RPi3
- Alimentation utilisée | EG : 5V 1A RAVpower
- Carte SD utilisée | EG : SanDisk ultra 

Renseignements supplémentaires (s'il y a lieu) :
- Titre du logiciel |  Nextcloud
- Le titre du logiciel a-t-il été installé récemment ou a-t-il été mis à jour ou migré ? yes
- Ce numéro peut-il être reproduit sur une nouvelle installation de DietPi ? no
- ID `dietpi-bugreport` ID

###### Étapes pour se reproduire :
>>le numéro.
1. ...
2. ...

###### Comportement attendu :
Que DEVRAIT-il se passer ? -->
- ...

###### Comportement réel :
Qu'est-ce qui se passe ? -->
- ...

Traduit avec www.DeepL.com/Translator

**Comment by ludji49** [comment]
![screenshot-nextcloud-myweb ddns net-2018 07 18-06-44-34](https://user-images.githubusercontent.com/10480101/42878039-f385b8dc-8a8b-11e8-86f4-43009a672a8e.png)

**Comment by MichaIng** [comment]
@ludji49 
`.well-known` folders are added by various web services and scripts, nothing to worry about.
Simply move it outside your Nextcloud folder and inside again after update has finished:
`mv /path/to/nextcloud/.well-known /tmp/`
Update Nextcloud via web updater
`mv /tmp/.well-known /path/to/nextcloud/`

**Comment by ludji49** [comment]
I just don't understand moving out of your Nextcloud folder and inside 
With the cmd putty

**Comment by MichaIng** [comment]
@ludji49 
1. Copy the command into your putty terminal:
`mv /path/to/nextcloud/.well-known /tmp/`
2. Update Nextcloud as your tried
3. Copy next command into your putty terminal:
`mv /tmp/.well-known /path/to/nextcloud/`

**Comment by ludji49** [comment]
there is an error on the writing of the command
![2018-07-19_175538](https://user-images.githubusercontent.com/10480101/42954625-80274bec-8b7d-11e8-982e-a298399896d5.png)

**Comment by MichaIng** [comment]
@ludji49 
Ah sorry, `/path/to/nextcloud/` should be replaced with the path to your nextcloud directory. On DietPi it should be then:

`mv /var/www/nextcloud/.well-known /tmp/`

and after Nextcloud update: `mv /tmp/.well-known /var/www/nextcloud/`

**Comment by ludji49** [comment]
Update done, but for the next update I have to go through this command 
mv /var/www/nextcloud/.well-known /tmp/
and after Nextcloud update: mv /tmp/.well-known /var/www/nextcloud/

![2018-07-19_201637](https://user-images.githubusercontent.com/10480101/42962057-00b61bae-8b91-11e8-94ee-a8b1b8b65149.png)

**Comment by MichaIng** [comment]
@ludji49 
That's true.

One of the negative sides of having webroot within /nextcloud directory. Other software tends to place file into webroot, which Nextcloud then identifies as integrity check violation. They already added much of the "well known" files/folders to be excluded for this, but for some reason `.well-known` still breaks updates.

You could check what is inside and if it's needed: `ls -al /var/www/nextcloud/.well-known`

**Comment by ludji49** [comment]
Thank you very much .......

**Comment by MichaIng** [comment]
I mark this as closed, as initial issue is answered/solved. Please reopen, if required.
