### ISSUE TITLE
DietPi-Software | Add Zim Desktop Wiki installation option 

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#194]
Please add Zim Desktop Wiki, its like dokuwiki but simpler and easier to use.

i use it to gather all information, references.

[http://zim-wiki.org/downloads.html](url)

**Comment by xenfomation** [comment]
Checking out Zim - as it is cool - and deps.  Thanks.

**Comment by xenfomation** [comment]
Install reqs can be found at 
http://zim-wiki.org/install.html

While there are custom options, I will run a stock install this week on RPI.  The reason is due to previous comments related to discussing user directories.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
