### ISSUE TITLE
Unable to install latest DietPi version

### ISSUE THREAD

**Issue by giulio92** [MichaIng/DietPi#1944]
#### Details:
- Date           | Fri 20 Jul 22:23:56 CEST 2018
- Bug report     | N/A
- DietPi version | v6.12
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1123 SMP Wed Jun 27 17:35:49 BST 2018
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:
1. Download the DietPi Raspberry Pi image (.img) from the official DietPi website 
2. Flash the .img to a microSD card
3. Install using `SSH` protocol

#### Expected behaviour
- Installation should complete successfully

#### Actual behaviour:
- Installation stops with an error

#### Additional logs:
```
Log file contents:
Ign:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Err:2 http://raspbian.raspberrypi.org/raspbian stretch Release
  Unable to connect to raspbian.raspberrypi.org:http:
Err:3 https://archive.raspberrypi.org/debian stretch InRelease
  Failed to connect to archive.raspberrypi.org port 443: No route to host
Reading package lists...
E: The repository 'http://raspbian.raspberrypi.org/raspbian stretch Release' does no longer have a Release file.
```

**Comment by Fourdee** [comment]
@giulio92 

Hi thanks for the report 👍 

Were any changes made to ```dietpi.txt``` prior to running the system for the 1st time?

Please can you also paste results of the following:
```
cat /etc/apt/sources.list
```

It may also be a temp issue with local/remote network, please try running the following command:
```
G_AGUP
```

If the above command works, resume setup with:
```
dietpi-software
```

Note to self:
Link appears to be functional http://raspbian.raspberrypi.org/raspbian

**Comment by giulio92** [comment]
Hi @Fourdee,

I made no changes to `dietpi.txt`, here's the `cat /etc/apt/sources.list` result:

```
root@DietPi:~# cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian stretch main contrib non-free rpi
```

and here's `G_AGUP`'s

```
root@DietPi:~# G_AGUP
[  OK  ] Root access verified.
[  OK  ] APT update, please wait...
Err:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
  Temporary failure resolving 'raspbian.raspberrypi.org'
Err:2 https://archive.raspberrypi.org/debian stretch InRelease
  Could not resolve host: archive.raspberrypi.org
Reading package lists...
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/stretch/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch https://archive.raspberrypi.org/debian/dists/stretch/InRelease  Could not resolve host: archive.raspberrypi.org
W: Some index files failed to download. They have been ignored, or old ones used instead.
[  OK  ] G_AGUP
```

I was able to install DietPi without issues in the past

**Comment by MichaIng** [comment]
@giulio92 
It seems to be a network issue on your side. All links and files open and resolve fine here.

Are you able to ping other web resources, e.g. `ping dietpi.com`?
Do you have a working DNS server configured: `cat /etc/resolv.conf`?

You can also use `dietpi-config` to review and reset your network configuration.

**Comment by giulio92** [comment]
I have flashed the `.img` again and surprisingly enough the installation succeeded with the same settings 😊

**Comment by MichaIng** [comment]
@giulio92 
Okay, no change to investigate how your system ran into the prior situation. But good that it works now 🙂.
