### ISSUE TITLE
SMP affinity

### ISSUE THREAD

**Issue by antonellocaroli** [MichaIng/DietPi#1962]
I do not know if it's something that can interest.
I use the system as a player/render audio.
Then isolate CPU 3 at boot, adding isolcpus=3 to boot parameters
I dedicate this cpu to the player through dietpi-process_tool.

after I move the system interrupts.
apparently both the sparky and the rpi3 use the cpu0 for system interrupts

`cat /proc/interrupts`

![selection_091](https://user-images.githubusercontent.com/11161093/43217931-443d8d4c-9043-11e8-999b-860d2a931726.png)
so I move the 56 and 93 on cpu1 and 32 on cpu2

`echo "2" > /proc/irq/56/smp_affinity`
`echo "2" > /proc/irq/93/smp_affinity`
`echo "4" > /proc/irq/32/smp_affinity`

https://cs.uwaterloo.ca/~brecht/servers/apic/SMP-affinity.txt

![selection_093](https://user-images.githubusercontent.com/11161093/43218671-55625fd8-9045-11e8-92c7-1867d42063c7.png)

twd I do not know what it is (29), but that does not move.
But already so it seems more balanced.

I do not know if this can be added to the DietPi scripts.

**Comment by Fourdee** [comment]
@antonellocaroli 

Hi,

Thanks for the info and request 👍 

I am aware of the ```isolcpus=X``` option, have tried it in the past, can benefit audio systems. 
However, the issue from our end is that not all systems support kernel boot options on the fly, and, they vary per device.
So from a DietPi point, its nothing something we can implement across all systems.

This is also very advanced, and I believe the majority of our end users would simply not benefit from this feature (to a point it could be used incorrectly).

As such, i've marked this as information, to alllow those users who want to tinker with this option, a method to do so.

I'll mark this as closed, however, please continue discussions as required. And again, thanks for posting this info 👍
