### ISSUE TITLE
PSU | External harddrive disconnect automatically

### ISSUE THREAD

**Issue by Lanneer487** [MichaIng/DietPi#1966]
My external harddrive can be disconnected automatically after a various time. In drive_manager it is visible but not accessible by /mnt/...

**Comment by Fourdee** [comment]
@roelfoubert 

Its most likely one of the following:
- The drive is failing
- The USB device is not getting enough power

Please can you confirm:
- SBC device (eg: RPi Zero)
- PSU used (eg 5v/1a)
- USB drive used, and, does it have its own PSU?

**Comment by Lanneer487** [comment]
I use a raspberry pi 3 with a powersupply of 5V/2.4A
I have 3 drives connected. 2 normal usb drives and one external harddrive. Non of them with own PSU

**Comment by Fourdee** [comment]
@roelfoubert 

> I use a raspberry pi 3 with a powersupply of 5V/2.4A
I have 3 drives connected. 2 normal usb drives and one external harddrive. Non of them with own PSU

Might be slightly over the available 1.2A max shared across all USB ports.

To verify power is the issue, when the system has been running for a few hours, check the following command for any voltage issues:
```
dmesg | grep volt
```

and
```
dmesg | grep sd[a-z]
```

Ideally, a powered USB hub (at least 2A) is recommended for multiple connected drives.

**Comment by Lanneer487** [comment]
This is the info:
root@RaspberryPi:~# dmesg | grep volt
[   33.271502] Under-voltage detected! (0x00050000)
[   39.511627] Under-voltage detected! (0x00050005)
[   54.071520] Under-voltage detected! (0x00050005)
[ 2186.072408] Under-voltage detected! (0x00050005)
[ 3184.471604] Under-voltage detected! (0x00050005)
[ 3217.751806] Under-voltage detected! (0x00050005)
[ 3261.431646] Under-voltage detected! (0x00050005)
[ 5439.191526] Under-voltage detected! (0x00050005)
[11535.671558] Under-voltage detected! (0x00050005)

And

root@RaspberryPi:~# dmesg | grep sd[a-z]
[    0.870314] sdhci: Secure Digital Host Controller Interface driver
[    0.874775] sdhci: Copyright(c) Pierre Ossman
[    0.884300] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.888882] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.086807] sdhost: log_buf @ b3907000 (f3907000)
[    1.171425] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    3.837885] sd 1:0:0:0: [sdb] 60555264 512-byte logical blocks: (31.0 GB/28.9 GiB)
[    3.843033] sd 1:0:0:0: [sdb] Write Protect is off
[    3.847752] sd 1:0:0:0: [sdb] Mode Sense: 45 00 00 00
[    3.848168] sd 1:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    4.033381]  sdb: sdb1 sdb2
[    4.040363] sd 1:0:0:0: [sdb] Attached SCSI removable disk
[    5.394166] sd 0:0:0:0: [sda] 126918656 512-byte logical blocks: (65.0 GB/60.5 GiB)[    5.400638] sd 0:0:0:0: [sda] Write Protect is off
[    5.405784] sd 0:0:0:0: [sda] Mode Sense: 23 00 00 00
[    5.407032] sd 0:0:0:0: [sda] No Caching mode page found
[    5.412222] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    5.446654]  sda: sda1
[    5.455721] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    5.462667] EXT4-fs (sdb2): INFO: recovery required on readonly filesystem
[    5.467841] EXT4-fs (sdb2): write access will be enabled during recovery
[    6.397832] sd 2:0:0:0: [sdc] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)[    6.403217] sd 2:0:0:0: [sdc] Write Protect is off
[    6.408192] sd 2:0:0:0: [sdc] Mode Sense: 47 00 00 08
[    6.408639] sd 2:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    6.714231]  sdc: sdc1
[    6.721029] sd 2:0:0:0: [sdc] Attached SCSI disk
[    9.612405] EXT4-fs (sdb2): recovery complete
[    9.624502] EXT4-fs (sdb2): mounted filesystem with ordered data mode. Opts: (null)[   13.699563] EXT4-fs (sdb2): re-mounted. Opts: (null)
[   16.461940] EXT4-fs (sda1): warning: maximal mount count reached, running e2fsck is recommended
[   16.809345] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)[   20.157509] FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   26.280475] EXT4-fs (sdc1): recovery complete
[   26.295269] EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: (null)

**Comment by Fourdee** [comment]
@roelfoubert 

Thanks, appears issue is caused by:
- Insufficient PSU, which is not providing stable 5V. Please use the official RPi PSU 5v/2.5A.

You also have filesystem issues (due to the above) on your drives. I'd highly recommend:
- Purchasing an official RPi PSU 5v/2.5A
- Writing a new DietPi image and starting from scratch
- Formatting all the drives prior to use

As this is a hardware issue, with known cause of PSU, i'll mark this as closed.
