### ISSUE TITLE
DietPi-Software | Seafile

### ISSUE THREAD

**Issue by msongz** [MichaIng/DietPi#1971]
#### Give us some formal software information:
- Software title | seafile
- Short description | File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
- GitHub URL (if available) | https://github.com/haiwen/seafile
- External URL (if available) | http://seafile.com/

**Comment by MichaIng** [comment]
Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+10
