### ISSUE TITLE
VirtualBox image dbus problem

### ISSUE THREAD

**Issue by jjit** [MichaIng/DietPi#1973]
I'm using VirtualBox image to do some test
I find out that I can't power off the vm normally and I use "shutdown" command
it says "Failed to connect to bus: No such file or directory"
so I have to do a force shutdown by VirtualBox
I did some search, it seems that it's dbus problem
so I use "sudo apt-get install dbus"
now I can power off vm normally

**Comment by MichaIng** [comment]
@jjit 
Thanks for your report.

Jep indeed, when using `shutdown` command only (which defaults to shutdown scheduled for 1 minute later) or with a defined time, `dbus` is needed . I usually use `shutdown now` or `poweroff`, which does not schedule shutdown, but does it immediately and does not need `dbus` then.

So yes, if you require to schedule shutdown after a certain time, then you need to install `dbus`. But as this is rarely needed, we will not pre-install it (including an additional permanently running background process) by default on images.

**Comment by MichaIng** [comment]
I will mark this as closed:
- For my impression installing `dbus` only for scheduled shutdown is not worth it. There are as well better methods, if somehow required conditionally, via systemd units etc.
- `dbus` will be installed automatically with desktops, as well as when using timesyncd (timedatectl) in daemon mode, as then there is more need for it, which users might expect.
- Installing `dbus` manually (as above), if required is trivial.

We will have an eye on `dbus` needs however. Especially systemd features use it increasingly and perhaps some Debian versions later we might need to pre-install it for the system to run properly.

Suggestions on how to inform users about this shutdown schedule case are welcome as well. Not sure, if an alias for the fault commands might help, to instead print user info? But `shutdown now` e.g. must not be affected 🤔.
