### ISSUE TITLE
WiFi modules turn off after reboot/shutdown | Pine A64

### ISSUE THREAD

**Issue by andrewsudz** [MichaIng/DietPi#1995]
#### Required Information:
- DietPi version	| 6.12
- Distro version	| StretchV8
- Kernel version	| 3.10.105-bsp-1.2-ayufan-118
- SBC device		| Pine A64 2GB
- Power supply used	| 5V 2A
- SDcard used		| SanDisk
##
Hello, I setup my Pine A64+ on the latest version of DietPi over Ethernet SSH. I am now trying to switch from Ethernet to onboard WiFi. I have both modules activated in dietpi-config and they are both connected.

I then run `ifdown eth0` to stop the Ethernet, unplug the ethernet cable, and switch over to the WiFi's IP on SSH and it connects. When I connect it is running on wlan0 and the Internet Test works.

I then reboot to make sure everything will work but now it won't connect. I replug my ethernet cable back in and my WiFi adapter is turned off / says Not Found. I did this a couple times now and it seems that reboots/shutdowns or ethernet cable plug ins turn off my WiFi adapter. It also forgets my WiFi setup and seems like this issue is related to midwan's https://github.com/Fourdee/DietPi/issues/1844.

Please help, thanks!
##
Also, the only way to access my Pine A64 is through SSH because their is no video output. I have tried many HDMI cables, monitors, and TVs. No success.

Other people also say this version does not support video output so I don't know if this is intentional or not. I have tried version 1.44 and the video output works on that one.

**Comment by Fourdee** [comment]
@andrewsudz 

Hi, thanks for the report 👍 

Please run the following command and paste results:
```
G_CONFIG_INJECT '8723bs' '8723bs' /etc/modules
```

If the entry did not previously exist (```[  OK  ] G_CONFIG_INJECT | Added setting 8723bs to end of file /etc/modules```), please reboot system and see if the WiFi issue after reboot is resolved.

**Comment by Fourdee** [comment]
@andrewsudz 

> Also, the only way to access my Pine A64 is through SSH because their is no video output. I have tried many HDMI cables, monitors, and TVs. No success.

Thanks for reporting this, i'll run some local testing to verify.

**Comment by Fourdee** [comment]
REF: https://github.com/Fourdee/DietPi/issues/1844

**Comment by andrewsudz** [comment]
@Fourdee

It works! Ran the code above and used the same procedure to switch to WiFi from my original post and it is staying connected after reboots and shutdowns!

Thanks so much

**Comment by Fourdee** [comment]
@andrewsudz 

Excellent, thanks for confirming resolved 👍 

I'll apply this fix to v6.13 during patching.

**Comment by Fourdee** [comment]
Completed, resolved for v6.13.
