### ISSUE TITLE
FreshRSS

### ISSUE THREAD

**Issue by msongz** [MichaIng/DietPi#1996]
## Creating a software request:

- Software title | FreshRSS
- Short description | A free, self-hostable rss reader
- GitHub URL (if available) | https://github.com/FreshRSS/FreshRSS
- External URL (if available) | http://freshrss.org
- (Official) install documentation | 
https://github.com/FreshRSS/FreshRSS#installation

**Comment by MichaIng** [comment]
@msongz 
Thanks for your request.

Jep that is possible to easily implement in comparison to feedbin.

Install steps: https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu

**Comment by MichaIng** [comment]
I will implement this with v6.14, if nothing urgent comes in between. v6.13 has already much new stuff the now needs to be tested and fine tuned, before we go on with further new features?

**Comment by msongz** [comment]
That's awesome!
Thanks for your hard work

**Comment by MichaIng** [comment]
PR is up <s>and needs testing on all distro + webserver configurations</s>: https://github.com/Fourdee/DietPi/pull/2016
- [x] **€: Testing done** 🈯️ 
- CLI install, login via `your.domain.org/freshrss`, default user `dietpi`, as well as default password, or the one set in `dietpi.txt`/first run setup.
- Cron job included to update feeds every 30 minutes
- MySQL database, as this is the recommended choice. SQLite and PostgreSQL would be possible as well.
- I am opened for suggestions which other features/pre-configurations we could add.

**Comment by Fourdee** [comment]
- 🈯️ Install test ARMv8 @MichaIng Great work 👍 
- 🈯️ Online doc https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=13918#p13918, NB: I have no experience with RSS, so i've linked the official online documentation for usage information.
- 🈯️ dietpi.com addition

**Comment by Fourdee** [comment]
@MichaIng 

Legend, works a charm , great work adding this one, thank you 👍 

I believe this is now completed? Please close as needed.

**Comment by MichaIng** [comment]
@Fourdee 
Great, jep can be closed then.
