### ISSUE TITLE
RPi Zero W |  boot loop

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2008]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4346

<s>Maybe some firmware related issue, needs replication.</s>
Obviously not related to RPi webcam, also appears with just RealVNC. Perhaps some dependency of both... Hmm there are non... desktop vs webserver dependency.

Perhaps hardware related.

**Comment by Fourdee** [comment]
@MichaIng 

I suspect fault with camera unit or loose ribbon/sunny cable.

However, found an issue during testing:
- Resolved 🈯️ https://github.com/Fourdee/DietPi/commit/a0818fd88288c4b9a55b0d45be38490db3e6cebf
![image](https://user-images.githubusercontent.com/7077026/44433100-cdbd0c00-a59c-11e8-85df-df0ebfce4fbc.png)

debugging now, then will continue with test.
![image](https://user-images.githubusercontent.com/7077026/44433184-22f91d80-a59d-11e8-9296-7ca258c7f9e4.png)

**Comment by Fourdee** [comment]
Notes:
- Us locale
- RPi webcam install only

**Comment by Fourdee** [comment]
- 🈯️ Unable to replicate with RPi3 B+.
- 🈴 Unable to test RPi Zero, as I lack the smaller ribbon cable: https://thepihut.com/products/raspberry-pi-zero-camera-adapter. Will order one once Pateron donations come in at start of month. Spent the majority (if not all and then a little more) of last months Pateron donations on rewards and shipping out competition items. No more free competitions for a while ☹️. I waffled on there a bit 🤣

**Comment by Fourdee** [comment]
🈯️ Cable on order.

**Comment by Fourdee** [comment]
Unable to replicate:
- RPi Cam Control v6.4.30: mycam@DietPi-ZeroW

I suspect faulty:
- Camera
- Cable
- Bad connection
- Sunny connector loose

Marking as closed.
