### ISSUE TITLE
OPi-PC | Add GL HW acceleration

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#201]
> Note to self: email from Helmut

**Comment by Fourdee** [comment]
Unable to test GL as my OPi-PC HDMI output has died. No signal from device.

**Comment by Fourdee** [comment]
On hold to focus on v110 completion and release.

**Comment by openmy** [comment]
hold to focus on it

**Comment by Fourdee** [comment]
My OrangePi PC HDMI output is dead. As I am unable to test this, its not possible for me to implement it at this stage.

**Comment by Fourdee** [comment]
Going to close this. 
Cant see myself buying another OPi PC board anytime soon, which i'd need to implement this request.

If anyone else has a OPi PC and wants to implement GL support, please reopen.
