### ISSUE TITLE
can't upgrade nodejs 

### ISSUE THREAD

**Issue by fmuntean** [MichaIng/DietPi#2012]
--------------------------------------------------------------------
- DietPi has encounted an error, and, is unable to continue        -
- Please create a ticket: https://github.com/Fourdee/DietPi/issues -
- Copy and paste the BLUE lines below, into the ticket             -
--------------------------------------------------------------------

#### Details:
- Date           | Tue 14 Aug 14:36:10 EDT 2018
- Bug report     | N/A
- DietPi version | v6.13
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | RPi Zero (armv6l) (index=1)
- Kernel version | #1123 Wed Jun 27 17:05:32 BST 2018
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. starting sudo dietpi-software
2. selecting to install (upgrade) nodejs

#### Expected behaviour:
should install 
#### Actual behaviour:
getting error 

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Ign:23 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en
Ign:8 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main all Packages
Ign:9 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
Ign:10 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en_GB
Ign:11 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en
Ign:12 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib armhf Packages
Ign:13 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib all Packages
Ign:14 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en_GB
Ign:15 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en
Ign:16 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free armhf Packages
Ign:17 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free all Packages
Ign:18 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en
Ign:19 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en_GB
Ign:20 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi all Packages
Ign:21 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi armhf Packages
Ign:22 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en_GB
Ign:23 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en
Ign:8 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main all Packages
Ign:9 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
Ign:10 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en_GB
Ign:11 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en
Ign:12 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib armhf Packages
Ign:13 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib all Packages
Ign:14 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en_GB
Ign:15 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en
Ign:16 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free armhf Packages
Ign:17 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free all Packages
Ign:18 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en
Ign:19 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en_GB
Ign:20 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi all Packages
Ign:21 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi armhf Packages
Ign:22 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en_GB
Ign:23 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en
Ign:8 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main all Packages
Err:9 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
  404  Not Found
Ign:10 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en_GB
Ign:11 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/main Translation-en
Ign:12 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib armhf Packages
Ign:13 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib all Packages
Ign:14 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en_GB
Ign:15 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/contrib Translation-en
Ign:16 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free armhf Packages
Ign:17 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free all Packages
Ign:18 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en
Ign:19 https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/non-free Translation-en_GB
Reading package lists...
W: The repository 'https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch Release' does not have a Release file.
E: Failed to fetch https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian/dists/stretch/main/binary-armhf/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by MichaIng** [comment]
@fmuntean 
Thanks for your report.
> https://www.mirrorservice.org/sites/raspbian.raspberrypi.org/raspbian stretch/rpi Translation-en

Ui, you did not update DietPi for some versions right? And seems the Raspbian repo maintainers did not fix their careless `sources.list` adjustment...

Please do the following to fix:
`sed -i 's|www.mirrorservice.org/sites/||g' /etc/apt/sources.list`

**Comment by fmuntean** [comment]
I am using: 
───────────────────────────────────────
 DietPi     | 20:20 | Tue 14/08/18
 ───────────────────────────────────────
 v6.13      | RPi Zero (armv6l)
 ───────────────────────────────────────
I have run the command and I still get following errors:

pi@DietPi:~ $ sudo apt-get update
Ign:1 http://download.webmin.com/download/repository sarge InRelease
Err:2 https://raspbian.raspberrypi.org/raspbian stretch InRelease
  Failed to connect to raspbian.raspberrypi.org port 443: Connection refused
Hit:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
Hit:4 http://repo.mosquitto.org/debian jessie InRelease
Hit:5 http://download.webmin.com/download/repository sarge Release
Hit:6 https://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
W: Failed to fetch https://raspbian.raspberrypi.org/raspbian/dists/stretch/InRelease  Failed to connect to raspbian.raspberrypi.org port 443: Connection refused
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by fmuntean** [comment]
running DietPI update gives me this:

 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Checking for DietPi updates

[ INFO ] DietPi-Update | Checking Mirror : https://dietpi.com/downloads/dietpi-update_mirror/master/server_version-6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0      4      0  0:00:01  0:00:01 --:--:--     4
[  OK  ] DietPi-Update | Using update server: https://dietpi.com/downloads/dietpi-update_mirror/master/server_version-6

[  OK  ] DietPi-Update | No updates required, your DietPi installation is up to date.

[ INFO ] DietPi-Update | Current Version : 6.13
[ INFO ] DietPi-Update | Server Version  : 6.13

It seems I am running latest DietPI

**Comment by MichaIng** [comment]
@fmuntean 
Ah sorry, forgot that raspbian.raspberrypi.org is not available via HTTPS. Please try:
`sed -i 's|https://raspbian.raspberrypi.org|http://raspbian.raspberrypi.org|g' /etc/apt/sources.list`
Then it should work.

**Comment by fmuntean** [comment]
Thank You for your fast help.
This fixed the apt-get update issue.
