### ISSUE TITLE
RPi | Compile realtime Kernel (Fully preemptible RT) + installation option.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#202]
Done. (not for RPI v3)
RT kernel can be installed with:

```
wget http://dietpi.com/downloads/binaries/rpi/DietPi-RPi-4.1.17-rt17.zip -O package.zip
unzip -o package.zip -d /
rm package.zip
```

**Comment by Fourdee** [comment]
Add Kernel "hotswap" option to ```DietPi-Config```
+ Ultra lightweight kernel

**Comment by k-plan** [comment]
Hi Dan,
will this option also be available on  Odroid-C1+ ?

As far I can see, it exist also a full preemptive kernel 3.10.75-rtxx on Odroid-C1 :
[https://blog.georgmill.de/2015/09/03/realtime-preemtive-kernel-sources-3-10-80-rt88-for-odroid-c1-on-github/](url)
[https://blog.georgmill.de/2015/05/27/full-preemptive-kernel-3-10-75-rt80-on-odroid-c1/](url)

**Comment by Fourdee** [comment]
@k-plan 
I wasn't planning on it as the Odroid kernel we use is built and maintained by Meveric via apt-get upgrade. 

I've not compiled any odroid kernels yet, so I will do some research and look through the links you provided :+1: .

**Comment by k-plan** [comment]
Hi Dan,
I personally see this at an outside estimate option for Kernel "hotswap" to DietPi-Config, not more at the moment.
I don't really need it, but notice in Software selection on DietPi, one main focus is audio/multimedia. So for this guys, it may be useful. Only suggest this option, because I do some research, in which case a full preemptive RT kernel is needed. Didn't know this possibility before you post it here. But i notice, it is  on Milestone v110 for now.

Prefer to see same bugfixes, better localization support and more productive Software as Cloudshell, Pi-Hole, ...

**Comment by Fourdee** [comment]
@k-plan

> Prefer to see same bugfixes, better localization support and more productive Software as Cloudshell, Pi-Hole, ...

If you can link the Git tickets that contain the items you are refering to, I will look into their priority. If the ticket does not exist, please create one.

**Comment by Fourdee** [comment]
Pushed back menu integration to focus on bug fixes for v110.

**Comment by rhkean** [comment]
I compiled a 4.2 kernel for my XU4 this weekend, but it still needs some work.  
- The kernel doesn't report the hardware like meverick's 3.10 kernel does (affects dietpi's ability to detect the correct hardware) 
- the base configuration didn't include any cpu governors except 'performance'
- uas module (the reason I experimented in the 1st place) was not enabled
- kernel/initrd/uInitrd installation wasn't as smooth as it could be (and if you don't properly configure the boot.ini file, you better have another boot image available to fix it)

all in all, it booted and I got to see my 12TB of usb drives running on an SBC with UsbAttachedScsi speeds, but I didn't get the feeling that it was production ready yet.  (I also didn't see a C2 branch on tobetter's github page:  https://github.com/tobetter/linux )

**Comment by Fourdee** [comment]
@rhkean 
Hardkernel has a 4.2-rc1 kernel branch for the XU4, is this the one you tried? https://github.com/hardkernel/linux/tree/odroidxu4-v4.2-rc1

I must admit, thats one benefit of the RPi, they are always developing for the latest kernel. Although, they probably have 20+ staff members working on it, and a bigger comminuty.

**Comment by rhkean** [comment]
No, I haven't tried that one yet.  I used the one referenced on [Odroid dokuwiki](http://odroid.com/dokuwiki/doku.php?id=en:odroid-xu4)

it's found at [tobetter's github repository](https://github.com/tobetter/linux)

I found the hardkernel repository late last night.  The last check-in date on both repos are within a day of each other, so I'm betting they're pretty similar, but I'm going to do a file compare on them and try the hardkernel one today or tomorrow.  (preliminary scan shows that the hardkernel branch is also missing the odroid files in the src/linux/arch/arm/mach-exynos folder, though. (That's where the /proc/cpuinfo data comes from)

**Comment by rhkean** [comment]
It's worth spending the time on, though...

Did you see my post under [General Discussion on Fuzon](http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=357)?

**Comment by Fourdee** [comment]
@k-plan @rhkean 
Just doing some late spring cleaning. As the original item in this ticket was completed in Feb, will mark this as closed.

Rob, if you want to explore the 4.x kernel for XU4 with uas support. Please create a new ticket for this :+1: 

K-Plan,
Unless we get asked by our users for a RT kernel for Odroid devices, there isn't much pointing doing it. Mainly due to the constant Odroid kernel updates on a daily/weekly basis that would render the RT kernel out of date, very quickly.

**Comment by rhkean** [comment]
I agree with your analysis.
