### ISSUE TITLE
DietPi-Survey | SSH key: Change IP to sub domain name (after Cloudflare setup)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2022]
since 10AM on 18th Aug
```
Aug 19 01:19:40 DietPi sshd[28504]: Accepted password for dietpi-survey from 82.
7.94.230 port 3223 ssh2
Aug 19 01:19:40 DietPi sshd[28504]: pam_unix(sshd:session): session opened for u
ser dietpi-survey by (uid=0)
Aug 19 01:19:40 DietPi sshd[28504]: pam_unix(sshd:session): session closed for u
ser dietpi-survey
root@DietPi:~# ls -lha /home/dietpi-survey/
total 2.2M
drwxr-x--x 5 root          root          920K Aug  4 07:03 .
drwxr-xr-x 4 root          root          4.0K Apr 27 13:11 ..
drwx------ 3 root          root          4.0K Jun 17 01:23 backup
d-wx------ 3 dietpi-survey dietpi-survey  20K Aug 15 18:12 bugreport
d-wx------ 2 dietpi-survey dietpi-survey 1.3M Aug 18 10:16 survey
```

**Comment by Fourdee** [comment]
Cloudflare issue?
```
root@DietPi:~# curl --connect-timeout 4 --retry 1 --retry-delay 4 -T file sftp://"$SFTP_USER":"$SFTP_PASS"@"$SFTP_ADDR"/survey/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (28) Connection timed out after 4001 milliseconds
```

Via IP:
```
root@DietPi:~# curl --connect-timeout 4 --retry 1 --retry-delay 4 -T file sftp://"$SFTP_USER":"$SFTP_PASS"@185.101.93.93/survey/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (51) SSL peer certificate or SSH remote key was not OK
```

**Comment by Fourdee** [comment]
```
G_CONFIG_INJECT '185.xxx.xxx.xxx ' '185.xxx.xxx.xxx ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE6aw3r6aOEqendNu376iiCHr9tGBIWPgfrLkzjXjEsHGyVSUFNnZt6pftrDeK7UX\+qX4FxOwQlugG4fymOHbimRCFiv6cf7VpYg1Ednquq9TLb7/cIIbX8a6AuRmX4fjdGuqwmBq3OG7ZksFcYEFKt5U4mAJIaL8hXiM2iXjgY02LqiQY/QWATsHI4ie9ZOnwrQE\+Rr6mASN1BVFuIgyHIbwX54jsFSnZ/7CdBMkuAd9B8JkxppWVYpYIFHE9oWNfjh/epdK8yv9Oo6r0w5Rb\+4qaAc5g\+RAaknHeV6Gp75d2lxBdCm5XknKKbGma2\+/DfoE8WZTSgzXrYcRlStYN' /root/.ssh/known_hosts
```

🈯️ 
```
root@DietPi:~# curl --connect-timeout 4 --retry 1 --retry-delay 4 -T file sftp://"$SFTP_USER":"$SFTP_PASS"@185.101.93.93/survey/                                  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2    0     0  100     2      0      2  0:00:01 --:--:--  0:00:01     2
100     2    0     0  100     2      0      2  0:00:01 --:--:--  0:00:01     2
```

**Comment by Fourdee** [comment]
RTFM Fourdee 🤣 :
https://support.cloudflare.com/hc/en-us/articles/200169346-Using-FTP-with-Cloudflare-

Done:
![image](https://user-images.githubusercontent.com/7077026/44304309-86dad680-a350-11e8-9eec-e45f56e589b5.png)


```
;; A Records (IPv4 addresses)
sftp.dietpi.com.	120	IN	A	185.xxx
```

Waiting for TTL/records/DNS cache to update.

Unable to get this working. Still rejects sftp on both dietpi.com and sftp.dietpi.com. 

Will set manual IP for survey uploads.

**Comment by Fourdee** [comment]
🈯️ Resolved for v6.14. 
```
[  OK  ] DietPi-Survey | Successfully sent survey data
```

**Comment by MichaIng** [comment]
@Fourdee 
Hmm, on to long term it would be nice to stay with domain for SFTP connection actually, so also shifting the server does not break connectivity for older version. `sftp.dietpi.com` would be indeed nice, or to be more general with this, as SFTP uses SSH connection+port `ssh.dietpi.com`.

No idea how sub domains are handled from provider + cloudflare, maybe forwarding of this needs to be enabled on provider side and/or the full sub domain needs to be added to the cloudflare exclusions?

€: Got it working. Of course the sub domain needs to be added to `/root/.ssh/known_hosts`, forgot that as well first 🤣. So after changing `dietpi.com` key there to the desired sub domain and add this as excluded record to cloudflare DNS, upload works fine.
Don't know if we want to add/change this now again, but actually it would not hurt, since raw IP will still always work. We could even clean up `known_hosts`, removing old dietpi.com and raw IP entry.

**Comment by Fourdee** [comment]
@MichaIng 

> Got it working. Of course the sub domain needs to be added to /root/.ssh/known_hosts, forgot that as well first 🤣. So after changing dietpi.com key there to the desired sub domain and add this as excluded record to cloudflare DNS, upload works fine.
Don't know if we want to add/change this now again, but actually it would not hurt, since raw IP will still always work. We could even clean up known_hosts, removing old dietpi.com and raw IP entry.

Legend 👍 

Yep, if it works, we should use the domain name and remove all previous keys (if safe to do so) during patch?

**Comment by Fourdee** [comment]
```
[ .... ] DietPi-Survey | (1/5) Testing connection to ssh.dietpi.com, please wait[  OK  ] DietPi-Survey | Connection test: ssh.dietpi.com
[  OK  ] DietPi-Survey | Successfully sent survey data
[ INFO ] DietPi-Update | Current Version : 6.15
[ INFO ] DietPi-Update | Server Version  : 6.15
```

Completed, nice one @MichaIng 👍
