### ISSUE TITLE
DietPi-Software | Bazarr

### ISSUE THREAD

**Issue by DiogoAbu** [MichaIng/DietPi#2045]
#### Give us some formal software information:
- Software title | Bazarr
- Short description | Manage and download subtitles, companion to Sonarr and Radarr.
- GitHub URL (if available) | https://github.com/morpheus65535/bazarr
- (Official) install documentation | https://github.com/morpheus65535/bazarr/wiki/Installation#linux

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
- It needs git and jpeg support, and python with pip requirements

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
- Yes, I could help out with this

**Comment by Fourdee** [comment]
@DiogoAbu 

Hi,

Many thanks for the request, looks good 👍 

We'll implement when we can.

**Comment by MichaIng** [comment]
Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+13

**Comment by MichaIng** [comment]
Debugging install on ARM: https://github.com/MichaIng/DietPi/issues/2645
- Good to know which APT packages and/or Python modules are required to successfully build all further requirements for bazarr.

**Comment by MichaIng** [comment]
Started with implementation: #3796
**EDIT: Done, including Sonarr and Radarr auto-configuration, ready for testing.**
