### ISSUE TITLE
DietPi-Drive_Manager | Allow mounting drive to existing directory

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2056]
#### Is your feature request related to a problem? Please describe:

- DietPi-Drive_Manager does not allow to mount a drive to an existing directory.
- This is no issue, as long as drives are always unmounted via drive_manager, but if they were unplugged accidentally or unmounted via `umount` command, they can't be remounted via drive_manager because of this.

#### Describe the solution you'd like:

- Conditionally allow to ignore and mount the drive, even that mount point directory exists.
- Only if directory is not a mount point of any other mounted drive, otherwise tell user the owning drive.
- If directory is empty, allow to simply ignore and mount.
- If directory is not empty, throw a bid warning, but allow user to backup existing directory and mount drive. 

#### Describe alternatives you've considered:

- Safety should be most important here, thus assure clear user info, especially in case of non-empty mount target.
- But the current situation leads to user either need to manually remove the folder or manually mount the drive, which is not handy.

#### Additional context:

- Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4589
- **Thanks @thisisdanni for reporting the issue!**

**Comment by Fourdee** [comment]
@MichaIng 

Yep, reason for doing it this way is prevent users mounting multiple/different drives to a previous mount point (and its sub directories).

If the directory exists, it must of had a purpose, and, the user should be aware of that.

> If directory is empty, allow to simply ignore and mount.

Could cause an issue if:
- User had a mounted drive, previously at that location, but it is not plugged in
- User accidentally mounts the wrong drive
- Expected Data on mount location is incorrect. 
- User had DietPi userdata on the other drive, services now fail to start.

> allow to ignore and mount the drive, even that mount point directory exists.

Yep, agree 👍 Probably the best approach I believe.

---

If directory is empty:
- Prompt/warn user, this may of been used for another mount, however, allow for override.

If directory contains data:
- Deny mount.

**Comment by Fourdee** [comment]
Testing passed 🈯️ 
Completed.
