### ISSUE TITLE
Connection Test fails on NanoPi K1 Plus after initial update.

### ISSUE THREAD

**Issue by TedMichalik** [MichaIng/DietPi#2063]
## Creating a bug report/issue:
Image DietPi_v6.7_NanoPiK1Plus-ARMv8-Stretch.img booted successfully. Initial update ran OK, but after reboot the connection test fails:
ERROR: The certificate of ‘deb.debian.org’ is not trusted.
ERROR: The certificate of ‘deb.debian.org’ is not yet activated.

#### Required Information:
- DietPi version	| 6.14
- Distro version	| stretch 9.5
- Kernel version	| Linux DietPi 4.16.0-rc6 #19 SMP Fri Apr 20 14:25:42 CST 2018 aarch64 GNU/Linux
- SBC device		| NanoPi K1 Plus (aarch64)
- Power supply used	| 5.1V 2.1A Apple
- SDcard used		| SanDisk edge

#### Additional Information (if applicable):
- Can this issue be replicated on a fresh installation of DietPi? Yes
- Bug report sent, reference code: 752c8a95-9e50-4d48-a5cb-a7d903685e05

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:
DietPi-Software: Connection test: https://deb.debian.org/debian/
 - Exit code: 5
 - DietPi version: v6.14 | HW_MODEL:67 | HW_ARCH:3 | DISTRO:4
 - Image creator: DietPi Core Team
 - Pre-image: FriendlyARM

Log file contents:
Spider mode enabled. Check if remote file exists.
--2016-11-03 17:30:53--  https://deb.debian.org/debian/
Resolving deb.debian.org (deb.debian.org)... 5.153.231.4, 149.20.4.15,
128.31.0.62, ...
Connecting to deb.debian.org (deb.debian.org)|5.153.231.4|:443... connected.
ERROR: The certificate of ‘deb.debian.org’ is not trusted.
ERROR: The certificate of ‘deb.debian.org’ is not yet activated.
The certificate has not yet been activated

**Comment by TedMichalik** [comment]
Another attempt:

#### Details:
- Date           | Thu  3 Nov 17:24:59 GMT 2016
- Bug report     | N/A
- DietPi version | v6.14
- Img creator    | DietPi Core Team
- Pre-image      | FriendlyARM
- SBC device     | NanoPi K1 Plus (aarch64) (index=67)
- Kernel version | #19 SMP Fri Apr 20 14:25:42 CST 2018
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Ign:1 https://deb.debian.org/debian stretch InRelease
Ign:2 https://deb.debian.org/debian stretch-updates InRelease
Ign:3 https://deb.debian.org/debian-security stretch/updates InRelease
Ign:4 https://deb.debian.org/debian stretch-backports InRelease
Err:5 https://deb.debian.org/debian stretch Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Err:6 https://deb.debian.org/debian stretch-updates Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Err:7 https://deb.debian.org/debian-security stretch/updates Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Err:8 https://deb.debian.org/debian stretch-backports Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists...
E: The repository 'https://deb.debian.org/debian stretch Release' does no longer have a Release file.
E: The repository 'https://deb.debian.org/debian stretch-updates Release' does no longer have a Release file.
E: The repository 'https://deb.debian.org/debian-security stretch/updates Release' does no longer have a Release file.
E: The repository 'https://deb.debian.org/debian stretch-backports Release' does no longer have a Release file.

**Comment by Fourdee** [comment]
@TedMichalik 

Thanks for the report 👍 

Apologies for this issue, please see below link for reason + solution:
https://github.com/Fourdee/DietPi/issues/2061#issuecomment-419623473
