### ISSUE TITLE
Dietpi-Cloudshell Issue

### ISSUE THREAD

**Issue by docgalaxyblock** [MichaIng/DietPi#2066]
Hi Fourdee
Bugreport id: f356d26d-a01a-4490-98d9-24eed509a7b0
I just made fresh Dietpi installation on my CS2, because of a corrupted Partition.

The Dietpi cloudshell script has some issues displaying the correct amount of ram
![20180911_234937](https://user-images.githubusercontent.com/21227087/45389894-9d0d4700-b61d-11e8-994c-d5e8fb389487.jpg)
It was also at my last install, but there is thought the reason could be a broken Uninstaller of zram.

Sometimes the Screen just goes blank but the backlight is still staying on.

Greetings from Germany ^^

**Comment by Fourdee** [comment]
@potter-91 

Many thanks for the report 👍 

I'll take a look.

**Comment by Fourdee** [comment]
- Confirmed bug with ```free -m``` result. Appears cached result has moved back 1 ```awk```
- ```free -m``` also excludes the cache now, in usage result, but not in the free result!:
```
root@DietPi:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           1727          92        1004           7         630        1607
Swap:           320           0         320
```
- Also bug with running on same screen
![image](https://user-images.githubusercontent.com/7077026/45409456-1d0bcf00-b667-11e8-954f-79f02b77342b.png)

**Comment by Fourdee** [comment]
@potter-91 

> Sometimes the Screen just goes blank but the backlight is still staying on.

Sounds like screen-blanking not being set, i'll have this applied during init.

**Comment by Fourdee** [comment]
RAM and a few other issues resolved.

@potter-91 

In regards to the screen blanking (i'am assuming) this should also be resolved, however, if problems persist, please let us know so we can investigate further.

v6.15 (with this fix) will be released today.

**Comment by docgalaxyblock** [comment]
Hi
Tonight the backlight stays on
