### ISSUE TITLE
Samba/NFS | Support userdata directory with permissions that allow apps to function?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2067]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4595#p14233
- Does the issue occur, if the server (Windows?) file system (NTFS?) does not support permissions?
- Is it somehow possible via cifs mount options e.g. to adjust owner and permissions for the whole network mount, just client-side, e.g. to dietpi:dietpi 775 to allow Sonarr etc users r/w access?
- Could this be a similar issue for other network mounts and is there a similar solution possible?

**Comment by Fourdee** [comment]
@MichaIng 

Samba does not support setting remote permissions with NTFS volume (linux Samba server with NTFS drive):
```
root@DietPi:/mnt/samba# chown -R dietpi:dietpi Video
root@DietPi:/mnt/samba# ls -lha
total 4.0K
drwxr-xr-x 2 root root    0 Sep 11 09:35 .
drwxr-xr-x 8 root root 4.0K Jul 23 21:53 ..
drwxr-xr-x 2 root root    0 Dec 12  2016 #Backups
drwxr-xr-x 2 root root    0 Sep 11 13:43 downloads
drwxr-xr-x 2 root root    0 Jul 21 22:14 Music
drwxr-xr-x 2 root root    0 Jul 21 22:14 Pictures
drwxr-xr-x 2 root root    0 Jul 21 22:21 _PRE_BK
drwxr-xr-x 2 root root    0 Jul 21 22:14 Video
```

Same with EXT4:
```
root@DietPi:/mnt/samba2# chown -R dietpi:dietpi Video
root@DietPi:/mnt/samba2# ls -lha
total 4.0K
drwxr-xr-x 2 root root    0 Sep 10 12:17 .
drwxr-xr-x 9 root root 4.0K Sep 12 10:03 ..
drwxr-xr-x 2 root root    0 Sep 10 12:17 downloads
drwxr-xr-x 2 root root    0 Sep 10 12:17 Music
drwxr-xr-x 2 root root    0 Sep 10 12:17 Pictures
drwxr-xr-x 2 root root    0 Sep 10 12:17 Video
```

Hmm, need to research and confirm this is as Samba intended.

Ok, I believe this is per design, as setting a user/group permissions on a remote system, would require the remote system to also have that user/group locally.
Samba appears to mount with the creds that the server has setup (eg: ```dietpi```), past that point, permissions cannot be changed on the filesystem.
You can however, change the following settings in ```/etc/samba/smb.conf```, to tweak the file/folder mask once connected:
```
        create mask = 0775
        directory mask = 0775
```

As far as I can tell, setting file/folder permissions on a remote samba server is not possible, by design. Either that, or there is some magical Samba server setting, which I'am unaware of.

**Comment by Fourdee** [comment]
non-root applications are unable to access ```/mnt/samba``` (eg: radarr, sonarr), is it possible to:
- Mount Samba with nobody:dietpi? Allowing access?
- Provide info for the user to change run-level user back to ```root``` for required applications? (the whole point of doing this was to improve security, with lack of Samba access being the downside, due to inability to set folder specific permissions)

**Comment by MichaIng** [comment]
@Fourdee 
Check: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4595&start=10#p14439
- Works well here 😀.
€: Works as well for user, check forum. 
_________________
Btw: On NFS mounts, permissions are directly taken from NFS server. Changing them on client mount, changes them directly on server as well.
Only issue might be, the NFS server share does not support permissions. But there is nothing we could do about that, as I could not find settings to globally set/change permissions on the mount. Not sure who actually has which access to a fs without permission support? root only, or the user that mounted the drive? Needs testing with NTFS NFS share.

**Comment by Fourdee** [comment]
@MichaIng 

> dietpi:dietpi 770 should allow r/w access for Sonarr and such, as these software titles run as their own user, but as dietpi group.

Legend 👍 

Yep, I'll send a commit to make the changes, will run some tests aswell.

**Comment by Fourdee** [comment]
Mounts root with:
```
					G_ERROR_HANDLER_INFO_ONLY=1 G_RUN_CMD mount -t cifs -o username="$samba_clientuser",password="$samba_clientpassword",uid=dietpi,gid=dietpi,file_mode=0770,dir_mode=0770,vers=${acifs_versions[$i]} //"$samba_clientname"/"$samba_clientshare" "$samba_fp_mount_target"
```

umount and remount required to apply 😕 

🈯️ Does work, forgot to add to initial mount lol

**Comment by Fourdee** [comment]
Testing required:
- Install sonarr/radarr
- Set Samba as userdata dir

DietPi-Drive_Manager
- Userdata move is disabled for network drives.

DietPi-Software
- 🈯️ Can set a custom location, and/or, list mounted drives (including samba)

---

🈯️ Works fine.
```
root@DietPi:~# ls -lha /mnt/samba/dietpi_userdata/
total 0
drwxrwx--- 2 dietpi dietpi 0 Sep 18 14:18 .
drwxrwx--- 2 dietpi dietpi 0 Sep 18 14:50 ..
drwxrwx--- 2 dietpi dietpi 0 Sep  8 09:44 downloads
drwxrwx--- 2 dietpi dietpi 0 Sep  8 09:44 Music
drwxrwx--- 2 dietpi dietpi 0 Sep  8 09:44 Pictures
drwxrwx--- 2 dietpi dietpi 0 Sep 18 14:49 radarr
drwxrwx--- 2 dietpi dietpi 0 Sep 18 14:50 sonarr
drwxrwx--- 2 dietpi dietpi 0 Sep  8 09:44 Video

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: status

[  OK  ] DietPi-Services | sonarr       active (running) since Tue 2018-09-18 14:51:04 BST; 5s ago
[  OK  ] DietPi-Services | radarr       active (running) since Tue 2018-09-18 14:51:04 BST; 5s ago
[  OK  ] DietPi-Services | cron active (running) since Tue 2018-09-18 14:51:04 BST; 5s ago
[  OK  ] DietPi-Services | ssh  active (running) since Tue 2018-09-18 11:51:37 BST; 2h 59min ago
[  OK  ] DietPi-Services | dietpi-preboot       active (exited) since Tue 2018-09-18 11:51:37 BST; 2h 59min ago
[  OK  ] DietPi-Services | dietpi-boot  active (exited) since Tue 2018-09-18 11:51:42 BST; 2h 59min ago
[  OK  ] DietPi-Services | dietpi-postboot      active (exited) since Tue 2018-09-18 11:51:42 BST; 2h 59min ago
```

**Comment by Fourdee** [comment]
Offtopic issue with RockPro64:
- 🈯️ Resolved with https://github.com/Fourdee/DietPi/commit/f83c35d8ad7ba28e40f795b1d51bd4c1678919bd
![image](https://user-images.githubusercontent.com/7077026/45692013-b4828d80-bb51-11e8-8f37-235580431007.png)

http://www.linux-mtd.infradead.org/doc/general.html

> MTD subsystem (stands for Memory Technology Devices) provides an abstraction layer for raw flash devices. It makes it possible to use the same API when working with different flash types and technologies, e.g. NAND, OneNAND, NOR, AG-AND, ECC'd NOR, etc.
MTD subsystem does not deal with block devices like MMC, eMMC, SD, CompactFlash, etc. These devices are not raw flashes but they have a Flash Translation layer inside, which makes them look like block devices. 

I'll disable this from scrape for now.

```
root@DietPi:~# lsblk -nro NAME
mtdblock0
mtdblock1
mtdblock2
```

**Comment by Fourdee** [comment]
- 🈯️ Samba is completed
- NFS, needs research/testing before we/if implement.

**Comment by Fourdee** [comment]
🈯️ NFS supports permissions, at least on a Linux share:
```
root@DietPi:~# ls -lha /mnt/nfs_client/
total 32K
drwxrwxr-x 8 dietpi   dietpi   4.0K Sep 30 18:49 .
drwxr-xr-x 7 root     root     4.0K Sep 30 19:30 ..
drwxrwxr-x 2 dietpi   dietpi   4.0K Sep 19 14:12 downloads
drwxrwxr-x 2 dietpi   dietpi   4.0K Sep 19 14:12 Music
drwxrwx--- 6 statd         112 4.0K Sep 30 19:30 mysql
drwxrwx--- 5 www-data www-data 4.0K Sep 30 18:55 nextcloud_data
drwxrwxr-x 2 dietpi   dietpi   4.0K Sep 19 14:12 Pictures
drwxrwxr-x 2 dietpi   dietpi   4.0K Sep 19 14:12 Video
```

**Comment by Fourdee** [comment]
🈴 Samba does not
```
root@DietPi:~# ls -lha /mnt/samba
total 4.0K
drwxrwx--- 2 dietpi dietpi    0 Sep 30 18:49 .
drwxr-xr-x 7 root   root   4.0K Sep 30 19:35 ..
drwxrwx--- 2 dietpi dietpi    0 Sep 19 14:12 downloads
drwxrwx--- 2 dietpi dietpi    0 Sep 19 14:12 Music
drwxrwx--- 2 dietpi dietpi    0 Sep 30 19:35 mysql
drwxrwx--- 2 dietpi dietpi    0 Sep 30 18:55 nextcloud_data
drwxrwx--- 2 dietpi dietpi    0 Sep 19 14:12 Pictures
drwxrwx--- 2 dietpi dietpi    0 Sep 19 14:12 Video
```

However, now mounts with ```dietpi``` user and group, so in theory, userdata applications "should" work, however, this needs to be manually set/tweaked by the user, as it will fail the permissions test during userdata move as of v6.17, which is now required.

Completed.

**Comment by Dr0bac** [comment]
@Fourdee i have the same problem with radarr not importing movies but my hdd is external hdd connected directly to rpi3, it says in radarr logs:"
Couldn't import movie /mnt/dietpi_userdata/downloads/Avatar: Acess to the path "/mnt/dietpi_userdata/Plex/Movies/Avatar" is denied..
Then i changed user of /mnt/dietpi_userdata/Plex/Movies to radarr:root and now in radarr logs i get
Couldn't import movie /mnt/dietpi_userdata/downloads/Avatar: Acess to the path is denied..
I guess download folder is now the problem..i don't know should i change users of that folder.
I tried adding radarr user to root group but nothing changed
usermod -a -G root radarr
All my folders in Plex folders have permissions drwxrwxr-x and plex was main user, so i can delete movies from plex menu..

**Comment by MichaIng** [comment]
@Dr0bac 
Thanks for your report. But this is a different issue. So not NFS or Samba is the problem in your case, but plex+radarr cross access.

So I guess, the files in flex folder are owned by plex:plex?
To allow access to most other software, installed via dietpi-software, you need to add radarr user to plex group and add plex as well to dietpi group, to allow access of plex to download and other folders as well.

I link the issue to: https://github.com/Fourdee/DietPi/issues/350#issuecomment-423763518
- Fits better there. Like transmission, plexmediaserver is a APT install that brings its own service. We can make the service run as `dietpi` group, which allows access to dietpi_userdata/*, and hope that this also leads to files being created with dietpi group. Or we add a `usermod -a -G` step to dietpi-software to add each software run user to each others group, where cross access is needed. This prevents the need to edit the APT installed service file and allows APT to patch it in case.

**Comment by Dr0bac** [comment]
@Michalng
 Yes, different problem, but it started recently i guess when 6.14 update was installed.. no it's not plex:plex.. it's plex:root.. and it worked like that perfectly last 6 months..so i guess plex and radarr are in root group? So if radarr don't have permissions to download folder i must add it to dietpi group, not root group?

**Comment by MichaIng** [comment]
@Dr0bac 
> plex:root

🤔 Okay this is bad. Hmm I would never want to add software run users to root group actually. Bad repo package default then... I hope for our fix in DietPi install script we can change it the way that files are created as plex:plex or plex:dietpi.
So yeah, in this case you have no other chance then adding radarr user to root group for now.

> i guess when 6.14 update was installed

It should have worked until v6.12: https://github.com/Fourdee/DietPi/pull/1938
- We changed most software titles run with their own users instead of all as root, for security reasons.
- But indeed that made cross software access quite complicated.

> So if radarr don't have permissions to download folder i must add it to dietpi group, not root group?

Radarr does already run as dietpi group, so should have access to download folder actually.

Verify:
`cat /etc/systemd/system/radarr.service`
- Should show User=radarr and Group=dietpi

`ls -al /mnt/dietpi_userdata/downloads`
- Should be `dietpi:dietpi 775`

With radarr should have access 🤔.

**Comment by Dr0bac** [comment]
@MichaIng
It's my fault that media folders are plex:root. I saw somewhere i guess on reddit that plex must be owner of media files so i can delete movies with it..also plex plugin subzero for subtitles can't work without changing permissions..
I tried first command and i got like you said
User=radarr
Group=dietpi
After second command i saw that download folder owner is dietpi:dietpi, but downloaded movie folders are under root:root.. and permissions are different..maybe that is the reason..who create that folders, transmission or radarr?
![](https://i.imgur.com/vRqMITY.jpg)

**Comment by Dr0bac** [comment]
@MichaIng i don't know why i can't tag you manually..anyway i did what you asked me to do..

**Comment by MichaIng** [comment]
@Dr0bac
The folders should be created by transmission then. It has currently the same issue as plex. Check this: https://github.com/Fourdee/DietPi/issues/350#issuecomment-423763518

Please try: 
Replace our custom transmission service (/etc/systemd/system/transmission-daemon.service) with the one provided in the link (this is package default), but add Group=dietpi beneath User=debian-transmission.

Then adjust transmission settings to create new downloads with 770 (or if you need 775) permissions: 
`G_CONFIG_INJECT '\"umask\":' '\"umask\": 7,' /etc/transmission-daemon/settings.json` should do it, respectively with  value 2 instead of 7.

That should lead to transmission creating files as debian-transmission:dietpi with 770/775 permissions, allow access for all other software (in dietpi group) and transmission being able to access other dietpi group files.

If downloads by transmission are not created as dietpi group, then it would be needed to add plex and radarr to debian-transmission group:
`usermod -a -G debian-transmission radarr plex`

The working solution well be implemented to DietPi v6.17 :).
____
Yeah not sure why the first tag didn't work, however the second did. I edited my tag in your first post, now or does as well, even I can't see a change :thinking:.

**Comment by Dr0bac** [comment]
@MichaIng thanks for your suport, but i don't see any link.. do you want me to add two lines in current transmission service file or i need to change that service file with the new one and add those lines..
But i can wait new dietpi update if you guys gonna fix it, it's not big deal..
Thanks

**Comment by MichaIng** [comment]
@Dr0bac 
Whole steps:
```
cat << _EOF_ > /etc/systemd/system/transmission-daemon.service
[Unit]
Description=Transmission BitTorrent Daemon
After=network.target

[Service]
User=debian-transmission
Group=dietpi
Type=notify
ExecStart=/usr/bin/transmission-daemon -f --log-error
ExecStop=/bin/kill -s STOP $MAINPID
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
_EOF_
G_CONFIG_INJECT '\"umask\":' '\"umask\": 7,' /etc/transmission-daemon/settings.json
```
€: Ah, when you already used transmission, the config file will be owned by root, thus the following is needed to start the daemon with above:
`chown debian-transmission:debian-transmission /etc/transmission-daemon/settings.json`

I will also test now myself 🙂.
🈯️ Jep, now files are created correctly. We will add the group via:
```
cat << _EOF_ > /etc/systemd/system/transmission-daemon.service.d/dietpi-group.conf
[Service]
Group=dietpi
_EOF_
```
This allows APT in case to update the local config file.

**Comment by MichaIng** [comment]
PR up for changing Plex + Transmission run as group "dietpi": https://github.com/Fourdee/DietPi/pull/2117

**Comment by Dr0bac** [comment]
@MichaIng 
Hey thanks for fixing that permission bug in new dietpi update..now movies are imported nice in plex folder..after update i changed plex movies folders to be plex:dietpi, and also in radarr permission setings i edited so new movies are created with plex:dietpi..previously
It was plex:root

but i have another issue now..
For few days i noticed that subzero plugin that download subtitles for plex did not download subtitles for recent movies i downloaded.si i went to putty to see permissions..and something is not right..radarr is setting strange permissions..look at pictures
![](https://i.imgur.com/q35oNUp.png)

![](https://i.imgur.com/CU6O8Ix.png)

![](https://i.imgur.com/SzzI69s.png)


New movie folders are created as radarr:dietpi and movies are moved as root:dietpi

**Comment by MichaIng** [comment]
@Dr0bac 
I am not 100% how all those software works together, which one initially creates the folders and/or adjusts permissions on existing files/folders, but it is expected that radarr runs as and creates/imports files/folders with `radarr:dietpi`.

The contained video file user/permissions are from the downloader (Transmission in your case, right?), I guess and radarr does only import those without changing permissions (on file).
**€: Hmm but yours is root:dietpi 🤔. This was the old behaviour, if I remember right, did you adjust the `transmission-daemon.service` as mentioned above (?) with:**
```
User=debian-transmission
Group=dietpi
```

More precisely, thinking about this:
- Transmission downloads the movies to dietpi_userdata/downloads dir and is responsible for those permissions.
- Radarr then imports those files, create related dirs in dietpi_userdata/Video (thus radarr:dietpi) and moves/sorts the movies into those folders without touching permissions. It can do this, as it runs as dietpi group which has r/w permissions on the movie files.

Plex then can adjust permissions when importing/touching movies, but this should not be needed. Plex runs as dietpi group as well, thus has full permissions.

Do you run in any permission related issues or just wonder about the different ones on the Video dir?
- It would be a bid more consistent/save, if we could convince sonarr/radarr/lidarr to create the folders with 77X permissions, so other software can theoretically rename/reorder them, if such features are available.
- Is 0644/0755 and enabled "Set Permissions" default in Plex? Would be as well here failsafe if we could pre-configure this to be 0664/0775 instead for the same reason and/or disable "Set Permissions" by default to not have again more permissions/owner patchwork as already with all those software titles interacting 😉.

**Comment by Dr0bac** [comment]
@MichaIng that first picture with permissions is from radarr settings..before, all folders and movie files were created with permissions that was in this settings..before i did put in this settings user plex group root..now it seems that this settings are ignored 

Edit:  no, i didnt change anything, it was to complicated for me..i said i will wait for dietpi update..

**Comment by MichaIng** [comment]
@Dr0bac 
Does Radarr actually move or copy the Movies from Transmission download folder? So do they still exist in downloads as well? Would be not ideal due to doubled disk size consumption, but I remember this being the case when I did tests during this permissions fixes...

Actually Radarr might not be always able to adjust the permissions. It runs as radarr:dietpi (check via: `cat /etc/systemd/system/radarr.service`) and as such it can only change permissions of files owned by radarr. If it moves movie files from Transmission downloads, then this is the case.

> subzero plugin that download subtitles for plex did not download subtitles for recent movies i downloaded

Does it save the subtitles within the move container file (thus need write access) or separately? Plex runs as dietpi group so should have access to all files, but not sure if this is the case as well for plugins. Do they run as separate process or inside Plex main process (`htop`)?

Also if already make Radarr set permissions, please use 664/775 for files/folders, just in case Plex/subzero requires write permissions.

**Comment by Dr0bac** [comment]
Yes radarr only move video file ( i know, because file is moved quickly, in seconds) and after that radarr delete download movie folder and leftovers (like nfo, poster and similar)

Yes, subtitle is stored in same folder where movie is.. in htop all plugins are plex users..i think movie file must also be in plex group so subzero can work..i will try now to change movie file to be radarr:dietpi like folder..and i will check again will it work 

But movie file is in plex group.. it says root: dietpi

I will try with few permissions and will tell you 

@Michalng

I'm looking at folders permissions and it says only user have write permissions..and user in this case is radarr, so subzero can't write to folder..i will try now to download a movie with you recomended permissions, to see if this settings work or not

**Comment by MichaIng** [comment]
@Dr0bac 
> Yes radarr only move video file

Okay that is great in general. But then it makes sense that Radarr cannot change the files permissions, since they are owned by root (in your case) respectively transmission-daemon on current fresh install.

Transmission downloads allow group write access as desired. So Plex needs dietpi group permissions.
Please assure this is the case. On current install script we do:
`echo -e '[Service]\nGroup=dietpi' > /etc/systemd/system/plexmediaserver.service.d/dietpi-group.conf`

In case somehow the plugin sub processes do not take the dietpi group permissions from main systemd unit, you could try `usermod -a -G dietpi plex`

> Yes, subtitle is stored in same folder where movie is

Ah okay, but then no file write access is required, but folder write access. Then as well, change Radarr settings to set `0775` folder permissions. Should be not required if plugins run as `plex` user but who knows, worth to give it a try.

**Comment by Dr0bac** [comment]
@MichaIng you were right.. ichanged permissions to 0775/0664 and i see now that permissions are changed from drwxr-xr-x to drwxrwxr-x.. and now subzero works :)

One thing is strange.. before when radarr was root he did create those movie folders and movie files like i wrote in permissions plex:root 0755/0644.. now he lost that ability.. iguess before i created folders with plex owner so i didnt need group write access for subzero to work 

But nevermind, its working now and that is important :) 
Thank you

**Comment by MichaIng** [comment]
@Dr0bac 
Jep as said, since Radarr runs as radarr user now, it can only change permissions of it's own files, not those which are owned by other users. `root` of course can chown every file, so could Radarr when running as root.

Great it works now and thanks for feedback. I will open a new issue to configure sonarr/radarr/lidarr by default using this permissions: https://github.com/Fourdee/DietPi/issues/2220

**Comment by Dr0bac** [comment]
@MichaIng  hey sorry can i ask one more question?

I see that you moved radarr, sonarr log/backup folders to dietpi_userdata folder few dietpi updates back..

And when i had transmission issue with permissions, and when radarr could not move movie files to plex folder, radarr loged every minut that he can not move movie files..and because my dietpi_userdata folder is on external hdd that mean my hdd didnt sleep at all that time..right?

So is there a way to put those logs folders back to main micro sd card od maybe to the ram? 
Thanks

**Comment by MichaIng** [comment]
@Dr0bac 
Theoretically you can move it back by removing the `-data=$G_FP_DIETPI_USERDATA/sonarr` option from `/etc/systemd/system/sonarr.service` but this includes all data.

Also having constant I/O to the SDcard increases wear and leads to it breaking faster. I would always want to have as much I/O on external drive instead of SDcard! If there is some software flooding the log that the drive can't sleep, then better take care that software, resolve the issue or reduce logging verbosity, instead of moving this contant I/O to SDcard.

Moving logging to RAM of course would be best. But you don't want other data there. So we would need to find a way to move sonarr logs only to e.g. dietpi-ramlog (/var/log), but keeping other data inside dietpi_userdata 🤔.

**Comment by Dr0bac** [comment]
@MichaIng 
Someone asked the same question on reddit and someone from sonarr team answered this..

https://www.google.rs/amp/s/amp.reddit.com/r/sonarr/comments/7vn9c3/how_to_disable_logging/

Is it helpful for you?

So to bring back appdata folder to sd card i need to delete that line
-data=$G_FP_DIETPI_USERDATA/sonarr
From
/etc/systemd/system/sonarr.service
And restart raspberry and everything will be like before? 

In sonarr settings minimum loging level is info..and info is loging rss sync every 15 minutes..my hdd is going to sleep after half hour..so it gonna always stay wake because of sonarr, radarr logs.. on micro sd card there always something happening, my hdd wake up onky when i watch or download movies, so its better sonarr loging to be on sd card

**Comment by MichaIng** [comment]
@Dr0bac 
Move content of /mnt/dietpi_userdata/sonarr to default location first, to not loose config/data. I believe it's `/root/.<something>`?
Jep the link supports my assumption. So there seems to be no possibility to change the logging location only.

**But really, I absolutely not recommend this and future dietpi-updates may break it/require to reapply. It is definitely better to have an external drive running through the night then to have an SDcard being constantly written to. Fix the logging issue, change logging settings, do not break your SDcard and have a full system+data loss instead!**

Within the link an SSD is the assumption. This of course would be a proper solution as well, if for some reason you need that much logging. But SDcard is no option from my point of view.

Wait, a nice solution actually would be to symlink the log file(s) themself to /var/log (with dietpi-ramlog)? Not sure about the remaining database writes. If really all log is doubled to database + logfile then the issue remains of course, but this is not explicitly mentioned, actually.

**Comment by Dr0bac** [comment]
@MichaIng 

https://github.com/Sonarr/Sonarr/wiki/Log-Files

On sonarr wiki it is written:

You can clear log files and the logs database directly from the UI, under System -> Logs -> Files and System -> Logs respectively.

So sonarr and radarr are storing logs in txt file and db file..how can we symlink them to var/log?
In appdata folder there are several db files but i can look in date modified times to see which db is for logs, to compare with txt file..

**Comment by Fourdee** [comment]
@Dr0bac 

> /var/log/sonarr.log

I do not believe Sonarr logging is compatible with our RAMlog system. As it uses ```.db``` (database) file, if we clear the contents every 1 hour, it may cause the application to fail:
```
root@Fuzon:~# ls -lha /mnt/dietpi_userdata/sonarr/
total 17M
drwxrwxrwx 1 root root 4.0K Nov  5 04:38 .
drwxrwxrwx 1 root root 4.0K Oct 28 13:47 ..
drwxrwxrwx 1 root root    0 Jul 28 22:20 Backups
-rwxrwxrwx 1 root root  464 Oct 25 14:21 config.xml
drwxrwxrwx 1 root root 4.0K Oct 27 04:39 logs
-rwxrwxrwx 1 root root 1.4M Nov  5 07:29 logs.db
-rwxrwxrwx 1 root root  32K Nov  5 13:11 logs.db-shm
-rwxrwxrwx 1 root root 5.2M Nov  5 13:11 logs.db-wal
drwxrwxrwx 1 root root 4.0K Nov  5 10:31 MediaCover
-rwxrwxrwx 1 root root 5.8M Nov  5 13:08 nzbdrone.db
-rwxrwxrwx 1 root root  32K Nov  5 13:22 nzbdrone.db-shm
-rwxrwxrwx 1 root root 4.0M Nov  5 13:22 nzbdrone.db-wal
-rwxrwxrwx 1 root root    4 Oct 25 14:21 nzbdrone.pid
```

We could ```/var/log``` the following directory, but this would ignore the ```.db``` files which I assume have the same IO use as the actual ```.txt``` file:
```
root@Fuzon:~# ls -lha /mnt/dietpi_userdata/sonarr/logs/
total 5.8M
drwxrwxrwx 1 root root  4.0K Oct 27 04:39 .
drwxrwxrwx 1 root root  4.0K Nov  5 13:26 ..
-rwxrwxrwx 1 root root 1000K Oct 27 04:39 sonarr.0.txt
-rwxrwxrwx 1 root root 1000K Oct 16 19:26 sonarr.1.txt
-rwxrwxrwx 1 root root 1000K Oct  6 03:52 sonarr.2.txt
-rwxrwxrwx 1 root root 1000K Sep 25 08:11 sonarr.3.txt
-rwxrwxrwx 1 root root 1000K Sep 14 03:00 sonarr.4.txt
-rwxrwxrwx 1 root root  5.8K Jul 21 23:32 sonarr.debug.txt
-rwxrwxrwx 1 root root  875K Nov  5 13:26 sonarr.txt
```

Ticket for request: https://github.com/Fourdee/DietPi/issues/2223
