### ISSUE TITLE
Aria2 web interface shows apache directory listing

### ISSUE THREAD

**Issue by sureshachary** [MichaIng/DietPi#2069]
## Creating a bug report/issue:
<img width="483" alt="aria2_webui_error" src="https://user-images.githubusercontent.com/37358234/45474864-6e47bb80-b758-11e8-9a30-1620dbe04432.png">

#### Required Information:
- DietPi version	| 6.15
- Distro version	| stretch 9.4
- Kernel version	| Linux mypi 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux
- SBC device		| RPi 3 Model B+ (armv7l)
- Power supply used	| 5V 2A
- SDcard used		| 
Strontium Nitro A1 64GB Micro SDXC Memory Card 100MB/s A1 UHS-I U3 Class 10 

#### Additional Information (if applicable):
- Software title	| Aria2
- Was the software title installed freshly or updated/migrated? fresh
- Can this issue be replicated on a fresh installation of DietPi? Ys
- `dietpi-bugreport` ID b2da1b9d-e0b7-48f8-8109-4f87ef663fde

#### Steps to reproduce:

1. Installed fresh DietPi on a new RPi 3 B+, from Software Optimized just installed Aria2 and nothing else.
2. On accessing Aria2 web interface, it shows apache directory listing instead of Aria2 web UI

#### Expected behaviour:
Should show Aria2 web UI

#### Actual behaviour:

 it shows apache directory listing

#### Extra details:

- ...

**Comment by MichaIng** [comment]
@sureshachary
Thanks for your report.

It looks like the Gihub repo folder structure was changed: https://github.com/ziahamza/webui-aria2/commit/54c56d57ae0e175530d98530d8bc830c57208127
The actual WebUI is now within the docs/ directory.

Could you try to open `10.0.0.2/aria2/docs` in the browser instead?

So we need to download/install this subdir only then. Need to check if the files in patent dir are still needed or just for own build, docker and NodeJS exec.

**Comment by sureshachary** [comment]
Thank you, yes the folder structure has changed. http://10.0.0.2/aria2/docs is working.

**Comment by MichaIng** [comment]
@sureshachary 
Great to hear. I reopened to not forget fixing this. We try to apply/setup the WebUI the way, that you can access again via `<IP/domain>/aria2`.

Perhaps install size can be reduced by downloading the docs sub directory only and leave out the others.

Also at least we can think about using the additional methods, e.g. allow users to decide whether they want to use it via usual webserver or via NodeJS. The latter could be beneficial is either you have no other use for the webserver or you already have other software that require NodeJS.

**Comment by sureshachary** [comment]
Okay

**Comment by Fourdee** [comment]
Symlink not compatible:
```
ln -sf /var/www/aria2/docs/index.html /var/www/aria2/index.html
```

![image](https://user-images.githubusercontent.com/7077026/45700332-22d04b80-bb64-11e8-9e21-9132a634e48f.png)
---

This appears to work 🈯️ 
```
mv /var/www/aria2/docs/* /var/www/aria2/
```

However, if they have any matching file names added in the future, will break installation.

Therefore, for now and to prevent potential future issues with moving files, i'll simply update the online doc to reflect the new URL.
🈯️ https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=6177#p6177

Completed.

**Comment by Fourdee** [comment]
Delete parent dir and move docs over
```
mv /var/www/aria2/docs /tmp/
rm -R /var/www/aria2/*
mv /tmp/docs/* /var/www/aria2/
rm -R /tmp/docs
```

Parent dir not required?

Interesting, this works 🈯️ 

But if they make changes in the future, that relies on the parent dir, this could break our installation. I'll leave this as is, with the updated online doc link.
