### ISSUE TITLE
DietPi-Software | Add Java installation option 

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#207]
Please add Java in Dietpi software because some application require java to run.

https://wiki.debian.org/Java/

**Comment by Fourdee** [comment]
@starstuff 

Thanks for the suggestion. In the mean time, instructions to install Oracle Java 8 is listed below.

On the Raspberry Pi (Jessie), you can install Java with this command:

```
apt-get install oracle-java8-jdk
```

For other systems on Jessie (Odroids/VM/OrangePi):

```
cat << _EOF_ > /etc/apt/sources.list.d/webupd8team-java.list
deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
_EOF_

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer
```

**Comment by Fourdee** [comment]
> note to self:
> remove java installation code for `SUBSONIC` and set `ORACLEJAVA=1`.

**Comment by Fourdee** [comment]
Completed, v111
