### ISSUE TITLE
Jessie | DietPi-Preboot causes systemd to skip networking service

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2075]
> https://github.com/Fourdee/DietPi/issues/2071#issuecomment-421127903
https://github.com/Fourdee/DietPi/issues/2071#issuecomment-421145760

Non-issue for Stretch+

> re: @MichaIng 
networking wants to run before sysinit.target
But sysinit.target runs before basic.target, which is required by all our services.
So it's: networking -> sysinit -> basic -> preboot -> networking

**Comment by MichaIng** [comment]
Manual workaround works well here on Jessie VM: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4726&p=14440#p14440
- Although the solution is a bid ugly. Would be nice, if we could somehow resolve the dependency loop completely. At least otherwise on Jessie systems disable networking service and then add `[[ $G_DISTRO < 4 ]] && systemctl start networking` e.g.?
- Must be somehow possible to add a service to start after root/boot mount and before network 🤔. How where does the sysinit dependency come from, otherwise how can be make networking not want to run before sysinit.target (which would make most sense for me)?

**Comment by Fourdee** [comment]
Note to self:
- Setup Jessie system, investigate issue.

**Comment by MichaIng** [comment]
@Fourdee 
I found a perhaps cleaner solution: https://unix.stackexchange.com/a/239978

- Adding `Wants=network-pre.target` to pull in this target, which seems not to be pulled by default.
- Adding `Before=network-pre.target` to let it run before all networking services.
- Removing all other network targets+services from `Before=` to remove the dependency loop.

Works well here on Jessie VM, but should be tested on some other Jessie devices.
_______
🈯️ Testing on Buster, to be sure this target is always present and works as expected...Works well!

**Comment by Fourdee** [comment]
@MichaIng 

```
systemd-analyze plot > /root/after.html
```

Tweaked the services, appears fine on Stretch:
- before https://dietpi.com/downloads/testing/before.html
- after https://dietpi.com/downloads/testing/after.html

Just need to test Jessie.

---

Jessie:
- 🈴 PREP > eth0 down
<img width="363" alt="capture" src="https://user-images.githubusercontent.com/7077026/46093703-f0e86600-c1af-11e8-9e96-99da13846503.PNG">
. ```networking.service``` was not started.

**Comment by MichaIng** [comment]
Nice tool btw.

**Comment by Fourdee** [comment]
@MichaIng 

Went for the workaround for Jessie. Not ideal, however, all our official current images are Stretch.

Re-test using PREP
- 🈯️ Stretch
- 🈯️ Jessie


Completed.

**Comment by MichaIng** [comment]
@Fourdee 
Okay, so found that basic.target and sysinit.target are by default added as required, which can be overridden via `DefaultDependencies=no`.
But I guess, this would be needed for ramdisk+ramlog as well, to completely resolve the loop. Not sure, if there is any needed service starting between local-fs.target and sysinit.target/basic.target on Jessie.

Why do ramdisk/ramlog actually start before `boot.mount`, when they are actually set to start `After=local-fs.target boot.mount`?? `DietPi.mount` is already done, so /boot definitely mounted. I see `boot.automount` starting at very early stage, maybe that solves/replaces somehow `boot.mount` 🤔.

However, I will test a bid with `DefaultDependencies=no`, but at least we have a workaround now.
___________
€: Ah better no mess around with those default dependencies. We call too much scripts/functions/commands within preboot to test, if everything is working properly before basic/sysinit.target. Workaround works /close 😄.

**Comment by sdubrick** [comment]
I just wanted to mention that I was having issues with my Odroid C1 not connecting eth0 on startup in v6.16, and the workaround didn't fix it (see https://dietpi.com/phpbb/viewtopic.php?f=11&t=5116).  The changes @Fourdee checked in here DID fix it though, thanks.

**Comment by MichaIng** [comment]
@sdubrick 
The `systemctl start networking` inside preboot script was the change that finally fixed it for Jessie systems (G_DISTRO=3), if one does not want to apply all those changes 😉: https://github.com/Fourdee/DietPi/blob/be64a2c84aae9215de1bce6d2684f2d84a1bbd1d/dietpi/preboot#L269-L274
