### ISSUE TITLE
DietPi-Drive_Manager | Support ecryptfs mounts

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2078]
## Creating a feature request:
- Thanks @johnvick for reporting this.

#### Is your feature request related to a problem? Please describe:

- `ecryptfs` mount type (encrypted folder) is not yet supported and preserved, when opening `dietpi-drive_manager`.

#### Describe the solution you'd like:

- Adding feature to add an encrypted drive.
- Check/Preserve existing `ecryptfs` mounts.

#### Additional info:

- https://dietpi.com/phpbb/viewtopic.php?f=11&t=4803
- `eCryptfs is a native Linux filesystem. The kernel module component of eCryptfs is part of the Linux kernel since 2.6.19.`
Should be possible to check for this kernel module and only offer the feature, if it is present.
- `df => /home/john/crypt 29254192 16431072 12806736 57% /home/john/crypt`
Hmm, need to check if there is a better output to identify these mounts, as an identifying string is missing :?. Currently, as the "mount source" has no UUID, drive_manager just identifies it as network drive (thus should show it in the list), which need to be identified and added to fstab separately.
I will do some research about it.

**Comment by MichaIng** [comment]
#### PR up: https://github.com/MichaIng/DietPi/pull/2729
- No full support (handling these mounts), but at least the fstab entries are preserved.

**Comment by johnvick** [comment]
Thanks.
