### ISSUE TITLE
DietPi Menu standards

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2079]
- If the item contains a changeable value, it must contain ```[VALUE]```?
- All menu array 2nd items, must contain ```:``` at start to separate the 1st item?

🈯️ Currently, this looks fine:
![image](https://user-images.githubusercontent.com/7077026/45752352-0fc58600-bc0d-11e8-89f7-f622dd5621d5.png)
![image](https://user-images.githubusercontent.com/7077026/45752393-34216280-bc0d-11e8-870d-f179142130fb.png)

🈴 But this looks a mess, as the text blends into each other:
![image](https://user-images.githubusercontent.com/7077026/45752366-18b65780-bc0d-11e8-9f5c-247ca4ecab0b.png)
![image](https://user-images.githubusercontent.com/7077026/45752405-3edbf780-bc0d-11e8-8ea0-dcdaa66d9557.png)

**Comment by MichaIng** [comment]
@Fourdee 
We could make `G_WHIP_INIT` add delimiters automatically. So on array creation we only need to add the raw text.
Allows us to change it easily for all together, if something beautiful was found.

**Comment by Fourdee** [comment]
@MichaIng 

> We could make G_WHIP_INIT add delimiters automatically. So on array creation we only need to add the raw text.

Yep, thought the same already 👍 , but processing on large menu's may be an issue to add and re-shuffle the chars?

**Comment by MichaIng** [comment]
@Fourdee 

For `G_WHIP_MENU`:
```
for ((i=1;i<${#G_WHIP_MENU_ARRAY[@]};i=i+2))
do

	G_WHIP_MENU_ARRAY[$i]=": ${G_WHIP_MENU_ARRAY[$i]}"

done
```

For `G_WHIP_CHECKLIST`:
```
for ((i=1;i<${#G_WHIP_CHECKLIST_ARRAY[@]};i=i+3))
do

	G_WHIP_CHECKLIST_ARRAY[$i]=": ${G_WHIP_CHECKLIST_ARRAY[$i]}"

done
```

As very first step, before estimating windows size and such?

Just checked G_WHIP_INIT(). `((i=1;i<${#G_WHIP_MENU_ARRAY[@]};i=i+2|3))` can be also used there for some of the loops instead of current (($i%2|3) checks and such. Maybe the performance improvement of that can catch up with the performance loss due to the above a bid.

**Comment by Fourdee** [comment]
@MichaIng 

Nice 👍 

Although my issue is with any performance impact. The RPI 1/Zero is borderline slow with ```dietpi-software``` list generation. Any slower and it will become painful lol.

I think for simplicity and keeping current performance, we simply need to add ```:``` manually to ```G_WHIP``` items as we see them?

**Comment by MichaIng** [comment]
@Fourdee 
Okay for now, as mentioned, there seem to be some other parts where we can improve performance. Then we do some tradeoff with the above 😉.

**Comment by MichaIng** [comment]
PR to speed up G_WHIP: https://github.com/Fourdee/DietPi/pull/2136

**Comment by Fourdee** [comment]
@MichaIng 

Thanks 👍 

Issue with missing text:
https://github.com/Fourdee/DietPi/pull/2136#issuecomment-429524800

**Comment by Fourdee** [comment]
New format:
- ```:``` on all 2nd array items at start
- ```[ ]``` indicates a changeable option, with current value inside.
![image](https://user-images.githubusercontent.com/7077026/46905162-b7219a00-cee7-11e8-8b60-20ce3805d58f.png)

**Comment by MichaIng** [comment]
@Fourdee 
Fixed with: https://github.com/Fourdee/DietPi/commit/6570a9949f84f18d68f8476061f1796814cfb25d

However somehow found another issue:
- $WHIP_MESSAGE is not shown, debug:
```
                        # - Calculate lines required, including addition lines, if the text is longer than X
                        [[ $WHIP_MESSAGE ]] && echo -e "$WHIP_MESSAGE" | while read -r line
                        do

                                lines_required_whip_y=$(( lines_required_whip_y + 1 + ${#line} / ( $WHIP_SIZE_X - $whip_x_internal_margin) ))
                                echo $lines_required_whip_y

                        done
                        echo $lines_required_whip_y

                        #       Process final whiptail size
                        #       Add internal whiptail margins to end line total
                        lines_required_whip_y=$(($lines_required_whip_y+$whip_y_internal_margin))
```
```
root@VM-Stretch:~# G_WHIP_MSG "TEST\nTEST2\nTEST3"
1
2
3
0
```
- `lines_required_whip_y` increase is lost outside the while read loop 🤔. Strange since we used this as well before...
- Found issue: `echo ... | while` seems to open subshell for the loop, and variables assigned/edit within subshell are not available in parent shell. Solved via here string: https://github.com/Fourdee/DietPi/commit/027c8a555be67bd2c241c2921dfaa6a9acbf0ae9

**Comment by MichaIng** [comment]
Added to v6.17 milestone, so we not forget it an apply to scripts that we touch anyway:

> New format:
> - ```:``` on all 2nd array items at start
> - ```[ ]``` indicates a changeable option, with current value inside.

**Comment by MichaIng** [comment]
There are now several menus, where the values are shown within the menu entries and above in whiptail text again: When adding the value to the menu entry, we should remove the related text above.

From code side, with last PRs I added real linebreaks to long whiptail texts (replacing `\n`) to make it more readable and reduce the need to scroll left and right within code.

**Comment by Fourdee** [comment]
@MichaIng 

> There are now several menus, where the values are shown within the menu entries and above in whiptail text again: When adding the value to the menu entry, we should remove the related text above.

Yep, agree 👍

**Comment by Fourdee** [comment]
Will mark as completed:
- I believe all menus now have the new standard ```'X' ': X'```
- Will further reduce double current value print out in ```G_WHIP_MENU``` when I come across them 😄

**Comment by MichaIng** [comment]
@Fourdee 
I think I saw one missing case, cloudshell or another misc program. Will check quickly.

**Comment by MichaIng** [comment]
Done: https://github.com/Fourdee/DietPi/commit/b6635e0ca426a2c20e3169ddd192bf8c58a2a3ed
- Applied to all menus, besides where second entry is "Seconds" or "Hours"
