### ISSUE TITLE
DietPi-Software | SpigotMC Minecraft server

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#2082]
Hello, i would like when there is time to create for dietpi a simple minecraft server unlike the gui versions that need a lot of configurations 
its something like the pe/nukkit version but it works on general/official minecraft version
a simple straight loading server without anything to setup.for users that want to start right away.

The best instructions i can find are on this two pages:

https://www.makeuseof.com/tag/setup-minecraft-server-raspberry-pi/

https://pimylifeup.com/raspberry-pi-minecraft-server/

----------------------------------------------------------
Its a server that will use the latest build at this time 1.13.1
With the NoSpawnChunk plugin to save memory
Works on older pi with the right configuration Model B and up and on latest ones 2/3/3B+
and it can start at boot.
------------------------
i can help if you want.

Thanks

**Comment by MichaIng** [comment]
@symbios24 
Thanks for your request. However not that it might take a while, as there are other interesting software requests in the pipe.

Also I think we will not implement any of those with v6.17 where we implement a new Beta system that needs to be announced and tested first.

**Comment by MichaIng** [comment]
Official link: https://www.spigotmc.org/wiki/about-spigot/

Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+15

**Comment by MichaIng** [comment]
No votes (more down == up) so far. Will mark as closed for general cleanup. However the FeatHub page stays in place to allow further voting. If it reaches closer to the top we will reopen.

**Comment by nonnorm** [comment]
@symbios24
Just want to point out, PaperMC was recently added and is an optimized version of SpigotMC.  It can basically run all Spigot plugins and is much more performant.
