### ISSUE TITLE
Issue with Xserver and booting LXDE desktop on Rock64

### ISSUE THREAD

**Issue by pfordmedia** [MichaIng/DietPi#2086]
Total coding newbie here, but I'm having issues. Also, please excuse my lack of knowledge of how GitHub works as I'm new to that as well.
#### Required Information:
- DietPi version	| 6.16 
- Distro version	| Debian 9 stretch
- Kernel version	| Linux DietPi 4.4.132 #1 SMP Thursday Jul 26 08:22:22 UTC 2018 aarch64
- SBC device		| Pine64 Rock64 ARM64 4gb.
- Power supply used	| Pine64 5v 3A
- SDcard used		| SanDisk Ultra 32GB

#### Additional Information (if applicable):
- Software title	| 
- Was the software title installed freshly or updated/migrated? DietPi flashed with PineInstaller64 for Windows.
- Can this issue be replicated on a fresh installation of DietPi? Yes
- `dietpi-bugreport` ID

#### Steps to reproduce:

1.  Format SD card using Windows disk utility
2.  Flash DietPi 6.16 Rock64 ARMv8 Stretch to SD using Etcher
3.  Boot from SD 
4. Install DietPi
5. Install LXDE from `dietpi-software` without setting  autostart options
6. Reboot and login
7. In console, run `startx`

#### Expected behaviour:

- ... LXDE desktop should begin and open.

#### Actual behaviour:

- `root@DietPi:~# startx`
`xauth: file /root/ .Xauthority does not exist`
 
`X.org X Server 1.19.2`

and then below XServer info:

`(==) Log file: "/var/log/Xorg.0.log", Time: Sat Sep 22 03:46:37 2018`
`(==) Using config directory: "/etc/X11/xorg.conf.d"`
`(==) Using system config directory "usr/share/X11/xorg.conf.d"`
`(EE)`
`Fatal server error:`
`(EE) no screens found (EE)`
`(EE)`
`Please consult The X.Org Foundation support`
`at http://wiki.x.org`
`for help`
`(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.`
`(EE)`
`(EE) Server terminated with error (1). Closing log file.`
`xinit: giving up`
`xinit: unable to connect to X server: Connection refused`
`xinit: server error`

#### Extra details:

- When I check the log file using `tail -f`it basically gives me the same message.  Is this a result of a missing video driver on my chipset or a driver that is incompatible with the Rock64 chipset? The X.org wiki shows this issue in their FAQ, however their fixes did not have any effect. Please see this page: https://www.x.org/wiki/FAQErrorMessages/#index8h2

**Comment by Fourdee** [comment]
@pfordmedia 

Hi, 

Many thanks for the report 👍  I'll try to replicate.

**Comment by Fourdee** [comment]
Confirmed, taking a look now.

**Comment by Fourdee** [comment]
> https://github.com/rockchip-linux/rk-rootfs-build/tree/master/packages/armhf/libmali

🈴 
```
dpkg --add-architecture armhf
G_AGUP
wget https://github.com/rockchip-linux/rk-rootfs-build/raw/master/packages/armhf/libmali/libmali-rk-utgard-450-r7p0_1.6-1_armhf.deb
dpkg -i *.deb
G_AGF
```

```
root@DietPi:~# cat /var/log/Xorg.0.log
[    20.694]
X.Org X Server 1.19.2
Release Date: 2017-03-02
[    20.694] X Protocol Version 11, Revision 0
[    20.694] Build Operating System: Linux 4.9.0-4-arm64 aarch64 Debian
[    20.695] Current Operating System: Linux DietPi 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64
[    20.695] Kernel command line: earlycon=uart8250,mmio32,0xff130000 rw panic=10 init=/sbin/init coherent_pool=1M ethaddr=06:5e:db:ec:44:e5 eth1addr=06:5e:db:ec:44:05 serial=964171e64c6243f cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 root=LABEL=linux-root rootwait rootfstype=ext4
[    20.696] Build Date: 16 October 2017  08:11:43AM
[    20.696] xorg-server 2:1.19.2-1+deb9u2 (https://www.debian.org/support)
[    20.696] Current version of pixman: 0.34.0
[    20.696]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[    20.696] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    20.697] (==) Log file: "/var/log/Xorg.0.log", Time: Sat Sep 22 13:46:24 2018
[    20.706] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    20.706] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    20.709] (==) ServerLayout "ServerLayout0"
[    20.709] (**) |-->Screen "DefaultScreen" (0)
[    20.709] (**) |   |-->Monitor "<default monitor>"
[    20.715] (**) |   |-->Device "Mali FBDEV"
[    20.716] (==) No monitor specified for screen "DefaultScreen".
        Using a default monitor configuration.
[    20.716] (**) Option "BlankTime" "0"
[    20.716] (**) Option "StandbyTime" "0"
[    20.716] (**) Option "SuspendTime" "0"
[    20.716] (**) Option "OffTime" "0"
[    20.716] (==) Automatically adding devices
[    20.716] (==) Automatically enabling devices
[    20.716] (==) Automatically adding GPU devices
[    20.716] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    20.724] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    20.724]    Entry deleted from font path.
[    20.724] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[    20.725] (==) ModulePath set to "/usr/lib/xorg/modules"
[    20.725] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[    20.725] (II) Loader magic: 0x5560d15dc8
[    20.725] (II) Module ABI versions:
[    20.725]    X.Org ANSI C Emulation: 0.4
[    20.725]    X.Org Video Driver: 23.0
[    20.725]    X.Org XInput driver : 24.1
[    20.725]    X.Org Server Extension : 10.0
[    20.727] (++) using VT number 1

[    20.732] (II) systemd-logind: took control of session /org/freedesktop/login1/session/_31
[    20.734] (II) xfree86: Adding drm device (/dev/dri/card0)
[    20.736] (II) systemd-logind: got fd for /dev/dri/card0 226:0 fd 11 paused 0
[    20.736] (II) no primary bus or device found
[    20.736]    falling back to /sys/devices/platform/display-subsystem/drm/card0
[    20.736] (II) LoadModule: "glx"
[    20.740] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    20.791] (II) Module glx: vendor="X.Org Foundation"
[    20.791]    compiled for 1.19.2, module version = 1.0.0
[    20.791]    ABI class: X.Org Server Extension, version 10.0
[    20.793] (II) LoadModule: "armsoc"
[    20.793] (WW) Warning, couldn't open module armsoc
[    20.793] (II) UnloadModule: "armsoc"
[    20.793] (II) Unloading armsoc
[    20.793] (EE) Failed to load module "armsoc" (module does not exist, 0)
[    20.793] (EE) No drivers available.
[    20.793] (EE)
Fatal server error:
[    20.793] (EE) no screens found(EE)
[    20.793] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[    20.793] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    20.794] (EE)
[    20.861] (EE) Server terminated with error (1). Closing log file.
```

- Same issue as: https://github.com/ayufan-rock64/linux-build/issues/201
- ```xserver-xorg-video-armsoc``` not available in Debian repos: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=armsoc

**Comment by Fourdee** [comment]
@pfordmedia 

Workaround is to remove the Mali GPU xorg definition:
```
mv /etc/X11/xorg.conf.d/20-armsoc.conf /root/
startx
```

This allows X to init under software mode.

I'am not having much success with HW GPU currently:(https://github.com/Fourdee/DietPi/issues/2086#issuecomment-423741172)

**Comment by pfordmedia** [comment]
@Fourdee I was able to install a stable version from Pine Installer which has version 156 preloaded before. Then I reflashed with 6.16 and did an apt-get update and from then on out I’ve been getting this error. 

Haven’t tried to flash an older version though after the apt-get update. I may try that now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pfordmedia** [comment]
Sorry I just saw the workaround. This works great! Thanks so much!

**Comment by Fourdee** [comment]
Completed.

However, as above, we only offer software rendering for the GPU at this time.

**Comment by denni-isl** [comment]
> @pfordmedia
> 
> Workaround is to remove the Mali GPU xorg definition:
> 
> ```
> mv /etc/X11/xorg.conf.d/20-armsoc.conf /root/
> startx
> ```
> 
> This allows X to init under software mode.
> 
> I'am not having much success with HW GPU currently:([#2086 (comment)](https://github.com/Fourdee/DietPi/issues/2086#issuecomment-423741172))

Did work like a charm.    Quick fix.  Thanks!
