### ISSUE TITLE
Update readme？？

### ISSUE THREAD

**Issue by FusionPlmH** [MichaIng/DietPi#2118]
about the branch of dev ,beta ,stable

**Comment by MichaIng** [comment]
@LeeMenHin 
Info is available on: https://github.com/Fourdee/DietPi/blob/dev/TESTING-BRANCH.md
- But yet, not yet on default master branch. We will do that, once we officially announce the new beta testing system (+versioning and updateing). It is still in internal testing phase.

However file name could be updated (BRANCH_SYSTEM.md or something like that?) and/or the included info could be indeed merged into README.md.

**Comment by Fourdee** [comment]
@MichaIng 

> However file name could be updated (BRANCH_SYSTEM.md or something like that?) and/or the included info could be indeed merged into README.md.

Yep 👍 

And we'd need to keep the old file, redirect to new one (as linked in forums etc)

I'll make the change
🈯️ https://github.com/Fourdee/DietPi/blob/dev/BRANCH_SYSTEM.md#steps-to-use-the-dietpi-beta-branch

**Comment by Fourdee** [comment]
@LeeMenHin 

As @MichaIng mentioned, we are still developing the beta system for DietPi. We are aiming to release this to the public in the next few days. Once its ready, i'll post on our Twitter page with the info https://twitter.com/DietPi_

I'll mark this as completed.

**Comment by MichaIng** [comment]
@Fourdee 
We could also search the forum for links and fix them. In case of `TESTING-BRANCH.md` this should not be much, if anything.

**Comment by MichaIng** [comment]
We could also add/move those information to the Wiki instead. Perhaps it's better places there instead of being part of the update archive.

**Comment by Fourdee** [comment]
@MichaIng 

> We could also add/move those information to the Wiki instead.

If you get the time, go for it 👍
