### ISSUE TITLE
DietPi-System | Add Privacy Extensions (RFC 4941) in Stateless Address Autoconfiguration (SLAAC) for IPv6

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#212]
@Fourdee 

I have notice MuJJus request in [#72](https://github.com/Fourdee/DietPi/issues/72#issuecomment-172444787) to have [IPv6 privacy extensions](https://debian-handbook.info/browse/stable/sect.ipv6.html)  additional to EUI-64 based IPv6 address generated by SLAAC.

To get this, we had to added some lines in `/etc/network/interfaces` (e.g. oDroid C1) if we use IPv6 in DietPi:

```
#/etc/network/interfaces
#Please use DietPi-Config to modify network settings.

# Local
auto lo
iface lo inet loopback

# Ethernet
auto eth1
iface eth1 inet dhcp

iface eth1 inet6 auto
    # Prefer the randomly assigned addresses for outgoing connections.
    privext 2
```

IPv6 is default since v107, but can be also switched off in `dietpi-config`.

To probe, if IPv6 privacy extensions ist active (example):

```
root@oDroid-C1:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1e:06:aa:bb:cc brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 brd 192.168.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 2001:db8:1234:5:4f:97c3:2bc0:3e14/64 scope global temporary dynamic
       valid_lft 533792sec preferred_lft 14792sec
    inet6 2001:db8:1234:5:21e:6ff:feaa:bbcc/64 scope global dynamic
       valid_lft 2591733sec preferred_lft 604533sec
    inet6 fe80::21e:6ff:feaa:bbcc/64 scope link

```

But I don't have success to change default value for preferred life time (preferred_lft) in IPv6 privacy extensions.

**Comment by k-plan** [comment]
@Fourdee 

sorry, perhaps not precise express. 
I have tested this  _Feature Request_ now since v107 crowned with success.
Yes, I have a Dual Stack network at home, with dyn. IPv4 (via NAT) and native IPv6 with a static address block.
I notice, unfortunately you do not have access to any IPv6 networks to test it. So perhaps, it is possible, to integrate this into DietPi-Config as a toggle option.

**Comment by Fourdee** [comment]
@k-plan 

Sorry Frank. Going to have to nudge this one again. Still no access to a IPv6 network at my end, would make implementing and testing this a nightmare.
