### ISSUE TITLE
v6.16 | RPI v1B (256mb RAM)

### ISSUE THREAD

**Issue by S60Team** [MichaIng/DietPi#2131]
v6.16, RPI v1B (256mb RAM), using 8Gb MicroSDHC Class4:
Infinite INSTALL loop after install:
  nginx+sqlite, mc and vsftpd.
and selecting "not to send data".

**Comment by MichaIng** [comment]
@S60Team 
Thanks for your report.

Can you give us some more details:
- What you mean with `mc`?
- Did you install these software via DietPi-Automation (dietpi.txt settings) on 1st boot? And install loop then, as after reboot, first run setup (+dietpi-software auto install) just runs again?

**Comment by Fourdee** [comment]
@S60Team 

Hi,

Please also provide us with the make, model, volt, amperage of the PSU used.

**Comment by S60Team** [comment]
mc is MidnightCommander. No, i've not used auto-install.
PSU is CinkeyPro USB 5v (2A + 1A, 2 ports).
PS: After re-formatting my sdcard i've tried to install OS again.
Installation was successful, but it it taken many time, because of some files was overwriting.

**Comment by Fourdee** [comment]
@S60Team 

Thanks for the info. I suspect unstable 5V on the PSU (check ```dmesg | grep undervolt``` ), and/or failing SD card.

To ensure hardware stability, and, full support from our end, please use:
- Official RPi PSU
- Well branded SD card (eg: Sandisk Ultra/Samsung EVO)

As i'am unable to replicate our end, and, a re-flash resolved the issue for you, i'll mark this as closed.
