### ISSUE TITLE
DietPi-Software | Kodi: Shutdown/Restart options disappeared

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2155]
https://dietpi.com/phpbb/viewtopic.php?f=11&t=4596&sid=604d72c431f39c16f16c5dd61ab8284f

**Comment by Fourdee** [comment]
Confirmed on native PC, running kodi under autostart. Will investigate.
Notes to self:
- systemd-logind
- dbus
- Works under desktop?

**Comment by Fourdee** [comment]
Confirmed ```systemd-logind``` required for shutdown options, will patch.
