### ISSUE TITLE
Official 7'' Touchdisplay Chromium autostart resolution failure

### ISSUE THREAD

**Issue by docgalaxyblock** [MichaIng/DietPi#2158]
Dietpi (6.16)     PI3B+

Installed Chromium and chose it at autostart.
The resolution (1280x720) is to big for the Display (800x480). See pictures ^^
Could it be possible that the dietpi-autostart chromium windowsize-flag use the resolution which is chosen at dietpi-config -> Display Options?

![21-10-_2018_14-32-59](https://user-images.githubusercontent.com/21227087/47270787-154a1f00-d571-11e8-951c-120ab4caf6ae.png)
![20181021_184919 1](https://user-images.githubusercontent.com/21227087/47270803-3ad72880-d571-11e8-821a-12e3d08e4779.jpg)

Greetings from Germany^^

**Comment by Fourdee** [comment]
@potter-91 

> Could it be possible that the dietpi-autostart chromium windowsize-flag use the resolution which is chosen at dietpi-config -> Display Octions?

Yep, great idea, we can apply to Chromium if installed, when setting display resolution.

**Comment by MichaIng** [comment]
Makes sense, currently hardcoded: https://github.com/Fourdee/DietPi/blob/dev/dietpi/dietpi-software#L11112

What happens if we just skip this flag/setting? Best would be if Chromium just starts with same resolution then console?

**Comment by Fourdee** [comment]
@MichaIng 

> What happens if we just skip this flag/setting? Best would be if Chromium just starts with same resolution then console?

Doesn't scale or use full screen available last time I checked.

Will be hard to detect current resolution for all devices. Might be best to add a prompt to select screen size when setting autostart option + apply there.

or, get + apply during run?

Xorg needs to be running for these to function:
```
xdpyinfo | grep dimensions
xrandr
```
- xinit chromium + thread, get data, kill, restart with obtained?
-- "cant open display"
- + thread function to get data, same result.

Seems the x commands must be run at the local system, once Xorg is running. No way for us to get this data as far as I can see.

**Comment by Fourdee** [comment]
For RPi, we'll auto match current resolution, dietpi.txt entry.
For other devices, users can change the dietpi.txt entries. As, this would require a vast rewrite to support all devices via above method.

**Comment by Fourdee** [comment]
Ordered a 7inch touchscreen HDMI, will do some testing when it arrives.

**Comment by Fourdee** [comment]
@potter-91 

Fixed in v6.17, you can test this now using our Beta program:
https://github.com/Fourdee/DietPi/blob/dev/BRANCH_SYSTEM.md#steps-to-use-the-dietpi-beta-branch

To apply the new settings, after patch, please re-select the RPi touch screen from ```dietpi-config```.

**Comment by docgalaxyblock** [comment]
I've got another idea:
A integration or your own script to change the touchscreens brightness and power.
I use this: https://github.com/linusg/rpi-backlight

Chromium now works perfect.
Could be "unclutter" also a good idea to chose it in dietpi.software or -config to hide the mouse?

**Comment by Fourdee** [comment]
Notes:
- hide mouse https://stackoverflow.com/a/39518893
- Brightness https://raspberrypi.stackexchange.com/a/46229

@potter-91 
We should be able to do both in bash script, however, i'll need you to test it (lack the device, went for a cheaper IPS screen with higher resolution 😄)

Leave it with me, will let you know when its available in beta to test.

**Comment by Fourdee** [comment]
This ticket is completed.

Will open a new ticket for feature requests:
https://github.com/Fourdee/DietPi/issues/2169
