### ISSUE TITLE
RaspberryPi 3 | Add support and optimizations in DietPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#216]

**Comment by Fourdee** [comment]
#### Disable BCM 43438 (Wifi/Bluetooth)

https://www.raspberrypi.org/forums/viewtopic.php?p=919172#p919172

```
cat << _EOF_ > /etc/modprobe.d/disable_rpi3_bcm43438.conf
#wifi
blacklist brcmfmac
blacklist brcmutil
#bt
blacklist btbcm
blacklist hci_uart
_EOF_
```

#### Bluetoothctl:

https://www.raspberrypi.org/forums/viewtopic.php?p=919261#p919261

**Comment by rhkean** [comment]
Is this shaping up to be a separate image file or will it be an RPi1/2/3 image?

**Comment by Fourdee** [comment]
@rhkean
Same image to support all RPi devices. But if you want RPiv3 support, you will need to use the updated "v111 DietPi RPi-Jessie image" (when its released).

The DietPi Wheezy image will not support RPiv3. For now anyway, trying to save unnecessary workload.

**Comment by Fourdee** [comment]
Completed. RPiv3 image : http://dietpi.com/downloads/images/DietPi_RPi-(Jessie).7z
