### ISSUE TITLE
Docker Failing Install During DietPi Installation

### ISSUE THREAD

**Issue by dezren39** [MichaIng/DietPi#2161]
## Creating a bug report/issue:
I recently attempted to take a copy of DietPi and install Docker. This failed, and so I'll attached the messages below. My only modifications to the DietPi config file were for locatalization, to 'auto-install' without user interference, infinite wait on network and to install Docker at the very bottom. I'll also attach this config file. It appears some module for the kernel may be missing, though I haven't been able to ascertain much more than that.

#### Required Information:
- DietPi version	| 6.16
- Distro version	| 9.5
- Kernel version	| Linux f3-cluster 4.4.49-s5p6818 #1 SMP PREEMPT Wed May 9 14:01:02 CST 2018 armv7l GNU/Linux
- SBC device		| NanoPi M3/T3/F3 (armv7l)
- Power supply used	| 5V 2.5A per Port, 12A max, 6-Ports 
- SDcard used		| Generic 16gb, first formatting, Etcher writes at ~10MB/sec verifies at ~20mb/sec

#### Additional Information (if applicable):
- Software title	| Docker
- Was the software title installed freshly or updated/migrated?
- Freshly
- Can this issue be replicated on a fresh installation of DietPi?
- Yes, but when I run dietpi-bugreport I obtain the following:
```
root@f3-cluster:~# dietpi-bugreport
[  OK  ] DietPi-Bugreport | Root access verified.
[  OK  ] DietPi-Bugreport | RootFS R/W access verified.

[ INFO ] DietPi-Bugreport | Lines required for Whiptail box and its contents (y=61, z=0), exceeds screen dimensions (y=40).
[ INFO ] DietPi-Bugreport | Lines required for Whiptail box and its contents (y=61, z=0), exceeds screen dimensions (y=40).
Warning: rc-local.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[ INFO ] DietPi-Bugreport | Packing upload archive, please wait...
[  OK  ] DietPi-Bugreport | Connection test: ssh.dietpi.com
stat: cannot stat 'ffb1dd3a-80b7-4fdc-947f-700c2212c26a.7z': No such file or directory
/DietPi/dietpi/dietpi-bugreport: line 153: ((: <= 10000000 : syntax error: operand expected (error token is "<= 10000000 ")
[FAILED] DietPi-Bugreport | The bug report upload archive appears to be unexpected large. Please inspect and in case clean up the locations to be uploaded, as their size should never be that large:
CMD_OUT.txt
G_ERROR_HANDLER_GITREPORT
/var/log/*
/DietPi/*
/boot/dietpi.txt
/boot/config.txt
/boot/dietpi/*
/tmp/.G*
/var/tmp/dietpi/logs/*
/var/lib/dietpi/*
/etc/bash.bashrc
/etc/bashrc.d/*
/root/.bashrc
/home/*/.bashrc
/etc/profile
/etc/profile.d/*
/root/.profile
/home/*/.profile
/etc/rc.local
/etc/X11/xorg.conf
/etc/asound.conf
/etc/network/interfaces
/etc/fstab
/etc/sysctl.conf
/etc/sysctl.d/*
/etc/init.d/*
/etc/systemd/system/*
/lib/systemd/system/*
/etc/apt/sources.list
/etc/apt/sources.list.d/*
root@f3-cluster:~#
```
[2018-10-21_journalctl_copied.txt](https://github.com/Fourdee/DietPi/files/2499778/2018-10-21_journalctl_copied.txt)

#### Steps to reproduce:
1. Format SD Card with most recent DietPi
2. Replace DietPi.txt config file with the file to be attached.
3. Power on the Fire3 with the SD card on a DHCP-enabled network with internet.

#### Expected behaviour:
- Device obtains IP, boots, installs all dependencies and updates, installs Docker, Docker service can be started.

#### Actual behaviour:
- Device obtains IP, boots, installs all dependencies and updates, fails to install Docker, showing error messages, `docker` command becomes available but Docker service cannot be started. `service docker start` produces similar output to the error output when the initial install fails.

#### Extra details:
- [2018-10-21_journalctl_copied.txt](https://github.com/Fourdee/DietPi/files/2499778/2018-10-21_journalctl_copied.txt) Attached is my install/config file and a copy of executing `journalctl -xe`. I'd be happy help with debugging this if there is anything you'd like me to try or if there were something I'm doing wrong. I'm hoping that these boards are at least capable of using Docker as that is what I bought them for and they are using a new enough kernel. LMK what I can do to help.

**Comment by dezren39** [comment]
[dietpi.txt](https://github.com/Fourdee/DietPi/files/2499784/dietpi.txt)

**Comment by Fourdee** [comment]
Dupe of https://github.com/Fourdee/DietPi/issues/2163 due to Github SQL failure
