### ISSUE TITLE
DietPi Virtualbox VM Root Filesystem

### ISSUE THREAD

**Issue by louisefindlay23** [MichaIng/DietPi#2165]
Using the DietPi .ova file, I can't allocate more than 8 GBs to the root filesystem so I get out of space errors.

**Comment by MichaIng** [comment]
You need to adjust it in the virtual machines settings, where you can also adjust RAM, CPU count (e.g. match your host machines CPU/thread count) network etc.

**Comment by louisefindlay23** [comment]
I don't see where because any new storage device I add is a different drive and where the option is to alter the DietPi_VirtualBox drive size.

![image](https://user-images.githubusercontent.com/26024131/47303598-42074080-d61c-11e8-9cf0-9e30ca76566f.png)

**Comment by MichaIng** [comment]
Ah sorry I was mistaken, it's in the virtual drive manager, so not the VM tab of the GUI. Switch at the top right, there you see a tree structure of the virtual drives and when selecting one way the bottom you can adjust their sizes.
I am not at home currently, still post some screens later, if you didn't find it yet.

**Comment by louisefindlay23** [comment]
Thanks. I never realised that was there. I tried it but got this error 

Result Code: | VBOX_E_NOT_SUPPORTED (0x80BB0009)
-- | --
Component: | MediumWrap
Interface: | IMedium {4afe423b-43e0-e9d0-82e8-ceb307940dda}

**Comment by louisefindlay23** [comment]
I ended up converting it to .vdi by this [guide](https://stackoverflow.com/questions/11659005/how-to-resize-a-virtualbox-vmdk-file) which then let me resize it and then dietpi-drive_manager let me resize the drive. Thanks for your help
