### ISSUE TITLE
Getty service required for Mainline Kernel on ttyS2 (NanoPC-T4)

### ISSUE THREAD

**Issue by carlosedp** [MichaIng/DietPi#2168]
I have a DietPi deployment on a NanoPC-T4 and working on compiling the latest Mainline Kernel. The RK3399 boards have the serial UART on ttyS2 but after boot, the serial console does not accept input.

I had to create a getty service for the port and after this, it worked:

```bash
sudo cp /usr/lib/systemd/system/serial-getty@.service /etc/systemd/system/serial-getty@ttyS2.service
sudo sed s/'^ExecStart.*'/'ExecStart=-\/sbin\/agetty --keep-baud 1500000 %I $TERM'/g  -i /etc/systemd/system/serial-getty@ttyS2.service
ln -s /etc/systemd/system/serial-getty@ttyS2.service /etc/systemd/system/getty.target.wants/

systemctl daemon-reload
systemctl start serial-getty@ttyS2.service
systemctl enable serial-getty@ttyS2.service

```

Don't know if it's a mainline quirk. My Kernel boot params are:

`append earlycon=uart8250,mmio32,0xff1a0000 console=ttyS2,1500000n8 rw root=/dev/mmcblk2p5 rootwait rootfstype=ext4 init=/sbin/init`

**Comment by Fourdee** [comment]
@carlosedp 

Hi,

By default, DietPi disables serial console after 1st run setup to save on resources.

To change this, you'll need to either edit:
- ```CONFIG_SERIAL_CONSOLE_ENABLE=1``` in ```dietpi.txt``` before 1st run (tricky with this board)
- Enable it in ```dietpi-config``` > advanced > serial console.

Or run the commands you listed above for manual enable 😄

**Comment by MichaIng** [comment]
I mark as closed, since question has been answered. I aim to add such info to our Wiki, so how fresh DietPi systems behave different and which features are not enabled by default: https://github.com/MichaIng/DietPi/wiki
