### ISSUE TITLE
RPi Touchscreen | Support brightness change

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2169]
> https://github.com/Fourdee/DietPi/issues/2158#issuecomment-431978189

**Comment by docgalaxyblock** [comment]
Another idea
A new section in dietpi-software, named Chromium default page (or something else)
There you could choose which site would be the start page of chromium.

I use chromium for octoprint
And you could choose between the dietpi-optimized-softwares and a custum way.

**Comment by Atavic** [comment]
But the homepage is set inside chromium.

**Comment by Fourdee** [comment]
@potter-91 

Currently, you can set the homepage by changing ```URL=${CHROMIUM_URL:-"http://google.com"}``` in:
```
/var/lib/dietpi/dietpi-software/installed/chromium-autostart.sh
```

But not a bad idea for us to add an option to set this during autostart 👍 

---

🈯️ Page loads, lasts 5 seconds, then:
🈴 
![img_20181023_182722](https://user-images.githubusercontent.com/7077026/47379263-4c940980-d6f2-11e8-9bcc-84e08ee7be61.jpg)
- 🈯️ Unsure of cause, fresh install of both Chromium + LXDE is fine

**Comment by Fourdee** [comment]
Completed.

Autohide X11 cursor option will require a new ticket + enough user interest to warrant our implantation.
