### ISSUE TITLE
Unable to install opens

### ISSUE THREAD

**Issue by acrd-co** [MichaIng/DietPi#2170]
#### Details:
- Date           | Wed 24 Oct 08:36:14 BST 2018
- Bug report     | N/A
- DietPi version | v6.16
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B+ (armv7l) (index=3)
- Kernel version | #1145 SMP Fri Sep 21 15:38:35 BST 2018
- Distro         | stretch (index=4)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. launch dietpi-software
2. change ssh server to openssh instead of dropbear

#### Expected behaviour:

- installation should complete

#### Actual behaviour:

- error messages and is unable to continue

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up openssh-server (1:7.4p1-10+deb9u4) ...
Job for ssh.service failed because the control process exited with error code.
See "systemctl status ssh.service" and "journalctl -xe" for details.
invoke-rc.d: initscript ssh, action "start" failed.

**Comment by MichaIng** [comment]
Close due to duplicate: https://github.com/Fourdee/DietPi/issues/2171
