### ISSUE TITLE
DietPi-Software | SABnzbd: Switch to user "dietpi"?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2172]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5175

Did we forget it or was there a reason to still run it as root?

Current systemd unit:
https://github.com/Fourdee/DietPi/blob/dev/dietpi/dietpi-software#L11319-L11329
```
cat << _EOF_ > /etc/systemd/system/sabnzbd.service
[Unit]
Description=sabnzbd DietPi
[Service]
Type=simple
ExecStart=/usr/bin/python /etc/sabnzbd/SABnzbd.py -f /etc/sabnzbd/sabnzbd.ini
[Install]
WantedBy=multi-user.target
_EOF_
```

**Comment by Fourdee** [comment]
@MichaIng 

Looks like it got missed 👍 

Will make change, test and send commit if passes.

**Comment by Fourdee** [comment]
- 🈯️ Install + GUI tests passed. 
- Just need to test actual nzb use.

**Comment by MichaIng** [comment]
@Fourdee 
Is there a possibility to force umask=0002 or 0007 as well, so other media software (+network shares/drives) have write access as well?

**Comment by Fourdee** [comment]
```
root@DietPi:~# ls -lha /mnt/dietpi_userdata/downloads/complete/
total 12K
drwxr-xr-x 3 sabnzbd dietpi 4.0K Oct 24 14:59 .
drwxrwxr-x 6 dietpi  dietpi 4.0K Oct 24 14:59 ..
drwxr-xr-x 2 sabnzbd dietpi 4.0K Oct 24 14:59 18081905 test.nfo
```

@MichaIng 

> mask

Unable to find any entries matching 'mask' in ```/etc/sabnzbd/sabnzbd.ini```, or in GUI pages

---

?
```
permissions = ""
```

https://sabnzbd.org/wiki/advanced/unix-permissions

**Comment by Fourdee** [comment]
```
G_CONFIG_INJECT 'permissions =' 'permissions = "0775"' /etc/sabnzbd/sabnzbd.ini
```

download nzb

- 🈯️ 

```
root@DietPi:~# ls -lha /mnt/dietpi_userdata/downloads/complete/                 total 20K
drwxrwxrwx 5 sabnzbd dietpi 4.0K Oct 24 15:11 .
drwxrwxrwx 6 dietpi  dietpi 4.0K Oct 24 14:59 ..
drwxrwxr-x 2 sabnzbd dietpi 4.0K Oct 24 15:11 test.rar
```

**Comment by Fourdee** [comment]
> so other media software has write access as well?

@MichaIng 

done 775 for now, allows group r/w under dietpi, think we need 777?

777 Not required. Tested samba removal fine.
