### ISSUE TITLE
Nextcloud | Rpi3 | Fails to install

### ISSUE THREAD

**Issue by tesseract241** [MichaIng/DietPi#2189]
- DietPi version	| VERSIONE_CORE=6 VERSION_SUB=17 VERSION:_RC=12 BRANCH=master OWNER=Fourdee
- Distro version	| stretch
- Kernel version	| 4.14.71.v7+
- SBC device		| RPi3 Model B+
- Power supply used	USB 3.0
- SDcard used		| No name SD

- Software title	| Nextcloud
- Fresh installation of both Dietpi and Nextcloud

#### Steps to reproduce:
On a fresh installation of Dietpi installing Nextcloud fails because the php class "Memcached", used at line 1156 of /var/www/nextcloud/config/Config.php is not defined.  
After installing php-memcached through "apt-get install php-memcached" another error comes up:
MYSQL_ATTR_SSL_CA is not defined at line  in file  
This is again solved by installing php-mysql through apt.  
Finally, the installation fails giving first a warning that fileperms returns a failure at line 137  in /var/www/nextcloud/lib/private/Log/File.php, which uses that function on /var/www/nextcloud/data/log-php (the 'data' folder doesn't exist) and then an error an unhandled expeption is thrown: "Doctrine\DBAL\DBALException: Failed to connect to the database: an expetion occured in driver: could not find driver in /var/www/nextcloud/lib/private/DBN/Connection.php:64 "

#### Expected behaviour:
First off, the php-memcached and php-mysql modules should be installed or the nextcloud installation should be configured not to need them.  
After that, I don't know what that error actually means, but the end result should be a functioning nextcloud installation.

**Comment by MichaIng** [comment]
@tesseract241 
Thanks for your report.

However check existing issues please 😉: https://github.com/Fourdee/DietPi/issues/2184

To fix it quickly, run the following:
```
sed -i "\|cp '/var/www/nextcloud/config/config.sample.php'|d" /DietPi/dietpi/dietpi-software
rm /var/www/nextcloud/config/config.php
rm /var/www/nextcloud/occ
dietpi-software install 114
```
- The last command will rerun Nextcloud installation.

Sorry for the breakfix our side, it is resolved for v6.18, which you can also already apply via beta: https://github.com/Fourdee/DietPi/blob/master/BRANCH_SYSTEM.md

I mark this as closed, if still any issues, please reply to the other opened issue.
