### ISSUE TITLE
[dupe] DietPi-Software - Failed to auto install either ownCloud or Nextcloud 

### ISSUE THREAD

**Issue by v1rot-8** [MichaIng/DietPi#2203]
#### Details:
- Date           | Wed 31 Oct 17:53:30 NZDT 2018
- Bug report     | N/A
- DietPi version | v6.17.12 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 2 Model B (armv7l) (index=2)
- Kernel version | #1145 SMP Fri Sep 21 15:38:35 BST 2018
- Distro         | stretch (index=4)
- Command        | ncc maintenance:install
- Exit code      | 1
- Software title | DietPi-Software

#### Steps to reproduce:

1. ... Selected either of these 2 options and fault occured.
2. ...

#### Expected behaviour:

- ... Either of these installs should complete

#### Actual behaviour:

- ... Produced this report and returned me to the prompt.

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
An unhandled exception has been thrown:
Error: Class 'Memcached' not found in /var/www/nextcloud/config/config.php:1156
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(214): include()
#1 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#2 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#3 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#4 /var/www/nextcloud/lib/base.php(1068): OC::init()
#5 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#7 {main}
```

**Comment by Fourdee** [comment]
@v1rot-8 

Thanks for the report 👍 

This is a known issue, fixed in next release: https://github.com/Fourdee/DietPi/issues/2184
Also available in Beta:
https://github.com/Fourdee/DietPi/blob/master/BRANCH_SYSTEM.md#steps-to-use-the-dietpi-beta-branch
