### ISSUE TITLE
Nextcloud - install error

### ISSUE THREAD

**Issue by matbar87** [MichaIng/DietPi#2207]
#### Details:
- Date           | Wed 31 Oct 18:34:21 CET 2018
- Bug report     | N/A
- DietPi version | v6.17.12 (Fourdee/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | RPi 3 Model B+ (armv7l) (index=3)
- Kernel version | #1141 SMP Mon Sep 10 15:26:29 BST 2018
- Distro         | stretch (index=4)
- Command        | ncc maintenance:mode --on
- Exit code      | 1
- Software title | DietPi-Services

#### Steps to reproduce:

1. dietpi-software -> check Nextcloud on Software Optimized list 
2. Install

#### Expected behaviour:

- Nextcloud installed

#### Actual behaviour:

- after configuring in installation, there is an error

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
An unhandled exception has been thrown:
Error: Class 'Memcached' not found in /var/www/nextcloud/config/config.php:1156
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(214): include()
#1 /var/www/nextcloud/lib/private/Config.php(63): OC\Config->readData()
#2 /var/www/nextcloud/lib/base.php(140): OC\Config->__construct('/var/www/nextcl...')
#3 /var/www/nextcloud/lib/base.php(591): OC::initPaths()
#4 /var/www/nextcloud/lib/base.php(1068): OC::init()
#5 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#7 {main}
```

**Comment by MichaIng** [comment]
Thanks for the report. Jep it's a known issue, please check to resolve: https://github.com/Fourdee/DietPi/issues/2192
I mark this as closed.
