### ISSUE TITLE
Unable to update Roon Bridge

### ISSUE THREAD

**Issue by Kreeblah** [MichaIng/DietPi#2209]
#### Required Information:
- DietPi version	| 6.17
- Distro version	| stretch
- Kernel version	| Linux odroidc2-2 3.16.56+ #1 SMP PREEMPT Wed Apr 18 16:59:34 CEST 2018 aarch64 GNU/Linux
- SBC device		| Odroid C2 (aarch64)
- Power supply used	| https://ameridroid.com/products/5v-2a-power-supply
- SDcard used		| https://ameridroid.com/products/emmc-black-module-c2-linux-red-box?variant=7245907460130

#### Additional Information (if applicable):
- Software title	| Roon Bridge
- Was the software title installed freshly or updated/migrated? Both
- Can this issue be replicated on a fresh installation of DietPi? Unknown as of yet
- Bug report: ddce5205-bb46-48c6-b6a9-39dd074f93a8

#### Steps to reproduce:

1. Install the Roon Bridge software from the DietPi optimized library (it pulls from the latest tarball hosted on the Roon site, which at the time of filing this is currently an outdated version)
2. Load a copy of the Roon controller software on another computer and make sure it finds the Roon bridge
3. See that there's an update from build 164 of the Roon Bridge software to 167
4. Attempt to update through Roon

#### Expected behaviour:

- The update should complete and the Roon Bridge app should restart.  This used to happen.

#### Actual behaviour:

- After downloading and attempting to install the Roon Bridge software, Roon gives the following error: "There was an error checking for an update."

#### Extra details:

- I thought this might be related to the dietpi user/group owning /etc/roonbridge, so I changed the group for that directory and everything in it to roon and added group write privileges, but that didn't help.

**Comment by MichaIng** [comment]
@Kreeblah
Thanks for your report. I mark for investigation and try to replicate.

#### From bugreport
Service status:
```
Nov 01 05:02:49 odroidc2-2 systemd[1]: Started Roon Bridge.
Nov 01 05:02:49 odroidc2-2 start.sh[1010]: /etc/roonbridge/Bridge/RoonBridge: 40: ulimit: error setting limit (Operation not permitted)
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: 00:00:00.005 Trace: [childprocess] using unix child process
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: Initializing
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: 00:00:00.236 Info:  Starting /etc/roonbridge/Bridge/RoonBridgeHelper
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: 00:00:00.249 Info:  ConnectOrStartAndWaitForExit RAATServer
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: /etc/roonbridge/Bridge/RoonBridgeHelper: 40: ulimit: error setting limit (Operation not permitted)
Nov 01 05:02:50 odroidc2-2 start.sh[1010]: Not Running (.o)
Nov 01 05:02:51 odroidc2-2 start.sh[1010]: Running
Nov 01 05:02:51 odroidc2-2 start.sh[1010]: /etc/roonbridge/Bridge/RAATServer: 40: ulimit: error setting limit (Operation not permitted)
```
RoonBridge log:
```
11/01 06:02:49 Trace: [rnet/RnetJsonServer] [client XXX.XXX.XXX.XXX:XXXXX] GOT {"request":"updates_subscribe"}
11/01 06:02:49 Trace: [rnet/RnetJsonServer] [client XXX.XXX.XXX.XXX:XXXXX] SENT NONFINAL {"status":"Success","updates":{"is_supported":true,"status":"Error","progress":null,"current_version":{"machine_value":100000164,"branch":"stable","di$
11/01 06:04:01 Warn: Error in web request https://push.roonlabs.com/push/1/connect: NetworkError (System.Net.WebException: Error: ConnectFailure (TLS Support not available.) ---> System.NotSupportedException: TLS Support not available. $
  at Mono.Net.Security.MonoTlsProviderFactory.LookupProviderType (System.String name, System.Boolean throwOnError) [0x00032] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsProviderFactory.LookupProvider (System.String name, System.Boolean throwOnError) [0x00000] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsProviderFactory.TryDynamicLoad () [0x00019] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsProviderFactory.CreateDefaultProviderImpl () [0x00000] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsProviderFactory.InitializeInternal () [0x0001a] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
   --- End of inner exception stack trace ---
  at Mono.Net.Security.MonoTlsProviderFactory.InitializeInternal () [0x0002e] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsProviderFactory.GetProviderInternal () [0x00010] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Mono.Net.Security.MonoTlsStream..ctor (System.Net.HttpWebRequest request, System.Net.Sockets.NetworkStream networkStream) [0x00027] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at System.Net.WebConnection.CreateStream (System.Net.HttpWebRequest request) [0x00066] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <b6534a6184ef4469b91bfdbb8f0fde19>:0
  at Sooloos.HttpClient+<>c__DisplayClass10_1.<POST>b__1 (System.IAsyncResult req_ar) [0x00000] in <07742387b3d246d6a69506235c76ed38>:0 )
11/01 06:04:01 Trace: [push] request to manager failed
11/01 06:04:01 Trace: [push] retrying connection in 1125603ms
```

**Comment by MichaIng** [comment]
@Kreeblah 
<s>Hard to test it here, since I have no RoonServer. Fresh install works fine.
The internal updater does an initial update check, but doesn't find one:
```
11/03 20:30:24 Trace: [appupdater] initial check for updates
11/03 20:30:24 Debug: [base/updater] Checking for updates: http://updates.roonlabs.com/update/?v=2&serial=B32B3A54-2F3A-45E4-A852-5C0F89F30A7C&userid=&platform$
11/03 20:30:25 Debug: [appupdater] Update not needed
```
So strange that in your case it is not the current version. In my case it's x86_64, but same tarball source. Perhaps they forgot or somehow broke the ARMv8 (arm64) package?
You can simply reinstall RoonBridge via `dietpi-software reinstall 121`. It will purge the old install dir (not configs etc.) and place the new one. But if you did a fresh install anyway, then this is only something to test later and hope that then the tarball was updated.

Your error logs contain an error about TLS not being available when attempting update. Did you somehow enable TLS on RoonServer or -Brige?
If it's only about accessing the update server via TLS, this should be covered by the pre-installed encryption related packages on DietPi 🤔.

In case someone with same or at least ARMv8 device need to try replicate. @Fourdee if you find time? 🙂
 
If older tarballs are available, we can also check update procedure on other devices. I will check and try in case.
€: Hmm can't find older tarballs: http://kb.roonlabs.com/LinuxInstall

> I thought this might be related to the dietpi user/group owning /etc/roonbridge, so I changed the group for that directory and everything in it to roon and added group write privileges, but that didn't help.

Hmm, the service runs as `root:dietpi` to keep e.g. media files handled accessible for other software titles. For consistency the...</s>

Wait...

**Comment by MichaIng** [comment]
@Kreeblah @Fourdee 
Ah lol sorry just found the fix that was already done by Fourdee: https://github.com/Fourdee/DietPi/commit/264709280064c3e595bcbd725ea0049bbec59f01 👍 🎆 

Only the change to the `roonbridge.service` is required (run as root user). Then
```
systemctl daemon-reload
systemctl restart roonbridge
```

I guess RoonBridge bind to TLS port fails, if not running with root permissions.

**Comment by Kreeblah** [comment]
I already uninstalled/reinstalled the Roon Bridge package, which installed the current version, so I'll have to wait until the next time there's an update for it before I can test and report back.

Thanks for looking into this!

**Comment by Fourdee** [comment]
Yep, resolved in our next release:
https://community.roonlabs.com/t/dietpi-allo-units-not-getting-the-roonbridge-b167-update-from-b164/52503/10?u=dan_knight

#### Workaround until v6.18
```
dietpi-software reinstall 121
```

**Comment by blogabe** [comment]
I also had this issue and resolved it with the ^above^ reinstall command.  Can confirm it worked for me, but I also received this message:
```
...
Mode: Installation completed

[ SUB1 ] DietPi-Services > start
[  OK  ] DietPi-Services | start : avahi-daemon
[  OK  ] DietPi-Services | start : nmbd
[  OK  ] DietPi-Services | start : smbd
[  OK  ] DietPi-Services | start : mysql
[  OK  ] DietPi-Services | start : php7.0-fpm
[  OK  ] DietPi-Services | start : lighttpd
[  OK  ] DietPi-Services | start : mpd
[  OK  ] DietPi-Services | start : shairport-sync
[  OK  ] DietPi-Services | start : squeezelite
[  OK  ] DietPi-Services | start : gmrender
[  OK  ] DietPi-Services | start : networkaudiod
[  OK  ] DietPi-Services | start : roonbridge
[  OK  ] DietPi-Services | start : netdata
[  OK  ] DietPi-Services | start : cron
[ SUB2 ] DietPi-Process_tool > Apply
[FAILED] DietPi-Process_tool | NetData (32324) : Nice      0
[FAILED] DietPi-Process_tool | NetData (32324) : Scheduler SCHED_OTHER 0
[FAILED] DietPi-Process_tool | NetData (32325) : Nice      0
[FAILED] DietPi-Process_tool | NetData (32325) : Scheduler SCHED_OTHER 0
[FAILED] DietPi-Process_tool | An issue has occurred
```
