### ISSUE TITLE
DietPi-Config | Always shows en_G + Plex media server doesn't start

### ISSUE THREAD

**Issue by Lanneer487** [MichaIng/DietPi#2216]
I have a fully updated system but today my plex server wont start.
when I look for the service status I get a failed status.
<img width="1920" alt="schermafbeelding 2018-11-03 om 14 54 23" src="https://user-images.githubusercontent.com/9874656/47953081-8083f000-df78-11e8-8bc4-5821b59d0361.png">
someone knows how to fix this?

**Comment by MichaIng** [comment]
@roelfoubert 
Thanks for your report.
Could you please check the full log when attempting to start:
```
systemctl start plexmediaserver
sleep 5
journalctl -r
```
This shows the full syslog output in reverse order, newest at the top, so you don't need to scroll to bottom 😉.

**Comment by Lanneer487** [comment]
Nov 03 15:04:15 raspberrypi systemd[1]: plexmediaserver.service: Failed with result 'exit-code'.
Nov 03 15:04:15 raspberrypi systemd[1]: plexmediaserver.service: Unit entered failed state.
Nov 03 15:04:15 raspberrypi systemd[1]: Failed to start Plex Media Server for Linux.
Nov 03 15:04:15 raspberrypi systemd[1]: plexmediaserver.service: Start request repeated too quickly.
Nov 03 15:04:15 raspberrypi systemd[1]: Stopped Plex Media Server for Linux.
Nov 03 15:04:15 raspberrypi systemd[1]: plexmediaserver.service: Service hold-off time over, scheduling restart.
Nov 03 15:04:10 raspberrypi systemd[1]: plexmediaserver.service: Failed with result 'exit-code'.
Nov 03 15:04:10 raspberrypi systemd[1]: plexmediaserver.service: Unit entered failed state.
Nov 03 15:04:10 raspberrypi systemd[1]: plexmediaserver.service: Main process exited, code=exited, status=255/n/a
Nov 03 15:04:09 raspberrypi systemd[1]: Started Plex Media Server for Linux.
Nov 03 15:04:09 raspberrypi systemd[1]: Starting Plex Media Server for Linux...
Nov 03 15:04:09 raspberrypi systemd[1]: Stopped Plex Media Server for Linux.
Nov 03 15:04:09 raspberrypi systemd[1]: plexmediaserver.service: Service hold-off time over, scheduling restart.
Nov 03 15:04:04 raspberrypi systemd[1]: plexmediaserver.service: Failed with result 'exit-code'.
Nov 03 15:04:04 raspberrypi systemd[1]: plexmediaserver.service: Unit entered failed state.
Nov 03 15:04:04 raspberrypi systemd[1]: plexmediaserver.service: Main process exited, code=exited, status=255/n/a
Nov 03 15:04:03 raspberrypi systemd[1]: Started Plex Media Server for Linux.
Nov 03 15:04:03 raspberrypi systemd[1]: Starting Plex Media Server for Linux...
Nov 03 15:04:03 raspberrypi systemd[1]: Stopped Plex Media Server for Linux.
Nov 03 15:04:03 raspberrypi systemd[1]: plexmediaserver.service: Service hold-off time over, scheduling restart.
Nov 03 15:03:58 raspberrypi systemd[1]: plexmediaserver.service: Failed with result 'exit-code'.
Nov 03 15:03:58 raspberrypi systemd[1]: plexmediaserver.service: Unit entered failed state.
Nov 03 15:03:58 raspberrypi systemd[1]: plexmediaserver.service: Main process exited, code=exited, status=255/n/a
Nov 03 15:03:57 raspberrypi systemd[1]: Started Plex Media Server for Linux.
Nov 03 15:03:57 raspberrypi systemd[1]: Starting Plex Media Server for Linux...

**Comment by MichaIng** [comment]
@roelfoubert 
Okay this just shows the 5 repeating startup attempts from systemd 🤔.

We need some Plex internal log. If you can find this somewhere would be great, but I will also set it up and check.

**Comment by MichaIng** [comment]
Okay works fine here. Logs were hard to find, but here it is:
`/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.log`

This is the best start, I guess, but the same folder contains more logs for the sub processes. Check for this  for ERROR messages, e.g. `grep 'ERROR' /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs/*`
This then hopefully gives a hint.

**Comment by Lanneer487** [comment]
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.2.log:Mar 28, 2018 01:37:13.414 [0x75357140] ERROR - Couldn't rename file "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.dlna-new.db-shm" to "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.dlna.db-shm": No such file or directory
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex DLNA Server.2.log:Mar 28, 2018 01:37:13.414 [0x75357140] ERROR - Couldn't rename file "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.dlna-new.db-wal" to "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.dlna.db-wal": No such file or directory
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner Analysis.1.log:Jul 13, 2018 21:15:45.590 [0x73158400] ERROR - [FFMPEG] - Valid timecode frame rate must be specified. Minimum value is 1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner Analysis.1.log:Jul 13, 2018 21:15:46.865 [0x73158400] ERROR - [FFMPEG] - Valid timecode frame rate must be specified. Minimum value is 1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner Analysis.1.log:Jul 13, 2018 21:15:48.468 [0x73158400] ERROR - [FFMPEG] - Valid timecode frame rate must be specified. Minimum value is 1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner Analysis.1.log:Jul 13, 2018 21:15:49.819 [0x73158400] ERROR - [FFMPEG] - Valid timecode frame rate must be specified. Minimum value is 1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner Analysis.1.log:Jul 13, 2018 21:17:11.487 [0x73158400] ERROR - [FFMPEG] - Valid timecode frame rate must be specified. Minimum value is 1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:12.587 [0x732ff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:12.587 [0x732ff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:12.588 [0x732ff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:17.443 [0x6daff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:19.380 [0x6a8ff400] ERROR - QueryParser: Invalid field 'onlyTransient' found, ignoring.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:23.640 [0x698ff400] ERROR - [PlexRelay] kex protocol error: type 7 seq 11
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.1.log:Jul 29, 2018 17:45:52.029 [0x706ff400] ERROR - Extras: Preroll file didn't exist or couldn't be read: ''.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.2.log:Jul 29, 2018 17:42:44.869 [0x731ff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.2.log:Jul 29, 2018 17:42:44.869 [0x731ff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.2.log:Jul 29, 2018 17:42:44.879 [0x731ff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.2.log:Jul 29, 2018 17:42:52.219 [0x6d9ff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.2.log:Jul 29, 2018 17:43:38.357 [0x6fcff400] ERROR - [PlexRelay] kex protocol error: type 7 seq 11
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.3.log:Jul 29, 2018 16:35:26.302 [0x718ff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.3.log:Jul 29, 2018 16:35:26.305 [0x718ff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.3.log:Jul 29, 2018 16:35:26.305 [0x718ff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.3.log:Jul 29, 2018 16:35:41.998 [0x6d2ff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.3.log:Jul 29, 2018 16:36:18.372 [0x6d2ff400] ERROR - Network Service: Error in advertiser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:32:31.486 [0x717ff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:32:31.487 [0x717ff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:32:31.526 [0x717ff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:33:04.622 [0x6d2ff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:34:10.482 [0x66aff400] ERROR - Timeout or error reading status line from plug-in pipe [com.plexapp.agents.imdb], we're killing it.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:34:10.482 [0x66aff400] ERROR - Error received reading configuration for com.plexapp.agents.imdb
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:34:10.483 [0x66aff400] ERROR - downloadContainer: expected MediaContainer element, found html
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.4.log:Jul 29, 2018 16:34:10.483 [0x66aff400] ERROR - IVA: failed to get IMDB prefs
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.5.log:Jul 29, 2018 16:29:16.071 [0x70fff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.5.log:Jul 29, 2018 16:29:16.072 [0x70fff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.5.log:Jul 29, 2018 16:29:16.085 [0x70fff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.5.log:Jul 29, 2018 16:29:40.293 [0x717ff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.5.log:Jul 29, 2018 16:30:51.671 [0x717ff400] ERROR - Network Service: Error in advertiser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:01:32.017 [0x718ff400] ERROR - Error issuing curl_easy_perform(handle): 7
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:01:32.018 [0x718ff400] ERROR - Error parsing content.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:01:32.023 [0x718ff400] ERROR - Error parsing XML.
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:01:40.469 [0x706ff400] ERROR - Network Service: Error in browser handle read: 125 (Operation canceled) socket=-1
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:02:06.502 [0x706ff400] ERROR - Network Service: Error in advertiser handle read: 125 (Operation canceled) socket=72
grep: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs: Is a directory

**Comment by MichaIng** [comment]
@roelfoubert 
Okay last ERROR from end of Juli, so this should not related 🤔:
```
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log:Jul 29, 2018 18:02:06.502 [0x706ff400] ERROR - Network Service: Error in advertiser handle read: 125 (Operation canceled) socket=72
grep: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs: Is a directory
```

Did the error actually appear after a `dietpi-update`, or do you remember something else that changed?

Also check the very last logs:
`tail /var/lib/plexmediaserver/Library/Application Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.log`

**Comment by Lanneer487** [comment]
yesterday it all works today I had a problem. the only thing it does is auto apt-get upgrade so maybe a bad upgrade?

**Comment by Lanneer487** [comment]
tail logs:
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 14.
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 15.
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 16.
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 17.
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 18.
Jul 29, 2018 18:02:06.544 [0x745ab0d0] DEBUG - Captured session 19.
Jul 29, 2018 18:02:06.603 [0x706ff400] INFO - Network Service: Abandoning advertise socket, it was closed.
Jul 29, 2018 18:02:06.617 [0x745ab0d0] DEBUG - Database: Shutting down.
Jul 29, 2018 18:02:06.617 [0x745ab0d0] DEBUG - Captured session 0.
Jul 29, 2018 18:02:06.617 [0x745ab0d0] DEBUG - Captured session 1.

**Comment by MichaIng** [comment]
@roelfoubert 
Possible. Which system logging mode did you choose? If you don't use dietpi-ramlog, could you check which packages were updated during this upgrade step? `/var/log/apt/term.log`
In case of dietpi-ramlog with storing logs before clearing, you would find them in /root/ directory.

Strange, the last log entries are from Jul 29, but your system time is correct according to screen above 🤔.

Just checked out install code. Did you change the locale on your system? Just checked out install code and found that locale needs to be en_US.UTF-8 on ARM devices.
@Fourdee 
We just apply US locale on interactive installs: https://github.com/Fourdee/DietPi/blob/dev/dietpi/dietpi-software#L10286
- I guess we should always apply it? G_WHIP_MSG already turns into simple [ INFO ] when G_USER_INPUTS=0.

**Comment by Lanneer487** [comment]
the timezone is correct
<img width="863" alt="schermafbeelding 2018-11-03 om 16 47 28" src="https://user-images.githubusercontent.com/9874656/47954246-4884a900-df88-11e8-8ca9-2919c3d222b0.png">

the log file:
root@raspberrypi:~# /var/log/apt/term.log
-bash: /var/log/apt/term.log: Permission denied

**Comment by MichaIng** [comment]
@roelfoubert 
```
root@raspberrypi:~# /var/log/apt/term.log
-bash: /var/log/apt/term.log: Permission denied
```
This tries to execute the log file 😉
Use `cat /var/log/apt/term.log` to fully output to terminal. But when not using ramlog this can be veeery much.
I mostly use `nano /var/log/apt/term.log` which opens the log in the editor which allows scrolling up and down.

Hmm your locale is en_GB, but according to our install script en_US is needed. Could you try to change that? Sadly I can't test here, as I use a VM for testing and this locale is only required for ARM devices (which use the Plex repo instead of manual package install).

**Comment by Lanneer487** [comment]
When I change to en_US it automatically changes to en_GB

**Comment by Lanneer487** [comment]
If you want I can give you remotely access to my pi

**Comment by Fourdee** [comment]
@MichaIng 

> We just apply US locale on interactive installs: https://github.com/Fourdee/DietPi/blob/dev/dietpi/dietpi-software#L10286
I guess we should always apply it?

Yep 👍, + ```G_WHIP_MSG 'Locale will be changed to en_US``` etc?

**Comment by Fourdee** [comment]
@roelfoubert @MichaIng 

> When I change to en_US it automatically changes to en_GB

confirmed, looking into it now.

---

dietpi-config reports en_GB, when:
```
root@DietPi:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Due to current bash session not reloading the locale vars.
We set en_GB in our scripts.

locale is applied to system correctly, visual issue our end.

**Comment by MichaIng** [comment]
@Fourdee 
Jep, I didn't check the reason for this, but if required then should not depend on interactive/noninteractive call.

@roelfoubert 
<s>Jep also just verified, locale change does not work 🤔.</s>

**Comment by Lanneer487** [comment]
I'm going to reinstall the pi on another micro sd card and restore a backup from before and see if it works

**Comment by MichaIng** [comment]
@Fourdee @roelfoubert 
Ah, actually locale changes. Check via `locale`
Just the wrong is shown in dietpi-config, since script internally en_GB is applied. We need to check either `/etc/default/locale` or dietpi.txt to get correct value 😉.

**Comment by Lanneer487** [comment]
After more testing it turned out to be a problem in the application support folder. When reinstalling plex and made a new server it works again

**Comment by MichaIng** [comment]
@roelfoubert 
Thanks for feedback. So there is noting we need to change with our Plex install code, so we can close the issue right?
Visual issue with locale is solved in current Beta.

**Comment by Fourdee** [comment]
> Visual issue with locale is solved in current Beta.

@MichaIng 

Yep, resolved in beta, completed.

Unable to replicate the Plex issue on fresh install.

---

@roelfoubert 

If the issue reoccurs, please reopen this ticket for further investigation.
