### ISSUE TITLE
RPi.GPIO | Broken by current kernel release (APT)?

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2218]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=9&t=5198
- [x] Replicate
- [x] ~Check if current master resolves it: `rpi-update`~
- [x] ~Hope for fast package/release update 😉.~

**Comment by MichaIng** [comment]
@Fourdee 
Found your answer on the forum. Have you been able to replicate, is it expected on current kernel/misconfiguration?

**Comment by Fourdee** [comment]
@MichaIng 

Will re-test, moved to milestone.

**Comment by Fourdee** [comment]
RPi install test:
- 🈯️ 
```
root@DietPi:~# uname -a
Linux DietPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```

Unable to test user specific script with reported issue, as, lacking the script itself.

Waiting for user response:
https://dietpi.com/phpbb/viewtopic.php?f=9&t=5198&p=15398#p15398

**Comment by Fourdee** [comment]
No response from user, will mark as closed. Will reopen if user replies.
