### ISSUE TITLE
DietPi-Software | Son/Rad/Lidarr: Create files/dirs with 664/775 permissions

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2220]
..to allow media software write access and file create permissions (e.g. subtitle downloads via Plex subzero plugin): https://github.com/Fourdee/DietPi/issues/2067#issuecomment-435624393

Hopefully this can be pre-configured, otherwise add info to online doc to change the settings accordingly.

**Comment by Fourdee** [comment]
Note to self:
- Under Settings > Media Management > Show advanced > Permissions
![image](https://user-images.githubusercontent.com/7077026/48566724-6987bb00-e8f3-11e8-99a8-52355a28e0ce.png)


Will try and find in cfg options
- ```/mnt/dietpi_userdata/sonarr/config.xml```? No info on this, or existing options visible. Will try backing up with the settings in place, then check.
- Does config.xml exist before 1st run? has a unique key generated by Sonarr during 1st run. Else, may be better as info on forum.

**Comment by MichaIng** [comment]
@Fourdee 
Searched Sonarr wiki, code and forum for a complete config.xml documentation, but just found articles/issues/code snippets about single settings 🤔.
Generally the settings seem to be stored within the SQLite database and only a few basic settings can be pre-set via config.xml.

We could also try to identify the related database table, or check CLI for config related commands, which would be safer indeed.

**Comment by Fourdee** [comment]
Ok, for now lets add this info the online docs:
- 🈯️ Sonarr
- 🈯️ Radarr
- 🈯️ Lidarr

arr arr arr 🤣

**Comment by Fourdee** [comment]
Will mark as completed. Cant see a viable way to automate this in our setup currently.
