### ISSUE TITLE
Nano Pi Fire 3 - No output on HDMI TTY1

### ISSUE THREAD

**Issue by okipol88** [MichaIng/DietPi#2225]
# Workaround: https://github.com/Fourdee/DietPi/issues/2225#issuecomment-436263111

---

#### Required Information:
- DietPi version	| N/A
- Distro version	|  N/A 
- Kernel version	|  N/A
- SBC device		|  Nano Pi Fire 3
- Power supply used	|  5V 3.1 A
- SDcard used		|  SanDisk Ultra 16 GB

#### Additional Information (if applicable):
- Flashed using Etcher 

#### Steps to reproduce:

1. Flash the image in **REMOVED OBSOLETE LINK** to SD card
2. Run on device

#### Expected behaviour:

- FriendlyArm Boot screen appears.
- DietPi boots.

#### Actual behaviour:

- FriendlyArm Boot screen appears .
- Black screen appears.
- DietPi does not boot.

#### Extra details:

- Caps lock does not work on the keyboard (no input to switch on the CapsLock LED indicator).
- Using DELL U2414H monitor
- Works fine with Armbian (not SBC fault)

**Comment by Fourdee** [comment]
@okipol88 

Thanks for the report, i'll try to replicate.

Please check the PCB for any revision codes, and, list them here if possible.

Also, are you able to SSH into the device over network, regardless of black screen on HDMI?

**Comment by Fourdee** [comment]
Issue with tty1.

After the system is booted switch to tty2:
CTRL+ALT+F2

**Comment by Fourdee** [comment]
Current:
```
Linux DietPi 4.4.49-s5p6818 #1 SMP PREEMPT Wed May 9 14:01:02 CST 2018 armv7l GNU/Linux
```

Tried the lastest image + dtb's from s5p6818-sd-friendlycore-xenial-4.4-armhf-20180906.img, same issue.

**Comment by Fourdee** [comment]
REF: https://github.com/Fourdee/DietPi/issues/1926#issuecomment-405736808

**Comment by Fourdee** [comment]
Works after boot, hangs system during boot.
```
systemctl start getty@tty1
chvt 1
```

**Comment by MichaIng** [comment]
@Fourdee 
Perhaps we can hardcode TTY2 use when NanoPi Fire 3 is detected (on DietPi-PREP)?
It this `'62' ': NanoPi M3/T3/F3'` or requires new hardware ID (e.g. free 54)?

But indeed a really strange issue... Why tty1 is disabled...

**Comment by okipol88** [comment]
@Fourdee Nice ;)
Would be much appreciated to add this info tfor all the dummies (like me or only me ;() to the download section on [DietPI website](https://dietpi.com) -> Download section.
I Think i did encounter the [REF](https://github.com/Fourdee/DietPi/issues/1926#issuecomment-405736808) for a brief moment. I did not associate it with this :/.

Many thanks ;). Will try it out.

**Comment by Fourdee** [comment]
@MichaIng 

Yep, we should be able to do during boot to switch tty2, i'll run some tests:
```
chvt 2
```

> It this '62' ': NanoPi M3/T3/F3' or requires new hardware ID (e.g. free 54)?

Shares same HW_MODEL as M3, we can try checking dmesg for loaded dts.

**Comment by Fourdee** [comment]
🈯️ during boot ```chvt 2```

~Issue is no hardware specific info in dmesg or ```lscpu``` that is unique.~
```
Machine model: FriendlyElec NanoPi Fire3
```
