### ISSUE TITLE
Network | IFB (intermediate functional block) support

### ISSUE THREAD

**Issue by bhpark84** [MichaIng/DietPi#2228]
Is there a way to use an ifb(intermediate functional block)?

I installed [fireQOS](https://firehol.org/tutorial/fireqos-new-user/) for traffic control.
It is useful because can give priority to each service.
However, an ifb network device is required to control incoming traffic.
I would kindly like to ask to enable the ifb.

Thanks you.

**Comment by MichaIng** [comment]
@bhpark84 
Thanks for your request.

Interesting topic. Requires a kernel module or function enabled: https://wiki.linuxfoundation.org/networking/ifb#ifb-requirements
Seems to be available on most current kernels, e.g. was added to Raspberry Pi kernel 5 years ago: https://github.com/raspberrypi/linux/issues/453

iproute2 seems to be a front-end, so generally should work. Needs investigation how this is applied best on adapter/interface basis. Most properly a dedicated GUI required, hopefully no changes to our current networking setup.

**Comment by MichaIng** [comment]
Looping through older issues. @bhpark84 is this still a topic for you? If so, which SBC are you using? On RPi and x86_64 systems. the following should work to enable the IFB kernel module temporarily:
```
modprobe ifb
```

To enable it permanently (if the above succeeeds):
```
echo 'ifb' > /etc/modules-load.d/ifb.conf
```

**Comment by bhpark84** [comment]
I use Odroid HC2.
I am not currently using FireQOS.
However, I checked it as follows.


root@DietPi: modprobe ifb
root@DietPi: modinfo ifb
filename:       /lib/modules/4.14.180+/kernel/drivers/net/ifb.ko
alias:          rtnl-link-ifb
author:         Jamal Hadi Salim
license:        GPL
depends:
intree:         Y
name:           ifb
vermagic:       4.14.180+ SMP preempt mod_unload ARMv7 p2v8
parm:           numifbs:Number of ifb devices (int)


Thanks for help.

**Comment by MichaIng** [comment]
Great, feel free to report back when it is not working as expected, then we can check back with kernel maintainers.
