### ISSUE TITLE
Question Re: Automated image builder workflow, no hardware required

### ISSUE THREAD

**Issue by spiderkeys** [MichaIng/DietPi#223]
My organization has been working with the Beaglebone Black for years now and we are used to building our custom Debian image on a remote build server which primarily uses chroot as the method of modifying the base image and getting all of the packages installed and updated. I was curious if there is an implemented/existing workflow for getting a DietPi image fully built and updated without having to burn the base image to an SD card, power it up, make sure it is connected to the internet, and run the update process? I saw the automatic configuration feature, but that just seems to cut out the manual config steps, still requiring me to use a physical RPi to update the image.

Thanks for any info!

P.s. Awesome work on DietPi; the base resource usage and boot times are impressive!

**Comment by Fourdee** [comment]
> P.s. Awesome work on DietPi; the base resource usage and boot times are impressive!

Thank you. Its good to hear. Alot of hard work has gone into making that possible :)

> I was curious if there is an implemented/existing workflow for getting a DietPi image fully built and updated without having to burn the base image to an SD card, power it up, make sure it is connected to the internet, and run the update process?

Currently, DietPi is designed to be used by the end user. A hardware device is required to complete the DietPi setup and installation.

When I create a DietPi image from scratch, I use an existing image (eg: Raspbian Jessie, and Merveric's Odroid images) and modify it to become the DietPi image. I do not currently build or compile the images.

All I can offer is the notes I use when setting up a DietPi image. In theory you could use those steps when you compile and build a Jessie image. The notes are a little messy, so if you are unsure of any steps, let me know.

#### This applies to Jessie, and assumes you have all the DietPi files and folders (excluding github) in `/boot/*` https://github.com/Fourdee/DietPi

```
#-------------------------------------------------------------------------
//DietPi on a fresh install (Jessie).
#-------------------------------------------------------------------------

#Jessie , unified apt sources.
rm /etc/apt/sources.list.d/deb-multimedia.list
# ------- NOT RPI -------------------------
cat << _EOF_ > /etc/apt/sources.list
deb http://ftp.debian.org/debian jessie main contrib non-free
deb http://ftp.debian.org/debian jessie-updates main contrib non-free
deb http://security.debian.org jessie/updates main contrib non-free
deb http://ftp.debian.org/debian jessie-backports main contrib non-free
_EOF_
# ------- NOT RPI -------------------------

#Remove following Jessie
apt-get purge dhcpcd5 libsqlite* libxapian22 lua5.1 luajit netcat-* make makedev ncdu plymouth openresolv shared-mime-in* tcpd strace tasksel* wireless-* xdg-user-dirs triggerhappy python* v4l-utils traceroute xz-utils ucf xauth zlib1g-dev xml-core aptitude* avahi-daemon rsyslog logrotate man-db manpages vim vim-common vim-runtime vim-tiny mc mc-data
apt-get autoremove --purge -y

#install
echo -e "CONF_SWAPSIZE=0" > /etc/dphys-swapfile
apt-get install -y resolvconf bc dbus bzip2 psmisc bash-completion cron whiptail sudo ntp ntfs-3g dosfstools parted hdparm pciutils usbutils zip htop wput wget fake-hwclock dphys-swapfile curl unzip ca-certificates console-setup console-data console-common keyboard-configuration wireless-tools wireless-regdb crda --no-install-recommends

#firmware
apt-get install firmware-realtek firmware-ralink firmware-brcm80211 firmware-atheros -y --no-install-recommends

#DIETPI STUFF
#Create folders
mkdir /DietPi
mkdir -p /mnt/usb_1
mkdir -p /mnt/samba
mkdir -p /mnt/ftp_client
echo -e "Samba client can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/samba/readme.txt
echo -e "FTP client mount can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/ftp_client/readme.txt

/boot/dietpi/dietpi-logclear 2

#FSTAB
cp /boot/dietpi/conf/fstab /etc/fstab

#setup dietpi service
echo 1 > /boot/dietpi/.install_stage
cp /boot/dietpi/conf/dietpi-service /etc/init.d/dietpi-service
chmod +x /etc/init.d/dietpi-service
update-rc.d dietpi-service defaults 00 80
service dietpi-service start

#Cron jobs
cp /DietPi/dietpi/conf/cron.daily_dietpi /etc/cron.daily/dietpi
chmod +x /etc/cron.daily/dietpi
cp /DietPi/dietpi/conf/cron.hourly_dietpi /etc/cron.hourly/dietpi
chmod +x /etc/cron.hourly/dietpi

#Crontab
cat << _EOF_ > /etc/crontab
#Please use dietpi-cron to change cron start times
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m h dom mon dow user  command
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 1    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 1    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 1    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
_EOF_

#ntp
rm /etc/cron.daily/ntp &> /dev/null
rm /etc/init.d/ntp &> /dev/null

#/etc/sysctl.conf
echo -e "vm.swappiness=1" >> /etc/sysctl.conf

#----------------------------------------------------
#rc.local
cat << _EOF_ > /etc/rc.local
#!/bin/sh -e
/DietPi/dietpi/dietpi-services start
/DietPi/dietpi/dietpi-banner 0
echo " Default Login:\n Username = root\n Password = dietpi\n"
exit 0
_EOF_

#login
echo -e "\n/DietPi/dietpi/login" >> /root/.bashrc

#Network
# - enable auto eth0 after copying.
cp /boot/dietpi/conf/network_interfaces /etc/network/interfaces

#htop cfg
cp /boot/dietpi/conf/htoprc /root/.config/htop/htoprc

#Hosts
cat << _EOF_ > /etc/hosts
127.0.0.1 localhost
127.0.1.1 DietPi
_EOF_

cat << _EOF_ > /etc/hostname
DietPi
_EOF_

#hdparm
cat << _EOF_ >> /etc/hdparm.conf

#DietPi external USB drive. Power management settings.
/dev/sda {
        #10 mins
        spindown_time = 120

        #
        apm = 254
}
_EOF_

#MANUALLY ADD /etc/bash.bashrc -----------------------------------------
export $(cat /etc/default/locale | grep LANG=)
#DietPi Additions
alias dietpi-process_tool='/DietPi/dietpi/dietpi-process_tool'
alias dietpi-letsencrypt='/DietPi/dietpi/dietpi-letsencrypt'
alias dietpi-autostart='/DietPi/dietpi/dietpi-autostart'
alias dietpi-cron='/DietPi/dietpi/dietpi-cron'
alias dietpi-launcher='/DietPi/dietpi/dietpi-launcher'
alias dietpi-cleaner='/DietPi/dietpi/dietpi-cleaner'
alias dietpi-morsecode='/DietPi/dietpi/dietpi-morsecode'
alias dietpi-sync='/DietPi/dietpi/dietpi-sync'
alias dietpi-backup='/DietPi/dietpi/dietpi-backup'
alias dietpi-bugreport='/DietPi/dietpi/dietpi-bugreport'
alias dietpi-uninstall='/DietPi/dietpi/dietpi-uninstall'
alias dietpi-services='/DietPi/dietpi/dietpi-services'
alias dietpi-config='/DietPi/dietpi/dietpi-config'
alias dietpi-software='/DietPi/dietpi/dietpi-software'
alias dietpi-update='/DietPi/dietpi/dietpi-update'
alias emulationstation='/opt/retropie/supplementary/emulationstation/emulationstation'
alias opentyrian='/usr/local/games/opentyrian/run'

alias cpu='/DietPi/dietpi/dietpi-cpuinfo'
alias dietpi-logclear='/DietPi/dietpi/dietpi-logclear'
treesize()
{
     du -k --max-depth=1 | sort -nr | awk '
     BEGIN {
        split("KB,MB,GB,TB", Units, ",");
     }
     {
        u = 1;
        while ($1 >= 1024)
        {
           $1 = $1 / 1024;
           u += 1;
        }
        $1 = sprintf("%.1f %s", $1, Units[u]);
        print $0;
     }
    '
}
#MANUAL ADD END---------------------------------------------------


#fakehwclock - allow times in the past
sed -i "/FORCE=/c\FORCE=force" /etc/default/fake-hwclock

#wifi dongles
echo -e "options 8192cu rtw_power_mgnt=0" > /etc/modprobe.d/8192cu.conf
echo -e "options 8188eu rtw_power_mgnt=0" > /etc/modprobe.d/8188eu.conf

#Set swapfile size
echo -e "CONF_SWAPSIZE=0" > /etc/dphys-swapfile

#--------SYSTEMD---------
#nano /etc/systemd/logind.conf
#NAutoVTs=1

#nano /etc/default/console-setup
#Reduce gettys ACTIVE_CONSOLES="/dev/tty[1-2]"

systemctl disable getty@tty[2-6].service

#NTPd - remove systemd's version
systemctl disable systemd-timesync

#Remove rc.local from /etc/init.d
update-rc.d -f rc.local remove
rm /etc/init.d/rc.local
cat << _EOF_ > /etc/systemd/system/rc-local.service
[Unit]
Description=/etc/rc.local Compatibility
After=dietpi-service.service

[Service]
Type=idle
ExecStart=/etc/rc.local
StandardOutput=tty
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
_EOF_
systemctl enable rc-local.service
systemctl daemon-reload


#Shutdown SSH/Dropbear before reboot
cat << _EOF_ > /etc/systemd/system/kill-ssh-user-sessions-before-network.service
[Unit]
Description=Shutdown all ssh sessions before network
DefaultDependencies=no
Before=network.target shutdown.target

[Service]
Type=oneshot
ExecStart=/usr/bin/killall sshd && /usr/bin/killall dropbear

[Install]
WantedBy=poweroff.target halt.target reboot.target
_EOF_
systemctl enable kill-ssh-user-sessions-before-network
systemctl daemon-reload

dpkg-reconfigure tzdata
dpkg-reconfigure keyboard-configuration #Keyboard must be plugged in for this to work!
dpkg-reconfigure locales
```

**Comment by spiderkeys** [comment]
Appreciate it! If we end up writing a method for making automated builds, I'll be sure to send a pull request your way.

**Comment by Fourdee** [comment]
@spiderkeys 
No worries :+1:

**Comment by spiderkeys** [comment]
Just wanted to provide an update on this. Just today, the image engineer at RPI put the image build scripts up at: https://github.com/RPi-Distro/pi-gen. I'm currently working through them and modifying them to build a completely configured DietPi image (which still uses a pre-defined DietPi configuration to choose what to install and what settings to use). If you're interested, I will share my progress for all to use. May need help with some of the DietPi specifics here and there, but this will be extremely valuable for us, and I'm sure others might be interested in rolling custom images as well.

**Comment by Fourdee** [comment]
@spiderkeys 
Thanks for the info :+1: 

I will give this a spin when I can.

> If you're interested, I will share my progress for all to use. May need help with some of the DietPi specifics here and there, but this will be extremely valuable for us, and I'm sure others might be interested in rolling custom images as well.

Sounds good, i'll help you with any DietPi stuff/queries, just pop them in this git ticket.

**Comment by Fourdee** [comment]
I'll mark this as closed. Please reopen as required.

**Comment by spiderkeys** [comment]
@Fourdee 
I've been working through this, and have been having some issues, which I believe to be mostly related to the ambiguity of where the DietPi files need to be.

In bold above your notes you write: "assumes you have all the DietPi files and folders (excluding github) in /boot/*"

However, at various parts in your script you write things like:

```
cp /DietPi/dietpi/conf/cron.daily_dietpi /etc/cron.daily/dietpi
```

```
cat << _EOF_ > /etc/rc.local
#!/bin/sh -e
/DietPi/dietpi/dietpi-services start
/DietPi/dietpi/dietpi-banner 0
```

Which seem to indicate that the files should have been placed in /DietPi/*, except that conf/dietpi-service definitely expects things to be in /boot/dietpi/ as shown here:

```
NAME="dietpi-service"

start(){

    #Start DietPi-Ramdisk
    /boot/dietpi/dietpi-ramdisk 0

    #Start DietPi-Ramlog
    /DietPi/dietpi/dietpi-ramlog 0

    #start bootup
    /DietPi/dietpi/boot
```

Could I get some clarification on the directory structures? Is /DietPi/ just a copy of the files in /boot/ or maybe its the other way around? Are there really no other steps than what you mentioned when starting from a Raspbian image?

Here is a link to my script that sets up this stage of the image build. I built upon a Raspbian Lite rootfs which exists in ${ROOTFS_DIR} at the time of executing this script. I had all of my DietPi files (from the github repo) stored in ./files/DietPi, which I then copied over to ${ROOTFS_DIR}/DietPi/.

https://github.com/OpenROV-Dev/pi-gen/blob/dev/stage3/00-dietpi-setup/00-run.sh

Thanks

**Comment by Fourdee** [comment]
@spiderkeys 
The files are physically located in `/boot/`. During boot, the files are copied to ramdisk `/DietPi/`, during shutdown, the files are copied back to `/boot/`. `dietpi-service` completes this task.

During the DietPi image setup, `dietpi-service` is started: https://github.com/OpenROV-Dev/pi-gen/blob/dev/stage3/00-dietpi-setup/00-run.sh#L76. This allows us to continue the setup using the ramdisk `/DietPi/`, and call files from it. 

Hope that makes sense, if not, let me know and I'll get some more caffeine and try again :+1:  :)

**Comment by spiderkeys** [comment]
Alright, thanks. I'll make the appropriate changes, give it a try, and provide updates soon.

**Comment by spiderkeys** [comment]
Another question I suppose I'll field in advance:

After I finish getting the initial setup complete, can you guide me in the right direction of what scripts I'll need to call to automatically execute the functionality contained in the DietPi automation process (http://dietpi.com/phpbb/viewtopic.php?f=8&t=273)? I assume that it gets kicked off at boot based on a flag set somewhere, but didn't immediately find where. Any potential gotchas that you might think of would be helpful too.

Thanks :smile:

**Comment by spiderkeys** [comment]
Made the changes so that all of the files are copied to boot. New script reflected here:

https://github.com/OpenROV-Dev/pi-gen/blob/feat_dietpi/stage3/00-dietpi-setup/00-run.sh#L81-L95

For the above lines, I'm running into the following issues:

``` bash
+ chroot /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/ sh -e -
/boot/dietpi/dietpi-logclear: line 217: /DietPi/dietpi/dietpi-banner: No such file or directory
 Info:
 - Log file directory      | /var/log
 - Processed files         | 12
 - Excluded files          | 0
 - Cleared log files       | 0
 - Unsupported files       | 0
 - Deleted files           | 10
 - Space cleared           | 740 KB

+ cp /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/boot/dietpi/conf/fstab /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/etc/fstab
+ on_chroot sh -e -
+ mount
++ realpath /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/proc
+ grep -q /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/proc
+ mount
++ realpath /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/dev
+ grep -q /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/dev
+ mount
++ realpath /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/dev/pts
+ grep -q /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/dev/pts
+ mount
++ realpath /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/sys
+ grep -q /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/sys
+ chroot /home/openrov/workspace/pi-gen/work/2016-05-02-raspbian/stage3/rootfs/ sh -e -
DietPi-Ramdisk: Starting
/bin/cp: cannot stat '/boot/boot.ini': No such file or directory
DietPi-Ramdisk: Completed
DietPi-Ramlog: Starting
/bin/chown: invalid user: 'debian-tor:nogroup'
DietPi-Ramlog: Completed
/bin/df: cannot read table of mounted file systems: No such file or directory
Cannot open netlink socket: Address family not supported by protocol
 ───────────────────────────────────────
 DietPi     | 22:54 | Mon 05/02/16 
 ───────────────────────────────────────
 V117       | Unknown Device
 ───────────────────────────────────────
 IP Address | 
 ───────────────────────────────────────

 Created by: Daniel Knight
 Web:        DietPi.com
 Twitter:    twitter.com/dietpi_

 DietPi's web hosting is powered by MyVirtualServer.com

 DietPi is a free product and relies on your donations for funding.
 Donations:  http://goo.gl/pzISt9

 dietpi-launcher  = All the DietPi programs in one place.
 dietpi-config    = Feature rich configuration tool for your device.
 dietpi-software  = Select optimized software for installation.
 htop             = Resource monitor.
 cpu              = Shows CPU information and stats.

```

The logclearing errors seem pretty benign, presumably caused by it being called before dietpi-service sets up /DietPi/. However, the dietpi-service errors don't look so nice:

```
DietPi-Ramdisk: Starting
/bin/cp: cannot stat '/boot/boot.ini': No such file or directory
DietPi-Ramdisk: Completed
DietPi-Ramlog: Starting
/bin/chown: invalid user: 'debian-tor:nogroup'
DietPi-Ramlog: Completed
/bin/df: cannot read table of mounted file systems: No such file or directory
Cannot open netlink socket: Address family not supported by protocol
```

Are these failures expected and safely ignored?

**Comment by Fourdee** [comment]
@spiderkeys Apologies for the delay on this and thanks for sharing your script.

These warnings can be safely ignored.

```
DietPi-Ramdisk: Starting
/bin/cp: cannot stat '/boot/boot.ini': No such file or directory
DietPi-Ramdisk: Completed
DietPi-Ramlog: Starting
/bin/chown: invalid user: 'debian-tor:nogroup'
DietPi-Ramlog: Completed
```

Intresting, `df` fails to read the mounts. Can you try running `mount` at this point, any results?

```
/bin/df: cannot read table of mounted file systems: No such file or directory
```

This is because you are running DietPi scripts prior to running the main DietPi service `/etc/init.d/dietpi-service`. It can be safely ignored if your trying to clear the log directory prior to mounting the ramdisk.

```
/boot/dietpi/dietpi-logclear: line 217: /DietPi/dietpi/dietpi-banner: No such file or directory
 Info:
 - Log file directory      | /var/log
 - Processed files         | 12
 - Excluded files          | 0
 - Cleared log files       | 0
 - Unsupported files       | 0
 - Deleted files           | 10
 - Space cleared           | 740 KB
```
