### ISSUE TITLE
rpi cam web install

### ISSUE THREAD

**Issue by krishnasen2401** [MichaIng/DietPi#2231]
#### Details:
- Date           | Fri  9 Nov 16:40:50 GMT 2018
- Bug report     | N/A
- DietPi version | v6.17.12 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1145 SMP Fri Sep 21 15:38:35 BST 2018
- Distro         | stretch (index=4)
- Command        | Connection test: https://github.com/silvanmelchior/RPi_Cam_Web_Interface/archive/master.zip
- Exit code      | 4
- Software title | DietPi-Software

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Spider mode enabled. Check if remote file exists.
--2018-11-09 16:40:08--  https://github.com/silvanmelchior/RPi_Cam_Web_Interface/archive/master.zip
Resolving github.com (github.com)... failed: Connection timed out.
wget: unable to resolve host address ‘github.com’

**Comment by Fourdee** [comment]
@krishnasen2401 

Thanks for the report 👍 

Appears to be a local issue with your system/DNS, and/or, temp issue with github:

```
root@DietPi:~# G_CHECK_URL https://github.com/silvanmelchior/RPi_Cam_Web_Interce/archive/master.zip
[  OK  ] Root access verified.
[  OK  ] Connection test: https://github.com/silvanmelchior/RPi_Cam_Web_Interface/archive/master.zip
```

Please re-try the installation, if it continues to fail, please set a static IP in ```dietpi-config``` and use google DNS.

**Comment by MichaIng** [comment]
Will mark as closed. Issue DNS and/or GitHub server, as mentioned by Fourdee.
E.g. GitHub had server issues ~3 weeks ago.
