### ISSUE TITLE
DietPi-Software | Snapcast - Multiroom audio

### ISSUE THREAD

**Issue by docgalaxyblock** [MichaIng/DietPi#2244]
Snapcast
Multi-room client-server audio player
https://github.com/badaix/snapcast
Good Documentation at Github

Similar to Shairport-sync
But can be configured to use MPD, Mopidy, FFmpeg, mpv, MPlayer, Alsa, (Pulse,) AirPlay, Spotify, Line-in

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
Configuration of MPD, ALSA, Snapserver/-client

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes Yes, it's good documentated and easy
https://github.com/badaix/snapcast/blob/master/doc/player_setup.md

**Comment by MichaIng** [comment]
Added to FeatHub, feel free to vote for it: https://feathub.com/MichaIng/DietPi/+18

**Comment by jappish84** [comment]
I'd love to see this soon, I've added a vote as well over at feathub

**Comment by claypole** [comment]
Any news on this? Just starting using DietPi, hoping to find Snapcast as one of the optimised applications.

**Comment by dnj0104** [comment]
> 
> 
> Any news on this? Just starting using DietPi, hoping to find Snapcast as one of the optimised applications.

I vote for that, by the moment I have 1 pie running dietpi-mopidy-snapcastserver and snapcast client and one pie running dietpi - snapcast client. It should have been nice n smooth with snapcast in dietpi, just install maybe some config-menu for snapcast and then boom, up n runnin in no time.
