### ISSUE TITLE
Email on Update

### ISSUE THREAD

**Issue by Micha-Btz** [MichaIng/DietPi#2249]
At first, thanks for this great project.

Mostly the dietpi does this job without my attention, so it would be great, if it can send me a mail if a new update is available. Like apticron does.

Maybe I can create a script that test if there is an update available, is there a point where I can get the infos on the pi directly?

Thanks Micha

**Comment by Fourdee** [comment]
@Micha-Btz 

Hi Micha,

Many thanks for the request 👍 

The main reason we do not offer this feature, is we simply do not log any contact or identifiable data on our users.
The only information we do obtain is hardware/software data:
https://dietpi.com/survey/

#### Current methods for update news:
- Twitter is probably the best bet, we post straight after release: https://twitter.com/dietpi_
- Forum: https://dietpi.com/phpbb/viewforum.php?f=10&sid=637a67be502be3ae925262c1a06a5435 (can be delayed)
- DietPi system: update notifications (when available) are displayed after system login. Checks are run during boot and every 1 day.

---

If we receive more interest for this feature, we can look into allowing users to opt in for email notifications via the DietPi survey system.

**Comment by MichaIng** [comment]
@Fourdee @Micha-Btz 
Of course it's possible to send an email vor local SMTP client, so credentials only need to be stored locally. This then also gives an update notification regardless of used Git branch, just parsing `/DietPi/dietpi/.update_available` flag 🙂.

Clearly an optional feature (including SMTP client install), but a good idea definitely.

**Comment by Micha-Btz** [comment]
Oh, mail just locally from my pi to me. Not a global solution. I will make a test with parsing the /DietPi/dietpi/.update_available. I will report back.

Thanks

**Comment by MichaIng** [comment]
`msmtp` seems to be the lightest solution. No full MTA (like exim e.g.) or GUI mailer:
- https://packages.debian.org/de/stretch/msmtp
- https://marlam.de/msmtp/msmtp.html
- Or install from source: https://marlam.de/msmtp/download/

sendmail: 45M 😮 
postfix: 35M
exim4: 4M (Debian default pre-installed)
msmtp: 1M

Configuration looks quite clear, using TLS with `ca-certificates`. A random self-singed certificate should do. At least if, I would by default pre-configure TLS.

Only question is:
- How to send an email via CLI? We don't want/need MUTT or something like this, since we only send a simple plain text pre-written mail.
€: `msmtp me@my_provider.org <<< 'Hello you!'` it seems.
- https://hostpresto.com/community/tutorials/how-to-send-email-from-the-command-line-with-msmtp-and-mutt/ (Mutt just optional, not required, see sending from txt file as best practice for our use?)

**Comment by Micha-Btz** [comment]
I have a fully working postfix config on my pi, also send local mails with mailx and postfix send the mail out to my provider (smarthost).

So I only need a point that I can grep for a trigger and then cron sends me a mail. 
But maybe the msmtp solution is for other users as well.

**Comment by mrmajik45** [comment]
So if it detects a new version of DietPi has been released it'll email them?

**Comment by Micha-Btz** [comment]
this script should do what I want. If /DietPi/dietpi/.update_available is created, the script send me an email.

root@DietPi:~#  cat /etc/cron.daily/update
```
#!/bin/bash
if test -f /DietPi/dietpi/.update_available && VERSION=`cat /DietPi/dietpi/.update_available`;
     then mail -s "dietpi update available" donald@duck.com <<< "update available $VERSION"
fi
```

**Comment by Micha-Btz** [comment]
For me it is solved, so I close this issue. If you want create a solution for all users, please reopen.

**Comment by Grip** [comment]
The path 

`/Dietpi/dietpi/.update_available`

is no longer available, now you should use

`/run/dietpi/.apt_updates`

hope it will be useful to someone else.

**Comment by MichaIng** [comment]
`/run/dietpi/.apt_updates` is a flag for (and number of) available APT package upgrades. `/run/dietpi/.update_available` is what `/DietPi/dietpi/.update_available` and later `/boot/dietpi/.update_available` was.

**Comment by Grip** [comment]
when I see the banner that states APT updates are available, with a non-root user, I only see the file .apt_updates in /run/dietpi; may I use it as a test to send an email on pending updates?

**Comment by MichaIng** [comment]
You can use whatever you want, depending on what you want to be informed about. If `/run/dietpi/.apt_updates` exists, you know that APT upgrades are available via `apt upgrade`. If `/run/dietpi/.update_available` exists, you know that a DietPi update is available via `dietpi-update`.

**Comment by Grip** [comment]
you're just too much! I just subscribed a small amount to support you on your patreon just as a little sign of appreciation for your efforts! I wish I could do more but it's important to know that free is not as in free beer.. ;)

**Comment by MichaIng** [comment]
Thank you very much!

DietPi is free as in speech and free as in beer both. But of course there are some costs, and more importantly efforts going into FLOSS projects. Always good when users voluntarily help to cover them 🙂.

**Comment by Joulinar** [comment]
When it comes to sending a notification about available updates, I've set up an NTFY server and created a script to send a message. This is how I did it:

```
#!/bin/bash

# ntfy configuration
NTFY_URL="https://ntfy.server.com"
USER="myuser"
PASSWORD="secret"

# read hostname from system
HOSTNAME=$(hostname)

# path of DietPi files
DIETPI_UPDATE_FILE="/run/dietpi/.update_available"
APT_UPDATE_FILE="/run/dietpi/.apt_updates"

# 1. New DietPi update available?
if [ -s "$DIETPI_UPDATE_FILE" ]; then
    # send message
    curl \
      --retry 5 \
      --retry-delay 2 \
      -u "$USER:$PASSWORD" \
      -H "Title: new DietPi update available! 🚀" \
      -H "Priority: high" \
      -H "Tags: arrow_up,computer" \
      -d "On '$HOSTNAME' there is a new DietPi update available. Pls run dietpi-update." \
      "$NTFY_URL"

    echo "DietPi is available – Message was sent."

# 2. If there is no DietPi update, check for Debian package updates
elif [ -s "$APT_UPDATE_FILE" ]; then
    # read number of Debian packages from file
    UPDATES_COUNT=$(cat "$APT_UPDATE_FILE")

    # sent message
    curl \
      --retry 5 \
      --retry-delay 2 \
      -u "$USER:$PASSWORD" \
      -H "Title: Debian package update available! 📦" \
      -H "Priority: default" \
      -H "Tags: wrench" \
      -d "On '$HOSTNAME' there are $UPDATES_COUNT Debian package updates available." \
      "$NTFY_URL"
    
    echo "There are (${UPDATES_COUNT}) Debian package updates available – Message was sent."

# 3. No file exist
else
    echo "There is no DietPi and Debain package update available."
fi
```
