### ISSUE TITLE
DietPi-Software | Minetest

### ISSUE THREAD

**Issue by FlameFireling** [MichaIng/DietPi#2251]
Is an open source voxel game engine. Play one of our many games, mod a game to your liking, make your own game, or play on a multiplayer server. Would be great with PirateBox for portable server parties
minetest.net can be installed from the website from source or packages "apt-get install minetest" but the current minetest version on the raspbian repository is outdated. (Don't use minetest.org as the owner tracks information...)

**Comment by MichaIng** [comment]
@FlameFireling 
Thanks for your request. Could you add some links to official websides, download links, install methods to your both requests? This will make it easier for us to check and implement.

**Comment by MichaIng** [comment]
URL: https://www.minetest.net/
GitHub: https://github.com/minetest/minetest
Feel free to vote for it on FeatHub: https://feathub.com/MichaIng/DietPi/+20

**Comment by MichaIng** [comment]
This request has been down voted to minus. Due to general cleanup, I will mark this issue as closed. However the FeatHub page stays open and as fast as this request reaches closer to top, we will reopen to start working on it.
