### ISSUE TITLE
Why native pc images are still beta ? 

### ISSUE THREAD

**Issue by CorentinDy** [MichaIng/DietPi#2268]
Hi, 
I am wondering why the images for pc are still in beta, is there a buglist or is it just not fully tested to report if there are bugs? 

Thx for this repo ;)

**Comment by MichaIng** [comment]
@CorentinDy 
Good question 😃. Actually the BIOS/CSM images could be taken out of beta from my point of view. Of course the amount of different systems is very large, so on special hardware something might not work. But generally we didn't face much issues, AFAIK.

But UEFI/GPT images should stay beta for now. There are still manual steps required via CloneZilla installer and the method worked not reliable on all systems/worked different on different CloneZilla versions and such. Not 100% sure about current stage, but at least it works a bid inconsistent: https://github.com/Fourdee/DietPi/issues/1171

@Fourdee 
You agree to remove BETA flag from BIOS/CSM images, or did I oversee issues with them?

**Comment by Fourdee** [comment]
@MichaIng 

> You agree to remove BETA flag from BIOS/CSM images, or did I oversee issues with them?

Yep 👍 

The main reason for leaving the "Beta" flag in there, is simply due to the sheer variation of x86_64 CPUs/setups/GPU's etc. And the fact, we cannot offer a like for like RPi experience on every x86_64 system due to that.

But yes, the core images are stable and should be removed from beta status.

**Comment by CorentinDy** [comment]
Good to know for the UEFI one ! Thank's for the answer !

**Comment by Fourdee** [comment]
Will reopen to remind me to make the change :)

**Comment by Fourdee** [comment]
🈯️ dietpi.com
🈯️ https://github.com/Fourdee/DietPi/issues/1171#issuecomment-336522021
