### ISSUE TITLE
DietPi-Software | Tautulli: chown install folder missing? 

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2273]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5256&p=15467#p15467

PR up: https://github.com/Fourdee/DietPi/pull/2274

Needs reinstall fix as well, as currently new folder will fail to move. Handling depends on availability of internal update mechanisms or if git client/command should be used.
____________
For macOS it is at least possible to install without git client: https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#macos
Test and skip git as well, downloading bare archive instead? Still depends on possible internal update mechanisms, e.g. Pi-hole internal updater uses git client.
____________
NB: Can't check updater and stuff myself, lacking Plex.tv account 🤔.

**Comment by MichaIng** [comment]
@Fourdee 
Do you have a Plex.tv account?

**Comment by Fourdee** [comment]
@MichaIng 

> Do you have a Plex.tv account?

Have the free account, not the paid subscription model.
Free account is created when Plex is installed, then goto the GUI to register.

**Comment by MichaIng** [comment]
@Fourdee 
Was able to verify internal updater based on git client though docs and finished PR accordingly.

**Comment by MichaIng** [comment]
I mark this as closed, since it worked for you during tests, ARMv8 including.
