### ISSUE TITLE
TinkerOS_Debian V2.0.8

### ISSUE THREAD

**Issue by ibnbd** [MichaIng/DietPi#2275]
Tinker OS has new version, as I can see the beta at `v6.18.9`. Hopefully you will consider adding latest TinkerOS for `v6.18` final release.

Thank You

**Comment by Fourdee** [comment]
@ibnbd 

Thanks, we'll check and redo image if its running a earlier tinkerOS version.

**Comment by ibnbd** [comment]
@Fourdee thank you very much

**Comment by Fourdee** [comment]
Currently 2.0.7, due to WiFi issues, will retry with 2.0.8.

2.0.8, WiFi test + reboot:
- 🈯️ 
![image](https://user-images.githubusercontent.com/7077026/49266054-9b009a80-f44c-11e8-8225-657d1ae54893.png)

**Comment by Fourdee** [comment]
Image live:
https://dietpi.com/download

Completed.

**Comment by Millichrome** [comment]
Sorry for necroing this. 

The SSH login data still says 2.0.5. 

https://i.imgur.com/5HiE6rP.jpg

Btw, thank you for the new release! DietPi is the best for DIY home servers!

**Comment by MichaIng** [comment]
@Millichrome 
Did you install the fresh image? Updating DietPi will not raise the underlying Tinker OS version AFAIK, though of course all APT packages etc. are updated.
But especially the `/DietPi/dietpi/.prep_info` file which provides the info for the banner is not updated. This just says which base image was used at the time the DietPi image was created.

**Comment by Millichrome** [comment]
Ah, I see. It's an updated install on my "production" home server.

Thanks for the clarification.
