### ISSUE TITLE
DietPi-Software | Update Ampache 3.8.0 > 3.8.2.

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#228]
Hardware: DietPi on a raspberry pi first-generation.
Occurs when installing Ampache through DietPi-Software.
Ampache 3.8.0 is installed when 3.8.2 is available according to the Ampache web interface.

**Comment by Fourdee** [comment]
@Zone22 
:+1: I'll get this updated to 3.8.2

Our Ampache install reads a pre-setup SQL DB during install, makes it easier for the user and installation is completely automatic, but it does mean we need to update the install now and then.

**Comment by Fourdee** [comment]
3.8.2 requires composer install:
![untitled](https://cloud.githubusercontent.com/assets/7077026/13707177/57accf44-e7a0-11e5-963e-d02bac1e8131.png)

**Comment by Fourdee** [comment]
Composer requires Git install:
![untitled](https://cloud.githubusercontent.com/assets/7077026/13707472/beb81ecc-e7a1-11e5-9a8f-93e5f1dc5fd7.png)

**Comment by Fourdee** [comment]
Done. Ampache 3.8.2 install available in v113.

**Comment by ghost** [comment]
Thank You! DietPi is amazing.
