### ISSUE TITLE
alsa-base missing

### ISSUE THREAD

**Issue by OE333** [MichaIng/DietPi#2289]
Hello,
I just upgraded to 6.18.12 (beta) and found my USB DAC not working properly any more.

My findings so far:
dpkg -l  shows that alsa-base seems not to be installed (but alsa-utils is installed).

Trying to install alsa via dietpi-software does not change the situation.

Trying to install alsa-base via 'apt-get install alsa-base'  brings error message: "Package alsa-base is not available.... "

So the alsa-base package seems to be missing.

#### Required Information:
- DietPi version	= 6.18.12 (beta)
- Distro version	= 9.6
- Kernel version = 4.14.0
- SBC device     = NanoPi NEO 2 (aarch64)

Thanks for any help,
OE333

**Comment by Fourdee** [comment]
@OE333 

Hi,

If you updated when the DAC was unplugged/powered off, the detection may have failed and reset the soundcard on system.

```alsa-utils``` is the only package required, contains the alsa libs

Try re-selecting USB DAC in ```dietpi-config``` > Audio options. Reboot system and check sound is functional.

If problems persist, please send us a bug report
```
dietpi-bugreport
```

**Comment by Fourdee** [comment]
No response. Please reopen if required.

**Comment by adminy** [comment]
ok, so I don't think this is related much but my bass and tremble controls are missing also with usb dac, any idea why this might be?

**Comment by MichaIng** [comment]
Please run
```
amixer contents
```
to see available controls and the current values. In `alsamixer` GUI, note that you may need to navigate further right to see all controls.

**Comment by adminy** [comment]
that basically tells me that my device is a potato, which in all fairness it might be, can that be a lack of alsa drivers? or do the device features indentification not happen at driver level?

**Comment by MichaIng** [comment]
Are you on an RPi or which device? For USB DACs it is often required to add additional device tree overlays or kernel modules to get it running fully featured. On RPi there is a large amount of device tree overlays for various USB DACs available (`/boot/overlays/`) on DietPi selectable via `dietpi-config` > `Audio Options` or one can add to `/boot/config.txt`, for other devices I suggest to check manufacturer instructions for Debian or Linux in general, which might contain the build of a device tree overlay or kernel module from source.

**Comment by adminy** [comment]
Yes, it's on the 64 bit dietpi of the pi 4b model. The usb dac is JieLi BR21 Which is listed in dietpi-config > audio section to select. but I have no idea where to get the device trees for such dac. The manufacturer just said it's a plug and play device but if it is that, then The only feature this dac has is volume adjustment and I fail to believe that to be true.

**Comment by MichaIng** [comment]
In `dietpi-config` its auto-detected then. Is it this sound bar with can be also attached via Bluetooth? I think I found it in online shop but not the manufacturer website so far 😄.

Seems to be not included in RPi overlays:
```
# grep -i 'name:.*dac' /boot/overlays/README
Name:   akkordion-iqdacplus
Name:   allo-boss-dac-pcm512x-audio
Name:   allo-katana-dac-audio
Name:   allo-piano-dac-pcm512x-audio
Name:   allo-piano-dac-plus-pcm512x-audio
Name:   applepi-dac
Name:   hifiberry-dac
Name:   hifiberry-dacplus
Name:   hifiberry-dacplusadc
Name:   hifiberry-dacplusadcpro
Name:   hifiberry-dacplusdsp
Name:   hifiberry-dacplushd
Name:   iqaudio-dac
Name:   iqaudio-dacplus
Name:   justboom-dac
Name:   mbed-dac
Name:   rpi-dac
Name:   rra-digidac1-wm8741-audio
```

Yeah I'm afraid it's plug & play-only then, at least with generic Linux driver. Did you try it on another OS, e.g. Windows, to see if it has more tuneables there?

You could of course ask the manufacturer if there are any Linux drivers available for it, either in binary or in source code (preferred) form, but I know some cases where, if at all, only Windows drivers are available, in a single initial version, never maintained until Windows generic driver supports it better...

**Comment by adminy** [comment]
Yes it can be attached through bluetooth. Does that change anything? I do have a windows partition on the mac I could give it a try, see if I get more options that way, but to be honest I don't know where in windows I have to check audio device capabilities. I'll get onto that now.

**Comment by MichaIng** [comment]
> Yes it can be attached through bluetooth. Does that change anything?

Nope, I only wanted to assure that I found the correct device.

> but to be honest I don't know where in windows I have to check audio device capabilities.

Check the sound options of the classic control panel. The sound devices properties have an "enhancements" tab where bass control, room correction and all such can be done, if supported.
