### ISSUE TITLE
Fatal Error Zend OPcache cannot allocate buffer for interned strings

### ISSUE THREAD

**Issue by Twilight0** [MichaIng/DietPi#2293]
## Creating a bug report/issue:

Cannot install any software after 6.18 update.

#### Required Information:
- DietPi version	| `cat /DietPi/dietpi/.version`

```
#!/bin/bash
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=18
G_DIETPI_VERSION_RC=14
G_GITBRANCH=master
G_GITOWNER=Fourdee
```

- Distro version	| `echo $G_DISTRO_NAME` or `cat /etc/debian_version`

stretch

- Kernel version	| `uname -a`

Linux DietPi 4.14.78-sunxi #412 SMP Fri Oct 26 11:37:04 CEST 2018 armv7l GNU/Linux

- SBC device		| `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)

OrangePi Zero (armv7l)

- Power supply used	| (EG: 5V 1A RAVpower)

5V 1A

- SDcard used		| (EG: SanDisk ultra)
EMTEC 16GB, class 10

#### Additional Information (if applicable):
- Software title	| (EG: Nextcloud)
Any
- Was the software title installed freshly or updated/migrated?
Fresh
- Can this issue be replicated on a fresh installation of DietPi?
I don't know
- `dietpi-bugreport` ID
9444d4b6-b4e7-4096-9996-a532804506cf

#### Steps to reproduce:

1. For instance try to install LinuxDash
`sudo dietpi-software install 63
`

#### Expected behaviour:

- Install the software and reboot

#### Actual behaviour:

- Getting the following error:

Tue Nov 27 00:11:50 2018 (4528): Fatal Error Zend OPcache cannot allocate buffer for interned strings
/DietPi/dietpi/dietpi-software: line 7469: / 1024 / 1024: syntax error: operand expected (error token is "/ 1024 / 1024")

#### Extra details:

- Also this error somewhere in between:

Tue Nov 27 00:32:17 2018 (6687): Fatal Error Zend OPcache cannot allocate buffer for interned strings

**Comment by MichaIng** [comment]
@Twilight0 
Thanks for your report.

The command that fails is: `php -r 'print(PHP_INT_MAX);'`
Works well here on VirtualBox Stretch and `dietpi-software install 63` went through without error:
```
root@VM-Stretch:~# php -r 'print(PHP_INT_MAX);'
9223372036854775807
```

> Fatal Error Zend OPcache cannot allocate buffer for interned strings

Something with PHP OPcache module seems to be broken.

OPcache can be configured via: `opcache.interned_strings_buffer` in `php.ini`/`opcache.ini`. The only case where we touch this is on Nextcloud install. But using the value we add there `opcache.interned_strings_buffer=8` works well here as well. Default is `4`.

Can you check if/where you set this value:
`grep 'opcache.interned_strings_buffer' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini`

Possibly a reinstall of the OPcache module will fix: `apt-get -y install --reinstall php7.0-opcache`

**Comment by Twilight0** [comment]
I am sorry but I get frustrated easily sometimes and re-installed DietPi from scratch. I 'll provide report if necessary from the fresh install or close and comment it if everything is fine.

**Comment by Twilight0** [comment]
I will close this issue as it looks like it is ok on fresh installations. I had tweaked something according to this comment when tried to installed nextcloud on 6.17, probably something broke: https://github.com/Fourdee/DietPi/issues/2192#issuecomment-433711737

**Comment by Twilight0** [comment]
Reopening this issue... yeah I tried installing nextcloud once again since you claim it has been fixed for 6.18.
And it failed gloriously with the same error. And yes I tried this after re-installing **php7.0-opcache**.

So this is the output of `grep 'opcache.interned_strings_buffer' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini`:

> /etc/php/7.0/cli/php.ini:;opcache.interned_strings_buffer=4
> /etc/php/7.0/fpm/php.ini:;opcache.interned_strings_buffer=4
> /etc/php/7.0/mods-available/opcache.ini:opcache.interned_strings_buffer=8
> /etc/php/7.0/phpdbg/php.ini:;opcache.interned_strings_buffer=4
> /etc/php/7.0/cli/conf.d/10-opcache.ini:opcache.interned_strings_buffer=8
> /etc/php/7.0/fpm/conf.d/10-opcache.ini:opcache.interned_strings_buffer=8
> /etc/php/7.0/phpdbg/conf.d/10-opcache.ini:opcache.interned_strings_buffer=8

**Comment by MichaIng** [comment]
@Twilight0 
Thanks for testing. Jep this issue is a different one than: https://github.com/Fourdee/DietPi/issues/2192#issuecomment-433711737

We will have to do some research about when/why this issue can occur. I am stuck currently since everything looks as expected.

Just, because this is the only place where we touch OPcache settings, can you try to comment all `opcache.*` lines inside `/etc/php/7.0/mods-available/opcache.ini` (not the one that loads the module itself, just the settings. Comment them with `;`.
Then:
```
systemctl restart php7.0-fpm
php -r 'print(PHP_INT_MAX);'
```
and see if the error still shows up (with default settings then).

**Comment by MichaIng** [comment]
https://bugs.php.net/bug.php?id=72720
SHM is full? They don't mean `/dev/shm`, I guess.
________________
https://forums.zend.com/viewtopic.php?t=113253
`memory_limit`, must this in case be as large as `opcache.memory_consumption` + `opcache.interned_strings_buffer`, so being an overall limit? But actually no chance to hit that with Nextcloud 🤔.
_______________
@Twilight0 
Okay some more to check, going through the memory limits and consumptions:
```
grep 'memory_limit' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini
grep 'opcache.memory_consumption' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini
grep 'apc.shm_size' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini
df # Just to verify no other tmp folder is full, please remove output which contains personal data, e.g. FTP mounts
free -m
```

And you can also check the actual PHP memory consumption of OPcache and APCu:
```
<your_ip>/opcache.php
<your_ip>/apc.php
```

Ah just saw you sent a bug report. I will also go through it there.

**Comment by Fourdee** [comment]
Issue appears limited to this device + pre-image. Could be a PREP issue (unlikely if everything else is working fine)

@Twilight0 

Which pre-image/image did you use for the OPi Zero?

**Comment by Twilight0** [comment]
Armbian's one. Stable PREP script & stable Dietpi release. Will report back when I have time to test things out.

**Comment by MichaIng** [comment]
@Twilight0 
Could you please paste the output of above mentioned commands? If all this is as expected, perhaps there is a sysctl.conf/sysctl.d/*.conf entry that somehow limits memory allocation. Not sure what's possible there.
And could you send a bug report?

But perhaps it's easiest of @Fourdee can try to replicate, if you have a OPi Zero there? Even it is an issue with a non-officially supported device, perhaps there is some setting outside of PHP that causes this issue that we then need to check/adjust on PHP install.

**Comment by Twilight0** [comment]
@MichaIng: OK

`grep 'memory_limit' /etc/php/7.0/*/*.ini /etc/php/7.0/*/*/*.ini`

> /etc/php/7.0/cli/php.ini:memory_limit = -1
> /etc/php/7.0/fpm/php.ini:memory_limit = 128M
> /etc/php/7.0/phpdbg/php.ini:memory_limit = 128M

`grep 'opcache.memory_consumption' /etc/php/7.0/*/*.ini /etc/php/7.2/*/*/*.ini`
> /etc/php/7.0/cli/php.ini:;opcache.memory_consumption=64
> /etc/php/7.0/fpm/php.ini:;opcache.memory_consumption=64
> /etc/php/7.0/mods-available/opcache.ini:opcache.memory_consumption=10
> /etc/php/7.0/phpdbg/php.ini:;opcache.memory_consumption=64
grep: /etc/php/7.2/*/*/*.ini: No such file or directory

`grep 'apc.shm_size' /etc/php/7.0/*/*.ini /etc/php/7.2/*/*/*.ini`

> /etc/php/7.0/mods-available/apcu.ini:apc.shm_size=10M
> grep: /etc/php/7.2/*/*/*.ini: No such file or directory

`df`

> Filesystem     1K-blocks      Used Available Use% Mounted on
> udev               87112         0     87112   0% /dev
> tmpfs              24580      4592     19988  19% /run
> /dev/mmcblk0p1  14905760   3211112  11517444  22% /
> tmpfs             122888         0    122888   0% /dev/shm
> tmpfs               5120         0      5120   0% /run/lock
> tmpfs             122888         0    122888   0% /sys/fs/cgroup
> /dev/sdb1        3658611     26655   3432225   1% /mnt/flash
> /dev/sda1      976760532 749137600 227622932  77% /mnt/toshiba
> tmpfs            1047552         0   1047552   0% /tmp
> tmpfs              10240      1476      8764  15% /DietPi
> tmpfs              51200       120     51080   1% /var/log

`free -m`
>   total        used        free      shared  buff/cache   available
>   Mem:            240          65          58          13         116         153
>   Swap:          1807           0        1807

However these are after clean install plus a few things without Nextcloud marked, because in case I try installing Nextcloud, it will ruin the system with ncc maintenance error messages etc.

**Comment by MichaIng** [comment]
Forward from @Akito13
> #### Details:
> * Date           | Mon  4 Feb 04:37:16 CET 2019
> * Bug report     | N/A
> * DietPi version | v6.20.6 (Fourdee/master)
> * Img creator    | DietPi Core Team
> * Pre-image      | Raspbian Lite
> * SBC device     | RPi 3 Model A+ (armv7l) (index=3)
> * Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
> * Distro         | stretch (index=4)
> * Command        | ncc maintenance:install
> * Exit code      | 254
> * Software title | DietPi-Software
> 
> #### Steps to reproduce:
> 1. Install Nextcloud through `dietpi-software`.
> 
> #### Expected behaviour:
> * Nextcloud should be installed.
> 
> #### Actual behaviour:
> * Installation interrupts with error.
> 
> #### Extra details:
> * Selected Nextcloud to be installed from `dietpi-software`. DietPi was freshly set up, nothing was on storage, yet.
> 
> #### Additional logs:
> ```
> [  OK  ] DietPi-Software | Connection test: https://raw.githubusercontent.com/Fourdee/DietPi/master/.conf/dps_114/nginx.nextcloud.conf
> [  OK  ] DietPi-Software | wget https://raw.githubusercontent.com/Fourdee/DietPi/master/.conf/dps_114/nginx.nextcloud.conf -O 114.nginx.nextcloud.conf
> [  OK  ] DietPi-Software | cp -f 114.nginx.nextcloud.conf /etc/nginx/sites-dietpi/dietpi-nextcloud.conf
> [  OK  ] DietPi-Software | Cleaning download directory
> [ INFO ] DietPi-Software | Enable 4-byte support for MariaDB
> [  OK  ] DietPi-Software | systemctl restart mariadb
> [  OK  ] DietPi-Software | systemctl start redis-server
> [FAILED] DietPi-Software | ncc maintenance:install
> ```
> Log file contents:
> Mon Feb 4 04:35:56 2019 (22158): Fatal Error Zend OPcache cannot allocate buffer for interned strings

No OPi specific issue then. @Akito13 could you please as well paste the outputs as mentioned above: https://github.com/Fourdee/DietPi/issues/2293#issuecomment-442054386

**Comment by MichaIng** [comment]
I mark this as closed now due to PHP7.3 migration. If issue appears again, we'll re-investigate.

**Comment by jbsky** [comment]
Hello,

Nothing to do with your application that I don't know, however, I'm confronted with this bug.

Indeed, I have a firewall in VM Pfsense that runs with 256Mb, if I pass it to 512MB of RAM, I have the error mentioned.

How to fix it...?

Sincerely.

**Comment by MichaIng** [comment]
@jbsky
Thanks for sharing.

Possibly this error can occur on low RAM systems (256M) if the PHP/OPcache memory limits exceed available (or free?) RAM.

Strange is that the error states the interned strings buffer allocation to fail, since this one is very small (4M default, 8M as we set on Nextcloud install due to admin panel warnings/recommendation).
What should fail in the first place is the overall OPcache memory limit which is 128M by default since PHP7.0.

And you say if you set overall PHP memory limit from 512M (default on Debian) to 256M, it does not occur? Even more strange.

I will play around with a 256M memory VM as well and try to replicate.

**Comment by mtruitt** [comment]
I ran into this same issue @MichaIng and you are correct it will throw this error on low RAM systems that use more than the actually amount available. 

I have an application that I cranked the instance size up and adjusted opcache.memory_consumption. Friday I turned it back down as there is no traffic over the weekend and came into that error.  

I actually didn't adjust the PHP memory limit for itself. Just the opcache memory consumption so that may help some in tracking it down.

**Comment by MichaIng** [comment]
Okay I reopen this to not forget the testing on VM. We'll see if it depends on total memory, free memory and if total PHP memory limit has any effect.

**Comment by MichaIng** [comment]
Hmm just got on fresh 1 GiB RAM Buster VirtualBox machine:
> The PHP memory limit is below the recommended value of 512MB.

```
root@VM-Buster:~# grep 'memory_limit' /etc/php/7.3/*/*.ini /etc/php/7.3/*/*/*.ini
/etc/php/7.3/cli/php.ini:memory_limit = -1
/etc/php/7.3/fpm/php.ini:memory_limit = 128M
```
The following then solves the warning:
```
root@VM-Buster:~# G_CONFIG_INJECT 'memory_limit[[:blank:]]*=' 'memory_limit = 512M' /etc/php/7.3/fpm/php.ini
[  OK  ] G_CONFIG_INJECT | Setting in /etc/php/7.3/fpm/php.ini adjusted: memory_limit = 512M
root@VM-Buster:~# systemctl restart php7.3-fpm
```

Since we do not touch this value, it's Debian Buster package default:
```
root@VM-Buster:~# grep 'memory_limit' /usr/lib/php/7.3/php.ini-production
memory_limit = 128M
```

Strange that I never faced this before. New on Nextcloud side? Would be a real problem since low RAM devices (RPi1 with 256M) are perfectly able to run a single user or family Nextcloud instance and should never set `memory_limit` > 128M of course.

**Comment by MichaIng** [comment]
Okay, I ran some tests and was able to produce the following error on PHP-FPM start/restart:
```
Mar 11 12:45:15 VM-Buster php-fpm7.3[21105]: Wed Mar 11 12:45:15 2020 (21105): Fatal Error Insufficient shared memory!
```
Basically this appears in two cases:
1. The virtual memory of any PHP child process exceeds the available system memory, including swap files, minus a few megabytes.
  - The assigned `opcache.memory_consumption` increases the virtual memory usage 1-to-1.
  - The assigned `opcache.interned_strings_buffer` has no effect on virtual memory usage, it seems to be included in the overall OPcache memory consumption.
  - `memory_limit` as well has no influence, also I think the boarder at which those are active, are different. `opcache.memory_consumption` limits the overall OPcache consumption, as it's virtual/shared memory, across all PHP-FPM child processes, I guess, while `memory_limit` is a per-script limit.
2. `opcache.interned_strings_buffer` is equal or larger than `opcache.memory_consumption`.
  - This fits the above assumption that `opcache.interned_strings_buffer` is included in `opcache.memory_consumption`.
  - However default values and those applied by us on Nextcloud installs provide a every large difference between the two sizes (default: 128 vs 4, DietPi + Nextcloud: 512 vs 8), hence this cannot be a reason.

If I reduce system memory or raise memory usage by other processes, while keeping the above rules, I run into usual OOM killer.

What I will do is the following:
- On PHP install, when setting `opcache.memory_consumption`, set `opcache.interned_strings_buffer` as well to half of it, if it is not yet half or smaller.
- On Nextcloud installs, check for system memory, and raise swapfile size, if total memory available is less then 1024M.

**Comment by MichaIng** [comment]
Not a de-facto solution but best we can do for now: https://github.com/MichaIng/DietPi/commit/1996775e572d4812bac4247d2e875a67454e8865

**Comment by Bolkarr** [comment]
I was getting the "Fatal Error Insufficient shared memory!" after I switched the docker linuxserver/nextcloud:arv32v7-php8 version (from php7). The suggested solution;

"On PHP install, when setting opcache.memory_consumption, set opcache.interned_strings_buffer as well to half of it, if it is not yet half or smaller."

fixed the issue. Now Nextcloud docker with php8 works fine. Thanks a lot!

**Comment by MichaIng** [comment]
Having `opcache.interned_strings_buffer` max half the size of `opcache.memory_consumption` is indeed the right safety limit, since  `opcache.interned_strings_buffer` at some point internally seems to allocate the next power of 2 of what has been assigned. So giving it a little more than half can cause the error since it internally fills the whole OPcache buffer. This is however badly documented and not even shown when checking back the stats via [`opcache_get_status`](https://www.php.net/manual/en/function.opcache-get-status.php).
