### ISSUE TITLE
DietPi-Software | PiHole: Does not finish installing after setting new password.

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#2297]
#### Required Information:
- DietPi version	| `cat /DietPi/dietpi/.version`
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=18
G_DIETPI_VERSION_RC=14

- Distro version	| `echo $G_DISTRO_NAME` or `cat /etc/debian_version` stretch 
- Kernel version	| `uname -a`
- SBC device		| `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)
- Power supply used	| (EG: 5V 1A RAVpower) Official power supply
- SDcard used		| (EG: SanDisk ultra) 

#### Additional Information (if applicable):
- Software title	| (EG: Nextcloud) PiHole
- Was the software title installed freshly or updated/migrated? Updated
- Can this issue be replicated on a fresh installation of DietPi? Unknown

#### Steps to reproduce:

1. ... Install pihole

#### Expected behaviour:

- ... after accepting the new password the installer should continue

#### Actual behaviour:

  [i] Nothing to whitelist!
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled
  [✓] New password set <- despite an hour of waiting

**Comment by LexiconCode** [comment]
I was able to reset password using a much shorter less complex password.  I'm guessing there something wrong with long computer passwords.

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks for the report 👍 

Please can you provide a rough example of the password used?

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode
> 
> Thanks for the report 👍
> 
> Please can you provide a rough example of the password used?

I5#l@qQUT&G7@Om5M8aGZ1pH#^u8qs*fof6KdPz0*yZzrZ9pisyCHfxX@I*fXrGn^a2

**Comment by Fourdee** [comment]
@LexiconCode 

> I5#l@qQUT&G7@Om5M8aGZ1pH#^u8qsfof6KdPz0yZzrZ9pisyCHfxX@I*fXrGn^a2

Epic, thanks. Will run some tests 👍 

Our end 🈯️ https://www.diffchecker.com/XX67Ysyl
```
root@DietPi:~# cat /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin | openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:'DietPiRocks!'
I5#l@qQUT&G7@Om5M8aGZ1pH#^u8qsfof6KdPz0yZzrZ9pisyCHfxX@I*fXrGn^a2
```

Hmm, seems fine in v6.18:
- UI login 🈯️ 
![image](https://user-images.githubusercontent.com/7077026/49273885-66053f80-f46e-11e8-8a94-168b23908fb3.png)


@LexiconCode 
Password appears fine in our tests, maybe github is converting some chars, please could you place the password you originally used (with some minor changes), on https://pastebin.com?

**Comment by LexiconCode** [comment]
I'll get back to you as soon as I have access to the system

**Comment by LexiconCode** [comment]
2Qs55DRYwH1J5q1LttY778DyY3PaetKSxzAMNu4kX7OCFnQhYboh2Toi95EHVx9FHDJyhrS6D64iUGAUDo4H7nb0DqRi8NK7uNVrZxAe4SB5fhrKcEg0TuFiR2Ad5mRj

**Comment by MichaIng** [comment]
Checked our encryption system with this password as well:
```
2019-03-03 17:56:57 root@micha:/tmp# echo '2Qs55DRYwH1J5q1LttY778DyY3PaetKSxzAMNu4kX7OCFnQhYboh2Toi95EHVx9FHDJyhrS6D64iUGAUDo4H7nb0DqRi8NK7uNVrZxAe4SB5fhrKcEg0TuFiR2Ad5mRj' | openssl enc -a -e -aes-256-cbc -nosalt -pass pass:'DietPiRocks!'
Uq6GpgM7gwZdaV9Nnxs9dKTz7ty+gDAfHmXVxGgytOGQK4JTLuPgRVH4cOJBW5L5
e5ShXE1MiOTfQ3oryAUSarRCwWI3SUKwjVb3ovLzY5ZBQv4lnLm4KQkivW+XEss/
GDr7zlqAUd2axEWzQU3b6KutvMrp4KkKJsInfEIh5VEwDnK/eEdDqMG1fnwf787r

2019-03-03 21:52:55 root@micha:/tmp# echo 'Uq6GpgM7gwZdaV9Nnxs9dKTz7ty+gDAfHmXVxGgytOGQK4JTLuPgRVH4cOJBW5L5e5ShXE1MiOTfQ3oryAUSarRCwWI3SUKwjVb3ovLzY5ZBQv4lnLm4KQkivW+XEss/GDr7zlqAUd2axEWzQU3b6KutvMrp4KkKJsInfEIh5VEwDnK/eEdDqMG1fnwf787r' | openssl enc -a -d -aes-256-cbc -nosalt -pass pass:'DietPiRocks!'
2Qs55DRYwH1J5q1LttY778DyY3PaetKSxzAMNu4kX7OCFnQhYboh2Toi95EHVx9FHDJyhrS6D64iUGAUDo4H7nb0DqRi8NK7uNVrZxAe4SB5fhrKcEg0TuFiR2Ad5mRj
```

According to Fourdees test also Pi-hole threats special characters correctly.

@LexiconCode 
Sorry that this issue was forgotten btw,
Are you still running into this issue with current version?

In case we need to replicate step-by-step:
- Apply the global password via dietpi-config.
- Check if `cat /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin | openssl enc -base64 -d -aes-256-cbc -nosalt -pass pass:'DietPiRocks!'` correctly decrypts this password.
- (Re)install Pi-hole and check if the password changed prompt as well shows the correctly decrypted password.
- Check if Pi-hole web UI accepts the password.

**Comment by LexiconCode** [comment]
I will be able to get to test this some time this coming Tuesday or Wednesday this week. I'll let you know then.

**Comment by MichaIng** [comment]
@LexiconCode 
Could you solve the issue?

**Comment by MichaIng** [comment]
I mark issue as closed for now. Feel free to reopen if required.
