### ISSUE TITLE
DietPi-Software | Add MPD installation option 

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#230]
Music Player Daemon (MPD) is a flexible, powerful, server-side application for playing music. Through plugins and libraries it can play a variety of sound files while being controlled by its network protocol.

http://www.musicpd.org/

MPD could be used in conjunction with Ampache for localplay.

**Comment by Fourdee** [comment]
@Zone22 
MPD (and YMPD) can be installed by selecting HiFi from DietPi software. Although HiFi is a frontend webplayer, it will still install and config MPD. 
http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5#p50

I will look into separating MPD into its own installation option, sometime in the future.

I've not tested MPD using the HiFi install with Ampache myself. If you try it, please let me know, I will assist you to get it working if needed.

**Comment by ghost** [comment]
YMPD and Ampache in terms of compatibility coexist they are although not integrated. They share the same music directory. I am unable to connect to an Ampache MPD instance using the local IP and any port. Conversely I am able to connect to YMPD uusing a local IP and default port.  My setup is rather unusual because I'm using YMPD, Ampache, WiFi HotSpot, and ownclowd to manage music/data sync. Owncloud next to the Ampache music folder through its API.

Edit 2 While not integrated I was able to Symbolic link the ownclowd music/video folders to Ampache. 
ln -s source/files destination/files to create symbolic links
ln -f  source/files destination/files to remove symbolic links

Example
ln -s /mnt/usb_1/owncloud_data/_User_/files/Videos /mnt/usb_1/Video
ln -s /mnt/usb_1/owncloud_data/_User_/files/Photos /mnt/usb_1/Pictures
ln -s /mnt/usb_1/owncloud_data/_User_/files/Music /mnt/usb_1/Music

**Comment by Fourdee** [comment]
MPD is now its own installation in dietpi-software.
