### ISSUE TITLE
RPI SBC | RPi 3 Model A+

### ISSUE THREAD

**Issue by adamotte** [MichaIng/DietPi#2301]
#### Give us some formal device information:
- Device name | **Raspberry Pi 3 Model A+**
- Official product URL | https://www.raspberrypi.org/products/raspberry-pi-3-model-a-plus/
- GitHub resource URL | https://github.com/raspberrypi
- Image download URL | https://www.raspberrypi.org/downloads/

If default image is not working as this and need some tweaking...

**Comment by MichaIng** [comment]
@adamotte
Thanks for your request. Actually the RPi image should work for all RPi versions. Did you face any issues with it?

But indeed or hardware model identifier script does not identify model 3 A+ currently.

Could you paste the result of: `cat /proc/cpuinfo`
So we can implement based on that info.

But the image should still work?

**Comment by Fourdee** [comment]
DietPi naming for 3A+ will be fixed in v6.19.  https://github.com/Fourdee/DietPi/commit/2c584c17c012b8d15f839c97717c9c50aa3d0911

@adamotte 
Image should work out the box with 3A+. However, if you can confirm, i'd be grateful.

**Comment by adamotte** [comment]
My ticket was just to keep in mind this new device and double check if, has you said, it works out of the box.
He is not available yet in my country, i will buy it as soon as i can.

**Comment by Fourdee** [comment]
@adamotte 

> My ticket was just to keep in mind this new device and double check if, has you said, it works out of the box.
He is not available yet in my country, i will buy it as soon as i can.

Yep, thank you for the heads up 👍 

I'll order one when I can and verify. Unless someone else can confirm its fine.

**Comment by Fourdee** [comment]
Results now in survey, will mark as completed.
```

RPi 3 Model A+ (armv7l) | 23
-- | --


```
