### ISSUE TITLE
DietPi-Config | Change the number of WiFi Slots in Wireless Network Options

### ISSUE THREAD

**Issue by craviee** [MichaIng/DietPi#2302]
It is possible to change the number of WiFi Slots from 5 to 10 or 20?

I tried to change the variable MAX_SSID_SLOTS of /boot/dietpi/func/dietpi-wifidb to 10 but nothing happened, and when I reboot the system the variable returns to the default 5.

**Comment by MichaIng** [comment]
@craviee 
You need to adjust the value within `/DietPi/dietpi/func/dietpi-wifidb`. On reboot this will be ported to `/boot/dietpi/func/dietpi-wifidb` as well.

But a `dietpi-update` will revert of course.
My aim, perhaps can be done for v6.19, is to have no static max slot amount, but simply start with one slot. Then have a button within `dietpi-wifidb` menu to add an additional slot up to no limit.

**Comment by craviee** [comment]
> @craviee
> You need to adjust the value within `/DietPi/dietpi/func/dietpi-wifidb`. On reboot this will be ported to `/boot/dietpi/func/dietpi-wifidb` as well.
> 
> But a dietpi-update will revert of course.
> My aim, perhaps can be done for v6.19, is to have no a static max slot amount, but simply start with one slot. Then have a button within `dietpi-wifidb` menu to add an additional slot up to no limit.

This fully resolves my issue.
May I close this issue?

**Comment by MichaIng** [comment]
Thanks for feedback, yes you can close. The feature/improvement will be done via separate issue.
