### ISSUE TITLE
Chromium Browser Runs Half Screen

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#2306]
Hello i`m using latest DietPi Version 6.18 in a Raspberry Pi3B

I installed Chromium Browser and after i set i to auto-start standalone

and it only shows in half of my screen on the left side i have a fullhd 22" screen  the other half is black

i had this bug in 6.17 version also it looks like is not fixed yet

Thanks

**Comment by Fourdee** [comment]
@symbios24 

This is resolved in v6.19, please see below for info and a solution you can apply now:
https://github.com/Fourdee/DietPi/issues/2298#issuecomment-443108829

**Comment by symbios24** [comment]
thanks one more question i have set the chromium to autostart but i cannot exit to apply the fix is there a way to exit ? or is there a way to cancel to autostart ?

**Comment by Fourdee** [comment]
@symbios24 

SSH would be preferred.

Or on local machine, use CTRL+ALT+F2

**Comment by symbios24** [comment]
thanks by the way also firefox esr can be done the same way like chromium (autostart) i have tried it 
if you want to add it on a later update

**Comment by Fourdee** [comment]
@symbios24 

> thanks by the way also firefox esr can be done the same way like chromium (autostart) i have tried it
if you want to add it on a later update

Default Firefox-esr is not compiled with ALSA, requires pulseaudio, no sound for our systems. Very unlikely we'd implement autostart feature as we'd also need to compile + maintain Firefox-esr for all CPU archs and distros.
https://www.linuxquestions.org/questions/slackware-14/firefox-in-current-alsa-sound-4175622116/
