### ISSUE TITLE
DietPi-Software | Pydio: Pretty URL rewrite required for sync clients

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2308]
https://dietpi.com/phpbb/viewtopic.php?f=11&t=484&p=15596&sid=79a48e972c5bbda81778deff5b9ef565#p15596

**Comment by MichaIng** [comment]
@Fourdee
I will add this to v6.19 now:
- Lighttpd according to solution in forum. Hope user can verify it's working there (with Windows client). I tested with another DietPi VM as client. Connection worked (without not), but last step to start dir sync somehow didn't start it. Pressing the button didn't have an effect. Not sure if something is missing for the client binary, since I just installed required libraries according to execution error messages. Didn't find a list about requirements and there is no installer available for the linux client, just the bare binary.
- Apache works out of the box with .htaccess
- Nginx still needs check, but should be fast forward with docs and similar to ownCloud/Nextcloud config.

**Comment by MichaIng** [comment]
Damn, more complicated rewrite rules required, since php files are as well inside subdirs with dots in their path... https://dietpi.com/phpbb/viewtopic.php?f=11&t=484&start=20

**Comment by MichaIng** [comment]
php-cli is recommended within docs and also shown on Lighttpd install guide: https://github.com/pydio/pydio-doc-howto/blob/master/system_installing_on_fedora_lighttpd.md#init-2

Used for background jobs, if I understood right.

**Comment by MichaIng** [comment]
Just found: https://github.com/Fourdee/DietPi/issues/297
~That actually gives a hint about the different required rewrite rules... Why there is no official doc about this, which all seems to be required... 🤔~
**€: Nope, outdated according to: https://pydio.com/en/docs/kb/system/installing-debiannginx**
_______
No official hints here: https://pydio.com/en/docs/kb/system/installing-linux-distribution-nginx-1
WebDAV rewrites only: https://pydio.com/en/docs/kb/system/installing-freebsd-nginx-and-php-fpm
Another one 😠: https://pydio.com/en/docs/kb/system/installing-debiannginx
- <s>Jep finally rewrites are inside the last guide for Nginx. REST API is the one required for client sync:
```
        rewrite ^/dashboard|^/settings|^/welcome|^/ws- /index.php last;
        if ( !-e $request_filename ) {
                # WebDAV Rewrites
                rewrite ^/shares /dav.php last;
                # Sync client
                rewrite ^/api /rest.php last;
                # External users
                rewrite ^/user ./index.php?get_action=user_access_point last;
                # Public shares
                rewrite ^/data/public/([a-zA-Z0-9_-]+)\.php$ /data/public/share.php?hash=$1?;
        }
        rewrite ^/data/public/([a-zA-Z0-9_-]+)--([a-z]+)$ /data/public/share.php?hash=$1&lang=$2?;
        rewrite ^/data/public/([a-zA-Z0-9_-]+)$ /data/public/share.php?hash=$1?;
```
</s>

**€: Nope:**
> ### PS: Pydio 6 Nginx Configuration
> This is the **old** config.

- Also those other php files do not exist on current install anymore.
___________________
Console error on `pydio-ui`, Linux sync client last step. This appears already regularly the whole time, but everything works until very last step... You can trigger error by pressing the last "next" button.
![pydio-ui](https://user-images.githubusercontent.com/28480705/49343625-5dc72300-f66d-11e8-8082-d3b482d74b3c.png)

**Comment by MichaIng** [comment]
### Lighttpd

Gave up in Linux client. Most properly some library is missing.

🈯️ Test with Windows client succeeds with:
```
$HTTP["url"] =~ "^/pydio($|/)" {
        # Deny access to pydio/data dir
        $HTTP["url"] =~ "^/pydio/(data|conf|core)" {
                url.access-deny = ("")
        }

        # Pretty URL rewrite, required for sync clients
        url.rewrite-if-not-file = ( "^/pydio/(.+)/?$" => "/pydio/index.php/$1" )

        # Disable PHP output buffering, recommended by Pydio
        setenv.add-environment += ( "PHP_ADMIN_VALUE" => "output_buffering=Off" )

}
```
- Added more access denials according to `.htaccess` files. Will add again more.

**Comment by MichaIng** [comment]
### Nginx

Nginx example conf... to a while to find it 😆: https://github.com/pydio/pydio-core/blob/develop/core/src/nginx.conf.sample

Sadly even with redirection statement from this sample, sync on Nginx does not work 🤔

🈯️ `try_files $uri $uri/ /pydio/index.php?$args;`
- Checks for file/folder existence, otherwise rewrites to index.php with args attached. This is the way to go with ~modern (actually since long time ago working) Nginx.

**Comment by MichaIng** [comment]
Done:
- Lighttpd: https://github.com/Fourdee/DietPi/commit/6537620a91e6923d1853c549df683aea6b46a693
- Nginx: https://github.com/Fourdee/DietPi/commit/3471de975283e5f489d4fef3c75d5334ffd72526

🈯️ Passed Windows client connection, sync and public shares
- [x] Jessie Lighttpd | Requires mod_rewrite via `lighttpd.conf,` since `rewrite.ini` is not yet available
  - 🈯️ Done: https://github.com/Fourdee/DietPi/commit/6b18e166d8643ec3a0e80c104d7b4df9fef41336
- [x] Jessie Nginx
- [x] Jessie Apache

**Comment by Fourdee** [comment]
🈯️ Test install Lighttpd , not tested Sync client yet.

**Comment by Fourdee** [comment]
Need to verify:
- Sync clients functional with:
-- 🈯️ Lighttpd after reboot or ```service lighttpd force-reload```
-- 🈯️ Nginx
-- 🈯️ Apache2

Update online doc:
- 🈯️ https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1064#p1064

Then we can mark this as completed.

**Comment by Fourdee** [comment]
@MichaIng 

Works a charm, great work 👍
