### ISSUE TITLE
Please enable cgroups memory in the kernel

### ISSUE THREAD

**Issue by St3S0f** [MichaIng/DietPi#2315]
## Creating a feature request:
can cgroups memory be enabled in the kernel?

#### Is your feature request related to a problem? Please describe:
cgroups memory is a prerequisite to install kubernetes

#### Additional context:
```
 ────────────────────────────────────────────────
 DietPi | Mon 03/12/18 - 23:35
 ────────────────────────────────────────────────
 v6.18.14 | Asus Tinker Board (armv7l)

# cat /proc/cgroups 
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	4	1	1
cpu	2	50	1
cpuacct	2	50	1
devices	3	50	1
freezer	5	1	1
```

**Comment by Fourdee** [comment]
@1uc4 

Hi, many thanks for the request 👍 

Unfortunately, we do not offer custom kernels at this time. All ours kernels are provided by manufacture, or, community.

You'd need to build the kernel with custom changes, as per your requirements.
