### ISSUE TITLE
Initial install fail - Odroid HC1

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#2319]
#### Details:
- Date           | Mon 10 Sep 07:09:19 EDT 2018
- Bug report     | N/A
- DietPi version | v6.14
- Img creator    | DietPi Core Team
- Pre-image      | Meveric
- SBC device     | Odroid XU3/XU4/HC1/HC2 (armv7l) (index=11)
- Kernel version | #1 SMP PREEMPT Thu Aug 23 05:59:33 UTC 2018
- Distro         | stretch (index=4)
- Command        | Connection test: https://deb.debian.org/debian/
- Exit code      | 4
- Software title | DietPi-Software

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Spider mode enabled. Check if remote file exists.
--2018-09-10 07:09:17--  https://deb.debian.org/debian/
Resolving deb.debian.org (deb.debian.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘deb.debian.org’
```

**Comment by MichaIng** [comment]
@rlamans 
Thanks for your report.

Just to clarify:
- This was after 1st auto setup went fine, `dietpi-software` auto prompt and then you optionally chose your software to install and hit `Go >> Install`?

First check, if this is generally a DNS server issue or only a temporary deb.debian.org issue: `ping dietpi.com`
- This should correctly resolve to an IP and succeed. If it doesn't then it's a general DNS config issue, so go on below.

Please check configured DNS server:
`cat /etc/resolv.conf`

This file is auto handled by the `resolvconf` package and adjusted with DHCP lease etc. So if you use the DHCP client get your IP, this should be the IP of your DHCP server (router) and if you chose static IP, then this most properly should be the default gateway (router) as well. If the router itself does not support DNS server functionality, then it should forward another proper one from www.

If somehow this auto configuration does not work properly, then please try to manually overwrite the DNS entry with e.g. Google DNS server:
`echo 'nameserver 8.8.8.8' > /etc/resolv.conf`

Recheck `ping dietpi.com` and in case it succeeds, rerun `dietpi-software`.

**Comment by ghost** [comment]
Yep - initial install problem - self imposed. I think I had a problem because I edited the Dietpi file. Reloaded the op sys, edited the Dietpi file (paying close attention to detail) and all is well. I had a comma between two DNS servers and noticed it when editing Dietpi the second time.

Thanks for the quick response ...

**Comment by MichaIng** [comment]
@rlamans 
Thanks for reply. Had not in mind that indeed you can actively choose the DNS with static IP via `dietpi.txt`. Great it worked with syntax correction.
