### ISSUE TITLE
Coding | Use "mawk" instead of "awk" for consistency and performance

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2323]
On a fresh system, only `mawk` is installed and linked for `awk` implementation:
```
root@VM-Stretch:~# which awk
/usr/bin/awk
root@VM-Stretch:~# l /usr/bin/awk
lrwxrwxrwx 1 root root 21 Jul 20 14:57 /usr/bin/awk -> /etc/alternatives/awk
root@VM-Stretch:~# l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 Jul 20 14:57 /etc/alternatives/awk -> /usr/bin/mawk
root@VM-Stretch:~# l /usr/bin/mawk
```

When installing `gawk`, the default is replaced by it:
```
root@VM-Stretch:~# apt-get -y install gawk
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libmpfr4 libsigsegv2
Suggested packages:
  gawk-doc
The following NEW packages will be installed:
  gawk libmpfr4 libsigsegv2
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,156 kB of archives.
After this operation, 3,151 kB of additional disk space will be used.
Get:1 https://cdn-aws.deb.debian.org/debian stretch/main amd64 libmpfr4 amd64 3.1.5-1 [556 kB]
Get:2 https://cdn-aws.deb.debian.org/debian stretch/main amd64 libsigsegv2 amd64 2.10-5 [28.9 kB]
Get:3 https://cdn-aws.deb.debian.org/debian stretch/main amd64 gawk amd64 1:4.1.4+dfsg-1 [571 kB]
Fetched 1,156 kB in 2s (490 kB/s)
Selecting previously unselected package libmpfr4:amd64.
(Reading database ... 16305 files and directories currently installed.)
Preparing to unpack .../libmpfr4_3.1.5-1_amd64.deb ...
Unpacking libmpfr4:amd64 (3.1.5-1) ...
Selecting previously unselected package libsigsegv2:amd64.
Preparing to unpack .../libsigsegv2_2.10-5_amd64.deb ...
Unpacking libsigsegv2:amd64 (2.10-5) ...
Setting up libmpfr4:amd64 (3.1.5-1) ...
Setting up libsigsegv2:amd64 (2.10-5) ...
Selecting previously unselected package gawk.
(Reading database ... 16327 files and directories currently installed.)
Preparing to unpack .../gawk_1%3a4.1.4+dfsg-1_amd64.deb ...
Unpacking gawk (1:4.1.4+dfsg-1) ...
Setting up gawk (1:4.1.4+dfsg-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
root@VM-Stretch:~# which awk
/usr/bin/awk
root@VM-Stretch:~# l /usr/bin/awk
lrwxrwxrwx 1 root root 21 Jul 20 14:57 /usr/bin/awk -> /etc/alternatives/awk
root@VM-Stretch:~# l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 Dec  4 19:54 /etc/alternatives/awk -> /usr/bin/gawk
```

`gawk` is e.g. installed as dependency with MariaDB: https://packages.debian.org/stretch/mariadb-server-10.1

`mawk` on Debian is marked as `required`, thus is available on all Debian systems and will never be autoremoved:
```
root@VM-Stretch:~# apt show mawk
Package: mawk
Version: 1.3.3-17+b3
Priority: required
Section: interpreters
Source: mawk (1.3.3-17)
Maintainer: Steve Langasek <vorlon@debian.org>
Installed-Size: 187 kB
Provides: awk
Pre-Depends: libc6 (>= 2.14)
Tag: devel::interpreter, implemented-in::c, interface::commandline,
 role::program, scope::utility, use::filtering, use::scanning,
 works-with::text
Download-Size: 84.6 kB
APT-Manual-Installed: no
APT-Sources: https://deb.debian.org/debian stretch/main amd64 Packages
Description: a pattern scanning and text processing language
```

`gawk` on the other hand on Debian is marked as `optional`:
```
root@VM-Stretch:~# apt show gawk
Package: gawk
Version: 1:4.1.4+dfsg-1
Priority: optional
Section: interpreters
Maintainer: Adrian Bunk <bunk@debian.org>
Installed-Size: 2,252 kB
Provides: awk
Pre-Depends: libc6 (>= 2.15), libgmp10, libmpfr4 (>= 3.1.3), libreadline7 (>= 6.0), libsigsegv2 (>= 2.9)
Suggests: gawk-doc
Homepage: http://www.gnu.org/software/gawk/
Tag: devel::interpreter, implemented-in::c, interface::commandline,
 role::program, scope::utility, suite::gnu, use::converting,
 use::filtering, use::scanning, works-with::text
Download-Size: 571 kB
APT-Manual-Installed: yes
APT-Sources: https://deb.debian.org/debian stretch/main amd64 Packages
Description: GNU awk, a pattern scanning and processing language
```

`bash` depends on either one of them: `bash` > `base-files` > `gawk|mawk|original-awk`: https://packages.debian.org/stretch/base-files
___________________
`mawk` is less featured, instead less dependent and faster: https://github.com/Fourdee/DietPi/issues/1510#issuecomment-444213593
- But we must assume that `mawk` feature set is sufficient and working with DietPi code, since this is default on fresh images.
- So to have more consistently used the same and faster binary, I suggest we explicitly use `mawk` instead of the current, possibly changing `awk` link.
___________
There is one issue with `mawk` on Debian:
- The version is 1.3.3 from 2009 by old developer that has stopped maintenance: https://packages.debian.org/buster/mawk
- There is a maintained version/fork 1.3.4 from a new developer, that has fixed some bugs and keeps API in sync with current POSIX standards: http://invisible-island.net/mawk/mawk.html
- E.g. `[[:blank:]]` regular expressions do not work with mawk 1.3.3 yet, but with 1.3.4
- All distros switched to the new version, but Debian not and seem not to aim this. There are several open issues/bug reports, but moreless ignored by package maintainer for unclear reasons. I read somewhere that it is simply a personal thing between new mawk dev and Debian package  maintainer 🙄...

We might want to install v1.3.4 from source with DietPi-PREP (uuuh, requires dev packages 🤔) or find a reliable pre-compiled deb package source?

However all of this is low priority, since we never faced issues with either mawk or gawk, so it's just a minor performance concern and to resolve those obviously rare bugs/quirks with mawk 1.3.3.

**Comment by MichaIng** [comment]
`mawk` v1.3.4 source + build instructions: https://github.com/ThomasDickey/mawk-20140914

PR merged: https://github.com/Fourdee/DietPi/pull/2424

**Comment by Fourdee** [comment]
@MichaIng 

Appears fine in testing, good work @MichaIng  👍 

Will mark as completed.
