### ISSUE TITLE
DietPi-Config | Fix HDMI boost setting on RPi

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2350]
Ref: https://github.com/Fourdee/DietPi/pull/2349#issuecomment-447169037

**Comment by Fourdee** [comment]
@MichaIng 

Tweaked the options to provide more of them.

![image](https://user-images.githubusercontent.com/7077026/50102995-7f540d00-021e-11e9-8d2e-adb4c218f17c.png)

Tested passed, completed.
