### ISSUE TITLE
DietPi-FS_partition_resize | Issues on Jessie and VirtualBox in general

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2358]
Ref: https://github.com/Fourdee/DietPi/pull/2357#issuecomment-448335954
- On Jessie, `sfdisk -fN1 /dev/sda <<< ',+,,,'` partition resizing makes image unbootable.
- Reason is, that an `fdisk` partitioned disk is affectively shrunken a tiny bit, on Jessie only, not on Stretch and above and FS cannot be shrunken on a mounted drive, but only on external system, which recovers boot-ability.

So on Jessie images we either need to:
- Revert `DietPi-FS_partition_resize` to use `fdisk` instead of `sfdisk`
- Disable/remove `DietPi-FS_partition_resize` completely on Jessie VMs, so we only resize once on image creation, respectively Debian installer does this.
_____________
At least on VirtualBox disk resizing (the disk from VBox GUI, not the partition within VM) does not work at all, at least with new VirtualBox 6 (currently RC1):
- For VMDK disks, it is not supported at all natively by VirtualBox.
- Converting to VDI, then changing disk size works. `fdisk` + `sfdisk` resizing both works then, since the partition is in both cases effectively enlarged. But from then on during boot mass disk I/O errors appear on boot.
- `partprobe` of course directly after (s)fdisk to inform kernel, but then `resize2fs` throws an VBox error message, which pauses the VM. Resuming works, but still the above I/O errors on boot show up.

So effectively I could not find any way on VirtualBox 6 to increase the disk size without having errors on multiple levels. We could create our VBox images with VDI disks to allow resizing, but due to the mentioned errors, it anyway does not go well...
_____________
@Fourdee 
Maybe this is an issue with my VBox 6. Could you by times try to replicate, at best with VBox 5? Perhaps both issues are related and due to a bug in VBox 6 with disks in general. I just found VBox 6 was released just today. Will also retry and check Beta/RC info for known issues and/or other user reports.
- 🈴 Same error on VBox 6 release with VMDK drive copied to VDI, replaced/reattached to VM, resized 8G => 9G, boot. Partition resize makes it even works => More of these error messages an boot. The system runs otherwise fine, currently testing Nextcloud installation. But anyway, would never feel well with these error messages...
- Inconsistent: Auto reboot after Nextcloud install has finished: No errors. Next reboot: Errors re-appear...
```
Dec 19 00:58:25 VM-Stretch kernel: ata1: failed to read log page 10h (errno=-5)
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: exception Emask 0x1 SAct 0x7e0fffff SErr 0x0 action 0x0
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: irq_stat 0x40000008
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: failed command: READ FPDMA QUEUED
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: cmd 60/08:00:68:1e:80/00:00:00:00:00/40 tag 0 ncq dma 4096 in
                                            res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x1 (device error)
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: status: { DRDY }
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: failed command: READ FPDMA QUEUED
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: cmd 60/08:08:70:1e:80/00:00:00:00:00/40 tag 1 ncq dma 4096 in
                                            res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x1 (device error)
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: status: { DRDY }
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: failed command: READ FPDMA QUEUED
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: cmd 60/08:10:78:1e:80/00:00:00:00:00/40 tag 2 ncq dma 4096 in
                                            res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x1 (device error)
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: status: { DRDY }
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: failed command: READ FPDMA QUEUED
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: cmd 60/08:18:80:1e:80/00:00:00:00:00/40 tag 3 ncq dma 4096 in
                                            res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x1 (device error)
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: status: { DRDY }
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: failed command: READ FPDMA QUEUED
Dec 19 00:58:25 VM-Stretch kernel: ata1.00: cmd 60/08:20:88:1e:80/00:00:00:00:00/40 tag 4 ncq dma 4096 in
                                            res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x1 (device error)
... and much more until tag 30, then...
Dec 19 00:58:26 VM-Stretch kernel: ata1.00: configured for UDMA/133
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#0 Sense Key : Illegal Request [current]
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#0 Add. Sense: Unaligned write command
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#0 CDB: Read(10) 28 00 00 80 1e 68 00 00 08 00
Dec 19 00:58:26 VM-Stretch kernel: blk_update_request: I/O error, dev sda, sector 8396392
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#1 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#1 Sense Key : Illegal Request [current]
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#1 Add. Sense: Unaligned write command
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#1 CDB: Read(10) 28 00 00 80 1e 70 00 00 08 00
Dec 19 00:58:26 VM-Stretch kernel: blk_update_request: I/O error, dev sda, sector 8396400
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#2 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#2 Sense Key : Illegal Request [current]
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#2 Add. Sense: Unaligned write command
Dec 19 00:58:26 VM-Stretch kernel: sd 0:0:0:0: [sda] tag#2 CDB: Read(10) 28 00 00 80 1e 78 00 00 08 00
... and more again
```

**Comment by Fourdee** [comment]
Tested fine with VB6 on our Stretch image, will mark as closed as we dropped support for Jessie.

**Comment by MichaIng** [comment]
@Fourdee 
Did you try to resize the drive as well (on Stretch)?
