### ISSUE TITLE
DietPi-Software | myMPD: Use latest release via api.github.com

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2362]
... instead of master or fixed history point: https://api.github.com/repos/jcorporation/myMPD/releases/latest

**Comment by sChUhBiDu** [comment]
How can I do that? Sorry Linux noob here? having problems with playing music. Can see all files but when I press play nothing happens ;_(

**Comment by MichaIng** [comment]
@sChUhBiDu 
High likely this is due to a current permissions issue with mpd. Please try the following:
```
sed -Ei '/^(user|group)[[:blank:]]/d' /etc/mpd/mpd.conf
G_CONFIG_INJECT 'User=' 'User=mpd' /lib/systemd/system/mpd.service '\[Service\]'
G_CONFIG_INJECT 'PermissionsStartOnly=' 'PermissionsStartOnly=true' /lib/systemd/system/mpd.service '^User=mpd'
usermod -a -G audio,dietpi mpd
systemctl daemon-reload
systemctl restart mpd
```

**Comment by sChUhBiDu** [comment]
Thanks but this [https://github.com/Fourdee/DietPi/issues/2522](url) help me already.

1 problem left: when I want to save a **playlist** it says "**Invalid filename**"

How can I install latest version of MyMPD?

**Comment by MichaIng** [comment]
@sChUhBiDu 
We currently froze the version due to a database update issue with the latest release some time ago: https://github.com/Fourdee/DietPi/issues/2156

But you can try out the most current release (actually from today 😄) and if it works, we can finish this topic and implement auto install of latest release into DietPi-Software. To try it out:
```
cd /tmp
wget https://github.com/jcorporation/myMPD/archive/v5.1.0.tar.gz
tar xf v5.1.0.tar.gz
cd myMPD*
./mkrelease.sh
cd /tmp
rm -R myMPD*
```

**Comment by MichaIng** [comment]
Latest upstream version is already installed since DietPi v6.25. We simply download the master branch archive, which matches the latest release/is release branch.
