### ISSUE TITLE
DietPi-Software | Kodi: Increase default gpu_mem to 512 on 1024M devices

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2365]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=12&t=5341

**Comment by Fourdee** [comment]
320MB recommended by: https://forum.kodi.tv/showthread.php?tid=217170&pid=1918800#pid1918800

Seems reputable. Lets go with 320MB, users can always increase as needed in ```dietpi-config```.

**Comment by Fourdee** [comment]
Testing passed, completed.
