### ISSUE TITLE
FeatHub | Vote for or add your requests for DietPi

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2368]
We added DietPi to **FeatHub**: https://feathub.com/MichaIng/DietPi
Will go through our open requests and add them there. Hope this gives us a better overview and priorities.

#### Please always open an issue/request on [GitHub](https://github.com/MichaIng/DietPi/issues) as well to discuss and develop!

@Fourdee 
Hope you agree 😉.

**Comment by Fourdee** [comment]
@MichaIng 

Yep, love it, nice idea 👍
