### ISSUE TITLE
Softether VPN Server.  Pls restore to optimized software.

### ISSUE THREAD

**Issue by ac-anhydros** [MichaIng/DietPi#237]
Please reinstate softether vpn server as a choice in the dietpi optimize software, both for the VM and the distro.  We are using it from v 100 on a VM, and it is far better than openvpn server.

Alternatively, could you e-mail me a script or directions to install it on the latest dietpi distro?

Thanks!

**Comment by Fourdee** [comment]
@ac-anhydros 
Softether was removed in v104: https://github.com/Fourdee/DietPi/pull/154

> DietPi-Software | Softether VPN server has been removed. Its setup was overcomplicated for the end user. OpenVPN server offers a much better and simpler VPN experience for the user.

For the moment, it wont be returning. 

You can find the softether VPN installation code in v103 of DietPi. Simply browse the commits prior to v104:
https://github.com/Fourdee/DietPi/tree/0fcef522c9975121ce938278fa8e7e687e00557e

Search dietpi-software script for `SOFTETHERVPNSERVER`. You'll find the installation code and config code there.
