### ISSUE TITLE
META | Commit changes directly to Debian repo

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2380]
If we find improvements for certain Debian packages that are not really a bug, instead of using the [bug tracker](https://www.debian.org/Bugs/), I found the [Debian GitLab page](https://salsa.debian.org/) can be used, e.g.: https://salsa.debian.org/debian/cron/merge_requests

Just a quick note to devs/contributors to keep in mind. It is always better to share a benefit across all Debian users instead of just DietPi users.

It requires an account of course, but this is only for the Debian GitLab instance and nothing else.

**Comment by Fourdee** [comment]
@MichaIng 

>  It is always better to share a benefit across all Debian users instead of just DietPi users.

Agree 👍
