### ISSUE TITLE
HQPlayer NAA (networkaudiod) upgrade from 3.5.4 to 3.5.5

### ISSUE THREAD

**Issue by volpone** [MichaIng/DietPi#2387]
HQPlayer NAA (networkaudiod) version is 3.5.4-38 in last DietPi released version (6.19.7).
NAA has been upgraded from 3.5.4-38 to 3.5.5-39
See: https://www.signalyst.eu/bins/naa/linux/stretch/
Thank's for your work !

**Comment by MichaIng** [comment]
@volpone 
Thanks for the info. We will patch for v6.20.

Hmm would be great if there was a way to automatically grab the latest release 🤔.

**Comment by Fourdee** [comment]
@volpone 

Thanks for heads up 👍 

@MichaIng 

Yep, would be nice to have a latest version link, however, for now i'll manually set the latest version.

**Comment by Fourdee** [comment]
Completed: https://github.com/Fourdee/DietPi/commit/2c767921ba7458de9b431011b611e9c1a31a7c1f
