### ISSUE TITLE
DietPi-Config | RPi: Disable HDMI + framebuffer completely via config.txt entries

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2401]
Ref: https://github.com/raspberrypi/userland/issues/447

Should be preferred, instead of manually running `tvservice -o` on boot. Also framebuffer is disabled completely, so does not need to be reduced.
The downside is, that there is no chance to re-enable HDMI without a reboot, but with our framebuffer x=y=16 this was anyway practically the case.

PR up, which as well removes some other obsolete settings: https://github.com/Fourdee/DietPi/pull/2402

**Comment by Fourdee** [comment]
@MichaIng 

Good work, tested on RPi with HDMI disabled, no output to HDMI TV. Will mark as completed 👍
