### ISSUE TITLE
Networking issue and a bug

### ISSUE THREAD

**Issue by krishnasen2401** [MichaIng/DietPi#2403]
Device rpi3 with latest dietpi install
Problem 1
Config 1
1.wired connect DHCP (to tplink portable router)(just for control and readyshare media transfer)
2.wifi DHCP to mobile hotspot(for internet)
Config 2 (to confirm problem)
1.wired connect DHCP and static (normal router as lan)(just for control and readyshare media speed) with internet access
2.connected to the mobile hotspot

Observation
The raspberry pi is not able to connect to internet.
That the system is not able to connect to internet like normal system based on speed or connection status

The senario raspberry pi is used as media center which downloads(sonarr +transmission) and streams media connected to college wifi(medium strength signal) to stream to phone buffering occurs and disconnection if signal interruption so I had to connect via ethernet using the tplink wr702n router to control the device via android phone

Bug(install and uninstall)
Netdata monitoring doesn't appear in uninstall menu

**Comment by Fourdee** [comment]
@krishnasen2401 

Many thanks for the report 👍 

> Netdata missing from uninstall

Unable to replicate on our test system:
![image](https://user-images.githubusercontent.com/7077026/50960847-3c542500-14be-11e9-8415-568b957335db.png)

The installation may have failed. Please try the following to force install flag, and allow removal:
- edit ```/DietPi/dietpi/.installed```
- change ```aSOFTWARE_INSTALL_STATE[65]=0``` to ```=2```
- Save changes
- ```dietpi-software``` will now show the uninstall option for netdata

> Observation
The raspberry pi is not able to connect to internet.
That the system is not able to connect to internet like normal system based on speed or connection status

DietPi is designed to be used with a single connection with internet (eg: ETH or WiFi). For advanced connections with multiple network cards, you'll need to manually configure routing on the device.
https://www.cyberciti.biz/faq/howto-linux-configuring-default-route-with-ipcommand/

**Comment by krishnasen2401** [comment]
The write error guess due to unexpected shutdown maybe

Have also noticed that external HDD doesn't get uncounted similar to PC just remove the USB cord(only noticed after hearing the disk sound when we just remove it in middle)
sed: couldn't open temporary file /boot/sed62qGCF: Read-only file system ( for changing autobot option)

This was when installing netdata
[ SUB1 ] DietPi-Software > Configuring Sonarr: automatically download TV shows sed: couldn't open temporary file /boot/sed70sEYO: Read-only file system
sed: couldn't open temporary file /boot/sedudxWWR: Read-only file system
sed: couldn't open temporary file /boot/sedRngwrS: Read-only file system

**Comment by Fourdee** [comment]
@krishnasen2401 

> The write error guess due to unexpected shutdown maybe

Yep, you need to shutdown the system before pulling out the power. 

Also, before unplugging USB harddrives, you must dismount them using ```dietpi-drive_manager``` before-hand. Not doing this will render filesystem corruptions. Try to run a repair on the disk, using the above command.

**Comment by krishnasen2401** [comment]
The unexpected power off was due to battery

I asking in case of "poweroff" command for system shutdown which stop each and every service I didn't notice it umounting the storage(the user data is not transferred only sonarr download are stored)

**Comment by Fourdee** [comment]
@krishnasen2401 

> I asking in case of "poweroff" command for system shutdown which stop each and every service I didn't notice it umounting the storage(the user data is not transferred only sonarr download are stored)

Once the device has powered off, the drive may still be powered. Depends on the SBC device used.

Regardless, once ```poweroff``` is used, and the system has completely shutdown, it is safe to unplug the HDD. No need to dismount for poweroff.

**Comment by krishnasen2401** [comment]
So poweroff doesn't auto unmount the drive right I have to do it manually.so that the force shut sound doesn't come like in pc

**Comment by MichaIng** [comment]
In most cases poweroff should stop services and disk I/O gracefully,  so you can power/plug off the drives then safely. But especially with temporary mounted drives (not via fstab) it is possible that e.g. writes hang and the drive is not unmounted gracefully. So jep to be safe, unmount it manually first.

If you added the drive via dietpi-drive_manager, it is added to fstab, so included into the regular systemd schedule and there is no need to manually unmount for sure.

**Comment by Fourdee** [comment]
@MichaIng 

>  it is possible that e.g. writes hang and the drive is not unmounted gracefully. So jep to be safe, unmount it manually first.

Good point 👍 Some USB <> SATA converters may cache writes on chip.

**Comment by krishnasen2401** [comment]
I noticed unmouted first before boot partion
