### ISSUE TITLE
DietPi-Software | Remove Tomcat 8

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2411]
- For Stretch via backports: https://packages.debian.org/stretch-backports/tomcat9

**Comment by Fourdee** [comment]
62 installs, will flag as low priority + info

**Comment by MichaIng** [comment]
@Fourdee 
Jep basically the question is, if an existing Tomcat8 instance can be upgraded safely to Tomcat9. Simply installing the APT package at least is a simple task.

**Comment by MichaIng** [comment]
Added to next version milestone. We'll basically remove the Tomcat 8 install option, which is only available on Debian Stretch, where we don't ship any images for since a while, and replace it with Tomcat 9, only available on Debian Buster and Bullseye, and theoretically via `stretch-backports`.

**Comment by MichaIng** [comment]
Actually there is not really a point in keeping Tomcat in our software list. We'd now migrate to tomcat9, tomcat10 is already in the pipeline (experimental suite) and the tomcat8 package in Raspbian Buster and above is actually a pretty outdated one while on Stretch there is a much newer one available already. And all that we do aside of installing the APT package is setting the JAVA_HOME setting, which is not required as Tomcat is able to find it automatically, when unset, based on common OpenJDK and Oracle JDK paths.

I'll hence remove the install option now, refer to simply using APT to install tomcat9 instead on current Debian releases. If a new reason appears, e.g. for reasonably change the default config or setup another Java application with Tomcat automatically, we can re-implement it with new version and proper config block.
