### ISSUE TITLE
DietPi-Software | Home Assistant: Skip virtualenv/pyenv tu run install script

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2418]
Ref: https://dietpi.com/phpbb/viewtopic.php?t=5369

Currently we run the install script within a virtual environment (virtualenv/pyenv), which runs in a subshell of again a sudo subshell, so three (or more) orders of abstraction... There everything, especially Python is built from source, which takes a veeery long time. Users report more than 40 minutes (on SBC), only for the Python build, afterwards pip installs again take time.

Of course it is always safe to run stuff in a sandbox, but if we know what we do, it should be not required.

- [ ] Check current HA install instructions
- [ ] Try to reduce the abstraction layers, at least `su ... eval ...` is not required. At best install outside of `pyenv`, make it use Python (+pip) from APT packages instead.

**Comment by MZorzy** [comment]
#2374

**Comment by MichaIng** [comment]
I close this in favour of the existing very similar topic.
