### ISSUE TITLE
Pinebook | initramfs-tools fails on APT upgrade

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2429]
# Workaround/Fix: https://github.com/Fourdee/DietPi/issues/2429#issuecomment-455994355

Ref: https://dietpi.com/phpbb/viewtopic.php?f=9&t=5422&start=10#p16131

Suspicious log part:
```
update-initramfs: Generating /boot/initrd.img-4.20.0-sunxi64
/etc/initramfs/post-update.d//99-uboot: 3: .: Can't open /etc/armbian-release
run-parts: /etc/initramfs/post-update.d//99-uboot exited with return code 2
```

There seems to be a post-update script for the initramfs placed on the base image, which obviously is ARMbian?

The APT upgrade makes the system unbootable. The initramfs is removed first, then the generation of the new one fails due to above, so the system is left without any initramfs.

I am not sure now, if the uboot actually ships it's own initramfs that enables the system to boot and if thus, the `initramfs-tools` package is not required on our Pine64 images, similar to RPi?

____________

Further info:
`ii linux-stretch-root-dev-pinebook-a64 5.67 arm64 Armbian tweaks for stretch on pinebook-a64 (dev branch)`

This package might ship the post-update script.

Generally kernel is on v4.20, due to all related packages are from `dev` branch. If it works reliable it's okay, but this is really bleeding edge. Perhaps there is a stable branch where we should install firmware/kernel/bootloader from on our image?

**Comment by MichaIng** [comment]
Ah lol found the already applied fix:
- https://github.com/Fourdee/DietPi/commit/f10e9f2eabe854d199c15a37924ef78b02eb6414
- https://github.com/Fourdee/DietPi/commit/ffd743a3a7b1932dae63eb96ddb42159683803ca

However, I think we should find the root of this and remove the APT trigger that was obviously placed by ARMbian: `ls -Al /etc/initramfs/post-update.d/`

**Comment by Fourdee** [comment]
@MichaIng 

Yep, already fixed, however if the v6.20 patch fails, users will need to manually apply the ```/etc/armbian-release``` file before updating.
```
cat << _EOF_ > /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=pinebook-a64
BOARD_NAME="Pinebook A64"
BOARDFAMILY=sun50iw1
VERSION=5.67
LINUXFAMILY=sunxi64
BRANCH=next
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
_EOF_
```

>  I think we should find the root of this and remove the APT trigger that was obviously placed by ARMbian:

I'd prefer we leave it with the file left in place. Prevent any further issues down the road should that file and/or its contents be required in any form.

**Comment by MichaIng** [comment]
@Fourdee 
> I'd prefer we leave it with the file left in place. Prevent any further issues down the road should that file and/or its contents be required in any form.

Good point. However perhaps we could additionally remove the offending APT drop-in trigger (still keeping `/etc/armbian-release`), if it does nothing useful. Generally good to know/learn about the custom ARMbian changes.

**Comment by Fourdee** [comment]
Will update image in following ticket:
https://github.com/Fourdee/DietPi/issues/2026
