### ISSUE TITLE
DietPi-Software | Pi-hole fails to install due to missing php-opcache

### ISSUE THREAD

**Issue by rox-wolf** [MichaIng/DietPi#2438]
#### Details:
- Date           | Fri 25 Jan 10:54:09 GMT 2019
- Bug report     | Bug report sent, reference code: 633aaeb5-6038-4947-b643-ab269f99e9e8
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Meveric
- SBC device     | Odroid XU3/XU4/HC1/HC2 (armv7l) (index=11)
- Kernel version | #1 SMP PREEMPT Thu Aug 23 05:59:33 UTC 2018
- Distro         | stretch (index=4)
- Command        | G_AGI: php-fpm php-curl php-gd php-apcu php-mbstring php-opcache php-zip php-xml php-mcrypt php-sqlite*
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:
Try installing pi-hole using dietpi-software and using optimized pi-hole software.

#### Expected behaviour:
It should install php with dependencies.

#### Actual behaviour:
apt cant find package **php-opcache**

#### Extra details:
I have also tried few apt debian mirrors, but no luck.

#### Additional logs:

Log file contents:
E: Package 'php-opcache' has no installation candidate
```
![op-cache](https://user-images.githubusercontent.com/37755494/51743253-c0a0cd80-20a4-11e9-89f3-228ed3699954.png)

**Comment by MichaIng** [comment]
@rox-wolf
Many thanks for your report.

Hmm, obviously Debian removed the alias/meta package from the repo. Only `php7.0-opcache` can be found. Might be also the case for other PHP packages. I think on Stretch we should switch to php7.0-* package naming, besides APCu, Redis and some where those do not exist.

We have to check which packages are affected by this change to provide a reliable solution. I can do that in 6 hours after work.

**Comment by MichaIng** [comment]
@rox-wolf 
Okay quite easy to fix:
`sed -i "s/^[[:blank:]]*PHP_APT_PACKAGE_NAME='php'/	PHP_APT_PACKAGE_NAME='php7.0'/" /DietPi/dietpi/dietpi-software`

Then retry Pi-hole install.
___________
#### Dev todo
🈯️ Test succeed on VM
- [x] At best test on RPi Stretch, just in case the Raspbian repo has differences.
______________
PR up: https://github.com/Fourdee/DietPi/pull/2441

**Comment by Fourdee** [comment]
@MichaIng 

RPi + Pi-Hole install = 🈯️ 

```

[  OK  ] DietPi-Software | APT installation for: php7.0-fpm php7.0-curl php7.0-gd php-apcu php7.0-mbstring php7.0-opcache php7.0-zip php7.0-xml php7.0-mcrypt php7.0-sqlite*, please wait...
```

**Comment by rox-wolf** [comment]
Applied the sed fix and Pihole installed successfully 👍

**Comment by MichaIng** [comment]
@rox-wolf 
Great, thanks for reply. I will leave the issue opened, just in case we've overseen something in relation with any other PHP dependant software. Want to go through them once carefully tomorrow moring, before v6.20 release.
