### ISSUE TITLE
DietPi LetsEncrypt Nginx missing plugin !?

### ISSUE THREAD

**Issue by docgalaxyblock** [MichaIng/DietPi#2443]
Dietpi 6.19.7 ODROID XU4 Cloudshell-1

Today I made a fresh DietPi install 
When I came to my Webserver and I tried to encrypt it, it fails.
Her my terminal output
 
DietPi-LetsEncrypt
─────────────────────────────────────────────────────
 Mode: Running CertBot

[  OK  ] DietPi-LetsEncrypt | Nginx webserver detected
[  OK  ] DietPi-LetsEncrypt | Desired setting in /etc/nginx/sites-available/default was already set:    server_name ********;
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested nginx plugin does not appear to be installed
[FAILURE] CertBot failed with error code (1), please check it's terminal output. Aborting...

I changed nginx-light to nginx-extras without any change

Greetings

**Comment by MichaIng** [comment]
@potter-91 
Jep known issue and fixed with v6.20: https://github.com/Fourdee/DietPi/commit/4fa045e60fa2b868abbf8ebeb5eeeef21ba1eafe

Please install `apt install python-certbot-nginx` and retry.

**Comment by docgalaxyblock** [comment]
Oh OK
Could't find an existing issue
Nice to hear that it is fixed ^^

**Comment by MichaIng** [comment]
@potter-91 
I will mark as close, but please reopen if there is still an issue.
