### ISSUE TITLE
DietPi-Software | Add NFS installation options for Client and Server

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#246]
NFS server is better optimized for *nix sharing (all computers in home running linux, *BSD)

**Comment by Fourdee** [comment]
@stefaniniMM 
Thanks for the request and apologies for the delay in this response. I'll setup this ticket accordingly and look into your request when possible.

**Comment by xenfomation** [comment]
@Fourdee -- in initial testing, NFS4 is rather straight forward.  It is easy enough to create a default NFS4 Server/Client install with templates for /etc/exports, etc.

The questions I have -- to fully implement this for user needs -- would be if a sub-menu is warranted to ask:

Export path
NFS version
IP Exclusions
Etc

In the next 24 hours I can get a basic NFS4 server installer implemented to dietpi-software that creates:

/mnt/nfs4/
/etc/exports
/etc/nfs-common
/etc/nfs-kernel-common
Creates an NFSv4 service

Either way is fine with me as I do think NFS is a good thing for us YP/Old School/Penguin lovers.

Thanks!
![nfs1](https://cloud.githubusercontent.com/assets/10519408/14947046/a7dacb56-0ffa-11e6-82a5-3d386ccac4f4.PNG)

**Comment by xenfomation** [comment]
Oh, cool factor is -- just like Samba -- I have staggered out an NFS Client (common packages) and NFS Server (common + core).  The part next is to follow in footsteps to assist the user in configuring their NFS Server (if that is selected), etc.

@Fourdee  &  @stefaniniMM -- So I have been actively (albeit slowly) incrementing this with care and I hope this update finds you all in kind.

**Comment by xenfomation** [comment]
Options have been subbed in -- expanding upon NFS server install, such as with Samba.

Thanks.

**Comment by xenfomation** [comment]
Delay to request has been to ensuring I reconfigure git scripts/git desktop to avoid collisions. 

Thanks, everyone.

**Comment by Fourdee** [comment]
Notes to self:
- :u6307: More testing of both server + client required
- :u6307: Security: Add docs to explain how to limit users by IP address > http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=2821#p2821

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/18387665/d8eb7a72-7695-11e6-8211-9a9aa8a6abf6.png)

**Comment by Fourdee** [comment]
Done.
- NFS server | dietpi-software > DietPi-Optimized
- NFS client | dietpi-software > Linux | dietpi-config > networking options: NAS

Added to DietPi.

NB: Not added to fileserver choice system.

**Comment by msdos** [comment]
I had some problems when using the NFS client in Dietpi. When trying to configure, giving my NFS server ip, the following message is shown (it's really fast):

```
mount.nfs4: Protocol not supported
```

After some help from these guys http://unix.stackexchange.com/a/205736 and http://dietpi.com/phpbb/viewtopic.php?f=11&t=791, I edited `/etc/fstab` and changed to 

```
192.168.1.1:/media/ /mnt/nfs_client nfs auto,vers=3,_netdev 0  0
```

And now it's working. Would it be the case to add an option in NFS config "Do not use nfs4" or something like that when configuring nfs? The default now is to use `nfs4`thus giving the error above.

**Comment by Fourdee** [comment]
@msdos 

Thanks for the feedback and solution 👍 I'll get this information added in the script.
