### ISSUE TITLE
DietPi-Software | Add Friendica: A Personal Social Networking Platform

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#247]
[Friendica ](http://friendica.com/)is a communications platform for integrated social communications utilizing decentralized communications and linkage to several indie social projects - as well as popular mainstream providers.

"Currently, Friendica users can integrate contacts from Facebook, Twitter, Diaspora, GNU social, App.net, Pump.io and other services in their social streams. Communication is bi-directional wherever possible. There is also a bridge to include email contacts and RSS feeds. Additionally, connectors allow cross-posting to blog platforms like WordPress, Livejournal, Tumblr and Posterous. As the user account are spread over many servers, the addresses are composed of three parts, similar to email addresses, the user name, at "@" and the domain name of the Friendica instance." - Source wiki

[Installation](https://github.com/friendica/friendica/blob/master/INSTALL.txt)

**Comment by Fourdee** [comment]
@Zone22 

Thanks for the request. I will look into this when I can.

**Comment by xenfomation** [comment]
@Fourdee & @Zone22 --

I have an order of tasks I've been doing my best to contribute to, however I took 5 minutes to check out Friendica and it seems rather nice.  I have items for DietPi to correct pronto, so the point is I will circle back to this ASAP as it seems straight forward enough to test and discuss.

**Comment by ghost** [comment]
Excellent I look forward to it

**Comment by xenfomation** [comment]
Still prototyping outside of testing. Manual install, size, and testing before I share the results with @Fourdee.

Thanks for the patience @zone22

**Comment by xenfomation** [comment]
Still prototyping outside of testing. Manual install, size, and testing before I share the results with @Fourdee.

Thanks for the patience @zone22

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
