### ISSUE TITLE
DietPi-Update | v6.20.5 issue sum-up

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2473]
To get an overview and for reference, I sum up the issues, users faced when updating to v6.20.5 here.
There were two issues:

#### Issue 1
- `chmod: cannot access '/etc/profile.d/dietpi-*.sh': No such file or directory`
- Ref: https://github.com/Fourdee/DietPi/issues/2458, https://github.com/Fourdee/DietPi/issues/2471
- It is still an issue when updating from v6.19.7 or lower.
- I have no idea how this can happen, not even when considering `async`.
  - Update places new code: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-update#L346
  - Incremental patch applies new install stage system and restarts update nested: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L90
  - Nested incremental patch now goes on and removes `/etc/profile.d/dietpi-unsupported_terminal.sh`: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L1540
  - After nested update has finished, initial update is killed + incremental patch exits: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L49
  - So after `/etc/profile.d/dietpi-unsupported_terminal.sh` removal, in every case update finishes or exits (on fresh image as well), so no idea how this error can occur so far.
  - However to resolve this, I did a quick patch by placing a fake script, that has no affect on boot, is removed at end of incremental patches anyway and prevents the error: https://github.com/Fourdee/DietPi/pull/2460/files
  - But this was no good solution, since the error at least gives a hint that the wrong update code is executed, which should be better fixed instead worked around.
    - For example the old code recreates `.update_stage`: https://github.com/Fourdee/DietPi/blob/8c629fa34e0d47f427c67066c0a1098543c5203e/dietpi/dietpi-update#L477
    - This on v6.20.5 `patch_file` can lead to `[[ -f /DietPi/dietpi/.update_stage ]]` => but not `(( $(</DietPi/dietpi/.install_stage) == 1 ))` => `echo 0 > /DietPi/dietpi/.install_stage` => On next reboot, login causes first run update (that might even find an update due to issue 2 below) and `dietpi-software` prompt.

#### Issue 2
- DietPi-RAMdisk stopping too late at shutdown, after `boot.mount` has already been unmounted: `cp: failed to access '/boot/': Host is down`
- This should be actually not possible, since default dependencies make systemd units run after `sysinit.target` which is reached after `local-fs.target` which is again after every single mount.
- ... and now while writing this I found the reason:
  - We already recognized that `x-systemd.automount` removes drives from the `local-fs.target`. For this reason we patched it with v6.20 as well: https://github.com/Fourdee/DietPi/blob/master/dietpi/patch_file#L1562
  - But of course in current session the automount is still active. The update now removes `After=boot.mount` from DietPi-RAMdisk.
  - So for this one single shutdown phase, `boot.mount` is still not tied to `local-fs.target` while DietPi-RAMdisk is not tied anymore to `boot.mount`, which causes the disk sync to fail in some cases. It does not always fail, but it can, depends on the final systemd order which has some variety.
- Okay then this issue leads to:
  - v6.17.9 "recovered" on reboot
  - `.update_stage` not being available, since this was removed from disk as well, causing with old code another first run update on reboot, possible looping. This can actually explain issue 1 then, but only in combination with a reboot.
  - `.dietpi-autostart_index` not being available, if index was `0` causing with old code: `/DietPi/dietpi/login: line 160: ((: > 0 : syntax error: operand expected (error token is "> 0 ") `https://github.com/Fourdee/DietPi/issues/2465#issuecomment-458576926

Both issues in combination mess the whole install stage system, besides causing error messages, update loops, first run setup prompts and all this...
However v6.20.6 should fix at least issue two: https://github.com/Fourdee/DietPi/pull/2470/files
- `sync` after removing `.update_stage` to prevent possible update loops when `async` is an issue. This as well should sync new DietPi code.
- New `dietpi-update` as well contains a `sync` now before running incremental patches: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-update#L355
- When applying new install stage system, `echo 0 > /DietPi/dietpi/.install_stage` is only applied, when `(( $(</DietPi/dietpi/.install_stage) < 1 ))` to prevent unintended first run update/setup prompts.
- Initial quick fix is reverted, so if `chmod: cannot access '/etc/profile.d/dietpi-*.sh': No such file or directory` occurs it will not go on running old update code, instead, if still reported by users, rerun `dietpi-update 1`, in case with leading `sync` is the safer solution.
- And finally and most importantly, re-add all required mounts to RAMdisk/RAMlog `After=`. Even if this should be not required, when `x-systemd.automount` is removed from `/boot`, leave it inside: Failsafe!

**Comment by MichaIng** [comment]
@Fourdee 
For review. Perhaps you have some idea, especially how issue 1 could have occurred and how to assure this does not happen.

**Comment by Fourdee** [comment]
@MichaIng 

Thanks Micha, really appreciate the quick investigations and fixes 👍 

Might also be worth us restarting the RAMdisk after ```dietpi-update``` is completed, to ensure disk write as a fail safe?
- https://github.com/Fourdee/DietPi/commit/212498cc6053eac21e9d40b0bcf82f7329da6c8f

> Issue 1

Initially unsure, will take a look.

**Comment by MichaIng** [comment]
@Fourdee 
> Might also be worth us restarting the RAMdisk after dietpi-update is completed

Jep makes sense!

**Comment by MichaIng** [comment]
Investigating `Issue 1`, so far no success to replicate or even think of a possible path, leading to the error 🤔: https://github.com/Fourdee/DietPi/issues/2471#issuecomment-459092596
