### ISSUE TITLE
[dupe] Software Update error

### ISSUE THREAD

**Issue by Roxas72** [MichaIng/DietPi#2485]
#### Details:
- Date           | Fri  1 Feb 13:42:10 GMT 2019
- Bug report     | N/A
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | chmod -R +x /DietPi /var/lib/dietpi/services /etc/cron.daily/dietpi /etc/cron.hourly/dietpi /etc/profile.d/dietpi-*.sh /etc/bashrc.d/dietpi-bash_completion.sh /etc/bashrc.d/dietpi-login.sh /etc/bashrc.d/dietpi-posix-set-locale.sh /etc/bashrc.d/dietpi-ps1_kill_animation.sh /etc/bashrc.d/dietpi-unsupported_terminal.sh
- Exit code      | 1
- Software title | DietPi-Update

#### Steps to reproduce:

Well I've just done the dietpi-update command after the update available message was displayed

#### Expected behaviour:

Update I guess?

#### Actual behaviour:

Not update due to this error that I cannot really understand (not really an expert here!)

#### Extra details:
I did the update command and everything seemed to be just fine, the only odd thing was that at the end there was a message about Sickrage that has been dismissed and stuff. But I thought the update itself was fine because it even asked me to reboot the raspi. But after logging back in, the SW info displayed on top was the previous one and the update message was still there, so I re-gave the command and the already mentioned error occurred. Anything to solve this? 

#### Additional logs:
```
Log file contents:
chmod: cannot access '/etc/profile.d/dietpi-*.sh': No such file or directory
```

**Comment by Fourdee** [comment]
@Roxas72 

Hi, many thanks for the report 👍 

Please see following ticket for solution: https://github.com/Fourdee/DietPi/issues/2471
