### ISSUE TITLE
Can't boot my rock64 board with a new image

### ISSUE THREAD

**Issue by FloRup** [MichaIng/DietPi#2486]
Hello,
I just got my rock64 board and because I liked dietpi on my rpi3+ I wanted to install it on there too.

I used etcher to burn the recently downloaded rock64 image to a sd card. I recently did this with another device and I had no problem so I think nothing went wrong there.

The board wont boot. I connected a tv via hdmi and it shows a bunch of text and then reboots in 10 seconds. It does this forever.

This is the output on the screen https://imgur.com/a/Dugz7CC

The only error I can see is error while loading shared library's: usr/lib/aarch64-linux-gpu/libiz4.so.1: invalid ELF header

I googled that but couldn't find anything helpful.

**Comment by Fourdee** [comment]
@FloRup 

Hi, thanks for the report 👍 

Looks like a kernel dump during boot.

Could be either of:
- Bad image write
- Hardware related issue (PSU/SD)
- Issue with our image.

#### Please try the following: https://github.com/Fourdee/DietPi/issues/769#issuecomment-283030267

If problems persist, please state:
- PSU used (make, model, amps)
- SD/EMMC used

**Comment by FloRup** [comment]
> 
> * PSU used (make, model, amps)
> * SD/EMMC used


-I got the psu with the board via amazon(pine64) [link](https://www.amazon.de/gp/product/B0786Q5JQ5/ref=ppx_yo_dt_b_asin_title_o01__o00_s00?ie=UTF8&psc=1) It has 3 amps and I highly doubt this is the reason.

-[This is the SanDisk Ultra SD card I bought for it](https://www.amazon.de/gp/product/B073S8LQSL/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1)


> Please try the following: #769 (comment)

I try that  now and will come back if it works

**Comment by FloRup** [comment]
> #### Please try the following: [#769 (comment)](https://github.com/Fourdee/DietPi/issues/769#issuecomment-283030267)

OK I tried that but it made no difference.

**Comment by Fourdee** [comment]
@FloRup 

Will redo our image to cover any issues our end. Once its ready for testing, i'll let you know.

**Comment by Fourdee** [comment]
@FloRup 

🈯️ Image updated and tested locally fine, please retry with this image:
- https://dietpi.com/downloads/images/DietPi_Rock64-ARMv8-Stretch.7z

**Comment by FloRup** [comment]
It works now thanks.
I connected with ssh and I'm going through the installation right now
