### ISSUE TITLE
RPi Cam autostarts when installed, disabling normal Pi Camera function

### ISSUE THREAD

**Issue by JohnAllen** [MichaIng/DietPi#249]
Just wanted to say thank you for DietPi and also that it would be great to get some notification that installing DietPiCam (or what it was exactly called) prevents the normal function of the `raspi*` programs.

**Comment by Fourdee** [comment]
@JohnAllen 
Hi John,

Thanks for the feedback.

DietPiCam is essentially https://github.com/silvanmelchior/RPi_Cam_Web_Interface thats been modified for DietPi. This includes support for optional USB drives, and works with our optimized LASP stack.
In regards to the RPi camera and DietPiCam. Are you referring to the autostart of the camera during boot which prevents other programs using it? Or something else?

**Comment by JohnAllen** [comment]
When RPi Cam Web is installed, it autoruns, autostarts, which wasn't obvious to me.  When I went to use the Pi camera as usual it didn't work because there was already the RPi Cam Web using it.  It just wasn't obvoius that that would occur when I installed that software, so it would have been great to know that it would autorun and disable stuff like `raspistill`, etc.

**Comment by JohnAllen** [comment]
Just a warning somewhere maybe, or not autostarting that for users like me who thought it sounded cool, but didn't necessarily want it to autorun the second I got DietPi configured and up and running.

**Comment by Fourdee** [comment]
@JohnAllen 
Thanks John. 
I'll add a whiptail message that will warn the user after selecting DietPiCam for install. I'll also include the instructions to disable the autostart of DietPiCam in there aswell.

**Comment by Fourdee** [comment]
@JohnAllen 
Completed.
Starting from v114, this notification will show when the user selects DietPiCam for installation:
![untitled](https://cloud.githubusercontent.com/assets/7077026/14060904/f05851c6-f369-11e5-8815-57e476acca07.png)

You can also use the following from terminal.

```
/etc/dietpi/dietpi-software/services/raspimjpeg.service stop
/etc/dietpi/dietpi-software/services/raspimjpeg.service start
```

**Comment by JohnAllen** [comment]
Wow, awesome.  Excellent work.  That's perfect.
