### ISSUE TITLE
Nextcloud installation fails with error about OPcache

### ISSUE THREAD

**Issue by theAkito** [MichaIng/DietPi#2496]
#### Details:
- Date           | Mon  4 Feb 04:37:16 CET 2019
- Bug report     | N/A
- DietPi version | v6.20.6 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model A+ (armv7l) (index=3)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | ncc maintenance:install
- Exit code      | 254
- Software title | DietPi-Software

#### Steps to reproduce:

1. Install Nextcloud through `dietpi-software`.

#### Expected behaviour:

- Nextcloud should be installed.

#### Actual behaviour:

- Installation interrupts with error.

#### Extra details:

- Selected Nextcloud to be installed from `dietpi-software`. DietPi was freshly set up, nothing was on storage, yet.

#### Additional logs:
```
[  OK  ] DietPi-Software | Connection test: https://raw.githubusercontent.com/Fourdee/DietPi/master/.conf/dps_114/nginx.nextcloud.conf
[  OK  ] DietPi-Software | wget https://raw.githubusercontent.com/Fourdee/DietPi/master/.conf/dps_114/nginx.nextcloud.conf -O 114.nginx.nextcloud.conf
[  OK  ] DietPi-Software | cp -f 114.nginx.nextcloud.conf /etc/nginx/sites-dietpi/dietpi-nextcloud.conf
[  OK  ] DietPi-Software | Cleaning download directory
[ INFO ] DietPi-Software | Enable 4-byte support for MariaDB
[  OK  ] DietPi-Software | systemctl restart mariadb
[  OK  ] DietPi-Software | systemctl start redis-server
[FAILED] DietPi-Software | ncc maintenance:install

```
Log file contents:
Mon Feb  4 04:35:56 2019 (22158): Fatal Error Zend OPcache cannot allocate buffer for interned strings

```

**Comment by MichaIng** [comment]
@Akito13 
Thanks for your report.

I was searching where I found the error already: https://github.com/Fourdee/DietPi/issues/2293
I will add your report there as post, further discussions in the other topic then. Since you have RPi3, it is no device specific issue then.

Will mark this as closed in favour of: https://github.com/Fourdee/DietPi/issues/2293
