### ISSUE TITLE
Error while updating APT | Read error (-5: DATA_ERROR_MAGIC)

### ISSUE THREAD

**Issue by tkrusterholz** [MichaIng/DietPi#2497]
#### Details:
- Date           | Mon  4 Feb 15:15:19 GMT 2019
- Bug report     | N/A
- DietPi version | v6.19.7 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B+ (armv7l) (index=3)
- Kernel version | #1159 SMP Sun Nov 4 17:50:20 GMT 2018
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Update

#### Steps to reproduce:

1. Attempting to run dietpi-upgrade from v6.19.7 to v6.20.6

#### Expected behaviour:

- Normal upgrade

#### Actual behaviour:

- Upgrade fails because some Debian repositories appear to not be signed with a cert and/or public keys are missing

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Ign:3 http://ftp.nl.debian.org/debian stretch InRelease
Get:4 http://ftp.nl.debian.org/debian stretch Release [118 kB]
Get:5 http://ftp.nl.debian.org/debian stretch Release.gpg [2,434 B]
Hit:6 https://archive.raspberrypi.org/debian stretch InRelease
Ign:5 http://ftp.nl.debian.org/debian stretch Release.gpg
Hit:1 https://dl.ubnt.com/unifi/debian unifi-5.9 InRelease
Get:7 http://ftp.nl.debian.org/debian stretch/main armhf Packages [6,918 kB]
Hit:8 http://ftp.nl.debian.org/debian stretch/main Translation-en
Ign:8 http://ftp.nl.debian.org/debian stretch/main Translation-en
Hit:8 http://ftp.nl.debian.org/debian stretch/main Translation-en
Ign:8 http://ftp.nl.debian.org/debian stretch/main Translation-en
Err:8 http://ftp.nl.debian.org/debian stretch/main Translation-en
  BZ2_bzread: /var/lib/apt/lists/partial/ftp.nl.debian.org_debian_dists_stretch_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
Fetched 7,039 kB in 9s (777 kB/s)
Reading package lists...
W: GPG error: http://ftp.nl.debian.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
W: The repository 'http://ftp.nl.debian.org/debian stretch Release' is not signed.
E: Failed to fetch http://ftp.nl.debian.org/debian/dists/stretch/main/i18n/Translation-en  BZ2_bzread: /var/lib/apt/lists/partial/ftp.nl.debian.org_debian_dists_stretch_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MichaIng** [comment]
@patho5
Thanks for your report.

Often SSL/GPG errors appear due to system clock being out of sync. Please try:
```
/DietPi/dietpi/func/run_ntpd 1
G_AGUP
```

But your error message sound more like a temporary repository issue.

I will try the nl.debian.org repo here later, I guess it will work when retrying a bid later.

**Comment by tkrusterholz** [comment]
Hello,

Thanks for the reply.  I tried your recommended steps but I see the same
error.  Do you have any additional suggestions?

Thank you,
Tom R

**Comment by Fourdee** [comment]
@patho5 

Try changing the APT mirror in:
- ```dietpi-config``` > Networking: Misc > APT mirror

**Comment by tkrusterholz** [comment]
Hi Dan,

Thanks for your response to this.  Turns out my lists file was corrupted
(as stated by this output: *Failed to fetch
http://ftp.nl.debian.org/debian/dists/stretch/main/i18n/Translation-en
<http://ftp.nl.debian.org/debian/dists/stretch/main/i18n/Translation-en>
BZ2_bzread:
/var/lib/apt/lists/partial/ftp.nl.debian.org_debian_dists_stretch_main_i18n_Translation-en.bz2
Read error (-5: DATA_ERROR_MAGIC)) * and by simply deleting my lists folder
and running apt-get update, the key file was refreshed and I was able to
update dietpi.

Thanks again for your willingness to assist.

Tom

**Comment by Fourdee** [comment]
@patho5 

Excellent, thanks for letting us know, i'll mark this as resolved 👍
