### ISSUE TITLE
Services don't autostart after upgrading to 6.20.6

### ISSUE THREAD

**Issue by ezekini** [MichaIng/DietPi#2502]
#### Required Information
- DietPi version | 
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=20
G_DIETPI_VERSION_RC=6
G_GITBRANCH=master
- Distro version | stretch 9.6
- Kernel version | Linux DietPi-rpi 4.14.79-v7+
- SBC device | RPi 3 Model B+ (armv7l)

#### Actual behaviour
I upgraded to the last version and now most services don't start automatically. I have to manually `dietpi-services start` to get everything up and running.

**Comment by Fourdee** [comment]
@ezekini 

Many thanks for the report, please do the following:
- Reboot system
- Allow for the system to boot up
- Login
- paste results of ```dietpi-services status```

**Comment by ezekini** [comment]
Well now everything seems to be booting as expected. I don't know what was happening. Sorry for the trouble.

**Comment by Dr0bac** [comment]
@Fourdee 
I also noticed on last update that after reboot services wont start.. then after next reboot everything load up fine

![](https://i.imgur.com/Cxfv3Qv.jpg)

**Comment by ezekini** [comment]
Hello. I have to reopen this, because the problem has persisted in a somehow random way. Sometimes all services start fine, sometimes they don't. Sometimes some of them are active and others are dead. I have also noticed that some services die after a while. This all started after upgrading to 6.20.6. Could you help me finding out what is wrong @Fourdee @MichaIng ?

**Comment by moritzvieli** [comment]
I experienced something similar in 6.20 but did not investigate further. Instead, I downgraded to an earlier version. I'm preparing the DietPi image with this script:
https://github.com/moritzvieli/rocketshow/blob/master/dist/install/prepare_dietpi_raspberry_image.sh

Maybe some of those settings break it?

**Comment by MichaIng** [comment]
@ezekini @moritzvieli 
Yeah with v6.20 some issue on first reboot could occur leading to several issues. v6.21 solved that issues. And there is one other thing that could prevent services start, mostly if you have chosen an autologin mode via `dietpi-autostart`, fixed with v6.22.

@ezekini 
You are already on v6.21 it seems, right? The second case seems to be true for you, also according to your screenshot, so please try the following:
```
sed -i '/After=/s/[[:blank:]]multi-user.target//' /etc/systemd/system/dietpi-postboot.service
systemctl daemon-reload
systemctl enable dietpi-postboot
```
- This should re-allow service starts on boot. Skip the following then.

@moritzvieli 
Please do the following to force update to v6.21 in a failsafe way in case of prior v6.20 update issues:
```
> /etc/profile.d/dietpi-unsupported_terminal.sh
> /DietPi/dietpi/.update_stage
echo 1 > /DietPi/dietpi/.install_stage
dietpi-update 1
```
- Update to v6.21 should work fine with this and solves the issues occurred with v6.20.
- You can as well do the above steps, if DietPi controlled services are not starting on boot.

**Comment by ezekini** [comment]
Yes @MichaIng, actually on v6.21.1. The first command returns:
sed: can't read file /etc/systemd/systemd/dietpi-postboot.service: There is no file or directory
So I can't proceed with the instructions.

I don't know if this is related (my guess is that it is), but after doing a _dietpi-services start_, all services start as expected, except jackett: 
`jackett	activating (auto-restart) (Result: exit-code) since Mon 2019-02-25 19:32:39 -03; 4s ago`

**Comment by MichaIng** [comment]
@ezekini 
Whoopsie typo, should be:
`sed -i '/After=/s/[[:blank:]]multi-user.target//' /etc/systemd/system/dietpi-postboot.service`

Jep it's expected that manually running services start works.

Jackett failure is a different issue. Will check on test system.
#### EDIT: My goodness, mono install takes a looong time on VM 😢. I am really no friend of runtime systems...
Okay finally, works well here. Does `journalctl -t mono` show some error?

**Comment by ezekini** [comment]
Ok, now the commands run succesfully. Will monitor to see if the services keep alive. Regarding jackett, it is still in the same state described above. Would you like me to start a new issue @MichaIng ?

**Comment by MichaIng** [comment]
@ezekini 
Jep a separate issue about Jackett would be better.
