### ISSUE TITLE
dietpi-drive_manager keeps forgettind and adding mounts | G_RUN_CMD always returns exit 1 code

### ISSUE THREAD

**Issue by ilgrank** [MichaIng/DietPi#2508]
Hi
After the upgrade from 6.17.20 to 6.20 (but could be unrelated, I simply noticed after the upgrade) a couple of strange things began to happen:
1) dietpi-drive_manager doesn't remove entries of mounted smb shares (or better, when I do remove them, they disappear, but after a while they do re-appear in the list of mounted shares) 
I tried removing them several times, but after a reboot or two, old entries do re-appear.

2) mounted smb shares do un-mount. Forcing a mount -a does nothing, but running dietpi-drive_manager (just opening it and quitting) does the trick.. for a while. 
(every evening after coming back from work I do find my emby server complaining it can't access the shares anymore)

Is there anything I can do to investigate this? Is there a log of drive_manager operations?
Thanks!

**Comment by Fourdee** [comment]
@ilgrank 

Hi, many thanks for the report 👍 

Ok, so when unmounting SMB/NFS shares, DietPi also removes the entry from ```/etc/fstab```. 

Might be a scrape issue with ```/etc/fstab```, please can you paste results of:
```
cat /etc/fstab
```

I'll also try to replicate issue here.

**Comment by Fourdee** [comment]
```
root@DietPi:~# G_RUN_CMD umount /mnt/samba; echo $?
[  OK  ] Root access verified.
[  OK  ] umount /mnt/samba
1

root@DietPi:~# G_RUN_CMD echo 1; echo $?
[  OK  ] echo 1
1

```

G_RUN_CMD always returning 1?

**Comment by Fourdee** [comment]
@ilgrank 

Resolved for v6.21.

You can also apply the fix now with:
```
wget https://raw.githubusercontent.com/Fourdee/DietPi/fbdf165270f03af65b284942de0bcf3df3f61a0e/dietpi/func/dietpi-globals -O /DietPi/dietpi/func/dietpi-globals
```

Then load ```dietpi-drive_manager``` to remove the drive. Spam ```Refresh``` option in same program, the drive will no longer re-appear.

**Comment by ilgrank** [comment]
Wow! I didn't even get to arrive home and you had already a fix out!  🥇 
 Testing immediately but meanwhile.. THANKS!! 👍 

**EDIT**: The removal is working ok now!
The open/close disk manager to have the disks re-mount didn't tho.
If I try to benchmark a previously mount-ed (but not un-mounted) drive from drive_manager, i get:
`Input value "10" is higher than allowed "-100". No changes applied. `
and of course
`ls: cannot access '/mnt/smb_media': Input/output error`

so I removed the share, and re-created it.
It is working now, but I'll have to check tomorrow it it 'disappeared' like the last times.

Again, thanks, I'll keep you updated

**UPDATE Feb 07**: ...aaaand, the shares remained Mount-ed! WOW! 👍 👍 👍 :) Thanks @Fourdee

**Comment by ilgrank** [comment]
**UPDATE Feb 10**: after 3 days the SMB Shares remained mounted, so both issues are definitely resolved
again, thanks @Fourdee
