### ISSUE TITLE
DietPi-Software | Add uMurmur - Mumble VOIP Server

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#251]
uMurmur is a minimalistic Mumble server primarily targeted to run on embedded computers, like routers, with an open OS like e.g. OpenWRT. The server part of Mumble is called Murmur, hence the name uMurmur. It is available as a precompiled package for quite a lot distributions. Check your distribution's package repository.

[Building Instructions if needed](https://github.com/umurmur/umurmur/wiki/Building)

**Comment by Fourdee** [comment]
@Zone22 
Thanks for the request, I will look into this when I can.

**Comment by oshank** [comment]
I am currently running a mumble server on my B+ and its works great.

**Comment by ghost** [comment]
Yes it's trivial to install but it's nice to have things going through the dietpi software.

That being said due to the simplicity of installing Mumble I might fork and do a Pull request to included it into dietpi. It'll take a bit of work for me to digest how dietpi installs everything. We will see!

**Comment by oshank** [comment]
I'm trying to find some time and patience to do the same thing. I really want to contribute to this awesome project with more then some Bitcoin.

**Comment by Fourdee** [comment]
@Zone22 @oshank 
I've not documented on how to code in additional software into DietPi-Software. So if you need some pointers or have any issues, let me know.

**Comment by Fourdee** [comment]
> https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-mumble-server-murmur-on-ubuntu-14-04

**Comment by xenfomation** [comment]
i will update my clone'd test repo AS this seems similar to the mc, mtrtiny, vim-tiny package discussion in a previous issue... i have some ideas, but will compose them before 09:00 EST 28-APRIL-2016 to see if myopia can be turned into one of the cool DietPi menus for a "most righteous means to install favorite software", etc... hrm...

**Comment by Fourdee** [comment]
@xenfomation 
Sounds good, looking forward to your ideas :+1:

**Comment by Fourdee** [comment]
Done, available for v117. http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1691#p1691
