### ISSUE TITLE
Support IQaudIO DACs

### ISSUE THREAD

**Issue by alcoheca** [MichaIng/DietPi#253]
To support Pi-DAC, Pi-DAC+ and Pi-DigiAMP+, all that is needed is

`dtoverlay=iqaudio-dacplus`

**Comment by Fourdee** [comment]
@alcoheca 
Thanks for the info. I'll get this added into dietpi-config > audio options.

**Comment by Fourdee** [comment]
Completed for next release (v114)
Will be available for selection in `dietpi-config` > Audio options > Set soundcard
![untitled](https://cloud.githubusercontent.com/assets/7077026/14051969/8408879e-f2be-11e5-9d57-88bdee994a64.png)
