### ISSUE TITLE
ASUS Tinker Board non-S | Fresh image fails to boot

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2533]
Ref: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5540

@Fourdee 
Do you have an idea? Does S/non-S model make a difference?

**Comment by Fourdee** [comment]
@MichaIng 

Should not make a difference, backwards compatible.

Although, i'll test my non-s board to verify any issues.

**Comment by Fourdee** [comment]
Unable to replicate, both S and non-S working fine in local testing.

Most likely a bad image write, bad PSU/SD etc. However, serial debug would be required from user to assist further.

Only thing I can suggest is full format SD card: https://dietpi.com/format
