### ISSUE TITLE
dietpi-wireguard.list / Wireguard previously installed breaks APT (and dietpi-software)

### ISSUE THREAD

**Issue by FabioEight** [MichaIng/DietPi#2545]
- DietPi version | 6.21.1
- Distro version | 9.6
- Kernel version | Linux DietPi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
- SBC device | RPi 3B+
- Power supply used | 5V 2.5A

- Was the software title installed freshly or updated/migrated? Fresh
- Can this issue be replicated on a fresh installation of DietPi? Probably
-  4dbf4340-cc8a-4b55-b691-377e8007f2bb

#### Steps to reproduce

1. Install WireGuard
2. Set WireGuard according to your needs, etc.
3. Uninstall WireGuard 
4. apt-get update

#### Expected behaviour

- apt-get update should complete accordingly.

#### Actual behaviour
- GPG keys errors, breaking dietpi-software and apt-get upgrade:

Example:
```
W: GPG error: https://cdn-aws.deb.debian.org/debian sid InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
W: The repository 'https://deb.debian.org/debian sid InRelease' is not signed.
```
#### Extra details
Workaround:

```
root@DietPi:~# apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 https://archive.raspberrypi.org/debian stretch InRelease
Get:3 https://cdn-aws.deb.debian.org/debian sid InRelease [243 kB]
Ign:3 https://cdn-aws.deb.debian.org/debian sid InRelease
Fetched 243 kB in 3s (74.2 kB/s)
Reading package lists... Done
W: GPG error: https://cdn-aws.deb.debian.org/debian sid InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
W: The repository 'https://deb.debian.org/debian sid InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@DietPi:~# cat /etc/apt/sources.list && ls /etc/apt/sources.list.d/
deb http://raspbian.raspberrypi.org/raspbian stretch main contrib non-free rpi
dietpi-wireguard.list  raspi.list
root@DietPi:~# cat /etc/apt/sources.list.d/dietpi-wireguard.list
deb https://deb.debian.org/debian/ sid main
root@DietPi:~# rm  /etc/apt/sources.list.d/dietpi-wireguard.list
root@DietPi:~# apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 https://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done
```
Since Wireguard has been uninstalled on my system, I think it should remove also the "dietpi-wireguard.list" which is breaking apt.
Now everything seems to be nominal.

**Comment by MichaIng** [comment]
@XRay437 
Thanks very much for your report.

Actually interesting that this missing key error does not appear on initial install of WireGuard... Thinking about it, addition a Debian repo to a Raspbian system should require to add the Debian keyring, however it seems not in this case, perhaps not as long as preferences limit it's use to the WireGuard package, not sure.

> Since Wireguard has been uninstalled on my system, I think it should remove also the "dietpi-wireguard.list" which is breaking apt.

Jep that was intended but prevented by typo. Just fixed it, many thanks: https://github.com/Fourdee/DietPi/commit/770deb5b74cad2456b7abff086aa24bde7174d6b
Changelog: https://github.com/Fourdee/DietPi/commit/484f34751ced06bb00eba0aff2393cba9d50fb54
