### ISSUE TITLE
rc.local not running on new image

### ISSUE THREAD

**Issue by DeanRM** [MichaIng/DietPi#2548]
#### Required Information
- DietPi version | `cat /DietPi/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC device | `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?
- `dietpi-bugreport` ID | `sed -n 5p /DietPi/dietpi/.hw_model`

#### Steps to reproduce

1. ...
2. ...

#### Expected behaviour

- ...

#### Actual behaviour

- ...

#### Extra details

- ...

**Comment by MichaIng** [comment]
@DeanRM
You found the solution yourself?

It's recommended to use an own systemd unit/service on modern Debian system for custom boot scripts.
Or use a DietPi implementation and place the desired script into: `/var/lib/dietpi/postboot.d`

But to enable `rc.local` via backwards compatibility systemd unit, run: `systemctl enable rc-local.service`
