### ISSUE TITLE
DietPi-Software | Weaved: Source removed from GitHub

### ISSUE THREAD

**Issue by techano** [MichaIng/DietPi#2551]
#### Details:
- Date           | Fri 15 Feb 03:13:38 GMT 2019
- Bug report     | N/A
- DietPi version | v6.21.1 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi Zero W (armv6l) (index=1)
- Kernel version | #1159 Sun Nov 4 17:28:08 GMT 2018
- Distro         | stretch (index=4)
- Command        | Connection test: https://github.com/weaved/installer/raw/master/Raspbian%20deb/1.3-07/weavedconnectd_1.3-07z1_armhf.deb
- Exit code      | 8
- Software title | DietPi-Software

#### Steps to reproduce:

1. Go to Dietpi-software
2, try to install Remot3.it (Weaved)

#### Expected behaviour:

- Should be a successful install.

#### Actual behaviour:

- Fails to download the file with the connection to github successful just the file seems to not exist

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Spider mode enabled. Check if remote file exists.
--2019-02-15 03:13:31--  https://github.com/weaved/installer/raw/master/Raspbian%20deb/1.3-07/weavedconnectd_1.3-07z1_armhf.deb
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
```

**Comment by MichaIng** [comment]
@techano 
Thanks for your report.

Indeed weaved branch removed from GitHub 😱: https://github.com/weaved/

#### EDIT
Try this one:
```
cd /tmp
wget https://github.com/remoteit/installer/releases/download/v2.2.5/connectd_2.2.5_armhf.deb
dpkg -i connectd_2.2.5_armhf.deb
rm connectd_2.2.5_armhf.deb
connectd_installer # This runs the installer whose name changed as well. I already updated our online docs accordingly.
```
_______
Switched to totally new repo: https://github.com/remoteit
Docs on website state to install from Debian/Raspbian repo:
- https://docs.remote.it/getting-started/quick-start-on-raspberry-pi/install-remote.it
- https://docs.remote.it/downloads

Non of them contain the `connectd` package in not a single branch. Misleading...

But deb packages available on GitHub release page for all architectures: https://github.com/remoteit/installer/releases

GitHub API download for latest version possible: https://api.github.com/repos/remoteit/installer/releases/latest

**Comment by MichaIng** [comment]
PR up to switch to new repo: https://github.com/Fourdee/DietPi/pull/2552

**Comment by Fourdee** [comment]
Testing passed, will mark as completed: https://github.com/Fourdee/DietPi/pull/2552#issuecomment-464109910
