### ISSUE TITLE
DietPi-Software | EmonPi - Add optional installation for RF features.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#256]
> note to self:
> Buy RF device (eg: temp sensor module, emonTX etc) so I can impliment/test.

**Comment by Fourdee** [comment]
Continuation from https://github.com/Fourdee/DietPi/issues/210.

**Comment by WolfganP** [comment]
Just for reference related to EmonPi alternate comms, the system also supports wired serial connection as per https://openenergymonitor.org/emon/node/3884 (so cheap TTL/RS232 or RS485 adapters can be used were wiring isn't an issue)

**Comment by Fourdee** [comment]
@WolfganP 
Interesting, i've got two of those serial adapters at the moment but no emonTX, wonder if they can be used with the emonPi?

I've ordered a EmonTH so I can implement RF, and have some fun checking temp/humidity around the house lol :)

**Comment by Fourdee** [comment]
RF receiver features (EmonTH/EmonTX) is already supported by our installation. RF transmission is untested.

EmonTH inputs: http://dietpi.com/downloads/misc/EmonPi_Guide/emonth_inputs.png
