### ISSUE TITLE
Dietpi-Software | UrBackup Server Update to 2.3.7

### ISSUE THREAD

**Issue by athisun** [MichaIng/DietPi#2577]
There is a new version of UrBackup server available (2.3.7). Download it [here](https://www.urbackup.org/download.html)

#### Required Information
- DietPi version | 6.21.1

**Comment by MichaIng** [comment]
@DeathIsUnknown 
Thanks for the info. Will update our download links for v6.22.

#### EDIT: PR up: https://github.com/Fourdee/DietPi/pull/2578
