### ISSUE TITLE
DietPi-Software | MPD: mpd.conf permissions issue

### ISSUE THREAD

**Issue by seniorgod** [MichaIng/DietPi#2605]
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=21
G_DIETPI_VERSION_RC=1
G_GITBRANCH=master
G_GITOWNER=Fourdee

stretch

Linux DietPi 3.10.38 #22 SMP PREEMPT Fri Dec 22 10:45:41 IST 2017 armv7l GNU/Linux

Allo Sparky with usbridge

Power supply used | 2 x 5 V on Sparky and on usbridge
SDcard used | emmc

Dear all,

in version 6.21.1 you changed mpd.conf 
 
you set:
user "mpd"
group "dietpi"

at my system mpd was not able to open also device hw:1,0 

It work when i change 
user "root"
group "dietpi"
or 
user "mpd"
group "audio"

So i guess you want to change to the latter version 

best regards
senior.god

**Comment by MichaIng** [comment]
@seniorgod 
Thanks for reporting. Jep this is a known issue with v6.21, fixed already for v6.22: https://github.com/MichaIng/DietPi/issues/2462

Please see for a safer solution then running MPD as root: https://github.com/MichaIng/DietPi/issues/2522#issuecomment-466820376
______
I mark this as closed/solved.
