### ISSUE TITLE
System | APT certificate error

### ISSUE THREAD

**Issue by RynFlutsch** [MichaIng/DietPi#2612]
Installation of additional software

![ef40c70b-583a-4d94-ac81-a057c2c26c72](https://user-images.githubusercontent.com/29811876/53702253-42eb8280-3e05-11e9-995b-e81ac959b923.jpeg)

**Comment by MichaIng** [comment]
#### EDIT:
Ah I see the system clock is out of sync which leads to the SSL error.
Please try `/DietPi/dietpi/run_ntpd 1`

<s>Hmm, dietpi.com certificate is not trusted? Accessed it now several times directly via browser and also during software installs and no issues. It's a Let's Encrypt certificate, respectively applied through Cloudflare.

Please try again manually the connection test, if it was just a temporary issue:
`G_CHECK_URL dietpi.com`

If it still fails, try to reinstall/refresh the ca-cerficates packages, then retry the above:
`G_AGI --reinstall ca-certificates`</s>

**Comment by MichaIng** [comment]
I will mark as closed as above. Feel free to reopen if error persists after updating the system clock (as above).
