### ISSUE TITLE
OPi PC unstable.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#263]
> https://twitter.com/ewan2395/status/714738230629900289

This is to resolve the comminuty known issue with the 1.5ghz clock and high voltage on the Loboris image (that DietPi is built on):
http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=785&fromuid=29411

Basically limits the Allwinner H3 to 1.2ghz and lower voltage vastly improving stability and reducing heat.

**Comment by Fourdee** [comment]
Attempting ARMbian kernel to replace Loboris: https://github.com/igorpecovnik/lib/issues/250#issuecomment-203021008

**Comment by Fourdee** [comment]
Notes:

/boot

```
rwxrwxrwx  1 root root   24 Mar  8 20:20 script.bin -> /boot/bin/orangepipc.bin
lrwxrwxrwx  1 root root   21 Mar  8 20:19 zImage -> vmlinuz-3.4.110-sun8i
```

.fex

```
root@orangepipc:~# find / -type f -name *.fex
/usr/lib/nand-sata-install/h3/boot0_OPI.fex
/usr/lib/nand-sata-install/h3/u-boot_OPI-emmc.fex
```

**Comment by Fourdee** [comment]
Community fix by Thomas Kaiser for vcore/clocks will be applied during v115 patch: https://github.com/igorpecovnik/lib/issues/250#issuecomment-203502587

**Comment by rhkean** [comment]
now if I can just figure out ho-w to get a 3.15 or greater kernel on the Odroid-XU4, so that we can have UAS (USB Attached SCSI) support
