### ISSUE TITLE
Feature Request | Voice/Speech Automation

### ISSUE THREAD

**Issue by starstuff** [MichaIng/DietPi#266]
Hello!

Adding Voice Automation in DietPi will open up new possibilities!

In surfing the web, i found there are many ways to integrate voice in pi, the good news is that it does work.

I think it would be best to create a poll to ask DietPi community to choose which of the software to use.  

Links:

[http://diyhacking.com/best-voice-recognition-software-for-raspberry-pi/](url)
Jasper – Voice Recognition Software.
[https://jasperproject.github.io/](url)

Raspberry Pi Voice Recognition by Oscar Liang.
[http://blog.oscarliang.net/raspberry-pi-voice-recognition-works-like-siri/](url)

Raspberry Pi Voice Control by Steven Hickson.
[http://stevenhickson.blogspot.com/2013/05/voice-command-v20-for-raspberry-pi.html](url)

[https://wolfpaulus.com/journal/embedded/raspberrypi2-sr/](url)
SphinxBase and PocketSphinx

[www.digitaltrends.com/home/alexa-on-raspberry-pi/](url)
[github.com/amzn/alexa-avs-raspberry-pi](url)

**Comment by Fourdee** [comment]
@starstuff 
Thanks for the requests and additional information :+1:  . Definitely something I will look into, interests me :)

**Comment by WolfganP** [comment]
Adding to the Alexa experiment commented above, Google recently announced it's going to open the Speech API http://techcrunch.com/2016/03/23/google-opens-access-to-its-speech-recognition-api-going-head-to-head-with-nuance/
Let's hope the Cortana APIs open up for debian/raspi OS instead of the MS IoT core https://developer.microsoft.com/en-us/windows/iot 
Interesting times ahead...

**Comment by chrisvella** [comment]
Checkout [Mycroft](https://github.com/MycroftAI/mycroft-core)
Open source, and reasonably functional already. Very excited to see where this project goes.
Its developed on ubuntu so it shouldn't be much work to get it running on debian at all.

As far as automation goes you would need to write a mycroft skill to do whatever task you required.

**Comment by Fourdee** [comment]
Jasper

```
dietpi-software install 5 16 17

#libportaudio-dev  not in debian repo
apt-get install -y python python3 python-dev python-pip bison libasound2-dev libportaudio2 python-pyaudio

cat << _EOF_ >> /root/.bashrc
LD_LIBRARY_PATH="/usr/local/lib"
export LD_LIBRARY_PATH
PATH="\$PATH:\$LD_LIBRARY_PATH"
export PATH
_EOF_

git clone --depth 1 https://github.com/jasperproject/jasper-client.git jasper

chmod +x jasper/jasper.py
pip install --upgrade setuptools
pip install -r jasper/client/requirements.txt

#GoogleTTS engine
apt-get install -y python-pymad
pip install --upgrade gTTS

root@DietPi:~# pip install -r --upgrade gTTS
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
