### ISSUE TITLE
Website: typo

### ISSUE THREAD

**Issue by jimt** [MichaIng/DietPi#2668]
There is an extra apostrophe in the **features** section of the website:

`DietPi programs use lightweight Whiptail menu's.`

menu's -> menus

**Comment by MichaIng** [comment]
@jimt 
Many thanks for your report.

Jep indeed the apostrophe is not required/wrong here.

This area could require some rework/update anyway 🤔.

**Comment by Fourdee** [comment]
@MichaIng @jimt  

Resolved 👍 (CTRL+F5 to force refresh)
