### ISSUE TITLE
Add netdata (realtime perfomance monitoring) to dietpi

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#267]
feature suggestion:
Readme.md:  https://github.com/firehol/netdata/blob/master/README.md

http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=354

**Comment by rhkean** [comment]
This is my first full add-on feature (not just a code tweak to @Fourdee 's code), so figured I'd start small... (since this will require modifications to the whiptail menus and such)

I'll probably lean on you guys more for review and testing....

**Comment by Fourdee** [comment]
@rhkean 
Nice :+1: Looking forward to seeing this.

**Comment by k-plan** [comment]
@rhkean 

Cool, assistance for Fourdee.  :+1: 

> I'll probably lean on you guys more for review and testing....

If you have something to test, give it to us.  :smile:

**Comment by Fourdee** [comment]
@rhkean 
Excellent work on implementing this, top stuff :+1: 

Ticket closed, marked as completed.
