### ISSUE TITLE
DietPi-Banner | Add "Please use spacebar to select option" to menu

### ISSUE THREAD

**Issue by Millichrome** [MichaIng/DietPi#2670]
### Creating a bug report/issue

After initially running the dietpi-banner command, I couldn't figure out how to select any of the options. Then I remembered having the same issue when initially running dietpi-software, so I ran it and noticed the note about using spacebar. 

Not a big deal at all. I am a casual linux user, so maybe it's just me not being accustomed to linux/cli conventions.        

#### Required Information
- DietPi version | 6.22.3
- Distro version | stretch
- Kernel version | 4.4.71+
- SBC device | ASUS Tinker Board

**Comment by MichaIng** [comment]
@Millichrome 
Many thanks for your request.

Yeah indeed I remember when using Whiptail the first time I also struggled. Also how to go to `<Ok>`/ `<Cancel>` buttons via `<TAB>`/`<left>`/`<right>`.

Perhaps our programs main menus should contain the basic Whiptail navigation hints, or we add some Whiptail intro when logging in the first time?

However adding the info from dietpi-software is easy for now.

€: You are okay with this: https://github.com/MichaIng/DietPi/commit/8bc4e09ee9ba3b96d798b5ae7c7bebadc7fd587f#diff-62c2a7ce801099eca1c044bd841da40bR226 ? Very tiny for now, I am thinking about a DietPi-wide solution, e.g. little tutorial or something. In the deeper config menus I think it would not be good to add all navigation infos in every case. It takes too much screen space then 🤔.

**Comment by Millichrome** [comment]
A tiny text prompt would be perfect. I am sure I am not the only user with this issue. :) 

I agree that it would be too much to add it to every menu. IMO it shouldn't really clutter the "dietpi-banner" (at least as it is right now). Just my take though.

**Comment by MichaIng** [comment]
@Millichrome 
The menu now (with above commit) shows:
`Please (de)select options via spacebar to be shown in the DietPi-Banner:`

**Comment by Millichrome** [comment]
Awesome! Hope this helps other people too. :)
