### ISSUE TITLE
DietPi-Update | Fix first run update to prevent DietPi-Software loop on first boot

### ISSUE THREAD

**Issue by avworldme** [MichaIng/DietPi#2682]
### Creating a bug report/issue
I have installed the DietPi_v6.14_NanoPiNEO2-ARMv8-Stretch on my Neo2 LTS, however the system is stuck on Diet-Pi Configuration, I cannot go to command prompt.  When I choose exit, it just loops back to the configuration men.

I also cannot get squeezebox to run.  I don't have any troubleshooting logs as i am no able to get command prompt.

I am using the Samsung Evo+ SD card.
any guidance would be appreciated.

**Comment by MichaIng** [comment]
@avworldme 
Thanks for your report.

Do not choose "Exit" but "Install" to finish first run setup. Perhaps we should change the wording to make this clear if it indeed was the mistake? Or as/if you did this already for installing Squeezebox, does the DietPi-Software prompt re-appear after reboot?

**Comment by avworldme** [comment]
What I meant is that my login always goes to DietPi-Software (not DietPi-Configuration).  I tried all the suggested options with Install--> Exit, Install -->OK  and I still go back to that window.  When I manually reboot and login using ssh, i get Update available and then get looped back into the DietPi-Software screen.

As for the LMS installation, I am attaching the install log here:  https://pastebin.com/5aapxeTk

when I try to access it using the web browser, it's not running.

**Comment by nicolasbuch** [comment]
Just encountered the same issue with DietPi v6.14 Odroid XU4. Screen gets stuck in the first dietpi config. Choosing exit or install just loops back to same config screen. 

I noticed that it was a few versions behind, so i fixed the issue by updating to the newest version before running the initial dietpi launcher.

I did the following:

When booting (just before the automated script throws you into the dietpi-launcher screen) hit CTRL + C to interrupt. Run dietpi-update. Next time it boots finish the config and enjoy :) 

Fix suggestion to dietpi-team might be to run update before initial config.

**Comment by avworldme** [comment]
Thank you nicolasbuch, that worked for me with a bit of modification.  I don't have a video output on the Neo2, so my system booted too quick to hit ctrl-C.  So the trick for me was to open a new terminal window which gave me the message:

[ INFO ] DietPi-Login | DietPi-Software is already running on another terminal/screen. Please complete or exit, before continuing.

that was enough time form me to break, then do the update.  then i removed lms and reinstalled it again and boom there it is.

Now I have a new issue, i'll open another ticket.

Perhaps it's time for a new image for the Neo2.

**Comment by MichaIng** [comment]
@avworldme @nicolasbuch 
I believe it is resolved with: https://github.com/MichaIng/DietPi/pull/2684
This also fits to your solutions to manually run dietpi-update before doing first run setup.

**Comment by avworldme** [comment]
Is it possible to update the DietPi Neo 2 image to the latest?  I believe the one that's available now is 6.14.  So it will always have this issue.

**Comment by MichaIng** [comment]
@avworldme 
> So it will always have this issue.

Nope, the issue was within the online part of the updater only, not the offline part which is shipped with the image. Or lets say the PR changed the online patch_file in a way that as well older images are updated correctly on first boot. Tested with v6.2 (current x86 BIOS image 😉).
______
But regardless we should update those outdated images just to have a cleaner first boot with less update/install/APT steps anyway 😉.

**Comment by avworldme** [comment]
Ok, I just tried a fresh install and I indeed didn't have any more loops.  Thank you.

**Comment by MichaIng** [comment]
@avworldme 
Thanks for testing. The change to the update system with v6.20 really caused a lot of trouble. I hope now the last bit is resolved.
