### ISSUE TITLE
Network setup with German locale

### ISSUE THREAD

**Issue by dimpfelmoser** [MichaIng/DietPi#27]
If the locale is set to de-de-UTF8 in the config dialog prior to setting up a static network address, there are erroneous strings prepended to the ip address and mask, i.e. instead of

192.168.0.1

the installer writes

Adresse:192.168.0.1

into /etc/network/interfaces

**Comment by Fourdee** [comment]
Hi,

Many thanks for the report. Could you please run:
dietpi-bugreport

This will generate a bug report with system configuration data. You dont need to fill the information in. Once its sent, please paste your "Reference CODE:" here. I'll then be able to look into this further.

**Comment by Fourdee** [comment]
Unable to replicate on RPi + DietPi v74. 
Correct values are applied to /etc/network/interfaces when set to de-de-UTF8 before and after reboot.

If you wish to reopen this error, please provide the following information:
- Any overclocking applied to the system?
- PSU used is stable (5v 1amp+)?
- MicroSD card used?
- complete the dietpi-bugreport, link reference code.
