### ISSUE TITLE
DietPi-software | Can't install Git client

### ISSUE THREAD

**Issue by RubykZ11** [MichaIng/DietPi#2709]
#### Required Information
- DietPi version | `cat /DietPi/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC device | `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?
- `dietpi-bugreport` ID | `sed -n 5p /DietPi/dietpi/.hw_model`

#### Details:
- Date           | Wed 10 Apr 20:06:41 CEST 2019
- Bug report     | N/A
- DietPi version | v6.22.3 (Fourdee/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | RPi 3 Model B (armv7l) (index=3)
- Kernel version | #1200 SMP Tue Feb 12 20:27:48 GMT 2019
- Distro         | stretch (index=4)
- Command        | G_AGUP
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. Run command;
2. curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -

#### Expected behaviour:

- install grove.py

#### Actual behaviour:

- See log
#### Extra details:

- Git client wasn't installed
- Try to install git client
- Log list on screen
- [FAILED] Dietpi-software | Unable to continu, DietPi-software will now terminate.
_ Same after reboot

#### Additional logs:
```
Log file contents:
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Ign:2 https://seeed-studio.github.io/pi_repo unknown InRelease
Ign:3 https://seeed-studio.github.io/pi_repo unknown Release
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Ign:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Hit:7 https://archive.raspberrypi.org/debian stretch InRelease
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Ign:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Ign:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Ign:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Ign:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Ign:4 https://seeed-studio.github.io/pi_repo unknown/main all Packages
Err:5 https://seeed-studio.github.io/pi_repo unknown/main armhf Packages
  404  Not Found
Ign:6 https://seeed-studio.github.io/pi_repo unknown/main Translation-en
Ign:8 https://seeed-studio.github.io/pi_repo unknown/main Translation-en_GB
Reading package lists...
W: The repository 'https://seeed-studio.github.io/pi_repo unknown Release' does not have a Release file.
E: Failed to fetch https://seeed-studio.github.io/pi_repo/dists/unknown/main/binary-armhf/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Fourdee** [comment]
@RubykZ11 

Hi,

Thanks for the report.

> https://seeed-studio.github.io/pi_repo/dists/unknown/main/binary-armhf

It would appear the repo (which the custom script you used) does not provide any ARMhf packages for the system you are running, or, the repo is having maintenance issues.

You will need to contact the provider of the script (https://github.com/Seeed-Studio/grove.py/raw/master/install.sh) for support.

---

EDIT: Quick solution would be to remove the offending repo from your system
```
rm /etc/apt/sources.list.d/seeed.list
```
