### ISSUE TITLE
DietPi.com/survey | Benchmarks reset for v6.23 released

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#2715]
Reason:
- Incorrect RAM benchmarks due to low MB size test against sub second time result. Gives poor total MB/s calculation.
- CPU temps on Pine A64 incorrect.

All we need to do is change ```dietpi-survey_report``` to only calculation benchmarks with version ```2```.

---

@MichaIng 

We could do fixes on ```dietpi-survey_report``` to check for invalid CPU temps (+cpu time), but the RAM results need resetting.

**Comment by MichaIng** [comment]
@Fourdee 
Jep makes sense. Perhaps we can do the version check only when reading RAM values but keep reading the other ones.

**Comment by Fourdee** [comment]
@MichaIng 

Made a start:
https://dietpi.com/survey/debug.html

**Comment by MichaIng** [comment]
@Fourdee 
Added below and committed to GitHub: https://github.com/MichaIng/DietPi/commit/458d8a0bfb01c9ed4e5a6da823d566d20c079b2a
- Like the new colours on full row. Much better readable when the table is already long (headers possibly out of screen) 👍.

Jump directly to desired table:
- DietPi vesion: https://dietpi.com/survey/#version
- Git branches: https://dietpi.com/survey/#git
- Device: https://dietpi.com/survey/#device
- CPU arch: https://dietpi.com/survey/#arch
- CPU cores: https://dietpi.com/survey/#cores
- Distro: https://dietpi.com/survey/#distro
- Autostart: https://dietpi.com/survey/#autostart
- Automation: https://dietpi.com/survey/#automation
- Software: https://dietpi.com/survey/#software
- Benchmark (first, CPU, where I derived it from, love this `id="..."` 😃.): https://dietpi.com/survey/#benchmark
- Benchmark disk: https://dietpi.com/survey/#bench_disk
- Benchmark RAM: https://dietpi.com/survey/#bench_ram
- Benchmark LAN: https://dietpi.com/survey/#bench_lan

**Comment by Fourdee** [comment]
@MichaIng 

Also with this update (https://github.com/MichaIng/DietPi/commit/b6044942e0bb6e800f776292ac230434fda5c68e), we seperatlely check for valid entries in each CPU/RAM/RootFS benchmark. So if user only has valid RAM benchmark, the others will be ignored.

Previously we expected CPU/RAM/RootFS to be done together, and, any invalid entry would cause havoc. Changes allow for more control and safety net.

Also yep, colors to ID table easily.

**Comment by MichaIng** [comment]
@Fourdee 
That is great. Long term we can also offer individual benchmarks, e.g. if user doesn't want to wear SDcard. I remember you wanted to keep it easy that time, all benchs + upload with a single. Perhaps keep that and have a sub menu for individual benchs, e.g. combined with per-drive bench as well.

I will fill the RAM bench table with the devices I have later. I think we can mark this as closed then?

**Comment by Fourdee** [comment]
@MichaIng 

> Perhaps keep that and have a sub menu for individual benchs, e.g. combined with per-drive bench as well.

Yep, something we can do in the future. No rush and the benchmark suite is a nice touch to ensure user can quickly benchmark system and compare.

> I will fill the RAM bench table with the devices I have later. I think we can mark this as closed then?

:+1: 

I also added the customFS to survey. So yep, all done for now :+1:
