### ISSUE TITLE
DietPi-Software | Emby Server: Installation failure

### ISSUE THREAD

**Issue by Havenlee13** [MichaIng/DietPi#2719]
I can install software like SAMBA, but I can not install Emby or Plex. I am using the OS DietPI like requested. below is the error that I have gotten. I wasn't able to copy and paste. sorry for the inconvenience. Any help would be appreciated. 
![DietPI Error](https://user-images.githubusercontent.com/49736607/56328716-d8d53580-6145-11e9-9ba0-5be8382a5e0b.PNG)

**Comment by Havenlee13** [comment]
I didn't think it was actually going to show the picture. I though it was just going to put a URL there instead.

**Comment by MichaIng** [comment]
@Havenlee13 
Many thanks for your report.

Please see for solution: https://github.com/MichaIng/DietPi/issues/2714#issuecomment-483254053
