### ISSUE TITLE
Failed to start dhcpcd

### ISSUE THREAD

**Issue by JJGO** [MichaIng/DietPi#2731]
#### Required Information
- DietPi version | `6.22.3 master`
- Distro version | `stretch`
- Kernel version | `Linux Iroh 4.14.98-v7`
- SBC device | `RPi 3 Model B+ (armv7l)`
- Power supply used | `Official RPi Power Supply`
- SDcard used | SanDisk ultra 128GB

#### Description
1. Fresh install of latest Dietpi
2. Only thing I manually configured was WPA-EAP using `/etc/wpa_supplicant/wpa_supplicant.conf`
3. On startup I get a fail message saying  `failed to start dhcpcd on all interfaces` and to run `systemctl status dhcpd.service`
4. When I run `systemctl status dhcpd.service` it outputs `Unit dhcpd.service could not be found.`
5. Software seems to be installed, i.e. `sudo apt list --installed | grep dhcpcd` outputs `dhcpcd5/stable,now 1:6.11.5-1+rpt7 armhf [installed]`

**Comment by MichaIng** [comment]
@JJGO 
Many thanks for your report.

Hmm, actually `dhcpcd` should not be installed and is not required. We use `isc-dhcp-client` which is also the reason the former fails.

Simply do `G_AGP dhcpcd5` to solve.

I check the RPi image, actually we actively purge this on image creation: https://github.com/MichaIng/DietPi/blob/dev/PREP_SYSTEM_FOR_DIETPI.sh#L883
🈯️ Definitely not pre-installed on our image, so far so good.
____________
So it generally looks like you did some manual setup of your network. `dhcpd.service` is a DHCP **server** daemon (`isc-dhcp-server`), so I guess not what you want and it is not related to `dhcpcd5` as well.

So if you just want WiFi with EAP please try the following (based on what you did/didn't do already):
- Purge dhcpcd: `G_AGP dhcpcd5`
- Backup your current wpa_supplicant config: `mv /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak`
- `dietpi-config` > Network Options: Adapters > WiFi > enable (if asked) > keep/toggle DHCP > Apply
- Select WiFi credentials, scan for your SSID and select WPA-PSK for now, enter password etc. of course it fails, if you need WPA-EAP, but at least now the base setup/files/packages are there.
- Now edit `/etc/wpa_supplicant/wpa_supplicant.conf` and re-add the wpa-eap related settings (from backup file).
- Reload the WiFi interface: `ifdown wlan0 && ifup wlan0`
  - This as well loads the `isc-dhcp-client` service (`dhclient`) and `wpa_supplicant` automatically without any further needs. Their starts are hooked into `ifupdown` which handles network interface bring ups/downs.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.

**Comment by Sopor** [comment]
I got this error message after a clean install with updates `failed to start WPA supplicant.`. What should i do to get rid of it?

**Comment by MichaIng** [comment]
@Sopor 
Many thanks for your report. Jep I remember this was indeed one (though visual only) issue with the current life RPi image. One of the reasons I created the new one (check out the other topic you opened).

Simply do: `systemctl disable wpa_supplicant`
This service is started as instances for the particular network interface, so the global service is not required and conflicts with the prior one.

**Comment by Sopor** [comment]
```
Removed /etc/systemd/system/dbus-fi.w1.wpa_supplicant1.service.
Removed /etc/systemd/system/multi-user.target.wants/wpa_supplicant.service.
```

**Comment by MichaIng** [comment]
@Sopor 
Jep, the error should not show up again now.
