### ISSUE TITLE
DietPi-Software | PiVPN: Check official installer for IP redirection

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2746]
Ref: https://github.com/MichaIng/DietPi/issues/2505#issuecomment-487706128

Should be included, at least optionally, but added to the PiVPN repo itself at best: https://github.com/pivpn/pivpn

There is as well a dedicated OpenVPN APT repo available: http://build.openvpn.net/debian/openvpn/stable/dists/
- Beneficial to add it to our installs as well?
- Ships newer version than Debian Stretch: v2.4.7 vs v2.4.0

🈯️ IPv4 forwarding included: https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L909-L910
🈺 IPv6 forwarding missing

So the issue in above link is indeed the missing sysctl.conf symlink, whyever this has happened. Resolved with: https://github.com/MichaIng/DietPi/blob/dev/dietpi/patch_file#L1872-L1878

**Comment by tohjg** [comment]
For those who **installed pihole and pivpn**, but **no internet when device connected to vpn**, you need to either:

1. set `net.ipv4.ip_forward` to `1` inside `/etc/sysctl.d/99-sysctl.conf` 
2. or, you may create symlink from `/etc/sysctl.d/99-sysctl.conf` to `/etc/sysctl.conf`.

PiVPN installer script modified `/etc/sysctl.conf` but it was ignored, instead it reads config file(s) from `/etc/sysctl.d`. 

Reported using Raspberry Pi Model 3+, dietpi version 6.24.1.

**Comment by MichaIng** [comment]
@tohjg 
Jep, the symlink is expected (and default): `/etc/sysctl.d/99-sysctl.conf => /etc/sysctl.conf`
To recover this symlink: `ln -sf /etc/sysctl.conf /etc/sysctl.d/99-sysctl.conf`
Actually I thought we recreated this already some DietPi versions ago via update... let me check...
#### EDIT: https://github.com/MichaIng/DietPi/blob/dev/dietpi/patch_file#L1896-L1902
- Hmm and in your case this was not present even on v6.24.1??
- I am wondering if there is something removing/reverting the symlink. Was already wondering when this was reported first since we never touch it and all our images come with the symlink in place, as this is default on Debian and Raspbian.

**Comment by MichaIng** [comment]
IPv6 support on PiVPN still outstanding, so we leave it as is for now: https://github.com/pivpn/pivpn/issues/259

The other issue is strange, since we already re-created missing symlink with v6.23 so it is still outstanding why/how it got removed again. At least we never touch it.

However I mark this issue as closed for now.
