### ISSUE TITLE
Test NETDATA install on devices

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#276]
Continuation from recent merged pull request: https://github.com/Fourdee/DietPi/pull/275

**Comment by Fourdee** [comment]
#### Odroid's (C2) = Failed

```
E: Package 'nodejs' has no installation candidate
```

I'll look into this

**Comment by Fourdee** [comment]
Ok, as we already have a NODEJS installation option (linux software), i've flagged `NETDATA` to set `NODEJS=1`: https://github.com/Fourdee/DietPi/commit/b1b8581a87b9f6c1d86f58c8023e12e9ecd24e82

Now it appears NodeJS install/repo is no longer working:

```
W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/jessie/InRelease  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
deb https://deb.nodesource.com/node_5.x jessie main
```

I'll look into this further.

**Comment by Fourdee** [comment]
Tried the following:

```
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Appears there is no arm 64bit package yet for C2: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by Fourdee** [comment]
I'll compile for arm64 and host .deb on dietpi.com

**Comment by Fourdee** [comment]
Compiled NodeJS for ARM64 (C2) and updated NodeJS installation code: https://github.com/Fourdee/DietPi/commit/67291022cfc383ba6909ad9cdb8dadcbdd8e9376

**Comment by Fourdee** [comment]
Ok, we need to also compile netdata for ARM64 (C2):

```
root@DietPi:~# ls -lha /usr/sbin/netdata
-rwxr-xr-x 1 root root 312K Apr 12 04:19 /usr/sbin/netdata
root@DietPi:~# /usr/sbin/netdata
-bash: /usr/sbin/netdata: No such file or directory
```

@rhkean If you dont have a C2, or cross compiler, let me know and email me the steps (or guide you used) to compile NetData

**Comment by Fourdee** [comment]
> note to self:
> http://192.168.0.104:19999

@rhkean 
I tested netdata on the RPi 3 with the nodeJS code changes, running fine. Looks awesome :+1: 
![image](https://cloud.githubusercontent.com/assets/7077026/14530015/f8c9d2a0-024e-11e6-9b09-c372d1d4b11e.png)

**Comment by Fourdee** [comment]
@rhkean 
I've added the online documentation: http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5&start=60#p1611

ps. My son is at his nans for the day, so trying to get as much done as I can :+1:

**Comment by rhkean** [comment]
you're a BEAST!!!!

I forgot that you added nodejs to the other software menu.... DOH!

so, to recap:
- if NETDATA == 1, then NODEJS=1 (instead of 'AGI nodejs' in the netdata install block)
- need ARM64 build for the C2
- while you were at it, you fixed the NODEJS on ARM64 issue that we didn't know was an issue
- AND... you did the documentation

all before I got out of my morning meeting with my boss....
yup... you're a coding BEAST!!!!  :laughing:

**Comment by rhkean** [comment]
I don't have a cross compiler setup, but I'm about to compile the RPi 1 version....
the steps will be the same.... I'll document them and post them here...

**Comment by Fourdee** [comment]
@rhkean 
Hehe,

> if NETDATA == 1, then NODEJS=1 (instead of 'AGI nodejs' in the netdata install block)

Yep.

> need ARM64 build for the C2

I wasnt sure if you had a ARM64 system available, so i made a start based on: https://github.com/firehol/netdata/wiki/Installation#install-netdata. All we really need is the ARM64 binaries.

> while you were at it, you fixed the NODEJS on ARM64 issue that we didn't know was an issue

Yep

> AND... you did the documentation

Aye, been a busy beaver. Been storing it all up last few weeks lol.

> I don't have a cross compiler setup, but I'm about to compile the RPi 1 version

Excellent :+1:

**Comment by Fourdee** [comment]
@rhkean 
Ok ARM64 is done (C2). Tested it and running fine: https://github.com/Fourdee/DietPi/commit/3816fc3507301e76a5a01acecae8613b2d2949dd

I noticed this on the Odroid C2 compile:

```
I see you have kernel memory de-duper (called Kernel Same-page Merging,
or KSM) available, but it is not currently enabled.

To enable it run:

echo 1 >/sys/kernel/mm/ksm/run
echo 1000 >/sys/kernel/mm/ksm/sleep_millisecs

If you enable it, you will save 20-60% of netdata memory.
```

Was this the same for RPi? If so, we could add this to the existing netdata service `/etc/systemd/system/netdata.service`.

**Comment by rhkean** [comment]
start:  DietPi + Vim + BuildEssentials + Git + NodeJS

```
apt-get install zlib1g-dev gcc make git autoconf autogen automake pkg-config
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
export LC_ALL=C
export CFLAGS="${CFLAGS--O3}"
export ZLIB_CFLAGS=" "
export ZLIB_LIBS="-lz"

./autogen.sh
./configure --prefix="/usr" --sysconfdir="/etc" --localstatedir="/var" --with-zlib --with-math --with-user=netdata CFLAGS="${CFLAGS}"

make
DESTDIR=$(mkdir temp_install && readlink -e temp_install) make install
install -D system/netdata.service temp_install/etc/systemd/system/netdata.service
tar -czvf netdata_1.0.0_rpi1.tgz -C temp_install .
rm -rf temp_install
```

(I'll email you the RPi 1 tarball shortly and add the HW_MODEL support)

**Comment by rhkean** [comment]
I got the same message, but I haven't looked into it

**Comment by k-plan** [comment]
Tested on Odroid C1+ ( armv7l):

install via`dietpi-software` : works! 👍 

Nice job rhkean and Fourdee . 😄 

Do a quick look.Only thing I notice , is the flashing update button in the top right corner. But no big deal.

![160414-0002](https://cloud.githubusercontent.com/assets/17237601/14542426/2739ae54-028f-11e6-982c-cb63f4a422c7.gif)

Have to do a deeper look on netdata. Its a cool and mega powerful monitoring tool.

**Comment by rhkean** [comment]
@k-plan 
BAH!!!!!
that's annoying!  I hadn't noticed that before.  It's apparently checking github for commits. 
So, there was no flashing right after a build.  My Odroid XU4 is flashing, but my Rpi 1 (binary built today) isn't flashing....

Let me see if I can disable that "feature"....  I'm not going to rebuild that tarball everytime there's a new commit to github.... :smiling_imp: 

EDIT:
it slows down by changing the conf file (which doesn't actually exist)....
It'll generate the default file (w/ everything commented out here:  http://server:19999/netdata.conf )
put that file here: /etc/netdata/netdata.conf
then change the value of:  update every = 1 
to:  update every = 3600

but that will just delay the inevitable... 
I'll see about disabling it...

**Comment by k-plan** [comment]
@rhkean 

> Let me see if I can disable that "feature".... I'm not going to rebuild that tarball everytime ...

👍  - best choice. 

But anyway, it will not subtract your effort. 
Really quick and smooth netdata implementation. Congratulation.

**Comment by Fourdee** [comment]
@rhkean @k-plan 
Yep I agree, the update flashing is ruining this great application. Its unnecessary, especially considering it just checks for commits, and not stable release cycles?

I'd be more inclined to make a request directly to NetData, to remove the flash animation by default. Or at the very least have an option to disable this highly unnecessary and distracting UI element.

**Comment by Fourdee** [comment]
If there is no way to disable the update animation button ,we could always fork NetData and do our own release cycles for our users.
EDIT: We would also need to find the line of code (url) that is used to check for updates, to our fork

Lets see NetData's response first.

**Comment by Fourdee** [comment]
@rhkean 

#### So items left on this ticket:
- :u6307: https://github.com/Fourdee/DietPi/commit/3f7dea6940682ca6c8eabb9566cccda34b2dbfbf I need the armv6 compiled .tgz
- :u6307: https://github.com/Fourdee/DietPi/commit/b611159df77fcea990d590b91f40308a620978bb Prevent the UI update animation flashing. using workaround https://github.com/firehol/netdata/issues/233
- :u6307: https://github.com/Fourdee/DietPi/commit/bcee8832b7138b1e21aad8d11e4c1ff79bf5ceb6 `dietpi-uninstall` code for NetData (based on their uninstall script)
- :u6307: https://github.com/Fourdee/DietPi/commit/3040aef0f356d461059bac2738a8d0f5bd499099 Add NetData to `dietpi-process_tool` and set default to nice +19
- :u6307: Test RPi 1 (ARMv6)
- :u6307: Test RPi 2/3 (ARMv7)
- :u6307: Test C2 (ARM64). Working fine.

**Comment by rhkean** [comment]
OMG... did I forget to email you the tarball.

**Comment by Fourdee** [comment]
@rhkean 
I cant find it in my emails, any chance you could send it over again please?

**Comment by Fourdee** [comment]
@rhkean 

**EDIT:**
Fixed it, EOL conversion was set to dos, change back to UNIX. Must of occured during a sync.

Bizzare, these lines of code:

```
            for x in /var/cache/netdata /usr/share/netdata/web /etc/netdata /var/log/netdata; do
                chown -R netdata.netdata $x
                chmod 0755 $x
            done
```

is causing:

```
root@DietPi:~# dietpi-software
/DietPi/dietpi/dietpi-software: line 4330: syntax error near unexpected token `fi'
/DietPi/dietpi/dietpi-software: line 4330: `            fi'
```

I looked through the commits, cant see anything that would cause this to happen. Strange, I'll check again.

**Comment by Fourdee** [comment]
Tested and confirmed:

```
echo 0 > /usr/share/netdata/web/version.txt
```

Prevents update flashing.

**Comment by rhkean** [comment]
we can just change that file in all of the tarballs
or do the echo during install and keep the tarballs as-is

preference?

**Comment by Fourdee** [comment]
@rhkean 
I've added this to the Apply_Config function in DietPi-Software: https://github.com/Fourdee/DietPi/commit/b611159df77fcea990d590b91f40308a620978bb

I've been updating this post with status: https://github.com/Fourdee/DietPi/issues/276#issuecomment-210417905

Apologies if I'am going a bit "full on" with this. I just want to get NetData finished today, so I can focus on the v116 re-images Saturday (son is away for the day) https://github.com/Fourdee/DietPi/issues/278 . Should also be able to get v116 released Saturday also.

**Comment by rhkean** [comment]
no apologies necessary.
I'm learning in the process... I caught the need to edit the patch_file, but missed the process_tool change requirements... :smile_cat:

**Comment by Fourdee** [comment]
Tested RPi 3, working fine. @rhkean , any chance you can test the RPi 1 install?

**Comment by rhkean** [comment]
yes, if I can get away from the office I'll test it at lunch.  Otherwise it'll be tonight, after work.
I've been wanting to test with my son's A+ anyhow... :smile:

**Comment by Fourdee** [comment]
@rhkean 
Excellent, I don't own a A+, got a Zero though. You will have to let us know what you think of it :)

> I'm learning in the process... I caught the need to edit the patch_file, but missed the process_tool change requirements...

You managed to do great so far, you've understood the DietPi code on your own. So good work :+1:

**Comment by rhkean** [comment]
:laughing: , I think the Zero has more RAM.

**Comment by rhkean** [comment]
A+ passed

BTW... we need to add the ip address to the banner.
the single usb port had the wifi in it....  I had to look up the dhcp address on the router so that I could access it remotely.. 😄

**Comment by rhkean** [comment]
B+ passed

**Comment by rhkean** [comment]
Rpi 2 B+: passed

**Comment by Fourdee** [comment]
@rhkean 
Excellent, thanks for the tests :+1: 

> BTW... we need to add the ip address to the banner.
> the single usb port had the wifi in it.... I had to look up the dhcp address on the router so that I could access it remotely.. 

Is this in DietPi-Software, or something else?

**Comment by rhkean** [comment]
the banner on the console at boot (before login) that says the version and default login information.

so, if you don't have a keyboard (but do have a monitor) you know what ip address to ssh to after the initial setup is complete.

**Comment by rhkean** [comment]
I think it comes from /Dietpi/dietpi/dietpi-banner
but, I haven't looked at the code yet

**Comment by Fourdee** [comment]
@rhkean 
Makes sense, good idea :+1: . `/Dietpi/dietpi/dietpi-banner` is correct. 
We can use the current code in `dietpi-software` for the same in `/Dietpi/dietpi/dietpi-banner`

```
WHIP_BACKTITLE="DietPi-Software | IP address: $(sed -n 4p /DietPi/dietpi/.network)"
```

So, add to `/Dietpi/dietpi/dietpi-banner`

```
echo -e "IP address: $(sed -n 4p /DietPi/dietpi/.network)"
#using existing colors as needed
```

You up for this one? Or want me to pop it in?

**Comment by rhkean** [comment]
done (created #284 ) and submitted the pull request

**Comment by Fourdee** [comment]
Thanks Rob. I'll mark this ticket as completed.

**Comment by WolfganP** [comment]
I just updated to v116, thx a lot for the enhancements guys. I noticed the discussions around the (almost constant) update notification and the mod to hide it, but I think one of the side effects is that it disallows manual updating (as netdata version is reflected as unknown)

![dietpi-netdata](https://cloud.githubusercontent.com/assets/2248211/14651878/2f154414-0648-11e6-981a-336a4c1480ee.jpg)

**Comment by Fourdee** [comment]
@WolfganP 
Yep. The downside of disabling the flashing update button (using the workaround https://github.com/firehol/netdata/issues/233#issuecomment-210468649) is the version check will not work: https://github.com/firehol/netdata/issues/233#issuecomment-210468649.

ktsaou mentions a possible option in the future that will simply disable the automatic update check. Until this is available, we will continue to use the workaround.

Its worth noting that the netdata update button only checks the version and lists changes, it does not have a facility to actually update the installation.

**Comment by rhkean** [comment]
@WolfganP ,

As @Fourdee mentioned, it does not actually facilitate updating the code.  Also note, we're providing pre-compiled binaries for netdata.

We'll try to keep up with netdata's major releases, and recompile when those milestones occur.

**Comment by WolfganP** [comment]
Yes, I read those issues # as well. Good to hear you're both on top of it. Thanks!
