### ISSUE TITLE
DietPi-Software | Disable Screen blanking during installation.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#277]
As per @rhkean suggestion: http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=356&p=1610#p1558

Not 100% sure if user input is the only thing that prevents screenblanking (power saving) on main screen. But there is no harm in adding it to our code.

This will only affect the main screen. Does not get applied to SSH sessions. Redirect output to prevent the warning from appearing on SSH sessions and unsupported devices.

**Comment by Fourdee** [comment]
Tested on RPi. 

```
setterm -blank 0 -powersave off &> /dev/null
```

Added to DietPi-Software to both functions: 
- `FirstRun_DietPi_Update`
- `Run_Installations`

Completed.

**Comment by Fourdee** [comment]
Retested, failed due to command being sent to `/dev/null`, rather than tty.

Resolved with stderr redirect:

```
setterm -blank 0 -powersave off 2> /dev/null
```

**Comment by hadifarnoud** [comment]
would be great to have this option in config as well.

**Comment by Fourdee** [comment]
@hadifarnoud 

> would be great to have this option in config as well.

In `dietpi-config` and `dietpi.txt`  to enable/disable screen blanking?
