### ISSUE TITLE
Network | wget --spider returns 500 on github.com and dietpi.com

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#2772]
Unable to download scripts from dietpi or GitHub on fresh build saying connection failed yet apt-get update is able to connect just fine.

**Comment by MichaIng** [comment]
@raidensnake 
Many thanks for your report.

Could you please run and paste:
```
time wget --spider https://dietpi.com/downloads/binaries/all/cava.psf
time wget --spider https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
```
- It will not download anything, just checking and verifying file existence and report the time required for this.

**Comment by ghost** [comment]
The response came back as 500 internal server error on both.

**Comment by MichaIng** [comment]
@raidensnake 
Both? 🤔
It's definitely not about github.com or dietpi.com since they work very well here, finishing the check successful in 0.2s.

Please paste the full output regardless, possibly it contains some other helpful info.

**Comment by ghost** [comment]
`root@DietPi:~# time wget --spider https://dietpi.com/downloads/binaries/all/cava.psf
Spider mode enabled. Check if remote file exists.
--2019-05-07 13:28:20--  https://dietpi.com/downloads/binaries/all/cava.psf
Resolving dietpi.com (dietpi.com)... 104.27.179.199, 104.27.178.199, 2606:4700:30::681b:b3c7, ...
Connecting to dietpi.com (dietpi.com)|104.27.179.199|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
Failed to get a valid response!!!`

**Comment by raidensnake** [comment]
`root@DietPi:~# time wget --spider https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
Spider mode enabled. Check if remote file exists.
--2019-05-07 13:28:06--  https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
Failed to get a valid response!!!`

**Comment by raidensnake** [comment]
there are the outputs also my shell didn't copy the first part properly.

**Comment by ghost** [comment]
`root@DietPi:~# time wget --spider https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
Spider mode enabled. Check if remote file exists.
--2019-05-07 13:28:06--  https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
Failed to get a valid response!!!`

**Comment by ghost** [comment]
there are the outputs also my shell didn't copy the first part properly. it decided to bug out on me since I'm on a tablet. the touch screen is a pain sometimes.

**Comment by MichaIng** [comment]
@raidensnake
Hmm since it's two totally dedicated servers it's perhaps related to wget.

Could you try it with replacing `wget --spider` with `curl -IL`?

**Comment by ghost** [comment]
Sorry the command failed to connect.

**Comment by MichaIng** [comment]
@raidensnake 
Do you have any local adblocker, VPN, Pi-hole or something similar installed? I guess opening this link in browser works, right? https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt 

Does downloading/connecting to any other server work? E.g.
```
cd /tmp
wget --spider https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.5.deb
wget https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.5.deb
```

**Comment by MichaIng** [comment]
Ref: https://github.com/MichaIng/DietPi/issues/2834

**Comment by MichaIng** [comment]
I mark this as closed, feel free to reopen if issue persists and is not related to Pi-hole blocklist (referenced issue).
