### ISSUE TITLE
DietPi-Software | Firefox standalone install

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#2815]
#### Formal software information
- Software title | Firefox Browser
- Short description | <-Web Browser->

#### Are there similar/alternative software titles available with DietPi-Software?
Chromium Browser

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

1. apt-get install  xorg matchbox firefox-esr
2. sudo nano /etc/apt/sources.list
3. type in the end deb http://ftp.debian.org/debian stretch main contrib non-free
4. save and exit
5. apt-get update && apt-get install browser-plugin-freshplayer-pepperflash
6. autostart with the same method as Chromium Browser

### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
Yes, I could help out with this, e.g. if I experience issues

**Comment by MichaIng** [comment]
@symbios24 
Many thanks for your request.

Actually we ship Firefox as default web browser with all desktop installs. Do you want it available as standalone install? But since a desktop is required anyway for this, I don't see a reason currently?

**Comment by symbios24** [comment]
yes i want it as standalone install ,i have tested it and runs standalone with the same method as chrome browser

**Comment by MichaIng** [comment]
Done for next release, including a preference menu to be respected when a desktop is installed: #4314
