### ISSUE TITLE
Add IP Address to DietPi Banner to ease remote access

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#284]
Adding for tracking purposes

**Comment by Fourdee** [comment]
@rhkean 
Thanks Rob :+1:.

Looking good:
![image](https://cloud.githubusercontent.com/assets/7077026/14582795/c2cc559c-0406-11e6-80f5-65824eb116c7.png)

The only issue is this wont be active until the user updates their version of DietPi, or, I redo the DietPi images again for v116. Apologies for that, I should of mentioned. I had to get the images done today, only chance I'll have for a week or two: https://github.com/Fourdee/DietPi/issues/278

I'll make a note to redo the main images (c2/c1/rpi), but it may be after v116 is released.

**Comment by rhkean** [comment]
😺 figures. too funny

should have thought of it before last night.... my bad.   ROFL

**Comment by Fourdee** [comment]
lol. 

I could explain the image creation process if you are intrested? It's a little lengthy, but would allow you to update the DietPi images as you need :)

ps. Son is staying over nans tonight, Can finally watch Martinsville SCS , cant wait :)

**Comment by rhkean** [comment]
I'm game...  Not tonight though... Heading out to dinner with the Mrs.

**Comment by k-plan** [comment]
hmm ... I have "Address" twice

![160417-0001](https://cloud.githubusercontent.com/assets/17237601/14587415/d9a55f3c-04b2-11e6-9f63-afd70d0e2165.gif)
![160417-0002](https://cloud.githubusercontent.com/assets/17237601/14587418/e802a184-04b2-11e6-9579-6d8b19ab35b9.gif)

```
root@oDroid-C1-Plus-Test:~# sed -n 4p /DietPi/dietpi/.network
Adresse:172.16.1x.xx
```

Sorry, and yes 

```
root@oDroid-C1-Plus-Test:~# locale
LANG=de_DE.UTF-8
```

**Comment by rhkean** [comment]
not so much a typo, but an issue with the locale... how the value gets parts and stored in the /DietPi/dietpi/.network file.

just suck it up @k-plan !!!!   😈 

no, seriously, I'll look into it.  good catch

**Comment by k-plan** [comment]
https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-config#L1813

... but I don't understand what you are doing there. Sorry - Null-coding-skill.

**Comment by rhkean** [comment]
@k-plan can you give me the output of your ifconfig ?
the double address is a parsing error that I can fix, but I need to verify what the non-english ifconfig output looks like.

**Comment by k-plan** [comment]
```
root@oDroid-C1-Plus-Test:~# ifconfig
eth1      Link encap:Ethernet  Hardware Adresse 33:e6:20:13:30
          inet Adresse:192.168.0.154  Bcast:192.168.0.255  Maske:255.255.255.0
          inet6-Adresse: fe80::33e:6ff:fe20:1330/64 Gültigkeitsbereich:Verbindung
          inet6-Adresse: 2001:170:110b:c2c:33e:6ff:fe20:1330/64 Gültigkeitsbereich:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metrik:1
          RX packets:79254 errors:0 dropped:64 overruns:0 frame:0
          TX packets:71248 errors:0 dropped:0 overruns:0 carrier:0
          Kollisionen:0 Sendewarteschlangenlänge:1000
          RX bytes:6067871 (5.7 MiB)  TX bytes:12547760 (11.9 MiB)
          Interrupt:40

lo        Link encap:Lokale Schleife
          inet Adresse:127.0.0.1  Maske:255.0.0.0
          inet6-Adresse: ::1/128 Gültigkeitsbereich:Maschine
          UP LOOPBACK RUNNING  MTU:65536  Metrik:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          Kollisionen:0 Sendewarteschlangenlänge:0
          RX bytes:984 (984.0 B)  TX bytes:984 (984.0 B)

wlan0     Link encap:Ethernet  Hardware Adresse 61:da:38:73:e3:aa
          inet Adresse:192.168.0.54  Bcast:192.168.0.255  Maske:255.255.255.0
          inet6-Adresse: fe80::61da:38ff:fe73:e3aa/64 Gültigkeitsbereich:Verbindung
          inet6-Adresse: 2001:170:110b:c2c:61da:38ff:fe73:e3aa/64 Gültigkeitsbereich:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metrik:1
          RX packets:3954 errors:0 dropped:525 overruns:0 frame:0
          TX packets:47 errors:0 dropped:5 overruns:0 carrier:0
          Kollisionen:0 Sendewarteschlangenlänge:1000
          RX bytes:569676 (556.3 KiB)  TX bytes:6169 (6.0 KiB)
```

**Comment by rhkean** [comment]
bug tracking:  #287 
patched:  #286

**Comment by k-plan** [comment]
@rhkean 

Sorry dump question:
Now we have to wait @Fourdee, to look over and merge your fix in testing branch.
After this, I can update to testing branch and test it. Is it correct?

**Comment by rhkean** [comment]
@k-plan correct
and he just did that, so you're good to test

**Comment by k-plan** [comment]
```
root@oDroid-C1-Plus-Test:~# sed -n 4p /DietPi/dietpi/.network
172.16.10.54
```

![160417-0003](https://cloud.githubusercontent.com/assets/17237601/14588572/05202dbc-04cd-11e6-9c4a-f8f1b36a4c3a.gif) 
![160417-0004](https://cloud.githubusercontent.com/assets/17237601/14588573/0fd1a128-04cd-11e6-9fcb-02c2c846c66a.gif)

@rhkean 💯  👍 

@Fourdee  👍  - push v.116 out (_please quick_ - 😄   - _and have a break_)

---

@k-plan    🇩🇪 
@Fourdee  🇬🇧 
@rhkean  :question:

**Comment by rhkean** [comment]
🇺🇸

**Comment by Fourdee** [comment]
@rhkean @k-plan 
Looking like v116 release for tomorrow, however, may be Tuesday at the latest. Just need to finish these jobs off:
- DietPi's hosting provider MyVirtualServer.com: https://github.com/Fourdee/DietPi/issues/288
- `LANG=en_GB.UTF-8` to all scripts if we can prevent `locale-gen --purge` from being used to remove `en_GB.UTF-8`: https://github.com/Fourdee/DietPi/issues/287

**Comment by Fourdee** [comment]
Will mark this as closed. 
I've created a new ticket to resolve non-english parsing issues throughout DietPi scripts: https://github.com/Fourdee/DietPi/issues/291

**Comment by rhkean** [comment]
Anyone else not seeing the IP Address populated with V117?

It's not getting populated on dietpi-banner call from rc.local and my RPi A+

I'm wondering if we optimized it too much... :laughing:

**Comment by Fourdee** [comment]
@rhkean 
Yep, it occurred a few times for me. Seems to be when set to DHCP, and when https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/obtain_network_details#L83 results have no IP entry.

I thought about creating a while loop if the IP address is empty, but this would need to be launched as another thread (process) to prevent delaying the system during boot.

For now, I added `obtain_network_details` to the `login` script: https://github.com/Fourdee/DietPi/blob/testing/dietpi/login#L128

**Comment by Fourdee** [comment]
@rhkean 
Did some debugging, added the following to the `obtain_network_details` script:

```
        #debug
        ip r >> /root/ipr
        ifconfig "$ACTIVE_DEVICE" >> /root/ifc
        echo -e "$ACTIVE_DEVICE" >> /root/iactive
```

Results after reboot:

```
root@DietPi:~# cat iactive
eth0
root@DietPi:~# cat ipr
root@DietPi:~# cat ifc
eth0      Link encap:Ethernet  HWaddr 00:1e:06:33:15:23
          inet6 addr: fe80::21e:6ff:fe33:1523/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:600 (600.0 B)
          Interrupt:40
```

So it looks like `ip r` and `ifconfig` dont have the IP address for ipv4 at the time its called. Tested with DHCP.

**Comment by xenfomation** [comment]
How did I miss this?!?!  I can translate as I read/speak Spanish, French, German, and Dutch... and more.   AUGH!  I will look at  https://github.com/Fourdee/DietPi/issues/291 NOW so I can at least get something checked in!!
