### ISSUE TITLE
Webmin bug

### ISSUE THREAD

**Issue by echable9999** [MichaIng/DietPi#2847]
Got this error during webmin install on fresh OS flash on XU4. Brought up prompt that required OK.

Additional errors followed but they were too quick.

**Comment by MichaIng** [comment]
@echable9999 
Many thanks for your report.

Unable to replicate. Could you paste the full error message:
```
cd /tmp
wget http://www.webmin.com/download/deb/webmin-current.deb
```

**Comment by echable9999** [comment]
Sorry that's all I got it was during a fresh OS install software install
