### ISSUE TITLE
Pinebook | New image required to fix firstrun update issue

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2864]
Ref: https://dietpi.com/phpbb/viewtopic.php?p=18226#p18226

The fix was patched with v6.20 but the image we offer for download is older and does not yet contain it. Since error appears during APT upgrade, patch cannot be applied.

We can move the fix to pre-patches (we should do this anyway), but a new image would not hurt as well.

**Comment by Fourdee** [comment]
@MichaIng 

Leave the image update with me, will try and do it today.

**Comment by MichaIng** [comment]
@Fourdee 
Many thanks!

Try out https://github.com/MichaIng/DietPi/blob/dietpi-image/.meta/dietpi-image to speed things up. Should be safe, only GPT I am not sure about.

**Comment by Fourdee** [comment]
Notes:
- Unable to change brightness of LCD panel | ```/sys/class/backlight/backlight/brightness``` now has no effect.
- ```bl_power 0``` turns off display, no other value turns it back on
```
root@DietPi:~# echo 0 > /sys/class/backlight/backlight/bl_power 
root@DietPi:~# echo 1 > /sys/class/backlight/backlight/bl_power

root@DietPi:~# /sys/class/backlight/backlight/
actual_brightness  device/            subsystem/
bl_power           max_brightness     type
brightness         power/             uevent
```

---

- dietpi-boot.service taking 2minutes?

---

- Any ARMbian image we read, then resize. Reopening the image under loopback causes a "Cant have a partition outside of the disk" error. Partition is visible in gparted, however not mountable. Regardless the image works.
- Issue is why are ARMbian images only doing this? Something they have added to prevent users re-imaging, or, their resize script on their 1st run setup is causing this issue?
Requires testing.
- Images are MBR, no GPT resize issue?
- If we run a truncate on the original ARMbian image, this causes the issue:
![image](https://user-images.githubusercontent.com/7077026/58492572-1677a600-8169-11e9-803a-95a821569f5d.png)

**Comment by Fourdee** [comment]
Notes:
- ```resizepart``` does not re-arrange contents: https://unix.stackexchange.com/questions/169395/how-do-i-resize-partitions-and-filesystems-on-them

**Comment by MichaIng** [comment]
@Fourdee 
You mean `parted resizepart`, right? https://github.com/MichaIng/DietPi/pull/2693/files#diff-38702c6380ec8afa2acb3aff1616a6ccR114

Hmm we anyway can't resize the partition to a lower value then the size of the file system with `resize2fs`. Also gparted simply denies to do so. And since `resize2fs` does not rearrange content of course, `parted resizepart` to the size of the file system (resize2fs) should include possible gaps. AFAIK gparted as well does not rearrange content, in terms of closing gaps. It moves partitions around if you choose to do so but does not allow to shrink them any further than what resize2fs had as minimum before. This is why some month ago I had trouble with creating the x86 PC image, since whatever I did, the fs/partition gaps were not closed. Only solution was to move out the whole content, shrink the empty partition to what should be enough and move the content inside again.

Did you run into the issue when running the above script?

**Comment by Fourdee** [comment]
#### PB image is currently being redone due to a previous update issue. We aim to have this image available again ASAP.

---

@MichaIng 

```dietpi-imager``` appears to be working now, nice work on the resize loop btw. Script will be a timer saver.

Redone the PB image, however, wont boot back up a second time after FS resize. more debugging to do.

**Comment by Fourdee** [comment]
User reports truncated .7z, fails to extract. Will look into this once we fix the initial image.

For now, updated the URL for PB DL to this ticket.

**Comment by MichaIng** [comment]
@Fourdee 
> truncated .7z

Since the 7z archive is not truncated of course, does the extraction indeed fail or flashing/booting the interned img file (which is truncated)?
#### EDIT: Just tested it, indeed it fails to extract or even open in 7zip on Windows. But has nothing to do with the interned file, but the 7z archive itself.

Not sure if compression method could be an issue (LZMA2 ultra), but with current Windows and Debian Stretch available versions it works. Also RAM usage on extraction is not high, just for the compression it is.
_____________
About the bootup issue:
- Does the "partition outside the disk" error still appear on parted? Perhaps this needs to be fixed first?
- Otherwise what is the issue/error on second boot? If it simply hangs at some stage, the following might be the reason: https://github.com/MichaIng/DietPi/issues/2806
  - I am afraid we might need to pre-install `haveged` on all images, since the long random init causes issues on several edges, sometimes visible to user, sometimes not. I am still investigating/testing this, e.g. depending on attached hardware or not.

**Comment by MichaIng** [comment]
New image from past week opens well, so I mark this as finished.

**Comment by canonex** [comment]
> #### PB image is currently being redone due to a previous update issue. We aim to have this image available again ASAP.
> 
> @MichaIng
> 
> `dietpi-imager` appears to be working now, nice work on the resize loop btw. Script will be a timer saver.
> 
> Redone the PB image, however, wont boot back up a second time after FS resize. more debugging to do.

Dear DiedPi,
the Pinebook download page redirects here:
is there any news for a fixed image?

Thank you
Riccardo

**Comment by MichaIng** [comment]
@canonex 
Damn, the download link got reverted or was never updated, many thanks for reporting! Just fixed it. Please try again, in case refresh browser cache by reloading the download page via CTRL+F5.

Please report back if you find any issue with the image, first or first reboot, so we're sure the initial issue for the image re-creation is fixed.

**Comment by canonex** [comment]
I'm downloading the image right now, the link works fine.
I'll report any issue when installing.

Thank you,
Riccardo

**Comment by canonex** [comment]
Diet is starting properly (even if no audio and don't know how to copy to eMMC).

**Comment by MichaIng** [comment]
@canonex 
Many thanks for testing.

Selecting the default sound card via dietpi-config > Audio Options does not enable audio?

AFAIK it should be possible to flash the image to the eMMC directly, if you have some adapter. Or you download it on the now running Pinebook system and flash it onto internal eMMC via `dd`.

Finally it would be great if we would ship some DietPi installer that you flash on e.g. USB flash drive and which then installs/flashes DietPi to an internal drive. We have this for our EFI images, where it is required, and tools/methods (via Clonezilla) to create images for CSM/BIOS images as well. They only need some fine tuning and finally someone needs to find time to create those images, test them etc 😉.

**Comment by canonex** [comment]
@MichaIng thank you, dd solved the copy.

Audio is not working, even after update. I should open a bug report (was working with Manjaro).
The configuration scripts are bash super-powered!
