### ISSUE TITLE
DietPi-Software | DuckDNS

### ISSUE THREAD

**Issue by mzramna** [MichaIng/DietPi#2868]
#### Is your feature request related to a problem? Please describe:

- duckdns is an easy and free to use alternative to no-ip,that can be asily setup from terminal

#### Describe the solution you'd like:

- could be added to the software tab as an alternative to the already existent softwares

#### Additional context

- it dows exactaly the same as no-ip,so why not put it in there since it is free,and simple to setup? 
the own duckdns website already gives the bash script to setup in solutions like the dietpi-software (just change the variables by the given website name and the given token)

#### Vote for this feature on https://feathub.com/MichaIng/DietPi/+85

**Comment by MichaIng** [comment]
@mzramna 
Many thanks for your request.

We'll have a look when we can. You might want to raise priority by adding the request to FeatHub and complete the link above to collect votes.

**Comment by MichaIng** [comment]
Ref: https://dietpi.com/phpbb/viewtopic.php?p=18685#p18685

**Comment by Joulinar** [comment]
@MichaIng 
I guess it can be closed as 7.1 has been released 😃

**Comment by MichaIng** [comment]
Whoops, I forgot to add the milestone, so oversaw it, thanks.
