### ISSUE TITLE
obtain_network_details not parsing ip address properly on non-english systems

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#287]
see comments on #284 

fixed with pull request #286

**Comment by Fourdee** [comment]
@rhkean 

I recently applied:
`LANG=en_GB.UTF-8` to our main DietPi scripts. This ensures all parsing is returned in English: 
Ticket = https://github.com/Fourdee/DietPi/issues/273#issuecomment-210806262
Commit = https://github.com/Fourdee/DietPi/commit/aaf33009c717b42cab74353c0324590dbd8af182

I'am tempted to add this to all the DietPi scripts , which should prevent non-english parsing errors from occurring completely in all DietPi scripts.

**Comment by Fourdee** [comment]
@rhkean 

> we can do that, too... I still recommend the 'cut' instead of the 'sed'
> also, the forcing of en_GB will work, right up until someone runs 'locale-gen --purge' with en_GB not checked.

Yep, I've merged the pull request.

`locale-gen --purge` good spot :+1: . We could add a bash alias to `/etc/bash.bashrc` to prevent this from occurring, if we can't find another solution.

**Comment by Fourdee** [comment]
Ok will mark this as closed, created a new ticket to attempt to force english parsing throughout DietPi scripts: https://github.com/Fourdee/DietPi/issues/291
