### ISSUE TITLE
https://dietpi.com/ website is down !!

### ISSUE THREAD

**Issue by cocoflan** [MichaIng/DietPi#2878]
### ADMIN EDIT
@ Odroid users, if you need to do APT update, please comment the fuzon.co.uk entries in `/etc/sources.list.d/*.list` files for now. We will inform you here and via MOTD when our VPS is back up.

**Comment by MichaIng** [comment]
@cocoflan 
Many thanks for the info.

My goodness, https://myvirtualserver.com itself is completely down. Damn, no chance to reach the VPS.

**Comment by cocoflan** [comment]
What is happening ???

**Comment by MichaIng** [comment]
@cocoflan 
No idea. Since Fourdee is main contact, perhaps he got some info, not sure. Seem to be some serous issue if even their website is down + at least our VPS 😨.

**Comment by cocoflan** [comment]
That is something that should be very exceptional, a host down, keep us informed.

**Comment by MichaIng** [comment]
@cocoflan 
Jep, first time since 3 years 2 months. Hmm would bring my home server up to serve static downloads, but they're not up to date. Used this to keep static downloads up during server update and backup. Should keep it in sync regularly perhaps 🤔.

**Comment by cocoflan** [comment]
yes i should do that, the more to know, always beter.

**Comment by cocoflan** [comment]
Even https://status.myvirtualserver.com/ doesn't work, not professional!!

**Comment by cocoflan** [comment]
For users how need some manuals

https://web.archive.org/web/20171103051823/http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&sid=0559b1fac8c50dc0964322750da2cf1c

**Comment by causefx** [comment]
:/ today was the day I was gonna try this out.... Now I can't download it :(

**Comment by MichaIng** [comment]
@causefx 
Sorry for that. Tomorrow we will know more, it's late after midnight in Europe 😉.

**Comment by causefx** [comment]
no worries :)

Hope it all works out for ya guys.

**Comment by benjaminpreiss** [comment]
I just visited the status page. It says the downtime was planned and all systems should be Working again.

But sadly sudo apt update is still failing

**Comment by benjaminpreiss** [comment]
I just successfully ran sudo apt update and upgrade... server seems to be up and running.

Whatever you guys did, thanks!

**Comment by MichaIng** [comment]
@benjaminpreiss 
Many thanks for the info. Jep, everything fine again. Hmm from the status page it sounds like if it was about the domain. But actually the VPS' were down as well, and they were not shut down gracefully but it was a kill. We can just hope there there is no database corruption or such, will do some checkup.

**Comment by MichaIng** [comment]
Okay everything indeed seems to be fine, although I am still not happy with the fact that it was no ordered shutdown and that obviously there was not information given e.g. 1 week before. If one relies on the web services, the information about planned downtimes needs to be given way earlier so that one can prepare alternative servers and such.

However I mark this issue as closed.
