### ISSUE TITLE
MyVirtualServer.com - The new web hosting provider of DietPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#288]
http://MyVirtualServer.com is now DietPi's hosting provider. http://dietpi.com has been redirected (pending ahost update), forum move will start in the week.
New IP URL = http://185.101.92.145
#### Add following MyVirtualServer.com coverage/sponsership to DietPi as discussed:
- :u6307:  http://dietpi.com = Header + description + image at bottom of page
- :u6307: README.md = Header + description (above DietPi team)
  https://github.com/Fourdee/DietPi/blob/testing/README.md#dietpis-web-hosting-is-powered-by-httpmyvirtualservercom
- :u6307: Twitter post linking our new hosting provider
  https://twitter.com/DietPi_/status/722137726645051392
- :u6307: Add hosting coverage to all DietPi forum signature accounts (RPi forum/Odroid forum etc)
  RPi =  https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=100976&p=699863#p699863
  XU4 =http://forum.odroid.com/viewtopic.php?f=96&t=15700&p=102472#p102472
  C1 = http://forum.odroid.com/viewtopic.php?f=114&t=11962&p=83691#p83691
  C2 = http://forum.odroid.com/viewtopic.php?f=138&t=19948
- :u6307: Add hosting coverage to `dietpi-banner 1`
  ![image](https://cloud.githubusercontent.com/assets/7077026/14615773/3411773e-059f-11e6-98d4-252f51f46bc9.png)

**Comment by k-plan** [comment]
OT:
@Fourdee 

do you ever slow down and have a break? :flushed:

Puhh, changing additional  the hoster/isp now. Is the new vServer a for-free / sponsoring offer? Or have you to pay for it? A OVZ-1 model? 

Can we  assist  you, or do something else?

**Comment by Fourdee** [comment]
@k-plan 
Slowing down today, come down with flu lol.

MyVirtualServer.com are sponsoring DietPi by providing us with a VPS to host dietpi.com, and, the dietpi forums (once i've moved them over).

> Can we assist you, or do something else?

I cant think of anything at the moment, but I will let you know if I do :+1:

**Comment by Fourdee** [comment]
@k-plan 
The VPS package is OVZ-3, and its blazingly fast :)

**Comment by Fourdee** [comment]
Completed, marked as closed.
