### ISSUE TITLE
`dietpi-apt-get_update` killing `ntpd`

### ISSUE THREAD

**Issue by plattrap** [MichaIng/DietPi#289]
`dietpi-apt-get_update` script is killing `ntpd`, and not restarting it. Also ignores current setting of `ntpd_update_mode=` in `dietpi.txt`.

Probably should ignore `ntpd` if `ntpd_update_mode=0`?

I have ntp running as a network time server on my system, with a local GPS attached, and would like it to run forever. I have created a service to start ntpd at startup, but have the daemon being killed bu the update script.

**Comment by Fourdee** [comment]
@plattrap 

Many thanks for the bug report. 
We have a NTPD option that allows for it to run constantly, with time drift. This option is available in `dietpi-config` > advanced > Time sync (ntpd). Once in this mode, `dietpi-apt-get_update` will not kill the process.

> Probably should ignore ntpd if ntpd_update_mode=0?

Yep, make sense.
I've updated `dietpi-apt-get_update` to ignore waiting for NTPD (and killing it) if `ntpd_update_mode=0`

This fix will be available in the v116 update: https://github.com/Fourdee/DietPi/commit/b29a7847cccf7fd9b9623afbf49de4d17d905cdf

I'll mark this as closed, please reopen if required.
