### ISSUE TITLE
Trying to toggle state to Enable WiFi Hotspot on Pi

### ISSUE THREAD

**Issue by muzzak123** [MichaIng/DietPi#2894]
#### Details:
- Date           | Fri  7 Jun 13:55:16 AWST 2019
- Bug report     | N/A
- DietPi version | v6.24.1 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B+ (armv7l) (index=3)
- Kernel version | `#1219 SMP Tue May 14 21:20:58 BST 2019`
- Distro         | stretch (index=4)
- Command        | systemctl start hostapd
- Exit code      | 1
- Software title | DietPi-Config

#### Steps to reproduce:

1. Go into DietPi-Config
2. Select 7  : Network Options: Adapters 
3. Select WiFi         : Available | [On] | Disconnected
4. Select State    : [Disabled] | Select to turn on hotspot 
                       
#### Expected behaviour:

Should turn WiFi State to Enabled

#### Actual behaviour:

tPi-Config: systemctl start hostapd
Exit code: 1
DietPi version: v6.24.1 (MichaIng/master) | HW_MODEL:3 | HW_ARCH:2 | DISTRO:4
Image creator: DietPi Core Team
Pre-image: Raspbian Lite

 file contents:
 for hostapd.service failed because the control process exited with error code.
 "systemctl status hostapd.service" and "journalctl -xe" for details.
unable to continue, DietPi-Config will now terminate.

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Job for hostapd.service failed because the control process exited with error code.
See "systemctl status hostapd.service" and "journalctl -xe" for details.


Jun 07 14:09:29 DietPi systemd[1]: hostapd.service: Service hold-off time over,
scheduling restart.
Jun 07 14:09:29 DietPi systemd[1]: Stopped Advanced IEEE 802.11 AP and IEEE 802.
1X/WPA/WPA2/EAP Authenticator.
-- Subject: Unit hostapd.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit hostapd.service has finished shutting down.
Jun 07 14:09:29 DietPi systemd[1]: Starting Advanced IEEE 802.11 AP and IEEE 802
.1X/WPA/WPA2/EAP Authenticator...
-- Subject: Unit hostapd.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit hostapd.service has begun starting up.
Jun 07 14:09:29 DietPi hostapd[4925]: Configuration file: /etc/hostapd/hostapd.c
onf
Jun 07 14:09:29 DietPi hostapd[4925]: nl80211: Could not configure driver mode
Jun 07 14:09:29 DietPi hostapd[4925]: nl80211: deinit ifname=wlan0 disabled_11b_
rates=0
Jun 07 14:09:29 DietPi hostapd[4925]: nl80211 driver initialization failed.
Jun 07 14:09:29 DietPi hostapd[4925]: wlan0: interface state UNINITIALIZED->DISA
BLED
Jun 07 14:09:29 DietPi hostapd[4925]: wlan0: AP-DISABLED
Jun 07 14:09:29 DietPi hostapd[4925]: hostapd_free_hapd_data: Interface wlan0 wa
sn't started
Jun 07 14:09:29 DietPi systemd[1]: hostapd.service: Control process exit
ed, code=exited status=1
Jun 07 14:09:29 DietPi systemd[1]: Failed to start Advanced IEEE 802.11
AP and IEEE 802.1X/WPA/WPA2/EAP Authenticator.
-- Subject: Unit hostapd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit hostapd.service has failed.
--
-- The result is failed.

```

**Comment by MichaIng** [comment]
@murraykessell 
Many thanks for your report.

Please try to upgrade to the Raspbian repo version: `G_AGI --reinstall hostapd`

**Comment by muzzak123** [comment]
Thanks that's fixed it

**Comment by MichaIng** [comment]
@murraykessell 
Thanks for feedback. Will implement it as default into DietPi-Software.
