### ISSUE TITLE
DietPi-Config in interfaces is not the correct command

### ISSUE THREAD

**Issue by Sopor** [MichaIng/DietPi#2901]
In `interfaces` i can read this info
`#Please use DietPi-Config to modify network settings.` but that command doesn't work because it is not found. The correct command should be `dietpi-config`.

It may sound ridiculous but if you are a newbie you will get problem if you copy that and try to run it.

**Comment by MichaIng** [comment]
@Sopor 
Thanks for the hint, jep makes sense to use the actual command name here, at best in double quotes.

Ah, I did this already when adding the drop-in config support: https://github.com/MichaIng/DietPi/blob/dev/dietpi/dietpi-config#L2407
So once you change+apply interface settings, it should show the command as you suggested.

**Comment by MichaIng** [comment]
I mark this as closed, feel free to reopen if required.
