### ISSUE TITLE
Ensure all DietPi scripts can parse correctly, regardless of system locale

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#291]
All DietPi scripts rely on english results to ensure parsing is completed correctly.

Force `en_GB.UTF-8` throughout DietPi scripts to ensure all parsing results are returned in english, regardless of system locale.

**Comment by Fourdee** [comment]
I have applied the following to all DietPi scripts https://github.com/Fourdee/DietPi/commit/5500ffd83ab2b2072595dd9f36dc97e9f070fc2d:

```
    #Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
    LANG=en_GB.UTF-8
```

This will ensure all parsing results are returned in english, regardless of active system locale.

To prevent users removing `en_GB.UTF-8`:
I've added a message box to `dietpi-config`, when user changes locale:
![image](https://cloud.githubusercontent.com/assets/7077026/14612275/26232ade-058e-11e6-8b25-3726fc6421ab.png)

**Comment by k-plan** [comment]
@Fourdee 

hmm ...  you although  keep track of DietPi-Automation and templates? 

```
#Language/Regional settings | Requires AUTO_Install_Index=1
. . .
#   Locale eg: en_GB en_US | Full list: cat /etc/locale.gen
AUTO_Locale=en_GB
```

I like dietpi-automation templates very much and often use it.

If someone set here a other language, what will happen now?

Would be nice to have always set "`C`" and "`en_GB.UTF-8`" and 
e.g. `AUTO_Locale=de_DE` should only added the new extra default-language.

#174

**Comment by Fourdee** [comment]
@k-plan
As far as I'am aware, the current automation system for setting locale is not working correctly.

> e.g. AUTO_Locale=de_DE should only added the new extra default-language

Yep :+1: , I'll make a note to test `en_GB.UTF-8` is not removed when user has automation setting for locale.

**Comment by rhkean** [comment]
Away from my computer at the moment, but I know that tool creates a text
file that lists out all the locales to build...  We could add some extra
code to always insert en-GB

Otherwise we'll need to go through everywhere that a bin util output is
parsed and correct it.
On Apr 18, 2016 1:44 PM, "Dan" notifications@github.com wrote:

@k-plan https://github.com/k-plan
As far as I'am aware, the current automation system for setting locale is
not working correctly.

I'll make a note to test en_GB.UTF-8 is not removed when I get round to
fixing it.

**Comment by Fourdee** [comment]
@rhkean 

> but I know that tool creates a text
> file that lists out all the locales to build...  We could add some extra
> code to always insert en-GB

Excellent, sounds perfect :+1:

**Comment by Fourdee** [comment]
@rhkean 
I'am aiming to release v116 today, this is the only item left.

Do you think it is possible to have your suggestion implemented within the next 2-4 hours? If not, I will close this ticket and we can create a new one for v117 (eg: Prevent users from deselecting/removing en_GB during locale change).

As we have a msgbox warning when users change their locale, its not critical at the moment as users will be aware. Let me know your thoughts.

**Comment by rhkean** [comment]
@Fourdee 

Sorry Dan.  I can't get to this today.  I'm being pulled in about 6 directions at work at the moment.

EDIT...
and.... I just realized that you asked me to do this several hours ago.... I'm really sorry.

**Comment by Fourdee** [comment]
@rhkean 
No worries and no rush. :+1: 
I was just seeing if we could get this in before v116 release. Its not critical and can wait until your available and have the time.

**Comment by Fourdee** [comment]
@rhkean 
I'll mark this as closed. I believe the warning message I've added to `dietpi-config` when changing locale should be enough.

If we get users reporting errors due to removal of `en_GB`, then we can add in your suggested measure to force `en_GB` as always installed.
