### ISSUE TITLE
RPi | Onboard WiFi not available

### ISSUE THREAD

**Issue by diveyez** [MichaIng/DietPi#2924]
DietPi Stable Stretch
Rpi3b, Clean install. 
wlan0 is not available, installing net-tools reveals no devices in ifconfig, as well as other various tools.

Desktop configuration failed as no adapter is visible.

diet-pi config reveals 
WiFi : Not Found [on] Disconnected
Onboard WiFi [on]
however again, there is no adapter to tinker with.

pre-req apt packages were not found, installer failed, had to manually install the packages.

I remember specifically enabling wifi, something is wrong with the dietpi-config tool and it needs to be reworked, especially since it also failed to allow me to change keyboard language/region.

**Comment by MichaIng** [comment]
@diveyez 
Many thanks for your report.

Forget about `net-tools`, it's outdated and obsolete on modern systems :wink:. `iproute2` and the `ip` command set is the replacement which is pre-installed and used on all Debian systems (and many other distros).
Please check: `ip r`
- This should list all available adapters, regardless if being configured or not.

> pre-req apt packages were not found, installer failed, had to manually install the packages.

Can you paste the exact messages about this error? Actually all WiFi packages should be installed by default on our images, and if manually removed, of course they should be installed automatically.

> especially since it also failed to allow me to change keyboard language/region.

As of the other issue, it is an external issue on Buster only, which requires fix on Debian side. We will only invest effort for a workaround if Debian does not fix it until official Buster release: https://github.com/MichaIng/DietPi/issues/2912

**Comment by diveyez** [comment]
Thanks

**Comment by MichaIng** [comment]
@diveyez 
Is missing onboard WiFi issue still apparent?

**Comment by diveyez** [comment]
Negative. Seems to have been patched with rpikernelhack updates recently.
