### ISSUE TITLE
download link error in website

### ISSUE THREAD

**Issue by as3ii** [MichaIng/DietPi#2928]
#### Steps to reproduce
1. go to https://dietpi.com/
2. click on `Download` or scroll down to download section
3. click the `Raspberry Pi` picture
4. click on `Download Buster experimental image for testing`

#### Expected behaviour

- Start download of https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster.7z

#### Actual behaviour

-  open https://dietpi.com/downloads/testing/DietPi_RPi-ARMv6-Buster.7z with 404 error

**Comment by MichaIng** [comment]
@as3ii 
Many thanks for your report. Looks like @Fourdee updated the website from his local version while I moved and edited the RPi Buster image it meanwhile.

Funny that I just checked this earlier today (for another reason) and link was still correct. We have to communicate better about website changes 😄.

Fixed it. Press ctrl+F5 to clear cache and reload the page, then it should show the correct URL again.
