### ISSUE TITLE
Move fuzon.co.uk forums/links over to new VPS dietpi.com

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#294]
fuzon.co.uk > dietpi.com
- :u6307: Forums
- :u6307: dietpi-survey
- :u6307: dietpi-bugreport
- :u6307: https://github.com/Fourdee/DietPi/commit/9e2b3c85ada60ba4df1e9fe93b9dd42435f6c45f DietPi scripts, change all references of `http://fuzon.co.uk` to `http://dietpi.com`
- :u6307: Point fuzon.co.uk to new VPS via ahost. Ensures existing fuzon.co.uk link references will still function, until they are phased out.
- :u6307: Update all dietpi.com links, to dietpi.com
- :u6307: Update all forum posts to dietpi.com instead of fuzon.co.uk
- :u6307: Update all other online documentation (rpi/odroid forums, SF etc) to dietpi.com instead of fuzon.co.uk
- :u6307: Power off the current fuzon.co.uk server thats been running on my home network. Take it upstairs, watch movies on it lol :)

**Comment by rhkean** [comment]
so, are you moving the forums from http://fuzon.co.uk/phpbb to http://dietpi.com/phpbb ?

**Comment by Fourdee** [comment]
`dietpi-survey` `dietpi-bugreport` now uploads to dietpi.com

**Comment by Fourdee** [comment]
@rhkean 
Yep, to start with will move the whole forums. Need to sort out a redirect from fuzon.co.uk to dietpi.com also, as documentation links `http://fuzon.co.uk/phpbb/` in DietPi wont be updated until users install v117.

Edit:
Made a progress tracky thingy https://github.com/Fourdee/DietPi/issues/294#issue-149490172. Will keep it updated. :)

**Comment by Fourdee** [comment]
ACP (/adm) is a little broken lol:
![image](https://cloud.githubusercontent.com/assets/7077026/14646917/5af09088-0653-11e6-8780-1a2dff8d50bb.png)

**Comment by rhkean** [comment]
do you still have a host for fuzon.co.uk ?

**Comment by Fourdee** [comment]
At the moment yes, its still running on home server/network, at least until the move is finished.

As I will need to redirect fuzon.co.uk to dietpi.com anyway (to ensure existing links throughout the web will still work), dietpi.com will be the new home of both dietpi.com and fuzon.co.uk (forums).

In the future i'll look into clean up the forums and separate the non-dietpi stuff somewhere else. Until then, another host for fuzon.co.uk is not needed.

**Comment by k-plan** [comment]
@Fourdee 

BTW: don't see it on your list, but the links on dietpi.com pointed for now as well to "http://fuzon.co.uk/phpbb/viewtopic.php?...."

And have a look for the sponsor image layout, displayed on mobile devices. 

![image-1](https://cloud.githubusercontent.com/assets/17237601/14685562/37a05658-0735-11e6-8903-cd4994888d12.jpg)

nice-looking and better fit  if it will be embed like raspberry-pi.jpg or odroid.jpg

No big deal and take one's time.

**Comment by Fourdee** [comment]
@k-plan 

> BTW: don't see it on your list, but the links on dietpi.com pointed for now as well to 

Good spot, missed that one :+1:. There's so many things to do lol. Added to list.

> And have a look for the sponsor image layout, displayed on mobile devices.

Yep, looks like we need to reduce the image size and set centre alignment. Thanks for letting me know :+1:

**Comment by k-plan** [comment]
> Yep, looks like we need to reduce the image size and set centre alignment.

So far I can see it from here, this will do your nice website template in one's own right, if choose the right "`<span class>`"

But take a look, if  have some peace and quiet. Yes, it's hard for  _workerholics_. :wink:
No worry, it works well on desktops.

**Comment by Fourdee** [comment]
@k-plan I couldn't figure out how to align centre with the template (html isn't my strength), but i've resized the image for now, should be better on mobile view :)

**Comment by xenfomation** [comment]
I'll gladly take a look at the HTML/CSS mark-up.  The IMG tag may be inheriting another class parameter or it's container may just neet a center/alignment adjustment.

Glad to be back into the world of non-book writing and while github is something I use for my own purposes, yeah -- I'm no pro at it -- but I'm sure we can suss something.  I will poke around to see what I can do with the centre necessity...

**Comment by k-plan** [comment]
@Fourdee 
yes, better. But it will be beautiful, to use the auto-scaling potential of your html5 template.

Let @xenfomation have look. Thanks for his offer. 👍

**Comment by Fourdee** [comment]
So its just the forums left now. Need to replace all `fuzon.co.uk` reference links with `dietpi.com`. 

If I can find a way to "find and replace" in SQL, I'll do it that way. If not, manually replacing and checking each forum post would be a nightmare. Although as `fuzon.co.uk` is also redirected to `dietpi.com`, theres no harm in leaving those old links as they are.

EDIT:
Done using sql export, find and replace, sql import.
`fuzon&#46;co&#46;uk` to `dietpi&#46;com`

**Comment by xenfomation** [comment]
No problem!  Just tying to sort out my account credentials and will reach out to @Fourdee to make sure he can point me to the right part of the branch.  Ah... this is the life!

**Comment by k-plan** [comment]
@Fourdee 

> So its just the forums left now.

No, no ...  😄 

Have a look on: https://github.com/Fourdee/DietPi/blob/master/README.md

Your testing is fine: https://github.com/Fourdee/DietPi/blob/testing/README.md

But really no big deal. 

BTW forum: Could you perhaps change this? (may puzzled some user)
http://fuzon.co.uk/phpbb/styles/dualcore/theme/images/logo.png

But only if you like to have dietpi-logo there. Corporate design colours of you website,  black and purple/violet/pink/magenta as well  be a looker for your forum design.
My favourite colour is indeed  blue, but ... 😉

**Comment by rhkean** [comment]
about the only way that I've found to find/replace in SQL would be:

# mysqldump -u root -p[root_password] [database_name] > dumpfilename.sql

then find replace on the sql file

then

# _mysql -u root -p[root_password] [database_name] < dumpfilename.sql_

**Comment by Fourdee** [comment]
@rhkean Yep, same method I used. :+1: 

@k-plan 

> Have a look on: https://github.com/Fourdee/DietPi/blob/master/README.md
> Your testing is fine: https://github.com/Fourdee/DietPi/blob/testing/README.md
> But really no big deal.

Testing > Master will be done when v117 is released :)

> BTW forum: Could you perhaps change this? (may puzzled some user)

Yep. I've been thinking about sticking DietPi logo in there. Will take a look.

> My favourite colour is indeed blue, but ..

Hehe, keeping the purple for now :)

**Comment by k-plan** [comment]
@Fourdee 

> Testing > Master will be done when v117 is released :)

Yep. 👍   I have notice, big coding is going on in the background,  so ..

> current fuzon.co.uk server power off and take it upstairs, watch movies on it lol :)

... your home cinema have to wait for a spell. :laughing:

**Comment by xenfomation** [comment]
Heads up for all -- thanks to @Fourdee I am using Firefox, FireFox Mobile Browser Test, and a Samsung Galazy S4.
- The sponsor image is inheriting responsive/css declarations in the Footer section and it's absolute size definition is all causing the slight RIGHT-JUSTIFIED bleed over

![sponsorcutoff](https://cloud.githubusercontent.com/assets/10519408/14877347/459af352-0cea-11e6-9e66-0ecaa9e4119a.png)
- There is a wrap around issue for the "Community Section's" button text: "Getting Started online documentation and"...

![community-360x640-wraparound](https://cloud.githubusercontent.com/assets/10519408/14877332/2113b7da-0cea-11e6-93b9-a0957ccdc57e.png)
- Testing at many variable sizes, I can isolate the button text issue to wrap and I can uncover other layout design values that attempt to ruin the GLORY of the site...

![oddsize-result](https://cloud.githubusercontent.com/assets/10519408/14877303/e0eef840-0ce9-11e6-99c0-972e9bb481b4.png)
- I should be able to isolate the inheritance size shortly -- before 07:00AM EST 28-APRIL-2016

Cheers!

**Comment by xenfomation** [comment]
Assigned to myself.  As the code will be sent directly to @Fourdee, I will highlight items I solved (great job on this, btw!)
1.  Issue with sponsor image occurs when resolution is <= 360x480; that is resolved
2. The img/link tab were nested within two classes.  Image style was not set to 100% max-width, so auto scaling from the responsive code could not do it's job
- Move link and img ref 1 level "further" from the copyright/li group; set style to max-width of 100%; RESOLVED

![correctedsponsor](https://cloud.githubusercontent.com/assets/10519408/14877502/8db5cf26-0ceb-11e6-8e7b-629d9d792868.png)
- Community Button's text was too long if wrap-text was used, the button doubled in size.  I shortened this text.  WORK AROUND.

![shortenedtext](https://cloud.githubusercontent.com/assets/10519408/14879487/8c756002-0cf7-11e6-84f9-0d7026578ad1.png)
- The extremely random sizes leave the Community Icons skewed -- this shouldn't happen due to some standards with mobile devices
- Emailing Dan and seeking his approval (for now until the next wave of super resolution promotes further updates)

Cheers

**Comment by xenfomation** [comment]
I sent two emails, @Fourdee -- the 28-APRIL-2016-04:48AM has the non-QA site as I originally sent the QA version.  Point is, all bases are covered unless we get reports from the end-users about skewing or any oddities none of us have seen (along with their monitor, resolution, etc).  All of this feeds back into the HTML->CSS:RESPONSIVE_PAGE flow.  If further work is desired, you know I'm for it and I will be available again this evening circa 20:00 EST.

**Comment by Fourdee** [comment]
@xenfomation 

The issue with alignment in the section "DietPi - features overview" has been there a while. To this day, I still dont know whats causing it lol.

I've uploaded your revised code (dietpi.com-28-APR-2016-FINAL_TEST.zip) to http://dietpi.com. Great work on this, looks much better :+1: :)

**Comment by Fourdee** [comment]
Marking this as closed. I will continue to work on the forum to add DietPi logo, in the future.

**Comment by xenfomation** [comment]
"One is happy to be of service" ;)

**Comment by k-plan** [comment]
@Fourdee 

https://github.com/Fourdee

![160527-0001](https://cloud.githubusercontent.com/assets/17237601/15603311/40e286a0-23fa-11e6-9885-60a48845ab34.gif)

**Comment by Fourdee** [comment]
@k-plan 
Bloody good spot :+1: Thanking you!

Updated :)

**Comment by Fourdee** [comment]
@k-plan 
Also, before I forget. I tried the DietPi logo with the current forum style weeks back, colours do not look right. So i had to revert it back to Fuzon logo. Most likely needs a new forum style to work with logo.
