### ISSUE TITLE
Install mpc along with mpd

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#2958]
Sometimes it's practical to use mpc, e.g. when one of the mpd clients (mympd, O!mpd etc.) fails for some reasons, can mpc be installed alongside mpd ?

**Comment by MichaIng** [comment]
@maartenlangeveld 
Jep you should be able to simply install it simply via APT. I am just not sure, since MPD runs as user "mpd", if you need to start mpc then as well via `sudo -u mpd mpc` to have the same home/XDG directories and possible included settings/flag files applied.

**Comment by maartenlangeveld** [comment]
@MichaIng 
Have installed mpc using apt, was only suggestion to automatically install when installing mpd. Works fine, anyway.

**Comment by MichaIng** [comment]
@maartenlangeveld 
Hmm yeah not sure, as most users seem to not require it, at least I couldn't find some related request on quick check. I would keep the install slim until further requests appear.

You could add it to https://feathub.com/MichaIng/DietPi/ and we'll see how much votes we get.

And I can add it to our online docs as a suggestion.
Does it work well just running it as root or any other user that has permissions?

**Comment by maartenlangeveld** [comment]
Seems to work well as root, but have not tried all possibilities. I needed mpc since I use also upmpdcli (DietPi) with Linn Kazoo (on Windows PC) as alternative to O!MPD and when playing radio Linn Kazoo sets 'single: on'... When returning to O!MPD it wouldn't play a whole album until I discovered that mpd single flag was set to 'on'. Needed mpc to set it back to off.

So not important and you're right that you want to keep DietPi install slim. I will close since not important at all. Thanks.

BTW upmpdcli works as a charm, can recommend.
