### ISSUE TITLE
DietPi-Update | RPi4 / beta: "Update" button in menu just exits 

### ISSUE THREAD

**Issue by adamgibbo** [MichaIng/DietPi#2960]
#### Solution: Run `dietpi-update 1`
- The issue has been solved with v6.25 release.
_______________
#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=24
G_DIETPI_VERSION_RC=1337
G_GITBRANCH='master'
G_GITOWNER='MichaIng'`
- Distro version | `Buster`
- Kernel version | `Linux DietPi 4.19.56-v7+ #1242 SMP Wed Jun 26 17:31:47 BST 2019 armv7l GNU/Linux`
- SBC device | `RPi 3 Model B+ (armv7l)`

#### Steps to reproduce

1. sudo dietpi-update
2. 
![image](https://user-images.githubusercontent.com/52538290/60671638-71d53c00-9e6b-11e9-9131-a31e4b8a3c57.png)
3. Can not proceed any further when selecting 'ok' just flashes and returns to the menu
4 . Following text is then showing when exiting:
![image](https://user-images.githubusercontent.com/52538290/60671878-05a70800-9e6c-11e9-8308-d84f9d7f1a20.png)

Any assistance would be appreciated.
Thanks

**Comment by MichaIng** [comment]
@adamgibbo 
Many thanks for your report.

Jep known issue with the beta code that the RPi4 testing image is based on. Please update by skipping the manu: `dietpi-update 1`
- It is resolved with v6.25

**Comment by adamgibbo** [comment]
@MichaIng `dietpi-update 1` has worked.
Many thanks

**Comment by MichaIng** [comment]
I will reopen an Pin, since all RPi4 and beta testers are affected.
