### ISSUE TITLE
dietpi-software command fails

### ISSUE THREAD

**Issue by soloza** [MichaIng/DietPi#2964]
#### Details:
- Date           | Sun  7 Jul 07:25:16 BST 2019
- Bug report     | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Debian mini.iso
- SBC device     | Native PC (x86_64) (index=21)
- Kernel version | #1 SMP Debian 4.9.144-3.1 (2019-02-19)
- Distro         | stretch (index=4)
- Command        | Connection test: http://security.debian.org
- Exit code      | 127
- Software title | DietPi-Software

#### Steps to reproduce:

1. ... run dietpi-software
2. ...

#### Expected behaviour:

- ... want to configure software i.e.uninstall app

#### Actual behaviour:

- ... 

#### Extra details:

- ... Internet connection is working 100%, have changed APT sources
![Pi_Error](https://user-images.githubusercontent.com/52619352/60765044-26ea3d00-a094-11e9-8dfb-57d31e20b9ab.jpg)

#### Additional logs:
```
Log file contents:
/DietPi/dietpi/func/dietpi-globals: line 1379: wget: command not found

**Comment by MichaIng** [comment]
@soloza 
Many thanks for your report.

You or something removed `wget`, which is an essential download utility for DietPi. To resolve: `G_AGI wget`

**Comment by soloza** [comment]
![wget](https://user-images.githubusercontent.com/52619352/60770335-3c825580-a0da-11e9-8545-f5584e9d3a58.jpg)
Hi.
Very strange as server has been running a week and have not changed anything.

ran
root@DietPi:~# G_AGI wget
[ INFO ] APT installation for: wget, please wait...
[  OK  ] G_AGI wget
root@DietPi:~#

But I get the exact sane error.

Also tried.

root@DietPi:~# apt-get install wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.18-5+deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Also:

root@DietPi:~# time wget --spider http://ftp.debian.org/debian/
-bash: wget: command not found

real    0m0.001s
user    0m0.000s
sys     0m0.000s
root@DietPi:~#

**Comment by MichaIng** [comment]
@soloza 
Ah good it is installed. Strange that the command is not found. Please try and paste:
```
which -a wget
hash -d
wget
```

**Comment by soloza** [comment]
root@DietPi:~# which -a wget
root@DietPi:~# hash -d
hits    command
   3    /usr/bin/which
   3    /bin/rm
   1    /usr/bin/mesg
   6    /usr/bin/apt-get
   2    /usr/bin/clear
root@DietPi:~# wget
-bash: wget: command not found
root@DietPi:~#

**Comment by soloza** [comment]
![wget2](https://user-images.githubusercontent.com/52619352/60770550-5e7cd780-a0dc-11e9-876e-7eecd80bae4c.jpg)

**Comment by MichaIng** [comment]
@soloza 
Very strange, please paste: `echo $PATH`

In case for whatever reason the binary was removed (manually), so if the $PATH variable is correct, a reinstall might solve it: `G_AGI --reinstall wget`

**Comment by soloza** [comment]
"G_AGI --reinstall wget" allowed me to get into dietpi-software again.

Thank you very much!

Saved me from re-installing the OS :)

**Comment by MichaIng** [comment]
@soloza 
Whatever removed the binary, good that it works now.

I mark this issue as closed, feel free to reopen if required.
