### ISSUE TITLE
Gitea download link is broken

### ISSUE THREAD

**Issue by tindecken** [MichaIng/DietPi#2965]
#### Required Information
- Diepi v6.25.3

#### Additional Information (if applicable)
- Software: Gitea

![image](https://user-images.githubusercontent.com/4727197/60769191-e8399e80-a0f6-11e9-827a-3554306e7f5f.png)

![image](https://user-images.githubusercontent.com/4727197/60769276-d99fb700-a0f7-11e9-89a7-2470e98138b2.png)

**Comment by MichaIng** [comment]
@tindecken 
Many thanks for your report. Known issue, see here for solution: https://github.com/MichaIng/DietPi/issues/2959

I already fixed this for future v6.25 updates, however a small number of early updaters are affected, sorry for that.

**Comment by tindecken** [comment]
Thank you for the information :)
