### ISSUE TITLE
diepi-cloudshell for xorg and cloudshell LCD screen

### ISSUE THREAD

**Issue by studioai** [MichaIng/DietPi#299]
Hi,

I was wondering there's a way to run dietpi-cloudshell on LCD while running Kodi on HDMI display for my cloudshell.

and I have found a answer and I posted it fuzon.

[http://fuzon.co.uk/phpbb/viewtopic.php?f=11&t=310](http://fuzon.co.uk/phpbb/viewtopic.php?f=11&t=310)

My modification on the script is
- Removing Configuration Codes : this causes crash on Xterm on LCD Screen
- Removing Option Parameter: modified version will run without the parameter '1'
- Added USB Storage 2 Information and Layout of storage info screen

and I also posted, xorg.conf and xorg autorun script for auto running on cloudshell LCD.

It works fine on my cloudshell. If you like it. Please test and add it on next update.

**Comment by Fourdee** [comment]
@studioai 
Great find and thanks for sharing :+1:
