### ISSUE TITLE
Update netdata to v1.1.0

### ISSUE THREAD

**Issue by WolfganP** [MichaIng/DietPi#300]
NetData released v1.1.0 5 days ago https://github.com/firehol/netdata/releases/tag/v1.1.0 , official tarfiles released at http://firehol.org/download/netdata/releases/v1.1.0

**Comment by rhkean** [comment]
Those tarballs are source code, not binaries.

But, I'll look over the changes when I get a moment.

**Comment by WolfganP** [comment]
Thx @rhkean I found a relevant discussion on debian packaging at https://github.com/firehol/netdata/pull/132 and https://github.com/firehol/netdata/issues/42

**Comment by rhkean** [comment]
Wow... I thought some of our Issue conversations were long.... LOL

looks like they're adding deb package builds.  that'll make it easier...  Probably won't get to it this week, though.

**Comment by Fourdee** [comment]
I'll grab this, its 1.2 currently. Time to get compiling:
:u6307: armv6
:u6307: armv7+
:u6307: arm64
:u55b6: x86_64 | Leaving this one out as netdata is disabled, and, seems pointless to monitor stats from within the emulated machine.

**Comment by Fourdee** [comment]
Netdata on RPi 1 really isnt a good idea (idle 900mhz) lol:
<img width="719" alt="untitled" src="https://cloud.githubusercontent.com/assets/7077026/16708832/da720b64-45f7-11e6-922d-c0e11d124221.png">

**Comment by Fourdee** [comment]
Completed: https://github.com/Fourdee/DietPi/commit/1ce2f5043133cd1a1f1481ba9a55affbbecdd21c
