### ISSUE TITLE
DietPi-Software | Re-check/remove rsyslog dependency from all software titles

### ISSUE THREAD

**Issue by PeterLacknase** [MichaIng/DietPi#3014]
#### Is your feature request related to a problem? Please describe:

unbound pulls rsyslog as (an unnecessary) dep, though ramlog is active.

#### Describe the solution you'd like:
 Dependency checks for superficial log daemons.

#### Describe alternatives you've considered:

`sudo apt-get purge rsyslog ;
sudo apt-get autoremove`

(The latter removes unnecessary remaining deps from rsyslog like libestr0, libfastjson4, liblognorm5.)

**Comment by MichaIng** [comment]
@PeterLacknase 
Thanks for your report.

I could not find unbound pulling rsyslog: https://packages.debian.org/stretch/unbound
Is this on RPi or non-RPi and which `echo $G_DISTRO`?

However generally DietPi-RAMlog and rsyslog do not conflict and purging rsyslog could purge dependants as well. Actually we should be more careful, the other way round, when enabling RAMlog not purging rsyslog, but instead do `apt-mark auto rsyslog; G_AGA` to only autoremove it, if nothing depends on it.

There is another open issue tangent to this topic btw: https://github.com/MichaIng/DietPi/issues/2454

My middle-term aim for this is the following:
- Remove rsyslog from our logging options completely, as it is an obsolete overhead on systemd systems, where journald is anyway running as in-RAM syslog daemon.
- rsyslog will then only be installed as dependency, if any 3rd party package depends on it. Is so, actually we should open a bug report to get all packages removing rsyslog from their deps list. Every modern Debian package should allow to use journald instead, if any system logs are required.
- As an alternative, when RAMlog is disabled, one will be able to select logrotate and select journald to be boot persistent. With this set, rsyslog is superseded in every use case 😉.

**Comment by PeterLacknase** [comment]
Thanks a lot, Micha! Maybe rsyslog was pulled earlier with OpenVPN. I did a clean install from buster testing Image and never installed rsyslog myself (willingly that is).


Raspberry Pi 3B+
Debian/Raspbian Buster 
DietPi 6.25.3

`echo $G_DISTRO` yields „5“.

**Comment by MichaIng** [comment]
@PeterLacknase 
Indeed, DietPi-Software itself installs rsyslog together with OpenVPN and some other software titles as well.

Before blaming package dependencies and 3rd party software, we should instead re-check those requirements first and in case remove or workaround this in DietPi-Software 😄.
__________
- [x] OpenVPN: #3016
- [x] PiVPN: https://github.com/MichaIng/DietPi/commit/e4672395838e43313768004491c8fc09c9ddf0c0
- [x] Webmin: https://github.com/MichaIng/DietPi/commit/ec55d49a488fd9cb1dbb18cbfa067b5d1d1a974e
Online docs adjusted: https://dietpi.com/phpbb/viewtopic.php?p=3047#p3047

🈴 CloudPrint (package dependency)
  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954309
  - https://github.com/davesteele/cloudprint-service/pull/58
  - Change committed to master/upstream, but will most likely never reach Debian Buster, for sure never Debian Stretch.
  - However Cloudprint does in the end of the year, hence no reason to start larger effort on this.

**Comment by MichaIng** [comment]
Removed from all software titles but CloudPrint. However the latter pulls it as APT dependency. I committed the removal of this dependency to upstream (see above) but it will likely never reach Debian repo anymore. Also not that CloudPrint will shutdown til the end of the year, so no reason to start larger efforts on this.

**Comment by MichaIng** [comment]
Dependency has been removed from newest version on Debian as well 👍: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954309
The new version `0.14-14` ~has not yet reached any repo suite~ **EDIT: reached Bullseye**: https://packages.debian.org/cloudprint
