### ISSUE TITLE
[FAILED] DietPi-Software | G_AGUG (11: Resource temporarily unavailable)

### ISSUE THREAD

**Issue by github619** [MichaIng/DietPi#3032]
#### Details:
- Date           | Sat  3 Aug 20:05:08 PDT 2019
- Bug report     | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi B (armv6l) (index=1)
- Kernel version | #1245 Fri Jul 12 17:20:08 BST 2019
- Distro         | buster (index=5)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. dietpi-software was installing a selection of packages in one ssh window
2. Start new ssh session and run htop

#### Actual behaviour:

- Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Comment by MichaIng** [comment]
@github619
Many thanks for your report.
There seems to be another APT command running.
Try "apt update", if it fails with the same error message, check "htop" for other apt it apt-get processes. Those need to finish, if handing, kill them by selecting from htop via up/down buttons and F9+return.
