### ISSUE TITLE
DietPi-Software | Netdata removed from stretch-backports repo

### ISSUE THREAD

**Issue by Velociraptor85** [MichaIng/DietPi#3062]
So I wanted to install Netdata on my Dietpi Nanopi Neo2 but apparently it is missing in the repository? Or at least it did not install and gave the following error.

#### Details:
- Date           | Sun 18 Aug 12:24:08 BST 2019
- Bug report     | N/A
- DietPi version | v6.25.3 (Fourdee/master)
- Img creator    | DietPi Core Team
- Pre-image      | FriendlyARM
- SBC device     | NanoPi NEO 2 (aarch64) (index=65)
- Kernel version | #82 SMP Fri Dec 8 14:33:14 CST 2017
- Distro         | stretch (index=4)
- Command        | G_AGI netdata
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:
1. dietpi-software
2. search - netdata
3. install

#### Expected behaviour:
- It should have been installed or dietpi-software should not find/offer the package if its not available

#### Actual behaviour:
- APT is being called but apparently it cant find netdata for the stretch distro

#### Extra details:
- before the dietpi-update from 6.14 to 6.25 netdata could be installed

#### Additional logs:
```
Log file contents:
E: Package 'netdata' has no installation candidate
```

**Comment by MichaIng** [comment]
@Velociraptor85 
Damn you are right. This was available via `stretch-backports` but obviously Debian removed it, why ever... https://packages.debian.org/search?keywords=netdata

The packages have already been removed from the pool server... 
Worst case is that we fallback to the older packages on our server (1.11.1) and hopefully find time to recompile to current version by times.
_____________
Or build from source: https://docs.netdata.cloud/packaging/installer/
But this might install a lot of pre-req dev packages and take a long time on slower SBCs. For x86_64 at least there are pre-compiled binaries available.

**Comment by liepumartins** [comment]
Meanwhile, how to workaround this?
I am trying to install allo GUI package, which tries to get netdata and fails. 
`dietpi-software install 159`

**Comment by MichaIng** [comment]
@liepumartins 
Okay I found the backport packages in Debian snapshots. The latest snapshot that still contains them is 2019-09-07 morning: https://snapshot.debian.org/archive/debian/20190709T042518Z/pool/main/n/netdata/
They were removed the next hours from official repo, for whatever was the reason 🤔.

Okay I wrapped the packages together. Worked for me on x86_64 machine. Lets see if this works for you on ARMv7 as well. Try:
```
cd /tmp
rm -Rf netdata*
wget https://dietpi.com/downloads/binaries/stretch/netdata_armv7l.7z
7zr x netdata_armv7l.7z
rm netdata_armv7l.7z
G_AGUP
dpkg -i netdata-{core,plugins-bash,web,}_*.deb # Error messages are expected here, fixed with the command below
G_AGF
```
Optionally you can as well install the Python and Node.js plugins, which show a bunch of additional charts for certain software titles:
- The Python plugin shows e.g. charts for Redis and MariaDB databases and some others. Most simply double with what the default bash-based plugins already show. So I would not install it as long as you don't have Python 3 installed anyway.
It requires some package version from backports. The following worked for me:
```
apt install python3-six python3-yaml python3-urllib3/stretch-backports
dpkg -i netdata-plugins-python_1.12.1-2_bpo9+1_all.deb
```
- The Node.js plugin installs fine, but this only makes sense if your have Node.js based software installed, AFAIK:
```
dpkg -i netdata-plugins-nodejs_1.12.1-2_bpo9+1_all.deb
```
#### Cleanup:
```
rm -Rf netdata*
```

**Comment by liepumartins** [comment]
@MichaIng thank You for quick response!

However,  I have an armv8 (NanoPi NEO2).

And I can live without netdata, I just want to install the allo GUI. If I could customize what packages it requires, that would be awesome. Since, in this case, I care only about audio (roon,gmrender,shairport,squeezelite) and the ability for user to configure settings via web GUI.

*EDIT*: sorry, now this looks like an other issue should have been filed.
*EDIT2*: I found the aarch64 packages. Had to manually install `libipmimonitoring5a`, but after that everything worked, thanks!

**Comment by MichaIng** [comment]
@liepumartins 
> Had to manually install `libipmimonitoring5a`

`G_AGF` did not install this package automatically?

**Comment by MichaIng** [comment]
Hmm there is a separate netdata repository: https://packagecloud.io/netdata/netdata/install#bash-deb
Will test this and probably add as default install method.

🈴 Fails with
> E: The repository 'https://packagecloud.io/netdata/netdata/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Needs to be forwarded to devs.
_______
Ah the stable repo does not yet contain packages, but the `-edge` repo does: https://packagecloud.io/netdata/netdata-edge/install#bash-deb

However the install is extremely heavy with full `cups` and stuff...
```
root@VM-Stretch:~# apt install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  cups cups-client cups-common cups-core-drivers cups-daemon cups-filters cups-filters-core-drivers cups-ppdc cups-server-common fontconfig-config fonts-dejavu-core freeipmi freeipmi-bmc-watchdog freeipmi-common freeipmi-ipmidetect
  freeipmi-tools ghostscript hicolor-icon-theme imagemagick imagemagick-6-common imagemagick-6.q16 libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libcairo2 libcap2-bin libcups2 libcupscgi1 libcupsfilters1 libcupsimage2
  libcupsmime1 libcupsppdc1 libdbus-1-3 libexpat1 libfftw3-double3 libfontconfig1 libfontembed1 libfreeipmi16 libglib2.0-0 libgomp1 libgs9 libgs9-common libicu57 libijs-0.35 libipmiconsole2 libipmidetect0 libipmimonitoring5a libjbig0
  libjbig2dec0 libjpeg62-turbo libjson-c3 libjudydebian1 liblcms2-2 liblqr-1-0 libltdl7 libmagickcore-6.q16-3 libmagickwand-6.q16-3 libnetfilter-acct1 libnspr4 libnss3 libopenjp2-7 libpaper1 libpixman-1-0 libpoppler64 libprotobuf-c1
  libprotobuf10 libprotoc10 libqpdf17 libsnappy1v5 libtiff5 libusb-1.0-0 libuv1 libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxml2 libxrender1 poppler-data poppler-utils ssl-cert
Suggested packages:
  cups-bsd foomatic-db-compressed-ppds | foomatic-db printer-driver-hpcups hplip cups-pdf smbclient xpp printer-driver-gutenprint antiword docx2txt ghostscript-x imagemagick-doc autotrace cups-bsd | lpr | lprng enscript ffmpeg gimp
  gnuplot grads graphviz groff-base hp2xx html2ps libwmf-bin mplayer povray radiance sane-utils texlive-base-bin transfig ufraw-batch xdg-utils libfftw3-bin libfftw3-dev liblcms2-utils libmagickcore-6.q16-3-extra fonts-japanese-mincho
  | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum openssl-blacklist
Recommended packages:
  avahi-daemon colord printer-driver-gutenprint cups-browsed liblouisutdml-bin | liblouis-bin gsfonts libmagickcore-6.q16-3-extra netpbm libpam-cap dbus libglib2.0-data shared-mime-info xdg-user-dirs fonts-droid-fallback libpaper-utils
  qpdf xml-core
The following NEW packages will be installed:
  cups cups-client cups-common cups-core-drivers cups-daemon cups-filters cups-filters-core-drivers cups-ppdc cups-server-common fontconfig-config fonts-dejavu-core freeipmi freeipmi-bmc-watchdog freeipmi-common freeipmi-ipmidetect
  freeipmi-tools ghostscript hicolor-icon-theme imagemagick imagemagick-6-common imagemagick-6.q16 libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libcairo2 libcap2-bin libcups2 libcupscgi1 libcupsfilters1 libcupsimage2
  libcupsmime1 libcupsppdc1 libdbus-1-3 libexpat1 libfftw3-double3 libfontconfig1 libfontembed1 libfreeipmi16 libglib2.0-0 libgomp1 libgs9 libgs9-common libicu57 libijs-0.35 libipmiconsole2 libipmidetect0 libipmimonitoring5a libjbig0
  libjbig2dec0 libjpeg62-turbo libjson-c3 libjudydebian1 liblcms2-2 liblqr-1-0 libltdl7 libmagickcore-6.q16-3 libmagickwand-6.q16-3 libnetfilter-acct1 libnspr4 libnss3 libopenjp2-7 libpaper1 libpixman-1-0 libpoppler64 libprotobuf-c1
  libprotobuf10 libprotoc10 libqpdf17 libsnappy1v5 libtiff5 libusb-1.0-0 libuv1 libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxml2 libxrender1 netdata poppler-data poppler-utils ssl-cert
0 upgraded, 87 newly installed, 0 to remove and 1 not upgraded.
Need to get 47.7 MB of archives.
After this operation, 171 MB of additional disk space will be used.
```

🈴 Bullseye repo is not yet available.
🈴 Buster: `netdata : Depends: libprotoc10 but it is not installable`
- Buster ships [libprotoc17](https://packages.debian.org/buster/libprotoc17)

However `171M` for a bunch of stuff that most will never need is not something we gonna offer. No idea why they don't ship a core package...
To compare:
```
root@DietPi:~# apt install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fonts-font-awesome fonts-glyphicons-halflings freeipmi-common libfreeipmi17 libipmimonitoring6 libjs-bootstrap netdata-core netdata-plugins-bash netdata-web
Suggested packages:
  freeipmi-tools fping
Recommended packages:
  netdata-plugins-nodejs netdata-plugins-python
The following NEW packages will be installed:
  fonts-font-awesome fonts-glyphicons-halflings freeipmi-common libfreeipmi17 libipmimonitoring6 libjs-bootstrap netdata netdata-core netdata-plugins-bash netdata-web
0 upgraded, 10 newly installed, 0 to remove and 8 not upgraded.
Need to get 3,888 kB of archives.
After this operation, 15.0 MB of additional disk space will be used.
```
- `15M`, that is how it should be, offering a very large amount of monitoring modules with web access. No idea why one want `cups` and all those libraries and dependencies as a strict addition...

**Comment by MichaIng** [comment]
PR merged: https://github.com/MichaIng/DietPi/pull/3091
To test, switch to dev branch:
```
# Optionally create a backup first to revert:
dietpi-backup 1
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=dev' /DietPi/dietpi.txt
dietpi-update 1
dietpi-software install 65
```

**Comment by Velociraptor85** [comment]
Is there a Fallback or rather how would I go back to the "default" branch?

Edit: Btw it works I checked with my NanoPi NEO 2

**Comment by liepumartins** [comment]
> @liepumartins
> 
> > Had to manually install `libipmimonitoring5a`
> 
> `G_AGF` did not install this package automatically?

Not 100% sure. But `dpkg -i netdata*.deb` failed without `libipmimonitoring5a` present.

**Comment by MichaIng** [comment]
@liepumartins 
Jep the dpkg command is expected to fail, if not yet all dependencies are installed. `G_AGF` == `apt-get -f install` fixes this by pulling all required dependencies automatically. So I hope when running both commands in a row, afterwards you should have the netdata process running, thus ip:19999 accessible from local machine. Note that you need to edit config to allow access from remote browser, check the online docs.
______
You can go back to default branch by restoring the backup. Theoretically you can also revert DietPi code to master branch, but I would not recommend, since some system/config changes might not be compatible.
```
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=master' /DietPi/dietpi.txt
```
will lead to dev updates are not shown, but only the next stable release.
