### ISSUE TITLE
DietPi Scripts need author's website updated

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#307]
As of current version & web presence moved to www.dietpi.com, the DietPi core scripts should be updated to reflect this:

Created by XXXXXXXXXXXX / yyyyyyy / dietpi.com

Will seek @Fourdee's thoughts for criticality, milestone, etc.

**Comment by Fourdee** [comment]
@xenfomation 

These changes are already in the testing branch. They will become live when v117 is released :)
commit https://github.com/Fourdee/DietPi/commit/9e2b3c85ada60ba4df1e9fe93b9dd42435f6c45f

**Comment by Fourdee** [comment]
I'll mark this as closed. v117 will be released today.
