### ISSUE TITLE
Choosing language for keyboard when installing looks wierd, the buster build for Rpi

### ISSUE THREAD

**Issue by bobby276070** [MichaIng/DietPi#3073]
Hi, please have a look at the menue for selecting language for keyboard, what I see when scrolling is in most cases a lot of black squares instead for specific language, in my case I was looking for Swedish, found a line named "Sweed" - Sweed is neither English or German for Swedish.

Another important point is that if I like to give a good password for root/dietpi and SW-setup, this has to take place after changing to the proper language of keyboard. Maybe have he choise of keyboard to use and activate, before the question of changing the passwords .. ?!

Many thanks Robert

**Comment by MichaIng** [comment]
@bobby276070 
Many thanks for your report.

Indeed a known issue with Debian Buster: https://github.com/MichaIng/DietPi/issues/2912
Sadly they did not fix it yet... I am wondering why this didn't get some priority BEFORE official Debian release. If one cannot read the keyboard menu and keys are assigned wrong, then this can break the whole Debian console usage...

Fix has been merged for a while already to upstream code, but package release does not yet include it...

**Comment by MichaIng** [comment]
I close this issue in favour of the other one. We cannot do much besides hoping for a soon solution from Debian. A custom workaround would be much work, which is rendered obsolete with a Debian-wise fix, we at least me not gonna do that 😉.
