### ISSUE TITLE
MD5 and SHA1 don't match the hash.txt

### ISSUE THREAD

**Issue by mbonne** [MichaIng/DietPi#3077]
### Creating a bug report/issue

Downloaded the current release of the VMware version from site: 
https://dietpi.com/downloads/images/DietPi_VMware-x86_64-Buster.7z

Ran a comparison check against the included files using the hash.txt in .7z file.

Comparing SHA1 values: DietPi_VMware-x86_64-Buster.vmdk - doesn't match.
The SHA1 from txt: a5444a3b425f578a905a5879a0ebe3d4be19856a
Your files Hash:  844d87bda28f04d640c15c79460fe23bba36a868

DietPi_VMware-x86_64-Buster.vmx matches up.
 Correct Hash:    ba42a6ea3ea158e423f836fd61fc1d010014107f
 Your files Hash: ba42a6ea3ea158e423f836fd61fc1d010014107f

Please advise.

[hash.txt](https://github.com/MichaIng/DietPi/files/3537621/hash.txt)

**Comment by MichaIng** [comment]
@mbonne 
Many thanks for your report.

I just checked and verified that vmdk hashes in `hash.txt` are wrong and I get the same SHA1 you got. Also checked the archive on server. Obviously a packaging mistake, perhaps a last-minute check/change and forgotten to redo the hashes.

This means you can safely use the image. I am currently repacking the archive with the correct hashes.
**EDIT: Done: https://dietpi.com/downloads/images/DietPi_VMware-x86_64-Buster.7z**

**Comment by mbonne** [comment]
Thanks for the prompt response.
🍻
