### ISSUE TITLE
DietPi for Xenserver

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#309]
> Test/release the DietPi for XenServer implementation created by @xenfomation (JK)

@xenfomation ^^ so i dont forget :)

**Comment by xenfomation** [comment]
Thanks for letting me do this, @Fourdee -- I am wrapping up the documentation as OpenSource XenServer is my primary virtualization environment.  The screenshot is from XenCenter, but I am working with the code base through SSH (of course)!
![xenserver-1](https://cloud.githubusercontent.com/assets/10519408/14945864/59d89c70-0fe7-11e6-9134-9f3d560dd253.PNG)

**Comment by xenfomation** [comment]
The native format for XenServer VM exports are XVA files.  Sparse disks, meaning efficient use of compacting the VM, and I have tested it within XenServer 6.2 and 6.5 -- works great.

**Comment by xenfomation** [comment]
Attached is an additional text - based on the mock-up I sent you previously - to explain where the XenServer resources are at.  That's all as to be blunt, the public documentation is sufficient enough and outside of scope to cover installing XenServer.  The additional information explains how to import the XVA file with XenCenter. 
[xenserverInstructions.txt](https://github.com/Fourdee/DietPi/files/244470/xenserverInstructions.txt)

**Comment by xenfomation** [comment]
@Fourdee  -- Of course it sounds like you are all over this, but if I have left anything unclear -- let me know and I shall grant thee access to my private XenServer if you want to see how sweet your sandbox/X64 environment runs (as it does else where)!

Yeah - seriously, no sucking up on my part.  Best part about this project?  I use it.  :-)

**Comment by Fourdee** [comment]
@xenfomation 

> Of course it sounds like you are all over this

Actually, not at the moment :). I didn't realise you can not run XenServer virtualization on a Windows system lol. I also dont have a x32/x64 system available to dedicate a installation.

> let me know and I shall grant thee access to my private XenServer

This would be ideal and I'd be greatful if we could make this happen. 
All i want to do is some basic tests with the image before its released. The VirtualBox image you did was spot on, so I cant see any issues, its just something I like to do with every image.

**Comment by xenfomation** [comment]
Completely understood!  Tomorrow first, EST, I you shall have full access!

**Comment by Fourdee** [comment]
@xenfomation 
Sending a "prod and poke" your way for Xenserver access :)

**Comment by xenfomation** [comment]
Don't blame you and thanks!!  Moved one of XenServers to my DMZ and will have that ready to go tonight. All you need will be XenCenter for XenServer 6.5 and the connection criteria.  Thanks!

**Comment by Fourdee** [comment]
@xenfomation 
Thanks :+1: . If you can email me details i'd appreciate it, I'am aiming to try it tomorrow.

**Comment by Fourdee** [comment]
Going to move this outside the milestone as there is no rush, and not critical to v118's release. Give me a bell when your ready @xenfomation :+1:

**Comment by xenfomation** [comment]
Thanks. The good news is that I have things ready to go for you, but your executive call gives us time to test your remote connection (three methods), etc. 

Thanks, @Foudree

**Comment by xenfomation** [comment]
@Fourdee  --  Tested download of image and import and all looks fantastic.

![import01](https://cloud.githubusercontent.com/assets/10519408/15446658/7d678fbc-1ef5-11e6-9fd8-5f63b38637a8.PNG)
![import02](https://cloud.githubusercontent.com/assets/10519408/15446655/7d632b34-1ef5-11e6-9a96-25196a0798ca.PNG)
![import03](https://cloud.githubusercontent.com/assets/10519408/15446656/7d647f02-1ef5-11e6-8f44-2b8e0910c0ed.PNG)
![import04](https://cloud.githubusercontent.com/assets/10519408/15446657/7d67489a-1ef5-11e6-9822-b3f9f603c0cf.PNG)

**Comment by Fourdee** [comment]
@xenfomation 
Excellent,, thanks for this :+1: 

I'll update the website/forums today and get this image released. Great work JK :+1:

**Comment by Fourdee** [comment]
@xenfomation 
Just need the "setup guide" for XenServer and the forums when you get a chance. Then we can close this ticket :+1:

**Comment by xenfomation** [comment]
Thanks for the patience, @Fourdee & @rhkean  --  most of what I am documenting can be found on XenServer's public, open source facing website ([http://xenserver.org/](http://xenserver.org/)).  However, I am consolidating this to explain what XenServer is, where documentation is available, and how to use the Windows-centric tool to import the XVA file.

**Comment by Fourdee** [comment]
Minus the missing documentation, making as closed.
