### ISSUE TITLE
webmin does not start after install

### ISSUE THREAD

**Issue by nnovaes** [MichaIng/DietPi#3096]
dietpi version 6.25.3

after install of webmin through dietpi-software:

root@DietPi:~# service webmin status
● webmin.service - Webmin (DietPi)
   Loaded: loaded (/etc/systemd/system/webmin.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-09-03 10:39:52 EDT; 5min ago
  Process: 882 ExecStart=/etc/webmin/start (code=exited, status=203/EXEC)

Sep 03 10:39:52 DietPi systemd[1]: Starting Webmin (DietPi)...
Sep 03 10:39:52 DietPi systemd[1]: webmin.service: Control process exited, code=exited status=203
Sep 03 10:39:52 DietPi systemd[1]: Failed to start Webmin (DietPi).
Sep 03 10:39:52 DietPi systemd[1]: webmin.service: Unit entered failed state.
Sep 03 10:39:52 DietPi systemd[1]: webmin.service: Failed with result 'exit-code'.
root@DietPi:~# 

root@DietPi:/var/log# cat daemon.log | grep web
Sep  3 10:39:52 DietPi systemd[882]: webmin.service: Failed at step EXEC spawning /etc/webmin/start: No such file or directory
Sep  3 10:39:52 DietPi systemd[1]: webmin.service: Control process exited, code=exited status=203
Sep  3 10:39:52 DietPi systemd[1]: webmin.service: Unit entered failed state.
Sep  3 10:39:52 DietPi systemd[1]: webmin.service: Failed with result 'exit-code'.
root@DietPi:/var/log#

**Comment by MichaIng** [comment]
@nnovaes
Many thanks for your report.
Looks like they switched the binary name or location.
**EDIT: Nope, it has not changed: https://github.com/webmin/webmin/blob/master/webmin-init#L22
Then something must have gone wrong with your install.
Can you paste: `ls -l /etc/webmin`**

Also there is a repository available now which we might apply instead of installing the package manually: https://doxfer.webmin.com/Webmin/Installation

**Comment by nnovaes** [comment]
> Can you paste: `ls -l /etc/webmin`**
> 
> Also there is a repository available now which we might apply instead of installing the package manually: https://doxfer.webmin.com/Webmin/Installation

there's no such directory ...

root@DietPi:/# ls -l /etc/webmin
ls: cannot access '/etc/webmin': No such file or directory

**Comment by nnovaes** [comment]
i've also tried to uninstall and reinstall through dietpi-software, no success.

**Comment by MichaIng** [comment]
@nnovaes 
Very strange, I could not replicate. Install works very well here. Especially strange, since download of the Webmin package and dpkg install are both error handled, so there is not really a chance this can fail without interactive error prompt.
I would need a full dietpi-software install output to check for suspicious/missing/error output.

However I switched our install script to use the official Webmin APT repo: https://github.com/MichaIng/DietPi/commit/ec55d49a488fd9cb1dbb18cbfa067b5d1d1a974e
Before attempting to debug the old install, please try first the new way manually:
```
curl -sSL 'http://www.webmin.com/jcameron-key.asc' | apt-key add -
echo 'deb https://download.webmin.com/download/repository sarge contrib' > /etc/apt/sources.list.d/webmin.list
G_AGUP
G_AGI webmin
```

I'll add a reinstall on next DietPi-Update as well to switch all users to the APT repo. It ships a newer version as well and there is no dependency reinstalled with it, so it's a pretty fast and safe reinstall/update.

**Comment by nnovaes** [comment]
same issue... when i run

> 
> curl -sSL 'http://www.webmin.com/jcameron-key.asc' | apt-key add -
> echo 'deb https://download.webmin.com/download/repository sarge contrib' > /etc/apt/sources.list.d/webmin.list
> G_AGUP
> G_AGI webmin

i get

> 
> ecting previously unselected package libapt-pkg-perl.^M
> paring to unpack .../4-libapt-pkg-perl_0.1.32_amd64.deb ...^M
> acking libapt-pkg-perl (0.1.32) ...^M
> ecting previously unselected package apt-show-versions.^M
> paring to unpack .../5-apt-show-versions_0.22.7_all.deb ...^M
> acking apt-show-versions (0.22.7) ...^M
> paring to unpack .../6-webmin_1.930_all.deb ...^M
> acking webmin (1.930) ...^M
> g: error processing archive /tmp/apt-dpkg-install-fgVF4k/6-webmin_1.930_all.deb
> unpack):^M
> able to open '/usr/share/webmin/quota/uninstall.pl.dpkg-new': Operation not
> mitted^M
> ors were encountered while processing:^M
> mp/apt-dpkg-install-fgVF4k/6-webmin_1.930_all.deb^M
> Sub-process /usr/bin/dpkg returned an error code (1)
> 
>

**Comment by MichaIng** [comment]
@nnovaes 
> Operation not
mitted

Did you run those commands as root user or with `sudo`/`G_SUDO` prefix?

**Comment by nnovaes** [comment]
yes, i did run as root

**Comment by MichaIng** [comment]
Please try to purge the old package first: `apt purge webmin`

**Comment by nnovaes** [comment]
same issue after running "apt purge webmin"

#### Details:
- Date           | Tue 17 Sep 14:46:56 EDT 2019
- Bug report     | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Debian mini.iso
- SBC device     | Virtual Machine (x86_64) (index=20)
- Kernel version | #1 SMP Debian 4.9.144-3.1 (2019-02-19)
- Distro         | stretch (index=4)
- Command        | G_AGI webmin
- Exit code      | 100
- Software title | 

#### Additional logs:
```
Log file contents:
(Reading database ... 41699 files and directories currently installed.)
Preparing to unpack .../archives/webmin_1.930_all.deb ...
Unpacking webmin (1.930) ...
dpkg: error processing archive /var/cache/apt/archives/webmin_1.930_all.deb (--unpack):
 unable to open '/usr/share/webmin/gray-theme/samba/images/askepass.gif.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/webmin_1.930_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MichaIng** [comment]
@nnovaes 
Not the same issue, but now a different file: `/usr/share/webmin/quota/uninstall.pl.dpkg-new` vs `/usr/share/webmin/gray-theme/samba/images/askepass.gif.dpkg-new`.

Lets see how this files meta data look like:
```
stat /usr/share/webmin/gray-theme/samba/images/askepass.gif.dpkg-new
```

Does `dmesg` report any error? Having random files missing and random changing access issues could mean some drive I/O issues, although I see it's a VM 🤔. However I tried it on all my VMs and didn't face any issue any of them (neither with old manual deb install, nor with new repo install), so its a system specific issue, not a general/method one.

Also force some file system check on reboot, just in case. Is this VirtualBox, VMware or something else?

**Comment by MichaIng** [comment]
I close this issue due to missing reply. Feel free to reopen if required, although it indeed looks like something went wrong with download/extraction/storing of files, probably disk corruption.
