### ISSUE TITLE
Beta branch lags behind master at release points

### ISSUE THREAD

**Issue by CollinChaffin** [MichaIng/DietPi#3099]
I have noticed (now as perfect example), that those wanting to test the latest beta to stay at least AT or above master regularly at release time do not realize they are stuck BEHIND master.

As example, there was a 6.26 release in master (current).  Before the release, all was good but AT the point of the release, master appears to have additional commits that BETA does not.

My current beta version:  6.25.3 (up to date)
Current available master: 6.26

My suggestion is that until the 1st beta arrives after each release to ensure that the BETA branch gets all the commits to still bring it to the same version (by actual fixes and version number) as master.  So in this case, I would then be on version 6.26, yet still on BETA branch not missing the final release fixes.

Thoughts?  Thanks!

**Comment by MichaIng** [comment]
@CollinChaffin 
master is not on v6.26. There is a single hotfix commit that does not effect any end-user code, but was our image creation. Not sure, was more an accident that this commit is named "v6.26".

The version string is generally defined in this file:
- Beta: https://github.com/MichaIng/DietPi/blob/beta/dietpi/server_version-6
- Master: https://github.com/MichaIng/DietPi/blob/master/dietpi/server_version-6
- So beta is identical to master currently, aside of this one non end-user relevant hotfix for image creations.

**Comment by MichaIng** [comment]
I mark this issue as closed. Feel free to reopen if any questions left.
