### ISSUE TITLE
Formatting SSD drive failed on Rpi4

### ISSUE THREAD

**Issue by tjamaa** [MichaIng/DietPi#3106]
#### Required Information
- Date                | Thu 12 Sep 12:03:42 BST 2019
- Bug report      | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator     | DietPi Core Team
- Pre-image       | Raspbian Lite
- SBC device      | RPi 4 Model B (armv7l) (index=4)
- Kernel version | #1245 SMP Fri Jul 12 17:31:45 BST 2019
- Distro              | buster (index=5)
- Command       | parted -s /dev/sda mklabel gpt
- Exit code         | 1
- Software title  | DietPi-Drive_Manager

#### Steps to reproduce
1. I formatted the Crucial MX500 1TB SSD drive on a windows machine as ntfs
2. I than plugged the drive in the USB3.0 port of my Rpi4
3. the drive was properly recognized as /dev/sda
    fdisk output: /dev/sda1      932G  205M  932G   1%  /mnt/ssd
4. I could read and write to the disk still formatted as ntfs
5. I then ran dietpi-diskmanager to format /dev/sda/ as ext4

#### Expected behaviour
Successful ext4-formatted drive, to be mounted as /dev/sda1.

#### Actual behaviour
DietPi-Drive_Manager output:
umount: /dev/sda1: not mounted.
[ INFO ] DietPi-Drive_Manager | Writing zeros to partition: /dev/sda1
[  OK  ] DietPi-Drive_Manager | dd if=/dev/zero of=/dev/sda1 bs=4K count=10
umount: /dev/sda1: not mounted.
[ INFO ] DietPi-Drive_Manager | Writing zeros to partition table: /dev/sda
[  OK  ] DietPi-Drive_Manager | dd if=/dev/zero of=/dev/sda bs=4K count=1337
[ INFO ] DietPi-Drive_Manager | Creating partition table, with target type: gpt
[FAILED] DietPi-Drive_Manager | parted -s /dev/sda mklabel gpt

 DietPi has encounted an error, and is unable to continue 
[FAILED] DietPi-Drive_Manager | Unable to continue, DietPi-Drive_Manager will now terminate.

#### Extra details
At one time the drive seemed to work, but I had stability issues. 
I then resorted to the "steps to reproduce" described above.
Possibly the SSD drive is defective (although brand new, and 
properly working under windows).
By the way, a normal 2.5inch sata drive worked fine on the Rpi4 for several weeks

#### Additional logs:
Log file contents:
Error: Error opening /dev/sda: No such device or address

**Comment by MichaIng** [comment]
@tjamaa
Many thanks for your report.

Do you power the SSD via dedicated power supply or via USB only? In letter case the RPi only offers a maximum current across all USB ports of 1.2A with max USB current enabled, else even only 0.6A. Although in case of RPi4 this needs verification.
However that would explain sudden disconnects as appeared during format.

Since the other steps went through, you could try to reconnect and run the partition table creation manually: `parted -s /dev/sda mklabel gpt`

**Comment by tjamaa** [comment]
Thanks a lot for your feedback/ You were right indeed: when the SSD drive was connected via a powered hub the problem went away and formatting proceeded without issues. Still strange though, since the current use by the SSD drive is below the maximum current available from the USB port, according to googled info.. I will double-check the power supply of the Rpi4! In any case the problem is solved. Thanks again, also for the great work you do on Dietpi!

**Comment by MichaIng** [comment]
Great, thanks for feedback. Yeah probably some power peaks or USB voltage fluctuations are the reason. Generally I would always power 2.5" drives externally on SBCs.
