### ISSUE TITLE
NetData package failed to deploy

### ISSUE THREAD

**Issue by TDelux** [MichaIng/DietPi#3116]
#### Details:
- Date           | Wed 18 Sep 09:41:48 EDT 2019
- Bug report     | N/A
- DietPi version | v6.25.3 (Fourdee/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | Rock64 (aarch64) (index=43)
- Kernel version | #1 SMP Thu Oct 12 09:14:48 UTC 2017
- Distro         | stretch (index=4)
- Command        | G_AGI netdata
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
E: Package 'netdata' has no installation candidate
```

**Comment by MichaIng** [comment]
@TDelux 
Many thanks for your report.

Please have a look here for the solution, otherwise DietPi v6.26 will as well fix it: https://github.com/MichaIng/DietPi/issues/3062#issuecomment-524880146

**EDIT: Since you run an aarch64 machine, replace the `armv7l` from the commands with `aarch64`.**
