### ISSUE TITLE
shairpoirt-sync include alac support?

### ISSUE THREAD

**Issue by seniorgod** [MichaIng/DietPi#3117]
Dear all,

this is more a question than a feature request... 

Is shairport-sync compiled with support for ALAC (libalac) or not? 

best regards
seniorgod

**Comment by MichaIng** [comment]
@seniorgod 
Oh, sadly I cannot answer this since the binaries were compiled by Fourdee some time ago and not by me. I will ask him, however easiest is to simply try it out.

But if ALAC support needs to be explicitely enabled via build option/variable, then I guess it was not done.

**Comment by seniorgod** [comment]
ok, i had built lib alac and mid by myself.
thanks
