### ISSUE TITLE
How can I create a modified image of DietPi on a Linux box I can only access over SSH?

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#3118]
Hello,

I bought a NanoPi NEO2 recently and wanted to put my modified version of DietPi with some extra software on it. I also want to use the imager to create a backup image if I ever mess up anything in the future and I need to reflash.

I can only access the NEO2 over Ethernet SSH. I don't have any soldering tools or wire so I can't access it over serial. How would I go about creating a custom DietPi image for my NEO2 without serial access?

**Comment by MichaIng** [comment]
@LemonLime3 
SSH should be generally sufficient. It only breaks when you do radical network adjustments, install (or remove) one of the high level network manager or such. But even this can be worked around when having network-related changes done on reboot only.

So boot up the regular image (or use DietPi-PREP script to convert any Debian-based image into DietPi). Install your custom code/software, reboot, assure that everything works as expected, shutdown, unplug + clone SDcard.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
