### ISSUE TITLE
DietPi-Software Raspberry | not required HTTP server

### ISSUE THREAD

**Issue by AlexanderBykin** [MichaIng/DietPi#3120]
#### Is your feature request related to a problem? Please describe:
Yes, when install DietPi on Raspberry i haven't choice to don't install any HTTP server

#### Describe the solution you'd like:
Add option to do not install HTTP server

#### Describe alternatives you've considered:
...

#### Additional context
...

**Comment by MichaIng** [comment]
@AlexanderShniperson 
Note that the chosen webserver preference is not installed, as long as you don't choose any other software title that actually requires a webserver. It is just a preference that will be respected in case required. But yeah, maybe we should make this point clearer right from the main menu? The dialog after selecting the preference however is very clear IMO?
> Webserver Preference Changed:
>
> Apache2 has been selected as your webserver preference.
>
> When you select any software for install that requires a webserver, DietPi will automatically install your preferred choice (Apache2).

**Comment by AlexanderBykin** [comment]
Hi, looks like i somehow missed this note, yes it is clear

**Comment by MichaIng** [comment]
@AlexanderShniperson 
We'll add a desktop preference as well soon, which will behave similar then. When doing this we'll assure that the result/handling of this selection is very clear right from the main menu.

**Comment by MichaIng** [comment]
Okay I mark this as closed then. Feel free to reopen if required.
