### ISSUE TITLE
NodeRED not working on VM?

### ISSUE THREAD

**Issue by Phil1988** [MichaIng/DietPi#3122]
**Required Information**

    DietPi version |
    G_DIETPI_VERSION_CORE=6
    G_DIETPI_VERSION_SUB=25
    G_DIETPI_VERSION_RC=3
    G_GITBRANCH=master
    G_GITOWNER=MichaIng

    Distro version | stretch

    Kernel version | Linux DietPi 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

    SBC device |
    Virtual Machine (x86_64)

**Description**

I am using dietpi on a VM with following programs installed:
pi-hole
nextcloud
letsencrypt
blynk server
LASP (blynk wanted it I think...)
LAMP
Home Assistant
NodeRED

I just installed NodeRED and wanted to access the website with the port number 1880 (as specified [here](https://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=80#p4292) )

Sadly there is nothing.
I also checked the installation folder /mnt/dietpi_userdata/node-red but its empty.

Do I have to install more to get this working?

**Comment by MichaIng** [comment]
@Phil1988 
Many thanks for your report.

Jep known issue with v6.25: https://github.com/MichaIng/DietPi/issues/2975

Please do:
```
mkdir -p $G_FP_DIETPI_USERDATA/node-red
usercmd='useradd -rMU'
getent passwd nodered &> /dev/null && usercmd='usermod'
$usercmd -d $G_FP_DIETPI_USERDATA/node-red -s $(command -v nologin) nodered
getent group gpio &> /dev/null && usermod -aG gpio nodered
echo 'nodered ALL=NOPASSWD: ALL' > /etc/sudoers.d/nodered
chown -R nodered:nodered $G_FP_DIETPI_USERDATA/node-red
systemctl restart node-red
```
