### ISSUE TITLE
DietPi on Tinkerboard (Sorry, re-Etching solved the problem)

### ISSUE THREAD

**Issue by wimdirks** [MichaIng/DietPi#3134]
### Creating a bug report/issue
I just downloaded and installed the latest version for Tinkerboard: 
20190821-tinker-board-linaro-stretch-alip-v2.0.11.img
and discovered that in 2 files in directory /etc/apt/apt.conf.d
the last line has a missing semicolon.
Giving errors during install.
Hope this helps,
Wim Dirks

**Comment by MichaIng** [comment]
@wimdirks 
This was not one of our images, was it? Our official image is Debian Buster-based and from earlier date, named `DietPi_v6.25_ASUSTB-ARMv7-Buster.img`.

However as you managed to solve it via re-flashing, I will mark this as closed.
