### ISSUE TITLE
missing closing quote in boot_xu4.ini

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#314]
```
# Mac address configuration
setenv macaddr "00:1e:06:61:7a:72
```

macaddr should have a closing quote

**Comment by Fourdee** [comment]
@rhkean 
Good spot on this :+1: 

Although, not sure if its a bug as it doesn't seem to have any negative effect. Either that, or we somehow got lucky and away with it lol

I'll leave the "Labels" on this one down to you :)

**Comment by rhkean** [comment]
the labels for the changelog?
or for "are we calling it a bug?"

**Comment by rhkean** [comment]
How's that?  :laughing:

**Comment by Fourdee** [comment]
@rhkean 
lol, epic :+1:

**Comment by Fourdee** [comment]
Will mark this as closed Rob.
