### ISSUE TITLE
DietPi-Software | Jellyfin

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#3152]
Ref:
- https://dietpi.com/phpbb/viewtopic.php?f=12&t=5581
- https://dietpi.com/phpbb/viewtopic.php?f=9&t=6221
- https://dietpi.com/phpbb/viewtopic.php?f=9&t=6437

Vote for it on FeatHub: https://feathub.com/MichaIng/DietPi/+63

**Comment by Duchesst** [comment]
Would be great since its open source

**Comment by davidjmorin** [comment]
Still waiting to see this gem in your OS

**Comment by MichaIng** [comment]
Will be the next software title I implement, in case no-one is faster. I added v6.31 milestone 🙂.

**Comment by MichaIng** [comment]
Initial PR up: #3687

**Comment by MichaIng** [comment]
Hey guys, what is the maximum (or current) Jellyfin cache dir size you get? I'm considering moving it to RAM (`/run/jellyfin/`) by default to speed things up and reduce SD writes. But if the size is in the hundred MiBs, It causes an issue on low RAM devices. Also a reboot means empty cache then, not sure about the effect on larger video libraries, e.g. thumbs view and such.

For now cache dir is moved to `/mnt/dietpi_userdata/jellyfin/cache` so at least it can be easily moved to an external drive or is already there.

**Comment by brunoro** [comment]
I'd like to test this! How should I proceed? I'm currently running DietPi 6.31.2

**Comment by Joulinar** [comment]
You would need to switch to DEV branch and update your system to DEV v6.32

DEV Branch on an existing installation:

1. **Recommended**: Backup your system with `dietpi-backup` (or backup quickly with dietpi-backup 1)
2. Run the following command to switch to 'dev' branch:
`G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=dev' /boot/dietpi.txt`
3. Run `dietpi-update` to update the system, then reboot.

**Comment by brunoro** [comment]
@Joulinar I tried setting my `DEV_GITBRANCH` to both `beta` and `dev`, but both of them seem to be at 6.31.2

**Comment by brunoro** [comment]
here's the `dietpi-update` output:
```
[  OK  ] DietPi-Update | Using update server: https://raw.githubusercontent.com/MichaIng/DietPi/beta/dietpi/server_version-6
[  OK  ] DietPi-Update | No update required, your DietPi installation is already up to date:
[ INFO ] DietPi-Update | Current version : v6.31.2 (branch: MichaIng/master)
[ INFO ] DietPi-Update | Latest version  : v6.31.2 (branch: MichaIng/beta)
```

**Comment by Joulinar** [comment]
pls set to `dev` branch and run `dietpi-update -1`. This should reload dev scripts to your system

**Comment by MichaIng** [comment]
Ah yes we did not yet raise the version string, `dietpi-update -1` is correct then.

**Comment by brunoro** [comment]
Thanks, got it working now! No problems with jellyfin so far. Are there any specifics I should be testing for?

**Comment by MichaIng** [comment]
Thanks for testing! Not really something specific to test, but if you find something about the implementation, dirs/locations or default config or such that could be enhanced, that would be great to know.

Ah, when you added your media so that it's somehow production size, it would be interesting to know how big `/mnt/dietpi_userdata/jellyfin/cache` can grow, e.g.
```
du -sm /mnt/dietpi_userdata/jellyfin/cache
```
I was thinking to either move it to RAM by default or add some option to allow that. Especially when dietpi_userdata has not been moved to external drive but is on a SD card, such data are not great placed there.

**Comment by brunoro** [comment]
That doesn't seem to be a concern, at least in my install. The cache folder has mostly resized images and some text metadata. I have around 600GB of data in my jellyfin media library and the cache folder currently has 58M.

**Comment by MichaIng** [comment]
Okay indeed it might not matter that much then since the thumbs are only created a single time.
