### ISSUE TITLE
Unable to locate package grub-efi-amd64grub-efi-amd64-signed

### ISSUE THREAD

**Issue by timocapa** [MichaIng/DietPi#3166]
Converting Debian 9.9.0 (x86_64) to DietPi Buster (beta)

#### Steps to reproduce

1. Install Debian 9.9.0 (I used netinstall without any packages) in a VM
2. Run PREP, choose Beta and Buster
3. Wait

#### Expected behaviour

- Installs fine

#### Actual behaviour

- 
![image](https://user-images.githubusercontent.com/22844613/67000976-19077780-f0d9-11e9-946b-19a10d13d71d.png)

#### Extra details

- This is a VM from FreeNAS, which uses bhyve as hypervisor.
- I believe this isn't a system issue, but a source or script issue.

E: Yeah, it's trying to install "grub-efi-amd64grub-efi-amd64-signed", it's missing a space between.

E2: Workaround / fix is adding an extra space before grub here.

https://github.com/MichaIng/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L814

**Comment by MichaIng** [comment]
@timocapa 
Jep indeed, I just fixed it: https://github.com/MichaIng/DietPi/commit/5bd0d7735e34050e78b3448e5e532b058e477b9a

Backport into master: https://github.com/MichaIng/DietPi/commit/c426a4af851fb6f44aeeaf9e40695d8a0ad42c61

Many thanks  for reporting!

**Comment by MichaIng** [comment]
I mark this as closed since solved for dev and master branch. Feel free to reopen if required.
