### ISSUE TITLE
Dietpi-update 404 error

### ISSUE THREAD

**Issue by ictinc** [MichaIng/DietPi#32]
Hi Fourdee,
Since about a week it seems not possible anymore to run the dietpi update script on my rpi2. 
I'm able to ping the host so it doesn't seem like a local network issue.

D I E T - P I | 05:43 | Sun 07/12/2015                                                                                               ───────────────────────────────────────                                                                                              V75 | Raspberry Pi 2 (1GB)                                                                                                           ───────────────────────────────────────                                                                                              DietPi-Update: Checking for DietPi updates, Please wait...                                                                                         --2015-07-12 05:43:02--  https://raw.githubusercontent.com/Fourdee/DietPi//dietpi/server_version                                     Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.43.133                                                     Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.43.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found                                                                                2015-07-12 05:43:06 ERROR 404: Not Found.                                                                                            root@rpi2:~#

Kind regards,

Ronald

**Comment by Fourdee** [comment]
Hi ictinc,

Many thanks for the bug report. Apologies for the delay (was moving house).

Could you please run dietpi-bugreport and follow the onscreen instructions. This will give me more information on your system, and, help me debug the issue your experiencing.

Kind Regards,
Dan

**Comment by ictinc** [comment]
Hi Dan,

Thanks for your reply, no worries for the delayed response.

I've sent you a bug report as requested which was filled under eference number;
b827eb55b259-0

Kind regards,

Ronald

**Comment by Fourdee** [comment]
Hi Ronald,

Many thanks for the bug report. I've checked through your settings. It appears at some point, your device wasnt shut-down correctly (eg: power cut). Because of this, some of your settings have been corrupted.

A patch to prevent the above from occurring will be available in the next release (v78).
https://github.com/Fourdee/DietPi/pull/33

Kind Regards
Dan

**Comment by Fourdee** [comment]
We have released the update that will stop this from occurring  https://github.com/Fourdee/DietPi/pull/35. Unfortunately, if you have the 404 error currently, this will need to be patched manually.

See here for details: http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=39&p=131#p131
