### ISSUE TITLE
Longterm DB Considerations - MySQL vs MariaDB

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#320]
Low priority foreward thinking.

MariaDB 5.5 is a "replacement/equivalent" to MySQL 5.5.  Beyond MySQL 6.x and despite my own resources, has there been consideration to <gulp> drop MySQL anytime this year/next?

I want to be clear this is not to limit options for DietAdmin's, but to toss an idea out based on the seemingly aggresive ramp for MariaDB (it's all the same, but MySQL is just so "personal" :8ball: )

Cheers!

**Comment by Fourdee** [comment]
@xenfomation 

> has there been consideration to drop MySQL anytime this year/next?

We will continue to offer both MySQL and MariaDB as options in webserver stacks. All comes down to user preference and letting them choose.

I'll mark this as closed, please reopen if required.
