### ISSUE TITLE
DietPi-Software | Update Shairport binaries

### ISSUE THREAD

**Issue by kmplngj** [MichaIng/DietPi#3216]
Hi,

would it be possible to get a Shairport Update? 

There are some nice bugfixes and support for MQTT in the new release.

Thanks
Jan

**Comment by MichaIng** [comment]
@kmplngj 
Many thanks for your request. I'll see if I find time to dig into this compilation. Which SBC do you own, hence which architecture are you able to test the binary on?

**Comment by kmplngj** [comment]
Thanks. I could test on the RaspberryPi 3.

**Comment by MichaIng** [comment]
@kmplngj 
I was in mood to compile them as package, ready for testing: #3428
Changelog: https://github.com/MichaIng/DietPi/pull/3428/commits/8b2baf60c53b96789b051b28f797faaa58647dfa

For RPi Raspbian Buster:
```
cd /tmp
wget https://dietpi.com/downloads/binaries/buster/shairport-sync_armv6l.deb
apt-get -y install ./shairport-sync_armv6l.deb
rm shairport-sync_armv6l.deb
```

ARMv7+ARMv8 binaries are still missing but on the way 😉. However for RPi the ARMv6 ones will work fine.
___________
Lol dammit, now I see you mentioned the MQTT support. I didn't enable that compiling flag... Saw it too late as it is not yet documented on the main GitHub page 😅. However, if this is really wanted, compilation is not too time consuming as I wrote a script for this, hence I can redo those packages 😉.

**Comment by MichaIng** [comment]
MQTT support has been added with the latest package updates. Install procedure same as above.
