### ISSUE TITLE
DietPi-Software | Allo Web Gui - Upgrade from 6.18 to 6.26 => "Login failed"

### ISSUE THREAD

**Issue by Heroldgray** [MichaIng/DietPi#3264]
- Using USBridge ALLO Sparky SBC (armv7l - Linux DietPi 3.10.38 #22 SMP PREEMPT Fri Dec 22 10:45:41 IST 2017 armv7l GNU/Linux)
- Flashed ALLO Web Gui image  downloaded from: https://dietpi.com/downloads/images/DietPi_SparkySBC-ARMv7-Stretch_AlloGUI.7z
- DietPi upgrade process (6.18 > 6.26)
- Result: "Login failed" in ALLO Web GUI login page.(ALLO seems aware of this issue: https://audiophilestyle.com/forums/topic/32132-allo-sparky-usbridge/?do=findComment&comment=1012005).

#### Extra details
Using SSH console (dietpi-config etc ..) under 6.26 is OK as a workaround but, unfortunately, Web GUI unusable. Thank's for your work.

**Comment by MichaIng** [comment]
@Heroldgray 
Many thanks for your report. I'll have a look to get this fixed. Since the Allo web GUI was worked on by @Fourdee I cannot guarantee to be able to fix it for v6.27 already, as long as it needs to be fixed in its own code.

**Comment by MichaIng** [comment]
Issues solved with: https://github.com/MichaIng/DietPi/commit/61ccd94abb77e06fe18689081dd1d061f79a89a6

To solve now:
```
chown -R www-data:www-data /var/www/allo
chmod -R 770 /var/www/allo
chpasswd <<< 'allo:allo'
```

**Comment by Heroldgray** [comment]
> To solve now:
> chown -R www-data:www-data /var/www/allo
> chmod -R 770 /var/www/allo

Thank's @MichaIng !
I've tried your quick fix (chown / chmod) under 6.26.3 but unfortunately still "login failed" on web GUI after reboot.

- Some logs to monitor ?
- Would you advise me to reinstall Allo Gui (160) ?

**Comment by MichaIng** [comment]
@Heroldgray 
Okay, so it was not just me. Please try:
```
chpasswd <<< 'allo:allo'
```

The user is definitely created with this password, not sure if the web GUI changes something about that somehow, when failing 🤔.
_________
Further testing:
```
usermod -p 'allo' allo
```
breaks it again 🤔. Mysterious, no special characters inside, but it fails as well when trying to log in manually with password "allo" then...
... ahh, the given string is taken as encrypted... quite important to know, same for `useradd`...

Okay `chpasswd` is the right thing to go with.
Resolved with: https://github.com/MichaIng/DietPi/commit/1dfa7575b06ea8c5ef07a7143571205a052b89d0

**Comment by Heroldgray** [comment]
> Please try:
> chpasswd <<< 'allo:allo'

Bingo !
Thank's @MichaIng

**Comment by MichaIng** [comment]
@Heroldgray 
Great, thanks for testing!
