### ISSUE TITLE
Transmission Client Permission Denied Error

### ISSUE THREAD

**Issue by AdamF100001** [MichaIng/DietPi#3274]
#### Required Information

root@DietPi:~# #!/bin/bash
root@DietPi:~# G_DIETPI_VERSION_CORE=6
root@DietPi:~# G_DIETPI_VERSION_SUB=26
root@DietPi:~# G_DIETPI_VERSION_RC=3
root@DietPi:~# G_GITBRANCH='master'
root@DietPi:~# G_GITOWNER='MichaIng'

DietPi v6.26.3
Device model : RPi 4 Model B (armv7l)

#### Additional Information (if applicable)
- Software title | Transmission Client
software installed freshly
- Can this issue be replicated on a fresh installation of DietPi?

Bug report sent, reference code: acfeb6c1-f9bc-4ee9-a5aa-972f3aca413e
#### Steps to reproduce

1. Start a torrent download.
2. Then the Error Permission denied (/mnt/ will be shown in the client.

#### Expected behaviour

- ... The torrent should successfully download. 

#### Actual behaviour

- ... Torrent download not successfully completing 

#### Extra details

full error string

Permission denied (/mnt/USB256GB/downloads/Brassic.S01E02.1080p.HDTV.x264-LiNKLE[rarbg]/Brassic.S01E02.1080p.HDTV.x264-LiNKLE.m
- ...
![Capture](https://user-images.githubusercontent.com/59096769/71280676-d3269400-2353-11ea-8fe2-74f2f0f6b9ad.PNG)

**Comment by MichaIng** [comment]
@AdamF100001 
The user must be member of the `dietpi` group to have full R/W access to the downloads dir. I guess you have a custom user account? Then do:
```
usermod -aG dietpi <username>
```

**Comment by Fourdee** [comment]
@AdamF100001 

Thanks for the bug report and moving from Twitter.

Quick check of bug report, everything appears fine, just a permissions mishap somewhere.

Based on @MichaIng , @AdamF100001 copy and paste these commands:
```
systemctl stop transmission-daemon
sync
usermod -aG dietpi debian-transmission
chmod 775 -R /mnt/dietpi_userdata/downloads
chown -R debian-transmission:dietpi /mnt/dietpi_userdata/downloads
systemctl restart transmission-daemon
```

Then check Transmission web page for errors.

**Comment by MichaIng** [comment]
Is it about the server or the client? The server service starts with `Group=dietpi` and `usermod -aG dietpi debian-transmission` is part of the install process. With 775 permissions on download dir this should be sufficient, it is with my tests.

But when using some CLI/GUI client (https://transmissionbt.com/) one must probably take care those permissions. Ahh but now I see it's about the web interface, which is part of the server install. Sorry for misunderstanding 😉.
___________
Just tested again, works fine. When using a custom dir (not /mnt/dietpi_userdata or the one moved via dietpi-drive_manager), the following should be sufficient:
```
chmod 775 /mnt/USB256GB/downloads
chown :dietpi /mnt/USB256GB/downloads
```
- This does not change owner, but group only and allows dietpi group R/W access, which includes media players and Sonarr/Radarr etc access, when installed via dietpi-software.
- `/mnt/dietpi_userdata/downloads` however should have correct permission, even when moved to external drive 🤔.

**Comment by AdamF100001** [comment]
I have just checked my transmission client. It is still displaying the same permission denied error as before.

**Comment by AdamF100001** [comment]
> 
> 
> Is it about the server or the client? The server service starts with `Group=dietpi` and `usermod -aG dietpi debian-transmission` is part of the install process. With 775 permissions on download dir this should be sufficient, it is with my tests.
> 
> But when using some CLI/GUI client (https://transmissionbt.com/) one must probably take care those permissions. Ahh but now I see it's about the web interface, which is part of the server install. Sorry for misunderstanding wink.
> 
> Just tested again, works fine. When using a custom dir (not /mnt/dietpi_userdata or the one moved via dietpi-drive_manager), the following should be sufficient:
> 
> ```
> chmod 775 /mnt/USB256GB/downloads
> chown :dietpi /mnt/USB256GB/downloads
> ```
> 
>     * This does not change owner, but group only and allows dietpi group R/W access, which includes media players and Sonarr/Radarr etc access, when installed via dietpi-software.
> 
>     * `/mnt/dietpi_userdata/downloads` however should have correct permission, even when moved to external drive thinking.

I have ran the following commands

chmod 775 /mnt/USB256GB/downloads
chown :dietpi /mnt/USB256GB/downloads

I will keep you posted.

**Comment by AdamF100001** [comment]
its still the same issue & error.

**Comment by MichaIng** [comment]
@AdamF100001 
Which file system is it, probably it does not support UNIX permissions?
```
df -T /mnt/USB256GB
ls -l /mnt/USB256GB # Erase/rephrase any private date
```

Ah and btw, if its on the same files, my commands only changed the downloads directory permissions but not for any sub directory or contained file that existed already. It should have been better:
```
chmod -R 775 /mnt/USB256GB/downloads
chown -R :dietpi /mnt/USB256GB/downloads
```
`-R` means to include all contained files/dirs **r**ecursively.

**Comment by AdamF100001** [comment]
> 
> 
> @AdamF100001
> Which file system is it, probably it does not support UNIX permissions?
> 
> ```
> df -T /mnt/USB256GB
> ls -l /mnt/USB256GB # Erase/rephrase any private date
> ```
> 
> Ah and btw, if its on the same files, my commands only changed the downloads directory permissions but not for any sub directory or contained file that existed already. It should have been better:
> 
> ```
> chmod -R 775 /mnt/USB256GB/downloads
> chown -R :dietpi /mnt/USB256GB/downloads
> ```
> 
> `-R` means to include all contained files/dirs **r**ecursively.

I have ran all the commands above & rebooted my pi.

please see terminal screenshot.

![Untitled1](https://user-images.githubusercontent.com/59096769/71423720-27e34b00-2683-11ea-867e-547943820eb3.png)

**Comment by MichaIng** [comment]
@AdamF100001 
Okay, file system is `ext4`, which is fine. Owner of the one dir is `777`? Probably a removed user name? However should not really matter since dietpi group has R/W access on them, although probably transmission does not like invalid owners.
Please try `chown -R dietpi <dir_name>` on that dir with user `777`, if this is the downloads dir?

Btw I guess you erased the directory names from the screen, since they should be just on the right side of the modification time/year?

**Comment by AdamF100001** [comment]
I think the error has been resolved. I am currently downloading a Linux distro. I will seed this torrent for 24 hours if there are no issues, this thread can be closed.

Thanks for the help & support.

**Comment by AdamF100001** [comment]
> 
> 
> @AdamF100001
> Okay, file system is `ext4`, which is fine. Owner of the one dir is `777`? Probably a removed user name? However should not really matter since dietpi group has R/W access on them, although probably transmission does not like invalid owners.
> Please try `chown -R dietpi <dir_name>` on that dir with user `777`, if this is the downloads dir?
> 
> Btw I guess you erased the directory names from the screen, since they should be just on the right side of the modification time/year?

I think the error has been resolved. I am currently downloading a Linux distro. I will seed this torrent for 24 hours if there are no issues, this thread can be closed.

Thanks for the help & support.

**Comment by AdamF100001** [comment]
Please close this thread as the issue has been resolved. Thanks

![Capture1](https://user-images.githubusercontent.com/59096769/71519250-a7089700-28ae-11ea-9c19-f49595c28991.PNG)

**Comment by Fourdee** [comment]
@AdamF100001 

Thank you Adam, and for the donation :heart: :+1: 

Great to hear its now working, i'll mark this as closed, however if the issue reoccurs, please reopen this ticket, then I will arrange a remote connection allowing us to do a speedy resolve.
