### ISSUE TITLE
6.27 bug if you updated "to soon"? 2x Backports Install zip? No zip? Please clarify

### ISSUE THREAD

**Issue by GvY85** [MichaIng/DietPi#3307]
I updated to 6.27 1 hour after it was released.
Now i see there is some fix(es) out there?

There are now two close "Backport Download_Install zip to target fix " (#3302 & #3303) but i cant find the zip fix anywhere?

I did apply this fix:
sed -i 's/target="-d \$target"/target="-d\$target"/' /DietPi/dietpi/dietpi-software 

Is that all and will the rest be fixed in 6.28 or? Please clarify a bit

Also, the 6.27 master now has a 6.28 dietpi-software in it :)

**Comment by MichaIng** [comment]
@GvY85 
Those backports are included in current master/release zips. Yes not best practice as early updaters do not have those fixes now. Although, If you have MOTD enabled in your DietPi terminal banner, those were applied for you as well. I just wanted to prevent as much users as possible from running into this bugs quickly.

However I'll wrap up a tiny v6.28 bugfix release now to include all those little fixes for all users and have a consistent code across systems again.

**Comment by MichaIng** [comment]
v6.28 is out, I mark this issue as closed.
