### ISSUE TITLE
DietPi-Software | Rethink user data directories

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#334]
Just brainstorming.

Currently its:

```
/mnt/usb_1 #dedicated usb install
/root #SD card only
```

We need to change where we store user data for `/root`, some programs have issues with accessing it, even if we apply the correct permissions. A static global location in /mnt would be ideal.
eg:

```
/mnt/DietPi-UserData
```

Then we can use symlinks to point usb drive.
Using a single location will make installation code simpler, and the online documentation. eg: where is my files ? `/mnt/DietPi-UserData`

**Comment by k-plan** [comment]
@Fourdee 

a go from my side, if allow for me to say this,

> Using a single location will make installation code simpler,

:100: 

Idea;
- if done, a option via menu to move the file to usb drive or a usb drive partitoin (eg. sda2) and point back to `/mnt/DietPi-UserData` 
  (for running system, not only clean installations)

Future;
- support for UUID
-  moving rootfs from sd-card to usb devices, like armbian  `nand-sata-install.sh`  
  (for running system, not only clean installations)

**Comment by xenfomation** [comment]
I agree and say, sorry for the delay on the disk by uuid as I am finalizing code for dual USB mounts. 

Thanks for your patience.  Crazy week and every inch I can get into DietPi had been a warm reprieve.

**Comment by Fourdee** [comment]
Ok, so the new Userdata location is `/mnt/dietpi_userdata` for both USB drive and Flash storage. This will only take effect for new installations in DietPi-Software. Existing installed software will use the previous location/s.

If the user has a USB drive, a symlink will be created. All data that exists in `/mnt/dietpi_userdata` will be copied to USB drive beforehand:

```
                        USERDATA_DIRECTORY="/mnt/dietpi_userdata"
            # - Copy any existing data to usb drive, if it is not a symlink already.
            if [ -d "$USERDATA_DIRECTORY"] && [ ! -L "$USERDATA_DIRECTORY" ]; then

                # - stop all running services. As this is done in apply_configs sections, its probably unessacary, but lets be safe.
                /DietPi/dietpi/dietpi-services stop
                cp -R "$USERDATA_DIRECTORY"/* /mnt/usb_1/

            fi

            # - Create symlink
            rm -R "$USERDATA_DIRECTORY"
            ln -sf /mnt/usb_1 "$USERDATA_DIRECTORY"

```

If user has a custom directory set in dietpi.txt (or via menu), that will be used instead:

```
        local dietpi_userdata_basedirectory=$(cat /DietPi/dietpi.txt | grep -m1 'dietpi_userdata_basedirectory=' | sed 's/.*=//')
        if [ "$dietpi_userdata_basedirectory" != "Auto" ]; then
            USERDATA_DIRECTORY="$dietpi_userdata_basedirectory"


```

Just need to test it.

**Comment by Fourdee** [comment]
Tests fine.

> note to self: When moving data from flash to usb drive, add a check to ensure all data is copied over before removing the folder and creating the symlink.

**Comment by Fourdee** [comment]
Completed.
