### ISSUE TITLE
error after Nextcloud installation

### ISSUE THREAD

**Issue by Ewies** [MichaIng/DietPi#3345]
Hello I restarted the system after a Nextcloud installation but then the system no longer starts up.

I can only access it via a screen and keyboard.

I get that as a root login error...

-bash: /DietPi/dietpi/func/dietpi-globals: Datei oder Verzeichnis nicht gefunden
[FAILED] DietPi-Login | Failed to load DietPi-Globals. Skipping DietPi login scripts...

What can I do now?

**Comment by MichaIng** [comment]
@Ewies 
Many thanks for your report.

Obviously the RAMdisk failed to initialise. Is this on an RPi? Please always fill the bug report template when reporting issues 😉.

However please paste the following command outputs (or photo from screen, what is handy for you), which should give a clue:
```
journalctl -u boot.mount
journalctl -u DietPi.mount
journalctl -u dietpi-ramdisk
tail -4 /var/tmp/dietpi/logs/dietpi-ramdisk.log
```

**Comment by Ewies** [comment]
I have now completely reinstalled the system, so unfortunately I can no longer deliver these issues.

Thanks anyway
