### ISSUE TITLE
[SOLVED] The update process couldn't proceed, because the PiHole blacklisted 'raw.githubusercontent.com' as update source.

### ISSUE THREAD

**Issue by LeatherMolly** [MichaIng/DietPi#3358]
New Issue - 25.01.2020 - While the update process, an error ocured and said I should post a ticket here.
The blue lines to post:
#### Details:
- Date           | Sat 25 Jan 15:22:07 CET 2020
- Bug report     | 9e7b7f07-aa5c-4ea8-8c32-0be03c112593
- DietPi version | v6.26.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (ID=3)
- Kernel version | Linux DietPizza 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
- Distro         | buster (ID=5)
- Command        | Connection test: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
- Exit code      | 4
- Software title | DietPi-Set_software

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Spider mode enabled. Check if remote file exists.
--2020-01-25 15:21:27--  https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 192.168.178.31
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|192.168.178.31|:443... failed: Connection refused.


 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Installing new DietPi code

######################################################################################################################################################################################################### 100.0%
[  OK  ] DietPi-Update | Unpacking update archive
[  OK  ] DietPi-Update | Installing new DietPi scripts to RAMdisk
[  OK  ] DietPi-Update | Installing new DietPi system files to disk
[  OK  ] DietPi-Update | Setting execute permissions for DietPi scripts
[ SUB1 ] DietPi-Set_software > verify_dietpi.txt ()
[FAILED] DietPi-Set_software | Connection test: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
[ INFO ] DietPi-Set_software | If problems persist, please report at https://github.com/MichaIng/DietPi/issues for investigation.
[FAILED] DietPi-Set_software | Connection test: https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi.txt
[ INFO ] DietPi-Set_software | If problems persist, please report at https://github.com/MichaIng/DietPi/issues for investigation.
[ INFO ] DietPi-Bugreport | Packing upload archive, please wait...
[  OK  ] DietPi-Bugreport | Connection test: ssh.dietpi.com
[  OK  ] DietPi-Bugreport | Bug report sent, reference code: 9e7b7f07-aa5c-4ea8-8c32-0be03c112593

**Comment by Joulinar** [comment]
Hi,
these 2 lines looks quite strange to me
```
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 192.168.178.31
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|192.168.178.31|:443... failed: Connection refused.
```

Looks like `raw.githubusercontent.com` is resoled as `192.168.178.31`. But 192.168.178.x is a privat network. I guess you home network. Usually used by Internet Router like FritzBox.

**Comment by LeatherMolly** [comment]
Hi Joulinar,

I am running DietPi with PiHole and did not really change much of the original settings, as I am more or less a beginner in this sphere.
I found the problem, the little nice PiHole buddy blacklisted 'raw.githubusercontent.com', so I couldn't reach the site. After whitelisting it, the 'dietpi-update' command could proceed.
So thanx for the hint.
LeatherMolly

**Comment by Joulinar** [comment]
Ok yep that could happen, thx for update. I will close the issue.
