### ISSUE TITLE
DietPi-Drive_Manager | Support glusterfs mounts

### ISSUE THREAD

**Issue by Sudrien** [MichaIng/DietPi#3374]
#### Is your feature request related to a problem? Please describe:
- `glusterfs` mount type (distributed filesystem) is not preserved, when opening `dietpi-drive_manager`.

#### Describe the solution you'd like:
- https://github.com/MichaIng/DietPi/pull/2729 style preservation

#### Additional context

- https://github.com/MichaIng/DietPi/issues/2078
- /etc/fstab line looks like 
> 127.0.0.1:/gv0 /mnt/gluster_gv0 glusterfs rw,defaults,_netdev 0 0

**Comment by MichaIng** [comment]
@Sudrien 
Many thanks for your request and PR #3375. Looks all perfectly fine 👍.
Changelog: https://github.com/MichaIng/DietPi/commit/0c0ed9db79f9bcbd7988e1730baac64d244fd209
