### ISSUE TITLE
Cannot remove Xserver

### ISSUE THREAD

**Issue by bugmaschine** [MichaIng/DietPi#3384]
#### Details:
- Date           | Sat 15 Feb 11:57:47 CET 2020
- Bug report     | 30e3b511-95ac-4b3d-8465-6b9df23603d3
- DietPi version | v6.28.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 4 Model B (armv7l) (ID=4)
- Kernel version | Linux DietPi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Distro         | buster (ID=5)
- Command        | G_AGP xorg* xserver-xorg* x11-* xinit xcompmgr xterm xfonts-base
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:
1. Uninstall Xserver

#### Expected behaviour:
- It should remove the programs

#### Actual behaviour:
- it doesn't remove the programs

#### Extra details:
- I did the removing via ssh

#### Additional logs:
```
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by MichaIng** [comment]
@Crasher124 
Many thanks for your report. Yeah I recognised this when creating images where desktop is preinstalled. Can you please run the following and paste output:
```
apt purge $(dpkg --get-selections | mawk '{print $1}' | grep '^(xorg|xserver-xorg|x11-|xinit$|xcompmgr$|xterm$|xfonts-base$')
```

**Comment by bugmaschine** [comment]
Here is the output
![Anmerkung 2020-02-15 151322](https://user-images.githubusercontent.com/38097264/74589449-c34ec780-5005-11ea-8d6b-4322656576e5.png)

**Comment by MichaIng** [comment]
@Crasher124 
Whoopsie, forgot the extended regex option for grep:
```
apt purge $(dpkg --get-selections | mawk '{print $1}' | grep -E '^(xorg|xserver-xorg|x11-|xinit$|xcompmgr$|xterm$|xfonts-base$')
```

**Comment by bugmaschine** [comment]
![Anmerkung 2020-02-15 151322](https://user-images.githubusercontent.com/38097264/74589621-15dcb380-5007-11ea-8728-e0562d101aa3.png)

Is this better?

**Comment by MichaIng** [comment]
@Crasher124 
Still a syntax error, damn thing that APT itself does not silently ignore non-installed packages 😄:
```
apt purge $(dpkg --get-selections | mawk '{print $1}' | grep -E '^(xorg|xserver-xorg|xinit$|xcompmgr$|xterm$|xfonts-base$|x11-xserver-utils$|x11-utils$|x11-xkb-utils$)')
```
I just recognised that x11-common is required for the Java package (if installed), hence this must not be purged. I adjusted the pattern above.

**Comment by bugmaschine** [comment]
It worked thanks 😃

**Comment by MichaIng** [comment]
@Crasher124 
Finally, great. Running this does not mark Xserver as uninstalled within `dietpi-software`, however it is practically uninstalled 😉. You could mark it manually:
```
sed -i '/aSOFTWARE_INSTALL_STATE\[6\]=2/aSOFTWARE_INSTALL_STATE\[6\]=0/' /DietPi/dietpi/.installed
```

Ah, there will be some dependency packages left. You can purge them via: `G_AGA`

**Comment by bugmaschine** [comment]
I did run the command but it is still in dietpi software. It's not important to have it not anymore listed,
But thanks for the help. 😃

**Comment by MichaIng** [comment]
@Crasher124 
I need to better review my commands :sweat_smile: it's (missed `s` above to do the actual replacement):
```
sed -i 's/aSOFTWARE_INSTALL_STATE\[6\]=2/aSOFTWARE_INSTALL_STATE\[6\]=0/' /DietPi/dietpi/.installed
```
_________
I mark this issue as closed then, the following commit should fix the issue in most cases: https://github.com/MichaIng/DietPi/commit/d8b4979c77a571359d0295594866bbbd198850e2#diff-d92a6ee04e02fd2a2dc23d5bec3e6a98
