### ISSUE TITLE
DietPi-Software | Pi-hole: Add version 5 support

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3391]
Just testing Pihole v5 (beta), in order to add domains (blacklist, whitelist) through pihole's web interface, user 'www-data' needs to be part of 'pihole' group.

**Comment by MichaIng** [comment]
@maartenlangeveld 
Many thanks for your report. Yes indeed there is also some more testing and tweaking required/possible with v5. I'll do that the next days, the new `pihole` group is already good to know.

**Comment by maartenlangeveld** [comment]
Hi Michael,


With pleasure.

Have also tested your new NanoPi NEO2 buster dietpi image but cannot get my NanoHatOLED working... Seems that I2C is not supported in the Buster build (works well with strech build). Is there a solution?


Many thanks & kind regards,

Maarten

**Comment by MichaIng** [comment]
@maartenlangeveld 
Many thanks for testing. Could you please try to edit `/boot/armbianEnv.txt` and add:
`i2c0` to the overlays line, so it should look like this:
```
overlays=usbhost1 usbhost2 i2c0
```
There is also an `i2c1` overlay available, not sure which one uses which pins.
And if you don't use Docker, add the following as new line as well, which should lead to minor performance enhancements:
```
docker_optimizations=off
```

**Comment by maartenlangeveld** [comment]
@MichaIng 

That works! Thanks again for your truly great support !!

**Comment by Joulinar** [comment]
just for reference regarding PiHole v5

https://discourse.pi-hole.net/t/error-message-attempt-to-write-a-readonly-database/27092/17

`usermod -a -G pihole www-data`

**Comment by MichaIng** [comment]
@Joulinar 
Jep many thanks. Will run some further tests the next days, I think there are more things that should be adjusted for Pi-hole v5 compatibility.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/b90b49fe701546da69f87b10de6f70e6009b5cb0
Changelog: https://github.com/MichaIng/DietPi/commit/d5a44d0151fa1ccec311be9a54418d0013d95d2b

**Comment by Joulinar** [comment]
@MichaIng 
I guess it will impact new installation only? Right?
What about existing installation? Should we do anything on it as well?

**Comment by MichaIng** [comment]
@Joulinar 
Good point. We can check on update if dietpi group exists and in case add www-data user to it.

**Comment by MichaIng** [comment]
Pi-hole v5 as well depends on PHP intl module now: https://github.com/MichaIng/DietPi/commit/c18f6c66d9ab24f6259faaf04fb85b21c91b2c04

**Comment by MichaIng** [comment]
v5 compatibility guaranteed with next DietPi-Update: https://github.com/MichaIng/DietPi/commit/9dc959687c4a9eaf1c46a7716809f3897d842f3a

**Comment by Joulinar** [comment]
@MichaIng 
I tested 2 scenario on my Buster VM

1. upgrade from v6.28 to v6.29 with an already existing PiHole installation
2. install new PiHole on v6.29

Both are working fine and PiHole 5 was working ootb after upgrade.

**Comment by MichaIng** [comment]
@Joulinar
That is great, many thanks for testing.

**Comment by mistakenideas** [comment]
Tested upgrading from DietPi 6.28 to 6.29 on RaspberryPi B Rev 1. Only really running Pi-Hole 4 on this which I then [switched to the Pi-Hole 5 Beta branch](https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/). All seems to be running okay so far.

**Comment by MichaIng** [comment]
@mistakenideas 
Many thanks for testing ❤️.
