### ISSUE TITLE
Dietpi: problem with DNS???

### ISSUE THREAD

**Issue by carminerodio86** [MichaIng/DietPi#3404]
#### Details:
- Date           | Sat 29 Feb 12:51:12 GMT 2020
- Bug report     | 75cb8204-fbcc-42d8-9602-a1fa0af7447e
- DietPi version | v6.28.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B (armv7l) (ID=3)
- Kernel version | Linux DietPi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
- Distro         | buster (ID=5)
- Command        | ping -c 1 -W 5 one.one.one.one
- Exit code      | 2
- Software title | DietPi-Login

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
ping: one.one.one.one: Name or service not known
```

**Comment by carminerodio86** [comment]
These are my Network configurations. Internet test ran with success.
 Ethernet     : Available | [On] | Connected                   │
│                WiFi         : Available | [On] | Disconnected                │
│                Onboard WiFi : [On]                                           │
│                             ●─ Additional Options ──────────●                │
│                IPv6         : [On]                                           │
│                Prefer IPv4  : [On]                                           │
│                Proxy        : [Off]                                          │
│                Test         : [Success] | Online

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. pls can you try to do the following

`ping -4 -c 1 one.one.one.one`

**Comment by carminerodio86** [comment]
root@DietPi:~ ping -4 -c 1 one.one.one.one
ping: one.one.one.one: Name or service not known
root@DietPi:~

**Comment by Joulinar** [comment]
what about `ping 1.1.1.1` or `ping 8.8.8.8`

**Comment by carminerodio86** [comment]
64 bytes from 8.8.8.8: icmp_seq=3 ttl=47 time=130 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=59 time=23.9 ms

**Comment by Joulinar** [comment]
and `ping google.com`

**Comment by carminerodio86** [comment]
64 bytes from lhr35s11-in-f14.1e100.net (216.58.206.78): icmp_seq=3 ttl=46 time=77.9 ms
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 49.224/59.932/77.887/12.774 ms

**Comment by Joulinar** [comment]
so you are unable to resolve host name of `one.one.one.one` which is quite strange as this is part of Cloudflares DNS Server. It is the globally available DNS Name for Cloudflares 1.1.1.1 DNS resolver:

https://www.dnswatch.info/dns/dnslookup?la=en&host=1.1.1.1&submit=Resolve

Anyway if you like to change the connection check setting, you can do as follow. 

Do `nano /DietPi/dietpi.txt` and search for the following 2 lines:

```
# General connection and DNS testing
# - IP to ping when checking network connectivity. Default: 1.1.1.1 (Cloudflare DNS, should be very fast world-wide)
CONFIG_CHECK_CONNECTION_IP=1.1.1.1
# - Domain to ping when checking DNS resolver. Default: one.one.one.one (Cloudflare DNS domain, see above)
CONFIG_CHECK_DNS_DOMAIN=one.one.one.one
```
you can change it to `8.8.8.8` and `google.com`

as well you cold try to disable IPv6. Sometimes this helps.

BTW: do you use a local DNS server or a public one?

**Comment by carminerodio86** [comment]
Ok. Now it seems working fine. First I was unable to start the software installation, but now the problem seems overcome. You have been very good and helpful. Thank you very much

**Comment by Joulinar** [comment]
Did you changed something on config files or was it just working fine now without any change done?

**Comment by carminerodio86** [comment]
I resolved applying your two indications (changing 1.1.1.1 and one.one.one.one in 8.8.8.8 and google.com rispectively)

**Comment by Joulinar** [comment]
ok good. At least ist fix now.

But would be good to find out why you are not able to resolve `one.one.one.one`. Maybe it's blocked by your DNS Server/Provider.

**Comment by MichaIng** [comment]
Strange indeed that 1.1.1.1 is reachable but the related domain name not. The "one" top level domain is relatively new (2015) which might be a reason for some outdated DNS caches: https://en.m.wikipedia.org/wiki/.one_(domain)

Another reason to not use Cloudflare as default for connection and DNS tests at all.

**Comment by Joulinar** [comment]
@MichaIng 
Which is a pity as Cloudflare is one if the best and fastest DNS providers atm

**Comment by MichaIng** [comment]
Jep world-wide average the fastest :cry:.
