### ISSUE TITLE
DietPi-Software | Node.js v13 fails on ESXi Buster VM

### ISSUE THREAD

**Issue by borpin** [MichaIng/DietPi#3408]
#### Required Information
- DietPi version | `cat /DietPi/dietpi/.version`
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=28
G_DIETPI_VERSION_RC=0
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
10.3
- Kernel version | `uname -a`
Linux DietPi 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
- SBC device | `echo $G_HW_MODEL_DESCRIPTION` or (EG: RPi3)
ESXI VM x86_64
- Power supply used | (EG: 5V 1A RAVpower)
VM - 240V
- SDcard used | (EG: SanDisk ultra)
Nil

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud) Node-Red
- Was the software title installed freshly or updated/migrated? Fresh install clean VM
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `sed -n 5p /DietPi/dietpi/.hw_model`

#### Steps to reproduce

1. `diepi-software install 122`

#### Expected behaviour

- Node-Red should install

#### Actual behaviour

- There is an Illegal Instruction error

#### Extra details

- Please see discussion [Cannot install Node-Red on VM](https://dietpi.com/phpbb/viewtopic.php?f=11&t=7325)

- Node-Red state that V12 is the most recent supported version of nodejs - DietPi installs V13
- The Raspbian install script installs V12 of nodejs.
- Installing V12 manually and then fooling DietPi into thinking nodejs is installed (edit out the execution of the install script in dietpi-software), Node-Red installs successfully with the `dietpi-software` command.

Whilst I accept that some setups do work with V13, as V12 is the supported version, that is the version that should be installed by DietPi.

**Comment by borpin** [comment]
I have just used the official NR install script (commented out the DietPi check) and node-red successfully installed (as user `dietpi`).

**Comment by MichaIng** [comment]
@borpin 
Many thanks for your report. Yes there are other cases where lower Node version are required. Via `n` module this is luckily quite easy.

I'll also check the official NR install script, not sure if this did not exist earlier or we faced other issues with it.

**Comment by borpin** [comment]
> I'll also check the official NR install script, not sure if this did not exist earlier or we faced other issues with it.

I wasn't suggesting using it, the locations of the user data precludes it I suspect, I just used it as an example of the version of nodjs it installed.

**Comment by MichaIng** [comment]
@borpin 
I'll check regardless, probably the steps required afterwards (to comply with DietPi) are less effort compared to keeping up with dependencies and Node version... However a main Node version indeed is not hard to apply and we do this in other cases as well. Only issue is that with "n", the Node version is applied system-wide. We're thinking about running each program with the latest Node version it supports as well: #2226 (**EDIT: Ah, you were already responding to that issue as well :smile:**)

**Comment by borpin** [comment]
> Ah, you were already responding to that issue as well

😀 yes, 18 months ago 😀.  I think that was because of a npm package that required a specific version of nodejs.

One other point, for me, I could not manually downgrade as nodejs V13 simply does not work - any `npm` command is greeted with an 'illegal instruction' error 😢.

As a minimum, I think the nodejs install should offer a 'do you want a specific version?' option during install (or before).

**Comment by MichaIng** [comment]
@borpin 
We use the official Node installer, and generally, as well since we offer unintended installs, it should by default pull the most current version. Manual downgrading via "n" as you mentioned in the other issue is easy anyway.

> One other point, for me, I could not manually downgrade as nodejs V13 simply does not work - any npm command is greeted with an 'illegal instruction' error :cry:.

Okay, but this then means that v13 is not only incompatible with Node-RED but with your whole system? Hmm this requires additional investigation then, probably there have been made some deeper changes that require a certain Linux version or such :thinking:.

**Comment by Joulinar** [comment]
As already mention on the forum entry, node-red installation is working fine on my VM as well as RPi system. Even if it pull node.js v13. So it seems something special on the ESXi Server installation. Maybe due to the server architecture.

**Comment by MichaIng** [comment]
Okay good to know. Probably a kernel upgrade helps, e.g. pulling Linux 5.X from backports:
`apt install linux-image-amd64/buster-backports`

**Comment by borpin** [comment]
> Okay, but this then means that v13 is not only incompatible with Node-RED but with your whole system?

@MichaIng Potentially yes. As I said it used to work but when I started with a fresh Buster image it would not work.

> node-red installation is working fine on my VM as well as RPi system. Even if it pull node.js v13.

@Joulinar As I said, I'm not denying that. But if the **official** NR install script uses V12 and their pages state that the supported version is V12, then custom installers should respect that and only install V12 (IMHO).

**Comment by MichaIng** [comment]
I'll run some test on VMware later, which should behave very close to ESXI VM (?).

**Comment by MichaIng** [comment]
I ran testes on VMware and everything works pretty fine. So even that Node-RED officially states Node v12 as latest supported version, I am not too keen to add a version downgrade to the installer, which we then need to remove again at a later time.

A better idea is to concentrate on debugging Node v13 on (your) ESXi Buster machine, as this seems to be the root of the issue, not Node-RED + Node v13 compatibility.

And as said, just in case, try to fully upgrade your system:
```
apt update
apt full-upgrade
```
And try it with Linux 5.4:
```
apt install linux-image-amd64/buster-backports
```

**Comment by MichaIng** [comment]
I mark this as closed. VM-specific it seems, must be replicated on current ESXi with current kernel package before we can pick up.
