### ISSUE TITLE
General | Disable serial console by default on all DietPi images

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#343]
#### This was originally a ticket to Enable serial console by default, however, please see reasons for this revert: https://github.com/Fourdee/DietPi/issues/343#issuecomment-226946848

> https://github.com/Fourdee/DietPi/issues/306#issuecomment-219524494

Once implemented:
For the serial console to be available from 1st run, all images would need to be updated for the change to be active: https://github.com/Fourdee/DietPi/issues/306#issuecomment-219775734.

**Comment by Fourdee** [comment]
List of current DietPi images with Serial console enabled by default. http://dietpi.com/downloads/images
:u6307: BPi M2+
:u5272: C1
:u6307: C2
:u5272: XU3/4
:u5272: RPi
:u6307: OPi-PC
:u6307: Pine64

I'll update it, as and when, each image is redone.

Yes, i like the Chinese symbols :+1:, for all I know, they could mean ***\* lol.

**Comment by Fourdee** [comment]
Ok so the initial coding is done: https://github.com/Fourdee/DietPi/commit/2922cb8cce7399c2737d42b7e9b895dd19e483c0

Serial console will now be enabled by default for all future images we create (eg: when finalize is run). The current images will remain disabled by default. 

Users can also disable the serial console before running DietPi for the 1st time. `dietpi.txt` : `serial_console_enabled=0`. Will get automatically disabled during 1st boot.

**Comment by Fourdee** [comment]
Most likely going to annoy a few people, doing a u-turn on serial consoles, but here goes:

#### Serial console will now be Disabled for all DietPi images by default. Heres why:
- DietPi is supposed to be minimal and optimized. Serial console uses up resources.
- DietPi requires a network connection to run through the initial setup. So generally speaking, the ease of remote access over SSH should always be preferred, when compared to serial.
- 99.9% of pre boot issues that may require a serial console to debug, will always (in my experience) be caused by a faulty/unstable PSU and/or corrupt filesystem on flash device.
- Very few people know what a serial console is, let alone use one.
- RPi 3 requires `core_freq=250` to prevent corrupt characters. This reduces the performance of the device (down from 400mhz).

If users still require a serial console, they can set the following in dietpi.txt prior to boot. DietPi will then enable the serial console during 1st run:

```
serial_console_enabled=1
```

Users can also toggle the serial console via `dietpi-config` > advanced.

Open for discussion, so if you have feedback, let me know.

**Comment by Fourdee** [comment]
v120 SBC images completed.

**Comment by axel-h** [comment]
I agree that there is really not need to run a login prompt there. But aside from this, dies the console really eat this much resources?
But can we get a message "serial console disabled" at least then? Seems I'm coming from a completely different background and I've see too many cases where the serial console prints "loading kernel..." and then nothing - which usually means the kernel has crashed. Having a nice message there that says things are fine and now please use SSH or the network to connect would really help. 
Thinking of this, printing the DietPi version and IP might also be nice. Or an option to get the full dmsg output printed there.
