### ISSUE TITLE
Emby crash on rpi 3b

### ISSUE THREAD

**Issue by Dr0bac** [MichaIng/DietPi#3451]
I guess problem is within emby app, but i'm seeing that developer is not sure what can be the issue, so maybe there can be problem with the system, i don't know.
Here is the thread where i mentioned the details

https://emby.media/community/index.php?/topic/83857-server-crash-when-loading-posters-in-library/#entry864735

What do you think?

**Comment by MichaIng** [comment]
@Dr0bac 
Lets keep discussion on the Emby forum. I created an account there: https://emby.media/community/index.php?/topic/83857-server-crash-when-loading-posters-in-library/?p=865106
