### ISSUE TITLE
DietPi-Config | systemd-timesyncd fails

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#3467]
#### Required Information
- DietPi version | 6.28
- Distro version | debian_version 10.3
- Kernel version | Linux DietPi 4.19.0-8-amd64 
- SBC device | VPS

#### Extra details
`NTP mirror : Change the NTP mirror used `
Successfully change to any mirror however systemd-timesyncd still fails. Most likely related to an issue with the VPS however I little guidance to troubleshoot.

Semi-related seems to fails intermittently
```
 - Command: ping -c 1 -W 10 one.one.one.one 
│  - Exit code: 1
```
yet I can ping `debian.pool.ntp.org` just fine.
```
root@DietPi:~# until ping -c 1 0.debian.pool.ntp.org; do sleep 0.5; done
PING 0.debian.pool.ntp.org (51.158.147.92) 56(84) bytes of data.
64 bytes from 51-158-147-92.rev.poneytelecom.eu (51.158.147.92): icmp_seq=1 ttl=48 time=151 ms

--- 0.debian.pool.ntp.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 151.079/151.079/151.079/0.000 ms
```

fails timing out
`/DietPi/dietpi/func/run_ntpd 1`

Also checked using `ntpdate` package. 

An alternative approach `htpdate`
	The HTTP Time Protocol (HTP) is used to synchronize a computer's time with web servers as reference time source. Htp will synchronize your computer's time to Greenwich Mean Time (GMT) via HTTP headers from web servers. The htpdate package includes a program for retrieving the date and time from remote machines via a network. Htpdate works through proxy servers. Accuracy of htpdate will be usually within 0.5 seconds (better with multiple servers). If this is not good enough for you, try the ntpd package. 

`sudo apt-get install htpdate`
`sudo htpdate -a google.com`

**Update** `ntp.multacom.com` seems to work provided by the VPS.
So all that's left is figuring out the flaky DNS resolution. 

```
 local domain=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_DNS_DOMAIN=/{s/^[^=]*=//p;q}' /DietPi/dietpi.txt)
                                l_message='Checking DNS resolver' G_RUN_CMD ping -c 1 -W ${timeout:-5} ${domain:-one.one.one.one}

```

**Comment by Joulinar** [comment]
Hi,

I'm a little bit lost what your issue now is? You can change NTP server to `ntp.multacom.com` if this is working for you.

**Comment by LexiconCode** [comment]
> I'm a little bit lost what your issue now is? You can change NTP server to `ntp.multacom.com` if this is working for you.

Greetings, yes that fixes my original problem. However `ping -c 1 -W 10 one.one.one.one ` refusing to resolve is still an issue. The DNS can resolve links as demonstrated with `sudo apt-get update`.

**Comment by Joulinar** [comment]
Can you try the following

```
ping -4 -c 1 -W 10 one.one.one.one
ping -c 1 -W 10 1.1.1.1
```

**Comment by LexiconCode** [comment]
```
root@DietPi:~# ping -4 -c 1 -W 10 one.one.one.one
PING one.one.one.one (1.1.1.1) 56(84) bytes of data.
64 bytes from one.one.one.one (1.1.1.1): icmp_seq=1 ttl=61 time=0.924 ms

--- one.one.one.one ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.924/0.924/0.924/0.000 ms
```

```
root@DietPi:~# ping -c 1 -W 10 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=61 time=1.03 ms

--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.032/1.032/1.032/0.000 ms

```

**Comment by Joulinar** [comment]
so you are able to `ping one.one.one.one` using IPv4. Do you have IPV6 activated? If not needed pls can you disable IPv6 on `dietpi-config` network settings

**Comment by LexiconCode** [comment]
Thank you very much @Joulinar that worked.

**Comment by Joulinar** [comment]
ok looks like that IPv6 is not fully working on that network. So better to have it deactivated if not needed.
