### ISSUE TITLE
Diet-Pi Software | No Machine

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#347]
This secure, omni OS supported software acts as a remote desktop server or client. It is light weight and easy to install and configure. 

Will provide more insight to these steps as for consideration to be included under Linux Software. 

It is a secure alternative to xrdp - just hoping to diversify the offerings.

**Comment by k-plan** [comment]
@xenfomation 

I personally like multi-platform-supporting-software. :+1: 

https://www.nomachine.com/download

**Comment by xenfomation** [comment]
Thanks!  It allows me to access many of my machines - virtual or real, windows or linux-based - easily.

While the original install generates a very generic configuration, specifically for ports, could be augmented via a whiptail menu post installation.

I am wondering if items such as XRDP and NoMachine should be tied with tightnc, etc under header "---Remote Desktop Access----" or something that indicates Graphical Interfaces?

**Comment by xenfomation** [comment]
NoMachine tested and working.

![nomachine](https://cloud.githubusercontent.com/assets/10519408/15632019/aaf19e7e-2552-11e6-8d08-abd1d1cb41bc.PNG)

It supports different architectures, so hardware models will need to be considered, @Fourdee --

[https://www.nomachine.com/download](https://www.nomachine.com/download)

[http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_1_amd64.deb](http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_1_amd64.deb)

[
http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_6_armv6hf.deb](http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_6_armv6hf.deb)

[http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_5_armhf.deb
](http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.26_5_armhf.deb)

**Comment by xenfomation** [comment]
@Fourdee --

So as part of my check-in, I realized I had no mapping of HW_MODELS & Descriptions as to add an IF/THEN/ELSE condition so that the right DEB package is pulled from NoMachine's downloads.

I can add those in as they support x64, ARMv6, and even ARMHF has a lot of support for tons of boards.

**Comment by Fourdee** [comment]
Additional implementation and testing for reference: https://github.com/Fourdee/DietPi/pull/364

**Comment by Fourdee** [comment]
Documentation to finish: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=60#p2071

**Comment by Fourdee** [comment]
Done.
