### ISSUE TITLE
Missing armbian.list in /etc/apt/sources.list.d/ at M3, Fire3, ZeroPi Buster images

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi#3473]
The file armbian.list is missing in the buster images of M3, Fire3 and ZeroPi.

- https://dietpi.com/downloads/images/DietPi_NanoPiM3-ARMv8-Buster.7z
- https://dietpi.com/downloads/images/DietPi_NanoPiFire3-ARMv8-Buster.7z
- https://dietpi.com/downloads/images/DietPi_NanoPiZeroPi-ARMv7-Buster.7z

The result is, that the kernel is not updated any more.

I have already generated corrected images and did first, short tests, how can I upload them?

**Comment by StephanStS** [comment]
FYI: I did generate the three images (M3, Fire3, ZeroPi) which are downloadable in 11/2019. MichaIng uploaded them to the download area.

**Comment by Joulinar** [comment]
So topic can be closed?

**Comment by StephanStS** [comment]
Sorry, my description was a bit misunderstandable.
I generated in 11/2019 the images which had the mistake with the missing file.
I actually have generated three new images which need to be uploaded.

**Comment by Joulinar** [comment]
@MichaIng 
Your turn :smiley:

**Comment by MichaIng** [comment]
@StephanStS 
Found some time today to go through open issues and will upload your new images now.

I'll change `DEV_GITBRANCH=master` in dietpi.txt since those are based on `dev` branch, so they will immediately update to stable v6.29(.1+) once released.

**Comment by MichaIng** [comment]
**Done: https://dietpi.com/downloads/images/**

**Comment by StephanStS** [comment]
Tested the downloadable image it with ZeroPi, assume that it is also valid for Fire3 and M3 (not explicitly tested).
