### ISSUE TITLE
Transmission download folder without rwx (---) permission

### ISSUE THREAD

**Issue by sealteam666** [MichaIng/DietPi#3487]
So i am downloading movies to  /mnt/mydisk/transmission but movies are downloading with drwxrwx--- i want it to download with drwxrwxrwx 
Goal is that jellyfin can read new movie download with transmission i am new to dietpi i dont know where to post also i dont permission and writes in linux..please help

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. basically you would need to set umask value in `transmission` config file. Do `nano /etc/transmission-daemon/settings.json` and change `umask` value to `0`. Once done you would need to reload transmission service.

`systemctl restart transmission-daemon.service`

https://github.com/transmission/transmission/wiki/Editing-Configuration-Files

**Comment by sealteam666** [comment]
Thank you so much man it worked .
