### ISSUE TITLE
Orange Pi PC H3 kernel

### ISSUE THREAD

**Issue by supercoollbob** [MichaIng/DietPi#349]
Please add the kernel http://www.armbian.com/orange-pi-pc/ of this distribution.
Kodi youtube work fine, tested 48 hours.

**Comment by Fourdee** [comment]
@supercoollbob 
As of v118, our OrangePi PC image is now built with ARMbian: https://github.com/Fourdee/DietPi/issues/329#issuecomment-218830125

I'am unable to fully test Kodi as my OPi PC HDMI output is dead. Let us know if you get any issues and reopen ticket if required.
