### ISSUE TITLE
[FAILED] DietPi-Update

### ISSUE THREAD

**Issue by carlosspre** [MichaIng/DietPi#3522]
#### Details:
can someone help me solve the problem

- Date           | Sun 10 May 15:14:43 BST 2020
- Bug report     | d7a220ef-87b4-40aa-85fb-dba9d86db73f
- DietPi version | v6.28.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 4 Model B (armv7l) (ID=4)
- Kernel version | Linux NetPlexPi4 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Distro         | buster (ID=5)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Update

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Preconfiguring packages ...
(Reading database ... 44937 files and directories currently installed.)
Removing rsync (3.1.3-6) ...
/usr/bin/deb-systemd-helper: 1: /usr/bin/deb-systemd-helper: shape:EventCategoriesMapList,: not found
/usr/bin/deb-systemd-helper: 2: /usr/bin/deb-systemd-helper: documentation:<p>A list of EventCategoriesMap data types.</p>: not found
/usr/bin/deb-systemd-helper: 3: /usr/bin/deb-systemd-helper: Syntax error: "}" unexpected
dpkg: error processing package rsync (--remove):
 installed rsync package post-removal script subprocess returned error exit status 2
Errors were encountered while processing:
 rsync
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Joulinar** [comment]
Hi,

Many thanks on your report. Pls wait with an update to DietPi v6.29.2 independent on your issue.

Pls can you try running `apt update` and `apt upgrade` manually

**Comment by carlosspre** [comment]
I can't install any programs on my dietpi either ..... but in a new installation of dietpi it's all normal

**Comment by Joulinar** [comment]
Let's close this issue as you opened another with same content

**Comment by Joulinar** [comment]
Continuing in #3523

**Comment by carlosspre** [comment]
root@NetPlexPi4:~# apt upgrade

E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
root@NetPlexPi4:~#

**Comment by Joulinar** [comment]
Did you tried running `dpkg --configure -a` as suggested by the error message?
