### ISSUE TITLE
DietPi-Software | qBittorrent: Set 775 permissions/002 UMask by default on install

### ISSUE THREAD

**Issue by compdealer** [MichaIng/DietPi#3524]
#### Is your feature request related to a problem? Please describe:

- radarr/sonarr can't hardlink downloaded files from qbittorrent

#### Describe the solution you'd like:

- add UMask=002 in qbittorrent.service

#### Additional context

- [https://github.com/MichaIng/DietPi/issues/2339](https://github.com/MichaIng/DietPi/issues/2339)

**Comment by MichaIng** [comment]
@compdealer 
Many thanks for your report. I though this would be already the case, let me see.

**Comment by MichaIng** [comment]
Fixed for v6.30: https://github.com/MichaIng/DietPi/commit/b73d24eb8b4d954d3e498e2b8c61cae0348be1ab
