### ISSUE TITLE
haproxy fails to start

### ISSUE THREAD

**Issue by crazyquark** [MichaIng/DietPi#353]
Looks like the default config for haproxy is broken as the service fails to start:
-- Logs begin at Tue 2016-05-24 08:20:23 EEST, end at Tue 2016-05-24 08:44:06 EEST. --
May 24 08:44:06 DietPi haproxy[14414]: [WARNING] 144/084406 (14416) : config : missing timeouts for proxy 'stats'.
May 24 08:44:06 DietPi haproxy[14414]: | While not properly invalid, you will certainly encounter various problems
May 24 08:44:06 DietPi haproxy[14414]: | with such a configuration. To fix this, please ensure that all following
May 24 08:44:06 DietPi haproxy[14414]: | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
May 24 08:44:06 DietPi haproxy[14414]: [WARNING] 144/084406 (14416) : config : 'stats' statement ignored for proxy 'stats' as it requires HTTP
May 24 08:44:06 DietPi haproxy[14414]: [ALERT] 144/084406 (14416) : Fatal errors found in configuration.
May 24 08:44:06 DietPi systemd[1]: haproxy.service: control process exited, code=exited status=2
May 24 08:44:06 DietPi systemd[1]: Failed to start LSB: fast and reliable load balancing reverse proxy.
-- Subject: Unit haproxy.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit haproxy.service has failed.
-- The result is failed.
May 24 08:44:06 DietPi systemd[1]: Unit haproxy.service entered failed state.
May 24 08:44:06 DietPi haproxy[14414]: failed!

Running on Odroid C1/latest dietpi.

**Comment by crazyquark** [comment]
It would appear that the line causing issues is this:

listen stats _:1338
[ALERT] 144/220546 (12162) : parsing [/etc/haproxy/haproxy.cfg:60] : 'listen' cannot handle unexpected argument '_:1338'.

**Comment by crazyquark** [comment]
Looks like a haproxy backwards compat issue:
http://www.serverphorums.com/read.php?10,1326393

needed to change that line to:
 listen stats
        bind *:1338

**Comment by xenfomation** [comment]
Hey, @crazyquark -- which version which version were you running before (and currently)?  Thanks!

**Comment by xenfomation** [comment]
Well, I found the code -- will check out, correct, and test before reporting to @Fourdee ....

```

#Admin web page
        # listen stats *:1338
        listen stats
        bind *:1338
        stats enable
        stats uri /
```

Will keep all posted on top of issue #309

**Comment by crazyquark** [comment]
haproxy is now version 1.6.2
When I first started dietPi it updated my system to the latest DietPi version(from 115 to 118 I think).

**Comment by xenfomation** [comment]
Thanks, @crazyquark  -- this will allow me to ensure a condition is set to check for haproxy < = > 1.6.2

**Comment by xenfomation** [comment]
This is the highest item on my backlog list and I will have a commit today for this.

#353 - haproxy fails to start #353
#361 - cli grouping of software?
#357 - DietPi-Software | GNUStep Desktop Environment #357 
#347 - No Machine & stock configs
#325 - DietPi Idea | Sourceable script with pre-defined color codes #325 
#309 - xenserver docs
#247 - DietPi-Software | Add Friendica: A Personal Social Networking Platform #247 
#246 - NFS
#245 - Full Disk Encryption #245
#271 - General | Add support for 2+ USB drives #271 
#195 - DietPi-Software | Add QuiteRSS installation option #195 
#191 - DietPi-Software | Add xrdp installation option #191 
#151 - DietPi-Software | Add MATE desktop installation option #151 
#41  - [Wish List] Convert DietPi-Software into SQL database #41

**Comment by Fourdee** [comment]
Outdated ticket, making as closed. Please reopen if required.

**Comment by attzonko** [comment]
Has this been fixed? I hit this same issue when I installed haproxy today using dietpi-software

I am running DietPi version 136

**Comment by Fourdee** [comment]
@attzonko 

Thanks for letting us know. 👍 
I'll take a look.

**Comment by attzonko** [comment]
By the way the workaround suggested by @crazyquark on May 24 corrected the issue for me.

**Comment by Fourdee** [comment]
@attzonko 

> By the way the workaround suggested by @crazyquark on May 24 corrected the issue for me.

Yep, same for me. Excellent 👍 
I'll update sourcecode for those changes.

**Comment by Fourdee** [comment]
Completed.
