### ISSUE TITLE
DietPi-Software | Snapcast

### ISSUE THREAD

**Issue by sealteam666** [MichaIng/DietPi#3539]
#### Is your feature request related to a problem? Please describe:

- ...

#### Describe the solution you'd like:

- ...

#### Describe alternatives you've considered:

- ...

#### Additional context

- ...

**Comment by MichaIng** [comment]
@sealteam666 
Many thanks for your request.

A few more information, some links and what it is, would have been helpful. I guess you mean: https://github.com/badaix/snapcast

**Comment by MichaIng** [comment]
The client side is currently worked on: #4465
I mark this issue as closed in favour of #2244, where some more info has been collected already.
