### ISSUE TITLE
how can i connect hciuart to console OR what should i type in HCIUART.service to connect to CONSOLE for bluetooth 

### ISSUE THREAD

**Issue by sealteam666** [MichaIng/DietPi#3547]
### Creating a bug report/issue
dietpi@DietPi:~$ sudo journalctl -u hciuart.service
-- Logs begin at Tue 2020-05-19 22:22:36 +09, end at Tue 2020-05-19 22:58:52 +09. --
May 19 22:46:52 DietPi systemd[1]: Dependency failed for Configure Bluetooth Modems connected by UART.
May 19 22:46:52 DietPi systemd[1]: hciuart.service: Job hciuart.service/start failed with result 'dependency'.
May 19 22:52:23 DietPi systemd[1]: Dependency failed for Configure Bluetooth Modems connected by UART.
May 19 22:52:23 DietPi systemd[1]: hciuart.service: Job hciuart.service/start failed with result 'dependency'.

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...
2. ...

#### Expected behaviour

- ...

#### Actual behaviour

- ...
hciuart.service takes time to create symlink  while switching on and bluetooth in dietpi-config
#### Extra details

- ...

**Comment by MichaIng** [comment]
Closing in favour of #3549
