### ISSUE TITLE
DietPi-Software | Plex Media Server: systemd unit remains after purging package

### ISSUE THREAD

**Issue by thecarlosv** [MichaIng/DietPi#3551]
After unistalling plex, the service still tries to go active. Already tried 
root@CarlosPi:~# systemctl stop plexmediaserver
root@CarlosPi:~# apt-get purge plexmediaserver -y
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete plexmediaserver

but i get that error. 

9e34f6c6-7ed5-4c77-9758-11706481f1e7

**Comment by MichaIng** [comment]
@thecarlosv 
Many thanks for your report.

Indeed I see `/lib/systemd/system/plexmediaserver.service` is still present, which of course should have been removed when purging the package. We have to forward this to Plex devs and implement a workaround until it has been resolved upstream: https://github.com/MichaIng/DietPi/commit/b0c23fbf209f48a77bb50b3a80d5b55c31b1f833

Please do the following:
```
systemctl unmask plexmediaserver
systemctl disable --now plexmediaserver
rm -R /lib/systemd/system/plexmediaserver.service*
```

**Comment by thecarlosv** [comment]
Thanks, it works!
