### ISSUE TITLE
KVM problem

### ISSUE THREAD

**Issue by Dreaming-Codes** [MichaIng/DietPi#3557]
I have no other way of accessing vps than ssh and vnc so I can't know what goes wrong with the boot

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. Well, if we don't have any logs and you are not able to access the system, it will be quite hard to assist. Maybe you can ask your VPS provider of there are any other console to access the VM layer.

**Comment by MichaIng** [comment]
@Dreaming-Codes 
Many thanks for your report.

Have you gone through the steps on the other issue already? https://github.com/MichaIng/DietPi/issues/1285#issuecomment-630510940

It is basically about LVM support: #2995
Lets keep the discussion there, so I mark this as closed.
