### ISSUE TITLE
dietpi-update on Rock64 board+EMMC

### ISSUE THREAD

**Issue by linusky** [MichaIng/DietPi#3560]
#### Details:
- Date           | Sat 23 May 10:15:42 EDT 2020
- Bug report     | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator    | n/a
- Pre-image      | n/a
- SBC device     | Rock64 (aarch64) (index=43)
- Kernel version | #1 SMP Thu Oct 12 09:14:48 UTC 2017
- Distro         | stretch (index=4)
- Command        | /DietPi/dietpi/func/dietpi-ramdisk 1
- Exit code      | 127
- Software title | DietPi-Update

#### Steps to reproduce:

1. dietpi-update

#### Expected behaviour:

- ...

#### Actual behaviour:

- One command failed during the update of DietPi

#### Extra details:

- Board Rock64 + EMMC

#### Additional logs:
```
Log file contents:
/DietPi/dietpi/func/dietpi-globals: line 1316: /DietPi/dietpi/func/dietpi-ramdisk: No such file or directory
```

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. I guess it will be same like #3532 

Following this comment, issue can be ignored
https://github.com/MichaIng/DietPi/issues/3532#issuecomment-628528041

**Comment by MichaIng** [comment]
Jep exactly, simply ignore it, the first boot setup will finish as intended.

All v6.25 systems are affected by this, but no chance to solve it as v6.25 has a usually minor bug that does not allow the patch_file script to kill its parent dietpi-updater script as it is intended to. Damn shell pipes 😄.

**Comment by linusky** [comment]
Hi, Thank you for the answer. I ignore it so.
After the reboot all seems to be good.
