### ISSUE TITLE
DietPi-Imager | Loop device support for Clonezilla

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#3578]
@sal666 
FTR: https://gitlab.com/stevenshiau/clonezilla/-/merge_requests/43
When allowing loop devices for Clonezilla in DietPi-Imager, it runs through nicely with this Clonezilla function additions: https://dietpi.com/downloads/images/
I'm doing a test install on UEFI-capable VM with this, finally on native PC. This allows automated builds without involving any real machine or disk.

**Comment by MichaIng** [comment]
🈴 Restoring fails with:
![clonezilla](https://user-images.githubusercontent.com/28480705/83431357-8208e900-a437-11ea-9194-944ee9852224.png)

This is strange since the mentioned file clearly states "gpt":
```
Model: Loopback device (loopback)
Disk /dev/loop0: 2299904s
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start    End       Size      File system  Name  Flags
 1      2048s    194559s   192512s   fat32              boot, esp
 2      194560s  2297928s  2103369s  ext4
```
- Probably the restoring functions as well need some rework to accept "loop[0-9]" here.
- **Ah I am stupid and forgot to apply the changes to the Clonezilla live disk as well 😅!**

**Comment by MichaIng** [comment]
🈯 Bingo! Applying the change to the live disk as well solves the issue.

Boots nicely 😃!

**Comment by sal666** [comment]
Great news!! Let's hope that team Clonezilla will apply your fix.

**Comment by MichaIng** [comment]
Looks good, might be merged after the coming release: https://gitlab.com/stevenshiau/clonezilla/-/merge_requests/43#note_358529644

**Comment by MichaIng** [comment]
Self-reminder:
- Create new UEFI installer image and by this test the new Clonezilla version with integrated loop device support: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative_testing/20200910-focal/
- Many thanks to @stevenshiau for merging this quite quickly and even providing an early test image. Sorry that I was not able to test this until now. I'll do later with the current "official" testing image and provide feedback.

**Comment by MichaIng** [comment]
🈯 Works like a charm, any `x86_64` image can be reliably directly created a Clonezilla installer with, awesome!

**Comment by sal666** [comment]
Awesome!! Great work!!

**Comment by MichaIng** [comment]
Updated milestone, just to keep track until the Clonezilla update has been released.

**Comment by MichaIng** [comment]
Release is there: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20201102-groovy/
