### ISSUE TITLE
Checking DNS resolver issues

### ISSUE THREAD

**Issue by nigiriemoji** [MichaIng/DietPi#3584]
Hey I'm having issues setting up my Pi Zero W on DietPi. I flash it and immediately plug into my Pi, ethernet thru micro usb. Nothing configured in dietpi.txt so defaults. I was able to ping other sites just fine, the connection seems to be online but I just can't get past the Checking DNS resolver part. I'm trying dietpi-update command and see if I can setup after that.

```
#### Details:
- Date           | Fri  5 Jun 06:50:37 BST 2020
- Bug report     | 17dbc259-84d6-4544-b1fa-c315bb9bd44e
- DietPi version | v6.28.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi Zero W (armv6l) (ID=1)
- Kernel version | Linux DietPi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux
- Distro         | buster (ID=5)
- Command        | ping -c 1 -W 5 one.one.one.one
- Exit code      | 1
- Software title | DietPi-Login

#### Steps to reproduce:
<!-- Explain how to reproduce the issue -->
1. ... Flash new image of DietPi
2. ... Plug in and setup thru SSH

#### Expected behaviour:
<!-- What SHOULD happen? -->
- ... DNS resolver works

#### Actual behaviour:
<!-- What IS happening? -->
- ... DNS resolve isn't working

#### Extra details:
<!-- Please post any extra details that might help solve the issue -->
- ...

#### Additional logs:
```
PING one.one.one.one(one.one.one.one (2606:4700:4700::1111)) 56 data bytes

--- one.one.one.one ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

```

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. Pls can you try to deactivate IPv6 if possible?

**Comment by StephanStS** [comment]
@yslupdates: Is there any Pi-Hole present in your setup? If yes, check Pi-Hole for too strong filtering or disable Pi-Hole during the first run.

**Comment by nigiriemoji** [comment]
Turning off IPv6 in dietpi-config worked! Can turn it back on after I’m done though?

And yes, I do have a 2nd pihole running but I disabled it before installing to no avail!

**Comment by nigiriemoji** [comment]
Quick update, I tried doing dietpi installation over wifi and that worked smoothly. No DNS resolver checking issues on wifi. I just did that, then plugged in ethernet and switched and then setup static IP just fine. Although I did have the same issue, but now with trying to run dietpi-software. I can install pi-hole the normal bash script way they recommend, but I can't access dietpi-software. I was able to change the command from saying one.one.one.one to 1.1.1.1 and that worked. I've disabled my other pi-hole this whole time. Guess it's something with ethernet.

`│ Checking DNS resolver                                                        │
│  - Command: ping -c 1 -W 5 one.one.one.one                                   │
│  - Exit code: 1                                                              │
│  - DietPi version: v6.30.0 (MichaIng/master) | HW_MODEL: 1 | HW_ARCH: 1 |    │
│ DISTRO: 5                                                                    │
│  - Image creator: DietPi Core Team                                           │
│  - Pre-image: Raspbian Lite                                                  │
│  - Error log:                                                                │
│ PING one.one.one.one(one.one.one.one (2606:4700:4700::1001)) 56 data bytes   │
│                                                                              │
│ --- one.one.one.one ping statistics ---                                      │
│ 1 packets transmitted, 0 received, 100% packet loss, time 0ms `

**Comment by Joulinar** [comment]
Hi,

I guess your issue is with IPv6. Seems you have issues connection to the IPv6 address of Cloudflare. You could check if other IPv6 address are working fine.

If not needed you should have IPv6 disabled

**Comment by faxesystem** [comment]
Having the same problem. My pi is connected via ethernet. I can ping one.one.one.one from all other systems in my network without problems and get the IPv6 address resolved. But dietpi seems to have a problem with it.
Seems to be a problem with pinging one.one.one.one

```
ping google.com
PING google.com(muc11s04-in-x0e.1e100.net (2a00:1450:4016:807::200e)) 56 data bytes
64 bytes from muc11s04-in-x0e.1e100.net (2a00:1450:4016:807::200e): icmp_seq=1 ttl=49 time=33.9 ms
64 bytes from muc11s04-in-x0e.1e100.net (2a00:1450:4016:807::200e): icmp_seq=2 ttl=49 time=31.8 ms
64 bytes from muc11s04-in-x0e.1e100.net (2a00:1450:4016:807::200e): icmp_seq=3 ttl=49 time=27.2 ms
```

```
ping dns9.quad9.net
PING dns9.quad9.net(dns9.quad9.net (2620:fe::9)) 56 data bytes
64 bytes from dns9.quad9.net (2620:fe::9): icmp_seq=1 ttl=56 time=25.3 ms
64 bytes from dns9.quad9.net (2620:fe::9): icmp_seq=2 ttl=56 time=23.7 ms
64 bytes from dns9.quad9.net (2620:fe::9): icmp_seq=3 ttl=56 time=23.5 ms
```

```
ping one.one.one.one
PING one.one.one.one(one.one.one.one (2606:4700:4700::1111)) 56 data bytes
--- one.one.one.one ping statistics ---
26 packets transmitted, 0 received, 100% packet loss, time 25029ms
```

So another destination for the DNS resolver test should be used I assume?

My bad. I was using the Dismail DNS on my router https://dismail.de/info.html#dns which seems to be blocking one.one.one.one

> fdns1 and fdns2 includes the following lists to filter Ad-, Tracker- and Malwaredomains:
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    http://sysctl.org/cameleon/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://easylist.to/easylist/easylist.txt
    https://easylist.to/easylist/easyprivacy.txt

Seems to be an issue with cloudflare since it was not resolving again. I followed this tip and changed the IP and DNS of the resolver check. https://dietpi.com/phpbb/viewtopic.php?p=23876

**Comment by MichaIng** [comment]
I mark this issue as closed. Feel free to reopen if required.

**Comment by ghost** [comment]
I also encounter this issue on a fresh install because https://cleanbrowsing.org/ blocks dns9.quad9.net on our test network:

```
[FAILED] DietPi-Software | Checking DNS resolver
 - Command: ping -c 1 -W 10 dns9.quad9.net
```

Would it be possible to replace or add a family-friendly backup test, e.g. `ping -c 1 -W 10 doh.familyshield.opendns.com` ?

**Comment by Joulinar** [comment]
You can change the DNS as well as ping check to a value fitting your need. This is possible inside `dietpi.txt`
