### ISSUE TITLE
DietPi-Software | DietPi-RAMlog not removed

### ISSUE THREAD

**Issue by Pain-Patate** [MichaIng/DietPi#3588]
#### Required Information
- DietPi version | `6.30` | It's a [6.28](https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster.7z) update online to 6.3
- Distro version | `10.4 | Buster`
- Kernel version | `Linux DietPi: 4.19.118-v71`
- SBC model | `RPi4 4Gb`
- Power supply used | `Official Raspberry pi allimentation 5,1V - 3A`
- SDcard used | `SanDisk`

#### Steps to reproduce
1. [Downloaded](https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster.7z), unzipped, checksum sha256sum OK, put ond SD card
 2.  Rpi4 turn ON and link to internet
 3.  Installation in progress. I modify somes options in **Networking Options: Adapters**, **Language / Regional Options**
 4. In **Software Additional**, I choice **Fail2Ban** and **LxQt** and  [NONE] in **Log System** 
![Log-system--none](https://user-images.githubusercontent.com/51061448/83971497-b9661280-a8db-11ea-829a-c8733620e403.jpg)

5.I go to **Install** an click on **OK**
![DietPi-sofware--with-DietPi-RAMlog](https://user-images.githubusercontent.com/51061448/83971520-ec100b00-a8db-11ea-9031-165eda637cae.jpg)

 6. After some reboot system and installation, I check  **Software Additional** 
![DietPi-sofware--with-DietPi-RAMlog-after-installation -](https://user-images.githubusercontent.com/51061448/83971617-a0119600-a8dc-11ea-838c-053553cb646a.jpg)

**DietPi-RAMlog is installed. Is it normal ?**

Thanks to all and have goods days

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. Not sure what happen on your system but as you can see on your 2nd screen, `DietPi-RAMlog` was selected to be installed. Therefore it's logic that it is installed. I guess you would need to set it to `None` again using `dietpi-software`. I did a small test in my RPi3B and couldn't replicate the issue. For me `DietPi-RAMlog` was removed and I installed `LXQt`.

**Comment by Pain-Patate** [comment]
Hi, 

Speed answer :-). In fact, I didn't choose to install `DietPi-RAMlog` and he did it anyway. It's strange

**Comment by Pain-Patate** [comment]
I tried it again and it does the same thing.
I put **[None]** on **Log System** 
Next, the system display :
![After-choice-NONE-on-Log-system](https://user-images.githubusercontent.com/51061448/83971972-2084c680-a8de-11ea-807b-d97175f7da0d.jpg)
In **DietPi-Software**, after some reboot system and installation :
![Log-sytem-after-setting-none](https://user-images.githubusercontent.com/51061448/83972114-be789100-a8de-11ea-8332-ca3cff3553a2.jpg)
In **DietPi-Software**, **Uninstall** :
![Uninstall-after-installation](https://user-images.githubusercontent.com/51061448/83972176-f5e73d80-a8de-11ea-89a9-23db18770294.jpg)

I can uninstall **DietPi-RAMlog** while there is **[None]** on **Log System** (**DietPi-Sofware**)

**I should check to see if the installation really happened. How can I see it?**

**Comment by MichaIng** [comment]
Verified and fixed with: https://github.com/MichaIng/DietPi/commit/fe170d5bec55974d3bcd2167085bd66ae8f677a9
Changelog: https://github.com/MichaIng/DietPi/commit/f68580a74af77334631f64b4c57c96b5a588ff5e

**Comment by Pain-Patate** [comment]
> 
> 
> Verified and fixed with: [fe170d5](https://github.com/MichaIng/DietPi/commit/fe170d5bec55974d3bcd2167085bd66ae8f677a9)
> Changelog: [f68580a](https://github.com/MichaIng/DietPi/commit/f68580a74af77334631f64b4c57c96b5a588ff5e)

Great. :-)
