### ISSUE TITLE
Raspberry Pi 4 (4GB) running DietPi via Berryboot

### ISSUE THREAD

**Issue by apatel007** [MichaIng/DietPi#3592]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=30
G_DIETPI_VERSION_RC=0
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
10.4

- Kernel version | `uname -a`
Linux dietpi4 4.19.75v64 #1 SMP PREEMPT Sat Oct 5 03:06:01 CEST 2019 aarch64 GNU/Linux

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
RPi 4 Model B (aarch64)

- Power supply used | (EG: 5V 1A RAVpower)
The one that came with the Pi4 Kit made for it.

- SDcard used | (EG: SanDisk ultra)
64GB SanDisk Ultra

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
Fresh latest IMG taken from a berryboot image archive of DietPi4:
https://berryboot.alexgoldcheidt.com/images/

- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...Install image referenced above; run all updates.
2. ...Periodically getting "dpkg: warning: failed to open configuration file '/etc/dpkg/dpkg.cfg.d/dietpi-no_armbian' for reading: No such device or address" whenever running apt-get install or reinstall or remove on anything.

#### Expected behaviour

- ...That error should not come.

#### Actual behaviour

- ...I get the error above.

#### Extra details

- ...There is a file there:
user@host:/etc/dpkg/dpkg.cfg.d# ls -als
total 8
4 drwxr-xr-x 2 root root 4096 Jun  1 12:59 .
4 drwxr-xr-x 6 root root 4096 Jan  7 17:33 ..
0 crwxrwxrwx 1 root root 0, 0 Jun  1 12:59 dietpi-no_armbian

What is this dietpi-no_armbian c file for and why does it throw these errors? I appreciate any insight you may be able to provide. I did not see anything in the forums about this. Thanks in advance for whatever you can help with!

**Comment by MichaIng** [comment]
Many thanks for your report.

Can you give the link of the exact download you found and flashed? I cannot find it although they seem to offer downloads of a large amount of different images.

What I cannot verify is if they are regularly updated and if they host the untouched official images or add/change something. I can only recommend to use our official download: https://dietpi.com/downloads/images/DietPi_RPi-ARMv6-Buster.7z

`dietpi-no_armbian` should not be present on any RPi image from us, although I think we accidentally added it on one batch of images. It is aimed for images based on Armbian kernel which require an Armbian package that pulls user space tools and services as well. This config prevents those services and tools from being installed, which would otherwise conflict with DietPi tools and services.

However it should not produce any error. The contained file exclusions are very specific and the directives do not require any "device or address". This should be the content: https://github.com/MichaIng/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L1132-L1141

So what I would do:
- Verify that you don't have any Armbian repository installed: `cat /etc/apt/sources.list{,.d/*.list}`
- If not, remove the file: `rm /etc/dpkg/dpkg.cfg.d/dietpi-no_armbian`
- If there is indeed an Armbian repo installed, the image is wrong and manipulated since our RPi images are based on Raspbian Lite and only use official RPi and Raspbian repo and Armbian does not even support RPi at all 😉.

**Comment by apatel007** [comment]
Hi @MichaIng,

Thank you for your thorough and helpful response Michal. I did not get a chance to try to reach out to Alex G., but Alex is doing some cool stuff making images. (He is not part of the Berryboot project, but creates the images I referenced and uses the source distributions like the dietpi install images.)

You may already know this, but essentially it looks like for Berryboot has 2 partitions. The first partition boots up to a boot menu. You can choose/load an IMG via USB or Network Share into the second partition (one-time action) and then you can boot into that IMG file system going forward...and of course load other OS IMG files as additional boot menu option items to boot into.

Unfortunately, it is not easy to find/navigate to "all" of the images on Alex Goldcheidt's page for some reason...

(Sorry for the lengthy response, but hopefully this long post may help others.)

------------------------------------------------------------------------------------------------------------

**Navigation to it:**
On the images link, there is a tiny sentence with a link to see "all OS images" wedged above the search box (i'm not sure if the search works on his page?..it did not find DietPi anyway) and the current red and black banner looking links to download test images for pi4 (red) and the 8gb pi4 is on sale (black).
I manually found the 3 DietPi images on page 2 of that link here:
https://berryboot.alexgoldcheidt.com/search-downloads/?dl_page=2

------------------------------------------------------------------------------------------------------------

**These Are The 3 Image Links** posted on the berryboot site and hosted on SourceForge.net . (I used this first **Buster** image.):

  **DietPi (Buster) for all Raspberry Pi Devices (2020.01.25) (126.5 MiB, 1,352 downloads) February 19, 2020**
Amazing OS based on Debian Buster. His author say that: "DietPi is highly optimized for minimal CPU and RAM resource usage, ensuring your SBC always runs at its maximum potential". On the first boot the device will reboot, on second boot it will load regularly. APT directory fixed.
➤ Project Homepage - https://berryboot.alexgoldcheidt.com/go/0005
  
➤ Download OS Image - https://berryboot.alexgoldcheidt.com/download/265/ --> 
..it redirects you to ... 
https://sourceforge.net/projects/berryboot-updated-images/files/Raspberry-Pi/dietpi_buster_all_rpi_2020.01.25_berryboot.img.gz/download

  **DietPi (Jessie) for all Raspberry Pi Devices (2018.01.20) (72.2 MiB, 550 downloads) February 24, 2018**
Amazing OS based on Debian Jessie. His author say that: "DietPi is highly optimized for minimal CPU and RAM resource usage, ensuring your SBC always runs at its maximum potential". On the first boot the device will reboot, on second boot it will load regularly.
➤ Project Homepage - https://berryboot.alexgoldcheidt.com/go/0005
  
➤ Download OS Image - https://berryboot.alexgoldcheidt.com/download/266/

  **DietPi (Stretch) for all Raspberry Pi Devices (2019.05.17) (104.0 MiB, 3,911 downloads) June 11, 2019**
Amazing OS based on Debian Stretch. His author say that: "DietPi is highly optimized for minimal CPU and RAM resource usage, ensuring your SBC always runs at its maximum potential". On the first boot the device will reboot, on second boot it will load regularly.
➤ Project Homepage - https://berryboot.alexgoldcheidt.com/go/0005
  
➤ Download OS Image - https://berryboot.alexgoldcheidt.com/download/135/


I also found this interesting post: https://github.com/maxnet/berryboot/issues/344

------------------------------------------------------------------------------------------------------------
On SourceForge, Alex (https://sourceforge.net/u/alexxgg/) says, 
"Berryboot Updated OS Images Overview

Download up-to-date images for Berryboot

This is the biggest list of OS images for Berryboot. All these images have been tested before public availability.

The original OS images were _downloaded from their respective official websites, I did not modified any data of the original nor converted OS images_. I convert most of the OS images by using this method: http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions. RetroPie and others already have OS images for Berryboot, I just compress it and serve as a mirror. Fedora OS images were converted by using this tool: https://github.com/sjenning/rpi2-fedora-image-builder.

I'm not part of the Berryboot project, I'm just a web developer with a Raspberry Pi 2. I cannot offer full support on these images. However, if you find any issue, please contact me and I'll look into it.

You can request OS images at: http://berryboot.alexgoldcheidt.com/request-os-images/"

------------------------------------------------------------------------------------------------------------

Interesting Post on GitHub regarding repo of images: 👍 
https://github.com/maxnet/berryboot/issues/344

------------------------------------------------------------------------------------------------------------

I took a look at my sources list records and found I must have put these in along the way while testing other things out with XFCE and such (I probably need to dump that papirus/ubuntu one.):

user@host:/etc/apt/sources.list.d# cat /etc/apt/sources.list{,.d/*.list}
deb http://raspbian.raspberrypi.org/raspbian buster main contrib non-free rpi
deb http://ppa.launchpad.net/papirus/papirus/ubuntu xenial main
deb https://archive.raspberrypi.org/debian/ buster main ui

I made a clone in Berryboot (to backup what is built/configured in case it breaks) and removed the dietpi-no_armbian 'c' file:
rm /etc/dpkg/dpkg.cfg.d/dietpi-no_armbian

So now, if I try to install/remove some application program:
e.g. 
sudo apt-get install firefox-esr
sudo apt-get remove firefox-esr
I am not seeing the armbian error, and everything appears to be working fine.

Thank You for helping me confirm I could get rid of this file in my situation. It would still be interesting for me to learn what that file is used for and how I probably managed to put it in there in the first place, but looks like problem is solved! I appreciate your help Michal!  👍 👍 

------------------------------------------------------------------------------------------------------------

**Other Sound Problems:**
...now I will need to figure out why I can't get sound working out of HDMI on this DietPi Berryboot IMG. I followed the same config steps on a Pi3b+ except it is not using Berryboot, but had the latest base DietPi...works on the Pi3b+, but not this Pi4 Berryboot IMG. I will have to find the difference in config somehow. Every time on this Pi4 that I open Firefox and play a youtube video it crashes the tab. :-/

AlsaMixer v1.1.8 shows < PCM > at the bottom instead of HDMI for the bcm2835 ALSA in Pi4. I set the /boot/config.txt to use HDMI explicitly and then set it back to auto, so not sure what is going on. My dtparam=audio=on is also set... so a little confused what might be going on. If you have something you can recommend I check, i'd appreciate it. 👍 

... I will post here if I figure out what is going on.

**Comment by MichaIng** [comment]
Okay found and checked the DietPi Buster image and indeed the `dietpi-no_armbian` file is present there. Current DietPi RPi images do not contain it so the next update will resolve it. I just remember that even DietPi-Update should remove it via incremental patches, as long as it's no Armbian-based image.

However the errors are still strange. I just tested on other non-Armbian systems (my RPi and VMs) and could not replicate the output. apt/dpkg is just silent as expected in any case. However not worth it do dig deeper here as long as we don't get more reports about this.
_____________
Not sure about HDMI audio, of course in case of RPi4 one has to take are that there are two HDMI ports and by default I guess audio is sent to port 0 only.
Did you configure ALSA manually or via `dietpi-config`? In case can you paste:
```
cat /etc/asound.conf
```

**Comment by MichaIng** [comment]
I mark this as closed. Issue is not replicable on DietPi an obsolete file has been removed on current images. Feel free to reopen if required.
