### ISSUE TITLE
Dietpi

### ISSUE THREAD

**Issue by glecin** [MichaIng/DietPi#3599]
#### Details:
- Date           | Tue Jun  9 20:28:48 MDT 2020
- DietPi version | v6.30.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Armbian
- Hardware       | ROCK64 (aarch64) (ID=43)
- Kernel version | Linux DietPi 5.4.43-rockchip64 #20.05.2 SMP PREEMPT Tue Jun 2 22:47:34 CEST 2020 aarch64 GNU/Linux
- Distro         | buster (ID=5)
- Command        | apt-get -qq --allow-change-held-packages install xserver-xorg xinit xcompmgr xterm dbus-x11 xfonts-base x11-xserver-utils x11-utils libgl1-mesa-dri mesa-utils mesa-utils-extra
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```
---------------------------------------------------------------------
[FAILED] DietPi-Software | Unable to continue

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. Pls can you post a couple of more lines from the error message. As well did you executed `dpkg --configure -a` as requested on the error message?

**Comment by MichaIng** [comment]
At best run the following in your terminal and paste the full output here:
```
apt --allow-change-held-packages install xserver-xorg xinit xcompmgr xterm dbus-x11 xfonts-base x11-xserver-utils x11-utils libgl1-mesa-dri mesa-utils mesa-utils-extra
```

**Comment by MichaIng** [comment]
I mark this issue as closed due to missing reply. Feel free to reopen if required.
