### ISSUE TITLE
DietPi-Software | Ubooquity - update to latest version

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#3603]
@MichaIng 
pls can you upload latest version 2.1.2 of Ubooquity.jar file to dietpi.com 

Download URL: https://vaemendis.net/ubooquity/service/download.php
Location at dietpi.com: https://dietpi.com/downloads/binaries/all/Ubooquity.jar

https://dietpi.com/phpbb/viewtopic.php?f=12&t=7786

**Comment by MichaIng** [comment]
Many thanks for forwarding. Why do we not download from Var Mendis directly? 😄
PR is up: #3605
