### ISSUE TITLE
DietPi-Software | Question - CLI-Based grouping of software

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#361]
Inquiry to @Fourdee, @rhkean, and all --

For Software-Optimized and Software-Additional, is it worth adding a Category/Group Collection of "Command Line/Text-Based Software"?

For example, ViFM (VI-based File Manager) is CLI based (along with many packages I will be adding to software) and while it may seem logical to group these as "CLI-Based" to save space on the description, does it seem like a valid effort to the rest of you?

Shoot this down or throw feedback!

Cheers!

**Comment by Fourdee** [comment]
@xenfomation 
Apologies JK, I somehow missed this one. I think the "Editors" description we use is fine. I'll mark this as closed. Please reopen if needed.
