### ISSUE TITLE
Install of NodeJs failed to install dependency libatomic.so.1

### ISSUE THREAD

**Issue by larsno** [MichaIng/DietPi#3614]
### Creating a bug report/issue
For maintenance I would like to report that the installation of nodejs on dietpi failed to install dependency libatomic.so.1 After manually installing the missing library, node runs. 

#### Required Information
- DietPi version | v6.30.0
- Distro version | 10.4
- Kernel version | `Linux DietPi 4.19.72-sunxi #5.97 SMP Fri Sep 13 08:31:42 CEST 2019 armv7l GNU/Linux`
- SBC model | ZeroPi (armv71) by NanoPi
- Power supply used | 5V 2A from Asus Router 
- SDcard used | SanDisk ultra 32GB

#### Additional Information (if applicable)
- Software title | NodeJs
- Was the software title installed freshly or updated/migrated? Installed from dietpi-software
- Can this issue be replicated on a fresh installation of DietPi? I don't know
- Bug report ID | -

#### Steps to reproduce

1. Install NodeJs from dietpi-software
2. When you run "node --version" get error  
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

#### Expected behaviour

- node should respond with the version

#### Actual behaviour

- Get error  
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory.

#### Extra details

- When I manually installed the library using  "sudo apt-get install libatomic1", node then replied correctly with:  
$ node --version
v14.4.0

**Comment by Joulinar** [comment]
Hi,

I used a fresh clean DietPi on my RPi3B+ and tried to replicate the issue without success. For me Node.js installation was running fine. As well `libatomic1` was present on my empty test system right from the beginning.

```
root@DietPi3:~# dpkg -l libatomic1
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version      Architecture Description
+++-================-============-============-=====================================================
ii  libatomic1:armhf 8.3.0-6+rpi1 armhf        support library providing __atomic built-in functions
root@DietPi3:~#
```
```
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing Node.js: javascript runtime

[  OK  ] DietPi-Software | Checking URL: https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh
--2020-06-19 11:19:18--  https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1943 (1.9K) [text/plain]
Saving to: ‘node-install.sh’

node-install.sh                       100%[=========================================================================>]   1.90K  --.-KB/s    in 0.004s

2020-06-19 11:19:18 (513 KB/s) - ‘node-install.sh’ saved [1943/1943]

Node Linux Installer by www.github.com/taaem
Running as Root User
Get Latest Version Number...
Done
Downloading latest stable Version node-v14.4.0-linux-armv7l.tar.gz...
Done
Installing...
Finished installing!
```
```
root@DietPi3:~# node --version
v14.4.0
root@DietPi3:~#
```

**Comment by MichaIng** [comment]
Many thanks for your report and solution. From Debian package dependencies it looks like libatomic is required since Node 10 already, or it depends on build options...

Would be nice to have a shared lib dependency list for the pre-compiled Linux binaries but there is none: https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

**Comment by MichaIng** [comment]
Found the discussion around that, seems that this dependency is not fully intended. Many PRs were opened to remove it but all closed: https://github.com/nodejs/node/issues/29718
Link has been added here: https://github.com/nodejs/node/issues/28231
_______
I was checking on my Ethernet-only webserver system and `libatomic1` was only required for MariaDB and Redis, hence we cannot assume that it is available in every case. On my testing/building VMs it is missing as well.

@Joulinar 
Out of interest, what would be removed/depends on `libatomic1` on your test system? `apt purge libatomic1`

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/95b8e7e33a1aa46baa088258d0c981673908e222
Changelog: https://github.com/MichaIng/DietPi/commit/3b7712d75c11818cf5b9175653f767b85abc5502
