### ISSUE TITLE
Wifi adopters are not working in kali linux dual boot

### ISSUE THREAD

**Issue by elitex45** [MichaIng/DietPi#3619]
i have installed kali linux in my laptop as dual boot, i am unable to find the wifi adopters ,when i type `lspci` command in terminal under network controller i got this **Realtek Semiconductor Co., Ltd. RTL8723DE 802.11b/g/n PCIe Adapter**
but when i use command `iwconfig` there is no wlan0 and it also shows no wireless extensions 
can anyone please help me with this 
here are the screen shots 
[click here](https://drive.google.com/drive/folders/1kKrKO1kThGV1SPk0CuLrC_9vNB3iAy29?usp=sharing)

**Comment by Joulinar** [comment]
Hi,

many thanks for your message. Just for clarification. Do you have the issue with DietPi or with Kali?

**Comment by elitex45** [comment]
@Joulinar thank you for your reply i am using Kali , the Wifi adopter works fine with Windows 10 but they won't work with Kali Linux

**Comment by Joulinar** [comment]
hi, well not sure if your are in the right GitHub. We are supporting DietPi and not Kali 😃

**Comment by elitex45** [comment]
@Joulinar can u tell me where can i find the solution please

**Comment by Joulinar** [comment]
maybe you can ask your question at Kali Forum https://forums.kali.org/

**Comment by elitex45** [comment]
@Joulinar thank you so much

**Comment by Joulinar** [comment]
ok I will close the ticket if you agree.

**Comment by elitex45** [comment]
@Joulinar ok and thank you
