### ISSUE TITLE
DietPi-Banner | Proposal for stats

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#362]
Use case is:
- I use various locales, specifically en:US|UK|DE
- I use various dev machines with static IPs
- Just a proposal for how to go about adding useful login/head information?
- Displays IPv4/6 information along with hostname, locale, and uptime -s

![dietpi-login-stats-proposal](https://cloud.githubusercontent.com/assets/10519408/15630733/3c2d7982-2515-11e6-908d-fbc2bc534bbb.PNG)

Attached is the altered code as this is - IMHO - not valid for any commit, but for review of @Fourdee to consider.

Cheers!
[dietpi-banner.txt](https://github.com/Fourdee/DietPi/files/288080/dietpi-banner.txt)

**Comment by Fourdee** [comment]
Yep, i think we can add some of these in. Although the banner would need cleaning up (move stuff around). 

I think these should be in:
- Uptime
- IPv4
- IPv6

The items i think might be useful, but not necessary:
- Hostname

The items i personally feel shouldnt be there:
- Locale. Maybe we could scrape the current locale and add that to `dietpi-config` language menu instead?

**Comment by Fourdee** [comment]
Just an idea, maybe we could do a `dietpi-sysinfo` script. Similar to cpu  `dietpi-cpuinfo`? Instead of filling up the banner? Then we can add as much info as we want :)

**Comment by xenfomation** [comment]
I completely agree, @Fourdee -- I hated filling up the screen, especially when using SSH/Terminal access.  Obviously I am cooking with NASA rocket fuel this weekend, so I think I can definitely cook something up -- even something with a webhook so one could poke, say:

http://myhost.mydomain:1234
(prompts for authentication and that is the only stateful bit!)

Prototypes will be sent your way after I look at the backlog I have :-)

**Comment by Fourdee** [comment]
I want to keep the banner lightweight and clean as possible. We currently have the IP address in there. Adding more stats means more processing and more mess.

We also have dietpi-cloudshell stats for those users who want it: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=20#p204

Marking as closed. Please reopen if required.
