### ISSUE TITLE
Stub | ViFM to Software Additional

### ISSUE THREAD

**Issue by xenfomation** [MichaIng/DietPi#363]
Per work on #295 I had left out ViFM as a command-line file manager.
In testing my backlog, I have created this ticket to track the original ticket and additional software that was intended to be added.

**Comment by xenfomation** [comment]
Per work on #151 - testing addition of ViFM for CLI-based file manager
![vimfm-test1](https://cloud.githubusercontent.com/assets/10519408/15631487/e52aa9f4-253a-11e6-8473-33b44f610d92.PNG)

**Comment by xenfomation** [comment]
@Fourdee -- for tickets we have arranged the commit -> pull request, do I need to assign them back to you for testing, etc?  Just want to ensure I am following protocol

Cheers!

**Comment by Fourdee** [comment]
@xenfomation 
Just send a pull request, make a note of whats been changed/added, then put a @fourdee in there. I'll then take a look :+1:

**Comment by Fourdee** [comment]
Additional implementation and testing for reference: https://github.com/Fourdee/DietPi/pull/364

**Comment by Fourdee** [comment]
Done. Marking as closed.
