### ISSUE TITLE
DietPi-Software | Node.js: taaem installer now completely broken

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#3650]
https://github.com/taaem/nodejs-linux-installer/blob/master/node-install.sh#L13

This curl check is now doomed to fail since nodejs.org has HTTPS redirect enabled (now) which makes curl output being empty without `-L` option.

My PR fixes this by using HTTPS, however the `-L` open additionally makes sense as file structure might change.

For now I'll switch to my fork, probably integrate this completely into dietpi-software, if taaem does not maintain it anymore.

**Comment by MichaIng** [comment]
MOTD live patch is up:
```
[[ -w '/boot/dietpi/dietpi-software' ]] && grep -q taaem /boot/dietpi/dietpi-software && sed -i 's/taaem/MichaIng/' /boot/dietpi/dietpi-software
```

**Comment by marius86ar** [comment]
not working

**Comment by MichaIng** [comment]
Bug in my MOTD hack, please fix with:
```
rm /run/dietpi/.dietpi-motd
curl -sSfL https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi/dietpi-software > /boot/dietpi/dietpi-software
sed -i 's/taaem/MichaIng/' /boot/dietpi/dietpi-software
```

**Comment by MichaIng** [comment]
I'll mark this as closed. Own script works fine, I'll give taaem some time to react before merging code into `dietpi-software`.
