### ISSUE TITLE
Dietpi-Software didn’t open

### ISSUE THREAD

**Issue by FrostyMisa** [MichaIng/DietPi#3652]
#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=31
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'`
- Distro version | `buster`
- Kernel version | `Linux Pi4 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux`
- SBC model | `RPi 4 Model B (armv7l)`
- Power supply used | Original 5,1V 3A
- SDcard used | (USB SSD Verbatim Store 'n' Go 120GB)

#### Steps to reproduce

```

root@Pi4:~# dietpi-software
/boot/dietpi/dietpi-software: line 6594: syntax error: unexpected end of file

```

#### Expected behaviour

Command will run Dietpi software

#### Actual behaviour

Syntax error 

#### Extra details

Update to v6.31.2, reboot and this happened

**Comment by MichaIng** [comment]
Bug in my MOTD hack, please fix with:
```
rm /run/dietpi/.dietpi-motd
curl -sSfL https://raw.githubusercontent.com/MichaIng/DietPi/master/dietpi/dietpi-software > /boot/dietpi/dietpi-software
sed -i 's/taaem/MichaIng/' /boot/dietpi/dietpi-software
```

**Comment by FrostyMisa** [comment]
Good job, it’s working again 🙃
You are the best!

**Comment by MichaIng** [comment]
Please also remove the stored MOTD to refresh on next banner print: `rm /run/dietpi/.dietpi-motd`

**Comment by marius86ar** [comment]
working now

**Comment by FrostyMisa** [comment]
```

root@Pi4:~# rm /run/dietpi/.dietpi-motd
rm: cannot remove '/run/dietpi/.dietpi-motd': No such file or directory

```

**Comment by MichaIng** [comment]
All fine if the file is not present 🙂.

**Comment by MichaIng** [comment]
I mark this as closed, as there shouldn't be any more effected users.
