### ISSUE TITLE
DietPi Upgrade to v6.31.2 Failed

### ISSUE THREAD

**Issue by mprince28117** [MichaIng/DietPi#3655]
#### Details:
- Date           | Mon Jul  6 10:11:45 EDT 2020
- Bug report     | ed987da7-8247-4ac6-ac0e-f58a33c89e02
- DietPi version | v6.30.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 3 Model B+ (armv7l) (ID=3)
- Kernel version | Linux DIETPI 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
- Distro         | stretch (ID=4,RASPBIAN=1)
- Command        | apt-get -qq --allow-change-held-packages install ./36.deb
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
E: Unable to correct problems, you have held broken packages.
```

**Comment by Joulinar** [comment]
Hi,

many thanks for your report. Looks like you have not finished package installations from the past. The error message is created by `dietpi-software`, pointing to an `squeezelite` (software ID 36) installation. Are you sure this is happening during `dietpi-update`? Pls can you run `apt update && apt upgrade`

**Comment by mprince28117** [comment]
Yes, I will.  I first encountered this error during a dietpi-upgrade command.  I had another sd card with the image installed and could not complete the upgrade there either.  I've gone back and loaded an "original" image from the dietpi forum.  Let me try loading that SD card and see if I can upgrade to the latest version from there.

**Comment by MichaIng** [comment]
> Are you sure this is happening during dietpi-update?

During dietpi-update we reinstall/upgrade SqueezeLite, so this is thinkable. Lets check the full output:
```
cd /tmp
wget https://dietpi.com/downloads/binaries/stretch/squeezelite_armv7l.deb
apt install ./squeezelite_armv7l.deb
```

**Comment by Joulinar** [comment]
@MichaIng 

> During dietpi-update we reinstall/upgrade SqueezeLite, so this is thinkable. Lets check the full output:

But than I would expect the error message above created bei `dietpi-update`. But it's stating `dietpi-software`

`Software title | DietPi-Software`

**Comment by MichaIng** [comment]
We do software updates through dietpi-software reinstalls. Would be a huge overhead to add the whole procedure to the updater patch file.

The prints to not contain parent script names, although this would be actually nice, basically an error stack trace.
____________
To give some insights: https://github.com/MichaIng/DietPi/blob/master/dietpi/patch_file#L2440-L2473
- During incremental patches we collect the software titles that need to be reinstalled (to avoid incompatibilities) or where the reinstall is assumed to be risk/pain-less or the implied update beneficial enough.
- After last incremental patch, we apply all collected reinstalls via single `dietpi-software` call.

**Comment by Joulinar** [comment]
ok understood.

**Comment by mprince28117** [comment]
Apologies for slow response.  My pi stopped responding, and I am formatting and re-imaging an SD card so that I can carry forward with this.  It will have whatever version of dietpi is in the image from the dietpi website.

**Comment by MichaIng** [comment]
On first boot, it will be auto-updated to v6.32.1, so when you install SqueezeLite it will be the new version right from the start. However if there were some general package incompatibilities, the error message might look the same, like the suggested debug steps: https://github.com/MichaIng/DietPi/issues/3655#issuecomment-654272427

I'll check in on my Pi as well now.

**Comment by MichaIng** [comment]
Found it:
```
The following packages have unmet dependencies:
 squeezelite : Depends: libmpg123-0 (>= 1.23.8-1+b1) but 1.23.8-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This is the problem when building ARMv7 packages on Debian, which are pulled on ARMv7 RPi models. 99,9% match, but this `+b1` version was never ported over to Raspbian:
- http://raspbian.raspberrypi.org/raspbian/pool/main/m/mpg123/
- https://deb.debian.org/debian/pool/main/m/mpg123/
- https://packages.debian.org/stretch/libmpg123-0

I'll remove the part from the dependency version string, hang on.

**Comment by MichaIng** [comment]
Fixed it, package repacked, install/update should now succeed.
Checking on Raspbian Buster...
... fine there 👍.
____________
Reminder to myself: Always test ARMv7 packages on RPi/Raspbian as well.
I was actually thinking to always pull ARMv6 packages with RPi+Raspbian to assure everything is compiled for the same architecture and against the exact same library versions. However ARMv7 RPi models might loose some benefits. Mid-term I plan to release an ARMv7 Debian-based RPi image for this one ARMv7 RPi2 v1.1, so together with 64-bit image all RPi models can then run on the highest architecture they actually support.

**Comment by mprince28117** [comment]
Excellent, many thanks.  I will boot up my pi in a bit (SD still formatting) and make sure everything comes up OK.

**Comment by mprince28117** [comment]
Was able to install upgrade without errors, now to set everything up again as I had to reload the image...:)
