### ISSUE TITLE
DietPi-Software | Python 3 and Python 2 dependants

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#3656]
We need to get rid of installing EOL Python 2, so we need to:
1. Clearly separate Python 2 pip and Python 3 pip
2. List Python 2 dependants and check whether there are Python 3 migrations available, else check or bring this to discussion on software devs.
3. If there is no plan for a Python 3 migration, drop support for affected software.
________
This includes #3627 which is solved by separating Python 2 pip and Python 3 pip.

**Comment by MichaIng** [comment]
- 🈯 Mopidy: Python 3 from Buster on, now as well for ARMv8/arm64. Due to outdated Python 3(.5) on Stretch, Mopidy v3 cannot run on Stretch, same as with OctoPrint below.
    - All we can do. Issue solves itself when dropping support for Debian Stretch, which contains many other packages that use/required Python 2 anyway.
- 🈯 emonPi: We use an own Python 2 fork currently but upstream is already Python 3 compatible. Larger project to migrate since I have never uses this piece of software or even the hardware part. Help and testing required to hopefully do DietPi-adjustments within DietPi-Software so that we can pull from the original upstream repo.
    - [x] **PR up: #4357**
- 🈺 MotionEye: Work in progress on `python3` branch: https://github.com/ccrisan/motioneye/tree/python3
- 🈯 HTPC-Manager:
  - Original project dead: https://github.com/styxit/HTPC-Manager
  - Fork (that we use) doesn't show much progress lately, Python 3 discussion doesn't look promising: https://github.com/Hellowlol/HTPC-Manager/issues/611
If anyone is interested in this piece of software, contribution and fresh wind seems to be desperately required 🚀 💪!
  - **EDIT: Python 3 fork available, requires testing: https://github.com/gmiranda/HTPC-Manager**
  - **EDIT2: PR up to test migration: https://github.com/MichaIng/DietPi/pull/3735**
  - **EDIT3: Migration done, I'll help maintaining this project a bid, but more active contributors required!**
- 🈯 SABnzbd: Python 3 release in RC1 stage, expected to be released before DietPi v6.32: https://github.com/sabnzbd/sabnzbd/releases **EDIT: stable and done**
- 🈴 CouchPotato: Not Python 3 compatible, no issue/request so far, even cementation: https://github.com/CouchPotato/CouchPotatoServer/commit/ab25630f8e2cb4f0868ad808297e58142a9e6f5a
Request for Python 3 migration desperately required as I cannot see ANY steps in this direction so far 👎: No GitHub issues enabled, forum [down](https://couchpota.to/forum/)
    - [x] Mail sent to author to evaluate development status
- 🈯 Google AIY
- 🈯 OctoPrint: Supports Python 3 but not Python 3.5 (Stretch), hence on Stretch we must stay with Python 2.
    - All we can do. Issue solves itself when dropping support for Debian Stretch, which contains many other packages that use/required Python 2 anyway.
- 🈺 Firefox Sync Server: Planned switch to Rust, however not yet production ready. So there will not be a Python 3 version, instead we'll migrate to the Rust version, once it is stable or at least late beta stage: https://github.com/mozilla-services/syncserver/issues/165#issuecomment-584584965 (probably not the nicest post but it contains all relevant links)
- 🈯 WebIOPi: No development since 2015: http://sourceforge.net/projects/webiopi/files/
  - Although, there is a fork which seems to have even Python 3 support? As well stopped development > 2 years ago: https://github.com/thortex/rpi3-webiopi
  - The newest fork is used now, being Python 3 compatible: https://github.com/MichaIng/DietPi/pull/4310
- 🈯 Tautulli: Python 3 support ~from 3.6 up, hence needs to stay Python 2 on Stretch~ **EDIT: Works just fine on Stretch with Python 3.5 👍**
    - [x] Implement switch to Python 3 on Buster+: #3784
- 🈯 RPi.GPIO: We simply install both, the Python 2 and Python 3 packages. The Python 2 variant is currently required for WebIOPi, but could be skipped otherwise.
  - **EDIT: Only the Python 3 package is installed now: https://github.com/MichaIng/DietPi/pull/4310**

**Comment by maartenlangeveld** [comment]
Samba server (dietpi-sofware: 96) installs Python2.7

**Comment by MichaIng** [comment]
Good find. On Bullseye it pulls Python 3: https://packages.debian.org/bullseye/samba
Until Debian Buster there are many cases where packages pull Python 2 as dependency:
```
2020-09-21 14:50:19 root@VM-Buster:/# apt rdepends python | wc -l
2573
```
This will not change. But at least where we have control, we should try to migrate until Bullseye release, although it currently ships a compatibility package, now called `python2`: https://packages.debian.org/bullseye/python2

**Comment by MichaIng** [comment]
Okay, all items where we can currently do something about have been addressed. In case of MotionEye and Firefox Sync Server, we need to wait until upstream migrations have been finished/become stable, but we'll address those in dedicated issues.

CouchPotato will likely (and sadly!) be removed from the list, as it doesn't seem to be developed anymore. Dealt with in dedicated issue as well: #4323
