### ISSUE TITLE
Error deitpi-software last update

### ISSUE THREAD

**Issue by gael1980** [MichaIng/DietPi#3677]
#### Required Information
- DietPi version : 
G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=31
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version : Buster
- Kernel version : Linux DietPi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
- SBC model : RPi 3 Model B (armv7l)
- SDcard used : SanDisk 16 Go

#### Additional Information (if applicable)
- Software title : Dietpi-software
- Was the software title updated to last version of dietpi

- Bug report ID : 8f31027a-ac32-4067-ba7e-45fc26a5a55a

#### Expected behaviour
since the last update, I can't launch dietpi anymore.
root@DietPi:~# dietpi-software
/boot/dietpi/dietpi-software: ligne 6594: erreur de syntaxe : fin de fichier prématurée

**Comment by Joulinar** [comment]
Hi,

Many thanks for your report. Should be similar to this. #3652 
A fix is provided as well.

**Comment by gael1980** [comment]
Yeah, it's the same problem.
the solution works perfectly
Thank you for your help
