### ISSUE TITLE
DietPi-Software | Desktops: Add browser selection dialog

### ISSUE THREAD

**Issue by TamaTamaGoGo** [MichaIng/DietPi#3683]
### Add Browser install selection dialog when install Desktop
**DietPi-Software | Desktops: Add browser selection dialog**
*Suggested by owner.*
Thanks for owner!

#### Describe of request:

Add Software install dialog when install Desktop.
Like for example
 - [FireFox-esr] firefox-esr
 - [Chromium] ?
 - [Midori] midori
 - [epiphany] epiphany-browser

Detail is here!
https://github.com/MichaIng/DietPi/issues/3683#issuecomment-660582344

#### By Owner’s post

https://github.com/MichaIng/DietPi/issues/3683#issuecomment-660474909
> #### Background:
> * Currently we pre-install Firefox with all desktops.
> * It is not visible on all desktops, i.e. the default browser icon is there and opens Firefox, but no Firefox icon is shown, but hidden in menu instead.
> * As we have Chromium as separate install option, when selected, users have two browsers installed.
> 
> #### Implementation ideas:
> * Make Firefox a dedicated software title with own ID, like Chromium is. This also enables us to implement some enhancements, e.g. having browser cache in tmpfs or on external drive to enhance performance and reduce SD card writes.
> * Browser preference system like we have for webservers, including the option "none".
> * Add interactive preference selections for both preference systems when a desktop respectively a webserver dependant is installed. I think we can even derive if a preference has been actively chosen before to then skip the obsolete dialog.
> * Add further browsers by times.

**Another details will add here when some idea appear or good idea at discuss**

**Comment by MichaIng** [comment]
#### Background:
- Currently we pre-install Firefox with all desktops.
- It is not visible on all desktops, i.e. the default browser icon is there and opens Firefox, but no Firefox icon is shown, but hidden in menu instead.
- As we have Chromium as separate install option, when selected, users have two browsers installed.

#### Implementation ideas:
- Make Firefox a dedicated software title with own ID, like Chromium is. This also enables us to implement some enhancements, e.g. having browser cache in tmpfs or on external drive to enhance performance and reduce SD card writes.
- Browser preference system like we have for webservers, including the option "none".
- Add interactive preference selections for both preference systems when a desktop respectively a webserver dependant is installed. I think we can even derive if a preference has been actively chosen before to then skip the obsolete dialog.
- Add further browsers by times.

**Comment by TamaTamaGoGo** [comment]
[NOTE]
Share with Owner (@MichaIng ) and Author ( @TamaTamaGoGo )

# Browser Software list

---
Software Name: FireFox-esr
Description: The popular browser at world
How-to-install: apt-get install firefox-esr

---

---
Software Name: Chromium
Description: The old version of Chrome (the popular browser as FireFox)
How-to-install: apt-get install chromium?

---

---
Software Name: Midori
Description: The lite browser but have many functions.
How-to-install: apt-get install midori

---

---
Software Name: epiphany
Description: The lite browser and have many functions as Midori.
How-to-install: apt-get install midori

---

**Comment by TamaTamaGoGo** [comment]
I know how to use tmpfs for Chromium
Type it and edit /etc/fstab

    sudo nano /etc/fstab

And add

    tmpfs  /home/pi/.cache/chromium/Default/Cache  tmpfs  defaults,size=768m,noatime,mode=1777  0  0

By, https://webcache.googleusercontent.com/search?q=cache:vGVSsTDRqsYJ:https://www.fabshop.jp/%25E3%2580%2590step-28%25E3%2580%2591chromium%25E3%2581%25AE%25E3%2582%25AD%25E3%2583%25A3%25E3%2583%2583%25E3%2582%25B7%25E3%2583%25A5%25E3%2582%2582ramdisk%25E3%2581%25A7%25E5%25BF%25AB%25E9%2581%25A9%25E3%2583%2596%25E3%2583%25A9%25E3%2582%25A6%25E3%2582%25B8%25E3%2583%25B3%25E3%2582%25B0/+

**Comment by MichaIng** [comment]
tmpfs cache for Chromium (browsers in general) or on low RAM devices cache on external drive (i.e. dietpi_userdata) is a great idea, however its again a separate topic, lets concentrate on a browser selection for now 😉. Also additional browsers are a separate topic, especially when we want to implement nicely (e.g. according to cache, probably GPU acceleration).

> Description: The old version of Chrome

Chromium is the underlying open source project, while "Chrome" is just Googles Chromium-based browser, like Opera, Brave, Microsofts Chromium Edge, Vivaldi etc, all are Chromium browsers. On Debian/Raspbian you get a very basic Chromium version without any branding or additions, indeed being visually close to "Chrome" but e.g. without their specific telemetry additions.

**Comment by TamaTamaGoGo** [comment]
Hm...?
What should we describe shortly...

**Comment by TamaTamaGoGo** [comment]
With some researching I found these things

**Midori**
YouTube said YouTube couldn't find corresponding video type.

**epiphany**
YouTube said YouTube couldn't find corresponding video type.

When I installed epiphany browser with following this command
`sudo apt-get install epiphany-browser`

epiphany doesn't appeared to Application Menu.

**Comment by MichaIng** [comment]
Done: #4314
For now Firefox has become an independent software option for this but otherwise no new browser has been implemented yet. `epiphany-browser` was an idea, Brave and Opera for x86_64. But I'll now concentrate on the other planned tasks for v7.2.
