### ISSUE TITLE
Error messages at boot

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#3693]
When booting my RPi-zero-w (with Buster and kernel 5.4) I get following two error messages:

`vc_vchi_sm_init: failed to open VHCI service (-1)`
`[vc_sm_connected_init]: failed to initialize shared memory service`

Is this trouble some or harmless, can or should I do something about it?

**Comment by Joulinar** [comment]
Hi,

many thanks for your message. something that can be ignored. 

for reference an older forum post https://dietpi.com/phpbb/viewtopic.php?f=11&t=6012

**Comment by maartenlangeveld** [comment]
@Joulinar, thanks !

**Comment by Joulinar** [comment]
ok, I will close this issue, feel free to reopen if needed.
