### ISSUE TITLE
dietpi-software :- Updating or reinstalling - reports No Internet

### ISSUE THREAD

**Issue by MDAR** [MichaIng/DietPi#3702]
#### Details:
- Date           | Fri Jul 31 15:45:34 BST 2020
- DietPi version | v6.31.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Meveric
- Hardware       | Odroid C2 (aarch64) (ID=12)
- Kernel version | Linux DietPi 3.16.57+ #1 SMP PREEMPT Sun Aug 19 15:27:56 CEST 2018 aarch64 GNU/Linux
- Distro         | stretch (ID=4)
- Command        | ./node-install.sh
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

I can run 
apt-get update 
apt-get upgrade
happily from the command line and perform all other tasks.

But the dietpi-update fails and reports no internet

As does trying to upgrade Node-RED

#### Actual behaviour:

Scripts fail and report "No Internet"

#### Extra details:
is supect it is failing to download a particular file, rather than not getting access to the internet

#### Additional logs:
```
Node Linux Installer by www.github.com/taaem
Running as Root User
Get Latest Version Number...
ERROR: No Internet Connection
```
######

[  OK  ] DietPi-Software | Free space check: path=/ | available=12860 MiB | required=500 MiB
[  OK  ] DietPi-Software | DietPi-Userdata validation: /mnt/dietpi_userdata
[  OK  ] DietPi-Software | Checking network connectivity
[  OK  ] DietPi-Software | Checking DNS resolver
[  OK  ] Network time sync | Completed
[ SUB1 ] DietPi-Services > unmask
[  OK  ] DietPi-Services | unmask : nmbd
[  OK  ] DietPi-Services | unmask : smbd
[  OK  ] DietPi-Services | unmask : cron
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : smbd
[  OK  ] DietPi-Services | stop : nmbd

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Update & upgrade APT

[ INFO ] DietPi-Software | APT update, please wait...
Hit:1 http://fuzon.co.uk/meveric all InRelease
Hit:2 http://fuzon.co.uk/meveric stretch InRelease
Ign:3 https://deb.debian.org/debian stretch InRelease
Hit:4 https://deb.debian.org/debian stretch-updates InRelease
Hit:5 https://deb.debian.org/debian-security stretch/updates InRelease
Ign:6 https://dl.bintray.com/openhab/apt-repo2 stable InRelease
Hit:7 https://deb.debian.org/debian stretch-backports InRelease
Hit:8 https://deb.debian.org/debian stretch Release
Get:9 https://dl.bintray.com/openhab/apt-repo2 stable Release [6051 B]
Hit:9 https://dl.bintray.com/openhab/apt-repo2 stable Release

[  OK  ] DietPi-Software | APT upgrade

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Checking for prerequisite software

[ INFO ] DietPi-Software | Build-Essentials will be installed
[ INFO ] DietPi-Software | Node.js will be installed

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing Build-Essentials: common packages for compile

[ INFO ] DietPi-Software | APT install for: build-essential automake, please wait...
[  OK  ] DietPi-Software | APT install for: build-essential automake

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Installing Node.js: javascript runtime

[  OK  ] DietPi-Software | Checking URL: https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh
[  OK  ] DietPi-Software | wget https://raw.githubusercontent.com/taaem/nodejs-linux-installer/master/node-install.sh
[  OK  ] DietPi-Software | mkdir -p /usr/local
[  OK  ] DietPi-Software | chmod +x node-install.sh
[ INFO ] DietPi-Software | ./node-install.sh, please wait...
Node Linux Installer by www.github.com/taaem
Running as Root User
Get Latest Version Number...
ERROR: No Internet Connection
[FAILED] DietPi-Software | ./node-install.sh

####

Running the ./node-install.sh returns this

```
root@DietPi:~# ./node-install.sh
Node Linux Installer by www.github.com/taaem
Running as Root User
Get Latest Version Number...
ERROR: No Internet Connection
```

Just running this line, doesn't fetch anything

`curl http://nodejs.org/dist/latest/`

**Which seems to be pivotal to the success of the other IF statements in the script, as the version number is derived from the download.**

Changing the curl command so that it addresses a HTTPS site, allows the script to get a little further.

`curl https://nodejs.org/dist/latest/`

But it fails with this text

```
root@DietPi:~# ./node-install.sh
Node Linux Installer by www.github.com/taaem
Running as Root User
Get Latest Version Number...
Done
Downloading latest stable Version node-v14.7.0-linux-arm64.tar.gz...
Done
Installing...

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Couldn't extract tar

```

If I download the file manually to /tmp and cp it to node.tar.gz and disable the curl command in the script, it states that the installation finished.

**Comment by MDAR** [comment]
HOWEVER

Node-RED hasn't been installed / updated.


######

Curiously, it doesn't matter how I edit /root/node-install.sh and add in silly echo commands for example, it looks like dietpi-software is calling a different (unedited) version

**Comment by Joulinar** [comment]
Hi,

Many thanks for your report. This is already known and should be similar to #3671 

Usually a quick fix should have been provided by MOTD.

**Comment by MichaIng** [comment]
Quick fix:
```
sed -i 's/taaem/MichaIng/' /boot/dietpi/dietpi-software
```
I mark this as closed 😉.

**Comment by MDAR** [comment]
Thank you so much 😃 


This has fixed it perfectly 😄 


The only thing to note is that because I uninstalled then, reinstalled Node-RED, I've lost all the library and flows.

(I have backups, so it's not a major issue)
