### ISSUE TITLE
Update all online documentation referencing user data locations to /mnt/dietpi_userdata

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#371]
> https://github.com/Fourdee/DietPi/issues/334#issuecomment-222503304

```
/root
/mnt/usb1_1
```

Is now replaced with `/mnt/dietpi_userdata`

http://dietpi.com/phpbb/viewtopic.php?f=8&t=5
Nice big job for me lol.

**Comment by k-plan** [comment]
@Fourdee 

> Nice big job for me lol.

another "nice job" will be to update  this: [DietPi-Config | Feature rich config tool for your device](http://dietpi.com/phpbb/viewtopic.php?f=8&t=63)

Sorry ...  :smile:

**Comment by Fourdee** [comment]
@k-plan 
:+1: 
Updated :dancer: http://dietpi.com/phpbb/viewtopic.php?f=8&t=63

**Comment by k-plan** [comment]
@Fourdee 

really good and very quick realisation. :smile: 
:100:  :+1: 

Thank you very much.

**Comment by xenfomation** [comment]
Noted for #271

**Comment by Fourdee** [comment]
Think i got all the references updated to `/mnt/dietpi_userdata` on forum docs. Will leave this open just in case @k-plan wants to kindly check :+1: :+1:  _wink wink_ hehe

**Comment by k-plan** [comment]
@Fourdee 

> Will leave this open just in case @k-plan wants to kindly check 👍 👍 wink wink hehe

---

http://dietpi.com/phpbb/viewtopic.php?p=55#p55
- In the address bar at the top type ftp://root:`raspberry`@192.168.0.100 press enter.

Accessing ProFTP with a FTP Client:
username = root
password = The same as your root login password. Default is `dietpi`
address = Your ip address (eg: 192.168.0.100)

---

http://dietpi.com/phpbb/viewtopic.php?p=68#p68

DietPi will automatically save/update log file data to disk every hour `/root/logfile_storage`.

---

http://dietpi.com/phpbb/viewtopic.php?p=188#p188

```
cd /root
./weaved_setup.bin

```

??

---

http://dietpi.com/phpbb/viewtopic.php?p=1066#p1066

```
cd /root/wiringPi*
ls
```

??

---

**Comment by Fourdee** [comment]
@k-plan 

>  ftp://root:raspberry@192.168.0.100 

Good spot :+1: 

> DietPi will automatically save/update log file data to disk every hour /root/logfile_storage

Yep, thats right. DietPi-Ramlog mode 2

> cd /root
> ./weaved_setup.bin

Yep, required so user can enter their login creds for their weaved account.

> cd /root/wiringPi*
> ls

Yep, this is where WiringPi is installed. It contains samples, examples the user can run. As well as docs.

**Comment by k-plan** [comment]
@Fourdee 

sorry, so fare no time to test on a clean install v.119, but  ...

> ```
> /root
> /mnt/usb1_1
> ```
> 
> Is now replaced with `/mnt/dietpi_userdata`

 . . .

> > DietPi will automatically save/update log file data to disk every hour `/root/logfile_storage`
> 
> Yep, thats right. DietPi-Ramlog mode 2

In v119 now it will be:  `/mnt/dietpi_userdata/logfile_storage` ?

> ```
> cd /root
> ./weaved_setup.bin
> ```

will be:

```
cd /mnt/dietpi_userdata
./weaved_setup.bin
```

and:

```
cd /mnt/dietpi_userdata/wiringPi*
ls
```

... what will be the question. But I see, I have to test it be myself ... 😉 

😄

**Comment by Fourdee** [comment]
> In v119 now it will be: /mnt/dietpi_userdata/logfile_storage ?

Nope. It will stay as /root/logfile_storage

> cd /mnt/dietpi_userdata/wiringPi*
> ls

User data is classed as:
- bittorrent downloads
- owncloud storage, 
- Fileservers default location (music/video folders)
- etc etc

**Comment by k-plan** [comment]
@Fourdee 

> User data is classed as:
> - bittorrent downloads
> - owncloud storage,
> - Fileservers default location (music/video folders)
> - etc etc

Aha ... that's the missing description. 😄 

So it means more: `/mnt/dietpi_user_application_storage_data` 

Suggestion: so please write this description somewhere in http://dietpi.com/phpbb/viewforum.php?f=8

Worry that I will not be the only one, who don't understand it instantly.

**Comment by Fourdee** [comment]
@k-plan 

> Suggestion: so please write this description somewhere in http://dietpi.com/phpbb/viewforum.php?f=8
> Worry that I will not be the only one, who don't understand it instantly.

Yep, it needs to be explained a little better in the docs :+1:

**Comment by Fourdee** [comment]
Further description improvements required:

> http://dietpi.com/phpbb/viewtopic.php?f=9&t=470#p2049

**Comment by Fourdee** [comment]
first run setup question updated:
![image](https://cloud.githubusercontent.com/assets/7077026/15858753/1d48c178-2cba-11e6-80e4-4b5279b7b583.png)

**Comment by Fourdee** [comment]
Ok, so, here goes :dancer: 

#### What is user data?

In DietPi, we class user data as:
- Data storage for applications. Some examples:
  - Ownclound data store.
  - BitTorrent downloads.
- The location where your fileserver choice will point to, if you install one (eg: Samba Server, Proftpd).
- The location where you can upload and store your media content, for other applications to use (eg: Kodi, Emby, Plex etc).

#### Where is my user data?

As of DietPi v120. For all future software you install in `dietpi-software`, you can access your user data with `/mnt/dietpi_userdata`. Regardless of where the data is physically stored, a symlink will automatically be created for you if needed.
To check where the physical location is, you can run the following command `readlink -f /mnt/dietpi_userdata`.

#### Can I move my user data to another location (eg: USB drive?)

Yes. 
Simply run `dietpi-software` and enter the "User data" menu option. Once there, simply select the location you wish to use, or select Manual for a custom location. You can also setup a dedicated USB drive, if one is not currently installed.
DietPi will also move your existing user data to your chosen location.

**Comment by Fourdee** [comment]
@k-plan

Hope this covers user data. If not, please let me know :+1: 

http://dietpi.com/phpbb/viewtopic.php?f=8&t=478&p=2087

During 1st run setup questions for DietPi
![image](https://cloud.githubusercontent.com/assets/7077026/15985444/e177ac94-2fe4-11e6-8a8c-9dde7d8cefa2.png)

**Comment by Fourdee** [comment]
@k-plan 
Also updated the new user data screen in dietpi-software with link:
![image](https://cloud.githubusercontent.com/assets/7077026/15985461/ce62660c-2fe5-11e6-902c-6034ccfe7a31.png)

**Comment by Fourdee** [comment]
I'll mark this as completed for now. 

I would appreciate your feedback @k-plan for any improvements, if you have them.
