### ISSUE TITLE
Uninstall failed

### ISSUE THREAD

**Issue by Aakhroot** [MichaIng/DietPi#3718]
#### Details:
- Date           | Sun Aug 16 20:00:50 BST 2020
- DietPi version | v6.31.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 3 Model B (armv7l) (ID=3)
- Kernel version | Linux DietPi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
- Distro         | buster (ID=5,RASPBIAN=1)
- Command        | apt-get -qq --purge autoremove
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by Joulinar** [comment]
Hi,

Many thanks for your message. Seems something went wrong during `apt uninstall`. Pls can you executed `apt --fix-broken install`

**Comment by MichaIng** [comment]
I mark this as closed due to missing reply. Feel free to reopen if required.

**Comment by Aakhroot** [comment]
Thanks. I had to reimage so could not reproduce.

**Comment by MichaIng** [comment]
Okay, no problem 🙂.
