### ISSUE TITLE
Error: Obtained server version value from github is invalid. Please try running dietpi-update again.

### ISSUE THREAD

**Issue by squirrelboot** [MichaIng/DietPi#372]
Hello,

I am having the same issue as [here](https://github.com/Fourdee/DietPi/issues/331). 
I used the fix [here](https://github.com/Fourdee/DietPi/issues/301). 
However, **this did not work**. 

Outputs:
cat /DietPi/dietpi.txt 
Was blank.

cat /DietPi/dietpi/.version
115

cat /DietPi/dietpi/dietpi-update
http://pastebin.com/CEYfauMQ

**Comment by Fourdee** [comment]
> cat /DietPi/dietpi.txt 
> Was blank.

@squirrelboot 

dietpi.txt should not be blank. The file also contains the `gitbranch` var that `dietpi-update` will use. So lets get that file back.

```
wget https://raw.githubusercontent.com/Fourdee/DietPi/master/dietpi.txt -O /DietPi/dietpi.txt
```

Now try running the update again.

**Comment by xenfomation** [comment]
I have tested this myself, but without the same results:

![test01](https://cloud.githubusercontent.com/assets/10519408/15767274/aad50cbc-2914-11e6-8320-157df29498dc.PNG)

![test02](https://cloud.githubusercontent.com/assets/10519408/15767289/c4a05250-2914-11e6-93cd-4482b9204997.PNG)

**Comment by Fourdee** [comment]
Will mark this as closed. Please reopen if required.

**Comment by WolfganP** [comment]
Just for statistics, it happened to me as well while on v126. dietpi.txt got corrupted somehow, the wget command above solved the issue and dietpi-update run without issues after.

**Comment by Fourdee** [comment]
@WolfganP 
Thanks for the info :+1: 

Did you by any chance save a copy of the corrupted dietpi.txt? It may give us some clues as to what caused it to corrupt.
