### ISSUE TITLE
proftpd slow ftp login

### ISSUE THREAD

**Issue by bbsixzz** [MichaIng/DietPi#3727]
I noticed my SSH logins were a lot faster than my FTP logins (RPi4).

I added `UseReverseDNS          off` to `/etc/proftpd/proftpd.conf` and it made a huge difference.

Maybe you want to consider adding this?

[EDIT]

According to [ProFTPD: Best Common Practices](http://www.proftpd.org/docs/howto/BCP.html):

> Performance Tuning
> When configuring a proftpd for performance, here are some settings to try. First, make sure that you have ident and reverse DNS lookups disabled:
> 
> ```
>   IdentLookups off
>   UseReverseDNS off
> ```
> 
> By default, both are done for each new FTP session, and, depending on the response time from both identd and DNS servers, this can add a noticeable delay during the login process.

**Comment by MichaIng** [comment]
Many thanks, jep makes totally sense, reverse DNS lookups seem not reasonable here, in case the raw IP is the more precise information if one needs to check the access log.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/5fba8dd3877c83c6e9c8af5450337aaeec3f5a7b
Changelog: https://github.com/MichaIng/DietPi/commit/9726727f949cf4f2a32bd026974e15c884b18c20
