### ISSUE TITLE
Allow resuming (append/restart) of FTP transfer using ProFTPD

### ISSUE THREAD

**Issue by bbsixzz** [MichaIng/DietPi#3729]
I've added the following to `/etc/proftpd/proftpd.conf` to enable this functionality.

```
AllowStoreRestart On
AllowRetrieveRestart On
```

Would you consider adding this to the next release?

**Comment by MichaIng** [comment]
`AllowRetrieveRestart` is btw On by default.

When resuming uploads is enabled, one should not allow anonymous uploads: http://www.proftpd.org/docs/directives/linked/config_ref_AllowStoreRestart.html
But this is disabled by default, so not an issue for your default config IMO.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/91b6cb6346d90d4d2bac4a185c1544041158ef2e
Changelog extension: https://github.com/MichaIng/DietPi/commit/9561e3a72e34c71c592b811ccd0e569cf4920197
