### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by hai3009** [MichaIng/DietPi#3765]
[###](url) Creating a bug report/issue

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...
2. ...

#### Expected behaviour

- ...

#### Actual behaviour

- ...

#### Extra details

![捕获](https://user-images.githubusercontent.com/60032719/92423339-5f633a80-f1b3-11ea-950d-d4ce3354daf0.PNG)

- ...

**Comment by Joulinar** [comment]
Hi,

Many thanks for your report. Do you use PiHole? Because you are resolving Github with 0.0.0.0. Looks like your DNS request is blocked somewhere.

**Comment by hai3009** [comment]
thanks!Don't know how to use it PiHole

**Comment by Joulinar** [comment]
If you use PiHole, login to web interface, search on the logs if something from GitHub is blocked. If yes, put it to Whitelist.

**Comment by MichaIng** [comment]
Jep indeed this is not the first time that Pi-hole (i.e. one of the available non-standard block lists) blocks `githubusercontent.com`, a shame.

But just to be sure it it really Pi-hole, as faulty ISP or local DNS servers or hosts file can do the same thing of course:
```
cat /etc/resolv.conf
grep '0\.0\.0\.0' /etc/hosts
curl -IL --dns-servers 9.9.9.9 raw.githubusercontent.com
```
Feel free to mask any contained private information/IPs etc, I'm just interested if there is any related hosts entry and if the configured DNS server is a local network one (e.g. Pi-hole), one from ISP (e.g. assigned via DHCP) or a global one, like 9.9.9.9 (Quad9) or 1.1.1.1 (Cloudflare).

**Comment by hai3009** [comment]
When will the latest image download be released？

**Comment by Joulinar** [comment]
@hai3009 
what you mean? Or what do you looking for?

**Comment by MichaIng** [comment]
I'll now create a new image for RPi, but that will not solve your issue as this is not related to DietPi but a blocking list or firewall rule on your side 😉.

**Comment by Joulinar** [comment]
yep, last RPI image was released less than 2 month ago and it working fine. As already said, your issue seems to be some DNS blocking, aka PiHole 😉

**Comment by hai3009** [comment]
Thank you for your reply. I can only use dietpi first_ V6.18 is not upgraded

**Comment by Joulinar** [comment]
a new image will bring you to latest release DietPi v6.32.2, always.

But still, your issue on your very old/outdated V6.18 has nothing to do with DietPi. You are not able to complete your update, because there is something on your side who is blocking DNS resolution for `raw.githubusercontent.com`

**Comment by MichaIng** [comment]
New image uploaded, after 1-2 positive feedback I'll move it to stable downloads: https://dietpi.com/downloads/images/testing/DietPi_RPi-ARMv6-Buster.7z

**Comment by hai3009** [comment]
Thank you. The new image can be used normally.

**Comment by MichaIng** [comment]
Many thanks for testing and feedback! I mark this issue as closed then. Feel free to reopen if required.
