### ISSUE TITLE
rc.local default file

### ISSUE THREAD

**Issue by 2O23** [MichaIng/DietPi#3766]
Hello, i edited the rc.local file by wrong can some one send le the original one please ? thanks a lot.

**Comment by MichaIng** [comment]
The default basically does nothing, simply erase it and add the code you need or remove it completely. But if you insist in the original as shipped with Debian:
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
 
exit 0
```
Only informational comments and exist 😉.

**Comment by 4o4forbidden** [comment]
Thanks a lot sir !
