### ISSUE TITLE
Zerotier

### ISSUE THREAD

**Issue by cocoflan** [MichaIng/DietPi#3792]
Zerotier
 ZeroTier makes networking easy for everyone - anywhere.
 https://www.zerotier.com 
 https://github.com/zerotier
https://www.zerotier.com/download/ 

It is fully open source, without any (feature) limitation to free users.-->

https://www.zerotier.com/download/

 It is on the feathub page.

**Comment by MichaIng** [comment]
Many thanks for your request.

Remember that you already opened it a while ago 😄: #2843
I close this in favour of the old issue which contains some more info and discussion around it.

**Comment by cocoflan** [comment]
Ok, still hope it will get in the software list!
