### ISSUE TITLE
How to upgrade Emby server to the latest version

### ISSUE THREAD

**Issue by quyentruong** [MichaIng/DietPi#3803]
My pi 4 currently run version 4.4.3.0. I saw in the api https://api.github.com/repos/MediaBrowser/Emby.Releases/releases/latest.
The latest version is 4.5.1.0. I don't see any option to upgrade it. Please help.

**Comment by Joulinar** [comment]
Hi,

many thanks for your request. Just follow instructions on our DietPi user guide https://dietpi.com/phpbb/viewtopic.php?p=1789#p1789

`dietpi-software reinstall 41`
