### ISSUE TITLE
Issue installing octoprint

### ISSUE THREAD

**Issue by vcliment89** [MichaIng/DietPi#3816]
#### Details:
- Date           | Thu Oct  8 11:16:49 CDT 2020
- Bug report     | 52b91532-4b83-4ca0-b448-e35bbaf977cc
- DietPi version | v6.32.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Armbian
- Hardware       | PINE A64 (aarch64) (ID=40)
- Kernel version | Linux DietPi 5.4.28-sunxi64 #20.02.7 SMP Sat Mar 28 17:25:10 CET 2020 aarch64 GNU/Linux
- Distro         | buster (ID=5)
- Command        | pip3 install -U .
- Exit code      | 127
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
/boot/dietpi/func/dietpi-globals: line 930: /usr/bin/pip3: No such file or directory
```

**Comment by MichaIng** [comment]
<s>Not sure currently why on v6.32 the install would even call pip3, but with v6.33 we migrated the OctoPrint install to Python 3.
You can test it with the beta:</s>
**EDIT: Ah sorry, we migrated to Python 3 with v6.32 already, but still, you can test the current beta and I'll have a look into the code to be sure:**
```
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=beta' /boot/dietpi.txt
dietpi-update 1
dietpi-software install 153
```
_________
Okay, from the code, everything is as it should be. Also that your error message contains even the command path `/usr/bin/pip3` shows that it was found and hashed like that before. Also the pip3 install is error handled, so something quite strange happened on your system. I'd try it with the above, but please report back if you run into the same or similar issues, then we need to have a closer look what is going on.

**Comment by Joulinar** [comment]
Hi,

DietPi v6.33.3 is out now. I guess installation should be working. 

@vcliment89 
pls could you try again and report if there are issues still. thx

**Comment by vcliment89** [comment]
Yes, I'm now able to install octoprint. Thanks!

**Comment by Joulinar** [comment]
@MichaIng 
Do you like to keep this open for further investigation? Or can it be closed?

**Comment by MichaIng** [comment]
Just ran another test and all works as expected. Okay to have it closed and we'll keep it in mind in case a similar report is done.
