### ISSUE TITLE
Update PineA64 image with new ATF Blob

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#383]
http://forum.pine64.org/showthread.php?tid=99&pid=12817#pid12817

this is taken care of with the`dietpi-config` -> `update firmware` option, but I believe it best to apply it to the latest images by default.

**Comment by Fourdee** [comment]
@rhkean 

> but I believe it best to apply it to the latest images by default.

Yep :+1:  
Might be worth putting this update in the patch file aswell to force it for existing installations?

**Comment by rhkean** [comment]
hmm... I thought I had done that, but I just checked and it's not there.... must've been one of my test images

**Comment by Fourdee** [comment]
@rhkean 
I think this ticket is now completed with the updated Pine image? Please close if it is :+1:

**Comment by rhkean** [comment]
applied to V120 image
