### ISSUE TITLE
DietPi-Software | Unbound DNS Server

### ISSUE THREAD

**Issue by nonnorm** [MichaIng/DietPi#3849]
#### Formal software information
- Software title | 
Unbound
- Short description | 
A validating, recursive, and caching DNS resolver.
- Official URL (if available) | 
N/A
- GitHub URL (if available) | 
https://github.com/NLnetLabs/unbound
- (Official) install documentation | 
https://nlnetlabs.nl/documentation/unbound/howto-setup/

#### Are there similar/alternative software titles available with DietPi-Software?

- Pi-hole?

#### What makes your requested software better than the above solutions, if available?

- Private and recursive DNS server

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- Lots of configuration options

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

(0. Pi-hole config page)
1. Install Unbound
2. Configure

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.

- Probably

I also would like to add this to Pi-hole as one of the configuration options at the end.

**Comment by Joulinar** [comment]
FeatHub request already open https://feathub.com/MichaIng/DietPi/+107

And one open request https://github.com/MichaIng/DietPi/issues/2409
