### ISSUE TITLE
[FAILED] DietPi-Software | APT install for: chromium-browser

### ISSUE THREAD

**Issue by punktilend** [MichaIng/DietPi#3852]
#### Details:
- Date           | Wed Oct 21 15:30:27 EDT 2020
- Bug report     | a9d4a378-de18-413f-9250-6b2886c67003
- DietPi version | v6.33.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi Zero W (armv6l) (ID=1)
- Kernel version | Linux DietPi 5.4.51+ #1333 Mon Aug 10 16:38:02 BST 2020 armv6l GNU/Linux
- Distro         | buster (ID=5,RASPBIAN=1)
- Command        | apt-get -qq --allow-change-held-packages install chromium-browser
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 36454 files and directories currently installed.)
Preparing to unpack .../chromium-browser_78.0.3904.108-rpt1_armhf.deb ...
Unpacking chromium-browser (78.0.3904.108-rpt1) ...
dpkg: error processing archive /var/cache/apt/archives/chromium-browser_78.0.3904.108-rpt1_armhf.deb (--unpack):
 cannot copy extracted data for './usr/lib/chromium-browser/chromium-browser' to '/usr/lib/chromium-browser/chromium-browser.dpkg-new': failed to write (No space left on device)
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/chromium-browser_78.0.3904.108-rpt1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by MichaIng** [comment]
Many thanks for your report.

> failed to write (No space left on device)

It seems your drive has not enough free space. Can your check:
```
df -T
```

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
