### ISSUE TITLE
Automatic Backup schedule

### ISSUE THREAD

**Issue by Lycidias93** [MichaIng/DietPi#3871]
#### Is your feature request related to a problem? Please describe:

- ...No

#### Describe the solution you'd like:

- ... I would like to have an option in dietpi-backup to automate my backup with time settings. autodelete for max backups would be nice too or uploading to cloud  option.

#### Describe alternatives you've considered:

- ... cron...

#### Additional context

- ...

**Comment by StephanStS** [comment]
@Lycidias93: Could be timeshift meet your functional requirements?
Up to now, you need a manual installation. 

See:
- https://www.fossmint.com/backup-restore-linux-with-timeshift/
- https://www.linuxlinks.com/essential-system-tools-timeshift-reliable-system-restore-tool-linux/

**Comment by anvarit** [comment]
Easiest solution would be to add this per default in the cron.daily script with similar options as the line "DietPi-Sync daily".
If you would add a toggle in the GUI to enable daily backup then the daily cron script can then read this out and execute the /boot/dietpi/dietpi-backup 1 script.
While it is currently possible with manual different steps, I could be made easier this way

**Comment by MichaIng** [comment]
While earlier or later we want to merge the two scripts, actually adding this now is simple enough until we find time for the merge. It simply makes sense! I'll add it to next milestone.

**Comment by MichaIng** [comment]
A PR is up to add this feature: #4922
