### ISSUE TITLE
DietPi-Software | Mate Desktop on RPi3

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#388]
- `DietPi- ...` links on Mate Desktop didn't work:

![rpi-3-test linux 06252016-18 25 07](https://cloud.githubusercontent.com/assets/17237601/16358152/cc87f46a-3b0b-11e6-9d25-1eafa6c99494.png)

solution: 

`root@RPi-3-test:~# apt-get install xterm`

![rpi-3-test linux 06252016-19 23 17](https://cloud.githubusercontent.com/assets/17237601/16358169/41d20e22-3b0c-11e6-8a9c-0fe5d1f1db2b.png)

---
- File manager link on Mate Desktop didn't work:

![rpi-3-test linux 06252016-19 27 43](https://cloud.githubusercontent.com/assets/17237601/16358165/2eb6dc78-3b0c-11e6-881c-6c764876b33f.png)

solution: 

create a link to `Caja` - the official File manager on Mate-Desktop

**Comment by Fourdee** [comment]
@k-plan 
Thanks for the report and solutions, i'll take a look :+1:

**Comment by Fourdee** [comment]
Great work @k-plan, all issues now resolved and patched in v121 :+1: 

Also resolved following by setting execute permissions during install:

```
chmod +x /usr/share/applications/*
```

![image](https://cloud.githubusercontent.com/assets/7077026/16380369/8e73c2bc-3c6e-11e6-8113-b5532dc2afe2.png)

**Comment by Fourdee** [comment]
@k-plan 
As I've completed my tests and everything appears resolved, I'll mark this as completed, but please reopen if required. Good job :+1:
