### ISSUE TITLE
Mouse/Keyboard not working in KODI while External HDD connected

### ISSUE THREAD

**Issue by mjessa12** [MichaIng/DietPi#3882]
Hello,

Last night I setup kodi on my RPI B3+ with an external mouse and keyboard, but when the external HDD is connected, the mouse and keyboard do not respond. When I don't have the HDD connected, the mouse and keyboard work fine.

I tried googling and found to add this:

```
sudo tee -a /etc/udev/rules.d/998-fix-input.rules <<_EOF_
# input
KERNEL=="mouse*|mice|event*",   MODE="0660", GROUP="input"
KERNEL=="ts[0-9]*|uinput",      MODE="0660", GROUP="input"
KERNEL=="js[0-9]*",             MODE="0660", GROUP="input"

# tty
SUBSYSTEM=="tty", KERNEL=="tty[0-9]*", GROUP="tty", MODE="0666"
_EOF_
```

But that still did not fix it.

Anyone have any solution to solve this?

Thank you

**Comment by MichaIng** [comment]
Many thanks for your report.

How did you connect the external HDD, is it powered via dedicated power supply or only via USB?

It's not a permissions issue if it works without the HDD attached, so the udev rules do not work. I guess it's something with power/voltage across the USB ports.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
