### ISSUE TITLE
DietPi-Image | v.120

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#389]
- Download:  http://dietpi.com/downloads/images/DietPi_RPi-armv6-(Jessie).7z
- unpacked: `DietPi_v120_RPi-armv6-(Jessie).img`
- Write on sd-card and starting
- first thing which will be preformed is a update from v.119 => v.120 

```
root@RPi-3-test:~# cat /DietPi/dietpi/.version
119

root@RPi-3-test:~# uname -a
Linux RPi-3-test 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
```

As far as I can see in the image files for Odroid C1 v.120  and Odroide C2 v.120 is is the same ....

**Comment by Fourdee** [comment]
@k-plan 

Yep this is expected. 
When we finalize the image, we drop the version number by 1. This allows us to create the image at a specific time during v120 devolpment, then run any final patches during v120 update.

If we are being clinical, i agree, the images should be called v119. But as our update system runs during 1st run, they will always be updated to v120. Technically speaking, the images are v119.5 :).

**Comment by k-plan** [comment]
> Technically speaking, the images are v119.5 

😄
