### ISSUE TITLE
DietPi-Update And UserData Problem

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#390]
1) I cant use dietpi-update it gives this error. I am absouletly sure about my internet connection is good
![aaaa](https://cloud.githubusercontent.com/assets/20144485/16358765/e10a5458-3b26-11e6-8324-5a990eb8a02f.PNG)
after exit from updates;
![a11](https://cloud.githubusercontent.com/assets/20144485/16359085/d83f993c-3b30-11e6-8a44-6e0e4df6e270.PNG)

2) im taking user data error when i click the Go button on dietpi-software at first boot. and it closing dietpi-software app, and i am seeing some syntax errors on command line :/ (and yes i tried fresh install 5 times)
![a2](https://cloud.githubusercontent.com/assets/20144485/16359089/de2495be-3b30-11e6-8c70-0342780b75df.PNG)
![a3](https://cloud.githubusercontent.com/assets/20144485/16359090/e0dafe9c-3b30-11e6-8b34-76b55f1776ff.PNG)

Solve = Changing user data location to usb hard drive and changing back it to Flash(SD/EMMC)
Sorry for my bad english and im really loving you distro : ) Keep Going :+1:
(there were no error or problem on v116)
My System Spec:
Raspberry Pi 3
Samsung Evo+ 32GB

**Comment by Fourdee** [comment]
@yunussandikci 
Thanks for the report, looks like a possible issue with `^M` EOL.

Would please to send us a bug report? Please see here for instructions: http://dietpi.com/phpbb/viewtopic.php?f=8&t=499&p=2184#p2184

**Comment by Fourdee** [comment]
Note to self:

> Possible link to another user reporting similar issues: https://twitter.com/DietPi_/status/747019385932492800

**Comment by ghost** [comment]
@Fourdee 
My reference code is 4e2c7da6-a3f7-4a75-bce1-231c7b6151c9-0
Note : Dont forget to look for that i mentioned "**2**" bugs :)
Thanks :)

**Comment by Fourdee** [comment]
> Note : Dont forget to look for that i mentioned "2" bugs :)

Noted and thanks for doing the bug report  :+1: . I will look into this tomorrow and get back to you.

**Comment by Fourdee** [comment]
For my reference, possible same issue: https://github.com/Fourdee/DietPi/issues/393

**Comment by Fourdee** [comment]
Looks your dietpi.txt has dos line endings (bottom right):
![image](https://cloud.githubusercontent.com/assets/7077026/16378376/7d045e16-3c63-11e6-9c8a-367ff90002d9.png)

I've checked DietPi_v120_RPi-armv6-(Jessie).img. The dietpi.txt file contained inside is unix line endings.

**Comment by Fourdee** [comment]
@yunussandikci 

Please run the following command to convert line endings:

```
sed -i $'s/\r$//' /DietPi/dietpi.txt
dietpi-update
```

**Comment by Fourdee** [comment]
#### Testing / Notes to self:

Flip incorrectly detects bash scripts as binary files:

```
root@DietPi:~# flip -uv /DietPi/dietpi/*
/DietPi/dietpi/boot
flip: /DietPi/dietpi/conf: can't open: Is a directory
/DietPi/dietpi/dietpi-apt-get_update
/DietPi/dietpi/dietpi-autostart
/DietPi/dietpi/dietpi-backup
/DietPi/dietpi/dietpi-banner: binary file, not converted
/DietPi/dietpi/dietpi-bugreport
/DietPi/dietpi/dietpi-cleaner: binary file, not converted
```

dos2unix seems better excluding `dos2unix: Binary symbol 0x15 found at line 50 dos2unix: Skipping binary file /DietPi/dietpi/dietpi-uninstall`:

```
root@DietPi:~# dos2unix /DietPi/dietpi/*
dos2unix: converting file /DietPi/dietpi/boot to Unix format ...
dos2unix: Skipping /DietPi/dietpi/conf, not a regular file.
dos2unix: converting file /DietPi/dietpi/dietpi-apt-get_update to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-autostart to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-backup to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-banner to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-bugreport to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-cleaner to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-cloudshell to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-config to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-cpuinfo to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-cpu_set to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-cron to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-external_drive_setup to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-funtime to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-launcher to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-letsencrypt to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-logclear to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-morsecode to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-obtain_hw_model to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-process_tool to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-ramdisk to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-ramlog to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-services to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-software to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-survey to Unix format ...
dos2unix: converting file /DietPi/dietpi/dietpi-sync to Unix format ...
dos2unix: Binary symbol 0x15 found at line 50
dos2unix: Skipping binary file /DietPi/dietpi/dietpi-uninstall
dos2unix: converting file /DietPi/dietpi/dietpi-update to Unix format ...
dos2unix: converting file /DietPi/dietpi/finalise to Unix format ...
dos2unix: Skipping /DietPi/dietpi/func, not a regular file.
dos2unix: converting file /DietPi/dietpi/login to Unix format ...
dos2unix: Skipping /DietPi/dietpi/misc, not a regular file.
```

Could probably get away with forcing the conversion as there are no binary files in `/DietPi`. Aside from text/scripts, the only other file format is .png. So, need to test if .png is effected by the conversion `/DietPi/dietpi/conf/desktop/*.png`

**Comment by Fourdee** [comment]
@yunussandikci 
Some questions:
- Where did you download the compressed image (url)?
- Once decompressed, which version is in the image file? (eg: DietPi_v120_RPi-armv6-(Jessie).img)
- Which program did you use to write the image to SD card? And, OS of that system.
- Did you modify the /boot/dietpi.txt file prior to booting (eg: setting swapfile size)?

Thanks.

**Comment by ghost** [comment]
1) I downloaded image from this url "http://dietpi.com/downloads/images/DietPi_RPi-armv6-(Jessie).7z"
2) DietPi_v120_RPi-armv6-(Jessie).img
3) Win32  Disk Imager 0.9.5 with Windows 10 Pro 64Bit
4) I modified only this lines with Notepad++ ;

Wifi_Enabled=1
Wifi_SSID=YunusErk
Wifi_KEY=password
Use_Static=1
Static_IP=192.168.0.100
Static_Mask=255.255.255.0
Static_Gateway=192.168.0.1
Static_DNS=8.8.8.8
Thanks :)

**Comment by ghost** [comment]
I dont really know much about  "what is dos line endings" or something you mentioned :(  I made some changenings in dietpi.txt because i dont have ethernet cable, im doing my installation with ssh over wifi. What should i do when i want to make fresh installation,
Should i change change my eol conversation setting to UNİX/OSX on notepad++ ? am i right? was it the problem ?
Thanks :)

**Comment by Fourdee** [comment]
@yunussandikci 
Thanks. Yes it looks like the modifications to dietpi.txt somehow converted the line endings to dos.

I'll code something into v121 that will automatically convert that file and a few others. Should prevent this from occurring in the future.

For now, you can set EOL Unix in notepad++ here:
![image](https://cloud.githubusercontent.com/assets/7077026/16380770/e1287c44-3c70-11e6-8389-443fc2424be5.png)

**Comment by ghost** [comment]
I'm sorry about my ignorance :/ And really thank you for effort. Best RPi Distro Ever! :+1:

**Comment by Fourdee** [comment]
@yunussandikci 

> I'm sorry about my ignorance about that :/ 

Not at all! I didn't know what line endings were when I started DietPi lol. Had a few similar issues myself, and took me a while to figure it all came down to line endings.

I've updated DietPi to automatically apply unix line endings to dietpi.txt and core user files during boot. It wont take effect until the user has updated DietPi to v121, or, when we next update the images. So, in a case like this ticket, users can run `sed -i $'s/\r$//' /DietPi/dietpi.txt` to proceed.

```
#echo -e $(date +%N) >> /root/test
sed -i $'s/\r$//' "$FILEPATH_RAM"/uEnv.txt &> /dev/null
sed -i $'s/\r$//' "$FILEPATH_RAM"/boot.ini &> /dev/null
sed -i $'s/\r$//' "$FILEPATH_RAM"/config.txt &> /dev/null
sed -i $'s/\r$//' "$FILEPATH_RAM"/dietpi.txt
#echo -e $(date +%N) >> /root/test
```

Adds 20~ms (probably <10ms due to file write) to bootime, but its worth it. Line endings are a nightmare and not always obvious to debug.

```
root@DietPi:~# cat test
295602000
315157000
```
