### ISSUE TITLE
DietPi-Software | Add installation option for Gogs

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#391]
As title: https://gogs.io/

**Comment by Fourdee** [comment]
docs: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=70#p2187

**Comment by Fourdee** [comment]
Completed, available from v121.

**Comment by ghost** [comment]
Is it available on arm64?

**Comment by Fourdee** [comment]
@Zone22 
Yep its disabled for ARM64: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L744
Gogs do not currently offer the ARM64 binary as a download: https://dl.gogs.io/

**Comment by DJCrashdummy** [comment]
there is an open issue #686 for adding [Gitea](http://gitea.io/) (a community managed fork of Gogs) which [provides arm64-binaries (and even more)](https://dl.gitea.io/gitea/master/) besides a quicker development and some other improvements.

i guess adding Gitea (maybe replacing Gogs) and solving #686 will bring some real benefit to DietPi.
