### ISSUE TITLE
dietpi apt upgrade erro

### ISSUE THREAD

**Issue by carlosspre** [MichaIng/DietPi#3927]
root@NetPlexPi4:~# apt upgrade
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.

**Comment by Joulinar** [comment]
Did you tried running `dpkg --configure -a` as suggested by the error message?

**Comment by carlosspre** [comment]
I did this information more
root@NetPlexPi4:~# dpkg --configure -a
Setting up rpi-eeprom (10.2-1) ...

**Comment by Joulinar** [comment]
anything else? is it hanging? some error message?

**Comment by carlosspre** [comment]
I don't have any more error information

**Comment by Joulinar** [comment]
does it finished, is it still hanging?

**Comment by MichaIng** [comment]
Marking as closed due to missing reply. Feel free to reopen if required.
