### ISSUE TITLE
DietPi-Config | Add display options for Pine A64

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#398]
> http://forum.pine64.org/showthread.php?tid=1068&pid=13760#pid13760

**Comment by Fourdee** [comment]
@rhkean 
Would appreciate your input on this if you can :+1:. Is changing display resolution even possible at the moment?

**Comment by rhkean** [comment]
@Fourdee 
I believe that I saw some threads on the pine forum regarding this, but I didn't get a chance to follow up on it, so I'm not 100% sure

**Comment by Fourdee** [comment]
uEnv.txt

```
optargs=disp.screen0_output_mode=720p60
```

List of available options: https://github.com/longsleep/sunxi-disp-tool#available-hdmi-output-names

**Comment by Fourdee** [comment]
Gonna leave the non-refresh rate options out, else, just looks more confusing.
![image](https://cloud.githubusercontent.com/assets/7077026/16528091/80f02d82-3fb2-11e6-8672-dd34c42fa165.png)

**Comment by Fourdee** [comment]
Done, available for v123. Tested 1080i60 720p50 720p60 and 1080p60. I'll test 4K in a few years, when they are affordable and the world catches up with the extra bandwidth lol
