### ISSUE TITLE
DietPi-Software | Kodi will not run.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#399]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=504&p=2205#p2205

**Comment by Fourdee** [comment]
Due to shift from fbdev to X11 with recent mali driver release. Many thanks to Meveric for his help on this one:

> Changes for X11 installing xf86-video-mali and libump-odroid aside of mali450-odroid and a new set of aml-libs-odroid. 
> xorg.conf for /etc/X11

**Comment by rhkean** [comment]
so, is it fixable?

**Comment by Fourdee** [comment]
@rhkean Yep, just testing now

**Comment by Fourdee** [comment]
notes:
- :u55b6: boot.ini `setenv vout "dvi"` now disables hdmi audio. So this must now be commented out.
- :u6307: Kodi 32bit works from console.
- :u55b6: Kodi 24bit from console visually appears slower and stutters. 32bit is alot smoother.
- :u5408: LXDE 24bit fails on xorg.
- :u55b6: LXDE 32bit desktop fine. Kodi stutters and flashes in menus. Desktop visible in video playback. ![img_20160629_173325](https://cloud.githubusercontent.com/assets/7077026/16460602/16aa4a90-3e20-11e6-8fa5-fe70d8fc301d.jpg) 
  - Desktop visible is caused by `xcompmgr -n` in `/etc/xdg/lxsession/LXDE/autostart`
  - `xcompmgr -a` hides the desktop and Kodi runs as smooth as butter. However, if a window is open prior to running Kodi, Kodi's menu interface stutters.
  - We need to use `xcompmgr -a/n` for LXDE, else, moving windows results in 100% cpu.
- :u55b6: MATE 32bit desktop fine. Kodi stutters and flashes in menus. Audio latency in Kodi menus. Video playback is fine.
  - `xcompmgr -a` resolves all the above issues.

**Comment by Fourdee** [comment]
notes:
- 32bit is now default. Required for optimal performance in Kodi and allows for working Desktops.
- `setenv vout "dvi"` is now commented out by default to allow HDMI audio.
- `xcompmgr -a` is set when user runs Kodi from any Desktop. Prevents stuttering/flashing in Kodi menus and prevents laggy audio in pulseaudio desktops (eg: MATE).

The main question is patching:
- Due to so many needed changes from fbdev to X11, might not be feasible.
- Might need to consider a forced v121 image for C2. Lets see, maybe we can uninstall and reinstall KODI.

**Comment by Fourdee** [comment]
The above commit should cover patching. But i'll test it tomorrow from 120 master with Kodi+LXDE installed > 121 testing.

Reason for boot.ini overwrite:
Patching boot.ini would be risky due to far too many additions and changes at various lines, and, I honestly don't have the time at the moment to code around it :-1: . Also contains the new "nographics" (headless) option which i'll add to dietpi-config at a later date (+300MB RAM whoooho :+1: ).

**Comment by Fourdee** [comment]
Patch tests completed. Resolved for v121.
Marking as closed :)
