### ISSUE TITLE
DietPi has encountered an error

### ISSUE THREAD

**Issue by LeatherMolly** [MichaIng/DietPi#3996]
#### Details:
- Date           | Wed Dec 23 05:35:47 CET 2020
- DietPi version | v6.34.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 2 Model B (armv7l) (ID=2)
- Kernel version | Linux DietPizza 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
- Distro         | buster (ID=5,RASPBIAN=1)
- Command        | ping -c 1 -W 5 one.one.one.one
- Exit code      | 2
- Software title | DietPi-Software
- 
#### Steps to reproduce:

1. # pihole -up
gives out:
`[i] Checking for updates...
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Could not resolve host: github.com
  [i] Pi-hole Core:	up to date
fatal: unable to access 'https://github.com/pi-hole/AdminLTE.git/': Could not resolve host: github.com
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✗] Retrieval of supported OS list failed. dig failed with return code 10. 
      Unable to determine if the detected OS (Raspbian 10) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues

      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

           If you are seeing this message after having run pihole -up:
             PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

  Unable to complete update, please contact Pi-hole Support
`

`# PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r`
gives out
`[✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.3.19-1~deb10u1
  [i] Repair option selected

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [i] PIHOLE_SKIP_OS_CHECK env variable set to true - installer will continue
  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2

  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found
  [✗] FTL Engine not installed
`

What you ask ist too much for me as non informatic person.

I installed Unbound from within Dietpi for use with Pihole. Since then I have problems with my setup. I try to get help at Kuketz forum [https://forum.kuketz-blog.de/viewtopic.php?f=42&t=3067&start=750](url) as "olga-of-wolga » 23. Dez 2020, 05:24".
Maybe this helps.

**Comment by Joulinar** [comment]
Hi,

Looks like DNS issues on your system. Can you check in `dietpi-config` what DNS server is used?

**Comment by MichaIng** [comment]
From your post on the other forum it seems that you mixed two configurations:
- DietPi-Software installs Unbound (when Pi-hole is or was installed) to listen on port `5353`.
- But you created additionally `/etc/unbound/unbound.conf.d/pi-hole.conf` to listen to and tested DNS on port `5335`.

Please decide which config you want to use and either:
- `rm /etc/unbound/unbound.conf.d/dietpi*.conf` => Unbound will listen on port 5335 as the blog/guide suggests it.
- or: `rm /etc/unbound/unbound.conf.d/pi-hole.conf` => Unbound will listen on port 5353, as DietPi configures it.

Those port settings seem to sometimes override each other, sometimes not, so having multiple port directives in place seems to not work reliably. Since port 5353 is [mDNS](https://wikipedia.org/wiki/Multicast_DNS), port 5335 is actually better for Unbound as a default. So I'd go with the first option and use the `pi-hole.conf` instead.

Another topic: It seems that you configured DietPi to use it's own Pi-hole for DNS resolution. Please do not do that, as on Pi-hole or Unbound updates, or if anything else goes wrong, the system can lock out itself from network access. The server itself should use a regular upstream DNS provider, so you are able to stop every service without loosing network capabilities on the server itself.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
