### ISSUE TITLE
Xfce | Software Request

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#400]
As a normal raspberry pi user for torrent and media box, i wish dietpi had a option for install latest Xfce desktop environment. Because its lightweight, more user friendly and eye candy and its more comprehensive for using raspberry as remote desktop. So if there is chance can you include it? It's just a idea, but if it will be included i will be so happy. Thanks :)

**Comment by Fourdee** [comment]
@yunussandikci 
Great timing :+1:  completed this today lol. XFCE will be available in v121: https://github.com/Fourdee/DietPi/issues/397

**Comment by ghost** [comment]
omg I LOVE YOU! ahahah
