### ISSUE TITLE
Image | NanoPi R1

### ISSUE THREAD

**Issue by robyscar** [MichaIng/DietPi#4017]
#### Formal device information
- Device name | **FriendlyARM NanoPi R1**
- Official product URL | **https://www.friendlyarm.com/index.php?route=product/product&product_id=248**
- GitHub resource URL (if available) | **https://github.com/friendlyarm**
- Image download URL | **http://download.friendlyarm.com/nanopir1**
- Wiki URL | **https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R1**

#### Is the SBC officially supported by the Debian installer?
- only UNSTABLE | **https://wiki.debian.org/InstallingDebianOn/Allwinner**
- on sunny **H5** | !FriendlyARM NanoPi NEO 2 | **sun50i-h5-nanopi-neo2.dtb**
- on sunny **H3** | Nano Pi Neo | **sun8i-h3-nanopi-neo.dtb**

#### If not, is a reliable 3rd party Debian image available for this SBC?
- ARMBIAN | **https://redirect.armbian.com/nanopi-r1/Buster_current**

#### If not, are there install instructions for Debian available?
**https://github.com/drtyhlpr/rpi23-gen-image/
https://github.com/Debian/raspi3-image-spec**
- ...

#### SBC Spec
Hardware Spec
    CPU: Allwinner H3, Quad-core Cortex-A7 Up to 1.2GHz
    DDR3 RAM: 512MB/1GB
    Storage: NC/**8GB eMMC**
    Network:
        10/100/1000M Ethernet x 1，
        10/100M Ethernet x 1
    WiFi: **802.11b/g/n, with SMA antenna** interface
    Bluetooth：4.0 dual mode
    USB Host: Type-A x2
    MicroSD Slot x 1
    MicroUSB: for OTG and power input
    Debug Serial Port: 3Pin 2.54mm pitch pin-header
    UART: 4Pin 2.54mm pitch pin-header
    LED: LED x 3
    KEY: KEY x 1
    PC Size: 50.5 x 60mm
    Power Supply: DC 5V/2A
    Temperature measuring range: -20℃ to 70℃
    **OS/Software: U-boot，Ubuntu-Core，OpenWRT**

**Comment by midzelis** [comment]
+1, I have this board, and will be willing to contribute testing and whatever I as far as development goes. I noticed this dietpi is basically a TON of bash? scripts. shell scripts are not my strong suite, but I can get by. It seems like Nano Pi R1 uses the same chip as ZeroPi, NanoPi NEO/Neo Air/M1/T1/M1 Plus -- so it seems like adapting one of those could work. In fact, i'm going to download the NanoPi M1/T1 image and see if it loads. 

What goes into creating support for a new SBC? 

Thanks!

**Comment by MichaIng** [comment]
Easiest world be to implement it with Armbian base image / kernel repository. I'll do that next week together with two other outstanding NanoPi SBCs. I'm tinkering with the Debian kernel as well, but that will take a bit longer.

**Comment by robyscar** [comment]
thanks @MichaIng really appreciated!
we (at least me and @midzelis ) we are sure that 1st version will be good, and the Debian one will be great!
thanks
Roby

**Comment by ScottSturdivant** [comment]
The ZeroPi image boots and runs on the Nano Pi R1. Is there any thing I should be on the lookout for that might not work? Or should I be hopeful that by virtue of it booting and seeing to operate OK that it'll fine?

Thank you!

**Comment by MichaIng** [comment]
Comparing the hardware specs:
- https://wiki.friendlyarm.com/wiki/index.php/ZeroPi#Hardware_Spec
- https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R1#Hardware_Spec

The ZeroPi has only one Ethernet, no WiFi/BT module and no eMMC, so those three might not work. On the other hand, the kernel + device tree package should be the same, so likely the correct device tree is present and picked already by the bootloader. Since Armbian uses minimally modified upstream kernels, sharing then across a large span of SBCs, the images are often cross-compatible.

**Comment by MichaIng** [comment]
Image ready: https://dietpi.com/downloads/images/DietPi_NanoPiR1-ARMv7-Buster.7z
