### ISSUE TITLE
[DietPi Update Error] - Obtained server value from github is invalid!  

### ISSUE THREAD

**Issue by bhaveshgohel** [MichaIng/DietPi#402]
Hello @Fourdee ,

Today when i update my Raspberry Pi I get the bellow error message. I tried again but same error.

![dietpi-update-error](https://cloud.githubusercontent.com/assets/5253753/16476934/78998d58-3eaa-11e6-9dba-57edd1d7041a.png)

OS: DietPi v116 [Debian Jessie]
Hardware: Raspberry Pi 3

I'll be happy to provide more info if needed. :smiley:

**Comment by Fourdee** [comment]
@bhaveshgohel 
Thanks for the report.

> I'll be happy to provide more info if needed.

Excellent :+1:  
I mainly need to see `/DietPi/dietpi.txt`, but, its probably best to send us a bug report as this will upload the majority of DietPi settings including dietpi.txt: http://dietpi.com/phpbb/viewtopic.php?f=8&t=499

**Comment by bhaveshgohel** [comment]
@Fourdee : Bug Report Sent! :+1: 

Where can i send you the "Reference CODE"?

**Comment by Fourdee** [comment]
@bhaveshgohel 
On here will be good :+1:

**Comment by bhaveshgohel** [comment]
@Fourdee : I'm planning to backup this OS and completely install the latest one. So if anything is there i can switch between that OS and we can debug it. :)

**Comment by Fourdee** [comment]
Assuming issue has not occurred on fresh install. Marking as closed, please reopen if required.
