### ISSUE TITLE
erro upgrade dietpi

### ISSUE THREAD

**Issue by carlosspre** [MichaIng/DietPi#4023]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...
2. ...

#### Expected behaviour

- ...

#### Actual behaviour

- ...

#### Extra details

- ...

**Comment by nonnorm** [comment]
Hello,
Could you please provide some information about your system and the error?  Filling out the bug report form would be easiest.

**Comment by carlosspre** [comment]
![image](https://user-images.githubusercontent.com/54223462/103322178-e9ae0380-4a1b-11eb-8d92-6632ddefd664.png)


I can't update my dietpi

**Comment by nonnorm** [comment]
After the `sudo dpkg --configure -a` completes, could you try again and see if there are any more errors?

**Comment by carlosspre** [comment]
![image](https://user-images.githubusercontent.com/54223462/103322568-42ca6700-4a1d-11eb-8f8d-651d80fdd60b.png)


no more errors, how can I solve this

**Comment by Joulinar** [comment]
how long is you system in this status? Are you running RP4?

**Comment by carlosspre** [comment]
2 months ,, I'm using pi4 4g

**Comment by Joulinar** [comment]
no I mean the command, how long is it hanging?

**Comment by carlosspre** [comment]
I didn't understand friend

**Comment by Joulinar** [comment]
you have entered the command `dpkg --configure -a`. Does you system do anything? Dos it nothing? How long is it doing nothing? Did you cancelled the command in meantime?

**Comment by carlosspre** [comment]
I did run the command dpkg --configure -a, but it doesn't do it anymore, and it doesn't solve the problem

**Comment by Joulinar** [comment]
> but it doesn't do it anymore

what do you mean by this? Is your system stuck or did the command finished

**Comment by carlosspre** [comment]
command ended

**Comment by Joulinar** [comment]
can you run `apt update && apt upgrade`

**Comment by carlosspre** [comment]
![image](https://user-images.githubusercontent.com/54223462/103323491-c7b77f80-4a21-11eb-8579-a11513527bbe.png)

apt update ok

**Comment by carlosspre** [comment]
![image](https://user-images.githubusercontent.com/54223462/103323517-ed448900-4a21-11eb-894e-3f294bea7a57.png)

apt upgrade. not going correctly

**Comment by Joulinar** [comment]
pls reboot your system. And there is no need to copy screen prints. You can just copy/past the text out of the SSH gui. this is much more readable.

As well you have more than 200 packages to be updated. This looks like an entire system upgrade? Did you have done anything before?

**Comment by MichaIng** [comment]
General hint here: Whenever `rpi-eeprom` is stuck/terminated, it should be assured that the EEPROM has been successfully flashed: `rpi-eeprom-update -a`
Else the RPi 4 might become unbootable without the ability to fix it by flashing any OS image. I guess there is a possibility for offline EEPROM flash... ...ah okay an official recovery image exists that obviously is able to boot with broken EEPROM: https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/

However, it seems to have ended. 220 package upgrades are indeed nearly impossible on a Raspbian Buster based image, probably something with that package states file is wrong.

**Comment by carlosspre** [comment]
- DietPi has encounted an error, and, is unable to continue         -
- Please create a ticket: https://github.com/MichaIng/DietPi/issues -
- Copy and paste the BLUE lines below, into the ticket              -
---------------------------------------------------------------------


#### Details:
- Date           | Mon  8 Feb 22:50:36 GMT 2021
- Bug report     | d7a220ef-87b4-40aa-85fb-dba9d86db73f
- DietPi version | v6.28.0 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 4 Model B (armv7l) (ID=4)
- Kernel version | Linux NetPlexPi4 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- Distro         | buster (ID=5)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Update

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

**Comment by Joulinar** [comment]
you posted into 2 different issues now, pls try to stick to one.

**Comment by Joulinar** [comment]
btw we should close this one in favour of https://github.com/MichaIng/DietPi/issues/4097
