### ISSUE TITLE
DietPi-Software | MineOS fails to start/copy server profiles "Error 127"

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#403]
_A report from [MineOS](https://discourse.codeemo.com/t/dietpi-mineos-server-start-failed/1375) forums by chooch79._

 After I accept the EULA and click "Start" server, I get "[servername] start failed 127." I also tried to click "Copy profile to live server files" and get the error "[servername] copy_profile failed 127."

_The author and maintainer of MineOS (Hexparrot) suggested resolution_

"It doesn't appear that rsync, the method that copies over profiles to the live server directory is present.

I was able to remedy this with apt-get install rsync as root at the command line. This step, however, should be added to the MineOS installation process since it essential to easy use of MineOS."

Reported Hardware: Raspberry Pi 2 - Although verify that the other install scripts include rsync.

**Comment by Fourdee** [comment]
@Zone22 
Thank you for letting me know. :+1: 

Resolved for v121:
I've added rsync to the default package list for MineOS, and, existing MineOS installations will be patched during dietpi-update. 

Commit: https://github.com/Fourdee/DietPi/commit/ccdb8d94287229f94b2b8ccf6ce2eedab9d2042e
