### ISSUE TITLE
DietPi-Software | Remove mandatory reboot after installs

### ISSUE THREAD

**Issue by Games-Crack** [MichaIng/DietPi#4032]
#### Is your feature request related to a problem? Please describe:
I am always frustrated when I install software on my diet pi with dietpi-software because I can't say no to the reboot!

#### Describe the solution you'd like:
Let the user decide if he/she wants to reboot

#### Describe alternatives you've considered:
Or a "Flag" that you can set to not reboot

**Comment by Joulinar** [comment]
Hi,

you can avoid the reboot by using `dietpi-software install <ID>` but I guess @MichaIng can explain the reason for the reboot required 😉

**Comment by MichaIng** [comment]
Good news is I just thought the same a few days ago: There is not really a reason for the reboot, probably required in a very few cases only. It's just that it was there as long as I can think of and no one aimed to remove it until now.

Let's remove it. In a few cases we might want to start the respective software service one time manually (for those which are not controlled by `dietpi-services`): VPN and VNC servers + XRDP, SSH servers, NoMachine, hostapd, that should be it.

In case of WireGuard, if the kernel got upgraded in the same turn, a reboot is required to allow it starting. But in case of `dietpi-software install 172` with upgraded kernel we already print a related info message that we could make a bid "larger".

**Comment by Games-Crack** [comment]
@Joulinar I know that you sometimes have to reboot ;-) 
but not all the time like @MichaIng said and thank you for the command i didn't know this.

**Comment by MichaIng** [comment]
Done: #4095
