### ISSUE TITLE
vmtouch fails with segmentation fault on raspberry RPi B (armv61)

### ISSUE THREAD

**Issue by berndhose** [MichaIng/DietPi#4050]

**Comment by MichaIng** [comment]
Many thanks for your report.

Did you face this issue on a fresh image?

Could you try the following:
```
cd /tmp
wget https://dietpi.com/downloads/binaries/buster/vmtouch_armv6l.deb
apt install --reinstall ./vmtouch_armv6l.deb
```

**Comment by berndhose** [comment]
yes, happened on fresh image right after automatic first time upgrade.

reinstalling vmtouch from dietpi repository resolved the issue

many thanks

**Comment by MichaIng** [comment]
Strange, probably I created that image before I added forced armv6l for 32-bit RPi images to the creation script. I'll update all our RPi images tomorrow.

**Comment by MichaIng** [comment]
All RPi images have been updated meanwhile.
