### ISSUE TITLE
Orange PI Image Request

### ISSUE THREAD

**Issue by retro24** [MichaIng/DietPi#4054]
Hello is it possible to add an image for the Orange PI one ??

if you cannot do it, are there any instructions to do it my self ???

is it possible to give me the link for the last Dietpi Orangepi one image made before the images are removed from downloads??

thanks

**Comment by Joulinar** [comment]
Hi, 

many thanks for your message. You could try to install Armbian. Not sure what your device is. There a couple of them support. https://www.armbian.com/download/?tx_maker=xunlong

Once done, run DietPi PREP script to install DietPi on top https://dietpi.com/docs/dietpi_sbc/#make-your-own-distribution

**Comment by MichaIng** [comment]
I'm gonna mark Orange Pi related image requests as closed for now. Referring to our preparation script guide: https://dietpi.com/docs/hardware/#make-your-own-distribution

Orange Pi is on my first priority list when image creation has been automated enough, for for now I personally cannot effort adding a new manufacturer to my creation schedule.
