### ISSUE TITLE
dietpi has encountered an error

### ISSUE THREAD

**Issue by drewcopping** [MichaIng/DietPi#4065]
#### Details:
- Date           | Sun Jan 24 01:06:53 GMT 2021
- DietPi version | v6.34.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Debian mini.iso
- Hardware       | Native PC (x86_64) (ID=21)
- Kernel version | Linux dev 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
- Distro         | buster (ID=5)
- Command        | curl -sSfL https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/lastStableBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar -o nukkit-1.0-SNAPSHOT.jar
- Exit code      | 92
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by Joulinar** [comment]
Hi,

Many thanks for your message. Looks like the file was not download correctly. Did you tried it again? Can you check if you are able to download the file manually.

```
cd /tmp
curl -sSfL https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/master/lastStableBuild/artifact/target/nukkit-1.0-SNAPSHOT.jar -o nukkit-1.0-SNAPSHOT.jar
```

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
