### ISSUE TITLE
DietPi-Software | Tidal connect

### ISSUE THREAD

**Issue by MatteoEng** [MichaIng/DietPi#4078]
#### Is your feature request related to a problem? Please describe:
Can we have a tidal connect like spotify connect?

#### Describe the solution you'd like:
would be nice to have a tidal feature

#### Describe alternatives you've considered:

- ...

#### Additional context

- ...

**Comment by MichaIng** [comment]
As TIDAL Connect is closed sources (at least I couldn't find sources) and the only RPi installer uses binaries, found from a removed repo, which require legacy Jessie and Stretch shared libraries, there is no currently no way to have this added to DietPi. I refer to the discussion on our forum: https://dietpi.com/phpbb/viewtopic.php?t=9436
