### ISSUE TITLE
[Odroid HC1] Dietpi causing DNS server to go down? Related to dietpi?

### ISSUE THREAD

**Issue by RicardoCst** [MichaIng/DietPi#4102]
When I have my Odroid HC1 on my network sometimes goes down for a couple of secs to a couple of minutes, windows saying the DNS server isnt responding, modem is based on DOCSIS3 and has a Puma 6 chipset.

**Comment by RicardoCst** [comment]
Nevermind just happend again, thanks internet for giving me confirmation.

**Comment by Joulinar** [comment]
Hi,

Many thanks for your message. Are running a DNS server on DietPi? Usually DietPi is not able to bring down your network. Or do you have duplicate IP addresses in your network?
