### ISSUE TITLE
DietPi - Cloudshell v6 | Run + Skip intro doesn't work

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#411]
@Fourdee 

>   #////////////////////////////////////
>     #
>     # Info:
>     # - System Stats for Cloudshell (or monitor/terminal)
>     #
>     # Usage:
>     # dietpi-cloudshell             = Config Menu
>     # dietpi-cloudshell 1           = Run
>     # dietpi-cloudshell 2           = Run + Skip intro
>     #////////////////////////////////////

`:~# dietpi-cloudshell 2` doesnt' work. (nothing happens)

Tested on Odroid C2 and RPi 3.

**Comment by Fourdee** [comment]
@k-plan 
Good find :+1: 

I've updated the dietpi-cloudshell script with commit above to fix this.

**Comment by Fourdee** [comment]
Tested and working fine here. I'll mark as closed, @k-plan please reopen if needed.

**Comment by k-plan** [comment]
@Fourdee 

wow, this fix was very quick! :smiley:  Thanks!

```
#Run DietPi-Cloudshell
elif (( $INPUT >= 1 )); then
```

edit, testing and it works on C2. :+1:
