### ISSUE TITLE
[Raspberry Pi 2] Enabling I2C during first setup breaks sed and fails

### ISSUE THREAD

**Issue by RicardoCst** [MichaIng/DietPi#4130]
[FAILED] DietPi-Set_hardware | sed -i /^aSOFTWARE_INSTALL_STATE\[72\]=/cSOFTWARE                                                                                                                                                             _INSTALL_STATE\[72\]=2 /boot/dietpi/.installed

**Comment by MichaIng** [comment]
Many thanks for your report. The issue has been solved with v7.0 already: https://github.com/MichaIng/DietPi/commit/90911f789d530467a2954a75e12606e1ac3fcead

**Comment by RicardoCst** [comment]
Ah okay I will close this issue then.
