### ISSUE TITLE
sound isn`t working on dietpi with retropie

### ISSUE THREAD

**Issue by SuperPi911** [MichaIng/DietPi#4131]
i followed te guide on on github and everiyhon works fine (not the sound)
unable to open SDL audio ....permission denied
failed to attach default soundcard

emulationstation cannot run with sudo or root account , i need to login as dietpi and run it

**Comment by MichaIng** [comment]
Many thanks to your report.

Please grant the dietpi user access to audio devices, by adding it to the audio system group: `usermod -aG audio dietpi`

**Comment by SuperPi911** [comment]
I am trying now

**Comment by SuperPi911** [comment]
Still no sound

**Comment by SuperPi911** [comment]
It's working!!!!!!!!!
