### ISSUE TITLE
Nextcloud Talk won't install

### ISSUE THREAD

**Issue by BugDave** [MichaIng/DietPi#4135]
#### Required Information
- DietPi version | 6.34.3
- Distro version | buster
- Kernel version | Linux DietPi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- SBC model | RPi 4 Model B (armv7l)
- Power supply used | Canakit that came with pi4b
- SDcard used | Samsung evo

#### Additional Information (if applicable)
- Software title | Nextcloud
- Was the software title installed freshly or updated/migrated? | Fresh Install
- Can this issue be replicated on a fresh installation of DietPi? | Yes

- Bug report ID | 0f767985-7352-4bde-9e92-236a97471c40

#### Steps to reproduce

1. ... Install Nextcloud
2. ...Install Nextcloud talk

#### Expected behaviour

- ...Nextcloud talk should install but is saying it's not supported on version 21

#### Actual behaviour

- Spreed is failing to install

#### Extra details

- It looks like nextcloud 21 came out yesterday and isn't compatible with the current release of nextcloud talk? Is there a way to install v20 of nextcloud so i can install nextcloud talk until it's compatible?

**Comment by Joulinar** [comment]
Hi,

many thanks for your message. Just a short question. Is that you open same topic on or forum? https://dietpi.com/phpbb/viewtopic.php?p=31972#p31972

In addition, I did a test installation today without issues.

```
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Configuring Nextcloud Talk: Video calls with configured coTURN server

[ INFO ] DietPi-Software | Configuring TURN server:
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: listening-port=3478
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: fingerprint
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: use-auth-secret
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: realm=DietPi3
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: total-quota=100
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: bps-capacity=0
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: stale-nonce
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: no-multicast-peers
[  OK  ] DietPi-Software | systemctl start mariadb
[  OK  ] DietPi-Software | systemctl start redis-server
[  OK  ] DietPi-Software | ncc maintenance:mode --off
[  OK  ] DietPi-Software | ncc app:install spreed
spreed already enabled
Config value stun_servers for app spreed set to ["DietPi3:3478"]
[  OK  ] DietPi-Software | Comment in /etc/turnserver.conf converted to setting: static-auth-secret=***
Config value turn_servers for app spreed set to [{"server":"DietPi3:3478","secret":"<OMITTED>","protocols":"udp,tcp"}]
[  OK  ] DietPi-Autostart | systemctl daemon-reload

```

**Comment by BugDave** [comment]
did you already have nextcloud installed? My issue is with a fresh install of both nextcloud and nextcloud talk

**Comment by Joulinar** [comment]
on my test I installed them one by one separately

**Comment by BugDave** [comment]
i just installed again, nextcloud binary host is being hammered but after a few timeouts it installed spreed this time without error. Maybe they pushed and update? Looks good now

**Comment by Joulinar** [comment]
Probably. I had similar experiences today. Binary download was extremely slow. But this is something out of our control.

**Comment by MichaIng** [comment]
Servers were overloaded likely because of today's NC 21 release and announcement with live stream: https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/
