### ISSUE TITLE
mjpg-streamer is unable to install because of missing blank in dependend apt-get install

### ISSUE THREAD

**Issue by mhansi12** [MichaIng/DietPi#4151]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=1
G_GITBRANCH='beta'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
      10.8
- Kernel version | `uname -a`
      Linux DietPi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
      RPi 4 Model B (armv7l)
- Power supply used | (EG: 5V 1A RAVpower)
   2,5A
- SDcard used | (EG: SanDisk ultra)
  SanDisk 32 GB
#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
  mjpg-streamer
- Was the software title installed freshly or updated/migrated?
   fresh install, because it was not available in 6.34
- Can this issue be replicated on a fresh installation of DietPi?
   I think so, I have upgraded from 6.34.5, but problem is probebly the same

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

Install 6.34.5 ( maybe new install is also ok )
Update to 7.0.0/7.0.1
install "mjpg-streamer"  with "dietpi-software" --> "Software Optimised" --> mjpg-streamer
Problem: unable to install dependend libxx-dev files, because of missing blank (" ")
Line shows:
 `apt-get -qq --allow-change-held-packages install make cmake gcc libc6-dev **libjpeg-devlibraspberrypi-dev**`

#### Expected behaviour
 `apt-get -qq --allow-change-held-packages install make cmake gcc libc6-dev libjpeg-dev libraspberrypi-dev`

#### Actual behaviour

  apt-get install error

#### Extra details
  with blank between "libjpeg-devlibraspberrypi-dev"  everything installs fine

**Comment by MichaIng** [comment]
Many thanks for reporting, I just fixed it: https://github.com/MichaIng/DietPi/commit/b2959fa29fa56f56793313f1387386216730d060

It's "**mjpg**-streamer" btw 😉.

**Comment by mhansi12** [comment]
Thank your for your fast response - I fix the name in my report and subject- other people should find ... :-)
