### ISSUE TITLE
DietPi-Software | SickRage

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#416]
> https://twitter.com/MattScherbatsky/status/750460181201481728

**Comment by rhkean** [comment]
yeah, we can do that... It's written in Python and runs similarly to CouchPotato and HeadPhones.  I used to run it before I found Sonarr.

I'll work on these next week while the Mrs. is out of town.  I've already got a media-server-common that is the base to all 3.

**Comment by Fourdee** [comment]
@rhkean 

> I'll work on these next week while the Mrs. is out of town. I've already got a media-server-common that is the base to all 3.

Excellent :+1:  I installed it just to take a look, havn't a clue how to use it lol

**Comment by rhkean** [comment]
Yeah.  Installation is pretty straight forward.

Configuration, however will require a usenet search index server.  Most of those are not free.

I'll find one that's free to use for basic setup and then document the recommendation to get an account on a non-public index server

**Comment by Fourdee** [comment]
Docs: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=3327#p3327

**Comment by Fourdee** [comment]
Completed
