### ISSUE TITLE
dietpi-software uninstall <ID> shortcut not working

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#4169]
@MichaIng 

on DietPi v7.0.2 the shortcut `dietpi-software uninstall <ID>` is not doing anything. The uninstall process is starting but terminated right after

```
root@DietPi3:~# dietpi-software uninstall 88
[  OK  ] DietPi-Software | Initialised database
[  OK  ] DietPi-Software | Reading database

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Automated uninstall

[  OK  ] DietPi-Software | Uninstalling MariaDB: database
root@DietPi3:~#
```

Running uninstallation via `dietpi-software` menu is working fine

This is the original forum post https://dietpi.com/phpbb/viewtopic.php?p=32273#p32273

I verified it on my test system

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/6449f910b6f4f7397dbf99fd16a02410eb912271
Changelog: https://github.com/MichaIng/DietPi/commit/2fef0dcfe0f16408e99d6ed360d6c8ba4a407530
