### ISSUE TITLE
DietPi-Software | Plex Remote Transcoder

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#417]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=503&p=2269#p2269

Note to self: Test installation guide by Luzi.

**Comment by ghost** [comment]
Is this by default installed in diet-pi?

**Comment by Fourdee** [comment]
@bastian94 

> Is this by default installed in diet-pi?

Plex Remote Transcoder: Not at the moment.

**Comment by ghost** [comment]
Will it never be?

**Comment by Fourdee** [comment]
@bastian94 

> Will it never be?

At some point, possibly, but i'am currently swamped with other tasks, unable to pick this one up at the moment.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
