### ISSUE TITLE
feathub doesn't work any more?

### ISSUE THREAD

**Issue by cocoflan** [MichaIng/DietPi#4174]
Is this down?

https://feathub.com/MichaIng/DietPi

**Comment by Joulinar** [comment]
Probably an issue at FeatHub themselves as the web site is not reachable at all

**Comment by MichaIng** [comment]
Yes, it's regularly down and it is not developed at all. I through to not use it anymore and switch to 👍 👎 in the GitHub issue directly.

**Comment by cocoflan** [comment]
Ok, thx for the info.

**Comment by Joulinar** [comment]
@MichaIng 
should we close this one?

**Comment by cocoflan** [comment]
ok close this one.

**Comment by MichaIng** [comment]
FYI: https://github.com/feathub/feathub/issues/11

**Comment by MichaIng** [comment]
It's up again.
