### ISSUE TITLE
Python3 Module lost after Rebooting Dietpi

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#4183]
When I install a Python3 module with `pip` (in my case `psutils`), the module will be "lost", after rebooting the Raspberry Pi. Executing my Python-Script will throw "Missing Module". Reinstalling the Module will solve this issue (until the next Reboot).

```
import psutil
ImportError: No module named psutil
```
**Debug-Information**
```
Dietpi: v6.34.3
Python v3.7.3
```
Installation: `sudo pip install psutil`
Installation-Path: `/usr/local/lib/python3.7/dist-packages/psutil/`

```
dmesg -l emerg,alert,crit,err

[   14.693962] vc_sm_cma_vchi_init: failed to open VCHI service (-1)
[   14.693977] [vc_sm_connected_init]: failed to initialize shared memory service
[   14.736935] bcm2835_mmal_vchiq: Failed to open VCHI service connection (status=-1)
[   14.941058] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   15.148396] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   15.148464] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   15.149086] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 22 2019 01:59:28 version 7.45.98.94 (r723000 CY) FWID 01-3b33decd
[   17.137060] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save disabled
```

**Comment by MichaIng** [comment]
Sounds like a read-only feature, lol.

Did you check whether the files have been created at /usr/local/lib|bin? And any kernel errors after installing the module?
```
dmesg -l emerg,alert,crit,err
```

**Comment by Gill-Bates** [comment]
My Userdata is outsourced to an external drive. It that maybe the issue?

![image](https://user-images.githubusercontent.com/25774289/110369788-2a914c80-804b-11eb-90d4-a5b722574648.png)

**Comment by MichaIng** [comment]
Not as long as it's not a local Python module installed to the userdata directory. Global/root pip installs are done to /usr/local/lib and /usr/local/bin, which is located on the root filesystem.

**Comment by Gill-Bates** [comment]
Issue solved. Root-Cause: OSI-Layer 8 :-)
I have called the script in a wrong manner.

**Comment by MichaIng** [comment]
Okay, great that it works now 🙂.
