### ISSUE TITLE
Plex server Rpi0

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#4189]
Hello
Im trying to install plex server on a Rpi0 with the:
Dietpi-software install 42
But it says its not supported by my system
Is there a way to override this and install plex?
I remember i have it installed in an older dietpi version before.
Thanks

**Comment by Joulinar** [comment]
Hi,

can you share Debian version your are running. `echo $G_DISTRO_NAME`. Unfortunately you did not fill out the questioner for opening a new issue 😉

**Comment by symbios24** [comment]
Yes sorry its Raspbian buster debian 10

**Comment by MichaIng** [comment]
Plex does not provide binaries for ARMv6, so it cannot work on Raspberry Pi 1 and Zero models. That was never different for five years 😉: https://github.com/MichaIng/DietPi/issues/648

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
