### ISSUE TITLE
autologin as dietpi user fails for LXQt

### ISSUE THREAD

**Issue by scgbckbone** [MichaIng/DietPi#4190]
#### Required Information
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=1
G_DIETPI_VERSION_RC=0
G_GITBRANCH='dev'
G_GITOWNER='MichaIng'
- Distro version | Buster 10.8
- Kernel version | Linux DietPi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:30 GMT 2021 aarch64 GNU/Linux
- SBC model | RPi 400 (aarch64)
- Power supply used | 5,1V 3A
- SDcard used | Samsung Pro Endurance 32gb

#### Additional Information (if applicable)
- Software title | LXQt
- Was the software title installed freshly or updated/migrated? fresh
- Can this issue be replicated on a fresh installation of DietPi? yes

#### Steps to reproduce
1. use appended dietpi.txt and cmdline.txt for autoinstall that tries to autologin to LXQt as dietpi user

#### Expected behaviour
this should autologin user dietpi to GUI Desktop

#### Actual behaviour
autologin to GUI as root user
then when trying to reboot I see promtp asking for removal of /var/lib/dietpi/license.txt file and after that it fails with permission denied for /dev/tty
[cmdline.txt](https://github.com/MichaIng/DietPi/files/6122809/cmdline.txt)
[dietpi.txt](https://github.com/MichaIng/DietPi/files/6122810/dietpi.txt)

**Comment by Joulinar** [comment]
Hi,

many thanks for your message. Actually this is know and works like designed. Atm you would need to use root if you like to use a desktop. We already have following feature request https://github.com/MichaIng/DietPi/issues/3586

**Comment by scgbckbone** [comment]
thanks
