### ISSUE TITLE
Jellyfin black screen after apt upgrade

### ISSUE THREAD

**Issue by rayoul** [MichaIng/DietPi#4202]
Details:
Date | Mon Mar 15 
DietPi version | v7.0.2

Hardware | Native PC (x86_64)
Kernel version | 4.19.0-14-amd64
Command | apt upgrade
Software title | Jelllyfin

Hi,
I've done an apt upgrade on my dietpi server, and saw that jellyfin package was upgraded.
After that upgrade my jellyfin server was only responding with a black screen. 
I've found a solution and change my config.json file like it's mentioned here: https://forum.jellyfin.org/t/broken-jellyfin-following-debian-buster-update-web-gui-black/4457
Now I've a loading loop (only header is loaded with home and favorites but nothing is working).

In advance thanks for your help

**Comment by MichaIng** [comment]
Hmm, a good package upgrade should apply required config file changes automatically, or the service should show a deprecation or invalid config key error, and not force the user to reset it as only solution.

But probably that was the case. General recommendation: Check the service logs before you copy&paste a random config file from non-official community members 😉:
```
journalctl -u jellyfin
```

**Comment by Joulinar** [comment]
Hi,

we had similar messages on the forum regarding Jellyfin not working after update to 10.7. It seems the update is not working well. A possible solution for the web package issue.

https://dietpi.com/phpbb/viewtopic.php?p=32522&sid=4804b67fbb625cbb6bc64189b929e707#p32522

**Comment by rayoul** [comment]
Thanks I'll try it this evening and tell you if it's working

**Comment by Joulinar** [comment]
whatever you do, it's recommended to perform a backup before. In case things will go worse, you are able to restore.

**Comment by rayoul** [comment]
It's Ok but I loose my settings, need to redo the jellyfin server settings (users and librairies)! 

To solve black screen problem You only have to replace the config.json file with this one (from jellyfin on official github): https://github.com/jellyfin/jellyfin-web/blob/master/src/config.json located at /usr/share/jellyfin/web/

I think I've done some mistakes because I was not on my local network, and I finally uninstall and reinstall jellyfin with dietpi-software.
The problem was not solved, I had to replace the config.json  And it was ok but freshly new install without my users.

I don't know how to put this issue as Solve.

Sorry for my english (I'm from France).

**Comment by nonnorm** [comment]
If the issue is solved, all you need to do is close it.

**Comment by rayoul** [comment]
> If the issue is solved, all you need to do is close it.

Thanks!
