### ISSUE TITLE
Kernel module "bcm2835_isp" is loaded even if camera is off

### ISSUE THREAD

**Issue by ferbar** [MichaIng/DietPi#4203]
### Creating a bug report/issue
lsmod shows that several video* kernel modules are loaded even if camera is turned off.
It looks as if bcm2835_isp should be blacklisted, too.

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
```
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
```
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
`10.8`
- Kernel version | `uname -a`
Linux raspi-99-4651 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
RPi A+ (armv6l)
- Power supply used | (EG: 5V 1A RAVpower)
Battery powered ;-)
- SDcard used | (EG: SanDisk ultra)
SanDisk 16GB

#### Steps to reproduce
1. fresh image
2. lsmod
```
bcm2835_isp            28672  0
bcm2835_mmal_vchiq     28672  1 bcm2835_isp
vc_sm_cma              32768  2 bcm2835_isp,bcm2835_mmal_vchiq
videobuf2_dma_contig    20480  1 bcm2835_isp
videobuf2_memops       16384  1 videobuf2_dma_contig
videobuf2_v4l2         32768  1 bcm2835_isp
videobuf2_common       61440  2 bcm2835_isp,videobuf2_v4l2
videodev              241664  3 bcm2835_isp,videobuf2_common,videobuf2_v4l2
```

#### Expected behaviour
no v4l2 kernel modules loaded
bcm2835-isp is built from https://github.com/raspberrypi/linux/tree/rpi-5.10.y/drivers/staging/vc04_services/bcm2835-isp and this code seems to be related v4l2. 

#### Actual behaviour
see "Steps to reproduce"

#### Extra details
This module probably appeared recently and was not yet added to the blacklist in
https://github.com/MichaIng/DietPi/blob/master/dietpi/func/dietpi-set_hardware#L130

```
cat /etc/modprobe.d/dietpi-disable_rpi_camera.conf
blacklist bcm2835_codec
blacklist bcm2835_v4l2
blacklist bcm2835_isp

```

Thanks a lot!

**Comment by MichaIng** [comment]
Many thanks for your report.

Indeed the automatic loading of non-required kernel modules, despite disabled devices is kinda issue on RPi: https://github.com/raspberrypi/firmware/issues/1141

Good find on this forgotten module, I have it already blacklisted on my personal RPis but forgot to add it to DietPi.

Done with: https://github.com/MichaIng/DietPi/commit/422e66fea31efd0ffcaf53fa1d9ed4fc5aa5c91e
And patches on next update with: https://github.com/MichaIng/DietPi/commit/ead4f4a50dab0cbce0ea15b58c41abb43da865b6
Changelog: https://github.com/MichaIng/DietPi/commit/8decbdb330544237dda73be34efc4414bca16422
