### ISSUE TITLE
motioneye - pytz module ImportError

### ISSUE THREAD

**Issue by githlp** [MichaIng/DietPi#4206]
G_DIETPI_VERSION_CORE=7, SUB=0, RC=2, master, MichaIng
buster
Linux DietPi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
RPi 4 Model B (armv7l)
5V 3A
SanDisk ultra 32GB

#### Steps to reproduce
in case you activate this in /etc/motioneye/motioneye.conf

`local_time_file /etc/localtime`

then the motioneye.service on DietPi is broken:

`sudo journalctl -u motioneye`
   ...
   DietPi meyectl[507]: ImportError: no module named pytz

It cannot load, although i installed pytz as user with pip/pip2.
In python shell the pytz module can be loaded though..

**Comment by MichaIng** [comment]
Many thanks for your report.

Please try to install the module globally by running pip2 as root: `sudo pip2 install -U pytz`

**Comment by githlp** [comment]
seems to work, thx!

Now i have an issue with dietpi user permantly logged in on dietpi-ip:8765 and no cam shown though i see the actual stream on dietpi-ip:8081..

i restartet motion.service, motioneye.service, the raspi .. nothing helps. When accessing :8765 the user DietPi is logged in (even on other browsers) and i have no clue how to logout and login as admin or as user again..

The "switch user" button only refreshes the site and the login dialog will not show up..

`sudo journalctl -u motioneye`

`DietPi meyectl[24360]:  WARNING: 403 GET /login/?_=1614955804882&_username=_&_signature=bcda15e9cc244b885c24bb3730ba00a0b1b5e72f (192.168.100.10) 1.33m`

**Comment by MichaIng** [comment]
Did it work before you added/uncommented the local_time_file setting? Unlikely, but at least worth to give it a try when this is all you changed. I tested here and it works, also the switch user button. But I see the same 403 warning in the logs.

I can only change the admin username and add a surveillance user. Is "dietpi" your surveillance user?

I also see an error about missing `lsb_release` command which can be fixed by `apt install lsb-release`, but I cannot see what changed, i.e. what it does. Will further investigate tomorrow: https://github.com/ccrisan/motioneye/search?q=lsb_release

**Comment by githlp** [comment]
The user is not "dietpi" , i figured out the DietPi next to the "switch user" button represents the computer (OS) name.

So it seems i am not logged in at all, therefor no cam is found/available.

It worked before for "admin" as well as for "user", and as far as i can remember i logged in mostly as "admin" to adjust settings.

To me it seems there is some problem with changed camera resolution but why should that have an effect on the login popup mask?

**Comment by githlp** [comment]
now it worked from another Computer, though. But i checked firewall and fail2ban and the first computer is not blocked or banned in any way.. Maybe DietPi or motioneye itself is blocking the IP somehow so the login popup mask won't show up?

**Comment by Joulinar** [comment]
Did you tried a different browsers? Did you cleared cookies and cache on the browser?

**Comment by githlp** [comment]
Yes, of course. That is why i think the IP gets some restriction. I will examine more logs, though most of them are empty or on some different place within DietPi..

**Comment by MichaIng** [comment]
DietPi does not block any IP by itself and does not configure motioneye to do so. By default there are indeed two users, "admin" to setup everything and indeed "user" to only view the camera. Yes the settings slide shows the hostname, hence "DietPi" by default.

Are the DietPi system and both PCs in the same network, i.e. do their IP only differ in the last triple?

**Comment by githlp** [comment]
No, they DietPi is in different subnet, but as i said, it used to work and after some while the login page just "hangs" somehow.

I can access the login page from another laptop that is also in another subnet of my home network - so that is not the problem..

When the motioneye service is not reachable/available i do not see anything in the browser except an error message. Thats why i was astonished to see the motioneye web interface just omitting the login dialog to me..

There must be some function within the login procedure that for any reason does not work for me anymore on my main computer.

**Comment by MichaIng** [comment]
Please try to update MotionEye: `sudo pip2 install -U motioneye`

**Comment by MichaIng** [comment]
I mark this as closed. If the issue persists, feel free to reopen.
