### ISSUE TITLE
nano replacement...

### ISSUE THREAD

**Issue by rhkean** [MichaIng/DietPi#421]
http://www.theregister.co.uk/2016/07/11/in_mourning_for_nano_chap_crafts_1kloc_text_editor/

https://github.com/antirez/kilo

**Comment by k-plan** [comment]
Hmm ... please don't replace nano, please add Kilo, if you can. 

It's a brand new "_toy project_" , like the coder self announce here:  http://antirez.com/news/108

**Comment by rhkean** [comment]
> @k-plan 
> Hmm ... please don't replace nano, please add Kilo, if you can.

nano must GO!!!!

(hehe... just kidding)

**Comment by Fourdee** [comment]
1272 lines, dam impressive. True lightweight justice :+1: 

But, I just cant live without:

```
CTRL+W
CTRL+T
The line number for the syntax error I may of created lol
```
