### ISSUE TITLE
DietPi-Software | PHP: Ondrej's PHP repo key expired

### ISSUE THREAD

**Issue by StormCh** [MichaIng/DietPi#4219]
#### Solution
```
apt-key del '95BD4743' # delete the old key
curl -sSfL 'https://packages.sury.org/php/apt.gpg' -o /etc/apt/trusted.gpg.d/dietpi-php.gpg # download the new key
/boot/dietpi/func/dietpi-set_software apt-cache clean # clean the apt cache
apt update # update again the package cache
```
------------
#### Details:
- Date           | Wed Mar 24 18:52:32 GMT 2021
- DietPi version | v6.34.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Meveric
- Hardware       | Odroid C2 (aarch64) (ID=12)
- Kernel version | `Linux DietPi 3.16.85+ #1 SMP PREEMPT Tue Jun 30 19:02:35 CEST 2020 aarch64 GNU/Linux`
- Distro         | stretch (ID=4)
- Command        | `apt-get -qq upgrade`
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

run dietpi-update
#### Expected behaviour:

- update to dietpi 6.35.0
#### Actual behaviour:

- ...update process fails
#### Extra details:

- ...
#### Additional logs:
```
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-defaults/php-common_81+0~20210223.34+debian9~1.gbpf52eb0_all.deb  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-apcu/php-apcu_5.1.19+4.0.11-7+0~20210222.23+debian9~1.gbp08eb57_arm64.deb  404  Not Found
E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-apcu/php7.3-apcu_5.1.19+4.0.11-7+0~20210222.23+debian9~1.gbp08eb57_arm64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by StormCh** [comment]
Solved by:

rm /etc/apt/trusted.gpg.d/php.gpg
apt-key del 95BD4743
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
apt update

**Comment by MichaIng** [comment]
Many thanks for reporting. I recognised the same on our server, Ondrejs key expired and needs to be updated. I'll implement a pre-patch to have this done automatically on next DietPi update and the present key is older than from 16-Feb-2021.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/912606ed46c8961dd20f260db281aac0858c95ea
Good idea to no install it via deprecated apt-key anymore: https://github.com/MichaIng/DietPi/commit/1356370cd8c98adcfd66171f76c829f70f1b37b2

**Comment by MichaIng** [comment]
Opening the issue and pinning it, with solution added to first post.
Ref: https://github.com/MichaIng/DietPi/issues/4254#issuecomment-815855943

**Comment by Joulinar** [comment]
Should we add the cache clean to the first post as well?

**Comment by MichaIng** [comment]
It should be not required as the list files definitely changed in the meantime, so lists are updated and the cache itself is always renewed anyway on `apt update`.
