### ISSUE TITLE
DietPi-Software | NextCloud

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#423]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=525#p2283
> a fork by the original developer of OwnCloud

https://nextcloud.com/install/#instructions-server

**Comment by sootstone** [comment]
This would be cool! It might just be that OwnCloud is frustrating enough that any alternative seems like a good idea, but I do prefer the look of where this is heading. Let me know how it's going, I'd be happy to help!

**Comment by Fourdee** [comment]
- 🈯 Lighttpd
- 🈯 Nginx
- 🈯 Apache2
- 🈯 Data store = `/mnt/dietpi_userdata/nextcloud_data`
- http://ip/nextcloud
- username = admin
- pass = dietpi
- 🈯 online doc = http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=3026#p3026

**Comment by Fourdee** [comment]
@sootstone 
Completed. Available in next release (DietPi v132).
