### ISSUE TITLE
Transmission crashing basically every day

### ISSUE THREAD

**Issue by RuneMason1** [MichaIng/DietPi#4240]
#### Required Information
7.0.2 - DietPi version | `cat /boot/dietpi/.version`
10.9 - Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
Linux DietPi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux  - Kernel version | `uname -a`
RPi4B+- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3) 
Originally included - Power supply used | (EG: 5V 1A RAVpower)
Sandisk Ultra (i think)128 GB - SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
Transmission - Software title | (EG: Nextcloud)
It's done this since i moved from aDownloader (That install corrupted somehow)- Was the software title installed freshly or updated/migrated?
This was a fresh install, if i recall correctly- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. Wait for transmission to crash?
2. ...

#### Expected behaviour

- Transmission shouldn't be crashing

#### Actual behaviour

- Transmission is crashing, nearly daily. usually when it's under load (downloading something or multiple somethings)

#### Extra details

- ...

**Comment by Joulinar** [comment]
Hi,

many thanks for your message. Some more information would be helpful. How does CPU and memory usage looks like if Transmission is crashing? Did you checked `htop` and/or `free -m`

As well can you have a look to `journalctl -u transmission-daemon.service`

Furthermore you can check kernel messages `dmesg -l err,crit,alert,emerg`

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
