### ISSUE TITLE
Dietpi-Software | Readarr

### ISSUE THREAD

**Issue by Maggus101** [MichaIng/DietPi#4246]
#### Formal software information
- Software title | Readarr
- Short description | Readarr is a ebook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books from your favorite authors and will interface with clients and indexers to grab, sort, and rename them. 
- Official URL (if available) | https://readarr.com/
- GitHub URL (if available) | https://github.com/Readarr/Readarr
- (Official) install documentation | https://github.com/Readarr/Readarr#wiki-linux

#### Are there similar/alternative software titles available with DietPi-Software?
Similar to Radarr V3 in design / implementation. Different purpose

#### What makes your requested software better than the above solutions, if available?
N/A

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
Same as Radarr

#### Can you provide the installation steps that you would suggest DietPi-Software to do?
Same as Radarr

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
Totally inexperienced sorry!

**Comment by Joulinar** [comment]
Many thanks for your request. I moved it to discussions where we start to collect software requests now. Users can vote here, which is one benefit, since FeatHub is sadly down, respectively unmaintend and cannot be used anymore.
