### ISSUE TITLE
Dietpi-software All configs

### ISSUE THREAD

**Issue by ponasromas** [MichaIng/DietPi#4257]
Recently I migrated from Nginx to Apache and all vhosts needs to be reconfigured. Re-install does not help as vhost configs are highly customized. Now, where dietpi holds default configs? For example for rtorrent apache? Nextcloud apache? Where are those files and from where they are downloaded?

**Comment by MichaIng** [comment]
Here is the default Nextcloud Apache config: https://github.com/MichaIng/DietPi/blob/dev/.conf/dps_114/apache.nextcloud.conf
The one for rTorrent is created in the dietpi-software script. Coincidentally I'm currently reworking it, that one should be fine:
```
cat << '_EOF_' > /etc/apache2/sites-available/dietpi-rutorrent.conf
<Directory /var/www/rutorrent>
	AuthType Basic
	AuthName "ruTorrent login"
	AuthBasicProvider file
	AuthUserFile "/etc/.rutorrent-htaccess"
	Require valid-user
</Directory>
<Location /RPC2>
	AuthType Basic
	AuthName "rTorrent secure access"
	AuthBasicProvider file
	AuthUserFile "/etc/.rutorrent-htaccess"
	Require valid-user
</Location>
SCGIMount /RPC2 127.0.0.1:5000
_EOF_
apt install libapache2-mod-scgi
a2enmod scgi
a2enside dietpi-rutorrent
htpasswd -cb /etc/.rutorrent-htaccess '<username>' '<password>'
```
Generally, some configs are stored [here](https://github.com/MichaIng/DietPi/tree/master/.conf) while others can be found inside of the `/boot/dietpi/dietpi-software` script.

**Comment by MichaIng** [comment]
I mark this as closed. Feel free to reopen if required.
