### ISSUE TITLE
Keep getting "[FAILED] Unknown install state/First run setup failed'

### ISSUE THREAD

**Issue by jspiers1231** [MichaIng/DietPi#4283]
I've recently got a new pack of 32gb SD cards, and put the diet pi image on one of them, and when I try to setup dietpi, the resizing fails and when I try to finish the install process, for example, when I get to the dietpi-software screen and choose the software I want, and click install, I get the first run setup failed error. I've tried hard drives and many different storage solutions, tried all the SD cards, and I couldn't get dietpi to work for a couple days.(I'm using a pi 4) And I've gone through the forums asking for help, but nothing seems to work.

**Comment by Joulinar** [comment]
Hi,

pls can you share following 3 files

```
dietpi-firstboot.log
dietpi-firstrun-setup.log
fs_partition_resize.log
```

they are located at `/var/tmp/dietpi/logs`

**Comment by jspiers1231** [comment]
[dietpi-firstboot.log](https://github.com/MichaIng/DietPi/files/6336590/dietpi-firstboot.log)

when I try to upload the dietpi-firstrun-setup.log, it says it is empty

**Comment by Joulinar** [comment]
What about the other one. `fs_partition_resize.log`

**Comment by jspiers1231** [comment]
i copied it to /boot/ and im not seeing it

**Comment by Joulinar** [comment]
Hmm that's the important one to see what the issue was during resize

**Comment by jspiers1231** [comment]
on the raspberry pi, its a file, but when i cp it to /boot/ and open it on my computer, fs_partition_resize.log is not there

**Comment by Joulinar** [comment]
You could try to open the file using `cat` and just copy the output from SSH terminal

**Comment by jspiers1231** [comment]
```
root@DietPi:~# cat /var/tmp/dietpi/logs/fs_partition_resize.log
Removed /etc/systemd/system/local-fs.target.wants/dietpi-fs_partition_resize.service.
Disk /dev/mmcblk0: 29.1 GiB, 31266439168 bytes, 61067264 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe8af6eb2

Old situation:

Device         Boot  Start     End Sectors   Size Id Type
/dev/mmcblk0p1        8192  532479  524288   256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 2092431 1559952 761.7M 83 Linux

/dev/mmcblk0p2:
New situation:
Disklabel type: dos
Disk identifier: 0xe8af6eb2

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 61067263 60534784 28.9G 83 Linux

The partition table has been altered.
```

**Comment by jspiers1231** [comment]
it does this for every single hard drive and SD card no matter if used or new

**Comment by Joulinar** [comment]
This always will be done on first initial boot as part of the initial setup

**Comment by jspiers1231** [comment]
but it just stops after there and I just unplug the power and plug it back in to continue the process

**Comment by Joulinar** [comment]
Usually it should not happen again as the trigger got removed at first

`Removed /etc/systemd/system/local-fs.target.wants/`

@MichaIng 
Can you have a look why it is not continuing. The resize seems to be fine according the log.

**Comment by jspiers1231** [comment]
@Joulinar after i plug the power back, after i seen the fs_partition_resize.log screen, it does the setup of dietpi, like setting up the passwords and selecting the software. but after i choose the software i want and click "install", i get the "[FAILED] Unknown install state/First run setup failed" error every single time

**Comment by Joulinar** [comment]
What I don't understand, why are you going to remove power. This should not be needed and indeed interrupt first initial setup

**Comment by jspiers1231** [comment]
Because it doesn't continue after:
Removed /etc/systemd/system/local-fs.target.wants/dietpi-fs_partition_resize.service.
Disk /dev/mmcblk0: 29.1 GiB, 31266439168 bytes, 61067264 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe8af6eb2

Old situation:

Device         Boot  Start     End Sectors   Size Id Type
/dev/mmcblk0p1        8192  532479  524288   256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 2092431 1559952 761.7M 83 Linux

/dev/mmcblk0p2:
New situation:
Disklabel type: dos
Disk identifier: 0xe8af6eb2

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 61067263 60534784 28.9G 83 Linux

The partition table has been altered.
^^^^^^^^
After this line, it just sits there, doesn't do anything. The process does not continue until i plug the power back in

**Comment by nonnorm** [comment]
Note that it can take a while after it shows that to finish.  How long did you wait?

**Comment by jspiers1231** [comment]
5-10 minutes

**Comment by Joulinar** [comment]
It depends on the size. Let's wait on @MichaIng

**Comment by jspiers1231** [comment]
> Note that it can take a while after it shows that to finish. How long did you wait?

Ok so i waited a little bit longer, and it worked. So it was not the software that was the problem, it was I that was the problem. It was me pulling the power too early and i didnt need to. and the reason why i pulled the power was because i thought that screen was an error

**Comment by nonnorm** [comment]
So is the issue resolved?

**Comment by jspiers1231** [comment]
yes
