### ISSUE TITLE
Default username and password for WordPress database.

### ISSUE THREAD

**Issue by poggingfish** [MichaIng/DietPi#4286]
Hey! I have really been loving DietPi. But i went to setup a wordpress server and saw that it i couldnt connect to the database during setup.

Does anyone know what the default Username and Password is? 

![image](https://user-images.githubusercontent.com/38115495/115334741-88907400-a161-11eb-82a2-50f67c96bf12.png)

**Comment by poggingfish** [comment]
### For people that are looking for the answer to this same question. Its your root password!

**Comment by Joulinar** [comment]
This is described on or online docs. https://dietpi.com/docs/software/social/#wordpress
