### ISSUE TITLE
New commands (dietpi-ddns, dietpi-vpn) do not start from commandline

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#4317]
New commands (dietpi-ddns, dietpi-vpn) do not start from commandline are not recognised.
They do start via dietpi-launcher menu.

```
root@M-DNS:/# dietpi-ddns
-bash: dietpi-ddns: command not found
```

```
root@M-DNS:/# dietpi-vpn
-bash: dietpi-vpn: command not found
```

**Comment by Joulinar** [comment]
Did you reboot your system after update?

**Comment by maartenlangeveld** [comment]
No... will try

**Comment by MichaIng** [comment]
Alternatively `. /etc/bashrc.d/dietpi.bash` to load the new aliases.

**Comment by Joulinar** [comment]
Or logout/login

**Comment by maartenlangeveld** [comment]
Thanks!

**Comment by Joulinar** [comment]
Is it working now?

**Comment by maartenlangeveld** [comment]
Yes! Thanks for the great work.
I have one question. Using pivpn up until now as openvpn server. Does dietpi-vpn openvpn server as well (or only client?)

**Comment by MichaIng** [comment]
It's a client only so far. Maybe we can extend it to configure a server as well by times, adding a client config/revocation UI. But first of all we'll extend the client functionality, adding more providers, free port choice, server rotation and such 😃.

**Comment by Joulinar** [comment]
Going to close this as the issue is fixed
