### ISSUE TITLE
DietPi-Software | FireFox Sync 1.5 Server

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#435]
Although this is limited to Firefox it would be nice to find something that worked for Chrome and FF.

 FireFox Sync allows users devices to access Firefox browsing history, bookmarks, and recent tabs.
https://github.com/mozilla-services/syncserver
https://docs.services.mozilla.com/howtos/run-sync-1.5.html#howto-run-sync15

**Comment by joaofl** [comment]
I had it once, but I no longer found means of configuring my Firefox with a custom server address. How can it be done?

**Comment by Elluminatus** [comment]
+1

**Comment by Fourdee** [comment]
+1 > http://dietpi.com/phpbb/viewtopic.php?f=12&t=788&p=7246#p7244

**Comment by molnarti** [comment]
@joaofl see here https://mozilla-services.readthedocs.io/en/latest/howtos/run-fxa.html

**Comment by Jlkam** [comment]
+1 hope we see this soon!

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
