### ISSUE TITLE
Dietpi-banner | VPN Status not showing

### ISSUE THREAD

**Issue by Maggus101** [MichaIng/DietPi#4354]
### Creating a bug report/issue

/boot/dietpi/func/dietpi-banner: line 214: /boot/dietpi/misc/dietpi-vpn: No such file or directory

Using Mullvad VPN. Connected and working using their Mac OVPN file. Just can't get the banner to show connected.

#### Required Information
- DietPi version | `v7.1.2 (beta)`
- Distro version | `buster`
- Kernel version | `4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`
- SBC model | `Native PC (x86_64)

#### Additional Information (if applicable)
- Software title | Dietpi-banner
- Was the software title installed freshly or updated/migrated? Updated
- Can this issue be replicated on a fresh installation of DietPi? 

#### Steps to reproduce

1. ... Login / run dietpi-banner

#### Expected behaviour

- ... Show connected / disconnected

#### Actual behaviour

- ... /boot/dietpi/func/dietpi-banner: line 214: /boot/dietpi/misc/dietpi-vpn: No such file or directory

#### Extra details

- ... Confirmed that /boot/dietpi/misc/dietpi-vpn is missing. 
- Tried in root. Same issue

**Comment by MichaIng** [comment]
Many thanks for your report.

We changed the scripts path but indeed forgot to change it in the banner code as well. Just fixed for the next version: #4355
