### ISSUE TITLE
DietPi-Software | Emby now requires FFmpeg to be installed

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#436]
As title:

> http://dietpi.com/phpbb/viewtopic.php?f=12&t=365&p=2395#p2393

**Comment by Fourdee** [comment]
Tested on RPi 3. No longer asks for FFmpeg during Emby wizard.

**Comment by WolfganP** [comment]
Tested workaround with manual ffmpeg installation on RasPi2, it worked as well.
