### ISSUE TITLE
DietPi-Automation | Apply public SSH key on first boot

### ISSUE THREAD

**Issue by mwip** [MichaIng/DietPi#4381]
#### Is your feature request related to a problem? Please describe:
- ssh authorization through keys is both more convenient and secure than password-based authentication

#### Describe the solution you'd like:
- It would be cool to have two variables in `/boot/diepi.txt`

1. to share one or multiple public ssh-rsa key(s) of the client machine(s) one will want to access dietpi from
2. a toggle variable to disable password-based authentication alltogehter

#### Additional context
- this feature request is based on #4380 

*Note*: Full disclosure, I'm no expert on (ssh-)security. So this should be looked into, verified and checked by more credible people in that realm.

**Comment by MichaIng** [comment]
Not to forget modern ECDSA and Ed25519 keys 😉.

**Comment by mwip** [comment]
I tested Ed25519 on my dietpi install and it seems that the version of dropbear (v2018.76) does not yet support Ed25519. Reading through the [changelog](https://matt.ucc.asn.au/dropbear/CHANGES), it seems that only dropberar_2020.79 and higher support it. Thought I leave this here, in case someone runs into this.

**Comment by MichaIng** [comment]
Jep that is true.

**Comment by MichaIng** [comment]
I accidentally opened a duplicate with some more ideas on that: #4639

**Comment by MichaIng** [comment]
Implemented with DietPi v8.5: #5509
