### ISSUE TITLE
Home Assistant not starting from fresh install

### ISSUE THREAD

**Issue by LilTrublMakr** [MichaIng/DietPi#4421]
#### Required Information
- DietPi version |
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=1
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | BUSTER
- Kernel version | `Linux DietPi 5.10.17-v8+ #1414 SMP PREEMPT Fri Apr 30 13:23:25 BST 2021 aarch64 GNU/Linux`
- SBC model | RPi 4B 4GB
- Power supply used | Official Power Supply
- SDcard used | Samsung EVO Select 32GB

#### Additional Information (if applicable)
- Software title:
Home Assistant

- Was the software title installed freshly or updated/migrated?
Fresh install

- Can this issue be replicated on a fresh installation of DietPi?
Have not tried since the install is fresh as of yesterday.

- Bug report ID | N/A

#### Steps to reproduce
1. Install Home Assistant via the official `dietpi-software` command
2. Waited for the installation to complete. (https://pastebin.com/h87JS2Fe)
3. Ran `htop` in another SSH window.

#### Expected behaviour
- Expected to see a home assistant process running as per the docs (https://dietpi.com/docs/software/home_automation/#home-assistant)

#### Actual behaviour
- No Home Assistant process running. 

#### Extra details
- I tried restarting the HA service manually using `systemctl start home-assistant` and it instantly exits.
- Logs via `journalctl -u home-assistant`: https://pastebin.com/zT33bNHt

**Comment by ravenclaw900** [comment]
Hello,
This is a known issue, and will be fixed with the release of 7.2 in a few days.  You can find a fix for this [here](https://github.com/MichaIng/DietPi/issues/4372#issuecomment-840643762).
