### ISSUE TITLE
Blynk Server for IoT

### ISSUE THREAD

**Issue by joaofl** [MichaIng/DietPi#445]
A very nice initiative for IoT is called [Blynk](http://www.blynk.cc/), and they provide their server code to be run in you own server for privacy concerns. Have it installed at my dietpi xu4, and would be great to have it listed at dietpi-software.

They provide an Android iOS app to interface with your raspberry/arduino/esp8266, through an onlline server of yours.

it requires java (openjdk8), and almost none initial setup

http://docs.blynk.cc/#blynk-server-requirements

**Comment by oshank** [comment]
I second this request. Been looking into it for the last few days. I think it would be pretty cool to see this on the list. Should be relatively simple to set up I believe.

http://docs.blynk.cc/#blynk-server

**Comment by Fourdee** [comment]
Fails connection test...
```
			INSTALL_URL_ADDRESS='https://github.com/blynkkk/blynk-server/releases/download/v0.22.3/server-0.22.3.jar'
			/DietPi/dietpi/func/check_connection "$INSTALL_URL_ADDRESS"
```

- 🈯️ https://github.com/blynkkk/blynk-server/releases
- 🈴 https://github.com/blynkkk/blynk-server/releases/download

**Comment by Fourdee** [comment]
online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=5901#p5901

**Comment by Fourdee** [comment]
Commit: https://github.com/Fourdee/DietPi/commit/045284afc43488822e83c549de2bb924362eaa32

**Comment by Fourdee** [comment]
Just about to finish off the online doc, http://blynk.cc is down lol, typical.

**Comment by Fourdee** [comment]
Completed.

**Comment by oshank** [comment]
Thanks!

**Comment by joaofl** [comment]
@Fourdee 

I was testing the Blynk server today, but could not access the admin page from a remote pc, because by default, it is enable to local only. 

Also, by not having a config file, limits on doing other customizations.
So I did some minor changes to the dietpi-software install script to address this issue. 

I only missed adding a line to replace a line in the config file (sed -i   afraid of messing around).

I'm not exactly sure if I proposed the patches using the correct procedure, but anyway, I hope it helps.

**Comment by Fourdee** [comment]
@joaofl 

Thanks for the report and changes 👍 

> So I did some minor changes to the dietpi-software install script to address this issue.

Would you be able to send a pull request for the changes, here on git? Please use the following **testing** branch when sending the pull request:
https://github.com/Fourdee/DietPi/tree/testing

**Comment by joaofl** [comment]
I think I did it right this time.

https://github.com/Fourdee/DietPi/pull/810

**Comment by Fourdee** [comment]
@joaofl 
Awesome 👍 
![image](https://cloud.githubusercontent.com/assets/7077026/24071958/ac6faf06-0bd5-11e7-8b3e-74303c6a8e17.png)

I'll update online docs once our hosting provider is back online, then mark this as completed.

**Comment by Fourdee** [comment]
Online doc updated: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=5901#p5901

Great work @joaofl, marking this as completed 👍

**Comment by joaofl** [comment]
@Fourdee ,thanks for that. I hope I can contribute further on. :+1::+1::+1:
