### ISSUE TITLE
TOR-version outdated

### ISSUE THREAD

**Issue by mews-se** [MichaIng/DietPi#4467]
Any chance that the TOR version could be updated. As of today DietPI comes with 0.3.5.14 when TORProject as of today recommends 0.4.5.8

**Comment by Joulinar** [comment]
Hi,

TOR is installed from global Debian `apt` package source. There latest version is 0.3.5.14 https://packages.debian.org/buster/tor

**Comment by MichaIng** [comment]
If you're not using a Raspberry Pi, or you're using the 64-bit image (hence not Raspbian but Debian), then you can upgrade via backports to current version: https://packages.debian.org/buster-backports/tor
```
apt install -t buster-backports tor
```
