### ISSUE TITLE
DietPi-Software | Web Dashboard for DietPi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#448]
### **ADMIN EDIT**

Dashboard is available for testing, see https://github.com/ravenclaw900/DietPi-Dashboard#installation for instructions.

#

Base:
- Must not require a webserver stack (implies self contained website). eg: Websockets and Bootstrap/JS
- Lightweight (minimal cpu and memory usage)

Main DietPi programs for web implementation:
- DietPi-Software
- DietPi-Config

Additional features:
- Terminal window

**Comment by rhkean** [comment]
brainstorming.....  this can probably be done with python.  Couchpotato and NzbHydra use python and have decent simple web interfaces.  But, so does netdata and it's written in C.

**Comment by tr0yspradling** [comment]
I plan on taking a stab at this with Python/Flask.

**Comment by Fourdee** [comment]
@tr0yspradling 

> I plan on taking a stab at this with Python/Flask.

Excellent :+1: 

We will need to change alot of the DietPi code to truly accommodate the web dashboard, but either myself or @rhkean can do this alongside @tr0yspradling's work. 
If you have any progress, let us know.

**Comment by Fourdee** [comment]
@rhkean 

> But, so does netdata and it's written in C.

YMPD is also written in C: https://github.com/notandy/ympd

> Standalone MPD Web GUI written in C, utilizing Websockets and Bootstrap/JS http://www.ympd.org

**Comment by WolfganP** [comment]
Great idea. I think that the system will benefit more if it's designed extensible from the start, so it can be tailored for custom system commands or headless operation (ie one button remote system shutdown/restart, modules commands -ie minidlna db rescan-, etc)

**Comment by Fourdee** [comment]
@WolfganP 

Yep, ideally i'd like a system where users can either use the web dash, or, terminal for all DietPi features.  
So for example, we could have a DietPi-Software page where the user can install software from a list, then follow a link to the docs. Basically a duplicate of the whiltail menu, but in a better web format. Possibilities are endless.

 I recently added code that allows for automated command line installations:

```
/DietPi/dietpi/dietpi-software install KODI HIFI
```

But I/we will need help with this, I can do the bash/unix side, but i lack the skills for the web side.

**Comment by rhkean** [comment]
> @WolfganP 
> Yep, ideally i'd like a system where users can either use the web dash, or, terminal for all DietPi features.

terrific idea.  The trick, I think, will come in finding a way to do this that maintains the small footprint that is at the heart of DietPi

**Comment by WolfganP** [comment]
Ideally it should just be a different UI for using the existing installation / config scripts, with the ability to add user scripts / commands / recipes somehow (to avoid reinventing the wheel and having to reimplement the current / tuned dietpi-\* specific scripts).

**Comment by tr0yspradling** [comment]
I've created [DietPi-Dashboard](https://github.com/tr0yspradling/DietPi-Dashboard). It's a skeleton project at the moment, but I'll have some progress up soon. 

I've decided to use CherryPy instead of Flask, but I'm curious, should we reverse proxy through NGINX or use the standalone server with CherryPy?

**Comment by Fourdee** [comment]
@tr0yspradling 

That was quick, looking forward to seeing it progress :+1: 

> I've decided to use CherryPy instead of Flask, but I'm curious, should we reverse proxy through NGINX or use the standalone server with CherryPy?

I would prefer it didn't required a webserver, self contained in a standalone server would be ideal.

**Comment by Fourdee** [comment]
@WolfganP 

> Ideally it should just be a different UI for using the existing installation / config scripts, with the ability to add user scripts / commands / recipes somehow (to avoid reinventing the wheel and having to reimplement the current / tuned dietpi-\* specific scripts).

Yep. 
To start off with, we'll start small and see what the dash can do. In time, we can always add more to it. I have this vision of making DietPi completely web interfaced, but at this time, its just an idea. We'll see how it goes :)

**Comment by tr0yspradling** [comment]
Right now I'm working on syncing live system information with [python-socketio](https://github.com/miguelgrinberg/python-socketio) and displaying it with [Chart.js](https://github.com/chartjs/Chart.js). Once I finish that, I'm going to add process & software package management.

**Comment by k-plan** [comment]
Hi,

are where any news? Thanks.

**Comment by Fourdee** [comment]
Note to self: 

Libaries:
- https://www.webtoolkit.eu/wt
- http://cppcms.com/wikipp/en/page/main

IDE's:
- VS2015 + https://visualstudiogallery.msdn.microsoft.com/725025cf-7067-45c2-8d01-1e0fd359ae6e
- http://www.linuxandubuntu.com/home/8-best-ides-or-code-editors-for-linux
- https://code.visualstudio.com/

**Comment by tr0yspradling** [comment]
I'll be updating the repository tonight. I'll post back here when I do.

**Comment by tr0yspradling** [comment]
@Fourdee I considered using [Crow](https://github.com/ipkn/crow).

**Comment by tr0yspradling** [comment]
I haven't been able to get as much done as I hoped, I had another project taking up most of my time. 

Check out [DietPi-Dashboard](https://github.com/tr0yspradling/DietPi-Dashboard) to see what's there. It needs cleaned up and reorganized a little, some of the major features aren't implemented yet.

**Comment by Fourdee** [comment]
@tr0yspradling

> time

No worries :+1: 

> Check out DietPi-Dashboard to see what's there. It needs cleaned up and reorganized a little, some of the major features aren't implemented yet.

I'am a bit of a Python "n00b" (Its like reading an Alien language for me, with a few English letters and numbers in-between lol) , but i'll give it a whirl, `run.py` to launch?

**Comment by Fourdee** [comment]
Notes: Quick install deps and run:

```
apt-get install -y python python3 python-pip python-dev #build-essential
wget https://github.com/tr0yspradling/DietPi-Dashboard/archive/master.zip -O package.zip
unzip package.zip
rm package.zip
chmod +x -R DietPi-Dashboard-master
cd DietPi-Dashboard-master
pip install -r requirements.txt
./start
```

@tr0yspradling Expected?

```
root@DietPi:~# DietPi-Dashboard-master/run.py
from: can't read /var/mail/flask
from: can't read /var/mail/werkzeug.debug
from: can't read /var/mail/flask_socketio
DietPi-Dashboard-master/run.py: line 5: import: command not found
DietPi-Dashboard-master/run.py: line 6: import: command not found
DietPi-Dashboard-master/run.py: line 7: import: command not found
from: can't read /var/mail/project.server
from: can't read /var/mail/project.server
DietPi-Dashboard-master/run.py: line 12: syntax error near unexpected token `('
DietPi-Dashboard-master/run.py: line 12: `application = create_application(debug=True)'
```

**Comment by tr0yspradling** [comment]
The application depends on several python packages. The python package index can be installed with
`sudo apt install python-pip`
and the dependencies can be installed by running
`sudo pip install -r requirements.txt`

I'm creating a virtualenv and startup script for it now. I'll update when I've finished my modifications.

**Comment by tr0yspradling** [comment]
Check [DietPi-Dashboard](https://github.com/tr0yspradling/DietPi-Dashboard). Executing `./start` should work.

**Comment by Fourdee** [comment]
@tr0yspradling 

Tried on my test rig (Odroid C2, ARM64):

```
root@DietPi:~/DietPi-Dashboard-master# ./start
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from project.server import sioServer
  File "/root/DietPi-Dashboard-master/project/server/__init__.py", line 3, in <module>
    from dashboard.views import dashboard_routes
  File "/root/DietPi-Dashboard-master/project/server/dashboard/views.py", line 9, in <module>
    from diagnosticsReport import DiagnosticsReport
  File "/root/DietPi-Dashboard-master/project/server/dashboard/diagnosticsReport.py", line 2, in <module>
    import cpuinfo
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/__init__.py", line 5, in <module>
    from cpuinfo import *
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 1553, in <module>
    _check_arch()
  File "/usr/local/lib/python2.7/dist-packages/cpuinfo/cpuinfo.py", line 1510, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.
```

I'll power up a RPi and try it.

**Comment by Fourdee** [comment]
@tr0yspradling 

I love where this is going. This is exactly what DietPi needs. Great work :+1:
![image](https://cloud.githubusercontent.com/assets/7077026/18009068/98c183ae-6ba2-11e6-988b-f67f305f0e0a.png)

Ps. you should put "DietPi-Dashboard created by tr0yspradling/realname" in the footer ;)

**Comment by tr0yspradling** [comment]
I'll have to go through and check the supported architectures for each supported platform. I didn't think of that. 

I should have done this from the start, but I'll go through and pull the data from the special file: `/proc/cpuinfo`

**Comment by tr0yspradling** [comment]
We should start reporting issues to the dashboard repository so it's more organized.

**Comment by Fourdee** [comment]
@tr0yspradling 

> We should start reporting issues to the dashboard repository so it's more organized.

Good call :+1: 
I'd like to add a few tickets with features I'd like to see, and discuss their implementation if thats ok?

**Comment by tr0yspradling** [comment]
Absolutely. Check your email!

**Comment by WolfganP** [comment]
Looks great guys, good work

**Comment by bhaveshgohel** [comment]
@tr0yspradling Neat and clean, that's what needed! Awesome! :+1:

**Comment by WolfganP** [comment]
@Fourdee Looking at your instructions, I think it's easier to install (and keep updated) via git

```
git clone https://github.com/tr0yspradling/DietPi-Dashboard.git
cd DietPi-Dashboard
pip install -r requirements.txt
./start
```

Anyways, I assume that the way to access the Dashboard is via a desktop browser and http://raspi-ip:9090 ?

**Comment by Fourdee** [comment]
@WolfganP 

> I think it's easier to install (and keep updated) via git

Yep. 
We prefer to download the zip instead of using git clone in `dietpi-software`. Reason being additional packages are required to use `git clone`.

> http://raspi-ip:9090

Yep, thats the plan. I think the current port is 8080, but this may change.

**Comment by Fourdee** [comment]
@tr0yspradling 
Looks like you deleted your repo for this? https://github.com/tr0yspradling/DietPi-Dashboard

Heres the C++ version i've started: https://github.com/Fourdee/DietPi-Dashboard
Managed to pull all the DietPi-Software data into c++. Can now install software from it. Time to start on the web side.

**Comment by mknrls** [comment]
@Fourdee so you still want the dashboard to be  self contained meaning without using a webserver?

**Comment by Fourdee** [comment]
@mknrls 

> so you still want the dashboard to be self contained meaning without using a webserver?

Yep, self contained, that was the plan, try and keep it minimal. But at this stage, I am up for anything.

**Comment by Fourdee** [comment]
As much as I'd love to see this in DietPi, we currently lack the man hours to achieve this. Just not feasible at the moment.

Closing.

**Comment by ravenclaw900** [comment]
I could try and create this with Go and Svelte.  I'll probably use TailwindCSS instead of Bootstrap, though.

**Comment by MichaIng** [comment]
Interesting find, I never knew that there has already been some work done on this idea, sadly discontinued. Would be awesome to revive it, basically some sort of webmin tailored for DietPi, which can potentially inherit the features of the Allo GUI as well, which, to be honest, requires a major rework to fit modern standards, also security wise. But while I learned to do HTML, CSS, JavaScript etc, I have not much experience with any real programming language, neither C++, not Go, while I usually learn and understand it fast, when needed.

Yep, Go seems to generally fit well, or Rust (while then I'd even less of help, given the larger syntax and logic differences 😄)? No preference on the style framework on my end. While our website uses bootstrap, I actually aim to remove it, when I find time. We use only a minimal subset and overwrite many of the defaults, so much wasted code we load into browsers. But first and easier will be to eliminate jQuery 😃.

**Comment by ravenclaw900** [comment]
> We use only a minimal subset and overwrite many of the defaults

That's why I prefer Tailwind, it's a utility framework instead of a component, and it supports tree-shaking.

**Comment by ravenclaw900** [comment]
Note to anyone that wants to compile this, make sure that you have Yarn and Go installed, then just run `make` in the project root.  This should compile a binary for your platform, however I wrote it with Linux/Unix commands, so I'm not sure how it will run on Windows.

**Comment by ravenclaw900** [comment]
@MichaIng, @Joulinar, @fpetru, @StephanStS, could you review?  I plan to also add a management page, with generic tasks like shutting down and restarting the system, and a terminal.  Also, currently I'm just using the generic Tailwind lime colors, if you have a specific color code you'd like me to use please let me know.

**Comment by Joulinar** [comment]
for colour code, I would recommend to use the same as on our web side/ docs.

Basically I like the idea. Especially to have a web terminal. 😃

**Comment by GvY85** [comment]
This sounds like a great idea 👍 .

@ravenclaw900 can you perhaps write a (very minimal, only a list of cli commands is enough) manual on how to install/use this so more people can test/try/give feedback.

**Comment by ravenclaw900** [comment]
Prereq:
```sh
dietpi-software install 9 16 17 188 # Install Node.js (webpage), Build-Essential (make), Git (git clone), and Go (binary), respectively
npm install -g yarn # Install Yarn package manager, for node dependencies
```
Now log out and log back in to register GOPATH
Compiling:
```sh
rm -rf DietPi-Dashboard # Remove possibly pre-download repository
git clone https://github.com/ravenclaw900/DietPi-Dashboard # Download source code
cd DietPi-Dashboard/src/frontend # Change directories
yarn # Install dependencies
cd ../.. # Change directories
make # Compile binary for your platform
./dietpi-dashboard # Run binary
```
Now just visit http://device.IP:8080.  Note that for DietPi-Software installs to work, the binary needs to be run as root.

Wow, I thought that it was a bug in the program that RAM and CPU were almost 0, stock DietPi is *really* lightweight.

**Comment by Joulinar** [comment]
Nice, I did a test installation. Some observation

- process overview seems to be a heavy view. At least on my test VM it's causing high CPU usage
- I did 2 test installations from software catalogue, The output window on the bottom seems to be very small. It's quite hard to read the output.
- after software installations, the other 2 options `Statistics` and `Processes` are not working anymore. It's needed to perform a full fresh of the web page. This are the messages during page reload

```
2021/09/03 01:27:23 http: panic serving 192.168.0.53:56438: interface conversion: interface {} is nil, not []interface {}
goroutine 45 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x673720, 0xc00014e000})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/ravenclaw900/DietPi-Dashboard/lib.ServeWebsockets({0x758fc8, 0xc0000c8380}, 0x0)
        /root/DietPi-Dashboard/src/backend/lib/sockets.go:107 +0x898
net/http.HandlerFunc.ServeHTTP(0x0, {0x758fc8, 0xc0000c8380}, 0x0)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x758fc8, 0xc0000c8380}, 0xc0002f3900)
        /usr/local/go/src/net/http/server.go:2424 +0x149
net/http.serverHandler.ServeHTTP({0xc00014ec00}, {0x758fc8, 0xc0000c8380}, 0xc0002f3900)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc000080320, {0x75a060, 0xc00006ef60})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
```

Tested on Bullseye VM amd64

**Comment by ravenclaw900** [comment]
1. Yeah, that's a bit resource heavy, I'm trying to figure that out
2. Enlarged window height
3. It kept reading messages into the same struct, without trying to overwrite them, thus it was probably still trying to un/install software whenever the page was changed.  Fixed
4. The graph is being generated in the browser, and it will keep going until it's closed

**Comment by ravenclaw900** [comment]
I just pushed a commit with a terminal window, let me know how it looks.

**Comment by ravenclaw900** [comment]
Alright, I added a few more features, and I'm hopeful for a `0.1.0` release.

**Comment by Joulinar** [comment]
ok did some testing. looks quite nice. Joining the `terminal` view is giving following

2021/09/06 15:08:46 Request to /ws/term (terminal)
2021/09/06 15:09:31 Couldn't get data from frontend: websocket: close 1005 (no status)
2021/09/06 15:09:37 Request to /ws/term (terminal)
2021/09/06 15:09:39 Couldn't get data from frontend: websocket: close 1005 (no status)
2021/09/06 15:09:40 Request to /ws/term (terminal)
2021/09/06 15:09:41 Couldn't get data from frontend: websocket: close 1005 (no status)
2021/09/06 15:09:48 Request to /ws/term (terminal)
2021/09/06 15:09:49 Couldn't get data from frontend: websocket: close 1005 (no status)
2021/09/06 15:09:52 Request to /ws/term (terminal)
2021/09/06 15:09:54 Couldn't get data from frontend: websocket: close 1005 (no status)

**Comment by ravenclaw900** [comment]
That's normal, it closes the connection when you leave the terminal page (as long as it's only happening when you leave the page).  I'll make it use the normal exit code.

**Comment by ravenclaw900** [comment]
Version 0.1.0 released, see https://github.com/ravenclaw900/DietPi-Dashboard/releases/tag/v0.1.0 for precompiled binaries.

**Comment by ravenclaw900** [comment]
I might try to rewrite part of the backend in Rust, just to see how it compares (Rust is supposed to be faster, use less memory, and have smaller binary sizes).  If it's better by a sizeable amount, I might consider switching the whole thing.

**Comment by ravenclaw900** [comment]
New compilation instructions:
Prereq:
```sh
dietpi-software install 9 16 17 # Install Node.js (webpage), Build-Essential (make and gcc), and Git (git clone), respectively
npm install -g yarn # Install Yarn package manager, for node dependencies
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # Install Rust (backend)
```

Compiling:
```sh
rm -rf DietPi-Dashboard # Remove possibly pre-download repository
git clone https://github.com/ravenclaw900/DietPi-Dashboard # Download source code
cd DietPi-Dashboard/src/frontend # Change directories
yarn # Install dependencies
cd ../.. # Change directories
make # Compile binary for your platform
./dietpi-dashboard # Run binary
```

**Comment by ravenclaw900** [comment]
@Joulinar, could you test the new Rust binary. Performance seems to have improved greatly on things like the Processes page, for me from `103%` to `12%` CPU.

**Comment by Joulinar** [comment]
@ravenclaw900 
there is an error message running `make`

```
root@DietPi4:/tmp/DietPi-Dashboard# make
cd src/frontend; yarn build
yarn run v1.22.11
$ rollup -c

src/main.ts → public/build/bundle.js...

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
created public/build/bundle.js in 51.1s
Done in 53.11s.
rustfmt --edition 2018 src/backend/src/*
/bin/sh: 1: rustfmt: not found
make: *** [Makefile:27: fmt] Error 127
root@DietPi4:/tmp/DietPi-Dashboard#
```

**Comment by ravenclaw900** [comment]
Interesting, that should be installed when installing Rust. Could you try `rustup component add rustfmt`?

**Comment by Joulinar** [comment]
way better now as you added the `source` line.

that's resource consumption while process view is open. Running on RPi4B 8GB, Bullseye, ARMv8

![image](https://user-images.githubusercontent.com/47155374/134416970-76dbedeb-5ca7-4f05-b3fb-5022036ce8cf.png)

**Comment by ravenclaw900** [comment]
@MichaIng, there's dark mode now.

**Comment by ravenclaw900** [comment]
Version 0.2.0 released, see https://github.com/ravenclaw900/DietPi-Dashboard/releases/tag/v0.2.0 for precompiled binaries.

**Comment by ravenclaw900** [comment]
Other than a file browser, I can't think of any other core features (other than `dietpi-config`, but it would require the whiptail to be parsed) that would need to be added. Any ideas?

**Comment by Joulinar** [comment]
hmm what about the possibility to view status of DietPi services like `dietpi-services status`. Or to show current DietPi version + available updates, as well available apt package updates?

**Comment by ravenclaw900** [comment]
Current version is already shown in the management page, but I could show updates there too. And a services page would also make sense.

**Comment by Joulinar** [comment]
question: It always shows `DietPi update avalible:` on the header. Should it be visible on available updates only? It is there on red letters and could lead to the impression an update would be available.

**Comment by ravenclaw900** [comment]
I noticed the update issue, fixed now. Log is shown when a service fails. What architecture/device are you using? It displays correctly on aarch64, but not on armv6. I also noticed it getting stuck on my lower-power RPi0W, I'll try to see where.

**Comment by Joulinar** [comment]
I used RPi3B+ ARMv6 Bullseye

**Comment by ravenclaw900** [comment]
Problem solved, it doesn't get stuck anymore. I had to specify multi-thread by default.

**Comment by GvY85** [comment]
Hi, I think this does not get the attention it deserves :).
Perhaps it helps to update the posts (here or on your repo) with some screenshots and an updated how to use for the releases.
I think this shows a lot of potential but we need people to start using it in order to get @MichaIng to implement it

**Comment by Joulinar** [comment]
@ravenclaw900 is part of our team and the dashboard is in an early status. We invite everybody to test and give feedback

**Comment by MichaIng** [comment]
I read every post that appears here and am very interested to implement this. I just kept quite until I find the time to really test it 😉. With v7.8 we'll get this merged, I'm sure.

**Comment by Joulinar** [comment]
ahh cool. Quite easy to install the `nightly`. Looks good.

**Comment by ravenclaw900** [comment]
@MichaIng, just added config file with port and TLS support.

**Comment by ravenclaw900** [comment]
Could you test the binaries linked against the `musl` libc library? They seem to have lower memory usage in general. https://github.com/ravenclaw900/DietPi-Dashboard/actions/runs/1427621051

**Comment by MichaIng** [comment]
Hmm, when downloading these artifacts via curl, I get a 404, when using wget, a 400, same when I use the final URL that is redirected to. Via browser it works well, but I'm too lazy to install desktop + browser on all test systems. Any idea how those can be downloaded from command line? 🤔

**Comment by ravenclaw900** [comment]
It requires you to be logged in with a GitHub account. You could use the nightly.link: https://nightly.link/ravenclaw900/DietPi-Dashboard/actions/runs/1427621051.

**Comment by MichaIng** [comment]
These work, thanks. Indeed these use only about 60% of memory 👍.

**Comment by GvY85** [comment]
Tried out the Stable release in 7.8 Beta and this is really great!

Some remarks:
-I could not get the terminal working. There seems to be a cursor when clicking but nothing happens when typing.
-Is it possible to add a login screen? Now everyone with local network access can mess with the system.
-The installation and updating process needs some tweaking/more info I think. I had to `systemstl status dietpi-webdashboard` to find put the port it was using. Perhaps make that also configurable?
-Layout and graphics are really nice but perhaps an option to change the default colors?I know everyone loves the DietPi theme but for those that love other colors just a bit more that would be great ;) .

**Comment by MichaIng** [comment]
> I could not get the terminal working. There seems to be a cursor when clicking but nothing happens when typing.

Known issue and fixed with next beta, which I will push in 1-2 hours: https://github.com/ravenclaw900/DietPi-Dashboard/issues/24

> When switching 'tabs' a few times it seemed to get stuck on "loading" after a while.

I suppose this is as navigating to Terminal currently stops the service. Here a manual fix btw:
```sh
cat << '_EOF_' > /etc/systemd/system/dietpi-dashboard.service
[Unit]
Description=Web Dashboard (DietPi)
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/opt/dietpi-dashboard/dietpi-dashboard
StandardInput=tty
TTYPath=/dev/tty42
StandardOutput=journal

[Install]
WantedBy=multi-user.target
_EOF_
systemctl daemon-reload
systemctl restart dietpi-dashboard
```

> Is it possible to add a login screen?

Indeed needed IMO. My idea was to keep it simple and use password protection only (no user management): https://github.com/ravenclaw900/DietPi-Dashboard/issues/11
The only question is whether regular HTTP authentication with user + password is much simpler to implement with existing Rust crates. Feel free to contribute to the linked request/discussion.

> The installation and updating process needs some tweaking/more info I think

Jep, a documentation is required: https://github.com/MichaIng/DietPi-Docs/issues/610

Update should be done via `dietpi-software reinstall 200`, but we may consider to do this automatically as part of `dietpi-update`, at least definitely if changes in DietPi require a related update of the dashboard.

> Layout and graphics are really nice but perhaps an option to change the default colors?

Good idea. As of my preference for dark modes, @ravenclaw900 was so kind to make realise this: https://github.com/MichaIng/DietPi/issues/448#issuecomment-927196217
However, would be great to have at least a dark/bright mode switch, or even switching the accent colour from green to something else. But I'd consider this a minor long term request and focus on stability and a reasonable set of core features first.

Since this issue will be closed with the release, it would be great if you guys could check for requests/issues on the actual dashboard repository, and if not existing yet, report it there: https://github.com/ravenclaw900/DietPi-Dashboard/issues

**Comment by tandy-1000** [comment]
>![image](https://cloud.githubusercontent.com/assets/7077026/18009068/98c183ae-6ba2-11e6-988b-f67f305f0e0a.png)

I installed the dashboard, but I much prefer these colors to the current "dietpi"-esque theme, . I imagine https://github.com/ravenclaw900/DietPi-Dashboard/issues/29 is fixing that?

Another idea that may be out of scope to this project is doing regular SMART checking of hard drives. Could require an extension to dietpi_drive-manager.
I use scrutiny for that purpose at the moment.

**Comment by MichaIng** [comment]
Jep, the linked request is about this at least. Though no ETA when we will address it.

SMART data is indeed an interesting idea, probably to show on the Management page. Since not all drives support SMART, I'd implement it as optional, e.g. using `smartmontools`, if installed, and skip it, if not installed.

**Comment by MichaIng** [comment]
I'll mark this issue as closed now. Please do reports/requests at the dedicated repository from now on: https://github.com/ravenclaw900/DietPi-Dashboard/issues
