### ISSUE TITLE
PI-SPC install issue: pi-spc/sds.sh lin 18 unexpected operator

### ISSUE THREAD

**Issue by renaudlarzilliere** [MichaIng/DietPi#4488]
#### Required Information
- DietPi version | 7.2.3 master
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
- Kernel version | `uname -a`
- SBC model | RPI3 B+
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated? Freshly
- Can this issue be replicated on a fresh installation of DietPi? It is, tried both latest 32 and 64 bits image

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. Install dietpi from latest image
2. install pi-spc, shaireport and raspotify
3. updates run and when reboot, then repeated error message:
4

#### Expected behaviour

- reboot normally

#### Actual behaviour

- repeated error message: /var/lib/dietpi/dietpi-software/installed/pi-spc/sds.sh : 18: [: 0: unexpected operator

#### Extra details

- ...

**Comment by Joulinar** [comment]
Hi,

pls can you post content of `sds.sh` file

`cat /var/lib/dietpi/dietpi-software/installed/pi-spc/sds.sh`

**Comment by renaudlarzilliere** [comment]
![9BC59401-EA04-4D3D-8C4F-4045194FA4D1](https://user-images.githubusercontent.com/85832267/121812009-8aa91780-cc66-11eb-81ff-7f4e06dc84df.jpeg)

**Comment by MichaIng** [comment]
Dammit, there is a syntax bug in the script. Please try to resolve with this command:
```
sed -i 's/==/=/' /var/lib/dietpi/dietpi-software/installed/pi-spc/sds.sh
```

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/96a78c445107efd328af71689d8b8b21fc8bc620
Changelog: https://github.com/MichaIng/DietPi/commit/33f572fed1b77f7cca3f842ddcd4f92fe0e2708f

**Comment by renaudlarzilliere** [comment]
> Dammit, there is a syntax bug in the script. Please try to resolve with this command:
> 
> ```
> sed -i 's/==/=/' /var/lib/dietpi/dietpi-software/installed/pi-spc/sds.sh
> ```
Worked ! Thanks
