### ISSUE TITLE
DietPi-Config | RPi 3 B+: Disabling WiFi breaks Bluetooth as well

### ISSUE THREAD

**Issue by BelgarionNL** [MichaIng/DietPi#4512]
Details:

    Bug report | N/A
    DietPi version | latest stable and beta 7.3
    Img creator | DietPi Core Team
    SBC device | RPi 3 Model B+ (armv7l) (index=3)
    Kernel version | 
    Linux DietPi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l 

GNU/Linux

Steps to reproduce:

    Install dietpi image enable bluetooth in dietpi-config and then nada.

Expected behaviour:

    Bluetooth should be working?

Actual behaviour:

    Bluetooth does not work

Extra details:

    Running the command systemctl start hciuart fails
    Tried to disable/enable Bluetooth from the dietpi-software menu, no change

Additional logs:
```
root@dietpi-woonkamer:~# journalctl -u hciuart
-- Logs begin at Fri 2021-06-25 09:57:19 CEST, end at Fri 2021-06-25 09:58:02 CEST. --
Jun 25 09:57:22 dietpi-woonkamer systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Jun 25 09:58:02 dietpi-woonkamer btuart[209]: Initialization timed out.
Jun 25 09:58:02 dietpi-woonkamer btuart[209]: bcm43xx_init
Jun 25 09:58:02 dietpi-woonkamer systemd[1]: hciuart.service: Control process ex
ited, code=exited, status=1/FAILURE
Jun 25 09:58:02 dietpi-woonkamer systemd[1]: hciuart.service: Failed with result
 'exit-code'.
Jun 25 09:58:02 dietpi-woonkamer systemd[1]: Failed to start Configure Bluetooth
 Modems connected by UART.
```

**Comment by BelgarionNL** [comment]
similar to this:

https://github.com/MichaIng/DietPi/issues/3018
https://github.com/MichaIng/DietPi/issues/4060

**Comment by BelgarionNL** [comment]
UPDATE: seems to work on the 7.3 beta branch

**Comment by MichaIng** [comment]
Many thanks for your report.

Bluetooth on Raspberry Pi can fail for various reasons, so you'll always find many of those reports on all distros 😉.

You had a very old DietPi version when doing the report and the image is a Stretch image (not a new one as stated in the header) with a very strange kernel signature:
```
Letsencrypt supports Free Noip.com Dynamic DNS #1159 SMP Sun Nov 4 17:50:20 GMT 2018
Distro | stretch (index=4)
```

Where did you get this image from, and is the first line above really the output of `uname -a`?

**Comment by BelgarionNL** [comment]
I got the latest version from your website. tried both the stable and beta 7.3

I copied the layout from another similar bug report so perhaps I forgot to change it :)

**Comment by Joulinar** [comment]
Can you share `uname -a` pls. So we know what you are running

**Comment by BelgarionNL** [comment]
sorry its now running raspbian os lite.

pi@rpi3-woonkamer:~ $ Linux rpi3-woonkamer 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l G                                                                         NU/Linux

Do you absolutely need it? I can flash another sd card if you want.

**Comment by BelgarionNL** [comment]
![image](https://user-images.githubusercontent.com/10578097/123468542-3270fe80-d5f2-11eb-85ea-2a311aa55b0f.png)

I think something is going wrong here because before the reboot I had 3 options :D

**Comment by MichaIng** [comment]
Ah, there it is: The serial console on ttyAMA0 needs to be disabled, as this is used for Bluetooth. If you need a serial console/device for other purpose, use ttyS0 (mini UART) for this. Toggle the device selector to [On], then reboot, and it becomes available to toggle the console on it.

**Comment by BelgarionNL** [comment]
![image](https://user-images.githubusercontent.com/10578097/123512452-d789e680-d687-11eb-9040-70e9c4cb924a.png)
![image](https://user-images.githubusercontent.com/10578097/123512463-e83a5c80-d687-11eb-8340-62c7874e585e.png)
![image](https://user-images.githubusercontent.com/10578097/123512478-f7210f00-d687-11eb-9f19-f2a245f9a5fb.png)

**Comment by BelgarionNL** [comment]
Just going to document all my steps so you guys can point to my mistake :)

![image](https://user-images.githubusercontent.com/10578097/123514078-22f4c280-d691-11eb-94ab-d190ad0578e5.png)
![image](https://user-images.githubusercontent.com/10578097/123514087-32740b80-d691-11eb-8ff0-156deb641e03.png)
![image](https://user-images.githubusercontent.com/10578097/123514098-4c155300-d691-11eb-8b1d-be140bce6726.png)
![image](https://user-images.githubusercontent.com/10578097/123514127-8e3e9480-d691-11eb-8fb6-ef42f5f3afa0.png)
![image](https://user-images.githubusercontent.com/10578097/123514135-9e567400-d691-11eb-8fc9-f56af0b31374.png)

Just checking here, not changing anything:
![image](https://user-images.githubusercontent.com/10578097/123514155-b62df800-d691-11eb-8811-65a2faaebc59.png)
![image](https://user-images.githubusercontent.com/10578097/123514177-de1d5b80-d691-11eb-9b69-a1a7e05b11c4.png)
![image](https://user-images.githubusercontent.com/10578097/123514199-f8efd000-d691-11eb-8d8b-348573a82586.png)
![image](https://user-images.githubusercontent.com/10578097/123514268-64d23880-d692-11eb-9bd5-bb75c4ffc4b4.png)

**Comment by BelgarionNL** [comment]
![image](https://user-images.githubusercontent.com/10578097/123516134-e3cb6f00-d69a-11eb-845d-021db25b3f6c.png)
![image](https://user-images.githubusercontent.com/10578097/123516162-065d8800-d69b-11eb-8f34-ce3ad32880fe.png)

**Comment by Joulinar** [comment]
Pla if possible don't do screen prints. Try to copy the output from SSH terminal

**Comment by BelgarionNL** [comment]
updated post with text. how do I spoiler tag it or something so its not so long?

**Comment by MichaIng** [comment]
Can you try the following:
```sh
sed -i '/dtoverlay=disable-wifi/d' /boot/config.txt
reboot
```
I remember a case where, if I'm not mistaken, the Bluetooth module needed to be enabled for WiFi to work, and I guess in these cases it's true as well the other way round. It's rare RPi 3 revisions where both seem to be on the same lane and always toggled together, instead of independently, as expected. I cannot find the issue currently, let's first see if this is the case for you. As it fails only after reboot, it seems to be one of the boot/firmware configs, done during firstrun setup, at least.

**Comment by BelgarionNL** [comment]
yep! thats it

its pure luck that both of these rpi3b+ have this then since I got one ecently and the other one is a couple years old.

so using the GUI simply enabling wifi will also work? or should I keep using this command for new versions?

**Comment by MichaIng** [comment]
Ah great that we found it.

> so using the GUI simply enabling wifi will also work?

Better keep using that command or remove the related line manually form `config.txt`, so the kernel modules and the network interface stays disabled, but only the hardware device part is enabled.

Could you check the revisions of those two RPis?
```sh
echo $G_HW_REVISION
```

**Comment by BelgarionNL** [comment]
will do thanks!

a020d3

and the other one has raspbian on it that does not give me any. Once I have moved my devices over to the now working dietpi then I will give you the other revision :)

**Comment by MichaIng** [comment]
On Raspbian, the following shows the revision:
```sh
mawk '/Revision/{print $3}' /proc/cpuinfo
```

**Comment by BelgarionNL** [comment]
well they are the same. good to know.

**Comment by MichaIng** [comment]
Oh you are right. Hmm, it is a little late before the release, but I would want to check this back with the RPi devs. Probably there is a possibility to fix this firmware-wise.

**Comment by MichaIng** [comment]
Found the two related threads in the Raspberry Pi forum, and indeed it's model 3B+:
- https://www.raspberrypi.org/forums/viewtopic.php?t=276582
- https://www.raspberrypi.org/forums/viewtopic.php?t=284221

And indeed it's when disabling WiFi, that Bluetooth is disabled as well while I couldn't find a way that it's true the other way round as well, at least.

**Comment by Joulinar** [comment]
@MichaIng 

this is how it looks on my system after reboot. WiFi disabled +  BT enabled

```
root@DietPi3:~# cat /boot/config.txt | grep dtoverlay
dtoverlay=dietpi-disable_vcsm
dtoverlay=disable-wifi
root@DietPi3:~# systemctl status hciuart.service
● hciuart.service - Configure Bluetooth Modems connected by UART
   Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-07-12 23:30:32 CEST; 2min 30s ago
  Process: 224 ExecStart=/usr/bin/btuart (code=exited, status=0/SUCCESS)
 Main PID: 416 (hciattach)
    Tasks: 1 (limit: 2181)
   CGroup: /system.slice/hciuart.service
           └─416 /usr/bin/hciattach /dev/serial1 bcm43xx 3000000 flow - b8:27:eb:7c:cb:e0

Jul 12 23:29:57 DietPi3 systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Jul 12 23:30:32 DietPi3 btuart[224]: bcm43xx_init
Jul 12 23:30:32 DietPi3 btuart[224]: Flash firmware /lib/firmware/brcm/BCM4345C0.hcd
Jul 12 23:30:32 DietPi3 btuart[224]: Set BDADDR UART: b8:27:eb:7c:cb:e0
Jul 12 23:30:32 DietPi3 btuart[224]: Set Controller UART speed to 3000000 bit/s
Jul 12 23:30:32 DietPi3 btuart[224]: Device setup complete
Jul 12 23:30:32 DietPi3 systemd[1]: Started Configure Bluetooth Modems connected by UART.
root@DietPi3:~#
```

**Comment by MichaIng** [comment]
Many thanks for testing, and strange that it works in your case. The revision is `a020d3`, right?
```sh
mawk '/Revision/{print $3}' /proc/cpuinfo
```

**Comment by Joulinar** [comment]
yep

```
root@DietPi3:~# mawk '/Revision/{print $3}' /proc/cpuinfo
a020d3
root@DietPi3:~#
```

**Comment by BelgarionNL** [comment]
gave this another fresh go on 1 of my 2 rpi3b+ and yea for me it fails every time :) 

weird yours is working. anyway its working with the workaround so thanks for getting this sorted 👍

**Comment by MichaIng** [comment]
Nasty, as I'm not sure then how to know whether the workaround is required or not (for an implementation in our scripts) 🤔. I'll keep the issue open and see whether I can find further info about this, if it's a specific charge of the RPi 3+ builds that are affected or so, and how to detect.

**Comment by MichaIng** [comment]
@BelgarionNL 
When you disable Bluetooth, but enable onboard WiFi, does the WiFi adapter/interface work? Short test:
```sh
sed -i '/dtoverlay=disable-wifi/d' /boot/config.txt
G_CONFIG_INJECT 'dtoverlay=' 'dtoverlay=disable-bt' /boot/config.txt
rm -f /etc/modprobe.d/dietpi-disable_wifi.conf
reboot
# after reboot
ip l
```

**Comment by MichaIng** [comment]
Okay, indeed there seem to have been a change on the RPi 3B+ models without a revision code increment. On RPi 3A+ it behaves the same. I'm checking back another detail, probably we can implement a probe on RPi 3B+ and then, when user requests to disable WiFi while Bluetooth is enabled or the other way round, we can add an additional continue/abort prompt, informing user that at least the `dtoverlay=disable-wifi` needs to be/stay absent for Bluetooth to function, which means at some level, WiFi is enabled. Not a real issue IMO, also since we blacklist the Broadcom WiFi kernel modules, but some like to assure that certain communication channel/hardware is disabled lowest possible level.

**Comment by MichaIng** [comment]
@BelgarionNL 
Could you try to install these two files into your `/boot` directory (overwriting the existing ones): https://drive.google.com/file/d/10gBNYX6UcFFwjZircjbfgOd7uKzBSnzA/view

To have those loaded, you need to at least have 32 MiB GPU memory applied, i.e. check via `dietpi-config` > `Display Options` > `GPU/RAM Memory Split` and raise it to 32 MiB, if 16 MiB are currently applied. Else the cutdown firmware is loaded, hence `start_cd.elf` and `fixup_cd.dat`. Then disable again WiFi, reboot and see if Bluetooth is still working:
```sh
G_CONFIG_INJECT 'dtoverlay=disable-wifi' 'dtoverlay=disable-wifi' /boot/config.txt
reboot
systemctl status hciuart
```

**Comment by MichaIng** [comment]
Now even easier to apply the fix without manual file download:
```sh
apt install rpi-update
rpi-update
G_CONFIG_INJECT 'dtoverlay=disable-wifi' 'dtoverlay=disable-wifi' /boot/config.txt
reboot
systemctl status hciuart
```

**Comment by MichaIng** [comment]
@BelgarionNL 
Could you test with recent stable kernel/firmware (`apt update && apt upgrade`)? It should be fixed now, i.e. you should be able to disable WiFi now without breaking Bluetooth.

**Comment by MichaIng** [comment]
I'll mark this as closed now, AFAIK it has been solved, though I have no RPi 3+ to test.
