### ISSUE TITLE
DietPi-Software | Matrix Synapse Server

### ISSUE THREAD

**Issue by nonnorm** [MichaIng/DietPi#4525]
#### Formal software information
- Software title | 
Synapse Server
- Short description | 
Homeserver for the Matrix protocol
- GitHub URL (if available) | 
https://github.com/matrix-org/synapse
- (Official) install documentation | 
https://github.com/matrix-org/synapse/blob/develop/INSTALL.md

#### Are there similar/alternative software titles available with DietPi-Software?

- No

#### What makes your requested software better than the above solutions, if available?

- N/A

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- Requires adding APT repository and some configuration

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

1. Add APT repository
2. Install APT package
3. Configure
4. Create new user

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.

- Yes

#### Vote for this software on FeatHub: 
https://feathub.com/MichaIng/DietPi/+131
https://feathub.com/MichaIng/DietPi/+162

**Comment by Joulinar** [comment]
@MichaIng @ravenclaw900 

could someone of you have a look to https://dietpi.com/phpbb/viewtopic.php?f=11&t=9249

There is a user having issues to set an upload file limit
