### ISSUE TITLE
VM Image for VMware aarch64

### ISSUE THREAD

**Issue by marshallmassengill** [MichaIng/DietPi#4534]
#### Formal device information
- Device name | aarch64 VM
- Official product URL | https://flings.vmware.com/esxi-arm-edition
- GitHub resource URL (if available) | N/A
- Image download URL | https://flings.vmware.com/esxi-arm-edition

#### Is the SBC officially supported by the Debian installer?
- Yes, Debian will work as a VM on ESXi-Arm

#### If not, are there install instructions for Debian available?
- There are a few blogs out there:
- https://www.virten.net/2020/10/vmware-tools-for-debian-10-arm64-on-esxi-arm/
- https://www.servethehome.com/getting-started-with-vmware-esxi-on-arm-with-a-raspberry-pi/

**Comment by marshallmassengill** [comment]
This might also be another reason to create this: https://blogs.vmware.com/teamfusion/2021/04/fusion-on-apple-silicon-progress-update.html

**Comment by MichaIng** [comment]
I mark this as closed in favour of: #3831
