### ISSUE TITLE
Read-Only RootFS To Increase MicroSD Longevity

### ISSUE THREAD

**Issue by springfielddatarecovery** [MichaIng/DietPi#4543]
#### Is your feature request related to a problem? Please describe:
MicroSD cards have a limited number of read/write cycles. While DietPi does an astounding job at minimizing the total number of reads and writes, it is not zero. Additionally, if power is lost during a write, the filesystem can become corrupted and the device will be "bricked" or silently lose data/functionality (or do so not so silently). This is especially important for people developing embedded devices which are difficult to get to physically or sold to end users who lack the expertise to re-flash their MicroSD card.
- ...

#### Describe the solution you'd like:
Option for a read-only rootfs in dietpi-manager. Once the user has configured their dietpi exactly as they like, they select the read-only rootfs option, and future boots mount / as read-only. 
- ...

#### Describe alternatives you've considered:
There is no real alternative to this functionality
- ...

#### Additional context
I will add a $40 bounty to any developer who implements this feature along with a $10 contribution to DietPi. Not much but maybe others will pitch in as well :). If DietPi themselves make the patch then they get the whole $50. The feature has to make it into an official DietPi release to qualify for this bounty, only one bounty will be awarded, if there are multiple bounty claims for some reason I will allocate at my discretion.
- ...

**Comment by Joulinar** [comment]
Hi,

this is basically a duplicate. I'm going to close this request in favour of https://github.com/MichaIng/DietPi/issues/3663

For RPi devices, I described a possible way on how to mount RootFS r/o in our forum https://dietpi.com/phpbb/viewtopic.php?p=24920#p24920
