### ISSUE TITLE
Installing G++ Multilib Problems

### ISSUE THREAD

**Issue by oDinZu** [MichaIng/DietPi#4557]
I am new to DietPi, but would I need to add to the sources list to install this package manually?

I am using the RaspPi 400 and v8arm. 
I am unsure why it is difficult to have this installed? 

I discovered related information on the web about it here: https://www.raspberrypi.org/forums/viewtopic.php?p=701320

**Comment by MichaIng** [comment]
Many thanks for your question. I migrated the issue to the correct repository, as this is not related to our documentation site.

Does the following not work?
```sh
apt install g++-multilib
```

**Comment by csharpee** [comment]
Yes, apt install g++-multilib doesn't work. 

I ended up cross-compiling a binary for Linux from amd64 to arm64 architecture through a virtual docker machine. 

Thanks for your reply.

**Comment by MichaIng** [comment]
> Yes, apt install g++-multilib doesn't work.

What is the error message?

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required. Would still be interesting what the error message of the package install was, as I cannot replicate any.
