### ISSUE TITLE
Changes to /boot/config.txt are reset on reboot.

### ISSUE THREAD

**Issue by ruscogit** [MichaIng/DietPi#456]
I can't seem to get this file to keep its changes after a reboot.

**Comment by Fourdee** [comment]
@ruscogit 

https://github.com/Fourdee/DietPi/blob/master/config.txt#L1-L2

DietPi moves common setting files to Ramdisk during boot, increasing performance and flash lifespan.
So when powered on, you need to edit `/DietPi/config.txt`

**Comment by ruscogit** [comment]
Thanks for the quick response!
