### ISSUE TITLE
apt update fails with "Redirection from https is forbidden"

### ISSUE THREAD

**Issue by numanair** [MichaIng/DietPi#4600]
#### Required Information
- DietPi version | G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=4
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

Was on v7.3.2

- Distro version | buster
- Kernel version | `Linux rock64 5.10.43-rockchip64 #21.05.4 SMP PREEMPT Wed Jun 16 08:02:12 UTC 2021 aarch64 GNU/Linux`
- SBC model | `ROCK64 (aarch64)`
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | apt
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

sudo apt update

#### Expected behaviour

sources update successfully

#### Actual behaviour

Fails with 

`Redirection from https to 'http://armbian.tnahosting.net/apt/dists/buster/Release' is forbidden [IP: 173.45.128.12 443]`

#### Extra details

My other SBC, a pi3B+ appears to use different sources. Hence it does not have this issue.

### Fix:
To fix it, I changed /etc/apt/sources.list.d/armbian.list from https to http. Hopefully this is the correct fix?

`deb http://apt.armbian.com/ buster main buster-utils buster-desktop`

**Comment by Joulinar** [comment]
Hi,

The RPi is using Raspberry OS and therefore a different sources list compare to your Rock64, which is using Arabian OS. This might be a temp problem at Armbian side. You could switch back to https in a day or 2 to check if this is still present. But at least nothing we can do from DietPi side as we do not manage Armbian package server.

**Comment by MichaIng** [comment]
It's the Armbian APT mirror service. Strange is that https://armbian.tnahosting.net/apt/ works, so that mirror supports HTTPS as well. Not sure why then the redirect goes to plain HTTP 🤔.

**Comment by P4tzr1ot** [comment]
I dont know if this can help in your investigation or if it is linked but i think i have similar issue on raspberry pi 4 not on Rock64![image](https://user-images.githubusercontent.com/79951094/127545160-599a7bff-bd24-4f12-a383-e692827fae19.jpeg)

Let me know if its another issue i will create it. 

Thanks

**Comment by Joulinar** [comment]
This is a complete different issue. As well, pls try to avoid screen prints and copy content from SSH terminal directly if possible.

**Comment by P4tzr1ot** [comment]
ok no problem but you have to tell me something,
i get this error on first boot how i can reach this screen via ssh ?

**Comment by Joulinar** [comment]
SSH server is active right from the beginning and should be reachable before first login from another computer using SSH.

**Comment by MichaIng** [comment]
@P4tzr1ot 
You have a time sync issue, i.e. the system clock is in the past so that the HTTPS certificates are not "yet" valid, from the systems point of view. Please try to run:
```sh
/boot/dietpi/func/run_ntpd 1
```
from console. Not sure if you are asking how to use SSH in general, i.e. is it clear how to use e.g. [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) from Windows?
You can also exit this error prompt (and the next one asking you whether to repeat or exit the first run setup) to reach the local console.

**Comment by MichaIng** [comment]
Found it on the Armbian forum: https://forum.armbian.com/topic/18711-update-in-buster-is-failing-with-redirection-from-https-to-httparmbiantnahostingnetaptdistsbusterrelease-is-forbidden/

I hope a redirect which preserves the initial scheme to allow HTTPS connections will be applied quickly.

**Comment by MichaIng** [comment]
Issue solved: https://github.com/armbian/dl-router/pull/14

**Comment by P4tzr1ot** [comment]
> @P4tzr1ot 
> 
> You have a time sync issue, i.e. the system clock is in the past so that the HTTPS certificates are not "yet" valid, from the systems point of view. Please try to run:
> 
> ```sh
> 
> /boot/dietpi/func/run_ntpd 1
> 
> ```
> 
> from console. Not sure if you are asking how to use SSH in general, i.e. is it clear how to use e.g. [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) from Windows?
> 
> You can also exit this error prompt (and the next one asking you whether to repeat or exit the first run setup) to reach the local console.

It was NTP parameter 🤦🏻‍♂️ into dietpi.txt it works now. Probably I have deleted it by error. thanks for the clue 👍

**Comment by swashy69** [comment]
Ok so I figured it out now.
This one is for the newbies
(Make sure you are root user)
Step 1:-cd /etc/apt/sources.list.d
Step-2:-ls -a     (this is going to show you the files present in the current directory)
Now note down the file name which has its extension as .list , for example:- there was a file named armbian.list in the directory, so I am going to use it.
Step 3:-sudo nano /etc/apt/sources.list.d/YOUR_FILE_NAME.list       (this is going to open up an editor)
Step 4:-rename the https to http
Step 5:- press ctrl+o then enter
Step 6:- press ctrl+x
Step 7:- reboot now
Step 8:- sudo apt update
Fixed.
:)

**Comment by Joulinar** [comment]
Did you actually facing an issue with Armbian repository? Because the particular issue should have been fixed by Armbian guy's end of last year already.

**Comment by MichaIng** [comment]
No it was never fixed, some strange sort of caching is preventing reliable request protocol detection. The Armbian repo cannot be used with HTTPS currently. However, we change it to HTTP via pre-patch, so with recent DietPi you shouldn't face this issue.

**Comment by jace** [comment]
I've been affected by this with a fresh install of Armbian 25.5.1:

```apt
Err:9 https://mirror.albony.in/armbian bookworm Release
  Redirection from https to 'http://mirror.nag.albony.in/armbian/dists/bookworm/Release' is forbidden [IP: 82.180.145.196 443]
Reading package lists... Done
E: The repository 'https://apt.armbian.com bookworm Release' no longer has a Release file.
```

It took a while to realise `mirror.albony.in` was itself a redirect from `apt.armbian.com`. Replacing `https` with `http` in the scheme fixed it.

**Comment by MichaIng** [comment]
The original issue was actually really fixed with a switch to a new mirror redirection software, which did not have this weird caching issue with the old one, we tried but failed to solve. But individual mirrors continued to do downgrades on their end by times.

One of the reasons we replaced the Armbian APT repo with our own. A dezentral distribution and mirror redirection is generally a good idea, but their partners are too unreliable. Our image builds needed to be retriggered multiple times, as 5-10% failed with some random error with an Armbian APT mirror doing a protocol downgrade or simply being offline.

For end users it is usually not such a big problem, may even remain unnoticed, if lists were successfully updated the `apt update` call before and after, also since Armbian keeps old package versions in repos for a long time. But we do error-handle these calls in our scripts, hence it constantly caused bug reports like this one as well.

**Comment by jace** [comment]
I can confirm the problem is gone _after_ `apt update`. I've changed all my sources back to `https://` and they work fine now.

**Comment by MichaIng** [comment]
It is random, depends on the particular mirror host your are redirected to. The original issue this thread was originally about, which enforced the faulty protocol downgrade at the mirror director itself, has been fixed.

In any case, not relevant for us anymore. If you face this issue with Armbian, a suitable place to report might be the the GitHub repo of the mirror director: https://github.com/armbian/armbian-router/issues
Or the forum, not sure: https://forum.armbian.com/
There is also a status page: https://v6monitor.com/list/view/011727251/

Looks like the particular mirror where you faced the issue `mirror.albony.in` changed its hostname to `mirror.nag.albony.in`, and the redirect is (still) falsely done to plain HTTP:
```console
root@micha:~# curl -I https://mirror.albony.in/armbian/dists/bookworm/Release
HTTP/2 302
alt-svc: h3=":443"; ma=2592000
date: Tue, 05 Aug 2025 12:35:24 GMT
location: http://mirror.hyd.albony.in/armbian/dists/bookworm/Release
server: Caddy
x-geo-distance: 7113503.818478
```
So you will likely run into the same issue again by times, until either the mirror host fixes the redirection, or Armbian updates its hostname. Which mirror is picked, depends, among other, on the `x-geo-distance` header.

**Comment by dejavu21** [comment]
Types: deb
URIs: https://apt.armbian.com
Suites: trixie
Components: main
Signed-By: /usr/share/keyrings/armbian.gpg
