### ISSUE TITLE
How to access DLNA devices in the home network with Wireguard

### ISSUE THREAD

**Issue by GvY85** [MichaIng/DietPi#4617]
This is probably very simple to fix but I am a bit of a networking/iptables n00b so I cant seemt to figure this one out.
Have been using 2 DietPi devices for years. 
One has Pi-hole + Unbound + Wireguard (PiVPN) server and number two has Samba + Wireguard client (to Mullvad) + Qbittorrent-nox + MiniDLNA.
This is all behind a Fritz!Box router with a open port to device One so that all my mobile devices have a Wireguard tunnel to the home network and use Pi-hole.  So far so good and this has been working for a few years.
However, when I try to access device Two that is running MiniDLNA via the Wireguard tunnel that does not seem to work.
So, I cannot watch anything via DLNA (with VLC) on device Two when connected via Wireguard to device One. Everything works fine while I am in the home Wifi network and disconnected from Wireguard.

My assumption is that the problem lies in the fact that my home network has a 192.168.178.0/24 network range and WG devices get a 10.0.0./24(?) range? 
So it seems WG clients can connect to the internet via device One but not to all the devices in the home network. Wierd thing is that I can access the qBittorrent webinterface running on device Two and the Admin page of the Fritz!Box but not MiniDLNA on device Two so I can access more devices than just the internet and device One
Is WG by default only allowing some ports or?

**Comment by Joulinar** [comment]
even if already closed, duplicate of https://github.com/MichaIng/DietPi/issues/4616
