### ISSUE TITLE
DietPi-Software | Cuberite: Re-apply official builds on ARMv6

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#4654]
As of: https://github.com/MichaIng/DietPi/issues/3664#issuecomment-901261614

Testing again on RPi Zero. Would be highly appreciated as we currently ship a very old build from before ARMv6 support was dropped.

**Comment by Joulinar** [comment]
just run installation on a RPi1 on 7.4 or is it needed to got with 7.5? Any special thinks to add in addition next to `dietpi-software` ?

**Comment by MichaIng** [comment]
This one: #4659
We replaced the official binary with an own (old) ARMv6-compatible one, but now the the official one should be again ARMv6-compatible.

**Comment by Joulinar** [comment]
let me know once ready for testing

**Comment by MichaIng** [comment]
It is.
