### ISSUE TITLE
remove "elevator=deadline" from /boot/cmdline.txt

### ISSUE THREAD

**Issue by PeterLacknase** [MichaIng/DietPi#4678]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
`G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=5
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
`
- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`
`bullseye`
- Kernel version | `uname -a`
`Linux dietpi 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux
`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
`RPi 3 Model B+ (armv7l)
`
- Power supply used | (EG: 5V 1A RAVpower)
`5V 2A`
- SDcard used | (EG: SanDisk ultra)
`SDXC SN64G`

#### Steps to reproduce
1. applies to any version of bullseye:
`sudo journalctl`

#### Expected behaviour
boot without any delay and without message

`Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.`

#### Actual behaviour
above message appears and bootup is delayed.

#### Extra details

cf.:

`https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971882`

**Comment by MichaIng** [comment]
Many thanks for your report.

It does not delay the boot at all but prints the warning only.

We do not ship it with out images anymore, but I also recognised that it is still shipped with Raspberry Pi OS images, which our older RPi images took over from there. I already opened a PR to fix it: https://github.com/RPi-Distro/pi-gen/pull/535
I didn't know about the same issue with the Debian RPi firmware package, seems like nobody recognised the related entry in the Linux 5.4 changelog 😄: https://kernelnewbies.org/Linux_5.4?highlight=%28elevator%29#Block_layer

But in the meantime we create images from scratch and also the PREP script itself writes a new `cmdline.txt`, to have consistency.

What we could additionally do is remove it on next DietPi updates from the `cmdline.txt` of existing images as well.
