### ISSUE TITLE
DietPi image based on jessie (still) available for sparkySBC?

### ISSUE THREAD

**Issue by seniorgod** [MichaIng/DietPi#4706]
Dear all,

because i have to compile old software with gcc 4 i'd like to know if there is a old image available of DietPi / Jessie for sparky SBC.

**Comment by Joulinar** [comment]
Hi,

these old images are not available anymore.

**Comment by MichaIng** [comment]
We only host the Bullseye and Buster images. Probably you're able to install or at least manually extract and use the gcc-4 binaries from the Debian Jessie packages: http://ftp.debian.org/debian/pool/main/g/gcc-4.9/

**Comment by seniorgod** [comment]
ok,

i asked because i thought there is an easy way to build kernel image for sparky. 
I thought about to include the the RealTime patch (no idea if it increase audio quality, on Raspi it do) 
That's why i asked for jessie and gcc4 because the downloaded Sparky/LINUX repo from git require it.

Meanwhile i found that there is a sparkysbc/sparky_sdk repo which seems to include a build setup to build the sparky Linux image via cross compiling on a ubuntu i386 computer.

My question is: 
How do you compile the sparky kernel?
With that ubuntu cross compile toolchain from sparky_sdk ? (the toolchain obviously include the correct gcc) 
Did you compile the kernel in a different way?
How do you configure the sparky kernel? Are Control groups and namespaces part of the kernel.
Is there any chance to include the RT patch?

**Comment by MichaIng** [comment]
I'm afraid we cannot answer these questions and you should ask them on the Sparky SBC repositories or by contacting Allo directly. If you find a good way to compile the Sparky SBC kernel on an x86 machine, I would be highly interested in this as well, as there are some issues with our old kernel build which I would try to solve with a fresh build. Our kernel seems to include patches from Volumio and it is finally not transparent anymore which patches/commits went into it and which not.

**Comment by MichaIng** [comment]
Marking this as closed. Feel free to reopen when required.
