### ISSUE TITLE
DietPi-Config | Overclocking for RPi Zero v1.3

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#471]
@Fourdee 

```
root@RPi-Zero:~# /DietPi/dietpi/misc/rpi_boardinfo

  - RPi Board Info -
 Revision         |     900093
 Released         |     Q2 2016
 Model            |     Zero
 Memory           |     512 MB
 Manufacturer     |     Sony

```

with default  `/boot/config.txt` from _RASPBIAN JESSIE LITE_

```
root@RPi-Zero:~# vcgencmd get_config int
arm_freq=1000
audio_pwm_mode=1
config_hdmi_boost=5
core_freq=400
disable_auto_turbo=1
disable_commandline_tags=2
enable_uart=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=300
hdmi_force_cec_address=65535
ignore_lcd=1
init_uart_clock=0x2dc6c0
over_voltage_avs=0x249f0
overscan_bottom=32
overscan_left=32
overscan_right=32
overscan_top=32
pause_burst_frames=1
program_serial_random=1
sdram_freq=450
temp_limit=85

```

![160813-0002](https://cloud.githubusercontent.com/assets/17237601/17644976/2b41a9ee-6198-11e6-9f85-fe07ea7fa68b.gif)

But in `dietpi-config` it will show:
![160813-0005](https://cloud.githubusercontent.com/assets/17237601/17644985/672a9e7a-6198-11e6-8996-972285444d06.gif)

`dietpi-config` works, so you can/will overclock or underclock RPi Zero, but I think, do this, it is not correct. Read on raspberrypi.org form the developer, no over-clock options are presented in raspi-config as the stock 1000MHz settings are at the upper end of what the majority of the hardware is capable of.

![160813-0003](https://cloud.githubusercontent.com/assets/17237601/17645028/877fc186-6199-11e6-8694-3ae319a3273e.gif)

Tested, with `raspi-config`, where is no overclocking option.

I think, undervolt and underclock will be okay,for people want to save power consume. It's no will damage your hardware.
But overclocking will not be a good idea, just as RPi3.

So better will do something like that:

![160813-0007](https://cloud.githubusercontent.com/assets/17237601/17645278/fdc5c9d8-61a0-11e6-86c4-c6c41dcf602e.gif)

**Comment by Fourdee** [comment]
@k-plan 

Great find :+1: 

Also found a few other issues while i was fixing that lol:
- RPi 2/3/Zero will now show correct sdram speed (450mhz default) in overclocking menu
- RPi 2 overclocking sdram speeds are now set to 450mhz (default for device)

**Comment by k-plan** [comment]
@Fourdee 

> Also found a few other issues while i was fixing that lol:

Yes! 😄 

Testing on RPi 3 v.128:

![160814-0001](https://cloud.githubusercontent.com/assets/17237601/17649200/c61036a2-622e-11e6-9c37-0b1abd36d601.gif)

and now with v.129:

![160814-0002](https://cloud.githubusercontent.com/assets/17237601/17649204/ecf4ba90-622e-11e6-9c16-61837c65f9a7.gif)

![160814-0003](https://cloud.githubusercontent.com/assets/17237601/17649208/f78ba324-622e-11e6-9806-cde05b715964.gif)

Looks good on RPi 3 and RPi Zero V1.3, very nice. Thanks.

But no RPi 2 or RPi Zero V1 for testing here.

**Comment by Fourdee** [comment]
@k-plan 

> Looks good on RPi 3 and RPi Zero V1.3, very nice. Thanks.
> But no RPi 2 or RPi Zero V1 for testing here.

Excellent :+1: 

RPi 2:
![image](https://cloud.githubusercontent.com/assets/7077026/17649325/7faf06b0-622a-11e6-9fa4-703095aaacbc.png)

RPi 1 256mb:
![image](https://cloud.githubusercontent.com/assets/7077026/17649389/5714681a-622c-11e6-8ec0-7b09513405fa.png)
