### ISSUE TITLE
DietPi-Software | qbittorrent login not working ≥ 4.2.0

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#4711]
Using qbittorrent version ≥ 4.2.0, variable to store password in config file has been changed.

Config file location: `/home/qbittorrent/.config/qBittorrent/qBittorrent.conf`

- version < 4.2.0, `WebUI\Password_ha1`
- version ≥ 4.2.0, `WebUI\Password_PBKDF2`

Means our installation procedure will set incorrect value and you are not able to login into WebUi.

https://github.com/MichaIng/DietPi/blob/140fa046bb55b2efe9bc09b8d5da716e8a0956d1/dietpi/dietpi-software#L11594

Workaround would be to manually remove `WebUI\Password_ha1` from config file and restart service.

QBit Wiki: https://github.com/qbittorrent/qBittorrent/wiki/Web-UI-password-locked-on-qBittorrent-NO-X-%28qbittorrent-nox%29

**Comment by MichaIng** [comment]
Good find. We can use the same method used for the global software password to generate the hash.

**Comment by K92Pi** [comment]
I have a question regarding to qbittorrent. How do I set it as a daemon, so it runs automatically after restart?

**Comment by Joulinar** [comment]
if you use `dietpi-software` to install qbittorrent, it's done automatically.

**Comment by K92Pi** [comment]
@Joulinar I've installed with it and the app never starts automatically.

**Comment by Joulinar** [comment]
as your issue is not related to the original post, let's continue in #4718

**Comment by MichaIng** [comment]
Should be solved with: https://github.com/MichaIng/DietPi/commit/bfc7ebb8debd14fe57d1a6f1a21f4859a7f1b58e
