### ISSUE TITLE
Nginx config error: /var/log/nginx/error.log (no such file or directory) after rebooting pi-hole in a vbox VM.

### ISSUE THREAD

**Issue by EggzyGallahad** [MichaIng/DietPi#4739]
I am not sure why this happens. Here is the problem. Provided is my solution.

#### Required Information
- DietPi version | G_DIETPI_VERSION_CORE=7, G_DIETPI_VERSION_SUB=5, G_DIETPI_VERSION_RC=2
- Distro version | bullseye
- Kernel version | `Linux DietPi 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`
- SBC model | VirtualMachine (x86_64)

#### Additional Information (if applicable)
- Software title | Nginx
- Was the software title installed freshly or updated/migrated? Freshly.
- Can this issue be replicated on a fresh installation of DietPi? I don't know.

#### Steps to reproduce

1. Install diet pi in virtualbox vm, per the download.
2. Install pihole with nginx
3. When all is done and system is up, everything is hunky dory and works fine.
4. After some time, needed to reboot host machine. I closed the dietpi vm, rebooted, restarted dietpi vm, pi hole is functional, but nginx httpd fails to start the service, and so no http GUI.

#### Expected behaviour

- nginx should start.

#### Actual behaviour

- nginx fails to start because  `/var/log/nginx/error.log (no such file or directory)`. 
- if you type `nginx -t` it passes syntax check but fails config file check since the specified path to the error_log does not actually exist on the FS, so nginx fails as the config is broken.

#### Extra details

Since  /var/log/nginx is not a valid directory that exists, one must create it. Since nginx.conf already expects error.log file, we must touch it.

- mkdir /var/log/nginx
- touch /var/log/nginx/error.log
- `$service nginx start; service nginx status` and it should be running now.

Even though nginx is running now, pi hole web gui is unavailable at port 80. 

nginx service is running/active

`/etc/init.d/nginx status` gives me out out of which one line stands out

`nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argument`

Otherwise it stops and starts the service just fine.

My pi hole ip is 10.1.10.64 and I can ping it, nginx is fine, I can ping google from diet pi so that's fine, but I can't get to http://10.1.10.64 as I get `ERR_CONNECTION_REFUSED`

`netstat -tupln` output for dietpi vm on my network:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3005/nginx: master  
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      411/pihole-FTL      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      477/sshd: /usr/sbin 
tcp        0      0 127.0.0.1:5335          0.0.0.0:*               LISTEN      395/unbound         
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      395/unbound         
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      411/pihole-FTL      
tcp6       0      0 :::80                   :::*                    LISTEN      3005/nginx: master  
tcp6       0      0 :::53                   :::*                    LISTEN      411/pihole-FTL      
tcp6       0      0 :::22                   :::*                    LISTEN      477/sshd: /usr/sbin 
tcp6       0      0 ::1:8953                :::*                    LISTEN      395/unbound         
tcp6       0      0 ::1:4711                :::*                    LISTEN      411/pihole-FTL      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           411/pihole-FTL      
udp        0      0 127.0.0.1:5335          0.0.0.0:*                           395/unbound         
udp6       0      0 :::53                   :::*                                411/pihole-FTL      
```

DietPi's pihole nginx in /etc/nginx/sites-dietpi/ looks fine too, it's just default.

Is there anything else I can check?

EDIT:... I used netcat to get into port 80, GET HTTP/1.1 and it said bad request. I refreshed browser and now it is magically back... http GUI is up.

**Comment by Joulinar** [comment]
Hi,

question: did you safely shutdown the VM or just cancelled the running instance? Because it's needed to always `poweroff` the system to ensure to write down files from `tmpfs`.

Usually PiHole should be reachable `http://your_IP/admin`

**Comment by hashborgir** [comment]
> Hi,
> 
> question: did you safely shutdown the VM or just cancelled the running instance? Because it's needed to always `poweroff` the system to ensure to write down files from `tmpfs`.
> 
> Usually PiHole should be reachable `http://your_IP/admin`

I did `shutdown` command.

**Comment by Joulinar** [comment]
does `/var/log/nginx` still exist after a reboot?

**Comment by hashborgir** [comment]
> does `/var/log/nginx` still exist after a reboot?

It does.

Thank you for said information. I believe perhaps not shutting down the vm cleanly might have caused an issue in the file system.

**Comment by Joulinar** [comment]
`/var/log` and `/run` are temporary file systems (tmpfs) and it's important to perform a clean `poweroff`. Especially after a software installation to ensure files are written down from tmpfs to disk.

Are you able to access PiHole now?

**Comment by MichaIng** [comment]
In case of `/run` nothing from there is stored back to disk, for the logs indeed a clean shutdown is required at least once after a new software install to have the possibly new log directory stored on disk for DietPi-RAMlog to recover at boot.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
