### ISSUE TITLE
Filebrowser login issue

### ISSUE THREAD

**Issue by barukh27** [MichaIng/DietPi#4756]
Hi there!

I've installed filebrowser after the las dietpi's update. Everything works fine but I can't log in. I've tried some credentials:

admin-admin
dietpi-dietpi
filebrowser-filebrowser
dietpi-(my frequent password)
dietpi-admin
dietpi-filebrowser

What should I try?

Thanks in advance.

**Comment by MichaIng** [comment]
It should be `dietpi` and the global software password you at at first boot or changed manually via dietpi-software, and it defaults to `dietpi` as well if you didn't change it.

You can change the password via CLI, but we need to find the exact command. As a start:
```sh
/opt/filebrowser/filebrowser -h users
```

**Comment by barukh27** [comment]
It worked now! 

Thanks!!!
