### ISSUE TITLE
Raspberry Pi 400: Missing Fn + F10 soft safe shutdown

### ISSUE THREAD

**Issue by pipapoquant** [MichaIng/DietPi#4769]
### Creating a bug report/issue
I miss the soft shutdown after key combination Fn + 10 for Pi 400. Only hard shutdown works pressing F10 longer than 10 sec.
#### Required Informationo
- DietPi version | `cat /boot/dietpi/.version`
core 7, sub 6, RC=2, master, MichaIng

DietPi_RPi-ARMv8-Bullseye, 
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
DietPi_RPi-ARMv8-Bullseye, 

- Kernel version | `uname -a`

5.10.60-v8+

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)

RPi 400 (aarch64)

- Power supply used | (EG: 5V 1A RAVpower)
original RPi 400 DC power

- SDcard used | (EG: SanDisk ultra)
SanDisk ultra

#### Steps to reproduce

1. ...Hold down Fn key and keep it pressed
2. ...Press F10 key and keep it pressed for 3 seconds

no reaction!

#### Expected behaviour

In Raspberry Pi OS the shortcut switches off the Raspberry Pi 400. It's a safe shutdown.
Would you please repair it / implement it for the Pi 400 in DietPi, too? 

#### Actual behaviour

nothing.

Pulling the plug on the Raspberry Pi 400 before it safely shuts down would be bad idea!
This can result in corrupted microSD card and file system. I don't use a monitor or second PC with SSH.
In my installation I have to switch off the Pi 400 just with the key combination Fn + 10.
It's really missing on this new device in DietPi on PI 400.

#### Extra details

[https://support.thepihut.com/hc/en-us/articles/360015199118-How-to-use-the-Raspberry-Pi-400-Power-Key](url)
"Power off by holding down the Fn+F10 keys for two seconds. This carefully shuts down your operating system, so you don’t cause any corruption to your memory card."

Fn-F10 is predefined as a power on/off control.
Power on, if you press Fn-F10 for more than 2 seconds the system does an orderly shutdown.
Shutdown, not sleep!
cnf. [https://www.zdnet.com/article/hands-on-with-the-raspberry-pi-400-pleased-and-impressed/](url)

**Comment by MichaIng** [comment]
Many thanks for your report.

This `Fn+F10` shutdown is internally done via GPIO ping, similar or the same as with the [GPIO shutdown device tree overlay](https://github.com/raspberrypi/firmware/blob/dcc1650/boot/overlays/README#L1035), which seems to be implicitly enabled on RPi 400. The letter requires `systemd-logind` (and hence `dbus`), so probably this helps in your case as well:
```sh
apt install dbus
systemctl unmask systemd-logind
systemctl start systemd-logind
```

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
