### ISSUE TITLE
Wi-Fi RPi 4 - No supported WI-FI hardware was found

### ISSUE THREAD

**Issue by FrostyMisa** [MichaIng/DietPi#4770]
#### Required Information
- DietPi version | G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
G_LIVE_PATCH_STATUS[1]='applied'
- Distro version | bullseye 0
- Kernel version | `Linux DietPi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux`
- SBC model | RPi 4 Model B (armv7l)
- Power supply used | official 
- SDcard used | portable SSD

#### Steps to reproduce

Fresh install, flash today 9.22.2021 ARMv7 32-bit image, make update to latest Dietpi and tried turn on Wi-Fi and connect. 
![image](https://user-images.githubusercontent.com/59890223/134379781-d58a6fcf-2871-43f2-aae8-2609e5f44184.png)

![image](https://user-images.githubusercontent.com/59890223/134379814-60e14510-e465-4bef-a5ac-a16330f4fe7e.png)

Here I paste everything from terminal. 
```
root@DietPi:~# dietpi-launcher
[ SUB1 ] DietPi-Set_hardware > wifimodules (onboard_enable)
[  OK  ] wifimodules onboard_enable | Completed
[ INFO ] DietPi-WiFiDB | Applied WiFi DB slot 0 with SSID ""
[ INFO ] DietPi-WiFiDB | Applied WiFi DB slot 1 with SSID ""
[ INFO ] DietPi-WiFiDB | Applied WiFi DB slot 2 with SSID ""
[ INFO ] DietPi-WiFiDB | Applied WiFi DB slot 3 with SSID ""
[ INFO ] DietPi-WiFiDB | Applied WiFi DB slot 4 with SSID ""
[ SUB1 ] DietPi-Services > stop 
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : smbd
[  OK  ] DietPi-Services | stop : nmbd
[ SUB1 ] DietPi-Set_hardware > wifimodules (enable)
[ INFO ] DietPi-Set_hardware | Please wait, enabling WiFi modules...
[ INFO ] DietPi-Set_hardware | Checking for required APT packages: iw wireless-tools crda wpasupplicant
[ INFO ] DietPi-Set_hardware | Flagged for install: iw
[ INFO ] DietPi-Set_hardware | Flagged for install: wireless-tools
[ INFO ] DietPi-Set_hardware | Flagged for install: crda
[ INFO ] DietPi-Set_hardware | Flagged for install: wpasupplicant
[ INFO ] DietPi-Set_hardware | APT update, please wait...
Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease
Hit:3 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
[  OK  ] DietPi-Set_hardware | APT update
[ INFO ] DietPi-Set_hardware | APT install for: iw wireless-tools crda wpasupplicant, please wait...
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package wireless-regdb.
(Reading database ... 24353 files and directories currently installed.)
Preparing to unpack .../0-wireless-regdb_2020.04.29-2_all.deb ...
Unpacking wireless-regdb (2020.04.29-2) ...
Selecting previously unselected package iw.
Preparing to unpack .../1-iw_5.9-3_armhf.deb ...
Unpacking iw (5.9-3) ...
Selecting previously unselected package crda.
Preparing to unpack .../2-crda_4.14+git20191112.9856751-1_armhf.deb ...
Unpacking crda (4.14+git20191112.9856751-1) ...
Selecting previously unselected package libiw30:armhf.
Preparing to unpack .../3-libiw30_30~pre9-13.1_armhf.deb ...
Unpacking libiw30:armhf (30~pre9-13.1) ...
Selecting previously unselected package libnl-route-3-200:armhf.
Preparing to unpack .../4-libnl-route-3-200_3.4.0-1+b1_armhf.deb ...
Unpacking libnl-route-3-200:armhf (3.4.0-1+b1) ...
Selecting previously unselected package libpcsclite1:armhf.
Preparing to unpack .../5-libpcsclite1_1.9.1-1_armhf.deb ...
Unpacking libpcsclite1:armhf (1.9.1-1) ...
Selecting previously unselected package wireless-tools.
Preparing to unpack .../6-wireless-tools_30~pre9-13.1_armhf.deb ...
Unpacking wireless-tools (30~pre9-13.1) ...
Selecting previously unselected package wpasupplicant.
Preparing to unpack .../7-wpasupplicant_2%3a2.9.0-21_armhf.deb ...
Unpacking wpasupplicant (2:2.9.0-21) ...
Setting up wireless-regdb (2020.04.29-2) ...
update-alternatives: using /lib/firmware/regulatory.db-debian to provide /lib/firmware/regulatory.db (regulatory.db) in auto mode
Setting up libnl-route-3-200:armhf (3.4.0-1+b1) ...
Setting up libpcsclite1:armhf (1.9.1-1) ...
Setting up iw (5.9-3) ...
Setting up crda (4.14+git20191112.9856751-1) ...
Setting up libiw30:armhf (30~pre9-13.1) ...
Setting up wireless-tools (30~pre9-13.1) ...
Setting up wpasupplicant (2:2.9.0-21) ...
Created symlink /etc/systemd/system/dbus-fi.w1.wpa_supplicant1.service → /lib/systemd/system/wpa_supplicant.service.
Created symlink /etc/systemd/system/multi-user.target.wants/wpa_supplicant.service → /lib/systemd/system/wpa_supplicant.service.
Failed to start wpa_supplicant.service: Unit dbus.socket not found.
Processing triggers for libc-bin (2.31-13+rpt2+rpi1) ...
[  OK  ] DietPi-Set_hardware | APT install for: iw wireless-tools crda wpasupplicant
[  OK  ] wifimodules enable | Completed
[  OK  ] DietPi-Config | Dropping connections, please wait...
[ INFO ] DietPi-Config | Restarting network, please wait...
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:33:03:50
Sending on   LPF/eth0/dc:a6:32:33:03:50
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 5
DHCPOFFER of 192.168.144.139 from 192.168.144.1
DHCPREQUEST for 192.168.144.139 on eth0 to 255.255.255.255 port 67
DHCPACK of 192.168.144.139 from 192.168.144.1
bound to 192.168.144.139 -- renewal in 33746 seconds.
wpa_supplicant: /sbin/wpa_supplicant daemon failed to start
run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1
ifup: failed to bring up wlan0
[ SUB1 ] DietPi-Services > start 
[  OK  ] DietPi-Services | start : nmbd
[  OK  ] DietPi-Services | start : smbd
[  OK  ] DietPi-Services | start : cron
[ INFO ] DietPi-Config | Reloading networking data, please wait...
[  OK  ] DietPi-Config | Network restarted
```

Expected behaviour

Search Wi-Fi networks and connect to them

#### Actual behaviour

Write: Not supported Wi-Fi hardware was found. 

#### Extra details

I tried like everyone after flash edit the Wi-Fi file and fill in my Wi-Fi and password. But after I can't connect to my raspberry. So after many other flashes of my SSD and flash cards, I tried connect LAN cable to raspberry and after I can see and connect to it. But if I tried manually connect to Wi-Fi, I get above error.
Yesterday I flash Raspberry zero w, set Wi-Fi and password after flash, inserted card inside and everything works. So maybe problem with bullseye and Wi-Fi drivers for RPi4?

**Comment by MichaIng** [comment]
Many thanks for your report. Did you already reboot once after enabling WiFi (especially the onboard WiFi switch)?

**Comment by FrostyMisa** [comment]
Ok, thank you for quick response. I don't make restart (before I never need it), so I do it and now it's available, but I cannot find my 5G connection. Even I write it manually.  Only 2,4G. I restart router as well, nothing change. One hour before it's running Dietpi one year without problem with 5G Wi-Fi...

**Comment by MichaIng** [comment]
Since WiFi is enabled/disabled via device tree overlay, a restart is always required and dietpi-config should have informed you about that. You don't require it if you configure WiFi via `dietpi.txt` and `dietpi-wifi.txt` before first boot or at the first boot session, because the image ships with WiFi enabled: The device tree overlay to disable it is added during first run setup, if WiFi has not been enabled in `dietpi.txt`. This is why it worked on the RPi Zero W, while you obviously rebooted the RPi4 once before you tried to enable WiFi.

The 5 GHz WiFi is a known issue with the current Broadcom driver it seems, at least in some countries (WiFi country codes) like China:
- https://github.com/raspberrypi/firmware/issues/1359
- https://github.com/raspberrypi/linux/issues/4530
- https://github.com/raspberrypi/firmware/issues/1246

Not sure why it worked before in your case, I guess you didn't use a different WiFi country code, did you? Probably it's something with the combination with newer kernel and the firmware, else a downgrade of the Broadcom WiFi firmware could at least be tried: https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/
But probably going forward and help testing the new firmware makes more sense:
- https://www.raspberrypi.org/forums/viewtopic.php?p=1914620#p1914620

**Comment by FrostyMisa** [comment]
Thanks for explain and yes, it's like what you say about Broadcom driver, because before with Buster default setup works. Now even I change region, I cannot find my 5Ghz. With 2,4 it works ok. 
So thank you for your time to help me🙃

**Comment by FrostyMisa** [comment]
I want to tell you, after today update and upgrade I saw some Wi-Fi updates, so I tried scan networks again and tada, I found my 5G network! So problem is solved😉

**Comment by MichaIng** [comment]
Okay great. Probably the kernel/firmware update from October 6 solved it 👍.
