### ISSUE TITLE
DietPi-Software | Revisit and test Letsencrypt (Certbot) with Lighttpd

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#479]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=603&p=2625#p2624

Using aar0nism's guide posted above.

Currently we only allow installation on apache2.

**Comment by montreuilg** [comment]
My goals are to set up the dietpi3s as RFM95 lora/ethernet gateways using lighttpd and SQLite, so I'm ready to help if can. :-)

**Comment by Fourdee** [comment]
@montreuilg 

> so I'm ready to help if can. :-)

Excellent :+1:
If you would be willing to test a LLSP installation using aar0nism's guide: http://dietpi.com/phpbb/viewtopic.php?f=9&t=603&p=2625#p2624, then report results, this will help speed things up.

Note to self:
`--cert-only` and modify Apache2/Nginx/Lighttpd configurations in DietPi, rather than the certbot installer?

**Comment by Fourdee** [comment]
Lighttpd code is done, aar0nism's guide was spot on. Just tested with 2 certs. Had to buy a 99p domain lol.

@montreuilg
I'll send the commit and let users know when its ready for testing.

![image](https://cloud.githubusercontent.com/assets/7077026/18441028/440e6250-7903-11e6-99fd-f45319692791.png)

![image](https://cloud.githubusercontent.com/assets/7077026/18441056/5f1e9010-7903-11e6-8aeb-cc6bb32b4b55.png)

**Comment by Fourdee** [comment]
@montreuilg 

Good to go. 

#### If you (and/or anyone else) could test Lighttpd and Cerbot using the testing branch, i'd be grateful:
- Setup a new installation of DietPi for testing branch: https://github.com/Fourdee/DietPi/blob/master/TESTING-BRANCH.md
- `dietpi-software` select LLSP for installation
- `dietpi-software` select Certbot for installation
- Start the installation
- After reboot, run `dietpi-letsencrypt`, enter your details and create the cert.
- Check your website works with https:// link

#### EDIT:

Tested once more on a fresh install my end. Working fine. Still would like confirmation from other testers.

**Comment by Fourdee** [comment]
Successful in my testing. Marking this as closed.

Please reopen if required. 

NB: No Nginx support yet, if we get requests for this, i'll look into it.

**Comment by ghost** [comment]
Thanks but, Oups, i am not on the same beat as you guys are it seems! I was going to check that today, i had a few hours of playtime... 🔢 :-)

I'll reinstall and keep on trying to make that small tft working then :-(

 One thing I'll take time to look at and i think you should too for developpers: [RethinkDB](https://www.rethinkdb.com/docs/quickstart/) It would be great to have it as part of an IOT offer lets say ;-)

**Comment by k-plan** [comment]
@Fourdee 

> NB: No Nginx support yet, if we get requests for this, i'll look into it.

New request:
http://dietpi.com/phpbb/viewtopic.php?f=9&t=1045

**Comment by LexiconCode** [comment]
Excellent, thank you @Fourdee @k-plan

**Comment by LexiconCode** [comment]
Alternate Certbot clients that might more easily integrate in to dietpi and all three web services.
https://github.com/acmephp/acmephp
https://github.com/kuba/simp_le

**Comment by sootstone** [comment]
Certbot does now provide a plugin for nginx since last October [https://certbot.eff.org/docs/using.html#nginx](https://certbot.eff.org/docs/using.html#nginx)

It's still technically in alpha, but may be something worth considering?

**I have not tested this!** Might give it a go though.

**Comment by sootstone** [comment]
Worked fine for me with standard server block:

```
server {
      listen 80;
      listen [::]:;
      server_name domain.com;
}
```

Basically does the same as the --apache plugin.
