### ISSUE TITLE
Error installing box64 after using software sections

### ISSUE THREAD

**Issue by RPTST** [MichaIng/DietPi#4792]
#### Details:
- Date           | Fri Oct  1 09:56:29 EDT 2021
- Bug report     | 062c0eca-085c-4b46-bf2d-2eea87c4f90b
- DietPi version | v7.6.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | From scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux dietpi 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `systemctl restart systemd-binfmt`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Job for systemd-binfmt.service failed because the control process exited with error code.
See "systemctl status systemd-binfmt.service" and "journalctl -xe" for details.
```

_Originally posted by @RPTST in https://github.com/MichaIng/DietPi/issues/3957#issuecomment-932262244_

**Comment by Joulinar** [comment]
Pls provide the information requested. https://github.com/MichaIng/DietPi/issues/3957#issuecomment-932271070

Did you tried to reboot your system?

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
