### ISSUE TITLE
DietPi-Backup | error message during restore

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#4800]
@MichaIng 
There is one error message at the end of a restore using `dietpi-backup`

```
/boot/dietpi/dietpi-backup: line 364: hash: -d: option requires an argument
```

I guess it would need to be `-r `option instead of `-d` as `-d` require to specify a command.

https://www.computerhope.com/unix/bash/hash.htm

**Comment by MichaIng** [comment]
Great find. Even true on Stretch.

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/f9f98ee869b157fc4ea476ba81dba3a41bbbe4ed
Changelog: https://github.com/MichaIng/DietPi/commit/3e8437f654d2a7463c2a7c898b19838674de6226
