### ISSUE TITLE
no installation candidate for »php7.4-apcu« and »php7.4-redis« 

### ISSUE THREAD

**Issue by nixisklar** [MichaIng/DietPi#4811]
#### Details:
- Date           | Thu Oct  7 18:49:05 CEST 2021
- Bug report     | c98cf88f-2627-4b1d-9a80-bfbb41f3f22b
- DietPi version | v7.6.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 3 Model B (armv7l) (ID=3)
- Kernel version | `Linux DietPi 5.10.63-v7+ #1457 SMP Tue Sep 28 11:25:31 BST 2021 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `apt-get -qq --allow-change-held-packages install php7.4-fpm php7.4-apcu php7.4-curl php7.4-gd php7.4-mbstring php7.4-xml php7.4-zip php7.4-mysql php7.4-redis`
- Exit code      | 100
- Software title | DietPi-Software

#### Steps to reproduce:

1. Updated from Buster to Bullseye according to 
    "https://dietpi.com/blog/?p=811#2.1-fresh-install".
2. Step 2.2.5 (dietpi-software reinstall 38 40 47 48 56 83 84 85 88 89 93 114 143) produced the above error message and the abort of the installation)

#### Expected behaviour:
- completion of update.
- 
#### Actual behaviour:

```
- terminatio of process with error message 100
- E: Package 'php7.4-apcu' has no installation candidate
   E: Package 'php7.4-redis' has no installation candidate
```

#### Extra details:
![image](https://user-images.githubusercontent.com/39263341/136433801-5ef57d31-1067-401a-9953-38496cb22c6a.png)
Only error during the update process: 
![image](https://user-images.githubusercontent.com/39263341/136434061-60cc7f36-e93e-4467-a38c-9186f43668c4.png)

#### Additional logs:

```
E: Package 'php7.4-apcu' has no installation candidate
E: Package 'php7.4-redis' has no installation candidate
```

#### Required Information
- SDcard used | SanDisk ultra

#### Extra details
![image](https://user-images.githubusercontent.com/39263341/136433801-5ef57d31-1067-401a-9953-38496cb22c6a.png)

**Comment by Joulinar** [comment]
Hi,

did you upgrade from Stretch to Buster before? Pls could you share 

```
dpkg -l php*
```

**Comment by nixisklar** [comment]
> Hi,
> 
> did you upgrade from Stretch to Buster before? Pls could you share
> 
> ```
> dpkg -l php*
> ```

I upgraded from Stretch to Buster (https://dietpi.com/docs/usage/#how-to-upgrade-to-buster), which worked nicely and I checked and Buster worked as well as did nextcloud.
I then upgraded from Buster to Bullseye, when the referenced error occurred.

**Comment by Joulinar** [comment]
pls share `dpkg -l php*` as requested

**Comment by nixisklar** [comment]
dpkg -l php*
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name               Version                                           Architektur  Beschreibung
+++-==================-=================================================-============-========================================================================
un  php-amqp           <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-apcu           5.1.20+4.0.11-1+0~20210304.24+debian9~1.gbp1c3d4d armhf        APC User Cache for PHP
un  php-apcu-bc        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-ast            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-calendar       <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-cli            <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-common         2:84+0~20210621.36+debian9~1.gbp28513e            all          Common files for PHP packages
un  php-crypt-gpg      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-ctype          <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-curl           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-dom            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-exif           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-ffi            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-fileinfo       <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-fpm            2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
un  php-ftp            <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-gd             2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          GD module for PHP [default]
un  php-geoip          <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-gmagick        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-iconv          <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-igbinary       3.2.6+2.0.8-1+0~20210913.27+debian9~1.gbp64b0ea   armhf        igbinary PHP serializer
un  php-imagick        <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-intl           2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          Internationalisation module for PHP [default]
ii  php-mbstring       2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          MBSTRING module for PHP [default]
ii  php-mcrypt         3:1.0.4-5+0~20210223.3+debian9~1.gbp68347e        armhf        PHP bindings for the libmcrypt library
un  php-memcache       <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-memcached      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-mongodb        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-msgpack        <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-mysql          2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          MySQL module for PHP [default]
un  php-mysqli         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-mysqlnd        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-opcache        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-pdo            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-pdo-mysql      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-pear           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-phar           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-posix          <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-radius         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-readline       <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-redis          5.3.4+4.3.0-1+0~20210329.35+debian9~1.gbpdc7ead   armhf        PHP extension for interfacing with Redis
un  php-rrd            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-shmop          <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-simplexml      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-smbclient      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-sockets        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-ssh2           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-sysvmsg        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-sysvsem        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-sysvshm        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-tokenizer      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-uploadprogress <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-uuid           <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-xcache         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-xdebug         <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-xml            2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
--More—
ii  php-xml            2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
un  php-xmlreader      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-xmlwriter      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-xsl            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php-yac            <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php-zip            2:8.0+84+0~20210621.36+debian9~1.gbp28513e        all          Zip module for PHP [default]
un  php-zmq            <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php5.6-common      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php5.6-json        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php7.0-common      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php7.0-curl        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php7.2-sodium      <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-apcu        5.1.20+4.0.11-1+0~20210304.24+debian9~1.gbp1c3d4d armhf        APC User Cache for PHP
un  php8.0-calendar    <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-cli         8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        command-line interpreter for the PHP scripting language
ii  php8.0-common      8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        documentation, examples and common module for PHP
un  php8.0-ctype       <keine>                                           <keine>      (keine Beschreibung vorhanden)
rc  php8.0-curl        8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        CURL module for PHP
un  php8.0-dom         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-exif        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-ffi         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-fileinfo    <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-fpm         8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        server-side, HTML-embedded scripting language (FPM-CGI binary)
un  php8.0-ftp         <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-gd          8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        GD module for PHP
un  php8.0-gettext     <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-iconv       <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-igbinary    3.2.6+2.0.8-1+0~20210913.27+debian9~1.gbp64b0ea   armhf        igbinary PHP serializer
ii  php8.0-intl        8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        Internationalisation module for PHP
un  php8.0-json        <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-mbstring    8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        MBSTRING module for PHP
ii  php8.0-mcrypt      3:1.0.4-5+0~20210223.3+debian9~1.gbp68347e        armhf        PHP bindings for the libmcrypt library
ii  php8.0-mysql       8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        MySQL module for PHP
un  php8.0-mysqli      <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-mysqlnd     <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-opcache     8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        Zend OpCache module for PHP
un  php8.0-pdo         <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-pdo-mysql   <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-phar        <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-posix       <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-readline    8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        readline module for PHP
ii  php8.0-redis       5.3.4+4.3.0-1+0~20210329.35+debian9~1.gbpdc7ead   armhf        PHP extension for interfacing with Redis
un  php8.0-shmop       <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-simplexml   <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-sockets     <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-sysvmsg     <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-sysvsem     <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-sysvshm     <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-tokenizer   <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-xml         8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        DOM, SimpleXML, XML, and XSL module for PHP
un  php8.0-xmlreader   <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-xmlwriter   <keine>                                           <keine>      (keine Beschreibung vorhanden)
un  php8.0-xsl         <keine>                                           <keine>      (keine Beschreibung vorhanden)
ii  php8.0-zip         8.0.10-1+0~20210826.23+debian9~1.gbp9ab3fd        armhf        Zip module for PHP
un  phpapi-20200930    <keine>                                           <keine>      (keine Beschreibung vorhanden)
![dpkg -l php_1](https://user-images.githubusercontent.com/39263341/136450961-2532ac04-4f0f-49cb-9e72-4ad7db895351.JPG)
![dpkg -l php_2](https://user-images.githubusercontent.com/39263341/136451005-5a119a9c-f7c0-4ad7-b584-09f3ab2e5787.JPG)

**Comment by Joulinar** [comment]
pls stop trying to run any reinstall. This doesn't make any sense until we fixed your PHP installation as you still have old Debian 9 PHP packages installed.

**Comment by nixisklar** [comment]
I received the output: 
re-installatio of php-common not possible:

:~# apt install --reinstall --allow-downgrades php-common
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Erneute Installation von php-common ist nicht möglich,
es kann nicht heruntergeladen werden.
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  fontconfig-config fonts-dejavu-core libdeflate0 libffi6 libfontconfig1 libfreetype6 libgd3 libicu65 libjbig0 libjpeg62-turbo libmagic-mgc libmagic1 libmcrypt4 libncurses5 libonig4 libsodium23 libtiff5 libtinfo5 libwebp6 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 libxslt1.1 libzip4 ucf
Verwenden Sie »apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
root@DietPi:~# apt install php7.4-apcu php7.4-redis
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Hinweis: »php-apcu« wird an Stelle von »php7.4-apcu« gewählt.
Hinweis: »php-redis« wird an Stelle von »php7.4-redis« gewählt.
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  fontconfig-config fonts-dejavu-core libdeflate0 libffi6 libfontconfig1 libfreetype6 libgd3 libjbig0 libjpeg62-turbo libmcrypt4 libncurses5 libonig4 libtiff5 libtinfo5 libwebp6 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxpm4
  libxslt1.1 libzip4
Verwenden Sie »apt autoremove«, um sie zu entfernen.
Die folgenden zusätzlichen Pakete werden installiert:
  php-igbinary php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-phpdbg php7.4-readline
Vorgeschlagene Pakete:
  php-gd php-pear
Empfohlene Pakete:
  php-apcu-bc
Die folgenden NEUEN Pakete werden installiert:
  php-apcu php-igbinary php-redis php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-phpdbg php7.4-readline
0 aktualisiert, 9 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Es müssen 3.337 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 15,6 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]

**Comment by Joulinar** [comment]
but this is a different issue than. If possibly try to connect a screen to see what the output is.

**Comment by nixisklar** [comment]
![image](https://user-images.githubusercontent.com/39263341/136669708-d86f5d31-5b5a-4200-a86a-596433014653.png)

**Comment by Joulinar** [comment]
looks like WiFi driver not loaded on boot.

@MichaIng could you have a look pls.

**Comment by MichaIng** [comment]
Ah, I missed the fact that you dist-upgraded. Please try this one:
```sh
grep 'net.ifnames=0' /boot/cmdline.txt
# if the above does not output anything, run the below:
sed -i '/root=/s/$/ net.ifnames=0/' /boot/cmdline.txt
reboot
```
Basically the network interface names have changed to be "predictable" with the upgrade to Bullseye, when done on older images where the above kernel config was not added by default yet. You should see different names than `wlan0` and `eth0` here:
```sh
ip l
```
Run the above again after applying the above kernel configuration and this should be reverted to the classic names.

**Comment by nixisklar** [comment]
grep 'net.ifnames=0 /boot/cmdline.txt
fives out the following result: 
/boot/cmdline.txt: Zeile 1: dwc_otg.lpm_enable=0: Kommando nicht gefunden. 
#"Kommando nicht gefunden" means "command not found" in German.

after reboot, ip l  would bring the following: 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state INKNOWN mode DEFAULT group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enxb827ebb8c37f: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
      link/ether b8:27:eb:b8:c3:7f brd ff:ff:ff:ff:ff:ff

There is still no connection .

**Comment by Joulinar** [comment]
did you run following command?

```
sed -i '/root=/s/$/ net.ifnames=0/' /boot/cmdline.txt
```

Issue is with the interface names as indicated by @MichaIng . It should be `wlan0` or `eth0` but you have `enxb827ebb8c37f `atm

**Comment by Joulinar** [comment]
OK I'm going to close this issue for now, feel free to reopen if needed.
