### ISSUE TITLE
After set static ip unable to install any software

### ISSUE THREAD

**Issue by rajesh-loganathan** [MichaIng/DietPi#4814]
#### Details:
- Date           | Sat Oct  9 15:03:03 BST 2021
- DietPi version | v7.6.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 2 Model B (armv7l) (ID=2)
- Kernel version | `Linux DietPi 5.10.63-v7+ #1457 SMP Tue Sep 28 11:25:31 BST 2021 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `ping -c 1 -W 10 9.9.9.9`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.
From 192.168.1.7 icmp_seq=1 Destination Host Unreachable

--- 9.9.9.9 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

**Comment by Joulinar** [comment]
That looks like a local network problem. Pls ensure internet connectivity. Are you able to ping anything else on the internet like Google or Cloudflare DNS?

**Comment by Joulinar** [comment]
What about `apt update`? And can you ping `1.1.1.1` or `8.8.8.8` ?

**Comment by Joulinar** [comment]
Does static IP fits to your network? Are you able to ping your gateway/router? Could you switch back to DHCP and get an IP assign. Once done switch to Static and use the option to assign current DHCP IP as static

**Comment by Joulinar** [comment]
Independent on DNS, is ping working?

**Comment by rajesh-loganathan** [comment]
Ping to ip not working.

Reinstall dietpi resolves internet issue, after set static ip again this issue raising.

**Comment by Joulinar** [comment]
You are using same IP, netmask, gateway an static as on DHCP?

**Comment by rajesh-loganathan** [comment]
Default DNS settings from router blocks.

@Joulinar  Thanks a lot for guiding to cross check the issues

**Comment by Joulinar** [comment]
but usually DNS settings should not have any impact in normal ping via IP address as there is no DNS used.
