### ISSUE TITLE
DietPi | Create image for NanoPi M2

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#482]
Many thanks to @k-plan for sending the board (and some Haribo :laughing: ) :+1:

**Comment by Fourdee** [comment]
No ARMbian support for this one (yet), so i'll try the official Debian images.

**Comment by Fourdee** [comment]
Image is done and available on http://dietpi.com/download

> http://dietpi.com/phpbb/viewtopic.php?f=8&t=620
> DietPi for NanoPi M2 is based on the official Friendly ARM image, which, has been completely stripped and optimized for DietPi.

Need to try and fix:
- CPU temp readouts

Cant be right:

```
root@DietPi:~# find /sys -type f -name temp*
/sys/devices/platform/nxp-adc-tmp.0/temp_max
/sys/devices/platform/nxp-adc-tmp.0/temp_label
/sys/devices/platform/nxp-adc-tmp.0/temp_value
root@DietPi:~# find /sys -type f -name thermal*
root@DietPi:~# cat /sys/devices/platform/nxp-adc-tmp.0/temp_value
 30:4095
```

Feels like 65'c+ on touch. 

Doesn't look like we will be able to measure CPU temp for this device. `/sys/devices/platform/nxp-adc-tmp.0/temp_*` always return same values. Cant find another other `/sys/` locations with `temp` or `thermal` in the name.

**Comment by Fourdee** [comment]
Marking this as done. Unfortunately, no CPU temp readouts available at this time.

**Comment by k-plan** [comment]
@Fourdee 

yes, I didn't find any CPU Temp. value. Perhaps something in the prebuild debian image/kernel is missing.

And the ext4 boot partition is as well annoying.

> Feels like 65'c+ on touch.

Yes, correct. My [Pyrometer](https://en.wikipedia.org/wiki/Pyrometer) shows up as well something like that. Better to put on a heatsink for Samsung Cortex-A9 S5P4418 CPU.

But anyway, nice job Fourdee. 👍

**Comment by Fourdee** [comment]
@k-plan 

> And the ext4 boot partition is as well annoying.

Yep, I know, same here. 
If i get some time, i'll look at compiling from scratch using: http://wiki.friendlyarm.com/wiki/index.php/NanoPi_M2#Make_Your_Own_OS_Image and hopefully set vfat and fix cpu temp readout.

> My Pyrometer shows up as well something like that. Better to put on a heatsink for Samsung Cortex-A9 S5P4418 CPU.

I'll add a Pyrometer to my wish list lol :+1: I've got a spare RPi heatsink, tiny, but should be better than nothing :)
