### ISSUE TITLE
Dietpi-software error in vmware while installing software.

### ISSUE THREAD

**Issue by alpgul** [MichaIng/DietPi#4824]
#### Required Information
- DietPi version |
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2

- Distro version | bullseye
- Kernel version | Linux DietPi 5.10.0-9-amd64 /1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
- SBC model | [Virtual Machine (x86_64)](https://dietpi.com/downloads/images/DietPi_VMware-x86_64-Bullseye.7z)
- Power supply used | (EG: 5V 1A RAVpower)
- SDcard used | (EG: SanDisk ultra)

#### Additional Information (if applicable)

- Bug report ID | c576ebed-c68d-46e4-8b83-0c2af010c4d2

#### Steps to reproduce

I wanted to test dietpi-software on vmware, for a clean install of dietpi. but when I want to install software( ProFTPD,kodi and jellyfin) with dietpi-software I got an error.
#### Expected behaviour

- dietpi-software work

#### Actual behaviour

- E: Sub-process /usr/bin/dpkg returned an error code (1)

#### Extra details

-

**Comment by Joulinar** [comment]
Issue seems to be ProFTP service not starting. This is blocking `apt` installation now. Can you share

`journalctl -u proftpd.service`
