### ISSUE TITLE
Unable to detemine if installation is DietPi

### ISSUE THREAD

**Issue by APMustard** [MichaIng/DietPi#4828]
#### Required Information
```
root@DietPi:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@DietPi:~# cat /usr/lib/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
root@DietPi:~# cat /boot/dietpi/.version
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
G_LIVE_PATCH_STATUS[1]='applied'
G_LIVE_PATCH_STATUS[2]='applied'
G_LIVE_PATCH_STATUS[3]='applied'
G_LIVE_PATCH_STATUS[4]='not applicable'
root@DietPi:~# uname -a
Linux DietPi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
root@DietPi:~# echo $G_HW_MODEL_NAME
RPi 4 Model B (armv7l)
root@DietPi:~#
```

- Power supply used |  5V 1A 
- SDcard used | ( SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (Nextcloud)
- the software title installed freshly 
- Can this issue be replicated on a fresh installation of DietPi?  Yes

#### Steps to reproduce

1. cat /etc/os-release

#### Expected behaviour

- It would be nice to have perhaps a VARIANT keyword identifying the OS is a DietPi variant

#### Actual behaviour

- The DietPi variant identifies as just a normal Rasbian Linux

**Comment by MichaIng** [comment]
Marking as closed: As said, I think an own `/etc/os-release` does not only cause additional maintenance efforts but may trigger wrong assumptions that on DietPi one would need to do anything differently compared to any other Debian based distro. DietPi uses the official Debian repository, so `/etc/os-release` is precisely correct about what package manager can be used and what you get when using it. Nothing else can or should be derived from `/etc/os-release`.

However, feel free to reopen when required.

**Comment by ravenclaw900** [comment]
Also, if you need to check if the OS is DietPi and get data about it, you can check the `/boot/dietpi/.version` file.

**Comment by MichaIng** [comment]
Indeed. Although when writing a program or script where such questions are relevant, aside of whether it's Debian or another base distribution, I'd go with a more generic approach:
- Assure that required packages are installed, which may be missing on DietPi, but also on any other system.
- Check which init system is used, systemd, SysV or such, when relevant.
- Check with network stack is used, ifupdown, dhcpcd, systemd-networkd, NetworkManager, etc, when relevant.
