### ISSUE TITLE
error update DietPi from v6.22.3 to v6.35.0.

### ISSUE THREAD

**Issue by aeppsi** [MichaIng/DietPi#4834]
#### Details:
- Date           | Wed 13 Oct 19:22:56 CEST 2021
- Bug report     | N/A
- DietPi version | v6.22.3 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 2 Model B (armv7l) (index=2)
- Kernel version | `#1253 SMP Thu Aug 15 11:49:46 BST 2019`
- Distro         | stretch (index=4)
- Command        | G_AGUG
- Exit code      | 100
- Software title | DietPi-Update

#### Steps to reproduce:

1. ...
2. ...

#### Expected behaviour:

- ...

#### Actual behaviour:

- ...

#### Extra details:

- ...

#### Additional logs:
```
Log file contents:
Extracting templates from packages: 100%
Preconfiguring packages ...
Setting up systemd (232-25+deb9u13) ...
/var/lib/dpkg/info/systemd.postinst: 105: /var/lib/dpkg/info/systemd.postinst: addgroup: not found
dpkg: error processing package systemd (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MichaIng** [comment]
That is a pretty broken PATH. This is how it should look like:
```
2021-10-13 19:53:55 root@micha:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
Can you check the following:
```sh
grep 'PATH=' /etc/profile /etc/bash.bashrc /etc/profile.d/* /etc/bashrc.d/* ~/.profile ~/.bashrc
```
And:
```sh
sudo bash -c 'echo $PATH'
```

**Comment by MichaIng** [comment]
Strange, a clean shell contains the correct PATH it seems.  Can you simply try to reboot.

**Comment by aeppsi** [comment]
it is rebooting. What shall I do than? Shall I try to update the system? Or shall I echo "$PATH"?

**Comment by aeppsi** [comment]
the command echo "$PATH" gives back the broken path

root@DietPi:~# echo "$PATH"
/sbin:/bin:/usr/bin:/usr/local/bin

**Comment by aeppsi** [comment]
`root@DietPi:~# sudo bash -ic 'echo $PATH'
 ─────────────────────────────────────────────────────
 DietPi v7.6.2 : 21:14 - Mi 13.10.2021
 ─────────────────────────────────────────────────────
 - Device model : RPi 2 Model B (armv7l)
 - CPU temp : 49'C : 120'F (Optimal temperature)
 - LAN IP : 192.168.178.71 (eth0)
 - MOTD : Learn how to upgrade your system from Stretch to Buster:
          https://dietpi.com/docs/usage/#how-to-upgrade-to-buster
 ─────────────────────────────────────────────────────

 DietPi Team     : MichaIng (lead), Daniel Knight (founder), Joulinar (support)
 Image by        : DietPi Core Team (pre-image: Raspbian Lite)
 Web             : https://dietpi.com | https://twitter.com/DietPi_
 Patreon Legends : Camry2731
 Contribute      : https://dietpi.com/contribute.html
 DietPi Hosting  : Powered by https://myvirtualserver.com

 dietpi-launcher : All the DietPi programs in one place
 dietpi-config   : Feature rich configuration tool for your device
 dietpi-software : Select optimised software for installation
 htop            : Resource monitor
 cpu             : Shows CPU information and stats

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@DietPi:~# 
root@DietPi:~# sudo bash -lc 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
`

**Comment by MichaIng** [comment]
Last test:
```sh
sudo bash -ilc 'echo $PATH'
```
Seems the login shell flag does not imply that it is interactive 🤔.

**Comment by aeppsi** [comment]
dietpi@DietPi:~$ echo "$PATH"
/sbin:/bin:/usr/bin:/usr/local/bin

yes, it looks like it is the same.

**Comment by MichaIng** [comment]
Strange, not sure where this is coming from. You may check all files here
```sh
ls -l /etc/profile.d/* /etc/bashrc.d/* ~/.profile ~/.bashrc
```
whether they load any other script. This is AFAIK everything that is loaded on a shell login, which can then affect the environment (variables like PATH). There are other things loaded at boot, but AFAIK nothing which can change the (bash) shell environment.

**Comment by MichaIng** [comment]
It's fine 😄. By default, when you run `bash`, you'll have `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` as in internal default/fallback. But in interactive shells there are additional scripts loaded which can change variables like `PATH` and obviously this is true in your case. The `PATH` variable is very important, as it defines the default locations or executables/commands, so that you can run commands like `ls` (list file/directory content) without using the full path to them `/bin/ls`. If there are important executable directories missing in that variables, then executing related commands fails.

Okay let's go through them:
```sh
echo "------- /etc/profile.d/at-dbus-fix.sh:
$(</etc/profile.d/at-dbus-fix.sh)"
echo "------- /etc/profile.d/vte-2.91.sh:
$(</etc/profile.d/vte-2.91.sh)"
echo "------- /root/.bashrc:
$(</root/.bashrc)"
echo "------- /root/.profile:
$(</root/.profile)"
```

**Comment by aeppsi** [comment]
root@DietPi:~# echo "------- /etc/profile.d/at-dbus-fix.sh:
> $(</etc/profile.d/at-dbus-fix.sh)"
------- /etc/profile.d/at-dbus-fix.sh:
if ! /usr/bin/dpkg -l at-spi2-core 2> /dev/null | /bin/grep -q ii ; then
   export NO_AT_BRIDGE=1
fi
root@DietPi:~# echo "------- /etc/profile.d/vte-2.91.sh:
> $(</etc/profile.d/vte-2.91.sh)"
------- /etc/profile.d/vte-2.91.sh:
# Copyright © 2006 Shaun McCance <shaunm@gnome.org>
# Copyright © 2013 Peter De Wachter <pdewacht@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Not bash or zsh?
[ -n "$BASH_VERSION" -o -n "$ZSH_VERSION" ] || return 0

# Not an interactive shell?
[[ $- == *i* ]] || return 0

# Not running under vte?
[ "${VTE_VERSION:-0}" -ge 3405 ] || return 0

__vte_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
    safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
    printf "%s" "$safe"
    str="${str#"$safe"}"
    if [ -n "$str" ]; then
      printf "%%%02X" "'$str"
      str="${str#?}"
    fi
  done
)

# Print a warning so that anyone who's added this manually to his PS1 can adapt.
# The function will be removed in a later version.
__vte_ps1() {
  echo -n "(__vte_ps1 is obsolete)"
}

__vte_osc7 () {
  printf "\033]7;file://%s%s\007" "${HOSTNAME:-}" "$(__vte_urlencode "${PWD}")"
}

__vte_prompt_command() {
  local pwd='~'
  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
  printf "\033]0;%s@%s:%s\007%s" "${USER}" "${HOSTNAME%%.*}" "${pwd}" "$(__vte_osc7)"
}

case "$TERM" in
  xterm*|vte*)
    [ -n "$BASH_VERSION" ] && PROMPT_COMMAND="__vte_prompt_command"
    [ -n "$ZSH_VERSION"  ] && precmd_functions+=(__vte_osc7)
    ;;
esac

true
root@DietPi:~# echo "------- /root/.bashrc:
> $(</root/.bashrc)"
------- /root/.bashrc:
# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
# export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
# alias ls='ls $LS_OPTIONS'
# alias ll='ls $LS_OPTIONS -l'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
root@DietPi:~# echo "------- /root/.profile:
> $(</root/.profile)"
------- /root/.profile:
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true

**Comment by aeppsi** [comment]
The lines above it gives back when I login via Putty ssh.

**Comment by MichaIng** [comment]
Ah okay, in the meantime you should be actually able to connect via `Xorg` authentication method, at least when applying recent fixes (not sure if these were applied automatically on DietPi update):
```sh
G_AGI xrdp xorgxrdp
G_CONFIG_INJECT 'Option "DefaultServerLayout" "X11 Server"' /etc/X11/xrdp/xorg.conf '    Option "DefaultServerLayout" "X11 Server"' 'Section "ServerFlags"'
```

If this works and you don't use the VNC server directly, you may uninstall it:
```sh
dietpi-software uninstall 28 120
```
__________
The files content is identical, regardless how you connect. The question is whether the PATH variable is the same or now:
```sh
echo $PATH
```
Probably the XRDP/VNC invocation manipulates it, or the desktop session. Test the above when connecting via RDP => `Xorg`.

**Comment by MichaIng** [comment]
Okay then it's at least not the VNC server's fault. Let's check whether one of the X server scripts set the PATH:
```sh
grep -r PATH /etc/X11
```

**Comment by aeppsi** [comment]
root@DietPi:~# grep -r PATH /etc/X11
/etc/X11/Xsession.d/20x11-common_process-args:        STARTUP_FULL_PATH=$(/usr/b                                                                                                      in/which "$1" || true)
/etc/X11/Xsession.d/20x11-common_process-args:        if [ -n "$STARTUP_FULL_PAT                                                                                                      H" ] && [ -e "$STARTUP_FULL_PATH" ]; then
/etc/X11/Xsession.d/20x11-common_process-args:          if [ -x "$STARTUP_FULL_P                                                                                                      ATH" ]; then

**Comment by aeppsi** [comment]
I just updated DietPi from v7.6.2 to v7.7.3. So it obviously had something to do with VNC.

**Comment by MichaIng** [comment]
> Connecting via Windows remote desktop connection is not possible anymore.

Even when using the `Xorg` method? That shouldn't be affected at all by the VNC server. Probably a reinstall helps:
```sh
dietpi-software reinstall 29
```

Okay so the global X11 startup scripts do not set PATH either. Last idea one of the user ones:
```sh
grep -r PATH /root
```

> I just updated DietPi from v7.6.2 to v7.7.3. So it obviously had something to do with VNC.

Actually not, why? Is XRDP working again after the update?

**Comment by aeppsi** [comment]
Connecting via Xorg is not possible. The windows remote desktop app does not find the dietpi device. Reinstalling didn't fix this issue.
I updated the system via Putty ssh.

root@DietPi:~# grep -r PATH /root
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting WINDOWPATH=1
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/usr/local/sbin                                                                     :/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/root/.xsession-errors:dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr                                                                     /bin:/usr/local/bin
/root/.bash_history:echo "$PATH"
/root/.bash_history:grep 'PATH=' /etc/profile /etc/bash.bashrc /etc/profile.d/* /etc/ba                                                                     shrc.d/* ~/.profile ~/.bashrc
/root/.bash_history:sudo bash -c 'echo $PATH'
/root/.bash_history:echo "$PATH"
/root/.bash_history:sudo bash -ic 'echo $PATH'
/root/.bash_history:sudo bash -ic 'echo $PATH'
/root/.bash_history:sudo bash -lc 'echo $PATH'
/root/.bash_history:PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
/root/.bash_history:echo $PATH
/root/.bash_history:echo $PATH
/root/.bash_history:echo $PATH
/root/.bash_history:sudo bash -ic 'echo $PATH'
/root/.bash_history:sudo bash -lc 'echo $PATH'
/root/.bash_history:sudo bash -ilc 'echo $PATH'
/root/.bash_history:echo $PATH
/root/.bash_history:echo $PATH
/root/.bash_history:root@DietPi:~# echo $PATH
/root/.bash_history:root@DietPi:~# echo $PATH
/root/.bash_history:grep -r PATH /etc/X11
/root/.bash_history:root@DietPi:~# grep -r PATH /etc/X11
/root/.bash_history:/etc/X11/Xsession.d/20x11-common_process-args:        STARTUP_FULL_                                                                     PATH=$(/usr/b                                                                                                                                                                           in/which "$1" || true)
/root/.bash_history:/etc/X11/Xsession.d/20x11-common_process-args:        if [ -n "$STA                                                                     RTUP_FULL_PAT                                                                                                                                                                           H" ] && [ -e "$STARTUP_FULL_PATH" ]; then
/root/.bash_history:echo 'PATH
/root/.bash_history:echo $PATH

**Comment by MichaIng** [comment]
`dbus-update-activation-environment` seems to do this. I'll try to replicate on Stretch.

> The windows remote desktop app does not find the dietpi device.

Please share the output of the following command:
```sh
journalctl -u xrdp
ss -tulpn
```

**Comment by aeppsi** [comment]
root@DietPi:~# journalctl -u xrdp
-- Logs begin at Thu 2016-11-03 18:16:42 CET, end at Sun 2021-10-17 21:55:07 CES
T. --
Okt 17 20:35:34 DietPi systemd[1]: Dependency failed for xrdp daemon.
Okt 17 20:35:34 DietPi systemd[1]: xrdp.service: Job xrdp.service/start
failed with result 'dependency'.
root@DietPi:~# ss -tulpn
Netid  State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
tcp    LISTEN     0      50        *:445                   *:*                   users:(("smbd",pid=560,fd=32))
tcp    LISTEN     0      5      127.0.0.1:4711                  *:*                   users:(("pihole-FTL",pid=462,fd=10))
tcp    LISTEN     0      50        *:139                   *:*                   users:(("smbd",pid=560,fd=33))
tcp    LISTEN     0      128       *:80                    *:*                   users:(("lighttpd",pid=594,fd=4))
tcp    LISTEN     0      32        *:53                    *:*                   users:(("pihole-FTL",pid=462,fd=5))
tcp    LISTEN     0      128       *:22                    *:*                   users:(("dropbear",pid=282,fd=3))
tcp    LISTEN     0      50       :::445                  :::*                   users:(("smbd",pid=560,fd=30))
tcp    LISTEN     0      5       ::1:4711                 :::*                   users:(("pihole-FTL",pid=462,fd=14))
tcp    LISTEN     0      50       :::139                  :::*                   users:(("smbd",pid=560,fd=31))
tcp    LISTEN     0      128      :::80                   :::*                   users:(("lighttpd",pid=594,fd=5))
tcp    LISTEN     0      32       :::53                   :::*                   users:(("pihole-FTL",pid=462,fd=7))
tcp    LISTEN     0      128      :::22                   :::*                   users:(("dropbear",pid=282,fd=4))

**Comment by aeppsi** [comment]
root@DietPi:~# journalctl -u xrdp -u xrdp-sesman
-- Logs begin at Thu 2016-11-03 18:16:42 CET, end at Mon 2021-10-18 19:36:06 CES
T. --
Okt 17 20:35:34 DietPi systemd[1]: Starting xrdp session manager...
Okt 17 20:35:34 DietPi xrdp-sesman[439]: (439)(1995763072)[INFO ] starting xrdp-
sesman with pid 439
Okt 17 20:35:34 DietPi xrdp-sesman[439]: (439)(1995763072)[ERROR] bind e
rror on port '3350': 22 (Invalid argument)
Okt 17 20:35:34 DietPi xrdp-sesman[439]: (439)(1995763072)[DEBUG] Closed socket
7 (AF_INET6 :: port 0)
Okt 17 20:35:34 DietPi systemd[1]: xrdp-sesman.service: PID file /run/xrdp/xrdp-
sesman.pid not readable (yet?) after start: No such file or directory
Okt 17 20:35:34 DietPi systemd[1]: Failed to start xrdp session manager.

Okt 17 20:35:34 DietPi systemd[1]: Dependency failed for xrdp daemon.
Okt 17 20:35:34 DietPi systemd[1]: xrdp.service: Job xrdp.service/start
failed with result 'dependency'.
Okt 17 20:35:34 DietPi systemd[1]: xrdp-sesman.service: Unit entered fai
led state.
Okt 17 20:35:34 DietPi systemd[1]: xrdp-sesman.service: Failed with resu
lt 'resources'.

**Comment by aeppsi** [comment]
Okay, I will do so and set up the new system.

Thank you very much for your support. I learned a lot during our conversation. You guys are doing a great job. Cheers.

**Comment by MichaIng** [comment]
Did you have the issue solved with the new system?

**Comment by aeppsi** [comment]
Yes. I set up the new system and everything works as it should. Thanks again for your help.

**Comment by Joulinar** [comment]
OK I'm going to close the issue. Feel free to reopen if needed.
