### ISSUE TITLE
Got display problem after kodi exit

### ISSUE THREAD

**Issue by 467815891a** [MichaIng/DietPi#484]
I setup v129 on my Rasberrypi2.Use VGA to HDMI Cable connect to my monitor(1366_768).
I modify /boot/config.txt and force Raspberrypi output with 1366_768 resolution.It works well.
I am sure my Raspberrypi got enough current and VGA to HDMI Cable got External power.
I used dietpi-software to install kodi. kodi plays video perfectly.But after I exit kodi,I only saw my desktop in a flash,and soon it jump to a "abnormal" desktop.The resolution and color are both changed. Forgive my poor english,I can't describe it,but I took pictures.
This is normal Desktop before I run kodi: http://5aimiku.com/wp-content/uploads/2016/08/2016082913214040.jpg
This is "abnormal" Dsktop after exit kodi: http://5aimiku.com/wp-content/uploads/2016/08/2016082913210273.jpg
I try to change Desktop environment frome LDXE to XFACE4,turn Overscan on or off,but It doesn't change anything.I need some advice...

**Comment by Fourdee** [comment]
@467815891a 

Looks like a possible bug with the "black screen kodi on exit" workaround we use on RPi: https://github.com/Fourdee/DietPi/blob/master/dietpi/misc/start_kodi#L34-L40

I'll take a look. Thanks for report :+1:

**Comment by 467815891a** [comment]
Thanks for reply, I am very appreciated for your work!

**Comment by Fourdee** [comment]
@467815891a 

Yep, seems the workaround is no longer needed. Possibility added to Kodi binary.

I'd appreciate it if you can confirm this update has resolved the issue.
Please run the following command:

```
wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/dietpi/misc/start_kodi -O /DietPi/dietpi/misc/start_kodi
```

Then launch Kodi from your desktop, followed by exit.

**Comment by Fourdee** [comment]
Tested and working for me on RPi3. 

@467815891a I'll mark as closed, please reopen if required.
