### ISSUE TITLE
Pi-hole - automatic install

### ISSUE THREAD

**Issue by ksz16** [MichaIng/DietPi#4841]
#### Is your feature request related to a problem? Please describe:
I tried to install Pi-hole automatically (AUTO_SETUP_INSTALL_SOFTWARE_ID=93 in dietpi.txt) - unfortunately Pi-hole was not installed.
I thought maybe it failed because prerequisites were missing, so I tried again by putting additional packages to dietpi.txt file (Git, Lighttpd, SQLite and PHP).
Unfortunately again with no effect - Pi-hole was not installed.
Is there any way to automatically install this package in DietPi?
- ...

#### Describe the solution you'd like:
As far as I know, there is a flag "--unattended", which allows it, if a configuration file /etc/pihole/setupVars.conf exists.

You could add the configuration to dietpi.txt - something like this:

```
#------------------------------------------------------------------------------------------------------
##### DietPi-Software settings #####
#------------------------------------------------------------------------------------------------------

# Pi-hole
PIHOLE_INTERFACE=wlan0
IPV4_ADDRESS=
IPV6_ADDRESS=
PIHOLE_DNS_1=127.0.0.1#5335
QUERY_LOGGING=false
INSTALL_WEB_SERVER=false
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
CACHE_SIZE=10000
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
BLOCKING_ENABLED=true
WEBPASSWORD=
ADMIN_EMAIL=
WEBUIBOXEDLAYOUT=boxed
WEBTHEME=default-auto
```

And change the installation command to (of course only if one chooses this option in the dietpi.txt file):

`./install.sh --disable-install-webserver --unattended` 
- ...

Is there any chance to solve this problem?

**Comment by MichaIng** [comment]
Pi-hole cannot be reasonably installed automatically, the setup variables may chance at any time and this `--unattended` is basically unsupported (by Pi-hole team) to be used like that. It is only used for updates internally. In `dietpi-software` it is hence, among with a few other software titles where interactive input is strictly required, excluded from automated installs. But actually it makes sense that we document this somewhere to avoid confusion 🤔.

See the discussion made here: https://github.com/pi-hole/pi-hole/pull/3589
The idea first was to allow/support an automated Pi-hole install, but it was denied.
