### ISSUE TITLE
Temp in banner doesn't match CPU temp [x86]

### ISSUE THREAD

**Issue by rhinot** [MichaIng/DietPi#4848]
#### Required Information
- DietPi version | 
```
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
G_LIVE_PATCH_STATUS[1]='applied'
G_LIVE_PATCH_STATUS[2]='applied'
G_LIVE_PATCH_STATUS[3]='applied'
G_LIVE_PATCH_STATUS[4]='not applicable'
```

- Distro version | bullseye
- Kernel version | `Linux nuc 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`
- SBC model | Native PC (x86_64)
    It's an Intel NUC7PJYH
- Power supply used | Power supply provided with Intel NUC
- SDcard used | 256GB SSD

#### Steps to reproduce
1. Open terminal, look at temperature in banner
2. Run sensors, look at temperature displayed
3. Run MichaIng's previous debug command on this topic from https://github.com/MichaIng/DietPi/issues/3172#issuecomment-543683123

#### Expected behaviour
- Terminal banner temperature should match one of the two other temperature sources

#### Actual behaviour
- Terminal banner temperature is significantly hotter

Example (all taken within 30s of each other; see screenshots at bottom)

```
Banner: CPU temp : 65'C : 149'F (Running hot, not recommended)
Sensor: Package & all cores: 54C
Debug loop: Highest temp is 62C
```

![Screenshot 2021-10-16 12 07 50 PM](https://user-images.githubusercontent.com/1837254/137594669-2aa68d30-5381-45b9-a662-e408c714b7a7.png)
![Screenshot 2021-10-16 12 08 57 PM](https://user-images.githubusercontent.com/1837254/137594666-66d13dc0-b662-4684-bae4-269115aa3eb1.png)
![Screenshot 2021-10-16 12 09 12 PM](https://user-images.githubusercontent.com/1837254/137594664-913f7651-c4a6-4931-96d9-a4e9a3bb92a6.png)

#### Extra details
Because you've asked in previous posts, the dir structure

```
total 0
lrwxrwxrwx 1 root root    0 Oct 16 12:11 driver -> ../../../bus/platform/drivers/coretemp
-rw-r--r-- 1 root root 4096 Oct 16 12:11 driver_override
drwxr-xr-x 3 root root    0 Oct 16 12:05 hwmon
-r--r--r-- 1 root root 4096 Oct 16 12:11 modalias
drwxr-xr-x 2 root root    0 Oct 16 12:11 power
lrwxrwxrwx 1 root root    0 Oct 16 12:05 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root 4096 Oct 16 12:05 uevent
```

![Screenshot 2021-10-16 12 11 28 PM](https://user-images.githubusercontent.com/1837254/137594662-92be36d7-fa77-4820-95e1-768f5965e78e.png)

**Comment by MichaIng** [comment]
The CPU temperature can change quite quickly, so I believe it has just cooled down until you ran the checks. Please verify via:
```
G_OBTAIN_CPU_TEMP
for i in /sys/class/thermal/thermal_zone[0-9]/temp /sys/class/hwmon/hwmon[0-9]/temp[0-9]_input /sys/devices/platform/coretemp.[0-9]/hwmon/hwmon[0-9]/temp[0-9]_input
do
[[ -e $i ]] && echo "$i : $(<$i)"
done
```
