### ISSUE TITLE
Update to DietPi 7.7.3 failed

### ISSUE THREAD

**Issue by Aid-Mic70** [MichaIng/DietPi#4853]
#### Details:
- Date           | Sun Oct 17 10:07:13 CEST 2021
- Bug report     | d13736b8-9e40-4dc1-9e4b-36d1993f7104
- DietPi version | v7.6.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 4 Model B (armv7l) (ID=4)
- Kernel version | `Linux DietPi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `apt-get -q update`
- Exit code      | 255
- Software title | DietPi-Update
#### Steps to reproduce:

1. Initiate Update ( dietpi-Update ) v7.6.2 to v7.7.3

#### Expected behaviour:
Update was expected to be finished without any problem
- ...
#### Actual behaviour:

- Update failed with an error
#### Extra details:

- ...
#### Additional logs:
```
Err:1 https://archive.raspberrypi.org/debian bullseye InRelease
  Temporary failure resolving 'archive.raspberrypi.org'
Err:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
  Temporary failure resolving 'raspbian.raspberrypi.org'
Reading package lists...
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/bullseye/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch https://archive.raspberrypi.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'archive.raspberrypi.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
