### ISSUE TITLE
NanoPI NEO2 bullseye image seems corrupt/flawed

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#4856]
The NanoPI NEO2 bullseye image (https://dietpi.com/downloads/images/DietPi_NanoPiNEO2-ARMv8-Bullseye.7z) seems corrupt/flawed.

After burning the image to SD-card with either rufus or balenaEtcher there's no filesystem to mount: not in Windows and also not with debian (DietPi).

**Comment by MichaIng** [comment]
It is normal that on Windows nothing is mounted, as Windows does not support ext4. So this and was always the same (with single partition images) 😉.

I'll test the image.

**Comment by MichaIng** [comment]
Mounts and boots flawlessly here 🤔. Probably an issue with the SD card?

**Comment by MichaIng** [comment]
Okay great, through sad for the SD card 🤔.
