### ISSUE TITLE
Updating to Bullseye

### ISSUE THREAD

**Issue by barukh27** [MichaIng/DietPi#4857]
Hi there!

I'm upgrading from Buster to Bullseye following this tutorial: https://dietpi.com/blog/?p=811#2.2-manual-upgrade

I think I've followed every step but when I run the command  apt upgrade I receive the following error:

![image](https://user-images.githubusercontent.com/49249214/137635902-2b72bdba-0632-4dfb-97e3-dc8add04bdea.png)

What should I do?

Thanks in advance.

**Comment by MichaIng** [comment]
Many thanks for your report.

Has the Raspberry Pi repository migrated to Bullseye as well?
```sh
cat /etc/apt/sources.list.d/raspi.list
```

**Comment by MichaIng** [comment]
And if you upgrade `g++` separately?
```sh
apt install --autoremove g++
```

**Comment by barukh27** [comment]
Idem

![image](https://user-images.githubusercontent.com/49249214/137636643-8c6eeab1-fabc-4996-a712-c8cb2165ab5e.png)

**Comment by MichaIng** [comment]
Okay, then we need to purge it. This will remove a bunch of other development packages and compilers, but shouldn't be any end user software package:
```sh
apt purge --autoremove libgcc-8-dev
```
If you require them, you can re-install them later:
```sh
apt install g++
```
But if you installed software via `dietpi-software` only, then it is not required for regular usage and will be automatically reinstall when you (re)install software which requires the C/C++ toolkit for installation.

**Comment by barukh27** [comment]
Hi again.

Now I've got this issue.

![image](https://user-images.githubusercontent.com/49249214/137637868-a895f16c-a2f8-4fb7-8222-5466c95315ba.png)

**Comment by Joulinar** [comment]
Could you try running

```
apt full-upgrade
```

**Comment by barukh27** [comment]
thank you for your answer.

That's the error I got.
