### ISSUE TITLE
Update Process failing with Tor (dietpi-update)

### ISSUE THREAD

**Issue by Nickwasused** [MichaIng/DietPi#4859]
#### Required Information
- DietPi version | `7.7.3`
- Distro version | `buster`
- Kernel version | `5.10.60`
- SBC model | `RPi 3 Model B (aarch64)`
- Power supply used | `5V 1A`
- SDcard used | `Samsung + USB Boot`

#### Additional Information (if applicable)
- Software title | `Tor`
- Can this issue be replicated on a fresh installation of DietPi?
`Well, yes if you configure apt to use Tor.`

#### Steps to reproduce
1. Install Tor
2. Configure apt to use Tor for their updates
`deb tor+https://deb.debian.org/debian/ buster main contrib non-free`
3. Wait for a new Version of dietpi
4. run `dietpi-update`
5. The updater should fail at `Phase: Upgrading APT packages`

#### Expected behaviour
The updater shouldn´t kill tor before fetching the apt updates. Maybee the steps should be like that:
1. Fetch the Apt updates
2. Kill the other Services like tor
3. Run apt upgrade

#### Actual behaviour
1. Updater gets run
2. Tor is killed
`[  OK  ] DietPi-Services | stop : tor`
3. At `Phase: Upgrading APT packages` the Updater can´t get the Updates because tor is already killed.

#### Extra details
At the moment I wait for the error to appear, then I log in using a second shell and start tor manually. After that I select `retry` and the Update process finishes with no problems.

**Comment by MichaIng** [comment]
So not only network clients use Tor but the server itself must use Tor to be able to do any network connection? That is not a setup I'd keep, I mean it's the server which only rarely connects to well known software/update servers where you probably don't require all that being passed through Tor?

However, if you want to keep it like that, you need to exclude the Tor service from being handled by `dietpi-services`:
```sh
echo '- tor' >> /boot/dietpi/.dietpi-services_include_exclude
```
Can be also done via `dietpi-services` menus.
