### ISSUE TITLE
DietPi-Software | Kodi runs in background on RPi 4 Bullseye

### ISSUE THREAD

**Issue by barukh27** [MichaIng/DietPi#4860]
Hi there,

I've performed an update to Bullseye but get I reboot the RPi Kodi doesn't autostart. I get this error: /boot/dietpi/misc/start_kodi: 28 exec: kodi: not found

I've checked the program list and Kodi appears as mark (number 31) and in the autostart options is checked as #1

Any ideas?

**Comment by MichaIng** [comment]
Probably the Kodi APT package was removed. Can you check:
```sh
dpkg -l kodi
```
Is it a 32-bit or 64-bit system? I know the bug report template may appear unnecessary work, but it's not. The information helps us to quickly replicate and offer tailored platform-specific solutions instead of requiring another Q&A iteration 😉.

**Comment by barukh27** [comment]
> > How do I check that?
> 
> Would have been part of the issue template: `uname -m` However, I see already from the Kodi package version (the left configuration files) that it's a 32-bit image, so indeed it got removed, which actually makes sense. We need to add that to reinstalls as well:
> 
> ```shell
> dietpi-software reinstall 31
> ```

Should I reinstall then?

**Comment by MichaIng** [comment]
Yes, please do so, as there is a custom package from our servers installed. Is it an RPi 4 or earlier model? On RPi 4 with it's two HDMI ports there is currently an issue where Kodi starts somehow always in background (on the other port, even without any screen attached). So then we need to apply a workaround as well, I have an idea already.

**Comment by barukh27** [comment]
I've reinstalled and I get this errro:

![image](https://user-images.githubusercontent.com/49249214/137641945-9cc19aac-00de-4863-92fc-d964bfb342b7.png)

It's a RPi 4

**Comment by MichaIng** [comment]
Ah yes, the known issue. The error message is irrelevant (doesn't break anything), and moving the mouse or probably even using keyboard up/down buttons should produce the hover sounds of the Kodi GUI. It for some reason runs in background.

Can you try the following (hit CTRL+C to exit the background Kodi):
1. Attempt: Enable both framebuffer devices:
```sh
G_CONFIG_INJECT 'max_framebuffers=' 'max_framebuffers=2' /boot/config.txt
reboot
```
2. Attempt: Wrap Kodi into an X server session:
```sh
xinit $(which kodi) --standalone
```
3. Attempt: Use Debian's Kodi package:
```sh
apt install --reinstall --allow-downgrade kodi
kodi --standalone
# Or if the issue is the same with above, which at least was the case on our tests
xinit $(which kodi) --standalone
```

**Comment by barukh27** [comment]
I get this performing the third attempt:

![image](https://user-images.githubusercontent.com/49249214/137643674-0ea7633f-3f7d-4b5c-b426-f1f34c1f57a7.png)

**Comment by MichaIng** [comment]
Ah sorry, it's (missing `s`):
```sh
apt install --reinstall --allow-downgrades kodi
kodi --standalone
# Or if the issue is the same with above, which at least was the case on our tests
xinit $(which kodi) --standalone
```

**Comment by MichaIng** [comment]
Ah dammit, it's not compiled on Raspbian 🤔. Okay let's try it like that:
```sh
cd /tmp
curl -sSfLO https://deb.debian.org/debian/pool/main/k/kodi/kodi_19.1+dfsg2-2_armhf.deb
curl -sSfLO https://deb.debian.org/debian/pool/main/k/kodi/kodi-bin_19.1+dfsg2-2_armhf.deb
curl -sSfLO https://deb.debian.org/debian/pool/main/k/kodi/kodi-data_19.1+dfsg2-2_all.deb
apt install --reinstall --allow-downgrades kodi*.deb
```

**Comment by MichaIng** [comment]
Next correction (missing `./` to select the local files):
```sh
apt install --reinstall --allow-downgrades ./kodi*.deb
```

**Comment by barukh27** [comment]
I can install but when I run:  kodi --standalone I get:

failed to open zone.tab
libva info: VA-API version 1.10.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by MichaIng** [comment]
So without X server it is exactly the same, which matches @Joulinar's tests. Does it work when wrapping into an X server (the Debian build has support for X it natively included, compared to ours):
```sh
xinit "$(which kodi)" --standalone
```

**Comment by MichaIng** [comment]
Dammit thing. Changing the HDMI port for the screen doesn't help, does it? Or attaching two screens? Ah, as I'm not sure which defaults are used when, another attempt:
```sh
xinit "$(which kodi)" --windowing=x11 --standalone
# or
kodi --windowing=gbm --standalone
```

**Comment by barukh27** [comment]
failed to open zone.tab
/usr/lib/arm-linux-gnueabihf/kodi/kodi-xrandr: Failed to get size of gamma for output default
Segmentation fault
Crash report available at /root/kodi_crashlog-20211017_230006.log
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

**Comment by MichaIng** [comment]
Btw, you have a desktop installed (so a fully fledged X server)?

**Comment by barukh27** [comment]
Yes, I have LXDE: ultra lightweight desktop

**Comment by Joulinar** [comment]
> Btw: I can't access to the rpi via VNC either.

you have installed RealVNC or TigerVNC?

**Comment by barukh27** [comment]
RealVNC

**Comment by barukh27** [comment]
Thank you for your help, both Michalng, and Joulinar.

I'll wait for the workaround.

**Comment by Joulinar** [comment]
nope until know we have no solution for the Kodi issue.

**Comment by MichaIng** [comment]
Nasty... I'll start to compile a new ARMv7 build tomorrow. Let's see whether this helps.

**Comment by barukh27** [comment]
> Ah, I mixed it up, that was for TigerVNC, not RealVNC (obviously from the path).
> 
> Hmm, when `ss -tulpn` shows RealVNC, then the server is running and listening to requests. 

How does the connection issue look like? Do you reach a login mask? And which VNC client do you use?

I use vnc viewer and I don't reach the login mask, the program says that the time for the request is out.

**Comment by MichaIng** [comment]
Strange, can you show the logs:
```sh
journalctl -u vncserver
```

**Comment by barukh27** [comment]
Oct 17 22:51:00 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 17 22:51:00 DietPi systemd[624]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 17 22:51:01 DietPi vncserver[685]: /usr/bin/vncserver-virtual: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory
Oct 17 22:51:01 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 22:51:01 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.

**Comment by Joulinar** [comment]
ahh that`s the missing library issue

probably this is helping https://github.com/MichaIng/DietPi/issues/4729#issuecomment-917494127

```
cd /usr/lib/arm-linux-gnueabihf
ln -s libmmal_core.so.0 libmmal_core.so
ln -s libmmal_util.so.0 libmmal_util.so
ln -s libmmal_vc_client.so.0 libmmal_vc_client.so
ln -s libbcm_host.so.0 libbcm_host.so
ln -s libvcsm.so.0 libvcsm.so
ln -s libvchiq_arm.so.0 libvchiq_arm.so
ln -s libvcos.so.0 libvcos.so
```

**Comment by barukh27** [comment]
Sorry but it doesn't work.

**Comment by MichaIng** [comment]
I thought RealVNC got a rebuild already 🤔. But indeed it didn't: https://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/?C=M;O=D

> Sorry but it doesn't work.

Did you restart the service?
```sh
systemctl restart vncserver
sleep 3
journalctl -u vncserver
```

**Comment by MichaIng** [comment]
That one does not exist?
```sh
ls -l /usr/lib/arm-linux-gnueabihf/libvcos.so.0
```
On my system it does. So that one should have solved it:
```sh
cd /usr/lib/arm-linux-gnueabihf
ln -s libvcos.so.0 libvcos.so
```

**Comment by MichaIng** [comment]
Can you show the output of this:
```sh
ls -l /usr/lib/arm-linux-gnueabihf/libvcos.so*
```

**Comment by MichaIng** [comment]
Ah there was one missing:
```sh
cd /usr/lib/arm-linux-gnueabihf
ln -s libmmal.so.0 libmmal.so
systemctl restart vncserver
sleep 3
journalctl -u vncserver
```

**Comment by barukh27** [comment]
root@DietPi:/usr/lib/arm-linux-gnueabihf# journalctl -u vncserver
Journal file /var/log/journal/d6e05c03d8af48498a671f8f0d7bf636/system.journal is truncated, ignoring file.
-- Journal begins at Mon 2021-10-18 00:02:08 CEST, ends at Mon 2021-10-18 00:42:58 CEST. --
Oct 18 00:02:19 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:02:19 DietPi systemd[590]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:02:20 DietPi vncserver[652]: /usr/bin/vncserver-virtual: error while loading shared libraries: libvcos.so: cannot open shared object file: No such file or directory
Oct 18 00:02:20 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:02:20 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:17:22 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:17:22 DietPi systemd[5850]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:17:22 DietPi vncserver[5858]: /usr/bin/vncserver-virtual: error while loading shared libraries: libvcos.so: cannot open shared object file: No such file or directory
Oct 18 00:17:22 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:17:22 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:27:05 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:27:05 DietPi systemd[7606]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:27:05 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:27:05 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:28:11 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:28:11 DietPi systemd[7837]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:28:12 DietPi vncserver[7846]: /usr/bin/vncserver-virtual: error while loading shared libraries: libmmal.so: cannot open shared object file: No such file or directory
Oct 18 00:28:12 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:28:12 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:29:25 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:29:25 DietPi systemd[8067]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:29:26 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:29:26 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:42:45 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:42:45 DietPi systemd[10372]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:42:45 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:42:45 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:42:58 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:42:58 DietPi systemd[10430]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:42:58 DietPi vncserver[10438]: /usr/bin/vncserver-virtual: error while loading shared libraries: libmmal_components.so: cannot open shared object file: No such file or directory
Oct 18 00:42:58 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:42:58 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.

**Comment by MichaIng** [comment]
Issue reported: https://github.com/RPi-Distro/repo/issues/267

And the next:
```
cd /usr/lib/arm-linux-gnueabihf
ln -s libmmal_components.so.0 libmmal_components.so
systemctl restart vncserver
sleep 3
journalctl -u vncserver
```

**Comment by barukh27** [comment]
> Issue reported: [RPi-Distro/repo#267](https://github.com/RPi-Distro/repo/issues/267)
> 
> And the next:
> 
> ```
> cd /usr/lib/arm-linux-gnueabihf
> ln -s libmmal_components.so.0 libmmal_components.so
> systemctl restart vncserver
> sleep 3
> journalctl -u vncserver
> ```
> 
> Until it succeeds, you can repeat the same for every new library file it cannot find 😉.

I don't get it. Could you please elaborate?

**Comment by barukh27** [comment]
I don't know what I'm doing wrong.

root@DietPi:/usr/lib/arm-linux-gnueabihf# ln -s libvcos.so.0 libvcos.so
ln: failed to create symbolic link 'libvcos.so': File exists

**Comment by Joulinar** [comment]
pls post following

```
systemctl restart vncserver
sleep 3
journalctl -u vncserver
```

**Comment by barukh27** [comment]
Journal file /var/log/journal/d6e05c03d8af48498a671f8f0d7bf636/system.journal is truncated, ignoring file.
-- Journal begins at Mon 2021-10-18 00:02:08 CEST, ends at Mon 2021-10-18 13:31:47 CEST. --
Oct 18 00:02:19 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:02:19 DietPi systemd[590]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:02:20 DietPi vncserver[652]: /usr/bin/vncserver-virtual: error while loading shared libraries: libvcos.so: cannot open shared object file: No such file or directory
Oct 18 00:02:20 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:02:20 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:17:22 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:17:22 DietPi systemd[5850]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:17:22 DietPi vncserver[5858]: /usr/bin/vncserver-virtual: error while loading shared libraries: libvcos.so: cannot open shared object file: No such file or directory
Oct 18 00:17:22 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:17:22 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:27:05 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:27:05 DietPi systemd[7606]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:27:05 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:27:05 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:28:11 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:28:11 DietPi systemd[7837]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:28:12 DietPi vncserver[7846]: /usr/bin/vncserver-virtual: error while loading shared libraries: libmmal.so: cannot open shared object file: No such file or directory
Oct 18 00:28:12 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:28:12 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:29:25 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:29:25 DietPi systemd[8067]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:29:26 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:29:26 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:42:45 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:42:45 DietPi systemd[10372]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:42:45 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:42:45 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:42:58 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:42:58 DietPi systemd[10430]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:42:58 DietPi vncserver[10438]: /usr/bin/vncserver-virtual: error while loading shared libraries: libmmal_components.so: cannot open shared object file: No such file or directory
Oct 18 00:42:58 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:42:58 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 00:50:00 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 00:50:00 DietPi systemd[11572]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 00:50:00 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 00:50:00 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 07:45:49 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 07:45:49 DietPi systemd[27364]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 07:45:49 DietPi vncserver[27373]: /usr/bin/vncserver-virtual: error while loading shared libraries: libcontainers.so: cannot open shared object file: No such file or directory
Oct 18 07:45:49 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 07:45:49 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 10:57:39 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 10:57:39 DietPi systemd[20809]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 10:57:39 DietPi systemd[1]: vncserver.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 10:57:39 DietPi systemd[1]: vncserver.service: Failed with result 'exit-code'.
Oct 18 11:03:18 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 11:03:18 DietPi systemd[21774]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 11:07:35 DietPi systemd[1]: Stopping Manage VNC Server (DietPi)...
Oct 18 11:07:35 DietPi systemd[22643]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 11:07:37 DietPi systemd[1]: vncserver.service: Succeeded.
Oct 18 11:07:37 DietPi systemd[1]: Stopped Manage VNC Server (DietPi).
Oct 18 11:07:37 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 11:07:37 DietPi systemd[22654]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 13:30:28 DietPi systemd[1]: Stopping Manage VNC Server (DietPi)...
Oct 18 13:30:28 DietPi systemd[7353]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 13:30:28 DietPi systemd[1]: vncserver.service: Succeeded.
Oct 18 13:30:28 DietPi systemd[1]: Stopped Manage VNC Server (DietPi).
Oct 18 13:30:28 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 13:30:28 DietPi systemd[7363]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 13:31:44 DietPi systemd[1]: Stopping Manage VNC Server (DietPi)...
Oct 18 13:31:44 DietPi systemd[7726]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
Oct 18 13:31:46 DietPi systemd[1]: vncserver.service: Succeeded.
Oct 18 13:31:46 DietPi systemd[1]: Stopped Manage VNC Server (DietPi).
Oct 18 13:31:46 DietPi systemd[1]: Started Manage VNC Server (DietPi).
Oct 18 13:31:46 DietPi systemd[7742]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)

**Comment by barukh27** [comment]
Hi there!

I've found this topic: https://forum.kodi.tv/showthread.php?tid=357454

Can it be related to our topic in question?

Thanks.

**Comment by MichaIng** [comment]
Sadly this is about the properly working Kodi 18 from the RPi Buster branch. We have the issues with Kodi 19 for Bullseye. Somehow it it worked for one user at our forum: https://dietpi.com/phpbb/viewtopic.php?p=39212#p39212

I'll rebuild the package tomorrow, Kodi 19.3 against latest firmware/libraries. Let's see whether this helps.

**Comment by barukh27** [comment]
Ok, thanks again.

**Comment by MichaIng** [comment]
Issue solved itself via firmware upgrade. Also a new official Kodi build from RPi engineers is available, which will be implemented with next release: https://dietpi.com/phpbb/viewtopic.php?p=39873#p39873
