### ISSUE TITLE
Initial setup fails with dpgk code 1 (09-linux-image-current-sunxi_21.08.2_armhf.deb)

### ISSUE THREAD

**Issue by megum1n** [MichaIng/DietPi#4868]
#### Required Information
- DietPi version
```
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=3
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
```
- Distro version
`buster`
- Kernel version
`Linux DietPi 5.10.43-sunxi #21.05.6 SMP Mon Jun 21 15:07:45 UTC 2021 armv7l GNU/Linux`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
`NanoPi NEO (armv7l)`
- Power supply used
5V 2A
- SDcard used
SanDisk ultra 16G

#### Additional Information (if applicable)
- Can this issue be replicated on a fresh installation of DietPi?
Yes

#### Steps to reproduce
1. Flash new OS to sdcard
2. Connect to the device via SSH and start initial setup

#### Expected behaviour
- Just werks

#### Actual behaviour
<details>
  <summary>Logfile attached. Click to expand!</summary>

```
/etc/kernel/preinst.d/dietpi-initramfs_cleanup: 23: /etc/kernel/preinst.d/dietpi-initramfs_cleanup: Syntax error:
"if" unexpected (expecting "do")
run-parts: /etc/kernel/preinst.d/dietpi-initramfs_cleanup exited with return code 2
dpkg: error processing archive /tmp/apt-dpkg-install-tAAtKl/09-linux-image-current-sunxi_21.08.2_armhf.deb
(--unpack):
```
</details>

#### Extra details
- https://github.com/MichaIng/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh#L901

**Comment by Megum1n** [comment]
Sorry, it fixed already. Script on my device doesn't have semicolon before `do`.

**Comment by Joulinar** [comment]
Image is working fine for the guy on the forum.
