### ISSUE TITLE
Home Assistant using generic camera configuration is missing dependencies (glibc 2.28/2.29.) 

### ISSUE THREAD

**Issue by mookman288** [MichaIng/DietPi#4872]
#### Required Information
- DietPi version | `7.7.3`
- Distro version | `buster 1`
- Kernel version | `Linux DPH 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux`
- SBC model | `RPi 2 Model B (armv7l)`
- Power supply used | `5V 1A Generic USB`
- SDcard used | `Samsung EVO Select`

#### Additional Information (if applicable)
- Software title | Home Assistant
- Was the software title installed freshly or updated/migrated? Freshly installed
- Can this issue be replicated on a fresh installation of DietPi? I do not know. 

#### Steps to reproduce

1. I had issues with Python when installing Home Assistant. 
2. I upgraded to 7.7.3, and those issues were corrected. 
3. I successfully added an RTSP stream to Home Assistant according to their documentation. 
4. The RTSP stream fails in the UI and defaults to still images due to libturbojpeg error. 
5. I attempted to resolve the issues myself (libturbojpeg) with the following: `apt install -y libturbojpeg0 libatlas-base-dev libhdf5-dev libatlas-base-dev libjasper-dev libqtgui4 libqt4-test libilmbase-dev libopenexr-dev libgstreamer1.0-dev libavcodec-dev libavformat-dev libswscale-dev libwebp-dev`
6. The RTSP stream continues to fail with a new error (glibc.) 

#### Expected behaviour

The RTSP stream should be running in Home Assistant.

#### Actual behaviour

The RTSP stream fails in the UI and defaults to still images. This only triggers the following error log when the UI is loaded.

The following errors are being reported via journalctl -f: 

```
Oct 19 14:01:01 DPH homeassistant[29943]: 2021-10-19 14:01:01 ERROR (MainThread) [homeassistant.components.camera.img_util] Error loading libturbojpeg; Cameras may impact HomeKit performance
Oct 19 14:01:01 DPH homeassistant[29943]: Traceback (most recent call last):
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
Oct 19 14:01:01 DPH homeassistant[29943]:     from . import multiarray
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
Oct 19 14:01:01 DPH homeassistant[29943]:     from . import overrides
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
```

```
Oct 19 14:01:01 DPH homeassistant[29943]:     from numpy.core._multiarray_umath import (
Oct 19 14:01:01 DPH homeassistant[29943]: ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)
Oct 19 14:01:01 DPH homeassistant[29943]: During handling of the above exception, another exception occurred:
Oct 19 14:01:01 DPH homeassistant[29943]: Traceback (most recent call last):
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/home/homeassistant/.pyenv/versions/3.9.7/lib/python3.9/site-packages/homeassistant/components/camera/img_util.py", line 94, in __init__
Oct 19 14:01:01 DPH homeassistant[29943]:     from turbojpeg import TurboJPEG  # pylint: disable=import-outside-toplevel
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/turbojpeg.py", line 31, in <module>
Oct 19 14:01:01 DPH homeassistant[29943]:     import numpy as np
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/__init__.py", line 150, in <module>
Oct 19 14:01:01 DPH homeassistant[29943]:     from . import core
Oct 19 14:01:01 DPH homeassistant[29943]:   File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
Oct 19 14:01:01 DPH homeassistant[29943]:     raise ImportError(msg)
Oct 19 14:01:01 DPH homeassistant[29943]: ImportError:
```

```
Oct 19 14:01:01 DPH homeassistant[29943]:   * The Python version is: Python3.9 from "/home/homeassistant/.pyenv/versions/3.9.7/bin/python3.9"
Oct 19 14:01:01 DPH homeassistant[29943]:   * The NumPy version is: "1.21.2"
```

```
Oct 19 14:01:01 DPH homeassistant[29943]: Original error was: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)
```

#### Extra details

When trying to figure out libturbojpeg: 

```
Package libturbojpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libturbojpeg0
```

```
libturbojpeg0 is already the newest version (1:1.5.2-2+deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

According to this thread, we are stuck on 2.28 glibc due to buster (oldstable):

https://dietpi.com/phpbb/viewtopic.php?t=8165

https://packages.debian.org/search?suite=all&searchon=names&keywords=glibc

According to this post (and the errors above) it appears that numpy needs 2.29:

https://www.reddit.com/r/linuxquestions/comments/ovfgaf/glibc_229_required_version_228_installed/

Trying to downgrade numpy is not possible, because pip3 is not accessible from root:

```
-bash: pip3: command not found
```

```
-bash: pip: command not found
```

This post provides a tentative solution, but also requires access to pip: 

https://community.home-assistant.io/t/trend-sensor-reboot-ok-vs-restart-problem/329426/3

Other parts of Home Assistant appear to be working fine, but I haven't really poked around too much.

**Comment by MichaIng** [comment]
Home Assistant was completely fresh installed on the system, or was `/mnt/dietpi_userdata/homeassistant` copied from a different one?
```
Oct 19 14:01:01 DPH homeassistant[29943]: ImportError: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-arm-linux-gnueabihf.so)
```
It looks for glibc 2.29 but Debian Buster ships glibc 2.28, Bullseye v2.31, so 2.29 doesn't fit to any Debian version. [pihwheels](https://piwheels.org/project/numpy/) ships pre-compiled numpy v1.21.2 for Buster and Bullseye, and has a green tick, so generally it seems to work 🤔.

**Comment by mookman288** [comment]
After ~4 hours of it upgrading, it has successfully finished. Trying to run Home Assistant has the following error crop up:

```
homeassistant[636]: ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

I did the following to resolve:

```
ln -s /usr/lib/arm-linux-gnueabihf/libffi.so.7 /usr/lib/arm-linux-gnueabihf/libffi.so.6
```

Now it's working, but throws this error:

```
 The system could not validate that the sqlite3 database at //mnt/dietpi_userdata/homeassistant/home-assistant_v2.db was shutdown cleanly
 ```
 
 Restarting seems to have dealt with that. 
 
 rtsp stream is now throwing this error (no more 2.29, something new:)
 
```
 ERROR (MainThread) [homeassistant.setup] Error during setup of component stream
```

and

```
ImportError: libavdevice.so.58: cannot open shared object file
```

So doing another symlink:

```
ln -s /usr/lib/arm-linux-gnueabihf/libavcodec.so.58 /usr/lib/arm-linux-gnueabihf/libavcodec.so.57
```

Now this error:

```
ImportError: libavdevice.so.58: cannot open shared object file: No such file or directory
```

At this point, all Internet posts point to installing opencv, but I'm gonna try `apt install libavdevice-dev`. That's where I'll leave it tonight.

**Comment by Joulinar** [comment]
Maybe you should try to remove the symbolic links created to see how it is going 🤔
