### ISSUE TITLE
DietPi-Software | CrowdSec

### ISSUE THREAD

**Issue by klausagnoletti** [MichaIng/DietPi#4873]
#### Formal software information
- Software title | CrowdSec
- Short description | CrowdSec is free and open souce, crowd sourced threat intelligence. In it's essense it's a moderne, more advanced version of Fail2Ban - but so much more.
- Official URL (if available) | https://crowdsec.net/
- GitHub URL (if available) | https://github.com/crowdsecurity/crowdsec
- (Official) install documentation | https://doc.crowdsec.net/docs/getting_started/install_crowdsec (rpi installation is at the bottom)

#### Are there similar/alternative software titles available with DietPi-Software?
- Fail2Ban

#### What makes your requested software better than the above solutions, if available?
(Disclaimer: I am head of community at CrowdSec and an avid user myself. I wouldn't work there if I didn't think the software was great. Just as I think DietPi is damn cool btw)
- First of all, CrowdSec is open source and free crowd sourced threat intelligence. This means that all installations of CrowdSec agent by default sends (anonymized) intelligence that it has collected by parsing logs to a collective database. This colletive database of bad ip is shared with all other CrowdSec installs.
- Secondly, while CrowdSec was originally meant as a modern version of Fail2Ban and it makes sense to compare with f2b when trying to explain what CrowdSec is, it actually doesn't do CrowdSec any justice since it's way more advanced (and undergoing a lot of improvements really fast). First of all it's modular. Everyone can contribute datasources to get more data into CrowdSec (right now data from files, cloudtrail, syslogd, journald is supported). Once data is in CrowdSec everything's an object which is assessed via very flexible scenarios. This means that on top of all the usual stuff f2b can do, CrowdSec can be used to fight DDoS on L7 by determining what normal usage of a website is (via scenarios). So whenever CrowdSec determines non-normal usage (via e.g. leaky bucket algoritm) it will block traffic via 'bouncers'. There's bouncers for nginx, wordpress, php in general, cloudflare, pf, iptables, nftables and more. And blocking doesn't nescessarily mean a hard block; On L7 blockings users can be forced through a CAPTCHA by country, ASN or ip. In this way no real users are denied access.
- Thirdly, there's support for notification via various plugins to Splunk, Slack and a general HTTP plugin that can be used to send notifications to Elastic, Teams, Telegram and many others. CrowdSec is written in Go so plugins can also be contributed.
- Fourthly, there's a few posibilites for observability via prometheus and a fancy web console (hosted by CrowdSec but free to use).
- As if that wasn't enough I recently did a talk at ShellCon that goes throught the architecture and talks more about the current and future possibilities: http://www.youtube.com/watch?v=vZgl00UcATw&t=138m26s

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
- There are no precompiled binaries available for the various arm platform. CrowdSec compiles fine, so no problem on that side. Official installation instructions tells you how to compile the software yourself. That sucks. 

#### Can you provide the installation steps that you would suggest DietPi-Software to do?
1. Basically what the installation on Debian does; installs agent, bouncer, auto detects services that can be protected out of the box and enables that. 
2. Detects whether f2b is already installed and makes sure there's no conflicts.

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
I am not a developer, so sadly no. But I would not rule out that we would pay someone to do the initial work and maintaining. For instance via financially supporting DietPi. Shoot me a mail at klaus@crowdsec.net so we can discuss the possibilities.

#### Vote for this software on FeatHub: https://feathub.com/MichaIng/DietPi/
I really wanted to do this but I wasn't able to login: "We're sorry, but something went wrong.".

**Comment by klausagnoletti** [comment]
Hi again

The crowdsec package in bullseye is just the agent (which doesn't block anything). Also it's rather old and probably won't work with many bouncers anyway. Bouncers block traffic so without them it's not really much fun. So I wouldn't recommend anyone not using CrowdSec's own builds :)

Thanks for your building comments. If you run in to issues let me know and I can set you up with a developer who can help you out. 

Thanks for looking into it. Highly appreciated :-)

**Comment by MichaIng** [comment]
> The crowdsec package in bullseye is just the agent (which doesn't block anything)

Ah okay, good to know. Probably we can provide an armv6hf package which matches the one provided at `packagecloud.io` and is then compatible with ARMv6 and ARMv7 systems.

**Comment by klausagnoletti** [comment]
I don't want to sound like an impatient ass here but do you have any idea about the time horizon for this? Also, can we contribute part of a developer for this? Would that make sense?

**Comment by MichaIng** [comment]
Let me move this to discussions, which we use now as new voting system, since FeatHub is broken.
