### ISSUE TITLE
DietPi 7.7.3 mkinitramfs problem

### ISSUE THREAD

**Issue by andreicaba** [MichaIng/DietPi#4877]
Hello

  Just wanted to tell you of an issue that I met while developing a product on top of your DietPi images (on top of the Raspberry Pi 4B hardware).
  We were working on top of DietPi_RPi-ARMv6-Buster.img (hash: MD5 af1fb54f9ca4e9b264ee26169108ffdb) - and everything was fine and dandy :)
  A part of our product required us to run some services inside the initramfs environment - so we used initramfs tools to create&config this initramfs environment ( mkinitramfs -o /boot/initrd ). We also managed to get the WiFi (and some other stuff) working great inside this environment (WiFi was enabled from the first install using dietpi.txt and dietpi-wifi.txt). This was going on great so far for the version mentioned above.
  Then, as new DietPi images appeared, we kept trying them on. While if upgrading from the image with the hash mentioned above - it kept working flawlessly, if we tried creating the initrd image directly from any of the new images (Bullseye or Buster), the mkinitramfs was creating the initrd (with warnings about some network drivers) - but the Raspberry Pi was unreachable over WiFi (we didn't debug it fully - as the same OS was working fine and dandy if we upgraded from the image mentioned above).
  Also... might be better to open a new issue for this, but... we couldn't install the fkms driver in the 64 bit versions of DietPi - and so we weren't able to run vlc properly in "no X server" mode (but in the 32 bit version it was working great). But because this could also happen because VLC itself maybe didn't finish it's 64 bit version with addressing the right fkms driver, we dropped that and right now we are using only 32 bit versions... :)
  If necessarily - we can do some "debugging" if you think it's worth it :)

Have a great day there - and thanks for your great contribution to all the SBC users!... 👍 :)

**Comment by MichaIng** [comment]
An issue may have been a missing or not yet fully fledged WiFi firmware package from the RPi repo: https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/?C=M;O=D
I remember there was none on the Bullseye suite a while ago and I needed to manually add some firmware files from the package of the Buster suite to get RPi Zero WiFi working.

I'll update the images after DietPi v7.8 release, which may fix it. I'll mark this as closed for now. If someone tests the new image when it is up and faces similar issues, we can reopen to debug.
