### ISSUE TITLE
DietPi Update Failed

### ISSUE THREAD

**Issue by paeore** [MichaIng/DietPi#4878]
I used `dietpi-update `. The installation did not work or at least failed to complete. Tried rebooting. Now Pi will not boot and am unable to ssh in.

I really do not wish to rebuild the system again and am unable to access the system to produce any logs.

What should I do? Please help.

paeore

**Comment by Joulinar** [comment]
First you have could filled the template we have created on the `issues`. There are there for purpose and not just for fun. This could help to avoid back and force questions. Some more system details would be helpful. Next question, do you have a screen you could attach? Otherwise it will be quite impossible to see what the issue is.

**Comment by paeore** [comment]
Well that does sound promising thanks @Joulinar 

I'll wait patiently to see if @MichaIng can assist 🤞

**Comment by MichaIng** [comment]
> how would I find out if actual client already has the OpenVPN client configuration?

If it can connect? 😄
Either you did manually install it on the client and can successfully connect to your OpenVPN server, or not. If you can, I'd remove the configuration from the server. The private key is meant to be known only by the client, not by the server.

**Comment by Joulinar** [comment]
Can you share the content?

**Comment by Joulinar** [comment]
Ok basically some of DietPi scripts. @MichaIng  Shouldn't be an issue to have them removed. Correct?

**Comment by MichaIng** [comment]
Yes you can remove them. In every case I saw such, those scripts were still or again present. Often those FSCK* files are created as a backups only, I guess, while the actual files were repaired successfully.

**Comment by MichaIng** [comment]
> aarch64

This confirms it. You can also verify this by checking the APT/userland architecture:
```sh
dpkg --print-architecture
```
which should show `arm64`.

**Comment by MichaIng** [comment]
Can you show:
```sh
dpkg -l | grep -E 'armhf|arm64'
```
Did you touch `/boot/config.txt` manually? Generally it doesn't make sense and causes issues when loading a 32-bit userland with a 64-bit kernel.
You can load the 32-bit kernel via:
```sh
sed -i '/arm_64bit=1/d' /boot/config.txt
reboot
```
The question is how that setting found it's way into the configuration.

**Comment by Joulinar** [comment]
This command will remove the flag to force 64bit. Somehow it seems you had set this before. But it's not a real 64bit system. It just force the kernel into 64bit mode while the userland and all packages stay on 32bit. Something not really recommended

**Comment by paeore** [comment]
Also, just as an FYI, I had to run `sudo dpkg --configure -a` in order for the `dietpi-update` to complete successfully.

But just a big thanks again for your help today @MichaIng & @Joulinar. I've learned alot just speaking with you both! 🙇‍♂️

paeore
