### ISSUE TITLE
DietPi-Software | Tailscale

### ISSUE THREAD

**Issue by cocoflan** [MichaIng/DietPi#4893]
A secure network that just works

Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere.

**What is Tailscale?**

Tailscale is a VPN service that makes the devices and applications you own accessible anywhere in the world, securely and effortlessly. It enables encrypted point-to-point connections using the open source WireGuard protocol, which means only devices on your private network can communicate with each other.
The Benefits

Building on top of a secure network fabric, Tailscale offers speed, stability, and simplicity over traditional VPNs.

Tailscale is fast and reliable. Unlike traditional VPNs, which tunnel all network traffic through a central gateway server, Tailscale creates a peer-to-peer mesh network (called a tailnet): 

https://github.com/tailscale/tailscale
https://tailscale.com/

**Comment by Joulinar** [comment]
Many thanks for your request. I moved it to discussions where we start to collect software requests now. Users can vote here, which is one benefit, since FeatHub is sadly down, respectively unmaintained and cannot be used anymore.
