### ISSUE TITLE
Vulkan support for ARM64 & Mali G31 GPU

### ISSUE THREAD

**Issue by MDAR** [MichaIng/DietPi#4896]
Hi, this isn't massively important, I am more looking for advice.

I'm trying to install this NDI viewer application on an ODroid C4 with DietPi.

https://github.com/keijiro/Nsm

Apparently, it runs on Arm64 with Vulkan support. 

(I didn't know what Vulkan was, until quickly reading this www.linuxadictos.com/en/how-to-install-vulkan-api-support-on-linux.html )

Apparently, there are common versions of Vulkan available for the Intel and Nvidia GPUs, but I've also found a version that supports Mali GPU and specifically the Mali G31 chip that is used on the ODroid C4

https://www.hardkernel.com/shop/odroid-c4/

> The main CPU of the ODROID-C4 is built with a quad-core Cortex-A55 cluster with a new generation Mali-G31 GPU

After a little web searching, I found this

https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/user-space

It's at this stage that I'm getting out of my depth (again)

Before I go down a dark rabbit hole, would one of you kind people cast your eye over it and let me know if you think it's possible to load the Mali drivers to get Vulkan support on an ODroid C4, so I can try this NDI viewer?

(I really want NDI-HX support in the viewer, but right now I'd be happy with any NDI support on Arm64)

Many thanks,

Stuart

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
