### ISSUE TITLE
update to 7.7.3 from 7.6.2

### ISSUE THREAD

**Issue by danzigrules** [MichaIng/DietPi#4898]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version` G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`  bullseye 1
- Kernel version | `uname -a` `Linux DietPi 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l GNU/Linux`

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)  RPi 3 Model B (armv7l)
- Power supply used | (EG: 5V 1A RAVpower) what came with the Pi
- SDcard used | (EG: SanDisk ultra) sandisk 64G

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?
  15cec181-288e-4471-a04e-61c75ab0f7de
- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. dietpi-update
2. ...

#### Expected behaviour

- ...upgrade to 7.7.3

#### Actual behaviour
dkpg error

#### Extra details

- ...

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen when required.
