### ISSUE TITLE
DNS resolution broken in Docker

### ISSUE THREAD

**Issue by blackthorne** [MichaIng/DietPi#4904]
#### Required Information
- DietPi version
```
G_DIETPI_VERSION_SUB=7
G_DIETPI_VERSION_RC=3
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied' 
```
- Distro version | buster
- Kernel version | `Linux DietPi 3.16.85+ #1 SMP PREEMPT Tue Jun 30 19:02:35 CEST 2020 aarch64 GNU/Linux`
- SBC model | Odroid C2 (aarch64)
- Power supply used | 5V 1A
- SDcard used | None (using eMMC)

#### Additional Information
- Software title | Docker-compose
- Fresh install
- Issue can be reproduced on fresh installation
- Bug report ID | e437aebf-8ec6-4464-a656-c2f0dfa011d6

#### Steps to reproduce

1. 
```
# cat > docker-compose.yml << EOF
version: '3'

services:
  my_service_1:
    container_name: container1
    hostname: container1
    image: alpine
    entrypoint: ["sh", "-c", "sleep 2073600"]
  
  my_service_2:
    container_name: container2
    hostname: container2
    image: alpine
    entrypoint: ["sh", "-c", "sleep 2073600"]
EOF
``` 
2. 
```
# docker-compose up -d
Creating network "test_default" with the default driver
Creating container2 ... done
Creating container1 ... done
```
3. 
```
# docker exec -it container1 sh
/ # ping container2
ping: bad address 'container2'
```

#### Expected behaviour
This ping should work, containers within the same docker network should be able to find each other by their DNS name but as you can see they are not. If I was to try to ping container2's IP address (as opposed to its name), it would work, so they are definitely on the same network.

#### Actual behaviour
`ping: bad address 'container2'`

#### Extra details
I found in docker logs some errors with iptables that seem related to this:
```
Oct 27 00:04:32 DietPi dockerd[611]: time="2021-10-27T00:04:32+01:00" level=error msg="set up rule failed, [-t nat -I DOCKER_OUTPUT -d 127.0.0.11 -p udp --dport 53 -j DNAT --to-destination 127.0.0.11:45256]"
Oct 27 00:04:33 DietPi dockerd[611]: time="2021-10-27T00:04:33+01:00" level=error msg="set up rule failed, [-t nat -I DOCKER_POSTROUTING -s 127.0.0.11 -p udp --sport 45256 -j SNAT --to-source :53]"
Oct 27 00:04:33 DietPi dockerd[611]: time="2021-10-27T00:04:33+01:00" level=error msg="set up rule failed, [-t nat -I DOCKER_OUTPUT -d 127.0.0.11 -p tcp --dport 53 -j DNAT --to-destination 127.0.0.11:56377]"
Oct 27 00:04:33 DietPi dockerd[611]: time="2021-10-27T00:04:33+01:00" level=error msg="set up rule failed, [-t nat -I DOCKER_POSTROUTING -s 127.0.0.11 -p tcp --sport 56377 -j SNAT --to-source :53]"
```

and from dmesg:
```
[48630.708613] x_tables: ip_tables: DNAT target: used from hooks FORWARD, but only usable from PREROUTING/OUTPUT
[48630.722739] x_tables: ip_tables: SNAT target: used from hooks FORWARD, but only usable from INPUT/POSTROUTING
[48630.736216] x_tables: ip_tables: DNAT target: used from hooks FORWARD, but only usable from PREROUTING/OUTPUT
[48630.749470] x_tables: ip_tables: SNAT target: used from hooks FORWARD, but only usable from INPUT/POSTROUTING
```

I don't know why these netfilter hooks are failing (custom kernel?) but seems to be at the root cause of this problem.

**Comment by blackthorne** [comment]
I did the opposite thing, I installed a minimal version of Armbian and manually run code from your build scripts to “turn it to DietPI” because I like your OS philosophy. Obviously, this is not a proper solution just something that allows me to get through this problem. One of the things I have noticed about Armbian is that they build nightly versions of the kernel so as soon as I hit `apt upgrage` I saw my kernel being updated to v5.3.14 working flawlessly. I am no one to say but seems quite valuable to have this build system as a base to DietPi in a more systematic approach as it seems to give you working and up to date kernels for many other ARM SBCs.

**Comment by MichaIng** [comment]
We use the Armbian kernel as well for most other SBCs, but not for Odroids currently, which use the official Hardkernel kernel sources. But yeah they are stuck on an old version.

For XU4 there is Linux 5.4 available, but not for Odroid C2, which was also stopped being produces this summer, and stock sold out.

Armbian should btw offer Linux 5.10 as stable version and 5.14 as edge version, so not sure how you land on 5.3?

I'm considering to move to Armbian kernel with all Odroids as well. I did already some compatibility steps in `dietpi-software` and with the next version `dietpi-drive_manager` (rootfs transfer, which doesn't make sense this way on single partition images). But more needs to be done in `dietpi-config` to not offer broken options on Odroids, when a dedicated boot partition and `boot.ini` with specific entries is expected.

**Comment by blackthorne** [comment]
@MichaIng sorry that was a typo, the `apt upgrade` got me to v5.14.11 . 

The odroid c2 was made obsolete but remains quite popular and used. In a way, I suspect these older devices are the ones where people find the DietPi and its leanness a very attractive option. 

thank you for sharing that.

**Comment by MichaIng** [comment]
Yep, the C2 is one of the most used SBCs reported via `dietpi-survey`, so I'm not saying that we shouldn't take care, just that we shouldn't expect any future development from Hardkernel. Moving to Armbian, respectively upstream kernel, hence seems a reasonable step earlier or later.

One of the core "blockers" was hardware acceleration for GUI and multi media applications, especially Kodi. Would you be open to do some testing/comparison, i.e. with our current Linux 3.16 Buster image and `kodi-odroid` package + Mali driver/library blob, compared to `kodi` package from Debian Bullseye with Armbian/upstream Linux and Mesa drivers.

**Comment by blackthorne** [comment]
happy to help. Do you have a particular benchmark in mind?

**Comment by MichaIng** [comment]
Not sure whether Kodi has a native FPS display feature? Otherwise with a proper high resolution video a the subjective feeling whether there is a notable difference on how fluent it is played and on an SSH screen `htop` can show the CPU usage during playback.

**Comment by blackthorne** [comment]
it does, I can use that. I used Libreelec for Kodi for a long time, I don't even know what it uses but performance-wise it was great, it would boot faster than my smart TV.

**Comment by MichaIng** [comment]
Our Odroid C2 image is now using the Armbian kernel, hence issue solved that way.
