### ISSUE TITLE
update DietPi from v7.1.2 to v7.7.3

### ISSUE THREAD

**Issue by juarezpedra** [MichaIng/DietPi#4905]
#### Required Information
- DietPi version | G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=1
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | stretch 1

- Kernel version | `Linux bob 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`

- SBC model | RPi 3 Model B+ (armv7l)

- Power supply used | phone charger
- SDcard used | SanDisk ultra 32Gb

#### Details:
- Date           | Tue Oct 26 21:59:16 -03 2021
- DietPi version | v7.1.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 3 Model B+ (armv7l) (ID=3)
- Kernel version | `Linux bob 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`
- Distro         | stretch (ID=4,RASPBIAN=1)
- Command        | apt-get -o Acquire::AllowReleaseInfoChange::Suite=true -q update
- Exit code      | 100
- Software title | DietPi-Pre-patches
#### Steps to reproduce:

1. run 'sudo dietpi-update'

#### Expected behaviour:

- update the system
#### Actual behaviour:

- system was not updated
#### Extra details:

- ...
#### Additional logs:
```
Hit:1 http://mirror.ufam.edu.br/raspbian/raspbian stretch InRelease
Ign:2 https://download.webmin.com/download/repository sarge InRelease
Hit:3 https://packages.sury.org/php stretch InRelease
Hit:4 https://archive.raspberrypi.org/debian stretch InRelease
Hit:5 https://downloads.plex.tv/repo/deb public InRelease
Err:6 https://download.webmin.com/download/repository sarge Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists...
E: The repository 'https://download.webmin.com/download/repository sarge Release' does no longer have a Release file.
```

**Comment by juarezpedra** [comment]
> 
> 
> Hi,
> 
> this is a know issue with SSL certificates for Webmin. Pls could you try following to switch to `http`
> 
> ```
> sed -i 's/https:/http:/' /etc/apt/sources.list.d/webmin.list
> apt update
> apt upgrade
> ```

Works! Thanks a lot!!

**Comment by MichaIng** [comment]
Okay great. I'll mark this issue as closed then.
