### ISSUE TITLE
DietPi-Config | Add Stress Test

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#492]
As per @zone22's suggestion: https://github.com/Fourdee/DietPi/issues/489

Tests for stability. Must test:
- CPU
- Filesystem IO
- RAM

**Comment by Fourdee** [comment]
`dietpi-config` > tools > Stress Test

```
stress -c $cores -i 2 -m $cores --vm-bytes "$memory_per_thread"M -d 1 -t "$duration"s 
```

![image](https://cloud.githubusercontent.com/assets/7077026/18230739/0fae42d0-729d-11e6-80b1-4bd603d1e3f0.png)

And it works, just killed my overclocked RPi 3 lol

**Comment by k-plan** [comment]
@Fourdee 

nice work! 😄  👍 

_**Testing result on NanoPi NEO:**_

![160904-0006](https://cloud.githubusercontent.com/assets/17237601/18231023/47be5592-72ad-11e6-8c32-1713a9336cf6.gif)

![160904-0005](https://cloud.githubusercontent.com/assets/17237601/18231027/525e58b2-72ad-11e6-8b4c-3c16017b3cd9.gif)

![160904-0003](https://cloud.githubusercontent.com/assets/17237601/18231028/5e1c6536-72ad-11e6-8e38-da706d22648a.gif)

![160904-0007](https://cloud.githubusercontent.com/assets/17237601/18231056/e09e754e-72ad-11e6-8a50-1a9c6a85ad87.gif)
