### ISSUE TITLE
VSCode as Codeserver

### ISSUE THREAD

**Issue by Gill-Bates** [MichaIng/DietPi#4939]
Hey there,

I would like to suggest Code Server for Dietpi. I have it successfully running:

https://github.com/cdr/code-server

![04C3E132-96A2-4EC1-A2F6-786C25A5C081](https://user-images.githubusercontent.com/25774289/140643469-3802e9b3-bbf7-4744-b1cd-5a9bb5781348.jpeg)

**Comment by Joulinar** [comment]
We are moving to GitHub discussion to collect software and image request in future. Therefore `issue` will be closed and reopen as `discussion.`
