### ISSUE TITLE
DietPi-Software | UrBackup Server and Client

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#494]
The Server has Arm and Arm64 builds

UrBackup is an easy to setup Open Source client/server backup system, that through a combination of image and file backups accomplishes both data safety and a fast restoration time.

File and image backups are made while the system is running without interrupting current processes.

UrBackup also continuously watches folders you want backed up in order to quickly find differences to previous backups. Because of that, incremental file backups are really fast.

Your files can be restored through the web interface, via the client or the Windows Explorer while the backups of drive volumes can be restored with a bootable CD or USB-Stick (bare metal restore).

A web interface makes setting up your own backup server really easy. For a quick impression please look at the screenshots here. 

https://www.urbackup.org/

**Comment by Fourdee** [comment]
@Zone22 
Looks good :+1:  i'll take a look in v131.

**Comment by Fourdee** [comment]
notes: 
compile needed for ARM64 and armv6

**Comment by ghost** [comment]
Just a quick note the client needs compiling there are ARM64 and armv7 server packages

**Comment by Fourdee** [comment]
Was about to start testing the server:
![image](https://cloud.githubusercontent.com/assets/7077026/18608159/b3688200-7cd9-11e6-8ba4-cf66dfcffcf1.png)

Edit:
non-MSI installer is fine: https://hndl.urbackup.org/Client/2.0.32/UrBackup%20Client%202.0.32.exe
Clearly "Only for up-to-date Windows" doesn't include Windows 10?!?!?

**Comment by Fourdee** [comment]
Annoyances:
- You cant stop backups on the client, with the client program
- Clicking the Stop button on a active backup, most of the time, doesn't stop the backup
- Clients ignore the server settings of, `disabled auto file and image backups`. Client does what it wants.
- Client always wants to resume, runs indexing (10+ mins), then checks if the server activity actually exists. Then stops.
- Various Client hangs, requires urbackup service restart.

These programs are riddled with bugs.

**Comment by k-plan** [comment]
@Fourdee 

Yes, by my tests as well, server looks good. But only the look of web interface, can't really test, because ...

Client for Windows (_yes, it's not my world_), testing with Win 7 64 Bit,  is crap! 
Sorry,  investing no more time into this. 👎

**Comment by Fourdee** [comment]
Server:
- ARMv7+ / AMD64 = Deb
- ARM64 = Sourcebuild | Unable to find a config setting in `/etc/default/urbackupsrv` or another config location for backup directory (set to `C:\` by default)

**Comment by Fourdee** [comment]
To Do:
- 🈴 Client? No. Has its own installation script. Will link to client installs in docs.

```
TF=`mktemp` && wget "https://hndl.urbackup.org/Client/2.0.32/UrBackup%20Client%20Linux%202.0.32.sh" -O $TF && sh $TF; rm $TF
```
- 🈯 Uninstall code
- 🈯 Online Docs: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=65#p65
- 🈺 Would be nice: ARM64. Find a way to set default backup directory | No method found.

**Comment by ghost** [comment]
@Fourdee @k-plan 
Well I'm open to an alternatives. 

The following are open source multiplatform solutions but further investigation is needed for arm support
[Bacula](http://blog.bacula.org/what-is-bacula/)
[Backuppc](http://backuppc.sourceforge.net/)
[Amanda](http://www.zmanda.com/amanda-enterprise-edition.html)

**Comment by Fourdee** [comment]
@Zone22 

> Well I'm open to an alternatives.
> The following are open source multiplatform solutions but further investigation is needed for arm support

They sound good, but they all need testing to find the "best one". If you can pick one alternative to investigate, create a ticket and we will take a look at adding it in the future.

**Comment by Fourdee** [comment]
Marking this as closed: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=65#p65

**Comment by ghost** [comment]
@k-plan I see your frustration and also there updating the client soon. Take a look at their blog!
http://blog.urbackup.org/
