### ISSUE TITLE
DietPi-Software | OMV Open Media Vault

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#495]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=561&p=2457#p2457
> 
> https://github.com/Fourdee/DietPi/issues/455#issuecomment-238925807

_Please note:_
https://en.wikipedia.org/wiki/OpenMediaVault#Release_history
- _Current openmediavault v2.2.6 (Stone Burner) only  support Debian 7 (Wheezy)_ 
- _Next version openmediavault v3.x (Erasmus) will support Debian 8 (Jessie), but it is still in beta for now ..._

**Comment by Fourdee** [comment]
Erasmus binaries: http://packages.openmediavault.org/public/dists/erasmus/main/

> The package repository can be accessed via http://packages.openmediavault.org/public. The repository is signed with PGP key ID: 2EF35D13, Fingerprint 0F6B CC17 C26B FADC 27F2 2100 7E7A 6C59 2EF3 5D13.

**Comment by k-plan** [comment]
New request:

http://dietpi.com/phpbb/viewtopic.php?f=12&t=1040

**Comment by Fourdee** [comment]
Requires:
- ProFTPD
- Samba Server
- Nginx + PHP5-fpm | Listed as dep for install 👎, no webserver choice:

```
echo "deb http://packages.openmediavault.org/public erasmus main" > /etc/apt/sources.list.d/openmediavault.list
apt-get update
apt-get install -y --force-yes openmediavault-keyring 

apt-get update
apt-get install -y openmediavault postfix # Must automate postfix whiptail, "no configuration" option?
omv-initsystem
```

```
root@DietPi:~# debconf-get-selections | grep postfix
postfix postfix/tlsmgr_upgrade_warning  boolean
postfix postfix/bad_recipient_delimiter error
postfix postfix/root_address    string
postfix postfix/mydomain_warning        boolean
postfix postfix/protocols       select
postfix postfix/relayhost       string
postfix postfix/procmail        boolean
postfix postfix/retry_upgrade_warning   boolean
postfix postfix/chattr  boolean false
postfix postfix/destinations    string
postfix postfix/mailname        string  /etc/mailname
# Install postfix despite an unsupported kernel?
postfix postfix/kernel_version_warning  boolean
postfix postfix/sqlite_warning  boolean
postfix postfix/rfc1035_violation       boolean false
postfix postfix/main_mailer_type        select  No configuration
postfix postfix/mynetworks      string  127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
postfix postfix/mailbox_limit   string  0
postfix postfix/relay_restrictions_warning      boolean
postfix postfix/not_configured  error
postfix postfix/recipient_delim string  +
```

```
root@DietPi:~# debconf-get-selections | grep openmediavault
openmediavault  openmediavault/run-initsystem   note
```

```
http://192.168.0.100
User: admin
Password: openmediavault
```

![image](https://cloud.githubusercontent.com/assets/7077026/21718098/ee1360fc-d40c-11e6-920c-9086f9a52057.png)

**Comment by Fourdee** [comment]
Ok nearly done:
- 🈯️ needs some testing. Done tests in regards to the web interface.
- 🈯️ online doc http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=4859#p4859

**Comment by Fourdee** [comment]
Marking as completed. 
Although, as OMV can take control of some DietPi features, until our users are able to test all areas of OMV's features, we won't know for sure if OMV, and all its plugins are fully compatible on a DietPi system.
