### ISSUE TITLE
vscode remote ssh not work

### ISSUE THREAD

**Issue by K0rkunc** [MichaIng/DietPi#4963]
remote vscode ssh not connect why ?  how to compile remote

**Comment by MichaIng** [comment]
Can you please be a bit more detailed? Is this what you are trying to achieve? https://code.visualstudio.com/docs/remote/ssh-tutorial
If so, does it show any error messages?

Can you connect with an SSH client outside of VSCode, e.g. with PuTTY?

Can you ping the DietPi system? If so, does the SSH server run on it?
```sh
ss -tlpn
```

**Comment by MichaIng** [comment]
Marking this as closed due to outstanding reply. Feel free to reopen when required.
