### ISSUE TITLE
DietPi-Config | Add RPi OpenGL driver

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#497]
As title. OpenGL support.

**Comment by Fourdee** [comment]
available in:
dietpi-config > display > resolution

tested with `glxgears`: 60fps woop woop! 24fps on fb

tested with `/usr/games/neverball`
`apt-get install neverball`

**Comment by stogoh** [comment]
How can I enable/install the OpenGL driver for the Tinkerboard? The setting `Dietpi-Config > Display > Resolution` is not available.

**Comment by Fourdee** [comment]
@Stogoh 

OpenGL ES with midgard will be available in our updated image ETA few days, once Xserver is installed:
https://github.com/Fourdee/DietPi/issues/2296#issuecomment-443101227
