### ISSUE TITLE
Auto redirect to wifi connection for radxa zero

### ISSUE THREAD

**Issue by almirus** [MichaIng/DietPi#4975]
#### Is your feature request related to a problem? Please describe:
Radxa Zero have only wifi module and doesn't LAN
On the first launch, I have to take a few steps before setting up the wifi (which is turned off by default)

#### Describe the solution you'd like:
When checking the network (first start), immediately launch dietpi-config and start wifi connection wizard

**Comment by Joulinar** [comment]
Hi,

Basically you can activate WiFi before first initial boot already by setting the respective value inside `dietpi.txt`

**Comment by MichaIng** [comment]
You can also enter `dietpi-config` from the error prompt when network connection is checked.

**Comment by MichaIng** [comment]
Marking this as closed. Feel free to reopen when required.
