### ISSUE TITLE
DietPi-Software | Add Gitlab CE

### ISSUE THREAD

**Issue by jma-9code** [MichaIng/DietPi#500]
Hi,
May be this software package interest some peoples (me included) : 
https://about.gitlab.com/downloads/#raspberrypi2

With arm64/aarch64 support for odroid-c2 plz :)

**Comment by midwan** [comment]
This is really good! Thanks for the heads-up!

**Comment by midwan** [comment]
This is really good! Thanks for the heads-up!

**Comment by ghost** [comment]
Me 3

**Comment by bhaveshgohel** [comment]
The steps provided in the [link](https://about.gitlab.com/downloads/#raspberrypi2) is also work on Pi3. i have tested it on dietpi.

**Comment by phonicmouse** [comment]
Isn't this too heavy for a poor raspberry?

**Comment by JoshuaJones** [comment]
@phonicmouse I've ran GitLab on a Pi3 running DietPi with passable results. It can chug/lag in my experience.

**Comment by phonicmouse** [comment]
@JoshuaJones Whoa, I'll try it then.

**Comment by tatoosh** [comment]
Any news to implement gitlab into dietpi?

**Comment by Fourdee** [comment]
@tatoosh 

> Any news to implement gitlab into dietpi?

Unfortunately, not something I can take on at the moment. Hopefully one of our source contributors can pick it up.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
