### ISSUE TITLE
DietPi + AmiBerry | Use OpenSSH server by default on image

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#502]
Requires new image: https://github.com/Fourdee/DietPi/issues/474#issuecomment-245259988

**Comment by Fourdee** [comment]
#### notes:
- Updated from 4.4.16 > 4.4.19 firmware
- Added OpenSSH server flag in `dietpi.txt`
- Tested image installation :u6307: 
- Uploaded image download: http://dietpi.com/downloads/images/DietPi-AmiBerry_RPi-armv6-(Jessie).7z

@midwan

Done, new image that will install OpenSSH server by default is available: http://dietpi.com/downloads/images/DietPi-AmiBerry_RPi-armv6-(Jessie).7z

Please note, usb auto mount (https://github.com/Fourdee/DietPi/issues/501) wont be available until we release v131:

**Comment by midwan** [comment]
Awesome, thank you for the quick response!
