### ISSUE TITLE
DietPi-Software | Overseerr

### ISSUE THREAD

**Issue by HDStremmie** [MichaIng/DietPi#5049]
#### Formal software information
- Software title | 
- Short description | 
- Official URL (if available) | 
- GitHub URL (if available) | 
- (Official) install documentation | 

#### Are there similar/alternative software titles available with DietPi-Software?

- ...

#### What makes your requested software better than the above solutions, if available?

- ...

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
It could be easy installed through ‘Dietpi-Software’ (all in one place) 
It’s installed through ‘snap’ not APT
- ...

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

- ...

**Comment by Joulinar** [comment]
We are moving to GitHub discussion to collect software and image request in future. Therefore `issue` will be closed and reopen as `discussion.`
