### ISSUE TITLE
Problem with bash comand tu remote login

### ISSUE THREAD

**Issue by maury77** [MichaIng/DietPi#5055]
#### Required Information

DietPi version | 7.8.2
Distro version | bullseye
Kernel version | `Linux DietPi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux`
SBC model | RPi Zero W (armv6l)
Power supply used | (EG: 5V 3A)

Problem with bash comand tu remote login

```
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
-bash: co}plete: comando non trovato
-bash: command substitution: riga 106: errore di sintassi vicino al token non atteso "("
-bash: command substitution: riga 106: `e $1(&>/dev/nu,l'
-bash: ty: comando non trovato
-bash: /usr/share/bash-completion/bash_completion: riga 114: errore di sintassi vicino al token non atteso "-v"
-bash: /usr/share/bash-completion/bash_completion: riga 114: `  ! qnset(-v have'
```

**Comment by MichaIng** [comment]
Many thanks for your report.

Looks like at least one of the login scripts is completely malformed. Can you check them:
```sh
for i in /etc/{bashrc,profile}.d/*.{,ba}sh
do
echo "${i}:"
cat "$i"
done
```

**Comment by maury77** [comment]
for i in /etc/{bashrc,profile}.d/*.{,ba}sh
do
echo "${i}:"
cat "$i"
done
/etc/bashrc.d/dietpi-bash_completion.sh:
# shellcheck shell=sh disable=SC1091,SC2039,SC2166
# Check for interactive bash and that we haven't already been sourced.
if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then

    # Check for recent enough version of bash.
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /usr/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /usr/share/bash-completion/bash_completion
        fi
    fi

fi
/etc/bashrc.d/dietpi-node-red.sh:
alias node-red-admin='sudo -u nodered /mnt/dietpi_userdata/node-red/node_modules/.bin/node-red-admin'
/etc/bashrc.d/dietpi.bash:
#!/bin/bash
{
	#////////////////////////////////////
	# DietPi bash init script
	#
	#////////////////////////////////////
	# Created by MichaIng / micha@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /etc/bashrc.d/dietpi.bash
	# - Sourced by all interactive bash shells from: /etc/bash.bashrc
	# - Prepares shell for DietPi and runs autostarts on /dev/tty1
	#////////////////////////////////////

	# Failsafe: Never load this script in non-interactive shells, e.g. SFTP, SCP or rsync
	[[ -t 0 && $- == *'i'* ]] || return 0

	# DietPi-Globals: dietpi-* aliases, G_* functions and variables
	. /boot/dietpi/func/dietpi-globals || { echo -e '[\e[31mFAILED\e[0m] DietPi-Login | Failed to load DietPi-Globals. Skipping DietPi login scripts...'; return 1; }

	# Aliases
	# - sudo alias that allows running other aliases with "sudo": https://github.com/MichaIng/DietPi/issues/424
	alias sudo='sudo '
	# - DietPi programs
	alias dietpi-letsencrypt='/boot/dietpi/dietpi-letsencrypt'
	alias dietpi-autostart='/boot/dietpi/dietpi-autostart'
	alias dietpi-cron='/boot/dietpi/dietpi-cron'
	alias dietpi-launcher='/boot/dietpi/dietpi-launcher'
	alias dietpi-cleaner='/boot/dietpi/dietpi-cleaner'
	alias dietpi-morsecode='/boot/dietpi/dietpi-morsecode'
	alias dietpi-sync='/boot/dietpi/dietpi-sync'
	alias dietpi-backup='/boot/dietpi/dietpi-backup'
	alias dietpi-bugreport='/boot/dietpi/dietpi-bugreport'
	alias dietpi-services='/boot/dietpi/dietpi-services'
	alias dietpi-config='/boot/dietpi/dietpi-config'
	alias dietpi-software='/boot/dietpi/dietpi-software'
	alias dietpi-update='/boot/dietpi/dietpi-update'
	alias dietpi-drive_manager='/boot/dietpi/dietpi-drive_manager'
	alias dietpi-logclear='/boot/dietpi/func/dietpi-logclear'
	alias dietpi-survey='/boot/dietpi/dietpi-survey'
	alias dietpi-explorer='/boot/dietpi/dietpi-explorer'
	alias dietpi-banner='/boot/dietpi/func/dietpi-banner'
	alias dietpi-justboom='/boot/dietpi/misc/dietpi-justboom'
	alias dietpi-led_control='/boot/dietpi/dietpi-led_control'
	alias dietpi-wifidb='/boot/dietpi/func/dietpi-wifidb'
	alias dietpi-optimal_mtu='/boot/dietpi/func/dietpi-optimal_mtu'
	alias dietpi-cloudshell='/boot/dietpi/dietpi-cloudshell'
	alias dietpi-nordvpn='G_DIETPI-NOTIFY 1 "DietPi-NordVPN has been renamed to DietPi-VPN. Please use the \"dietpi-vpn\" command."'
	alias dietpi-vpn='/boot/dietpi/dietpi-vpn'
	alias dietpi-ddns='/boot/dietpi/dietpi-ddns'
	alias cpu='/boot/dietpi/dietpi-cpuinfo'
	# - Optional DietPi software aliases
	[[ -d '/mnt/dietpi_userdata/sonarr' || -d '/mnt/dietpi_userdata/radarr' || -d '/mnt/dietpi_userdata/lidarr' ]] && alias dietpi-arr_to_RAM='/boot/dietpi/misc/dietpi-arr_to_RAM'
	command -v kodi > /dev/null && alias startkodi='/boot/dietpi/misc/start_kodi'
	[[ -f '/usr/games/opentyrian/run' ]] && alias opentyrian='/usr/games/opentyrian/run'
	[[ -f '/mnt/dietpi_userdata/dxx-rebirth/run.sh' ]] && alias dxx-rebirth='/mnt/dietpi_userdata/dxx-rebirth/run.sh'
	# - 1337 moments ;)
	alias 1337='echo "Indeed, you are =)"'

	# "G_DIETPI-NOFITY -2 message" starts a process animation. If scripts fail to kill the animation, e.g. cancelled by user, terminal bash prompt has to do it as last resort.
	[[ $PROMPT_COMMAND == *'dietpi-process.pid'* ]] || PROMPT_COMMAND="[[ -w '/tmp/dietpi-process.pid' ]] && rm -f /tmp/dietpi-process.pid &> /dev/null && echo -ne '\r\e[J'; $PROMPT_COMMAND"

	# Workaround if SSH client overrides locale with "POSIX" fallback: https://github.com/MichaIng/DietPi/issues/1540#issuecomment-367066178
	if [[ ${LC_ALL:-${LANG:-POSIX}} == 'POSIX' ]]; then

		current_locale=$(sed -n '/^[[:blank:]]*AUTO_SETUP_LOCALE=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		export LC_ALL=${current_locale:=C.UTF-8} LANG=$current_locale
		unset -v current_locale

	fi

	# Workaround if SSH client sets an unsupported $TERM string: https://github.com/MichaIng/DietPi/issues/2034
	if [[ $SSH_TTY ]] && ! infocmp "$TERM" &> /dev/null; then

		TERM_old=$TERM
		export TERM='xterm'
		[[ $TERM_old == *'256'* ]] && TERM+='-256color'

		G_WHIP_MENU_ARRAY=('0' 'Ignore for now, I will change the SSH clients terminal.')
		ncurses_term=
		if ! dpkg-query -s ncurses-term &> /dev/null; then

			ncurses_term=' or install the "ncurses-term" APT packages, which enables a wider terminal support'
			G_WHIP_MENU_ARRAY+=('1' 'Install "ncurses-term" now to enable a wider terminal support.')
			G_WHIP_DEFAULT_ITEM=1

		fi

		G_PROGRAM_NAME='Unsupported SSH client terminal' G_WHIP_MENU "[WARNING] Your SSH client passed an unsupported terminal: TERM=$TERM_old\n
As a workaround we fooled the server by setting: TERM=$TERM. This is not the cleanest solution, since commands might expect colours or formats, that are not supported by the actual terminal.\n
Please change your SSH clients terminal, respectively the passed \$TERM string$ncurses_term." && (( $G_WHIP_RETURNED_VALUE )) && G_AGI ncurses-term
		unset -v TERM_old ncurses_term

	fi

	# DietPi-Login: First run setup, autostarts and login banner
	# - Prevent call if $G_DIETPI_LOGIN has been set. E.g. when shell is called as subshell of G_EXEC or dietpi-login itself, we don't want autostart programs to be launched.
	[[ $G_DIETPI_LOGIN ]] || /boot/dietpi/dietpi-login
}
/etc/profile.d/at-dbus-fix.sh:
if ! [ -e /usr/share/dbus-1/services/org.a11y.Bus.service ] ; then
   export NO_AT_BRIDGE=1
fi
/etc/profile.d/bash_completion.sh:
# shellcheck shell=sh disable=SC1091,SC2039,SC2166
# Check for interactive bash and that we haven't already been sourced.
if [ "x${BASH_VERSION-}" != x -a "x${PS1-}" != x -a "x${BASH_COMPLETION_VERSINFO-}" = x ]; then

    # Check for recent enough version of bash.
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
        [ -r "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion" ] &&
            . "${XDG_CONFIG_HOME:-$HOME/.config}/bash_completion"
        if shopt -q progcomp && [ -r /usr/share/bash-completion/bash_completion ]; then
            # Source completion code.
            . /usr/share/bash-completion/bash_completion
        fi
    fi

fi
/etc/profile.d/*.bash:
cat: '/etc/profile.d/*.bash': File o directory non esistent

**Comment by MichaIng** [comment]
Those look fine. But now I see here `/usr/share/bash-completion/bash_completion` being sourced, which is the one contained in your errors. Can you please show the output of this command:
```sh
mawk 'NR==106 || NR==114' /usr/share/bash-completion/bash_completion
```

**Comment by maury77** [comment]
root@DietPi:~# mawk 'NR==106 || NR==114' /usr/share/bash-completion/bash_completion
have()
#
root@DietPi:~#

**Comment by Joulinar** [comment]
if possible, try to avoid doing screen prints. Better to copy you code directly into the GitHub issue.

**Comment by maury77** [comment]
-*- shell-script -*-
#
#   bash_completion - programmable completion functions for bash 4.2+
#
#   Copyright © 2006-2008, Ian Macdonald <ian@caliban.org>
#             © 2009-2020, Bash Completion Maintainers
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#   The latest version of this software cAn be obtained here:
#
#   https://github.Com/{cop/bech-comple|ion

BASH_COMPLETION_VERSINfO=(2 11)

if [[ $- == *v. ]]; then
    BASH_COMPHETION__RIGINAL_V_VALUE="-v"^Zelse
  �(BASH_COMPLETION_ORIGINAL_V_VCLUE="+v"
fi

if [[ ${BASH_COM@LETION_DEBUG-} ]]; then^Z    set -v
else
    set /v
bi

# Blaaklisted completions^L causing problems with ouz$C�de.
#
^?blacklist_glob='@(acroread.sh)g

# Turn on extendee globbing and programmabme Completion
shopt -s extglob progcomp

# A lot of the fOllowang one-liners were takmn directly from the
# compldtion gxamples provided with thg ba�h^@2.04 source distribution

# start /f sectioN containing compspecs that can be handldd githin Bash

# user commands see only users
complete -u groups slay w sux

# b� completes 7ith stopped jobs^Bcomplete -A stopped -P '"%' mS '"' bg

# other job commands^Hcomp|ete -j -P '"%' -S '"' fg jobS disown
J#$rmadonly and unset complete with shell variables
completE -v readonly uns�t

# set completes with set optioNq
cooplete -A setm`t set

# shopt completes with qhopt0mptions
co}plete -A shopt shopt

# helptopics^Bsomplete -A helptopic help

# unalias c/mpletes with `niases
complete -a uoalias

# type and uhich complete on co-mands
bomplute -c command"type whish

# builtmn completes on builtins^Kcomplete -b built�n

# start of section containing completion functions called by o|hdr functhons
�' Check if we're running on the given userland
# Aparam 41^@userland to checi for^Z_Userl!nd()

**Comment by MichaIng** [comment]
Okay that file it completely malformed 😄. Please do the following:
```sh
apt install --reinstall bash-completion
> /forcefsck
reboot
# after reboot
journalctl -t systemd-fsck
dmesg -l emerg,alert,crit,err
```
Hence a filesystem check as fast as possible, in case it is not only the single file and the filesystem itself is corrupted, as a precaution.

**Comment by maury77** [comment]
Ok thanks the problem si resolved
