### ISSUE TITLE
AUTO_SETUP_FILE_SERVER_INDEX options reversed

### ISSUE THREAD

**Issue by bsheeres** [MichaIng/DietPi#5081]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=9
G_DIETPI_VERSION_RC=3
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'
G_LIVE_PATCH_STATUS[1]='not applicable'
G_LIVE_PATCH_STATUS[2]='not applicable'

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
bullseye 0

- Kernel version | `uname -a`
`Linux WhyPi 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
RPi 3 Model B (armv7l)

- Power supply used | (EG: 5V 1A RAVpower)
5V 2.4A (Anker 40W 5-Port USB Wall Charger)

- SDcard used | (EG: SanDisk ultra)
ScanDisk 16 GB Class 4
Pioneer 32 GB Class 10

#### Additional Information (if applicable)
Clean install.
First run as root.
Repeatable (on the only RPi I have). Close to a dozen installs with the same result.

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. Create fresh install image
2. Edit the dietpi.txt file and select AUTO_SETUP_FILE_SERVER_INDEX=-2 (Samba according to dietpi.txt)
3. Run the install and notice ProFTP rather than Samba is installed.
4. Run the same steps selecting AUTO_SETUP_FILE_SERVER_INDEX=-1 (Pro FTP according to dietpi.txt) and notice Samba is installed.

#### Expected behaviour

The software matching the flag should be installed.

#### Actual behaviour

The opposite software is installed.

**Comment by MichaIng** [comment]
Many thanks for your report.

Looks like we mixed it up. Note that this is only kept for backwards compatibility reasons while this method is deprecated. Use the `AUTO_SETUP_INSTALL_SOFTWARE_ID` to have one or more file servers installed.

Fixed with: https://github.com/MichaIng/DietPi/commit/6be3928
