### ISSUE TITLE
DietPi-Software | Amiberry 4.1.6

### ISSUE THREAD

**Issue by wifi75** [MichaIng/DietPi#5082]
### Creating a feature request
hello when it is available amiberry 4.1.6?
#### Is your feature request related to a problem? Please describe:

- ...

#### Describe the solution you'd like:

- ...

#### Describe alternatives you've considered:

- ...

#### Additional context

- ...

**Comment by Joulinar** [comment]
We need to pre-compile the binaries. Pls be patient.
