### ISSUE TITLE
Unable To Connect To Deluge Web UI 

### ISSUE THREAD

**Issue by AdamF100001** [MichaIng/DietPi#5096]
Hi

I am unable to connect to Deluge Web UI in Deluge 1.3.15 Windows Client.

But I can connect to the Deluge Web UI on Andriod through an app called Deluge off the F-Driod app store.

Thanks    

Adam

**Comment by MichaIng** [comment]
This means it is a client side issue. Can you connect via browser from Windows?

**Comment by AdamF100001** [comment]
Yes I can connect via browser from Windows

**Comment by Joulinar** [comment]
Maybe an issue between the client 1.3.15 and deluge 2. Maybe they are not fitting to each other anymore. If I'm not mistaken the client is from 2017 https://ftp.osuosl.org/pub/deluge/windows/?C=M;O=D

**Comment by AdamF100001** [comment]
yeah client 2.0 is supported on everything apart from windows, but I have it working on Andriod so not all bad.

**Comment by Joulinar** [comment]
ok I marked the issue as outside DietPi as it is most probably the client

**Comment by MichaIng** [comment]
Ah right, I remember there was already an issue about that. At least one can always connect via browser 🙂.

**Comment by AdamF100001** [comment]
Also true. thanks for the help.

**Comment by Joulinar** [comment]
Going to close this as it is out of our scope. Feel free to reopen if needed.
