### ISSUE TITLE
wifi problem

### ISSUE THREAD

**Issue by geol** [MichaIng/DietPi#5105]
when the router's wifi set 802.11w to "Optional" or "Enable", then my rpi4 can not connect to it.

**Comment by Joulinar** [comment]
I guess this is an issue of RPi kernel/firmware not supporting ieee80211w/MFP https://github.com/raspberrypi/linux/issues/3619

**Comment by geol** [comment]
> I guess this is an issue of RPi kernel/firmware not supporting ieee80211w/MFP [raspberrypi/linux#3619](https://github.com/raspberrypi/linux/issues/3619)

thank u for reply. so, there is no any solutions at the moment?

**Comment by Joulinar** [comment]
Not sure if we are able to do anything if it is indeed a kernel/firmware topic. Because we don't do kernel development. You could ask on the GitHub post I linked above if there is a solution to geht ieee80211w/MFP running.

**Comment by geol** [comment]
> Not sure if we are able to do anything if it is indeed a kernel/firmware topic. Because we don't do kernel development. You could ask on the GitHub post I linked above if there is a solution to geht ieee80211w/MFP running.

okay, thank you.

**Comment by MichaIng** [comment]
And there was even a firmware and kernel patch available already, but it hasn't been supplied via any release until today 😞. @geol You may contribute to the issue, to hopefully get it more attention. I'm not sure how frequently `ieee80211w` is used, but especially WPA3 becomes common so plenty reasons to get it supported natively.
