### ISSUE TITLE
DietPi-Software | FFmpeg install misses libmp3lame dependency.

### ISSUE THREAD

**Issue by EraYaN** [MichaIng/DietPi#511]
When FFmpeg is installed on the latest version and ran the following output is shown:

```
ffmpeg: error while loading shared libraries: libmp3lame.so.0: cannot open shared object file: No such file or directory
```

after installing lame manually (the package) the error goes away.

**Comment by Fourdee** [comment]
@EraYaN 
Thanks for the report.

Which device are you running DietPi on?

**Comment by EraYaN** [comment]
A Raspberry Pi Model B (512MB)

**Comment by Fourdee** [comment]
@EraYaN 
Thanks. Fixed in v131 :+1:
