### ISSUE TITLE
DietPi | Add option to format external USB drive as FAT32/NTFS

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#512]
This suggestion came from several AmiBerry users, but I believe it might interest others as well.
Instead of offering only ext4 as the filesystem for the external USB drive, an option to format it and use it as FAT32 or NTFS should also be available.

That way, users could easily also use it on a Windows machine.

If this causes some features not to work, e.g. symlinks inside the USB drive, we could have a relevant warning and maybe disable such applications from utilizing it? Not sure if there's any such scenario though.

**Comment by Fourdee** [comment]
Ties in with: https://github.com/Fourdee/DietPi/issues/271

**Comment by Fourdee** [comment]
@midwan

> If this causes some features not to work, e.g. symlinks inside the USB drive, we could have a relevant warning and maybe disable such applications from utilizing it? Not sure if there's any such scenario though

Yep, symlinks is the main factor, `dietpi-backup` requires symlinks and will prevent use on non EXT drives. Aside from that, I think we should be fine.

Minor considerations:
NTFS = Higher CPU usage and slower performance (spawns a running process)
FAT32 = 4GB filesize limit | 2TB max volume

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/18514112/21cb37b4-7a88-11e6-8901-93191ad304d4.png)

edit: pppppppppp

**Comment by Fourdee** [comment]
@midwan 
Completed. `dietpi-drive_manager` can now format ext4/ntfs/fat32.

I'll take a look at https://github.com/Fourdee/DietPi/issues/513. Most likely prompt user and run our new `dietpi-drive_manager` so they can setup drive.

**Comment by midwan** [comment]
@Fourdee you have a typo there in the screenshot, in case you didn't notice:
Recommended if you plan to use this drive **soley** on this system

should be **solely** I believe?
