### ISSUE TITLE
DietPi-DDNS | Add provider YDNS

### ISSUE THREAD

**Issue by edmundlaugasson** [MichaIng/DietPi#5128]
#### Is your feature request related to a problem? Please describe:

As [YDNS](https://ydns.io/) is [free and open-source](https://github.com/ydns), then why not include it into DietPi.

#### Describe the solution you'd like:

When opening DietPi-DDNS tool, would like to see YDNS choice there. [Appropriate bash DDNS updater script is here](https://github.com/ydns/bash-updater).

#### Describe alternatives you've considered:

There are alternatives available at DietPi-DDNS tool

#### Additional context

This should work on all supported platforms of DietPi architecture (armhf, aarch64, etc).

**Comment by MichaIng** [comment]
Many thanks for your request.

Bare API docs are here: https://ydns.io/api/v1/#update
So instead of invoking a whole bash script, we can do a simple `curl` call like we do in the other cases 🙂.

**Comment by TDuffinNTU** [comment]
Would this be a good newcomer issue to tackle? From what I can tell I just need to modify dietpi-ddns:

* Add YDNS to USAGE and as a commandline option via Read()
* Add YDNS update URI to Apply()
* Add YDNS-specific option(s) to other methods.

Any other scripts that need updating to accommodate the change?

**Comment by MichaIng** [comment]
Jep, only this one script needs change. Searching for e.g. "DuckDNS" though the script and adding respective YDNS blocks should so it.

**Comment by MichaIng** [comment]
Done with: #6674
