### ISSUE TITLE
Missing package leads to failed installation of MyMPD

### ISSUE THREAD

**Issue by j-m-hoffmann** [MichaIng/DietPi#5148]
#### Required Information
- DietPi version | 7.9.3
- Distro version | bullseye
- Kernel version | 5.10.0
- SBC model | RPi3

#### Additional Information (if applicable)
- Software title | MyMPD

#### Expected behaviour
Install without a hitch

#### Actual behaviour
![IMG_20220108_194018](https://user-images.githubusercontent.com/27806916/148656639-c9e7ce60-04a5-4c88-bf54-c9f9bd4b818b.jpg)

#### Extra details
can be fixed by installing the libpcre2-dev package

**Comment by MichaIng** [comment]
Many thanks for your report.

Solved already. We migrated to the official myMPD APT repository: https://github.com/MichaIng/DietPi/pull/5122

**Comment by Joulinar** [comment]
This is already know and a permanent fix will be provided on next release https://github.com/MichaIng/DietPi/issues/5115#issuecomment-1001251945

**Comment by MichaIng** [comment]
Release has been done, issue solved.
