### ISSUE TITLE
Can't install docker using dietpi-software

### ISSUE THREAD

**Issue by s4tch** [MichaIng/DietPi#5154]
#### Details:
- Date           | Mon Jan 10 10:15:25 GMT 2022
- DietPi version | v8.0.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | DietPi
- Hardware       | Sparky SBC (armv7l) (ID=70)
- Kernel version | `Linux DietPi 3.10.38 #22 SMP PREEMPT Fri Dec 22 10:45:41 IST 2017 armv7l GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `apt-get -qq --allow-change-held-packages install docker-ce`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. dietpi-software
2. select docker from the list, install
#### Expected behaviour:

- docker should be installed
#### Actual behaviour:

- see log + screenshot please. (clean install, formatted-reflashed dietpi allo gui image, zero tweaking, just updated to dietpi v8.0.2 before that)
![Clipboard01](https://user-images.githubusercontent.com/96346912/148749941-6f48a997-96c6-412a-bea2-fc7bcfdfce0f.jpg)

#### Extra details:

- ...
#### Additional logs:
```
Setting up docker-ce (5:20.10.12~3-0~debian-bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-10 10:15:25 GMT; 44ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 3689 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 3689 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Joulinar** [comment]
Hi,

this is same issue as this one. https://github.com/MichaIng/DietPi/issues/4480
Reason is the pretty old kernel if I'm not mistaken.

**Comment by s4tch** [comment]
Thank you. So bottom line is that sparky is unsupported, right?

Joulinar ***@***.***> ezt írta (időpont: 2022. jan. 10., H
11:42):

**Comment by MichaIng** [comment]
Just to be sure whether it's the same issue:
```sh
journalctl -u docker -u containerd
```
But yes, the kernel lacks some features now required for Docker. Sadly there are also not much older packages available anymore: https://download.docker.com/linux/debian/dists/bullseye/pool/stable/armhf/
And no chance to get a newer Linux version running on Sparky SBC from current view.

Looks like we need to disable the Docker install option on Sparky SBC accordingly. If you have any chance to install the software you want to run inside the container natively on the host system, that would be the way to go, we may be able to help with this. At least from memory usage point of view it's preferable anyway.

**Comment by s4tch** [comment]
-- Journal begins at Mon 2022-01-10 11:23:28 GMT, ends at Mon 2022-01-10 12:43:56 GMT. --
Jan 10 11:23:35 DietPi systemd[1]: Starting containerd container runtime...
Jan 10 11:23:35 DietPi modprobe[936]: modprobe: FATAL: Module overlay not found in directory /lib/modules/3.10.38
Jan 10 11:23:35 DietPi systemd[1]: Starting Docker Application Container Engine...
Jan 10 11:23:38 DietPi containerd[943]: time="2022-01-10T11:23:38.930375001Z" level=info msg="starting containerd" revision="1.4.12~ds1-1~deb11u1" version="1.4.12~ds1"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.222228751Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.230296751Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.243248001Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exit status 1 \"modprobe: FATAL: Module aufs not found in directory /lib/modules/3.10.38\\n\"): skip plugin" type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.243538751Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.245587001Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (ext4) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.245800751Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.246090001Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.246233251Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.252311501Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.258838251Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.259991251Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.260193501Z" level=info msg="loading plugin \"io.containerd.metadata.v1.bolt\"..." type=io.containerd.metadata.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.260432001Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.260554751Z" level=info msg="metadata content store policy set" policy=shared
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.279733251Z" level=info msg="loading plugin \"io.containerd.differ.v1.walking\"..." type=io.containerd.differ.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.280494751Z" level=info msg="loading plugin \"io.containerd.gc.v1.scheduler\"..." type=io.containerd.gc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.282087001Z" level=info msg="loading plugin \"io.containerd.service.v1.introspection-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.282684001Z" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283016501Z" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283185751Z" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283374251Z" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283547251Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283809001Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.283973001Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.284153751Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.284696751Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.285310001Z" level=info msg="loading plugin \"io.containerd.monitor.v1.cgroups\"..." type=io.containerd.monitor.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.288766501Z" level=info msg="loading plugin \"io.containerd.service.v1.tasks-service\"..." type=io.containerd.service.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.289052251Z" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.289690751Z" level=info msg="loading plugin \"io.containerd.grpc.v1.containers\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.289959501Z" level=info msg="loading plugin \"io.containerd.grpc.v1.content\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290118501Z" level=info msg="loading plugin \"io.containerd.grpc.v1.diff\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290252751Z" level=info msg="loading plugin \"io.containerd.grpc.v1.events\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290378251Z" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290534251Z" level=info msg="loading plugin \"io.containerd.grpc.v1.images\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290659501Z" level=info msg="loading plugin \"io.containerd.grpc.v1.leases\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290784001Z" level=info msg="loading plugin \"io.containerd.grpc.v1.namespaces\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.290906501Z" level=info msg="loading plugin \"io.containerd.internal.v1.opt\"..." type=io.containerd.internal.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.295243751Z" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.295664251Z" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.295949001Z" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.296389501Z" level=info msg="loading plugin \"io.containerd.grpc.v1.cri\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.298747001Z" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc DefaultRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} UntrustedWorkloadRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} Runtimes:map[runc:{Type:io.containerd.runc.v2 Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:0x1f1c280 PrivilegedWithoutHostDevices:false BaseRuntimeSpec:}] NoPivot:false DisableSnapshotAnnotations:true DiscardUnpackedLayers:false} CniConfig:{NetworkPluginBinDir:/usr/lib/cni NetworkPluginConfDir:/etc/cni/net.d NetworkPluginMaxConfNum:1 NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.io:{Endpoints:[https://registry-1.docker.io]}] Configs:map[] Auths:map[] Headers:map[]} ImageDecryption:{KeyModel:} DisableTCPService:true StreamServerAddress:127.0.0.1 StreamServerPort:0 StreamIdleTimeout:4h0m0s EnableSelinux:false SelinuxCategoryRange:1024 SandboxImage:k8s.gcr.io/pause:3.2 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false MaxConcurrentDownloads:3 DisableProcMount:false UnsetSeccompProfile: TolerateMissingHugetlbController:true DisableHugetlbController:true IgnoreImageDefinedVolumes:false} ContainerdRootDir:/var/lib/containerd ContainerdEndpoint:/run/containerd/containerd.sock RootDir:/var/lib/containerd/io.containerd.grpc.v1.cri StateDir:/run/containerd/io.containerd.grpc.v1.cri}"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.299526251Z" level=info msg="Connect containerd service"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.300368751Z" level=info msg="Get image filesystem path \"/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs\""
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.320201751Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.320964001Z" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.321926501Z" level=info msg="Start subscribing containerd event"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.328008001Z" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.329001751Z" level=info msg=serving... address=/run/containerd/containerd.sock
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.330172501Z" level=info msg="containerd successfully booted in 0.432375s"
Jan 10 11:23:39 DietPi systemd[1]: Started containerd container runtime.
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.338021001Z" level=info msg="Start recovering state"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.339894001Z" level=info msg="Start event monitor"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.340245501Z" level=info msg="Start snapshots syncer"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.340478001Z" level=info msg="Start cni network conf syncer"
Jan 10 11:23:39 DietPi containerd[943]: time="2022-01-10T11:23:39.340616251Z" level=info msg="Start streaming server"
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.556169251Z" level=info msg="Starting up"
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.570128501Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.570283251Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.570469001Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.570690751Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.608920251Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.609143751Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.609314501Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.609536251Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:23:39 DietPi dockerd[941]: time="2022-01-10T11:23:39.722943751Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
Jan 10 11:23:39 DietPi dockerd[941]: failed to start daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed
Jan 10 11:23:39 DietPi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 11:23:39 DietPi systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 10 11:23:39 DietPi systemd[1]: Failed to start Docker Application Container Engine.
Jan 10 11:23:40 DietPi systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
Jan 10 11:23:40 DietPi systemd[1]: Stopped Docker Application Container Engine.
Jan 10 11:23:40 DietPi systemd[1]: Starting Docker Application Container Engine...
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.452558751Z" level=info msg="Starting up"
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.482317501Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.482499251Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.482801501Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.483036251Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.491341501Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.491558001Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.491731501Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.492004751Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:23:40 DietPi dockerd[981]: time="2022-01-10T11:23:40.603909501Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
Jan 10 11:23:40 DietPi dockerd[981]: failed to start daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed
Jan 10 11:23:40 DietPi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 11:23:40 DietPi systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 10 11:23:40 DietPi systemd[1]: Failed to start Docker Application Container Engine.
Jan 10 11:23:40 DietPi systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
Jan 10 11:23:40 DietPi systemd[1]: Stopped Docker Application Container Engine.
Jan 10 11:23:40 DietPi systemd[1]: Starting Docker Application Container Engine...
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.050755331Z" level=info msg="Starting up"
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.065024331Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.065250331Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.065721831Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.066309831Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.077035081Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.077455581Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.077761081Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.078761081Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.235194331Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
Jan 10 11:24:10 DietPi dockerd[1030]: time="2022-01-10T11:24:10.242861331Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
Jan 10 11:24:10 DietPi dockerd[1030]: failed to start daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed
Jan 10 11:24:10 DietPi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 11:24:10 DietPi systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 10 11:24:10 DietPi systemd[1]: Failed to start Docker Application Container Engine.
Jan 10 11:24:10 DietPi systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Jan 10 11:24:10 DietPi systemd[1]: Stopped Docker Application Container Engine.
Jan 10 11:24:10 DietPi systemd[1]: docker.service: Start request repeated too quickly.
Jan 10 11:24:10 DietPi systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 10 11:24:10 DietPi systemd[1]: Failed to start Docker Application Container Engine.
Jan 10 11:24:22 DietPi systemd[1]: docker.service: Start request repeated too quickly.
Jan 10 11:24:22 DietPi systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 10 11:24:22 DietPi systemd[1]: Failed to start Docker Application Container Engine.

**Comment by s4tch** [comment]
Thanks for the replies. All I'd want besides the basic DietPi features is to install the tidal connect service.

**Comment by MichaIng** [comment]
The same `devicemapper` error indeed.

Not sure whether it's a feasible alternative, but `O!MPD` has Tidal support included, maybe other media streaming servers as well.

**Comment by s4tch** [comment]
Thanks @MichaIng , unfortunately I couldn't get docker working. Sparky might not be supported after all.

**Comment by Joulinar** [comment]
I'm going to close the issue. Feel free to reopen if needed.
