### ISSUE TITLE
dietpi-software reinstall after Bullseye upgrade cannot find pip module

### ISSUE THREAD

**Issue by ehuang17** [MichaIng/DietPi#5163]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
```
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
```
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
`bullseye 1`

- Kernel version | `uname -a`
`Linux DietPi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux`

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
`RPi 4 Model B (armv7l)`
- Power supply used | (EG: 5V 1A RAVpower)
`5V 2.5A official RPi power supply`
- SDcard used | (EG: SanDisk ultra)
`Sandisk 32GB`

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
dietpi (following bullseye upgrade guide at https://dietpi.com/blog/?p=811)

- Was the software title installed freshly or updated/migrated?
I get this when running the command `dietpi-software reinstall 31 38 40 47 48 56 83 84 85 88 89 93 114 118 130 134 143`

- Can this issue be replicated on a fresh installation of DietPi?
probably not

- Bug report ID | `echo $G_HW_UUID`
dietpi-bugreport Reference code: `8f6387b5-1dc6-4181-9bc9-d5d623b56106`

#### Details:
- Date           | Wed Jan 12 17:58:11 PST 2022
- Bug report     | 8f6387b5-1dc6-4181-9bc9-d5d623b56106
- DietPi version | v8.0.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 4 Model B (armv7l) (ID=4)
- Kernel version | `Linux DietPi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `pip3 uninstall -y setuptools`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

1. follow manual bullseye upgrade instruction at https://dietpi.com/blog/?p=811
2. run the final command to reinstall software packages

#### Expected behaviour:
- reinstall succeeds

#### Actual behaviour:
- encounter error when reinstalling python3
```
 DietPi-Software
─────────────────────────────────────────────────────
 Step: Installing Python 3: Runtime system, pip package installer and development headers

[FAILED] DietPi-Software | pip3 uninstall -y setuptools
```

#### Extra details:
- the `apt full-upgrade` process was run in an SSH session that was interrupted due to an unexpected reboot of the client system. However upon the client system coming back, I killed the apt process and ran `dpkg --configure -a` and it completed successfully. Another run of `apt full-upgrade` returns no upgradeable packages.

#### Additional logs:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

**Comment by Joulinar** [comment]
@MichaIng 
We could check for `setuptools` being available and simply remove it on file system level, instead of running `pip3 uninstall`. This way we do not run into this trap if `pip` is already broken. Not that elegant but might be working.

**Comment by MichaIng** [comment]
I added the info and step to the guide: https://dietpi.com/blog/?p=811#2.2.4-software-migrations
I'll mark this as closed now. Feel free to reopen when required.
