### ISSUE TITLE
Hash Sum Mismatch on DietPi for VirtualBox

### ISSUE THREAD

**Issue by LazyGeniusMan** [MichaIng/DietPi#5167]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
![image](https://user-images.githubusercontent.com/58850480/149535169-fda4d23c-1973-425e-a71b-e1dadae1dd7f.png)

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
```
bullseye
```
- Kernel version | `uname -a`
![image](https://user-images.githubusercontent.com/58850480/149535516-a3a46809-7c5c-489e-a467-36e00c2a00c1.png)

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
Virtual Machine (x86_64)
- Power supply used | (EG: 5V 1A RAVpower)
None (VM)
- SDcard used | (EG: SanDisk ultra)
None (VM)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
Fresh
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`
![image](https://user-images.githubusercontent.com/58850480/149537719-b278d553-d142-4ef3-b466-8a081d6a3e1c.png)

#### Steps to reproduce

1. Download DietPi for VM from the website.
2. Extract the archive
3. Double click the `.ova` file
4. VirtualBox will Open; click import and then start the VM.
5. Follow the screen instruction
6. Failed on `apt-get -q update` phase

#### Expected behaviour

- `apt-get -q update` successful

#### Actual behaviour

- `apt-get -q update` failed
![image](https://user-images.githubusercontent.com/58850480/149537447-786e4067-dcb4-41d7-927a-9afc13de59ad.png)

#### Extra details

- Passed internet connection test
- Tried change APT mirror
- Disabled ipv6
![image](https://user-images.githubusercontent.com/58850480/149537489-de109236-34aa-4b34-b747-1085e40816b6.png)

**Comment by MichaIng** [comment]
Many thanks for your report.

Please simply retry, this can be an inconsistency in the repository during changes. You can also change the APT mirror via DietPi-Config (right from the error prompt) or `dietpi-config` (console command) > **Network Options: Misc** > **APT Mirror** in case `deb.debian.org` keeps failing.

**Comment by LazyGeniusMan** [comment]
> You can also change the APT mirror via DietPi-Config

Tried all of alt APT mirror (Global, UK, Germany, China, and Australia), all failed.

**Comment by Joulinar** [comment]
btw there is no need to do print screens. It would be better to copy the information directly from SSH terminal directly. 

For me this is working fine

```
root@DietPiVM1:/etc/apt# apt update
Get:1 https://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 https://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:3 https://deb.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:4 https://deb.debian.org/debian bullseye-backports InRelease [44.0 kB]
Get:5 https://deb.debian.org/debian bullseye/non-free amd64 Packages [93.8 kB]
Get:6 https://deb.debian.org/debian bullseye/contrib amd64 Packages [50.5 kB]
Get:7 https://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:8 https://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
Get:9 https://deb.debian.org/debian-security bullseye-security/main amd64 Packages [106 kB]
Get:10 https://deb.debian.org/debian bullseye-backports/non-free amd64 Packages [6116 B]
Get:11 https://deb.debian.org/debian bullseye-backports/main amd64 Packages [170 kB]
Get:12 https://deb.debian.org/debian bullseye-backports/contrib amd64 Packages [4012 B]
Fetched 8860 kB in 4s (2067 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@DietPiVM1:/etc/apt#
```

try following

```
/boot/dietpi/func/dietpi-set_software apt-cache clean
apt update
```

**Comment by MichaIng** [comment]
Disabling IPv6 is only required when your VirtualBox host uses WiFi for internet access (with VM network in bridged mode), but it isn't related to this error. Can you try to clear the APT cache:
```sh
/boot/dietpi/func/dietpi-set_software apt-cache clean
apt update
```

**Comment by LazyGeniusMan** [comment]
> btw there is no need to do print screens. It would be better to copy the information directly from SSH terminal directly.

ah yea, why I didn't think that, smh
> try following

Still same

wait, I'll try my luck using VPN in case this is my ISP problem

**Comment by LazyGeniusMan** [comment]
@MichaIng  Also error even when I use VPN :( , may I look your VM setting? (like CPU, RAM, Network etc), what's VM are you using ? I'll try to replicate your setup.

**Comment by Joulinar** [comment]
Issue is not with the VM and / or it's settings. Simply the release file you download did not fit. Something seems to be broken on download. Do you have any firewall or other security on your network, doing something like package inspection?

**Comment by LazyGeniusMan** [comment]
> Issue is not with the VM and / or it's settings. Simply the release file you download did not fit. Something seems to be broken on download. Do you have any firewall or other security on your network, doing something like package inspection?

the downloaded file hash is matched
```
PS C:\Users\LazyGeniusMan\Downloads\Archive\DietPi_VirtualBox-x86_64-Bullseye> Get-FileHash ./DietPi_VirtualBox-x86_64-Bullseye.ova

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          1EE57B3BE4FA1EB84BFC3D72A2CE7D6E77C4677BBB1FCE108945A2DCD48BDFA6       C:\Users\LazyGeniusMan\Downlo...


PS C:\Users\LazyGeniusMan\Downloads\Archive\DietPi_VirtualBox-x86_64-Bullseye> cat hash.txt | Select-String -Pattern 'SHA256'

SHA256: 1ee57b3be4fa1eb84bfc3d72a2ce7d6e77c4677bbb1fce108945a2dcd48bdfa6


```

**Comment by MichaIng** [comment]
It is a completely different level of failures, has nothing to do with the VM settings, image, virtualizer or something like that, it is purely a network or APT server/cache related issue 😉.

Can you manually download `https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz` and check the hashes of the contained `Packages` file?

**Comment by LazyGeniusMan** [comment]
> Can you manually download `https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz` and check the hashes of the contained `Packages` file?
Inside VM:
```
root@DietPi:/tmp/DietPi-Update# wget https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
--2022-01-14 16:56:38--  https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
Resolving ftp.debian.org (ftp.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to ftp.debian.org (ftp.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8183088 (7.8M) [application/x-xz]
Saving to: ‘Packages.xz’

Packages.xz                   100%[=================================================>]   7.80M  1.37MB/s    in 5.6s

2022-01-14 16:56:44 (1.38 MB/s) - ‘Packages.xz’ saved [8183088/8183088]

root@DietPi:/tmp/DietPi-Update# ls
Packages.xz
root@DietPi:/tmp/DietPi-Update# sha256sum Packages.xz
6d5509534097dd37bbcc2ed7bb18e117511395ac3812562abbe019b64071e1bf  Packages.xz
```

In Windows (Using JDownloader2):
```
6d5509534097dd37bbcc2ed7bb18e117511395ac3812562abbe019b64071e1bf
```

**Comment by MichaIng** [comment]
The hash is the one of the uncompressed `Packages` file, not the `.xz`. From Linux console:
```sh
apt install xz-utils
xz -d Packages.xz
```

**Comment by LazyGeniusMan** [comment]
> The hash is the one of the uncompressed `Packages` file, not the `Packages.xz`

Since I can't install apt package in the VM, this is from Windows (Extract and CRC using 7Zip):
```
cf77eaa6fb5f4cda14da07de79f02af4ab532bac707b0767b0cf3a3a83008480
```

it's matched :/

**Comment by LazyGeniusMan** [comment]
> `apt install` is failing as well?

yes, maybe because it's failed when doing `apt update` so it's not synced ?
```
root@DietPi:/tmp/DietPi-Update# apt install xz-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package xz-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'xz-utils' has no installation candidate
```

**Comment by Joulinar** [comment]
you could download the tool manually

```
cd /tmp
wget http://ftp.debian.org/debian/pool/main/x/xz-utils/xz-utils_5.2.5-2_amd64.deb
dpkg -i xz-utils_5.2.5-2_amd64.deb
rm xz-utils_5.2.5-2_amd64.deb
```

**Comment by MichaIng** [comment]
Wait, simpler:
```sh
wget https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
gzip -d Packages.gz
sha256sum Packages
rm Packages Packages.gz
```

**Comment by LazyGeniusMan** [comment]
```
root@DietPi:/tmp/DietPi-Update# xz -d Packages.xz
root@DietPi:/tmp/DietPi-Update# ls
Packages
root@DietPi:/tmp/DietPi-Update# sha256sum Packages
cf77eaa6fb5f4cda14da07de79f02af4ab532bac707b0767b0cf3a3a83008480  Packages
```

**Comment by MichaIng** [comment]
Okay, so that matches (now). `apt update` still fails?

**Comment by LazyGeniusMan** [comment]
> Okay, so that matches (now). `apt update` still fails?

yea, and now I try redownload the package.xz and it's corrupt lmao
```
root@DietPi:/tmp# wget https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
--2022-01-14 17:28:33--  https://ftp.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
Resolving ftp.debian.org (ftp.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to ftp.debian.org (ftp.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8183088 (7.8M) [application/x-xz]
Saving to: ‘Packages.xz’

Packages.xz                   100%[=================================================>]   7.80M  1.95MB/s    in 3.9s

2022-01-14 17:28:38 (2.01 MB/s) - ‘Packages.xz’ saved [8183088/8183088]

root@DietPi:/tmp# sha256sum Packages.xz
2adfd3250416c93fab49898bd79a691a94e4438567826632bb02c0da978d747e  Packages.xz
root@DietPi:/tmp# xz -d Packages.xz
xz: Packages.xz: Compressed data is corrupt
root@DietPi:/tmp#
```

**Comment by LazyGeniusMan** [comment]
is there any way to `apt update` manually ? looks like sometimes it's match sometimes it's not matched

**Comment by MichaIng** [comment]
Can you run a diff of those two files:
```sh
wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
mv Packages.xz Packages_xz.xz
gzip -d Packages.gz
xz -d Packages_xz.xz
diff Packages Packages_xz
```
As long as this file does not expect the expected one, I'd not use the list to install packages, for security reasons. It is unlikely, but in theory such can be used to install maliciously manipulated packages.

**Comment by LazyGeniusMan** [comment]
nothing show up, but I have to try to download it a bunch of time cuz sometimes it's broken
```
root@DietPi:/tmp# cd test
root@DietPi:/tmp/test# wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
mv Packages.xz Packages_xz.xz
gzip -d Packages.gz
xz -d Packages_xz.xz
diff Packages Packages_xz
--2022-01-14 17:39:04--  https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
Resolving deb.debian.org (deb.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to deb.debian.org (deb.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8183088 (7.8M) [application/x-xz]
Saving to: ‘Packages.xz’

Packages.xz                   100%[=================================================>]   7.80M   875KB/s    in 8.3s

2022-01-14 17:39:12 (968 KB/s) - ‘Packages.xz’ saved [8183088/8183088]

--2022-01-14 17:39:12--  https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
Resolving deb.debian.org (deb.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to deb.debian.org (deb.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11091682 (11M) [application/x-gzip]
Saving to: ‘Packages.gz’

Packages.gz                   100%[=================================================>]  10.58M   718KB/s    in 13s

2022-01-14 17:39:26 (832 KB/s) - ‘Packages.gz’ saved [11091682/11091682]


gzip: Packages.gz: invalid compressed data--crc error

gzip: Packages.gz: invalid compressed data--length error
xz: Packages_xz.xz: Compressed data is corrupt
diff: Packages: No such file or directory
diff: Packages_xz: No such file or directory
root@DietPi:/tmp/test# cd ..
root@DietPi:/tmp# rm -tf test
rm: invalid option -- 't'
Try 'rm --help' for more information.
root@DietPi:/tmp# rm -rf test
root@DietPi:/tmp# mkdir test
root@DietPi:/tmp# cd test
root@DietPi:/tmp/test# wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
mv Packages.xz Packages_xz.xz
gzip -d Packages.gz
xz -d Packages_xz.xz
diff Packages Packages_xz
--2022-01-14 17:40:08--  https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
Resolving deb.debian.org (deb.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to deb.debian.org (deb.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8183088 (7.8M) [application/x-xz]
Saving to: ‘Packages.xz’

Packages.xz                   100%[=================================================>]   7.80M  1.95MB/s    in 4.2s

2022-01-14 17:40:13 (1.86 MB/s) - ‘Packages.xz’ saved [8183088/8183088]

--2022-01-14 17:40:13--  https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.gz
Resolving deb.debian.org (deb.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to deb.debian.org (deb.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11091682 (11M) [application/x-gzip]
Saving to: ‘Packages.gz’

Packages.gz                   100%[=================================================>]  10.58M   914KB/s    in 8.9s

2022-01-14 17:40:22 (1.19 MB/s) - ‘Packages.gz’ saved [11091682/11091682]

xz: Packages_xz.xz: Compressed data is corrupt
diff: Packages_xz: No such file or directory
root@DietPi:/tmp/test# ls
Packages  Packages_xz.xz
root@DietPi:/tmp/test# rm Packages_xz.xz
root@DietPi:/tmp/test# wget https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
--2022-01-14 17:40:54--  https://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz
Resolving deb.debian.org (deb.debian.org)... 199.232.46.132, 2a04:4e42:48::644
Connecting to deb.debian.org (deb.debian.org)|199.232.46.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8183088 (7.8M) [application/x-xz]
Saving to: ‘Packages.xz’

Packages.xz                   100%[=================================================>]   7.80M  1.22MB/s    in 6.0s

2022-01-14 17:41:03 (1.29 MB/s) - ‘Packages.xz’ saved [8183088/8183088]

root@DietPi:/tmp/test# mv Packages.xz Packages_xz.xz
gzip -d Packages.gz
xz -d Packages_xz.xz
diff Packages Packages_xz
gzip: Packages.gz: No such file or directory
root@DietPi:/tmp/test# ls
Packages  Packages_xz
root@DietPi:/tmp/test# diff Packages Packages_xz
root@DietPi:/tmp/test# diff Packages Packages_xz
root@DietPi:/tmp/test#
```

**Comment by Joulinar** [comment]
just as side note, better to execute the commands one by one 😉

**Comment by MichaIng** [comment]
Interesting, so indeed the compressed file is not downloaded or stored correctly sometimes. The question is why, especially why so often 🤔.
Can you check for kernel errors:
```sh
dmesg -l emerg,alert,crit,err
```
How are you connected to the Internet, WiFi or Ethernet? VirtualBox is on newest version? What is the host OS?

**Comment by LazyGeniusMan** [comment]
> just as side note, better to execute the commands one by one 😉

Haha sorry, kinda lazy.


> Can you check for kernel errors:

nothing comes out.

> How are you connected to the Internet, WiFi or Ethernet? VirtualBox is on newest version? What is the host OS?

Wifi, VirtualBox 6.1.8 (latest is 6.1.30 iirc), using Windows 10 21H2.

Wait I'll update VirtualBox

**Comment by LazyGeniusMan** [comment]
Aight it's working fine after I update my VirtualBox. Tried it 3 times installation to make sure haha. Maybe there is some bug with VM Network that make connection unreliable so the hash is not consistent.
