### ISSUE TITLE
Snapcast client

### ISSUE THREAD

**Issue by maweki** [MichaIng/DietPi#517]
Snapcast is a solution to play synchronized audio on multiple devices. It even supports multiroom using multiple servers.

I already created an ansible playbook to install snapcast client (the one that plays the audio). Since most of the clients I want to install it to, will be running dietpi anyways, would it be time well spent for me if I would create an installer for dietpi-software? Is this something you would merge, if the quality was ok?

Project: https://github.com/badaix/snapcast

**Comment by Fourdee** [comment]
@maweki 

We currently have shairport-sync (airplay) installation in DietPi, which does multiroom sync: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=1221#p1221

>  Is this something you would merge, if the quality was ok?

By all means, go for it 👍 . If there are any issues, I'll let you know so they can be resolved.

Info:
- https://github.com/Fourdee/DietPi/issues/490#issuecomment-244416570 (how to add software to dietpi-software script)
- Use the testing branch for your work, and send the pull request there aswell please: https://github.com/Fourdee/DietPi/tree/testing

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by Jaffa** [comment]
> Once interest peaks, we'll reopen once work starts.

I'd love to have this for a multi-room audio set up inspired by https://www.reddit.com/r/homeautomation/comments/7jb3da/multiroom_audio_setup_w_mopidy_pulseaudio_and/

Currently, you have to download the deb from https://gist.github.com/gotling/9310f2572e1ea9c9d685c4ce5807001a and faff about with dependency correction.
