### ISSUE TITLE
Pydio - inputfilter.php - magic_quotes_gpc() is deprecated error. 

### ISSUE THREAD

**Issue by satnair** [MichaIng/DietPi#5171]
### Creating a bug report/issue

DietPi 8 latest version - 8.2.3 version
Pydio running on raspberry 400
inputfilter.php - function get_magic_quotes_gpc() is deprecated. 

Doesn't load any workspace , user access etc. Please help.

**Comment by MichaIng** [comment]
Many thanks for your report.

Can you please full the bug report template, most importantly Debian version, hardware and OS architecture, so that we are able to try replicating it? Also which webserver do you use?

Usually a deprecation warning shouldn't break anything, is this the only error you see in Pydio, webserver error logs and browser console?

**Comment by satnair** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/497374/149633546-99a51b2d-d49e-42d0-97fe-c6369ee2a9d8.png">

I use dietpi v 8.2.3
raspberry pi 400 version
64 bit arch

I am seeing this as error in the logs output. Because of this when I try to access user details (for example) nothing shows up.

**Comment by satnair** [comment]
Server logs here 
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/497374/149633656-e36e08ee-cf7e-49cb-b517-71f71c44ab43.png">

**Comment by Joulinar** [comment]
Just as a side note, there is not DietPi version 8.2.3 existing. Lates version is 8.0.2

**Comment by MichaIng** [comment]
> I am seeing this as error in the logs output. Because of this when I try to access user details (for example) nothing shows up.

You mean the Pydio logs, right? Why do you think that the deprecation warning is the reason for the other pages not showing up? As said, it is a warning/notice for developers that they should switch to a modern method/function by times, hence something to report to Pydio devs, but shouldn't cause any actual failure. Can you please show the browser console logs when trying to access a failing Pydio page?

I'll also try to replicate now.

**Comment by MichaIng** [comment]
Okay before investing too much time into Pydio Core, we should instead migrate to Pydio Cells, the standalone (written in Go) replacement: #3469

I can see the warning, however it does not effect functionality. Can you be a bit more precise which page/feature does not work?

What I did find is that the internal updater does not work as of some false file owner and modes. To fix this:
```sh
chown -R www-data:www-data /var/www/pydio
chmod -R u+w /var/www/pydio
```
Then you can update from v8.2.3 to v8.2.5.

**Comment by satnair** [comment]
Great thanks. Also, looks like a PHP compatibility issue. I will check this. Thanks.

**Comment by MichaIng** [comment]
I fixed the permissions:
- https://github.com/MichaIng/DietPi/commit/355a5c3
- https://github.com/MichaIng/DietPi/commit/a98adda

But aim to replace with Pydio Cells for next release as linked above.
