### ISSUE TITLE
RPi | Mirror director is unreliable and unstable

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#518]
Slow connections, unstable, unreliable, was offline this Sunday.

Resolution, we will use the Oxford UK mirror by default:

```
deb http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian jessie main contrib non-free rpi
```

I did look at hosting a mirror on DietPi.com. But I dont have 250GB+ space they recommend: https://www.raspbian.org/RaspbianMirrors

**Comment by Fourdee** [comment]
Default on v131 RPi images.

**Comment by tobohr** [comment]
Hey @Fourdee 
http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian
Today this mirror is down instead... shouldn't there be a fallback?

Thanks!

**Comment by Fourdee** [comment]
@tobohr 

Thanks for the report 👍 

Please this here for solution to change APT mirror in DietPi:
https://twitter.com/DietPi_/status/886553385255751681

**Comment by WolfganP** [comment]
It's always a good practice to use a mirror close to your geographical location. Officials are listed at https://www.raspbian.org/RaspbianMirrors
I used to change manually, but now I know there's another config solution integrated. Great work @Fourdee !
