### ISSUE TITLE
Release v131

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#520]
- 🈯 dietpi.com | move images in testing (http://dietpi.com/downloads/testing/) to live
- 🈯 dietpi.com | add entry for OPi One download
- 🈯 AmiBerry image test: completed.

**Comment by Fourdee** [comment]
@Midwan

Here are the current v2 installed binaries, and their creation date (should be latest):

```
-rwxr-xr-x  1 root root 1.3M Sep 13 21:48 uae4arm-rpi1
-rwxr-xr-x  1 root root 1.4M Sep 13 21:49 uae4arm-rpi2
-rwxr-xr-x  1 root root 1.4M Sep 13 21:48 uae4arm-rpi3
```

Would you also be able to test the updated AmiBerry image installation (works for me, but would like the go ahead from you): http://dietpi.com/downloads/testing/DietPi-AmiBerry_RPi-armv6-(Jessie).7z ?

Includes these main tickets: 
- https://github.com/Fourdee/DietPi/issues/513
- https://github.com/Fourdee/DietPi/issues/518
- https://github.com/Fourdee/DietPi/issues/502
- https://github.com/Fourdee/DietPi/issues/501 Auto mounts 1 drive to `/mnt/usb_1` when plugged in

**Comment by midwan** [comment]
@Fourdee I'll be testing these tonight.
Meanwhile, another bug in the GUI navigation was reported earlier today, so I'd like to fix that as well and provide you with new binaries. It should be ready later tonight or tomorrow at the latest, if that's ok?

**Comment by Fourdee** [comment]
@midwan 

> It should be ready later tonight or tomorrow at the latest, if that's ok?

If you can get it to me before tomorrow evening, all good and i'll update it before release 👍

**Comment by midwan** [comment]
Done!

**Comment by midwan** [comment]
@Fourdee 
New binaries are now uploaded. These include the fixes for the keyboard Navigation in the GUI, which caused freezes.

**Comment by Fourdee** [comment]
@midwan 

👍 
New zip uploaded. I will run a test AmiBerry image installation before release.
