### ISSUE TITLE
No soundcard

### ISSUE THREAD

**Issue by jimmyhenne** [MichaIng/DietPi#5221]
Hey,
I'm running DietPi 8.0.2 on Buster and myMPD stopped working, to be more clear it prompts "Failed to open "DietPi Alsa" (alsa); Failed to open ALSA device "default": No such file or directory" when clicking on play.
I did some research, but can't solve it since my knowledge isn't that good. 
In DietPi-config Audio is set to rcpi-bcm2835-hdmi but when I want to run the ALSA output Info of dietpi-justboom I get the error "cat: '/proc/asound/card*/pcm0p/sub0/hw_params': No such file or directory". 
aplay -l can't find a soundcard:
root@DietPi:~# aplay -l
aplay: device_list:272: keine Soundkarten gefunden ...

apt install alsa-utils doesn't help either.

Thanks for help

Edit: Reset display resolution and reset sound card and it works again although I have already done that before :-)

**Comment by MichaIng** [comment]
Probably you enabled a KMS driver? In this case the HDMI audio device changes from firmware one to KMS one. `rpi-bcm2835-hdmi` however should work for both applying the same audio `card 0`, hence after a reboot it should work the same way 🤔. The logic however is complicated when toggling KMS and sound cards, hence probably I missed a toggle path which hence currently leads to no sound card enabled unexpectedly.
