### ISSUE TITLE
DietPi-Config | Disabel the Wifi Hotspot dont work.

### ISSUE THREAD

**Issue by MaxPeal** [MichaIng/DietPi#5224]
### Creating a bug report/issue
i have enabled and used the Wifi Hotspot, now i want to disable it via:
Run dietpi-config
Navigate to Networking Options: Adapters, then select WiFi, than State, and finally back.

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
  bullseye 0
- Kernel version | `uname -a`
`Linux DietPi-01 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
  RPi 4 Model B (aarch64)

#### Additional Information (if applicable)
- Software title | hotspot
- Was the software title installed freshly or updated/migrated?

#### Actual behaviour
the hotspot is still enabled
also reboot dont help

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
