### ISSUE TITLE
I'm trending ❤️ to my followers 👍

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#5241]
I was made aware that I'm "trending" on GitHub 😮. Not exactly sure how the ranking is done, I guess based on daily/weekly/monthly new followers, or does the repos we are contributing to play a role as well? At time of writing:
- Top 15 overall developer this week: https://github.com/trending/developers?since=weekly
- Top 6 overall developer today: https://github.com/trending/developers?since=daily
- Top 2 shell developer today: https://github.com/trending/developers/shell?since=daily
- Top 1 shell developer this week: https://github.com/trending/developers/shell?since=weekly
- Top 1 shell developer this month: https://github.com/trending/developers/shell?since=monthly
- 737 followers: https://github.com/MichaIng?tab=followers

You are awesome and crazy guys, this makes me proud 😊. However, sadly DietPi is not ranking in top 25 anywhere. If you follow me, check out this repository and the [DietPi OS](https://dietpi.com/) on your server systems. Give this repository a ⭐ when you like it. Nearly all my activity on GitHub is directly or indirectly related to DietPi 😉.

**Comment by GvY85** [comment]
Well deserved and DietPi is awesome for any SBC or headless home server
