### ISSUE TITLE
DietPi-Software | Apache2 fails to start

### ISSUE THREAD

**Issue by Camry2731** [MichaIng/DietPi#5248]
#### Required Information
- DietPi version | 8.1.2
- Distro version | Bullseye
- Kernel version | 5.10.0-9
- SBC model | Virtual Machine (x86_64)
- Power supply used | N/A
- SD card used | N/A

#### Additional Information (if applicable)
- Software title | Apache2
- Was the software title installed freshly or updated/migrated? | Fresh
- Can this issue be replicated on a fresh installation of DietPi? | Yes

- Bug report ID | 05bf8268-5a23-4f25-8d4d-930bad903aa2

#### Steps to reproduce

1. Import VM into VirtualBox and start. (Note: I had to change the graphics controller from what it was set to, which was VboxVGA, to VMSVGA for it to boot, which is another issue)
2. Install WordPress and select Apache2 as the webserver
3. Check the status of Apache2 and it says "failed"

#### Expected behaviour

- Apache2 should start

#### Actual behaviour

- Apache2 is not starting

#### Extra details

- Attempted multiple times. I rebooted various times. Log attached below. I thought maybe it couldn't get a valid IP, but it connects to the internet fine and the IP is OK. Running G_GET_NET manually ip yields my IP, so unsure of what the issue is
![VirtualBox_DietPi_VirtualBox-x86_64-Bullseye_07_02_2022_11_55_23](https://user-images.githubusercontent.com/9684719/152835485-04f7bc43-ed0b-4eeb-a265-2f8e87b24a45.png)
![VirtualBox_DietPi_VirtualBox-x86_64-Bullseye_07_02_2022_12_04_26](https://user-images.githubusercontent.com/9684719/152836255-3af14200-baa1-4771-8714-1abff3929ac9.png)

**Comment by Joulinar** [comment]
As workaround, you could replace the variable with your IP to inside the configuration file and restart Apache afterwards.

**Comment by MichaIng** [comment]
Many thanks for reporting.

Indeed a bug our end. The command substitution was meant literally. Looks like we missed a fresh install test, hence without the config existing yet. Fixed with: https://github.com/MichaIng/DietPi/commit/b371fcd

I'll send a live patch for current release as well.

**Comment by MichaIng** [comment]
Live patch merged as well. Let's keep the issue open and pinned for some days, just in case others stumble over the same.

**Comment by MichaIng** [comment]
Marking this as closed now. With the live patch, all new and updated DietPi systems from now on are patched automatically. Since this issue appears immediately on fresh Apache2 installs, there shouldn't be any users which did the install before the patch went live and recognise the issue just now 😉.
