### ISSUE TITLE
[Bug] Folding at home installed through Automated install not in dietpi-software list

### ISSUE THREAD

**Issue by eyduh** [MichaIng/DietPi#5255]
Hi,

I accidentally installed folding at home during an automated install of a few things, but when I tried to uninstall it `dietpi-software` couldn't find it. So, I tried to "install" it using `dietpi-software` tui and was met with this error message below:

Bug reference code:

cdee7712-7a34-4441-9a0c-86e1da5efcdd

#### Details:
- Date           | Tue Feb  8 16:41:47 CET 2022
- Bug report     | cdee7712-7a34-4441-9a0c-86e1da5efcdd
- DietPi version | v8.1.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux dietprints0 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `systemctl stop FAHClient`
- Exit code      | 5
- Software title | DietPi-Software
#### Steps to reproduce:

1. Add the line "AUTO_SETUP_INSTALL_SOFTWARE_ID=2" for a fresh install
2. Check for fahclient in htop or dietpi-services
3. try to uninstall using `dietpi-software` tui or `dietpi-software uninstall 2`
4. fahclient is "not" installed
5. try to install using `dietpi-software` tui or `dietpi-software install 2`
6. "Failed to stop FAHClient.service: Unit FAHClient.service not loaded."
#### Expected behaviour:

- fahclient shows up in tui or is uninstalled with the cli version
#### Actual behaviour:

- fahclient cannot be uninstalled nor installed using dietpi-software
#### Extra details:

- ~I can't remember where the file is that is parsed for dietpi-software but I presume the problem lies therein.~
- I added `aSOFTWARE_INSTALL_STATE[2]=2` to `/boot/dietpi/.installed and could uninstall fine. I'll leave this open as I'm not sure why it wasnt added during the Autoinstall at firstboot.
#### Additional logs:
```
Failed to stop FAHClient.service: Unit FAHClient.service not loaded.
```
---------------------------------------------------------------------

**Comment by eyduh** [comment]
I edited `/boot/dietpi/.installed` and added the relevant lines so that I could uninstall it but I'll leave this open until we've figured out why it occured in the first place

**Comment by MichaIng** [comment]
Many thanks for your report.

Can you show the output of:
```sh
dietpi-software list | grep 'Folding@Home'
cat /var/tmp/dietpi/logs/dietpi-firstboot.log
```

Were other installed software titles added to `/boot/dietpi/.installed`?

**Comment by eyduh** [comment]
The first one shows that it isnt installed now that I already changed .installed:
```
$ sudo dietpi-software list | grep 'Folding@Home'
ID 2 | =0 | Folding@Home: distributed disease research project | | https://dietpi.com/docs/software/distributed_projects/#foldinghome
```
However, I scrolled up through my terminal and found a previous one I did before the fix:
```
$ sudo dietpi-software list | grep folding
ID 2 | =0 | Folding@Home: distributed disease research project | | https://dietpi.com/docs/software/distributed_projects/#foldinghome
```

firstboot log:
```
$ cat /var/tmp/dietpi/logs/dietpi-firstboot.log
[  OK  ] DietPi-FirstBoot | Setting in /boot/config.txt adjusted: temp_limit=75
[ INFO ] DietPi-FirstBoot | Running custom script, please wait...
adduser: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
[  OK  ] DietPi-FirstBoot | Custom script
[ SUB1 ] DietPi-Set_swapfile > Applying 1 /var/swap
[ INFO ] DietPi-Set_swapfile | Disabling and deleting all existing swap files
[ .... ] DietPi-Set_swapfile | swapoff -a
[  OK  ] DietPi-Set_swapfile | swapoff -a
[  OK  ] DietPi-Set_swapfile | Free space check: path=/var/ | available=28023 MiB | required=1089 MiB
[  OK  ] DietPi-Set_swapfile | Generating new swap space
[ INFO ] DietPi-Set_swapfile | Size = 1089 MiB
[ INFO ] DietPi-Set_swapfile | Path = /var/swap
[ .... ] DietPi-Set_swapfile | fallocate -l 1089M /var/swap
[  OK  ] DietPi-Set_swapfile | fallocate -l 1089M /var/swap
[ .... ] DietPi-Set_swapfile | mkswap /var/swap
[  OK  ] DietPi-Set_swapfile | mkswap /var/swap
[ .... ] DietPi-Set_swapfile | swapon /var/swap
[  OK  ] DietPi-Set_swapfile | swapon /var/swap
[ .... ] DietPi-Set_swapfile | chmod 0600 /var/swap
[  OK  ] DietPi-Set_swapfile | chmod 0600 /var/swap
[ .... ] DietPi-Set_swapfile | eval echo '/var/swap none swap sw' >> /etc/fstab
[  OK  ] DietPi-Set_swapfile | eval echo '/var/swap none swap sw' >> /etc/fstab
[  OK  ] DietPi-Set_swapfile | Setting in /boot/dietpi.txt adjusted: AUTO_SETUP_SWAPFILE_SIZE=1089
[  OK  ] DietPi-Set_swapfile | Desired setting in /boot/dietpi.txt was already set: AUTO_SETUP_SWAPFILE_LOCATION=/var/swap
[ INFO ] DietPi-Set_swapfile | Setting /tmp tmpfs size: 1024 MiB
[ .... ] DietPi-Set_swapfile | mount -o remount /tmp
[  OK  ] DietPi-Set_swapfile | mount -o remount /tmp
[ INFO ] DietPi-FirstBoot | Setting time zone Europe/Amsterdam. Please wait...
removed '/etc/localtime'

Current default time zone: 'Europe/Amsterdam'
Local time is now:      Wed Dec 15 16:49:06 CET 2021.
Universal Time is now:  Wed Dec 15 15:49:06 UTC 2021.

[ INFO ] DietPi-FirstBoot | Setting keyboard layout us. Please wait...
[  OK  ] DietPi-FirstBoot | Setting in /etc/default/keyboard adjusted: XKBLAYOUT="us"
[ SUB1 ] DietPi-Set_hardware > headless (enable)
[  OK  ] DietPi-Set_hardware | Comment in /boot/config.txt converted to setting: max_framebuffers=0
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already set: disable_splash=1
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already set: hdmi_blanking=1
[  OK  ] DietPi-Set_hardware | Comment in /boot/config.txt converted to setting: hdmi_ignore_hotplug=1
[ .... ] DietPi-Set_hardware | sed -i /^[[:blank:]]*enable_tvout=/c\#enable_tvout=0 /boot/config.txt
[  OK  ] DietPi-Set_hardware | sed -i /^[[:blank:]]*enable_tvout=/c\#enable_tvout=0 /boot/config.txt
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/dietpi.txt was already set: AUTO_SETUP_HEADLESS=1
[  OK  ] headless enable | Completed
[ SUB1 ] DietPi-Set_hardware > eth-forcespeed (disable)
[  OK  ] eth-forcespeed disable | Completed
[  OK  ] DietPi-Change_hostname | Setting in /etc/hosts adjusted: 127.0.1.1 dietprints0
[ .... ] DietPi-Change_hostname | eval echo 'dietprints0' > /etc/hostname
[  OK  ] DietPi-Change_hostname | eval echo 'dietprints0' > /etc/hostname
[ .... ] DietPi-Change_hostname | hostname dietprints0
[  OK  ] DietPi-Change_hostname | hostname dietprints0
[ SUB1 ] DietPi-Set_software > apt-mirror (https://deb.debian.org/debian/)
[ .... ] DietPi-Set_software | eval echo 'deb https://archive.raspberrypi.org/debian/ bullseye main' > /etc/apt/sources.list.d/raspi.list
[  OK  ] DietPi-Set_software | eval echo 'deb https://archive.raspberrypi.org/debian/ bullseye main' > /etc/apt/sources.list.d/raspi.list
[ .... ] DietPi-Set_software | eval echo 'deb https://deb.debian.org/debian/ bullseye main contrib non-free
deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb https://deb.debian.org/debian-security/ bullseye/updates main contrib non-free
deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free' > /etc/apt/sources.list
[  OK  ] DietPi-Set_software | eval echo 'deb https://deb.debian.org/debian/ bullseye main contrib non-free
deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb https://deb.debian.org/debian-security/ bullseye/updates main contrib non-free
deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free' > /etc/apt/sources.list
[ .... ] DietPi-Set_software | sed -i 3s|/updates|-security| /etc/apt/sources.list
[  OK  ] DietPi-Set_software | sed -i 3s|/updates|-security| /etc/apt/sources.list
[  OK  ] DietPi-Set_software | Desired setting in /boot/dietpi.txt was already set: CONFIG_APT_DEBIAN_MIRROR=https://deb.debian.org/debian/
[  OK  ] apt-mirror https://deb.debian.org/debian/ | Completed
removed '/etc/dropbear/dropbear_ecdsa_host_key'
Generating 256 bit ecdsa key, this may take a while...
Public key portion is:
ecdsa-sha2-nistp256 blargh root@dietprints0
Fingerprint: sha1!! 50:5e:4d:a1:cf:95:62:2a:2c:3a:38:9d:1d:81:c8:7c:37:06:ee:42
removed '/etc/dropbear/dropbear_ed25519_host_key'
Generating 256 bit ed25519 key, this may take a while...
Public key portion is:
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICcwZCzZvygJOVSFnsUS6Hre55k868+eiC2g7HmXBF7z root@dietprints0
Fingerprint: sha1!! 24:43:2a:25:e9:9c:26:5b:d4:9a:a2:bd:2e:da:c8:c2:67:e5:2f:1b
removed '/etc/dropbear/dropbear_rsa_host_key'
Generating 2048 bit rsa key, this may take a while...
Public key portion is:
ssh-rsa blargh blargh@dietprints0
Fingerprint: sha1!! 2f:96:8c:31:f7:40:5a:6d:f4:3a:2a:bd:bf:a0:63:5c:82:ce:3c:3c
Initializing machine ID from random generator.
[ SUB1 ] DietPi-Set_hardware > wifimodules (disable)
[  OK  ] DietPi-Set_hardware | Added setting dtoverlay=disable-wifi to end of file /boot/config.txt
[  OK  ] wifimodules disable | Completed
[ SUB1 ] DietPi-Set_hardware > enableipv6 (enable)
[  OK  ] DietPi-Set_hardware | Desired setting in /etc/hosts was already set: ::1 localhost ip6-localhost ip6-loopback
[  OK  ] DietPi-Set_hardware | Desired setting in /etc/hosts was already set: ff02::1 ip6-allnodes
[  OK  ] DietPi-Set_hardware | Desired setting in /etc/hosts was already set: ff02::2 ip6-allrouters
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/dietpi.txt was already set: CONFIG_ENABLE_IPV6=1
[  OK  ] enableipv6 enable | Completed
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/dc:a6:32:16:75:90
Sending on   LPF/eth0/dc:a6:32:16:75:90
Sending on   Socket/fallback
Created duid "\000\001\000\001)L\312\366\334\2462\026u\220".
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 1
DHCPOFFER of 192.168.178.47 from 192.168.178.1
DHCPREQUEST for 192.168.178.47 on eth0 to 255.255.255.255 port 67
DHCPACK of 192.168.178.47 from 192.168.178.1
bound to 192.168.178.47 -- renewal in -4309390 seconds.
[ SUB1 ] DietPi-Set_software > boot_wait_for_network (1)
[  OK  ] DietPi-Set_software | Desired setting in /boot/dietpi.txt was already set: AUTO_SETUP_BOOT_WAIT_FOR_NETWORK=1
[  OK  ] boot_wait_for_network 1 | Completed
Removed /etc/systemd/system/multi-user.target.wants/dietpi-firstboot.service
```
Looking at this it seems it's not the whole logs?

**Comment by eyduh** [comment]
> Ah sorry that was the wrong one from early pre-network boot stage. This is the right one:
> 
> ```shell
> cat /var/tmp/dietpi/logs/dietpi-firstrun-setup.log
> ```
[dietpi-firstrun-setup.log](https://github.com/MichaIng/DietPi/files/8025955/dietpi-firstrun-setup.log)


Attached.

**Comment by eyduh** [comment]
But probably cause of failed custom scripts. Also attached.
[Automation_Custom_scripts_x2.zip](https://github.com/MichaIng/DietPi/files/8025966/Automation_Custom_scripts_x2.zip)

Basically I was lazy and wanted the last step of this setup to happen while I went to bed but ended up doing it manually anyway since they obviously failed lol. I'm gonna bake them into some `if fi` statements next time.

**Comment by MichaIng** [comment]
The custom script is called after `.installed` is written. Also the steps involved with custom scripts have an error handler flag to not abort `dietpi-software`. The error is printed but the script finishes regardless.

You seem to have repeated the first run setup, probably as of the pip failure when MotionEye was tried to be installed, but did not select Folding@Home at the second go. When `dietpi-software` is aborted due to an error, the `.installed` file is not written, so all software should be re-selected, even that some may have been practically installed already, i.e. packages, services etc. Not 100% great but in some cases there are shared post install steps done, like disabling headless mode and increasing GPU memory on RPi, unmasking `systemd-logind` and other software dependant dialogues. So to assure those are covered it makes sense to repeat all installs in case of a failure with script abortion.

Ah, to fix the reason why Folding@Home (re)install fails:
```sh
sed -i '/G_EXEC systemctl stop FAHClient/d' /boot/dietpi/dietpi-software
dietpi-software install 2
```

**Comment by eyduh** [comment]
> So to assure those are covered it makes sense to repeat all installs in case of a failure with script abortion.

Yeah when I ssh'd into the machine it asked me to "Take over" the first run and I didn't select Folding@Home then because I just added all the things off the top of my head, not by the numbers in dietpi.txt. Since I had accidently put Folding@Home (dietpi-software 2) instead of something else I missed it.

Would be nice if the "Take Over" option listed the autoinstalls from dietpi.txt using something like 
cat /boot/dietpi.txt | grep AUTO_SETUP_INSTALL_SOFTWARE_ID= | awk -F = '{print $NF}

**Comment by MichaIng** [comment]
Okay, so then all is explained. The "Take over" option is a generic one, not related to a failure specifically in `dietpi-software` but on any failure during first run setup, including the initial `dietpi-update` or when anything else within the login script fails, e.g. reading globals or when the install stage is invalid. So listing the previously selected software titles there would often not apply, hence be confusing. I think it is generally fine. If there is an error, intentionally installs run interactively so one is able to see and handle errors. And generally if a software title was forgotten, it can be installed any time later. In your case it was just nasty that this (re)install of Folding@Home failed, but that has been fixed now 🙂.

In theory, what we could do is storing the intermediate software install states, i.e. `=1` for to be installed and `=-1` for to be uninstalled, at least when the script is about to exit due to error. So the selections remain when `dietpi-software` is started again and one can hit `Install` directly without needing to repeat the selection. Generally those states could be also stored directly to the persistent file once installs start. We just need to assure that `=1` is correctly treated as "not installed" everywhere outside of `dietpi-software`, but I think we are pretty explicit, checking for `=2`.
