### ISSUE TITLE
Pine A64 | Bluetooth support for add-on module

### ISSUE THREAD

**Issue by pfeerick** [MichaIng/DietPi#528]
[I'll add the link here to the pine64 forum post once it is available]

When trying to enable on the Bluetooth on the DietPi distro using the same steps that worked for the Debian Jessie distro, I had no luck. You can see the [steps needed here (from my notes)](https://www.evernote.com/shard/s1/sh/cb4b9f07-e182-4abf-8ee3-5db105192626/3a8d6c901cc8acab). 

I have come to believe after examining the `start_bt.sh` script further that that it may not be working as the kernel config flag "CONFIG_SERIAL_8250" is not set, and is apparently needed for this to work. 

Firmware binaries, start_bt.sh, etc were sourced from this repo: https://github.com/lwfinger/rtl8723bs_bt

**Comment by MichaIng** [comment]
@pfeerick 
Is the issue and procedure still current?

@Fourdee 
As far as I can see, we do not support bluetooth on Pine64. If there is still no native/repo support for this, it is a bid more to do then for the other devices, but maybe worth trying, setting kernel config flag included, if it (still) works?

**Comment by Fourdee** [comment]
@MichaIng 

I'll run a test today.

Yep, still broken.

---

```
G_AGI build-essential
wget https://github.com/lwfinger/rtl8723bs_bt/archive/master.zip -O package.zip
unzip package.zip
rm package.zip

cd rtl8723bs*
make -j $(nproc --all)
make install
```

Builds fine, but still hangs on BT
```
root@DietPi:~/rtl8723bs_bt-master# ./start_bt.sh
Using device /dev/at MM for Bluetooth
root@DietPi:~/rtl8723bs_bt-master# bluetoothctl
Waiting to connect to bluetoothd...
```

- Maybe ```CONFIG_SERIAL_8250``` is disabled, unsure, cant find any kernel configuration listed on https://github.com/ayufan-pine64/linux-build

**Comment by MichaIng** [comment]
@Fourdee 
The link provided by @pfeerick includes some other steps after `start_bt.sh`: https://www.evernote.com/shard/s1/sh/cb4b9f07-e182-4abf-8ee3-5db105192626/3a8d6c901cc8acab
- "...it configures the BT module and makes it available for use": `./rtk_hciattach -n -s 115200 /dev/ttyS1 rtk_h5 &` (needs to run in background, hmm serial tty needs to be active, then (?)...)
- "Remove soft block, scan for devices": `rfkill list`, then `rfkill unblock <bt_deviceID>` in case

**Comment by MichaIng** [comment]
@Fourdee 
Maybe we can pick this up again, if you find time to test with the steps provided in the link above?
Sadly I cannot test all the WiFi and BT stuff, however about the other WiFi (multiple SSID) topic, I can provide the initial dietpi-config/set_hardware menus/additions, when solution is chosen 😃.

**Comment by MichaIng** [comment]
Pine A64 image has been updated and is now based on ARMbian with different (newer) kernel. Perhaps the above works now.

And we have to take care here as well that neither the kernel cmd line nor systemd blocks /dev/ttyS1 for boot messages and/or as login console: https://github.com/MichaIng/DietPi/issues/2607

**Comment by MichaIng** [comment]
New Buster-based image available for testing: https://dietpi.com/downloads/testing/DietPi_PineA64-ARMv8-Buster.7z
Since there have been vast changes in kernel, system etc. this should or needs to be simply retested, following the linked guide and drivers. If it hangs even after error-free build and verifying that used UART device is not in other use and not blocked and listens to the correct hardware connectors, it should be reported to the drivers repo. I mark this as closed, as it is hence no DietPi-specific issue.
