### ISSUE TITLE
DietPi-Software | KOHA library software

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#5283]
### Discussed in https://github.com/MichaIng/DietPi/discussions/5282

<div type='discussions-op-text'>

<sup>Originally posted by **uid65252** February 15, 2022</sup>
#### Formal software information
- Software title | KOHA library software
- Short description | 
- Official URL (if available) | https://koha-community.org/
- GitHub URL (if available) | 
- (Official) install documentation | 

#### Are there similar/alternative software titles available with DietPi-Software?

- ...

#### What makes your requested software better than the above solutions, if available?

- ...

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- i cannot install it with DietPi running

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

1. https://wiki.koha-community.org/wiki/Debian#E-mail

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.

- ...
</div>

**Comment by MichaIng** [comment]
Check out my steps here: https://github.com/MichaIng/DietPi/discussions/5282#discussioncomment-2182258
I have a working instance now. Let's keep discussion over there from now on.
