### ISSUE TITLE
Dietpi-Software : problems with Docker-Compose / Portainer

### ISSUE THREAD

**Issue by echtfrank** [MichaIng/DietPi#5290]
#### Required Information
- DietPi version | 
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=1
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'
G_LIVE_PATCH_STATUS[1]='applied'
G_LIVE_PATCH_STATUS[2]='not applicable'
G_LIVE_PATCH_STATUS[3]='not applicable'cat /boot/dietpi/.version
- Distro version | bullseye
- Kernel version | `Linux biblio 4.9.241-arm64 #1 SMP PREEMPT Thu Feb 25 17:57:15 CET 2021 aarch64 GNU/Linux`
- SBC model | `Odroid C4/HC4 (aarch64)
- Power supply used | 12V 4A Hardkernel
- SD card used | SanDisk Ultra 32GB

#### Additional Information (if applicable)
- Software title | Docker-Compose from within Portainer
- Was the software title installed freshly or updated/migrated? The Docker-stack was installed with errors earlier. Last install gave no errors.
- Can this issue be replicated on a fresh installation of DietPi? unknown

- Bug report ID | c4a9d489-3f0b-4bd1-9437-d754bb569dd2

#### Steps to reproduce

1. Create a stack 'duplicati' using Docker-Compose in Portainer.

#### Expected behaviour

- The stack would have been created, including containers, a docker-network and docker-volumes.

#### Actual behaviour

- Within Portainer a network-error came (I was not able to note it down); the stack was not created, neither where the containers, and the network, nor a volume.

#### Extra details

Attached 3 files:

[1_systemctl_docker_20220217.log](https://github.com/MichaIng/DietPi/files/8087847/1_systemctl_docker_20220217.log)
Containing the output from systemctl -status docker.

After that I decided to reinstall Docker and Portainer; that gave errors:
[2_screenshot_sudo_dietpi-reinstall_reinstall_162_185_20220217.txt](https://github.com/MichaIng/DietPi/files/8087848/2_screenshot_sudo_dietpi-reinstall_reinstall_162_185_20220217.txt)

After that I decided to reinstall Docker-compose as well; wich gave errors also:
[3_sudo_dietpi-reinstall_reinstall_134_20220217.log](https://github.com/MichaIng/DietPi/files/8087846/3_sudo_dietpi-reinstall_reinstall_134_20220217.log)

Note, that Jellyfin is metioned in the log's. That was working alright, behind NGINX reverse-proxy. Both Nextcloud as Jellyfin where working correctly and could be reached from the internet by subfolders.

**Comment by Joulinar** [comment]
You have an issue to reinstall Python. This has nothing to do with Docker directly. Probably you tried to reinstall Docker-Compose. But for install/reinstall of Portainer, Docker-Compose is not needed. You should be able to due it without. BTW: for Docker-Compose, we will switch to v2 on next release and move to the new Go version instead of the Python one.

Jellyfin is probably a different issue. Maybe better to open a separate issue on this,

**Comment by MichaIng** [comment]
Never ending story with setuptools issues while they are migrating away from distutils 😄. Probably it has been solved already and the old version causes these uninstall issues. Not sure whether an upgrade works?
```sh
pip3 install -U setuptools
```

Not sure how the Jellyfin status went into the logs during DietPi-BugReport processing, a copy&paste issue or did it indeed show up like this while the bug report was generated?

Docker itself seems to run fine

**Comment by echtfrank** [comment]
Bypassing "pip3 uninstall -y setuptools" as @Joulinar suggested, helped a lot. (Un/installation of docker-compose went well.
But creating a stack went wrong; I think it went wrong creating a docker-network - maybe something wrong with a firewall,
I'll keep you posted.

**Comment by Joulinar** [comment]
the initial issue has been fixed right? And we could close this one?

**Comment by echtfrank** [comment]
Yes! Can be closed. Thank you very much.
