### ISSUE TITLE
Cannot Uninstall Portainer

### ISSUE THREAD

**Issue by minusplus8** [MichaIng/DietPi#5327]
### Details:
- Date           | Wed Mar  2 16:18:52 EST 2022
- DietPi version | v8.1.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | From scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi4 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `docker rmi 8000bafa387b`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:

1. ... Uninstall Portainer from Dietpi
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Error response from daemon: conflict: unable to delete 8000bafa387b (cannot be forced) - image is being used by running container 1d36e81c665f

**Comment by Joulinar** [comment]
Hi,

can you share following

```
docker container ls
docker image ls
```

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
