### ISSUE TITLE
Problem to upgrade 8.2.2.

### ISSUE THREAD

**Issue by maury77** [MichaIng/DietPi#5345]
#### Details:
- Date           | Wed Mar  9 07:02:16 CET 2022
- Bug report     | 3367cd8d-87ca-4a59-85e9-807a4979358e
- DietPi version | v8.1.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspbian Lite
- Hardware       | RPi 3 Model B+ (armv7l) (ID=3)
- Kernel version | `Linux sdomotica 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `apt-get -q update`
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Ign:1 https://dtcooper.github.io/raspotify jessie InRelease
Err:2 https://dtcooper.github.io/raspotify jessie Release
  404  Not Found [IP: 185.199.110.153 443]
Get:3 https://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Hit:4 https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable InRelease
Hit:5 https://openhab.jfrog.io/openhab/openhab-linuxpkg stable InRelease
Get:6 https://archive.raspberrypi.org/debian bullseye/main armhf Packages [257 kB]
Get:7 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:8 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Reading package lists...
E: The repository 'https://dtcooper.github.io/raspotify jessie Release' no longer has a Release file.
W: Skipping acquire of configured file 'main’/binary-armhf/Packages' as repository 'https://openhab.jfrog.io/openhab/op

**Comment by Joulinar** [comment]
You are using quite an old repository for Raspotify, which is failing now

```
Err:2 https://dtcooper.github.io/raspotify jessie Release
  404  Not Found [IP: 185.199.110.153 443]
E: The repository 'https://dtcooper.github.io/raspotify jessie Release' no longer has a Release file.
```

It's still Debian Jessie, while your system is already running Debian Bullseye. You can try following to update the list

```
eval "echo 'deb https://dtcooper.github.io/raspotify/ raspotify main' > /etc/apt/sources.list.d/raspotify.list"
```

**Comment by neilsmall** [comment]
Received the same error today when running the "Run now to update DietPi from v8.1.2 to v8.2.2"

![image](https://user-images.githubusercontent.com/43247563/157750895-44b707c6-e37f-49ee-bd7f-d0dae9aff31d.png)

**Comment by MichaIng** [comment]
"Structure needs cleaning" usually indicates a filesystem errors. Please try to clean it on reboot:
```sh
> /forcefsck
reboot
# after reboot check logs
journalctl -t systemd-fsck
```

**Comment by Joulinar** [comment]
yes, it's not the same issue. Complete different one. Maybe we should move it to an own issue.

**Comment by neilsmall** [comment]
> "Structure needs cleaning" usually indicates a filesystem errors. Please try to clean it on reboot:
> 
> ```shell
> > /forcefsck
> reboot
> # after reboot check logs
> journalctl -t systemd-fsck
> ```

Thanks - I'll do this later. I had to re-image the SD Card 'cause my Roon Bridge endpoint got trashed; off to a meeting. I'll get back later. Cheers.

**Comment by neilsmall** [comment]
> "Structure needs cleaning" usually indicates a filesystem errors. Please try to clean it on reboot:
> 
> ```shell
> > /forcefsck
> reboot
> # after reboot check logs
> journalctl -t systemd-fsck
> ```

After reboot, the update worked correctly. Thanks.

![image](https://user-images.githubusercontent.com/43247563/157756632-f7358b26-d7b9-4eca-88ab-78987d38589c.png)

**Comment by MichaIng** [comment]
Interesting, since there were no errors found or resolved. However, good that it worked well now.

**Comment by neilsmall** [comment]
An update to Roon Bridge was released a few hours ago. It failed on a newly built Pi 4B. I uninstalled Bridge and tried to reinstall Bridge, which has solved this issue in the past. I ended up at the same screens with the same errors as previously posted (this has =never= happened before). It was easiest to wipe the SD Card clean, and quickly configure DietPi with a fresh install of Bridge (build 918), which worked as expected. FYI, as I said, I've never had these difficulties in the past. 

Thanks for the reply.

**Comment by MichaIng** [comment]
Just to avoid mixing topics, which error did you face again? The "Structure needs cleaning" during an APT upgrade? Or an issue with the Roon Bridge update (`dietpi-software reinstall 121`)? If the letter, please open a new issue about this. Logs would be very helpful then.

**Comment by neilsmall** [comment]
> Just to avoid mixing topics, which error did you face again? The "Structure needs cleaning" during an APT upgrade? Or an issue with the Roon Bridge update (`dietpi-software reinstall 121`)? If the letter, please open a new issue about this. Logs would be very helpful then.

I didn't realize I still had the terminal window open. Screenshot below. Thanks. 

![image](https://user-images.githubusercontent.com/43247563/158642410-3f62b5df-28ef-48cb-b706-3c62c977db1c.png)

![image](https://user-images.githubusercontent.com/43247563/158642282-f46f1499-a2a1-41c1-acc9-1baafd436d30.png)

![image](https://user-images.githubusercontent.com/43247563/158642533-0acaacc4-c6c6-4a32-850c-239d492e5a6d.png)

**Comment by neilsmall** [comment]
And (still) getting this error. 

![image](https://user-images.githubusercontent.com/43247563/158643003-578c7148-a637-40ad-a3cb-52ec6f89e1df.png)

**Comment by Joulinar** [comment]
Try to reboot your system and do `apt update && apt upgrade` afterwards.

Btw: no need to create screen prints. Simply copy the output directly from SSH terminal.

**Comment by MichaIng** [comment]
This was a concurrently running or hard killed `apt-get` process. If the reboot suggested by Joulinar does not help, try to clean all cache and list files, which should include the lock files:
```sh
/boot/dietpi/func/dietpi-set_software apt-cache clean
apt update
apt upgrade
```
