### ISSUE TITLE
libssl1.1 upgrade fails

### ISSUE THREAD

**Issue by sberlit** [MichaIng/DietPi#5357]
#### Details:
- Date           | Sun Mar 13 20:30:39 GMT 2022
- DietPi version | v8.0.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux OwnRasp 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -qq upgrade`
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

1. Starting update with "sudo dietpi-update"
2. [FAILED] DietPi-Update | Unable to continue, DietPi-Update will now terminate.
#### Expected behaviour:

- Update completed successfully 
#### Actual behaviour:

- An Error was thrown
#### Additional logs:
```
debconf: delaying package configuration, since apt-utils is not installed
dpkg: error processing archive /var/cache/apt/archives/libssl1.1_1.1.1k-1+deb11u1+rpt1_arm64.deb (--unpack):
 subprocess dpkg-split returned error exit status 11
Errors were encountered while processing:
 /var/cache/apt/archives/libssl1.1_1.1.1k-1+deb11u1+rpt1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MichaIng** [comment]
Many thanks for your report. Can you retry cleanly and paste the output, please:
```sh
/boot/dietpi/func/dietpi-set_software apt-cache clean
apt update
apt install libssl1.1
```

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
