### ISSUE TITLE
DietPi-Software | Add Ajenti a web admin panel 

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#536]
A web admin panel [Ajenti](http://ajenti.org/). It's open source. very lightweight, runs on Debian, Ubuntu, CentOS/RHEL, FreeBSD (experimental), Raspbian. The icing on top of the cake is the the web UI is a nice modern polished look and doesn't damage your existing configuration files.

**Comment by joaofl** [comment]
Some relevant info:

Missing dependencies:
apt install python-dev python-pip
pip install gevent --upgrade 

They have an automated installing script, that includes the generating self-signed certificate, and service installing, by running:
wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sh

from: [here](http://support.ajenti.org/topics/1121-installing-on-ubuntu/)

Config file is located at /etc/ajenti/config.json
Default user: root
default pass: admin
