### ISSUE TITLE
Tinkerboard Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1'

### ISSUE THREAD

**Issue by cserl** [MichaIng/DietPi#5362]
Hello,
I used to have i2cdetect -y 1 working on dietPI v6.28 running on my Tinkerboard 2GB model. The Tinkerboard model name is without any postfix characters.
But after performing a clean install of dietPI 8.2.2 on the same Tinkerboard and when running the command "sudo i2cdetect -y 1" this is the response I get:

Error: Could not open file `/dev/i2c-1' or `/dev/i2c/1' : No such file or directory.

The following prerequisites were installed:
sudo apt-get install python3-smbus
sudo apt-get install i2c-tools

I have googled all forum threads dealing with the problem and tried different settings in /boot/config.txt and /etc/modules without success. 

i2cdetect -l
i2c-2   i2c             rk3x-i2c                                I2C adapter
i2c-0   i2c             rk3x-i2c                                I2C adapter
i2c-5   i2c             rk3x-i2c                                I2C adapter

uname -a
`Linux DietPi82TinkerBoard 5.15.25-rockchip #22.02.1 SMP PREEMPT Sun Feb 27 09:23:03 UTC 2022 armv7l GNU/Linux`

cat /etc/issue
Debian GNU/Linux 11 \n \l

Current content of /etc/modules after manually adding entries:
8723bs
i2c-bcm2708
i2c-dev

Current content of /boot/config.txt after manually adding entries:
dtparam=i2c_arm=on
dtparam=i2c_arm_baudrate=10000
dtparam=i2c1=on
dtparam=i2c_vc=on

Maybe something with device tree overlays?
Please help fixing this and advise with next steps for troubleshooting.

Bug report:  73ca9ec4-212d-4729-95d4-e88f0e272533

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
