### ISSUE TITLE
 Dietpi.txt | Set filing system and partition format for 1st run.

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#537]
Set filing system and partition format in dietpi.txt for first boot. A check would be needed if the filing system and partition format already exists. In that case it would skip formatting.

**Comment by Fourdee** [comment]
@Zone22 

We already have a AUTO_format feature in `dietpi.txt`:

> Dedicated USB drive automation
>     To use this feature, create a blank file: /boot/Automation_Format_My_Usb_Drive
>     If the file exists, the USB drive will be formatted to ext4. (WARNING: ALL DATA ON /dev/sda WILL BE DELETED. YOU HAVE BEEN WARNED!).
>    DietPi will configure your software installations to use your dedicated drive for personal data. (eg: owncloud data / bittorrent downloads etc)
>    NB: Plug in 1 USB drive before powering on system. Use 1 USB drive ONLY.

So currently:
- User creates file `/boot/Automation_Format_My_Usb_Drive` before 1st boot
- Boots system
- DietPi will wait for attached drive, then format EXT4
- GPT partition type (as of v133)
- Does not check for existing partition, format only. Checking for this could be risky, if the detection fails on say a unknown filesystem, the user will loose their data. So we really should keep this as a "format only" feature.
- Userdata moved to drive, if `dietpi_userdata_basedirectory=Auto`

We could add a feature to this, that sets filesystem type eg `AUTO_Format_Filesystem=btrfs`, thoughts?

**Comment by ghost** [comment]
I don't understand this step. Why would the user need to create the file?

> User creates file /boot/Automation_Format_My_Usb_Drive before 1st boot

Otherwise it seems great to me.

**Comment by Fourdee** [comment]
@Zone22 

> I don't understand this step. Why would the user need to create the file?

To prevent abuse, misuse and accidentally formatting their drive. 
I also would prefer `AUTO_Format_Drive=1`, but by forcing the user to create a file named `Automation_Format_My_Usb_Drive`, should prevent accidental formatting and user going "OMG DIETPI DELETE MY DRIVE, WTF BBQ" on social and giving DietPi a bad name 😉 

> Otherwise it seems great to me.

I'll add `AUTO_Dedicated_Usb_Drive_Format_Filesystem=` in.

**Comment by Fourdee** [comment]
Completed.
