### ISSUE TITLE
Gogs documentation and port forwarding clarification

### ISSUE THREAD

**Issue by ideomux** [MichaIng/DietPi#538]
Everything works great. Include a step mentioning forwarding port 3000 TCP would be helpful.

**Comment by Fourdee** [comment]
@ideomux 

> Include a step mentioning forwarding port 3000 TCP would be helpful.

For external access to gogs web interface?

**Comment by ideomux** [comment]
yes. (though I guess it's safe to assume most users would understand port forwarding)

**Comment by Fourdee** [comment]
@ideomux 

> http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=2187#p2187

Added to Docs 👍 
Not sure if UDP is needed, but no harm.
