### ISSUE TITLE
public key not available installing Mopidy with dietpi-software

### ISSUE THREAD

**Issue by hifi-On-Pi** [MichaIng/DietPi#5389]
#### Details:
- Date           | Tue Mar 29 19:59:02 CEST 2022
- Bug report     | 8726ecd6-5eda-49a8-ae75-5f47fbce2de6
- DietPi version | v8.2.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 3 Model B+ (aarch64) (ID=3)
- Kernel version | `Linux DietPi3 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -q update`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:
- choose installation of Mopidy in dietpi-software
#### Expected behaviour:
- after prerequisite pkgs ALSA and Python 3 also pkg Mopidy will be installed successfully
#### Actual behaviour:
- installation of pkg Mopiday not successfull by unavailable public key
#### Extra details:
- none
#### Additional logs:
```
Get:1 https://apt.mopidy.com buster InRelease [14.1 kB]
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:5 https://deb.debian.org/debian bullseye-backports InRelease
Hit:6 https://archive.raspberrypi.org/debian bullseye InRelease
Err:1 https://apt.mopidy.com buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78FD980E271D2943
Reading package lists...
W: GPG error: https://apt.mopidy.com buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78FD980E271D2943
E: The repository 'https://apt.mopidy.com buster InRelease' is not signed.
```

**Comment by MichaIng** [comment]
Hence solution is:
```sh
echo 'deb https://apt.mopidy.com/ buster main contrib non-free' > /etc/apt/sources.list.d/mopidy.list
apt update
```

**Comment by hifi-On-Pi** [comment]
Thanks for fast reactions.
I used #5381 (sorry for duplicate issue here) and during the repeated run of dietpi-software I had to use the command shell twice (now also in "Step: Checking for prerequisite software" - not in " Step: Installing Mopidy" only).
After that (and some temporary resolving errors) the installation finished successfully.
Thanks again for the effective solution.

**Comment by MichaIng** [comment]
Ah yes right, `dietpi-software` still downloads the trouble causing `mopidy.list`, so it needs to be run from the subshell 👍. Fixed `dietpi-software` is coming with DietPi v8.3 this Saturday.
