### ISSUE TITLE
No Local Sound

### ISSUE THREAD

**Issue by thechildofroth** [MichaIng/DietPi#539]
Having issues with no local sound from Subsonic/DAC again, can't see any issues with config

Bug report filled: 007bb5db-ab02-4525-9a09-589253418eba-1 

root@subsonic:~# aplay -l
***\* List of PLAYBACK Hardware Devices ****
card 0: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

root@subsonic:~# cat /etc/asound.conf 
pcm.!default {
type hw
card 0
}
ctl.!default {
type hw
card 0
}

**Comment by Fourdee** [comment]
@thechildofroth 

Strange, everything looks ok. Did you use dietpi-config to set the soundcard?

Does `speaker-test -c2` output any audio or errors?

**Comment by thechildofroth** [comment]
Aha, sorry please close / delete / mark as fixed

User error

/redface

**Comment by Fourdee** [comment]
@thechildofroth 

No worries. Thanks for letting us know 👍
