### ISSUE TITLE
Implement install and monitoring script for UPS HAT (B)

### ISSUE THREAD

**Issue by AdamF100001** [MichaIng/DietPi#5390]
#### Is your feature request related to a problem? Please describe:

- ...

#### Describe the solution you'd like:

- ...

#### Describe alternatives you've considered:

- ...

#### Additional context

- ...

I have purchased a Uninterruptible Power Supply UPS HAT (B) for Raspberry Pi from PiHut. 

Please can you develop a script for Support?

https://thepihut.com/products/uninterruptible-power-supply-ups-hat-b-for-raspberry-pi

I have alraedy asked the Raspberry Pi Forums for advice here with no luck.

https://forums.raspberrypi.com/viewtopic.php?p=1973049#p1973049

Here is my original tweet about support for the UPS hat here.

https://twitter.com/DietPi_/status/1491961760273903619

Here is a YouTube video of the device specs and it running in Raspberry Pi OS if that helps for development.

https://www.youtube.com/watch?v=p86AbqgRaIo

![20220330_123848](https://user-images.githubusercontent.com/59096769/160835966-f3d9e8df-2616-4973-9512-60b64979e470.jpg)
![20220330_123911](https://user-images.githubusercontent.com/59096769/160835973-17050ee9-5fcb-4dc4-91a8-8489cfb1485f.jpg)

Thank You :)

**Comment by MichaIng** [comment]
Many thanks for your request.

Did you already try it with the instructions given [here](https://www.waveshare.com/wiki/UPS_HAT_(B))?
- I2C can be enabled via `dietpi-config` > Advanced Options.
- Python 3 can be installed via `dietpi-software` or just `apt install python3`.
- Then download an execute the given Python script. If this is working well, you can start it at boot via `/var/lib/postboot.d/` or `dietpi-autostart` custom foreground script.

**Comment by AdamF100001** [comment]
Not yet still waiting for amazon to delivery the batteries for the PSU.

Which should be 5th - 11th April.

I will keep you posted.

**Comment by MichaIng** [comment]
Ah okay, makes sense. I should have known that manufacturers provide install instructions and software to use HATs on Raspberry Pi, to make it attractive for customers. So what I wrote about required API info and such is covered by this. Of course one can use the quite simple provided Python script as a basis to customise the way which/how info is provided.

**Comment by AdamF100001** [comment]
> Many thanks for your request.
> 
> Did you already try it with the instructions given [here](https://www.waveshare.com/wiki/UPS_HAT_(B))?
> - I2C can be enabled via `dietpi-config` > Advanced Options.
> - Python 3 can be installed via `dietpi-software` or just `apt install python3`.
> - Then download an execute the given Python script. If this is working well, you can start it at boot via `/var/lib/postboot.d/` or `dietpi-autostart` custom foreground script.

The example above didn't work with dietpi as it's a command for raspberry pi os and not dietpi.

**Comment by AdamF100001** [comment]
None of the commands worked off the website.

https://www.waveshare.com/wiki/UPS_HAT_(B)

Are any of the following options in dietpi for the UPS in this screenshot?

**Comment by Joulinar** [comment]
As requested by @MichaIng , you would need to share the error message and/or output of these commands. Otherwise we are not able to assist further. In general, things working on RPI OS will work same way on DietPi.

**Comment by MichaIng** [comment]
Did you actually read what I posted above and what you quoted? Instead of `raspi-config`, call `dietpi-config` to enable I2C. Install Python 3 as instructed. All commands below "Run the example" (from your link) will then work. The only question is whether the last `python3 INA219.py` will work OOTB or needs adjustments.

**Comment by AdamF100001** [comment]
Then download an execute the given Python script. If this is working well, you can start it at boot via /var/lib/postboot.d/ or dietpi-autostart custom foreground script.

**Comment by AdamF100001** [comment]
Where do I download the python script and how do I run it?

**Comment by MichaIng** [comment]
The commands below "Run the example" in the linked wiki.

**Comment by AdamF100001** [comment]
This is the output of the python3 INA219.py

Load Voltage:   8.412 V
Current:        0.045300 A
Power:          0.380 W
Percent:       100.0%

Is it working correctly?

**Comment by MichaIng** [comment]
Seems so, at least the values look consistent: Battery full, no charging. For a test whether it really works, you'd need to unplug the PSU.

**Comment by AdamF100001** [comment]
Yes! It works 

Load Voltage:   8.292 V
Current:       -0.134900 A
Power:          1.118 W
Percent:       95.5% 

How do I can start it at boot via /var/lib/postboot.d/ or dietpi-autostart custom foreground script? 

Will dietpi shutdown safely when battery is dead?

**Comment by MichaIng** [comment]
> How do I can start it at boot via /var/lib/postboot.d/ or dietpi-autostart custom foreground script?

Simplest solution:
```sh
mv INA219.py /var/lib/postboot.d/
```
This however blocks the console. You cannot enter any commands until hitting `CTRL+C` to cancel the script. The 2nd option:
```sh
sed -i '1i\#!/usr/bin/env python3' INA219.py
mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
dietpi-autostart 17
```
_It is a bit hacky, since `dietpi-autostart` is meant to start a shell script. So we rename this Python script and add a shebang to be executed with Python. That way we do not need a wrapper script._
This allows you to use the console, but the scripts output may interfere. In this case, the script can be stopped with this command:
```sh
systemctl stop dietpi-autostart_custom
```

SSH still works fine in both cases, of course. Those two use the local console (attached monitor or LCD) only.

> Will dietpi shutdown safely when battery is dead?

In theory it is possible to trigger a shutdown via GPIO, but as far as I can see on the product page, this is not supported. What can be done is the following:
- Since the script runs a loop already, parse the "Current" and "Percent" values.
- If "Percent" is below e.g. 10% and "Current" negative (de-charging), print a warning and shutdown the system.
- Could be also done nicely with a little timer, to shutdown in 60 seconds or so, not sure what is reasonable, also depends on how long the batteries hold.
- Could be also done as dedicated script/service, which does not print the stats to screen.

**Comment by AdamF100001** [comment]
Hi Again 

Please can you confirm that I have successfully added the UPS script to auto start?

root@DietPi:~# sed -i '1i\#!/usr/bin/env python3' INA219.py
sed: can't read INA219.py: No such file or directory
root@DietPi:~# mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
mv: cannot stat 'INA219.py': No such file or directory
root@DietPi:~# dietpi-autostart 17
[  OK  ] DietPi-AutoStart | mkdir -p /etc/systemd/system/getty@tty1.servic
e.d /etc/systemd/system/console-getty.service.d
[  OK  ] DietPi-AutoStart | systemctl daemon-reload
root@DietPi:~#

Also, what is the correct command to re-run the UPS_HAT python3 INA219.py script?

Thanks

**Comment by MichaIng** [comment]
> `INA219.py: No such file or directory`

Obviously not. You seem to be not in the directory where the script is located. First of all you need to have the script. `python3 INA219.py` can be used to run it, if you are in the same dir. After moving it to `/var/lib/dietpi/dietpi-autostart/custom.sh`, it would be
```sh
/var/lib/dietpi/dietpi-autostart/custom.sh
```
But don't do that after reboot, since then it will be started by the autostart option already.

**Comment by AdamF100001** [comment]
What am I doing wrong here?

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Jan 27 18:55:14 2023 from 192.168.1.152
root@DietPi:~# cd /var/lib/dietpi/dietpi-autostart/custom.sh
-bash: cd: /var/lib/dietpi/dietpi-autostart/custom.sh: No such file or directory
root@DietPi:~# /var/lib/dietpi/dietpi-autostart/custom.sh
-bash: /var/lib/dietpi/dietpi-autostart/custom.sh: No such file or directory
root@DietPi:~# cd UPS_HAT_B
root@DietPi:~/UPS_HAT_B#

**Comment by Joulinar** [comment]
Did you activated the `dietpi-autostart` option for custom scripts already?

**Comment by MichaIng** [comment]
I think some basics in shell commands are required 🙂. Can you check the content of the `UPS_HAT_B` directory you have just navigated to?
```sh
ls -l
```

**Comment by AdamF100001** [comment]
root@DietPi:~/UPS_HAT/UPS_HAT# ls -l
total 16
-rw-r--r-- 1 root root 8447 Mar 30  2020 INA219.py
drwx------ 2 root root 4096 Mar 30  2020 UPS_HAT
root@DietPi:~/UPS_HAT/UPS_HAT#

**Comment by AdamF100001** [comment]
> Did you activated the `dietpi-autostart` option for custom scripts already?

How do I activated the dietpi-autostart ?

**Comment by Joulinar** [comment]
> How do I activated the dietpi-autostart ?

run `dietpi-autostart` and select the option to start a custom script

**Comment by MichaIng** [comment]
Okay there is the script. Does it already have the shebang?
```sh
head -1 INA219.py
```

**Comment by AdamF100001** [comment]
> Okay there is the script. Does it already have the shebang? Print the first line of the script:
> ```sh
> head -1 INA219.py
> ```

```code
root@DietPi:~/UPS_HAT# head -1 INA219.py
head: cannot open 'INA219.py' for reading: No such file or directory
```

**Comment by AdamF100001** [comment]
> > How do I activated the dietpi-autostart ?
> 
> run `dietpi-autostart` and select the option to start a custom script

start a custom script in the background or foreground?

**Comment by MichaIng** [comment]
Wait with the autostart option, this cannot work yet.

> head: cannot open 'INA219.py' for reading: No such file or directory

Strange, you just showed the content of the current directory and it was right there 🤔. Was there some typo inside? Ah, it is somehow nested `~/UPS_HAT/UPS_HAT`. Please go into this directory and check again:
```sh
cd /root/UPS_HAT/UPS_HAT
head -1 INA219.py
```

**Comment by AdamF100001** [comment]
> Wait with the autostart option, this cannot work yet.
> 
> > head: cannot open 'INA219.py' for reading: No such file or directory
> 
> Strange, you just showed the content of the current directory and it was right there 🤔. Was there some typo inside? Ah, it is somehow nested `~/UPS_HAT/UPS_HAT`. Please go into this directory and check again:
> ```sh
> cd /root/UPS_HAT/UPS_HAT
> head -1 INA219.py
> ```

```code

root@DietPi:~/UPS_HAT/UPS_HAT# ls
INA219.py  UPS_HAT
root@DietPi:~/UPS_HAT/UPS_HAT# cd UPS_HAT
root@DietPi:~/UPS_HAT/UPS_HAT/UPS_HAT# cd /root/UPS_HAT/UPS_HAT
root@DietPi:~/UPS_HAT/UPS_HAT# head -1 INA219.py
import smbus
root@DietPi:~/UPS_HAT/UPS_HAT#

```

**Comment by MichaIng** [comment]
Okay not sure what you did, but you seem to have several of this directories nested into each other. However there is the script, without shebang. Add it:
```sh
sed -i '1i\#!/usr/bin/env python3' INA219.py
```
This is to tell the shell how to execute it. Before, you needed to do this to execute the script:
```sh
python3 INA219.py
```
So you need to call it with Python explicitly. With the above change, you can do:
```sh
./INA219.py
```
and the the shebang tells the shell how it needs to be invoked. This is required for the autostart option as well as the postboot.d option, since they execute the files just like this. Now you can move the script to the autostart location:
```sh
mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
```

**Comment by AdamF100001** [comment]
> Okay not sure what you did, but you seem to have several of this directories nested into each other. However there is the script, without shebang. Add it:
> ```sh
> sed -i '1i\#!/usr/bin/env python3' INA219.py
> ```
> This is to tell the shell how to execute it. Before, you needed to do this to execute the script:
> ```sh
> python3 INA219.py
> ```
> So you need to call it with Python explicitly. With the above change, you can do:
> ```sh
> ./INA219.py
> ```
> and the the shebang tells the shell how it needs to be invoked. This is required for the autostart option as well as the postboot.d option, since they execute the files just like this. Now you can move the script to the autostart location:
> ```sh
> mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
> ```

```code

root@DietPi:~/UPS_HAT/UPS_HAT# sed -i '1i\#!/usr/bin/env python3' INA219.
sed: can't read INA219.: No such file or directory
root@DietPi:~/UPS_HAT/UPS_HAT# python3 INA219.py
Load Voltage:  19.136 V
Current:        0.000600 A
Power:          0.014 W
Percent:       100.0%
Load Voltage:  19.064 V
Current:        0.000600 A
Power:          0.010 W
Percent:       100.0%
Load Voltage:  19.064 V
Current:        0.000600 A
Power:          0.010 W
Percent:       100.0%
^CTraceback (most recent call last):
  File "/root/UPS_HAT/UPS_HAT/INA219.py", line 214,
in <module>
    time.sleep(2)
KeyboardInterrupt
root@DietPi:~/UPS_HAT/UPS_HAT# ./INA219.py
-bash: ./INA219.py: Permission denied
root@DietPi:~/UPS_HAT/UPS_HAT#

```

I didn't run the last command.

Please can you create a fully automated script for the full process.

Sorry, I'm not a programmer, so finding this difficult.

**Comment by MichaIng** [comment]
You missed the `py` file ending in the first command. Use the copy button in the code blocks to assure everything is copied:
```sh
sed -i '1i\#!/usr/bin/env python3' INA219.py
chmod +x INA219.py
mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
dietpi-autostart 17
```

**Comment by AdamF100001** [comment]
```code 

root@DietPi:~/UPS_HAT/UPS_HAT# ./INA219.py
-bash: ./INA219.py: Permission denied
root@DietPi:~/UPS_HAT/UPS_HAT# sed -i '1i\#!/usr/bin/env python3' INA219.py
root@DietPi:~/UPS_HAT/UPS_HAT# chmod +x INA219.py
root@DietPi:~/UPS_HAT/UPS_HAT# mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
mv: cannot move 'INA219.py' to '/var/lib/dietpi/dietpi-autostart/custom.sh': No such file or directory
root@DietPi:~/UPS_HAT/UPS_HAT# dietpi-autostart 17
[  OK  ] DietPi-AutoStart | mkdir -p /etc/systemd/system/getty@tty1.service.d /etc/systemd/system/console-getty.service.d
[  OK  ] DietPi-AutoStart | systemctl daemon-reload
root@DietPi:~/UPS_HAT/UPS_HAT#

```

**Comment by MichaIng** [comment]
Repeat this one:
```sh
mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
```

**Comment by AdamF100001** [comment]
> Repeat this one:
> ```sh
> mkdir -p /var/lib/dietpi/dietpi-autostart
> mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
> ```

```code

root@DietPi:~/UPS_HAT/UPS_HAT# mkdir -p /var/lib/dietpi/dietpi-autostart
root@DietPi:~/UPS_HAT/UPS_HAT# mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
root@DietPi:~/UPS_HAT/UPS_HAT#

```

**Comment by AdamF100001** [comment]
```code 

root@DietPi:~/UPS_HAT/UPS_HAT# ./INA219.py
-bash: ./INA219.py: Permission denied
root@DietPi:~/UPS_HAT/UPS_HAT# sed -i '1i\#!/usr/bin/env python3' INA219.py
root@DietPi:~/UPS_HAT/UPS_HAT# chmod +x INA219.py
root@DietPi:~/UPS_HAT/UPS_HAT# mv INA219.py /var/lib/dietpi/dietpi-autostart/custom.sh
mv: cannot move 'INA219.py' to '/var/lib/dietpi/dietpi-autostart/custom.sh': No such file or directory
root@DietPi:~/UPS_HAT/UPS_HAT# dietpi-autostart 17
[  OK  ] DietPi-AutoStart | mkdir -p /etc/systemd/system/getty@tty1.service.d /etc/systemd/system/console-getty.service.d
[  OK  ] DietPi-AutoStart | systemctl daemon-reload
root@DietPi:~/UPS_HAT/UPS_HAT#

```

What should I do next?

**Comment by MichaIng** [comment]
You were done already yesterday. Just reboot and it should automatically login and start the script.

**Comment by AdamF100001** [comment]
OK great how can I tell the script is working and  check the status of the UPS?

**Comment by MichaIng** [comment]
As I said, just reboot, it should show the status on the main screen. If it doesn't something is wrong, which can be checked via:
```sh
journalctl -u dietpi-autostart_custom
```

**Comment by AdamF100001** [comment]
```code

root@DietPi:~# journalctl -u dietpi-autostart_custom
-- Journal begins at Sat 2023-01-28 19:48:40 GMT, ends at Sat 2023-01-28 20:39:01 GMT. --
-- No entries --
root@DietPi:~#

```

**Comment by MichaIng** [comment]
Has the service started?
```sh
systemctl status dietpi-autostart_custom
```

**Comment by AdamF100001** [comment]
```code

root@DietPi:~# systemctl status dietpi-autostart_custom
Unit dietpi-autostart_custom.service could not be found.
root@DietPi:~#

```

**Comment by MichaIng** [comment]
Hah, you ran into a bug. Fixed with: https://github.com/MichaIng/DietPi/commit/507b68e

Please do this, then `reboot` again to test:
```sh
cat << '_EOF_' > /etc/systemd/system/dietpi-autostart_custom.service
[Unit]
Description=DietPi-AutoStart custom script
Requisite=dietpi-boot.service
After=dietpi-boot.service dietpi-postboot.service rc-local.service
ConditionPathExists=/var/lib/dietpi/dietpi-autostart/custom.sh

[Service]
Type=idle
RemainAfterExit=yes
ExecStartPre=/bin/chmod +x /var/lib/dietpi/dietpi-autostart/custom.sh
ExecStart=/var/lib/dietpi/dietpi-autostart/custom.sh

[Install]
WantedBy=multi-user.target
_EOF_
systemctl enable dietpi-autostart_custom
```
Important: This needs to be copied and pasted into your console at once. The first block between `cat` and `_EOF_` at the bottom is a single command.

**Comment by MichaIng** [comment]
Ah sorry, forget what I just posted, it is all correct, we don't use the service for the foreground option. Wait I need to check how it is actually implemented 😄.

**Comment by AdamF100001** [comment]
I will wait for your reply.

I am determined to get this working.

**Comment by MichaIng** [comment]
Okay, the script is implemented differently, not with a systems service, I forgot it 😄. But the result should be the same. When you reboot, on your main screen login should happen automatically (no login prompt to enter user/password) and you should see, after the banner, a message
```
[ INFO ] Starting DietPi-Autostart custom script...
```
and then the output of the UPS monitor. Is this not the case?

**Comment by AdamF100001** [comment]
Rebooted, here  is the output 

```code 

Linux DietPi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch6
4
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jan 28 21:30:30 2023
 ─────────────────────────────────────────────────────
 DietPi v8.13.2 : 21:30 - Sat 01/28/23
 ─────────────────────────────────────────────────────
 - Device model : RPi 4 Model B (aarch64)
 - Uptime : up 0 minutes
 - CPU temp : 52 °C / 125 °F : Running warm, but safe
 - LAN IP : 192.168.1.6 (eth0)
 ─────────────────────────────────────────────────────
 dietpi-launcher : All the DietPi programs in one place
 dietpi-config   : Feature rich configuration tool for your device
 dietpi-software : Select optimised software for installation
 htop            : Resource monitor
 cpu             : Shows CPU information and stats
root@DietPi:~#

```

**Comment by AdamF100001** [comment]
Where am I going wrong?

**Comment by Joulinar** [comment]
I guess you login via SSH? If I understood @MichaIng the information is visible on a physical screen attached.

**Comment by AdamF100001** [comment]
> I guess you login via SSH? If I understood @MichaIng the information is visible on a physical screen attached.

Here is the ssh output.

Linux DietPi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch6 4 The programs included with the Debian GNU/Linux system are free software; the exact distribution terms for each program are described in the individual files in /usr/share/doc/*/copyright. Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law. Last login: Sat Jan 28 21:30:30 2023 ───────────────────────────────────────────────────── DietPi v8.13.2 : 21:30 - Sat 01/28/23 ───────────────────────────────────────────────────── - Device model : RPi 4 Model B (aarch64) - Uptime : up 0 minutes - CPU temp : 52 °C / 125 °F : Running warm, but safe - LAN IP : 192.168.1.6 (eth0) ───────────────────────────────────────────────────── dietpi-launcher : All the DietPi programs in one place dietpi-config : Feature rich configuration tool for your device dietpi-software : Select optimised software for installation htop : Resource monitor cpu : Shows CPU information and stats root@DietPi:~#

**Comment by MichaIng** [comment]
Yes, with "main screen" I mean the attached monitor. Autostart options in general never run on SSH sessions but always on TTY1.

Do you want to see this as well when logging in via SSH?

**Comment by AdamF100001** [comment]
I don't have a physical screen attached at the minute. I will connect one up tomorrow.

What steps will I need to do. I currently have no desktop gui installed, just ssh.

Thanks for all the help so far.

**Comment by Joulinar** [comment]
There should be an output automatically.

**Comment by MichaIng** [comment]
> I don't have a physical screen attached at the minute. I will connect one up tomorrow.

Then I'm actually wondering why you want the script to run automatically at boot? There is no point to show its output to anywhere at boot, if no screen is attached 😄.

So just to make things clear:
- The HAT just works, you do not need to run any script for that. You already tested it by unplugging the power cord.
- The script is really only meant as a monitoring tool, usually in combination with a little LCD screen. If you do not have an LCD screen, there is no point in running the script at boot, it would be just a waste or resources.

If you want to see the UPS status at SSH logins, then you need to do it differently:
```sh
dietpi-autostart 0
mv /var/lib/dietpi/dietpi-autostart/custom.sh /root/INA219.py
echo '/root/INA219.py' >> /root/.profile
```
Now, when the root user logs in, either locally or via SSH, the script will start on whichever console you are connected with.

**Comment by AdamF100001** [comment]
Thanks just to report it's working.

If the battery goes flat will dietpi disable all services and shutdowns like power off command has been run?

**Comment by MichaIng** [comment]
> If the battery goes flat will dietpi disable all services and shutdowns like power off command has been run?

Explained above already: https://github.com/MichaIng/DietPi/issues/5390#issuecomment-1396168264
