### ISSUE TITLE
Unable to install Deluge

### ISSUE THREAD

**Issue by jjlucas76** [MichaIng/DietPi#5394]
#### Details:
- Date           | Fri Apr  1 14:24:51 BST 2022
- DietPi version | v8.2.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | Odroid N2 (aarch64) (ID=15)
- Kernel version | `Linux DietPi 5.10.102-meson64 #22.02.1 SMP PREEMPT Sun Feb 27 09:09:25 UTC 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `systemctl stop deluged`
- Exit code      | 5
- Software title | DietPi-Software
#### Steps to reproduce:

1. ... dietpi-software install id 45
#### Expected behaviour:

- Deluge should be installed and functional
#### Actual behaviour:

- during installation, workflow attempts to stop deluged via systemctl. There is no deluged service configure in systemctl as deluge is not installed yet.
#### Extra details:

- ...
#### Additional logs:
```
Failed to stop deluged.service: Unit deluged.service not loaded.
```

**Comment by MichaIng** [comment]
Many thanks for your report.

Strange, the previously installed `deluged` package does actually install and start `/etc/init.d/deluged`: https://packages.debian.org/bullseye/all/deluged/filelist

I'm trying to replicate.

**Comment by MichaIng** [comment]
Works well here:
```
[  OK  ] DietPi-Software | APT install for: deluged deluge-web deluge-console
[  OK  ] DietPi-Software | systemctl stop deluged
```
When you open a subshell from the error prompt, can you run and paste the output of these commands:
```sh
ls -l /etc/init.d/deluged
systemctl status deluged
```

**Comment by jjlucas76** [comment]
root@DietPi:/tmp/DietPi-Software# ls -l /etc/init.d/deluged
systemctl status deluged
ls: cannot access '/etc/init.d/deluged': No such file or directory
Unit deluged.service could not be found.

**Comment by jjlucas76** [comment]
I have run an apt upgrade, as home prompt was showing some updates available. 
running install again now errors out with the following:

- Date           | Fri Apr  1 14:50:36 BST 2022
- Bug report     | b5d9f369-71bc-4386-a7df-a3a35f3f954f
- DietPi version | v8.2.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | Odroid N2 (aarch64) (ID=15)
- Kernel version | `Linux DietPi 5.10.102-meson64 #22.02.1 SMP PREEMPT Sun Feb 27 09:09:25 UTC 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `apt-get -q update`
- Exit code      | 255
- Software title | DietPi-Software
#### Steps to reproduce:

1. ... dietpi-software install id 45
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Err:1 http://apt.armbian.com bullseye InRelease
  Could not connect to apt.armbian.com:80 (107.175.134.226). - connect (113: No route to host) Cannot initiate the connection to apt.armbian.com:80 (2605:7900:20::5). - connect (101: Network is unreachable)
Hit:2 https://download.docker.com/linux/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian bullseye InRelease
Hit:4 https://deb.debian.org/debian bullseye-updates InRelease

**Comment by Joulinar** [comment]
Looks like some issues to connect to Armbian package source. Could you try to disable IPv6 on network settings?

**Comment by MichaIng** [comment]
The second error is unrelated, I guess Armbian servers are down, they were flaky the last days. Though at the moment I can reach `apt.armbian.com` just fine.

Strange with the missing service file. `deluged` was successfully installed and do you have probably some `dpkg.cfg` rules to not install any SysV services?
```sh
dpkg -l deluged
for i in /etc/dpkg/dpkg.cfg{,.d/*}
do
[[ -f $i ]] || continue
echo "$i:"
cat "$i"
done
```

**Comment by jjlucas76** [comment]
apt.armbian.com is reachable, but on port 80 cannot connect. However not related to deluge at all.

your last command results in the below:

root@DietPi:~# dpkg -l deluged
for i in /etc/dpkg/dpkg.cfg{,.d/*}
do
[[ -f $i ]] || continue
echo "$i:"
cat "$i"
done
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================================
ii  deluged        2.0.3-3.1    all          bittorrent client written in Python/PyGTK (daemon)
/etc/dpkg/dpkg.cfg:
# dpkg configuration file
#
# This file can contain default options for dpkg.  All command-line
# options are allowed.  Values can be specified by putting them after
# the option, separated by whitespace and/or an `=' sign.
#

# Do not enable debsig-verify by default; since the distribution is not using
# embedded signatures, debsig-verify would reject all packages.
no-debsig

# Log status changes and actions to a file.
log /var/log/dpkg.log
/etc/dpkg/dpkg.cfg.d/01-dietpi-exclude_doubled_devicetrees:
path-exclude /usr/lib/linux-image-current-*

**Comment by Joulinar** [comment]
You could try to update Armbian source file to use HTTPS?

**Comment by jjlucas76** [comment]
> You could try to update Armbian source file to use HTTPS?

indeed that solved the http issue on armbian.com
changed “http” to “https” in /etc/apt/sources.list.d/dietpi-armbian.list

still deluged is not installing with previous error:

_Failed to stop deluged.service: Unit deluged.service not loaded._

**Comment by Joulinar** [comment]
maybe you could try following workaround if your are hit by the `Failed to stop deluged.service: Unit deluged.service not loaded.` issue. You should have an option to change the actual command. Do this, remove the original command completely and just type `true`. Continue afterwards. Just as an idea.

**Comment by jjlucas76** [comment]
> maybe you could try following workaround if your are hit by the `Failed to stop deluged.service: Unit deluged.service not loaded.` issue. You should have an option to change the actual command. Do this, remove the original command completely and just type `true`. Continue afterwards. Just as an idea.

This worked! Many thanks

**Comment by jjlucas76** [comment]
Thank you for your support

**Comment by Joulinar** [comment]
@MichaIng 
Maybe we should do same as on the webmin issue and check the service running before trying to stop it?

**Comment by MichaIng** [comment]
@Joulinar 
We'll, of course we could add workarounds for all missing files that we do not need for our particular setup, but generally it is a major issue when a file that is shipped by a package is just not there after the package got installed. If by chance we did not create an own systemd unit to replace the SysV service, webmin would just not work. So that should be better debugged than silently ignoring it.

@jjlucas76 
Are other SysV services present?
```sh
ls -l /etc/init.d
```
And was the `deluged` package really installed by `dietpi-software` or was it probably installed before?

Since all files in `/etc` are forcefully marked as "conffiles" in packages shipped by the official Debian repositories, in theory the following is possible to run into this issue, even when the package received an upgrade in the meantime:
```sh
apt install deluged
rm /etc/init.d/deluged
# any time later
dietpi-software install 45
```
But why would someone manually remove the service file, especially without creating a systemd unit as replacement then (which would again solve the issue).

**Comment by jjlucas76** [comment]
> @Joulinar We'll, of course we could add workarounds for all missing files that we do not need for our particular setup, but generally it is a major issue when a file that is shipped by a package is just not there after the package got installed. If we did not by chance create an own systemd unit to replace the SysV service, webmin would just not work. So that should be better debugged than silently ignored.
> 
> @jjlucas76 Are other SysV services present?
> 
> ```shell
> ls -l /etc/init.d
> ```
> 
> And was the `deluged` package really installed by `dietpi-software` or was it probably installed before?
> 
> Since all files in `/etc` are forcefully marked as "conffiles" in packages shipped by the official Debian repositories, in theory the following is possible to run into this issue, even when the package received an upgrade in the meantime:
> 
> ```shell
> apt install deluged
> rm /etc/init.d/deluged
> # any time later
> dietpi-software install 45
> ```
> 
> But why would someone manually remove the service file, especially without creating a systemd unit as replacement then (which would again solve the issue).

root@DietPi:~# ls -l /etc/init.d
total 84
-rwxr-xr-x 1 root root 1232 Jul 23  2021 console-setup.sh
-rwxr-xr-x 1 root root 3059 Feb 22  2021 cron
-rwxr-xr-x 1 root root 3152 Feb 21  2021 dbus
-rwxr-xr-x 1 root root 3843 Mar 10 14:03 docker
-rwxr-xr-x 1 root root 2696 Jan 14  2021 dropbear
-rwxr-xr-x 1 root root  824 Sep  5  2014 fake-hwclock
-rwxr-xr-x 1 root root 1748 Jul 28  2021 hwclock.sh
-rwxr-xr-x 1 root root 1479 Oct 29  2018 keyboard-setup.sh
-rwxr-xr-x 1 root root 2044 Jan  7  2021 kmod
-rwxr-xr-x 1 root root 4486 Sep 21  2020 networking
-rwxr-xr-x 1 root root 1934 Feb  3 20:54 nmbd
-rwxr-xr-x 1 root root  924 Apr  6  2021 procps
-rwxr-xr-x 1 root root  557 Oct 19  2018 rngd
-rwxr-xr-x 1 root root 2259 Feb  3 20:54 samba-ad-dc
-rwxr-xr-x 1 root root 2061 Feb  3 20:54 smbd
-rwxr-xr-x 1 root root 1030 Feb 27  2021 sudo
-rwxr-xr-x 1 root root 6871 Jul 13  2021 udev
-rwxr-xr-x 1 root root 1306 Jan 20 20:10 uuidd
-rwxr-xr-x 1 root root 2757 Oct  9  2020 x11-common


the package was installed from dietpi-software , but not configured, in systemd and in database.

**Comment by MichaIng** [comment]
If you want to help further debugging it, this would be interesting to know:
```sh
systemctl disable --now deluged
rm /etc/systemd/system/deluged.service
systemctl daemon-reload
apt purge deluged
apt install deluged
ls -l /etc/init.d/deluged
```
