### ISSUE TITLE
/boot/dietpi/func/run_ntpd kicks out syntax error during dietpi-update

### ISSUE THREAD

**Issue by Wondering-Soul** [MichaIng/DietPi#5403]
- DietPi version | v8.2.2
- Distro version | bullseye 1
- Kernel version | `Linux 5.10.103-v7+ #1530 SMP Tue Mar 8 13:02:44 GMT 2022 armv7l GNU/Linux`
- SBC model | RPi 3 Model B+ (armv7l)
- Power supply used | 5V 2.5A (rpi branded)
- SD card used | 16GB SanDisk Extreme

When running dietpi-update (from v8.2.2 to current[v8.3.1]) I get the following output before whiptail appears:

`/boot/dietpi/func/run_ntpd: line 35: ((: == 1 : syntax error: operand expected (error token is "== 1 ")`

<img width="764" alt="Screenshot 2022-04-04 at 14 28 26" src="https://user-images.githubusercontent.com/102968856/161554770-2a96938b-5c6f-4c65-8c4f-f197420b7642.png">

#### Steps to reproduce
1. Run dietpi-update
2. First few lines of output produce the error

#### Expected behaviour
- dietpi-update runs as normal

#### Actual behaviour
- dietpi-update throws the ntp error, but does continue with the update

#### Extra details
- I have multiple raspberry-pi's in my network, this issue was present when trying to update from v8.2.2 to current on all devices (RPi 1, 3, 4).

**Comment by MichaIng** [comment]
This was a (visual-only) bug in v8.2. solved with v8.3. The update still runs the old code, so you still saw it but now you won't see it anymore 🙂.

I'll mark this as closed.
