### ISSUE TITLE
zramswap service failure

### ISSUE THREAD

**Issue by f-laurens** [MichaIng/DietPi#5419]
#### Context: 
- DietPi version: 8.3.1
- Distro version: bullseye 1
- Kernel version: Linux Pi 5.15.32+ # 1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux
- SBC model: Raspberry Pi Zero  (or Zero 2)

#### Additional Information:
DietPi_RPi-ARMv6-Bullseye  image
- configured with zramswap (`AUTO_SETUP_SWAPFILE_LOCATION=zram` in `/boot/dietpi.txt`)
- and using unmodified` /etc/default/zramswap` file:

The zramswap service reports an error:
```
dietpi@Pi:~$ systemctl status zramswap
● zramswap.service - Linux zramswap setup
     Loaded: loaded (/lib/systemd/system/zramswap.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-04-11 17:37:03 CEST; 1min 22s ago
       Docs: man:zramswap(8)
    Process: 14060 ExecStart=/usr/sbin/zramswap start (code=exited, status=1/FAILURE)
   Main PID: 14060 (code=exited, status=1/FAILURE)
        CPU: 115ms

Apr 11 17:37:03 Pi systemd[1]: Starting Linux zramswap setup...
Apr 11 17:37:03 Pi root[14061]: Starting Zram
Apr 11 17:37:03 Pi zramswap[14061]: <13>Apr 11 17:37:03 root: Starting Zram
Apr 11 17:37:03 Pi zramswap[14060]: /usr/sbin/zramswap: line 53: echo: write error: Device or resource busy
Apr 11 17:37:03 Pi root[14063]: Error: setting compression algo to lz4
Apr 11 17:37:03 Pi zramswap[14063]: <13>Apr 11 17:37:03 root: Error: setting compression algo to lz4
Apr 11 17:37:03 Pi systemd[1]: zramswap.service: Main process exited, code=exited, status=1/FAILURE
Apr 11 17:37:03 Pi systemd[1]: zramswap.service: Failed with result 'exit-code'.
Apr 11 17:37:03 Pi systemd[1]: Failed to start Linux zramswap setup.
```
RAM swap partition is created correctly:
```
dietpi@Pi:~$ swapon
NAME       TYPE      SIZE USED PRIO
/dev/zram0 partition 238M 1.8M   -2
```
but apparently `/usr/sbin/zramswap` script is unable to write to file `/sys/block/zram0/comp_algorithm`.

Problem is deterministic. Restarting service or rebooting does not fix the issue.

**Comment by MichaIng** [comment]
Many thanks for your report.

Why did you install `zram-tools`? It doubles with DietPi's zram swap implementation. So either you use `AUTO_SETUP_SWAPFILE_LOCATION=zram`, which configures a zram swap space via udev rules, without any service or process running in background, or you install and configure `zram-tools`, with it's own config file and a service which configures a zram swap space. Both together conflict, as you recognised 🙂.

**Comment by f-laurens** [comment]
My installation of `zram-tools` is the result of a generic routine to install additional packages which I apply both to my DietPi and Raspberry Pi OS images.
Thanks a lot for pointing out the duplication/conflict.
Indeed disabling the `zramswap` service on DietPi solves my issue.
