### ISSUE TITLE
Documentation update for Samba

### ISSUE THREAD

**Issue by RajatNair** [MichaIng/DietPi#542]
Was following instructions documented here - http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=10#p56 for Samba. After making changes to conf file and trying to start the service using - 
`service samba start`
following error was throw -

> Failed to restart samba.service: Unit samba.service is masked.

`service smbd start` or `systemctl restart smbd` works.

Guess we should update Samba docs.

**Comment by Fourdee** [comment]
@RajatNair 

Great find, you've also uncovered a bug 👍 

`smbd` and `nmbd` services were not being applied correctly by `dietpi-services`

I've updated online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=56#p56
`systemctl restart smbd nmbd`

**Comment by RajatNair** [comment]
I just came back to add that dietpi-services was throwing an error cause of Samba service -

>  DietPi-Services
> ─────────────────────────────────────────────────────
>  Mode: restart
>  Please wait...
>  [Ok] cron
>  [Failed] samba
>  [Ok] lighttpd

While @Fourdee already fixed it. That was quick! Nice work 👍
