### ISSUE TITLE
Software Request | Add Gitlab to Dietpi

### ISSUE THREAD

**Issue by rafidalhaque** [MichaIng/DietPi#5437]
#### Formal software information
- Software title | Gitlab
- Short description | Github open source alternative
- Official URL (if available) |  https://gitlab.com 
- GitHub URL (if available) | 
- (Official) install documentation | 

#### Are there similar/alternative software titles available with DietPi-Software?

- Gitea, Gogs

#### What makes your requested software better than the above solutions, if available?

- It is open source. Too much famous. And also have some unique features better than gitea or gogs.

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- ...

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

1. ...

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.

- Sorry, I'm not very expert to maintain it 😪

**Comment by Joulinar** [comment]
Might be similar to #500 right?
