### ISSUE TITLE
DietPi-Update | Checking network connectivity is failing

### ISSUE THREAD

**Issue by Leoin1** [MichaIng/DietPi#5446]
#### Details:
- Date           | Tue Apr 19 09:04:35 CST 2022
- DietPi version | v8.2.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `ping -nc 1 -W 10 9.9.9.9`
- Exit code      | 1
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.

--- 9.9.9.9 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```
---------------------------------------------------------------------
[FAILED] DietPi-Update | Unable to continue, DietPi-Update will now terminate.

**Comment by MichaIng** [comment]
This keeps failing?
```sh
ping 9.9.9.9
```
Nothing is for sure, but this IP should be reachable from all over the world as multicast IP with a large number of related data centres.

If it keeps failing, indeed you need to adjust these two settings, and, in case you use a static IP with Quad9 (`9.9.9.9`) as DNS server, change this as well.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
