### ISSUE TITLE
Failed to start systemd-timesyncd.service: Unit systemd-timesyncd.service not found

### ISSUE THREAD

**Issue by CodeSteph** [MichaIng/DietPi#5472]
#### Details:
- Date           | Tue Apr 19 08:56:26 CEST 2022
- DietPi version | v8.3.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Armbian
- Hardware       | ROCK Pi 4 (aarch64) (ID=72)
- Kernel version | `Linux FushichoPi 5.15.25-rockchip64 #22.02.1 SMP PREEMPT Sun Feb 27 09:05:47 UTC 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `systemctl start systemd-timesyncd`
- Exit code      | 5
- Software title | DietPi-TimeSync
#### Steps to reproduce:
the problem occures while I was executing dietpi-update
#### Expected behaviour:
no error is expected
#### Actual behaviour:
- Command: systemctl start systemd-timesyncd   
- Exit code: 5                                                              
- DietPi version: v8.3.1 (MichaIng/master) | HW_MODEL: 72 | HW_ARCH: 3 | DISTRO: 6   
- Image creator: DietPi Core Team                                          
- Pre-image: Armbian                                               
- Error log:                                                                                                        
Failed to start systemd-timesyncd.service: Unit systemd-timesyncd.service not found.  
#### Extra details:
<img width="442" alt="Capture d’écran 2022-05-04 à 23 28 03" src="https://user-images.githubusercontent.com/25659486/166828952-ee38fc99-582c-42f0-9bc4-027c144742bf.png">

#### Additional logs:
```
Failed to start systemd-timesyncd.service: Unit systemd-timesyncd.service not found.
```

**Comment by Joulinar** [comment]
usually this should have been fixed already. 

Can you share output of following

```
dpkg-query -s systemd-timesyncd &> /dev/null && [[ $(apt-mark showauto systemd-timesyncd) ]] && G_EXEC apt-mark manual systemd-timesyncd
```

**Comment by MichaIng** [comment]
It is only fixed if `systemd-timesyncd` was not already autoremoved. It it is, we cannot know whether it was intended or not, so I didn't want to touch things then.

**Comment by Joulinar** [comment]
Ah okay sorry that was a misunderstanding on my side

**Comment by CodeSteph** [comment]
Indeed @MichaIng is right,

The following NEW packages will be installed:
  systemd-timesyncd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

It's fixed, 
Thx
