### ISSUE TITLE
latest mpd version

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#5479]
Since the official Debian packages for mpd are outdated and unsupported by the project, I tried to update mpd on my RPi Zero W (armv6) with latest Diepi-Pi version (bullseye) following the instructions mentioned on mpd's official download page: 

 [Unofficial Debian/Raspberry Pi OS packages](https://www.musicpd.org/download-unoff-debian/)

It works fine. Maybe something for DietPi to implement?

**Comment by MichaIng** [comment]
Request open here 🙂: #4414

**Comment by maartenlangeveld** [comment]
Sorry, had not checked. Thanks!
