### ISSUE TITLE
Add -p option to mkdir for spotifyd installation

### ISSUE THREAD

**Issue by C0ntroller** [MichaIng/DietPi#5484]
When installing spotifyd using the dietpi interface an error happend when this line was executed:

https://github.com/MichaIng/DietPi/blob/5a7be6292a708d263167aee510595be2eb4b4439/dietpi/dietpi-software#L12132

The error happens because `/mnt/dietpi_userdata/spotifyd` does not exist. It can easily be solved by using `mkdir -p` to also create this parent directory.

**Comment by MichaIng** [comment]
Many thanks for your report. Right that is missing, I'll add it for next release.

**Comment by MichaIng** [comment]
Solved with: https://github.com/MichaIng/DietPi/commit/1ef7461
