### ISSUE TITLE
DietPi-Software | WiringPi: Install fails on Odroids

### ISSUE THREAD

**Issue by MDAR** [MichaIng/DietPi#5485]
#### Required Information
- DietPi version | ` G_DIETPI_VERSION_CORE=8`
                             `G_DIETPI_VERSION_SUB=4`
                             `G_DIETPI_VERSION_RC=2`
                             `G_GITBRANCH='master'`
                             `G_GITOWNER='MichaIng'`
- Distro version | `Bullseye`
- Kernel version | `Linux LiveStream-C4 4.9.241-arm64 #1 SMP PREEMPT Thu Feb 25 17:57:15 CET 2021 aarch64 GNU/Linux`
- SBC model | `Odorid C4`
- Power supply used | `12V 2Amp`
- SD card used | `16GB eMMC`

#### Additional Information (if applicable)
- Software title | `WiringPi: GPIO interface library (C)`
- Was the software title installed freshly or updated/migrated? - `Freshly installed - No 70`
- Can this issue be replicated on a fresh installation of DietPi? - `Yes, it happened before an update and afterwards`

- Bug report ID | `Reference code: e9065ed8-76b5-47f2-9cc1-3b8849e8d6ca`

```
 Step: Installing WiringPi: GPIO interface library (C)

[  OK  ] DietPi-Software | cd /tmp/DietPi-Software
[  OK  ] DietPi-Software | curl -sSfL https://github.com/hardkernel/wiringPi/archive/master.tar.gz -o master.tar.gz
[  OK  ] DietPi-Software | tar xf master.tar.gz
[  OK  ] DietPi-Software | rm master.tar.gz
[  OK  ] DietPi-Software | mv wiringPi-master WiringPi-master
[  OK  ] DietPi-Software | cd WiringPi-master
[ INFO ] DietPi-Software | ./build, please wait...
/boot/dietpi/func/dietpi-globals: line 850: ./build: No such file or directory
[FAILED] DietPi-Software | ./build
[ INFO ] DietPi-BugReport | Generating informative command outputs, please wait...
[ INFO ] DietPi-BugReport | cp /tmp/G_EXEC_ERROR_REPORT G_EXEC_ERROR_REPORT, please wait...
[  OK  ] DietPi-BugReport | cp /tmp/G_EXEC_ERROR_REPORT G_EXEC_ERROR_REPORT
[  OK  ] DietPi-BugReport | Packing upload archive
[  OK  ] DietPi-BugReport | Sending bug report
[  OK  ] DietPi-BugReport | Your bug report has been successfully uploaded.
- Reference code: e9065ed8-76b5-47f2-9cc1-3b8849e8d6ca
```

#### Steps to reproduce

Saw that Odrod C4 supports WiringPi - https://wiki.odroid.com/odroid-c4/application_note/gpio/wiringpi#tab__odroid-c41
(I'm sure I got it running on an Odroid C2 at some point in that past, but that was a while ago.)

1. Select option 70 from `dietpi-software`
2. Ran the install routine as guided
3. Returned the error

**Comment by Joulinar** [comment]
Looks like Hardkernel removed the old build script https://github.com/hardkernel/wiringPi/commit/f316f52636ade7c7d323d706119f855965cbba90

@MichaIng 
I guess we need to change installation procedure for Odroid device.

```
Building in local machine:
    $ sh autogen.sh
    $ ./configure
    $ make
    $ sudo make install
```

**Comment by MichaIng** [comment]
Thanks for your report. Will be fixed for next release.

**Comment by MichaIng** [comment]
Related commit from this January: https://github.com/hardkernel/wiringPi/commit/f316f52

**Comment by MichaIng** [comment]
Interesting, for Odroids (specifically Odroid M1), `libgpiod-dev` is required now. Based on the code it looks like the `gpio` executable basically uses `libgpiod` instead of WiringPi for this particular SBC.

The question is for what reason one uses WiringPi, respectively `gpio` at all then, since `apt install gpiod` and `libgpiod` basically replaced it (for SBCs which are supported). I guess it is just to have the same tool on all Odroids, but actually it makes sense to switch to `gpiod`/`libgpiod` completely instead of mixing `gpio` utility with `libgpiod` library for a single Odroid model and hence doubling build and runtime dependencies 🤔.
