### ISSUE TITLE
Sabnzbd reinstall issue

### ISSUE THREAD

**Issue by jaguar489** [MichaIng/DietPi#5498]
#### Required Information
- DietPi version | G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=4
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
- Distro version | bullseye
- Kernel version | Linux CutiePi 5.15.32-v8+ 1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
- SBC model | RPi4 4GB
- Power supply used: official power supply 
- SD card used  lexar or SanDisk 32GB

#### Additional Information (if applicable)
- Software title | Sabnzbd
- Was the software title installed freshly or updated/migrated?
- attempting to fresh reinstall
- Can this issue be replicated on a fresh installation of DietPi?
- have not tested

- Bug report ID | ffb05845-cb4e-4f7f-9a9b-578bb4e07177

#### Steps to reproduce
1. dietpi-software install 139

#### Expected behaviour
Sabnzbd should install without errors

#### Actual behaviour

Install fails with this error

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper

│ pkg_resources.py", line 200, in iter_dependencies                
│     return self._dist.requires(extras)
│   File
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 2736, in requires
│     dm = self._dep_map
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc
│ es/__init__.py", line 3023, in _dep_map
│     self.__dep_map = self._compute_dependencies()                
│   File
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 3032, in _compute_dependencies             
│     for req in self._parsed_pkg_info.get_all('Requires-Dist')
│ or []:
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc
│ es/__init__.py", line 3014, in _parsed_pkg_info
│     metadata = self.get_metadata(self.PKG_INFO)                  
│   File
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 1424, in get_metadata
│ pkg_resources.py", line 200, in iter_dependencies                
│     return self._dist.requires(extras)                           
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 2736, in requires                          
│     dm = self._dep_map                                           
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 3023, in _dep_map                          
│     self.__dep_map = self._compute_dependencies()                
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 3032, in _compute_dependencies             
│     for req in self._parsed_pkg_info.get_all('Requires-Dist')    
│ or []:                                                           
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 3014, in _parsed_pkg_info                  
│     metadata = self.get_metadata(self.PKG_INFO)                  
│   File                                                           
│ "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pkg_resourc  
│ es/__init__.py", line 1424, in get_metadata                      
│     return value.decode('utf-8')                                 
│ UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in      
│ position 2: invalid start byte in METADATA file at path:         
│ /usr/local/lib/python3.9/dist-packages/cffi-1.15.0.dist-info/ME  
│ TADATA                                                           
│
```

#### Extra details

- ...

**Comment by Joulinar** [comment]
Would it be possible to share the error on GitHub as well? Not everyone has access to the bug report. As well you could have filled the issue template. It has some sense and is not there for fun. 😉

**Comment by jaguar489** [comment]
Sorry I somehow created an issue in a way that missed the issue template, comment has been updated

**Comment by jaguar489** [comment]
It looks like there could possibly be some corruption involved since I also seem to get this error when attempting to install programs through apt-get install

dpkg: unrecoverable fatal error, aborting:
 files list file for package 'webmin' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)

Can this be fixed or would I be better off reflashing the card?

**Comment by Joulinar** [comment]
you could try following

```
> /forcefsck
reboot
# then after reboot
journalctl -t systemd-fsck
```

this should force a file system check on reboot.

**Comment by jaguar489** [comment]
Here are the results from running that

oot@CutiePi:~# journalctl -t systemd-fsck
-- Journal begins at Tue 2022-05-17 18:31:28 EDT, ends at Tue 2022-05-17 18:32:00 EDT. --
May 17 18:31:28 CutiePi systemd-fsck[139]: Please pass 'fsck.mode=force' on the kernel command line rather than creating /forcefsck on the root file system.
May 17 18:31:28 CutiePi systemd-fsck[161]: e2fsck 1.46.2 (28-Feb-2021)
May 17 18:31:28 CutiePi systemd-fsck[161]: Pass 1: Checking inodes, blocks, and sizes
May 17 18:31:31 CutiePi systemd-fsck[161]: Pass 2: Checking directory structure
May 17 18:31:36 CutiePi systemd-fsck[161]: Pass 3: Checking directory connectivity
May 17 18:31:36 CutiePi systemd-fsck[161]: Pass 4: Checking reference counts
May 17 18:31:36 CutiePi systemd-fsck[161]: Pass 5: Checking group summary information
May 17 18:31:36 CutiePi systemd-fsck[161]: /dev/mmcblk0p2: 348359/1942080 files (0.2% non-contiguous), 3699575/7797760 blocks
May 17 18:31:38 CutiePi systemd-fsck[264]: Please pass 'fsck.mode=force' on the kernel command line rather than creating /forcefsck on the root file system.
May 17 18:31:38 CutiePi systemd-fsck[271]: fsck.fat 4.2 (2021-01-31)
May 17 18:31:38 CutiePi systemd-fsck[271]: /dev/mmcblk0p1: 352 files, 64666/258077 clusters

**Comment by MichaIng** [comment]
Is it possible to reinstall webmin?
```sh
apt install --reinstall webmin
```

**Comment by Joulinar** [comment]
probably the best to start with a new image to bypass the corruption.

**Comment by MichaIng** [comment]
If it was only the corrupted webmin package file list, it would have been possible to remove it, including the status entry, and reinstall the package as if it was not installed before. But probably other files were affected as well.
