### ISSUE TITLE
RaspAP adoption

### ISSUE THREAD

**Issue by fmunteanu** [MichaIng/DietPi#5514]
#### Is your feature request related to a problem? Please describe:
Current solutions offer only wired connectivity through a secured DietPi Wifi hotspot.

#### Describe the solution you'd like:
A way to connect my laptop to a public WiFi network, through a secured DietPi Wifi hotspot. Please look at RaspAP and see if it can be adopted.

**Comment by Joulinar** [comment]
I'm going to close this request as it is basically a duplicate to these 2

https://github.com/MichaIng/DietPi/issues/2923
https://github.com/MichaIng/DietPi/issues/2813
