### ISSUE TITLE
DietPI does not respond

### ISSUE THREAD

**Issue by bellwethersmi** [MichaIng/DietPi#5541]
#### Required Information
- DietPi version | `8`
- Distro version | `N/I`
- Kernel version | `N/I`
- SBC model | `RPi400`
- Power supply used | N/I
- SD card used | SanDisk Ultra 256GB

Hey together, i just tried to reinstall my Pi400 with DietPi (Headless), strangely enough it appears in my router, but I can't ping it or access it via SSH. Since I unfortunately have no screen only a headless option comes into question and I don't know what I'm doing wrong - Maybe someone of you can help / knows this problem. (Little extra info; When I ping it it says "Target host not available).

_(Translated from German into English, translation errors may occur)._

**Comment by Joulinar** [comment]
Is the device connected via WiFi or Ethernet?

**Comment by Joulinar** [comment]
Did you configured DHCP or STATIC IP address?

**Comment by MichaIng** [comment]
Marking as closed. Feel free to reopen if required.
