### ISSUE TITLE
DietPi-Software | Home Assistant 

### ISSUE THREAD

**Issue by sytone** [MichaIng/DietPi#556]
This is a python based home automation platform. I am running it on my PINE64 board on dietpi.

I have had a quick look at the install scripts and may take this on myself. Suggestions on how to approach and good examples so I can cover install and updates. 

https://home-assistant.io/

**Comment by Fourdee** [comment]
@sytone 

Looks interesting, if you wish to add this into DietPi-Software yourself, here is a walkthrough of the source code to complete this: https://github.com/Fourdee/DietPi/issues/490#issuecomment-244416570

**Comment by sytone** [comment]
I added it, one more issue down
