### ISSUE TITLE
XU4 fails to power on

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#558]
As reported by some XU4 users: http://dietpi.com/phpbb/viewtopic.php?f=11&t=707&p=3337#p3337

Unable to replicate on my system.

**Comment by Fourdee** [comment]
Re-created the DietPi image from scratch. On the off chance we had some corruptions on the base image due to FStrim a while back: http://dietpi.com/downloads/testing/DietPi_OdroidXU4-armv7-(Jessie).7z

Requires user testing: http://dietpi.com/phpbb/viewtopic.php?f=11&t=707&p=3361#p3361

Failing the above, would require users to test with Meveric's base image and try to replicate issue.

**Comment by biccy** [comment]
Yep, with the newly downloaded image, I can now use the poweroff command or just pull the power and the XU4 boots up fine afterwards every time. Previously it NEVER booted again once I ran poweroff or pulled the power (it only rebooted with the reboot command).

**Comment by Fourdee** [comment]
@biccy 
Excellent, thanks for testing and letting us know 👍 

I'll move this and replace the current image download.

**Comment by nphil** [comment]
Good to hear, I would assume this requires a clean flash of the OS image again? As in, any chance of an update to fix it?

**Comment by Fourdee** [comment]
@nphil 
Will need a clean install, unfortunately. Most likely the partitions and/or table on our previous image is corrupt/misaligned which is causing the no boot issue.

**Comment by justin0a0** [comment]
I experienced this issue this morning using the old (127) image when I hit the power button.
Used the new image and no issues with it so far issued poweroff and used the button reboots went fine.

**Comment by Fourdee** [comment]
@nphil @justin0a0 @biccy 
Thanks guys for your help testing! 👍 
We can now mark this one as resolved.
