### ISSUE TITLE
Triyng to install a custom vpn service doesnt get the correct .crt file

### ISSUE THREAD

**Issue by p4cm4n** [MichaIng/DietPi#5584]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
- Kernel version | `uname -a`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
- Power supply used | (EG: 5V 1A RAVpower)
- SD card used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. get .conf file from vpn provider
2. triying to install it through dietpi-vpn

#### Expected behaviour

- VPN installed and working
- 
#### Actual behaviour

- the script doesn't discover the location of the crt file (evne though is in the same folder as the .conf 

#### Extra details

Jun 30 20:07:59 DietPi openvpn[631287]: DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
Jun 30 20:07:59 DietPi openvpn[631287]: Options error: --ca fails with 'mullvad_ca.crt': No such file or directory (errno=2)
Jun 30 20:07:59 DietPi openvpn[631287]: Options error: Please correct these errors.
Jun 30 20:07:59 DietPi openvpn[631287]: Use --help for more information.

- ...

The vpn install correctly (in fact, the service is running, but I don't think it's able to connect correctly 

Thanks for your support :)

**Comment by Joulinar** [comment]
Maybe the following file is needed `mullvad_ca.crt` and would need to be placed within `/etc/openvpn/`. https://mullvad.net/de/help/linux-openvpn-installation/

**Comment by p4cm4n** [comment]
I left the project on hold, better to close it, thank you very much for your support :)
