### ISSUE TITLE
After 5 days of work Pi locked up and couldn't read/write from boot stick

### ISSUE THREAD

**Issue by AAS-Crypt** [MichaIng/DietPi#5587]
#### Required Information
- DietPi version | `8.5.1`
- Distro version | `bullseye 0`
- Kernel version | `Linux DietPi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | `5V 3.5A Samsung`
- SD card used | `DataTraveler 100 G3 64GB - USB stick`

#### Steps to reproduce

1. I can't imagine how, today I reduced tasks to 1 which works every 15 minute, it's not that heavy compared to my last report.
2. Expose to long uptime.

#### Expected behaviour

To work fine.

#### Actual behaviour

Raspberry Pi dead locked, without ability to log in, after loging in to Pi - locally. Prints out lines below.  Interestingly it began behaving like this after 5 days of constant working.

#### Extra details

These are the logs that being printed on screen in ratio 1:4, being 1 proftpd to 4 zerotier.
[495401.244418] EXT4-fs error (device sda2): __ext4_find_entry:1614: inode #3161: comm proftpd: reading directory iblock 0
[495401.056099] EXT4-fs error (device sda2): __ext4_find_entry:1614: inode #16: comm zerotier-one: reading directory iblock 0
After rebooting Pi I get this on my screen.
![WhatsApp Image 2022-07-02 at 16 20 42](https://user-images.githubusercontent.com/77435348/176996500-884de44c-ea93-4ce2-b9cc-8d60df568865.jpeg)

**Comment by AAS-Crypt** [comment]
Got an video from booting Pi up without pre-installing USB stick to slot, and after the Boot image is shown connecting Boot stick.

Appears to me that some software cleaned up my volumes on boot driver.
https://user-images.githubusercontent.com/77435348/176996836-aac6790d-7fd4-474c-aaba-9fd6e9b1f3e0.mp4

Now will be inspecting my USB stick.

**Comment by AAS-Crypt** [comment]
After inspectioning it I have to conclusion that USB stick is read-only. I would appreciate any help on this matter.

**Comment by MichaIng** [comment]
You have filesystem errors. Please do the following to try fixing them:
```sh
mount -o remount,rw /
> /forcefsck
reboot
# after reboot
journalctl -t systemd-fsck
```

**Comment by AAS-Crypt** [comment]
I have only DataTraveler. Will try rn. Maybe keyboard is locked only on first tty.

**Comment by MichaIng** [comment]
Ah, right, it's `sda`, so first/only USB drive, I had a little mind outage 😅.

Saw the video just now, looks like it wouldn't even reach a point where `fsck` can run. I think you need to attach and fix it on another Linux system them. Also check the content of the boot partition (first partition with FAT filesystem) then, which you can also do on Windows, of course, probably it contains `FSCK*` named files, fsck backups, which indicate that there have been found some corruption before.

While SD cards are known to wear fast, USB drives should be actually more robust 🤔. Is that a new stick or an older one?

**Comment by AAS-Crypt** [comment]
Pi printing out same response as on photo. Keyboard is locked, already tried to unlock usb driver in Windows, will try in linux later on.

**Comment by AAS-Crypt** [comment]
> Saw the video just now, looks like it wouldn't even reach a point where `fsck` can run. I think you need to attach and fix it on another Linux system them. Also check the content of the boot partition (first partition with FAT filesystem) then, which you can also do on Windows, of course, probably it contains `FSCK*` named files, fsck backups, which indicate that there have been found some corruption before.

Yes I found FSCK0000.REC

> While SD cards are known to wear fast, USB drives should be actually more robust 🤔. Is that a new stick or an older one?

Pretty new been bought in 2020

**Comment by AAS-Crypt** [comment]
Here is the contents of file : 
G_HW_MODEL=4
G_HW_MODEL_NAME='RPi 4 Model B (aarch64)'
G_HW_ARCH=3
G_HW_ARCH_NAME='aarch64'
G_HW_CPUID=0
G_HW_CPU_CORES=4
G_DISTRO=6
G_DISTRO_NAME='bullseye'
G_ROOTFS_DEV='/dev/sda2'
G_HW_UUID='3dd5552d-fa1e-47a7-a519-c05dd9bc1238'
G_RASPBIAN=0
G_HW_ONBOARD_WIFI=1
G_HW_REVISION='d03114'
G_HW_PCB_REVISION=4
G_HW_MEMORY_SIZE=8192
G_HW_MANUFACTURER='Sony UK'

**Comment by MichaIng** [comment]
> Here is the contents of file :

Okay that's `/boot/dietpi/.hw_model`, that isn't critical and is recreated at reboot automatically. so you can remove that one.

> Pretty new been bought in 2020

Power there a sudden power outage or unclean shutdown?

**Comment by AAS-Crypt** [comment]
> Okay that's `/boot/dietpi/.hw_model`, that isn't critical and is recreated at reboot automatically. so you can remove that one.

Will try on Linux system, as Windows doesn't allow me to remove files from Driver.

> Power there a sudden power outage or unclean shutdown?

Neither, rather 100 hours bottleneck, after which I wasn't able to interact with Pi neither via ssh or keyboard, after reboot it kept showing me that image from above

**Comment by MichaIng** [comment]
Okay, let's hope another Linux system can repair it. Let's then see whether it happens a second time, and if so, I suggest to enable persistent system logs to enable the ability to see what happened before the crash and when first filesystem or I/O errors happened.

**Comment by AAS-Crypt** [comment]
Okay, will try to implement it and keep updating information.

**Comment by AAS-Crypt** [comment]
Just to be sure typing "repair" you mean override readonly option and removing "FSCK0000.REC"?

**Comment by AAS-Crypt** [comment]
My system mounts
![image](https://user-images.githubusercontent.com/77435348/177039430-6d727305-2afd-4912-81d6-ecc7431cab1c.png)

Mounted both partitions in linux distro. 
First partition automatically mounted, but in order to make it writable I proceed with this command `mount -o remount,rw /dev/sdb1 /media/sdb1`
-command in question `mount -o noload,ro /dev/sdb2 /media/sdb2`  | I was able to mount second partition succesfully, but only in read only mode.
-command in question `mount -o remount,rw /dev/sdb2 /media/sdb2` | And then when I remount it with readwrite parameters, I get these lines respectively.
fsck can succesfully run on sdb1 but aborts while running on sdb2

![image](https://user-images.githubusercontent.com/77435348/177039194-f0a3abd2-5f02-44d7-924f-a53c6acef076.png)

**Comment by MichaIng** [comment]
> Just to be sure typing "repair" you mean override readonly option and removing "FSCK0000.REC"?

Especially I mean to run an `fsck` on both partitions from an external Linux system. For `fsck` on the second partition to run, it must not be mounted. What is the error message `fack` returns?

**Comment by AAS-Crypt** [comment]
![image](https://user-images.githubusercontent.com/77435348/177041596-bd6b0508-bde7-41a6-b68a-744a2fea6fb4.png)
That's the output for sdb2 

![image](https://user-images.githubusercontent.com/77435348/177041608-102e1286-c6eb-49a3-aa1d-12ebac38bf01.png)
That's the ouput for sdb1 

While they are unmounted : 
sdb1 : 
![image](https://user-images.githubusercontent.com/77435348/177041635-d487323a-d626-4abe-9303-6fb07a9d24b1.png)

sdb2: 
![image](https://user-images.githubusercontent.com/77435348/177041647-2649998d-f177-440a-b852-698b6a327364.png)

**Comment by Joulinar** [comment]
If possible try to avoid doing screen shots. You should be able to copy the content directly from SSH session

**Comment by MichaIng** [comment]
Please try:
```
hdparm -r0 /dev/sdb2
hdparm -r /dev/sdb2 # check back
fsck -p /dev/sdb2
```

**Comment by AAS-Crypt** [comment]
Strangly, clipboard is not working so I cannot insert here text from my VM.
I see this problem as urgent so I will send text messages when I will figure out why It's not working.
![image](https://user-images.githubusercontent.com/77435348/177044879-14af3dc6-fb87-4888-93a1-592517e74f93.png)

**Comment by Joulinar** [comment]
Is the drive mounted? I guess this is not necessary 

//offtopic: Did you tried using SSH? There you should be able to copy the stuff 😃

**Comment by AAS-Crypt** [comment]
I'm currently using Host-to-Machine networking. Later on will change and try to ssh in.

Drive is required to be unmounted to be able to use fsck -p on it. While being mounted it will not be able to repair drive.

**Comment by MichaIng** [comment]
Is it the same (no write protection flag) for the whole disk?
```sh
hdparm -r /dev/sdb
hdparm -r0 /dev/sdb
```

**Comment by AAS-Crypt** [comment]
```
root@dhcppc10:/home/demo# hdparm -r /dev/sdb

/dev/sdb:
  readonly          =   1 (on)
root@dhcppc10:/home/demo# hdparm -r0 /dev/sdb

/dev/sdb:
  setting readonly to 0 (off)
  readonly          =   0 (off)
root@dhcppc10:/home/demo# fsck -p /dev/sdb
fsck from util-linux 2.36.1
fsck.ext2: Read-only file system while trying to open /dev/sdb
Disk write-protected; use the -n option to do a read-only
check of the device.
```
That's the output

**Comment by MichaIng** [comment]
```sh
fsck -p /dev/sdb2
```
A drive cannot be checked, only a filesystem 😉.

**Comment by AAS-Crypt** [comment]
By this point i have no means in understanding if the recovery could even
be made. I've done the command says that filesystem is read only.
Right now i have two options :
First being that I will give you access to VM.
Second is that I will proceed with fresh install of dietpi.

пн, 4 июл. 2022 г., 1:15 AM MichaIng ***@***.***>:

**Comment by MichaIng** [comment]
One more attempt:
```sh
sfdisk --no-reread --no-tell-kernel -fN2 /dev/sdb <<< ',+'
partprobe /dev/sdb
partx -u /dev/sdb
sleep 1
hdparm -r0 /dev/sdb
fsck -p /dev/sdb2
```

Probably there are other ways to try repairing the drive, but even when this is done, I guess some files are missing, which may not be obvious but cause subtile issues at a later time. So if the above doesn't work either, I'd go with a fresh install to a new/another USB stick and copy back data/configs from the old one. A USB stick should survive longer, but probably you got an unlucky piece. After all data has been copied off of it, format it cleanly, after which it can be probably used again. Depends on whether there are really dirty bits (hardware damage) or it was just some deeper data damage.

**Comment by AAS-Crypt** [comment]
Yes I've tried and still no result from these commands. Hopefully it's only on my memory drive.
Thanks for your attempts in teaching me how to repair broken driver. With this I'll wipe USB drive and install freshly released dietpi.
