### ISSUE TITLE
Dietpi_Drive_Manager add support for MergerFS

### ISSUE THREAD

**Issue by paradix** [MichaIng/DietPi#5622]
#### Is your feature request related to a problem? Please describe:

- Adding mergerfs entry to ```/etc/fstab``` gets deleted once you use Dietpi_Drive_Manager
- As example here is an entry to fstab:
```/mnt/disk* /mnt/storage fuse.mergerfs defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs 0 0```

#### Describe the solution you'd like:

- It would be enough if Dietpi_Drive_Manager would just leave the manual entry as is.
- Best if it would be able to handle and add entries for MergerFS

#### Describe alternatives you've considered:

- none

#### Additional context

- ...

**Comment by MichaIng** [comment]
Support has been added for next release: https://github.com/MichaIng/DietPi/commit/58f6601
