### ISSUE TITLE
Cant seem to get wifi working on pi zero w with dietpi

### ISSUE THREAD

**Issue by doobersn** [MichaIng/DietPi#5628]
deleted

**Comment by Joulinar** [comment]
At least you could have shared how you fixed it. Probably there are other user who will run into similar issue. 😉

**Comment by doobersn** [comment]
> At least you could have shared how you fixed it. Probably there are other user who will run into similar issue. 😉

Apologies! I had to set the wifi name and password and enable wifi in the text files before the _first_ boot. Anytime after that and it wouldnt work. I dont think that was mentioned anywhere that it won't work after first boot but im also very bad at the stuff and thought it might be common knowledge for others besides me.

**Comment by Joulinar** [comment]
settings done to `dietpi-wifi.txt` file are applicable on first boot only. Afterwards you would need to use `dietpi-config` to enable WiFi.
