### ISSUE TITLE
DietPi-Software | WiringOP support for H3 chipsets

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#563]
> H3 https://github.com/zhaolei/WiringOP
> EDIT: REMOVED OBSOLETE LINK

**Comment by Fourdee** [comment]
This is alot more involved than originally thought. As mentioned by Pete on forums, GPIO assignments are likely to be different for various boards. So, the WiringOP source code will need to be modified and tested. 

I don't really have the time (and minimal GPIO experience) to take this on at the moment.

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by Fmert24** [comment]
ı find github page that instaled wiringop successfully for orangepi zero lts
https://github.com/zhaolei/WiringOP/tree/h3

**Comment by MichaIng** [comment]
Based on our current SBC support, a RK3588-compatible version would be relevant. But that repo/branch got its last commit in 2017.

Nowadays WiringX needs to be seen as deprecated in general, as we have generic libgpio/[gpiod](https://packages.debian.org/gpiod) now. It is not yet perfect, not yet supported by all SBCs/used kernels, behaves a little different here and there, but it is the future to go for, getting rid of all those moreless badly maintained WiringPi vendor forks.

**Comment by Fmert24** [comment]
> Based on our current SBC support, a RK3588-compatible version would be relevant. But that repo/branch got its last commit in 2017.
> 
> Nowadays WiringX needs to be seen as deprecated in general, as we have generic libgpio/[gpiod](https://packages.debian.org/gpiod) now. It is not yet perfect, not yet supported by all SBCs/used kernels, behaves a little different here and there, but it is the future to go for, getting rid of all those moreless badly maintained WiringPi vendor forks.

thank you for updating me on gpio libary condition
