### ISSUE TITLE
set GPIO (for specified PIN) level on boot (or power on)

### ISSUE THREAD

**Issue by almirus** [MichaIng/DietPi#5633]
#### Is your feature request related to a problem? Please describe:

- I want to set pin 37 (GPIOAO_9) when booting into HIGH level. There is connected switcher for HDMI display (default is OFF) and not showing booting process.

**Comment by MichaIng** [comment]
Which SBC and Debian version are you using?

**Comment by almirus** [comment]
radxa zero 
Bullseye

**Comment by MichaIng** [comment]
Please try with libgpio:
```sh
apt install gpiod
```

**Comment by almirus** [comment]
yes
but how to set gpio before load OS (or while booting)?

**Comment by WolfganP** [comment]
> yes but how to set gpio before load OS (or while booting)?

Before loading the OS you obviously have almost nothing running other than the initialization firmware of your board.
OS booting is a multistep process, so "while booting" means you need to define exactly at which step your gpio action is needed (ie define precedence, need it before X Y and Z occurs).
Did you try issuing the gpio command in /etc/rc.local or via a custom systemd entry?

**Comment by MichaIng** [comment]
udev rules should be a clever way to assign GPIO states as fast as the device is detected by the kernel.

**Comment by almirus** [comment]
@MichaIng hello, do you have any example for this?

**Comment by MichaIng** [comment]
Like so, setting GPIO 21 of chip 0, as fast as GPIO chip 0 is added/detected:
```sh
echo 'SUBSYSTEM=="gpio", KERNEL=="gpiochip0", ACTION=="add", RUN+="/usr/bin/gpioset gpiochip0 21=1"' > /etc/udev/rules.d/99-gpio.rules
```

**Comment by MichaIng** [comment]
Did this work for you?

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Please reopen when you have feedback on the suggested udev rule.
