### ISSUE TITLE
Node-RED installation does not install any webbrowser on a fresh DietPi installation

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi#5648]
#### Required Information
- DietPi version | 
  - G_DIETPI_VERSION_CORE=8
  - G_DIETPI_VERSION_SUB=7
  - G_DIETPI_VERSION_RC=0
  - G_GITBRANCH='dev'
  - G_GITOWNER='MichaIng'

- Distro version | bullseye
- Kernel version | `Linux r5s 5.10.110 #81 SMP Mon Jul 4 15:26:21 CST 2022 aarch64 GNU/Linux`
- SBC model | Generic Device (aarch64), NanoPi R5s

#### Additional Information (if applicable)
- Software title | Node-RED (`#122`)
- Was the software title installed freshly or updated/migrated? Freshly on a fresh DietPi installation
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Steps to reproduce

1. Run `dietpi-software install 122`
2. Try to access your Node-RED instance via port 1880 or the webserver default page
    ![grafik](https://user-images.githubusercontent.com/57687516/180786374-0d9d4352-4ff2-469e-8f02-a03ea0b6fd32.png)

#### Expected behaviour

- The Node-RED page should appear:
    ![grafik](https://user-images.githubusercontent.com/57687516/180786556-eea72046-d17c-416b-ab34-98402f83a56d.png)
- I.e. a webserver installation should be triggered by the Node-RED installation
  

#### Actual behaviour

- No webpage is displayed
- In `dietpi-software`, no webserver is shown as an installed package

#### Extra details

- If a webserver is installed manually (e.g. `dietpi-software install 85`) and the system is rebooted, Node-RED can be accessed

**Comment by Joulinar** [comment]
Usually NodeRed is having an own web server and there shouldn't be a need to install Apache or Nginx.

**Comment by StephanStS** [comment]
> Usually NodeRed is having an own web server and there shouldn't be a need to install Apache or Nginx.

I'll check this (maybe it was a http vs. https problem).

**Comment by StephanStS** [comment]
@Joulinar: Right, webserver runs also in base installation. Problem occured due to usage of https: which is not valid in a base installation.

**Comment by Joulinar** [comment]
Correct. 😄
