### ISSUE TITLE
USB Soundcard Not Detected Anymore 

### ISSUE THREAD

**Issue by seniorm0ment** [MichaIng/DietPi#5663]
I had it working, then it had randomly stopped.
I just updated the system (stooped working before that), to see if it would fix. Did not.

aplay -l does not list it. Also tried uninstalling alsa and reinstalling, did not fix.
I use it for mopidy. I also tried dietpi-config and selecting usb dac, when I click ok it shows none, and cli says usb-soundcard exited with error.

It's a Schiit Modi USB dac, tried two different USB ports.

**Comment by MichaIng** [comment]
Many thanks for your report.

Please fill the bug report template, so we get the required information about your hardware and software. Please also add `dmesg -l emerg,alert,crit,err` or, if it doesn't contain something related, `dmesg | tail -10` some seconds after attaching the USB DAC.

**Comment by seniorm0ment** [comment]
Apologies, the bug templates don't get shown when using the Fasthub app. I will logon to web github when I get time and provide this info!

**Comment by MichaIng** [comment]
Any news from your end, regarding the info we'd need to help you?

**Comment by seniorm0ment** [comment]
Apologies, I kept meaning to get around to this. My room is completely torn apart due to moving stuff around so it's not even hooked up right now. I will get back

**Comment by MichaIng** [comment]
I'll mark it as closed for now (cleanup), please reopen when you find time to come back to this issue 🙂.
