### ISSUE TITLE
Alacritty is not a supported terminal

### ISSUE THREAD

**Issue by Helmet93** [MichaIng/DietPi#5666]
I have started using Alacritty as my default terminal. This presents a small issue when I `ssh` to my DietPi computers. I am presented with an error about an incompatible terminal. So far the automatic XTERM workaround seems to work.

#### Describe the solution you'd like:
Add Alacritty to the list of supported terminals. 

#### Describe alternatives you've considered:
Continuing to use the automatic solution that passes the XTERM flag rather than Alacritty.

**Comment by MichaIng** [comment]
The list of supported terminals is managed by the respective Debian packages, so we have no effect on this.

When you login via SSH, there should be no terminal emulator used, respectively the SSH client passes the relevant `TERM` variable. Or is Alacritty a SSH client as well?

The terminal support indeed needs to be installed manually: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo

**Comment by Mossy93** [comment]
Alacritty is a terminal emulator. I am using the `ssh` command in my terminal to connect to my DietPi systems remotely.

I will try that and see if it works.

**Comment by Mossy93** [comment]
Here is a screenshot of the error I get. One second while I try installing the terminal support.

![Screenshot_20220802_134325](https://user-images.githubusercontent.com/57846170/182439799-89fd775a-9dff-4b41-9905-3e0def2e2264.png)

**Comment by Mossy93** [comment]
Looks like it fixed it. Thanks.
