### ISSUE TITLE
DietPi-Globals | G_CHECK_NET: Skip IPv6 check within G_EXEC loop when disabled

### ISSUE THREAD

**Issue by derSebastian** [MichaIng/DietPi#5667]
#### Details:
- Date           | Tue Aug  2 04:16:14 BST 2022
- Bug report     | 3ade23f1-c7ea-4bac-bdac-db3fbe93bf54
- DietPi version | v8.7.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi B (armv6l) (ID=1)
- Kernel version | `Linux pihole.local 5.15.32+ #1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `ping -6nc 1 -W 10 2620:fe::fe`
- Exit code      | 2
- Software title | DietPi-Software
#### Steps to reproduce:

1. enter dietpi-software 
2. sleect unbound package
3. select install
#### Expected behaviour:

installation of unbound to complete

#### Actual behaviour:

- multiple errors
- at first i turned off IPv6 to see if that changed the message and it did:
Previous Error with IPv6 turned ON:

 Checking IPv6 network connectivity                                                                                   │
                                      │  - Command: ping -6nc 1 -W 10 2620:fe::fe                                                                            │
                                      │  - Exit code: 1                                                                                                      │
                                      │  - DietPi version: v8.7.1 (MichaIng/master) | HW_MODEL: 1 | HW_ARCH: 1 | DISTRO: 6                                   │
                                      │  - Image creator: DietPi Core Team                                                                                   │
                                      │  - Pre-image: from scratch                                                                                           │
                                      │  - Error log:                                                                                                        │
                                      │ PING 2620:fe::fe(2620:fe::fe) 56 data bytes                                                                          │
                                      │ From fe80::2a80:88ff:fe1e:178f%eth0 icmp_seq=1 Destination unreachable: Beyond scope of source address               │
                                      │                                                                                                                      │
                                      │ --- 2620:fe::fe ping statistics ---                                                                                  │
                                      │ 1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

#### Extra details:

- raspberry pi model 3A
#### Additional logs:
```
ping: connect: Cannot assign requested address
```

**Comment by MichaIng** [comment]
> ping: connect: Cannot assign requested address

This is the error you see when you disable IPv6? Actually it should then skip this check (after disabling IPv6) and head on to the DNS resolver check 🤔.

**Comment by derSebastian** [comment]
@MichaIng That just gave me an idea. and I tried it again and this time I had the option to 'continue AFTER disabling IPv6' form the installation menu. That also restarted a lot of the services (is that the right word?) unmask & stop - then pulled new release updates and APT updates. 
And then it installed unbound... Mhhh. I wont swear to it but I didn't see that option there before (maybe it was too late)

**Comment by MichaIng** [comment]
Ah right, that option I meant. Yeah it's a bit a problem that when you disable IPv6 another way, e.g. by entering `dietpi-config`/network settings, the same test is repeated, which can then only fail. I've just an idea about how to solve this with a pre-step which always skips the test (within the error handler loop) when no IPv6 gateway is found. I'll convert this into an Enhancement for next release.

**Comment by derSebastian** [comment]
Thanks, that's prob a good idea for ppl like me (just dangerous enough to screw things up another way - ;))

**Comment by MichaIng** [comment]
Implemented with: https://github.com/MichaIng/DietPi/commit/1e38413
Affects CONFIG_CHECK_CONNECTION/DOMAIN dietpi.txt settings the same way, i.e. if those are changed while the error handler is open, and you hit "Retry", the check is performed with the new IP/domain.
