### ISSUE TITLE
PiHole - password protect admin page

### ISSUE THREAD

**Issue by sootstone** [MichaIng/DietPi#568]
@pi-hole have a solution for password protecting the web admin page of pi-hole on a lightttpd [http://jacobsalmela.com/password-protect-a-lighttpd-web-server-on-a-raspberry-pi-using-mod-auth/](http://jacobsalmela.com/password-protect-a-lighttpd-web-server-on-a-raspberry-pi-using-mod-auth/)

Might be impossible, but would there be a way to add that kind of functionality into DietPi for other webservers (e.g. Apache2, Nginx)?

**Comment by sootstone** [comment]
Seems like the pi-hole people are working on a way to password protect [https://discourse.pi-hole.net/t/password-protect-the-dashboard/223](https://discourse.pi-hole.net/t/password-protect-the-dashboard/223)

**Comment by Fourdee** [comment]
> Seems like the pi-hole people are working on a way to password protect https://discourse.pi-hole.net/t/password-protect-the-dashboard/223

Marking as closed.
