### ISSUE TITLE
Samba installation problems

### ISSUE THREAD

**Issue by Challe777** [MichaIng/DietPi#5695]
#### Details:
- Date           | Sat Aug 20 17:13:06 BST 2022
- DietPi version | v8.5.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -y --allow-change-held-packages install samba`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:
I uninstalled samba server because I messed up a configuration file
1. ...
2. ...
#### Expected behaviour:
I wanted a clean fresh install
- ...
#### Actual behaviour:
this error message
- ...
#### Extra details:

- ...
#### Additional logs:
```
Reading package lists...
Building dependency tree...
Reading state information...
samba is already the newest version (2:4.13.13+dfsg-1~deb11u5).
0 upgraded, 0 newly installed, 0 to remove and 192 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up samba-common-bin (2:4.13.13+dfsg-1~deb11u5) ...
Checking smb.conf with testparm
Load smb config files from /etc/samba/smb.conf
set_variable_helper(= yes): value is not boolean!
Error loading services.
dpkg: error processing package samba-common-bin (--configure):
 installed samba-common-bin package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of samba:
 samba depends on samba-common-bin (= 2:4.13.13+dfsg-1~deb11u5); however:
  Package samba-common-bin is not configured yet.

dpkg: error processing package samba (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 samba-common-bin
 samba
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Joulinar** [comment]
Plus remove configuration file and try 

`rm /etc/samba/smb.conf`

**Comment by Challe777** [comment]
rm removes the file?

**Comment by Joulinar** [comment]
Yes https://linuxize.com/post/rm-command-in-linux/

**Comment by Challe777** [comment]
and then install again or uninstall?

lör 20 aug. 2022 kl. 18:40 skrev Joulinar ***@***.***>:

**Comment by Joulinar** [comment]
Try to install it again

**Comment by Challe777** [comment]
thanks that fixed the problem and the config file looks normal now :)

lör 20 aug. 2022 kl. 18:44 skrev Joulinar ***@***.***>:

**Comment by Joulinar** [comment]
Ok, going to close the issue.
