### ISSUE TITLE
DietPi-Software | Add Redis installation option

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#57]
Please consider adding Nginx 1.8 **not LEMP stack** (latest stable) install option, and Redis 3.0.X (repo has old 2.4 option). 

Btw. I have few sketches of design, so next week I'll add them inside design issue.

**Comment by Fourdee** [comment]
note to self:
non-SQL based data/key storage server.

**Comment by blindpet** [comment]
Unfortunately the latest redis in repos is always ancient and to my knowledge they do not have an official repo. It is easy to script building from source. I use [these instructions](http://www.htpcguides.com/install-configure-latest-redis-cache-wordpress/)

**Comment by Fourdee** [comment]
@blindpet

Thanks for the info. I'll give the compiling a spin.

notes to self: compile .deb for
ARMv6
ARMv7
x64

**Comment by Fourdee** [comment]
v113 will contain the installation from apt. When I continue work on EmonPi https://github.com/Fourdee/DietPi/issues/210 I will modify the install to latest version and compile.

**Comment by Fourdee** [comment]
Note to self: Add usage details to dietpi.com/software?

**Comment by Fourdee** [comment]
Available in v113 as a apt-get install.

**Comment by Fourdee** [comment]
Moved to v114 to improve it using latest redis server version, which will be from compiled source.

**Comment by Fourdee** [comment]
Created a new ticket for v114 to update the current apt-get install to latest version (from source): https://github.com/Fourdee/DietPi/issues/244
