### ISSUE TITLE
Reference code: 1e071e9e-6b83-4fd6-bebb-6bf3931f9e9a

### ISSUE THREAD

**Issue by W1LKC0** [MichaIng/DietPi#5700]
Reference code: 1e071e9e-6b83-4fd6-bebb-6bf3931f9e9a

**Comment by Joulinar** [comment]
Maybe you can fill our bug report or at least write some more words on what your issue is.

**Comment by MichaIng** [comment]
Jep, please provide some base info here, filling the bug report template. It isn't productive for us to start browsing to the uploaded config and log files without knowing what we need to look for 😉.

**Comment by W1LKC0** [comment]
You can close report i speak french language barrier if you need help for support in french language im here

Cordialement,
Ismael Cormier
Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
