### ISSUE TITLE
Webmin login password === root password at time of webmin install

### ISSUE THREAD

**Issue by ideomux** [MichaIng/DietPi#572]
Suggesting clarification of webmin documentation
<img width="448" alt="screen shot 2016-10-20 at 11 56 56 pm" src="https://cloud.githubusercontent.com/assets/15969369/19589425/031dee0a-9721-11e6-8001-8f4cddfe399c.png">

**Comment by Fourdee** [comment]
@ideomux 

Tested and confirmed, webmin password is root password at time of install. Great spot 👍 

Updated:
![image](https://cloud.githubusercontent.com/assets/7077026/19601004/52fa2ca8-979f-11e6-9d85-ad81116a81c1.png)

Will mark as closed.
