### ISSUE TITLE
DietPi-Imager hidden?

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#5721]
Updated, rebooted. DietPi-Imager is nowhere to be found.

**Comment by Joulinar** [comment]
The imager tool is not located on the system. It's a script we host on GitHub and it would need to be download on-demand.

`bash -c "$(curl -sSfL 'https://raw.githubusercontent.com/MichaIng/DietPi/master/.build/images/dietpi-imager')"
`

**Comment by maartenlangeveld** [comment]
I keep learning luckily. What does the script do, do I need it?

**Comment by maartenlangeveld** [comment]
Ok thanks a lot ! I will close this thread.
