### ISSUE TITLE
OTG does not work on Rock Pi 4B

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#5722]
I’m having trouble getting the OTG to work on the Rock Pi 4B. I have enabled it in the .dtb file, `/sys/class/udc` is empty and OTG does not work.

**Comment by MichaIng** [comment]
Many thanks for your report.

How did you enable it in the ".dtb file"? Usually one would use a device tree overlay then, not sure if there is one present and functional for OTG on current Armbian "rockchip64" kernel, which we use for our ROCK Pi 4 images.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
