### ISSUE TITLE
Exclude services for restart after modifying DietPi settings

### ISSUE THREAD

**Issue by scetu** [MichaIng/DietPi#5736]
#### Is your feature request related to a problem? Please describe:

- All services are automatically restarted during DietPi system modifications, there is currently no warning (on many places) in advance when it happen

#### Describe the solution you'd like:

- Option to exclude certain services from this restart ie. Docker service, because I would be happier to restart only container which is affected by change which I made, instead of whole docker service every time, this can hurt DB backed containers which are RW into their DBs, not talking about downtime taken for containers after start of the service

#### Describe alternatives you've considered:

- Have a selection screen before each attempt to restart services where user would select only services which can be restarted

#### Additional context

- ...

**Comment by Joulinar** [comment]
Services could be excluded using `dietpi-services`
