### ISSUE TITLE
DietPi-VPN killswitch blocks NFS

### ISSUE THREAD

**Issue by chumbazoid** [MichaIng/DietPi#5748]
**Required Information**
- DietPi version | `8.8`
- Distro version | `Bullseye`
- Kernel version | `Linux server2 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | `CanaKit 3.5A Raspberry Pi 4 Power Supply (USB-C)`

**Additional Information**
- Software title | `DietPi-VPN`
- Was the software title installed freshly or updated/migrated? | `Fresh`

**Steps to reproduce**
1. Create and confirm NFS share on DietPi server
2. Connect dietpi-vpn with .ovpn file from Windscribe VPN
3. Enable dietpi-vpn killswitch
4. [On client machine on local network] showmount -e 192.168.1.xxx [DietPi server address]

**Expected behaviour**
Client machine returns DietPi server's mountable exports and/or client can connect to DietPi NFS share

**Actual behaviour**
Client hangs, does not return mountable exports, cannot connect to DietPi NFS share

**Extra details**
Disabling killswitch + apply in DietPi-VPN does not restore NFS connectivity. DietPi server must be rebooted with killswitch off to restore NFS connectivity.

NFS works as expected with VPN on but killswitch off.

**Comment by Joulinar** [comment]
this is basically as exspected as the killswitch is blocking whole access (except SSH). You could have a look to following forum post describing a possible workaround https://dietpi.com/forum/t/dietpi-vpn-cannot-access-local-web-ui/6185/15?u=joulinar

Just add the NFS ports.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
