### ISSUE TITLE
DietPi and VestaCP or Sentora or Ispconfig

### ISSUE THREAD

**Issue by GeoWebDevCom** [MichaIng/DietPi#575]
Can you add support for vestaCP as well or ispconfig or sentora

**Comment by GeoWebDevCom** [comment]
Sentora Panel works great with dietpi (please have a look at it to optemize it for dietpi) i have on my profile the modified installer of sentora 

Only issue that i facing is postfix not working and can't move the hostdata to mnt/usb_1 (external hdd)

All this is done on a odroid xu4

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
