### ISSUE TITLE
k3s single node cluster failing with failed to find memory cgroup (v2)

### ISSUE THREAD

**Issue by Leonkoithara** [MichaIng/DietPi#5752]
#### Required Information
- DietPi version 
  ```
  G_DIETPI_VERSION_CORE=8
  G_DIETPI_VERSION_SUB=8
  G_DIETPI_VERSION_RC=1
  G_GITBRANCH='master'
  G_GITOWNER='MichaIng'
  ```
- Distro version
  bullseye 0
- Kernel version
  Linux DietPi 5.15.61-v8+ `#1579` SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux
- SBC model
  RPi 3 Model B+ (aarch64)

#### Additional Information (if applicable)
- K3S
- Was the software title installed freshly or updated/migrated?
   Yes
- Can this issue be replicated on a fresh installation of DietPi?
   Yes(Only docker is installed from dietpi-software)

#### Steps to reproduce
Install k3s from dietpi-software

#### Expected behaviour
A Single node Cluster should be up and running

#### Actual behaviour
Cluster crashes with the following error

```
<username>@<hostname>:~$ sudo systemctl status k3s.service
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; disabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/k3s.service.d
             └─<username>.conf
     Active: failed (Result: exit-code) since Sat 2022-09-17 16:48:07 BST; 2h 28min ago
       Docs: https://k3s.io
    Process: 4344 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 4346 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 4347 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 4349 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
   Main PID: 4349 (code=exited, status=1/FAILURE)
        CPU: 24.087s

Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=info msg="To join server node to cluster: k3s server -s https://<ip>:6443 -t ${SERVER_NODE_TOKEN}"
Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=info msg="Agent node token is available at /var/lib/rancher/k3s/server/agent-token"
Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=info msg="To join agent node to cluster: k3s agent -s https://<ip>:6443 -t ${AGENT_NODE_TOKEN}"
Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=info msg="Run: k3s kubectl"
Sep 17 16:48:07 <hostname> k3s[4349]: time="2022-09-17T16:48:07+01:00" level=fatal msg="failed to find memory cgroup (v2)"
Sep 17 16:48:07 <hostname> systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Sep 17 16:48:07 <hostname> systemd[1]: k3s.service: Failed with result exit-code.
Sep 17 16:48:07 <hostname> systemd[1]: Failed to start Lightweight Kubernetes.
Sep 17 16:48:07 <hostname> systemd[1]: k3s.service: Consumed 24.087s CPU time.


```

#### Extra details
Fix I found was appending `systemd.unified_cgroup_hierarchy=1` to `/boot/cmdline.txt` to enable cgroups v2

**Comment by MichaIng** [comment]
Many thanks for your report.

The unified cgroup hierarchy (aka cgroups v2) should be used by default. Also the error message mentions the memory cgroup explicitly, which is enable via `cgroup_enable=memory` in `/boot/cmdline.txt` on K3s installation, but effective only after reboot.

Did you do a reboot after installing K3s the first time?
If `cgroup_enable=memory` is present in `/boot/cmdline.txt` as expected, could you try to remove `systemd.unified_cgroup_hierarchy=1` again, reboot and see whether K3s continues to function?

It is however an important information that the memory cgroup seems to be strictly required now. In the past it enabled additional features but wasn't strictly required for K3s containers to run. In this case we need to prompt for a reboot after install, when the memory cgroups wasn't enabled before.

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
