### ISSUE TITLE
G_OBTAIN_CPU_TEMP from python ? 

### ISSUE THREAD

**Issue by jalsco** [MichaIng/DietPi#5756]
Hello,  hope someone can give some quick - howto - advice 

Just am trying to use :
`G_OBTAIN_CPU_TEMP`
`G_OBTAIN_CPU_USAGE`
from within a small python script.

Usually I use :  `subprocess.Popen`
I also tried using  `os.Popen`

Both of these I use successfully in other scripts - but python cannot find these 2 DietPi commands 🤷🏻‍♂️

Example: 
`now_temp = subprocess.run("G_OBTAIN_CPU_TEMP", shell=True)`
gives
`/bin/sh: 1: G_OBTAIN_CPU_TEMP: not found`

**Comment by MichaIng** [comment]
Those are no executables but shell functions. So you'd need to load `dietpi-globals` first:
```py
    now_cpu = subprocess.run(['bash -c ". /boot/dietpi/func/dietpi-globals; G_OBTAIN_CPU_USAGE"'],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             text=True,
                             shell=True)
```

**Comment by jalsco** [comment]
thank you so much !! 🙏🏻🙏🏻🙏🏻😁
