### ISSUE TITLE
The MOTD, like the cake, is a lie!

### ISSUE THREAD

**Issue by TimmyBCoding** [MichaIng/DietPi#5757]
#### Is your feature request related to a problem? Please describe:

- I was reading through [issue 4545](https://github.com/MichaIng/DietPi/issues/4545) and I noticed something that was being ignored and not wanting to interrupt the actual productive work going on there with my BS, i made a whole new issue for my BS. 

And what is that BS?

The MOTD isn't really a message of the day. I feel like I only see it change with a patch update {and Christmas, which was great}, but then I'm just staring at the same message till the next update. I'm just saying that even if it's from a daily cron job if you have chicken soup every day it's not soup de jour if you serve it six days a week. 

#### Describe the solution you'd like:

- Keep doing what you're doing because I love this distro and there's definitely more important things to do.
- Definitely more holiday banners.. 

#### Describe alternatives you've considered:

- Message of the Patch? Update of the week?  Pi Day banner?

#### Additional context

- Ok maybe calling a a lie was a bit [much.](https://knowyourmeme.com/memes/the-cake-is-a-lie)

**Comment by MichaIng** [comment]
No problem, aside of the semantics, using the MOTD more actively, especially since it can be used very flexible depending on hardware, installed software, distro version etc, as it is a script which creates a variable to be printed, no static text, is a good point 👍. We'll discuss this on team meeting tomorrow.

**Comment by MichaIng** [comment]
This reminds me to update it since now that Easter is now a week ago 🙂.

**Comment by Joulinar** [comment]
It's working fine on my system. 

On a running system, MOTD is updated once a day only.
