### ISSUE TITLE
Deactivate internal WiFi an activate external WiFi

### ISSUE THREAD

**Issue by mok-liee** [MichaIng/DietPi#576]
Hi,

i have an edimax ew-7811uac 5ghz wlan stick. I tried to deactivate the internal wifi. but i cant activate the external stick for using this for the hotspot feature.

is it possible to make a "choose device" point in the wifi menue?

another thing... if the hotspot feature is activated an configured, there is no option to deactivate wifi.

hoe u can help me again.

greetings mok

**Comment by Fourdee** [comment]
@mok-liee 

Hi Mok,

Currently, DietPi assumes the user would like to use the internal WiFi features of their RPi 3, essentially, its hard coded for that. So i'll need to look into this and create a feature which allows for specifying another device, if detected by system.

> another thing... if the hotspot feature is activated an configured, there is no option to deactivate wifi.

Thanks 👍, i'll take a look.

**Comment by Fourdee** [comment]
Option in dietpi.txt to disable RPi 3 onboard wifi using blacklist.

**Comment by Fourdee** [comment]
Onboard WiFi can now be disabled/enabled from `dietpi-config`.

NB:
- Requires a reboot to take effect

![image](https://cloud.githubusercontent.com/assets/7077026/20040093/0ce0d3dc-a449-11e6-964f-bedd3608ef9c.png)

**Comment by Fourdee** [comment]
Completed.
