### ISSUE TITLE
DietPi-Software | FreshRSS: Unable to install the software because the default repository branch has changed

### ISSUE THREAD

**Issue by bhedouin** [MichaIng/DietPi#5767]
#### Required Information

- DietPi version | `DietPi v8.9.2`
- Distro version | `Debian 11 bullseye`
- Kernel version | `Linux dietpi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | 5.1V / 3.0A DC
- SD card used | Kingston SSD NVMe

#### Additional Information (if applicable)

- Software title | FreshRSS
- The software has just been installed
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Steps to reproduce

1. Run the `dietpi-software` command and install FreshRSS

#### Actual behaviour

- In the middle of the installation the installation fails because the `master` branch of the GitHub repository has been removed and only the `edge` branch is available

#### Extra details

- I did manage to install FreshRSS by changing the command `mv /opt/FreshRSS-master FreshRSS` to `mv /opt/FreshRSS-edge FreshRSS`.

Thanks for your work on DietPi, I use it every day on my Raspberry Pi.

**Comment by MichaIng** [comment]
Proper fix merged. The simple fix to use the `edge` branch can be applied as live patch indeed. I'll do that tomorrow.
