### ISSUE TITLE
DietPi-Config | Add support for JustBoom soundcards

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#577]
High-end audiophile sound cards available from Pi Supply: https://www.pi-supply.com/brand/justboom/

**Comment by Fourdee** [comment]
> justboom-dac: DAC HAT, Amp HAT, DAC Zero and Amp Zero
> justboom-digi: Digi HAT and Digi Zero
> CARD=1 DEV=0

**Comment by shawaj** [comment]
Thanks :-)

**Comment by Fourdee** [comment]
Testing:
- 🈯️ Justboom-dac
- 🈯️ Justboom-digi | Tested with 96khz 32bit with DAC unit over optical

```
root@DietPi-JustBoom:~# cat /proc/asound/card*/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 96000 (96000/1)
period_size: 12000
buffer_size: 48000
```

**Comment by Fourdee** [comment]
@shawaj 
All done. Now everyone can wake their neighbors up lol 💃

**Comment by shawaj** [comment]
:-D
