### ISSUE TITLE
DiePi own distribution script - no bash

### ISSUE THREAD

**Issue by LOGIN-TB** [MichaIng/DietPi#5771]
After creating a custom diet distribution on a Hetzner Cloud (bas Debian 11 installation) server using the script

bash -c "$(curl -sSfL 'https://raw.githubusercontent.com/MichaIng/DietPi/master/.build/images/dietpi-installer')"

the bash is not starting automatically.

I installed dietpi last week on a couple of cloud instances without any issue. Today I had this issue.

After starting bash manually on the console everything is working fine

**Comment by Joulinar** [comment]
Hi Holger, you mean there is no output while executing the command? You are using root user, right? I just tested it on my R5S without issues. 🤔

**Comment by HolgerTB** [comment]
After login as root only # is prompted. after entering bash the shell is loaded and the configuration starts.

entering chsh -s /bin/bash fixed the problem

**Comment by Joulinar** [comment]
this is right after the install script finished and system rebooted??

**Comment by HolgerTB** [comment]
Yes. Correct. 

And when I start bash and finish installation and reboot there is no bash

**Comment by Joulinar** [comment]
how does it behave on user dietpi? Maybe this change could be the issue https://github.com/MichaIng/DietPi/commit/3e94f098657c6f343390bd5f7d803e2a93556923

**Comment by HolgerTB** [comment]
i will setup a new instance and post the outcome. stand by

**Comment by Joulinar** [comment]
but you should be able to login as user `dietpi` on the running system??

**Comment by HolgerTB** [comment]
I did the first login after installer script and reboot as dietpi. the prompt is 

[FAILED] Root login required                                                           
To finish DietPi first run setup, root permissions are required
Please login again as user "root" with password "dietpi", respectively the one you chose via "dietpi.txt".

**Comment by HolgerTB** [comment]
I finished installation and I can logon as dietpi. As root I don't have a bash

**Comment by Joulinar** [comment]
@MichaIng can you have a look to the latest changes you did on the installer?

**Comment by HolgerTB** [comment]
i tested it on Friday. It worked without any issues.

**Comment by Joulinar** [comment]
yes, the new installer has been released on weekend. And there is a change to fix/clear the shell 🙄 

```
usermod -d /root -s /bin/dash root
```

but it should be:

```
usermod -d /root -s /bin/bash root
```

This should fix it as well

**Comment by HolgerTB** [comment]
great.

**Comment by Joulinar** [comment]
did you tried running following? `usermod -d /root -s /bin/bash root`. After new login, it should be fixed.

**Comment by HolgerTB** [comment]
yes. This fixed it
