### ISSUE TITLE
Cannot add NFS Share on Raspi with dietpi-drive_manager

### ISSUE THREAD

**Issue by LOGIN-TB** [MichaIng/DietPi#5783]
Version: current DietPi Release on Raspi 4 / Raspi Zero W2

Issue:
started drive_manager / map nfs share
I entered IP address of NFS-Server (in this case QNAP NAS with NFS 4.3)
all available NFS Shares are showing up
I selected share /pi-backup
entered the mount point /mnt/pi-backup
directory is created
the system stuck - no further progress. I have to terminate with ctrl-C

Screen-Log:
[  OK  ] DietPi-Drive_Manager | APT install for: nfs-common
[  OK  ] DietPi-Drive_Manager | Added setting aSOFTWARE_INSTALL_STATE[110]=2 to end of file /boot/dietpi/.installed
[  OK  ] DietPi-Drive_Manager | rm /mnt/nfs_client/readme.txt
[  OK  ] DietPi-Drive_Manager | rmdir --ignore-fail-on-non-empty /mnt/nfs_client
[ INFO ] DietPi-Drive_Manager | Scanning for NFS exports by: 192.168.1.15
 NB: If the server cannot be reached correctly, this may take up to 90 seconds before it times out.
[  OK  ] DietPi-Drive_Manager | mkdir /mnt/pi-backup

Hint:
i have this issue with two pi's - Pi 4 connected with LAN / Zero W2 connected with WiFi
With a DietPi VM under proxmox I can mount the share!!!!

**Comment by Joulinar** [comment]
We had some reports about issues on QNAP NFS and kernel version 5.15 https://github.com/MichaIng/DietPi/issues/5358

It was needed to specify the NFS version explicitly on client side

**Comment by HolgerTB** [comment]
nfsvers=4 

did the job.

**Comment by Joulinar** [comment]
Ok going to close this one. Feel free to reopen if needed.
