### ISSUE TITLE
Where to put Kernel Parameters?

### ISSUE THREAD

**Issue by DrCWO** [MichaIng/DietPi#5785]
I like to add `btusb.enable_autosuspend=0` to the kernel boot cmd line but have no Idea where I find it on the Dietpi instance for my R2S.

Help would be appreciated :-)

**Comment by Joulinar** [comment]
I guess you need to look into `/boot/armbianEnv.txt`

**Comment by MichaIng** [comment]
The extraargs line to be precise.

**Comment by DrCWO** [comment]
Thank you found it.
I see the line: `extraargs=net.ifnames=0`.
This means there is already one argument present. 

Would you mind telling me what separator to use if I want to add `btusb.enable_autosuspend=0` ?
Comma, Colon, Space...???

**Comment by MichaIng** [comment]
Just append it with a space as separator.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
