### ISSUE TITLE
DietPi v8.9.2 specific raspberrypi-sys-mods breaks loading of some drivers

### ISSUE THREAD

**Issue by f-laurens** [MichaIng/DietPi#5789]
For some unknown reason, after updating from DietPi v8.8.1 to v8.9.2, some drivers do not load anymore on my Raspberry Pi
(no kernel error messages, the drivers just do not load).
I have kept same kernel version (5.15.32) so this is not a driver upgrade/rebuild issue.
My guess is that this might be related to the new DietPi specific version of `raspberrypi-sys-mods`...

What would be the way to reinstall the standard (_20220915_) version of `raspberrypi-sys-mods`, in order to validate this?

**Comment by MichaIng** [comment]
Which drivers do you mean in particular? We have a report that some LCD driver may not load correctly, leading to backlight sysfs entry (so backlight cannot be toggled).

Yes please test whether downgrading the package solves it again.

**Comment by f-laurens** [comment]
> Which drivers do you mean in particular? 

The driver that fails to load  in my case is this specific [NFC driver](https://github.com/pguyot/st25r391x).

> Yes please test whether downgrading the package solves it again.

What would be the procedure (I'm no dpkg/apt guru ;-) to downgrade `raspberrypi-sys-mods`?

**Comment by f-laurens** [comment]
I downgraded package `raspberrypi-sys-mods `to the standard (non DietPi) 20220915 version thru:
```
sudo apt-get remove raspberrypi-sys-mods
sudo apt-get autoremove
sudo apt-get install raspberrypi-sys-mods=20220915
```
and this indeed solves the problem for me: after rebooting, the NFC driver now loads correctly.

**Comment by MichaIng** [comment]
I think I found it, please test:
```sh
cd /tmp
curl -O https://dietpi.com/downloads/binaries/raspberrypi-sys-mods.deb
dpkg -i raspberrypi-sys-mods.deb
rm raspberrypi-sys-mods.deb
```

**Comment by f-laurens** [comment]
> I think I found it, please test:

This new version _2:20220915-dietpi2_ indeed fixes the problem.
Thank!

**Comment by MichaIng** [comment]
Many thanks for the feedback 👍.
