### ISSUE TITLE
PiHole White/Blacklist Menu Items Missing from GUI

### ISSUE THREAD

**Issue by leetol** [MichaIng/DietPi#5793]
#### Required Information
- DietPi version | v8.9.2
- Distro version | bullseye 0
- Kernel version | Linux DietPi 5.15.61-v7+
- SBC model | RPi 2 Model B (armv7l)
- SD card used | SanDisk 

#### Additional Information (if applicable)
- Software title | PiHole
- Was the software title installed freshly or updated/migrated?  FRESH
- Can this issue be replicated on a fresh installation of DietPi?  With un/re-installs of PiHole

#### Steps to reproduce
1. Install PiHole
2. Go to Admin Dashboard

#### Expected behaviour
Should be able to see ability to edit white/blacklists from Dashboard.

#### Actual behaviour
White/blacklists are missing from GUI.  Can only be edited from command line.

#### Extra details
I can add/remove items from the black/whitelists from the query log.  However, I can't see what's currently on the whitelist or edit entries from the GUI.  I have to use the CLI.

![image](https://user-images.githubusercontent.com/4616679/194739270-92f78d8a-c9d7-4a91-bc80-b2f21c1ce3b8.png)

**Comment by Joulinar** [comment]
PiHole guy's change the layout of the UI. Managing White and Blacklist is now part of Domain management.

**Comment by MichaIng** [comment]
I'll mark this as closed. Feel free to reopen if required.
