### ISSUE TITLE
Update DietPi from v8.8.1 to v8.9.2 fails

### ISSUE THREAD

**Issue by joshimosh** [MichaIng/DietPi#5794]
#### Details:
- Date           | Sun Oct  9 09:06:01 CEST 2022
- DietPi version | v8.8.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi Zero W (armv6l) (ID=1)
- Kernel version | `Linux RPiHB 5.15.61+ #1579 Fri Aug 26 11:08:59 BST 2022 armv6l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `cp -a DietPi-master/rootfs/. /`
- Exit code      | 1
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
cp: cannot stat '/./etc/sysctl.d/dietpi.conf': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-cloudshell.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-firstboot.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-fs_partition_resize.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-kill_ssh.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-postboot.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-preboot.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-vpn.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/dietpi-wifi-monitor.service': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/ifup@.service.d': Structure needs cleaning
cp: cannot stat '/./etc/systemd/system/ifupdown-pre.service.d': Structure needs cleaning

**Comment by Joulinar** [comment]
"Structure needs cleaning" usually indicates a filesystem errors. Please try to clean it on reboot:

```sh
> /forcefsck
reboot
# after reboot check logs
journalctl -t systemd-fsck
```

**Comment by joshimosh** [comment]
Thank you for the advice. Unfortunately the cleanup left a system that refused to boot.
I will install a backup and try again.

**Comment by nicgravel** [comment]
I have the same problem. Error on update and system dead on reboot.
![image](https://user-images.githubusercontent.com/8532140/195175316-9387bb1a-a7a4-4cad-a557-086165746fe3.png)

**Comment by Joulinar** [comment]
Looks your SD card has some file system corruption.

**Comment by MichaIng** [comment]
Is it an RPi or other device?

**Comment by nicgravel** [comment]
rpi4

**Comment by MichaIng** [comment]
So no fsck via initramfs possible. Do you have another Linux system where you can mount this SD card (or USB drive) to run fsck on? Because systemd itself is broken so that it cannot even boot util a stage where it might be able to repair itself.

**Comment by nicgravel** [comment]
i will try to repair it on another linux system tonight...

**Comment by joshimosh** [comment]
In my case, replacing from a backup (bootable image created with rpi-clone, it's very convenient and never gave me any problems) did it.
Update to v8.9.2 worked flawlessly.

**Comment by MichaIng** [comment]
@nicgravel 
Were you able to repair the drive?

**Comment by nicgravel** [comment]
unfortunately no. Had to reinstall everything but now I have a USB key to save a full backup of the system...just in case...
I tested it and everything works well after a restore.

**Comment by MichaIng** [comment]
Makes sense to keep full backups or at least backups of those data you need to restore on a newly setup system, especially when using an SD card as system drive.

Okay, I'll mark this as closed then.
