### ISSUE TITLE
Pi 3/4: How to disable Audio on HDMI and audio on Headphone but keep awareness for USB Audio?

### ISSUE THREAD

**Issue by DrCWO** [MichaIng/DietPi#5831]
#### Is your feature request related to a problem? Please describe:

- After istalling ALSA I see ALSA Card 0 and Card 1 if I enter aplay -l by default.

#### Describe the solution you'd like:

- I want to disable both but keep ALSA active to recognize USB audio interfaces.

#### Describe alternatives you've considered:

- none

#### Additional context

- ...

**Comment by MichaIng** [comment]
It should be possible to select `usb-dac` near the end of the list, even if there is no USB DAC connected currently. Onboard audio will then be disabled.

**Comment by Joulinar** [comment]
@DrCWO does this answer your question or is there still something open?

**Comment by DrCWO** [comment]
Anything is OK now thank you :-)

**Comment by Joulinar** [comment]
ok I'm going to close the issue, Feel free to reopen if needed.
