### ISSUE TITLE
Dietpi-Upgrade Issue

### ISSUE THREAD

**Issue by skwiz0d** [MichaIng/DietPi#5835]
I recently did an upgrade on an old VM from Stretch to Bullseye and the upgrade itself worked without issue.  The problem though is dietpi-update still reports the old stretch 7.9.4 version and says there are no updates while /etc/os-release shows Bullseye correctly.   Any Ideas?

TY

**Comment by Joulinar** [comment]
Can you share the entire error message pls. 

And did you already switched the DietPi branch back to `master`?

```
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=master' /boot/dietpi.txt
```

**Comment by skwiz0d** [comment]
there was no error message, but you were right.  I didn't switch it back to master.  I'm good to go now.  Thank you!
