### ISSUE TITLE
Diet Scheduled Reboot.

### ISSUE THREAD

**Issue by jdaien4783** [MichaIng/DietPi#5895]
What is the easiest / simplest way to tell the DietPi on raspberry pi to reboot daily or weekly?

**Comment by Joulinar** [comment]
Basically this is not specific to DietPi. You can schedule a reboot as on every other Linux system. Easiest might be to create a `crontab` entry.

**Comment by MichaIng** [comment]
Before you try the obvious way:
```sh
echo -e '#!/bin/dash\nreboot' > /etc/cron.daily/zzz-reboot
chmod +x /etc/cron.daily/zzz-reboot
```
The problem with this is that, AFAIK, those jobs can run concurrently, so that the reboot hard kills other jobs, e.g. backups and such, which should definitely not be aborted. So it's better to create a dedicated `crontab` entry, either via command:
```sh
sudo crontab
```
or more transparently
```sh
echo '59 3 * * * root reboot' > /etc/cron.d/daily-reboot
```
to reboot every day at 03:59 or
```sh
echo '59 3 * * 7 root reboot' > /etc/cron.d/weekly-reboot
```
to reboot every Sunday at 03:59.

**Comment by jdaien4783** [comment]
Still a little confused? Is this suppose to be a one step one command setup? If I just copy and paste:

"echo '59 3 * * * root reboot' > /etc/cron.d/daily-reboot"

I get the following error:

<img width="562" alt="Screen Shot 2022-11-20 at 9 13 09 AM" src="https://user-images.githubusercontent.com/39698512/202907067-1ef936c4-44fb-44c1-8540-073bbfabf630.png">

I have tried it with sudo also. I get the same error.

**Comment by MichaIng** [comment]
You do not need root permissions for executing `echo`, but for writing to the file, so `sudo echo something > /path/to/file` does generally not work (the `>` redirect is shell syntax and not part of the `sudo echo` command). Instead use:
```sh
echo '59 3 * * * root reboot' | sudo tee /etc/cron.d/daily-reboot
```

**Comment by MichaIng** [comment]
Did this work for you?

**Comment by StephanStS** [comment]
Could it also be a solution, that on reboot you execute `shutdown -r --no-wall +1440` (daily) resp. `shutdown -r --no-wall +10080` (weekly)? The idea is to trigger the reboot directly at system startup.

**Comment by MichaIng** [comment]
Requires `dbus` and probably `systemd-logind`, and not sure what the benefit is?

**Comment by MichaIng** [comment]
Marking as closed, as initial question has been answered.
