### ISSUE TITLE
Improvement: Keyboard layout vs. password change during initial setup

### ISSUE THREAD

**Issue by LeFish1** [MichaIng/DietPi#5925]
#### Is your feature request related to a problem? Please describe:
- For a first time user with a different keyboard layout other than US/GB it can be "dangerous" to be suggested to change the global software and user passwords before going into the initial setup menu and being pointed to the keyboard layout being US/GB.
- I just had to install a second time as I set global software and user passwords as suggested by the installer, before switching to my native keyboard layout in the initial setup menu. Not a big deal, but unnecessary...

#### Describe the solution you'd like:
- (1) I would suggest to just inform the user of the recommended option to change the passwords before switching to the initials setup menu.
- OR better
- (2) It would be even better to be forced into keyboard layout setup before initial change of password just to make sure the charset is as expected.

#### Describe alternatives you've considered:
See two options above. I prefer option (2).

#### Additional context

- The context is the initial setup menu. In my case on a x86_64 PC-installation.

Thanks for this great OS!

**Comment by MichaIng** [comment]
Agreed. At least when login is on ttyX (a local console), selecting the keyboard layout should be a mandatory first step.

**Comment by MichaIng** [comment]
Another case: #6276
Giving this priority now for v8.16.

**Comment by MichaIng** [comment]
Added for DietPi v8.16 with: https://github.com/MichaIng/DietPi/commit/0423238
