### ISSUE TITLE
dietpi-nextcloud-database-backup.sql failed during fresh install

### ISSUE THREAD

**Issue by droogi** [MichaIng/DietPi#5955]
#### Details:
- Date           | Sun Dec  4 21:55:21 CET 2022
- Bug report     | cbbe0cac-50ba-4b41-bff1-74d1e5a25167
- DietPi version | v8.11.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `mysql -e update nextcloud.oc_storages set id='local::/mnt/dietpi_userdata/nextcloud_data/' where id rlike 'local::';`
- Exit code      | 1
- Software title | DietPi-Software
#### Steps to reproduce:
nextcloud failed to start
https://dietpi.com/forum/t/nextcloud-general-error-2006-mysql-server-has-gone-away/15065/8

=> 
fresh 64bit image of dietpi
cp /mnt/dietpi_userdata/nextcloud_data to new system
cp 2022-11-20_01\:34\:32.sql /mnt/dietpi_userdata/nextcloud_data/dietpi-nextcloud-database-backup.sql

dietpi-software 
nextcloud
install
#### Expected behaviour:
installation of nextcloud and import use backup.sql

#### Actual behaviour:
during installing 114 with dietpi-software:

systemctl start mariadb
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
[FAILED] Creating MariaDB database nextcloud for user  | Exited with error
ERROR 1062 (23000) at line 533: Duplicate entry '22139' for key 'PRIMARY'
grep: /var/www/nextcloud/config/config.php: No such file or directory
[FAILED] DietPi-Software | mysql -e update nextcloud.oc_storages set id='local::/mnt/dietpi_userdata/nextcloud_data/' where id rlike 'local::';

#### Extra details:
- ...](https://dietpi.com/forum/t/nextcloud-calender-contact-backup-script/5911/8)
#### Additional logs:
```
ERROR 1146 (42S02) at line 1: Table 'nextcloud.oc_storages' doesn't exist
```

I may try with an older backup?

**Comment by Joulinar** [comment]
Was this a fresh installation or did NC already exist before?

BTW: using `cp` command, without `-p` option will most probably lead to losing all file system permissions.

**Comment by droogi** [comment]
thanks for your fast reply, so not a script error, but my mistake actually, 

i just used `mysqladmin drop nextcloud`, than

copied from old installation to new installation (cp -rp)
/mnt/dietpi_userdata/nextcloud_data, 
var/www/nextcloud and 
dietpi-nextcloud-database-backup.sql

installation (and reinstallation) runs fine now, but
when accessing http://ip/nextcloud, i get same errormessage as on old installation:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.

I will try to find sdcard images with more older backups...

**Comment by droogi** [comment]
i installed phpmyadmin and see nextcloud database and e.g. all users
i tried to execute `sudo -u www-data php occ files:cleanup`
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_admin'@'localhost' (using password: YES) in /var/www/nextcloud/lib/private/DB/Connection.php:139

**Comment by Joulinar** [comment]
Looks like password stored on configuration file did not match the database password. Theoretically you could try to reset manually.

**Comment by MichaIng** [comment]
Hmm, when `dietpi-nextcloud-database-backup.sql` is restored, the new database is pre-created with the user and password stored in `config.php`, so this should generally work.

Can you try to do this manually:
```sh
dbuser=$(grep -m1 "^[[:blank:]]*'dbuser'" /var/www/nextcloud/config/config.php | mawk -F\' '{print $4}')
dbpass=$(grep -m1 "^[[:blank:]]*'dbpassword'" /var/www/nextcloud/config/config.php | mawk -F\' '{print $4}')
echo "User: $dbuser, Password: $dbpass" # To verify, both was correctly obtained from the file.
mysql -e "grant all privileges on nextcloud.* to $dbuser@localhost identified by '$dbpass';"
```

**Comment by MichaIng** [comment]
Okay good so far. I'll check if we do set permissions/ownership correctly when restoring the backup, else add that.

Nextcloud install version must be at least as new as database version. So actually restoring an older database should work, but not a newer database with older Nextcloud install dir. At best, of course both should match.

For completeness, this script should be safest: https://github.com/MichaIng/DietPi/blob/master/.meta/dietpi-cloud-migration
Same is done when you uninstall Nextcloud, with backups (database and install dir) stored in Nextcloud data dir from where it is restored automatically when copied into a new system. For copying, always use `cp -a` so permissions etc are kept.

If the old SD card does not boot anymore, it might be an issue with the card, but could be also something different. Am any logs from screen our serial console would help to diagnose.

**Comment by MichaIng** [comment]
We do `chown` the Nextcloud install and data dirs in every case on install and reinstall with fresh instance or with backup. So it really was the database backup with missing `/var/www/nextcloud` backup, which we currently do not support. It would be theoretically possible, but high effort and many steps to retrieve all required info from the database backup and generate a matching `config.php` from it.

I'll mark this as closed. Feel free to reopen if required.
