### ISSUE TITLE
Dietpi cant install times out or fails to resolve apt and pip

### ISSUE THREAD

**Issue by eyduh** [MichaIng/DietPi#5956]
#### Required Information
```
root@DietPi:/tmp/DietPi-Software# cat /boot/dietpi/.version
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=11
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
root@DietPi:/tmp/DietPi-Software# echo $G_DISTRO_NAME $G_RASPBIAN
bullseye
root@DietPi:/tmp/DietPi-Software# ===
bash: ===: command not found
root@DietPi:/tmp/DietPi-Software# uname -a
Linux DietPi 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
root@DietPi:/tmp/DietPi-Software# echo $G_HW_MODEL_NAME
Native PC (x86_64)
```
#### Additional Information (if applicable)
- Software title | dietpi-software, apt, python3 get-pip.py
- Was the software title installed freshly or updated/migrated? trying to install first round of stuff
- Can this issue be replicated on a fresh installation of DietPi? see above

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. try to install
2. fail

#### Expected behaviour

- installs stuff

#### Actual behaviour

-isnt installing stuff

#### Extra details

- I'm doing all of this remotely through zerotier. I did have some wireguard client installed earlier but uninstaleld and installed zerotier

**Comment by eyduh** [comment]
```
 ip route
default via 192.168.2.254 dev wlan0 
172.26.0.0/16 dev zt5u4z3dof proto kernel scope link src 172.26.32.47 
192.168.2.0/24 dev wlan0 proto kernel scope link src 192.168.2.8 
```

**Comment by Joulinar** [comment]
Please can you share the exact error message for the failed apt package installation.
