### ISSUE TITLE
Odroid C2 Does not Detect/Power USB devices 

### ISSUE THREAD

**Issue by esage85** [MichaIng/DietPi#5963]
On the Odroid C2 Dietpi 8.11.2 I was not able to detect or power on any usb devices until I changed:

extraargs=net.ifnames=0 usbcore.autosuspend=-1 in /boot/dietpiEnv.txt

based on a issue thread in the armbian community:
https://forum.armbian.com/topic/20994-usb-devices-not-recognized-on-odroid-c2/

Thanks

**Comment by MichaIng** [comment]
This is still an issue with the latest kernel? My goodness... I'll implement the workaround.

**Comment by MichaIng** [comment]
Done with: https://github.com/MichaIng/DietPi/commit/5484283
