### ISSUE TITLE
Image for RaspberryPi's (all models) seems to be broken

### ISSUE THREAD

**Issue by Jurlind** [MichaIng/DietPi#597]
Hi,

I have tried to mount the iso or to open it with winrar, and I get the same result, namely that the image is broken. Any suggestions how to deal with this problem on a Windows platform? Actually, I tried win32disk however it modifies the size of the sd card, which makes the installation impossible, as there is no enough space on the disk anymore.

Cheers.

**Comment by Fourdee** [comment]
@Jurlind 

Try:
- Downloading the image again: http://dietpi.com/downloads/images/DietPi_RPi-armv6-(Jessie).7z
- Extract the compressed image file with 7zip (http://www.7-zip.org/download.html)
- Open win32diskimager
  - Select the extracted `.img` file
  - Click `write`

DietPi automatically resizes the filesystem during 1st run. Allowing full use of your SD card capacity.

**Comment by Jurlind** [comment]
Hi Fourdee,

thanks for your quick response. It seems that the installation is still failing, with error code 100. I am guessing that it is due to the size of the sd card, 1GB. I will try with a larger sd card, and will let you know, if this solves the problems I had. However, it definetly goes further in the installation by following your suggestion. Note that using 7zip, did not solve the problem of mounting the iso in Windows.

Cheers.

**Comment by Fourdee** [comment]
@Jurlind 

>  due to the size of the sd card, 1GB.

Possibly, although 1GB should be fine for a default/minimal installation of DietPi RPi image.

If the error 100 occurs again, please can you take a screenshot / image / note of the onscreen information?

**Comment by Fourdee** [comment]
No response, will mark as resolved.

@Jurlind 
Please reopen if required.
