### ISSUE TITLE
RPi 4 Model B: vcgencmd returns VCHI initialization failed

### ISSUE THREAD

**Issue by pulpe** [MichaIng/DietPi#5970]
#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=12
G_DIETPI_VERSION_RC=0
G_GITBRANCH='beta'
G_GITOWNER='MichaIng'`
- Distro version | `bullseye 0`
- Kernel version | `Linux DietPi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | `Argon USB-C 5,25V⎓3,5A`
- SD card used | `SanDisk Ultra 16GB`

#### Steps to reproduce

1. use command `vcgencmd` with or without parameters, doesn't matter

#### Expected behaviour
- should return usage information
#### Actual behaviour
- returns `VCHI initialization failed`
#### Extra details
- add user to group `video` to solve it

**Comment by MichaIng** [comment]
I think it is fine that this command requires root/sudo, and for login users, the option to add the user to `video` group remains an alternative. It shows sensitive information and can be also used to change some things, like toggling video output.

The error message however could be better. But that's outside of our control.
