### ISSUE TITLE
Home Assistant will need python 3.10

### ISSUE THREAD

**Issue by lukaszsobala** [MichaIng/DietPi#5979]
This is a quick issue. After installing home assistant using dietpi-software (dietpi ~~8.12~~ 8.11, everything went well) there is a warning message visible - see the screenshot. 

![Screenshot_20221215-090550174 (1)](https://user-images.githubusercontent.com/61153692/207806580-f3aae04f-f1e8-4751-8550-fdb6df4fe7e3.png)

It might be necessary to change the pyenv python version soon. The currently installed version is 3.9.

**Comment by Joulinar** [comment]
Wait for the upcoming DietPi release or apply to our current Beta. Once switched to DietPi v8.12, HA needs to be reinstalled and your warning message will be gone. https://github.com/MichaIng/DietPi/commit/09dd869765d40190cae89fd407703e386b38ba94

**Comment by lukaszsobala** [comment]
I'm sorry, you are right. This was on 8.11. Thank you!
