### ISSUE TITLE
Image for NanoPi R6S contains dev branch in dietpi.txt

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi#5981]
#### Required Information
- NanoPi R6S

#### Additional Information (if applicable)
Contents of /boot/dietpi.txt contains `DEV_GITBRANCH=dev` (should be `DEV_GITBRANCH=master`).

Need to be fixed with Release of DietPi v8.12

**Comment by Joulinar** [comment]
yeah a limitation as master branch did not support R6S actually 🤣

**Comment by MichaIng** [comment]
Exactly, needs to be done for first images of newly added SBCs until the DietPi release.
