### ISSUE TITLE
Deactivate Rpi3 wifi if using same network as eth0

### ISSUE THREAD

**Issue by trajano** [MichaIng/DietPi#609]
Can we make it such that if wlan0 gateway == eth0 gateway that we just shut off wlan0? Maybe leverage what has been done on #576

**Comment by Fourdee** [comment]
@trajano 

Yep, good idea, in theory this could work 👍 

Possible issues are:
- for this to be automatic, we'd have to create a background process/script that monitors the connection
- end user may not expect WiFi to be disabled (eg: unplugging eth would result in no connection)

**Comment by Fourdee** [comment]
Outdated, marking as closed, please reopen if required.
