### ISSUE TITLE
DietPi-Software | Mosh

### ISSUE THREAD

**Issue by hanscees** [MichaIng/DietPi#6096]
#### Is your feature request related to a problem? Please describe:
no
- ...

#### Describe the solution you'd like:
inclusion of the mosh shell which makes remote shell 1000x better 
https://mosh.org/
- ...

#### Describe alternatives you've considered:
mosh improves on ssh as remote shell, but takes over the connection via udp 
- ...

#### Additional context
see https://mosh.org/ 
its very beautiful with clients on for instance Ipad called blink 
https://blink.sh/

- ...

**Comment by MichaIng** [comment]
Thanks for your request.

Is this wrapped into a regular SSH session (detaching like GNU Screen does) or some own server-client model or how does it work?
