### ISSUE TITLE
Upgrate dist from Wheezy to Jessie

### ISSUE THREAD

**Issue by andrii-riabchun** [MichaIng/DietPi#61]
Hello, your work is amazing!
I have one question. Is it possible to upgrade with safety dist from Wheezy to Jessie on clear installation, after first run?

**Comment by Fourdee** [comment]
Hi Andrew,

Thanks for the feedback.

Unfortunately, DietPi (for RPi) does not currently support Debian Jessie at the moment. Doing a dist-upgrade will break most of the DietPi scripts and programs. 

As there is already a ticket for this request, and discussion, i have closed this one.
Please see/discuss here https://github.com/Fourdee/DietPi/issues/39

Kind Regards,
Dan
