### ISSUE TITLE
Installing mate

### ISSUE THREAD

**Issue by MCosta2016** [MichaIng/DietPi#610]
installing mate or lxde i get this error, that in the vm machine doesn't appear.
I can resolve it ?

Many thanks, Marco

![dietpi](https://cloud.githubusercontent.com/assets/20165457/20345896/82171816-abf9-11e6-8a2b-4d52afeb2a4c.jpg)

**Comment by Fourdee** [comment]
@MCosta2016 

Unable to replicate here, so lets try changing the apt mirror:
- run `dietpi-config`
- select `Network Options: NAS/Misc`
- select `Apt Mirror`
- select `ftp://ftp.fu-berlin.de/linux`
- exit dietpi-config

Lets clean, update the apt cache and repair any error-ed package installs:

```
apt-get clean
apt-get update
apt-get install -f
```

Now please try to install MATE via `dietpi-software` and let us know outcome.

**Comment by MCosta2016** [comment]
ok, good, but ...
![dietpi2](https://cloud.githubusercontent.com/assets/20165457/20347929/8fdc88be-ac03-11e6-8137-eafb33c85411.jpg)
![dietpi3](https://cloud.githubusercontent.com/assets/20165457/20347935/93ccec02-ac03-11e6-92e3-abfba8cb0d92.jpg)

**Comment by MCosta2016** [comment]
i think that is another problem ... sigh!

**Comment by MCosta2016** [comment]
infact i try to ping 8.8.8..8 and it is reacheable.... i don' t understand why the virtual machine go on without problem.... sigh!

**Comment by Fourdee** [comment]
@MCosta2016 

> infact i try to ping 8.8.8..8 and it is reacheable.... i don' t understand why the virtual machine go on without problem.... sigh!

Lets take a look at your network settings, please paste contents of the following (or screenshot). Hide any WiFi keys before hand:

```
cat /etc/network/interfaces
```

**Comment by Fourdee** [comment]
No response, will mark as closed.

@MCosta2016 
Please reopen if required.
