### ISSUE TITLE
Koel is not updated to the latest version

### ISSUE THREAD

**Issue by TheCheshireMan** [MichaIng/DietPi#6104]
#### Required Information
- DietPi version | `v8.13.2`
- Distro version | `bullseye`
- Kernel version | `Linux whitespace 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`
- SBC model | `Native PC (x86_64)` 
- Power supply used | ` PC power brick` 
- SD card used | ` Internal 500GB Hard Disk` 

#### Additional Information (if applicable)
- Software title | ` Koel` 
- Was the software title installed freshly or updated/migrated? | ` Fresh Install` 

#### Steps to reproduce

1. Attempt to install Koel through ` dietpi-software` 
2. Installation produces the following warning:
```
[FAILED] DietPi-Software | Automatic latest Koel download URL detection failed.
[FAILED] DietPi-Software | "https://github.com/koel/koel/releases/download/v5.1.14/koel-v5.1.14.tar.gz" will be used as fallback, but a newer version might be available.
[FAILED] DietPi-Software | Please report this at: https://github.com/MichaIng/DietPi/issues
```
#### Expected behaviour

- Koel is latest version (6.11)

#### Actual behaviour

- Koel is version 5.1 and cannot be upgraded via the docs' instructions (reinstalling through `dietpi-software`)

**Comment by Joulinar** [comment]
Koel v6 requires PHP 8.0 or higher, which is not available on Debian Bullseye ootb. Therefore, we are failing back to v5.1.14. Anyway, the error message is misleading as it's an excepted behaviour. I will go to change this.
