### ISSUE TITLE
DietPi-Software | InfluxDB: APT key has been revoked

### ISSUE THREAD

**Issue by muibusan** [MichaIng/DietPi#6112]
Hi!

I tried to install InfluxDB on DietPi 8.13.2 using dietpi-software, but it didn't succeed.

I sent a bug report, reference code: f7bdab83-8958-443f-94e1-7d5dab2dbb80.

The shell says:
```
[ INFO ] DietPi-Software | APT update, please wait...
Get:1 https://repos.influxdata.com/debian bullseye InRelease [7022 B]
Hit:2 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 https://mirror.de.leaseweb.net/debian bullseye InRelease
Hit:4 https://archive.raspberrypi.org/debian bullseye InRelease
Hit:5 https://mirror.de.leaseweb.net/debian bullseye-updates InRelease
Hit:6 https://mirror.de.leaseweb.net/debian bullseye-backports InRelease
Err:1 https://repos.influxdata.com/debian bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
Reading package lists...
W: GPG error: https://repos.influxdata.com/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/debian bullseye InRelease' is not signed.
```

**Comment by Joulinar** [comment]
We are already aware on this as the repository PGP key has been changed this week. We will provide a fix on next release. If you don’t like to wait until that time, you would need to go with manually fix and download the new key.

**Comment by MichaIng** [comment]
Yes, they rotated the key and changed the URL for the valid key, for whatever reason, breaking everyones scripts and CI... https://github.com/influxdata/influxdb/pull/24061

Run this to fix it:
```sh
sed -i 's/influxdb.key/influxdata-archive_compat.key' /boot/dietpi/dietpi-software
```
Fixed already with next DietPi update.

**Comment by MichaIng** [comment]
Reopened. It's better to have it here on GitHub, pinned and with the solution.

**Comment by sibofax** [comment]
Whoops - apologies!

**Comment by MichaIng** [comment]
Marking as closed now. But will stay pinned.
