### ISSUE TITLE
DietPi-Software | Can't install (114)Nextcloud is not compatible with PHP>=8.2. You are currently running 8.2.1

### ISSUE THREAD

**Issue by Alyciazsa** [MichaIng/DietPi#6121]
#### Required Information
- DietPi version | `8.13.2`
- Distro version | `bookworm`
- Kernel version | `Linux DietPi 6.0.12-flippy-79+ #41 SMP Thu Dec 8 23:41:34 CST 2022 aarch64 GNU/Linux`
- SBC model | `Generic Amlogic S905 (aarch64)`
- Power supply used | (5V 1A RAVpower)
- SD card used | (SanDisk ultra 32G)

#### Additional Information (if applicable)
- Nextcloud
- installed freshly
- this issue can be replicated on a fresh installation of DietPi

- Bug report ID | `30b21326-2f81-43eb-97a7-a4b6aaa8408d`

#### Steps to reproduce

1. use DietPi-Software
2. Install 114 Nextcloud

#### Expected behaviour

- Installed succesfully

#### Actual behaviour

- This version of Nextcloud is not compatible with PHP>=8.2. You are currently running 8.2.1

#### Extra details

- 
![image](https://user-images.githubusercontent.com/97645837/215967118-f06bdea2-dcd2-44c8-81a0-014262650069.png)

**Comment by Joulinar** [comment]
This is known for Debian Testing branch Bookworm. Pls switch to DietPi Dev branch and try again.

`G_DEV_BRANCH dev`
