### ISSUE TITLE
unable to install influxes

### ISSUE THREAD

**Issue by sibofax** [MichaIng/DietPi#6123]
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
- G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=13
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'
G_LIVE_PATCH_STATUS[1]='not applicable'- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`

- Kernel version | `uname -a`
`Linux dpi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux`

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)

RPI2

- Power supply used | (EG: 5V 1A RAVpower)

5V

- SD card used | (EG: SanDisk ultra)

HDD

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)

influxDB

- Was the software title installed freshly or updated/migrated?

freshly

- Can this issue be replicated on a fresh installation of DietPi?

Yes

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...use diet-software to install influxDB
2. ...

#### Expected behaviour

- ...influxDB installation

#### Actual behaviour

- ...fails with unsigned repository - see below

#### Extra details

- ...Reading package lists...
W: GPG error: https://repos.influxdata.com/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D8FF8E1F7DF8B07E
E: The repository 'https://repos.influxdata.com/debian bullseye InRelease' is not signed.
```

**Comment by MichaIng** [comment]
Please check existing, especially pinned issues, before opening a new one 😉: https://github.com/MichaIng/DietPi/issues/6112#issuecomment-1407391074
