### ISSUE TITLE
DietPi | New website

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#616]
As title

**Comment by Fourdee** [comment]
Preview:
![image](https://cloud.githubusercontent.com/assets/7077026/20632017/3cedfbca-b332-11e6-9b13-10f731f136f4.png)
![image](https://cloud.githubusercontent.com/assets/7077026/20632028/59db5282-b332-11e6-8519-a0c01a1400ec.png)

**Comment by bhaveshgohel** [comment]
Awesome @Fourdee :+1: 
Can we have the Link for Preview? :smiley:

**Comment by WolfganP** [comment]
Nice design. Radioactive background :-)

**Comment by Fourdee** [comment]
@bhaveshgohel 

Hoping to get it finished today, will post when its up :)

**Comment by Fourdee** [comment]
@bhaveshgohel @WolfganP 
Nearly done, you can preview it here: http://dietpi.com/dietpi.com_v2/

Welcome any feedback and testing if you guys have any :)

**Comment by WolfganP** [comment]
Nice one. I notice a minor misspelling at the top buttons and text below: "Comminuty"

**Comment by Fourdee** [comment]
Ok, new site is live (ctrl+f5) http://dietpi.com

**Comment by Fourdee** [comment]
- 🈯️  Update dietpi desktop icons with new logo

**Comment by k-plan** [comment]
@Fourdee 

fresh and  colourful looking new website.  👍 

... and a fitting new forum style! 😃 

Great job.

> Update dietpi icons with new logo

Thinking, you have leave one in old style here: https://github.com/Fourdee/DietPi#dietpi

**Comment by Fourdee** [comment]
@k-plan 

> Thinking, you have leave one in old style here: https://github.com/Fourdee/DietPi#dietpi

Thanking you 👍. The one that got away 😄 lol

**Comment by bhaveshgohel** [comment]
@Fourdee Awesome!

Just one suggestion to decrease the load time of site:
### Compress all Images using [mozjpeg](https://imageoptim.com/mozjpeg ) :
Image  - 311KB [Original]
<img width="320" alt="pyvoeo8lpruaaaaasuvork5cyii" src="https://cloud.githubusercontent.com/assets/5253753/20857111/67e0c6c0-b948-11e6-87e0-f254a0cd5e2c.png">

Image - 35.8KB! [compressed]
<img width="320" alt="pyvoeo8lpruaaaaasuvork5cyii" src="https://cloud.githubusercontent.com/assets/5253753/20857116/884fe684-b948-11e6-9cb6-7f49acb1a29d.jpg">

**Comment by Fourdee** [comment]
@bhaveshgohel 

Good spot and thanks for link 👍. I'll reopen and take another pass on whole site.

**Comment by Fourdee** [comment]
@bhaveshgohel 
Down from 3.5MB: http://tools.pingdom.com/fpt/bXGWGd/http://webcache.googleusercontent.com/search?q=cache:oFg0pV5BXHYJ:dietpi.com/+&cd=1&hl=en&ct=clnk&gl=uk

To 1.1MB: https://tools.pingdom.com/#!/cAAHDS/dietpi.com

Thanks @bhaveshgohel, awesome 👍
