### ISSUE TITLE
Bookworm | Non-free firmware moved into new APT non-free-firmware component

### ISSUE THREAD

**Issue by dragonflylee** [MichaIng/DietPi#6163]
### Creating a bug report/issue
package `firmware-iwlwifi` moved to `non-free-firmware` in bookworm

#### Required Information
- DietPi version | `v8.14.2`
- Distro version | `bookworm`
- Kernel version | `Linux morefine 6.1.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29) x86_64 GNU/Linux`
- SBC model | `Native PC (x86_64)`

#### Steps to reproduce
add `non-free-firmware` to `/etc/apt/sources.list`

**Comment by MichaIng** [comment]
Recognised and done already 🙂. With next DietPi version, Bookworm systems will be patched accordingly: https://github.com/MichaIng/DietPi/commit/c5ab2ef
