### ISSUE TITLE
DietPi-Software | Pi-hole + Nginx not working

### ISSUE THREAD

**Issue by Joulinar** [MichaIng/DietPi#6165]
@MichaIng this variable is not understood by Nginx

https://github.com/MichaIng/DietPi/blob/a933855bede63d77b14fa39a092b043758cc8388/.conf/dps_93/nginx.pihole.conf#L16-L17

resulting in Nginx not being able to start.

```
Feb 15 09:00:38 DietPiR6S nginx[17533]: nginx: [emerg] unknown "frame_option" variable
Feb 15 09:00:38 DietPiR6S nginx[17533]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

based on https://dietpi.com/forum/t/pi-hole-install-crashes-nginx/15960

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/5eddfef
And in master branch, from where the file is downloaded on install: https://github.com/MichaIng/DietPi/commit/5907a92
