### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by symbios24** [MichaIng/DietPi#6166]
Hello there.
Not really a bug

Im using latest dietpi bullseye on a Raspberry Pi zero in hotspot mode

Im connected with ssh in my Raspberry Pi zero when i run dietpi-update im disconnected and cannot connect anymore,the thing is,its probably necessary to answer yes to some prompts thats why i never get back to the ssh connection

Is it possible to add a command on a next update to answer yes automatically in all prompts(except the backup)

Example: dietpi-update -y

Or just a setting to activate auto update in dietpi-config with the option to disable/answer no to backup option

Thank you

**Comment by symbios24** [comment]
The thing is if i leave it, it never finishes the update.probably i have to answer yes to some prompt that i cannot since im disconnected (wifi dropped) i dont mind for the apt packages but for the dietpi updates

**Comment by Joulinar** [comment]
Usually the SSH session should not terminate at all. This is the current challenge because we stop the hotspot service during update. Something we need to change from our side. As workaround you could exclude hotspot service from being DietPi controlled. This should keep the hotspot active during update process

**Comment by symbios24** [comment]
How can i do that?

**Comment by MichaIng** [comment]
> Usually the SSH session should not terminate at all.

I was just thinking the same, and whether it is hence possible to control SSH servers without downside. But SSH connections can also break and leaving the possibility to always reconnect is mandatory.

> How can i do that?

In `dietpi-services` select `hostapd` and then change from "DietPi controlled" to "systemd controlled" and exclude it. To be failsafe, to the same for `isc-dhcp-server` so a DHCP lease can be renewed in case it times out during updates/installs.

**Comment by MichaIng** [comment]
Done with: https://github.com/MichaIng/DietPi/commit/c259660
