### ISSUE TITLE
SSH on Hyper-V not operational

### ISSUE THREAD

**Issue by zarigata** [MichaIng/DietPi#6177]
#### Required Information
- DietPi version | 8.14.12
- Distro version | Hyper-V
- Kernel version | 5.10.0

#### Steps to reproduce

1. try to log in via putty

#### Expected behaviour

- SSH OPEN ON PUTTY

#### Actual behaviour

- Access denied

#### Extra details

- ...

**Comment by Joulinar** [comment]
Are you able to login locally and check SSH server, if it has been started correctly.

**Comment by zarigata** [comment]
yes i am, no problems on that

**Comment by Joulinar** [comment]
SSH server is running a listen to correct port? Are you able to ping anything on the web? You get correct IP address assigned?

```
journalctl -u dropbear.service
ss -tulpn | grep LISTEN
ping google.com
ip a, ip r
```

**Comment by zarigata** [comment]
yes it can leave the signal
journalctl -u dropbear.service = no records
it is a IP fixed

**Comment by Joulinar** [comment]
I would be appreciated if you can share the output of the commands I request. Did you changed to OpenSSH server?

**Comment by zarigata** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/39637452/219882513-728562f2-c116-4cd0-9f23-292924566302.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/39637452/219882596-fb870013-3112-4b88-a064-3df048693f5f.png">

**Comment by MichaIng** [comment]
and
```sh
ss -tlpn
```
?

**Comment by Joulinar** [comment]
Is `192.168.15.0` your local network range?

**Comment by zarigata** [comment]
yes

**Comment by zarigata** [comment]
> 

ethernet

**Comment by Joulinar** [comment]
To be honest, it's not that easy to communicate with you. Some more words would be appreciated. As well, please answer our questions. Can you post the output as requested by @MichaIng . Did you disabled IPv6 in meantime? What interface type you setup on Hyper-V? What is the IP range of your local network?

**Comment by zarigata** [comment]
sorry not a good response, i have to do this while doing some other stuff at the company and they sell what they cant demand, so i have to keep, 

SS - tlpn 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/39637452/219893463-43bba9c8-2b25-492b-9b06-3986a0ed3d4e.png">
ipv6 is not enabled, it can  be activated ath the modem, but it is not recommended,  it is on a 100mbts ethernet, it has a IP locked on it.

**Comment by Joulinar** [comment]
disable IPv6 on your DietPi device. And still an outstanding question, what is the IP range of your local network? Is it `192.168.15.0`?

**Comment by zarigata** [comment]
it is 192,168,15,0 to 192,168,15,255, being 255 used to end

**Comment by Joulinar** [comment]
are you able to reach PiHole web interface located on this VM? Did you installed UFW?

**Comment by zarigata** [comment]
> are you able to reach PiHole web interface located on this VM? Did you installed UFW?

<img width="868" alt="image" src="https://user-images.githubusercontent.com/39637452/219901242-dcab52c2-8de8-4685-b1d7-f53f0fbfaa6c.png">
yes i can acees the progtrams i have made available, i have a firewall but is not UFW, it is a modem one

**Comment by MichaIng** [comment]
Double check your firewall rules then. The VM is generally connected to LAN and reachable, SSH is listening and not reporting any errors, so there is something else in front of it blocking requests. If there is any firewall, the very first attempt to solve connection issues is disabling the firewall 😉.

**Comment by zarigata** [comment]
i checked, it was not, i installed a BIOS version and it went well, perhaps some HYPER-V modification?
