### ISSUE TITLE
dietpi-update stalls on Applying incremental updates 8.13.2 to 8.14.2

### ISSUE THREAD

**Issue by eyduh** [MichaIng/DietPi#6191]
#### Required Information
- DietPi version 
``` # cat /boot/dietpi/.version
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=13
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
```
- Distro version | `bullseye`
- Kernel version | `Linux hostname 6.0.13-meson64 #22.11.2 SMP PREEMPT Sun Dec 18 16:52:19 CET 2022 aarch64 GNU/Linux`
- SBC model | `Odroid C4/HC4 (aarch64)`
- Power supply used | Stock
- SD card used | N/A, booting off a USB->SATA SSD with a ZFS mirror of spinny disks in the toaster slots.

#### Additional Information (if applicable)
- Software title | dietpi-update
- Was the software title installed freshly or updated/migrated? N/A
- Can this issue be replicated on a fresh installation of DietPi? N/A
- Bug report ID | `8984bd2a-5e20-464a-8e8b-229b1131f791`

Not sure the report worked, seem to have stalled like the update =/

#### Steps to reproduce
1. Run `dietpi-update` as root or `sudo dietpi-update` as dietpi

#### Expected behaviour
- the `dietpi-update` process finishes

#### Actual behaviour

- `dietpi-update` stalls on 
```
DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying incremental patches

[ INFO ] DietPi-Update | Current version : v8.13.2
[ INFO ] DietPi-Update | Latest version  : v8.14.2

```
I've left this overnight and between a few different minor kernel updates through `apt upgrade` and the issue persists.

#### Extra details

- This Odroid HC4 has the tiny LED display with an RTC clock and has `systemd-timesyncd` disabled.
- It also has [pimox](https://github.com/pimox/pimox7) installed which might be the sauce of `dietpi-update` not working.

**Comment by MichaIng** [comment]
pimox is for Raspberry Pi 4, according to info on the repo. Does it work at all on Odroid HC4? And if you already suspect it being the issue, did you try to stop it and repeat the update?

RTC and `systemd-timesyncd` are different things and complement each other. You need a network time sync, to keep the RTC accurate in the long term. However, shouldn't be related to the handing update.

Do know exactly where it hangs:
```sh
bash -x /boot/dietpi/dietpi-update 1
```

**Comment by eyduh** [comment]
re: timesyncd, forgot to mention that pimox installed chronyd and is keeping the RTC in sync with that.

tail of `bash -x /boot/dietpi/dietpi-update 1`
```
+ (( i<3 ))
+ output_string+='\n'
+ (( i++ ))
+ (( i<3 ))
+ echo -ne '\e[0m\r\e[J\e[90m[\e[0m INFO \e[90m]\e[0m \e[90mDietPi-Update |\e[0m \e[90mLatest version  : v8.14.2\n\e[0m'
[ INFO ] DietPi-Update | Latest version  : v8.14.2
+ unset -f Print
+ ((  8 == 6  ))
+ rm /boot/dietpi/patch_file
+ DietPi-master/.update/patches

```

tail of `bash -x /boot/dietpi/dietpi-bugreport 1`
```
+ cat /proc/cpuinfo
+ for i in "${aCOMMAND_LIST[@]}"
+ echo -e '\n----------\nfree -m\n----------'
+ free -m
+ for i in "${aCOMMAND_LIST[@]}"
+ echo -e '\n----------\nps aux\n----------'
+ ps aux
+ for i in "${aCOMMAND_LIST[@]}"
+ echo -e '\n----------\nblkid\n----------'
+ blkid
+ for i in "${aCOMMAND_LIST[@]}"
+ echo -e '\n----------\nmount\n----------'
+ mount
+ for i in "${aCOMMAND_LIST[@]}"
+ echo -e '\n----------\ndf -Th\n----------'
+ df -Th

```

**Comment by MichaIng** [comment]
> pimox installed chronyd and is keeping the RTC in sync with that.

Ah okay, makes sense. You changed time sync mode in `dietpi-config` > Advanced Options to custom then?

Ah, the `-x` flag is not passed through to the patch script. Try that:
```sh
sed -i 's|.update/patches"|.update/patches" -x|' /boot/dietpi/dietpi-update
dietpi-update 1
```

**Comment by eyduh** [comment]
> Ah okay, makes sense. You changed time sync mode in dietpi-config > Advanced Options to custom then?

Yes! It's all [joulinar's fault](https://dietpi.com/forum/t/pimox/5659/8) q:

running `dietpi-update 1` after adding the `-x` flag in the script returns the same output?
```
...
[  OK  ] DietPi-Update | APT upgrade

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Installing new DietPi code

[  OK  ] DietPi-Update | Downloading update archive
[  OK  ] DietPi-Update | Unpacking update archive
[  OK  ] DietPi-Update | Removing unused files
[  OK  ] DietPi-Update | Hardening update archive mode
[  OK  ] DietPi-Update | Installing new DietPi scripts
[  OK  ] DietPi-Update | Installing new DietPi system files
[ SUB1 ] DietPi-Set_software > verify_dietpi.txt
[  OK  ] DietPi-Set_software | Downloading current dietpi.txt
[  OK  ] verify_dietpi.txt  | Completed

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying incremental patches

[ INFO ] DietPi-Update | Current version : v8.13.2
[ INFO ] DietPi-Update | Latest version  : v8.14.2

```

**Comment by Joulinar** [comment]
can you open a 2nd SSH session and check running/hanging task using `ps -ef` or `htop`

**Comment by MichaIng** [comment]
Good idea, better than my idea to download and execute the `patches` script manually (with `-x` flag).

**Comment by eyduh** [comment]
Yeah I'm usually in a tmux session so can jsut split the view. I decided to have a look at the screen attached to it and the dietpi-banner was telling me to reboot, so I killed everything and tried to reboot. Strangely enough it is still telling me to reboot. 

The most recently installed kernel 6.1.11-meson64 doesn't get loaded at boot, maybe the pimox install got rid of some uboot magic that tells the board how to boot new kernels cause after a few reboots it's the same. 
```
root@lenticular:/# ls -lah /boot/
total 89M
drwxr-xr-x  5 root root 4.0K Feb 27 21:37 .
drwxr-xr-x 22 root root 4.0K Feb 23 01:07 ..
-rw-r--r--  1 root root    0 Feb 25 23:15 .next
lrwxrwxrwx  1 root root   22 Feb 25 23:15 Image -> vmlinuz-6.1.11-meson64
-rw-r--r--  1 root root 4.3M Feb 18 01:07 System.map-6.1.11-meson64
-rw-r--r--  1 root root 2.8K Feb 27 21:37 boot.cmd
-rw-r--r--  1 root root 2.8K Feb 27 21:37 boot.scr
-rw-r--r--  1 root root 246K Feb 18 01:07 config-6.1.11-meson64
drwxr-xr-x  4 root root 4.0K Feb 27 00:03 dietpi
-rw-r--r--  1 root root  18K Dec 20 05:31 dietpi-LICENSE.txt
-rw-r--r--  1 root root  16K Dec 20 05:31 dietpi-README.md
-rw-r--r--  1 root root  17K Feb 25 23:10 dietpi.txt
-rw-r--r--  1 root root  312 Feb 27 21:34 dietpiEnv.txt
lrwxrwxrwx  1 root root   18 Feb 25 23:15 dtb -> dtb-6.1.11-meson64
drwxr-xr-x  3 root root 4.0K Feb 25 23:11 dtb-6.1.11-meson64
-rw-r--r--  1 root root  17M Feb 27 21:11 initrd.img-6.1.11-meson64
drwxr-xr-x  2 root root 4.0K Jan 16 00:08 pve
-rw-r--r--  1 root root  26M Feb 25 23:15 uImage
lrwxrwxrwx  1 root root   22 Feb 27 21:11 uInitrd -> uInitrd-6.1.11-meson64
-rw-r--r--  1 root root  17M Feb 27 21:11 uInitrd-6.1.11-meson64
-rw-r--r--  1 root root  26M Feb 18 01:07 vmlinuz-6.1.11-meson64
root@lenticular:/# uname -r
6.0.13-meson64
```

**Comment by eyduh** [comment]
Oh awesome, the bugreport managed to do its thing this time around!
```
8984bd2a-5e20-464a-8e8b-229b1131f791
```

**Comment by MichaIng** [comment]
I fail to understand what pimox does in your case:
- The GitHub repo clearly states it is for Raspberry Pi 4, but you use it on Odroid HC4?
- It is a virtualisation host, so to run VMs on that system, isn't it? In this case, why should it mess with the hosts kernel?

But indeed, of the only installed kernel is not loaded, there seem to be another conflicting boot partition. Do you have any other drives attached, which contain a kernel? Also check `lsblk` and `df` regarding this.

**Comment by eyduh** [comment]
I dunno, for fun? Definitely not for profit. 

I have an old laptop and an old desktop running proxmox 7 and wanted to set up a cluster. With two nodes there will never be consensus and through it would be fun to try and get an LXC arm64 container or two running in HA on all three nodes (using qemu-static on the x86_64 nodes). Also figured it would be nice to have the hc4 reachable from the web gui of the other two nodes and use it for proxmox backups through zfs send or as storage through zfs share over nfs or smb.

Why I chose dietpi over armbian was for lean-ness sake and cause I like dietpi, plus found that thread on the forum. 
Why odroid hc4 over raspberry pi is because my experience with zfs through usb3-sata adapters is patchy at best.

I thought the SD card that was in there was dead and just making the odroid look for the next boot device but it was still alive and indeed had the older kernel in there, after rsyncing its /boot its managed to boot the new kernel and apply the dietpi update.

Found this other [proxmox arm git](https://github.com/jiangcuo/Proxmox-Arm64) and gonna see if that is better compatible with the odroid hc4.

**Comment by eyduh** [comment]
It is strange that the SD-card reports I/O errors when booted into the OS, but it perfectly readable on my desktop, as well as at boot obviously. I tried a reboot after the update and it keeps booting from the SD card which isnt where the updates to /boot go to.

Do I continue this conversation in [the related thread](https://dietpi.com/forum/t/odroid-hc4-booting-from-ssd/6322?u=eyduh) on the forum or start a new one?

**Comment by MichaIng** [comment]
Better open a new one, as booting from USB and I/O errors after successful boot are a different thing.
