### ISSUE TITLE
DietPi-Config | Add support for Odroid Remote

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#621]

**Comment by Fourdee** [comment]
draft code/testing status:
- 🈯️ C2
- 🈯️ C1
- 🈯️ XU4 Cloudshell

**Comment by Fourdee** [comment]
Now, where to put this in DietPi-Config...

**Comment by Fourdee** [comment]
Display Options at the moment. DietPi-Config main menu needs a rethink and reshuffle at some point:
![image](https://cloud.githubusercontent.com/assets/7077026/21052317/469514c0-be1c-11e6-8b88-788dcb538203.png)
![image](https://cloud.githubusercontent.com/assets/7077026/21052322/4e598934-be1c-11e6-9593-fda3d4066a77.png)

**Comment by k-plan** [comment]
@Fourdee 

> Now, where to put this in DietPi-Config...

![161210-0009](https://cloud.githubusercontent.com/assets/17237601/21075824/0acc1f00-bf1c-11e6-9d54-63f6a97ba802.gif)


hmm .. other option is to put it under `DietPi - Advanced Options`

![161210-0008](https://cloud.githubusercontent.com/assets/17237601/21075788/fe2b3b06-bf1a-11e6-9394-58bfa40ae268.gif)

It is rather a input option like a keyboard. But I don't like to put it under `DietPi - Language and Regional Options ` 👎 


> DietPi-Config main menu needs a rethink and reshuffle at some point:


 Yes, DietPi is raise up like the wind in the last year. So many new devices and supported hardware in the past months. 😃

**Comment by Fourdee** [comment]
@k-plan 

> It is rather a input option like a keyboard. But I don't like to put it under DietPi - Language and Regional Options 👎

Yep, I think we could do with a new menu option called?:
- Peripheral Options
 1 Remote controls
 2 LCD Addons
 3 Bluetooth (maybe fits below)

Networking Options NAS/MISC, could change to?
- Connectivity Options
 1 Bluetooth

Or, we could do a?:
- Hardware Options
 1 Display Options
 2 Audio Options
 3 Network Options

So many options and possibilities, will make a new GiT ticket for this: https://github.com/Fourdee/DietPi/issues/639

**Comment by k-plan** [comment]
@Fourdee 

puh ... it's really difficult. 

I don't know, where your journey will end up ...

For the moment:  `dietpi-config`

---------------


1 - System Options
 * Locale 
 * Change Hostname
 * User Data Location
 * Timezone
 * Time sync mode
 * NTP Server
 * Swapfile size 
 * Log System 
 * Apt Mirror
 * Change Root Password 
 * Update firmware
 

2 - Performance Options 
 * Overclocking 
 * Change CPU Governor
 * CPU Throttle Up
 * Ondemand Sample Rate
 * Ondemand Down Factor
 * CPU Max Freq Limit
 * ARM Initial Turbo
 * ARM Temp Limit
 * SD-Card Overclocking
 
                
3 - Display Options
 * Change Resolution 
 * GPU/RAM Memory Split 
 * HDMI Boost
 * Overscan
 * LCD Panel addon
 
                    
4 - Audio Options 
  * Soundcard 
 
                     
5 - Peripheral Options
 * Keyboard
 * Serial console
 * Remote controls
 * Max USB current
 * I2c state
 * I2c frequency
 * RPi Camera
 * RPI Camera led 
                   
                 
6 - Network Options
 * Ethernet 
 * WiFi
 * Bluetooth 
 * IPv6 
 * Proxy
 * Test
 
     
7 - Connectivity Options 
 * SSH Server
 * File Server
 * Samba Client
 * FTP Client
 * NFS Client



8 - Advanced Options 
 * ???
 
  
9 - AutoStart Options 
 * Console:   Manual 
 * Console:   Automatic
 * Kodi
 * Desktops
 * DietPi-Cloudshell
 * CAVA 
 * RetroPie
 * Uae4ARM: (Fast boot)
 * Uae4ARM
 * DXX-Rebith
 * OpenTyrian
 

10 - Tools  
 * Benchmarks
 * Stress Test


----


Better in `dietpi-software` :
* NoIp
                 

------------

But it's not fix or final.
Had to sleep some night and rethink this.   

Have a look and give an opinion.
