### ISSUE TITLE
DietPi-Software | smokeping

### ISSUE THREAD

**Issue by pilovali** [MichaIng/DietPi#623]
You can follow these steps: http://olivermarshall.net/install-smokeping-on-ubuntu-14-04/
I do not know if it works with Nginx or Lighttpd.

Example on my Pi1: http://s2.pilovali.nl/cgi-bin/smokeping.cgi?target=DNS_Servers (expect long loading times)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
