### ISSUE TITLE
DietPi-Software | RealVNC (for direct graphics capture)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#624]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=962&p=4145#p4144

> Open the VNC Server dialog. Navigate to More > Options > Troubleshooting and select Enable experimental direct capture method.

> vncserver-x11-serviced.service

**Comment by Fourdee** [comment]
> Installing Raspberry Pi license (VNC Personal)
Please note that this is only valid for non-commercial use on Raspberry Pi devices.

RPi only 👎

**Comment by Fourdee** [comment]
online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=4149#p4149

**Comment by Fourdee** [comment]
Completed.

**Comment by opticyclic** [comment]
I did this manually and when I typed `vncserver` I got the error:

    Error: execvp(xauth): No such file or directory (2) [System]

I think you also need to include `apt-get install xauth`

**Comment by Fourdee** [comment]
@opticyclic 
xauth is installed with XserverXorg: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L4986

XserverXorg should get triggered for all software that requires a desktop.

Lets check your install file, whats results of:
```
dietpi-software list | grep '[[:space:]]=2'
```
