### ISSUE TITLE
XU4 Kodi | No sound

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#625]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=908&p=4146#p4066

**Comment by Fourdee** [comment]
Requested Bug report to check system config files.

**Comment by Fourdee** [comment]
No response, moving out of milestone.

**Comment by Fourdee** [comment]
No response. Marking as closed.

**Comment by p3p1** [comment]
I don't know if it's possible open again this ticket, but I have this problem, on a Odroid XU4, of the audio over HDMI using Kodi, installed through `dietpi-software`. Can you investigate?

**Comment by Fourdee** [comment]
@p3p1 

Thanks for the report.

I'd like to check your system settings/installed packages. Please can you send us a bug report?
http://dietpi.com/phpbb/viewtopic.php?f=8&t=499

**Comment by p3p1** [comment]
I will send you the report in couple of hours.

**Comment by p3p1** [comment]
Bug report send. Reference code: 3b7de7c5-6117-4842-8212-1a36256df7f9-0

**Comment by p3p1** [comment]
any news?

**Comment by Fourdee** [comment]
@p3p1 

Apologies, will put this in milestone and take a look.

**Comment by Fourdee** [comment]
New password prompts during install. Seems they broke automated password entries:
```
root@DietPi:~# pihole -a -p dietpi
Enter New Password (Blank for no password):
```

**Comment by Fourdee** [comment]
#### Tests/notes:
- 🈯️ Fresh install of XU4 v145 image + Kodi install only + autostart kodi = sound ok
- Check bug report logs/settings | Settings/confs match | XFCE installed
- 🈴 Kodi launched from XFCE4 = no sound
- 🈯️ User has autostart set to kodi = sound fine

**Comment by Fourdee** [comment]
@p3p1 

Most likely a pulse audio setting/issue, but lets test basic sound. Please run the following (not from desktop):
```
speaker-test -c2
```

Press CTRL+C to stop. Let me know if you hear sound on HDMI.

**Comment by p3p1** [comment]
Apologies for late response. No sound unfortunately on HDMI. I think it's not a hardware problem: HDMI works on other device and TV is at maximum volume.

**Comment by Fourdee** [comment]
@p3p1 

> I think it's not a hardware problem: HDMI works on other device and TV is at maximum volume.

Its very bizarre, there is an issue with no sound in XFCE4 + Kodi, however, Kodi from console replicates sound fine each test for me. We've also had no other reports of this, so you could be right.

To verify DietPi is not the cause, you could try a fresh installation, only installing Kodi, then test sound again.

Failing that, possible hardware issue (try another XU4 image to verify, eg: official ubuntu), or, incompatibility with TV, or, faulty HDMI cable.

**Comment by p3p1** [comment]
I can confirm that kodi works perferctly under LXDE, in XFCE I had a problem about the audio but I think it's connected to fact that the XFCE is started with root user. I still have a problem but I can't understand the reason: when kodi is launched from LXDE works well, but any other service (ssh,home assistant,nginx) is stucked.  I will try with a fresh install in the weekend. Anyway thanks for this wonderful bug tracking service.

**Comment by Fourdee** [comment]
Outdated, marking as closed.
