### ISSUE TITLE
Extra Software found in Software installed 

### ISSUE THREAD

**Issue by AdamF100001** [MichaIng/DietPi#6272]
![20230325_172809.jpg](https://user-images.githubusercontent.com/59096769/227732601-7a2e57c4-be4c-4832-a49f-bc03c3d2c5fe.jpg)

Extra Software found in Software installed List: Git Lighttpd SQL Light PHP Hypertext preprocessor Dietpi-RAMlog. All other software in image installed by me but what are the ones listed used for as I did willingly install them myself?Thanks Adam

**Comment by Joulinar** [comment]
Git: required to install/update PiHole.
Lighttpd: Web server used to display PiHole web interface.
SQL Light: Database used by PiHole to store information.
PHP Hypertext preprocessor: required to be able to display PiHole web interface.
Dietpi-RAMlog: default DietPi log system.
