### ISSUE TITLE
initial boot set-up failed 

### ISSUE THREAD

**Issue by mistrysiddh** [MichaIng/DietPi#6291]
i flashed os in pi 0w and connect to wifi after that installation process start and stuck on this error

![20230407_103451.jpg](https://user-images.githubusercontent.com/25217451/230544606-400b7943-4922-4add-8ccd-99bbbbe407aa.jpg)

**Comment by Joulinar** [comment]
Looks like an issue with SD card. Can you flash a new image again or try another one?

**Comment by mrfoxie** [comment]
let me try on new sdcard

**Comment by mrfoxie** [comment]
still the same issue but that same sdcard works on raspberry Pi 4 perfectly without any errors

**Comment by mrfoxie** [comment]
i this it maybe having with repository

**Comment by Joulinar** [comment]
The repository is the global Raspberry one but your error is a timeout on mmc1, which would be your SD card.

**Comment by mrfoxie** [comment]
the same sdcard worked fine on raspberry Pi 4

**Comment by mrfoxie** [comment]
![20230407_130137.jpg](https://user-images.githubusercontent.com/25217451/230563749-b7622995-d40b-407a-8527-c83549843908.jpg)

now getting this error 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

**Comment by Joulinar** [comment]
looks like your system is trying to connect to some Raspbian mirrors in India. Not sure if they have some server issues? Or if it is a local network problem.

**Comment by mrfoxie** [comment]
well, I tried to change the network but still got the same issue. I change the repo to USA and it worked perfectly fine. I had to change the repo multiple times to check the perfect one but I got it.

**Comment by MichaIng** [comment]
Generally the mirror is accessible: https://raspbian.mirror.net.in/raspbian/raspbian/

And at least the first package ia as well here: https://raspbian.mirror.net.in/raspbian/raspbian/pool/main/libe/libedit/libedit2_3.1-20191231-2_armhf.deb

Probably a temporary server issue 🤔.

**Comment by Joulinar** [comment]
Or some geo blocking?

**Comment by MichaIng** [comment]
Although the apt update seems to have succeeded and only the DEB download timed out.

**Comment by mrfoxie** [comment]
may be its due to geo blocking

**Comment by MichaIng** [comment]
I'll mark this issue as closed. Feel free to reopen if required.
