### ISSUE TITLE
SNMP is not working on NEO!

### ISSUE THREAD

**Issue by scm2016** [MichaIng/DietPi#630]
While installation got this...

Job for snmpd.service failed. See 'systemctl status snmpd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript snmpd, action "start" failed.
dpkg: error processing package snmpd (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 snmpd
E: Sub-process /usr/bin/dpkg returned an error code (1)
 
Need help...polling OID is not working!

**Comment by aliosa27** [comment]
It seems to be working on my neo. Would you mind posting your snmpd.conf file?
