### ISSUE TITLE
CPU temp wrong since 8.16

### ISSUE THREAD

**Issue by churchofnoise** [MichaIng/DietPi#6317]
#### Required Information
- DietPi version | issue started at version 8.16 beta, currently still present in 8.17.1 dev
- Distro version | bookworm (issue started when still running bullseye)
- Kernel version | `Linux HomeAssistant 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1 (2023-03-19) x86_64 `GNU/Linux
- SBC model |  Native PC (x86_64)
- Power supply used | mini-PC power supply
- SD card used | Samsung SSD

#### Steps to reproduce

1. Boot the device or run CPU command
2. Look at CPU temp

#### Expected behaviour
Expect the CPU temp to display correctly

#### Actual behaviour
CPU temp shows constantly at 27 degree C / 80 F (real temp currently 44 degree C as indicated by 'sensor' in HA, which is in line with previous indications on DietPi as well)

**Comment by MichaIng** [comment]
Thanks for your report.

Check out the issue and solution here: #6315
