### ISSUE TITLE
Ethernet NIC & Fan Issue 

### ISSUE THREAD

**Issue by AdamF100001** [MichaIng/DietPi#6324]
Hi

Ethernet NIC stops working when fan is connected to GPIO pins.

Works when fan isn't connected.

Thanks 

Adam

**Comment by AdamF100001** [comment]
### Creating a bug report/issue

#### Required Information
- DietPi version

G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=16
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'


- Distro version

bullseye 0

- Kernel version

Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

- SBC model RPi 4 Model B (aarch64)
- Power supply used | White 5V 1A that comes with the pi (EG: 5V 1A RAVpower)
- SD card used | SanDisk 

#### Additional Information (if applicable)


- Bug report ID Reference code: 13d7588b-63bd-4089-b2d6-df575745ccad 

#### Steps to reproduce
Connect fan to GPIO pins

#### Expected behaviour
Fan and Ethernet NIC function as normal
- ...

#### Actual behaviour
Fan not working and Ethernet NIC not work at the same time 
- ...

#### Additional Details

root@DietPi:~# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether dc:a6:32:17:47:b2 brd ff:ff:ff:ff:ff:ff
root@DietPi:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:17:47:b2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.6/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a00:23c5:9b03:1a01:dea6:32ff:fe17:47b2/64 scope global dynamic mngtmpaddr 
       valid_lft 283sec preferred_lft 103sec
    inet6 fe80::dea6:32ff:fe17:47b2/64 scope link 
       valid_lft forever preferred_lft forever
root@DietPi:~# dmesg -l 0,1,2,3
[    0.601892] bcm2708_fb soc:fb: Unable to determine number of FBs. Disabling driver.

**Comment by Joulinar** [comment]
Maybe you like to share a solution as you closed the issue now.

**Comment by AdamF100001** [comment]
Found the correct pins on amazon item listing image.

Reboot pi and ethernet connected.

![71-84H+qbeL _AC_SL1500_](https://user-images.githubusercontent.com/59096769/233157757-a40cbf88-2698-4cd2-9419-b5675d621018.jpg)

**Comment by MichaIng** [comment]
Right. Simple fans without PWM simply require a 5V pin (red) and a ground ping (black). Here the GPIO header assignments: https://www.raspberrypi.com/documentation/computers/raspberry-pi.html
