### ISSUE TITLE
Error installing Home Assistant

### ISSUE THREAD

**Issue by robex2005** [MichaIng/DietPi#6337]
Hello, 

I wanted to try out Home Asisstant on my pi3 with Dietpi, but sadly, i got an error upon installing...

/tmp/pip-ephem-wheel-cache-yfd_ujpo/wheels/54/8e/98/3c8a462676f35ac84e7e2a886d2e90c50c796b73f4cd1f351f
│   Building wheel for multidict (pyproject.toml): started
│   Building wheel for multidict (pyproject.toml): finished with status 'done'
│   Created wheel for multidict: filename=multidict-6.0.4-cp310-cp310-linux_armv7l.whl size=108779
│ sha256=abbe91acad0f5d46a0e13f0d469efb041da2481846b7c2f4ada019a88c25840d
│   Stored in directory:
│ /tmp/pip-ephem-wheel-cache-yfd_ujpo/wheels/d3/0f/ad/bd2376f99105cc211cfe25f50868fdbddedcf5bab5a699e47b
│ Successfully built aiohttp bcrypt ciso8601 home-assistant-bluetooth lru-dict pyyaml ulid-transform yarl cffi
│ frozenlist MarkupSafe multidict
│ Failed to build cryptography
│ ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

I've uploaded a bug report also, Reference code: c59fccc9-67f4-4cfb-92ca-13114f2bcba9

Please advise

Thanks,

**Comment by Joulinar** [comment]
pls can you fill the bug report and share the entire error message. Maybe you need to scroll up on your SSH session to get all lines.

**Comment by robex2005** [comment]
First reference code  for bug report (from first post): c59fccc9-67f4-4cfb-92ca-13114f2bcba9
Second one, after second try: c59fccc9-67f4-4cfb-92ca-13114f2bcba9

Log file attached:
[Installing Python with Home Assis.txt](https://github.com/MichaIng/DietPi/files/11308425/Installing.Python.with.Home.Assis.txt)

**Comment by Joulinar** [comment]
not everybody has access to these reports. Therefore, we have the issue template.

**Comment by robex2005** [comment]
Yes, the extra package resolves the issue

Thanks for the support
