### ISSUE TITLE
SOquartz kernel is missing support for qmi modems 

### ISSUE THREAD

**Issue by derpeter** [MichaIng/DietPi#6338]
#### Is your feature request related to a problem? Please describe:
Attaching a LTE/5G modem to boards using the SOquartz is very usefull as there are nice boards e.g. by waveshare supporting the CM module formfactor and providing a modem slot. The kernel shipped in the SOqartz images is missing the modules for the qmi based modems CONFIG_USB_NET_QMI_WWAN

#### Describe the solution you'd like:
enable CONFIG_USB_NET_QMI_WWAN in the kernel config

#### Describe alternatives you've considered:
building my own kernel is of course an option but is not nice to keep up with updates.
I also did not find documentation to build a kernel "the dietpi way" not sure if it supported outside of gitlab ci.

#### Additional context
There might be more modem related modules people will desire e.g.
CONFIG_USB_NET_CDC_MBIM
CONFIG_MHI_WWAN_MBIM

**Comment by Joulinar** [comment]
Usually we don't create own kernel and use mainline kernel if possible.

**Comment by Joulinar** [comment]
Usually we don't bild own kernel except for one SBC. Not sure which one. @MichaIng knows for sure.

**Comment by MichaIng** [comment]
For Quartz64 we do build own kernel packages.

I just checked and the Debian kernel contains all 3 drivers as modules. The RPi kernel contains the first two, but it makes sense that it does not container one for PCIe modems without PCIe slot (which Quartz64 A and the official SOQuartz baseboard have), so I'll add all of them.

**Comment by MichaIng** [comment]
Done with: https://github.com/MichaIng/DietPi/commit/f7a40ac
New packages are built: https://github.com/MichaIng/DietPi/actions/runs/4788943441
You can find them here in ~45 minutes: https://dietpi.com/downloads/binaries/testing/
Would be great if you could test it, then I'll move them to stable place for new Quartz64 images and an automated kernel upgrade on next DietPi update.

**Comment by MichaIng** [comment]
@derpeter 
Does it work now with the new kernel?
