### ISSUE TITLE
DietPi-Cloudshell | RootFS, 'Mount not active'

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#634]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=786&sid=b7bd99494cdf787d3481dbe83ffb83f7&start=40#p4030

> "Mount not active" message.
It is not always there and mostly affects the rootfs drive. The numbers are fine it's just this message.

**Comment by Fourdee** [comment]
Note to self:
- Possible df > tmp file does not exist, causing 'mount not found'
- df isnt being terminated? killall -w df ?

**Comment by Fourdee** [comment]
John's on holiday, will move this out of milestone for now.

**Comment by MichaIng** [comment]
@Fourdee 
Looks like this was solved: http://dietpi.com/phpbb/viewtopic.php?f=12&t=786&sid=cda26334864007646c4b4b8e6a280941&start=50#p4557 ? 😃

**Comment by Fourdee** [comment]
@MichaIng 

Yep, ran it fine during v6.0 testing, lets mark this as closed 👍
