### ISSUE TITLE
Unable to continue, DietPi-TimeSync will now terminate

### ISSUE THREAD

**Issue by Gene22** [MichaIng/DietPi#6387]
#### Details:
- Date           | Sat May 20 18:32:51 CEST 2023
- Bug report     | 6a98169a-1cb6-49e8-808f-74c8b9678808
- DietPi version | v8.17.2 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | Odroid C2 (aarch64) (ID=12)
- Kernel version | `Linux Odroid 6.1.11-meson64 #23.02.2 SMP PREEMPT Sat Feb 18 00:07:55 UTC 2023 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6)
- Command        | `systemctl start systemd-timesyncd`
- Exit code      | 1
- Software title | DietPi-TimeSync
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Failed to start systemd-timesyncd.service: Unit systemd-timesyncd.service is masked.

**Comment by Joulinar** [comment]
Did you update to Debian Bullseye before? 

```
apt install systemd-timesyncd
systemctl unmask systemd-timesyncd
/boot/dietpi/func/run_ntpd 1
```
