### ISSUE TITLE
DietPi-Software | Node-RED: Install fails on RPi 4 with 32-bit image

### ISSUE THREAD

**Issue by allacmc** [MichaIng/DietPi#6388]
─────────────────────────────────────────────────────
 Step: Installing Node-RED: tool for wiring devices, APIs and online services

[ INFO ] DietPi-Software | APT install python3, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.9.2-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[  OK  ] DietPi-Software | APT install python3
[  OK  ] DietPi-Software | mkdir -p /mnt/dietpi_userdata/node-red
[  OK  ] DietPi-Software | usermod -aG dialout,gpio,i2c,spi -d /mnt/dietpi_userdata/node-red -s /usr/sbin/nologin nodered
[  OK  ] DietPi-Software | eval echo 'nodered ALL=NOPASSWD: ALL' > /etc/sudoers.d/nodered
[  OK  ] DietPi-Software | chown -R nodered:nodered /mnt/dietpi_userdata/node-red
[  OK  ] DietPi-Software | cd /mnt/dietpi_userdata/node-red
[ INFO ] DietPi-Software | sudo -u nodered npm i --no-audit node-red, please wait...
/usr/bin/env: ‘node’: No such file or directory
[FAILED] DietPi-Software | sudo -u nodered npm i --no-audit node-red

---------------------------------------------------------------------
- DietPi has encountered an error                                   -
- Please create a ticket: https://github.com/MichaIng/DietPi/issues -
- Copy and paste only the BLUE lines below into the ticket          -
---------------------------------------------------------------------
#### Details:
- Date           | Mon May 22 13:08:41 BST 2023
- DietPi version | v8.17.2 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=1)
- Command        | `sudo -u nodered npm i --no-audit node-red`
- Exit code      | 127
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
/usr/bin/env: ‘node’: No such file or directory
```
---------------------------------------------------------------------
[FAILED] DietPi-Software | Unable to continue, DietPi-Software will now terminate.

**Comment by MichaIng** [comment]
Hmm, I need to rework our Node installer, which uses `uname -m`: https://github.com/MichaIng/nodejs-linux-installer/blob/master/node-install.sh#L22

I have to check how Pi-hole and rustup detect 32-bit userland on 64-bit CPU/kernel arch.

**Comment by MichaIng** [comment]
This should do it, but a last test would be nice: https://github.com/MichaIng/nodejs-linux-installer/pull/4

**Comment by MichaIng** [comment]
If you find time to the the above two command blocks, to verify that 32-bit and 64-bit OS are detected correctly, then I will merge the PR. Afterwards, an actual Node-RED installation can be tested. So probably best to verify on 64-bit image first, then 32-bit image followed by Node-RED install on 32-bit image 🙂.

**Comment by MichaIng** [comment]
Okay, many thanks for testing. I merged the PR at the Node installer, so issue should be fixed. A DietPi update is not needed.
