### ISSUE TITLE
NanoPi Neo AIR | No WiFi

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#640]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=886&start=10#p4291

**Comment by Fourdee** [comment]
Seems to work fine for a while:
```
root@DietPi:~# iwconfig
lo        no wireless extensions.

tunl0     no wireless extensions.

wlan0     IEEE 802.11  ESSID:"FuzonWifi"
          Mode:Managed  Frequency:2.447 GHz  Access Point: E8:DE:27:4A:D0:66
          Bit Rate=26 Mb/s   Tx-Power:32 dBm
          Retry min limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Managementmode:All packets received
          Link Quality=5/5  Signal level=-57 dBm  Noise level=-91 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:1  Invalid misc:0   Missed beacon:0
```

Then connection hangs with:
```
[  374.585777] Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dhd instead.
[  381.693527] Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dhd instead.
[  381.721118] Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dhd instead.
```

Rebuild from ARMbian build tools, restest.

**Comment by aliosa27** [comment]
Taking a look into this.

**Comment by nydal91** [comment]
Does wifi work now?

**Comment by Fourdee** [comment]
I actually think this is an issue with the ```dhd``` module that ARMbian uses. Although wifi works, the signal strength is noticeably lower than other onboard WiFi devices. Even with half-decent WiFi antenna: http://www.dx.com/p/wi-fi-antenna-ipx-female-to-sma-ky-adapter-connection-cable-w-1-13-cable-black-white-25cm-191117
```iw reg set GB``` also has no effect.

From what I remember, on the official FriendlyARM image (which our users are claiming their WiFi works on), they use ```brcmxxxx```.

**Comment by nydal91** [comment]
So its best to use a wifi dongle for now?

**Comment by JaggerMD** [comment]
On my Neo Air only wlan1 was recognized.
Changing wlan0/1 in /etc/udev/rules.d/70-persistent-net.rules did the trick.
From this point onboard wifi is starting fine.

**Comment by Fourdee** [comment]
User claims WiFi works fine on ARMbian image.

> http://dietpi.com/phpbb/viewtopic.php?f=9&t=886&start=10#p4330

note to self:
- re-test and check hciattach? service.
- Try using ```bcm....``` module, instead of ```dhd``` and their hciattach? service from the FriendlyARM image. Which works flawlessly.

**Comment by Fourdee** [comment]
Been testing with ARMbian 4.9 kernel. Firmware is needed, but looking good so far:
https://github.com/igorpecovnik/lib/commit/8f4e8e25e425169c90d12c67d21e5b84f5cdb231#commitcomment-20297066

**Comment by Fourdee** [comment]
WiFi works.

Issue with cpu govs, missing from kernel?
Exists on NanoPi NEO 4.9.
```
root@nanopiair:~# ls -lha /sys/devices/system/cpu/cpufreq/
total 0
drwxr-xr-x  2 root root 0 Dec 26 14:49 .
drwxr-xr-x 10 root root 0 Jan  1  1970 ..

```

```
root@nanopiair:~# dmesg | grep cpu
[    0.000000] percpu: Embedded 14 pages/cpu @deb21000 s26188 r8192 d22964 u57344
[    0.000000] pcpu-alloc: s26188 r8192 d22964 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.003542] CPU0: update cpu_capacity 1024
[    0.003554] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.017142] CPU1: update cpu_capacity 1024
[    0.017155] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.028293] CPU2: update cpu_capacity 1024
[    0.028303] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.039472] CPU3: update cpu_capacity 1024
[    0.039482] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.478649] cpuidle: using governor ladder
[    0.518671] cpuidle: using governor menu
[    4.281509] ledtrig-cpu: registered to indicate activity on CPUs
[    8.464810] of: dev_pm_opp_of_cpumask_add_table: couldn't find opp table for cpu:0, -19
[    8.464859] cpu cpu0: dev_pm_opp_get_opp_count: OPP table not found (-19)
[    8.465133] cpu cpu1: cpufreq_init: failed to get clk: -2
[    8.465371] cpu cpu2: cpufreq_init: failed to get clk: -2
[    8.465620] cpu cpu3: cpufreq_init: failed to get clk: -2
```

```
root@nanopiair:~# cat /sys/devices/system/cpu/cpuidle/current_driver
none
```

**Comment by thomaspfeiffer-git** [comment]
Hi Fourdee,
what did you do to get wifi working?
(Will there be a new image available soon?)

Thanks and best regards
Thomas

**Comment by Fourdee** [comment]
@thomaspfeiffer-git 
So it looks like a new image will be needed to fix WiFi at the moment (using the 4.9 kernel). When we release that image depends on if we can resolve the issues with cpu govs, and, no other issues crop up: https://github.com/Fourdee/DietPi/issues/640#issuecomment-269232618

**Comment by nydal91** [comment]
get the wifi to work with nmtui. thanks for a stable build! the ubuntu core was unstable when I was using it on nano pi air.

**Comment by Fourdee** [comment]
@thomaspfeiffer-git @nydal91 

With thanks to @zador-blood-stained from ARMbian (https://github.com/igorpecovnik/lib/issues/592#issuecomment-269524792), 4.9 kernel image is now ready for testing:
http://dietpi.com/downloads/testing/DietPi_NanoPiNEOAir-armv7-(Jessie).7z

Personally tested WiFi (and system in general), seems much more stable than the previous 3.x image. If others can test image above and let us know results, i'd be grateful.

**Comment by thomaspfeiffer-git** [comment]
Great, wifi works fine now, thanks very much! :-)

**Comment by Fourdee** [comment]
@thomaspfeiffer-git 
Excellent 👍 

Also seems much more stable than 3.x image.
- 🈯️  I'll set this to live image.

**Comment by Fourdee** [comment]
Completed.
