### ISSUE TITLE
 DietPi v8.19.1 - Installation of Pihole fails

### ISSUE THREAD

**Issue by bruno-briner** [MichaIng/DietPi#6455]
#### Details:
- Date           | Sun Jul  2 20:26:24 CEST 2023
- DietPi version | v8.19.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 2 Model B (armv7l) (ID=2)
- Kernel version | `Linux RPi-Pihole2 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `lighty-enable-mod dietpi-https`
- Exit code      | 2
- Software title | DietPi-Software

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`

G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=19
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN` :  bookworm 0
- Kernel version | `uname -a` :  `Linux RPi-Pihole2 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3) : RPi 2 Model B (armv7l)
- Power supply used | (EG: 5V 1A RAVpower) : Orico 5V x 2.4A
- SD card used | (EG: SanDisk ultra)  :  SanDisk Extreme 16GB

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud) : Pihole
- Was the software title installed freshly or updated/migrated? :  Fresh install of Dietpi and Pihole
- Can this issue be replicated on a fresh installation of DietPi?  :  Yes
- Bug report ID | `echo $G_HW_UUID`. : f0323002-d125-4508-a70d-bcd37ceef613

#### Steps to reproduce

1. ... Fresh install of Dietpi in a new SD card
2. ... Install of Pihole

#### Expected behaviour

- ... Sucessfull installation

#### Actual behaviour

- ... [FAILED] DietPi-Software | lighty-enable-mod dietpi-https

#### Extra details

- ...

#### Additional logs:
```
Ignoring unknown module: dietpi-https
Run "service lighttpd force-reload" to enable changes
```

**Comment by MichaIng** [comment]
Many thanks for reporting. A copy&paste error. Fixed with: https://github.com/MichaIng/DietPi/commit/854bb14

I'll ship a live patch. Here is the code it will execute to fix the issue:
```sh
sed -i '/setenv.*dietpi-https/s/dietpi-https/setenv/' /boot/dietpi/dietpi-software
```
