### ISSUE TITLE
 DietPi-Software | Update Nextcloud to v11

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#647]
There's quite a few changes this time around from increased security and scalability optimizations.

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks, we'll get this updated for v140 👍

**Comment by Fourdee** [comment]
```
Nextcloud is not installed - only a limited number of commands are available
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'nextcloud'
 ->
```
Looks like we now need to create the MySQL DB.

^^ yep
```
Nextcloud was successfully installed
```

**Comment by Fourdee** [comment]
Tests:
- 🈯️ ARM64
- 🈯️ ARMv7

![image](https://cloud.githubusercontent.com/assets/7077026/21181931/3d2295b8-c1f8-11e6-9826-b5c811a286dc.png)

**Comment by Fourdee** [comment]
Completed. V11 for new installations only (unless NextCloud provides an update method within app).
