### ISSUE TITLE
[PaperMC] Geyser and Floodgate don't install correctly during initial setup using DietPi-Software

### ISSUE THREAD

**Issue by NatureHog** [MichaIng/DietPi#6471]
#### Details:
- Date           | Tue Jul 11 19:23:06 BST 2023
- Bug report     | e939f999-8460-4152-871e-01bf00369efb
- DietPi version | v8.19.1 (MichaIng/master)
- Image creator  |
- Pre-image      |
- Hardware       | RPi 3 Model B (aarch64) (ID=3)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `curl -sSfL https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastStableBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar -o Geyser-Spigot.jar`
- Exit code      | 22
- Software title | DietPi-Software
#### Steps to reproduce:

1. Using DietPi-Software, try to install PaperMC
2. During the setup, it asks you if you'd want to install Geyser and Floodgate plugins for comaptibility with MC: Bedrock Edition
3. If you answer "yes" the setup fails
#### Expected behaviour:

- During initial installation of PaperMC using DietPi-Software, it should automatically install Geyser and Floodgate if asked
#### Actual behaviour:

- Crash during setup, if installing Geyser and Floodgate along with PaperMC
#### Extra details:

- I was connected using WiFi when this error occurred. Since everything else worked using the same WiFi connection I haven't tried using Ethernet...
- I assume this error occurs because of a broken URL being used somewhere during setup...
#### Additional logs:
```
curl: (22) The requested URL returned error: 404
```

**Comment by Joulinar** [comment]
Looks like download location has been changed and we would need to update our installation script.
