### ISSUE TITLE
Odroid C2 - GPIO support

### ISSUE THREAD

**Issue by wreyniers** [MichaIng/DietPi#650]
I have a PIR sensor I would love to use on DietPi. I took a swing at installing wiringPi as they now support the Odroid C2 but I ended up in a dependency loop.  Essentially my goal is to turn off my TV over CEC if it doesn't detect motion for 15 minutes, then turn it back on when someone walks in the room. 

Any chance we could have this for our C2?

Here's the wiringPi Github repo:
https://github.com/hardkernel/wiringPi

**Comment by Fourdee** [comment]
- 🈯️ C1
- 🈯️ C2
- 🈯️ XU4
```
root@DietPi:~# gpio -v
gpio version: 2.33
Copyright (c) 2012-2014 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Hardkernel ODROID Details:
  Type: ODROID-C2, Revision: 1, Memory: 2048MB, Maker: Hardkernel
```

```
root@DietPi-XU4:~# gpio -v
gpio version: 2.33
Copyright (c) 2012-2014 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Hardkernel ODROID Details:
  Type: ODROID-XU3/4, Revision: 1, Memory: 2048MB, Maker: Hardkernel
```

```
root@DietPi:~# gpio -v
gpio version: 2.33
Copyright (c) 2012-2014 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Hardkernel ODROID Details:
  Type: ODROID-C1/C1+, Revision: 1, Memory: 1024MB, Maker: Hardkernel
```

**Comment by Fourdee** [comment]
Completed.

**Comment by wreyniers** [comment]
Wow. What a quick turn around! Do I just have to run apt-get upgrade to get
this on my dietpi?

**Comment by Fourdee** [comment]
It will be available in dietpi-software when v140 is released. Hopefully before Xmas [😊]

Once v140 is released, you can update with:
dietpi-update


________________________________

**Comment by wreyniers** [comment]
Awesome! Thanks, you da best!

**Comment by TominJoseph18** [comment]
Hi.

I want to send interrupts through my gpio pins. I am using the wiringPi Library for this purpose. When a code to wait for interrupt is run ,the ethernet connection to my laptop breaks and it says broken pipe error.

Could someone please help me to execute a command X in C when an interrupt event occurs which also prevents any kind of switch debouncing and transient voltages.

Thank you.
