### ISSUE TITLE
Ghotos-sync not running after upgrade to Bookworm

### ISSUE THREAD

**Issue by robex2005** [MichaIng/DietPi#6535]
#### Required Information
- DietPi version | 
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=20
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'
- Distro version | bookworm
- Kernel version | `Linux DietPi 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux`
- SBC model | Native PC (x86_64)

#### Additional Information (if applicable)
- Software title | Gphotos-sync (https://github.com/gilesknap/gphotos-sync)

#### Steps to reproduce
running the following command: 
~/gphotos_venv# /root/gphotos_venv/bin/python3 /root/gphotos_venv/bin/gphotos-sync  --secret /root/gphotos_venv/DB2/client_secret.json --db-path /root/gphotos_venv/DB2 /mnt/backup/GPhotos/ $@ >> /root/gphotos_venv/gphotos.log --logfile /tmp

#### Expected behaviour
should sync photos from account without error

#### Actual behaviour
running the above script, i'm getting the error:

Traceback (most recent call last):
  File "/root/gphotos_venv/bin/gphotos-sync", line 5, in <module>
    from gphotos_sync.Main import main
ModuleNotFoundError: No module named 'gphotos_sync'

#### Extra details
All was working fine untill upgraded Dietpi to Debian Bookworm from Bullseye

Tried to repair the istallation, reinstalling gphotos-sync, no change.

From the commands bellow, it seems that ghphotos-sync is installed correctly:

root@DietPi:# which gphotos-sync
/usr/local/bin/gphotos-sync
root@DietPi:# gphotos-sync --version
3.1.3
root@DietPi:~# which python3
/usr/bin/python3

Any pointers?

PS: i did submit a new issue to the developer also, but without a reply...

**Comment by Joulinar** [comment]
maybe `gphotos-sync` is not able to run on Debian Bookworm due to the new python3 version?

**Comment by MichaIng** [comment]
```
ModuleNotFoundError: No module named 'gphotos_sync'
```
You need to reinstall the `venv`. I guess in `/root/gphotos_venv/lib/` there is only a `python3.9` directory, right? Repeat whichever install instructions you followed to install gphotos-sync via `venv`, to have all dependencies as well as the app itself installed for Python 3.11.

**Comment by robex2005** [comment]
Hello, 

Reinstalled the whole venv, and after pointing the cron job to the new venv location, everything works 
Thanks for the pointers, and keep up the good work!

**Comment by MichaIng** [comment]
Great. Yeah that is one downside with Python projects when doing distro upgrades. They need to be reinstalled, including all their dependencies, regardless whether installed as system module, `venv`, `virtualenv` or as user module. Only with a self-contained `pyenv` it would continue to work, but that comes with other difficulties.
