### ISSUE TITLE
Dietpi Software not able to detect latest Ampache version

### ISSUE THREAD

**Issue by bartolus39** [MichaIng/DietPi#6598]
#### Required Information
- DietPi version | 8.21
- Distro version | bookworm 0
- Kernel version |  6.1.21-v8+
- SBC model | RPi 4 Model B (aarch64)
- Power supply used | 5.1V 3.5A iUniker
- SD card used | 128GB SanDisk Extreme

#### Additional Information (if applicable)
- Software title | Ampache
- Was the software title installed freshly or updated/migrated? Version 5.6.2. was installed
- Can this issue be replicated on a fresh installation of DietPi? Probably yes

#### Steps to reproduce
1. Update Ampache install by dietpi-software reinstall 40
 

#### Expected behaviour
- Should either remain at version 5.6.2 or (if already approved) upgrade to version 6.0.2

#### Actual behaviour

- During re-install process (dietpi-software reinstall 40) I see the error:
[FAILED] DietPi-Software | Automatic latest Ampache download URL detection failed.
[FAILED] DietPi-Software | "https://github.com/ampache/ampache/releases/download/5.5.3/ampache-5.5.3_all.zip" will be used as fallback, but a newer version might be available.

So finally I end with a downgrade. 

So, probably only the part of the script which is checking for latest version on github is not working anymore (but it did some months ago)

Thanks in advance
Kind regards,
Bernhard

**Comment by MichaIng** [comment]
Many thanks for your report.

Indeed Ampache releases are now done per PHP version and have it in the file names. Fixed for next release: https://github.com/MichaIng/DietPi/commit/4ca5181
