### ISSUE TITLE
install fails on PC/notebook

### ISSUE THREAD

**Issue by QuadCorei8085** [MichaIng/DietPi#6606]
### Creating a bug report/issue
Having an old Acer-5820tg notebbok with i5-480m cpu, wanted to try dietpi on it.

**I tried to install the "Native PC for BIOS/CSM" image.**
In this case the dietpi console shows up few seconds after I insert the USB flashdrive (flashed with rufus) and I turn on the notebook.
I see that the OS runs and I can update/configure/install software but it seems to be running of the flashdrive and I was not even asked where to install the OS. Issue is: I would like to have it installed on my HDD.

**tried to install Native PC for UEFI**
This image only worked when I formatted/flash the flashdrive in rufus with the MBR option.
After the green welcome screen I hit install, it asks if i want to install it to the only one detected HDD (correct). I hit enter it starts to go on for a while.
At some point it shows a warning with "possible missing firmware bnx2x" then goes on. 
After a while it shuts down the PC and when I boot it again it reports there is no bootable image.

Any idea how I could test diepit on this old hardware? Is there an age/architecture limitation?

**Comment by MichaIng** [comment]
So it seems this notebook does not support UEFI? Then you need the BIOS image. Use the "Installer Image" to have the Clonezilla-based dialogue to install DietPi to an internal drive. The "Direct write Image" would need to be flashed to the internal drive directly, i.e. flashed on a USB drive it indeed runs like a live OS, as you observed.
