### ISSUE TITLE
ARM64 VM Image

### ISSUE THREAD

**Issue by dirkhh** [MichaIng/DietPi#6627]
#### Formal device information
- Device name | UTM on Mac (or qemu/kvm for Linux based ARM64 systems
- Official product URL | https://mac.getutm.app/
- GitHub resource URL (if available) | https://github.com/utmapp/UTM
- Image download URL | https://mac.getutm.app/gallery/debian-11-ldxe

#### Is the SBC officially supported by the Debian installer?
- Debian Bookworm install on UTM seems straightforward and pain-free

**Comment by MichaIng** [comment]
Let's keep it on the existing request: #5637
