### ISSUE TITLE
V140: LMS installation fails on oDroid C2 (aarch64)

### ISSUE THREAD

**Issue by audiomuze** [MichaIng/DietPi#663]
Apt-get has failed:                                                │                                                                                    
                                                                                   │  - Apt string = zlib1g-dev libjpeg-dev libpng-dev                  │                                                                                    
                                                                                   │ libjpeg62-turbo-dev                                                │                                                                                    
                                                                                   │  - Error code = 100                                                │                                                                                    
                                                                                   │  - Software Title = SqueezeBox: logitech media server (lms)        │                                                                                    
                                                                                   │                                                                    │                                                                                    
                                                                                   │ Please report this issue to DietPi so it can be investigated.      │                                                                                    
                                                                                   │                                                                    │                                                                                    
                                                                                   │ DietPi-Software will now exit.                                     │                                                                                    
                                                                                   │                                                                    │                                                                                    
                                                                                   │                                                                    │                                                                                    
                                                                                   │                               <Ok>

**Comment by Fourdee** [comment]
@audiomuze 
Thanks for report, i'll take a look

**Comment by Fourdee** [comment]
@audiomuze 
Tested ok on fresh C2 install here.

Lets try manually installing those packages and see what errors we get (please paste results):
```
apt-get install zlib1g-dev libjpeg-dev libpng-dev libjpeg62-turbo-dev
```

**Comment by audiomuze** [comment]
`The following packages have unmet dependencies:
 libjpeg62-turbo-dev : Depends: libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
` 

So it would seem build-essential needs to be installed?

**Comment by audiomuze** [comment]
` Welcome to DietPi-Software 


 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Update & upgrade APT
 Please wait...

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt apt-utils libapt-inst1.5 libapt-pkg4.12
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,348 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main libapt-pkg4.12 arm64 1.0.9.8.4 [738 kB]
Get:2 http://security.debian.org/ jessie/updates/main apt arm64 1.0.9.8.4 [1,084 kB]
Get:3 http://security.debian.org/ jessie/updates/main libapt-inst1.5 arm64 1.0.9.8.4 [168 kB]                                                                                                                                               
Get:4 http://security.debian.org/ jessie/updates/main apt-utils arm64 1.0.9.8.4 [358 kB]                                                                                                                                                    
Fetched 2,348 kB in 15s (147 kB/s)                                                                                                                                                                                                          
(Reading database ... 16176 files and directories currently installed.)
Preparing to unpack .../libapt-pkg4.12_1.0.9.8.4_arm64.deb ...
Unpacking libapt-pkg4.12:arm64 (1.0.9.8.4) over (1.0.9.8.3) ...
Setting up libapt-pkg4.12:arm64 (1.0.9.8.4) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
(Reading database ... 16176 files and directories currently installed.)
Preparing to unpack .../apt_1.0.9.8.4_arm64.deb ...
Unpacking apt (1.0.9.8.4) over (1.0.9.8.3) ...
Setting up apt (1.0.9.8.4) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
(Reading database ... 16176 files and directories currently installed.)
Preparing to unpack .../libapt-inst1.5_1.0.9.8.4_arm64.deb ...
Unpacking libapt-inst1.5:arm64 (1.0.9.8.4) over (1.0.9.8.3) ...
Preparing to unpack .../apt-utils_1.0.9.8.4_arm64.deb ...
Unpacking apt-utils (1.0.9.8.4) over (1.0.9.8.3) ...
Setting up libapt-inst1.5:arm64 (1.0.9.8.4) ...
Setting up apt-utils (1.0.9.8.4) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Checking for prerequisite software
 Please wait...

 [Info] Alsa will be installed

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron


 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Install software
 Please wait...

 ALSA: linux sound system
 [Info] Please wait...

 #               processing | D i e t  P i             #

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libasound2 libasound2-data libsamplerate0
Suggested packages:
  libasound2-plugins
The following NEW packages will be installed:
  alsa-base alsa-utils libasound2 libasound2-data libsamplerate0
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,333 kB of archives.
After this operation, 5,108 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ jessie/main alsa-base all 1.0.27+1 [54.3 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main libasound2-data all 1.0.28-1 [64.8 kB]
Get:3 http://ftp.debian.org/debian/ jessie/main libasound2 arm64 1.0.28-1 [308 kB]
Get:4 http://ftp.debian.org/debian/ jessie/main libsamplerate0 arm64 0.1.8-8 [940 kB]
Get:5 http://ftp.debian.org/debian/ jessie/main alsa-utils arm64 1.0.28-1 [966 kB]                                                                                                                                                          
Fetched 2,333 kB in 12s (192 kB/s)                                                                                                                                                                                                          
Selecting previously unselected package alsa-base.
(Reading database ... 16176 files and directories currently installed.)
Preparing to unpack .../alsa-base_1.0.27+1_all.deb ...
Unpacking alsa-base (1.0.27+1) ...
Selecting previously unselected package libasound2-data.
Preparing to unpack .../libasound2-data_1.0.28-1_all.deb ...
Unpacking libasound2-data (1.0.28-1) ...
Selecting previously unselected package libasound2:arm64.
Preparing to unpack .../libasound2_1.0.28-1_arm64.deb ...
Unpacking libasound2:arm64 (1.0.28-1) ...
Selecting previously unselected package libsamplerate0:arm64.
Preparing to unpack .../libsamplerate0_0.1.8-8_arm64.deb ...
Unpacking libsamplerate0:arm64 (0.1.8-8) ...
Selecting previously unselected package alsa-utils.
Preparing to unpack .../alsa-utils_1.0.28-1_arm64.deb ...
Unpacking alsa-utils (1.0.28-1) ...
Processing triggers for systemd (215-17+deb8u5) ...
Setting up alsa-base (1.0.27+1) ...
Setting up libasound2-data (1.0.28-1) ...
Setting up libasound2:arm64 (1.0.28-1) ...
Setting up libsamplerate0:arm64 (0.1.8-8) ...
Setting up alsa-utils (1.0.28-1) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
Processing triggers for systemd (215-17+deb8u5) ...

 DietPi-Set_Hardware
─────────────────────────────────────────────────────
 Mode: soundcard (none)
 Please wait...

 [Ok] soundcard none | Completed


 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

 [Ok] cron


 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Install software
 Please wait...

 SqueezeBox: logitech media server (lms)
 [Info] Please wait...

 #               processing | D i e t  P i             #

 [Info] Testing connection to http://dietpi.com/downloads/binaries/all/logitechmediaserver_7.9.0_all.deb
 [Info] Max duration of 20 seconds, please wait...
 [Ok] Connection test | Completed

--2016-12-27 17:47:19--  http://dietpi.com/downloads/binaries/all/logitechmediaserver_7.9.0_all.deb
Resolving dietpi.com (dietpi.com)... 185.101.92.145
Connecting to dietpi.com (dietpi.com)|185.101.92.145|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133997278 (128M) [application/x-debian-package]
Saving to: ‘package.deb’

package.deb                                                 100%[==========================================================================================================================================>] 127.79M   235KB/s   in 13m 51ss

2016-12-27 18:01:11 (157 KB/s) - ‘package.deb’ saved [133997278/133997278]

Selecting previously unselected package logitechmediaserver.
(Reading database ... 16410 files and directories currently installed.)
Preparing to unpack package.deb ...
Unpacking logitechmediaserver (7.9.0~1451894331) ...
Setting up logitechmediaserver (7.9.0~1451894331) ...
Adding system user `squeezeboxserver' (UID 105) ...
Adding new user `squeezeboxserver' (UID 105) with group `nogroup' ...
Not creating home directory `/usr/share/squeezeboxserver'.
Processing triggers for systemd (215-17+deb8u5) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libencode-locale-perl libfile-listing-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libio-html-perl libio-socket-ssl-perl
  liblwp-mediatypes-perl liblwp-protocol-https-perl libnet-http-perl libnet-ssleay-perl libtimedate-perl liburi-perl libwww-perl libwww-robotrules-perl
Suggested packages:
  libdata-dump-perl libcrypt-ssleay-perl libauthen-ntlm-perl
Recommended packages:
  libhtml-format-perl libhtml-form-perl libhttp-daemon-perl libmailtools-perl
The following NEW packages will be installed:
  libencode-locale-perl libfile-listing-perl libhtml-parser-perl libhtml-tagset-perl libhtml-tree-perl libhttp-cookies-perl libhttp-date-perl libhttp-message-perl libhttp-negotiate-perl libio-html-perl libio-socket-ssl-perl
  liblwp-mediatypes-perl liblwp-protocol-https-perl libnet-http-perl libnet-ssleay-perl libtimedate-perl liburi-perl libwww-perl libwww-robotrules-perl libxml-parser-perl
0 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,542 kB of archives.
After this operation, 4,490 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ jessie/main libencode-locale-perl all 1.03-1 [13.6 kB]
Get:2 http://ftp.debian.org/debian/ jessie/main libtimedate-perl all 2.3000-2 [42.2 kB]
Get:3 http://ftp.debian.org/debian/ jessie/main libhttp-date-perl all 6.02-1 [10.7 kB]
Get:4 http://ftp.debian.org/debian/ jessie/main libfile-listing-perl all 6.04-1 [10.3 kB]
Get:5 http://ftp.debian.org/debian/ jessie/main liburi-perl all 1.64-1 [95.5 kB]
Get:6 http://ftp.debian.org/debian/ jessie/main libhtml-tagset-perl all 3.20-2 [13.5 kB]
Get:7 http://ftp.debian.org/debian/ jessie/main libhtml-parser-perl arm64 3.71-1+b2 [106 kB]
Get:8 http://ftp.debian.org/debian/ jessie/main libhtml-tree-perl all 5.03-1 [210 kB]
Get:9 http://ftp.debian.org/debian/ jessie/main libio-html-perl all 1.001-1 [17.6 kB]
Get:10 http://ftp.debian.org/debian/ jessie/main liblwp-mediatypes-perl all 6.02-1 [22.1 kB]
Get:11 http://ftp.debian.org/debian/ jessie/main libhttp-message-perl all 6.06-1 [80.1 kB]
Get:12 http://ftp.debian.org/debian/ jessie/main libhttp-cookies-perl all 6.01-1 [17.4 kB]
Get:13 http://ftp.debian.org/debian/ jessie/main libhttp-negotiate-perl all 6.00-2 [13.6 kB]
Get:14 http://ftp.debian.org/debian/ jessie/main libnet-ssleay-perl arm64 1.65-1+deb8u1 [261 kB]                                                                                                                                            
Get:15 http://ftp.debian.org/debian/ jessie/main libio-socket-ssl-perl all 2.002-2+deb8u1 [172 kB]                                                                                                                                          
Get:16 http://ftp.debian.org/debian/ jessie/main libnet-http-perl all 6.07-1 [24.8 kB]                                                                                                                                                      
Get:17 http://ftp.debian.org/debian/ jessie/main libwww-robotrules-perl all 6.01-1 [14.3 kB]                                                                                                                                                
Get:18 http://ftp.debian.org/debian/ jessie/main libwww-perl all 6.08-1 [194 kB]                                                                                                                                                            
Get:19 http://ftp.debian.org/debian/ jessie/main liblwp-protocol-https-perl all 6.06-2 [9,582 B]                                                                                                                                            
Get:20 http://ftp.debian.org/debian/ jessie/main libxml-parser-perl arm64 2.41-3 [214 kB]                                                                                                                                                   
Fetched 1,542 kB in 11s (129 kB/s)                                                                                                                                                                                                          
Selecting previously unselected package libencode-locale-perl.
(Reading database ... 21205 files and directories currently installed.)
Preparing to unpack .../libencode-locale-perl_1.03-1_all.deb ...
Unpacking libencode-locale-perl (1.03-1) ...
Selecting previously unselected package libtimedate-perl.
Preparing to unpack .../libtimedate-perl_2.3000-2_all.deb ...
Unpacking libtimedate-perl (2.3000-2) ...
Selecting previously unselected package libhttp-date-perl.
Preparing to unpack .../libhttp-date-perl_6.02-1_all.deb ...
Unpacking libhttp-date-perl (6.02-1) ...
Selecting previously unselected package libfile-listing-perl.
Preparing to unpack .../libfile-listing-perl_6.04-1_all.deb ...
Unpacking libfile-listing-perl (6.04-1) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../liburi-perl_1.64-1_all.deb ...
Unpacking liburi-perl (1.64-1) ...
Selecting previously unselected package libhtml-tagset-perl.
Preparing to unpack .../libhtml-tagset-perl_3.20-2_all.deb ...
Unpacking libhtml-tagset-perl (3.20-2) ...
Selecting previously unselected package libhtml-parser-perl.
Preparing to unpack .../libhtml-parser-perl_3.71-1+b2_arm64.deb ...
Unpacking libhtml-parser-perl (3.71-1+b2) ...
Selecting previously unselected package libhtml-tree-perl.
Preparing to unpack .../libhtml-tree-perl_5.03-1_all.deb ...
Unpacking libhtml-tree-perl (5.03-1) ...
Selecting previously unselected package libio-html-perl.
Preparing to unpack .../libio-html-perl_1.001-1_all.deb ...
Unpacking libio-html-perl (1.001-1) ...
Selecting previously unselected package liblwp-mediatypes-perl.
Preparing to unpack .../liblwp-mediatypes-perl_6.02-1_all.deb ...
Unpacking liblwp-mediatypes-perl (6.02-1) ...
Selecting previously unselected package libhttp-message-perl.
Preparing to unpack .../libhttp-message-perl_6.06-1_all.deb ...
Unpacking libhttp-message-perl (6.06-1) ...
Selecting previously unselected package libhttp-cookies-perl.
Preparing to unpack .../libhttp-cookies-perl_6.01-1_all.deb ...
Unpacking libhttp-cookies-perl (6.01-1) ...
Selecting previously unselected package libhttp-negotiate-perl.
Preparing to unpack .../libhttp-negotiate-perl_6.00-2_all.deb ...
Unpacking libhttp-negotiate-perl (6.00-2) ...
Selecting previously unselected package libnet-ssleay-perl.
Preparing to unpack .../libnet-ssleay-perl_1.65-1+deb8u1_arm64.deb ...
Unpacking libnet-ssleay-perl (1.65-1+deb8u1) ...
Selecting previously unselected package libio-socket-ssl-perl.
Preparing to unpack .../libio-socket-ssl-perl_2.002-2+deb8u1_all.deb ...
Unpacking libio-socket-ssl-perl (2.002-2+deb8u1) ...
Selecting previously unselected package libnet-http-perl.
Preparing to unpack .../libnet-http-perl_6.07-1_all.deb ...
Unpacking libnet-http-perl (6.07-1) ...
Selecting previously unselected package libwww-robotrules-perl.
Preparing to unpack .../libwww-robotrules-perl_6.01-1_all.deb ...
Unpacking libwww-robotrules-perl (6.01-1) ...
Selecting previously unselected package libwww-perl.
Preparing to unpack .../libwww-perl_6.08-1_all.deb ...
Unpacking libwww-perl (6.08-1) ...
Selecting previously unselected package liblwp-protocol-https-perl.
Preparing to unpack .../liblwp-protocol-https-perl_6.06-2_all.deb ...
Unpacking liblwp-protocol-https-perl (6.06-2) ...
Selecting previously unselected package libxml-parser-perl.
Preparing to unpack .../libxml-parser-perl_2.41-3_arm64.deb ...
Unpacking libxml-parser-perl (2.41-3) ...
Setting up libencode-locale-perl (1.03-1) ...
Setting up libtimedate-perl (2.3000-2) ...
Setting up libhttp-date-perl (6.02-1) ...
Setting up libfile-listing-perl (6.04-1) ...
Setting up liburi-perl (1.64-1) ...
Setting up libhtml-tagset-perl (3.20-2) ...
Setting up libhtml-parser-perl (3.71-1+b2) ...
Setting up libhtml-tree-perl (5.03-1) ...
Setting up libio-html-perl (1.001-1) ...
Setting up liblwp-mediatypes-perl (6.02-1) ...
Setting up libhttp-message-perl (6.06-1) ...
Setting up libhttp-cookies-perl (6.01-1) ...
Setting up libhttp-negotiate-perl (6.00-2) ...
Setting up libnet-ssleay-perl (1.65-1+deb8u1) ...
Setting up libio-socket-ssl-perl (2.002-2+deb8u1) ...
Setting up libnet-http-perl (6.07-1) ...
Setting up libwww-robotrules-perl (6.01-1) ...
Setting up libwww-perl (6.08-1) ...
Setting up liblwp-protocol-https-perl (6.06-2) ...
Setting up libxml-parser-perl (2.41-3) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libjpeg62-turbo-dev : Depends: libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.
 [Failed] The apt cache may be corrupt, apt mirror offline, or you have held broken pacakages. DietPi-Software will now exit.

 [Info] Please try:
 [Info] - Fixing apt package errors with 'apt-get install -f'
 [Info] - Change apt mirror: 'dietpi-config' > 'Networking: NAS/MISC' > 'Apt Mirror'
 [Info] - Clear and refresh apt 'apt-get update'
 [Info] - If problems persist, please create a Git ticket so DietPi can investigate the issue:
 - https://github.com/Fourdee/DietPi/issues`

Just tried a clean install for the 3rd time.  Could you explain how you installed?

**Comment by audiomuze** [comment]
`# apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`


Are we working off the same build?

**Comment by Fourdee** [comment]
@audiomuze 

> Are we working off the same build?

Yes.

Try fixing the broken packages and deps with:
```
apt-get install -f
```

**Comment by audiomuze** [comment]
Will do.

Your install works out the box?

**Comment by audiomuze** [comment]
```
# apt-get install -f zlib1g-dev libjpeg-dev libpng-dev libjpeg62-turbo-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libjpeg62-turbo-dev : Depends: libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.

```

**Comment by audiomuze** [comment]
```
# apt-get install -f build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:4.9.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by Fourdee** [comment]
@audiomuze 
Please run and paste results if any errors:
```
apt-get install libc6-dev g++ build-essential
```

**Comment by Fourdee** [comment]
@audiomuze 
Could you also please send us a bug report, I'd like to check system setup and installed software:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=499#p2184

**Comment by Fourdee** [comment]
Notes: 
- Also report by another user:
http://dietpi.com/phpbb/viewtopic.php?f=11&t=1109#p4662
Reference CODE: f1ac5977-f26c-45f4-9eff-668573de4827-0
- Check for installed software that may be conflicting repos and packages.

```
	Line 1: aSOFTWARE_INSTALL_STATE[0]=2
	Line 6: aSOFTWARE_INSTALL_STATE[5]=2
	Line 7: aSOFTWARE_INSTALL_STATE[6]=2
	Line 32: aSOFTWARE_INSTALL_STATE[31]=2 #kodi
	Line 104: aSOFTWARE_INSTALL_STATE[103]=2 #ramlog
	Line 106: aSOFTWARE_INSTALL_STATE[105]=2 #OpenSSH server
```

**Comment by Fourdee** [comment]
Impossible package version situation with ```libc6``` and ```libc6-dev```:
```
libc6-dev : Depends: libc6 (= 2.19-18+deb8u6) but 2.19-18+deb8u7 is to be installed
```

cause, CPAN prereqs:
```
root@DietPi:~# apt-get install zlib1g-dev libjpeg-dev libpng-dev libjpeg62-turbo-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libjpeg62-turbo-dev : Depends: libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.
```

```
root@DietPi:~# apt-get install zlib1g-dev libjpeg-dev libpng-dev libjpeg62-turbo-dev libc6-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.19-18+deb8u6) but 2.19-18+deb8u7 is to be installed
E: Unable to correct problems, you have held broken packages.

```

Its not specific to any repos we are using, including backports:
```
rm /etc/apt/sources.list.d/*
# remove of backports /etc/apt/sources.list
apt-get update
#same results
```

**Comment by Fourdee** [comment]
- 🈯️ Attempt force install of request u6 package for libc6
```
wget http://ftp.debian.org/debian/pool/main/g/glibc/libc6_2.19-18+deb8u6_arm64.deb -O package.deb
dpkg -i package.deb
rm package.deb
```

Ok, so this has occurred previously with libc6 and u6/u7 version situations:
https://github.com/Fourdee/DietPi/issues/653

We need to find where ```libc6:arm64 2.19-18+deb8u7``` is being installed from.
```
root@DietPi:~# apt-cache policy libc6
libc6:
  Installed: 2.19-18+deb8u7
  Candidate: 2.19-18+deb8u7
  Version table:
 *** 2.19-18+deb8u7 0
        100 /var/lib/dpkg/status
     2.19-18+deb8u6 0
        500 http://ftp.debian.org/debian/ jessie/main arm64 Packages
     2.19-18+deb8u3 0
        500 http://security.debian.org/ jessie/updates/main arm64 Packages
```

Ok, so we patched a install of ```u6``` in DietPi v140. But, only for existing installations. ~~Possible ```u7``` exists on Meveric's original image~~ Ours only. So we need to patch for fresh installations aswell.

**Comment by Fourdee** [comment]
@audiomuze 
As a temp fix for this run these commands: https://github.com/Fourdee/DietPi/issues/663#issuecomment-269865721

Then reinstall LMS with:
```
dietpi-software install 35
```

**Comment by Fourdee** [comment]
Nudged existing v140 patch for libc6, moved to v141 patch. Now applies to all installations (fresh and existing).

Resolved for v141

**Comment by Fourdee** [comment]
🈯️ Tested with fresh install of C2
