### ISSUE TITLE
Enable wildcards for dietpi-letsencrypt

### ISSUE THREAD

**Issue by DarrenSchwartz** [MichaIng/DietPi#6633]
#### Is your feature request related to a problem? Please describe:

- dietpi-letsencrypt throws an error when requesting a wildcard certificate like *.example.com.

#### Describe the solution you'd like:

- Should be able to get a cert for *.example.com.

#### Describe alternatives you've considered:

- ...

#### Additional context

![2023-09-23 13_32_01 Clipboard](https://github.com/MichaIng/DietPi/assets/33355526/8170968a-379b-4d35-8378-c7bef9614e10)

**Comment by MichaIng** [comment]
Wildcard certificates are generally supported via DNS authentication only, not via webroot/webserver based authentication, as Let's Encrypt cannot test whether ALL possible subdomains really are controlled by you. This again requires additional packages/plugins to be installed, and every DNS provider has its own plugin which works a little different.

Here is the documentation about this: https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins

As there is no generic method for this, it is hard or practically impossible to reasonably implement this into DietPi-LetsEncrypt. What you can do for now is adding all subdomains space-separated.

**Comment by DarrenSchwartz** [comment]
Yeah, you're right. Thanks for the docs and the explanation.
