### ISSUE TITLE
DietPi-Software | AUTO_Global_Password= not being used as MySQL login password for SQL DB generation

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#666]
When installing Nextcloud via dietpi.txt utilizing the global password setting causes a bug. When viewing the web interface for the first time with Nextcloud where you would use admin and the global password Nextcloud asks for the database to be set up. This should already be done and is not included in the instructions on dietpi.com to do so.
I followed the instructions using a password for the global password that excludes the following characters \"$

An example of the password I used
45nau@55q3J%44^ayr6#354hyt5n^oy2.Nnim^ByZhy

Backend: Nginx 
Device: Odroid XU4

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks for report 👍, i'll take a look

Linked for reference: https://github.com/Fourdee/DietPi/issues/647#issuecomment-267019815

> 45nau@55q3J%44^ayr6#354hyt5n^oy2.Nnim^ByZhy

I think some of these may be breaking the string sent to command line and sql DB generation func (https://github.com/Fourdee/DietPi/blob/master/dietpi/func/create_mysql_db#L34), and/or, we need to string ```$DATABASE_PW``` lemme test.

**Comment by Fourdee** [comment]
@LexiconCode 

Turns out, this effects all programs with SQL DB generation, when a custom password is used. Lets gets this fixed.

**Comment by Fourdee** [comment]
Tested with password provided by @LexiconCode:
- 🈯️ 

```
root@DietPi:~# cat /DietPi/dietpi.txt | grep Global
#Global Password to be applied for the system
AUTO_Global_Password=45nau@55q3J%44^ayr6#354hyt5n^oy2.Nnim^ByZhy
```
```
dietpi-software install 114
```

```
[Info] Creating MySql DB for nextcloud

 [Ok] Create database nextcloud | Completed

Nextcloud is not installed - only a limited number of commands are available
Nextcloud was successfully installed
```

Completed. Fixed for v141.

**Comment by LexiconCode** [comment]
Originally what password was being used? or did the DB Set up fail?

**Comment by Fourdee** [comment]
@LexiconCode 

> Originally what password was being used? or did the DB Set up fail?

DB creation was set to use ```dietpi``` as the MySQL root account, instead of ```AUTO_Global_Password=```. Which was incorrect.
