### ISSUE TITLE
DietPi-Software | Immich -  Self-Hosted backuo solution for photos and videos 

### ISSUE THREAD

**Issue by byalvaroft** [MichaIng/DietPi#6685]
#### Formal software information

- Software title | Immich
- Short description | A self-hosted backup solution for photos and videos
- Official URL | [[https://immich.app/](https://immich.app/)]
- GitHub URL | [[https://github.com/immich-app/immich/](https://github.com/immich-app/immich)]
- (Official) install documentation | [[https://documentation.immich.app/](https://documentation.immich.app/)]
- Live Demo | [[https://demo.immich.app/auth/login/](https://demo.immich.app/auth/login/)]

#### Are there similar/alternative software titles available with DietPi-Software?
- Yes, there are some alternatives such as ownCloud, Nextcloud, and Syncthing.

#### What makes your requested software better than the above solutions, if available?
- Immich is designed specifically for photo and video backup, with features such as face recognition, object detection, geolocation, and timeline view. It also supports offline and untracked files management, which allows you to delete or move files from your device without affecting the backup. Immich has a user-friendly interface that resembles Google Photos, and it offers mobile apps for Android and iOS devices.

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
- According to the official install documentation, there are several steps to install Immich on a Linux server, such as installing Docker, setting up environment variables, creating a PostgreSQL database, configuring Nginx, and running the Immich containers. DietPi could automate these steps, which would save end users a lot of time and hassle. DietPi could also provide an option to choose the storage location for the backup files, and integrate Immich with other DietPi services such as DietPi-Backup or DietPi-Drive_Manager.

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

There is several installation methods: https://immich.app/docs/install/requirements, but they usually require some tinkering because or the arm64 v8, the easiest would be using this script:

curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash

The script will perform the following actions:

Download [docker-compose.yml](https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml), and the [.env](https://github.com/immich-app/immich/releases/latest/download/example.env) file from the main branch of the [repository](https://github.com/immich-app/immich).
Populate the .env file with necessary information based on the current directory path.
Start the containers.

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
- Sorry, I do not have the required skills to maintain the software installation. I hope someone else can help with this.

**Comment by t-bullock** [comment]
Can this be moved to discussions so it can be voted on? Would love to see immich get added to dietpi. Thank you!
