### ISSUE TITLE
tailscale

### ISSUE THREAD

**Issue by jowtron** [MichaIng/DietPi#6692]
#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=22
G_DIETPI_VERSION_RC=3
G_GITBRANCH='master'
G_GITOWNER='MichaIng'`
- Distro version | `bookworm 0`
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- SBC model | `RPi Zero 2 W (aarch64)`
- Power supply used | (EG: 5V 1A RAVpower)
- SD card used | (SanDisk ultra)

#### Additional Information (if applicable)
- Software title | Tailscale
- fresh install
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. ...install tailscale, run tailscale up
2. ...

#### Expected behaviour

- ...should give a web address to connect to your tailnet

#### Actual behaviour

- ...failed to connect to local tailscaled (which appears to be running as tailscaled, pid 6844). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; systemd tailscaled.service not running. Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

#### Extra details

- ... It works after installing iptables by running "sudo apt-get install iptables"
- So I think iptables should be made a dependancy for tailscale?

**Comment by Joulinar** [comment]
See her: https://github.com/MichaIng/DietPi/issues/6649

Tailscale guys will change the bahovior on an upcomming release https://github.com/MichaIng/DietPi/issues/6649#issuecomment-1746982003
