### ISSUE TITLE
DietPi-Software | Sonarr: Install fails with DietPi v8.23

### ISSUE THREAD

**Issue by TheGitGuy007** [MichaIng/DietPi#6699]
#### Details:
- Date           | Sun Oct 22 03:53:29 BST 2023
- DietPi version | v8.23.3 (MichaIng/master)
- Image creator  |
- Pre-image      |
- Hardware       | Native PC (x86_64) (ID=21)
- Kernel version | `Linux DietPi 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux`
- Distro         | bookworm (ID=7)
- Command        | `curl -ILfvm 10 https://keyserver.ubuntu.com/pks/lookup?search=0x2009837CBFFD68F45BC180471F4F90DE2A9B4BF8&op=get`
- Exit code      | 22
- Software title | DietPi-Software
#### Steps to reproduce:

1. ... Install Sonarr 
2. ...
#### Expected behaviour:

- ... Sonarr  to be installed
#### Actual behaviour:

- ... Unable to find file/key.
#### Extra details:

- ...
#### Additional logs:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
```

Seems to be a invalid link here
![image](https://github.com/MichaIng/DietPi/assets/63202413/fabf32fc-976e-4b79-9542-1315114a468a)

Command: curl -ILfvm 10 https://keyserver.ubuntu.com/pks/lookup?search=0x2009837CBFFD68F45BC180471F4F90DE

**Comment by Joulinar** [comment]
I had a look, and it seems `curl` is returning a HTTP 405 error. Something we need to have a look into

```
< HTTP/1.1 405 Method Not Allowed
HTTP/1.1 405 Method Not Allowed
```

However, you can also skip this step to work around the problem. If you have run the installation process and the error screen is displayed, you should have an option to change the command. Select this option and remove the entire command specified. Replace it with `true` and continue.

**Comment by MichaIng** [comment]
The keyserver does not allow HEAD requests (the `-I` flag of `curl`), only GET (regular download). So we must remove the URL check. I haven't seen such case for a very long time.

Fixed with: https://github.com/MichaIng/DietPi/commit/c309978

I'll add a live patch as well.

**Comment by MichaIng** [comment]
Live patch merged. Should be offered when running `dietpi-update`.
