### ISSUE TITLE
DietPi-Software | PIXEL

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#670]
> https://twitter.com/PKTwook/status/812782631028981760

https://www.raspberrypi.org/blog/introducing-pixel/

RPi modified desktop, for all devices, including RPi.
- Is it possible?
- Is it "allowed" by RPi, to distribute on other devices?

**Comment by xenfomation** [comment]
It is possible and as I have this running in a local VM, I'll find the packages required and post you in 48 hours!

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by unclehowell** [comment]
Can we re-open this. Why not have PIXEL with Dietpi-Pi? What's the issue?
