### ISSUE TITLE
during update.. - DietPi has encountered an error                                   -

### ISSUE THREAD

**Issue by muppetlabs999** [MichaIng/DietPi#6728]
#### Details:
- Date           | Fri Nov  3 07:31:42 CET 2023
- DietPi version | v8.21.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | Native PC (x86_64) (ID=21)
- Kernel version | `Linux DietPi 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux`
- Distro         | bookworm (ID=7)
- Command        | `ping -6nc 1 -W 10 2620:fe::fe`
- Exit code      | 1
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
PING 2620:fe::fe(2620:fe::fe) 56 data bytes

--- 2620:fe::fe ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

**Comment by Joulinar** [comment]
Looks like IPv6 is not working within your network. Pls disable IPv6 and try again

**Comment by MichaIng** [comment]
Or retry it 1-2 times first, right from the error handler. Might be a temporarily network issue as well.

**Comment by MichaIng** [comment]
I guess it solved itself? I'll mark the issue as closed. Feel free to reopen if required.
