### ISSUE TITLE
DietPi-Configuration | Addition of 'index's ID's:user' as in Dietpi.txt dev settings.

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#673]
At the moment we have a very useful feature AUTO Dietpi Software Install feature.  For simplicity sake majority of the programs are installed by root with a global password and then run as root.  The exceptions are those that use a script to create user and run as then run the software as that user. I would like begin testing each install which each software is running its unique user. 

I propose the addition which can be under # D I E T - P I - Dev settings. That allows us to pair index's (ID's):users. This is meant for testing purposes only to work through each software in dietpi. So that each software runs as its unique user. This will allow me to go through each program to test for permissions issues.  

In the event there is a better method to test feel free to chime in.

**Comment by Fourdee** [comment]
Marking as closed due to no progress/lack of interest from our community.
