### ISSUE TITLE
Shairport-Sync (airplay 2) Failing 

### ISSUE THREAD

**Issue by vishnusure** [MichaIng/DietPi#6735]
#### Details:
- Date           | Tue Nov  7 20:52:21 GMT 2023
- Bug report     | 924046ed-3458-4290-8ee4-edaea6b732fa
- DietPi version | v8.23.3 (MichaIng/master)
- Image creator  |
- Pre-image      |
- Hardware       | RPi 3 Model B (aarch64) (ID=3)
- Kernel version | `Linux FamilyRoom 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `systemctl stop shairport-sync`
- Exit code      | 5
- Software title | DietPi-Software

#### Steps to reproduce:

1. ...Select USB Soundcard from dietpi-config
2. ...Install Shairport-Sync (Airplay 2) from dietpi-software, the installation fails with the error when executing systemctl stop shairport-syncshairport-sync

#### Expected behaviour:

Shairport-sync (airplay 2 should install sucessfully)
- ...

#### Actual behaviour:

- ... the installation fails with the error when executing systemctl stop shairport-sync

#### Extra details:

- ...

#### Additional logs:
```
Failed to stop shairport-sync.service: Unit shairport-sync.service not loaded.
```

**Comment by vishnusure** [comment]
**Issue Resolved**

**My System Details**

- DietPi version | v8.23.3 (MichaIng/master)
- Image creator |
- Pre-image |
- Hardware | RPi 3 Model B (aarch64) (ID=3)
- Kernel version | Linux FamilyRoom 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
- Distro | bookworm (ID=7,RASPBIAN=0)

**Issue 1**

1. shairport-sync (airplay 2) was failing after a fresh install of DietPi on My Raspberry Pi 3.

2. Upon further investigating found that nqptp is failing with the below error:

nqptp.service: Failed to determine user credentials: No such process
nqptp.service: Failed at step USER spawning /usr/local/bin/nqptp: No such process

3. Versions that came up with fresh install are:

nqptp -V
Version: 1.2.5-dev-10-gcfa8315. Shared Memory Interface Version: smi10.

shairport-sync -V
4.3.2-AirPlay2-smi10-OpenSSL-Avahi-ALSA-stdout-pipe-soxr-metadata-mqtt-dbus-mpris-sysconfdir:/usr/local/etc

**Solution**

1. Stop avahi-daemon, nqptp and shairport-sync services as below:

systemctl status nqptp
systemctl status shairport-sync.service
systemctl status avahi-daemon

2. Type dietpi-software and use the GUI to uninstall avahi-daemon and shairport-sync.service

3. Remove old files of nqptp as per below: 

4. Type the below comand to find the location of nqptp
which nqptp
it should be installed at /usr/local/bin/nqptp. Remove it using the below commands

# rm /lib/systemd/system/nqptp.service
# rm /usr/local/bin/nqptp
# systemctl daemon-reload

5. Build and Install both nqptp and shairport-sync manually as per below link:
https://github.com/mikebrady/shairport-sync/blob/master/BUILD.md

The issue seems to be some version mismatch in the dependencies installed for nqptp. Remember nqptp is installed automatically when we use dietpi-software to install shairport-sync (airplay 2 dev version)

**Comment by MichaIng** [comment]
Many thanks for reporting. Found it: The the NQPTP services runs now as `nqptp` user, which needs to be created: https://github.com/mikebrady/nqptp/commit/10969ea#diff-02c897cd7f1fe318c2321b0937845d24f6019eef8147ede65378b674044a96f9

**Comment by vishnusure** [comment]
Wonderful ! So no longer the issue occurrs when we install shairport through diet pi software after the new builds are implemented ?

**Comment by MichaIng** [comment]
Jep. Since your custom build implied the user creation as well, you could even just reinstall Shairport Sync now and it won't run into the error anymore. For everyone else:
```sh
useradd -rMU -d /nonexistent -s /usr/sbin/nologin nqptp
```

**Comment by vishnusure** [comment]
Wonderfully, thanks for identifying and fixing it so quickly

**Comment by MichaIng** [comment]
New packages have been installed on the server.
