### ISSUE TITLE
Can not install OpenVPN

### ISSUE THREAD

**Issue by onurcoskun14** [MichaIng/DietPi#6738]
#### Required Information
- DietPi version | 8
- Distro version | bookworm
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 `
- SBC model | Rpi 4
- Power supply used | 5v 3a
- SD card used | SanDisk ultra

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
- Was the software title installed freshly or updated/migrated?
- Can this issue be replicated on a fresh installation of DietPi?

- Bug report ID | 74e387cb-e091-4c9c-b10b-89170b43e8f8

#### Steps to reproduce

1. sudo apt-get install openvpn

#### Expected behaviour

- should install openvpn

#### Actual behaviour

- lzma_read: Read error(10)

#### Extra details

- ...

**Comment by Joulinar** [comment]
can you share whole output of

**Comment by onurcoskun14** [comment]
![image](https://github.com/MichaIng/DietPi/assets/117642438/49e801c8-9569-49a2-9907-a14468b29838)

**Comment by MichaIng** [comment]
Looks like the xz-compressed lists (or one of them) is broken, or the extractor. Try this:
```sh
/boot/dietpi/func/dietpi-set_software apt clean
apt update
```

**Comment by onurcoskun14** [comment]
Worked thanks.
