### ISSUE TITLE
I can't install Radarr anymore.

### ISSUE THREAD

**Issue by sagecandida** [MichaIng/DietPi#6748]
#### Details:
- Date           | Mon Nov 13 20:10:34 CET 2023
- DietPi version | v8.23.3 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi Zero 2 W (armv7l) (ID=3)
- Kernel version | `Linux DietPi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=1)
- Command        | `tar xf Radarr.master.5.1.3.8246.linux-core-arm.tar.gz`
- Exit code      | 2
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```

```

**Comment by MichaIng** [comment]
I just tried it here, and it works well.

Probably the download was corrupt. Can you retry it? If it fails again at the same point, are there some logs given on the error handler, or after exiting the script?

**Comment by sagecandida** [comment]
![Screenshot from 2023-11-13 21-28-27](https://github.com/MichaIng/DietPi/assets/73594748/7b76a8f8-cc9f-429b-8b3b-152383989c14)

![Screenshot from 2023-11-13 21-30-03](https://github.com/MichaIng/DietPi/assets/73594748/b9d6b49e-122f-446d-950e-7eec532116e7)

I tried again and still doesn't work.

**Comment by sagecandida** [comment]
I tried updating to beta version to see if it works on beta but not a chance.

**Comment by MichaIng** [comment]
Hmm, strange, no logs at all. Can you try this manually:
```sh
cd /tmp
curl -fLO 'https://github.com/Radarr/Radarr/releases/download/v5.1.3.8246/Radarr.master.5.1.3.8246.linux-core-arm.tar.gz'
tar xf Radarr.master.5.1.3.8246.linux-core-arm.tar.gz
ls -l Radarr
```

**Comment by sagecandida** [comment]
root@DietPi:/tmp# tar xf Radarr.master.5.1.3.8246.linux-core-arm.tar.gz
tar: Radarr/libcoreclr.so: Wrote only 5120 of 10240 bytes
tar: Radarr/Instances.dll: Cannot write: No space left on device
tar: Radarr/System.Reflection.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.FileProviders.Physical.dll: Cannot write: No space left on device
tar: Radarr/ICSharpCode.SharpZipLib.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Pipes.AccessControl.dll: Cannot write: No space left on device
tar: Radarr/System.Text.Encoding.Extensions.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Authorization.Policy.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Mvc.Core.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Hosting.WindowsServices.dll: Cannot write: No space left on device
tar: Radarr/System.Security.Principal.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Compression.Brotli.dll: Cannot write: No space left on device
tar: Radarr/System.Private.CoreLib.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.SqlServer.dll: Cannot write: No space left on device
tar: Radarr/BouncyCastle.Crypto.dll: Cannot write: No space left on device
tar: Radarr/libSystem.Native.so: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Logging.Debug.dll: Cannot write: No space left on device
tar: Radarr/System.Private.Xml.Linq.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.IdentityModel.Logging.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Caching.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Localization.Routing.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.Serialization.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Http.dll: Cannot write: No space left on device
tar: Radarr/System.Data.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.InteropServices.RuntimeInformation.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Http.Results.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.VisualBasic.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Configuration.Binder.dll: Cannot write: No space left on device
tar: Radarr/System.Drawing.Primitives.dll: Cannot write: No space left on device
tar: Radarr/Diacritical.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.SignalR.Core.dll: Cannot write: No space left on device
tar: Radarr/System.Net.WebSockets.Client.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Identity.Stores.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Compression.FileSystem.dll: Cannot write: No space left on device
tar: Radarr/System.Diagnostics.FileVersionInfo.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Hosting.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Primitives.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Hosting.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Data.SqlClient.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Win32.Primitives.dll: Cannot write: No space left on device
tar: Radarr/System.Security.Cryptography.Xml.dll: Cannot write: No space left on device
tar: Radarr/System.ComponentModel.DataAnnotations.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Components.Web.dll: Cannot write: No space left on device
tar: Radarr/DryIoc.dll: Cannot write: No space left on device
tar: Radarr/System.Xml.XDocument.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.WebSockets.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.HttpOverrides.dll: Cannot write: No space left on device
tar: Radarr/System.Net.WebProxy.dll: Cannot write: No space left on device
tar: Radarr/UI/420-de64e22271b9062a68e8.js: Cannot write: No space left on device
tar: Radarr/UI/login.html: Cannot write: No space left on device
tar: Radarr/UI/189-384f51e46762242ce177.js.map: Cannot write: No space left on device
tar: Radarr/UI/420-de64e22271b9062a68e8.js.LICENSE.txt: Cannot write: No space left on device
tar: Radarr/UI/420-de64e22271b9062a68e8.js.map: Cannot write: No space left on device
tar: Radarr/UI/index-f281bf95d8dab4159671.js.map: Cannot write: No space left on device
tar: Radarr/UI/oauth.html: Cannot write: No space left on device
tar: Radarr/UI/index.html: Cannot write: No space left on device
tar: Radarr/UI/index-f281bf95d8dab4159671.js: Cannot write: No space left on device
tar: Radarr/UI/Content/189-59ceffe4140b5e6e5bf7.css: Cannot write: No space left on device
tar: Radarr/UI/Content/189-59ceffe4140b5e6e5bf7.css.map: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/logo.svg: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/logo-full.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/logo-radarr.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/logo-lidarr.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon-16x16.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/mstile-310x150.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/manifest.json: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/android-chrome-192x192.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/mstile-150x150.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon.ico: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/mstile-144x144.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon-32x32.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon-debug-32x32.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon-debug.ico: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/logo-readarr.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/apple-touch-icon.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/favicon-debug-16x16.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/mstile-70x70.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/mstile-310x310.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/browserconfig.xml: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/logo-prowlarr.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/safari-pinned-tab.svg: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/logo-sonarr.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/Icons/android-chrome-512x512.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/poster-dark.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/404.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/logo.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Images/error.png: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/text-security-disc.woff: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Regular.woff2: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Light.woff: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/UbuntuMono-Regular.ttf: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Regular.woff: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Light.ttf: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/UbuntuMono-Regular.woff: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Regular.ttf: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/Roboto-Light.woff2: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/text-security-disc.ttf: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/UbuntuMono-Regular.eot: Cannot write: No space left on device
tar: Radarr/UI/Content/Fonts/fonts.css: Cannot write: No space left on device
tar: Radarr/UI/Content/robots.txt: Cannot write: No space left on device
tar: Radarr/UI/Content/styles.css.map: Cannot write: No space left on device
tar: Radarr/UI/Content/styles.css: Cannot write: No space left on device
tar: Radarr/UI/189-384f51e46762242ce177.js: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Logging.EventLog.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.ResponseCaching.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/System.Net.Requests.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Http.Features.dll: Cannot write: No space left on device
tar: Radarr/System.Reflection.TypeExtensions.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.Caching.dll: Cannot write: No space left on device
tar: Radarr/de-DE/FluentMigrator.Abstractions.resources.dll: Cannot write: No space left on device
tar: Radarr/System.Collections.NonGeneric.dll: Cannot write: No space left on device
tar: Radarr/libhostpolicy.so: Cannot write: No space left on device
tar: Radarr/Radarr.Http.deps.json: Cannot write: No space left on device
tar: Radarr/System.Resources.Reader.dll: Cannot write: No space left on device
tar: Radarr/System.Security.Cryptography.X509Certificates.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Logging.TraceSource.dll: Cannot write: No space left on device
tar: Radarr/System.ValueTuple.dll: Cannot write: No space left on device
tar: Radarr/Mono.Nat.dll: Cannot write: No space left on device
tar: Radarr/System.Threading.Channels.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.CompilerServices.VisualC.dll: Cannot write: No space left on device
tar: Radarr/Localization/Core/ja.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/cs.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/hr.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/es.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/vi.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ar.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/fa.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/it.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/tr.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/hi.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ta.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/hu.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ro.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/zh_TW.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/bn.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/en.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/th.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/lv.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/fi.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/et.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ca.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ru.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/he.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/nb_NO.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/pt_BR.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/ko.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/es_MX.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/nl.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/el.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/pl.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/id.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/sv.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/sk.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/zh_CN.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/lt.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/sr.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/pt.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/da.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/de.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/fr.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/bg.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/bs.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/is.json: Cannot write: No space left on device
tar: Radarr/Localization/Core/uk.json: Cannot write: No space left on device
tar: Radarr/WindowsBase.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Caching.Memory.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Identity.Core.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.SqlAnywhere.dll: Cannot write: No space left on device
tar: Radarr/Radarr.Http.dll: Cannot write: No space left on device
tar: Radarr/System.Drawing.Common.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Mvc.DataAnnotations.dll: Cannot write: No space left on device
tar: Radarr/Dapper.dll: Cannot write: No space left on device
tar: Radarr/System.Xml.XPath.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.Numerics.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Extensions.Oracle.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Configuration.UserSecrets.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll: Cannot write: No space left on device
tar: Radarr/Radarr.Core.deps.json: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.CookiePolicy.dll: Cannot write: No space left on device
tar: Radarr/LICENSE: Cannot write: No space left on device
tar: Radarr/Polly.Contrib.WaitAndRetry.dll: Cannot write: No space left on device
tar: Radarr/System.Text.Encoding.CodePages.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll: Cannot write: No space left on device
tar: Radarr/libcoreclrtraceptprovider.so: Cannot write: No space left on device
tar: Radarr/System.Resources.Writer.dll: Cannot write: No space left on device
tar: Radarr/Dynamitey.dll: Cannot write: No space left on device
tar: Radarr/Radarr.SignalR.xml: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Session.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Diagnostics.HealthChecks.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Configuration.Xml.dll: Cannot write: No space left on device
tar: Radarr/libmscordbi.so: Cannot write: No space left on device
tar: Radarr/System.Buffers.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Configuration.Json.dll: Cannot write: No space left on device
tar: Radarr/System.Net.WebHeaderCollection.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Identity.dll: Cannot write: No space left on device
tar: Radarr/libSystem.Globalization.Native.so: Cannot write: No space left on device
tar: Radarr/Radarr.Common.pdb: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll: Cannot write: No space left on device
tar: Radarr/System.Net.Security.dll: Cannot write: No space left on device
tar: Radarr/System.Security.Principal.Windows.dll: Cannot write: No space left on device
tar: Radarr/System.Threading.ThreadPool.dll: Cannot write: No space left on device
tar: Radarr/MailKit.dll: Cannot write: No space left on device
tar: Radarr/System.Web.dll: Cannot write: No space left on device
tar: Radarr/System.Net.Primitives.dll: Cannot write: No space left on device
tar: Radarr/System.Reflection.Emit.Lightweight.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.Oracle.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.dll: Cannot write: No space left on device
tar: Radarr/System.Numerics.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.DependencyInjection.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/System.IO.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Pipes.dll: Cannot write: No space left on device
tar: Radarr/System.IO.MemoryMappedFiles.dll: Cannot write: No space left on device
tar: Radarr/ServiceInstall: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.SqlServerCe.dll: Cannot write: No space left on device
tar: Radarr/System.Web.HttpUtility.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Server.IIS.dll: Cannot write: No space left on device
tar: Radarr/System.Formats.Asn1.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Hosting.Abstractions.dll: Cannot write: No space left on device
tar: Radarr/System.Xml.XmlSerializer.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Diagnostics.dll: Cannot write: No space left on device
tar: Radarr/Radarr.Mono.deps.json: Cannot write: No space left on device
tar: Radarr/Swashbuckle.AspNetCore.SwaggerGen.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.Serialization.Json.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Mvc.ViewFeatures.dll: Cannot write: No space left on device
tar: Radarr/createdump: Cannot write: No space left on device
tar: Radarr/Microsoft.VisualBasic.Core.dll: Cannot write: No space left on device
tar: Radarr/System.Text.Encodings.Web.dll: Cannot write: No space left on device
tar: Radarr/System.Globalization.Calendars.dll: Cannot write: No space left on device
tar: Radarr/System.Console.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Win32.SystemEvents.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Compression.ZipFile.dll: Cannot write: No space left on device
tar: Radarr/FFMpegCore.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.JSInterop.dll: Cannot write: No space left on device
tar: Radarr/Radarr.SignalR.dll: Cannot write: No space left on device
tar: Radarr/System.Linq.Expressions.dll: Cannot write: No space left on device
tar: Radarr/System.IO.Pipelines.dll: Cannot write: No space left on device
tar: Radarr/System.ComponentModel.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.SignalR.Common.dll: Cannot write: No space left on device
tar: Radarr/Newtonsoft.Json.dll: Cannot write: No space left on device
tar: Radarr/libSystem.IO.Compression.Native.so: Cannot write: No space left on device
tar: Radarr/System.Reflection.DispatchProxy.dll: Cannot write: No space left on device
tar: Radarr/System.Runtime.InteropServices.dll: Cannot write: No space left on device
tar: Radarr/Radarr.Api.V3.deps.json: Cannot write: No space left on device
tar: Radarr/System.Net.NameResolution.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Mvc.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.Redshift.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.Configuration.KeyPerFile.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Runner.Core.dll: Cannot write: No space left on device
tar: Radarr/System.Xml.XPath.XDocument.dll: Cannot write: No space left on device
tar: Radarr/Npgsql.dll: Cannot write: No space left on device
tar: Radarr/Radarr.Host.xml: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Localization.dll: Cannot write: No space left on device
tar: Radarr/FluentMigrator.Extensions.SqlAnywhere.dll: Cannot write: No space left on device
tar: Radarr/MimeKit.dll: Cannot write: No space left on device
tar: Radarr/libSystem.Net.Security.Native.so: Cannot write: No space left on device
tar: Radarr/Radarr.Host.deps.json: Cannot write: No space left on device
tar: Radarr/System.Threading.Tasks.Extensions.dll: Cannot write: No space left on device
tar: Radarr/Mono.Posix.NETStandard.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.Extensions.FileProviders.Embedded.dll: Cannot write: No space left on device
tar: Radarr/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll: Cannot write: No space left on device
tar: Exiting with failure status due to previous errors

**Comment by sagecandida** [comment]
It must be something wrong because here is my disk usage
![Screenshot from 2023-11-13 22-09-54](https://github.com/MichaIng/DietPi/assets/73594748/402e0aff-3e4d-40a7-908f-65c74bbfb5c7)

**Comment by MichaIng** [comment]
I had such a feeling that insufficient memory is the reason on a 512 MiB RAM RPi. It is downloaded to and extracted within `/tmp`, which is a tmpfs (RAM disk). Please add a swap file:
```sh
/boot/dietpi/func/dietpi-set_swapfile 512
```
Theoretically you can remove it again afterwards
```sh
/boot/dietpi/func/dietpi-set_swapfile 0
```
But it does not hurt to leave it in place. Thanks to `swappiness=1` it is really only used if really needed. And Radarr alone already requires 200 MiB or so in idle. Now you want a download server on top, and both being active concurrently, that would not work with 475 MiB memory anyway.

**Comment by sagecandida** [comment]
It works now. Thank you! And yes, you are right. It's hard to make it work due to lack of memory but i still wanted to give it a try.

**Comment by MichaIng** [comment]
The swap file makes it possible, and I don't think that those additional memory is used too regularly to affect performance significantly. Probably good to keep an eye on `htop` or `free` by times to verify that. If it is more regularly used, keep in mind that a (heavily used) swap file on SD card is not only bad performance-wise, but also degrades it life time. Better to attach a USB stick/drive and put the swap file there, in this case.
