### ISSUE TITLE
General | Update DietPi images

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#676]
- 🈯️ XU4 | Possible corruption
- 🈯️ RPi | https://github.com/Fourdee/DietPi/issues/660

**Comment by LexiconCode** [comment]
Does that include a new kernel to allow full throughput of the Ethernet port?

**Comment by Fourdee** [comment]
@LexiconCode 

> Does that include a new kernel to allow full throughput of the Ethernet port?

Not yet. Last time i checked the 4.x kernel was still in devolpment for XU4 and unstable.

Seems there are still having teething issues with ```eth0``` failing:
: http://forum.odroid.com/viewtopic.php?f=95&t=18034&start=300

**Comment by Fourdee** [comment]
Ok images done and set live. Marking as closed.

@aliosa27
If you get a chance to update any images, please reopen as needed and let me know.
