### ISSUE TITLE
Error on update from DietPI v8.24.0 (dev) to v8.25.-1

### ISSUE THREAD

**Issue by rtglobal** [MichaIng/DietPi#6767]
#### Details:
- Date           | Mon Nov 20 21:11:18 CET 2023
- DietPi version | v8.24.0 (MichaIng/dev)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `apt-get -y --with-new-pkgs upgrade`
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

1. dietpi-update

#### Expected behaviour:

- The magical update process should run until the end without any error.  
#### Actual behaviour:

- The DietPi update process interrupts. All services (nextcloud, redis, influxdb, ...) are on stop.
#### Extra details:

- Bug-report ID = 6f733a96-c184-47d8-b4e2-7f3d35bdb963

#### Additional logs:

```
      Setting up raspi-firmware (1:1.20231024+ds-1+rpt2) ...
stat: cannot read file system information for '/boot/firmware': No such file or directory
Error: missing /boot/firmware, did you forget to mount it?
dpkg: error processing package raspi-firmware (--configure):
 installed raspi-firmware package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 raspi-firmware
E: Sub-process /usr/bin/dpkg returned an error code (1)
[FAILED] DietPi-Update | APT upgrade
```

Reading package lists...
```

**Comment by MichaIng** [comment]
Please see the pinned issue: #6747

And you seem to be on the DietPi `dev` branch. After you applied the workaround, I strongly recommend to switch to the stable `master` branch:
```sh
G_DEV_BRANCH master
```
