### ISSUE TITLE
Error updating with dietpi-update (8.23.3-->8.24)

### ISSUE THREAD

**Issue by robotwisdom** [MichaIng/DietPi#6773]
#### Details:
- Date           | Tue Nov 21 10:05:41 EST 2023
- DietPi version | v8.23.3 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `apt-get -y --with-new-pkgs upgrade`
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Reading package lists...
```

**Comment by MichaIng** [comment]
Please see the large amount of duplicates and the pinned issue 😄: #6747
