### ISSUE TITLE
DietPi-Software | Update Vaultwarden to v1.30.1

### ISSUE THREAD

**Issue by pdsakurai** [MichaIng/DietPi#6777]
Hi!

May I request to update the binaries of Vaultwarden in your server?

Vaultwarden has a [new release, v1.30.1](https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.1), containing the fix for auto-fill issue.

Thanks!

Regards,
Paul

**Comment by MichaIng** [comment]
Done, you can upgrade with a reinstall:
```sh
sudo dietpi-software reinstall 183
```

**Comment by pdsakurai** [comment]
Thank you! 😊

**Comment by JappeHallunken** [comment]
JFYI:
it get's now updated via apt, directly from dietpi repos
```
root@RPi4:~# apt upgrade
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Paketaktualisierung (Upgrade) wird berechnet… Fertig
Die folgenden Pakete werden aktualisiert (Upgrade):
  vaultwarden
1 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 12,0 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 594 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] J
Holen:1 https://dietpi.com/apt bookworm/main arm64 vaultwarden arm64 1.31.0-dietpi1 [12,0 MB]
```
❤️

**Comment by MichaIng** [comment]
Yes, this has become much easier 🙂.

**Comment by yuukiAme** [comment]
Because of the newest update v1.32 from [Vaultwarden](https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.0).
I tried using `dietpi-software reinstall 183` and `apt update` but my Vaultwarden is not the latest version.

Screenshot here
![2024_08_12_11_33_04_firefox](https://github.com/user-attachments/assets/21d20904-69f0-4743-9c36-31480630f07d)

and from release notes

```
Other changes

- Updated web-vault to v2024.6.2

```

**Comment by MichaIng** [comment]
Done. vaultwarden can be updated easier in the meantime, since we ship it with our APT server:
```sh
apt update
apt install vaultwarden
```
I just updated our docs accordingly (not yet released to live docs).

**Comment by MichaIng** [comment]
I know, just need to wait for new DietPi image builds to finish, before we can trigger new vaultwarden builds.
