### ISSUE TITLE
DietPi-Software | UrBackup Client

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#678]
https://www.urbackup.org/download.html#linux_all_binary

Binary Linux client (command line only; with auto-update; x86/AMD64/ARMv6+/ARM64)
Only this Linux client is auto-updated from the UrBackup server

UrBackup Client 2.4.10 for Linux

**Install with:**
TF=$(mktemp) && wget "https://hndl.urbackup.org/Client/2.4.10/UrBackup%20Client%20Linux%202.4.10.sh" -O $TF && sudo sh $TF; rm -f $TF

**output**
Detected Debian (derivative) system
Detected systemd
Cannot run UrBackup client on this server. CPU architecture aarch64 not supported. Stopping installation.

**insight**
DietPi_v140_OdroidC2-arm64-(Jessie)

The install script supports aarch64. The issue with the script is on line 79256. The following command is executed 'uname -m' The script expects 'aarch64-linux-eng'  contrary to what's produced on the dietpi which only returns 'aarch64'

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
