### ISSUE TITLE
when trying to install kodi 

### ISSUE THREAD

**Issue by waltherwatz** [MichaIng/DietPi#6793]
### Creating a bug report/issue
dietpi-software asked me to open a resp. ticket; here it is: 

### Details:
- Date           | Wed Dec  6 16:07:27 CET 2023
- DietPi version | v8.24.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 3 Model B (armv7l) (ID=3)
- Kernel version | `Linux DietPi2 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=1)
- Command        | `apt-get -y --allow-change-held-packages install avahi-daemon`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. I simply tried to install kodi via dietpi-sofware
2. ...
#### Expected behaviour:

- installation as requested
#### Actual behaviour:

- error message as seen in log
#### Extra details:

- rather fresh installation, just started to add things; pihole and unbound running 
- my assumption "full diks" could not be verified:
root@DietPi2:~# df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/root        58G    1,4G   55G    3% /
devtmpfs        454M       0  454M    0% /dev
tmpfs           486M       0  486M    0% /dev/shm
tmpfs           195M    2,9M  192M    2% /run
tmpfs           5,0M    4,0K  5,0M    1% /run/lock
tmpfs           1,0G     12K  1,0G    1% /tmp
tmpfs            50M    300K   50M    1% /var/log
/dev/mmcblk0p1  127M     52M   76M   41% /boot
/dev/sda1       1,4T    131G  1,2T   11% /mnt/usb_ext4

dietpl-software installed:
#### Additional logs:
                         ┌─────────────────────────────────────────────────┤ DietPi-Software ├──────────────────────────────────────────────────┐
                          │ Use the spacebar to select the software you would like to remove:                                                    │ 
                          │                                                                                                                      │ 
                          │  [ ] 103  DietPi-RAMlog: Makes /var/log a RAM disk, preserves file structure on reboot                               │ 
                          │  [ ] 104  Dropbear: Lightweight SSH server                                                                           │ 
                          │                                                                                                                      │ 
                          │                                  <Ok>                                      <Back>                                    │ 
                          │                                                                                                                      │ 
                          └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ 
                                                                                                                                                   

```
Reading package lists...
Building dependency tree...
Reading state information...
avahi-daemon is already the newest version (0.8-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up kodi (3:20.2-2~bookworm) ...
dpkg: error processing package kodi (--configure):
 installed kodi package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 kodi
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MichaIng** [comment]
See here: #6703
But thanks for the reminder. I'll implement the workaround into `dietpi-software` since RPi seems to not fix the package any soon.
