### ISSUE TITLE
Rock 3C

### ISSUE THREAD

**Issue by gjm19761** [MichaIng/DietPi#6826]
#### Formal device information
- Device name | 
- Official product URL | 

#### Is the SBC officially supported by the Debian installer?
- .

#### If not, is a reliable 3rd party Debian image available for this SBC?
- ...yes  https://github.com/radxa-build/rock-3c/releases

#### If not, are there install instructions for Debian available?
<!-- [EG: (https://github.com/radxa-build/rock-3c/releases)->
- ...
This is a new rock 3 board and doent work with rock 3a images. its a great low cost sbc pleaas can you add it?

**Comment by isarrider** [comment]
https://github.com/MichaIng/DietPi/discussions/6475
linking this...

**Comment by MichaIng** [comment]
Jep, closing this as duplicate.
