### ISSUE TITLE
DietPi-Software | Gitea

### ISSUE THREAD

**Issue by petermused** [MichaIng/DietPi#686]
Hello, I see you have Gogs on your software list. Gitea ([gitea.io](https://gitea.io)) is a fork of Gogs which looks to be better maintained gogits/gogs#1304 (?) So I'd imagine the installation process would be similar to Gogs. Gitea is on it's 1.0 release as of writing this. I also would say that Gitea is more active than Gogs (Gitea has merged 42 PRs in the last week, Gogs merged 2. Look at the repos' pulses). If adding Gitea to the software list is possible, it would be appreciated. Thank you for your help.

**Comment by DJCrashdummy** [comment]
- documentation on their homepage: https://docs.gitea.io/en-us/install-from-binary/
- code @DPlatform-ShellCore: https://github.com/DFabric/DPlatform-ShellCore/blob/master/apps/Gitea.sh

**Comment by Fourdee** [comment]
> Binaries: https://dl.gitea.io/gitea/master/

**Comment by jbz-dev** [comment]
From what I understand it will be really the same process as gogs to include gitea in dietpi.

@Fourdee If you want testers I'm in :) Trying right now to install gitea on my DietPi powered Rpi3

**Comment by jbz-dev** [comment]
@Fourdee 

Did a bit of testing yesterday and tried to make a PR on `dietpi-software` but the file is damn too big for my poor skills (And I probably messed up the file )

I created a gist with a few things I managed to format according to Dietpi-Software syntax 

(https://gist.github.com/Bridouz/4a264d317c9690b7b28b1246b011ca92)

Obviously just as Gogs it needs `openssh`.

And I think that's it, tell me if something it's wrong :)

Thanks again for `Dietpi`, a really nice layer to use on top of Raspbian.

**Comment by ghost** [comment]
@Fourdee @Bridouz 

With the binaries available this one looks pretty easy to add. I might take a crack at it though I'm out of town for a few days.  One question -- is this a software request add or a replace? Should I be looking to remove Gogs or just add Gitea?

**Comment by ghost** [comment]
@Bridouz  I used your gist as a great jumping off point to work on adding this. I made a few changes the biggest one is I used this systemd script for running as a daemon instead of writing the init script from dietpi-software

https://github.com/go-gitea/gitea/blob/master/contrib/systemd/gitea.service

@Facel3ss1 Check it out/Test it if you like
https://github.com/techdabbler/DietPi/blob/gitea-add/dietpi/dietpi-software

If you are testing it make sure to grab an updated deitpi-services files from or else it will not autostart. (or nano /DietPi/dietpi/dietpi-services and add 'gitea' to the list)
https://github.com/techdabbler/DietPi/blob/gitea-add/dietpi/dietpi-services

Config Info:
DB User: root
DB Password: dietpi
DB: gitea

Location: /mnt/dietpi_userdata/gitea-repositories
Run As: git
(testing on x86_64 right not. Haven't tried arm yet)

**Comment by techdabbler** [comment]
Ok I'm at the initial config point and I'm having trouble knowing what the pw for MySQL is. I tried 'dietpi' from the gogs setup in the wiki and that didn't work.  So either I'm reading the code/wiki wrong or I've got a different issue.  I got this running gitea both as root and as git (the user the systemd file uses - though I can change it if I need to). 

![image](https://user-images.githubusercontent.com/31933671/31311738-84d1303c-ab67-11e7-8cd1-08f025c0a394.png)

**Comment by jbz-dev** [comment]
thanks for the fixes, rewrites and commits. I will test it tomorrow on my dietpi.

what do you think about creating a _git_ user @Fourdee ?

Is it OK or do you want to stick with `root` user only for now ?

**Comment by ghost** [comment]
@Bridouz I look forward to hearing how your test goes. Also, if you have any notes on uninstallation I'd appreciate them. Removing the executable and data is easy it is the command to drop the db from mysql that I haven't tried hunting down yet.

@Fourdee when marking an install as needing a pre-requisite software package (ie mysql, git, openssh in this case) when the software (gitea) is un-installed does diet-pi software automatically remove mysql or git for example? Or roll back dropbear? Or is there a way for the un-installer to call that via dietpi commands? Or is this something that is even recommended to consider?

**Comment by Fourdee** [comment]
@techdabbler 

> @Fourdee when marking an install as needing a pre-requisite software package (ie mysql, git, openssh in this case) when the software (gitea) is un-installed does diet-pi software automatically remove mysql or git for example? Or roll back dropbear? Or is there a way for the un-installer to call that via dietpi commands? Or is this something that is even recommended to consider?

We don't remove shared pre-requisite/library software, during uninstalls, unless the user has specifically selected it for uninstall.

EG: Remove MPD, does not remove ALSA, as it could be needed for other install programs.
EG: Remove MPD, and user also selects ALSA for removal, removes both.
![image](https://user-images.githubusercontent.com/7077026/31319849-506cb644-ac62-11e7-81df-429a0cda2643.png)

**Comment by ghost** [comment]
@Fourdee Thanks. That is what I expected. Just want to make sure I'm doing uninstalls as complete as possible.

**Comment by jbz-dev** [comment]
Gitea working on DP Stretch Rpi3 :)

Do we stick with that `git` user creation or do we keep all software running with `root` @Fourdee ?

PS: I also have a nginx config for a redirection from `localhost:3000` to `server_name/gogs` if you want.

**Comment by Fourdee** [comment]
@Bridouz 

> Do we stick with that git user creation

Ideally, stick with the user as defined by the software, just be aware may need to set permissions for that user in ```/mnt/dietpi_userdata/SOFTWARETITLE``` if used and requires it.

> PS: I also have a nginx config for a redirection from localhost:3000 to server_name/gogs if you want.

I personally prefer to keep the installation URL's and ports stock, matching official docs. The only exception being http://0.0.0.0/pihole because it made sense :)
I recommend leaving redirection and customization down to the end user.

**Comment by ghost** [comment]
@Bridouz Good to hear it is working for you too. I just committed uninstall section. I haven't tested yet but would you mind giving it a test in RPi3 stretch for me? Once that is in place I think we are readying to pull request it.

**Comment by Fourdee** [comment]
@techdabbler Thanks for adding this in 👍 

### Ready for testing, Install and uninstall:
- 🈯️ ARMv6
- 🈯️ ARMv7
- 🈯️ x86_64

### Web interface tests
Change
- MySQL user = ```root```
- MySQL PW = ```dietpi```

**Comment by Fourdee** [comment]
Online Doc:
- 🈯️ http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=9863#p9863

**Comment by Fourdee** [comment]
Tests:
- 🈯️ ARMv7
- 🈯️ ARMv8
- 🈯️ x86_64

Completed.
