### ISSUE TITLE
FileBrowser installed can't login

### ISSUE THREAD

**Issue by AJD1000** [MichaIng/DietPi#6862]
Fresh install of dietpi on raspberry 4b. Installed File Browser from the Software installion Menu, it seemed to install without errors. I can see the web page at raspberrypi:8040 when I attempt to login with Username: admin and Password: admin it says WRONG CREDENTIALS 
I have rebooted, and unistalled and re-installed File Browser, same outcome. Can anyone help with this please, Dietpi and File Browser seems a perfect solution for my needs.

![Login error](https://github.com/MichaIng/DietPi/assets/156709638/71a230cd-ccf9-4266-b274-4f7037b9ccc9)

**Comment by Joulinar** [comment]
have a look to our online docs for user/password information. https://dietpi.com/docs/software/cloud/#__tabbed_14_1
