### ISSUE TITLE
Error update dietpi 8.25.1 to 9.0.2 raspberry pi 4

### ISSUE THREAD

**Issue by caio1007** [MichaIng/DietPi#6874]
#### Details:
- Date           | Sun Jan 21 12:14:41 -03 2024
- DietPi version | v8.25.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspberry Pi OS Lite (64-bit)
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `rm master.tar.gz DietPi-master/dietpi/pre-patch_file DietPi-master/dietpi/server_version-6`
- Exit code      | 1
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
rm: cannot remove 'DietPi-master/dietpi/pre-patch_file': No such file or directory
rm: cannot remove 'DietPi-master/dietpi/server_version-6': No such file or directory

**Comment by MichaIng** [comment]
Strange, do you see pre-patches being applied? Basically this particular line:
```
[  OK  ] mkdir -p "../DietPi-Update/DietPi-master/dietpi"
```

**Comment by caio1007** [comment]
yes

![image](https://github.com/MichaIng/DietPi/assets/53404198/5790d7c2-a4ad-4ac3-b607-5f6de46ad328)

**Comment by MichaIng** [comment]
Strange, the branch is empty. Can you check this:
```sh
sed -n '/^[[:blank:]]*DEV_GITBRANCH=/{s/^[^=]*=//p;q}' /boot/dietpi.txt
grep DEV_GITBRANCH /boot/dietpi.txt
```

**Comment by caio1007** [comment]
sed -n '/^[[:blank:]]*DEV_GITBRANCH=/{s/^[^=]*=//p;q}' /boot/dietpi.txt
grep DEV_GITBRANCH /boot/dietpi.txt

DEV_GITBRANCH=

**Comment by MichaIng** [comment]
`dietpi-update` uses the `master` branch automatically as fallback, hence the update otherwise worked, but the pre-patch does/did not have the fallback. I just added it: https://github.com/MichaIng/DietPi/commit/c46ebc9

However, the branch setting is not supposed to be empty in any case. Please apply it:
```sh
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=master' /boot/config.txt
```
Then rerun the update.

**Comment by caio1007** [comment]
`G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=master' /boot/config.txt
[  OK  ] G_CONFIG_INJECT | Added setting DEV_GITBRANCH=master to end of file /boot/config.txt
root@DietPi:~# dietpi-update 
`

`#### Details:
- Date           | Sun Jan 21 13:08:01 -03 2024
- DietPi version | v8.25.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Raspberry Pi OS Lite (64-bit)
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `rm master.tar.gz DietPi-master/dietpi/pre-patch_file DietPi-master/dietpi/server_version-6`
- Exit code      | 1
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
rm: cannot remove 'DietPi-master/dietpi/pre-patch_file': No such file or directory
rm: cannot remove 'DietPi-master/dietpi/server_version-6': No such file or directory
```
`

**Comment by MichaIng** [comment]
Oh sorry, wrong file:
```sh
G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=master' /boot/dietpi.txt
sed -i '/DEV_GITBRANCH/d' /boot/config.txt'
```

**Comment by caio1007** [comment]
Worked, thank you👍

**Comment by MichaIng** [comment]
Okay great, I'll mark the issue as closed then.
