### ISSUE TITLE
NEO - Serial ttyS1 not working!

### ISSUE THREAD

**Issue by tusharvb19** [MichaIng/DietPi#688]
Though I have enabled  serial using this
/DietPi/dietpi/func/dietpi-set_hardware serialconsole enable
still I am not getting way to talked with serial device!
here is the error:
root@DietPi:~# python ser.py
Traceback (most recent call last):
  File "ser.py", line 4, in <module>
    ser = serial.Serial("/dev/ttyS1", baudrate=19200,timeout=1)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 282, in open
    self._reconfigurePort()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in _reconfigurePort
    raise SerialException("Could not configure port: %s" % msg)
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')

**Comment by Fourdee** [comment]
@tusharvb19 

Thanks for the report.

Which device are you running?

**Comment by tusharvb19** [comment]
I am using NanoPi NEO.

**Comment by Fourdee** [comment]
@tusharvb19 

Thanks.

I believe NanoPi Neo serial is enabled by default but we need to verify.

- Does a basic serial console work (excluding the python script)?
- Which kernel are you running ```uname -a```?. If its 3.x, try using the updated 4.9 kernel image and retest: http://dietpi.com/downloads/images/DietPi_NanoPiNEO-armv7-(Jessie).7z

I'll make a note to test NanoPi Neo serial console, but you may beat me too it 😉

**Comment by tusharvb19** [comment]
The serial console is working but I have to interface GSM module to UART1 thus ttyS1 but still after enabling them I am not able to make connection through screen to test basic AT commands.
The screen get exit automatically. And the other python serial code comes out with an error "can not configure port..."
Here is the link of fona(GSM module) tutorial which is working in other distro..core ubuntu!

https://learn.adafruit.com/fona-tethering-to-raspberry-pi-or-beaglebone-black/setup

**Comment by tusharvb19** [comment]
Help me please to solve this...I am not able to use UART1!

**Comment by tusharvb19** [comment]
Is there anyone who can make the ttyS1 work to get connected to various modules that operates on UART i.e. TX-RX. I have to interface SIM900 module(sic).

**Comment by tusharvb19** [comment]
I need the solution to use dietPi as a my deafult os. Can someone try and help me to get it working!
(sic)

**Comment by Fourdee** [comment]
@tusharvb19 

> I need the solution to use dietPi as a my deafult os. Can someone try and help me to get it working!

Unfortunately, anything beyond standard serial connection for remote tty, is not something I have experience with. I cannot offer any assistance in this case.

**Comment by tusharvb19** [comment]
The serial ports are there ttys1but I am not able to get it working for serial interface..it shows could not configure port/io error!

**Comment by DickyT** [comment]
@tusharvb19 I have the same problem, both uart1&2 is not working, but there is a workaround, use ssh to login your pi, and use uart0 (debug uart) for your serial device

**Comment by Fourdee** [comment]
Neo is no longer supported. Marking as closed.
