### ISSUE TITLE
Raspberry PI 4 + DietPi = problem with "kiauh"

### ISSUE THREAD

**Issue by Slawaspr0** [MichaIng/DietPi#6890]
### Creating a bug report/issue
- [ X ] First I was trying to search for help in kiauh github here: https://github.com/dw-0/kiauh/issues/426

#### Required Information
- DietPi version / Distro version / Kernel version - lastest, I just downloaded system image a few hours earlier, and let it update itself
- Raspberry PI 4
- IDK - some step down from printer power supply
- I use SSD GoodRam 128 GB

#### Additional Information (if applicable)
- kiauh
- installed freshly
- Can this issue be replicated on a fresh installation of DietPi? - Yes

#### Steps to reproduce

Run DietPI
Login to user dietpi
Trying to run "`cd ~ && git clone https://github.com/dw-0/kiauh.git`" - cant, no access, need root
Login to root
Again trying to run "`cd ~ && git clone https://github.com/dw-0/kiauh.git`" - success
Trying to run "`./kiauh/kiauh.s`h" - can't run this as root
Login to dietpi
Again trying to run "`./kiauh/kiauh.sh`" - can't run, no directory access

#### Expected behaviour
I needed to make new/clean system install on my RaspberryPi. Fast configuration - WIFI connection - SSH and trying to install kiauh. Last time i did it more than year ago. Something changed since that, because I remember that last time I did it without problems.

#### Actual behaviour
Can't use kiauh. I can install it, but can't run/use.

#### Extra details
I'm using my RaspberryPi with DietPi system in 3D printer. Kiauh is most popular script to manage my printer software/firmware. More details in link I provided at begining.

**Comment by MichaIng** [comment]
The `dietpi` user should of course have write access to its home directory. Can you verify that this is `/home/dietpi` as expected, and that it is owned by `dietpi`:
```sh
pwd
ls -l .
```

**Comment by Slawaspr0** [comment]
But default install directory of kiauh is root/kiauh, i was trying to move it manually to /home/dietpi then I had to change owner from root to dietpi (because kiauh can only be installe by root), then I was trying to change chmod of all files, at the end I cant run kiauh

**Comment by MichaIng** [comment]
Now I am confused. I thought the installer itself denies to be executed as root? Why does it explicitly try to install into the root's home directory then 🤔. And still, at first even `git clone` failed, as you wrote, so please run the above commands and paste the output here, so we can verify that `dietpi` has write access to its own home directory, as intended.

**Comment by dw-0** [comment]
> But default install directory of kiauh is root/kiauh

That is incorrect. You shouldn't even download kiauh as root user nor in roots home directory. You should never use root for kiauh. Always a regular user. And then download kiauh into that users home directory.

> because kiauh can only be installed by root

That is also incorrect. There is no such thing as "installing" kiauh. It's a git clone. In other words a simple download.

**Comment by MichaIng** [comment]
And why do you say "But default install directory of kiauh is root/kiauh" then? Or did I misunderstand it? Usually, such installers just stay in the PWD, which makes doubled sense here since it is a Git directory.

**Comment by Slawaspr0** [comment]
Look at this
![kiauh](https://github.com/MichaIng/DietPi/assets/92549375/a9f8bbfd-66fd-49c1-9d84-c0c418c4e883)

**Comment by MichaIng** [comment]
Can you please run the above 3 commands and paste the output here? I can still not see whether the directory is the intended one, and whether the `dietpi` user has intended permissions for this directory.

**Comment by Slawaspr0** [comment]
Sure
![kiauhv2](https://github.com/MichaIng/DietPi/assets/92549375/e0f77901-026f-4158-9e31-60b578624f3c)

**Comment by MichaIng** [comment]
Ah sorry, this one to see permissions of the directory:
```sh
ls -dl .
```

**Comment by Slawaspr0** [comment]
Hmmm, now I see, shoul be there dietpi instead of root right?
![kiauhv3](https://github.com/MichaIng/DietPi/assets/92549375/6bf47c11-f5c1-4f46-bd23-689c0fb2b120)

**Comment by MichaIng** [comment]
So indeed that directory is owned by `root`. That is pretty unintended, of course. Fix this, then you can clone and install the software there:
```sh
sudo chown -R dietpi:dietpi /home/dietpi
```

**Comment by Slawaspr0** [comment]
Ok, gonna try.
![kiauhv4](https://github.com/MichaIng/DietPi/assets/92549375/488f036a-c521-4560-b7b6-89604b0ad11b)
Cloning complete, looks promising, now trying to run it
![kiauhv5](https://github.com/MichaIng/DietPi/assets/92549375/9432370a-3d81-48c3-9c8b-e8b9388efeed)
Ok, super! It's working, but now I'm wondering, is this possible, that /home/dietpi have root owner since clean install?

**Comment by MichaIng** [comment]
> Ok, super! It's working, but now I'm wondering, is this possible, that /home/dietpi have root owner since clean install?

Okay perfect. And nope, `/home/dietpi` is definitely owned by `dietpi` on fresh images.

**Comment by Slawaspr0** [comment]
Ok, so IDK how i did it, but I'm really happy that You helped me to fix this, thank You.

**Comment by MichaIng** [comment]
Sure 🙂. I'll mark the issue as closed then.
