### ISSUE TITLE
DietPi-Software | Lighttpd webserver stack

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#69]
Lighttpd + SQLite + PHP5
http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=88

**Comment by pilovali** [comment]
apt-get install lighttpd php5-cgi php5-sqlite php-opcache
lighttpd-enable-mod fastcgi
lighttpd-enable-mod fastcgi-php
service lighttpd force-reload

I'm following https://www.digitalocean.com/community/tutorials/how-to-install-the-llmp-stack-linux-lighttpd-mysql-and-php-on-ubuntu-12-04. It should work about the same, but then with opcache and SQLite.

**Comment by Fourdee** [comment]
LLMP LLSP Available in next release (v109)
