### ISSUE TITLE
General | Incorrect fonts with de_DE@euro

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#694]
As reported by Rainer (email):

> From my point of view something is rotten in the termcap/-info system. Normally every terminal should go through it and get correct font and control commands.

>DietPi | Update available
âââââââââââââââââââââââââââââââââââââââ
 V140 | NanoPi M1/T1 (armv7l)
âââââââââââââââââââââââââââââââââââââââ

**Comment by k-plan** [comment]
@Fourdee 

![170109-0001](https://cloud.githubusercontent.com/assets/17237601/21774896/5e4ba1e8-d694-11e6-89ac-4556e40fb2b1.gif)

❓ 

```
root@NanoPi-NEO:~# locale
LANG=de_DE@euro
LANGUAGE=
LC_CTYPE="de_DE@euro"
LC_NUMERIC="de_DE@euro"
LC_TIME="de_DE@euro"
LC_COLLATE="de_DE@euro"
LC_MONETARY="de_DE@euro"
LC_MESSAGES="de_DE@euro"
LC_PAPER="de_DE@euro"
LC_NAME="de_DE@euro"
LC_ADDRESS="de_DE@euro"
LC_TELEPHONE="de_DE@euro"
LC_MEASUREMENT="de_DE@euro"
LC_IDENTIFICATION="de_DE@euro"
LC_ALL=

```

Configuring locales: `de_DE@euro ISO-8859-15 `


```
root@NanoPi-NEO:~# uname -a
Linux NanoPi-NEO 3.4.112-sun8i #10 SMP PREEMPT Sun Oct 23 16:06:55 CEST 2016 armv7l GNU/Linux
```

... a problem with SSH client or on screen (monitor)?
Sorry, but my NanoPi Neo (tested device) have no HDMI output.

**Comment by Fourdee** [comment]
@k-plan 

Thanks for running those tests 👍 . User is using NanoPi M1, so i'll setup a system at some point and see if its device specific.

**Comment by Fourdee** [comment]
Fine:
![image](https://cloud.githubusercontent.com/assets/7077026/21955992/1265bdf8-da6e-11e6-9d31-e2bf310b13f4.png)

Most likely as @k-plan suggested, due to SSH client and/or configuration.

Will mark as closed and discuss with user.
