### ISSUE TITLE
Nginx restart fails after install of LetsEncrypt from DietPi-Launcher (on VM)

### ISSUE THREAD

**Issue by refthoom** [MichaIng/DietPi#6942]
#### Details:
- Date           | Wed Feb 28 14:10:13 GMT 2024
- DietPi version | v9.1.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | Virtual Machine (x86_64) (ID=20)
- Kernel version | `Linux DietPi 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`
- Distro         | bookworm (ID=7)
- Command        | `systemctl restart nginx`
- Exit code      | 1
- Software title | DietPi-LetsEncrypt
#### Steps to reproduce:
1. start DietPi-Launcher and then from the menu start DietPi-LetsEncrypt
2. follow all steps from the wizard/menu, all goes  well except for the last step; restart nginx throws an error
#### Expected behaviour:
- succesfully restart nginx
#### Actual behaviour:
- DietPi-Launcher shows an error; DietPi has encountered an error .... See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.
#### Extra details:
- closed all diet-pi menus and rebooted VM >> **issue fixed, nginx running again**
- certbot is running as well so install of LetsEncrypt seems not to be (negatively) impacted
#### Additional logs:
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.

**Comment by Joulinar** [comment]
> See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details

and what was the output??
