### ISSUE TITLE
ncurses-term prompt doesn't install anything because of no root permissions

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#6947]
### Creating a bug report/issue
- [x] I have searched the existing open and closed issues

#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=9 G_DIETPI_VERSION_SUB=1 G_DIETPI_VERSION_RC=1 G_GITBRANCH='master' G_GITOWNER='MichaIng' G_LIVE_PATCH_STATUS[0]='not applicable'`
- Distro version | `bookworm 0`
- Kernel version | `Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`

when you use an unsupported terminal to ssh into dietpi it will prompt you about either installing ncurses-term or ignoring the issue, but if you choose to install ncurses-term it will fail because of no sudo permissions.

**Comment by Joulinar** [comment]
did you tried to login as root user?

**Comment by zbikk** [comment]
haven't tried, i just ignored the prompt and manually installed the package

**Comment by MichaIng** [comment]
Makes sense that we try to do the installation with `sudo`, if not logging in as root user, or print a warning only.

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/7582822
