### ISSUE TITLE
DietPI Sample rate issue

### ISSUE THREAD

**Issue by KenMoreira** [MichaIng/DietPi#6977]
I have been using a USBridge (allo) for a long time now)
recently I have had my Sample rate locked to 48k While using Audirvana from PC. As well as when I use Mconnect from my phone.

The issue is consistent weather using qobuz or local files.
Neither limiting to 44.1k nor upsampling in Audirvana change the sample rate displayed , stuck at 48k
the output signal in the Audirvana App shows the proper Sample sample 41/96/192 etc..

However, when using Hqplayer. I can successfully Change sample rates.

I am starting to think, it maybe an MPD or GMrender issue.  I do NOT have the ALLO gui. Is their a specific string I can input into my dietpi from putty.

(Currently on Bookworm)

**Comment by KenMoreira** [comment]
looking to view / editing those audio render settings. to allow maximum / whatever the file played is natively

**Comment by MichaIng** [comment]
You are accessing the audio device via MPD? In the past we did, but do not hardcode the sample rate (or other audio format parameters) in `/etc/mpd.conf` anymore. The stream is just forwarded to the default ALSA PCM as received from the player, and that one, as defined in `/etc/asound.conf`, does not hardcode the format either.

But the MPD audio format can be changed (or reset) via `dietpi-justboom`. Probably you did it that way?

**Comment by KenMoreira** [comment]
I've only updated using dietpi - update.

It's really the only ssh line I execute.

I'm just looking to see in my settings. I checked through comfig but since
I'm using usb dac I get
No alsa audio error or something when looking into mpd

**Comment by MichaIng** [comment]
Not sure then. At some point, Allo stopped building these ASIX Ethernet driver for the USBridge Sig, hence now the upstream driver is used which can cause flickers in audio playback: https://github.com/raspberrypi/linux/issues/2942

But the audio driver itself AFAIK has no changed. Can you show your MPD and ALSA config?
```sh
cat /etc/asound.conf
cat /etc/mpd.conf
```

GMediaRender is not related to MPD, but accesses audio devices directly in its own way. `/etc/default/gmediarender` defines the used ALSA PCM, which is just `default` by default, as defined in `/etc/asound.conf`.

> the sample rate displayed , stuck at 48k
the output signal in the Audirvana App shows the proper Sample sample 41/96/192 etc..

Where do you see this 48k displayed? So you mean you can define the output signal in players, but at the server/hardware side you see 48k, when doing playback via GMediaRender or MPD, and only higher sample rates when using HQPlayer?

And does it work to enforce a sample rate via e.g.
```sh
speaker-test -r 192000
```

**Comment by KenMoreira** [comment]
Correct.  I have a spring 3 kte
It has an on dac display.

Using mconnect or audirvana, any sample rate just shows as 48k.  Weather
it's 44.1 or up to 192k

But when using hqplayer the issue goes away as I up sample to dsd 512x
I could see if hqplayer pcm up sampling has issues.

**Comment by KenMoreira** [comment]
root@DietPi:~# cat /etc/asound.conf
cat: /etc/asound.conf: No such file or directory
root@DietPi:~# cat /etc/mpd.conf
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/
# or /usr/share/doc/mpd/html/user.html


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
music_directory "/mnt/dietpi_userdata/Music"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
playlist_directory "/mnt/dietpi_userdata/Music"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
db_file "/mnt/dietpi_userdata/.mpd_cache/db_file"
#
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog, or to journal if mpd was started as
# a systemd service.
#
#log_file "/var/log/mpd/mpd.log"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
#pid_file "/run/mpd/pid"
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server
# state will be reset on server start up.
#
state_file "/mnt/dietpi_userdata/.mpd_cache/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file "/mnt/dietpi_userdata/.mpd_cache/sticker.sql"
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
#user "mpd"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group                          "nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other than the default, any.
# This setting can deny access to control of the daemon. Choose any if you want
# to have mpd listen on every address. Not effective if systemd socket
# activation is in use.
#
# For network
bind_to_address                 "localhost"
#
# And for Unix Socket
bind_to_address "/run/mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
#port                           "6600"
#
# Suppress all messages below the given threshold.  Use "verbose" for
# troubleshooting. Available setting arguments are "notice", "info", "verbose",
# "warning" and "error".
#
#log_level                      "notice"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists       "no"
#
# This setting defines a list of tag types that will be extracted during the
# audio file discovery process. The complete list of possible values can be
# found in the user manual.
#metadata_to_use        "artist,album,title,track,name,genre,date,composer,perfo                                                                                                                                                             rmer,disc"
#
# This example just enables the "comment" tag without disabling all
# the other supported tags:
#metadata_to_use "+comment"
#
# This setting enables automatic update of MPD's database when files in
# music_directory are changed.
#
#auto_update    "yes"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links outside of the configured music_directory.
#
#follow_outside_symlinks        "yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
#follow_inside_symlinks         "yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
#zeroconf_enabled               "yes"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network. %h will be replaced with the hostname.
#
#zeroconf_name                  "Music Player @ %h"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in.
#
#default_permissions             "read,add,control,admin"
#
###############################################################################


# Database #####################################################################                                                                                                                                                             ##
#
# An example of a database section instead of the old 'db_file' setting.
# It enables mounting other storages into the music directory.
#
#database {
#       plugin "simple"
#       path "/var/lib/mpd/tag_cache"
#       cache_directory "/var/lib/mpd/cache"
#}
#
# An example of database config for a sattelite setup
#
#music_directory "nfs://fileserver.local/srv/mp3"
#database {
#       plugin "proxy"
#       host "other.mpd.host"
#       port "6600"
#}

# Input #######################################################################
#
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

# Decoder #####################################################################
#

decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
#       gapless                 "no"
}
decoder {
        plugin        "wildmidi"
        enabled       "no"
        #config_file "/etc/timidity/timidity.cfg"
}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple
# audio outputs at the same time, through multiple audio_output settings
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
#audio_output {
#       type            "alsa"
#       name            "My ALSA Device"
##      device          "hw:0,0"        # optional
##      mixer_type      "hardware"      # optional
##      mixer_device    "default"       # optional
##      mixer_control   "PCM"           # optional
##      mixer_index     "0"             # optional
#}
#
# An example of an OSS output:
#
#audio_output {
#       type            "oss"
#       name            "My OSS Device"
##      device          "/dev/dsp"      # optional
##      mixer_type      "hardware"      # optional
##      mixer_device    "/dev/mixer"    # optional
##      mixer_control   "PCM"           # optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#       type            "shout"
#       encoder         "vorbis"                # optional
#       name            "My Shout Stream"
#       host            "localhost"
#       port            "8000"
#       mount           "/mpd.ogg"
#       password        "hackme"
#       quality         "5.0"
#       bitrate         "128"
#       format          "44100:16:1"
##      protocol        "icecast2"              # optional
##      user            "source"                # optional
##      description     "My Stream Description" # optional
##      url             "http://example.com"    # optional
##      genre           "jazz"                  # optional
##      public          "no"                    # optional
##      timeout         "2"                     # optional
##      mixer_type      "software"              # optional
#}
#
# An example of a recorder output:
#
#audio_output {
#       type            "recorder"
#       name            "My recorder"
#       encoder         "vorbis"                # optional, vorbis or lame
#       path            "/var/lib/mpd/recorder/mpd.ogg"
##      quality         "5.0"                   # do not define if bitrate is de                                                                                                                                                             fined
#       bitrate         "128"                   # do not define if quality is de                                                                                                                                                             fined
#       format          "44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#       type            "httpd"
#       name            "My HTTP Stream"
#       encoder         "vorbis"                # optional, vorbis or lame
#       port            "8000"
#       bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
##      quality         "5.0"                   # do not define if bitrate is de                                                                                                                                                             fined
#       bitrate         "128"                   # do not define if quality is de                                                                                                                                                             fined
#       format          "44100:16:1"
#       max_clients     "0"                     # optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
# Please see README.Debian if you want mpd to play through the pulseaudio
# daemon started as part of your graphical desktop session!
#
#audio_output {
#       type            "pulse"
#       name            "My Pulse Output"
##      server          "remote_server"         # optional
##      sink            "remote_server_sink"    # optional
##      media_role      "media_role"            #optional
#}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#       type            "winmm"
#       name            "My WinMM output"
##      device          "Digital Audio (S/PDIF) (High Definition Audio Device)"                                                                                                                                                              # optional
#               or
##      device          "0"             # optional
##      mixer_type      "hardware"      # optional
#}
#
# An example of an openal output.
#
#audio_output {
#       type            "openal"
#       name            "My OpenAL output"
##      device          "Digital Audio (S/PDIF) (High Definition Audio Device)"                                                                                                                                                              # optional
#}
#
# An example of an sndio output.
#
#audio_output {
#       type            "sndio"
#       name            "sndio output"
#       mixer_type      "hardware"
#}
#
# An example of an OS X output:
#
#audio_output {
#       type            "osx"
#       name            "My OS X Device"
##      device          "Built-in Output"       # optional
##      channel_map      "-1,-1,0,1"    # optional
#}
#
## Example "pipe" output:
#
#audio_output {
#       type            "pipe"
#       name            "my pipe"
#       command         "aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#       command         "AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#       command         "nc example.org 8765"
#       format          "44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#       type            "null"
#       name            "My Null Output"
#       mixer_type      "none"                  # optional
#}
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <https://wiki.hydrogenaud.io/index.php?title=Replaygain> for
# more details about ReplayGain.
# This setting is off by default.
#
#replaygain                     "album"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp              "0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
#replaygain_missing_preamp      "0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
#replaygain_limit               "yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has
# equal "loudness". This setting is disabled by default.
#
#volume_normalization           "no"
#
###############################################################################

# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you
# may need to modify this setting.
#
filesystem_charset              "UTF-8"
#
###############################################################################
# Simple ALSA output
audio_output {
        type "alsa"
        name "DietPi ALSA"
}
root@DietPi:~#

**Comment by KenMoreira** [comment]
the forcing to 192 did NOT work. shows 48k

**Comment by MichaIng** [comment]
```console
root@DietPi:~# cat /etc/asound.conf
cat: /etc/asound.conf: No such file or directory
```
It seems there has been no (default) sound card selected. Please try to select it in `dietpi-config` > Audio Options > Sound card.

ALSA else uses internal defaults, as shown in `aplay -L` (`default` and `sysdefault`), but those might imply auto-conversion and stuff like that. Selecting a sound card via `dietpi-config` (and leaving "auto-conversion" "off") creates a `/etc/asound.conf` which assures plain input stream playback without any ALSA plugin manipulation. If would then throw an error if the audio format is not supported by the sound card/driver, instead of trying (or doing OOTB) any conversion.

**Comment by KenMoreira** [comment]
Does it matter which one I choose, I'm on an allo usbridge signature.

**Comment by MichaIng** [comment]
It matters in how far ALSA plugins are used, and e.g. it is possible that currently the RPi onboard audio is enabled and used as default ALSA PCM. The USBridge Sig audio device should show up at the bottom of the list in the "Auto detection" section, though I am not sure how exactly it is named.

**Comment by KenMoreira** [comment]
Thanks, I'll check it out.

**Comment by KenMoreira** [comment]
I selected the last one in the list and Enabled ASLA

**Comment by KenMoreira** [comment]
![20240406_080741](https://github.com/MichaIng/DietPi/assets/86688395/8ad69fcb-673c-4d8e-b36d-c891fa1f8cc3)

**Comment by KenMoreira** [comment]
Hw: selection sends me In a loop where it removes stuff then I get a pop up asking to install asla features, then I accept and I get back here.

**Comment by MichaIng** [comment]
`hw:0,0` is it.

> Hw: (enhanc USB aAudio) selection sends me In a loop where it removes stuff then I get a pop up asking to install asla features, then I accept and I get back here.

Weird, can you copy&paste the full output of the log, after exiting `dietpi-config`?

**Comment by KenMoreira** [comment]
I already closed it. What steps would you need me to perform

**Comment by MichaIng** [comment]
1. Open `dietpi-config` audio options
2. Select `hw:0,0` as sound card
3. Regardless what happens, go back and exit `dietpi-config`
4. Select for copy&paste here all output done by `dietpi-config`

**Comment by KenMoreira** [comment]
root@DietPi:~# dietpi-config
[ SUB1 ] DietPi-Set_hardware > soundcard (hw:0,0)
[ INFO ] DietPi-Set_hardware | Checking for required APT packages: alsa-utils
[ INFO ] DietPi-Set_hardware | Resetting all sound card settings...
Found hardware: "USB-Audio" "USB Mixer" "USB152a:87c0" "" ""
Hardware is initialized using a generic method
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei -e /^[[:blank:]]*(dtove                                                                                                                                                             rlay=(allo-|applepi-dac|dionaudio-|googlevoicehat-soundcard|hifiberry-|i-sabre-q                                                                                                                                                             2m|iqaudio-|justboom-|rpi-dac)|dtparam=i2s)/d -e s/^[[:blank:]]*(hdmi_drive(:[01                                                                                                                                                             ])?=.*$)/#\1/ /boot/config.txt
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already s                                                                                                                                                             et: dtparam=audio=off
[  OK  ] DietPi-Set_hardware | eval echo 'blacklist snd_bcm2835' > /etc/modprobe                                                                                                                                                             .d/dietpi-disable_rpi_audio.conf
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei /root=/s/[[:blank:]]*sn                                                                                                                                                             d_bcm2835.enable_[^[:blank:]]*([[:blank:]]*$)?//g /boot/cmdline.txt
[ INFO ] DietPi-Set_hardware | Applying new sound card settings...
[  OK  ] DietPi-Set_hardware | Setting in /boot/dietpi.txt adjusted: CONFIG_SOUN                                                                                                                                                             DCARD=hw:0,0
[  OK  ] DietPi-Set_hardware | alsactl -g store
[  OK  ] soundcard hw:0,0 | Completed
[ SUB1 ] DietPi-Set_hardware > soundcard (none)
[ INFO ] DietPi-Set_hardware | APT purge alsa-utils libasound2-plugin-equal firm                                                                                                                                                             ware-intel-sound firmware-sof-signed, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  alsa-utils* libatopology2* libfftw3-single3*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
                                                              After this operation, 4788 kB disk space will be freed.
(Reading database ... 35165 files and directories currently installed.)                                              (Reading database ...
Removing alsa-utils (1.2.8-1+rpt1) ...
Removing libatopology2:arm64 (1.2.8-1+rpt1) ...
Removing libfftw3-single3:arm64 (3.3.10-1) ...
Processing triggers for libc-bin (2.36-9+rpt2+deb12u4) ...
(Reading database ... 35067 files and directories currently installed.)
Purging configuration files for alsa-utils (1.2.8-1+rpt1) ...
[  OK  ] DietPi-Set_hardware | APT purge alsa-utils libasound2-plugin-equal firmware-intel-sound firmware-sof-signed
[ INFO ] DietPi-Set_hardware | Resetting all sound card settings...
[  OK  ] DietPi-Set_hardware | rm /etc/asound.conf
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei -e /^[[:blank:]]*(dtoverlay=(allo-|applepi-dac|dionaudio-|googlevoicehat-soundcard|hifiberry-|i-sabre-q2m|iqaudio-|justboom-|rpi-dac)|dtparam=i2s)/d -e s/^[[:blank:]]*(hdmi_drive(:[01])?=.*$)/#\1/ /boot/config.txt
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already set: dtparam=audio=off
[  OK  ] DietPi-Set_hardware | eval echo 'blacklist snd_bcm2835' > /etc/modprobe.d/dietpi-disable_rpi_audio.conf
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei /root=/s/[[:blank:]]*snd_bcm2835.enable_[^[:blank:]]*([[:blank:]]*$)?//g /boot/cmdline.txt
[ INFO ] DietPi-Set_hardware | Applying new sound card settings...
[  OK  ] DietPi-Set_hardware | Setting in /boot/dietpi.txt adjusted: CONFIG_SOUNDCARD=none
[  OK  ] soundcard none | Completed
[  OK  ] DietPi-Config | Setting in /boot/dietpi/.installed adjusted: aSOFTWARE_INSTALL_STATE[5]=0
[ INFO ] DietPi-Config | Checking for required APT packages: alsa-utils
[ INFO ] DietPi-Config | APT update, please wait...
Hit:1 https://deb.debian.org/debian bookworm InRelease
Get:2 https://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 https://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 https://deb.debian.org/debian bookworm-backports InRelease [56.5 kB]
Hit:5 https://archive.raspberrypi.com/debian bookworm InRelease
Fetched 160 kB in 4s (44.9 kB/s)
Reading package lists...
[  OK  ] DietPi-Config | APT update
[ INFO ] DietPi-Config | APT install alsa-utils, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libatopology2 libfftw3-single3
Suggested packages:
  dialog libfftw3-bin libfftw3-dev
The following NEW packages will be installed:
  alsa-utils libatopology2 libfftw3-single3
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1621 kB of archives.
After this operation, 4788 kB of additional disk space will be used.
Get:1 https://deb.debian.org/debian bookworm/main arm64 libfftw3-single3 arm64 3.3.10-1 [494 kB]
Get:2 https://archive.raspberrypi.com/debian bookworm/main arm64 libatopology2 arm64 1.2.8-1+rpt1 [48.2 kB]
Get:3 https://archive.raspberrypi.com/debian bookworm/main arm64 alsa-utils arm64 1.2.8-1+rpt1 [1079 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1621 kB in 2s (909 kB/s)
                                Selecting previously unselected package libatopology2:arm64.
(Reading database ... 35065 files and directories currently installed.)
Preparing to unpack .../libatopology2_1.2.8-1+rpt1_arm64.deb ...
Unpacking libatopology2:arm64 (1.2.8-1+rpt1) ...
Selecting previously unselected package libfftw3-single3:arm64.
Preparing to unpack .../libfftw3-single3_3.3.10-1_arm64.deb ...
Unpacking libfftw3-single3:arm64 (3.3.10-1) ...
Selecting previously unselected package alsa-utils.
Preparing to unpack .../alsa-utils_1.2.8-1+rpt1_arm64.deb ...
Unpacking alsa-utils (1.2.8-1+rpt1) ...
Setting up libfftw3-single3:arm64 (3.3.10-1) ...
Setting up libatopology2:arm64 (1.2.8-1+rpt1) ...
Setting up alsa-utils (1.2.8-1+rpt1) ...
alsa-restore.service is a disabled or a static unit, not starting it.
alsa-state.service is a disabled or a static unit, not starting it.
Processing triggers for libc-bin (2.36-9+rpt2+deb12u4) ...
[  OK  ] DietPi-Config | APT install alsa-utils
[  OK  ] DietPi-Config | Setting in /boot/dietpi/.installed adjusted: aSOFTWARE_INSTALL_STATE[5]=2
[ SUB1 ] DietPi-Set_hardware > soundcard (none)
[ INFO ] DietPi-Set_hardware | APT purge alsa-utils libasound2-plugin-equal firmware-intel-sound firmware-sof-signed, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  alsa-utils* libatopology2* libfftw3-single3*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
                                                              After this operation, 4788 kB disk space will be freed.
(Reading database ... 35165 files and directories currently installed.)                                              (Reading database ...
Removing alsa-utils (1.2.8-1+rpt1) ...
Removing libatopology2:arm64 (1.2.8-1+rpt1) ...
Removing libfftw3-single3:arm64 (3.3.10-1) ...
Processing triggers for libc-bin (2.36-9+rpt2+deb12u4) ...
(Reading database ... 35066 files and directories currently installed.)
Purging configuration files for alsa-utils (1.2.8-1+rpt1) ...
[  OK  ] DietPi-Set_hardware | APT purge alsa-utils libasound2-plugin-equal firmware-intel-sound firmware-sof-signed
[ INFO ] DietPi-Set_hardware | Resetting all sound card settings...
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei -e /^[[:blank:]]*(dtoverlay=(allo-|applepi-dac|dionaudio-|googlevoicehat-soundcard|hifiberry-|i-sabre-q2m|iqaudio-|justboom-|rpi-dac)|dtparam=i2s)/d -e s/^[[:blank:]]*(hdmi_drive(:[01])?=.*$)/#\1/ /boot/config.txt
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/config.txt was already set: dtparam=audio=off
[  OK  ] DietPi-Set_hardware | eval echo 'blacklist snd_bcm2835' > /etc/modprobe.d/dietpi-disable_rpi_audio.conf
[  OK  ] DietPi-Set_hardware | sed --follow-symlinks -Ei /root=/s/[[:blank:]]*snd_bcm2835.enable_[^[:blank:]]*([[:blank:]]*$)?//g /boot/cmdline.txt
[ INFO ] DietPi-Set_hardware | Applying new sound card settings...
[  OK  ] DietPi-Set_hardware | Desired setting in /boot/dietpi.txt was already set: CONFIG_SOUNDCARD=none
[  OK  ] soundcard none | Completed

**Comment by KenMoreira** [comment]
I eventually cycled through again. choose HW. and after it installed and asked to Me select a sound card. this time instead of saying None as usual. I still said HW so i chose exit. and then typed reboot.

**Comment by KenMoreira** [comment]
(Deleted the log as it was no longer needed for you to go through)

**Comment by MichaIng** [comment]
Hmm, there should not be a "none" option in the sound card menu. The only way to trigger this
```
[ SUB1 ] DietPi-Set_hardware > soundcard (none)
```
is to select "Disable" in the main audio menu. So I guess you selected "Ok", while "Disable" was highlighted, expecting this means to confirm/finish audio options, while instead the "Ok" button confirms the selection of the currently highlighted menu entry. "Back" or "Exit", i.e. the buttons on the right side, or hitting ESC key, would be the way to go.

A case where indeed the button text is misleading. In those whiptail menus, the button on the left side is equal to hitting enter/return. We really need to adjust the button texts to better represent what they actually mean. In case of those menus, where you can navigate through the menu entries and hit enter/return, while you can also select the left button instead, it would be actually best to just hide the button. Sadly only the cancel button can be hidden.

However, glad it was sorted. So this means you can now effectively play audio with all sample rates through the USBridge Sig?

**Comment by KenMoreira** [comment]
Thanks for the explanation.
Yes it's working as expected with audirvana and with m connect streamer
software

**Comment by MichaIng** [comment]
Okay great. I am happy that the driver is not broken 🙂. I'll mark the issue as closed then. Feel free to reopen if required.
