### ISSUE TITLE
Image | Sparky (Allo)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#699]
Website ratings notes:
- 100MBit eth
- CPU performance rating: 35% (h3 = 40%)
- Heat eff, 45'c idle 60'c full load: 
- 🈯️ USB3
- 🈯️ EMMC

EMMC performance:
![image](https://cloud.githubusercontent.com/assets/7077026/21805730/9e1270c4-d72d-11e6-9d99-30ef266e0f09.png)

**Comment by Fourdee** [comment]
constant dmesg, with Kali + Piano attached:
```
[  126.325167] gsl_ts_read set data address fail!
[  126.325192] ------gslX680 test_i2c error------
[  128.325077] owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x10013

[  128.325170] gsl_ts_read set data address fail!
[  128.325255] owl_i2c: owl_i2c_fifo_irq(): [i2c1] no ACK, fifostat 0x10013

[  128.325327] gsl_ts_read set data address fail!
[  128.325361] ======int_1st: 0 0 0 0 , int_2nd: 0 0 0 0 ======
```

**Comment by Fourdee** [comment]
cpu temp:
```
/sys/class/thermal/thermal_zone1/temp
```

**Comment by Fourdee** [comment]
## Audio:

HDMI only supports ```S32_LE```
```
speaker-test -c2 -F S32_LE
```

```
root@DietPi:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: atm7059link [atm7059_link], device 0: ATC2603C PCM atc2603c-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: atm7059link [atm7059_link], device 1: HDMI PCM atm7059-hdmi-dai-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: atm7059link [atm7059_link], device 2: SPDIF PCM atm7059-spdif-dai-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PianoDAC [PianoDAC], device 0: PianoDAC pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
```
root@DietPi:~# amixer -c 0 scontrols
Simple mixer control 'Mic0 Mode Mux',0
Simple mixer control 'ADC0 Digital Gain control',0
Simple mixer control 'ADC0 Mux',0
Simple mixer control 'AMP1 Gain boost Range select',0
Simple mixer control 'AOUT FL FR Mixer FL FR',0
Simple mixer control 'AOUT FL FR Mixer FM',0
Simple mixer control 'AOUT FL FR Mixer MIC',0
Simple mixer control 'Adc0 Digital Gain',0
Simple mixer control 'Adc0 Gain',0
Simple mixer control 'DAC Digital FL FR',0
Simple mixer control 'DAC FL FR PLAYBACK',0
Simple mixer control 'DAC FL Gain',0
Simple mixer control 'DAC FR Gain',0
Simple mixer control 'DAC PA',0
Simple mixer control 'DAC PA OUTPUT Stage',0
Simple mixer control 'Dummy earphone detect method',0
Simple mixer control 'Dummy earphone gain',0
Simple mixer control 'Dummy earphone volume',0
Simple mixer control 'Dummy mic Gain',0
Simple mixer control 'Dummy mic mode',0
Simple mixer control 'Dummy mic num',0
Simple mixer control 'Dummy speaker gain',0
Simple mixer control 'Dummy speaker volume',0
Simple mixer control 'External MIC Power Voltage',0
Simple mixer control 'External Mic Power',0
Simple mixer control 'Internal Mic Power',0
Simple mixer control 'PA Output Swing Mux',0
Simple mixer control 'audio output mode switch',0
Simple mixer control 'speaker on off switch',0
```

```
root@DietPi:~# amixer -c 0 sset 'audio output mode switch' 'i2s'
Simple mixer control 'audio output mode switch',0
  Capabilities: enum
  Items: 'i2s' 'hdmi' 'spdif'
  Item0: 'i2s'
```

**Comment by Fourdee** [comment]
WiFi:
- ```iw reg set GB``` no effect
```
root@DietPi:~# iw reg get
country 00: DFS-UNSET
        (2402 - 2472 @ 40), (6, 20), (N/A)
        (2457 - 2482 @ 40), (6, 20), (N/A), NO-IR
        (2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, NO-IR
        (5170 - 5250 @ 80), (6, 20), (N/A), NO-IR
        (5735 - 5835 @ 80), (6, 20), (N/A), NO-IR
        (57240 - 63720 @ 2160), (N/A, 0), (N/A)
```

**Comment by Fourdee** [comment]
## GPU:

- GPU driver: https://github.com/sparkysbc/sparky_sdk/tree/master/ubuntu/gpu/v2

use blacklist to disable GPU modules by default (free up memory):
```
root@DietPi:~# cat /etc/modprobe.d/disable_sparkysbc_gpu.conf
blacklist pvrsrvkm
blacklist drm
blacklist videobuf2_vmalloc
blacklist bc_example
```

```
rm /etc/modprobe.d/disable_sparkysbc_gpu.conf

wget http://dietpi.com/downloads/binaries/sparkysbc/sparkysbc_gpu.7z -O package.7z
7z x -aoa package.7z -o/etc
rm package.7z

chmod +x /etc/sparkysbc_gpu/install.sh
/etc/sparkysbc_gpu/install.sh


#uninstall
/etc/sparkysbc_gpu/install.sh -u
```

```
cat << _EOF_ > /etc/X11/xorg.conf
Section "Device"
        Identifier "Video Device"
        Driver "pvr"
        Option "FlipChain""true"
EndSection

Section "Monitor"
        Identifier "Monitor"
EndSection

Section "Screen"
        Identifier "Screen"
        Monitor "Monitor"
        Device "Video Device"
EndSection
_EOF_
```

```
[    17.377] (WW) Warning, couldn't open module pvr
```

**Comment by Fourdee** [comment]
Looks like we had a corruption on 1st partition of the initial image. Image and partitions has been re-generated and uploaded.

🈯️ Just waiting for confirmation from Paul resolves inability to boot on his system.

**Comment by Fourdee** [comment]
To Do (Many thanks to Jaikumar from Allo for the info):
- 🈯️ Added to website board info | We are using Actions semiconductor S500 chip
- 🈯️ module disabled during patch 142 | owl_i2c msg are related to touchscreen. It can be disabled in kernel config. or blacklist ctp_gsl3680
- 🈯️ Test EMMC | Kernel Image will work for both sdcard & emmc. kernel.dtb is modified to work for both. If the image is built using https://github.com/sparkysbc/Linux.git it can be used for both sdcard & emmc.
- 🈯️ HDMI snd currently only SE32_LE is supported

**Comment by Fourdee** [comment]
- 🈺 Allo Cheapo requires testing | Will test when it arrives
- GPU support, as this SBC is mostly aimed towards Audiophiles and usage, will leave this out for now due to lack of time. Unless, we get significant interest from our users to implement it.

**Comment by Fourdee** [comment]
Completed. Will test Cheapo when it arrives.

**Comment by joaofl** [comment]
@Fourdee 
Could you get USB3 to work full speed on this board?

Because this chip is the same as the one on Roseapple Pi. The issue is that at the armbian distro uses the kernel from lemaker, which does not support USB3.

It seems that the kernel by sparky (the one used here) support USB3... At least there are some commits supposed to fix that.
https://github.com/sparkysbc/Linux/commit/3867b3fd05d2998a5503bb6c72a4946b5580a563

However the sparky does not work on the Roseapple Pi out of the box. Ethernet works, but none of the USB ports work, but I still can't understand why.

**Comment by kotamotov** [comment]
Hi  Fourdee! 
I have one more question. Dietpi can't recognize my I2s DAC AK4495 connected to Sparky SBC+KALI.
What driver I need to install?
Here is my log file:
[    0.982476] pcm512x 2-004c: Failed to reset device: -6
[    0.983003] owl_i2c: owl_i2c_fifo_irq(): [i2c2] no ACK, fifostat 0x20013

[   11.397985] soc-audio soc-audio.1: ASoC: machine PianoDACPlus should use snd_soc_register_card()
[   11.400993] soc-audio soc-audio.1: ASoC: CODEC pcm512x.2-004c not registered
[   11.404418] platform soc-audio.1: Driver soc-audio requests probe deferral

[   11.611566] soc-audio soc-audio.1: ASoC: machine PianoDACPlus should use snd_soc_register_card()
[   11.611632] soc-audio soc-audio.1: ASoC: CODEC pcm512x.2-004c not registered
[   11.611692] platform soc-audio.1: Driver soc-audio requests probe deferral
[   12.128501] soc-audio: probe of soc-audio.1 failed with error -22
