### ISSUE TITLE
Failed to install Docker via software

### ISSUE THREAD

**Issue by martinhannover** [MichaIng/DietPi#7012]
### Creating a bug report/issue
- [ X ] I have searched the existing open and closed issues

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
G_DIETPI_VERSION_CORE=9
G_DIETPI_VERSION_SUB=2
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
bookworm 0
- Kernel version | `uname -a`
`Linux DockerPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
RPi 4 Model B (aarch64)
- Power supply used | (EG: 5V 1A RAVpower)
- SD card used | (EG: SanDisk ultra)

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
Docker
- Was the software title installed freshly or updated/migrated?
fresh install
- Can this issue be replicated on a fresh installation of DietPi?
it is a fresh installation

- Bug report ID | `echo $G_HW_UUID`
217b0638-4db5-48ba-8c73-0cab601f2237

#### Steps to reproduce
Start the installation get in this issue

#### Expected behaviour
complete the installation

#### Actual behaviour
stopping installation with this message:
```
Hit:1 https://deb.debian.org/debian bookworm InRelease
Get:2 https://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 https://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 https://deb.debian.org/debian bookworm-backports InRelease [56.5 kB]
Get:5 https://archive.raspberrypi.com/debian bookworm InRelease [23.6 kB]
Reading package lists...
E: Release file for https://deb.debian.org/debian/dists/bookworm-updates/InRelease is not valid yet (invalid for another 1d 13h 45min 24s). Updates for this repository will not be applied.
E: Release file for https://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet (invalid for another 1d 13h 2min 53s). Updates for this repository will not be applied.
E: Release file for https://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 1d 13h 5min 16s). Updates for this repository will not be applied.
E: Release file for https://deb.debian.org/debian/dists/bookworm-backports/InRelease is not valid yet (invalid for another 1d 13h 45min 23s). Updates for this repository will not be applied.
[FAILED] DietPi-Software | APT update
```

**Comment by MichaIng** [comment]
> is not valid yet (invalid for another 1d 13h 45min 24s)

Your system time is out of sync. Try for for a sync manually:
```sh
/boot/dietpi/func/run_ntpd 1
```

**Comment by Joulinar** [comment]
Maybe the global.pool ntp servers are blocked on the location you are.

**Comment by MichaIng** [comment]
Does a ping to these work, i.e. are they resolved properly?
```sh
ping pool.ntp.org
```

**Comment by MichaIng** [comment]
Marking as closed due to outstanding reply. Feel free to reopen if required.
