### ISSUE TITLE
Dietpi connecting to Chinese sites?

### ISSUE THREAD

**Issue by dr-raypc** [MichaIng/DietPi#7044]
I installed Dietpi on a VM and noticed it was connecting to Chinese websites. I figured that VM may have been compromised so I wiped it and created a new one using DietPi's latest release, however Dietpi is still connecting to Chinese websites. Why is that?

**Comment by MichaIng** [comment]
Which Chinese website in particular do you mean, and at which step?

- Internet connection checks are done at Quad9 DNS service by default (can be changed).
- DNS resolution is done via whatever your DHCP server serves or you configure manually.
- APT updates are done via `deb.debian.org` by default (can be changed).
- Some downloads from GitHub and `dietpi.com` are done at DietPi updates.
- `dietpi.com` is also connected to for the MOTD (can be disabled) and `dietpi-survey` (after installs and updates).

Apart from this, I do not have any other connections in mind, as long as you do not install software which needs to be downloaded from elsewhere, of course.

**Comment by MichaIng** [comment]
I'll mark this as closed due to outstanding reply. Feel free to reopen if required.
