### ISSUE TITLE
Image | ROCK 3C

### ISSUE THREAD

**Issue by keypunch416** [MichaIng/DietPi#7057]
#### Formal device information
- Device name | <Rock 3C>
- Official product URL | <https://docs.radxa.com/en/rock3/rock3c>
- GitHub resource URL (if available) | <https://github.com/radxa-build/rock-3c/releases>
- Image download URL | <https://docs.radxa.com/en/rock3/rock3c/getting-started/download>
The Rock 3C variant I am using has WiFi 6/BT5.4 using a RK3566 like all other Rock 3C designs.  The other variation of the Rock 3C uses WiFi5/BT5.

#### Is the SBC officially supported by the Debian installer?
- unknown, but apt works just fine to install packages

#### If not, is a reliable 3rd party Debian image available for this SBC?
- Yes, Pine Quartz64B CLI only.
- I did not try any DE based image as I only have need for CLI only image.
- via CLI only image I saved about month ago Data/Downloads/DietPi/0902-20240318/DietPi_Quartz64B-ARMv8-Bookworm.img.xz

#### If not, are there install instructions for Debian available?
<Unknown>

There is big hope as an existing DietPi CLI only image is very close to a working Rock 3C image.  My interest is for CLI only.

Today I used a DietPi V9.2 Pine Quartz64B CLI only image that was near perfect to use.  I used the DietPi V9.2 image as what I saw today when check was not many bug changes for V9.3.  Despite imaging the V9.2 image to SD card the V9.2.1 image updated to V9.3.0.  Near perfect to use means other than inxi showing as "ARM System: Pine64 RK3566 Quartz64-B Board details: N/A serial: 427ed4ab84d91732 CPU:", no HDMI CL:I console, and only one (fine there is only one). dtb file "rk3566-quartz64-b.dtb".  i2cdetect detected a number of I2C channels which is great.  ssh worked just fine as as expected.

I do not know if the boot/uboot is such that will only load the "rk3566-quartz64-b.dtb" file by name or not.  If so could one try using a Rock 3C .dtb as test using the "rk3566-quartz64-b.dtb" file name just as test?  I do not know if the  Data/Downloads/DietPi/0902-20240318/DietPi_Quartz64B-ARMv8-Bookworm.img.xz image on an actual Pine Quartx64B HDMI the CLI would work but my hope is would.  Ideally the HDMI needs to work for CLI as very important to ebable one to see and/or correct any boot issues created by one (like me) than sometimes makes changes to files that can cause the boot to halt part way though or wants a ctrl-d to continue so one can check and/or correct the error or typo made that caused the boot to be incomplete including when systemd is not "happy'.

I installed a number of packages, such as lftp, inxi, lm-sensors, screen, sysbench, et al that all installed just fine and worked just great.  I just installed CLI based packages.  I have no intent to use GUI.

I did not try to use WiFi 6 nor BT 5.4 with the Data/Downloads/DietPi/0902-20240318/DietPi_Quartz64B-ARMv8-Bookworm.img.xz.  For my use case I will not need BT.  I will likely will use USB based WiFi adapter for distance need to connect between.  I do not think the on board PCB antenna will be sufficient for the WiFi6.  I will try the WiFi 6 at some point just to see as WiFi 6 has certain advantages.  I did not have the Rock 3C located the typical distance.  My routers are only WiFi5 at best.  I have found WiFi4 to far more stable and longer distance than WiF5.  Hence, I run my routers in WiFi4. I only use WiFi when I cannot run Ethernet cable to the networking device.  I try to use Ethernet connection rather than WiFi for any network connection and have for years.

Please note the Radxa Rock 3C CLI images is not suitable as base in my opinion let alone for months.  Radxa has not addressed the known issue Radxa has stated with current B39 Rock 3C release.  The stated issue ongoing since 10 January 2024 B39 release is `Currently there is an issue preventing the Debian CLI image from booting`  

Supporting information in attached file [Rock3C-Via-Quartz64BCLI-Image-20240503.console.txt](https://github.com/MichaIng/DietPi/files/15205800/Rock3C-Via-Quartz64BCLI-Image-20240503.console.txt)

**Comment by maxun** [comment]
Hi,
I just wanted to share my experience about this: after reading your request, I tried the DietPI Quartz64B image 9.3 on my rock-3c and it actually worked much better than I was expecting.
I got hdmi console output at first boot, I installed a few things to try. After reboot I am not seeing the console anymore on my screen however since I installed and enabled a desktop environment I was quite surprised to see that the desktop is working:

![screenshot](https://github.com/MichaIng/DietPi/assets/527928/f010256e-23f5-45fd-872e-bbf3342c2aff)

Not everything is perfect. I am getting random freeze when using the GUI and the wifi card is not recognized but after searching for an alternative os of my board I am very happy.
