### ISSUE TITLE
Motioneye Telegram notification error

### ISSUE THREAD

**Issue by Marzal** [MichaIng/DietPi#7083]
### Creating a bug report/issue
- [x] I have searched the existing open and closed issues

#### Required Information
- DietPi version | `9.4.2`
- Distro version | `bookworm 0`
- Kernel version | `Linux Diet3Adri 6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux
`
- SBC model | `RPi 3 Model A+ (aarch64)`
- Power supply used | `5V 1A`
- SD card used | `2GB Transcend`

#### Additional Information (if applicable)
- Software title | `motioneye`
- Was the software title installed freshly or updated/migrated? `Freslhy`
- Can this issue be replicated on a fresh installation of DietPi? `Yes`

#### Steps to reproduce
1. Configure Telegram notification
2. Push Test

#### Actual behaviour
- `77, 'error setting certificate verify locations:\n CAfile: /etc/pki/tls/certs/ca-bundle.crt\n CApath: none')`

#### Extra details
- Upstream https://github.com/motioneye-project/motioneye/issues/2962
- Workarounds: https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url
  -  `mkdir -p /etc/pki/tls/certs ; ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt`

**Comment by MichaIng** [comment]
A bug in latest `pycurl`. Please try the workaround I posted in the motionEye issue you linked. I'll close this here to avoid double-posting.
