### ISSUE TITLE
Cant install Netdata

### ISSUE THREAD

**Issue by bong101** [MichaIng/DietPi#7132]
### Creating a bug report/issue
- [ x] I have searched the existing open and closed issues

#### Details:
- Date           | Fri Jun 28 10:23:54 CEST 2024
- Bug report     | 7b2fd194-9d75-4846-9bcd-eaccbae9b556
- DietPi version | v9.5.1 (MichaIng/master)
- Image creator  | 
- Pre-image      | 
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux zanbar 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
- Distro         | bookworm (ID=7,RASPBIAN=0)
- Command        | `apt-get -y --allow-change-held-packages install netdata`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
netdata-core : Depends: libuv1 (>= 1.4.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Joulinar** [comment]
can you share following

```
apt show libuv1
```

**Comment by bong101** [comment]
dietpi@zanbar:~$ apt show libuv1 -a
Package: libuv1
Version: 1.44.2-1+deb12u1
Priority: optional
Section: libs
Maintainer: Dominique Dumont <dod@debian.org>
Installed-Size: 305 kB
Depends: libc6 (>= 2.34)
Homepage: https://github.com/libuv/libuv
Download-Size: 130 kB
APT-Sources: https://deb.debian.org/debian-security bookworm-security/main arm64 Packages
Description: asynchronous event notification library - runtime library

Package: libuv1
Version: 1.44.2-1
Priority: optional
Section: libs
Maintainer: Dominique Dumont <dod@debian.org>
Installed-Size: 309 kB
Depends: libc6 (>= 2.33)
Homepage: https://github.com/libuv/libuv
Tag: role::shared-lib
Download-Size: 133 kB
APT-Sources: https://deb.debian.org/debian bookworm/main arm64 Packages
Description: asynchronous event notification library - runtime library

**Comment by bong101** [comment]
dietpi@zanbar:~$ apt show libuv1
Package: libuv1
State: pas un véritable paquet (virtuel)
N: Impossible de choisir une version candidate du paquet « libuv1 » qui n'en n'a pas
N: Il y a 2 enregistrements supplémentaires. Veuillez utiliser l'opérande « -a » pour les voir.
N: Aucun paquet n'a été trouvé

**Comment by Joulinar** [comment]
are you able to install that package manually?

```
apt install libuv1
```

**Comment by bong101** [comment]
No, I can't install it manually
```

sudo apt install libuv1
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Aucune version du paquet libuv1 n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

E: Le paquet « libuv1 » n'a pas de version susceptible d'être installée
```

**Comment by MichaIng** [comment]
Weird, there are two "real" variants of `libuv1`, but the system seems to try to install another "virtual" one, i.e. a version or variant which is not really in any repo, but only listed as dependency, recommendation, dependency, conflict or similar.

We would expect the "real" variant from the Debian security repo to be installed: https://packages.debian.org/bookworm/libuv1

Can you show:
```sh
apt policy libuv1
```

**Comment by bong101** [comment]
```
dietpi@zanbar:~$ apt policy libuv1
libuv1:
  Installé : (aucun)
  Candidat : (aucun)
 Table de version :
     1.44.2-1+deb12u1 -30000
        500 https://deb.debian.org/debian-security bookworm-security/main arm64 Packages
     1.44.2-1 -30000
        500 https://deb.debian.org/debian bookworm/main arm64 Packages
```

**Comment by MichaIng** [comment]
Both packages have a priority of `-30000`, hence someone or something create APT pins to make pretty clear that those must never be installed, for whatever reason 😄.

Please check related configs:
```sh
for i in /etc/apt/preferences{,.d/*}
do
[[ -f "$i" ]] || continue
echo "$i:"
cat "$i"
done
```

**Comment by bong101** [comment]
```
dietpi@zanbar:~$ 

for i in /etc/apt/preferences{,.d/*}
do
[[ -f "$i" ]] || continue
echo "$i:"
cat "$i"
done

/etc/apt/preferences.d/apt-listbugs:

Explanation: Pinned by apt-listbugs at 2024-06-28 10:05:28 +0200
Explanation:   #1058743: libuv1: FTBFS on s390x on older kernels
Package: libuv1
Pin: version *
Pin-Priority: -30000

```

**Comment by bong101** [comment]
thanks for your help !!

**Comment by bong101** [comment]
It works, thanks

**Comment by MichaIng** [comment]
Okay great. I'll mark this issue as closed then. Feel free to reopen when required.
