### ISSUE TITLE
Dietpi-banner displays garbled RAM usage

### ISSUE THREAD

**Issue by Krik658** [MichaIng/DietPi#7147]
Duplicate of #7107 
Didn't see that before :(

### Creating a bug report/issue
- [x] I have searched the existing open and closed issues

#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
```
G_DIETPI_VERSION_CORE=9
G_DIETPI_VERSION_SUB=5
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
```

- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
```
bookworm
```

- Kernel version | `uname -a`
```
Linux krux 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
```

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
```
$ echo $G_HW_MODEL_NAME
Native PC (x86_64)
```
Intel N100 MiniPC with 16 GB RAM

#### Additional Information (if applicable)
- Can this issue be replicated on a fresh installation of DietPi?
Yep.

#### Steps to reproduce
Login via ssh.
Read memory info.

#### Expected behaviour
It should always show 15.75 GB (w/o video memory in my case)

#### Actual behaviour
The conversion of numbers leads to garbled output.

#### Extra details
```
 ─────────────────────────────────────────────────────
 DietPi v9.5.1 : Update available
 ─────────────────────────────────────────────────────
 - Device model : Native PC (x86_64)
 - Uptime : up 23 minutes
 - CPU temp : 57 °C / 134 °F : Running warm, but safe
 - RAM usage : 13402 of 1702 MiB (787%)
 - Disk usage (RootFS) : 3,2G of 917G (1%)
 ─────────────────────────────────────────────────────

 dietpi-update   : Run now to update DietPi from v9.5.1 to v9.6.1

```

The error is in https://github.com/MichaIng/DietPi/blob/master/dietpi/func/dietpi-banner, line 259. I think the values are too big to be displayed correctly.

Original: `free -b | mawk 'NR==2 {CONVFMT="%.0f"; print $3/1024^2" of "$2/1024^2" MiB ("$3/$2*100"%)"}'`
Output: `13355 of 1747 MiB (765%)`

### Possible solutions

Human readable format, converts to Mi or Gi depending on values but there's no space between value and unit
Code: `free -h | mawk 'NR==2 {CONVFMT="%.0f"; print $3" of "$2" ("$3/$2*100"%)"}'`
Output: `1,7Gi of 15Gi (11%)`

Or force MiB, looks pretty enough
Code: `free -m | mawk 'NR==2 {CONVFMT="%.0f"; print $3" MiB of "$2" MiB ("$3/$2*100"%)"}'`
Output: `1725 MiB of 15770 MiB (11%)`

I assume the `-h` and `-m` parameters are available on the arm version of `free` but I don't know that for sure.

**Comment by MichaIng** [comment]
@Krik658 
What does `free -b` show?
