### ISSUE TITLE
DNS error in DietPi system

### ISSUE THREAD

**Issue by Ruslan-Musatov** [MichaIng/DietPi#7179]
![iJ9W1FMWPgM](https://github.com/user-attachments/assets/20708857-9a1d-4a17-8126-293a6070b447)

The error in the image shows that the DietPi system failed to ping to the 8.8.8.8.8 address (Google's DNS server), resulting in 100% packet loss. This indicates a problem with the network connection. Let's take a closer look at the possible causes and actions you can take to fix this problem.
No DNS is being pinged .
What could be the problem?

**Comment by Joulinar** [comment]
Please use English as non of us speaks Russian. Therefore I translate your post using DeepL

To your problem. This has nothing to do with DNS. It's simple ping check to verify basic internet connection. Ensure you are able to access the internet. Depending on your Geo location, Google DNS server IP might not be reachable.

**Comment by Ruslan-Musatov** [comment]
I use a Rock 4 Model C+ microcomputer, it's the same as the Raspberry Pi 4 model B. These are the settings I made in the file dietpi.txt:
AUTO_SETUP_NET_USESTATIC=1
AUTO_SETUP_NET_STATIC_IP=192.168.137.100
AUTO_SETUP_NET_STATIC_MASK=255.255.255.0
AUTO_SETUP_NET_STATIC_GATEWAY=192.168.137.1
AUTO_SETUP_NET_STATIC_DNS=9.9.9.9 149.112.112.112
I use isernet to transfer the network to a micro computer. I am transmitting it from my PC using an adapter. These are the settings I have for network transmission.
![MKnoiXoVBhA](https://github.com/user-attachments/assets/227c9a7c-94d6-43b0-b2c9-09098c78de3f)

**Comment by Ruslan-Musatov** [comment]
> I use a Rock 4 Model C+ microcomputer, it's the same as the Raspberry Pi 4 model B. These are the settings I made in the file dietpi.txt: AUTO_SETUP_NET_USESTATIC=1 AUTO_SETUP_NET_STATIC_IP=192.168.137.100 AUTO_SETUP_NET_STATIC_MASK=255.255.255.0 AUTO_SETUP_NET_STATIC_GATEWAY=192.168.137.1 AUTO_SETUP_NET_STATIC_DNS=9.9.9.9 149.112.112.112 I use isernet to transfer the network to a micro computer. I am transmitting it from my PC using an adapter. These are the settings I have for network transmission. ![MKnoiXoVBhA](https://private-user-images.githubusercontent.com/166721463/355022430-227c9a7c-94d6-43b0-b2c9-09098c78de3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDgyMzMsIm5iZiI6MTcyMjg0NzkzMywicGF0aCI6Ii8xNjY3MjE0NjMvMzU1MDIyNDMwLTIyN2M5YTdjLTk0ZDYtNDNiMC1iMmM5LTA5MDk4Yzc4ZGUzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwODUyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWQ3YzAwYTY4ZWEwODMzZWFjNjVkOTljNTUyMTZmODc1MWY3NTllZTg3MzZiZTFjM2IwODlmZGE3ZmEzODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PI7pw2mu07Zia8m-CFW16ZA3L8fWqiCarLcQamzJWAE)

![image](https://github.com/user-attachments/assets/b84e3060-07be-4a88-94b0-177fa068fe47)
the izernet 2 network is connected to Rock 4, it says without an internet connection, can this affect my error?

**Comment by MichaIng** [comment]
You solved it? If Ethernet 2 is connected to the SBC, then it is normal that it shows "no Internet", as this is only shown on those adapters, where the PC itself has Internet access through. Important is the other one, and that it is a shared Internet correction.
