### ISSUE TITLE
DietPi-Software | motionEye

### ISSUE THREAD

**Issue by lodgnewt** [MichaIng/DietPi#718]
Please add motionEye https://github.com/ccrisan/motioneye/
motionEye is the web user interface (the frontend) that you access with your browser to manage your camera(s).
Installation https://github.com/ccrisan/motioneye/wiki/Installation

**Comment by Fourdee** [comment]
- Online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=100#p6610

**Comment by Fourdee** [comment]
Excellent peice of software, impressive.

**Comment by Fourdee** [comment]
Commit:
https://github.com/Fourdee/DietPi/commit/324b6b8dfd64363abc687d3a51d7f7ba58ba0eda

Completed.

**Comment by lodgnewt** [comment]
Thank you very much!

**Comment by Invictaz** [comment]
@Fourdee is it possible to use all sorts of USB camera's?

**Comment by Fourdee** [comment]
@Invictaz 

> Fourdee is it possible to use all sorts of USB camera's?

Yep, as far as i'am aware any standard USB camera should (untested) work with Motion Eye.

**Comment by Sirse** [comment]
Why i can't install MotionEYE on Orange Pi One/PC?
UPD: MotionEyeOS unsupports OrangePI, but it can be installed on armbian (https://forum.armbian.com/index.php?/topic/2168-motioneye-opi/).
I will try install it manually today.

**Comment by Sirse** [comment]
It installs on Orange PI, web interface works, service are handled by DietPI, but motion don't work:
```
motion -h
motion: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
```
I don't can find, how to install required libs =(

*Required modules for stock OrangePI cam:
gc2035
vfe_v4l2
*

**Comment by anselal** [comment]
There is no picture after refreshing the web interface, although the camera is still active according to the camera's led.
Is this a motioneye bug or a dietpi bug ?

It worked great on motioneyeos

**Comment by MichaIng** [comment]
@anselal 
Hmm, we install it according to official instructions and do no custom settings changes, so on first view I would say a MotionEye but.

Was this a fresh install or did it suddenly appear?
Which device you are running this?

Update it: `pip install -U motioneye; systemctl restart motioneye`
Check service logs right after issue occurs: `systemctl -u motioneye`

And since this is in web UI, did you check the browser console for any errors?

**Comment by anselal** [comment]
It is a fresh install running on my RPi2. I use the 5MP camera module

**Comment by githlp** [comment]
in case you activate this

`local_time_file /etc/localtime`

in /etc/motioneye/motioneye.conf

then the motioneye.service on DietPi is broken:

`sudo journalctl -u motioneye`
...
DietPi meyectl[507]:  ImportError: no module named pytz

it cannot load, although i installed pytz as user with pip/pip2. In python shell the pytz module can be loaded though..

**Comment by MichaIng** [comment]
Assure that the module is installed globally by running the pip install as root: `sudo pip2 install -U pytz`
