### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#72]
http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=89&p=320#p315

**Comment by Fourdee** [comment]
I've planned to add a "toggle" in DietPi-Config, between ipv4 and ipv6. 

In the mean time...
IPv6 can be enabled in all DietPi images, by running the following code:

> rm /etc/modprobe.d/blacklist-ipv6.conf &> /dev/null
> sed -i "/net.ipv6.conf.all.disable_ipv6 /c\net.ipv6.conf.all.disable_ipv6 = 0" /etc/sysctl.conf
> sed -i "/net.ipv6.conf.default.disable_ipv6 /c\net.ipv6.conf.default.disable_ipv6 = 0" /etc/sysctl.conf
> sed -i "/net.ipv6.conf.lo.disable_ipv6 /c\net.ipv6.conf.lo.disable_ipv6 = 0" /etc/sysctl.conf

**Comment by Fourdee** [comment]
Does anyone have a IPv6 local network and willing to run some tests for DietPi?

Please run the following to enable IPv6:

> rm /etc/modprobe.d/blacklist-ipv6.conf &> /dev/null
> sed -i "/net.ipv6.conf.all.disable_ipv6 /c\net.ipv6.conf.all.disable_ipv6 = 0" /etc/sysctl.conf
> sed -i "/net.ipv6.conf.default.disable_ipv6 /c\net.ipv6.conf.default.disable_ipv6 = 0" /etc/sysctl.conf
> sed -i "/net.ipv6.conf.lo.disable_ipv6 /c\net.ipv6.conf.lo.disable_ipv6 = 0" /etc/sysctl.conf
> reboot

Then run dietpi-config. Test DHCP and STATiC networking options, then report back any issues.

**Comment by audy** [comment]
Worked for me using DCHP (didn't test static).

``` bash
$ uname -a
Linux DietPi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
```

**Comment by MuJJus** [comment]
worked for me

**Comment by Fourdee** [comment]
@audy @MuJJus 
Thanks guys.

I will begin to integrate this into DietPi-Config as a toggle option.

**Comment by Fourdee** [comment]
Completed. Integrated into DietPi-Config as a toggle option. Available in next release (v107):
![1](https://cloud.githubusercontent.com/assets/7077026/12379172/9c8ded9c-bd4c-11e5-9a9c-9e48e50b4a22.png)

**Comment by MuJJus** [comment]
Want DHCPv6 support
`iface eth0 inet6 dhcp`
in /etc/network/interfaces

EUI-64 address is too long and no privacy

**Comment by Fourdee** [comment]
IPv6 is now enabled by default on all DietPi systems, see link for explanation:
https://github.com/Fourdee/DietPi/issues/175

**Comment by Fourdee** [comment]
@MuJJus 

```
Want DHCPv6 support
iface eth0 inet6 dhcp
in /etc/network/interfaces

EUI-64 address is too long and no privacy
```

Unfortunately, I do not have access to any IPv6 networks that would allow me to test and implement this correctly into DietPi.
Your request will have to wait until the above is available.
