### ISSUE TITLE
[RPi 3 Model B] Boot freezes on start/restart with connected USB-DAC

### ISSUE THREAD

**Issue by kw-sudo** [MichaIng/DietPi#7212]
Hi,

I have just installed my RPi3 from the scratch as a test and failed with an 'Audio issue'.

Headless installation on SSD (no microSD), works basically flawless. Only MPD, myMPD, ALSA-utils installed.

When booting or restarting the RPi3 with connected SSD and USB-A (external amplifier/DAC), the boot sequence freezes after a few seconds. Not pingable, no ssh access.

After turning off the power and unplugging the DAC, it boots normally from SSD. I can then plug the DAC in again. The DAC itself is also recognized (aplay -l) and plays music via mpMPD without errors. Just that 'boot thing'.

There are no further bugs or hints.

#### Required Information
G_DIETPI_VERSION_CORE=9
G_DIETPI_VERSION_SUB=7
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
Bookworm 0
`Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
RPi 3 Model B
PS 5V 2,5A
external SSD SanDisk Ultra 3D 250GB 
DAC: nubert ampX
####

If there is any information missing that I don't know what you need, please let me know.

**Comment by MichaIng** [comment]
This is most likely a voltage issue, with the RPi drawing more voltage at boot with `initial_turbo` (maxed frequency) and high processing, and then the USB power draw kicking in with some peak on init.

Is there some output on the screen, in case what are the last lines?

Is the the official RPi PSU or a different one? If you have a 3A PSU, probably try with that one, to test/role out my guess.
