### ISSUE TITLE
Add support for software raid (mdadm) in drive manager and software installer

### ISSUE THREAD

**Issue by libf-de** [MichaIng/DietPi#723]
I'm using my Odroid XU4 with DietPi as a NAS server as probably many people do, storing my data on two USB3.0 2TB HDDs configured as raid1. But unfortunaly DietPi does not support that, so I have to configure it myself (which is not the problem) but then it does not work as good as a "single" harddisk would with the DietPi software. It would be nice to see raid support in DietPi :)

**Comment by Fourdee** [comment]
Marking as closed due to lack of interest from our community and no progress.
