### ISSUE TITLE
Add kernel setting required by cilium envoy on raspberrypi

### ISSUE THREAD

**Issue by vacquah** [MichaIng/DietPi#7232]
When installing cilium envoy as a daemonset on raspberrpi (CM4) , it fails due to a missing kernel settings`CONFIG_ARM64_VA_BITS_48`.   I think it is set to 39 by default.

Please the discussion [here](https://github.com/raspberrypi/linux/issues/5354) for more details.

Typical error message produced when attempting to install the cilium envoy daemonset on a raspberrypi CM4 is:

```
external/com_github_google_tcmalloc/tcmalloc/system-alloc.cc:625] MmapAligned() failed - unable to allocate with tag (hint, size, alignment) - is something limiting address placement? 0x361300000000 1073741824 1073741824 @ 0x559866ff44 0x559866c2c8 0x559866bc54 0x559864b4c0 0x5598669948 0x559866971c 0x5598640c88 0x559855a360 0x5598559094 0x7fb1ae754c
external/com_github_google_tcmalloc/tcmalloc/arena.cc:58] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size); is something preventing mmap from succeeding (sandbox, VSS limitations)? 131072 632 @ 0x55986702b4 0x559864b550 0x5598669948 0x559866971c 0x5598640c88 0x559855a360 0x5598559094 0x7fb1ae754c

```

**Comment by MichaIng** [comment]
The issue at the RPi kernel repo is the right place already. Please contribute to that one, since it seems stable since a year.
