### ISSUE TITLE
[software update request] new update is available for Vaultwarden

### ISSUE THREAD

**Issue by yuukiAme** [MichaIng/DietPi#7239]
Hi,

Can you guys update the repo and compile the newest version of Vaultwarden?
Thank you very much
[Release note](https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.1) for version 1.32.1.

**Comment by MichaIng** [comment]
Just done :)

**Comment by yuukiAme** [comment]
Thank you very much. Quickly as always :)

**Comment by MichaIng** [comment]
v1.32.2 build is already running, just in case one might ask 😉: https://github.com/MichaIng/DietPi/actions/runs/11327418865

**Comment by yuukiAme** [comment]
@MichaIng 
New CVE in Vaultwarden v1.32.3. 
Could you please update the Vaultwarden to v1.32.4 as soon as possible?
Thank you very much.

**Comment by sonnatager** [comment]
When i try to update vaultwarden, it says always i am up to date:
![image](https://github.com/user-attachments/assets/a97eb7e9-4d43-4b16-bc98-c30f99cebe21)

**Comment by Joulinar** [comment]
Yes as well need to build a new package first

**Comment by sonnatager** [comment]
I saw you have triggered a new run for vaultwarden: https://github.com/MichaIng/DietPi/actions/runs/11774771490

That means, a new package is available?

So when i run
`apt update`
`apt upgrade vaultwarden
`
there should be a new update?

I have an Odroid N2 (aarch64)

**Comment by Joulinar** [comment]
No, packages are stored within testing directory only. Like "[https://dietpi.com/downloads/binaries/bookworm/testing](https://dietpi.com/downloads/binaries/bookworm/testing/)

We would need to move them to production still. Something @MichaIng need to do.

**Comment by MichaIng** [comment]
Just done, please test whether everything works fine for you with the new version.

**Comment by yuukiAme** [comment]
@MichaIng 

"another one" in DJ Khaled's voice

[v1.32.5](https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.5) fixes further CVE.

Could you please update Vaultwarden again? 

Thank you very much.

**Comment by MichaIng** [comment]
No need to ping us here each time. I am subscribed to vaultwarden releases, and trigger builds as fast as I have access to GitHub: https://github.com/MichaIng/DietPi/actions/runs/11892355002

**Comment by Joulinar** [comment]
once package is available on our package servers, you can use regular Debian `apt` command like

```
apt update
```
