### ISSUE TITLE
Switch to zsh shell

### ISSUE THREAD

**Issue by oxoocoffee** [MichaIng/DietPi#7256]
#### Is your feature request related to a problem? Please describe:

- I like to switch to zsh shell from default bash since it is my prefered shell

#### Describe the solution you'd like:

- Installing and switching default shell works. But looks like all the aliases from  /etc/bashrc.d and specifically dietpi.bash needs to be "sourced".

#### Describe alternatives you've considered:

- None

#### Additional context

- none

**Comment by MichaIng** [comment]
I'll close it in favour of this existing request: https://github.com/MichaIng/DietPi/discussions/6118
