### ISSUE TITLE
[dupe] PINE64 | Upgrading the firmware breaks DietPi tools

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#726]
After using the provided menu option to upgrade the Firmware to the latest version, following the reboot the DietPi shortcuts no longer work:

`# dietpi-config`
`-bash: /DietPi/dietpi/dietpi-config: No such file or directory`

The /DietPi/ folder is actually empty!

**Comment by Fourdee** [comment]
@midwan 

Thanks, i'll take a look. 

I'll mark this one as closed (dupe) and use the other ticket: https://github.com/Fourdee/DietPi/issues/719

**Comment by Fourdee** [comment]
Unable to replicate:
```
root@DietPi:~# uname -a
Linux DietPi 3.10.104-2-pine64-longsleep #113 SMP PREEMPT Thu Dec 15 21:46:07 CET 2016 aarch64 GNU/Linux

root@DietPi:~# ls -lha /DietPi
total 36K
drwxrwxrwt  3 root root  160 Jan 23 12:36 .
drwxr-xr-x 20 root root 4.0K Jan 22 14:53 ..
-rwxr-xr-x  1 root root 4.7K Jan 23 12:36 boot.ini
-rwxr-xr-x  1 root root 2.0K Jan 23 12:36 config.txt
drwxr-xr-x  5 root root  880 Jan 23 12:36 dietpi
-rwxr-xr-x  1 root root 8.6K Jan 23 12:36 dietpi.txt
-rw-r--r--  1 root root    2 Jan 23 12:36 .ramdisk
-rwxr-xr-x  1 root root  169 Jan 23 12:36 uEnv.txt

```

Must be linked to issue: https://github.com/Fourdee/DietPi/issues/719
