### ISSUE TITLE
ddns with IPv4 and IPv6

### ISSUE THREAD

**Issue by LOGIN-TB** [MichaIng/DietPi#7278]
### Creating a feature request
in DDNS Config Menue (dietpi-ddns) we have 3 Options:

IPv4 : Force IPv4 usage for the DDNS update (best compatibility)
IPv6or4 : Do not force any IP family for the DDNS update
IPv6    : Force IPv6 usage for the DDNS update (for modern clients) 

It would be great to have the option to activate both protocols for ddns!

#### Is your feature request related to a problem? Please describe:
In these times it is very helpful if the hosted Servers are available through IPv4 and IPv6

#### Describe the solution you'd like:
Maybe its helpful to have a 4th option with IPv4 and IPv6 and a fallback to IPv4 if IPv6 is not available

#### Describe alternatives you've considered:
n/a

#### Additional context
n/a

Please consider to implement this feature.
Thanks
Holger

**Comment by MichaIng** [comment]
Good day Holder! You mean to update both, IPv4 + IPv6 (if possible)? Makes sense: "IPv6and4". We could then do the IPv4 request first, and allow the IPv6 request afterwards to fail, if either the system does not even have an IPv6 address, or the DDNS server is not reachable via IPv6, or it does not accept to add an IPv6 address to the DNS entry.

**Comment by LOGIN-TB** [comment]
Hi Micha,

Yes. This is exactly what I mean.  Update v4 and afterwards v6 with the option to fail. Sounds great,

Holger

**Comment by MichaIng** [comment]
I implemented it just now: #7309
