### ISSUE TITLE
rPI 4 and 5 VM images

### ISSUE THREAD

**Issue by oxoocoffee** [MichaIng/DietPi#7304]
#### Formal device information
- Device name | Mac Book Pro M4
- Official product URL | https://mac.getutm.app
- GitHub resource URL (if available) | 
- Image download URL | 

#### Is the SBC officially supported by the Debian installer?
- Yes

#### If not, is a reliable 3rd party Debian image available for this SBC?
- ...

#### If not, are there install instructions for Debian available?

I see various VM images provided [RC/VM](https://dietpi.com/#download). I have Parallels and UTM on my M4. 
Would it be possible to provide VM image for aarch64 vs only x86_64?
Any plans to do it other, or instructions how to make one for either VM software?

**Comment by MichaIng** [comment]
Closing it in favour of this existing request #5637
I currently do not have the time to start with this, but the issue contains some hints about how it can be implemented.
