### ISSUE TITLE
Error on Sonarr v3 to v4

### ISSUE THREAD

**Issue by tellice** [MichaIng/DietPi#7321]
i have updated to version 9.9.0 of DietPi and migration Sonarr from v3 to v4

When using the internal updater for Sonarr, i get the following error
Cannot install update because startup folder '/opt/sonarr' is not writable by the user 'sonarr'.

I have checked permissions on the folder and all child files and folders, and all have the correct permissions

any ideas?

**Comment by tellice** [comment]
I have also uninstalled sonarr and reinstalled it again

**Comment by MichaIng** [comment]
Thanks for reporting. The installer sets:
```sh
install_dir='/opt/sonarr'
...
chown -R sonarr:dietpi /mnt/dietpi_userdata/sonarr "$install_dir"
```
Do you see the last command with correct `/opt/sonarr` as last argument in your install/reinstall output?

I'll also try to replicate it.

**Comment by MichaIng** [comment]
I found it. We missed to update the path within the systemd unit. Fixed with: https://github.com/MichaIng/DietPi/commit/c7a3411

To fix it for you now:
```sh
sudo sed -i 's|/usr/lib/sonarr|/opt/sonarr|' /etc/systemd/system/sonarr.service
sudo systemctl daemon-reload
sudo systemctl restart sonarr
```
I'll ship a live path to fix it within `dietpi-software`.

**Comment by tellice** [comment]
Thats great, i tried the fix but it didnt work. I had to apply the live patch and reintall Sonarr. But it is now all working and updates great.

**Comment by MichaIng** [comment]
Thanks for testing it ASAP. No idea why the commands did not work for you, but more importantly the live patch did.
