### ISSUE TITLE
Sonarr v4 fail to start after upgrade  to dietpi v9.9

### ISSUE THREAD

**Issue by doopler** [MichaIng/DietPi#7326]
i did an upgrade of sonarr from v3 to v4 via `dietpi-software reinstall 144`
and also removed mono.
and now it failed to start 
here are my logs:
```
root@DietPi  /opt/sonarr  systemctl status sonarr.service
● sonarr.service - Sonarr (DietPi)
     Loaded: loaded (/etc/systemd/system/sonarr.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/sonarr.service.d
             └─dietpi-services_edit.conf
     Active: failed (Result: exit-code) since Thu 2024-12-26 13:19:35 IST; 25s ago
    Process: 547750 ExecStart=/opt/sonarr/Sonarr -nobrowser -data=/mnt/dietpi_userdata/sonarr (code=exited, status=226/NAMESPACE)
   Main PID: 547750 (code=exited, status=226/NAMESPACE)
        CPU: 28ms


Dec 26 13:19:32 DietPi systemd[1]: sonarr.service: Scheduled restart job, restart counter is at 3.
Dec 26 13:19:35 DietPi systemd[1]: Stopped Sonarr (DietPi).
Dec 26 13:19:35 DietPi systemd[1]: sonarr.service: Start request repeated too quickly.
Dec 26 13:19:35 DietPi systemd[1]: sonarr.service: Failed with result 'exit-code'.
Dec 26 13:19:35 DietPi systemd[1]: Failed to start Sonarr (DietPi).
```
```
sonarr.service: Failed to set up mount namespacing: /run/systemd/unit-root/usr/lib/sonarr: No such file or directory
sonarr.service: Failed at step NAMESPACE spawning /opt/sonarr/Sonarr: No such file or directory
```
BTW i'm sill on debian 11 if that matters

thanks

**Comment by doopler** [comment]
as it turns out sonarr was installed in /opt/Sonarr and not in /opt/sonarr/Sonarr
so i changed the path and it worked.
but i lost al the v3 DB and had to re configure from scrach ☹️

**Comment by MichaIng** [comment]
`dietpi-software` installs Sonarr v4 to `/opt/sonarr`. How did you originally install and migrate it?

On a test migration I also lost the one test series I added. Sonarr docs state that I attempts to migrate as much as possible and also firat startup logs show a database migration. So I also was confused. However one can import everything from the download directory structure, at least.

**Comment by doopler** [comment]
yep thats what i eventually ended up doing.

> dietpi-software installs Sonarr v4 to /opt/sonarr. How did you originally install and migrate it?
i installed v3  a while ago via `dietpi-software` as i also did this time (v4).
but it was installed in /`opt/sonarr/Sonarr` thats why i got this error.

regarding the database i did a manual backup before the upgrade an after  i got sonarr to start in was a blank database, so i tried to restore from a backup but it hanged so i had to completely reinstall it and manually add al the shows from scratch.
