### ISSUE TITLE
DietPi-Services | Add support for custom services from file

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#740]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=1262&p=5349#p5345

**Comment by Fourdee** [comment]
include file = ```/DietPi/dietpi/.dietpi-services_include```

example usage:
```
service1
myservice
anotherservice
service_four
```

**Comment by Fourdee** [comment]
Available for v144, can be tested now with:

```
wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/dietpi/dietpi-services -O /DietPi/dietpi/dietpi-services
```

- Then create include file as per: https://github.com/Fourdee/DietPi/issues/740#issuecomment-276068522
- Give DietPi control of services: 
```
dietpi-services disable
dietpi-services restart
```

**Comment by k-plan** [comment]
Tested, works with `rpimonitor-helper` on NanoPi Neo. 👍 

Hope, no need any more to manually edit  `/DietPi/dietpi/dietpi-services` every time I make a `dietpi-update` . 😃

**Comment by Fourdee** [comment]
@k-plan 

Excellent, thanks 👍 . Will mark as completed.

**Comment by k-plan** [comment]
Nice.

Sorry, but now it's time to make some documentation for `dietpi-services`

Perhaps you could please drop some lines into your forum, like for `dietpi-cron` or `dietpi-process_tool`

http://dietpi.com/phpbb/viewtopic.php?f=8&t=5

```
 root@NanoPi-Neo:~# dietpi-services -help

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: -help
 Please wait...


DietPi-Services
Available commands: start / stop / restart / enable / disable
```

**Comment by Fourdee** [comment]
@k-plan 

> Perhaps you could please drop some lines into your forum, like for dietpi-cron or dietpi-process_tool

😉

**Comment by thechildofroth** [comment]
Thanks for this, sadly doesn't seem to work for gmediarender at the moment (although just as likely to be user error as a real issue)

**Comment by studioai** [comment]
Works fine on XU4.

List of daemons I added

- Tonido
- couchpotato
- gitea

**Comment by Fourdee** [comment]
Completed: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=5393#p5393
