### ISSUE TITLE
DietPi-Config | Ondemand geovernor / WiFi driver inconsistency

### ISSUE THREAD

**Issue by gpo123** [MichaIng/DietPi#742]
**BananaPi Pro:**

1. ondemand governor: sample rate can not be set:
line 1235 in dietpi-config should read: MIN_VALUE=$(( $(cat /sys/devices/system/cpu/cpufreq/ondemand/**min_sampling_rate**

2. image has a little inconsistency: wifi driver brcmfmac is listed in /etc/modules, while in the meantime it's blacklisted in /etc/modprobe.d/wifi_disable.

**Comment by Fourdee** [comment]
@gpo123 

> image has a little inconsistency: wifi driver brcmfmac is listed in /etc/modules, while in the meantime it's blacklisted in /etc/modprobe.d/wifi_disable.

Reason for this:

The blacklist overrides whats in ```/etc/modules```. So for each image, we define the modules the board has in ```/etc/modules```, then apply a blacklist to disable the WiFi/BT modules in ```/etc/modprobe.d/wifi_disable```.

Then when the user enables WiFi in ```dietpi-config```, blacklist is removed, modules are loaded straight away in ```dietpi-set_hardware``` script, and, modules in ```/etc/modules``` are loaded during next boot.

**Comment by Fourdee** [comment]
Marking this as closed, due to revert from DEV (4.9) to STABLE (3.x) for our main images:
https://github.com/Fourdee/DietPi/issues/778#issuecomment-283112473
