### ISSUE TITLE
transmission-daemon eating op my memory

### ISSUE THREAD

**Issue by Thijzer** [MichaIng/DietPi#745]
board : odroid C1

Service "transmission-daemon" with default settings was running in hi memory usage.
found 300MB memory usage after minutes running with 2 torrents.

**Possible fix:**

Changing this value fixed it for me.

edit `/etc/transmission-daemon/settings.json`

change the value from to "cache-size-mb" to 4,

```json
{
  "cache-size-mb": 4,
}
```

**Comment by Thijzer** [comment]
I also noticed that transmission-remote-cli was not installed, I know it's not needed but it's such a small package with lots of functionality.

**Comment by Fourdee** [comment]
@Thijzer 

Hi,

DietPi allocates 1/7th of total RAM for BitTorrent cache. This vastly reduces IO thrashing on flash media, improving the performance of BitTorrent downloads and increasing flash media lifespan.

I'll mark this as closed, please re-open if required.

**Comment by Thijzer** [comment]
@Fourdee, Thank you for your quick answer.

I thought that would be the reason :) 

But honestly, who in his right mind would run transmission on the SD card?

**Comment by Fourdee** [comment]
@Thijzer 

> But honestly, who in his right mind would run transmission on the SD card?

You'd be surprised lol 😃
