### ISSUE TITLE
error while loading shared libraries: libidn.so.11: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by Bobbaone** [MichaIng/DietPi#75]
This error suddenly appears + segmentation fault at apt-get....

i think i switch to a stable version of the raspberry os

**Comment by Fourdee** [comment]
Segmentation fault indicates a PSU, SD or unstable overclocking issue. You will experience the same issue on the official Raspbian at some point.

You could also try to install the shared library:
apt-get instal libidn11
