### ISSUE TITLE
DietPi-Drive_Manager | Support multiple partitions & C2 EMMC + SD combo

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#751]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=1281&p=5436#p5436

**Comment by joshuamcginnis** [comment]
Looking forward to this!

**Comment by Fourdee** [comment]
Notes:
- After plugging in SD, reboot required to be detected in ```blkid```

Changes:
- We now scrape ```blkid``` to detect and support all drives + partitions.
- UUID is now the default mount type on new drives (excluding any existing ```/dev/sdX``` entries in ```/etc/fstab``` that will override this on existing installations only)
- Mount target locations, when generated, are now based on UUID (eg: ```/mnt/uaeur94ar4a33a3a3r```), instead of hard coded ```/mnt/usb_x```
- Formatting a drive  is only available if ALL partitions on the drive have been unmounted (as we format the whole drive with 1 new partition)
- Transfer RootFS no longer has limitations and can be done as many times as you like, on any target partition.

Possible changes:
- 🈯️  ~~We still need to keep one ```/dev/sda1``` entry, in ```/etc/fstab```, for the old format system (during 1st run setup)~~

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/23213178/d8f04a90-f901-11e6-99c3-c14972e2213c.png)

**Comment by joshuamcginnis** [comment]
@Fourdee For some reason, I'm not able to get my 64gb sd card to mount with this update.

```
lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0  7.3G  0 disk
├─mmcblk0p1 179:1    0  128M  0 part /boot
└─mmcblk0p2 179:2    0  7.2G  0 part /

fdisk -l

Disk /dev/mmcblk0: 7.3 GiB, 7818182656 bytes, 15269888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xd3630000

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        2048   264191   262144  128M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      264192 15269887 15005696  7.2G 83 Linux
```

I've installed the update and rebooted with the sd card inserted a couple of times.

**Comment by Fourdee** [comment]
@joshuamcginnis 

>  For some reason, I'm not able to get my 64gb sd card to mount with this update.

This is still in devolpment at my end and hasn't been synced to testing branch yet (v145) 

If you are able to assist us with testing, i'll get this synced tomorrow and let you know when its ready (with instructions for testing branch)?

**Comment by joshuamcginnis** [comment]
@Fourdee I just noticed you moved this `v145`. When I saw 144 shipped, I assumed this was included. I'll stand by for now and try to test if I can find some time.

**Comment by Fourdee** [comment]
@joshuamcginnis 

> I just noticed you moved this v145. When I saw 144 shipped, I assumed this was included. I'll stand by for now and try to test if I can find some time.

Ah yes, apologies 👍 

We had to release v144 early, contained critical fixes for most used software and support for new audio DAC's, hence we nudged a few things to v145. Sorry about that, although, this update will make it to v145 😉

**Comment by Fourdee** [comment]
The updated ```dietpi-drive_manager``` code also fixes hang issue with ```stretch```: 
https://github.com/Fourdee/DietPi/issues/475#issuecomment-252504800

**Comment by Fourdee** [comment]
- 🈯️ done | ~~SD to USB is disabled and needs rewrite, not compatible with new system.~~

**Comment by Fourdee** [comment]
- 🈯️ Done, rootfs move supports any partition | ~~Issue with moving rootFS back to ```p2``` as we require clear of partition tables~~

**Comment by Fourdee** [comment]
RootFS move tests:
- 🈯️ C2  ```/dev/mmcblk0p2``` > ```/dev/mmcblk1p1``` > ```/dev/mmcblk0p2```
- 🈯️ RPi  ```/dev/mmcblk0p2``` > ```/dev/sda1``` > ```/dev/mmcblk0p2```

**Comment by Fourdee** [comment]
Notes:
- 🈯️ Done | ```/mnt/usb_1``` was hardcoded throughout DietPi scripts as USB drive location. Lets remove this from all scripts, and plan to add a system where we can list all available mounts + offer selection, across various software (eg: dietpi-backup > select usb drive)

---

Removed/modified features, due to spring clean, and, updated code for how DietPi handles external drives :
- 🈯️ Function: ```/DietPi/dietpi/func/dietpi-set_userdata return_auto``` removed
- 🈯️ dietpi.txt automation: ```dietpi_userdata_basedirectory=``` removed
- 🈯️ dietpi-backup: USB drive selection | Will change to pull list of available mounts + selection
- 🈯️ dietpi-sync: USB drive selection | Will change to pull list of available mounts + selection
- 🈯️ dietpi-software: User data location, now launches ```dietpi-drive_manager```, and, pull list of available mounts option.
- 🈯️ dietpi-software | First run setup questions (including dedicated USB drive setup) removed. This was old code and old system. Will also reduce unnecessary confusion for inexperienced users during 1st run. Userdata/drives can be setup at a later date in ```dietpi-drive_manager```, or,  ```user data``` location option in ```dietpi-software```.
- 🈯️ DietPi-Automation | Automated format of USB drive in ```dietpi.txt``` (```Automation_Format_My_Usb_Drive```) removed.

**Comment by Fourdee** [comment]
#### Removal of hard coded USB drive selection throughout DietPi scripts,  change to list of active mounts.

Following programs, has a ```list``` option for active mount locations, with menu selection:
- DietPi-Backup
- DietPi-Sync
- DietPi-Software > Userdata location

![image](https://cloud.githubusercontent.com/assets/7077026/23216444/e5b930b4-f90d-11e6-9765-57b55657b1c3.png)

![image](https://cloud.githubusercontent.com/assets/7077026/23216416/cb30119a-f90d-11e6-8195-5ef20a2daa5b.png)

**Comment by Fourdee** [comment]
ToDo, online docs:
- 🈯️ Over complicates setup for new users. I will leave this out of 1st run guide | ~~Change step 5 from: http://dietpi.com/phpbb/viewtopic.php?f=8&t=9 to Optional setup USB/userdata ~~
- 🈯️ Update all references of ```/mnt/usb_1``` in online docs to ```/mnt/uuid-of-device```
- 🈯️ Update image for http://dietpi.com/phpbb/viewtopic.php?f=8&t=478 and reference setup drives with ```dietpi-drive_manager```
- 🈯️ update http://dietpi.com/phpbb/viewtopic.php?f=8&t=673

**Comment by Fourdee** [comment]
@midwan

The recent changes here will effect the AmiBerry automated image. All prompts to setup an external drive has now been removed from 1st run setup. 
As of DietPi v145, users can setup external drives and move "user data" (eg: where roms/kickstarts are stored) by running ```dietpi-software``` from command line and selecting ```User Data``` option. After installation is completed.

Pics + steps:
![image](https://cloud.githubusercontent.com/assets/7077026/23267879/f266130a-f9e3-11e6-894e-b00f0c2dea3c.png)
![image](https://cloud.githubusercontent.com/assets/7077026/23267887/f737d706-f9e3-11e6-8002-81fbba5671e4.png)

**Comment by Fourdee** [comment]
Completed.

**Comment by Fourdee** [comment]
Lets also update ```dietpi-cloudshell``` storage menu, to use the new mount list selection system.

**Comment by Fourdee** [comment]
Done.
