### ISSUE TITLE
VNC strange behaviour after update to 143

### ISSUE THREAD

**Issue by ad5trett** [MichaIng/DietPi#752]
After updating to 143, whenever i start a VNC session in VNC Viewer on my Mac (tightvnc server on Pi2), any window that is opened starts in the top left corner of the screen and i'm unable to move it around the screen or resize it. Any windows that open after that do the same and are on top of the previously opened window meaning you can't select the one underneath?

I've tried the built in VNC viewer in macOS as well, same problem.

Could it be a window manager problem? Bit of a novice here so appreciate any pointers.

Thanks.

<img width="1280" alt="screen shot 2017-02-04 at 10 50 54" src="https://cloud.githubusercontent.com/assets/25547195/22617932/271d9486-eac8-11e6-8be0-66b37a601b45.png">

**Comment by Fourdee** [comment]
@ad5trett 

Thanks for the report.

> Could it be a window manager problem?

👍 

I run tightvnc on my XU4, although different device, that remembers window locations.

I'll try to replicate on a RPi using Windows + RealVNC viewer.

**Comment by Fourdee** [comment]
Outdated <v6.0, marking as closed.
