### ISSUE TITLE
General | Updating PiHole overwrites lighttpd.conf

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#753]
> http://dietpi.com/phpbb/viewtopic.php?f=11&t=1277&p=5444#p5406

We prevent this in the ```dietpi-software``` installation, however, ```pihole -up``` will overwrite the lighttpd.conf.

Options:
- Inform users to backup lighttpd before updating, then move it back after update
- Find a method in ```pihole``` -up that prevents overwrite of lighttpd.conf

**Comment by k-plan** [comment]
> - Inform users to backup lighttpd before updating, then move it back after update

Hmm, a backup does `pihole -up` at the moment by default.

```
~# pihole -v
::: Pi-hole version is v2.12 (Latest version is v2.12.1)
::: Web-Admin version is v2.4 (Latest version is v2.4)

~# pihole -up

~# ls -lah /etc/lighttpd/
insgesamt 24K
drwxr-xr-x  4 root root 4,0K Feb  3 23:19 .
drwxr-xr-x 91 root root 4,0K Feb  3 23:19 ..
drwxr-xr-x  2 root root 4,0K Jan 24 15:06 conf-available
drwxr-xr-x  2 root root 4,0K Jan 24 15:14 conf-enabled
-rw-r--r--  1 root root 2,4K Feb  3 23:19 lighttpd.conf
-rw-r--r--  1 root root 1,1K Jan 24 15:14 lighttpd.conf.orig

```

After this, I do : 

```
:~# mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.bak
:~# cp /etc/lighttpd/lighttpd.conf.orig /etc/lighttpd/lighttpd.conf
:~# dietpi-services restart
```

... and I will be back in business. 
Can this be a option? Can DietPi have his own pihole update script?

**Comment by Fourdee** [comment]
@k-plan 

> Can DietPi have his own pihole update script?

Yes, but then the issue would be trying to remind users to use that, rather than ```pihole -up```. In effect, we could simply say do this as you mentioned:
```
cp /etc/lighttpd/lighttpd.conf.orig /etc/lighttpd/lighttpd.conf
```

---

- 🈴 mmm, wonder if we made empty file ```/etc/lighttpd/lighttpd.conf.orig```, and read only, that might prevent ```mv```.

Would work for this:
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L646

But then:
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L648

**Comment by Fourdee** [comment]
🈴 Another option, if we want to "fix" this from our side. Set ```lighttpd.conf``` to read only, when user installs PiHole.
```
root@DietPi:~# nano /etc/lighttpd/lighttpd.conf
root@DietPi:~# chmod 554 /etc/lighttpd/lighttpd.conf
root@DietPi:~# mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.orig
```

**Comment by Fourdee** [comment]
Added info to online docs, marking as closed:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=174#p174

**Comment by PromoFaux** [comment]
Just FYI, there was a line added to our `lighttpd.conf` that allows users to add their own customisations in `/etc/lighttpd/external.conf`, so that we would no longer overwrite any custom configs that people had set up. Seems a good compromise for now?

https://github.com/pi-hole/pi-hole/pull/704

(btw. incoming question for you over on our repo :wink:)

**Comment by Dagur** [comment]
You can't change the port in external.conf so this is not a good solution for me

**Comment by Joulinar** [comment]
Hi,

You have answered on a 4 years old post. What exactly you are looking for?

**Comment by MichaIng** [comment]
> You can't change the port in external.conf

Is it so? The `external.conf` was recently moved to be invoked earlier: https://github.com/pi-hole/pi-hole/commit/e5bfafefb97995ce4cdfadfed1e745141ac57c28
But its still done after the port was assigned. Or does Lighttpd complain when the port is assigned two times, so that it cannot be overridden by an included config?

If so, on a DietPi system, install Pi-hole via `dietpi-software`, so you can choose a different webserver as well set a custom port and `pihole -up` won't overwrite the config 😉.

**Comment by Dagur** [comment]
lighttpd complains that it's assigned two times. 

> Duplicate config variable in conditional 0 global: server.port

I did a quick google and read that it's not possible to set the port

**Comment by Joulinar** [comment]
> I'm not using DietPi

Now I'm confused and did not know what you are looking for.

**Comment by Joulinar** [comment]
Switch to DietPi and your issue will be gone as DietPi support Pihole running nginx 😉 

As well DietPi is based on Raspberry OS 😄

**Comment by MichaIng** [comment]
Ah, that covers Debian/Raspbian Buster and up and is even available from Stretch backports, if you're running an old Debian image: https://packages.debian.org/stretch-backports/lighttpd
```
apt install -t stretch-backports lighttpd
```
I was wondering already as I though to have tested this not too long ago.
