### ISSUE TITLE
DietPi | Add support and optimizations for CHIP

### ISSUE THREAD

**Issue by Famicoman** [MichaIng/DietPi#770]
Are there any plans to support the $9 CHIP computer?  
https://getchip.com/pages/chip

**Comment by Fourdee** [comment]
@Famicoman 

Hi, thanks for the request.

> Are there any plans to support the $9 CHIP computer?

If we can get our hands on one, yes. Although it works out at roughly £30 after shipping + import tax to UK :frowning_face: 

I'll send CHIP an email, see if they would be willing to send us a dev sample board, allowing us to achieve an DietPi image and support for this device. Failing that, we would need to achieve funds from donations.

**Comment by Fourdee** [comment]
Tweet, should get more attention than email, show your support and should help get things rolling 👍 : https://twitter.com/DietPi_/status/833279357380591617

**Comment by Famicoman** [comment]
Thanks guys, hope they end up sending one your way!

**Comment by Fourdee** [comment]
Received a few donations, ordered a CHIP kit for $43. On back order for Q1.

**Comment by aliosa27** [comment]
I have tried to do this on my chip's a few times, however things break when trying to recreate a ubifs from the installed, trimmed system, ill tackle this over the next week. time off work!

**Comment by woulf** [comment]
I have an unused chip and hdmi shield if it can help

**Comment by Fourdee** [comment]
Marking as closed due to the following:
- I lack the device, and, have no plans to purchase one currently.
- PREP can be used to convert an existing Debian pre-image into DietPi: https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh
