### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by floydianslips** [MichaIng/DietPi#773]
Only trying to install LXDE and Chromium:

Apt-get has failed:                                                │ 
     │  - Apt string = xcompmgr xterm xinit xauth xserver-xorg dbus-x11   │ 
     │ xfonts-base x11-xserver-utils x11-common x11-utils                 │ 
     │ --no-install-recommends                                            │ 
     │  - Error code = 100                                                │ 
     │  - Software Title = Xserver: linux display system

**Comment by Fourdee** [comment]
@floydianslips 

Thanks for the report 👍 

Which device is this running on?

**Comment by floydianslips** [comment]
Raspberry Pi 3. I spent a couple hours trying to get past this error. Tried LXFE and received errors as well. Never could get anything running on it. Please let me know if there is any way to help on this.

**Comment by Fourdee** [comment]
@floydianslips 

> Raspberry Pi 3

Thanks 👍 

I'll run a test here to try and replicate.

notes:
```
root@DietPi:~# dietpi-software list | grep chrom
id 113 | =0 | chromium: (optional) web browser | +desktop | http://dietpi.com/phpbb/viewtopic.php?http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=3011#p3011
root@DietPi:~# dietpi-software list | grep lxde
id 23 | =0 | lxde: ultra lightweight desktop | +alsa +xserver | http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p42
root@DietPi:~# dietpi-software install 23 113
```

**Comment by Fourdee** [comment]
@floydianslips 

Ok, appears to work fine here on fresh DietPi install with RPi 3, may be limited to your current installation and package combination, or, apt mirror.

We'll need to debug this manually, **please run the following commands and paste results:**
```
apt-get install -y xcompmgr xterm xinit xauth xserver-xorg dbus-x11 xfonts-base x11-xserver-utils x11-common x11-utils --no-install-recommends
cat /etc/apt/sources.list
```

**Comment by floydianslips** [comment]
I needed to commonadeer that SD card for another project unfortunately. 
I have tried a new card and just LXDE and it worked swimmingly. Sorry 
about that, I should have tried to keep that card.

If it helps the card is a Lexar 300x 16GB. I will try to load it on 
their again when I get a chance to test it. My goal with Diet Pi is to 
install Internet-in-a-Box (XSCE) on it. We are developing it to work on 
Raspberry Pi and I am hoping it will be easily installed on Diet Pi.

https://github.com/XSCE/xsce

Are there any plans to have Ansible as an install option in the future 
for Diet Pi?

Cheers,

Josh

**Comment by Fourdee** [comment]
@floydianslips 

> Are there any plans to have Ansible as an install option in the future
for Diet Pi?

Interesting software 👍  I'll create a ticket and take a look when possible.
https://github.com/Fourdee/DietPi/issues/782

> If it helps the card is a Lexar 300x 16GB

Thanks for letting us know. I've not tried Lexar SD cards yet, Sandisk seem to be the leader in stability on SBC's (even though they do not officially support use in SBC's lol 😉 ), only ever had 1 Sandisk fail since the start of DietPi.

**Comment by floydianslips** [comment]
Thanks. You have any plans on adding ansible as an install option?

On Feb 27, 2017 8:22 AM, "Dan" <notifications@github.com> wrote:

@floydianslips <https://github.com/floydianslips>

Are there any plans to have Ansible as an install option in the future
for Diet Pi?

Interesting software 👍 I'll create a ticket and take a look when possible.
#782 <https://github.com/Fourdee/DietPi/issues/782>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Fourdee/DietPi/issues/773#issuecomment-282769034>, or mute
the thread

**Comment by Fourdee** [comment]
@floydianslips 

> You have any plans on adding ansible as an install option?

Do now, lol 😄 
https://github.com/Fourdee/DietPi/issues/789

Marking this as closed (that is enough requests for 1 ticket lol 😉 )

I'll do some research when I start, but, in simple terms what does ansible actually do?

**Comment by floydianslips** [comment]
It is a process automation tool basically. We use it to install and 
enable all the components of our software. ie: moodle, kiwix server, web 
server, etc.

**Comment by Fourdee** [comment]
@floydianslips 

Thanks.

I'll need to run some tests and see if Ansible will be compatible with DietPi, and visa versa.
