### ISSUE TITLE
[dupe] Read-only root partition

### ISSUE THREAD

**Issue by ralienpp** [MichaIng/DietPi#774]
It would be of great benefit for the longevity and survivability of the system, if it could be guaranteed that it would always boot to a known clean state that cannot be affected by anything. This is especially relevant for contexts where power outages are common, or if some processes write to disk often.

Third party stuff and generated data files should be stored in the user's home directory on another partition, or elsewhere - as long as it is on a partition other than `/`.

For system-wide updates that require changes in the root partition, it could be remounted in `rw` mode for the process to complete, and then revert to read-only.

There are a number of guides that address this matter, e.g.:

* https://hallard.me/raspberry-pi-read-only/
* http://blog.gegg.us/2014/03/a-raspbian-read-only-root-fs-howto/

However, it would be great if this feature was officially endorsed and worked out of the box, or could be triggered by some sort of a config switch.

**Comment by Fourdee** [comment]
@ralienpp 

Thanks for the suggestion and info 👍 , as we already have a ticket with this request, i'll mark this one as dupe.

Here is the original ticket: https://github.com/Fourdee/DietPi/issues/229
