### ISSUE TITLE
DietPi-Software | Upgrade Pi-Hole to the latest version

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#776]
Is there a reason that Pi-hole is still on v2.9.5, while the are several versions after that available?

The current latest one is v2.12.1: https://github.com/pi-hole/pi-hole/releases

**Comment by Fourdee** [comment]
@midwan 

> Is there a reason that Pi-hole is still on v2.9.5, while the are several versions after that available?

Once installed, PiHole needs to be updated manually as it overwrites the ```lighttpd.conf```. i'd also recommend making a system backup before running this ```dietpi-backup```, as we cant predict/control what ```pihole -up``` will do:
```
mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.bak
pihole -up
mv /etc/lighttpd/lighttpd.conf.bak /etc/lighttpd/lighttpd.conf
```

**Comment by midwan** [comment]
Yeap, I read that in the forum post.. but I was wondering why installing it from scratch using Dietpi-Software doesn't install the latest version?

Also, is it normal that I don't see a Login link in the Pi-hole web interface?

**Comment by Fourdee** [comment]
> Yeap, I read that in the forum post.. but I was wondering why installing it from scratch using Dietpi-Software doesn't install the latest version?

Strange, ```dietpi-software``` does run the official installation script during install, it should be latest version:
http://install.pi-hole.net

> Also, is it normal that I don't see a Login link in the Pi-hole web interface?

Should be located on the left hand side. Is this a fresh installation of PiHole recently?

**Comment by midwan** [comment]
When I installed it it got v2.9.5, maybe if I remove it and install it again it would get the latest one (didn't test that). :)

This is what I see on the left hand side:
![image](https://cloud.githubusercontent.com/assets/3877365/23311075/118f6d04-fab5-11e6-8924-f26c186a2168.png)

**Comment by Fourdee** [comment]
> When I installed it it got v2.9.5, maybe if I remove it and install it again it would get the latest one (didn't test that). :)

Yep, uninstall and install though ```dietpi-software``` would work.

In older versions, the login option is in the top right hand corner, the PiHole button (i believe). 

Just did a fresh install, Pi-hole Version v2.12.1 Web Interface Version v2.4, login button is on left hand side.

**Comment by midwan** [comment]
Hm, I'll try a clean re-installation to see if it helps then

**Comment by midwan** [comment]
OK, re-installing from scratch works.

Note: the site is now accessible under <IP>/admin instead of <IP>/pihole, you may want to update the documentation on the forum... ;-)

**Comment by Fourdee** [comment]
@midwan 

> Note: the site is now accessible under /admin instead of /pihole, you may want to update the documentation on the forum... ;-)

It should be available under both. We create a symlink for /pihole to /admin aswell. So either should work:
ip/pihole
ip/admin

^^ I personally prefer ip/pihole 😉

**Comment by midwan** [comment]
Yeap, but it comes up with this:

![image](https://cloud.githubusercontent.com/assets/3877365/23313251/3a513e68-fabd-11e6-8dc0-006149ba730a.png)

**Comment by Fourdee** [comment]
@midwan 

Weird lol. Didn't happen for me on Chrome, which browser?

**Comment by midwan** [comment]
@Fourdee 
I tried it with Chrome... :) The block is from PiHole itself it you notice, and that's why it has the option to whitelist it. However, when I try to whitelist it from here it fails with an "unknown error".

It's not a big deal for me, as I can use the /admin page without a problem. Just thought that you should know in case other people come across this.

**Comment by Fourdee** [comment]
@midwan 

> Just thought that you should know in case other people come across this.

Aye, thanks 👍 

Its one of those days lol...
![image](https://cloud.githubusercontent.com/assets/7077026/23313807/22e178f2-fab7-11e6-8d4a-876673a048ff.png)

Although, not sure why PiHole is even blocking this for you, doesn't exist in gravity list:
```
root@DietPi:~# cat /etc/pihole/gravity.list | grep pihole
```
