### ISSUE TITLE
[dupe] DietPi - Requests Internet access during installation when internet connection is functional

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#777]
Dietpi: 144
Odroid C2

During the installation process DietPi Internet access during installation when internet connection is functional.

```

 [Info] Testing connection to http://ftp.debian.org/debian
 [Info] Max duration of 20 seconds, please wait...
 [Failed] Connection test | An issue has occured

```

"Run the Internet Connection Test"  it report  "Internet     : Online "

Additionally verified by...
```
root@test:~# wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip
--2017-02-24 16:49:17--  http://speedtest.wdc01.softlayer.com/downloads/test10.zip
Resolving speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)... 208.43.102.250, 2607:f0d0:3001:78::2
Connecting to speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|208.43.102.250|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11536384 (11M) [application/zip]
Saving to: ‘/dev/null’

/dev/null                         100%[===============================================================>]  11.00M   437KB/s   in 13s

2017-02-24 16:49:31 (847 KB/s) - ‘/dev/null’ saved [11536384/11536384]
```
Initially I thought this may be related to Pihole
I've changed my hostname to the website base URL but have redacted for privacy.  It would look like my 'website.com' I've done this because nginx utilizes the hostname for its configuration.

 Current Details:                                            
                                   │  - Mode    = STATIC                                           
                                   │  - Ip      = 192.168.1.118                                    
                                   │  - Mask    = 255.255.255.0                                   
                                   │  - Gateway = 192.168.1.1                                  
                                   │  - DNS     = 127.0.0.1  

```
root@test:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:1e:07:33:5b:37
          inet addr:192.168.1.118  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe70::21e:4ff:fe33:9b43/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9595 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3544 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:12335084 (11.7 MiB)  TX bytes:443761 (433.3 KiB)
          Interrupt:40

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:4096  Metric:1
          RX packets:306 errors:0 dropped:0 overruns:0 frame:0
          TX packets:306 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:27133 (26.4 KiB)  TX bytes:27133 (26.4 KiB)
```

**Comment by Fourdee** [comment]
@LexiconCode 

Thanks for the report, this is a known issue:
https://github.com/Fourdee/DietPi/issues/755#issuecomment-282203823

We'll get this fixed for v145, in the mean time, quick solution is here:
http://dietpi.com/phpbb/viewtopic.php?f=11&t=1373#p5810

I'll mark this as closed (dupe)

**Comment by LexiconCode** [comment]
@Fourdee 
The suggested fix may cause the following error when running 'apt-get update'

W: GPG error: http://www.deb-multimedia.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117

Which can be fixed by
apt-get install deb-multimedia-keyring

**Comment by Fourdee** [comment]
@LexiconCode 

> W: GPG error: http://www.deb-multimedia.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5C808C2B65558117

Yep, this doesn't exist on our image, it appears its pulled in during ```apt-upgrade``` possibly from one of Meveric's packages:
![image](https://cloud.githubusercontent.com/assets/7077026/23313260/e2660484-fab4-11e6-92f6-8405e56b2290.png)

Afterwards:
````
root@DietPi:~# ls -lha /etc/apt/sources.list.d/
total 32K
drwxr-xr-x 2 root root 4.0K Feb 22 17:20 .
drwxr-xr-x 6 root root 4.0K Feb  6 14:56 ..
-rw-r--r-- 1 root root   55 Feb 22 17:20 deb-multimedia.list
-rw-r--r-- 1 root root   52 Feb 22 17:19 meveric-all-C2.list
-rw-r--r-- 1 root root   40 Feb 22 17:19 meveric-all-main.list
-rw-r--r-- 1 root root   43 Feb 22 17:19 meveric-all-testing.list
-rw-r--r-- 1 root root   48 Feb 22 17:19 meveric-jessie-backports.list
-rw-r--r-- 1 root root   43 Feb 22 17:19 meveric-jessie-main.list
```

**Comment by LexiconCode** [comment]
Fyi: 	nextcloud-11.0.1.zip is available

**Comment by LexiconCode** [comment]
@Fourdee Thank you!

**Comment by Fourdee** [comment]
@LexiconCode 

> Fyi: nextcloud-11.0.1.zip is available

Thanks 👍 

Lets use: 
https://download.nextcloud.com/server/releases/latest-11.zip
