### ISSUE TITLE
Update all images to v145

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#778]
To resolve:
https://github.com/Fourdee/DietPi/issues/755#issuecomment-282374707

Although, may as well do RPi images aswell.

Images:
- I 🈯️ | Z 🈯️ | Live 🈯️ | RPi Jessie
- I 🈯️ | Z 🈯️ | Live 🈯️ | RPi Stretch
- I 🈯️ | Z 🈯️ | Live 🈯️ | C1
- I 🈯️ | Z 🈯️ | Live 🈯️ | C2
- I 🈯️ | Z 🈯️ | Live 🈯️ | XU4
- I 🈯️ | Z 🈯️ | Live 🈯️ | Sparky
- I 🈯️ | Z 🈯️ | Live 🈯️ | Pine A64
- I 🈯️ | Z 🈯️ | Live 🈯️ | OPi one
- I 🈯️ | Z 🈯️ | Live 🈯️ | OPi PC
- I 🈯️ | Z 🈯️ | Live 🈯️ | OPi Plus
- I 🈺 | Z 🈺 | Live 🈺 | OPi Zero (board failure, fix applied to v139 image, unable to update to v145 https://github.com/Fourdee/DietPi/issues/778#issuecomment-282562185)
- I 🈯️ | Z 🈯️ | Live 🈯️ | NanoPi Neo 
-- 🈴 USB devices not working in 4.10 ARMbian kernel upgrade: http://dietpi.com/phpbb/viewtopic.php?f=11&t=1391&p=5864#p5859
-- 🈯️ reverting back to stable 3.x: https://github.com/Fourdee/DietPi/issues/778#issuecomment-283112473
- I 🈯️ | Z 🈯️ | Live 🈯️ | NanoPi Neo Air (https://github.com/Fourdee/DietPi/issues/738#issuecomment-282555570)
- I 🈯️ | Z 🈯️ | Live 🈯️ | NanoPi M1
- I 🈯️ | Z 🈯️ | Live 🈯️ | NanoPi M2
- I 🈯️ | Z 🈯️ | Live 🈯️ | NanoPi M3
- I 🈯️ | Z 🈯️ | Live 🈯️ | BPi Pro 
-- 🈴 Boot issues with mmc, loops several times before kernel successfully loads | CPU govs do not exist: https://github.com/Fourdee/DietPi/issues/742)
-- 🈯️ reverting back to stable 3.x: https://github.com/Fourdee/DietPi/issues/778#issuecomment-283112473
- I 🈯️ | Z 🈯️ | Live 🈯️ | BPi M2+
- I 🈯️ | Z 🈯️ | Live 🈯️ | VMware
- I 🈯️ | Z 🈯️ | Live 🈯️ | Virtual Box

**Comment by Fourdee** [comment]
- 🈴 OPi Zero board failure. No boot, serial, leds. Unable to complete.

**Comment by taner1** [comment]
will this update rolls with 4.10 mainline kernel for opi zero? im waiting for it

**Comment by Fourdee** [comment]
@taner1 

Unfortunately not from my end as my board is dead. Would need someone else to generate image while I wait for replacement.

**Comment by Fourdee** [comment]
@taner1 

Although saying that, ARMbian may release 4.10 as a package install via their repo.

**Comment by taner1** [comment]
I tried to install it via apt but my goal is getting wifi ap+sta mode so will this update also install mainline ported xradio module or does it conflicts?  I cant figure it out because kernel headers filled my 1gb disk.  btw how can i delete old kernel files i tried cleaners and apt autoremove clean things but nothing done :)

**Comment by Fourdee** [comment]
@taner1 

> how can i delete old kernel files i tried cleaners

Manually is best way. 
- Remove the oldest version from (if 2 or more entries):
```
ls -lha /lib/modules
```

- On some images, also check boot for duplicate files with different versions:
```
ls -lha /boot
```

> wifi ap+sta mode so will this update also install mainline ported xradio module or does it conflicts?

If you are modifying the kernel, you may wish to put the ARMbian packages on hold. This would allow you to used the ported xradio_wlan driver without kernel being updated.

Not sure which package exactly, but you can list them with.
```
dpkg -l | grep linux
```

Then to hold:
```
apt-mark hold thispackageplease
```

---

OPI Zero ordered from GearBest, should be here in under a month.

**Comment by Fourdee** [comment]
Although DEV (4.9) offered excellent results with Nano Pi Neo's, the recent 4.10 update via ARMbian repo renders it unusable (breaks USB detection).

Making the decision to revert all DEV (4.x mainline) images to STABLE (3.x). We may offer DEV (4.x) as an alternative, but not for our main image.

Images effected by the revert:
- 🈯️ BPi Pro
- 🈯️ NanoPi Neo
- 🈯️ NanoPi Air

**Comment by Fourdee** [comment]
Completed

**Comment by Fourdee** [comment]
- 🈯️ OPi Zero arrived, rebuild and update image
- Test issues reported here: http://dietpi.com/phpbb/viewtopic.php?f=11&t=1449&p=6034#p6034
🈯️ Onboard sound works fine through expansion board.
🈯️ No installation errors. Will need more info on specific software title user selected.

**Comment by Fourdee** [comment]
https://i.imgur.com/KpeIJP0.gifv lol

**Comment by Fourdee** [comment]
OPi Zero v145 image live: http://dietpi.com/downloads/images/DietPi_OrangePiZero-armv7-(Jessie).7z
