### ISSUE TITLE
Pine64 | Incorrectly reporting No internet connection

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#780]
Fresh install of v142, updated to v144 on a Pine64.
I've enabled both Ethernet and Wifi, the Interent Test in the Adapters config screen works fine.
Apt-get works fine as well, and I was able to update the firmware from the menu also.

However, Dietpi-Software reports "No internet connection" when it attempts to start installing my selected applications, and refuses to continue.

Is this a known issue? Any workarounds?

**Comment by midwan** [comment]
I guess this is due to #755 then ?

**Comment by midwan** [comment]
Confirmed, the fix mentioned helped resolve the issue. Sorry :)

**Comment by Fourdee** [comment]
@midwan 

Thanks for report, your spot on 👍 

Aiming to have the Pine A64 image updated today, with the fix applied:
https://github.com/Fourdee/DietPi/issues/778

**Comment by Fourdee** [comment]
@midwan 

Pine image updated to v145:
http://dietpi.com/downloads/images/DietPi_PineA64-arm64-(Jessie).7z

Contains fix for this ticket, and latest firmware/kernel from longsleep (104)

**Comment by midwan** [comment]
Awesome, thanks!
