### ISSUE TITLE
Pip and Paho

### ISSUE THREAD

**Issue by JohnMacrae** [MichaIng/DietPi#788]
Another enhancement?
If we have the option to install Mosquitto it would be good to be able to install pip and paho as well.

Also, along with the GPIO options it would be good to include smbus?

Thx :)

**Comment by Fourdee** [comment]
@9H5G 

Python-Pip?:
We've added this to linux software entry in ```dietpi-software``` for v145: https://github.com/Fourdee/DietPi/issues/784#issuecomment-283358538

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
