### ISSUE TITLE
DietPi-Software | Ansible 

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#789]
> https://github.com/Fourdee/DietPi/issues/773#issuecomment-282828654

**Comment by Fourdee** [comment]
Not compatible with DietPi.

Ansible is a complete system deployment tool to allow for automated setup of a system, programs etc. Its essentially, in its own way, similar to DietPi and what we do.
Unfortunately, we have no way of controlling Ansible, it would be impossible to support it along side DietPi, and visa versa.

Marking as no fix.

**Comment by port19x** [comment]
#6486
