### ISSUE TITLE
/DietPi/config.txt does not contain the actual config.txt, despite what it claims

### ISSUE THREAD

**Issue by husnoo** [MichaIng/DietPi#79]
$ cat /DietPi/config.txt 
This file has been moved to DietPi-Ramdisk.
New location = /DietPi/config.txt

**Comment by Fourdee** [comment]
Hi Husnoo.

What version of DietPi are you currently running? Are you able to send a dietpi-bugreport?

**Comment by husnoo** [comment]
nawal@poobum:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

But report: 801f029201f3-0

**Comment by Fourdee** [comment]
This is a known issue with v77. 

Please follow this post to resolve the issue:
http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=39&p=131&hilit=404#p131

**Comment by Fourdee** [comment]
Assumed resolved as it is a known issue and resolution. Please reopen ticket if required.
