### ISSUE TITLE
[dupe] Pi ZeroW: Wifi Not found in dietpi-config

### ISSUE THREAD

**Issue by lavrentiy** [MichaIng/DietPi#790]
Using a Pi Zero Wifi edition the on board wifi chip can not be found.

**Comment by Fourdee** [comment]
@lavrentiy 

Thanks for the report.

I have one on order, we'll get that fixed when it arrives, please see this ticket for status:
https://github.com/Fourdee/DietPi/issues/787

I'll mark this closed (dupe).
