### ISSUE TITLE
DietPi-Software | Add OpenVPN installation option.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#80]
> http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=105&p=373#p373

**Comment by pilovali** [comment]
Installation instructions for Pi: https://www.raspberrypi.org/forums/viewtopic.php?t=81657
It's a bit more than dpkg -i openvpn.deb. Unfortunately.

**Comment by mamuesp** [comment]
I started a project on DietPi basis some months ago to automatically set up an VPN router, but I slowed down because of the lack of time. The link is here: https://github.com/mamuesp/pirouette - perhaps it's helpfull

**Comment by Fourdee** [comment]
Thanks guys, i'll take a look when I come round to implementing.

**Comment by Fourdee** [comment]
Implemented for DietPi v100.
