### ISSUE TITLE
DietPi-Software | hack.chat

### ISSUE THREAD

**Issue by phonicmouse** [MichaIng/DietPi#800]
hack.chat, a simple and lightweight chat built on top of Node.js:

- [https://hack.chat/](https://hack.chat/)

- [https://github.com/AndrewBelt/hack.chat](https://github.com/AndrewBelt/hack.chat)

**Comment by phonicmouse** [comment]
If it can be useful...i think that for you could be easier if  you use pm2 to install and manage nodejs apps:
[https://github.com/Unitech/pm2](https://github.com/Unitech/pm2)

I also think it could be a useful software to add.
@Fourdee

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
