### ISSUE TITLE
Re: Please help; Ampache not functioning

### ISSUE THREAD

**Issue by mzeichner** [MichaIng/DietPi#809]
Reference CODE: d58612fa-b924-40a4-8500-c236a83fd7cf-0

> http://dietpi.com/phpbb/viewtopic.php?f=11&t=1458&p=6082&hilit=ampache#p6058

**Comment by Fourdee** [comment]
@mzeichner 
Thanks 👍 

I'll take a look.

Notes:
- LAMP
- MySQL running fine:
```
mysql     1820  1.9  2.2 319408 46360 ?        Sl   10:42   8:36 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
```
- DietPi v144
- Userdata USB
```
lrwxrwxrwx  1 root root   10 Feb 26 19:17 dietpi_userdata -> /mnt/usb_1
```
- SQL/Apache2 logs are clear

**Comment by Fourdee** [comment]
@mzeichner 

Everything appears fine, lets try a reinstall to drop sql DB and regenerate, also log output for further debugging.

#### Please run the following commands:

Uninstall and log output:
```
dietpi-software uninstall 40  | tee -a /root/log.log
```

Install and log output:
```
dietpi-software install 40 | tee -a /root/log.log
```

#### Retry http://ip/ampache, if still failing, please upload the log file:
```
/root/log.log
```

**Comment by Fourdee** [comment]
No response.

@mzeichner 

I'll mark this as closed, please re-open if required.
