### ISSUE TITLE
DietPi-Software | Add Wordpress installation option.

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#81]

**Comment by pilovali** [comment]
This is just a matter of:
wget https://wordpress.org/latest.zip
unzip latest.zip -d /var/www

If you go to http://ip_address/wordpress it will start with the installation wizard.

**Comment by Fourdee** [comment]
> This is just a matter of:

I also had to automate the creation of a MySql db for Wordpress: https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/create_mysql_db

**Comment by Fourdee** [comment]
Done. Available in DietPi v95.
