### ISSUE TITLE
DietPi not installing due to dpkg error

### ISSUE THREAD

**Issue by pcktm** [MichaIng/DietPi#811]
I don't really know what's happening, but will attach logs. 
[logs.txt](https://github.com/Fourdee/DietPi/files/845983/dietpi.txt)

**Comment by Zac610** [comment]
Seems a mirror error, try to change mirror

**Comment by Fourdee** [comment]
@PuciekTM 

Thanks for the report 👍 

> root@DietPi:~# dpkg --configure -a
Setting up alsa-base (1.0.27+1) ...
Setting up libasound2-data (1.0.28-1+rpi2) ...
Setting up libasound2:armhf (1.0.28-1+rpi2) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
Setting up libsamplerate0:armhf (0.1.8-8) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...

Appears running the request ```dpkg --configure -a``` command has resolved the issue. Please can you try running ```dietpi-software``` again and see if the issue persists?

**Comment by pcktm** [comment]
This time something else broke. I don't know what's happening.

[logs.txt](https://github.com/Fourdee/DietPi/files/870660/logs.txt)

**Comment by Fourdee** [comment]
@PuciekTM 

> tar: lib/node_modules/npm/doc/files/npm-folders.md: time stamp 2017-03-12 18:00:47 is 3812412.957271956 s in the future
make: Warning: File '../../../../../../../../root/.node-gyp/7.7.4/include/node/common.gypi' has modification time 4244079 s in the future

Looks like the system time is incorrect, causing node-red and npm to fail install.

Lets check system date:
```
date
```

And if NTPD is enabled (default on with all DietPi images ```=2```):
```
cat /DietPi/dietpi.txt | grep ntpd
```

Lets ensure no other NTPD processes are still running:
```
ps aux | grep [n]tpd
```

Finally, Lets try running NTPD and check for errors:
```
ntpd -gq
```

---

Once the time updates, reinstall node red and nodejs:
```
dietpi-software uninstall 9 122
dietpi-software install 122
```

**Comment by Fourdee** [comment]
@PuciekTM 
Marking as closed. Please reopen if required.
