### ISSUE TITLE
DietPi Image | NanoPi Neo 2

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#814]
- 1GBit eth
- 64bit H5 ARM CPU

http://www.friendlyarm.com/index.php?route=product/product&product_id=180

Awaiting delivery.

**Comment by Fourdee** [comment]
ARMbian dev 4.x branch only for H5, lets hold packages (prevent apt-upgrade and possible buggy kernel update):
```
apt-mark hold armbian-firmware armbian-tools-jessie linux-u-boot-nanopineo2-dev linux-dtb-dev-sun50iw2 linux-image-dev-sun50iw2 
```

**Comment by Fourdee** [comment]
Notes:
- 🈯️ H5 is much more responsive than the H3. Doesn't have a noticeable "delay" in processing/command exec the H3 has. 
- 🈴 CPU freq/scaling not supported in kernel (yet):
```
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory
cat: /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor: No such file or directory
```
- 🈯️ Network throughput:
```
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
------------------------------------------------------------
Client connecting to 192.168.0.112, TCP port 5001
TCP window size:  306 KByte (default)
------------------------------------------------------------
[  5] local 192.168.0.26 port 54994 connected with 192.168.0.112 port 5001
[  4] local 192.168.0.26 port 5001 connected with 192.168.0.112 port 52141
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-30.0 sec  3.02 GBytes   865 Mbits/sec
[  4]  0.0-30.0 sec   586 MBytes   164 Mbits/sec
```
- 🈺 SD performance just above RPi (Sandisk Extreme 32GB uhs-3 rated at 60MB/s write):
![image](https://cloud.githubusercontent.com/assets/7077026/24455845/f37b7ea0-1488-11e7-8ccc-24aa3badc2d5.png)

**Comment by Fourdee** [comment]
Completed, image live on http://dietpi.com

**Comment by southwolf** [comment]
[Wiki page](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO2)

[Official Images](https://www.mediafire.com/folder/ah4i6w029912b/NanoPi-NEO2)

AFAIK, `/sys/devices/system/cpu/cpufreq` is not working. [Ref](http://linux-sunxi.org/Cpufreq)
