### ISSUE TITLE
DietPi Image | OPi Lite

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#815]
Dev sample en route (thanks Steven), awaiting arrival.

**Comment by joaofl** [comment]
@Fourdee 

Do you think you can share some of the steps on porting and creating an image from dietpi to a new board?

I got a sample from this Roseapple pi, which I would like to give it a try. It is quiet powerful and has USB3.

http://roseapplepi.org/

**Comment by Fourdee** [comment]
@joaofl 

> Do you think you can share some of the steps on porting and creating an image from dietpi to a new board?

Yep, you'll need to start with a minimal Debian Jessie image, or, build one with ARMbian build tools (https://github.com/igorpecovnik/lib). I can compile this if needed, just let me know.

Then you can prep system for DietPi:
https://github.com/Fourdee/DietPi/blob/master/PREP_SYSTEM_FOR_DIETPI.sh

**Comment by joaofl** [comment]
@Fourdee 
I'll give it a try on my spare time then. I'm really interested on learning more about..

For this reason I started another thread for that only: https://github.com/Fourdee/DietPi/issues/822
Thanks for the support!

**Comment by Fourdee** [comment]
Board arrived.

**Comment by Fourdee** [comment]
- 🈯️ Excellent signal strength/range with onboard WiFi, impressive, 150MBit:
```
wlan0     IEEE 802.11bgn  ESSID:"Mi6"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.447 GHz  Access Point: E8:DE:27:4A:D0:66
          Bit Rate:150 Mb/s   Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:****-****-****-****-****-****-****-****  
          Power Management:off
          Link Quality=98/100  Signal level=94/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

- 🈯️ 1 http://dietpi.com/phpbb/viewtopic.php?f=8&t=1559&p=6391#p6391
- 🈯️ image: http://dietpi.com/downloads/images/DietPi_OrangePiLite-armv7-(Jessie).7z
- 🈯️ dietpi.com updated http://dietpi.com/download

**Comment by Fourdee** [comment]
Completed.
