### ISSUE TITLE
Dietpi OrangePi PC H3 New kernel?

### ISSUE THREAD

**Issue by Mister-XY** [MichaIng/DietPi#820]
Hello, is it possible that you build a Test Version for OrangePi PC with a new 4x Kernel?

**Comment by Fourdee** [comment]
@Mister-XY 

> Hello, is it possible that you build a Test Version for OrangePi PC with a new 4x Kernel?

OPi images are built with ARMbian build tools, and optimized for DietPi.

We do not provide images for dev kernel (4.x mainline) at this time (-RPi). We did try it in the past, however, as this is a testing/dev branch, future kernel updates from ARMbian repo broke basic features. No fault of ARMbian, but too unstable for our end users.

If/when stable branch reaches 4.x kernel, we'll update our images. Appears legacy 3.x is still in use and no stable 4.x yet:
https://www.armbian.com/orange-pi-pc/

I'll mark this as closed, please reopen if required.

**Comment by Mister-XY** [comment]
Ok thats not so good, i need a dvb-t2 driver.
