### ISSUE TITLE
DietPi-Software | Add shoutcast/icecast server 

### ISSUE THREAD

**Issue by phonicmouse** [MichaIng/DietPi#826]
✌

**Comment by Fourdee** [comment]
Darkice (audio input) + Icecast (streaming server) looks a good combo:
- https://github.com/rafael2k/darkice
- https://github.com/xiph/Icecast-Server

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/24579431/929a7890-16ed-11e7-8691-6bccf94d3e9b.png)

**Comment by Fourdee** [comment]
Online doc:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=6526#p6526

**Comment by Fourdee** [comment]
Test (Wish I had a mic lol):
- 🈯️ Sparky + Allo Piano 2.1 (overkill) > RPi 3 + USB DAC mic input > Web stream
![image](https://cloud.githubusercontent.com/assets/7077026/24586506/b1e7388e-179a-11e7-9075-b088c209f205.png)

**Comment by Fourdee** [comment]
Completed

**Comment by phonicmouse** [comment]
Awesome!!! Thanks ✌

**Comment by Fourdee** [comment]
@phonicmouse 
No worries.
Will be available in v148 update once completed/released (1 week ish 😄 )

**Comment by Invictaz** [comment]
Great

**Comment by phonicmouse** [comment]
🤘
