### ISSUE TITLE
DietPi Images | CRC/MD5 hash for all images

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#831]
> https://github.com/Fourdee/DietPi/issues/830#issue-216664900

**Comment by shellshocker** [comment]
Please use SHA-256 or higher for the checksum. MD5 is old and broken.

**Comment by k-plan** [comment]
> Please use SHA-256 or higher for the checksum. MD5 is old and broken.

To check, if a downloaded and extracted image is corrupt? No.
SHA-256 is very bulky for human reading.
So please offer both checksum in one file, so human or software can decide, which one to use.
Most will do so.

**Comment by Fourdee** [comment]
Current:
[hash.txt](https://github.com/Fourdee/DietPi/files/892852/hash.txt)

For all future image updates, i'll include the hash inside the zip file.

**Comment by Fourdee** [comment]
Marking as completed.

Until we update all image downloads, and the zip contains a ```hash.txt```, see https://github.com/Fourdee/DietPi/files/892852/hash.txt for current hashes.
