### ISSUE TITLE
gogs not installing

### ISSUE THREAD

**Issue by mikolaj24** [MichaIng/DietPi#833]
Probably change urf for blob zip binary install
https://dl.gogs.io/gogs_v0.9.141_raspi2.zip

install info https://www.linode.com/docs/applications/development/install-gogs-on-debian-8-jessie/

**Comment by Fourdee** [comment]
@mikolaj24 

Thanks.

Appears Gogs has renamed/moved their "latest" binary links, yet again 👎 
https://github.com/Fourdee/DietPi/issues/793

**Comment by Fourdee** [comment]
We'll host binaries on DietPi.com. Whoever maintains https://dl.gogs.io/ needs a slap.

**Comment by Fourdee** [comment]
@mikolaj24 

Fixed for v148, you can patch now with:
```
wget https://github.com/Fourdee/DietPi/raw/886d0d43f0fecc8f579155a75268da84ba3becb4/dietpi/dietpi-software -O /DietPi/dietpi/dietpi-software

#Install gogs with
dietpi-software install 49
```

**Comment by Fourdee** [comment]
Completed.
