### ISSUE TITLE
DietPi-Set_Hardware | RPi OpenGL hangs xinit

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#834]
Complete system lock, unresponsive, possible driver issue.

### Workaround/Fix: https://github.com/Fourdee/DietPi/issues/834#issuecomment-291507267

**Comment by Fourdee** [comment]
Temp solution, disable openGL:
```
/DietPi/dietpi/func/dietpi-set_hardware rpi-opengl disable
```

Fresh installs of v147:
- We've disabled activating OpenGL during the Chromium installation for now.

**Comment by Fourdee** [comment]
Thanks to @midwan 👍  confirmed on latest firmware:

> Also with the latest firmware update on the Pi, all the SDL2 apps that used OpenGLES2 stopped working. Rolled back to the previous version and the work again

**Comment by Fourdee** [comment]
Kernel tests:
- 🈴 RPi Official via apt: ```4.4.50```
- 🈯️ rpi-update: ```4.9.20```

Clearly an issue with the kernel, OpenGL broken currently in  ```4.4.x```

Not much we can do about this at the moment.  Our DietPi kernel is  ```4.4.x```, inline with official kernel via apt (stable). I'am not keen on bumping upto to ```4.9.x``` just yet, still in heavy dev/testing.

Will mark as known issue with workaround.

**Comment by Fourdee** [comment]
### Workaround/Fix: Update RPi kernel to ```4.9```
NB: This will remove support for Allo Piano 2.1 and BOSS DAC's, 192KHz HDMI output.

```
apt-get install rpi-update
SKIP_BACKUP=1 rpi-update
reboot
```

**Comment by Fourdee** [comment]
@midwan

Looks like ```4.9``` kernel install is solution for OpenGL functionality: https://github.com/Fourdee/DietPi/issues/834#issuecomment-291501770

**Comment by midwan** [comment]
@Fourdee 
However, I found that going to kernel 4.9 broke the ability to start SDL2 applications from the console (i.e. not from within X11). Not just Amiberry, but any test code I tried. They all failed to find a render driver, even when run with xinit.

Maybe you'll have better luck and I did something wrong, but I tried it several times with the same result always... :(

**Comment by Fourdee** [comment]
@midwan 

> However, I found that going to kernel 4.9 broke the ability to start SDL2 applications from the console (i.e. not from within X11). Not just Amiberry, but any test code I tried. They all failed to find a render driver, even when run with xinit.

Thanks for the heads up 👍, very strange. I'll reference this to ticket:
https://github.com/Fourdee/DietPi/issues/850

**Comment by Fourdee** [comment]
Confirmed working on our Stretch image with our latest 4.9.62 kernel: https://github.com/Fourdee/DietPi/issues/475

Marking as completed, Stretch image will be released at weekend.
