### ISSUE TITLE
wifi Country

### ISSUE THREAD

**Issue by mikolaj24** [MichaIng/DietPi#838]
I cant set my country in diet-config wifi
I get

Country code (PL) could not been applied. Please    │ 
                       │ check the country code and try again.

**Comment by Fourdee** [comment]
@mikolaj24 

```iw reg set``` (used by DietPi-Config) does not work in all instances, depends on kernel version and WiFi chipset used.

Please try this alternative method:
```
echo -e "options cfg80211 ieee80211_regdom=PL" > /etc/modprobe.d/cfg80211.conf
reboot
```

Then check with:
```
iw reg get
```

**Comment by Fourdee** [comment]
We'll apply to ```ieee80211_regdom=```, as well as ```iw reg set```.

**Comment by Fourdee** [comment]
@mikolaj24 

Did this work for you? https://github.com/Fourdee/DietPi/issues/838#issuecomment-289210613

**Comment by Fourdee** [comment]
I'll mark this as closed. 
We now apply ```iw reg set``` and ```ieee80211_regdom=```. Aside from any module params, this is it in terms of applying country code, then, its up to kernel support for the WiFi chipset.

**Comment by symbios24** [comment]
Hello, i`m getting the Country code (US) could not been applied.
I tried your fix (echo -e "options cfg80211 ieee80211_regdom=US" > /etc/modprobe.d/cfg80211.conf) 
its not working 
Any solution?

**Comment by symbios24** [comment]
Hello, i`m getting the Country code (US) could not been applied.
I tried your fix (echo -e "options cfg80211 ieee80211_regdom=US" > /etc/modprobe.d/cfg80211.conf)
its not working
Any solution?

Plus i cannot the the wifi hotspot from any device computer/smartphone is this normal?
From Dietpi setting i see that its enabled.

**Comment by symbios24** [comment]
Hello, i`m getting the Country code (US) could not been applied.
I tried your fix (echo -e "options cfg80211 ieee80211_regdom=US" > /etc/modprobe.d/cfg80211.conf)
its not working
Any solution?

Plus i cannot see the wifi hotspot from any device computer/smartphone is this normal?
From Dietpi setting i see that its enabled.

**Comment by symbios24** [comment]
Hello, i tried the DietPi stretch  for my raspberryPi 3 i`m getting the Country code (US) could not been applied.
I tried your fix (echo -e "options cfg80211 ieee80211_regdom=US" > /etc/modprobe.d/cfg80211.conf)
its not working
Any solution?

Plus i cannot see the wifi hotspot from any device computer/smartphone is this normal?
From Dietpi setting i see that its enabled.

After that i tried the DietPi Jessie and i can see the hotspot from my devices i did not try to change the country thought.

Thanks

**Comment by Fourdee** [comment]
@symbios24  

Thanks for the report 👍 i'll investigate/test

RE: @k-plan 

Notes: believe we removed ```iw reg set``` in preference of ```wpa_supplicant.conf``` settings.

**Comment by k-plan** [comment]
@Fourdee 

on a running v6.-1 Odroid C1 (jessie):

![180119-0001](https://user-images.githubusercontent.com/17237601/35167715-c84d5f98-fd56-11e7-9f81-57be0f24b292.gif)

![180119-0003](https://user-images.githubusercontent.com/17237601/35167810-1b15e470-fd57-11e7-9c18-24b3e170ecf4.gif)


![180119-0002](https://user-images.githubusercontent.com/17237601/35167736-d74db9a2-fd56-11e7-8852-923e53687400.gif)



```
root@Odroid-C1:~# cat /etc/wpa_supplicant/wpa_supplicant.conf
country=JP
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="MySuperDooperWiFi"
    key_mgmt=WPA-PSK
    psk="0123456789"
}
```

```
root@Odroid-C1:~# cat /etc/modprobe.d/cfg80211.conf
options cfg80211 ieee80211_regdom=GB
```

```
root@Odroid-C1:~# iw reg get
country 00: DFS-UNSET
        (2402 - 2472 @ 40), (6, 20), (N/A)
        (2457 - 2482 @ 40), (6, 20), (N/A), PASSIVE-SCAN
        (2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 160), (6, 20), (N/A), PASSIVE-SCAN
        (5250 - 5330 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
        (5490 - 5730 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN

```

**Comment by Fourdee** [comment]
We'll need to bring back ```iw reg set```, as a fallback/in-addition of ```wpa_supplicant.conf```:
```
root@DietPi:~# iw reg get
country 00: DFS-UNSET
        (2402 - 2472 @ 40), (6, 20), (N/A)
        (2457 - 2482 @ 40), (6, 20), (N/A), PASSIVE-SCAN
        (2474 - 2494 @ 20), (6, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 160), (6, 20), (N/A), PASSIVE-SCAN
        (5250 - 5330 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
        (5490 - 5730 @ 160), (6, 20), (0 ms), DFS, PASSIVE-SCAN
root@DietPi:~# iw reg set GB
root@DietPi:~# iw reg get
country GB: DFS-ETSI
        (2402 - 2482 @ 40), (N/A, 20), (N/A)
        (5170 - 5250 @ 80), (N/A, 20), (N/A)
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS
        (5490 - 5710 @ 160), (N/A, 27), (0 ms), DFS
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)

```

Believe this is kernel related, either way, ```iw reg set``` will be added back in, as per before its removal (due to ```wpa_supplicant.conf```)

**Comment by Fourdee** [comment]
@k-plan 
https://github.com/Fourdee/DietPi/issues/838#issuecomment-359170668 | https://github.com/Fourdee/DietPi/commit/f6799dc099ea9dda4d9cc26a1f06507473b46701
Resolved, i've tested C1 (your image, works a treat 👍 ) in ```dietpi-config``` and also sets during boot.

Marking as completed.

**Comment by symbios24** [comment]
What i have to do now to be fixed on me? 
i only have to update DietPi stretch?

Thanks

**Comment by Fourdee** [comment]
@symbios24 

You'll need the updated v6.0 image, will be released next week, you can try it below:
http://dietpi.com/downloads/testing/v6.0/
RPi 3 image = http://dietpi.com/downloads/testing/v6.0/DietPi_RPi-ARMv6-Stretch.7z

**Comment by symbios24** [comment]
Thanks
another thing now if its possible
i removed the card with DietPi from my raspberry pi3 and insert it in my raspberry pi Model B that has a usb WIfi Adapter(realtek) is it possible the WifiHotspot to see and configure automatically any usb/or internal wifi adapter so it works at any time without any setup if you change wifi adapter or board?? i`m asking because the hospot is not active like this.

**Comment by symbios24** [comment]
Can you do the wifi to work automatic i mean if you have a raspberry pi 3 with internal wifi only to use it, or if you have a usb wifi to use that instead without the need to configure it from network adapters menu.
thanks
