### ISSUE TITLE
DietPi-Software | NTPD wait tweaks

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#840]
> http://dietpi.com/phpbb/viewtopic.php?f=9&t=1572&p=6426#p6426

- 🈯️ Disable wait (assume failed) instantly, if no connection is available on adapters
- 🈯️ Re-run ntpd completion check again, prior to ```Run_Install()``` (eg: user enters WiFi creds, reloads dietpi-software). If no connection is still available at this point, ```Check_Connection()``` will prevent progress, before NTPD status is checked.

**Comment by k-plan** [comment]
@Fourdee 

occur this only, if WiFi (WLAN) configured to use DHCP client?

If so, it will be worth to test a option `raspi-config` use:

![170326-0003](https://cloud.githubusercontent.com/assets/17237601/24333207/0c4823a2-1254-11e7-8b2b-0ad327142cde.gif)

Please take a look here:

https://github.com/raspberrypi-ui/rc_gui/blob/bf829a6cd4a130eaa421e1a39cee6388301f8414/raspi-config#L854

--------------

A similar question can be found here:

https://gitter.im/DietPi/Lobby

**Comment by Fourdee** [comment]
@k-plan 

Thanks 👍 

Notes:
- ```route | grep -m1 -ci '[[:space:]]UG[[:space:]]'```

**Comment by Fourdee** [comment]
@k-plan 

This already exists in our boot script: https://github.com/Fourdee/DietPi/blob/master/dietpi/boot#L235-L260

Although, it will time out after 10 seconds of waiting. I'll add an option in ```dietpi-config``` to allow infinite wait: https://github.com/Fourdee/DietPi/issues/842

**Comment by Fourdee** [comment]
Implemented changes as per: https://github.com/Fourdee/DietPi/issues/840#issue-217061769

Completed.
