### ISSUE TITLE
DietPi Image | NanoPi M1+

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#843]

**Comment by aliosa27** [comment]
i'll work on this one

**Comment by Fourdee** [comment]
@aliosa27 

> i'll work on this one

Thanks 👍 
Unfortunately, I finished the image yesterday but didn't get a chance to update here. Apologies for that. Although, if you could test it on your system aswell, I'd be greatful.

I'll get it uploaded today with: https://github.com/Fourdee/DietPi/issues/814 and let you know.

**Comment by Fourdee** [comment]
Completed, image live on http://dietpi.com
