### ISSUE TITLE
DietPi-Config | Soundcard: Support pHAT BEAT for Raspberry Pi's

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#846]
Product:

https://shop.pimoroni.com/products/phat-beat

https://shop.pimoroni.com/products/pirate-radio-pi-zero-w-project-kit

Code on Github:

https://github.com/pimoroni/phat-beat

https://github.com/pimoroni/clean-shutdown

https://github.com/pimoroni/phat-beat/tree/master/projects/vlc-radio

**Comment by Fourdee** [comment]
@k-plan 

Looks great, i'll get one ordered. Had my eye on this one aswell for a while: https://shop.pimoroni.com/products/speaker-phat

Lets get them both added :)

**Comment by Fourdee** [comment]
Worth a shot, lets see:
https://twitter.com/DietPi_/status/847139159672324096

**Comment by k-plan** [comment]
- pHAT BEAT Web-Radio based on [Mopidy](https://learn.pimoroni.com/tutorial/sandyj/streaming-spotify-to-your-pi) with [ODROID-SHOW2](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G141743018597) as display:

![2017-04-09 20-12-13](https://cloud.githubusercontent.com/assets/17237601/24840231/cb1b4528-1d69-11e7-9243-38b881e4046d.jpg)

- autoplay specify playlist, after device has boot up
- display shows radio station, track info and some device infos. Auto refresh every 15 sec.
- RPi-Zero W overclocked to: `arm_freq=1050
core_freq=500
sdram_freq=500
gpu_freq=500
sd_clock=100.000 MHz`
- current consumption: ca. 390 mA via USB powerbank  for RPi-Zero W (using WiFi) with pHAT BEAT (incl. VU Meters), stereo speaker 8 Ohm, Odroid-show2 display, usb hub with ethernet adapter

😃 

![2017-04-09 22-14-44](https://cloud.githubusercontent.com/assets/17237601/24840711/69e97ff0-1d72-11e7-90ce-15b6054ed9f8.jpg)


cons: 
- have to disable [clean-shutdown](https://github.com/pimoroni/clean-shutdown) because this script give rise to 100% cpu load. (normal running at 43 - 49 % cpu load)

**Comment by Fourdee** [comment]
@k-plan 

> pHAT BEAT Web-Radio based on Mopidy with ODROID-SHOW2 as display:

Epic 👍 

> have to disable clean-shutdown because this script give rise to 100% cpu load

Try moving this line:
https://github.com/pimoroni/clean-shutdown/blob/master/daemon/usr/bin/cleanshutd#L65

To, below the ```fi``` line:
https://github.com/pimoroni/clean-shutdown/blob/master/daemon/usr/bin/cleanshutd#L66

eg:
```
while [ $daemon = "on" ]; do
    if [ $(raspi-gpio get $trigger_pin | grep -c "level=0 fsel=0 func=INPUT") = 1 ]; then
        echo "BCM $trigger_pin asserted low, system shutdown in $shutdown_delay minutes"
        daemon="off" && shutdown -h +$shutdown_delay

    fi
    sleep $polling_rate
done
```

**Comment by Invictaz** [comment]
@k-plan Great project

**Comment by Fourdee** [comment]
#### Speaker-phat:
- 🈯️ Audio fine with hifiberry-dac overlay
- 🈴 Fails with ALSA dmix for VU meter https://github.com/pimoroni/pivumeter
```
root@DietPi:~# speaker-test -c2

speaker-test 1.0.28

Playback device is default
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
ALSA lib pcm_direct.c:896:(snd1_pcm_direct_initialize_slave) slave plugin does not support mmap interleaved or mmap noninterleaved access
ALSA lib pcm_dmix.c:1034:(snd_pcm_dmix_open) unable to initialize slave
Playback open error: -22,Invalid argument
```
