### ISSUE TITLE
DietPi Software | CPU temperature not shown on Roseapple Pi

### ISSUE THREAD

**Issue by joaofl** [MichaIng/DietPi#848]
CPU temperature is not shown by the "cpu" command.

Have to take a look at that. Must be the same as for the sparky board.

**Comment by Fourdee** [comment]
@joaofl 

Sparky CPU temp is a little different, has a special case:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-cpuinfo#L73-L82

https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-cpuinfo#L59

**Comment by joaofl** [comment]
@Fourdee 
Thanks for the link
I'll also check out how it is done on the Armbian distribution. It works there.

**Comment by joaofl** [comment]
@Fourdee 
Your suggestions worked right on. I've made a pull request to fix that: https://github.com/Fourdee/DietPi/pull/858

So I think I can close the issue.

**Comment by joaofl** [comment]
I've run a 5 min strees test from dietpi, and here is what I've got. It kind of runs cool.

It seems to stabilize around 60, but it is probably worth testing it for longer.

```
Wed Apr  5 04:04:48 BST 2017 | 45'c
...
Wed Apr  5 04:06:09 BST 2017 | 53'c
...
Wed Apr  5 04:08:17 BST 2017 | 56'c
...
Wed Apr  5 04:09:46 BST 2017 | 58'c
```

**Comment by Fourdee** [comment]
@joaofl 

Great work. Temps look good 👍
