### ISSUE TITLE
odroid apt repository timeout

### ISSUE THREAD

**Issue by woulf** [MichaIng/DietPi#849]
Hello, since yesterday apt-get update give me some errors about http://fuzon.co.uk/meveric/ tree.
I tried checking with http://dietpi.com/meveric with no luck
Should i directly use meveric apt repository? (http://oph.mdrjr.net/meveric/)
I there a new url i should use in my source.list?

i'm running v147 on both c2 and xu4

edit: attached log
[log.txt](https://github.com/Fourdee/DietPi/files/884768/log.txt)
edit2: Migth be due to this outage https://status.myvirtualserver.com/incident/204

**Comment by Fourdee** [comment]
@woulf 

Thanks for the report 👍 

Yep, appears the server has stalled and is in "offline" state. Strange, usually it restarts itself. Its been rebooted and is now back up and functional.
http://fuzon.co.uk/meveric/

**Comment by woulf** [comment]
Everything working as expected
thanks!
