### ISSUE TITLE
DietPi-Software | Removal of OMV, due to incompatibly with DietPi (eg: NextCloud install)

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#851]
Incompatible with DietPi:
http://dietpi.com/phpbb/viewtopic.php?f=11&t=1435&p=6524#p5976

**Comment by k-plan** [comment]
@Fourdee 

https://github.com/Fourdee/DietPi/issues/721#issuecomment-274515323

Yes, drop it from the list now.

Problem are inexperienced user. 
They don't have any idea what they really need or want, playing around, don't read, think or glean, but instantly open a new forum thread or a ticket.

Sorry.
Effort for support will kill the benefit.

**Comment by Fourdee** [comment]
@k-plan 

> Effort for support will kill the benefit.

Agree with you completely, and, DietPi can do most of what OMV does anyway, if not "better" (smaller footprint). I'll disable the install for now.

**Comment by Fourdee** [comment]
Install disabled. Marking as completed.
