### ISSUE TITLE
DietPi-Software | VirtualHere

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#852]
> https://twitter.com/ta11/status/848503358059139072
https://www.virtualhere.com/home

Basically share USB devices over the network, as if they were physically connected locally.

**Comment by tatoosh** [comment]
Nice, it works very good with deitpi by installing manually and adding systemd service.

**Comment by phonicmouse** [comment]
+1 for this

**Comment by Fourdee** [comment]
- ARMv6+: https://virtualhere.com/sites/default/files/usbserver/vhusbdarm
- ARM64: https://virtualhere.com/sites/default/files/usbserver/vhusbdarm64
- AMD64: https://virtualhere.com/sites/default/files/usbserver/vhusbdx86_64

**Comment by Fourdee** [comment]
- 🈯️ Online Doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=6709#p6709

Virtual Here is excellent, really impressed.
![image](https://cloud.githubusercontent.com/assets/7077026/24836989/b91ea006-1d21-11e7-9b3a-2d4ee0cfa2e2.png)

**Comment by Fourdee** [comment]
Ok, there is a minor issue with attached USB drives. 
- 🈺 Virtual here will unmount and take over all USB drives on system, excluding those in-use  (eg: DietPi user data)
- 🈴 Using the USB drive in client, will unmount the drive, regardless of if its in-use or not. (no longer shown in ```blkid``` and ```df```)

In other words, dont use mounted drives in the client, will make users aware in online doc.

**Comment by Fourdee** [comment]
Completed.
