### ISSUE TITLE
DietPi-Software | CloudPrint

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#855]
> http://dietpi.com/phpbb/viewtopic.php?f=12&t=1624#p6617

I do not own a printer (yet) 😆

**Comment by Invictaz** [comment]
If it works on the Zero / Zero W would be great. Hopefully also with HTTPS and low memory footprint.

**Comment by Fourdee** [comment]
Notes:
- 🈯️ Online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=100#p6630

**Comment by Fourdee** [comment]
- 🈴 ARM64:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Suite: stable
Codename: cloudprint-jessie
Date: Sat, 27 Aug 2016 16:00:42 UTC
Architectures: amd64 i386 armhf armel
```
- 🈺 ARMv6 needs testing. Cloud service seems happy, but unable to test with printer to verify.

**Comment by Fourdee** [comment]
Needs testing by user with printer (I do not own one) :
```
root@DietPi:~# systemctl status cloudprintd -l
● cloudprintd.service - Google Cloud Print proxy service
   Loaded: loaded (/lib/systemd/system/cloudprintd.service; disabled)
   Active: inactive (dead)

Apr 04 14:40:07 DietPi systemd[1]: Starting Google Cloud Print proxy service...
Apr 04 14:40:07 DietPi systemd[1]: Started Google Cloud Print proxy service.
Apr 04 14:40:08 DietPi cloudprintd[6426]: No printers found
```

---

- Requires testing branch install:
https://github.com/Fourdee/DietPi/blob/master/TESTING-BRANCH.md
- install CloudPrint with
```dietpi-software install 137```
- Continue configuration as per **STEP 2**: https://davesteele.github.io/raspberrypi/2016/04/23/raspberry-pi-cloudprint/
- CUPS web interface login
user = root
pw = dietpi

**Comment by Fourdee** [comment]
Confirmed working, thanks Sciamano  :
http://dietpi.com/phpbb/viewtopic.php?f=12&t=1624&p=6644#p6636

**Comment by Fourdee** [comment]
Completed.

**Comment by Fourdee** [comment]
cloudprint package is available in Jessie repos, investigate and convert from Dave Steele's repo if functional ( 🈯️ +ARM64 binaries):
http://dietpi.com/phpbb/viewtopic.php?f=12&t=1624&p=6660#p6659

- 🈴 Fails, outdated auth system used in binary? http://dietpi.com/phpbb/viewtopic.php?f=12&t=1624&start=10#p6688

**Comment by Fourdee** [comment]
- Jessie repo versions:
```
root@DietPi:~# dpkg -l | grep cloudprint
ii  cloudprint                     0.11-5                       all          Google Cloud Print proxy
ii  cloudprint-service             0.11-5                       all          provide a service for sharing printers on Google Cloud Print
```

```
root@DietPi:~# cloudprint -c -a /var/lib/cloudprintd/authfile.json
Google username: mygoogleusername
Password:
Traceback (most recent call last):
  File "/usr/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.11', 'console_scripts', 'cloudprint-cmd')()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 496, in main
    sync_printers(cups_connection, cpp)
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 330, in sync_printers
    remote_printers = dict([(p.name, p) for p in cpp.get_printers()])
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 177, in get_printers
    r = self.get_rest()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 173, in get_rest
    auth = self.get_auth()
  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 99, in get_auth
    'application/x-www-form-urlencoded')
  File "/usr/share/cloudprint/cloudprint/rest.py", line 122, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:404
Message: https://developers.google.com/accounts/docs/AuthForInstalledApps
```

- Dave Steele Repo:
```
root@DietPi:~# dpkg -l | grep cloudprint
ii  cloudprint                    0.14-5+deb8u1+ppa1              all          Google Cloud Print proxy
ii  cloudprint-service            0.14-5+deb8u1+ppa1              all          provide a service for sharing printers on Google Cloud Print
```

```
root@DietPi:~# cloudprint -c -a /var/lib/cloudprintd/authfile.json
No printers found
```

- Stretch Repo:
Contains ```cps-auth```:
https://packages.debian.org/stretch/all/cloudprint-service/filelist

Debs:
http://ftp.us.debian.org/debian/pool/main/c/cloudprint/cloudprint-service_0.14-8_all.deb
http://ftp.us.debian.org/debian/pool/main/c/cloudprint/cloudprint_0.14-8_all.deb
```
dpkg: dependency problems prevent configuration of cloudprint:
 cloudprint depends on python-daemon (>= 2.0); however:
  Version of python-daemon on system is 1.5.5-1.
```
Lets avoid dependency wars on this one...

**Comment by Fourdee** [comment]
Ok, so we'll use Dave Steele's repo for Jessie. Stretch will use Debian repos for install and support ARM64.

**Comment by Fourdee** [comment]
Completed.

**Comment by Fourdee** [comment]
Reference, Stretch support: https://github.com/Fourdee/DietPi/issues/475
