### ISSUE TITLE
Pi zero W hotspot instructions

### ISSUE THREAD

**Issue by JohnMacrae** [MichaIng/DietPi#856]
I tried the software install for wireless hotspot but of course there's no Ethernet. Is there an alternative method please. If so, please update software web page. The 😁

**Comment by Fourdee** [comment]
@9H5G 

Our WiFi hotspot install is designed for internet routing and requires:
- 1x WiFi
- 1x Ethernet

If you want a hotspot without network routing, you'll need to manually install it and set it up as needed.

**Comment by JohnMacrae** [comment]
Ok. Thx. Will your install work as a local router if the ethernet is
removed after installation?

**Comment by Fourdee** [comment]
> Ok. Thx. Will your install work as a local router if the ethernet is
removed after installation?

@9H5G 

Should be fine, give it a whirl :)

**Comment by Fourdee** [comment]
No updates/responses, assuming resolved. Please reopen if required.
