### ISSUE TITLE
DietPi-Software | Filerun

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#857]
NextCloud alternative, PHP

> http://dietpi.com/phpbb/viewtopic.php?f=12&t=1582
http://www.filerun.com/demo
http://www.filerun.com/download
http://blog.filerun.com/how-to-install-filerun-on-ubuntu-16/

**Comment by tatoosh** [comment]
+1

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
