### ISSUE TITLE
DietPi-Config | Option to rotate RPi LCD touchscreen

### ISSUE THREAD

**Issue by midwan** [MichaIng/DietPi#859]
It would be great if we had the option to rotate the RPI LCD (touch)screen.
Some cases require that you flip them 180 degrees, and that can be accomplished by entering the following line in /boot/config.txt:

lcd_rotate=2

Note that this takes care of rotating the touch input as well, in contrast to:

display_rotate = 2

which would rotate the display, but not the touch input layout.

**Comment by Fourdee** [comment]
@midwan 

Thanks 👍 

We'll get this added for v149.

**Comment by midwan** [comment]
Great! :)

**Comment by Fourdee** [comment]
@midwan 
On the RPi Touchscreen (I lack one for testing), when using ```lcd_rotate=1``` or ```3```, do also need to flip the ```framebuffer_width``` and ```framebuffer_height``` values to get full screen FB (as per HDMI and ```display_rotate```)?

**Comment by midwan** [comment]
@Fourdee I never had to use those values, so I'm not sure. I can run a test though a bit later and let you know.

I usually have lcd_rotate=2 to flip the screen 180 degrees, which is required for several cases ;)

**Comment by Fourdee** [comment]
@midwan 

>  never had to use those values, so I'm not sure. I can run a test though a bit later and let you know.

Thanks, would be a great help 👍

**Comment by midwan** [comment]
@Fourdee 

Had a chance to test this:
lcd_rotate only has an effect if specified with value "2" (rotate 180 degrees).
For other scenarios (e.g. Portrait mode) we have to use display_rotate with any extra options.
Relevant thread: https://www.raspberrypi.org/forums/viewtopic.php?f=108&t=120793

**Comment by Fourdee** [comment]
@midwan 

Legend, thank you 👍

**Comment by Fourdee** [comment]
Completed.
