### ISSUE TITLE
DietPi-Software | SabNZBd 

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#865]
> https://sabnzbd.org/

https://github.com/Fourdee/DietPi/issues/731#issue-202979307

**Comment by Invictaz** [comment]
Don't forget to include SABYenc, a module for CPU limited devices like the Raspberry Pi. It's new in the V2.0 RC version.

https://sabnzbd.org/wiki/installation/sabyenc.html

**Comment by Fourdee** [comment]
Notes:
- Jessie apt = ```sabnzbdplus (0.7.18-1)``` | git ```2```
-  http://192.168.0.105:8080/sabnzbd
- ```.sabnzbd/sabnzbd.ini``` https://sabnzbd.org/wiki/advanced/command-line-parameters
- ```python /etc/sabnzbd/SABnzbd.py -f /etc/sabnzbd/sabnzbd.ini```
- 🈺 Stuck in wizard loop... If API keys removed from our config template, keys only get generated if no config file exists. | 🈯️ run binary, generate conf, term binary, sed replace.
- 🈺 ```Unrar-free``` Your UNRAR version is 0.00, we recommend version 5.00 or higher. | http://ftp.debian.org/debian/pool/non-free/u/unrar-nonfree/ | full unrar for non-RPi's only.
- 🈺 Optional: Multicore par2 needs user compile: https://sabnzbd.org/wiki/installation/multicore-par2
- 🈯️ Online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=6747#p6747

**Comment by Invictaz** [comment]
@Fourdee Amazing you got it working. I'm really happy.

One question isn't 0.7 a bit old? That was launched in 2014.

https://tweakers.net/downloads/33035/sabnzbd-0718.html

**Comment by Fourdee** [comment]
> One question isn't 0.7 a bit old?

@Invictaz 

Yep, we wont be using apt-get for this one, we'll pull in from git (v2.0.0):
https://github.com/sabnzbd/sabnzbd/releases

**Comment by Fourdee** [comment]
Completed.

**Comment by Invictaz** [comment]
@Fourdee It installed now. Working great.

How to update to 2.0.1 RC1? It installs 2.0.0

There isnt a setting in Sabnzbd to update and 2.0.0 seems to be hardcoded?

**Comment by Fourdee** [comment]
> There isnt a setting in Sabnzbd to update and 2.0.0 seems to be hardcoded?

@Invictaz 

Yes its hard coded to install 2.0.0 

RC = release candidate. Potentially unstable.

We'll stick with 2.0.0 for now (stable), and update our install code when a future stable version of Sabnzbd is released.

**Comment by Invictaz** [comment]
Is there any way I can install it myself? If I really want to? Just unzip the contents?
Especially on Kodi RC's give vast improvements.

Found it: https://forums.sabnzbd.org/viewtopic.php?f=16&t=9844

Get it from Git and unzip. Not in its own directory but straight into sabnzbd so it has no deeper subfolder with the version number

unzip package.zip -d /etc/sabnzbd  
rm -R /etc/sabnzbd/sabnzbd-"$version"

**Comment by Invictaz** [comment]
@Fourdee 2.01 final was released.

Can you update it please?

https://github.com/sabnzbd/sabnzbd/releases/tag/2.0.1

**Comment by Fourdee** [comment]
@Invictaz 

Thanks for heads up 👍 

Done. Test install fine aswell.

**Comment by DasClarky** [comment]
2.1.0 is out, please update

**Comment by Fourdee** [comment]
@hydrouk 

Thanks 👍 

Done for v155. This won't effect existing installs of Sabnzbd, only new installs.

To try a manual upgrade (via reinstall), backup system 1st and run:
```
dietpi-software reinstall 139
```

**Comment by Invictaz** [comment]
@Fourdee Why 'reinstall 139' and not the newest DietPi version? Or is 139 the number of SabNZBd in dietpi-software?

**Comment by k3anton** [comment]
@Invictaz The number 139 refers to the software numbering within DietPi and has nothing to do with versions of that specific software.

**Comment by DasClarky** [comment]
I have run the reinstall a couple of times but it is still installing version 2.0.1, current version is 2.1.0

**Comment by k3anton** [comment]
@hydrouk I can also confirm what you are saying.

**Comment by DasClarky** [comment]
Ahh i just noticed it is done for v155, current version is v154, my bad @Fourdee

**Comment by Invictaz** [comment]
Better do 2.2.0 instead of 2.1.0 for v155. 2.2.0 is now in it's last release candidate. Wont be long until final. 
Has some major improvements.

**Comment by Fourdee** [comment]
@Invictaz 

2.2.0 is currently RC2, we'll stick with stable 2.1.0 for now.

**Comment by Invictaz** [comment]
Yeah but by the time 155 comes I mean. Or is that not too far away?

**Comment by Invictaz** [comment]
There it is, even 2.2.1 final

https://sabnzbd.org/downloads?v=2.2.1

**Comment by DasClarky** [comment]
Update Available! 2.3.0

Just so you know :) Thanks @Fourdee

**Comment by Invictaz** [comment]
2.3.1 released. Thanks @Fourdee 
https://tweakers.net/downloads/42607/sabnzbd-231.html

**Comment by clarky0000** [comment]
Im getting this in sabnzbd GUI and .rar archives are not being unzipped...

Your UNRAR version is 0.00, we recommend version 5.00 or higher.<br />

When i try to install unrar-free
-------------------------------
root@DietPi:~# apt-get install unrar-free
Reading package lists... Done
Building dependency tree
Reading state information... Done
unrar-free is already the newest version (1:0.0.1+cvs20140707-1).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
--------------------------------

Help me out - what am I missing?

**Comment by Fourdee** [comment]
@clarky0000 

Hi, ```unrar``` (non-free) is not available in the Raspbian repos. Try manually install it from Debian:
```
G_AGP unrar-free

wget http://ftp.us.debian.org/debian/pool/non-free/u/unrar-nonfree/unrar_5.3.2-1+deb9u1_armhf.deb -O package.deb
dpkg -i package.deb
dietpi-services restart
```

**Comment by clarky0000** [comment]
Thanks for you help on that. Im also getting these messages in sabnzbd:

_yenc module... NOT found!
SABYenc disabled: no correct version found! (Found v3.3.2, expecting v3.3.1)

Can I disregard those?

**Comment by Fourdee** [comment]
https://sabnzbd.org/wiki/installation/sabyenc.html

@clarky0000 

Seems your current install requires a specific version, run the following command to achieve it:
```
pip install sabyenc==3.3.1
dietpi-services restart
```

verify with:
```
python -c "import sabyenc ; print sabyenc.__version__ "
```

Where did you receive that error, which logfile?

**Comment by clarky0000** [comment]
Thats fixed it - thanks! 

root@DietPi:~# python -c "import sabyenc ; print sabyenc.__version__ "
3.3.1

I was just seeing it in the UI.  Thanks for your help - much appreciated. 

Final question - I promise - I can see there is a newer version of Sabnzbd available. Can you tell me the best command to perform the upgrade?

Cheers,
Clarky

**Comment by Fourdee** [comment]
@clarky0000 

> Final question - I promise - I can see there is a newer version of Sabnzbd available. Can you tell me the best command to perform the upgrade?

We only provide installs for stable releases. RC is release candidate (potentially unstable). Once 2.3.3 becomes stable release, we'll update and patch via ```dietpi-update```.
