### ISSUE TITLE
DietPi-RAMLog | Support 24H clear for PiHole FTL

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#868]
> https://github.com/pi-hole/FTL/issues/12#issuecomment-292726957

**Comment by Fourdee** [comment]
```/var/log/pihole-FTL.log```

**Comment by Fourdee** [comment]
Completed.

**Comment by k-plan** [comment]
> ### *Note by DL6ER:*
> ---------------
> Rolling log will not work without pihole.log.1, so there is nothing we would have to change here. Users have to be aware of limitations and _*without logrotate*_ they cannot have it.
>
>@pi-hole/dashboard We have to keep that in mind when bug reports about not seeing the rolling window are coming in...
