### ISSUE TITLE
Asus TinkerBoard + Kodi Installation missing

### ISSUE THREAD

**Issue by Darknet** [MichaIng/DietPi#873]
HI

I tries to download the image for thinker board, but the installation for kodi is not available in diet-setup

Thanks in advance

**Comment by Fourdee** [comment]
@Darknet 

> NB: GPU features are disabled for this board (eg: Kodi, Desktop). Ideal for server usage.

We found the official GPU driver unstable and under-performing. Its been disabled until Asus/ASrock can provide an improved driver:
https://github.com/Fourdee/DietPi/issues/806#issuecomment-288717781

**Comment by Fourdee** [comment]
Not possible, Debian Stretch lacks Kodi support for Rockchip. Rockchip lacks Kodi available binaries for Debian Stretch.
We lack the time required to invest implementation.

Marking as closed.
