### ISSUE TITLE
DietPi Image | OrangePi Win

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#875]

**Comment by Fourdee** [comment]
Dev image, hold uboot/kernel packages:
```
apt-mark hold linux-dtb-dev-sun50iw2 linux-image-dev-sun50iw2 linux-jessie-root-dev-orangepiwin linux-u-boot-orangepiwin-dev 
```

---

- 🈴 CPU frequency / Gov's not supported by kernel. Running in hotplug mode.
- 🈴 No known thermal zones ```/sys/class/thermal/thermal_zone*```
- 🈴 Onboard WiFi modules loaded ```brcmfmac```, device does not exist (possibly linked to: https://github.com/igorpecovnik/lib/commit/a09111c40722c9d508a01ebe4f44f88af08e8530)
- 🈴 Onboard BT not functional ^^
- 🈴 No soundcards:
```
root@DietPi:~# aplay -l
aplay: device_list:268: no soundcards found...
root@DietPi:~# dmesg | grep sound
[    3.578066]   No soundcards found.
```

- 🈯️ Image http://dietpi.com/downloads/images/DietPi_OrangePiWin-arm64-(Jessie).7z
- doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=1840&p=7056#p7056

**Comment by Fourdee** [comment]
Other than headless eth server usage, not much use for this board currently, hopefully ARMbian guys can improve support on this board in the future. 
Completed.

**Comment by emouawad** [comment]
Does that mean Orange Pi Win plus should also run?
