### ISSUE TITLE
DietPi Image | OrangePi 2G IoT

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#877]

**Comment by jhonoryza** [comment]
waiting for this ..:)

**Comment by Fourdee** [comment]
As we are going to use ARMbian to build this image, we'll need to wait for ARMbian to support this device in their build tools.

I believe zador-blood-stained has started/done some work on this:
https://github.com/armbian/build/commit/6a737f00b8d8198d1aec6404fcff55c1ad8e1ae2

I'll keep nudging until its available for build.

**Comment by Fourdee** [comment]
Moved out of milestone as we lack Debian image availability.
