### ISSUE TITLE
Force reboot after Hostname change

### ISSUE THREAD

**Issue by JohnMacrae** [MichaIng/DietPi#880]
Its possible to change the hostname in -config and go straight on to install LAMP/LASP etc. Theresult can be this: make-ssl-cert: Could not get FQDN, using "AG".
make-ssl-cert: You may want to fix your /etc/hosts and/or DNS setup and run
make-ssl-cert: make-ssl-cert generate-default-snakeoil --force-overwrite
make-ssl-cert: again.

Which is undesireable for a beginner (or many of us who won't know how to fix it) :)

Solution as title? :)

**Comment by Fourdee** [comment]
@9H5G 

> Its possible to change the hostname in -config and go straight on to install LAMP/LASP etc. Theresult can be this: make-ssl-cert: Could not get FQDN, using "AG".

Thanks for the report and suggestion. The reboot prompt is disabled on 1st run install in ```dietpi-config```, so this could be an issue.
I'll add a reboot prompt straight after changing hostname. It will be optional yes/no choice, but i'll make it highly recommended.

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/24999319/f4b25d22-2034-11e7-9fe7-ceb4d9af0fa1.png)

**Comment by Fourdee** [comment]
Completed.
