### ISSUE TITLE
DietPi-Software | Atom editor

### ISSUE THREAD

**Issue by and09** [MichaIng/DietPi#881]
Please add atom editor (markdown and other)
http://raspberrypi.stackexchange.com/questions/55031/install-atom-editor-on-raspberry-pi

**Comment by Fourdee** [comment]
@and09 

Looks great 👍. I'll get it added when possible.
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

**Comment by and09** [comment]
atom is beter than nano or gedit

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
