### ISSUE TITLE
[dupe] ReadOnly Filesystem

### ISSUE THREAD

**Issue by tatoosh** [MichaIng/DietPi#883]
Add an option to set the filesystem readonly, so a power down will not currupt SD card on raspberry pi.
Source: https://hallard.me/raspberry-pi-read-only/ or German: https://kofler.info/raspbian-lite-fuer-den-read-only-betrieb/

**Comment by Fourdee** [comment]
@tatoosh 

Thanks for the request, we already have a ticket for this:
https://github.com/Fourdee/DietPi/issues/229

I'll mark this as [dupe] and closed.
