### ISSUE TITLE
DietPi-Config | Add support for VC1 MPEG2 RPi key entry

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#885]
> https://twitter.com/W00fer/status/853414918586028032
```
decode_MPG2=0x00000000
decode_WVC1=0x00000000
```

**Comment by Fourdee** [comment]
Notes:

RPi 3 v1:
```
decode_MPG2=0x46de3941
decode_WVC1=0xf402b3ea
```

Status:
```
vcgencmd codec_enabled MPG2
vcgencmd codec_enabled WVC1
```

**Comment by Fourdee** [comment]
Completed.

**Comment by Invictaz** [comment]
Thanks!

**Comment by oldpzman89old** [comment]
I realize this is closed and if you prefer me to go to dietpi forums I can but when I enter my mpg codec (I don't have a wvc1),  I still get "codec disabled" when running the "vcgencmd codec_enabled MPG2" command.  I triple checked with raspberrypi.com to make sure I have them the right serial and they said yes.  Any thoughts on what might be the issue?  The ramdisk DietPi/Config.txt definitely has the serial in it.

**Comment by Fourdee** [comment]
@pzman89 

Thanks for the report 👍 

I'll reopen this ticket and see if we can replicate.

**Comment by Invictaz** [comment]
For me the WVC1 seems disabled in Movian (self compiled) MPEG2 does work.

**Comment by oldpzman89old** [comment]
I was thinking of running a fresh copy of dietpi to see if it gets resolved but let me know if theres something you want me to check before trying.

**Comment by oldpzman89old** [comment]
@Fourdee still a no go after a fresh DietPi install.  It doesn't even save my key through the interface, I have to manually enter it in /Dietpi/config.txt.  Even then, it still reports disabled.

**Comment by Fourdee** [comment]
@pzman89 

> It doesn't even save my key through the interface, I have to manually enter it in /Dietpi/config.txt. Even then, it still reports disabled.

Thanks, i'll try to replicate.

If its still reporting disabled, might be an issue with current kernel (4.9). I'll check with 4.4.

**Comment by Fourdee** [comment]
- Ok, possible bug with adding the entries, not generating the required line in ```config.txt```. I'll get that fixed. 
- Updated RPi kernel/firmware through apt, currently 4.9, same issue with status disabled.

**Comment by oldpzman89old** [comment]
@Fourdee You might be right about the kernel.  I installed raspbian, which has kernel 4.4.50 and added the key via config editor in NOOBS and its reporting as enabled.

**Comment by Fourdee** [comment]
@pzman89 

> You might be right about the kernel. I installed raspbian, which has kernel 4.4.50 and added the key via config editor in NOOBS and its reporting as enabled.

You beat me to it 👍  just installed Jessie lite to run the same tests lol. I'll see if I can confirm.

**Comment by Fourdee** [comment]
Raspian lite:
- 🈯️ ```4.4.50-v7+```
- 🈯️ ```apt-get upgrade``` = ``` 4.9.24-v7+```
- 🈯️ Install DietPi Kernel

Strange.

---

```
root@raspberrypi:/home/pi# vcgencmd version
Mar  3 2017 13:42:34
Copyright (c) 2012 Broadcom
version 9ae30f71c7ef4239e9d5b56346c0842f3ef56736 (clean) (release)

root@raspberrypi:~# vcgencmd get_config str
decode_MPG2=0x46de3941
decode_WVC1=0xf402b3ea
device_tree=-

root@raspberrypi:~# cat /proc/cpuinfo | grep Serial
Serial          : 00000000088e535b

root@raspberrypi:~# vcgencmd codec_enabled MPG2
MPG2=enabled
```


```
root@DietPi:~# vcgencmd version
Mar  3 2017 13:43:37
Copyright (c) 2012 Broadcom
version 9ae30f71c7ef4239e9d5b56346c0842f3ef56736 (clean) (release)

root@DietPi:~# vcgencmd get_config str
decode_MPG2=0x46de3941
decode_WVC1=0xf402b3ea
device_tree=-

root@DietPi:~# cat /proc/cpuinfo | grep Serial
Serial          : 00000000088e535b

root@DietPi:~# vcgencmd codec_enabled MPG2
MPG2=disabled
```

---

- 🈴 Use of dietpi ```config.txt``` with entries
- 🈯️ Use of original Raspbian ```config.txt``` with entries
- diff: https://www.diffchecker.com/7hcq6c0i
- 🈴 Set GPU mem to 16MB 
- 🈯️ Set GPU mem to 32MB

**Comment by Fourdee** [comment]
I'll mark this as closed and finish up with new ticket:
https://github.com/Fourdee/DietPi/issues/996
