### ISSUE TITLE
Using btrfs filesystem

### ISSUE THREAD

**Issue by taner1** [MichaIng/DietPi#887]
Is it possible to use btrfs for system partition? I dont see any distro using it but it does have compression for getting more free space and implies wear level algorithm that extends lifespan of sd cards. Also for some benchmarks its faster than obsolote fat32 filesystem.

**Comment by Invictaz** [comment]
Is it better than the F2FS used in modern Androids now? Is it backwards compatible so other computers an see it?

**Comment by taner1** [comment]
I dont know if its better than f2fs because there is no comparison between two but f2fs has no transparent compression support and btrfs is more mature than it.Also im using btrfs on my laptop and its supported since linux kernel 2.6. While dietpi focus on lower footprint i think btrfs is more suitable on this purpose.

**Comment by WolfganP** [comment]
There's an interesting discussion in https://github.com/raspberrypi/linux/issues/1761 , it seems that implementing btrfs in raspbian and derivatives requires high maintenance for now.

**Comment by Fourdee** [comment]
Marking as closed, please reopen if required.

**Comment by taner1** [comment]
I managed to migrate my rootfs ext4 to btrfs with adding btrfs to initramfs. The btrfs module already in kernel so no need to recompile. With lzo compression there is slight delay at startup time but after booting seems everything is good. It decreased my occupied space 650MB to 420MB. Anyone who using 1-2GB sd  cards i strongly recommend to use btrfs for it . Now finally i can install ffmpeg to my rpi zero :)

**Comment by trajano** [comment]
@taner1 how does it fare when you have unexpected power failures?  Does it recover well?
