### ISSUE TITLE
DietPi-Software | Add MongoDB Server

### ISSUE THREAD

**Issue by phonicmouse** [MichaIng/DietPi#889]

**Comment by phonicmouse** [comment]
What about this? @Fourdee 
😄

**Comment by Fourdee** [comment]
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
```
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo -e "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" > /etc/apt/sources.list.d/mongodb-org-3.4.list
apt-get update
apt-get install -y mongodb-org
```
- 🈴 Lacks ARMv7 ARMv8 binaries
```
W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

```
- x86_32 x86_64 only

---

- 🈯️ Available in Raspbian repo:
```
apt-get install mongodb
```
- 🈴 But not debian

**Comment by phonicmouse** [comment]
Thank You!

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.

**Comment by abhinavgupta** [comment]
Hi, installing mongodb is still an issue in aarch64 machines for Dietpi. I am trying to install mongodb on Pine64 version of Dietpi and getting similar errors:

W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.4/Release  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by Fourdee** [comment]
@abhinavgupta 

The repo links you listed, only provide x86 packages. They lack ARM.
```
Origin: mongodb
Label: mongodb
Suite: jessie
Codename: jessie/mongodb-org
Architectures: amd64 i386
```

**Comment by abhinavgupta** [comment]
@Fourdee Thanks, their testing branch has a binary for arm64, any recommendations on how to tackle this problem further?

**Comment by bhaveshgohel** [comment]
:negative_squared_cross_mark: [ Update 1 - 5th July 2018 : Dietpi Debian Stretch]: The Binaries for [Debian Stretch](https://andyfelong.com/2017/08/mongodb-3-0-14-for-raspbian-stretch/) dosn't work with [DietPi_OdroidXU4-ARMv7-Stretch](https://dietpi.com/downloads/images/DietPi_OdroidXU4-ARMv7-Stretch.7z) .. :disappointed: 

:heavy_check_mark: [ Update 2 - 5th July 2018 : Dietpi Debian Jessie ]: But The Binaries for [Debian Jessie](https://andyfelong.com/2017/03/mongodb-3-0-14-binaries-for-raspberry-pi-3/) work with [DietPi_OdroidXU4-ARMv7-Jessie](https://dietpi.com/downloads/images/DietPi_OdroidXU4-ARMv7-Jessie.7z) .. :+1: 
 - Download Binaries from [here](https://andyfelong.com/2017/03/mongodb-3-0-14-binaries-for-raspberry-pi-3/)
 - Follow these [instruction](https://andyfelong.com/2016/01/mongodb-3-0-9-binaries-for-raspberry-pi-2-jessie/) to install on Odroid XU4.
Proof:
![screenshot from 2018-07-05 18-48-25](https://user-images.githubusercontent.com/5253753/42325507-1a1f4132-8084-11e8-99a5-1d7b094592fb.png)



---

Dear All,

I find https://andyfelong.com/2017/03/mongodb-3-0-14-binaries-for-raspberry-pi-3 MonogDB 3.0.14 binary to be working fine in bellow system:

Board: Odroid XU4
Architecture : armv7l GNU/Linux
DietPi: v6.6

Thanks Andy (@AndyOfLinux) for your work :+1:
