### ISSUE TITLE
DietPi-Software | Roundcube/Rainloop

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#897]
> https://roundcube.net/screens/
http://dietpi.com/phpbb/viewtopic.php?f=12&t=1828#p7022
https://github.com/roundcube/roundcubemail

**Comment by pabgan** [comment]
https://www.rainloop.net/ has also been proposed.

**Comment by Jlkam** [comment]
+1 RainLoop

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
