### ISSUE TITLE
DietPi-Software | In additional software, under network monitoring add "slurm"

### ISSUE THREAD

**Issue by phonicmouse** [MichaIng/DietPi#902]
Very powerful
![slurm08](https://cloud.githubusercontent.com/assets/12597068/25509753/9003a3bc-2bbb-11e7-94ba-6ec511523d94.jpg)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
