### ISSUE TITLE
DietPi-Software | In additional software, under network monitoring add "bmon"

### ISSUE THREAD

**Issue by phonicmouse** [MichaIng/DietPi#903]
[https://github.com/tgraf/bmon](https://github.com/tgraf/bmon)
![bmon_big_2](https://cloud.githubusercontent.com/assets/12597068/25514750/4dbb018e-2bdf-11e7-8bf7-b23e996362f4.png)

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
