### ISSUE TITLE
"su" isn't working

### ISSUE THREAD

**Issue by greencopper** [MichaIng/DietPi#906]
I have just downloaded and installed DietPi on an ODROID XU4 and everything works perfectly except for "su".

I log in to the box using OpenSSH. Afterwards I do "su" to become root. I get the password prompt, but even though the correct password is entered, it fails with an authentication error.

Logging in as root using SSH works.

Kind regards

**Comment by Fourdee** [comment]
@greencopper 

Thanks for the report 👍 

I've got a few XU4 jobs to complete over the next few days, i'll check this at the same time.

**Comment by Fourdee** [comment]
@greencopper 

>  Afterwards I do "su" to become root. I get the password prompt, but even though the correct password is entered, it fails with an authentication error.

Did you add your user to group ```sudo```?

If your running DietPi v149, try our test DietPi user, see if you get same issue
- username = dietpi
- password = dietpi

This is the permissions the above user has:
https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-set_software#L145-L180

**Comment by greencopper** [comment]
Adding the user to sudo should make no difference as "su" and "sudo" aren't the same.

In my case I remove sudo, if it's installed, I only want "su" to work.

"su" normally works out-of-the-box on Debian.

**Comment by Fourdee** [comment]
@greencopper 

```
sudo su
```

**Comment by Fourdee** [comment]
Marking as resolved using:
https://github.com/Fourdee/DietPi/issues/906#issuecomment-298673747
