### ISSUE TITLE
CPU Temperature error

### ISSUE THREAD

**Issue by hectorcamp** [MichaIng/DietPi#909]
OrangePi with the new update v149, shows the CPU temperature as 0 °
![screenshot_52](https://cloud.githubusercontent.com/assets/9473919/25561402/3bf6b1ec-2d41-11e7-97ee-ae4f14b33273.png)

![screenshot_53](https://cloud.githubusercontent.com/assets/9473919/25561413/6d9dcfb4-2d41-11e7-8bd5-f535dca50f4b.png)

**Comment by Fourdee** [comment]
@hectorcamp 

Thanks for the report 👍 

We'll get that fixed :)

**Comment by Fourdee** [comment]
OPi PC report: http://dietpi.com/phpbb/viewtopic.php?f=11&t=1847#p7076

**Comment by Fourdee** [comment]
Confirmed:
- OPi one
- NanoPi M1

Seems all H3's may use 2 digit temp readouts?

- NanoPi Neo (4.x) 5 digit
- NanoPi Neo (3.x) 2 digit

**Comment by Fourdee** [comment]
@hectorcamp 

Think we fixed it, any chance you can update script and test for us?
```
wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-cpuinfo -O /DietPi/dietpi/dietpi-cpuinfo
cpu
```

**Comment by hectorcamp** [comment]
It works, thank you!.
![screenshot_54](https://cloud.githubusercontent.com/assets/9473919/25566190/dada04e4-2daa-11e7-852b-a226be4ee3fd.png)

**Comment by jcjdominguez** [comment]
>Think we fixed it, any chance you can update script and test for us?

>wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-cpuinfo -O /DietPi/dietpi/dietpi-cpuinfo
cpu

Hi. I also have this issue on a opi zero, but that fix doesn't work for me.

**Comment by motaboy** [comment]
Same Problem on Orange Pi Zero with H2+ CPU.

Please fix if possible as cat temp shows the value properly.

**Comment by motaboy** [comment]
DietPi CPU Info
 Use dietpi-config to change CPU / performance options
 ─────────────────────────────────────────────────────
 Architecture |     armv7l
 Temp         |     0'c | Who put me in the freezer!
 Governor     |     ondemand
 Throttle up  |     85% CPU usage

                 Current Freq    Min Freq   Max Freq
 CPU0         |      240 MHz      240 MHz    1200 MHz
 CPU1         |      240 MHz      240 MHz    1200 MHz
 CPU2         |      240 MHz      240 MHz    1200 MHz
 CPU3         |      240 MHz      240 MHz    1200 MHz

**Comment by Fourdee** [comment]
@motaboy 

Thanks for the report 👍 

Does this fix work for you? https://github.com/Fourdee/DietPi/issues/909#issuecomment-298228895

**Comment by motaboy** [comment]
No, tried it twice but didn't fix it.

**Comment by Fourdee** [comment]
@motaboy 

Thanks.

I've updated script, please can you test it for us again?
https://github.com/Fourdee/DietPi/issues/909#issuecomment-298228895

**Comment by motaboy** [comment]
Nice! 👌
Working fine now

**Comment by Fourdee** [comment]
Thanks to everyone who reported and tested this for us.

I think we can say this is now resolved. Marking as completed. Please reopen if required,

**Comment by syl3n7** [comment]
I confirm the 
"wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-cpuinfo -O /DietPi/dietpi/dietpi-cpuinfo"
worked for me.
device:OPi PC

**Comment by jonasmorais** [comment]
I confirm the
"wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-cpuinfo -O /DietPi/dietpi/dietpi-cpuinfo"
worked for me.
device:OPi One
thanks
Jonas

**Comment by yo8aiv** [comment]
i confirm also this fix worked also for me.
 V149       | OrangePi Zero (armv7l)

**Comment by Ahaus314** [comment]
Fix on my NanoPi M3!
