### ISSUE TITLE
DietPi-Software | h5ai

### ISSUE THREAD

**Issue by pidiet** [MichaIng/DietPi#910]
> **h5ai**

> **modern HTTP web server index**

> license **MIT**
github **lrsjng/h5ai**

> h5ai is a modern file indexer for HTTP web servers with focus on your files. Directories are displayed in a appealing way and browsing them is enhanced by different views, a breadcrumb and a tree overview. Initially h5ai was an acronym for HTML5 Apache Index but now it supports other web servers too.

> Requires **PHP 5.5+** and works fine with **Apache httpd, lighttpd, nginx and Cherokee**. Best user experience with the latest versions of Chrome, Firefox, Opera, Vivaldi, Safari and Edge, but a static fallback is provided for older browsers or if JavaScript is disabled.
> Features
> 
> There are lots of optional extensions and configuration options to customize the web appearance of your directory listings. All markup is valid HTML5 spiced up with CSS3 and finest JavaScript to build a fresh but minimal user interface and a user experience that focuses on your files.
> 
> Some of the optional features are:
> sorting – view modes – localization – breadcrumb – tree view – custom headers+footers – filter+search – folder sizes – auto refresh – packaged download – QR codes – thumbnails – image+text+audio+video preview

**Source**: https://larsjung.de/h5ai/
**Demo**: https://larsjung.de/h5ai/demo/

_Tag_: Software Request

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
