### ISSUE TITLE
Apt-get has failed | 0bytes free space

### ISSUE THREAD

**Issue by Sod-Almighty** [MichaIng/DietPi#917]
Apt-get has failed:                                                │
                         │  - Apt string = mate-desktop-environment-extras upower policykit-1 │
                         │ iceweasel p7zip-full --no-install-recommends                       │
                         │  - Error code = 100                                                │
                         │  - Software Title = MATE: desktop enviroment                       │
                         │  - Apt log = /var/log/dietpi-software_apt.log                      │
                         │                                                                    │
                         │ Please report this issue to DietPi so it can be investigated.      │
                         │                                                                    │
                         │ DietPi-Software will now exit.

**Comment by Sod-Almighty** [comment]
> You don't have enough free space in /var/cache/apt/archives/

Should probably have a test for this.

**Comment by Fourdee** [comment]
@Sod-Almighty 

> Should probably have a test for this.

Yep, In the next update v150, a general check for free space on RootFS has been added:
You must have 500MB+ free space on RootFS, before ```dietpi-software``` and ```dietpi-update``` can be used.
https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932

In the mean time, you'll need to manually ensure sufficient free space is available on your system. Using commands such as:
```
df -h
cd /
treesize
```

**Comment by Fourdee** [comment]
I'll mark this as closed (due to fix in https://github.com/Fourdee/DietPi/issues/905#issuecomment-298343932). Please reopen if required.
