### ISSUE TITLE
DietPi-Config | WiFi hotspot: Toggle on/off

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#924]
> https://github.com/Fourdee/DietPi/issues/921#issue-226366307

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/25741347/40a0c4d6-3182-11e7-8ec4-df563299d8a0.png)

**Comment by Fourdee** [comment]
Completed.

**Comment by tatoosh** [comment]
Can i toggle this by commandline?
So i can script if my house SSID is not found, run the hotspot.

**Comment by Fourdee** [comment]
@tatoosh 

Yep, its done with:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-config#L3396-L3404
