### ISSUE TITLE
Request: External USB backup cannot be FAT32 / VFAT

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#927]
Bit strange that I have to have a EXT formatted USB drive to store backups, otherwise symbolic links are not supported. I want a stationary backup for example in a .zip or something. 

The only thing I can do know is format my drive and then store a backup. But I don't want symbolic links, only a store of my userdata in case Dietpi goes wrong.

**Comment by Fourdee** [comment]
> have to have a EXT formatted USB drive to store backups

As the system we backup uses symlinks, EXT4 + symlink filesystem are required for ```dietpi-backup```. If FAT was allowed, a restore would cripple your installation.

If you want to simply backup your userdata to another location, try ```dietpi-sync```: 
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&start=30#p256

> I want a stationary backup for example in a .zip or something.

https://github.com/Fourdee/DietPi/issues/816

**Comment by Invictaz** [comment]
Thanks. Will wait for #816
