### ISSUE TITLE
DietPi-Software | PhantomJS

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#929]
Compiling it on my PiZero will take days (as per instructions) or isnt possible due to low RAM and swapfile. So I hope a prebuild binary can be included.

Slightly new 2.1.1
https://github.com/fg2it/phantomjs-on-raspberry
https://mecrazy.net/2016/06/06/i-built-phantomjs-2-1-1-for-raspberry-pi/

https://www.bitpi.co/2015/02/11/compiling-phantomjs-on-raspberry-pi/

Older builds:
https://grizzlykoalabear.com/2015/building-phantomjs-on-the-raspberry-pi-2/
http://raspberrypimaker.com/how-to-compile-phantomjs-on-the-raspberry-pi-2/
https://github.com/piksel/phantomjs-raspberrypi
https://github.com/aeberhardo/phantomjs-linux-armv6l

**Comment by phonicmouse** [comment]
+1

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
