### ISSUE TITLE
Pizero W - wlan0 not found, eth0 not found

### ISSUE THREAD

**Issue by JohnMacrae** [MichaIng/DietPi#930]
I've discovered an issue with PiZero W.  Was working fine for a month or so and took updates.  However, I decided to flash a new card and configure it for headless start as usual by enabling and setting the wlan parameters in dietpi.txt.  However, in the startup log, with this freshly flashed card, I see that Dietpi brings up neither network interface since it cannot find them (the interface).

Using a freshly flashed Raspian works just fine! #frustrating :)

What would you like me to do to track this one down?

**Comment by Fourdee** [comment]
@9H5G 

>  I decided to flash a new card and configure it for headless start as usual by enabling and setting the wlan parameters in dietpi.txt. However, in the startup log, with this freshly flashed card, I see that Dietpi brings up neither network interface since it cannot find them (the interface).

Which image version of DietPi did you write to SD? v148 is latest.

**Comment by Fourdee** [comment]
@9H5G 

I just successfully completed a automated install (using WiFi creds set in dietpi.txt) on RPi Zero W, with v148 image:
http://dietpi.com/downloads/images/DietPi_RPi-armv6-(Jessie).7z

Any chance you could download the above image and test it again?

**Comment by JohnMacrae** [comment]
r work.  Dan,

It seems that 148 worked so no dramas.  I was still on 143 since I was
travelling.

Thanks for all your work - drop me a note if you're ever over in Essex and
I'll buy you a beer :)

Kind Regards
John

**Comment by Fourdee** [comment]
@9H5G 

Excellent. RPi Zero W support was added to v145 image and higher.

> Thanks for all your work - drop me a note if you're ever over in Essex and
I'll buy you a beer :)

Will do, thanks 👍
