### ISSUE TITLE
DietPi-Software | Home Assistant

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#935]
> https://github.com/home-assistant/home-assistant
https://twitter.com/SomniusX/status/861403236795904004

**Comment by sytone** [comment]
So just created HTPC as a app, I think I can do Home Assistant next as I run it at home.

**Comment by sytone** [comment]
Given it is in time to close this issue?

**Comment by Fourdee** [comment]
@sytone 

Yep, Many thanks for implementing this 👍 

For reference : https://github.com/Fourdee/DietPi/issues/1145
