### ISSUE TITLE
Raspberry Pi 4.9 Kernel

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#936]
4.4 is quite old.

4.9 Has official Pi Zero support and Orange Pi and XFS improvements etc etc
4.10 and further have a lot of 3D improvements for Pi's.

http://www.phoronix.com/scan.php?page=news_item&px=Linux-4.9-ARM-Pull
https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.12-Features-Week-1

**Comment by Fourdee** [comment]
@Invictaz 

We generally follow what RPi images/apt do in terms of kernel version. Last time I checked their apt install is 4.4 and ```rpi-update``` recently bumped upto 4.9.

I'll take a look at 4.9. If our kernel patches (eg: allo DAC's) are compatible, cant see why not upgrading it.

edit:
RPi doesn't have a 4.12 branch yet: https://github.com/raspberrypi/linux/branches

**Comment by Invictaz** [comment]
@Fourdee they do have 4.11

**Comment by Fourdee** [comment]
@Invictaz 

Yep, however, 4.9 is LTS: https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.9-LTS-Kernel

**Comment by Fourdee** [comment]
Notes:
4.9 kernel contains required Allo DAC's already. Only change we needed to make is +384KHz support in ALSA.
- 🈴 Possible changes/broken kernel cpu info (RPi 3 and RPi Zero): Breaks our ```HW_MODEL```
- Confirmed with ```rpi-update``` ``` 4.9.27-v7+```

RPi 3
```
root@DietPi:~# cat /proc/cpuinfo | grep Hardware
Hardware        : BCM2835
root@DietPi:~# uname -a
Linux DietPi 4.9.27-v7+ #2 SMP Thu May 11 18:50:36 UTC 2017 armv7l GNU/Linux
```

RPi Zero:
```
root@DietPi:~# cat /proc/cpuinfo | grep Hardware
Hardware        : BCM2835
root@DietPi:~# uname -a
Linux DietPi 4.9.27+ #1 Fri May 12 14:22:28 UTC 2017 armv6l GNU/Linux
```

detect RPi, then check for ARMv6/7 ?? RPi 3 shows ARMv7.....
```
cat /proc/cpuinfo | grep '^Hardware' | grep -ci -m1 '[[:space:]]BCM'
```

BCM2835 is correct for RPi1/zero
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/README.md

RPi 2: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2836/README.md
RPi 3: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2837/README.md

**Comment by Invictaz** [comment]
@fourdee So what to do if you want to run the 3D apps supported in 4.11 then? I don't get the point of long term support if updates are available and they don't break anything as most likely backwards compatible.

**Comment by Fourdee** [comment]
@Invictaz 

> So what to do if you want to run the 3D apps supported in 4.11 then?

You can always compile 4.11 and install it on your DietPi system for testing purposes.

**Comment by Fourdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7077026/26034709/87be6d36-38b8-11e7-928b-49ff53f3d4c0.png)

**Comment by Fourdee** [comment]
- OpenGL should now be functional, lets test
🈴 Blank screen, even during boot, no output on HDMI what so ever.
https://github.com/Fourdee/DietPi/issues/834

**Comment by Fourdee** [comment]
Completed. 4.9 kernel patched in v150 update.
