### ISSUE TITLE
BananaPi pro image running on BananaPi too

### ISSUE THREAD

**Issue by Elluminatus** [MichaIng/DietPi#938]
The BananaPi Pro image of DietPi is running on BananaPi Pro image fine. So maybe you can write this in your download section as information for other users.

Greetings Elluminatus

**Comment by Invictaz** [comment]
They are both Allwinner A20 so quite compatible :)

**Comment by Fourdee** [comment]
> The BananaPi Pro image of DietPi is running on BananaPi Pro image fine. So maybe you can write this in your download section as information for other users.

Thanks for info 👍 

I'll link this info to the BPi image request ticket for now: https://github.com/Fourdee/DietPi/issues/824

**Comment by Elluminatus** [comment]
Maybe you can add a picture from the BananaPi to the download section or a hint under the bananaPi pro picture?

**Comment by Fourdee** [comment]
@Elluminatus 

> Maybe you can add a picture from the BananaPi to the download section or a hint under the bananaPi pro picture?

Although same CPU, they have some differences with hardware and features. The kernel/modules and voltages can be unique for each image/board. Potential damage by using an incorrectly configured image for the board (if CPU/Dram voltages are different for each board).

As we prefer to make a "fully compatible" image for the specific board, and to avoid any possible "DietPi blew up my BPi", I'll leave the information on Git for now.

**Comment by Elluminatus** [comment]
@ Fourdee

Thank you for the hint, I will make diethers tests.
