### ISSUE TITLE
Support for BananaPi R1 Router Board/ Lamobo R1 and LEDE software request

### ISSUE THREAD

**Issue by Elluminatus** [MichaIng/DietPi#939]
Maybe you can add support for BananaPi R1 Router Board/ Lamobo R1 and the possibility to install LEDE over the dietPi software section.

Greetings Elluminatus

**Comment by vsxen** [comment]
If you use BPI R1  ，the  image for BananaPi Pro (Allwinner A20) is ok.  #938 

 Install LEDE over the dietPi software section？ I think it is hard to do it .  chroot?

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
