### ISSUE TITLE
DB drivers problem on Nextcloud install

### ISSUE THREAD

**Issue by enolp** [MichaIng/DietPi#940]
Installing Nextcloud on a Raspberry Pi 2 shows me an error when trying to setup the installation within the webapp. It says: 

```No database drivers (sqlite, mysql, or postgresql) installed.```

Right now I'm using lighttpd as a web server.

**Comment by Fourdee** [comment]
@enolp 

Looks like a possible issue with failed/broken mysql installation.

Can you please send us a bug report? I'd like to check system settings/packages:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=499#p2184

**Comment by enolp** [comment]
Bug report done and sent. Here is the reference code: 2d1f034b-8d3b-4009-9a78-3c5858f120e8-0 .

Thank you for your support.

**Comment by Fourdee** [comment]
- fail2ban
- llmp
- pihole
- nextcloud
- pivpn

> No database drivers (sqlite, mysql, or postgresql) installed.

MySQL and all php modules appeared installed correctly. Unknown cause at the moment.

#### Ok, lets try purging nextcloud and mysql, then reinstall nextcloud:

_If system is critical, back it up 1st:_
```
dietpi-backup
```

Then:
```
#You'll receive some errors regarding mysql not found on nextcloud removal, thats fine as DB is removed during mysql removal.
dietpi-software uninstall 86 114 

#Install Nextcloud
dietpi-software install 114
```

**Comment by enolp** [comment]
I did that reinstallation but it didn't work, however I uninstalled mysql and switched to mariadb, and Nextcloud seems to be working. The problem now is I don't know which username and password were set.

**Comment by Fourdee** [comment]
@enolp 

> The problem now is I don't know which username and password were set.

Please see online doc:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=3026#p3026

**Comment by Fourdee** [comment]
@enolp 

Is your nextcloud installation now functional/resolved?

**Comment by enolp** [comment]
Sorry for not replying but yes, all worked fine. I did a fresh install and used Lighttpd, MariaDB and PHP as my choice.

**Comment by Fourdee** [comment]
@enolp 

Thanks. I'll mark this as resolved. Please reopen if required.
