### ISSUE TITLE
[Out off topic] Does the DietPi forum work?

### ISSUE THREAD

**Issue by it-praktyk** [MichaIng/DietPi#942]
Hi

I tried register to the DietPi forum twice - at: May 2th and today - but I didn't receive registration acceptation.

I would like ask for advise about what is the better/easiest option to prepare the new one package - Ansible managed node prerequisites.

**Comment by Fourdee** [comment]
@it-praktyk 

> I tried register to the DietPi forum twice - at: May 2th and today - but I didn't receive registration acceptation.

Apologies for that. Must of been triggered as a possible spambot account.

Whats the username for the account you made today? I'll activate.

> I would like ask for advise about what is the better/easiest option to prepare the new one package - Ansible managed node prerequisites.

Sorry, not sure what you mean? Or is this request and you'd like to see "Ansible" in ```dietpi-software```?

---

EDIT:

- Found you ```it-praktyk```, account is now active on forum.
- Reason for spam bot trigger, email address url invalid = http://wojteks.net has no webpage

**Comment by it-praktyk** [comment]
>> I  would like ask for advise about what is the better/easiest option to prepare the new one package - Ansible managed node prerequisites.

> Sorry, not sure what you mean? Or is this request and you'd like to see "Ansible" in dietpi-software?

I can try add it myself - probably Python 2.7.x + some modules from pip will be needed + tests with dropbear - but I need some instruction when I should start .

Packages are define in
```
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software
```
?

Thx for remarks about reasons why my email was classified as spam.

**Comment by Fourdee** [comment]
@it-praktyk 

Python-pip + python 2.7 install is available in DietPi-Software:
```
dietpi-software install 130
```

Ansible is not, so install via apt for now: http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian

**Comment by Elluminatus** [comment]
Same issue here: still waiting for activation: Name: Elluminatus

**Comment by Fourdee** [comment]
@Elluminatus 

Your forum account is now active.

**Comment by Shmio** [comment]
Same issue.  Name: Shmio

Appreciate it.

**Comment by Fourdee** [comment]
@Shmio 

All pending forum accounts now enabled.

**Comment by Fourdee** [comment]
I'll mark this as closed.

I check (and enable) the forum accounts for activation every day/2 days, where possible.

As for possible spam accounts, avoid using names such as ```exmdkfwiemfua``` and email addresses such as ```gooooieea..xoeckx@lol.unknownwebsite-thatdoesntwork.z```
