### ISSUE TITLE
Raspberry Pi 2 DietPi 4.4.50-v7+ kernel headers missing

### ISSUE THREAD

**Issue by monarc99** [MichaIng/DietPi#943]
Hi,

Dietpi uses its own compiled kernel with 149. 
I always compile some modules (e.g. zfs for a backup drive) and i would need the kernel headers for this kernel. (e.g. Module.symvers )

The modules compile with the default linux-headers, but can't be loaded.

**Comment by MichaIng** [comment]
@monarc99 
Since v6.0 DietPi uses the default RPi kernel packages, thus I would consider this as outdated.

If you still run up to v159, you can easily switch to official Kernel:
```
apt-mark unhold libraspberrypi-bin libraspberrypi0 raspberrypi-bootloader raspberrypi-kernel raspberrypi-sys-mods raspi-copies-and-fills
apt full-upgrade
```

I close this, reopen on demand.
