### ISSUE TITLE
DietPi-Software | Zoneminder

### ISSUE THREAD

**Issue by Elluminatus** [MichaIng/DietPi#945]
Hi,

it would be nice to use zoneminder with odroid xu4.
Further Infos: 

http://zoneminder.blogspot.de/p/zoneminder-on-odroid-xu4.html?m=1

Greetings Elluminatus

**Comment by Fourdee** [comment]
General Cleanup:
Marking all software requests as closed. Once interest peaks, we'll reopen once work starts.
