### ISSUE TITLE
Broken Subsonic 6 installation

### ISSUE THREAD

**Issue by Magtula** [MichaIng/DietPi#946]
It's not possible to install Subsonic 6. I also tried it with a new installed dietpi-system.
I attached an error-screenshot and log-file.

[Log.txt](https://github.com/Fourdee/DietPi/files/991030/Log.txt)
![grafik](https://cloud.githubusercontent.com/assets/28607433/25917915/f0d2d60a-35c9-11e7-9d01-3a9bf2e66e85.png)

**Comment by Fourdee** [comment]
@Magtula 

Thanks for the report 👍 

I'll take a look, which board?

**Comment by Fourdee** [comment]
```lame``` conflicting, with our ffmpeg ```libmp3lame```:
```
dpkg: error processing archive /var/cache/apt/archives/lame_3.99.5+repack1-7+deb8u1_armhf.deb (--unpack):
 trying to overwrite '/usr/bin/lame', which is also in package libmp3lame 3.99-1
```

**Comment by Fourdee** [comment]
Fixed for v150.

@Magtula Manual fix for this now:
```
apt-get install -f
apt-get purge lame -y
sed -i '/AGI lame/d' /DietPi/dietpi/dietpi-software

#Install subsonic 6
dietpi-software install 34
```

**Comment by Magtula** [comment]
Thank you very much - Awesome support!

Just for the sake of completeness, the board is a Raspberry Pi 2.

**Comment by Fourdee** [comment]
@Magtula 
I'll mark this as resolved, please reopen if required.
