### ISSUE TITLE
Not able to launch Kodi 15 from LXDE

### ISSUE THREAD

**Issue by Invictaz** [MichaIng/DietPi#952]
System: Pi Zero
v149 running

- Clicking on the kodi.desktop icon opens an empty leafpad. 
- Kodi is not in the start menu. Kodi is installed AFTER LXDE was installed.
- When you type Startkodi over SSH it runs but considerable slower than dedicated OpenElec 8.0 microSD. 
Maybe this is because of the SD card speed.
- Exiting is not possible, exits to a black screen.

**Comment by Fourdee** [comment]
@Invictaz 

Thanks 👍 

I'll take a look.

**Comment by Fourdee** [comment]
- 🈯️ RPi 3 : Fine, Kodi 17.1
- 🈯️ RPi Zero: Fine, Kodi 17.1

Unable to replicate any of the following:
- Clicking on the kodi.desktop icon opens an empty leafpad.

Unable to replicate.

- Kodi is not in the start menu. Kodi is installed AFTER LXDE was installed.

Unable to replicate. Available "Sound and Video"

- When you type Startkodi over SSH it runs but considerable slower than dedicated OpenElec 8.0 microSD.

Running Kodi from console (not desktop) will improve performance.

- Exiting is not possible, exits to a black screen.

Unable to replicate.

**Comment by Fourdee** [comment]
@Invictaz 

- Have you made any custom changes to your system, outside of the DietPi programs?
- Can you list installed software on this system ```dietpi-software list | grep ' =2 '```
- Do you get the same issues, on a test fresh installation?
- Have you changed the kernel from DietPi default ? ```uname -a```

**Comment by Invictaz** [comment]
@Fourdee will reply with full log. Maybe uninstall and install Kodi to solve this?

**Comment by Invictaz** [comment]
![image](https://cloud.githubusercontent.com/assets/20338545/26036988/036b5b84-38ea-11e7-942d-b7ddd179f5bf.png)

**Comment by Invictaz** [comment]
Kernel

![image](https://cloud.githubusercontent.com/assets/20338545/26036992/142eec06-38ea-11e7-8465-89aa4dcc38ad.png)

**Comment by Invictaz** [comment]
@Fourdee 

Kodi 15.2 Git:02e7013 Compiled Dec 28 2015

Started with Startkodi & as window 2359 if you exit it with the shutdown button in Kodi following happens.

Segmentation fault

Error log attached 

[kodi_crashlog-20170514_213356.txt](https://github.com/Fourdee/DietPi/files/999672/kodi_crashlog-20170514_213356.txt)

**Comment by Invictaz** [comment]
Screenshot to see that it is not opening via LXDE. And not in Sound/Video menu

![plaatje2](https://cloud.githubusercontent.com/assets/20338545/26037145/c130480c-38ed-11e7-92c4-096bbce0c1d4.jpg)

**Comment by Invictaz** [comment]
@Fourdee 

The issue I have is presented here. Strange is that it already suggests to start Kodi via Startkodi. But maybe my script is too old. Either way, upgrading to Kodi 17 sounds okay BUT Kodi 17 eats up more resources. Kodi 15.2 is fine for me.

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=109088&p=750252#p750252

**Comment by Fourdee** [comment]
@Invictaz 

DietPi-Software install of Kodi is via Raspbian apt repo. Current version is 17.1, previously it was 16.1. Not sure where/how 15.2 was installed on your system.

Maybe you have added additional apt repos that are conflicting with the install?:
```
ls -lha /etc/apt/sources.list.d
cat /etc/apt/sources.list
```

LXDE looks broken. I'd try a uninstall/reinstall of LXDE and Kodi. Failing that, please try a fresh install without any manual changes to system.

**Comment by Invictaz** [comment]
@Fourdee All is installed via Dietpi-software. As said this SD card is already running since Dietpi 120 ish.

**Comment by Invictaz** [comment]
![image](https://cloud.githubusercontent.com/assets/20338545/26379951/0d7723ea-401c-11e7-9ea1-7623edc66e89.png)

**Comment by Invictaz** [comment]
Setting is already at KODI setting 128mb GPU / 384MB RAM 

@Fourdee some opt to go to 160 or even 256 MB GPU?

Can that be done on Pi Zero?

**Comment by Invictaz** [comment]
This problem is quite big and maybe not present in newer Kodi's. But I prefer to stay on 15. 

http://forum.kodi.tv/showthread.php?tid=268099
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=91111
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=131742
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139758
https://www.raspberrypi.org/forums/viewtopic.php?f=35&t=17473
http://forum.kodi.tv/showthread.php?tid=294884
https://www.reddit.com/r/raspberry_pi/comments/4i9b9p/kodi_black_screen_on_exit_raspbian_install/
https://gist.github.com/aperezm-vlex/75d7481afff0db8f5894

**Comment by Invictaz** [comment]
@Fourdee 

The problem is partially fixed by reinstalling LXDE. Black screen on exit is gone then.
Also the DietPi-Config / DietPi-Launcher and DietPi-Software shortcuts now work :+1: 

Both kodi-standalone and startkodi work.

Shortcut is fixed by following this tutorial 
https://www.raspberrypi.org/forums/viewtopic.php?t=99866

sudo nano /usr/share/applications/kodi.desktop
Add the stuff below and don't forget to reboot.
I might fix the start menu shortcut later but starting from the desktop will do fine.

Issue can be closed now.

```
[Desktop Entry]
Version=1.0
Name=Kodi Media Center
GenericName=Media Center
Comment=Manage and view your media
Exec=kodi-standalone <-- this line
Icon=kodi
Terminal=false
Type=Application
Categories=AudioVideo;Video;Player;TV;

Actions=Fullscreen;Standalone;

[Desktop Action Fullscreen]
Name=Open in fullscreen
Exec=kodi-standalone -fs <-- this line
OnlyShowIn=Unity;

[Desktop Action Standalone]
Name=Open in standalone mode
Exec=kodi --standalone
OnlyShowIn=Unity
```
