### ISSUE TITLE
General | Default to SystemD-Timesyncd?

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#954]
investigate, remove NTPD? which is outdated.

> https://github.com/Fourdee/DietPi/issues/951

Will increase resources used slightly (daemon), but with the benefit of using systemd's inbuilt timesync.

**Comment by albaldi** [comment]
because dietpi use
`ntpd -gq`
and because according to the man
```
-q
Exit the ntpd just after the first time the clock is set. This behavior mimics that 
of the ntpdate program, which is to be retired. The -g and -x options can be used 
with this option. Note: The kernel time discipline is disabled with this option.
```
one can simply use a cronjob with
> ntpdate -u

BTW on my raspy 1 model B (256MB ram)
```
ps -p 310 -o %cpu,%mem,vsize,rssize,cmd
%CPU %MEM    VSZ   RSS CMD
 0.0  0.8  12612  2020 /lib/systemd/systemd-timesyncd
```

**Comment by Fourdee** [comment]
synced.
```
timedatectl | grep -ci -m1 'NTP synchronized: yes'
```

- if we convert to systemd-timesyncd:
```
apt-get purge ntp -y
timedatectl set-ntp true
```

- convert run_ntpd to check_ntp
- patch new cron jobs


---

- 🈺 Slow to sync after reboot. Takes roughly 60 seconds from a fresh boot for ```timedatectl``` to confirm time synced.

**Comment by Fourdee** [comment]
systemd-timesyncd is far too slow to verify sync (60's <>). We'll stick with NTP for now (10's <>), but i'll increase wait time to 30's (from 20), for slow DHCP ack's and slow connections.
