### ISSUE TITLE
怎么开启SPI？

### ISSUE THREAD

**Issue by gaye746560359** [MichaIng/DietPi#965]
dietpi-config中只能开启I2C，并没有SPI选项。
查看/boot/config.txt配置项dtparam=spi=off每次开机默认是关闭的。
请问怎么开启SPI？

**Comment by nickfox-taterli** [comment]
配置文件在/DietPi目录下,开机每次自动复制,先看好英文呢文档,发中文谁理你呢?

**Comment by k-plan** [comment]
_gaye746560359_:
> Dietpi-config can only open I2C, and no SPI option.
> View /boot/config.txt configuration item dtparam = spi = off Each boot is turned off by default.
> How to open the SPI?

---------------------


_nickfox-taterli_:
> Configuration file in / DietPi directory, boot each time automatically copy, first look at the English document, send Chinese who care about you?


-------------------

Can we close this?
