### ISSUE TITLE
DietPi-Software | Sonarr and Radarr

### ISSUE THREAD

**Issue by Gravesy83** [MichaIng/DietPi#966]
In reference to the request at #339 , and in light of support and development on Couchpotato apparently going quiet recently (as i mentioned here; http://dietpi.com/phpbb/viewtopic.php?f=11&t=1882 ), i'd like to ask if there's any option to have Sonarr and Radarr added.
They have native support for a lot of Linux based systems (including the Raspberry Pi's), so they should, in theory, make a good addition to the list.

**Comment by FireHelmet** [comment]
@Gravesy83 @Fourdee 

Installed and working well on odroid c2. Dan, I will send you an email about install procedure after few days of testing...

Thanks.

**Comment by Fourdee** [comment]
@FireHelmet 

> Dan, I will send you an email about install procedure after few days of testing...

Legend 👍

**Comment by FireHelmet** [comment]
@Gravesy83, scripts sent to @Fourdee

**Comment by Gravesy83** [comment]
Now this is a pleasant surprise after a boring vacation :-)
Many thanks for doing this.

**Comment by Fourdee** [comment]
#### Sonarr Notes:
![image](https://user-images.githubusercontent.com/7077026/26876231-21407afe-4b7d-11e7-931c-0147cecae91a.png)

```
Jun 07 12:48:21 DietPi mono[8134]: [Info] RssSyncService: Starting RSS Sync
Jun 07 12:48:21 DietPi mono[8134]: [Warn] FetchAndParseRssService: No available indexers. check your configuration.
```

- 🈯️ User required to add indexers in web interface > settings > indexers
- 🈯️ Online Doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=7455#p7455

**Comment by Fourdee** [comment]
#### Radarr Notes:
- 🈯️ Online Doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=7457#p7457

**Comment by FireHelmet** [comment]
@Fourdee , yes Health messages are normal. You need to add Download client and indexer in sonarr config.

For download client, you can use Nzbd client or p2p client like torrent. And for indexer you can use the built-in indexer or prefer Jackett.

**Comment by Fourdee** [comment]
@FireHelmet 

Great work on the install scripts, many thanks for doing them, worked a charm 👍 :clinking_glasses: 

Both tested, completed.
