### ISSUE TITLE
DietPi-Config | LED Control options

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#968]
eg: list all available (heartbeat/none etc) and apply.

**Comment by Invictaz** [comment]
Would be great that a pattern is able to be configurable if full startup is achieved so I can run it headless without a screen. For example 3 blips.

**Comment by Fourdee** [comment]
Automatically applied during boot aswell:
![image](https://cloud.githubusercontent.com/assets/7077026/26256069/a2511e7e-3cb3-11e7-9d6b-77abe56b0864.png)

![image](https://cloud.githubusercontent.com/assets/7077026/26256007/72055fbe-3cb3-11e7-97c6-56eefbf1ce5f.png)

**Comment by Fourdee** [comment]
@Invictaz 

> Would be great that a pattern is able to be configurable if full startup is achieved so I can run it headless without a screen. For example 3 blips.

The ```heartbeat``` option would benefit you for this. Basically flashes to a heartbeat once kernel is loaded (assumes booted)
https://www.youtube.com/watch?v=Cpm5Tb6aiJQ

**Comment by Fourdee** [comment]
Worth noting that not all available trigger modes function as expected. This is dependent on device as we set trigger directly to ```/sys/class/leds/XXXX/trigger```

In general, the following work on most boards:
- heartbeat
- none (off)

**Comment by Fourdee** [comment]
Completed.

**Comment by Fourdee** [comment]
The order + amount of ```/sys/class/leds``` entries change when devices are attached (eg: keyboard). So we need to match names in the save file to prevent incorrect LED triggers being applied.

**Comment by Fourdee** [comment]
Done.
