### ISSUE TITLE
DietPi-Software | PlexPy

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#971]
> https://github.com/JonnyWong16/plexpy

**Comment by FireHelmet** [comment]
@Fourdee 

Can you assign to me this job ?

Thanks

**Comment by Fourdee** [comment]
Odroid C2

Doesn't seem able to function with PMS server
```
There was an error communicating with your Plex Server.
```

Yet connections are confirmed:
![image](https://user-images.githubusercontent.com/7077026/26930376-1e0729cc-4c55-11e7-832f-c2c0dd521d35.png)

Logs filled with errors, and PlexPy thinks its outdated/unknown. Might be using Git to check versions (not installed):
![image](https://user-images.githubusercontent.com/7077026/26930398-303a7482-4c55-11e7-8f0a-2fb88a45ff70.png)

---

- 🈴 Tried enabling SSL
- 🈯️ RPi 3

Seems an issue with running PMS under ARM64 using ARMhf packages. I'll disable ARM64 install for now.

---

We'll install via Git to obtain github update functionality.

**Comment by Fourdee** [comment]
- 🈯️ Online Doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=7463#p7463

**Comment by FireHelmet** [comment]
@Fourdee , what is the port used in the settings of plexpy ? And yes, plexpy need git to check version...sorry.

I will try the latest version of plexpy in my DietPi. I keep you informed.

Thanks

**Comment by Fourdee** [comment]
> what is the port used in the settings of plexpy ?

@FireHelmet 

For web interface + settings? its :8181

**Comment by Fourdee** [comment]
🈯️ Tested on RPi, completed.

@FireHelmet 

Great work on the install script, many thanks 👍
