### ISSUE TITLE
DietPi-Software | Upgrade NextCloud 12

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#974]
> https://github.com/nextcloud/server/releases/tag/v12.0.0

**Comment by Fourdee** [comment]
- 🈯️ Test install fine, other than version link update, no code changes needed.

**Comment by molnarti** [comment]
does the uninstall/reinstall procedure maintain the nextcloud settings? like user, data location, quota, apps, etc. or a complete setup from scratch is needed?

**Comment by Fourdee** [comment]
> does the uninstall/reinstall procedure maintain the nextcloud settings? like user, data location, quota, apps, etc.

Nope. SQL DB + ```/var/www/nextcloud``` is dropped during uninstall.

>  or a complete setup from scratch is needed?

Unless NextCloud UI has a feature to update, a fresh reinstall is required.

**Comment by molnarti** [comment]
> Unless NextCloud UI has a feature to update, a fresh reinstall is  required. 

actually has and i used it in the past for minor updated (11.0.2 > 11.0.3), but for 12 it does not offer the upgrade

**Comment by molnarti** [comment]
tried updating via the uninstall reinstall path. this is what I am getting:

`[Info] Creating MySql DB for nextcloud`
` [Ok] Create database nextcloud | Completed`
`Nextcloud is not installed - only a limited number of commands are available`

then system gets stuck without any response
