### ISSUE TITLE
RPi - USB drive removal and reinsert doesn't mount device properly

### ISSUE THREAD

**Issue by danriches** [MichaIng/DietPi#975]
I've tried numerous fstab entries and with and without samba installed to no avail. The configuration works fine with Raspbian Jessie though, albeit Raspbian is a nightmare to get to boot in readonly mode hence why I'm trying out DietPi. I've attached the output from journal regarding the USB flash drive mount problem, this is without writing to the drive only reading at the moment. Any suggestions would be very much welcome, Thanks, Dan...

Of particular note is the mismatch of device identifiers (sdb and sda) in the following lines near the end of the log:
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] Attached SCSI removable disk
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30600) failed

JOURNAL OUTPUT
root@DietPi:~# apt-get remove usbmount
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  lockfile-progs pmount
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  usbmount
0 upgraded, 0 newly installed, 1 to remove and 4 not upgraded.
After this operation, 119 kB disk space will be freed.
Do you want to continue? [Y/n] y
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "0.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 31168 files and directories currently installed.)
Removing usbmount (0.0.22) ...
root@DietPi:~# reboot
login as: root
root@192.168.8.184's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
 ───────────────────────────────────────
 DietPi     | 16:09 | Fri 21/04/17
 ───────────────────────────────────────
 V150       | RPi 3 Model B (armv7l)
 ───────────────────────────────────────
 IP Address | 192.168.8.184
 ───────────────────────────────────────

 Created by : Daniel Knight
 Web        : http://DietPi.com
 Twitter    : http://twitter.com/dietpi_
 Donate     : http://goo.gl/pzISt9
 DietPi's web hosting is powered by: MyVirtualServer.com

 dietpi-launcher  = All the DietPi programs in one place.
 dietpi-config    = Feature rich configuration tool for your device.
 dietpi-software  = Select optimized software for installation.
 htop             = Resource monitor.
 cpu              = Shows CPU information and stats.

root@DietPi:~# ls /mnt/DISK
HDClinicalPacePort  System Volume Information
root@DietPi:~# ls /mnt/DISK
root@DietPi:~# ls /mnt/DISK
root@DietPi:~# ls /dev
autofs           gpiochip1     loop7               ram1    raw      tty13  tty28  tty42  tty57      vc-cma  vcsa5
block            gpiochip2     mapper              ram10   sdb      tty14  tty29  tty43  tty58      vc-mem  vcsa6
bsg              gpiomem       mem                 ram11   sdb1     tty15  tty3   tty44  tty59      vchiq   vhci
btrfs-control    hwrng         memory_bandwidth    ram12   serial1  tty16  tty30  tty45  tty6       vcio    watchdog
bus              initctl       mmcblk0             ram13   sg0      tty17  tty31  tty46  tty60      vcs     watchdog0
cachefiles       input         mmcblk0p1           ram14   shm      tty18  tty32  tty47  tty61      vcs1    zero
char             kmsg          mmcblk0p2           ram15   snd      tty19  tty33  tty48  tty62      vcs2
console          log           mqueue              ram2    stderr   tty2   tty34  tty49  tty63      vcs3
cpu_dma_latency  loop-control  net                 ram3    stdin    tty20  tty35  tty5   tty7       vcs4
cuse             loop0         network_latency     ram4    stdout   tty21  tty36  tty50  tty8       vcs5
disk             loop1         network_throughput  ram5    tty      tty22  tty37  tty51  tty9       vcs6
fb0              loop2         null                ram6    tty0     tty23  tty38  tty52  ttyAMA0    vcsa
fd               loop3         ppp                 ram7    tty1     tty24  tty39  tty53  ttyprintk  vcsa1
full             loop4         ptmx                ram8    tty10    tty25  tty4   tty54  uhid       vcsa2
fuse             loop5         pts                 ram9    tty11    tty26  tty40  tty55  uinput     vcsa3
gpiochip0        loop6         ram0                random  tty12    tty27  tty41  tty56  urandom    vcsa4
root@DietPi:~# journalctl -x -f
-- Logs begin at Fri 2017-04-21 16:09:18 UTC. --
Apr 21 16:10:47 DietPi systemd[1]: Starting Login Prompts.
-- Subject: Unit getty.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit getty.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Login Prompts.
-- Subject: Unit getty.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit getty.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Multi-User System.
-- Subject: Unit multi-user.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit multi-user.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Multi-User System.
-- Subject: Unit multi-user.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit multi-user.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Graphical Interface.
-- Subject: Unit graphical.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit graphical.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Graphical Interface.
-- Subject: Unit graphical.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit graphical.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Update UTMP about System Runlevel Changes...
-- Subject: Unit systemd-update-utmp-runlevel.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-update-utmp-runlevel.service has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Started Update UTMP about System Runlevel Changes.
-- Subject: Unit systemd-update-utmp-runlevel.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-update-utmp-runlevel.service has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Startup finished in 1.516s (kernel) + 1min 30.667s (userspace) = 1min 32.183s.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- All system services necessary queued for starting at boot have been
-- successfully started. Note that this does not mean that the machine is
-- now idle as services might still be busy with completing start-up.
--
-- Kernel start-up required 1516636 microseconds.
--
-- Initial RAM disk start-up required INITRD_USEC microseconds.
--
-- Userspace start-up required 90667135 microseconds.

^[[B^[[B
^Z
[1]+  Stopped                 journalctl -x -f
root@DietPi:~# journalctl -x -f
-- Logs begin at Fri 2017-04-21 16:09:18 UTC. --
Apr 21 16:10:47 DietPi systemd[1]: Starting Login Prompts.
-- Subject: Unit getty.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit getty.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Login Prompts.
-- Subject: Unit getty.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit getty.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Multi-User System.
-- Subject: Unit multi-user.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit multi-user.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Multi-User System.
-- Subject: Unit multi-user.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit multi-user.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Graphical Interface.
-- Subject: Unit graphical.target has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit graphical.target has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Reached target Graphical Interface.
-- Subject: Unit graphical.target has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit graphical.target has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Starting Update UTMP about System Runlevel Changes...
-- Subject: Unit systemd-update-utmp-runlevel.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-update-utmp-runlevel.service has begun starting up.
Apr 21 16:10:47 DietPi systemd[1]: Started Update UTMP about System Runlevel Changes.
-- Subject: Unit systemd-update-utmp-runlevel.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-update-utmp-runlevel.service has finished starting up.
--
-- The start-up result is done.
Apr 21 16:10:47 DietPi systemd[1]: Startup finished in 1.516s (kernel) + 1min 30.667s (userspace) = 1min 32.183s.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- All system services necessary queued for starting at boot have been
-- successfully started. Note that this does not mean that the machine is
-- now idle as services might still be busy with completing start-up.
--
-- Kernel start-up required 1516636 microseconds.
--
-- Initial RAM disk start-up required INITRD_USEC microseconds.
--
-- Userspace start-up required 90667135 microseconds.
Apr 21 16:12:11 DietPi kernel: usb 1-1.4: USB disconnect, device number 5
Apr 21 16:12:11 DietPi systemd[1]: Unmounting /mnt/DISK...
-- Subject: Unit mnt-DISK.mount has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has begun shutting down.
Apr 21 16:12:12 DietPi kernel: FAT-fs (sda1): unable to read boot sector to mark fs as dirty
Apr 21 16:12:12 DietPi systemd[1]: Unmounted /mnt/DISK.
-- Subject: Unit mnt-DISK.mount has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has finished shutting down.
Apr 21 16:12:12 DietPi systemd[1]: Unit mnt-DISK.mount entered failed state.
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: new high-speed USB device number 6 using dwc_otg
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: New USB device found, idVendor=058f, idProduct=6387
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: Product: Mass Storage
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: Manufacturer: Generic
Apr 21 16:12:25 DietPi kernel: usb 1-1.4: SerialNumber: 5D6A46EF
Apr 21 16:12:25 DietPi kernel: usb-storage 1-1.4:1.0: USB Mass Storage device detected
Apr 21 16:12:25 DietPi kernel: scsi host0: usb-storage 1-1.4:1.0
Apr 21 16:12:26 DietPi kernel: scsi 0:0:0:0: Direct-Access     Generic  Flash Disk       8.07 PQ: 0 ANSI: 4
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: Attached scsi generic sg0 type 0
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: [sda] 31334400 512-byte logical blocks: (16.0 GB/14.9 GiB)
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: [sda] Write Protect is off
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: [sda] Mode Sense: 23 00 00 00
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Apr 21 16:12:26 DietPi kernel:  sda: sda1
Apr 21 16:12:26 DietPi kernel: sd 0:0:0:0: [sda] Attached SCSI removable disk
Apr 21 16:12:27 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit dev-disk-by\x2did-usb\x2dGeneric_Flash_Disk_5D6A46EF\x2d0:0\x2dpart1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dev-disk-by\x2did-usb\x2dGeneric_Flash_Disk_5D6A46EF\x2d0:0\x2dpart1.device has finished starting up.
--
-- The start-up result is done.
Apr 21 16:12:27 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit dev-sda1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dev-sda1.device has finished starting up.
--
-- The start-up result is done.
Apr 21 16:12:27 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.0-host0-target0:0:0-0:0:0:0-block-sda-           sda1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.0-host0-target0:0:0-0:0:0:0-block-sda-sda1.devi           ce has finished starting up.
--
-- The start-up result is done.
Apr 21 16:12:27 DietPi systemd[1]: Starting File System Check on /dev/disk/by-label/DISK...
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun starting up.
Apr 21 16:12:28 DietPi systemd-fsck[2100]: fsck.fat 3.0.27 (2014-11-12)
Apr 21 16:12:28 DietPi systemd-fsck[2100]: 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt           .
Apr 21 16:12:28 DietPi systemd-fsck[2100]: Automatically removing dirty bit.
Apr 21 16:12:28 DietPi systemd-fsck[2100]: Performing changes.
Apr 21 16:12:28 DietPi systemd-fsck[2100]: /dev/sda1: 5 files, 5/1955907 clusters
Apr 21 16:12:28 DietPi systemd[1]: Started File System Check on /dev/disk/by-label/DISK.
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished starting up.
--
-- The start-up result is done.
Apr 21 16:12:28 DietPi systemd[1]: Mounting /mnt/DISK...
-- Subject: Unit mnt-DISK.mount has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has begun starting up.
Apr 21 16:12:28 DietPi systemd[1]: Mounted /mnt/DISK.
-- Subject: Unit mnt-DISK.mount has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:16 DietPi smbd[2109]: pam_unix(samba:session): session closed for user nobody
Apr 21 16:13:23 DietPi kernel: usb 1-1.4: USB disconnect, device number 6
Apr 21 16:13:23 DietPi systemd[1]: Unmounting /mnt/DISK...
-- Subject: Unit mnt-DISK.mount has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has begun shutting down.
Apr 21 16:13:23 DietPi kernel: FAT-fs (sda1): unable to read boot sector to mark fs as dirty
Apr 21 16:13:23 DietPi systemd[1]: Unmounted /mnt/DISK.
-- Subject: Unit mnt-DISK.mount has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has finished shutting down.
Apr 21 16:13:23 DietPi systemd[1]: Stopping File System Check on /dev/disk/by-label/DISK...
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun shutting down.
Apr 21 16:13:23 DietPi systemd[1]: Stopped File System Check on /dev/disk/by-label/DISK.
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished shutting down.
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: new high-speed USB device number 7 using dwc_otg
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: New USB device found, idVendor=058f, idProduct=6387
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: Product: Mass Storage
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: Manufacturer: Generic
Apr 21 16:13:30 DietPi kernel: usb 1-1.4: SerialNumber: 5D6A46EF
Apr 21 16:13:30 DietPi kernel: usb-storage 1-1.4:1.0: USB Mass Storage device detected
Apr 21 16:13:30 DietPi kernel: scsi host0: usb-storage 1-1.4:1.0
Apr 21 16:13:31 DietPi kernel: scsi 0:0:0:0: Direct-Access     Generic  Flash Disk       8.07 PQ: 0 ANSI: 4
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: Attached scsi generic sg0 type 0
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: [sda] 31334400 512-byte logical blocks: (16.0 GB/14.9 GiB)
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: [sda] Write Protect is off
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: [sda] Mode Sense: 23 00 00 00
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Apr 21 16:13:31 DietPi kernel:  sda: sda1
Apr 21 16:13:31 DietPi kernel: sd 0:0:0:0: [sda] Attached SCSI removable disk
Apr 21 16:13:31 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit dev-disk-by\x2did-usb\x2dGeneric_Flash_Disk_5D6A46EF\x2d0:0\x2dpart1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dev-disk-by\x2did-usb\x2dGeneric_Flash_Disk_5D6A46EF\x2d0:0\x2dpart1.device has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:31 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit dev-sda1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dev-sda1.device has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:31 DietPi systemd[1]: Found device Flash_Disk DISK.
-- Subject: Unit sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.0-host0-target0:0:0-0:0:0:0-block-sda-           sda1.device has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sys-devices-platform-soc-3f980000.usb-usb1-1\x2d1-1\x2d1.4-1\x2d1.4:1.0-host0-target0:0:0-0:0:0:0-block-sda-sda1.devi           ce has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:31 DietPi systemd[1]: Starting File System Check on /dev/disk/by-label/DISK...
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun starting up.
Apr 21 16:13:33 DietPi systemd-fsck[2144]: fsck.fat 3.0.27 (2014-11-12)
Apr 21 16:13:33 DietPi systemd-fsck[2144]: 0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt           .
Apr 21 16:13:33 DietPi systemd-fsck[2144]: Automatically removing dirty bit.
Apr 21 16:13:33 DietPi systemd-fsck[2144]: Performing changes.
Apr 21 16:13:33 DietPi systemd-fsck[2144]: /dev/sda1: 5 files, 5/1955907 clusters
Apr 21 16:13:33 DietPi systemd[1]: Started File System Check on /dev/disk/by-label/DISK.
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:33 DietPi systemd[1]: Mounting /mnt/DISK...
-- Subject: Unit mnt-DISK.mount has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has begun starting up.
Apr 21 16:13:33 DietPi systemd[1]: Mounted /mnt/DISK.
-- Subject: Unit mnt-DISK.mount has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has finished starting up.
--
-- The start-up result is done.
Apr 21 16:13:58 DietPi smbd[2151]: pam_unix(samba:session): session closed for user nobody
Apr 21 16:13:59 DietPi dhclient[1041]: DHCPREQUEST on eth0 to 192.168.8.3 port 67
Apr 21 16:13:59 DietPi dhclient[1041]: DHCPACK from 192.168.8.3
Apr 21 16:13:59 DietPi systemd[1]: Reloading LSB: start Samba SMB/CIFS daemon (smbd).
-- Subject: Unit smbd.service has begun with reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit smbd.service has begun with reloading its configuration
Apr 21 16:13:59 DietPi smbd[2179]: Reloading /etc/samba/smb.conf: smbd.
Apr 21 16:13:59 DietPi systemd[1]: Reloaded LSB: start Samba SMB/CIFS daemon (smbd).
-- Subject: Unit smbd.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit smbd.service has finished reloading its configuration
--
-- The result is done.
Apr 21 16:13:59 DietPi dhclient[1041]: bound to 192.168.8.184 -- renewal in 11316 seconds.
Apr 21 16:14:18 DietPi kernel: usb 1-1.4: USB disconnect, device number 7
Apr 21 16:14:18 DietPi systemd[1]: Unmounting /mnt/DISK...
-- Subject: Unit mnt-DISK.mount has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has begun shutting down.
Apr 21 16:14:18 DietPi umount[2196]: umount: /mnt/DISK: target is busy
Apr 21 16:14:18 DietPi umount[2196]: (In some cases useful info about processes that
Apr 21 16:14:18 DietPi umount[2196]: use the device is found by lsof(8) or fuser(1).)
Apr 21 16:14:18 DietPi systemd[1]: mnt-DISK.mount mount process exited, code=exited status=32
Apr 21 16:14:18 DietPi systemd[1]: Failed unmounting /mnt/DISK.
-- Subject: Unit mnt-DISK.mount has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit mnt-DISK.mount has finished shutting down.
Apr 21 16:14:18 DietPi systemd[1]: Stopping File System Check on /dev/disk/by-label/DISK...
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has begun shutting down.
Apr 21 16:14:18 DietPi systemd[1]: Stopped File System Check on /dev/disk/by-label/DISK.
-- Subject: Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-fsck@dev-disk-by\x2dlabel-DISK.service has finished shutting down.
Apr 21 16:14:20 DietPi smbd[2191]: pam_unix(samba:session): session closed for user nobody
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: new high-speed USB device number 8 using dwc_otg
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: New USB device found, idVendor=058f, idProduct=6387
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: Product: Mass Storage
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: Manufacturer: Generic
Apr 21 16:14:26 DietPi kernel: usb 1-1.2: SerialNumber: 5D6A46EF
Apr 21 16:14:26 DietPi kernel: usb-storage 1-1.2:1.0: USB Mass Storage device detected
Apr 21 16:14:26 DietPi kernel: scsi host1: usb-storage 1-1.2:1.0
Apr 21 16:14:27 DietPi kernel: scsi 1:0:0:0: Direct-Access     Generic  Flash Disk       8.07 PQ: 0 ANSI: 4
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: Attached scsi generic sg0 type 0
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] 31334400 512-byte logical blocks: (16.0 GB/14.9 GiB)
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] Write Protect is off
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] Mode Sense: 23 00 00 00
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Apr 21 16:14:27 DietPi kernel:  sdb: sdb1
Apr 21 16:14:27 DietPi kernel: sd 1:0:0:0: [sdb] Attached SCSI removable disk
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30600) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30601) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30602) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30603) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30604) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30605) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30606) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30607) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30608) failed
Apr 21 16:14:44 DietPi kernel: FAT-fs (sda1): Directory bread(block 30609) failed
Apr 21 16:14:58 DietPi smbd[2227]: pam_unix(samba:session): session closed for user nobody
Apr 21 16:15:01 DietPi kernel: fat__get_entry: 6 callbacks suppressed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30600) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30601) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30602) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30603) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30604) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30605) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30606) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30607) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30608) failed
Apr 21 16:15:01 DietPi kernel: FAT-fs (sda1): Directory bread(block 30609) failed
Apr 21 16:15:14 DietPi smbd[2232]: pam_unix(samba:session): session closed for user nobody

**Comment by Fourdee** [comment]
@danriches 

Hi,

We have tool (```dietpi-drive_manager```) which will allow you easily add USB drives, also applies auto mount (```x-systemd.automount```) to the fstab entry, removing the need for ```usbmount```:
http://dietpi.com/phpbb/viewtopic.php?f=8&t=673#p2898

Try clearing your ```/etc/fstab``` changes, then run ```dietpi-drive_manager``` to setup the drive.

> Directory bread(block 30605) failed

Possible issue with filesystem. Try repairing the drive with:
```
dosfsck -w -r -l -a -v -t /dev/sda1
```

**Comment by danriches** [comment]
There is a problem with using the drive manager as I can't mount by name only by uuid, I need this to be a name such as DISK and shared out on samba. Otherwise all my products will need the usb devices serial number set on format and not just a nice quick and easy rename. As I've said, this works like a charm on Raspbian Jessie and the only extra thing I need is to make the rootfs readonly which has given me nothing but trouble on Jessie.

The filesystem check ran up errors even though this is a brand new flash drive formatted as FAT32 as that's what an external piece of equipment needs, I cannot use NTFS or ext4 etc. If I format this on a Windows box and use in Jessie it works absolutely fine, no errors and the automount by name works.

It would seem to me that an essential package or configuration is missing for this all to work and the fact that you can't seem to mount by name in drive manager is a real issue for me. Personally, I'm going to look at other distros to see what they offer before probably biting the bullet and going back to Jessie and the awful mess of getting a readonly rootfs working.

Thanks for the response and if there's a resolution to my issue then please let me know, I'd much rather use DietPi for it's boot time and ease of use. You've done a cracking job :)

Dan

**Comment by Fourdee** [comment]
Outdated.
