### ISSUE TITLE
Documentation | Write to SD card using macOS

### ISSUE THREAD

**Issue by msdos** [MichaIng/DietPi#976]
In these instructions, there's no suggestion for macOS

http://dietpi.com/phpbb/viewtopic.php?f=8&t=9#p9

There's a small application with a GUI interface that can do it:

https://www.tweaking4all.com/software/macosx-software/macosx-apple-pi-baker/

![screen shot 2017-05-25 at 00 20 00](https://cloud.githubusercontent.com/assets/489034/26434615/0550b0e0-40e0-11e7-85bb-11d93e7955ff.png)

I've only tested in RPi, but they say it can work in other devices as well. It's really simple: I just select my SD Card, the IMG file and click "Restore Backup": done!

**Comment by sootstone** [comment]
Nice idea :+1: 

While on this subject, I see quite a few distros recommending [Etcher](https://etcher.io/) now (even Raspbian), which could be a nice way to standardize the installation across Windows, Linux and OSX.

**Comment by msdos** [comment]
This seems really nice @sootstone, actually I think yours is a better idea 😆

**Comment by Fourdee** [comment]
@msdos 

> This seems really nice @sootstone, actually I think yours is a better idea 

Agree 👍 

@sootstone 

I've updated our online doc for Etcher, seemed the best choice for all OS's
http://dietpi.com/phpbb/viewtopic.php?f=8&t=9&p=9#p9

I'll mark this as closed.
