### ISSUE TITLE
Read-only file system on RPi 3 after finishing the first-run configuration

### ISSUE THREAD

**Issue by enolp** [MichaIng/DietPi#981]
I submitted a bug report using dietpi-bugreport, here is the reference code: 4159ed3d-b43c-4d0b-8ef7-6d98f9e533c4-0

I think is not necessary to explain the problem here if I did that bug report, but i forgot to mention in the "Additional notes" section that probably an updated DietPi ISO will solve my issue.

**Comment by Fourdee** [comment]
@enolp 

Thanks 👍 

I'll take a look at your bug report and see whats up.

**Comment by Fourdee** [comment]
@enolp 

> it suddenly shows read-only file system error breaking Dietpi software

It sounds like a kernel remount to RO, to prevent further damage to file-system. 

You said you tried 2 new SD cards. Can you:
- List the brand of SD card
- List the Power Supply used

I'll try to replicate on a fresh install with my RPi 3. 
- 🈯️ Unable to replicate FS recovery/RO on fresh install.

---

FS recovery occurred on your system.
```
[    0.962161] EXT4-fs (mmcblk0p2): INFO: recovery required on readonly filesystem
[    0.965245] EXT4-fs (mmcblk0p2): write access will be enabled during recovery
[    9.480517] EXT4-fs (mmcblk0p2): orphan cleanup on readonly fs
[    9.502045] EXT4-fs (mmcblk0p2): 22 orphan inodes deleted
[    9.505233] EXT4-fs (mmcblk0p2): recovery complete
[   11.023930] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[   13.028272] EXT4-fs (mmcblk0p2): re-mounted. Opts: discard
```

**Comment by enolp** [comment]
My MicroSD cards brands are:

SAMSUNG 16GB EVO MicroSDHC I Class 10
Lexar 16GB 300x MicroSDHC I Class 10

Finally, the power supply I use is a TONTEC T520LE  input:100-240V-50/60Hz 0.5A output: 5V - 2A

That's strange because when Dietpi starts for the first time, it works perfectly fine and all partitions are resized successfully, as well as the creation of the swap file.

**Comment by Fourdee** [comment]
@enolp 
I believe this is hardware related (as for what that is, most likely PSU). Unstable system, causing filesystem errors and hence the read only mode to recover.

To exclude SD card's. Try full formatting the SD card, prior to image write (some users report success with this):
https://github.com/Fourdee/DietPi/issues/769#issuecomment-283030267

Failing that, check voltage of PSU output to ensure 4.9v> during load, or try another PSU.

**Comment by k-plan** [comment]
> SAMSUNG 16GB EVO MicroSDHC I Class 10

In my experience, this cards, the old black one and the new white/orange are very picky.
I don't like to use this any more.

> Failing that, check voltage of PSU output to ensure 4.9v> during load, or try another PSU.

[The Raspberry Pi Foundation say](https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md),  a RPi 3 have to be powered by a +5.1V PSU, that purchasing a 2.5A  output. 
Voltage input on the device with a stable 5.1 V is really important! You can measure it with a multimeter on GPIO pin no. 4 and no. 6.

And voltage drop  on simple micro USB plugs and cable can be a huge problem as well.

**Comment by enolp** [comment]
I have a RPi 2 and the RPi 3, so I compared the power supply which they was using and I noted that my RPi 2 was using the RPi 3 power supply, so I reinstalled again Dietpi but same result when updating.

@Fourdee I use Linux so I cannot use Windows program unless I create a virtual machine. Any alternatives?

**Comment by Fourdee** [comment]
@enolp 

> I use Linux so I cannot use Windows program unless I create a virtual machine. Any alternatives?

You can DD zero's to SD card, same effect. This assumes ```/dev/sda``` is your SD card, **change as needed**. Use ```blkid``` to list drives:
```
dd if=/dev/zero of=/dev/sda
```

**Comment by Fourdee** [comment]
@k-plan 

> In my experience, this cards, the old black one and the new white/orange are very picky.
I don't like to use this any more.

I had similar issues with the EVO (orange) card on RPi. Filesystem corruptions once or twice. Never used it since, back to Sandisk.

**Comment by enolp** [comment]
Well, I ordered an official Raspberry Pi power supply so I hope my problem gets solved. Anyway I'll fill with zeros my Lexar MicroSD because the EVO is in use on the other RPi 2, and update this issue when I have new results.

**Comment by enolp** [comment]
UPDATE:

It seems you were right, I received my official Raspberry Pi power supply and after doing some tests, i can conclude all is working fine.

You can close this issue.

**Comment by Fourdee** [comment]
@enolp 

Great to hear 👍
