### ISSUE TITLE
DietPi-Config | Enable boot Raspberry Pi 3 from a USB mass storage device

### ISSUE THREAD

**Issue by k-plan** [MichaIng/DietPi#983]
_Only for Raspberry Pi 3 !_

Would be nice to bring this feature into `dietpi-config` for easy users experience.

Please make a hint, to be warned that this feature is experimental and does not work with all USB mass storage devices. And it will done at owner's risk!

It's possible read out `vcgencmd otp_dump | grep 17:` and if it is not set ( `17:1020000a` => not enabled USB MSD), user can easy change it to enable , so `dietpi-config` will put `program_usb_boot_mode=1` in `/DietPi/config.txt` only once and force a reboot like you do, when changing the hostname.
After device reboot, please delete `program_usb_boot_mode=1` from `/DietPi/config.txt`.

Info: [BOOTMODES > MSD](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md)

**Comment by Fourdee** [comment]
Notes:
- @k-plan, confirmed this is a one time setting and non-reversible. ```program_usb_boot_mode=0``` has no effect.
- 
![image](https://cloud.githubusercontent.com/assets/7077026/26549104/40ba7926-446f-11e7-8dc0-fdede0787e44.png)

**Comment by Fourdee** [comment]
🈯️ Tested on my last RPi 3 that had no bit set.

Completed.
