### ISSUE TITLE
Kodi is not listed in software

### ISSUE THREAD

**Issue by kGitsov** [MichaIng/DietPi#987]
Hi there,

Installed DietPi recently but I noticed that there is no Kodi included in software, so I run into searching how to include. In DietPi software selection secton is not included, and when I try to install it from terminal it isn't successfully installed and can't run. I run OpeneElec with no problems before DietPi. Is it video driver problem?  What do I have to do?
I'm using Orange Pi PC
DietPi version: 150

Thank you in advance!

**Comment by Fourdee** [comment]
@kGitsov 

GPU features are not currently supported on this image. Ideal for server usage.
https://github.com/Fourdee/DietPi/issues/891

**Comment by kGitsov** [comment]
@Fourdee 

Is it possible to upgrade manually with a certain risk? I'm still testing the enviroment :)

**Comment by Fourdee** [comment]
@kGitsov 

> Is it possible to upgrade manually with a certain risk? I'm still testing the enviroment :)

By all means, but you'll need to compile Mali driver and Kodi. See links in this post for various methods:
https://github.com/Fourdee/DietPi/issues/891#issue-223369049

**Comment by Invictaz** [comment]
@kGitsov Very interested if you can pull this off.

**Comment by Fourdee** [comment]
We only support/offer Kodi for RPi/Odroid devices.
