### ISSUE TITLE
DietPi-Software | jRiver

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#988]
> https://yabb.jriver.com/interact/index.php?topic=95578.0

**Comment by Fourdee** [comment]
```
mediacenter22
Segmentation fault
```

---

```
#Requires ALSA XSERVER GPU=128
#dietpi-software install 5 6
apt-get install -y libx11-6 libuuid1 libidn11 libxcb1 libxau6 libxdmcp6 zlib1g libxext6 libgtk2.0-0 libp11-kit0 libstdc++6 p11-kit libgl1-mesa-glx libcanberra-gtk-module xdg-utils xfonts-75dpi xfonts-100dpi lame vorbis-tools musepack-tools xfonts-unifont

wget -q -O - http://dist.jriver.com/mediacenter@jriver.com.gpg.key | apt-key add -
wget http://dist.jriver.com/latest/mediacenter/mediacenter22native.list -O /etc/apt/sources.list.d/mediacenter22.list
apt-get update
apt-get install -y mediacenter22

cat << _EOF_ >> /DietPi/config.txt
framebuffer_depth=32
framebuffer_ignore_alpha=1
_EOF_
```

**Comment by sfb2** [comment]
works here->https://github.com/Fourdee/DietPi/issues/1005

**Comment by Fourdee** [comment]
@sfb2 

Still fails with seg fault on my RPi 3. Followed same guide as you:
- https://yabb.jriver.com/interact/index.php/topic,106027.0.html?PHPSESSID=tu9nj8hrnf77m3ef9ur3h6do27

And:
- Installed xserver/alsa
- GPU memory 128MB

Which desktop did you have installed? LXDE?

**Comment by sfb2** [comment]
No, XFCE...
"pure" Dietpi..
(try to hold it as pure as possible->only Dietpi-suggested software..)
(no further xserver and/or alsa installs and no framebuffer-corrections, only "apt-get install media...")
but so many thx again !! ;-)

**Comment by Fourdee** [comment]
@sfb2 

> No, XFCE...
"pure" Dietpi..
(try to hold it as pure as possible->only Dietpi-suggested software..)

Fresh installs, same result on RPi 3. I'll try RPi 2, same.

**Comment by sfb2** [comment]
?
absolute fresh install too..v1.51->see attachments..
(only "SMplayer" (and dependencies,clear) is also installed)
(just dietpi-stretch to install; try to install it there too->results here)
(sorry, forgot to mention:"xfce4-goodies" was also installed)
![20170611_200201](https://user-images.githubusercontent.com/28710544/27013227-16949f70-4ee0-11e7-813b-fc9a0099a8e8.jpg)
![20170611_200241](https://user-images.githubusercontent.com/28710544/27013228-16a95988-4ee0-11e7-8fc2-3f615f024de4.jpg)

**Comment by Fourdee** [comment]
@sfb2 

We'll i'am stumped lol

> SMplayer xfce-goodies

I'll try fresh installs again and check these are installed 👍

**Comment by Fourdee** [comment]
Fresh install RPi 3:
- +XFCE ```dietpi-software install 25```
-
```
wget -q -O - http://dist.jriver.com/mediacenter@jriver.com.gpg.key | apt-key add -
wget http://dist.jriver.com/latest/mediacenter/mediacenter22native.list -O /etc/apt/sources.list.d/mediacenter22.list
apt-get update
apt-get install -y mediacenter22

reboot
```
- 🈯️ Works
- 🈯️ Change GPU split from 64MB to 128MB 

Weird.

---

- Also runs under Xinit

--- 

- Online doc: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=7536#p7536

**Comment by Fourdee** [comment]
@sfb2 

Good to go, thanks for your help on this one 👍 

Marking as completed.
