### ISSUE TITLE
DietPi Image | OrangePI Plus 2E

### ISSUE THREAD

**Issue by lubeda** [MichaIng/DietPi#995]
Please Provide a Version for the OrangePI Plus 2E.

**Comment by Fourdee** [comment]
@lubeda 

Unfortunately, I do not have access to this device, at this time. This prevents us creating the image and supporting the device.

@it-praktyk is having a go at creating the image. See below:
https://github.com/Fourdee/DietPi/issues/977#issuecomment-305306245
