### ISSUE TITLE
DietPi-Config | decode_MPG2 decode_WVC1 : Reports disabled with 16MB GPU split

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#996]
> https://github.com/Fourdee/DietPi/issues/885#issuecomment-305776190

**Comment by Fourdee** [comment]
```vcgencmd codec_enabled MPG2``` will report ```disabled```, if GPU memory split is set to 16MB. This is default on DietPi, unless software such as Kodi/Desktop is installed, in which case its automatically increased.

**32MB GPU memory split is minimum for this command to return ```Enabled```.** 
Most likely due to VideoCore not fitting into 16MB, and therefor, not being loaded.

**Comment by Fourdee** [comment]
As DietPi-Software will automatically increase GPU memory splits, dependent on software installed (eg: Kodi = 128MB, desktop = 64MB etc), i'll mark this as a non-dietpi/known issue.

**Comment by Invictaz** [comment]
@Fourdee my MPG2 reports fine but WVC1 does not. What can be the case?
Memory is sufficient
