### ISSUE TITLE
Unable to Install Plex Media Server

### ISSUE THREAD

**Issue by MrHaCkEr** [MichaIng/DietPi#998]
At the moment it's not possible to install Plex from the Interface

![image](https://user-images.githubusercontent.com/1058844/26883360-48853ba2-4b9d-11e7-9797-4cb149618733.png)

**Comment by Fourdee** [comment]
@MrHaCkEr 

Thanks for the report 👍 

We'll update the links.

**Comment by Fourdee** [comment]
@MrHaCkEr 

Fixed for v152. If you want to install Plex now, please update the following script:
```
wget https://github.com/Fourdee/DietPi/raw/testing/dietpi/dietpi-software -O /DietPi/dietpi/dietpi-software
```

Then install Plex with:
```
dietpi-software install 42
```

**Comment by WolfganP** [comment]
I assume that the issues were observed in a VM, right? (due the target being amd64)
I have no issues installing plex on RPi2 via the custom dev2day repository.

**Comment by Fourdee** [comment]
@WolfganP 

> I assume that the issues were observed in a VM, right? (due the target being amd64)

Yep, the VM installer pulls directly from plex.tv download url. All other devices are apt/repo based.
